TRUST: Op_VDF_Face Class Reference
Op_VDF_Face Class Reference
#include <Op_VDF_Face.h>
Public Member Functions
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Detailed Description
Definition at line 31 of file Op_VDF_Face.h.
Member Function Documentation
void Op_VDF_Face::dimensionner (const Zone_VDF & la_zone, const Zone_Cl_VDF & la_zone_cl, Matrice_Morse & la_matrice) const
Definition at line 56 of file Op_VDF_Face.cpp.
References coeff, Objet_U::dimension, Matrice_Morse::dimensionner(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VDF::face_amont_princ(), Zone_VDF::face_bord_amont(), face_bord_amont2(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites(), DoubleVect::line_size(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), and Champ_Inc::valeurs().
{
// Dimensionnement de la matrice qui devra recevoir les coefficients provenant de
// la convection, de la diffusion pour le cas des faces.
// Cette matrice a une structure de matrice morse.
// Nous commencons par calculer les tailles des tableaux tab1 et tab2.
  int ndeb = 0;
  int nfin = la_zone.nb_faces_tot();
  int dimension = Objet_U::dimension;
  const DoubleTab& champ_inconnue = la_zone_cl.equation().inconnue().valeurs();
  const int nb_comp = champ_inconnue.line_size();
  la_matrice.dimensionner(nfin*nb_comp,nfin*nb_comp,0);
  DoubleVect& coeff = la_matrice.get_set_coeff();
  coeff=0;
  IntVect rang_voisin(nfin);
  rang_voisin=1;
  const IntVect& orientation=la_zone.orientation();
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      int ori=orientation(num_face);
      int face1=la_zone.face_amont_princ(num_face,0);
      int face2=la_zone.face_amont_princ(num_face,1);
      int face3=la_zone.face_bord_amont(num_face,(ori+1)%dimension,0);
      int face4=la_zone.face_bord_amont(num_face,(ori+1)%dimension,1);
      if(face1 > -1)
        (rang_voisin(num_face))++;
      if(face2 > -1)
        (rang_voisin(num_face))++;
      if(face3 > -1)
        (rang_voisin(num_face))++;
      if(face4 > -1)
        (rang_voisin(num_face))++;
      if (dimension==3)
        {
          int face5=la_zone.face_bord_amont(num_face,(ori+2)%dimension,0);
          int face6=la_zone.face_bord_amont(num_face,(ori+2)%dimension,1);
          if(face5 > -1)
            (rang_voisin(num_face))++;
          if(face6 > -1)
            (rang_voisin(num_face))++;
        }
    }
// Cerr<<"nbre max de voisin "<<max(rang_voisin)<<" "<<rang_voisin(0)<<finl;
// Cerr<<"nbre max de voisin "<<max(rang_voisin)<<" "<<rang_voisin(0)<<finl;
// on dimensionne tab1 et tab2 au nombre de faces
  IntVect& tab1=la_matrice.get_set_tab1();
  IntVect& tab2=la_matrice.get_set_tab2();
  tab1(0)=1;
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      for (int k=0; k< nb_comp; k++)
        tab1(num_face*nb_comp+1+k)=rang_voisin(num_face)+tab1(num_face*nb_comp+k);
    }
  la_matrice.dimensionner(nfin*nb_comp,tab1(nfin*nb_comp)-1);
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      int ori=orientation(num_face);
      int face1=la_zone.face_amont_princ(num_face,0);
      int face2=la_zone.face_amont_princ(num_face,1);
      int face3=la_zone.face_bord_amont(num_face,(ori+1)%dimension,0);
      int face4=la_zone.face_bord_amont(num_face,(ori+1)%dimension,1);
      int cpt=tab1[num_face]-1;
      tab2[cpt]=num_face+1;
      cpt++;
      if(face1 > -1)
        {
          tab2[cpt]=face1+1;
          cpt++;
        }
      if(face2 > -1)
        {
          tab2[cpt]=face2+1;
          cpt++;
        }
      if(face3 > -1)
        {
          tab2[cpt]=face3+1;
          cpt++;
        }
      if(face4 > -1)
        {
          tab2[cpt]=face4+1;
          cpt++;
        }
      if (dimension==3)
        {
          int face5=la_zone.face_bord_amont(num_face,(ori+2)%dimension,0);
          int face6=la_zone.face_bord_amont(num_face,(ori+2)%dimension,1);
          if(face5 > -1)
            {
              tab2[cpt]=face5+1;
              cpt++;
            }
          if(face6 > -1)
            {
              tab2[cpt]=face6+1;
              cpt++;
            }
        }
    }
// on traite la condition de periodicite
// en effet ce n'est pas sur que les faces de frontiere soient les bonnes
// plus precisement a droite on a la face de gauche et non celle de droite
  const Conds_lim& les_cl = la_zone_cl.les_conditions_limites();
  const IntTab& faces_voisins=la_zone.face_voisins();
  const IntTab& elem_faces=la_zone.elem_faces();
  for (int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb_p = la_front_dis.num_premiere_face();
          int nfaces = la_front_dis.nb_faces();
          int nfin_p=ndeb_p+nfaces;
// fait = 0;
          for (int num_face=ndeb_p; num_face<nfin_p; num_face++)
            {
              int ori=orientation(num_face);
              {
// fait[ind_face_local] = 1;
// fait[la_cl_perio.face_associee(ind_face_local)] = 1;
// int face1=la_zone.face_amont_princ(num_face,0);
// int face2=la_zone.face_amont_princ(num_face,1);
                int face3=la_zone.face_bord_amont(num_face,(ori+1)%dimension,0);
                int face4=la_zone.face_bord_amont(num_face,(ori+1)%dimension,1);
                int face1b=elem_faces(faces_voisins(num_face,1),ori);
                int cpt=tab1[num_face]-1;
                cpt+=3;
                if (face1b!=num_face)
                  {
// on recalcule fac3 fac4
                    int face3n=face_bord_amont2(la_zone,num_face,(ori+1)%dimension,0);
                    int face4n=face_bord_amont2(la_zone,num_face,(ori+1)%dimension,1);
                    if (face3!=-1)
                      {
// int face3n=la_cl_perio.face_associee(face3-ndeb_p)+ndeb_p;
// on remplace face3 pae face3n dans tab2
                        assert(tab2[cpt]==face3+1);
                        tab2[cpt]=face3n+1;
                        cpt++;
                      }
                    if (face4!=-1)
                      {
// int face4n=la_cl_perio.face_associee(face4-ndeb_p)+ndeb_p;
// on remplace face4 pae face4n dans tab2
                        assert(tab2[cpt]==face4+1);
                        tab2[cpt]=face4n+1;
                        cpt++;
                      }
                    if (dimension==3)
                      {
                        int face5=la_zone.face_bord_amont(num_face,(ori+2)%dimension,0);
                        int face6=la_zone.face_bord_amont(num_face,(ori+2)%dimension,1);
                        int face5n=face_bord_amont2(la_zone,num_face,(ori+2)%dimension,0);
                        int face6n=face_bord_amont2(la_zone,num_face,(ori+2)%dimension,1);
                        if (face5!=-1)
{
// int face5n=la_cl_perio.face_associee(face5-ndeb_p)+ndeb_p;
// on remplace face4 pae face4n dans tab2
                            assert(tab2[cpt]==face5+1);
                            tab2[cpt]=face5n+1;
                            cpt++;
                          }
                        if (face6!=-1)
{
// int face6n=la_cl_perio.face_associee(face6-ndeb_p)+ndeb_p;
// on remplace face4 pae face4n dans tab2
                            assert(tab2[cpt]==face6+1);
                            tab2[cpt]=face6n+1;
                            cpt++;
                          }
                      }
                  }
              }
            }
        }
    }
  /*
    coeff=1;
    Cout<<"iciMM"<<finl;
    la_matrice.imprimer_formatte(Cout);
    coeff=0;
    Cerr<<la_zone.xv()<<finl;
  */
}
void Op_VDF_Face::modifier_pour_Cl (const Zone_VDF & la_zone, const Zone_Cl_VDF & la_zone_cl, Matrice_Morse & la_matrice, DoubleTab & secmem) const
Definition at line 265 of file Op_VDF_Face.cpp.
References coeff, MorEqn::equation(), Cond_lim::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites(), DoubleVect::line_size(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), ref_cast, vect_impl::size(), sub_type, Dirichlet_homogene::val_imp(), Dirichlet::val_imp(), Deriv_Cond_lim_base::valeur(), and Champ_Inc::valeurs().
{
// Cerr << " dans modifier_pour_cl " << finl;
  int  face, i, k,nbvois;
// int nfin = la_zone.nb_faces();
  const Conds_lim& les_cl = la_zone_cl.les_conditions_limites();
  IntVect& tab1=la_matrice.get_set_tab1();
  DoubleVect& coeff = la_matrice.get_set_coeff();
  const IntVect& orientation=la_zone.orientation();
  const DoubleTab& champ_inconnue = la_zone_cl.equation().inconnue().valeurs();
  const int nb_comp = champ_inconnue.line_size();
// Prise en compte des conditions de type periodicite
  for (i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      if (sub_type(Dirichlet,la_cl.valeur()))
        {
          const Dirichlet& la_cl_Dirichlet = ref_cast(Dirichlet,la_cl.valeur());
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int numdeb = la_front_dis.num_premiere_face();
          int nfaces = la_front_dis.nb_faces();
          for (face=numdeb; face < (numdeb + nfaces); face++)
            {
              for (int comp=0; comp<nb_comp; comp++)
                {
                  int idiag = tab1[face*nb_comp+comp]-1;
                  coeff[idiag]=1;
// pour les voisins
                  nbvois = tab1[face*nb_comp+1+comp] - tab1[face*nb_comp+comp];
                  for (k=1; k < nbvois; k++)
                    {
                      coeff[idiag+k]=0;
                    }
// pour le second membre
// Correction erreur (10/99):
// WEC : correction numero de face
                  int ori = orientation(face);
                  secmem[face*nb_comp+comp] = la_cl_Dirichlet.val_imp(face-numdeb,ori);
                }
            }
        }
      if (sub_type(Symetrie,la_cl.valeur()))
        {
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int numdeb = la_front_dis.num_premiere_face();
          int nfaces = la_front_dis.nb_faces();
          for (face=numdeb; face < numdeb + nfaces; face++)
            {
              for (int comp=0; comp<nb_comp; comp++)
                {
                  int idiag = tab1[face*nb_comp+comp]-1;
                  coeff[idiag]=1;
// pour les voisins
                  nbvois = tab1[face*nb_comp+1+comp] - tab1[face*nb_comp+comp];
                  for (k=1; k < nbvois; k++)
                    {
                      coeff[idiag+k]=0;
                    }
                  secmem[face*nb_comp+comp] = 0;
                }
            }
        }
      if (sub_type(Dirichlet_homogene,la_cl.valeur()))
        {
          const Dirichlet_homogene& la_cl_Dirichlet_homogene = ref_cast(Dirichlet_homogene,la_cl.valeur());
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int numdeb = la_front_dis.num_premiere_face();
          int nfaces = la_front_dis.nb_faces();
          for (face=numdeb; face < numdeb + nfaces; face++)
            {
              for (int comp=0; comp<nb_comp; comp++)
                {
                  int idiag = tab1[face*nb_comp+comp]-1;
                  coeff[idiag]=1;
// pour les voisins
                  nbvois = tab1[face*nb_comp+1+comp] - tab1[face*nb_comp+comp];
                  for (k=1; k < nbvois; k++)
                    {
                      coeff[idiag+k]=0;
                    }
// pour le second membre
// Correction erreur (10/99) :
// WEC : correction numero de face
                  int ori = orientation(face);
                  secmem[face*nb_comp+comp] = la_cl_Dirichlet_homogene.val_imp(face-numdeb,ori);
                }
            }
        }
    }
}
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_VDF_Face.h
src/VDF/Operateurs/Op_VDF_Face.cpp