TRUST: Extruder_en20 Class Reference
Extruder_en20 Class Reference
Classe Extruder_en20
Cette classe est un interprete qui sert a lire et executer
la directive Extruder_en20:
Extruder_en20 nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
#include <Extruder_en20.h>
Public Member Functions
~Extruder_en20 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Extruder_en20 ()
Entree & interpreter_ (Entree &)
Fonction principale de l'interprete Extruder_en20
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder_en20::extruder(Zone& zone) const
Extruder signifie ici transformer en triangle des
elements geometrique d'une zone.
void setDirection (double lx, double ly, double lz)
void setNbTranches (int n)
void extruder (Domaine &)
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait raffiner que des Rectangles<br>(on les coupe en 4).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Extruder_en20 & self_cast (Objet_U &)
static const Extruder_en20 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
virtual void extruder_dvt (Domaine &, Faces &, int, int)
Protected Attributes
ArrOfDouble direction
int NZ
Private Member Functions
void traiter_faces_dvt (Faces &, Faces &, int, int, int)
Detailed Description
Classe Extruder_en20
Cette classe est un interprete qui sert a lire et executer
la directive Extruder_en20:
Extruder_en20 nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
Definition at line 43 of file Extruder_en20.h.
Constructor & Destructor Documentation
Extruder_en20::~Extruder_en20 ()
Definition at line 31 of file Extruder_en20.cpp.
Extruder_en20::Extruder_en20 ()
Definition at line 33 of file Extruder_en20.cpp.
References direction, Array_base::NOCOPY_NOINIT, and ArrOfDouble::resize().
{
  direction.resize(3,Array_base::NOCOPY_NOINIT);
}
Member Function Documentation
Objet_U * Extruder_en20::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 31 of file Extruder_en20.cpp.
int Extruder_en20::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 31 of file Extruder_en20.cpp.
void Extruder_en20::extruder (Domaine & dom)
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait raffiner que des Rectangles<br>(on les coupe en 4).
< Tableau dont on aura pas besoin
< les nouveaux elements
Definition at line 130 of file Extruder_en20.cpp.
References Domaine::ajouter(), Faces::associer_zone(), Cerr, construire_connectivite_som_elem(), Faces_builder::creer_faces_reeles(), DoubleTab::dimension(), Objet_U::dimension, IntTab::dimension(), direction, Zone::domaine(), Process::exit(), extruder_dvt(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Faces::nb_faces(), Zone::nb_som(), Domaine::nb_som_tot(), NZ, Objet_U::que_suis_je(), IntTab::ref(), DoubleTab::reset(), Faces::sommet(), Zone::type_elem(), Elem_geom::type_face(), Zone::typer(), Faces::typer(), Faces::voisin(), and Domaine::zone().
Referenced by ExtrudeBord::extruder_bord(), and interpreter_().
{
  Zone& zone = dom.zone(0);
  if (zone.type_elem()->que_suis_je() == "Rectangle" || zone.type_elem()->que_suis_je() ==  "Quadrangle" )
    {
      Cerr << " The extrusion of quadrangle is made by Extruder and not by Extruder_en20 " << finl;
      exit();
    }
  else if( zone.type_elem()->que_suis_je() == "Triangle")
    {
      int oldnbsom = zone.nb_som();
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      double dx = direction(0)/NZ;
      double dy = direction(1)/NZ;
      double dz = direction(2)/NZ;
      Faces les_faces;
// zone.creer_faces(les_faces);
      {
// bloc a factoriser avec Zone_VF.cpp :
        Type_Face type_face = zone.type_elem().type_face(0);
        les_faces.typer(type_face);
        les_faces.associer_zone(zone);
        Static_Int_Lists connectivite_som_elem;
        const int     nb_sommets_tot = zone.domaine().nb_som_tot();
        const IntTab&    elements       = zone.les_elems();
        construire_connectivite_som_elem(nb_sommets_tot,
                                         elements,
                                         connectivite_som_elem,
                                         1 /* include virtual elements */);
        Faces_builder faces_builder;
        IntTab elem_faces; //!< Tableau dont on aura pas besoin
        faces_builder.creer_faces_reeles(zone,
                                         connectivite_som_elem,
                                         les_faces,
                                         elem_faces);
      }
      const int nbfaces2D = les_faces.nb_faces();
      int newnbsom = oldnbsom*(NZ+1)+NZ*oldsz+nbfaces2D*NZ+oldnbsom*NZ;
      DoubleTab new_soms(newnbsom, 3);
      DoubleTab& coord_sommets=dom.les_sommets();
      Objet_U::dimension=3;
// les sommets du maillage 2D sont translates en premier
      for (int i=0; i<oldnbsom; i++)
        {
          double x = coord_sommets(i,0);
          double y = coord_sommets(i,1);
          double z=0;
          if (coord_sommets.dimension(1)>2)
            z=coord_sommets(i,2);
          for (int k=0; k<=NZ; k++)
            {
              new_soms(k*oldnbsom+i,0)=x;
              new_soms(k*oldnbsom+i,1)=y;
              new_soms(k*oldnbsom+i,2)=z;
              x += dx;
              y += dy;
              z += dz;
            }
        }
// creation des centres de gravite des elements 2D puis translation de ces points
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          double xg = 1./3.*(coord_sommets(i0,0)+coord_sommets(i1,0)+coord_sommets(i2,0))+0.5*dx;
          double yg = 1./3.*(coord_sommets(i0,1)+coord_sommets(i1,1)+coord_sommets(i2,1))+0.5*dy;
          double z = 0.5*dz;
          if (coord_sommets.dimension(1)>2)
            z = 1./3.*(coord_sommets(i0,2)+coord_sommets(i1,2)+coord_sommets(i2,2))+0.5*dz;
          for (int k=0; k<NZ; k++)
            {
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,0)=xg;
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,1)=yg;
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,2)=z;
              xg += dx;
              yg += dy;
              z  += dz;
            }
        }
// creation des centres des faces du maillage 2D puis translation de ces points
      for (int i=0; i<nbfaces2D; i++)
        {
          int i0=les_faces.sommet(i,0);
          int i1=les_faces.sommet(i,1);
          double x01 = 0.5*(coord_sommets(i0,0)+coord_sommets(i1,0))+0.5*dx;
          double y01 = 0.5*(coord_sommets(i0,1)+coord_sommets(i1,1))+0.5*dy;
          double z = 0.5*dz;
          if (coord_sommets.dimension(1)>2)
            z = 0.5*(coord_sommets(i0,2)+coord_sommets(i1,2))+0.5*dz;
          for (int k=0; k<NZ; k++)
            {
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,0)=x01;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,1)=y01;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,2)=z;
              x01 += dx;
              y01 += dy;
              z   += dz;
            }
        }
// creation des centres des aretes du maillage 2D puis translation de ces points
      for (int i=0; i<oldnbsom; i++)
        {
          double x = coord_sommets(i,0)+0.5*dx;
          double y = coord_sommets(i,1)+ 0.5*dy;
          double z = 0.5*dz;
          if (coord_sommets.dimension(1)>2)
            z=coord_sommets(i,2)+0.5*dz;
          for (int k=0; k<NZ; k++)
            {
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i,0)=x;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i,1)=y;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i,2)=z;
              x += dx;
              y += dy;
              z += dz;
            }
        }
      coord_sommets.reset();
      dom.ajouter(new_soms);
      int newnbelem = 20*NZ*oldsz;
      IntTab new_elems(newnbelem, 4); //!< les nouveaux elements
      int cpt=0;
// en premier, on stocke les tetra du haut et du bas : NZ*nb_triangle*2 tetra
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int ig=oldnbsom*(NZ+1)+i;
          for (int k=0; k<NZ; k++)
            {
              new_elems(2*k*oldsz+2*i,0) = i0;
              new_elems(2*k*oldsz+2*i,1) = i1;
              new_elems(2*k*oldsz+2*i,2) = i2;
              new_elems(2*k*oldsz+2*i,3) = ig;
              cpt++;
              new_elems(2*k*oldsz+2*i+1,0) = i0+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,1) = i1+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,2) = i2+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,3) = ig;
              cpt++;
              mettre_a_jour_sous_zone(zone,i,2*k*oldsz+2*i,2);
              i0+=oldnbsom;
              i1+=oldnbsom;
              i2+=oldnbsom;
              ig+=oldsz;
            }
        }
// puis les autres tetras
      for (int i=0; i<nbfaces2D; i++)
        {
          for (int ivois=0; ivois<2; ivois++)
            {
              int elem = les_faces.voisin(i,ivois);
              if (elem>=0)
                {
                  int i0=les_faces.sommet(i,0);
                  int i1=les_faces.sommet(i,1);
                  int i01=oldnbsom*(NZ+1)+NZ*oldsz+i;
                  for (int k=0; k<NZ; k++)
                    {
                      int ig=oldnbsom*(NZ+1)+k*oldsz+elem;
                      int i00=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+i0;
                      int i11=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+i1;
// int i00=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i0;
// int i11=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i1;
                      new_elems(cpt,0) = i0;
                      new_elems(cpt,1) = i1;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i0+oldnbsom;
                      new_elems(cpt,1) = i1+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i1;
                      new_elems(cpt,1) = i11;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i11;
                      new_elems(cpt,1) = i1+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i0;
                      new_elems(cpt,1) = i00;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i00;
                      new_elems(cpt,1) = i0+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      i0+=oldnbsom;
                      i1+=oldnbsom;
                      i01+=nbfaces2D;
                      ig+=oldsz;
                    }
                }
            }
        }
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      zone.invalide_octree();
      zone.typer("Tetraedre");
      extruder_dvt(dom, les_faces,oldnbsom, oldsz);
    }
  else
    {
      Cerr << "It is not known yet how to extrude "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
}
void Extruder_en20::extruder_dvt (Domaine & dom, Faces & les_faces, int oldnbsom, int oldsz) [protected, virtual]
Definition at line 470 of file Extruder_en20.cpp.
References List_Bord::add(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), Zone::les_elems(), Faces::les_sommets(), LIST_CURSEUR, Faces::nb_faces(), Frontiere::nommer(), NZ, IntTab::ref(), IntTab::resize(), traiter_faces_dvt(), Faces::triangle_3D, Faces::typer(), Faces::voisins(), and Domaine::zone().
Referenced by extruder().
{
  Zone& zone = dom.zone(0);
  const int nbfaces2D = les_faces.nb_faces();
  IntTab& les_elems=zone.les_elems();
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());
    while(curseur)
      {
        Faces& les_faces_bord=curseur->faces();
        traiter_faces_dvt(les_faces_bord, les_faces, oldnbsom, oldsz, nbfaces2D );
        ++curseur;
      }
  }
  {
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
    while(curseur)
      {
        Faces& les_faces_bord=curseur.valeur()->faces();
        traiter_faces_dvt(les_faces_bord, les_faces, oldnbsom, oldsz, nbfaces2D );
        ++curseur;
      }
  }
  Bord& devant = zone.faces_bord().add(Bord());
  devant.nommer("devant");
  Faces& les_faces_dvt=devant.faces();
  les_faces_dvt.typer(Faces::triangle_3D);
  IntTab som_dvt(oldsz, 3);
  les_faces_dvt.voisins().resize(oldsz, 2);
  les_faces_dvt.voisins()=-1;
  Bord& derriere = zone.faces_bord().add(Bord());
  derriere.nommer("derriere");
  Faces& les_faces_der=derriere.faces();
  les_faces_der.typer(Faces::triangle_3D);
  IntTab som_der(oldsz, 3);
  les_faces_der.voisins().resize(oldsz, 2);
  les_faces_der.voisins()=-1;
  for (int i=0; i<oldsz; i++)
    {
      int i0=les_elems(2*i,0);
      int i1=les_elems(2*i,1);
      int i2=les_elems(2*i,2);
      som_dvt(i,0) = i0;
      som_dvt(i,1) = i1;
      som_dvt(i,2) = i2;
      som_der(i,0) = i0+oldnbsom*NZ;
      som_der(i,1) = i1+oldnbsom*NZ;
      som_der(i,2) = i2+oldnbsom*NZ;
    }
  les_faces_dvt.les_sommets().ref(som_dvt);
  les_faces_der.les_sommets().ref(som_der);
}
const Type_info * Extruder_en20::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Extruder_en20.cpp.
const Type_info * Extruder_en20::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Extruder_en20.cpp.
Entree & Extruder_en20::interpreter_ (Entree & is) [virtual]
Fonction principale de l'interprete Extruder_en20
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder_en20::extruder(Zone& zone) const
Extruder signifie ici transformer en triangle des
elements geometrique d'une zone.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 98 of file Extruder_en20.cpp.
References Param::ajouter(), Param::ajouter_arr_size_predefinie(), Interprete_geometrique_base::associer_domaine(), direction, Interprete_geometrique_base::domaine(), extruder(), Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), NZ, Objet_U::que_suis_je(), Param::REQUIRED, and Scatter::uninit_sequential_domain().
{
  Nom nom_dom;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("nb_tranches",&NZ,Param::REQUIRED);
  param.ajouter_arr_size_predefinie("direction",&direction,Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_dom);
  Scatter::uninit_sequential_domain(domaine());
  extruder(domaine());
  Scatter::init_sequential_domain(domaine());
  return is;
}
Sortie & Extruder_en20::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 52 of file Extruder_en20.cpp.
{
  return Interprete::printOn(os);
}
Entree & Extruder_en20::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 72 of file Extruder_en20.cpp.
{
  return Interprete::readOn(is);
}
const Extruder_en20 & Extruder_en20::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Extruder_en20.cpp.
Extruder_en20 & Extruder_en20::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Extruder_en20.cpp.
void Extruder_en20::setDirection (double lx, double ly, double lz) [inline]
Definition at line 51 of file Extruder_en20.h.
References direction.
Referenced by ExtrudeBord::extruder_bord().
  {
    direction(0)=lx;
    direction(1)=ly;
    direction(2)=lz;
  };
void Extruder_en20::setNbTranches (int n) [inline]
Definition at line 57 of file Extruder_en20.h.
References NZ.
Referenced by ExtrudeBord::extruder_bord().
  {
    NZ = n;
  };
unsigned Extruder_en20::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 31 of file Extruder_en20.cpp.
void Extruder_en20::traiter_faces_dvt (Faces & les_faces_bord, Faces & les_faces, int oldnbsom, int oldsz, int nbfaces2D) [private]
Definition at line 393 of file Extruder_en20.cpp.
References Faces::les_sommets(), Faces::nb_faces(), NZ, IntTab::ref(), IntTab::resize(), Faces::sommet(), Faces::triangle_3D, Faces::typer(), and Faces::voisins().
Referenced by extruder_dvt().
{
  int size_2D = les_faces_bord.nb_faces();
  IntTab les_sommets(6*size_2D*NZ, 3);
  for (int i=0; i<size_2D; i++)
    {
      int i0=les_faces_bord.sommet(i,0);
      int i1=les_faces_bord.sommet(i,1);
// double x01 = 0.5*(coord_sommets(i0,0)+coord_sommets(i1,0));
// double y01 = 0.5*(coord_sommets(i0,1)+coord_sommets(i1,1));
// on recherche le numero de cette face de bord: pas top!
      int jface=-1;
      for (int iface=0; iface<nbfaces2D; iface++)
        {
          int j0=les_faces.sommet(iface,0);
          int j1=les_faces.sommet(iface,1);
          if (((i0==j0) &&(i1==j1)) || ((i0==j1) &&(i1==j0)))
            {
              jface=iface;
              break;
            }
        }
      assert(jface>=0);
      for (int k=0; k<NZ; k++)
        {
// double z = (k+0.5)*dz;
// int i01 = zone.chercher_sommets(x01, y01, z);
          int j01 = oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+jface;
          int i00=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+i0;
          int i11=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+i1;
// int i00=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i0;
// int i11=oldnbsom*(NZ+1)+NZ*oldsz+NZ*nbfaces2D+k*oldnbsom+i1;
          les_sommets(k*6*size_2D+6*i,0) = i0;
          les_sommets(k*6*size_2D+6*i,1) = i1;
          les_sommets(k*6*size_2D+6*i,2) = j01;
          les_sommets(k*6*size_2D+6*i+1,0) = j01;
          les_sommets(k*6*size_2D+6*i+1,1) = i1;
          les_sommets(k*6*size_2D+6*i+1,2) = i11;
          les_sommets(k*6*size_2D+6*i+2,0) = j01;
          les_sommets(k*6*size_2D+6*i+2,1) = i11;
          les_sommets(k*6*size_2D+6*i+2,2) = i1+oldnbsom;
          les_sommets(k*6*size_2D+6*i+3,0) = j01;
          les_sommets(k*6*size_2D+6*i+3,1) = i0+oldnbsom;
          les_sommets(k*6*size_2D+6*i+3,2) = i1+oldnbsom;
          les_sommets(k*6*size_2D+6*i+4,0) = j01;
          les_sommets(k*6*size_2D+6*i+4,1) = i0+oldnbsom;
          les_sommets(k*6*size_2D+6*i+4,2) = i00;
          les_sommets(k*6*size_2D+6*i+5,0) = j01;
          les_sommets(k*6*size_2D+6*i+5,1) = i00;
          les_sommets(k*6*size_2D+6*i+5,2) = i0;
          i0+=oldnbsom;
          i1+=oldnbsom;
        }
    }
  les_faces_bord.typer(Faces::triangle_3D);
  les_faces_bord.les_sommets().ref(les_sommets);
  les_faces_bord.voisins().resize(6*size_2D*NZ, 2);
  les_faces_bord.voisins()=-1;
}
Member Data Documentation
ArrOfDouble Extruder_en20::direction [protected]
Definition at line 68 of file Extruder_en20.h.
Referenced by extruder(), Extruder_en20(), interpreter_(), and setDirection().
const Type_info Extruder_en20::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 45 of file Extruder_en20.h.
int Extruder_en20::NZ [protected]
Definition at line 69 of file Extruder_en20.h.
Referenced by extruder(), extruder_dvt(), interpreter_(), setNbTranches(), and traiter_faces_dvt().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extruder_en20.h
src/Kernel/Geometrie/Extruder_en20.cpp