TRUST: Probleme_U Class Reference
Probleme_U Class Reference
classe Probleme_U
Cette classe ajoute des specificites TRUST a l'interface
generale definie dans la classe Problem.
De Probleme_U derivent :
* Probleme_base pour tous les problemes individuels
* Couplage_U pour les couplages de plusieurs Probleme_U
Toutes ces classes doivent satisfaire l'API de Problem
completee par celle de Probleme_U.
#include <Probleme_U.h>
Public Member Functions
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom
ScalarRegister reg
Detailed Description
classe Probleme_U
Cette classe ajoute des specificites TRUST a l'interface
generale definie dans la classe Problem.
De Probleme_U derivent :
* Probleme_base pour tous les problemes individuels
* Couplage_U pour les couplages de plusieurs Probleme_U
Toutes ces classes doivent satisfaire l'API de Problem
completee par celle de Probleme_U.
Definition at line 46 of file Probleme_U.h.
Constructor & Destructor Documentation
Probleme_U()
Probleme_U::Probleme_U ()
Definition at line 32 of file Probleme_U.cpp.
~Probleme_U()
Probleme_U::~Probleme_U () override
Definition at line 32 of file Probleme_U.cpp.
Member Function Documentation
abortTimeStep()
void Probleme_U::abortTimeStep () virtual
Aborts the resolution of the current time step.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 224 of file Probleme_U.cpp.
{
}
Referenced by Couplage_U::abortTimeStep(), ICoCo::ProblemTrio::abortTimeStep(), run(), and runUntil().
computeTimeStep()
double Probleme_U::computeTimeStep (bool & stop) const virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
Returns
double
Signification: The desired time step
Contraintes:
Reimplemented in Probleme_base, and Probleme_Couple.
Definition at line 132 of file Probleme_U.cpp.
{
  stop=true;
  return 0;
}
Referenced by Probleme_Couple::computeTimeStep(), ICoCo::ProblemTrio::computeTimeStep(), run(), and runUntil().
findInputField()
Ref_Field_base Probleme_U::findInputField (const Nom & name) const virtual
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Returns
REF(Field_base)
Signification: found <=> non_nul(), then points to a Champ_Input_Proto of that name.
Contraintes:
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 642 of file Probleme_U.cpp.
{
  REF(Field_base) ch;
  return ch;
}
References REF.
Referenced by Couplage_U::findInputField(), getInputFieldTemplate(), setInputDoubleValue(), setInputField(), and ICoCo::ProblemTrio::setInputMEDDoubleField().
findOutputField()
Ref_Champ_Generique_base Probleme_U::findOutputField (const Nom & name) const virtual
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 670 of file Probleme_U.cpp.
{
  REF(Champ_Generique_base) ch;
  return ch;
}
References REF.
Referenced by Couplage_U::findOutputField(), and getOutputField().
futureTime()
double Probleme_U::futureTime () const virtual
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Returns
double
Signification: future time
Contraintes:
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 599 of file Probleme_U.cpp.
{
  return 0;
}
Referenced by Couplage_U::futureTime(), and setInputField().
get_info()
const Type_info * Probleme_U::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 32 of file Probleme_U.cpp.
getInputFieldsNames()
void Probleme_U::getInputFieldsNames (Noms & noms) const virtual
This method is used to find the names of input fields understood by the Problem.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 619 of file Probleme_U.cpp.
{
}
Referenced by ICoCo::ProblemTrio::getInputFieldsNames(), and Couplage_U::getInputFieldsNames().
getInputFieldTemplate()
void Probleme_U::getInputFieldTemplate (const Nom & name, ICoCo::TrioField & afield) const virtual
This method is used to get a template of a field expected for the given name.
Definition at line 695 of file Probleme_U.cpp.
{
  REF(Field_base) ch=findInputField(name);
  if (!ch.non_nul())
    throw WrongArgument(le_nom().getChar(),"getInputFieldTemplate",name.getString(),"no input field of that name");
// Du au fait qu'on ne peut pas faire une ref sur Champ_Input_Proto qui n'est pas un Objet_U...
  Champ_Input_Proto * chip = dynamic_cast<Champ_Input_Proto *>(ch.operator->());
  if (!chip)
    throw WrongArgument(le_nom().getChar(),"getInputFieldTemplate",name.getString(),"field of this name is not an input field");
  chip->getTemplate(afield);
}
References findInputField(), Nom::getString(), Champ_Input_Proto::getTemplate(), le_nom(), and REF.
Referenced by ICoCo::ProblemTrio::getInputFieldTemplate().
getOutputField()
void Probleme_U::getOutputField (const Nom & nameField, ICoCo::TrioField & afield) const virtual
Definition at line 744 of file Probleme_U.cpp.
{
  REF(Champ_Generique_base) ref_ch=findOutputField(name);
  if (!ref_ch.non_nul())
    throw WrongArgument(le_nom().getChar(),"getOutputField",name.getString(),"no output field of that name");
  const Champ_Generique_base& ch = ref_ch.valeur();
  build_triofield(ch, afield);
  afield.setName(name.getString());
}
References build_triofield(), findOutputField(), Nom::getString(), le_nom(), and REF.
Referenced by ICoCo::ProblemTrio::getOutputField().
getOutputFieldsNames()
void Probleme_U::getOutputFieldsNames (Noms & noms) const virtual
This method is used to find the names of output fields understood by the Problem.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 666 of file Probleme_U.cpp.
{
}
Referenced by ICoCo::ProblemTrio::getOutputFieldsNames(), and Couplage_U::getOutputFieldsNames().
getOutputIntValue()
int Probleme_U::getOutputIntValue (const Nom & name) const virtual
Definition at line 778 of file Probleme_U.cpp.
{
  return reg.getOutputIntValue(name);
}
References ScalarRegister::getOutputIntValue(), and reg.
Referenced by Equation_base::equation_non_resolue(), and ICoCo::ProblemTrio::getOutputIntValue().
info()
const Type_info * Probleme_U::info () static
Definition at line 32 of file Probleme_U.cpp.
initialize()
void Probleme_U::initialize () virtual
This method is called once at the beginning, before any other one of
the interface Problem.
Reimplemented in Couplage_U, Probleme_base, and Probleme_Couple.
Definition at line 68 of file Probleme_U.cpp.
{
}
Referenced by Couplage_U::initialize(), ICoCo::ProblemTrio::initialize_pb(), and Resoudre::interpreter().
initTimeStep()
bool Probleme_U::initTimeStep (double dt) virtual
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Reimplemented in Couplage_U, Probleme_base, Probleme_Couple, and Pb_Dilatable_base.
Definition at line 156 of file Probleme_U.cpp.
{
  return false;
}
Referenced by Couplage_U::initTimeStep(), ICoCo::ProblemTrio::initTimeStep(), run(), and runUntil().
isStationary()
bool Probleme_U::isStationary () const virtual
Tells if the Problem unknowns have changed during the last time step.
Returns
bool
Signification: true=stationary, false=not stationary
Contraintes:
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 198 of file Probleme_U.cpp.
{
  return false;
}
Referenced by Couplage_U::isStationary(), ICoCo::ProblemTrio::isStationary(), and run().
iterateTimeStep()
bool Probleme_U::iterateTimeStep (bool & converged) virtual
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
Returns
bool
Signification: true=OK, false=unable to converge
Contraintes:
Reimplemented in Couplage_U, Probleme_base, Probleme_Couple, and Pb_Dilatable_base.
Definition at line 251 of file Probleme_U.cpp.
{
  return false;
}
Referenced by Couplage_U::iterateTimeStep(), Probleme_Couple::iterateTimeStep(), ICoCo::ProblemTrio::iterateTimeStep(), and solveTimeStep().
le_nom()
const Nom & Probleme_U::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 107 of file Probleme_U.h.
{
  return nom;
}
References nom.
Referenced by Probleme_Couple::ajouter(), Probleme_Couple::discretiser(), getInputFieldTemplate(), getOutputField(), Couplage_U::indice_probleme(), Discretiser::interpreter(), Resoudre::interpreter(), main_pilote_icoco_1(), main_pilote_icoco_2(), Probleme_Couple::readOn(), Probleme_Couple::schema_temps(), setInputDoubleValue(), and setInputField().
limpr()
int Probleme_U::limpr () const virtual
Doit-on imprimer les statistiques d'execution maintenant ?
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 281 of file Probleme_U.cpp.
{
  return 0;
}
Referenced by Couplage_U::limpr(), run(), and runUntil().
lsauv()
int Probleme_U::lsauv () const virtual
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 288 of file Probleme_U.cpp.
{
  return 0;
}
Referenced by Couplage_U::lsauv(), run(), and ICoCo::ProblemTrio::solveTimeStep().
nommer()
void Probleme_U::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 102 of file Probleme_U.h.
{
  nom=name;
}
References nom.
postraiter()
int Probleme_U::postraiter (int force = 1) virtual
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 274 of file Probleme_U.cpp.
{
  return 0;
}
Referenced by ICoCo::ProblemTrio::initialize_pb(), Couplage_U::postraiter(), run(), runUntil(), ICoCo::ProblemTrio::terminate(), and ICoCo::ProblemTrio::validateTimeStep().
presentTime()
double Probleme_U::presentTime () const virtual
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
Returns
double
Signification: present time
Contraintes:
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 109 of file Probleme_U.cpp.
{
  return 0;
}
Referenced by Couplage_U::presentTime(), ICoCo::ProblemTrio::presentTime(), runUntil(), and setInputField().
printOn()
Sortie & Probleme_U::printOn (Sortie & x) const override protected virtual
A surcharger...
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 39 of file Probleme_U.cpp.
{
  return os;
}
readOn()
Entree & Probleme_U::readOn (Entree & is) override protected virtual
A surcharger...
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 46 of file Probleme_U.cpp.
{
  return is ;
}
run()
bool Probleme_U::run () virtual
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
Returns
bool
Signification: true=OK, false=error
Contraintes:
< Does the Problem want to stop ?
< Is the time interval successfully solved ?
< Into _comm.TU file
< Is the time interval successfully solved ?
< The resolution failed, try with a new time interval.
< The resolution was successful, validate and go to the next time step.
< Impossible to solve the next time step, the Problem has given up
< Into _comm.TU file
< Into _detail.TU file
< Into .TU file
Definition at line 352 of file Probleme_U.cpp.
{
// Force the post process task at the beginning of the run
  Cerr<<"First postprocessing, this can take some minutes"<<finl;
  postraiter(1);
  Cerr<<"First postprocessing OK"<<finl;
  bool stop=false; //!< Does the Problem want to stop ?
  bool ok=true; //!< Is the time interval successfully solved ?
// Compute the first time step
  double dt=computeTimeStep(stop);
  statistiques().end_count(initialisation_calcul_counter_);
// Print the initialization CPU statistics
  if (!disable_TU)
    {
      if(GET_COMM_DETAILS)
        statistiques().print_communciation_tracking_details("Statistiques d'initialisation du calcul", 0);               //!< Into _comm.TU file
      statistiques().dump("Statistiques d'initialisation du calcul", 0);
      print_statistics_analyse("Statistiques d'initialisation du calcul", 0);
    }
  statistiques().reset_counters();
  statistiques().begin_count(temps_total_execution_counter_);
#ifdef VTRACE
// VT_USER_END("Initialization");
  VT_BUFFER_FLUSH();
  VT_ON();
  VT_USER_START("Resolution");
#endif
// Time step loop
  int tstep = 0;
  while(!stop)
    {
// Begin the CPU measure of the time step
      statistiques().begin_count(timestep_counter_);
      ok=false; //!< Is the time interval successfully solved ?
// Loop on the time interval tries
      while (!ok && !stop)
        {
// Prepare the next time step
          if (!initTimeStep(dt))
            return false;
// Backup unknown fields if necessary
          if (lsauv())
            sauver();
// Solve the next time step
          ok=solveTimeStep();
          if (!ok)   //!< The resolution failed, try with a new time interval.
            {
              abortTimeStep();
              dt=computeTimeStep(stop);
            }
          else //!< The resolution was successful, validate and go to the next time step.
            validateTimeStep();
        }
      if (!ok) //!< Impossible to solve the next time step, the Problem has given up
        break;
// Compute the next time step length
      dt=computeTimeStep(stop);
// Stop the resolution if the Problem is stationnary
      if (isStationary())
        {
          stop=true;
          setStationary(stop);
        }
// Post process task (Force the post processing/prints at the end of the run (stop=1))
      postraiter(stop);
// Stop the CPU measure of the time step and print:
      statistiques().end_count(timestep_counter_);
      if (limpr())
        {
          double temps = statistiques().last_time(timestep_counter_);
          Cout << finl << "clock: Total time step: " << temps << " s" << finl << finl;
        }
      if(JUMP_3_FIRST_STEPS && tstep < 3)
        {
// demarrage des compteurs CPU
          if(tstep == 2)
            {
              statistiques().set_three_first_steps_elapsed(true);
            }
        }
      else
        {
          statistiques().compute_avg_min_max_var_per_step(tstep);
        }
      tstep++;
#ifdef VTRACE
// Flush the buffer regulary to avoid setting VT_MAX_FLUSHES=0 variable...
      VT_BUFFER_FLUSH();
#endif
    }
#ifdef VTRACE
  VT_USER_END("Resolution");
  VT_OFF();
#endif
// Print the resolution CPU statistics
  if (!disable_TU)
    {
      if(GET_COMM_DETAILS)
        statistiques().print_communciation_tracking_details("Statistiques de resolution du probleme", 1);               //!< Into _comm.TU file
      statistiques().dump("Statistiques de resolution du probleme", 1);      //!< Into _detail.TU file
      print_statistics_analyse("Statistiques de resolution du probleme", 1); //!< Into        .TU file
    }
// Reset the CPU counters
  statistiques().reset_counters();
  statistiques().begin_count(temps_total_execution_counter_);
  return ok;
}
References abortTimeStep(), Statistiques::begin_count(), Cerr, Statistiques::compute_avg_min_max_var_per_step(), computeTimeStep(), Cout, Objet_U::disable_TU, Statistiques::dump(), Statistiques::end_count(), finl, GET_COMM_DETAILS, initialisation_calcul_counter_, initTimeStep(), isStationary(), JUMP_3_FIRST_STEPS, Statistiques::last_time(), limpr(), lsauv(), postraiter(), Statistiques::print_communciation_tracking_details(), print_statistics_analyse(), Statistiques::reset_counters(), sauver(), Statistiques::set_three_first_steps_elapsed(), setStationary(), solveTimeStep(), statistiques(), temps_total_execution_counter_, timestep_counter_, and validateTimeStep().
Referenced by Resoudre::interpreter().
runUntil()
bool Probleme_U::runUntil (double time) virtual
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
Returns
true=OK, false=error
Signification:
Contraintes:
< Does the Problem want to stop ?
< Is the time interval successfully solved ?
< The resolution failed, try with a new time interval.
< The resolution was successful, validate and go to the next time step.
< Impossible to solve the next time step, the Problem has given up
Definition at line 497 of file Probleme_U.cpp.
{
// Error if time is already past
  if (time<presentTime())
    return false;
  bool stop=false; //!< Does the Problem want to stop ?
  bool ok=true; //!< Is the time interval successfully solved ?
// Compute the first time step length
  double dt=computeTimeStep(stop);
// Boucle sur les pas de temps
  while(!stop)
    {
      statistiques().begin_count(timestep_counter_);
      ok=false;
// Loop on the time interval tries
      while (!ok && !stop)
        {
// Do not go past time
          if (presentTime()+dt>time)
            dt=time-presentTime();
// Prepare the next time step
          if (!initTimeStep(dt))
            return false;
// Solve the next time step
          ok=solveTimeStep();
          if (!ok)   //!< The resolution failed, try with a new time interval.
            {
              abortTimeStep();
              dt=computeTimeStep(stop);
            }
          else //!< The resolution was successful, validate and go to the next time step.
//
            validateTimeStep();
        }
      if (!ok) //!< Impossible to solve the next time step, the Problem has given up
        break;
// time was reached
      if (presentTime()==time)
        return true;
// Compute the next time step length
      dt=computeTimeStep(stop);
      statistiques().end_count(timestep_counter_);
      if (je_suis_maitre() && limpr())
        {
          double temps = statistiques().last_time(timestep_counter_);
          Cout << "clock: Total time step: " << temps << " s" << finl;
        }
      postraiter(0);
    }
  return ok;
}
References abortTimeStep(), Statistiques::begin_count(), computeTimeStep(), Cout, Statistiques::end_count(), finl, initTimeStep(), Process::je_suis_maitre(), Statistiques::last_time(), limpr(), postraiter(), presentTime(), solveTimeStep(), statistiques(), timestep_counter_, and validateTimeStep().
sauver()
void Probleme_U::sauver () const virtual
Sauvegarder l'etat du probleme sur disque.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 295 of file Probleme_U.cpp.
{
  return ;
}
Referenced by run(), Couplage_U::sauver(), and ICoCo::ProblemTrio::solveTimeStep().
self_cast() [1/2]
const Probleme_U & Probleme_U::self_cast (const Objet_U & r) static
Definition at line 32 of file Probleme_U.cpp.
self_cast() [2/2]
Probleme_U & Probleme_U::self_cast (Objet_U & r) static
Definition at line 32 of file Probleme_U.cpp.
setInputDoubleValue()
void Probleme_U::setInputDoubleValue (const Nom & name, const double val) virtual
Definition at line 757 of file Probleme_U.cpp.
{
  REF(Field_base) ch = findInputField(name);
  if (!ch.non_nul())
    throw WrongArgument(le_nom().getChar(),"setInputDoubleValue",name.getString(),"no input field of that name");
  if (ch->nb_comp() != 1)
    throw WrongArgument(le_nom().getChar(),"getOutputDoubleValue",name.getString(),"invalid field size!!");
// Wa can not do a REF on Champ_Input_Proto which is not an Objet_U...
  Champ_Input_Proto * chip = dynamic_cast<Champ_Input_Proto *>(ch.operator ->());
  if (!chip)
    throw WrongArgument(le_nom().getChar(),"setInputField",name.getString(),"field of this name is not an input field");
  chip->setDoubleValue(val);
}
References findInputField(), Nom::getString(), le_nom(), REF, and Champ_Input_Proto::setDoubleValue().
Referenced by ICoCo::ProblemTrio::setInputDoubleValue().
setInputField()
void Probleme_U::setInputField (const Nom & name, const ICoCo::TrioField & afield) virtual
This method is used to provide the Problem with an input field.
Definition at line 724 of file Probleme_U.cpp.
{
  REF(Field_base) ch=findInputField(name);
  if (!ch.non_nul())
    throw WrongArgument(le_nom().getChar(),"setInputField",name.getString(),"no input field of that name");
  if (!est_egal(afield._time1,presentTime()))
    throw WrongArgument(le_nom().getChar(),"setInputField","afield","Should be defined on current time interval");
  if (!est_egal(afield._time2,futureTime()))
    throw WrongArgument(le_nom().getChar(),"setInputField","afield","Should be defined on current time interval");
  if (strcmp(name.getChar(),afield.getCharName()))
    throw WrongArgument(le_nom().getChar(),"setInputField","afield","Should have the same name as the argument name ");
// Du au fait qu'on ne peut pas faire une ref sur Champ_Input_Proto qui n'est pas un Objet_U...
  Champ_Input_Proto * chip = dynamic_cast<Champ_Input_Proto *>(ch.operator->());
  if (!chip)
    throw WrongArgument(le_nom().getChar(),"setInputField",name.getString(),"field of this name is not an input field");
  chip->setValue(afield);
}
References est_egal(), findInputField(), futureTime(), Nom::getChar(), Nom::getString(), le_nom(), presentTime(), REF, and Champ_Input_Proto::setValue().
Referenced by ICoCo::ProblemTrio::setInputField().
setInputIntValue()
void Probleme_U::setInputIntValue (const Nom & name, const int & val) virtual
Definition at line 772 of file Probleme_U.cpp.
{
// add value in ICoCoScalarRegister
  reg.setInputIntValue(name, val);
}
References reg, and ScalarRegister::setInputIntValue().
Referenced by Value_Input_Int::readOn(), and ICoCo::ProblemTrio::setInputIntValue().
setStationary()
void Probleme_U::setStationary (bool) virtual
Tells to the Problem that stationary is reached or not.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 205 of file Probleme_U.cpp.
{
}
Referenced by run(), and Couplage_U::setStationary().
solveTimeStep()
bool Probleme_U::solveTimeStep (void) virtual
pour recodage eventuel et appel unifie en python
Reimplemented in Probleme_base, and Probleme_Couple.
Definition at line 567 of file Probleme_U.cpp.
{
  bool converged = false;
  bool ok        = true;
  while (!converged && ok)
    {
      ok= ok && updateGivenFields();
      ok = ok && iterateTimeStep(converged);
    }
  return ok;
}
References iterateTimeStep(), and updateGivenFields().
Referenced by run(), runUntil(), Probleme_base::solveTimeStep(), Probleme_Couple::solveTimeStep(), and ICoCo::ProblemTrio::solveTimeStep().
terminate()
void Probleme_U::terminate () virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 88 of file Probleme_U.cpp.
{
}
Referenced by Resoudre::interpreter(), Couplage_U::terminate(), and ICoCo::ProblemTrio::terminate().
updateGivenFields()
bool Probleme_U::updateGivenFields () virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
true=OK, false=error
Signification:
Contraintes:
Reimplemented in Couplage_U, Probleme_base, and Probleme_Couple.
Definition at line 329 of file Probleme_U.cpp.
{
  return true;
}
Referenced by Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Probleme_Couple::iterateTimeStep(), solveTimeStep(), and Couplage_U::updateGivenFields().
validateTimeStep()
void Probleme_U::validateTimeStep () virtual
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
Reimplemented in Couplage_U, and Probleme_base.
Definition at line 179 of file Probleme_U.cpp.
{
}
Referenced by run(), runUntil(), Couplage_U::validateTimeStep(), and ICoCo::ProblemTrio::validateTimeStep().
Member Data Documentation
info_obj
const Type_info Probleme_U::info_obj static
Definition at line 48 of file Probleme_U.h.
nom
Nom Probleme_U::nom protected
Definition at line 96 of file Probleme_U.h.
Referenced by Probleme_base::le_nom(), le_nom(), Probleme_base::nommer(), and nommer().
reg
ScalarRegister Probleme_U::reg protected
Definition at line 97 of file Probleme_U.h.
Referenced by getOutputIntValue(), and setInputIntValue().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Probleme_U.h
src/Kernel/Framework/Probleme_U.cpp