TRUST: Hexaedre_axi Class Reference
Hexaedre_axi Class Reference
Classe Hexaedre_axi
Cette classe represente la deformee de l'hexaedre dans
le cas d'un maillage en coordonnees cylindriques
Les methodes de la classe Hexaedre dont Hexaedre_axi derive sont
surchargees pour effectuer les calculs en coordonnees cylindrique.
#include <Hexaedre_axi.h>
Public Member Functions
Hexaedre_axi ()
~Hexaedre_axi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & nom_lml () const override
Renvoie le nom LML d'un triangle = "VOXEL8".
void reordonner () override
NE FAIT RIEN
A CODER.
int contient (const ArrOfDouble &, int) const override
NE FAIT RIEN: A CODER,renvoie toujours 0
Renvoie 1 si l'element "elemen" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un Hexaedre (Axi) n'a qu'un seul type de face.
void calculer_centres_gravite (DoubleTab &) const override
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
Public Member Functions inherited from Hexaedre
Hexaedre ()
~Hexaedre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Cette methode n'est plus inlinee car probleme au link symbol "reference dans une section .rodata" sur certains compilateurs gcc 3.3.x.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int face_sommet4 (int i) const
Renvoie le numero du i-ieme sommet de la face 4.
int face_sommet5 (int i) const
Renvoie le numero du i-ieme sommet de la face 5.
int nb_som () const override
Renvoie le nombre de sommets d'un hexaedre: 8.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 1, car l'element geometrique
Hexaedre est de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un triangle = "VOXEL8".
int contient (const ArrOfDouble &, int) const override
Renvoie 1 si l'element "elemen" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un hexaedre n'a qu'un seul type de face.
void reordonner () override
Reordonne les sommets de l'hexaedre.
int reordonner_elem ()
Reordonne les sommets de l'hexaedre.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const override
Calcule les normales aux faces des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
voir ElemGeomBase::get_tab_faces_sommets_locaux
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Hexaedre_axi & self_cast (Objet_U &)
static const Hexaedre_axi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Hexaedre
static Objet_U * cree_instance ()
static const Type_info * info ()
static Hexaedre & self_cast (Objet_U &)
static const Hexaedre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Hexaedre
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Hexaedre_axi
Cette classe represente la deformee de l'hexaedre dans
le cas d'un maillage en coordonnees cylindriques
Les methodes de la classe Hexaedre dont Hexaedre_axi derive sont
surchargees pour effectuer les calculs en coordonnees cylindrique.
Definition at line 36 of file Hexaedre_axi.h.
Constructor & Destructor Documentation
Hexaedre_axi()
Hexaedre_axi::Hexaedre_axi ()
Definition at line 19 of file Hexaedre_axi.cpp.
~Hexaedre_axi()
Hexaedre_axi::~Hexaedre_axi ()
Definition at line 19 of file Hexaedre_axi.cpp.
Member Function Documentation
calculer_centres_gravite()
void Hexaedre_axi::calculer_centres_gravite (DoubleTab & xp) const override virtual
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
Reimplemented from Elem_geom_base.
Definition at line 121 of file Hexaedre_axi.cpp.
{
  const IntTab& les_Polys = ma_zone->les_elems();
  const Domaine& le_domaine = ma_zone->domaine();
  int nb_elem = ma_zone->nb_elem();
  int num_som;
  xp.resize(nb_elem,dimension);
  xp=0;
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      double d_teta;
      int i, s;
      d_teta = le_domaine.coord(les_Polys(num_elem,3),1) -
               le_domaine.coord(les_Polys(num_elem,1),1);
      if( d_teta<0 )
        {
// Modif axi !
          for( s=0; s<nb_som(); s++)
            {
              num_som = les_Polys(num_elem,s);
              for( i=0; i<dimension; i++)
                xp(num_elem,i) += le_domaine.coord(num_som,i);
              if(le_domaine.coord(num_som,1) == 0.)
                xp(num_elem,1) += 2*M_PI;
            }
        }
      else
        for( s=0; s<nb_som(); s++)
          {
            num_som = les_Polys(num_elem,s);
            for( i=0; i<dimension; i++)
              xp(num_elem,i) += le_domaine.coord(num_som,i);
          }
    }
  double x=1./nb_som();
  xp*=x;
}
References Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone::les_elems(), M_PI, Elem_geom_base::ma_zone, Zone::nb_elem(), Hexaedre::nb_som(), and TRUSTTab< _TYPE_ >::resize().
calculer_volumes()
void Hexaedre_axi::calculer_volumes (DoubleVect & volumes) const override virtual
Calcule les volumes des elements de la zone associee.
Reimplemented from Hexaedre.
Definition at line 268 of file Hexaedre_axi.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double r,dr,d_teta,dz;
  int S1,S2,S4,S5;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      S1 = zone.sommet_elem(num_poly,0);
      S2 = zone.sommet_elem(num_poly,1);
      S4 = zone.sommet_elem(num_poly,3);
      S5 = zone.sommet_elem(num_poly,4);
      r = 0.5*(dom.coord(S2,0) + dom.coord(S1,0));
      dr = dom.coord(S2,0) - dom.coord(S1,0);
      d_teta = dom.coord(S4,1) - dom.coord(S2,1);
      if (d_teta<0) d_teta+=2.*M_PI;
      dz = dom.coord(S5,2) - dom.coord(S1,2);
      volumes[num_poly]= dr*r*d_teta*dz;
    }
}
References Domaine::coord(), Zone::domaine(), M_PI, Elem_geom_base::ma_zone, Zone::nb_elem_tot(), TRUSTVect< _TYPE_ >::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [1/2]
int Hexaedre_axi::contient (const ArrOfDouble & pos, int element) const override virtual
NE FAIT RIEN: A CODER,renvoie toujours 0
Renvoie 1 si l'element "elemen" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element "element"
0 sinon
Contraintes:
Reimplemented from Hexaedre.
Definition at line 192 of file Hexaedre_axi.cpp.
{
  assert(pos.size_array()==3);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som7 = zone.sommet_elem(element,7);
  double t7;
  t7=dom.coord(som7,1);
  if (t7<dom.coord(som0,1)) t7+=2*M_PI;
  if (    inf_ou_egal(dom.coord(som0,0),pos[0]) && inf_ou_egal(pos[0],dom.coord(som7,0))
          && inf_ou_egal(dom.coord(som0,1),pos[1]) && inf_ou_egal(pos[1],t7)
          && inf_ou_egal(dom.coord(som0,2),pos[2]) && inf_ou_egal(pos[2],dom.coord(som7,2)) )
    return 1;
  else
    return 0;
}
References Domaine::coord(), Zone::domaine(), inf_ou_egal(), M_PI, Elem_geom_base::ma_zone, TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [2/2]
int Hexaedre_axi::contient (const ArrOfInt & som, int element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Reimplemented from Hexaedre.
Definition at line 235 of file Hexaedre_axi.cpp.
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,2)==som[2])&&
      (zone.sommet_elem(element,3)==som[3])&&
      (zone.sommet_elem(element,4)==som[4])&&
      (zone.sommet_elem(element,5)==som[5])&&
      (zone.sommet_elem(element,6)==som[6])&&
      (zone.sommet_elem(element,7)==som[7]))
    return 1;
  else
    return 0;
}
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
cree_instance()
Objet_U * Hexaedre_axi::cree_instance () static
Definition at line 19 of file Hexaedre_axi.cpp.
duplique()
int Hexaedre_axi::duplique () const override virtual
Reimplemented from Hexaedre.
Definition at line 19 of file Hexaedre_axi.cpp.
get_info()
const Type_info * Hexaedre_axi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Hexaedre.
Definition at line 19 of file Hexaedre_axi.cpp.
info()
const Type_info * Hexaedre_axi::info () static
Definition at line 19 of file Hexaedre_axi.cpp.
nom_lml()
const Nom & Hexaedre_axi::nom_lml () const override virtual
Renvoie le nom LML d'un triangle = "VOXEL8".
Returns
Nom&
Signification: toujours egal a "VOXEL8"
Contraintes: reference constante
Reimplemented from Hexaedre.
Definition at line 98 of file Hexaedre_axi.cpp.
{
  static Nom nom="VOXEL8";
  return nom;
}
printOn()
Sortie & Hexaedre_axi::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Hexaedre.
Definition at line 36 of file Hexaedre_axi.cpp.
{
  return s;
}
readOn()
Entree & Hexaedre_axi::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Hexaedre.
Definition at line 56 of file Hexaedre_axi.cpp.
{
  return s;
}
reordonner()
void Hexaedre_axi::reordonner () override virtual
NE FAIT RIEN
A CODER.
Reimplemented from Hexaedre.
Definition at line 78 of file Hexaedre_axi.cpp.
{
  Hexaedre::reordonner();
}
References Hexaedre::reordonner().
self_cast() [1/2]
const Hexaedre_axi & Hexaedre_axi::self_cast (const Objet_U & r) static
Definition at line 19 of file Hexaedre_axi.cpp.
self_cast() [2/2]
Hexaedre_axi & Hexaedre_axi::self_cast (Objet_U & r) static
Definition at line 19 of file Hexaedre_axi.cpp.
taille_memoire()
unsigned Hexaedre_axi::taille_memoire () const override virtual
Reimplemented from Hexaedre.
Definition at line 19 of file Hexaedre_axi.cpp.
type_face()
Type_Face Hexaedre_axi::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un Hexaedre (Axi) n'a qu'un seul type de face.
Returns
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::quadrangle_3D_axi (si i=0)
Reimplemented from Hexaedre.
Definition at line 69 of file Hexaedre_axi.h.
{
  assert(i==0);
  return Faces::quadrangle_3D_axi;
}
References Faces::quadrangle_3D_axi.
Member Data Documentation
info_obj
const Type_info Hexaedre_axi::info_obj static
Definition at line 39 of file Hexaedre_axi.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Hexaedre_axi.h
src/Kernel/Geometrie/Hexaedre_axi.cpp