TRUST: Eval_Dift_VDF_const_Face Class Reference
Eval_Dift_VDF_const_Face Class Reference
!<
#include <Eval_Dift_VDF_Face_leaves.h>
Public Member Functions
void associer_modele_turbulence (const Mod_turb_hyd_base &mod)
void mettre_a_jour () override
double tau_tan_impl (int face, int k) const
bool uses_wall () const
Public Member Functions inherited from Eval_Diff_VDF_Face< Eval_Dift_VDF_const_Face >
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > flux_fa7 (const DoubleTab &, int, const Neumann_sortie_libre &, int, Type_Double &) const
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > flux_fa7 (const DoubleTab &, int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::MIXTE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
enable_if_t<(Arete_Type==Type_Flux_Arete::SYMETRIE), void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > coeffs_fa7 (int, const Neumann_sortie_libre &, Type_Double &, Type_Double &) const
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > coeffs_fa7 (int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::MIXTE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &, Type_Double &) const
enable_if_t<(Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE), void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &, Type_Double &) const
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > secmem_fa7 (int, const Neumann_sortie_libre &, int, Type_Double &) const
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > secmem_fa7 (int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI, void > secmem_arete (int, int, int, int, Type_Double &) const
enable_if_t<(Arete_Type==Type_Flux_Arete::INTERNE||Arete_Type==Type_Flux_Arete::MIXTE||Arete_Type==Type_Flux_Arete::SYMETRIE), void > secmem_arete (int, int, int, int, Type_Double &) const
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE, void > secmem_arete (int, int, int, int, Type_Double &, Type_Double &) const
enable_if_t<(Arete_Type==Type_Flux_Arete::PERIODICITE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE), void > secmem_arete (int, int, int, int, Type_Double &, Type_Double &) const
Public Member Functions inherited from Eval_VDF_Face
void associer_inconnue (const Champ_base &)
Public Member Functions inherited from Evaluateur_VDF
Evaluateur_VDF ()
virtual ~Evaluateur_VDF ()
Evaluateur_VDF (const Evaluateur_VDF &)
virtual void associer_zones (const Zone_VDF &, const Zone_Cl_VDF &)
virtual void associer_porosite (const DoubleVect &)
double dist_face_period (int fac1, int fac2, int k) const
double dist_face (int fac1, int fac2, int k) const
Public Member Functions inherited from Eval_Dift_VDF_const
void mettre_a_jour () override
void associer_diff_turb (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double nu_t_impl (int i, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double get_equivalent_distance (int boundary_index, int local_face) const override
Public Member Functions inherited from Eval_Diff_VDF_const
Eval_Diff_VDF_const ()
void associer (const Champ_base &) override
void mettre_a_jour () override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double nu_t_impl (int i, int compo) const
double tau_tan_impl (int i, int j) const
bool uses_wall () const
bool uses_mod () const
const DoubleTab & get_k_elem () const
pour F5 seulement ...
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Public Member Functions inherited from Eval_Turbulence
virtual ~Eval_Turbulence ()
virtual void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
virtual void init_ind_fluctu_term ()
void update_equivalent_distance ()
Static Public Attributes
static constexpr bool IS_TURB = true
static constexpr bool CALC_FA7_SORTIE_LIB = true
static constexpr bool CALC_ARR_PAR_FL = false
Static Public Attributes inherited from Eval_Diff_VDF_Face< Eval_Dift_VDF_const_Face >
static constexpr bool IS_VAR
static constexpr bool IS_TURB
static constexpr bool TEST_COEFFS
static constexpr bool ACTIVATE_TAU_TR
Static Public Attributes inherited from Eval_VDF_Face
static constexpr bool CALC_FA7_SORTIE_LIB = false
static constexpr bool CALC_ARR_FL = true
static constexpr bool CALC_ARR_BORD = true
static constexpr bool CALC_ARR_COIN_FL = false
static constexpr bool CALC_ARR_INT = true
static constexpr bool CALC_ARR_MIXTE = true
static constexpr bool CALC_ARR_PERIO = true
static constexpr bool CALC_ARR_PAR_FL = true
static constexpr bool CALC_ARR_PAR = true
static constexpr bool CALC_ARR_SYMM_PAR = true
static constexpr bool CALC_ARR_SYMM_FL = true
static constexpr bool CALC_ARR_SYMM = false
Protected Attributes
Ref_Mod_turb_hyd_base le_modele_turbulence
DoubleTab tau_tan_
Protected Attributes inherited from Eval_VDF_Face
Ref_Champ_base inconnue
Protected Attributes inherited from Evaluateur_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
int dimension
int premiere_face_bord
IntTab elem_
les 2 elements voisins d'une face
DoubleVect surface
surfaces des faces
IntVect orientation
orientations des faces
DoubleVect porosite
porosites surfaciques
DoubleVect volume_entrelaces
DoubleTab xv
coord des centres des faces
Protected Attributes inherited from Eval_Dift_VDF_const
Ref_Champ_Fonc diffusivite_turbulente_
DoubleVect dv_diffusivite_turbulente
Protected Attributes inherited from Eval_Diff_VDF_const
Ref_Champ_Uniforme diffusivite_
double db_diffusivite
Protected Attributes inherited from Eval_Turbulence
Ref_Turbulence_paroi_scal loipar
DoubleVects equivalent_distance
Additional Inherited Members
Protected Member Functions inherited from Evaluateur_VDF
double dist_norm_bord (int) const
Detailed Description
!<
class Eval_Dift_VDF_const_Face
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est un Champ_Face
Le champ de diffusivite est constant.
Definition at line 34 of file Eval_Dift_VDF_Face_leaves.h.
Member Function Documentation
associer_modele_turbulence()
void Eval_Dift_VDF_const_Face::associer_modele_turbulence (const Mod_turb_hyd_base & mod) inline
Definition at line 39 of file Eval_Dift_VDF_Face_leaves.h.
{ le_modele_turbulence= mod; }
References le_modele_turbulence.
mettre_a_jour()
void Eval_Dift_VDF_const_Face::mettre_a_jour () inline override virtual
Reimplemented from Eval_Dift_VDF_const.
Definition at line 51 of file Eval_Dift_VDF_Face_leaves.h.
{
  Eval_Dift_VDF_const::mettre_a_jour( ) ;
  if (le_modele_turbulence->loi_paroi().non_nul()) tau_tan_.ref(le_modele_turbulence->loi_paroi()->Cisaillement_paroi());
}
References Turbulence_paroi::Cisaillement_paroi(), le_modele_turbulence, Mod_turb_hyd_base::loi_paroi(), Eval_Dift_VDF_const::mettre_a_jour(), O_U_Ptr::non_nul(), TRUSTTab< _TYPE_ >::ref(), and tau_tan_.
tau_tan_impl()
double Eval_Dift_VDF_const_Face::tau_tan_impl (int face, int k) const inline
Definition at line 57 of file Eval_Dift_VDF_Face_leaves.h.
{
  const int nb_faces = la_zone.valeur().nb_faces();
  const ArrOfInt& ind_faces_virt_bord = la_zone.valeur().ind_faces_virt_bord();
  int f = (face >= tau_tan_.dimension(0)) ? ind_faces_virt_bord[face-nb_faces] : face;
  if(f >= tau_tan_.dimension_tot(0))
    {
      Cerr << "Erreur dans tau_tan " << finl;
      Cerr << "dimension : " << tau_tan_.dimension(0) << finl;
      Cerr << "dimension_tot : " << tau_tan_.dimension_tot(0) << finl;
      Cerr << "face : " << face << finl;
      Process::exit();
    }
  return tau_tan_(f,k);
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, Zone_VF::ind_faces_virt_bord(), Evaluateur_VDF::la_zone, Zone_VF::nb_faces(), tau_tan_, and Ref_Zone_VDF::valeur().
uses_wall()
bool Eval_Dift_VDF_const_Face::uses_wall () const inline
Definition at line 44 of file Eval_Dift_VDF_Face_leaves.h.
{ return le_modele_turbulence.valeur().utiliser_loi_paroi(); }
References le_modele_turbulence, Mod_turb_hyd_base::utiliser_loi_paroi(), and Ref_Mod_turb_hyd_base::valeur().
Member Data Documentation
CALC_ARR_PAR_FL
constexpr bool Eval_Dift_VDF_const_Face::CALC_ARR_PAR_FL = false static
Definition at line 38 of file Eval_Dift_VDF_Face_leaves.h.
CALC_FA7_SORTIE_LIB
constexpr bool Eval_Dift_VDF_const_Face::CALC_FA7_SORTIE_LIB = true static
Definition at line 38 of file Eval_Dift_VDF_Face_leaves.h.
IS_TURB
constexpr bool Eval_Dift_VDF_const_Face::IS_TURB = true static constexpr
Definition at line 38 of file Eval_Dift_VDF_Face_leaves.h.
le_modele_turbulence
Ref_Mod_turb_hyd_base Eval_Dift_VDF_const_Face::le_modele_turbulence protected
Definition at line 47 of file Eval_Dift_VDF_Face_leaves.h.
Referenced by associer_modele_turbulence(), mettre_a_jour(), and uses_wall().
tau_tan_
DoubleTab Eval_Dift_VDF_const_Face::tau_tan_ protected
Definition at line 48 of file Eval_Dift_VDF_Face_leaves.h.
Referenced by mettre_a_jour(), and tau_tan_impl().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Dift_VDF_Face_leaves.h