TRUST: Frontiere_ouverte_rho_u_impose Class Reference
Frontiere_ouverte_rho_u_impose Class Reference
Frontiere ouverte sur laquelle on impose le flux massique rho.U
et non la vitesse U. La vitesse est calculee par division par
rho(n+1) trouve dans le fluide au moment de l'appel a
val_imp.
#include <Frontiere_ouverte_rho_u_impose.h>
Public Member Functions
Frontiere_ouverte_rho_u_impose ()
~Frontiere_ouverte_rho_u_impose ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_vitesse_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
double val_imp_au_temps (double temps, int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
double val_imp_au_temps (double temps, int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Frontiere_ouverte_rho_u_impose & self_cast (Objet_U &)
static const
Frontiere_ouverte_rho_u_impose & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Attributes
Ref_Fluide_Dilatable_base le_fluide
Detailed Description
Frontiere ouverte sur laquelle on impose le flux massique rho.U
et non la vitesse U. La vitesse est calculee par division par
rho(n+1) trouve dans le fluide au moment de l'appel a
val_imp.
Definition at line 40 of file Frontiere_ouverte_rho_u_impose.h.
Constructor & Destructor Documentation
Frontiere_ouverte_rho_u_impose::Frontiere_ouverte_rho_u_impose ()
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
Frontiere_ouverte_rho_u_impose::~Frontiere_ouverte_rho_u_impose ()
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
Member Function Documentation
int Frontiere_ouverte_rho_u_impose::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_vitesse_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Entree_fluide_vitesse_imposee.
Definition at line 46 of file Frontiere_ouverte_rho_u_impose.cpp.
References Entree_fluide_vitesse_imposee::compatible_avec_eqn(), Cond_lim_base::ma_zone_cl_dis, and sub_type.
{
  if (!Entree_fluide_vitesse_imposee_libre::compatible_avec_eqn(eqn)) return 0;
  if (!sub_type(Fluide_Dilatable_base,ma_zone_cl_dis->equation().milieu())) return 0;
  return 1;
}
void Frontiere_ouverte_rho_u_impose::completer (void) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Definition at line 41 of file Frontiere_ouverte_rho_u_impose.cpp.
References le_fluide, Cond_lim_base::ma_zone_cl_dis, and ref_cast.
{
  le_fluide = ref_cast(Fluide_Dilatable_base,ma_zone_cl_dis->equation().milieu());
}
Objet_U * Frontiere_ouverte_rho_u_impose::cree_instance () [static]
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
int Frontiere_ouverte_rho_u_impose::duplique () const [virtual]
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
const Type_info * Frontiere_ouverte_rho_u_impose::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
const Type_info * Frontiere_ouverte_rho_u_impose::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
Sortie & Frontiere_ouverte_rho_u_impose::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 31 of file Frontiere_ouverte_rho_u_impose.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Frontiere_ouverte_rho_u_impose::readOn (Entree & s) [protected, virtual]
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 36 of file Frontiere_ouverte_rho_u_impose.cpp.
{
  return Entree_fluide_vitesse_imposee_libre::readOn(s);
}
const Frontiere_ouverte_rho_u_impose & Frontiere_ouverte_rho_u_impose::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
Frontiere_ouverte_rho_u_impose & Frontiere_ouverte_rho_u_impose::self_cast (Objet_U & r) [static]
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
unsigned Frontiere_ouverte_rho_u_impose::taille_memoire () const [virtual]
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 29 of file Frontiere_ouverte_rho_u_impose.cpp.
double Frontiere_ouverte_rho_u_impose::val_imp_au_temps (double temps, int i) const [virtual]
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
Reimplemented from Dirichlet.
Definition at line 54 of file Frontiere_ouverte_rho_u_impose.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Acces a une condition limite en rho.u sans preciser la composante" << finl;
  Process::exit();
  return 0;
}
double Frontiere_ouverte_rho_u_impose::val_imp_au_temps (double temps, int i, int j) const [virtual]
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
Reimplemented from Dirichlet.
Definition at line 61 of file Frontiere_ouverte_rho_u_impose.cpp.
References DoubleTab::dimension(), Frontiere_dis_base::frontiere(), Champ_front::frontiere_dis(), Cond_lim_base::le_champ_front, le_fluide, DoubleTab::nb_dim(), and Frontiere::num_premiere_face().
{
  double rho_u, rho;
  int ndeb=le_champ_front->frontiere_dis().frontiere().num_premiere_face();
  const DoubleTab& tab_rho_u=le_champ_front->valeurs_au_temps(temps);
  assert(tab_rho_u.nb_dim()==2);
  if (tab_rho_u.dimension(0)==1)
    rho_u=tab_rho_u(0,j);
  else
    rho_u=tab_rho_u(i,j);
  rho=le_fluide->rho_face_np1()(i+ndeb);
  return rho_u/rho;
}
Member Data Documentation
const Type_info Frontiere_ouverte_rho_u_impose::info_obj [static]
Reimplemented from Entree_fluide_vitesse_imposee_libre.
Definition at line 42 of file Frontiere_ouverte_rho_u_impose.h.
Ref_Fluide_Dilatable_base Frontiere_ouverte_rho_u_impose::le_fluide [protected]
Definition at line 51 of file Frontiere_ouverte_rho_u_impose.h.
Referenced by completer(), and val_imp_au_temps().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Cond_Lim/Frontiere_ouverte_rho_u_impose.h
src/ThHyd/Dilatable/Common/Cond_Lim/Frontiere_ouverte_rho_u_impose.cpp