TRUST: Navier_Stokes_QC Class Reference
Navier_Stokes_QC Class Reference
classe Navier_Stokes_QC
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
#include <Navier_Stokes_QC.h>
Public Member Functions
Navier_Stokes_QC ()
~Navier_Stokes_QC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
int impr (Sortie &os) const override
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_base
Navier_Stokes_Fluide_Dilatable_base ()
~Navier_Stokes_Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
int preparer_calcul () override
Appel Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
const Champ_Don & diffusivite_pour_transport () const override
const Champ_base & diffusivite_pour_pas_de_temps () const override
const Champ_base & vitesse_pour_transport () const override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
const Champ_base & get_champ (const Motcle &nom) const override
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem) override
void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem) override
void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) override
int impr (Sortie &os) const override
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
bool initTimeStep (double dt) override
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
const Champ_Inc & rho_la_vitesse () const override
Public Member Functions inherited from Navier_Stokes_std
~Navier_Stokes_std ()
< For Immersed Boundary Method (IBM)
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Navier_Stokes_std ()
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_pb_base (const Probleme_base &) override
S'associe au probleme:
apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
void associer_fluide (const Fluide_base &)
Associe un fluide incompressible a l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
void associer_milieu_base (const Milieu_base &) override
Associe un mileu physique a l'equation en construisant
dynamiquement (cast) un objet de type Fluide_base
a partir de l'objet Milieu_base passe en parametre.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
Pour Navier Stokes Standard c'est 2.
int nombre_d_operateurs_tot () const override
const Operateur & operateur (int) const override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1.
const Operateur & operateur_fonctionnel (int) const override
Operateur & operateur_fonctionnel (int) override
Operateur_Div & operateur_divergence ()
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
const Operateur_Div & operateur_divergence () const
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
(version const)
Operateur_Grad & operateur_gradient ()
Renvoie l'operateur de calcul du gradient
associe a l'equation.
const Operateur_Grad & operateur_gradient () const
Renvoie l'operateur de calcul du gradient
associe a l'equation.
(version const)
const Champ_Inc & inconnue () const override
Renvoie la vitesse (champ inconnue de l'equation)
(version const)
Champ_Inc & inconnue () override
Renvoie la vitesse (champ inconnue de l'equation)
SolveurSys & solveur_pression ()
Renvoie le solveur en pression<br>(version const)
void discretiser () override
Dicretise l'equation.
virtual void discretiser_vitesse ()
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique
Association d une equation de transport d interface a l ensemble
de points suivis si le fluide est marque.
Entree & lire_cond_init (Entree &) override
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
bool initTimeStep (double dt) override
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
void abortTimeStep () override
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
int impr (Sortie &os) const override
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
int sauvegarder (Sortie &) const override
Appelle Equation_base::sauvegarder(Sortie&)
et sauvegarde la pression sur un flot de sortie.
int reprendre (Entree &) override
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend la pression.
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
DoubleTab & corriger_derivee_expl (DoubleTab &) override
Add a specific term for Navier Stokes (-gradP(n)) if necessary.
DoubleTab & corriger_derivee_impl (DoubleTab &) override
Resolution de la pression, inconnue implicitee de Navier Stokes.
int preparer_calcul () override
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Matrice & matrice_pression ()
Assembleur & assembleur_pression ()
Champ_Inc & pression ()
Renvoie le champ de pression.
Champ_Inc & grad_P ()
Renvoie le gradient de pression<br>(version const)
const Champ_Inc & grad_P () const
Champ_Inc & pression_pa ()
Champ_Inc & div ()
const Champ_Inc & pression () const
Renvoie le champ de pression.
const Champ_Inc & pression_pa () const
const Champ_Inc & div () const
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application: "Hydraulique".
virtual const Champ_Inc & vitesse () const
virtual Champ_Inc & vitesse ()
virtual void projeter ()
Calcule la solution U des equations:
| M(U-V)/dt + BtP = 0
|-BU=0
On resoud le probleme en pression: -BM-1BtP = -BV/dt
sachant que -BV represente le calcul de la divergence de V
On resoud le probleme en vitesse en appliquant le solveur
de masse au gradient de P: U=V - dt*M-1BtP.
virtual int projection_a_faire ()
virtual void sauver () const
virtual void calculer_la_pression_en_pa ()
Calcul de "la_pression_en_pa" en fonction de "la_pression".
Si le champ milieu().masse_volumique() est uniforme, on suppose que
la_pression est P* = P/rho, et on multiplie par rho. Sinon,
la_pression est deja en Pa.
Cette methode est surchargee en front-tracking.
virtual void calculer_pression_hydrostatique (Champ_base &pression_hydro) const
int verif_Cl () const override
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual const Champ_Inc & rho_la_vitesse () const
Operateur_Conv & get_terme_convectif ()
virtual void renewing_jacobians (DoubleTab &derivee)
virtual void div_ale_derivative (DoubleTrav &derivee_ale, double timestep, DoubleTab &derivee, DoubleTrav &secmemP)
virtual void update_pressure_matrix (void)
const int & get_matrice_pression_penalisee_H1 () const
const int & get_correction_matrice_pression () const
const int & get_correction_vitesse_modifie () const
const int & get_correction_pression_modifie () const
const int & get_gradient_pression_qdm_modifie () const
const int & get_i_source_pdf () const
const DoubleTab & get_champ_coeff_pdf_som () const
const int & get_correction_vitesse_projection_initiale () const
const int & get_correction_calcul_pression_initiale () const
const int & get_correction_matrice_projection_initiale () const
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_Proto
Navier_Stokes_Fluide_Dilatable_Proto ()
int impr_impl (const Navier_Stokes_std &eqn, Sortie &os) const
void assembler_impl (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_avec_inertie_impl (const Navier_Stokes_std &eqn, Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_blocs_avec_inertie (const Navier_Stokes_std &eqn, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl)
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Calcule la derivee en temps de l'inconnue vitesse,
i.e. l'acceleration dU/dt et la renvoie.
Appelle Equation_base::derivee_en_temps_inco(DoubleTab&)
Calcule egalement la pression.
DoubleTab & rho_vitesse_impl (const DoubleTab &tab_rho, const DoubleTab &vit, DoubleTab &rhovitesse) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Navier_Stokes_QC & self_cast (Objet_U &)
static const Navier_Stokes_QC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_base
static const Type_info * info ()
static Navier_Stokes_Fluide_Dilatable_base & self_cast (Objet_U &)
static const Navier_Stokes_Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Navier_Stokes_std
static Objet_U * cree_instance ()
static const Type_info * info ()
static Navier_Stokes_std & self_cast (Objet_U &)
static const Navier_Stokes_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Navier_Stokes_Fluide_Dilatable_base
static const Type_info info_obj
Static Public Attributes inherited from Navier_Stokes_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Protected Member Functions inherited from Navier_Stokes_std
Sortie & printOn (Sortie &x) const override
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Entree & readOn (Entree &) override
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
virtual void discretiser_assembleur_pression ()
Typage de l'assembleur pression. Le nom de l'assembleur
utilise est construit comme :
Assembleur_P_xxx" ou "xxx" est le nom de la discretisation.
Cette methode est virtuelle et surchargee dans le front-tracking.
Elle est appelee par Navier_Stokes_std::discretiser()
void uzawa (const DoubleTab &, const Matrice_Base &, SolveurSys &, DoubleTab &, DoubleTab &)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Navier_Stokes_std
Ref_Fluide_base le_fluide
Champ_Inc la_vitesse
Champ_Inc la_pression
Champ_Inc divergence_U
Champ_Inc gradient_P
Champ_Inc la_pression_en_pa
Champ_Fonc la_vorticite
Champ_Fonc grad_u
Champ_Fonc critere_Q
Champ_Fonc pression_hydrostatique_
Champ_Fonc porosite_volumique
Champ_Fonc combinaison_champ
Champ_Fonc distance_paroi_globale
Champ_Fonc y_plus
Champ_Fonc Reynolds_maille
Champ_Fonc Courant_maille
Champ_Fonc Taux_cisaillement
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Operateur_Div divergence
Operateur_Grad gradient
Matrice matrice_pression_
Assembleur assembleur_pression_
SolveurSys solveur_pression_
int projection_initiale
double dt_projection
double seuil_projection
double seuil_uzawa
double max_div_U
double seuil_divU
double raison_seuil_divU
double LocalFlowRateRelativeError_
double cumulative_
Traitement_particulier_NS le_traitement_particulier
Nom chaine_champ_combi
int methode_calcul_pression_initiale_
int div_u_nul_et_non_dsurdt_divu_
int postraiter_gradient_pression_sans_masse_
int correction_matrice_projection_initiale_
int correction_calcul_pression_initiale_
int correction_vitesse_projection_initiale_
int correction_matrice_pression_
int matrice_pression_penalisee_H1_
int correction_vitesse_modifie_
int correction_pression_modifie_
int gradient_pression_qdm_modifie_
int i_source_pdf_
DoubleTab champ_coeff_pdf_som_
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Protected Attributes inherited from Navier_Stokes_Fluide_Dilatable_Proto
Champ_Inc rho_la_vitesse_
IntVect orientation_VDF_
DoubleTab tab_W
RHS of div(rho.U)
Detailed Description
classe Navier_Stokes_QC
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Definition at line 43 of file Navier_Stokes_QC.h.
Constructor & Destructor Documentation
Navier_Stokes_QC()
Navier_Stokes_QC::Navier_Stokes_QC ()
Definition at line 20 of file Navier_Stokes_QC.cpp.
~Navier_Stokes_QC()
Navier_Stokes_QC::~Navier_Stokes_QC ()
Definition at line 20 of file Navier_Stokes_QC.cpp.
Member Function Documentation
completer()
void Navier_Stokes_QC::completer (void) override virtual
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 59 of file Navier_Stokes_QC.cpp.
{
  Cerr<<"Navier_Stokes_QC::completer"<<finl;
  if (le_fluide->a_gravite())
    {
      Cerr << "Gravity = " << le_fluide->gravite() << finl;
      Cerr << "Creation of the buoyancy source term for the Navier_Stokes_QC equation : " << finl;
      Source t;
      Source& so=les_sources.add(t);
      Nom type_so = "Source_QC_Gravite_";
      Nom disc = discretisation().que_suis_je();
      if (disc=="VEFPreP1B") disc = "VEF";
      type_so += disc;
      so.typer_direct(type_so);
      so->associer_eqn(*this);
      Cerr << so->que_suis_je() << finl;
    }
  Navier_Stokes_Fluide_Dilatable_base::completer();
}
References Milieu_base::a_gravite(), List_Source::add(), Cerr, Navier_Stokes_Fluide_Dilatable_base::completer(), Equation_base::discretisation(), finl, Milieu_base::gravite(), Navier_Stokes_std::le_fluide, Equation_base::les_sources, Objet_U::que_suis_je(), and Source::typer_direct().
cree_instance()
Objet_U * Navier_Stokes_QC::cree_instance () static
Definition at line 20 of file Navier_Stokes_QC.cpp.
duplique()
int Navier_Stokes_QC::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Navier_Stokes_QC.cpp.
get_info()
const Type_info * Navier_Stokes_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 20 of file Navier_Stokes_QC.cpp.
impr()
int Navier_Stokes_QC::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 79 of file Navier_Stokes_QC.cpp.
{
  return Navier_Stokes_Fluide_Dilatable_base::impr(os);
}
References Navier_Stokes_Fluide_Dilatable_base::impr().
info()
const Type_info * Navier_Stokes_QC::info () static
Definition at line 20 of file Navier_Stokes_QC.cpp.
printOn()
Sortie & Navier_Stokes_QC::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 23 of file Navier_Stokes_QC.cpp.
{
  return Navier_Stokes_Fluide_Dilatable_base::printOn(is);
}
References Navier_Stokes_Fluide_Dilatable_base::printOn().
readOn()
Entree & Navier_Stokes_QC::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< XD attr disable_equation_residual chaine disable_equation_residual 1 The equation residual will not be used for the problem residual used when checking time convergence or computing dynamic time-step
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 28 of file Navier_Stokes_QC.cpp.
{
  Navier_Stokes_Fluide_Dilatable_base::readOn(is);
  assert(le_fluide.non_nul());
  if (!sub_type(Fluide_Quasi_Compressible,le_fluide.valeur()))
    {
      Cerr<<"ERROR : the Navier_Stokes_QC equation can be associated only to a quasi compressible fluid."<<finl;
      Process::exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, Navier_Stokes_std::le_fluide, O_U_Ptr::non_nul(), Navier_Stokes_Fluide_Dilatable_base::readOn(), sub_type, and Ref_Fluide_base::valeur().
self_cast() [1/2]
const Navier_Stokes_QC & Navier_Stokes_QC::self_cast (const Objet_U & r) static
Definition at line 20 of file Navier_Stokes_QC.cpp.
self_cast() [2/2]
Navier_Stokes_QC & Navier_Stokes_QC::self_cast (Objet_U & r) static
Definition at line 20 of file Navier_Stokes_QC.cpp.
taille_memoire()
unsigned Navier_Stokes_QC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Navier_Stokes_QC.cpp.
Member Data Documentation
info_obj
const Type_info Navier_Stokes_QC::info_obj static
Definition at line 45 of file Navier_Stokes_QC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Navier_Stokes_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Navier_Stokes_QC.cpp