TRUST: Integrale_tps_produit_champs Class Reference
Integrale_tps_produit_champs Class Reference
classe Integrale_tps_produit_champs
Cette classe represente l'integrale en temps d'un produit de 2 champs
eleves a une puissance entiere et positive entre un temps initial et un
temps courant
Un objet Integrale_tps_produit_champs a donc 2 champs associes dont
il represente l'integrale du produit.
#include <Integrale_tps_produit_champs.h>
Public Member Functions
Integrale_tps_produit_champs ()
~Integrale_tps_produit_champs ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Ref_Champ_Generique_base & mon_premier_champ () const
const Ref_Champ_Generique_base & mon_second_champ () const
int premiere_puissance () const
int seconde_puissance () const
const int & get_support_different () const
int & support_different ()
void associer (const Champ_Generique_base &, const Champ_Generique_base &, int, int, double, double)
Associe les champs et les temps.
void mettre_a_jour (double) override
void mettre_a_jour_integrale () override
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du
champ associe et poursuit l'integration jusqu'au temps courant.
si la borne superieure de l'integrale n'est pas depassee.
void ajoute_produit_tensoriel (double, const Champ_base &, const Champ_base &)
Public Member Functions inherited from Integrale_tps_Champ
Integrale_tps_Champ ()
~Integrale_tps_Champ ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Ref_Champ_Generique_base & le_champ () const
double temps_integrale () const
le temps courant de l'integrale
double t_debut () const
le temps de debut d'integration
double t_fin () const
le temps de fin d'integration
double dt_integration () const
la duree d'integration deja effectuee
void fixer_t_debut (double t)
Fixe le temps de debut d'integration.
void fixer_t_fin (double t)
Fixe le temps de fin d'integration.
void fixer_dt_integr (double t)
void fixer_tps_integrale (double t)
Fixe le temps courant de l'integrale (derniere date a laquelle on a mis l'integrale a jour)
void associer (const Champ_base &, int, double, double)
void associer (const Champ_Generique_base &, int, double, double)
virtual void mettre_a_jour (double)
virtual void mettre_a_jour_integrale ()
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du
champ associe et poursuit l'integration jusqu'au temps courant.
si la borne superieure de l'integrale n'est pas depassee.
Public Member Functions inherited from Champ_Fonc
Champ_Fonc ()
~Champ_Fonc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Fonc (const Champ_Fonc &)=default
Champ_Fonc & operator= (const Champ_Fonc_base &)
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
Champ_Fonc & operator= (const Champ_Fonc &)
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
void fixer_nb_valeurs_nodales (int)
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
int nb_valeurs_nodales () const
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
DoubleTab & valeurs () override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ<br>(version const)
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
double temps () const
Appel a l'objet sous-jacent
Renvoie le temps courant du champ.
double changer_temps (const double t)
Appel a l'objet sous-jacent
Change le temps courant du champ, et le renvoie.
void mettre_a_jour (double un_temps)
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
int initialiser (const double un_temps)
Appel a l'objet sous-jacent
Initilialise le champ (si il y lieu)
void associer_zone_dis_base (const Zone_dis_base &)
Appel a l'objet sous-jacent
Associe une zone discretisee au champ.
const Zone_dis_base & zone_dis_base () const
Appel a l'objet sous-jacent
Renvoe la zone discretisee associee.
int reprendre (Entree &) override
Appel a l'objet sous-jacent
Postraite au format lml.
int sauvegarder (Sortie &) const override
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &les_valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &les_valeurs) const
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_Fonc_base
~Deriv_Champ_Fonc_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Fonc_base ()
Deriv_Champ_Fonc_base (const Deriv_Champ_Fonc_base &)
const Champ_Fonc_base & valeur () const
Champ_Fonc_base & valeur ()
const Champ_Fonc_base * operator-> () const
Champ_Fonc_base * operator-> ()
const Deriv_Champ_Fonc_base & operator= (const Champ_Fonc_base &)
const Deriv_Champ_Fonc_base & operator= (const Deriv_Champ_Fonc_base &)
operator const Champ_Fonc_base & () const
operator Champ_Fonc_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Integrale_tps_produit_champs & self_cast (Objet_U &)
static const Integrale_tps_produit_champs & self_cast (const Objet_U &)
Static Public Member Functions inherited from Integrale_tps_Champ
static Objet_U * cree_instance ()
static const Type_info * info ()
static Integrale_tps_Champ & self_cast (Objet_U &)
static const Integrale_tps_Champ & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc & self_cast (Objet_U &)
static const Champ_Fonc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_Fonc_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Fonc_base & self_cast (Objet_U &)
static const Deriv_Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Integrale_tps_Champ
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture d'un Champ_Fonc sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Champ_Fonc sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecriture d'un Champ_Fonc sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Champ_Fonc sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecriture d'un Champ_Fonc sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Champ_Fonc sur un flot d'entree.
Protected Member Functions inherited from Deriv_Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Champ_Generique_base mon_second_champ_
int seconde_puissance_
int support_different_
Protected Attributes inherited from Integrale_tps_Champ
Ref_Champ_Generique_base mon_champ
int puissance
double t_debut_
double t_fin_
double tps_integrale
double dt_integr_calcul
Detailed Description
classe Integrale_tps_produit_champs
Cette classe represente l'integrale en temps d'un produit de 2 champs
eleves a une puissance entiere et positive entre un temps initial et un
temps courant
Un objet Integrale_tps_produit_champs a donc 2 champs associes dont
il represente l'integrale du produit.
Definition at line 33 of file Integrale_tps_produit_champs.h.
Constructor & Destructor Documentation
Integrale_tps_produit_champs()
Integrale_tps_produit_champs::Integrale_tps_produit_champs ()
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
~Integrale_tps_produit_champs()
Integrale_tps_produit_champs::~Integrale_tps_produit_champs ()
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
Member Function Documentation
ajoute_produit_tensoriel()
void Integrale_tps_produit_champs::ajoute_produit_tensoriel (double alpha, const Champ_base & a, const Champ_base & b)
Definition at line 97 of file Integrale_tps_produit_champs.cpp.
{
  if (support_different_)
    {
// On ramene au centre des elements
      const DoubleTab& xp = ref_cast(Zone_VF,zone_dis_base()).xp();
      int nb_elem_tot = xp.dimension_tot(0);
      DoubleTab val_a,val_b;
// Le jour ou les champs seront mieux foutus, on n'aura
// pas a faire ca:
      val_a.resize(nb_elem_tot,a.nb_comp());
      val_b.resize(nb_elem_tot,b.nb_comp());
      a.valeur_aux(xp, val_a);
      b.valeur_aux(xp, val_b);
      valeurs().ajoute_produit_tensoriel(alpha,val_a,val_b);
      valeurs().echange_espace_virtuel();
    }
  else
    {
      const DoubleTab& val_a = a.valeurs();
      const DoubleTab& val_b = b.valeurs();
      valeurs().ajoute_produit_tensoriel(alpha,val_a,val_b);
    }
}
References TRUSTTab< _TYPE_ >::ajoute_produit_tensoriel(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Field_base::nb_comp(), ref_cast, TRUSTTab< _TYPE_ >::resize(), support_different_, Champ_base::valeur_aux(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), and Champ_Fonc::zone_dis_base().
Referenced by Op_Correlation::calculer_valeurs(), and mettre_a_jour_integrale().
associer()
void Integrale_tps_produit_champs::associer (const Champ_Generique_base & ch1, const Champ_Generique_base & ch2, int n1, int n2, double t0, double t1) inline
Associe les champs et les temps.
Definition at line 88 of file Integrale_tps_produit_champs.h.
{
  Integrale_tps_Champ::associer(ch1, n1, t0, t1);
  mon_second_champ_=ch2;
  seconde_puissance_=n2;
}
References Integrale_tps_Champ::associer(), mon_second_champ_, and seconde_puissance_.
Referenced by Op_Correlation::associer().
cree_instance()
Objet_U * Integrale_tps_produit_champs::cree_instance () static
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
duplique()
int Integrale_tps_produit_champs::duplique () const override virtual
Reimplemented from Integrale_tps_Champ.
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
get_info()
const Type_info * Integrale_tps_produit_champs::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Integrale_tps_Champ.
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
get_support_different()
const int & Integrale_tps_produit_champs::get_support_different () const inline
Definition at line 54 of file Integrale_tps_produit_champs.h.
  {
    return support_different_;
  };
References support_different_.
info()
const Type_info * Integrale_tps_produit_champs::info () static
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
mettre_a_jour()
void Integrale_tps_produit_champs::mettre_a_jour (double) inline override virtual
Reimplemented from Integrale_tps_Champ.
Definition at line 95 of file Integrale_tps_produit_champs.h.
{
  mettre_a_jour_integrale();
  Champ espace_stockage_source;
  const Champ_base& source = mon_champ->get_champ(espace_stockage_source);
  changer_temps(source.temps());
}
References Champ_Fonc::changer_temps(), Champ_Generique_base::get_champ(), mettre_a_jour_integrale(), Integrale_tps_Champ::mon_champ, and Champ_base::temps().
Referenced by Op_Correlation::mettre_a_jour().
mettre_a_jour_integrale()
void Integrale_tps_produit_champs::mettre_a_jour_integrale () override virtual
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du
champ associe et poursuit l'integration jusqu'au temps courant.
si la borne superieure de l'integrale n'est pas depassee.
Reimplemented from Integrale_tps_Champ.
Definition at line 53 of file Integrale_tps_produit_champs.cpp.
{
  Champ espace_stockage_source,espace_stockage_source2;
  const Champ_base& source = mon_premier_champ()->get_champ(espace_stockage_source);
  const Champ_base& source2 = mon_second_champ()->get_champ(espace_stockage_source2);
  const Noms nom = mon_premier_champ()->get_property("nom");
  const Noms nom2 = mon_second_champ()->get_property("nom");
  double t_courant = mon_premier_champ()->get_time();
  if (t_courant != mon_second_champ()->get_time())
    {
      Cerr << "Integrale_tps_produit_champs::mettre_a_jour_integrale()" << finl;
      Cerr << "the current time of the field named " << nom[0] << " =" << t_courant << finl;
      Cerr << "is different of the second field current time " << nom2[0] << " =" <<  source2.temps() << finl;
      exit();
    }
  if (t_fin_ < t_debut_)
    {
      Cerr << " Statistics begining and ending times are not coherent " << finl;
      Cerr << " t_fin_=" << t_fin_ << " < t_debut_=" << t_debut_ << finl;
      exit();
    }
  if ( inf_ou_egal(t_debut_ ,t_courant) &&  inf_ou_egal(t_courant,t_fin_) )
    {
      double dt = t_courant - tps_integrale;
      if (dt > 0)
        {
// DoubleTab& mes_val = valeurs();
          if (premiere_puissance() == 1 && seconde_puissance() == 1)
            {
//
              ajoute_produit_tensoriel(dt, source, source2);
            }
          else
            {
              Cerr << "Integrale_tps_produit_champs::mettre_a_jour_integrale() : case not coded." << finl;
            }
          tps_integrale = t_courant;
          dt_integr_calcul += dt;
        }
    }
}
References ajoute_produit_tensoriel(), Cerr, Integrale_tps_Champ::dt_integr_calcul, Process::exit(), finl, Champ_Generique_base::get_champ(), Champ_Generique_base::get_property(), Champ_Generique_base::get_time(), inf_ou_egal(), mon_premier_champ(), mon_second_champ(), premiere_puissance(), seconde_puissance(), Integrale_tps_Champ::t_debut_, Integrale_tps_Champ::t_fin_, Champ_base::temps(), and Integrale_tps_Champ::tps_integrale.
Referenced by mettre_a_jour().
mon_premier_champ()
const Ref_Champ_Generique_base & Integrale_tps_produit_champs::mon_premier_champ () const inline
Definition at line 38 of file Integrale_tps_produit_champs.h.
  {
    return mon_champ;
  };
References Integrale_tps_Champ::mon_champ.
Referenced by mettre_a_jour_integrale().
mon_second_champ()
const Ref_Champ_Generique_base & Integrale_tps_produit_champs::mon_second_champ () const inline
Definition at line 42 of file Integrale_tps_produit_champs.h.
  {
    return mon_second_champ_;
  };
References mon_second_champ_.
Referenced by mettre_a_jour_integrale().
premiere_puissance()
int Integrale_tps_produit_champs::premiere_puissance () const inline
Definition at line 46 of file Integrale_tps_produit_champs.h.
  {
    return puissance;
  }
References Integrale_tps_Champ::puissance.
Referenced by mettre_a_jour_integrale().
printOn()
Sortie & Integrale_tps_produit_champs::printOn (Sortie & s) const override protected virtual
Ecriture d'un Champ_Fonc sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Integrale_tps_Champ.
Definition at line 24 of file Integrale_tps_produit_champs.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Integrale_tps_produit_champs::readOn (Entree & s) override protected virtual
Lecture d'un Champ_Fonc sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Integrale_tps_Champ.
Definition at line 32 of file Integrale_tps_produit_champs.cpp.
{
  return s ;
}
seconde_puissance()
int Integrale_tps_produit_champs::seconde_puissance () const inline
Definition at line 50 of file Integrale_tps_produit_champs.h.
  {
    return seconde_puissance_;
  }
References seconde_puissance_.
Referenced by mettre_a_jour_integrale().
self_cast() [1/2]
const Integrale_tps_produit_champs & Integrale_tps_produit_champs::self_cast (const Objet_U & r) static
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
self_cast() [2/2]
Integrale_tps_produit_champs & Integrale_tps_produit_champs::self_cast (Objet_U & r) static
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
support_different()
int & Integrale_tps_produit_champs::support_different () inline
Definition at line 58 of file Integrale_tps_produit_champs.h.
  {
    return support_different_;
  };
References support_different_.
Referenced by Op_Correlation::completer().
taille_memoire()
unsigned Integrale_tps_produit_champs::taille_memoire () const override virtual
Reimplemented from Integrale_tps_Champ.
Definition at line 20 of file Integrale_tps_produit_champs.cpp.
Member Data Documentation
info_obj
const Type_info Integrale_tps_produit_champs::info_obj static
Definition at line 35 of file Integrale_tps_produit_champs.h.
mon_second_champ_
Ref_Champ_Generique_base Integrale_tps_produit_champs::mon_second_champ_ protected
Definition at line 69 of file Integrale_tps_produit_champs.h.
Referenced by associer(), and mon_second_champ().
seconde_puissance_
int Integrale_tps_produit_champs::seconde_puissance_ protected
Definition at line 70 of file Integrale_tps_produit_champs.h.
Referenced by associer(), and seconde_puissance().
support_different_
int Integrale_tps_produit_champs::support_different_ protected
Definition at line 71 of file Integrale_tps_produit_champs.h.
Referenced by ajoute_produit_tensoriel(), get_support_different(), and support_different().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Integrale_tps_produit_champs.h
src/Kernel/Statistiques_temps/Integrale_tps_produit_champs.cpp