TRUST: Interpolation_IBM_elem_fluid Class Reference
Interpolation_IBM_elem_fluid Class Reference
: class Interpolation_IBM_elem_fluid
<Description of class Interpolation_IBM_elem_fluid>
#include <Interpolation_IBM_elem_fluid.h>
Public Member Functions
Interpolation_IBM_elem_fluid ()
~Interpolation_IBM_elem_fluid ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretise (const Discretisation_base &, Zone_dis_base &la_zone_EF) override
Public Member Functions inherited from Interpolation_IBM_base
Interpolation_IBM_base ()
~Interpolation_IBM_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void discretise (const Discretisation_base &, Zone_dis_base &)
double get_impr ()
void set_param (Param &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interpolation_IBM_elem_fluid & self_cast (Objet_U &)
static const Interpolation_IBM_elem_fluid & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interpolation_IBM_base
static const Type_info * info ()
static Interpolation_IBM_base & self_cast (Objet_U &)
static const Interpolation_IBM_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interpolation_IBM_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual void computeFluidElems (Zone_dis_base &)
void set_param (Param &)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don fluid_points_lu_
Champ_Don fluid_points_
Champ_Don fluid_elems_lu_
Champ_Don fluid_elems_
Protected Attributes inherited from Interpolation_IBM_base
Champ_Don solid_points_lu_
Champ_Don solid_points_
Champ_Don corresp_elems_lu_
Champ_Don corresp_elems_
int impr_ =0
Default value.
Friends
class Source_PDF_EF
Detailed Description
: class Interpolation_IBM_elem_fluid
<Description of class Interpolation_IBM_elem_fluid>
Definition at line 30 of file Interpolation_IBM_elem_fluid.h.
Constructor & Destructor Documentation
Interpolation_IBM_elem_fluid()
Interpolation_IBM_elem_fluid::Interpolation_IBM_elem_fluid ()
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
~Interpolation_IBM_elem_fluid()
Interpolation_IBM_elem_fluid::~Interpolation_IBM_elem_fluid ()
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
Member Function Documentation
computeFluidElems()
void Interpolation_IBM_elem_fluid::computeFluidElems (Zone_dis_base & la_zone_EF) protected virtual
Definition at line 67 of file Interpolation_IBM_elem_fluid.cpp.
{
  double eps = 1e-12;
  int nb_som = la_zone_EF.nb_som();
  int nb_som_tot = la_zone_EF.nb_som_tot();
  int nb_elem = la_zone_EF.nb_elem();
  int nb_elem_tot = la_zone_EF.nb_elem_tot();
  const DoubleTab& coordsDom = la_zone_EF.zone().domaine().coord_sommets();
// const IntTab& elems = la_zone_EF.zone().les_elems();
  DoubleTab& elems_fluid_ref = fluid_elems_.valeur().valeurs();
  DoubleTab& fluid_points_ref = fluid_points_.valeur().valeurs();
  DoubleTab& solid_points_ref = solid_points_.valeur().valeurs();
// La numerotation des elements peut avoir changee entre l'etape pre_pro et
// l'etape calcul (cas du pre_pro Salome)
// On utilise un champ d'etiquette pour fluid_elems_ (par exemple le no elem Salome)
// et un champ d'element reprenant ces etiquettes
  if ((&corresp_elems_)->non_nul())
    {
      DoubleTab& corresp_elems_ref = corresp_elems_.valeur().valeurs();
      int nb_tag_max = -1;
      for (int i = 0 ; i < nb_elem_tot ; i++)
        {
          int int_cor_elem = lrint(corresp_elems_ref(i));
          if (int_cor_elem > nb_tag_max) nb_tag_max = int_cor_elem;
        }
      int dimtag = nb_tag_max+1;
      DoubleTrav elems_fluid_trust(dimtag);
      elems_fluid_trust = -1.e+10;
      for (int i = 0 ; i < nb_elem_tot ; i++)
        {
          int indextag = lrint(corresp_elems_ref(i)) ;
// Cerr << indextag << ", " << dimtag << ", " << nb_elem << ", " << nb_elem_tot << ", " << nb_som << ", " << nb_som_tot << finl;
// abort();
          if (indextag < dimtag && indextag >= 0)
            {
              elems_fluid_trust(indextag) = i*1.0;
            }
          else
            {
              Cerr<<"erreur in computeFluidElems : elem corresp_elems_ref(elem) = "<<i<<" "<<corresp_elems_ref(i)<<" ; indextag = "<<indextag<<" < 0 ou >= "<<dimtag<<finl;
              exit();
            }
        }
      for (int i = 0 ; i < nb_som ; i++)
        {
          if (elems_fluid_ref(i) >= 0.0)
            {
              int indexr = lrint(elems_fluid_ref(i));
              if (indexr < dimtag && indexr >= 0)
                {
                  if (elems_fluid_trust(indexr) >= 0.)
                    {
                      elems_fluid_ref(i) = elems_fluid_trust(indexr);
                    }
                  else
                    {
                      double x = fluid_points_ref(i,0);
                      double y = fluid_points_ref(i,1);
                      double z = fluid_points_ref(i,2);
                      double xs = solid_points_ref(i,0);
                      double ys = solid_points_ref(i,1);
                      double zs = solid_points_ref(i,2);
                      double d = (x-xs)*(x-xs)+(y-ys)*(y-ys)+(z-zs)*(z-zs);
                      if (d < eps)
// A ne pas considerer si points fluide et solide sont confondus (erreur prepro)
{
                          elems_fluid_ref(i) = elems_fluid_trust(indexr);
                        }
                      else
{
                          Cerr << __FILE__ << (int)__LINE__ << "Interpolation_IBM_elem_fluid::computeFluidElems : ERROR : joint width too low?" << finl;
                          Cerr<<"node elems_fluid_ref(node) index = "<<i<<" "<<elems_fluid_ref(i)<<" "<<indexr<<finl;
                          Cerr<<"elems_fluid_trust(index) < 0. = "<<elems_fluid_trust(indexr)<<finl;
                          Cerr<<"nb som som_tot elem elem_tot = "<<nb_som<<" "<<nb_som_tot<<" "<<nb_elem<<" "<<nb_elem_tot<<finl;
                          Cerr<<"coords_point(node) : x y z    = "<<coordsDom(i,0)<<" "<<coordsDom(i,1)<<" "<<coordsDom(i,2)<<finl;
                          Cerr<<"fluid_points(node) : xf yf zf = "<<x<<" "<<y<<" "<<z<<finl;
                          Cerr<<"solid_points(node) : xs ys zs = "<<xs<<" "<<ys<<" "<<zs<<finl;
                          int elem_found = la_zone_EF.zone().chercher_elements(x,y,z);
                          Cerr<<"chercher_elements(xf,yf,zf) = "<<elem_found<<finl;
                          exit();
                        }
                    }
                }
              else
                {
                  Cerr << __FILE__ << (int)__LINE__ << "Interpolation_IBM_elem_fluid::computeFluidElems : ERROR : joint width too low?" << finl;
                  Cerr<<"node elems_fluid_ref(node) = "<<i<<" "<<elems_fluid_ref(i)<<finl;
                  Cerr<<"index = "<<indexr<<" < 0 ou >= "<<dimtag<<finl;
                  exit();
                }
            }
        }
    }
}
References Cerr, Zone::chercher_elements(), Domaine::coord_sommets(), Interpolation_IBM_base::corresp_elems_, Zone::domaine(), Process::exit(), finl, fluid_elems_, fluid_points_, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som(), Zone_dis_base::nb_som_tot(), Interpolation_IBM_base::solid_points_, Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), and Zone_dis_base::zone().
Referenced by discretise().
cree_instance()
Objet_U * Interpolation_IBM_elem_fluid::cree_instance () static
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
discretise()
void Interpolation_IBM_elem_fluid::discretise (const Discretisation_base & dis, Zone_dis_base & la_zone_EF) override virtual
Reimplemented from Interpolation_IBM_base.
Reimplemented in Interpolation_IBM_hybrid.
Definition at line 47 of file Interpolation_IBM_elem_fluid.cpp.
{
  int nb_comp = Objet_U::dimension;
  Noms units(nb_comp);
  Noms c_nam(nb_comp);
  dis.discretiser_champ("champ_sommets",la_zone_EF,"fluid_elems","none",1,0., fluid_elems_);
  fluid_elems_.valeur().affecter(fluid_elems_lu_);
  if ((&corresp_elems_lu_)->non_nul())
    {
      dis.discretiser_champ("champ_elem",la_zone_EF,"corresp_elems","none",1,0., corresp_elems_);
      corresp_elems_.valeur().affecter(corresp_elems_lu_);
    }
  dis.discretiser_champ("vitesse",la_zone_EF,vectoriel,c_nam,units,nb_comp,0.,fluid_points_);
  fluid_points_.valeur().affecter(fluid_points_lu_);
  dis.discretiser_champ("vitesse",la_zone_EF,vectoriel,c_nam,units,nb_comp,0.,solid_points_);
  solid_points_.valeur().affecter(solid_points_lu_);
  computeFluidElems(la_zone_EF);
}
References Champ_base::affecter(), computeFluidElems(), Interpolation_IBM_base::corresp_elems_, Interpolation_IBM_base::corresp_elems_lu_, Objet_U::dimension, Discretisation_base::discretiser_champ(), fluid_elems_, fluid_elems_lu_, fluid_points_, fluid_points_lu_, Interpolation_IBM_base::solid_points_, Interpolation_IBM_base::solid_points_lu_, Deriv_Champ_Don_base::valeur(), and vectoriel.
Referenced by Interpolation_IBM_hybrid::discretise().
duplique()
int Interpolation_IBM_elem_fluid::duplique () const override virtual
Implements Objet_U.
Reimplemented in Interpolation_IBM_hybrid, and Interpolation_IBM_power_law_tbl.
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
get_info()
const Type_info * Interpolation_IBM_elem_fluid::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interpolation_IBM_base.
Reimplemented in Interpolation_IBM_hybrid, and Interpolation_IBM_power_law_tbl.
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
info()
const Type_info * Interpolation_IBM_elem_fluid::info () static
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
printOn()
Sortie & Interpolation_IBM_elem_fluid::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interpolation_IBM_base.
Reimplemented in Interpolation_IBM_hybrid, and Interpolation_IBM_power_law_tbl.
Definition at line 24 of file Interpolation_IBM_elem_fluid.cpp.
{
  Interpolation_IBM_base::printOn( os );
  return os;
}
References Interpolation_IBM_base::printOn().
Referenced by Interpolation_IBM_power_law_tbl::printOn().
readOn()
Entree & Interpolation_IBM_elem_fluid::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interpolation_IBM_base.
Reimplemented in Interpolation_IBM_hybrid, and Interpolation_IBM_power_law_tbl.
Definition at line 39 of file Interpolation_IBM_elem_fluid.cpp.
{
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Interpolation_IBM_power_law_tbl::readOn().
self_cast() [1/2]
const Interpolation_IBM_elem_fluid & Interpolation_IBM_elem_fluid::self_cast (const Objet_U & r) static
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
self_cast() [2/2]
Interpolation_IBM_elem_fluid & Interpolation_IBM_elem_fluid::self_cast (Objet_U & r) static
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
set_param()
void Interpolation_IBM_elem_fluid::set_param (Param & param) protected
< XD_ADD_P field_base Node field giving the projection of the point below (points_solides) falling into the pure cell fluid
< XD_ADD_P field_base Node field giving the projection of the node on the immersed boundary
< XD_ADD_P field_base Node field giving the number of the element (cell) containing the pure fluid point
< XD_ADD_P field_base Cell field giving the SALOME cell number
Definition at line 30 of file Interpolation_IBM_elem_fluid.cpp.
{
  Interpolation_IBM_base::set_param(param);
  param.ajouter("points_fluides",&fluid_points_lu_,Param::REQUIRED); //!< XD_ADD_P field_base Node field giving the projection of the point below (points_solides) falling into the pure cell fluid
  param.ajouter("points_solides",&solid_points_lu_,Param::REQUIRED); //!< XD_ADD_P field_base Node field giving the projection of the node on the immersed boundary
  param.ajouter("elements_fluides",&fluid_elems_lu_,Param::REQUIRED);   //!< XD_ADD_P field_base Node field giving the number of the element (cell) containing the pure fluid point
  param.ajouter("correspondance_elements",&corresp_elems_lu_,Param::REQUIRED);   //!< XD_ADD_P field_base Cell field giving the SALOME cell number
}
References Param::ajouter(), Interpolation_IBM_base::corresp_elems_lu_, fluid_elems_lu_, fluid_points_lu_, Param::REQUIRED, Interpolation_IBM_base::set_param(), and Interpolation_IBM_base::solid_points_lu_.
Referenced by readOn(), and Interpolation_IBM_hybrid::readOn().
taille_memoire()
unsigned Interpolation_IBM_elem_fluid::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Interpolation_IBM_hybrid, and Interpolation_IBM_power_law_tbl.
Definition at line 21 of file Interpolation_IBM_elem_fluid.cpp.
Friends And Related Function Documentation
Source_PDF_EF
friend class Source_PDF_EF friend
Definition at line 48 of file Interpolation_IBM_elem_fluid.h.
Member Data Documentation
fluid_elems_
Champ_Don Interpolation_IBM_elem_fluid::fluid_elems_ protected
Definition at line 46 of file Interpolation_IBM_elem_fluid.h.
Referenced by Source_PDF_EF::associer_pb(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), computeFluidElems(), and discretise().
fluid_elems_lu_
Champ_Don Interpolation_IBM_elem_fluid::fluid_elems_lu_ protected
Definition at line 45 of file Interpolation_IBM_elem_fluid.h.
Referenced by discretise(), and set_param().
fluid_points_
Champ_Don Interpolation_IBM_elem_fluid::fluid_points_ protected
Definition at line 43 of file Interpolation_IBM_elem_fluid.h.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), computeFluidElems(), and discretise().
fluid_points_lu_
Champ_Don Interpolation_IBM_elem_fluid::fluid_points_lu_ protected
Definition at line 42 of file Interpolation_IBM_elem_fluid.h.
Referenced by discretise(), and set_param().
info_obj
const Type_info Interpolation_IBM_elem_fluid::info_obj static
Definition at line 33 of file Interpolation_IBM_elem_fluid.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_elem_fluid.h
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_elem_fluid.cpp