TRUST: Terme_Source_Coriolis_VDF_Face Class Reference
Terme_Source_Coriolis_VDF_Face Class Reference
#include <Terme_Source_Coriolis_VDF_Face.h>
Public Member Functions
Terme_Source_Coriolis_VDF_Face ()
~Terme_Source_Coriolis_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
const DoubleVect & omega () const
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Coriolis
void associer_eqn (const Navier_Stokes_std &)
const DoubleVect & omega () const
const Navier_Stokes_std & eq_hydraulique () const
void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Coriolis_VDF_Face & self_cast (Objet_U &)
static const Terme_Source_Coriolis_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void calculer_force_de_Coriolis () const
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Terme_Source_Coriolis
Entree & lire_donnees (Entree &)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
DoubleTab la_source
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Coriolis
DoubleVect omega_
Ref_Navier_Stokes_std eq_hydraulique_
double dim
Detailed Description
Definition at line 36 of file Terme_Source_Coriolis_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Coriolis_VDF_Face()
Terme_Source_Coriolis_VDF_Face::Terme_Source_Coriolis_VDF_Face ()
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
~Terme_Source_Coriolis_VDF_Face()
Terme_Source_Coriolis_VDF_Face::~Terme_Source_Coriolis_VDF_Face ()
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Coriolis_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 93 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const Zone_Cl_VDF& zone_Cl_VDF = la_zone_Cl_VDF.valeur();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntVect& orientation = zone_VDF.orientation();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  int ndeb,nfin,ncomp,num_face,num_elem;
  double vol;
  calculer_force_de_Coriolis();
// Boucle sur les conditions limites pour traiter les faces de bord
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet ou de Symetrie on ne fait rien
// Si face de Neumann on calcule la contribution au terme source
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
// const Neumann_sortie_libre& la_cl_neumann = ref_cast(Neumann_sortie_libre,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              ncomp = orientation(num_face);
              num_elem = face_voisins(num_face,0);
              if (num_elem == -1)
                num_elem = face_voisins(num_face,1);
              secmem(num_face)+= la_source(num_elem,ncomp)*vol;
            }
        }
      else if (sub_type(Symetrie,la_cl.valeur()))
        ;
      else if ( (sub_type(Dirichlet,la_cl.valeur()))
                ||
                (sub_type(Dirichlet_homogene,la_cl.valeur()))
              )
        ;
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              ncomp = orientation(num_face);
              secmem(num_face)+= 0.5*(la_source(face_voisins(num_face,0),ncomp)
                                      +la_source(face_voisins(num_face,1),ncomp))*vol;
            }
        }
    }
// Boucle sur les faces internes
  ndeb = zone_VDF.premiere_face_int();
  for (num_face =zone_VDF.premiere_face_int(); num_face<zone_VDF.nb_faces(); num_face++)
    {
      vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
      ncomp = orientation(num_face);
      secmem(num_face)+= 0.5*(la_source(face_voisins(num_face,0),ncomp)+
                              la_source(face_voisins(num_face,1),ncomp))*vol;
    }
}
References calculer_force_de_Coriolis(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), la_source, la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
associer_pb()
void Terme_Source_Coriolis_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 65 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  if (sub_type(Pb_Fluide_base,pb))
    {
      const Navier_Stokes_std& eqn_th = ref_cast(Navier_Stokes_std,pb.equation(0));
      Terme_Source_Coriolis::associer_eqn(eqn_th);
    }
  else
    {
      Cerr << "Error for the method Terme_Source_Coriolis_VDF_Face::associer_pb" << finl;
      Cerr << "The source term "<<que_suis_je()<<" cannot be activated for the problem "<<pb.que_suis_je()<< finl;
      exit();
    }
  la_source.resize(0,dimension);
  la_zone_VDF.valeur().zone().creer_tableau_elements(la_source);
}
References Terme_Source_Coriolis::associer_eqn(), Cerr, Zone::creer_tableau_elements(), Objet_U::dimension, Probleme_base::equation(), Process::exit(), finl, la_source, la_zone_VDF, Objet_U::que_suis_je(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
associer_zones()
void Terme_Source_Coriolis_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 84 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Source_Coriolis_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 176 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References Source_base::ajouter().
calculer_force_de_Coriolis()
void Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis () const protected
Definition at line 182 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
// On calcule la force de Coriolis par element (maillage entrelace!)
// On se ramenera aux faces dans le ajouter
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleTab& vitesse = eq_hydraulique().inconnue().valeurs();
// int nb_faces = zone_VDF.nb_faces();
  const int nb_elems =  eq_hydraulique().zone_dis().zone().nb_elem();
  const IntTab& elem_faces = zone_VDF.elem_faces();
// const IntTab& face_voisins = zone_VDF.face_voisins();
  DoubleVect om = omega();
  int num_elem,i;
  DoubleVect vit(dimension);
  DoubleTab& la_source_ = ref_cast_non_const(DoubleTab, la_source);
  switch(dimension)
    {
    case 2:
      {
        for (num_elem=0; num_elem <nb_elems; num_elem++)
          {
            for (i=0; i<dimension; i++)
              vit[i] = 0.5*(vitesse(elem_faces(num_elem,i))+vitesse(elem_faces(num_elem,i+dimension)));
            la_source_(num_elem,0)= 2.*om(0)*vit[1];
            la_source_(num_elem,1)=-2.*om(0)*vit[0];
          }
        break;
      }
    case 3:
      {
        for (num_elem=0; num_elem <nb_elems; num_elem++)
          {
            for (i=0; i<dimension; i++)
              vit[i] = 0.5*(vitesse(elem_faces(num_elem,i))+vitesse(elem_faces(num_elem,i+dimension)));
            la_source_(num_elem,0)=-2.*(om(1)*vit[2]-om(2)*vit[1]);
            la_source_(num_elem,1)=-2.*(om(2)*vit[0]-om(0)*vit[2]);
            la_source_(num_elem,2)=-2.*(om(0)*vit[1]-om(1)*vit[0]);
          }
        break;
      }
    default:
      {
        Cerr << "Pour pouvoir utiliser la force de Coriolis, il faut etre en 2D ou 3D" << finl;
        exit();
      }
    }
  if (eq_hydraulique().milieu().que_suis_je()=="Fluide_Weakly_Compressible")
    {
      Cerr << "Terme_Source_Coriolis_VDF_Face is not yet tested for a Weakly Compressible fluid !" << finl;
      Cerr << "Contact the TRUST support if you want to use this source term." << finl;
      Process::exit();
    }
// Si l'on est en Quasi Compressible, le terme source doit etre
// multiplie par la masse volumique puisque c'est sous cette forme
// qu'est ecrite l'equation de NS.
  const Probleme_base& pb = eq_hydraulique().probleme();
  if(pb.is_dilatable())
    {
      const Fluide_Dilatable_base& le_fluide = ref_cast(Fluide_Dilatable_base,eq_hydraulique().milieu());
      const DoubleTab& tab_rho_elem = le_fluide.masse_volumique().valeurs();
      double rhoelem;
      for (num_elem=0; num_elem <nb_elems; num_elem++)
        {
          rhoelem=tab_rho_elem[num_elem];
          for (i=0; i<dimension; i++)
            la_source_(num_elem,i)*=rhoelem;
        }
    }
  la_source_.echange_espace_virtuel();
}
References Cerr, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Terme_Source_Coriolis::eq_hydraulique(), Process::exit(), finl, Navier_Stokes_std::inconnue(), Probleme_base::is_dilatable(), la_source, la_zone_VDF, Milieu_base::masse_volumique(), Zone::nb_elem(), omega(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, ref_cast_non_const, Ref_Zone_VDF::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), Zone_dis::zone(), and Equation_base::zone_dis().
Referenced by ajouter_blocs().
cree_instance()
Objet_U * Terme_Source_Coriolis_VDF_Face::cree_instance () static
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
dimensionner_blocs()
void Terme_Source_Coriolis_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 49 of file Terme_Source_Coriolis_VDF_Face.h.
{}
duplique()
int Terme_Source_Coriolis_VDF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Terme_Source_Coriolis_QC_VDF_Face.
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
get_info()
const Type_info * Terme_Source_Coriolis_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_QC_VDF_Face.
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
has_interface_blocs()
int Terme_Source_Coriolis_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 51 of file Terme_Source_Coriolis_VDF_Face.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Coriolis_VDF_Face::info () static
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
mettre_a_jour()
void Terme_Source_Coriolis_VDF_Face::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_Coriolis_VDF_Face.h.
  {
    Terme_Source_Coriolis::mettre_a_jour(temps);
  }
References Terme_Source_Coriolis::mettre_a_jour().
omega()
const DoubleVect & Terme_Source_Coriolis_VDF_Face::omega () const inline
Definition at line 75 of file Terme_Source_Coriolis_VDF_Face.h.
{
  return Terme_Source_Coriolis::omega();
}
References Terme_Source_Coriolis::omega().
Referenced by calculer_force_de_Coriolis().
printOn()
Sortie & Terme_Source_Coriolis_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_QC_VDF_Face.
Definition at line 51 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Coriolis_VDF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_QC_VDF_Face.
Definition at line 60 of file Terme_Source_Coriolis_VDF_Face.cpp.
{
  return Terme_Source_Coriolis::lire_donnees(s);
}
References Terme_Source_Coriolis::lire_donnees().
self_cast() [1/2]
const Terme_Source_Coriolis_VDF_Face & Terme_Source_Coriolis_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
self_cast() [2/2]
Terme_Source_Coriolis_VDF_Face & Terme_Source_Coriolis_VDF_Face::self_cast (Objet_U & r) static
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Coriolis_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Terme_Source_Coriolis_QC_VDF_Face.
Definition at line 46 of file Terme_Source_Coriolis_VDF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Terme_Source_Coriolis_VDF_Face::info_obj static
Definition at line 38 of file Terme_Source_Coriolis_VDF_Face.h.
la_source
DoubleTab Terme_Source_Coriolis_VDF_Face::la_source protected
Definition at line 60 of file Terme_Source_Coriolis_VDF_Face.h.
Referenced by ajouter_blocs(), associer_pb(), and calculer_force_de_Coriolis().
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Source_Coriolis_VDF_Face::la_zone_Cl_VDF protected
Definition at line 59 of file Terme_Source_Coriolis_VDF_Face.h.
Referenced by ajouter_blocs(), and associer_zones().
la_zone_VDF
Ref_Zone_VDF Terme_Source_Coriolis_VDF_Face::la_zone_VDF protected
Definition at line 58 of file Terme_Source_Coriolis_VDF_Face.h.
Referenced by ajouter_blocs(), associer_pb(), associer_zones(), and calculer_force_de_Coriolis().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Coriolis_VDF_Face.h
src/VDF/Sources/Terme_Source_Coriolis_VDF_Face.cpp