TRUST: PolyMAC_P0_discretisation Class Reference
PolyMAC_P0_discretisation Class Reference
class PolyMAC_P0_discretisation (schema de base)
Classe qui gere la dicretisation PolyMAC_P0 du probleme
c'est ici que :
* l'on discretise les proprietes physiques du fluide et notamment celui du fluide
d'Ostwald(K, N, Mu, ...)
* l'on associe le champ d'Ostwald et l'equation hydraulique, le fluide et la
zone_dis_base
** (nouvelles procedures :
void proprietes_physiques_fluide_Ostwald(Zone_dis& ,Fluide_Ostwald& ,
const Navier_Stokes_std& , const Champ_Inc&) const;
a besoin de la classe Fluide_Ostwald pour avoir acces au fluide etudie
Navier_Stokes_Std pour avoir acces a l'equation hydraulique
#include <PolyMAC_P0_discretisation.h>
Public Member Functions
PolyMAC_P0_discretisation ()
~PolyMAC_P0_discretisation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void grad_u (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &ch_vitesse, Champ_Fonc &ch) const override
void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const override
void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Public Member Functions inherited from PolyMAC_discretisation
PolyMAC_discretisation ()
~PolyMAC_discretisation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const override
Discretisation d'un champ pour le PolyMAC en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s) et nature du champ) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const override
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const override
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
void zone_Cl_dis (Zone_dis &z, Zone_Cl_dis &zcl) const override
void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const override
void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const override
discretise en PolyMAC le fluide incompressible, donc K e N
void residu (const Zone_dis &z, const Champ_Inc &ch_inco, Champ_Fonc &champ) const override
void vorticite (Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void critere_Q (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void y_plus (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const override
void grad_T (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch) const override
void grad_u (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &ch_vitesse, Champ_Fonc &ch) const override
void h_conv (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch, Motcle &nom, int temp_ref) const override
type_calcul_du_residu codage_du_calcul_du_residu (void) const override
Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operateur, const Equation_base &eqn, const Ref_Champ_base &champ_sup) const override
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Discret_Thyd
Discret_Thyd ()
~Discret_Thyd () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void vitesse (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void translation (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void entcor (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void pression (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void pression_en_pa (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void divergence_U (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void gradient_P (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void concentration (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int=1, const Nom nom_champ="concentration") const
void porosite_volumique (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void diametre_hydraulique_elem (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void diametre_hydraulique_face (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void section_passage (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
virtual void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void grad_u (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
virtual void y_plus (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void grad_T (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch) const
virtual void h_conv (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch, Motcle &nom, int temp_ref) const
virtual void critere_Q (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void reynolds_maille (const Zone_dis &, const Fluide_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void courant_maille (const Zone_dis &, const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void estimateur_aposteriori (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, const Champ_Inc &, const Champ_Don &, Champ_Fonc &) const
virtual void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
Public Member Functions inherited from Discret_Thermique
Discret_Thermique ()
~Discret_Thermique () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void flux_neutronique (const Schema_Temps_base &sch, Zone_dis &z, Champ_Inc &ch, int nb_comp=1) const
void Fluctu_Temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void Flux_Chaleur_Turb (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
Public Member Functions inherited from Discretisation_base
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static PolyMAC_P0_discretisation & self_cast (Objet_U &)
static const PolyMAC_P0_discretisation & self_cast (const Objet_U &)
Static Public Member Functions inherited from PolyMAC_discretisation
static Objet_U * cree_instance ()
static const Type_info * info ()
static PolyMAC_discretisation & self_cast (Objet_U &)
static const PolyMAC_discretisation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thyd
static const Type_info * info ()
static Discret_Thyd & self_cast (Objet_U &)
static const Discret_Thyd & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thermique
static const Type_info * info ()
static Discret_Thermique & self_cast (Objet_U &)
static const Discret_Thermique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discretisation_base
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from PolyMAC_discretisation
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thyd
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thermique
static const Type_info info_obj
Static Public Attributes inherited from Discretisation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Discret_Thyd
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Objet_U &champ) const
Additional Inherited Members
Public Types inherited from Discretisation_base
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Static Protected Attributes inherited from Discretisation_base
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Detailed Description
class PolyMAC_P0_discretisation (schema de base)
Classe qui gere la dicretisation PolyMAC_P0 du probleme
c'est ici que :
* l'on discretise les proprietes physiques du fluide et notamment celui du fluide
d'Ostwald(K, N, Mu, ...)
* l'on associe le champ d'Ostwald et l'equation hydraulique, le fluide et la
zone_dis_base
** (nouvelles procedures :
void proprietes_physiques_fluide_Ostwald(Zone_dis& ,Fluide_Ostwald& ,
const Navier_Stokes_std& , const Champ_Inc&) const;
a besoin de la classe Fluide_Ostwald pour avoir acces au fluide etudie
Navier_Stokes_Std pour avoir acces a l'equation hydraulique
Definition at line 37 of file PolyMAC_P0_discretisation.h.
Constructor & Destructor Documentation
PolyMAC_P0_discretisation()
PolyMAC_P0_discretisation::PolyMAC_P0_discretisation ()
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
~PolyMAC_P0_discretisation()
PolyMAC_P0_discretisation::~PolyMAC_P0_discretisation ()
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
Member Function Documentation
cree_instance()
Objet_U * PolyMAC_P0_discretisation::cree_instance () static
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
creer_champ_vorticite()
void PolyMAC_P0_discretisation::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
< so it is calculated at time 0
Reimplemented from PolyMAC_discretisation.
Definition at line 109 of file PolyMAC_P0_discretisation.cpp.
{
  const Champ_Face_PolyMAC_P0&     vit = ref_cast(Champ_Face_PolyMAC_P0,ch_vitesse.valeur());
  const Zone_PolyMAC_P0&          zone = ref_cast(Zone_PolyMAC_P0, vit.zone_dis_base());
  int N = vit.valeurs().line_size();
  ch.typer("Champ_Fonc_Elem_PolyMAC_P0_rot");
  Champ_Fonc_Elem_PolyMAC_P0_rot&  ch_rot_u = ref_cast(Champ_Fonc_Elem_PolyMAC_P0_rot,ch.valeur());
  ch_rot_u.associer_zone_dis_base(zone);
  ch_rot_u.associer_champ(vit);
  ch_rot_u.nommer("vorticite");
  if (dimension == 2)
    {
      ch_rot_u.fixer_nb_comp(N);
      ch_rot_u.fixer_nature_du_champ(scalaire);
    }
  else if (dimension == 3)
    {
      ch_rot_u.fixer_nb_comp(dimension * N);
      ch_rot_u.fixer_nature_du_champ(vectoriel);
    }
  else abort();
  ch_rot_u.fixer_nb_valeurs_nodales(zone.nb_elem());
  ch_rot_u.fixer_unite("s-1");
  ch_rot_u.changer_temps(-1); //!< so it is calculated at time 0
}
References Process::abort(), Champ_Fonc_Elem_PolyMAC_P0_rot::associer_champ(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, scalaire, Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), vectoriel, and Champ_Face_PolyMAC::zone_dis_base().
discretiser_champ_fonc_don()
void PolyMAC_P0_discretisation::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Objet_U & champ) const private
duplique()
int PolyMAC_P0_discretisation::duplique () const override virtual
Reimplemented from PolyMAC_discretisation.
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
get_info()
const Type_info * PolyMAC_P0_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from PolyMAC_discretisation.
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
grad_u()
void PolyMAC_P0_discretisation::grad_u (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const override virtual
< dU
< dV
< dU
< dV
< dW
< tensoriel pour etre precis
< so it is calculated at time 0
Reimplemented from PolyMAC_discretisation.
Definition at line 52 of file PolyMAC_P0_discretisation.cpp.
{
  const Champ_Face_PolyMAC_P0&          vit = ref_cast(Champ_Face_PolyMAC_P0,ch_vitesse.valeur());
  const Zone_PolyMAC_P0&          zone_poly = ref_cast(Zone_PolyMAC_P0, z.valeur());
  const Zone_Cl_PolyMAC&    zone_cl_poly = ref_cast(Zone_Cl_PolyMAC, zcl.valeur());
  ch.typer("grad_Champ_Face_PolyMAC_P0");
  grad_Champ_Face_PolyMAC_P0&   ch_grad_u = ref_cast(grad_Champ_Face_PolyMAC_P0,ch.valeur()); //
  ch_grad_u.associer_zone_dis_base(zone_poly);
  ch_grad_u.associer_zone_Cl_dis_base(zone_cl_poly);
  ch_grad_u.associer_champ(vit);
  ch_grad_u.nommer("gradient_vitesse");
  ch_grad_u.fixer_nb_comp(dimension * dimension * vit.valeurs().line_size());
  for (int n = 0; n<ch_grad_u.valeurs().line_size(); n++)
    {
      Nom phase   = Nom(n);
      if (dimension == 2)
        {
          ch_grad_u.fixer_nom_compo(dimension*n+0,Nom("dU_")+phase); //!< dU
          ch_grad_u.fixer_nom_compo(dimension*n+1,Nom("dV_")+phase); //!< dV
        }
      else
        {
          ch_grad_u.fixer_nom_compo(dimension*n+0,Nom("dU_")+phase); //!< dU
          ch_grad_u.fixer_nom_compo(dimension*n+1,Nom("dV_")+phase); //!< dV
          ch_grad_u.fixer_nom_compo(dimension*n+2,Nom("dW_")+phase); //!< dW
        }
    }
  ch_grad_u.fixer_nature_du_champ(multi_scalaire); //!< tensoriel pour etre precis
  ch_grad_u.fixer_nb_valeurs_nodales(-1);
  ch_grad_u.fixer_unite("s-1");
  ch_grad_u.changer_temps(-1); //!< so it is calculated at time 0
}
References grad_Champ_Face_PolyMAC_P0::associer_champ(), grad_Champ_Face_PolyMAC_P0::associer_zone_Cl_dis_base(), Champ_Fonc_Face_PolyMAC::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_ >::line_size(), multi_scalaire, Field_base::nommer(), ref_cast, Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
info()
const Type_info * PolyMAC_P0_discretisation::info () static
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
printOn()
Sortie & PolyMAC_P0_discretisation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from PolyMAC_discretisation.
Definition at line 47 of file PolyMAC_P0_discretisation.cpp.
{
  return s ;
}
readOn()
Entree & PolyMAC_P0_discretisation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from PolyMAC_discretisation.
Definition at line 42 of file PolyMAC_P0_discretisation.cpp.
{
  return s ;
}
self_cast() [1/2]
const PolyMAC_P0_discretisation & PolyMAC_P0_discretisation::self_cast (const Objet_U & r) static
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
self_cast() [2/2]
PolyMAC_P0_discretisation & PolyMAC_P0_discretisation::self_cast (Objet_U & r) static
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
taille_memoire()
unsigned PolyMAC_P0_discretisation::taille_memoire () const override virtual
Reimplemented from PolyMAC_discretisation.
Definition at line 38 of file PolyMAC_P0_discretisation.cpp.
taux_cisaillement()
void PolyMAC_P0_discretisation::taux_cisaillement (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const override virtual
< tensoriel pour etre precis
< so it is calculated at time 0
Reimplemented from Discret_Thyd.
Definition at line 89 of file PolyMAC_P0_discretisation.cpp.
{
  const Champ_Face_PolyMAC_P0&          vit = ref_cast(Champ_Face_PolyMAC_P0,ch_vitesse.valeur());
// const Zone_PolyMAC_P0&          zone_poly = ref_cast(Zone_PolyMAC_P0, z.valeur());
  const Zone_PolyMAC_P0&          zone = ref_cast(Zone_PolyMAC_P0, vit.zone_dis_base());
  ch.typer("Champ_Fonc_Elem_PolyMAC_P0_TC");
  Champ_Fonc_Elem_PolyMAC_P0_TC&   ch_grad_u = ref_cast(Champ_Fonc_Elem_PolyMAC_P0_TC,ch.valeur()); //
  ch_grad_u.associer_zone_dis_base(zone);
  ch_grad_u.associer_champ(vit);
  ch_grad_u.nommer("Taux_cisaillement");
  ch_grad_u.fixer_nb_comp(vit.valeurs().line_size());
  ch_grad_u.fixer_nature_du_champ(scalaire); //!< tensoriel pour etre precis
  ch_grad_u.fixer_nb_valeurs_nodales(zone.nb_elem());
  ch_grad_u.fixer_unite("s-1");
  ch_grad_u.changer_temps(-1); //!< so it is calculated at time 0
}
References Champ_Fonc_Elem_PolyMAC_P0_TC::associer_champ(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, scalaire, Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), and Champ_Face_PolyMAC::zone_dis_base().
Member Data Documentation
info_obj
const Type_info PolyMAC_P0_discretisation::info_obj static
Definition at line 39 of file PolyMAC_P0_discretisation.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/PolyMAC_P0_discretisation.h
src/PolyMAC/Zones/PolyMAC_P0_discretisation.cpp