TRUST: Op_Dift_VEF_Face Class Reference
Op_Dift_VEF_Face Class Reference
class Op_Dift_VEF_Face
#include <Op_Dift_VEF_Face.h>
Public Member Functions
Op_Dift_VEF_Face ()
~Op_Dift_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
double diffusivite (int) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_cl (const DoubleTab &, Matrice_Morse &, const DoubleTab &, const DoubleTab &, const DoubleVect &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleVect &inconnue, DoubleVect &resu, DoubleTab &flux_bords, const DoubleVect &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleTab &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Dift_VEF_base
Op_Dift_VEF_base ()
~Op_Dift_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_borne_locale (DoubleVect &, double, double) const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_VEF_Face & self_cast (Objet_U &)
static const Op_Dift_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_base
static const Type_info * info ()
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Champ_base diffusivite_
DoubleTab grad_
grad DoubleTab grad_transp_;
Protected Attributes inherited from Op_Dift_VEF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_VEF_Face
Definition at line 30 of file Op_Dift_VEF_Face.h.
Constructor & Destructor Documentation
Op_Dift_VEF_Face()
Op_Dift_VEF_Face::Op_Dift_VEF_Face ()
Definition at line 39 of file Op_Dift_VEF_Face.cpp.
:grad_(0) { }
~Op_Dift_VEF_Face()
Op_Dift_VEF_Face::~Op_Dift_VEF_Face ()
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_VEF_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 944 of file Op_Dift_VEF_Face.cpp.
{
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleTab& nu_turb=diffusivite_turbulente()->valeurs();
  const int nb_comp = resu.line_size();
  DoubleTab nu,nu_turb_m;
  DoubleTab tab_inconnue;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  modif_par_porosite_si_flag(nu_turb,nu_turb_m,!marq,porosite_elem);
  const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue,marq,porosite_face);
  const Champ_base& inco = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inco.nature_du_champ();
  assert_espace_virtuel_vect(nu);
  assert_espace_virtuel_vect(inconnue);
  assert_espace_virtuel_vect(nu_turb_m);
  Debog::verifier("Op_Dift_VEF_Face::ajouter nu",nu);
  Debog::verifier("Op_Dift_VEF_Face::ajouter nu_turb",nu_turb_m);
  Debog::verifier("Op_Dift_VEF_Face::ajouter inconnue_org",inconnue_org);
  Debog::verifier("Op_Dift_VEF_Face::ajouter inconnue",inconnue);
  if(nature_champ==scalaire)
    ajouter_cas_scalaire(inconnue, resu, flux_bords_, nu, nu_turb_m, zone_Cl_VEF, zone_VEF);
  else if (nature_champ==vectoriel)
    ajouter_cas_vectoriel(inconnue, resu, flux_bords_, nu, nu_turb_m, zone_Cl_VEF, zone_VEF, nb_comp);
  else if (nature_champ==multi_scalaire)
    ajouter_cas_multi_scalaire(inconnue, resu, flux_bords_, nu, nu_turb_m, zone_Cl_VEF, zone_VEF, nb_comp);
  modifier_flux(*this);
  return resu;
}
References ajouter_cas_multi_scalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), assert_espace_virtuel_vect(), Op_Diff_Turbulent_base::diffusivite_turbulente(), MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), multi_scalaire, Field_base::nature_du_champ(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), scalaire, Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), vectoriel, and Debog::verifier().
Referenced by calculer().
ajouter_cas_multi_scalaire()
void Op_Dift_VEF_Face::ajouter_cas_multi_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, const DoubleTab & nu, const DoubleVect & nu_turb, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
< face reelle
< on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 658 of file Op_Dift_VEF_Face.cpp.
{
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA, d_nu;
  int nb_front=zone_VEF.nb_front_Cl();
// modif pour imprimer les flux sur les bords
  int size_flux_bords=zone_VEF.nb_faces_bord();
  tab_flux_bords.resize(size_flux_bords,nb_comp);
  tab_flux_bords=0.;
// contient -1 si la face n'est pas periodique et numero face_assso sinon
  ArrOfInt marq( zone_VEF.nb_faces_tot());
  marq=-1;
// On traite les faces bord
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              num_face = le_bord.num_face(ind_face);
              marq[num_face]=fac_asso;
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face,kk);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( ( (j= elem_faces(elem,i)) > num_face ) && (j != fac_asso) )
{
                          for (int nc=0; nc<nb_comp; nc++)
{
                              d_nu = nu(elem,nc)+nu_turb(elem);
                              valA = viscA(num_face,j,elem,d_nu);
                              resu(num_face,nc)+=valA*inconnue(j,nc);
                              resu(num_face,nc)-=valA*inconnue(num_face,nc);
                              if(j<nb_faces) //!< face reelle
{
                                  resu(j,nc)+=0.5*valA*inconnue(num_face,nc);
                                  resu(j,nc)-=0.5*valA*inconnue(j,nc);
                                }
                            }
                        }
                    }
                }
            }
        }
      else   //!< on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
//
//
        {
          const DoubleTab& face_normale = zone_VEF.face_normales();
          const DoubleVect& vol = zone_VEF.volumes();
          const Equation_base& my_eqn = zone_Cl_VEF.equation();
          const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
          if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
            {
              const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
              const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
              if (loiparth->use_equivalent_distance())
                {
                  const DoubleVect& d_equiv=loiparth->equivalent_distance(n_bord);
// d_equiv contient la distance equivalente pour le bord
// Dans d_equiv, pour les faces qui ne sont pas paroi_fixe (eg periodique, symetrie, etc...)
// il y a la distance geometrique grace a l'initialisation du tableau dans la loi de paroi.
// Les lois de parois ne s'appliquent qu'aux cas ou la CL
// est de type temperature imposee, car dans les autres cas
// (flux impose et adiabatique) le flux a la paroi est connu et fixe.
                  int nb_dim_pb=Objet_U::dimension;
                  if(sub_type(Scalaire_impose_paroi,la_cl.valeur()))
                    {
                      DoubleVect le_mauvais_gradient(nb_dim_pb);
                      for (int ind_face=num1; ind_face<num2; ind_face++)
{
                          for (int nc=0; nc<nb_comp; nc++)
{
// Tf est la temperature fluide moyenne dans le premier element
// sans tenir compte de la temperature de paroi.
                              double Tf=0.;
                              double bon_gradient=0.; //!< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
                              le_mauvais_gradient=0.;
                              num_face = le_bord.num_face(ind_face);
                              int elem1 = face_voisins(num_face,0);
                              if(elem1==-1) elem1 = face_voisins(num_face,1);
                              double surface_face=zone_VEF.face_surfaces(num_face);
                              double surface_pond;
                              for (i=0; i<nb_faces_elem; i++)
{
                                  if ( (j= elem_faces(elem1,i)) != num_face )
{
                                      surface_pond = 0.;
                                      for (int kk=0; kk<nb_dim_pb; kk++)
                                        surface_pond -= (face_normale(j,kk)*zone_VEF.oriente_normale(j,elem1)*face_normale(num_face,kk)*
                                                         zone_VEF.oriente_normale(num_face,elem1))/(surface_face*surface_face);
                                      Tf+=inconnue(j,nc)*surface_pond;
                                    }
                                  for(int kk=0; kk<nb_dim_pb; kk++)
                                    le_mauvais_gradient(kk)+=inconnue(j,nc)*face_normale(j,kk)*zone_VEF.oriente_normale(j,elem1);
                                }
                              le_mauvais_gradient/=vol(elem1);
// mauvais_gradient = le_mauvais_gradient.n
                              double mauvais_gradient=0;
                              for(int kk=0; kk<nb_dim_pb; kk++)
                                mauvais_gradient+=le_mauvais_gradient(kk)*face_normale(num_face,kk)/surface_face;
// inconnue(num_face) est la temperature de paroi : Tw.
// On se fiche du signe de bon gradient car c'est la norme du gradient
// de temperature dans l'element.
// Ensuite ce sera multiplie par le vecteur normal a la face de paroi
// qui lui a les bons signes.
                              bon_gradient=(Tf-inconnue(num_face,nc))/d_equiv(ind_face)*(-zone_VEF.oriente_normale(num_face,elem1));
                              double nutotal=nu(elem1,nc)+nu_turb(elem1);
                              for (i=0; i<nb_faces_elem; i++)
{
                                  j= elem_faces(elem1,i);
                                  double correction=0.;
                                  for(int kk=0; kk<nb_dim_pb; kk++)
{
                                      double resu2 = nutotal*(bon_gradient-mauvais_gradient)*face_normale(num_face,kk)*face_normale(j,kk)* (-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                      correction+=resu2;
                                    }
                                  resu(j,nc)+=correction;
                                  if (marq[j]!=-1)
                                    resu(marq[j],nc)+=correction;
// la face num_face n'est pas periodique  mar(num_face)==-1
// flux_bord n'est necessaire que sur les faces reelles
                                  if(j==num_face && j<size_flux_bords)
{
// flux_bords(j,0)+=resu1;
                                      tab_flux_bords(j,nc)-=correction;
                                    }
                                }
                            }
                        }
                    }//!< CL Temperature imposee
                }//!< loi de paroi
            }//Equation Convection_Diffusion_Turbulente
// Fin de la correction du gradient dans la premiere maille
// par la loi de paroi thermique.
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if (( (j= elem_faces(elem1,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                    {
                      for (int nc=0; nc<nb_comp; nc++)
{
                          d_nu = nu(elem1,nc)+nu_turb(elem1);
                          valA = viscA(num_face,j,elem1,d_nu);
                          if (ind_face<nb_faces_bord_reel)
{
                              resu(num_face,nc)+=valA*inconnue(j,nc);
                              resu(num_face,nc)-=valA*inconnue(num_face,nc);
// modif pour imprimer les flux sur les bords
                              tab_flux_bords(num_face,nc) -= valA*(inconnue(j,nc)-inconnue(num_face,nc));
                            }
                          if(j<nb_faces) //!< face reelle
{
                              resu(j,nc)+=valA*inconnue(num_face,nc);
                              resu(j,nc)-=valA*inconnue(j,nc);
                            }
                        }
                    }
                }
            }
        }
    }
// Faces internes :
  const int premiere_face_int=zone_VEF.premiere_face_int();
  for (num_face=premiere_face_int; num_face<nb_faces; num_face++)
    {
      for (int kk=0; kk<2; kk++)
        {
          int elem = face_voisins(num_face,kk);
          for (i=0; i<nb_faces_elem; i++)
            {
              if ( (j= elem_faces(elem,i)) > num_face )
                {
                  int el1,el2;
                  int contrib=1;
                  if(j>=nb_faces) //!< C'est une face virtuelle
                    {
                      el1 = face_voisins(j,0);
                      el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if(contrib)
                    {
                      for (int nc=0; nc<nb_comp; nc++)
{
                          d_nu = nu(elem,nc)+nu_turb(elem);
                          valA = viscA(num_face,j,elem,d_nu);
                          resu(num_face,nc)+=valA*inconnue(j,nc);
                          resu(num_face,nc)-=valA*inconnue(num_face,nc);
                          if(j<nb_faces) //!< On traite les faces reelles
{
                              resu(j,nc)+=valA*inconnue(num_face,nc);
                              resu(j,nc)-=valA*inconnue(j,nc);
                            }
                        }
                    }
                }
            }
        }
    }
// Neumann :
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  resu(face,nc) += la_cl_paroi.flux_impose(face-ndeb,nc)*zone_VEF.face_surfaces(face);
                  tab_flux_bords(face,nc) = la_cl_paroi.flux_impose(face-ndeb,nc)*zone_VEF.face_surfaces(face);
                }
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  resu(face,nc) += la_cl_paroi.h_imp(face-ndeb,nc)*(la_cl_paroi.T_ext(face-ndeb,nc)-inconnue(face,nc))*zone_VEF.face_surfaces(face);
                  tab_flux_bords(face,nc) = la_cl_paroi.h_imp(face-ndeb,nc)*(la_cl_paroi.T_ext(face-ndeb,nc)-inconnue(face,nc))*zone_VEF.face_surfaces(face);
                }
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int nc=0; nc<nb_comp; nc++)
              tab_flux_bords(face,nc) = 0.;
        }
    }
}
References Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Echange_impose_base::T_ext(), TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_scalaire()
void Op_Dift_VEF_Face::ajouter_cas_scalaire (const DoubleVect & inconnue, DoubleVect & resu, DoubleTab & flux_bords, const DoubleVect & nu, const DoubleVect & nu_turb, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF) const
< face reelle
< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 239 of file Op_Dift_VEF_Face.cpp.
{
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA, d_nu;
  int nb_front=zone_VEF.nb_front_Cl();
// modif pour imprimer les flux sur les bords
  int size_flux_bords=zone_VEF.nb_faces_bord();
  tab_flux_bords.resize(size_flux_bords,1);
  tab_flux_bords=0.;
  const int premiere_face_int=zone_VEF.premiere_face_int();
// contient -1 si la face n'est pas periodique et numero face_assso sinon
  ArrOfInt marq( zone_VEF.nb_faces_tot());
  marq=-1;
// On traite les faces bord
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              num_face = le_bord.num_face(ind_face);
              marq[num_face]=fac_asso;
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face,kk);
                  d_nu = nu(elem)+nu_turb(elem);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( ( (j= elem_faces(elem,i)) > num_face ) && (j != fac_asso) )
{
                          valA = viscA(num_face,j,elem,d_nu);
                          resu(num_face)+=valA*inconnue(j);
                          resu(num_face)-=valA*inconnue(num_face);
                          if(j<nb_faces) //!< face reelle
{
                              resu(j)+=0.5*valA*inconnue(num_face);
                              resu(j)-=0.5*valA*inconnue(j);
                            }
                        }
                    }
                }
            }
        }
      else   //!< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
//
//
//
        {
          const DoubleTab& face_normale = zone_VEF.face_normales();
          const DoubleVect& vol = zone_VEF.volumes();
          const Equation_base& my_eqn = zone_Cl_VEF.equation();
          const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
          if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
            {
              const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
              const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
              if (loiparth->use_equivalent_distance())
                {
                  const DoubleVect& d_equiv=loiparth->equivalent_distance(n_bord);
// d_equiv contient la distance equivalente pour le bord
// Dans d_equiv, pour les faces qui ne sont pas paroi_fixe (eg periodique, symetrie, etc...)
// il y a la distance geometrique grace a l'initialisation du tableau dans la loi de paroi.
// Les lois de parois ne s'appliquent qu'aux cas ou la CL
// est de type temperature imposee, car dans les autres cas
// (flux impose et adiabatique) le flux a la paroi est connu et fixe.
                  int nb_dim_pb=Objet_U::dimension;
                  const Cond_lim_base& cl_base=la_cl.valeur();
                  int ldp_appli=0;
                  if (sub_type(Scalaire_impose_paroi,cl_base))
                    ldp_appli=1;
                  else if (loiparth->get_flag_calcul_ldp_en_flux_impose() )
                    {
                      if ((sub_type(Neumann_paroi,cl_base))||(sub_type(Neumann_homogene,cl_base)))
                        ldp_appli=1;
                    }
                  if (ldp_appli)
                    {
                      DoubleVect le_mauvais_gradient(nb_dim_pb);
                      for (int ind_face=num1; ind_face<num2; ind_face++)
{
// Tf est la temperature fluide moyenne dans le premier element
// sans tenir compte de la temperature de paroi.
                          double Tf=0.;
                          double bon_gradient=0.; //!< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
                          le_mauvais_gradient=0.;
                          num_face = le_bord.num_face(ind_face);
                          int elem1 = face_voisins(num_face,0);
                          if(elem1==-1) elem1 = face_voisins(num_face,1);
                          double surface_face=zone_VEF.face_surfaces(num_face);
                          double surface_pond;
                          for (i=0; i<nb_faces_elem; i++)
{
                              if ( (j= elem_faces(elem1,i)) != num_face )
{
                                  surface_pond = 0.;
                                  for (int kk=0; kk<nb_dim_pb; kk++)
                                    surface_pond -= (face_normale(j,kk)*zone_VEF.oriente_normale(j,elem1)*face_normale(num_face,kk)*
                                                     zone_VEF.oriente_normale(num_face,elem1))/(surface_face*surface_face);
                                  Tf+=inconnue(j)*surface_pond;
                                }
                              for(int kk=0; kk<nb_dim_pb; kk++)
                                le_mauvais_gradient(kk)+=inconnue(j)*face_normale(j,kk)*zone_VEF.oriente_normale(j,elem1);
                            }
                          le_mauvais_gradient/=vol(elem1);
// mauvais_gradient = le_mauvais_gradient.n
                          double mauvais_gradient=0;
                          for(int kk=0; kk<nb_dim_pb; kk++)
                            mauvais_gradient+=le_mauvais_gradient(kk)*face_normale(num_face,kk)/surface_face;
// inconnue(num_face) est la temperature de paroi : Tw.
// On se fiche du signe de bon gradient car c'est la norme du gradient
// de temperature dans l'element.
// Ensuite ce sera multiplie par le vecteur normal a la face de paroi
// qui lui a les bons signes.
                          bon_gradient=(Tf-inconnue(num_face))/d_equiv(ind_face)*(-zone_VEF.oriente_normale(num_face,elem1));
                          double nutotal=nu(elem1)+nu_turb(elem1);
                          for (i=0; i<nb_faces_elem; i++)
{
                              j= elem_faces(elem1,i);
                              double correction=0.;
                              for(int kk=0; kk<nb_dim_pb; kk++)
{
                                  double resu2 = nutotal*(bon_gradient-mauvais_gradient)*face_normale(num_face,kk)*face_normale(j,kk)* (-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                  correction+=resu2;
                                }
                              resu(j)+=correction;
                              if (marq[j]!=-1)
                                resu[marq[j]]+=correction;
// la face num_face n'est pas periodique  mar(num_face)==-1
// flux_bord n'est necessaire que sur les faces reelles
                              if(j==num_face && j<size_flux_bords)
{
// flux_bords(j,0)+=resu1;
                                  tab_flux_bords(j,0)-=correction;
                                }
                            }
                        }
                    }//!< CL Temperature impose
                }//!< loi de paroi
            }//Equation Convection_Diffusion_Turbulente
// Fin de la correction du gradient dans la premiere maille
// par la loi de paroi thermique.
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem1 = face_voisins(num_face,0);
              d_nu = nu(elem1)+nu_turb(elem1);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if (( (j= elem_faces(elem1,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                    {
                      valA = viscA(num_face,j,elem1,d_nu);
                      if (ind_face<nb_faces_bord_reel)
{
                          double flux=valA*(inconnue(j)-inconnue(num_face));
                          resu(num_face)+=flux;
                          tab_flux_bords(num_face,0) -= flux;
                        }
                      if(j<nb_faces) //!< face reelle
{
                          double  flux=valA*(inconnue(num_face)-inconnue(j));
                          if (j<premiere_face_int)
                            tab_flux_bords(j,0)-=flux;
                          resu(j)+=flux;
                        }
                    }
                }
            }
        }
    }
// Faces internes :
  for (num_face=premiere_face_int; num_face<nb_faces; num_face++)
    {
      for (int kk=0; kk<2; kk++)
        {
          int elem = face_voisins(num_face,kk);
          d_nu = nu(elem)+nu_turb(elem);
          for (i=0; i<nb_faces_elem; i++)
            {
              if ( (j= elem_faces(elem,i)) > num_face )
                {
                  int el1,el2;
                  int contrib=1;
                  if(j>=nb_faces) //!< C'est une face virtuelle
                    {
                      el1 = face_voisins(j,0);
                      el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if(contrib)
                    {
                      valA = viscA(num_face,j,elem,d_nu);
                      resu(num_face)+=valA*inconnue(j);
                      resu(num_face)-=valA*inconnue(num_face);
                      if(j<nb_faces) //!< On traite les faces reelles
{
                          resu(j)+=valA*inconnue(num_face);
                          resu(j)-=valA*inconnue(j);
                        }
                    }
                }
            }
        }
    }
// Neumann :
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              resu[face] += la_cl_paroi.flux_impose(face-ndeb)*zone_VEF.face_surfaces(face);
              tab_flux_bords(face,0) = la_cl_paroi.flux_impose(face-ndeb)*zone_VEF.face_surfaces(face);
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              resu[face] += la_cl_paroi.h_imp(face-ndeb)*(la_cl_paroi.T_ext(face-ndeb)-inconnue(face))*zone_VEF.face_surfaces(face);
              tab_flux_bords(face,0) = la_cl_paroi.h_imp(face-ndeb)*(la_cl_paroi.T_ext(face-ndeb)-inconnue(face))*zone_VEF.face_surfaces(face);
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            tab_flux_bords(face,0) = 0.;
        }
    }
}
References Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Echange_impose_base::T_ext(), TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_vectoriel()
void Op_Dift_VEF_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, const DoubleTab & nu, const DoubleTab & nu_turb, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
Definition at line 519 of file Op_Dift_VEF_Face.cpp.
{
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces = zone_VEF.nb_faces();
  int nb_elem = zone_VEF.nb_elem();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  assert(nbr_comp>1);
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nbr_comp);
  tab_flux_bords=0.;
// Construction du tableau grad_ si necessaire
  if(!grad_.get_md_vector().non_nul())
    {
      grad_.resize(0, Objet_U::dimension, Objet_U::dimension);
      zone_VEF.zone().creer_tableau_elements(grad_);
    }
  grad_=0.;
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  int nb_cl=les_cl.size();
  Champ_P1NC::calcul_gradient(inconnue,grad_,zone_Cl_VEF);
  if (le_modele_turbulence.valeur().utiliser_loi_paroi())
    Champ_P1NC::calcul_duidxj_paroi(grad_,nu,nu_turb,tau_tan_,zone_Cl_VEF);
  grad_.echange_espace_virtuel();
  DoubleTab Re;
  Re.resize(0, Objet_U::dimension, Objet_U::dimension);
  zone_VEF.zone().creer_tableau_elements(Re);
  Re = 0.;
  if (le_modele_turbulence.valeur().calcul_tenseur_Re(nu_turb, grad_, Re))
    {
      Cerr << "On utilise une diffusion turbulente non linaire dans NS" << finl;
      for (int elem=0; elem<nb_elem; elem++)
        for (int i=0; i<nbr_comp; i++)
          for (int j=0; j<nbr_comp; j++)
            Re(elem,i,j) *= nu_turb[elem];
    }
  else
    {
      for (int elem=0; elem<nb_elem; elem++)
        for (int i=0; i<nbr_comp; i++)
          for (int j=0; j<nbr_comp; j++)
            Re(elem,i,j) = nu_turb[elem]*(grad_(elem,i,j) + grad_(elem,j,i));
    }
  Re.echange_espace_virtuel();
// Calcul du terme diffusif
// boucle sur les CL
  for (int n_bord=0; n_bord<nb_cl; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          for (int num_face=num1; num_face<num2; num_face++)
            {
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face,kk);
                  int ori = 1-2*kk;
                  for (int i=0; i<nbr_comp; i++)
                    for (int j=0; j<nbr_comp; j++)
                      resu(num_face,i) -= ori*face_normale(num_face,j)
                                          *(nu[elem]*grad_(elem,i,j) + Re(elem,i,j));
                } //!< Fin de la boucle sur les elements ayant la face comnune
            } //!< Fin de la boucle sur les faces
        } //!< Fin du cas periodique
      else
        {
          for (int num_face=num1; num_face<num2; num_face++)
            {
              int elem=face_voisins(num_face,0);
              for (int i=0; i<nbr_comp; i++)
                for (int j=0; j<nbr_comp; j++)
                  {
                    double flux = face_normale(num_face,j)
                                  *(nu[elem]*grad_(elem,i,j) + Re(elem,i,j));
                    resu(num_face,i) -= flux;
                    tab_flux_bords(num_face,i) -= flux;
                  }
            } //!< Fin de la boucle sur les faces
        }
    } //!< Fin du traitement des CL
//
// Faces internes
//
  int n0 = zone_VEF.premiere_face_int();
  for (int num_face=n0; num_face<nb_faces; num_face++)
    {
      for (int kk=0; kk<2; kk++)
        {
          int elem = face_voisins(num_face,kk);
          int ori = 1-2*kk;
          for (int i=0; i<nbr_comp; i++)
            for (int j=0; j<nbr_comp; j++)
              {
                resu(num_face,i) -= ori*face_normale(num_face,j)
                                    *(nu[elem]*grad_(elem,i,j) + Re(elem,i,j));
              }
        } //!< Fin de la boucle sur les 2 elements comnuns a la face
    } //!< Fin de la boucle sur les faces internes
// Symmetry condition
  for (int n_bord=0; n_bord<nb_cl; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Symetrie,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            tab_flux_bords(face,0) = 0.;
        }
    }
}
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), Mod_turb_hyd_base::calcul_tenseur_Re(), Cerr, Zone::creer_tableau_elements(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), TRUSTVect< _TYPE_ >::get_md_vector(), grad_, Op_Dift_VEF_base::le_modele_turbulence, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), MD_Vector::non_nul(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, Op_Dift_VEF_base::tau_tan_, Mod_turb_hyd_base::utiliser_loi_paroi(), Deriv_Cond_lim_base::valeur(), Ref_Mod_turb_hyd_base::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_contribution()
void Op_Dift_VEF_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
< C'est une face virtuelle
< on ajoutera grad_U transpose
< On traite les faces reelles
< on ajoute grad_U transpose
< On traite les faces reelles
Definition at line 1249 of file Op_Dift_VEF_Face.cpp.
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces = zone_VEF.nb_faces();
  const int nb_comp =transporte.line_size();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const DoubleTab& nu_turb_=diffusivite_turbulente()->valeurs();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  const DoubleVect& volumes = zone_VEF.volumes();
  DoubleVect n(dimension);
  DoubleTab nu,nu_turb;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  modif_par_porosite_si_flag(nu_turb_,nu_turb,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
// On traite les conditions limites separemment car sinon
// methode trop longue et mauvais inlining de certaines methodes
// sur certaines machines (Matrice_Morse::operator() et viscA)
  ajouter_contribution_cl(transporte, matrice, nu, nu_turb, porosite_eventuelle);
// On traite les faces internes
  int numpremiereface = zone_VEF.premiere_face_int();
  for (int num_face=numpremiereface; num_face<nb_faces; num_face++)
    {
      for (int l=0; l<2; l++)
        {
          int elem = face_voisins(num_face,l);
          double d_nu = nu(elem) + nu_turb(elem);
          for (int i=0; i<nb_faces_elem; i++)
            {
              int j = elem_faces(elem,i);
              if ( j > num_face )
                {
                  int contrib=1;
                  if(j>=nb_faces) //!< C'est une face virtuelle
                    {
                      int el1 = face_voisins(j,0);
                      int el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if (contrib)
                    {
                      double tmp = 0;
                      if (nb_comp>1) //!< on ajoutera grad_U transpose
{
                          int orientation = 1;
                          if ( (elem == face_voisins(j,l)) || (face_voisins(num_face,1-l) == face_voisins(j,1-l)))
                            orientation = -1;
                          tmp = orientation * nu_turb(elem) / volumes(elem);
                        }
                      double valA = viscA(num_face,j,elem,d_nu);
                      double contrib_num_face = valA*porosite_eventuelle(num_face);
                      double contrib_j = valA*porosite_eventuelle(j);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=contrib_num_face;
                          matrice(n0,j0)-=contrib_j;
                          if(j<nb_faces) //!< On traite les faces reelles
{
                              matrice(j0,n0)-=contrib_num_face;
                              matrice(j0,j0)+=contrib_j;
                            }
                          if (nb_comp>1) //!< on ajoute grad_U transpose
{
                              for (int nc2=0; nc2<nb_comp; nc2++)
{
                                  int n1=num_face*nb_comp+nc2;
                                  int j1=j*nb_comp+nc2;
                                  double coeff_s=tmp*face_normale(num_face,nc2)*face_normale(j,nc);
                                  matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                  matrice(n0,j1)-=coeff_s*porosite_eventuelle(j);
                                  if(j<nb_faces) //!< On traite les faces reelles
{
                                      double coeff_s2=tmp*face_normale(num_face,nc)*face_normale(j,nc2);
                                      matrice(j0,n1)-=coeff_s2*porosite_eventuelle(num_face);
                                      matrice(j0,j1)+=coeff_s2*porosite_eventuelle(j);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
References ajouter_contribution_cl(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by Op_Dift_Stab_VEF_Face::ajouter_contribution(), and contribuer_a_avec().
ajouter_contribution_cl()
void Op_Dift_VEF_Face::ajouter_contribution_cl (const DoubleTab & transporte, Matrice_Morse & matrice, const DoubleTab & nu, const DoubleTab & nu_turb, const DoubleVect & porosite_eventuelle) const
< C'est une face virtuelle
< On traite les faces reelles
< on ajoute grad_U transpose
< On traite les faces reelles
< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
< on ajoute grad_U transpose
Definition at line 999 of file Op_Dift_VEF_Face.cpp.
{
// On traite les faces bord
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const DoubleVect& volumes = zone_VEF.volumes();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  int nb_faces = zone_VEF.nb_faces();
  const int nb_comp =transporte.line_size();
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      int j;
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// on ne parcourt que la moitie des faces volontairement...
// GF il ne faut pas s'occuper des faces virtuelles
          num2=nb_faces_bord_reel/2;
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              int fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              int num_face = le_bord.num_face(ind_face);
              for (int l=0; l<2; l++)
                {
                  int elem = face_voisins(num_face,l);
                  double d_nu = nu(elem)+nu_turb(elem);
                  for (int i=0; i<nb_faces_elem; i++)
                    {
                      if ( (j= elem_faces(elem,i)) > num_face )
{
                          double valA = viscA(num_face,j,elem,d_nu);
                          int orientation = 1;
                          if ( (elem == face_voisins(j,l)) || (face_voisins(num_face,(l+1)%2) == face_voisins(j,(l+1)%2)))
                            orientation = -1;
                          int fac_loc=0;
                          int ok=1;
                          while ((fac_loc<nb_faces_elem) && (elem_faces(elem,fac_loc)!=num_face)) fac_loc++;
                          if (fac_loc==nb_faces_elem)
                            ok=0;
                          int contrib=1;
                          if(j>=nb_faces) //!< C'est une face virtuelle
{
                              int el1 = face_voisins(j,0);
                              int el2 = face_voisins(j,1);
                              if((el1==-1)||(el2==-1))
                                contrib=0;
                            }
                          if (contrib)
{
                              for (int nc=0; nc<nb_comp; nc++)
{
                                  int n0=num_face*nb_comp+nc;
                                  int n0perio=fac_asso*nb_comp+nc;
                                  int j0=j*nb_comp+nc;
                                  matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                                  matrice(n0,j0)-=valA*porosite_eventuelle(j);
                                  if(j<nb_faces) //!< On traite les faces reelles
{
// if (l==0)
                                      if (ok==1)
                                        matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                                      else
                                        matrice(j0,n0perio)-=valA*porosite_eventuelle(num_face);
                                      matrice(j0,j0)+=valA*porosite_eventuelle(j);
                                    }
                                  if ( nb_comp>1) //!< on ajoute grad_U transpose
                                    for (int nc2=0; nc2<nb_comp; nc2++)
{
                                        int n1=num_face*nb_comp+nc2;
                                        int j1=j*nb_comp+nc2;
                                        double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc2)*face_normale(j,nc);
                                        matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                        matrice(n0,j1)-= coeff_s*porosite_eventuelle(j);
                                        if(j<nb_faces) //!< On traite les faces reelles
{
                                            double coeff_s2=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc)*face_normale(j,nc2);
                                            if (ok==1)
                                              matrice(j0,n1)-=coeff_s2*porosite_eventuelle(num_face);
                                            else
                                              matrice(j0,fac_asso*nb_comp+nc2)-=coeff_s2*porosite_eventuelle(num_face);
                                            matrice(j0,j1)+=coeff_s2*porosite_eventuelle(j);
                                          }
                                      }
                                }
                            }
                        }
                    }
                }
            }
        }
      else
        {
// pas perio
// correction dans le cas dirichlet sur paroi temperature
          if(sub_type(Scalaire_impose_paroi,la_cl.valeur()))
            {
              const Equation_base& my_eqn = zone_Cl_VEF.equation();
              const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
              if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
                {
                  const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
                  const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
                  if (loiparth->use_equivalent_distance())
                    {
// const DoubleTab& face_normale = zone_VEF.face_normales();
                      const DoubleVect& vol = zone_VEF.volumes();
                      const DoubleVect& d_equiv=loiparth->equivalent_distance(n_bord);
                      int nb_dim_pb=Objet_U::dimension;
                      DoubleVect le_mauvais_gradient(nb_dim_pb);
                      for (int ind_face=num1; ind_face<num2; ind_face++)
{
                          int num_face = le_bord.num_face(ind_face);
// Tf est la temperature fluide moyenne dans le premier element
// sans tenir compte de la temperature de paroi.
                          double Tf=0.;
                          double bon_gradient=0.; //!< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
//
                          int elem1 = face_voisins(num_face,0);
                          if (elem1==-1) elem1 = face_voisins(num_face,1);
// inconnue(num_face) est la temperature de paroi : Tw.
// On se fiche du signe de bon gradient car c'est la norme du gradient
// de temperature dans l'element.
// Ensuite ce sera multiplie par le vecteur normal a la face de paroi
// qui lui a les bons signes.
// bon_gradient=(Tf-inconnue(num_face))/d_equiv(num_face);
                          bon_gradient=1./d_equiv(ind_face)*(-zone_VEF.oriente_normale(num_face,elem1));
                          double surface_face=zone_VEF.face_surfaces(num_face);
                          double nutotal=nu(elem1)+nu_turb(elem1);
                          for (int i=0; i<nb_faces_elem; i++)
{
                              j= elem_faces(elem1,i);
                              for (int ii=0; ii<nb_faces_elem; ii++)
{
                                  le_mauvais_gradient=0;
                                  int jj=elem_faces(elem1,ii);
                                  double surface_pond=0;
                                  for (int kk=0; kk<nb_dim_pb; kk++)
                                    surface_pond -= (face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1)*face_normale(num_face,kk)*
                                                     zone_VEF.oriente_normale(num_face,elem1))/(surface_face*surface_face);
                                  Tf=surface_pond;
// Tf=1./(nb_faces_elem-1); // Temperature moyenne.
                                  for(int kk=0; kk<nb_dim_pb; kk++)
                                    le_mauvais_gradient(kk)+=face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1);
                                  le_mauvais_gradient/=vol(elem1);
                                  double mauvais_gradient=0;
// double surface_face=zone_VEF.face_surfaces(num_face);
                                  for(int kk=0; kk<nb_dim_pb; kk++)
                                    mauvais_gradient+=le_mauvais_gradient(kk)*face_normale(num_face,kk)/surface_face;
                                  double resu1=0,resu2=0;
                                  for(int kk=0; kk<nb_dim_pb; kk++)
{
// resu1 += nutotal*le_mauvais_gradient(kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1));
                                      resu1 += nutotal*mauvais_gradient*face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                      resu2 += nutotal*bon_gradient    *face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                    }
// bon gradient_reel =bongradient*(Tf-T_face) d'ou les derivees...
// mauvais gradient_reel=mauvai_gradient_j*Tj
                                  if (jj==num_face)
                                    resu2*=-1;
                                  else
                                    resu2*=Tf;
                                  matrice(j,jj)+=(resu1-resu2)*porosite_eventuelle(jj);
                                }
                            }
                        }
                    }//!< loi de paroi
                }//Equation Convection_Diffusion_Turbulente
            } //!< CL Temperature imposee
          else if  (sub_type(Echange_externe_impose,la_cl.valeur()))
            {
              const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                {
                  matrice(face,face) += la_cl_paroi.h_imp(face-ndeb)*zone_VEF.face_surfaces(face);
                }
            }
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              int num_face = le_bord.num_face(ind_face);
              int elem=face_voisins(num_face,0);
              double d_nu = nu(elem)+nu_turb(elem);
// Boucle sur les faces :
              for (int i=0; i<nb_faces_elem; i++)
                if (( (j= elem_faces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                  {
                    double valA = viscA(num_face,j,elem,d_nu);
                    int orientation = 1;
                    if ( (elem == face_voisins(j,0)) || (face_voisins(num_face,(0+1)%2) == face_voisins(j,(0+1)%2)))
                      orientation = -1;
// retire terme croise pour l'intant
// orientation=0;
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        if (ind_face<nb_faces_bord_reel)
{
                            matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                            matrice(n0,j0)-=valA*porosite_eventuelle(j);
                          }
                        if(j<nb_faces)
{
                            matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                            matrice(j0,j0)+=valA*porosite_eventuelle(j);
                          }
                        if (nb_comp>1) //!< on ajoute grad_U transpose
                          for (int nc2=0; nc2<nb_comp; nc2++)
{
                              int n1=num_face*nb_comp+nc2;
                              int j1=j*nb_comp+nc2;
                              if (ind_face<nb_faces_bord_reel)
{
                                  double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc2)*face_normale(j,nc);
                                  matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                  matrice(n0,j1)-= coeff_s*porosite_eventuelle(j);
                                }
                              if (j<nb_faces)
{
                                  double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc)*face_normale(j,nc2);
                                  matrice(j0,n1)-=coeff_s*porosite_eventuelle(num_face);
                                  matrice(j0,j1)+=coeff_s*porosite_eventuelle(j);
                                }
                            }
                      }
                  }
            }
        }
    }
}
References Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), ref_cast, sub_type, TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_contribution(), and Op_Dift_Stab_VEF_Face::ajouter_contribution_cl().
ajouter_contribution_multi_scalaire()
void Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
< C'est une face virtuelle
< On traite les faces reelles
< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 1359 of file Op_Dift_VEF_Face.cpp.
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces = zone_VEF.nb_faces();
  const int nb_comp =transporte.line_size();
  int i0,j,num_face0;
  int elem0,elem1;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA, d_nu;
  const DoubleTab& nu_turb_=diffusivite_turbulente()->valeurs();
  DoubleVect n(dimension);
  DoubleTab nu,nu_turb;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  modif_par_porosite_si_flag(nu_turb_,nu_turb,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
// On traite les faces bord
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elem_faces = zone_VEF.elem_faces();
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
// on ne parcourt que la moitie des faces volontairement...
          num2/=2;
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso= le_bord.num_face(fac_asso);
              num_face0 = le_bord.num_face(ind_face);
// ICI
              for (int l=0; l<2; l++)
                {
                  elem0 = face_voisins(num_face0,l);
// On elimine les elements avec CL de paroi (rang>=1)
// int rang = rang_elem_non_std(elem);
// if (rang<0)
                  {
                    for (i0=0; i0<nb_faces_elem; i0++)
                      {
                        if ( (j= elem_faces(elem0,i0)) > num_face0 )
{
                            int fac_loc=0;
                            int ok=1;
                            while ((fac_loc<nb_faces_elem) && (elem_faces(elem0,fac_loc)!=num_face0)) fac_loc++;
                            if (fac_loc==nb_faces_elem)
                              ok=0;
                            for (int nc=0; nc<nb_comp; nc++)
{
                                d_nu = nu(elem0,nc)+nu_turb(elem0);
                                valA = viscA(num_face0,j,elem0,d_nu);
                                int n0=num_face0*nb_comp+nc;
                                int n0perio=fac_asso*nb_comp+nc;
                                int j0=j*nb_comp+nc;
                                int contrib=1;
                                if(j>=nb_faces) //!< C'est une face virtuelle
{
                                    int el1 = face_voisins(j,0);
                                    int el2 = face_voisins(j,1);
                                    if((el1==-1)||(el2==-1))
                                      contrib=0;
                                  }
                                if(contrib)
{
                                    matrice(n0,n0)+=valA*porosite_eventuelle(num_face0);
                                    matrice(n0,j0)-=valA*porosite_eventuelle(j);
                                    if(j<nb_faces) //!< On traite les faces reelles
{
// if (l==0)
                                        if (ok==1)
                                          matrice(j0,n0)-=valA*porosite_eventuelle(num_face0);
                                        else
                                          matrice(j0,n0perio)-=valA*porosite_eventuelle(num_face0);
                                        matrice(j0,j0)+=valA*porosite_eventuelle(j);
                                      }
                                  }
                              }
                          }
                      }
                  }
                }
            }
        }
      else
        {
// pas perio
// correction dans le cas dirichlet sur paroi temperature
          if(sub_type(Scalaire_impose_paroi,la_cl.valeur()))
            {
              const Equation_base& my_eqn = zone_Cl_VEF.equation();
              const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
              if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
                {
                  const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
                  const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
                  if (loiparth->use_equivalent_distance())
                    {
                      const DoubleTab& face_normale = zone_VEF.face_normales();
                      const DoubleVect& vol = zone_VEF.volumes();
                      const DoubleVect& d_equiv=loiparth->equivalent_distance(n_bord);
                      int nb_dim_pb=Objet_U::dimension;
                      DoubleVect le_mauvais_gradient(nb_dim_pb);
                      for (int ind_face=num1; ind_face<num2; ind_face++)
{
                          for (int nc=0; nc<nb_comp; nc++)
{
                              int num_face = le_bord.num_face(ind_face);
// Tf est la temperature fluide moyenne dans le premier element
// sans tenir compte de la temperature de paroi.
                              double Tf=0.;
                              double bon_gradient=0.; //!< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
//
                              elem1 = face_voisins(num_face,0);
                              if(elem1==-1) elem1 = face_voisins(num_face,1);
// inconnue(num_face) est la temperature de paroi : Tw.
// On se fiche du signe de bon gradient car c'est la norme du gradient
// de temperature dans l'element.
// Ensuite ce sera multiplie par le vecteur normal a la face de paroi
// qui lui a les bons signes.
// bon_gradient=(Tf-inconnue(num_face))/d_equiv(num_face);
                              bon_gradient=1./d_equiv(ind_face)*(-zone_VEF.oriente_normale(num_face,elem1));
                              double surface_face=zone_VEF.face_surfaces(num_face);
                              double nutotal=nu(elem1,nc)+nu_turb(elem1);
                              for (i0=0; i0<nb_faces_elem; i0++)
{
                                  j= elem_faces(elem1,i0);
                                  for (int ii=0; ii<nb_faces_elem; ii++)
{
                                      le_mauvais_gradient=0;
                                      int jj=elem_faces(elem1,ii);
                                      double surface_pond=0;
                                      for (int kk=0; kk<nb_dim_pb; kk++)
                                        surface_pond -= (face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1)*face_normale(num_face,kk)*
                                                         zone_VEF.oriente_normale(num_face,elem1))/(surface_face*surface_face);
                                      Tf=surface_pond;
// Tf=1./(nb_faces_elem-1); // Temperature moyenne.
                                      for(int kk=0; kk<nb_dim_pb; kk++)
                                        le_mauvais_gradient(kk)+=face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1);
                                      le_mauvais_gradient/=vol(elem1);
                                      double mauvais_gradient=0;
// double surface_face=zone_VEF.face_surfaces(num_face);
                                      for(int kk=0; kk<nb_dim_pb; kk++)
                                        mauvais_gradient+=le_mauvais_gradient(kk)*face_normale(num_face,kk)/surface_face;
                                      double resu1=0,resu2=0;
                                      for(int kk=0; kk<nb_dim_pb; kk++)
{
// resu1 += nutotal*le_mauvais_gradient(kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1));
                                          resu1 += nutotal*mauvais_gradient*face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                          resu2 += nutotal*bon_gradient    *face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                        }
// bon gradient_reel =bongradient*(Tf-T_face) d'ou les derivees...
// mauvais gradient_reel=mauvai_gradient_j*Tj
                                      if (jj==num_face)
                                        resu2*=-1;
                                      else
                                        resu2*=Tf;
                                      int j0=j*nb_comp+nc;
                                      int jj0=jj*nb_comp+nc;
                                      matrice(j0,jj0)+=(resu1-resu2)*porosite_eventuelle(jj0);
                                    }
                                }
                            }
                        }
                    }//!< loi de paroi
                }//Equation Convection_Diffusion_Turbulente
            } //!< CL Temperature imposee
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              int num_face = le_bord.num_face(ind_face);
              int elem=face_voisins(num_face,0);
// Boucle sur les faces :
              for (int i=0; i<nb_faces_elem; i++)
                if (( (j= elem_faces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                  {
// int orientation = zone_VEF.oriente_normale(j,elem);
// retire terme croisee pour l'intant
// orientation=0;
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        d_nu = nu(elem,nc)+nu_turb(elem);
                        valA = viscA(num_face,j,elem,d_nu);
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        if (ind_face<nb_faces_bord_reel)
{
                            matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                            matrice(n0,j0)-=valA*porosite_eventuelle(j);
                          }
                        if(j<nb_faces)
{
                            matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                            matrice(j0,j0)+=valA*porosite_eventuelle(j);
                          }
                      }
                  }
            }
        }
    }
// On traite les faces internes
  int rumpremiereface=zone_VEF.premiere_face_int();
  for (num_face0=rumpremiereface; num_face0<nb_faces; num_face0++)
    {
// ICI
      for (int l=0; l<2; l++)
        {
          elem0 = face_voisins(num_face0,l);
// On elimine les elements avec CL de paroi (rang>=1)
// int rang = rang_elem_non_std(elem);
// if (rang<0)
          {
            for (i0=0; i0<nb_faces_elem; i0++)
              {
                if ( (j= elem_faces(elem0,i0)) > num_face0 )
                  {
// int orientation = 1;
// if ((elem == face_voisins(j,l)) || (face_voisins(num_face,(l+1)%2) == face_voisins(j,(l+1)%2)))
// orientation = -1;
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        d_nu = nu(elem0,nc)+nu_turb(elem0);
                        valA = viscA(num_face0,j,elem0,d_nu);
                        int n0=num_face0*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        int contrib=1;
                        if(j>=nb_faces) //!< C'est une face virtuelle
{
                            int el1 = face_voisins(j,0);
                            int el2 = face_voisins(j,1);
                            if((el1==-1)||(el2==-1))
                              contrib=0;
                          }
                        if(contrib)
{
                            matrice(n0,n0)+=valA*porosite_eventuelle(num_face0);
                            matrice(n0,j0)-=valA*porosite_eventuelle(j);
                            if(j<nb_faces) //!< On traite les faces reelles
{
                                matrice(j0,n0)-=valA*porosite_eventuelle(num_face0);
                                matrice(j0,j0)+=valA*porosite_eventuelle(j);
                              }
                          }
                      }
                  }
              }
          }
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
References Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Modele_turbulence_scal_base::loi_paroi(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_face(), Zone_VEF::oriente_normale(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), and contribuer_a_avec().
associer_diffusivite()
void Op_Dift_VEF_Face::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
Definition at line 56 of file Op_Dift_VEF_Face.cpp.
{
  diffusivite_ = diffu;
}
References diffusivite_.
calculer()
DoubleTab & Op_Dift_VEF_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 988 of file Op_Dift_VEF_Face.cpp.
{
  resu = 0;
  return ajouter(inconnue,resu);
}
References ajouter().
calculer_dt_stab()
double Op_Dift_VEF_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
< PQ : 06/03
< PQ : 06/03
< get h_imp from datafile
< we should take the absolute value since it can be negative!
< Should we take the max if more than one bc has h_imp ?
Reimplemented from Op_Diff_VEF_base.
Definition at line 62 of file Op_Dift_VEF_Face.cpp.
{
// 12/04: Premiers efforts d'optimisation du code a tenir
// compte lors de la factorisation des pas de temps de stabilite
// Calcul de dt_stab
// La diffusivite est constante par elements donc
// il faut calculer dt_diff pour chaque element et
// dt_stab=Min(dt_diff (K) = h(K)*h(K)/(2*dimension*diffu2_(K)))
// ou diffu2_ est la somme des 2 diffusivite laminaire et turbulente
// GF
// alpha_dt_stab=(alpha+alpha_t)*alpha_dt_stab/alpha
// alpha_dt_stab=(nu+diff_nu_turb)*valeurs_diffusivite_dt/nu
// On remplit le tableau nu contenant la diffusivite en chaque elem
  remplir_nu(nu_);
  double dt_stab=1.e30;
  double coef;
  const Zone_VEF& la_zone_VEF = la_zone_vef.valeur();
// const DoubleVect& porosite_elem = la_zone_VEF.porosite_elem();
  const Zone& la_zone= la_zone_VEF.zone();
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  if (equation().que_suis_je().debute_par("Convection_Diffusion_Temp"))
    {
      double rhocp = mon_equation->milieu().capacite_calorifique().valeurs()(0, 0) * mon_equation->milieu().masse_volumique().valeurs()(0, 0);
      diffu_turb /= rhocp;
      diffu /= rhocp;
    }
  double alpha;
  int la_zone_nb_elem=la_zone.nb_elem();
  if (has_champ_masse_volumique())
    {
      const DoubleTab& rho_elem = get_champ_masse_volumique().valeurs();
      assert(rho_elem.size_array()==la_zone_VEF.nb_elem_tot());
      for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
        {
          alpha = diffu[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
          alpha/=rho_elem[num_elem];
// dt=1/(dimension/(pas*pas))/(2*alpha)
          coef=la_zone_VEF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
// dt_stab=min(dt);
          if (coef<dt_stab) dt_stab = coef;
        }
    }
  else
    {
      const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
      const DoubleTab&      valeurs_diffusivite = champ_diffusivite.valeurs();
      double valeurs_diffusivite_dt=-1;
      int unif_diffu_dt;
      const Nature_du_champ nature_champ = equation().inconnue()->nature_du_champ();
      if (sub_type(Champ_Uniforme,champ_diffusivite))
        {
          valeurs_diffusivite_dt=valeurs_diffusivite(0,0);
          unif_diffu_dt=1;
        }
      else
        unif_diffu_dt=0;
      if (nature_champ!=multi_scalaire)
        {
          for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
            {
              alpha =  diffu[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
              if(unif_diffu_dt==0)
                valeurs_diffusivite_dt=valeurs_diffusivite(num_elem,0);
              alpha*=valeurs_diffusivite_dt/(diffu[num_elem]+DMINFLOAT);
// dt=1/(dimension/(pas*pas))/(2*alpha)
              coef=la_zone_VEF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
              assert(coef>=0);
// dt_stab=min(dt);
              if (coef<dt_stab) dt_stab = coef;
            }
        }
      else
        {
          int nb_comp = valeurs_diffusivite.line_size();
          for (int nc=0; nc<nb_comp; nc++)
            {
              for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
                {
                  alpha =  diffu(num_elem,nc) + diffu_turb[num_elem];
// if(unif_diffu_dt==0)
                  valeurs_diffusivite_dt=valeurs_diffusivite(0,nc);
                  alpha*=valeurs_diffusivite_dt/(diffu(num_elem,nc)+DMINFLOAT);
                  coef=la_zone_VEF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
                  if (coef<dt_stab) dt_stab = coef;
                }
            }
        }
    }
  dt_stab = Process::mp_min(dt_stab);
  return dt_stab;
}
References Milieu_base::capacite_calorifique(), Zone_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, DMINFLOAT, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), MorEqn::mon_equation, Process::mp_min(), multi_scalaire, Zone::nb_elem(), Zone_dis_base::nb_elem_tot(), Op_Diff_VEF_base::nu_, Objet_U::que_suis_je(), Op_Diff_VEF_base::remplir_nu(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Zone_VEF::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
Referenced by calculer_pour_post().
calculer_pour_post()
void Op_Dift_VEF_Face::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const override virtual
< PQ : 06/03
< PQ : 06/03
Reimplemented from Op_Diff_VEF_base.
Definition at line 169 of file Op_Dift_VEF_Face.cpp.
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      if (la_zone_vef.non_nul())
        {
// On remplit le tableau nu contenant la diffusivite en chaque elem
          remplir_nu(nu_);
          double coef;
          const Zone_VEF& la_zone_VEF = la_zone_vef.valeur();
          const Zone& la_zone= la_zone_VEF.zone();
          const DoubleVect& diffu_turb=diffusivite_turbulente()->valeurs();
          double alpha;
          int la_zone_nb_elem=la_zone.nb_elem();
          if (has_champ_masse_volumique())
            {
              const DoubleTab& rho_elem = get_champ_masse_volumique().valeurs();
              assert(rho_elem.size_array()==la_zone_VEF.nb_elem_tot());
              for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
                {
                  alpha = nu_[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
                  alpha/=rho_elem[num_elem];
                  coef=la_zone_VEF.carre_pas_maille(num_elem)/(2.*dimension*alpha);
                  es_valeurs(num_elem) = coef;
                }
            }
          else
            {
              const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
              const DoubleTab&      valeurs_diffusivite = champ_diffusivite.valeurs();
              double valeurs_diffusivite_dt=-1;
              int unif_diffu_dt;
              if (sub_type(Champ_Uniforme,champ_diffusivite))
                {
                  valeurs_diffusivite_dt=valeurs_diffusivite(0,0);
                  unif_diffu_dt=1;
                }
              else
                unif_diffu_dt=0;
              for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
                {
                  alpha =  nu_[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
                  if(unif_diffu_dt==0)
                    valeurs_diffusivite_dt=valeurs_diffusivite(num_elem);
                  alpha*=valeurs_diffusivite_dt/nu_[num_elem];
                  coef=la_zone_VEF.carre_pas_maille(num_elem)/(2.*dimension*alpha);
                  es_valeurs(num_elem) = coef;
                }
            }
          assert(est_egal(mp_min_vect(es_valeurs),calculer_dt_stab()));
        }
    }
  else
    Op_Dift_VEF_base::calculer_pour_post(espace_stockage,option,comp);
}
References calculer_dt_stab(), Op_Diff_VEF_base::calculer_pour_post(), Zone_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, est_egal(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_VEF_base::la_zone_vef, mp_min_vect(), Zone::nb_elem(), Zone_dis_base::nb_elem_tot(), O_U_Ptr::non_nul(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::remplir_nu(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Zone_VEF::valeur(), Champ::valeurs(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
contribue_au_second_membre()
void Op_Dift_VEF_Face::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 1651 of file Op_Dift_VEF_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int n_bord;
  int nb_faces = zone_VEF.nb_faces();
// int elem;
  int nb_comp =resu.line_size();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  DoubleVect n(dimension);
  DoubleTrav Tgrad(dimension,dimension);
// On traite les faces bord
// if (nb_comp!=1)
  if (equation().inconnue()->nature_du_champ()==vectoriel)
    {
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const DoubleTab& nu_turb=diffusivite_turbulente()->valeurs();
      const DoubleTab& inconnue_org=equation().inconnue().valeurs();
      DoubleTab nu,nu_turb_m;
      DoubleTab tab_inconnue;
      int marq=phi_psi_diffuse(equation());
      const DoubleVect& porosite_face = zone_VEF.porosite_face();
      const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
      modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
      modif_par_porosite_si_flag(nu_turb,nu_turb_m,!marq,porosite_elem);
      const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue,marq,porosite_face);
      DoubleTab& grad = grad_;
      grad=0.;
// const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
// int nb_cl=les_cl.size();
      Champ_P1NC::calcul_gradient(inconnue,grad,zone_Cl_VEF);
      DoubleTab gradsa(grad);
      if (le_modele_turbulence.valeur().utiliser_loi_paroi())
        Champ_P1NC::calcul_duidxj_paroi(grad,nu,nu_turb,tau_tan_,zone_Cl_VEF);
      grad-=gradsa;
      grad.echange_espace_virtuel();
      for (int num_face=0; num_face<nb_faces; num_face++)
        {
// double d_nu;
          for (int kk=0; kk<2; kk++)
            {
              int elem=face_voisins(num_face,kk);
              if (elem!=-1)
                {
// d_nu = nu[elem]+nu_turb[elem];
                  int ori = 1-2*kk;
                  for (int i=0; i<nb_comp; i++)
                    for (int j=0; j<nb_comp; j++)
                      {
                        resu(num_face,i) -= ori*face_normale(num_face,j)*
                                            ((nu[elem]+nu_turb[elem])*grad(elem,i,j)
                                             +(nu_turb[elem])*grad_transp(elem,i,j));
                      }
                }
            }
        }
    }
// int nb_comp = resu.dimension(1);
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int comp=0; comp<nb_comp; comp++)
              resu(face,comp) += la_cl_paroi.flux_impose(face-ndeb,comp)*zone_VEF.face_surfaces(face);
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          if (resu.line_size() == 1)
            {
              const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                {
                  resu[face] += la_cl_paroi.h_imp(face-ndeb)*(la_cl_paroi.T_ext(face-ndeb))*zone_VEF.face_surfaces(face);
                }
            }
          else
            {
              Cerr << "Non code pour Echange_externe_impose" << finl;
              assert(0);
            }
        }
    }
}
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), Cerr, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), grad_, grad_transp, Echange_impose_base::h_imp(), Equation_base::inconnue(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Op_Dift_VEF_base::le_modele_turbulence, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Echange_impose_base::T_ext(), Op_Dift_VEF_base::tau_tan_, Mod_turb_hyd_base::utiliser_loi_paroi(), Deriv_Cond_lim_base::valeur(), Ref_Mod_turb_hyd_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Champ_Inc::valeurs(), and vectoriel.
Referenced by contribuer_au_second_membre().
contribuer_a_avec()
void Op_Dift_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 108 of file Op_Dift_VEF_Face.h.
{
  const Champ_base& inconnue = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inconnue.nature_du_champ();
  if (nature_champ!=multi_scalaire)
    ajouter_contribution(inco, matrice);
  else
    ajouter_contribution_multi_scalaire(inco, matrice);
}
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), MorEqn::equation(), Equation_base::inconnue(), multi_scalaire, Field_base::nature_du_champ(), and Deriv_Champ_Inc_base::valeur().
Referenced by Op_Dift_Stab_VEF_Face::contribuer_a_avec().
contribuer_au_second_membre()
void Op_Dift_VEF_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 122 of file Op_Dift_VEF_Face.h.
{
  contribue_au_second_membre(resu);
}
References contribue_au_second_membre().
cree_instance()
Objet_U * Op_Dift_VEF_Face::cree_instance () static
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
diffusivite() [1/2]
const Champ_base & Op_Dift_VEF_Face::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Definition at line 37 of file Op_Dift_VEF_Face.h.
  {
    return diffusivite_;
  };
References diffusivite_.
Referenced by diffusivite().
diffusivite() [2/2]
double Op_Dift_VEF_Face::diffusivite (int) const inline
Definition at line 41 of file Op_Dift_VEF_Face.h.
  {
    return (diffusivite().valeurs().nb_dim()==1)?(diffusivite().valeurs())(0):(diffusivite().valeurs())(0,0);
  };
References diffusivite(), and Champ_Proto::valeurs().
dimensionner()
void Op_Dift_VEF_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 94 of file Op_Dift_VEF_Face.h.
{
  Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
}
References Op_VEF_Face::dimensionner(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
duplique()
int Op_Dift_VEF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_VEF_Face_Var.
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
get_info()
const Type_info * Op_Dift_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Reimplemented in Op_Dift_VEF_Face_Var.
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
get_localisation_pour_post()
Motcle Op_Dift_VEF_Face::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Op_Diff_VEF_base.
Definition at line 230 of file Op_Dift_VEF_Face.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "elem";
  else
    return Op_Dift_VEF_base::get_localisation_pour_post(option);
  return loc;
}
References Op_Diff_VEF_base::get_localisation_pour_post().
info()
const Type_info * Op_Dift_VEF_Face::info () static
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
modifier_pour_Cl()
void Op_Dift_VEF_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 99 of file Op_Dift_VEF_Face.h.
{
  Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
}
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Op_VEF_Face::modifier_pour_Cl(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
printOn()
Sortie & Op_Dift_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Reimplemented in Op_Dift_VEF_Face_Var.
Definition at line 43 of file Op_Dift_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Reimplemented in Op_Dift_VEF_Face_Var.
Definition at line 51 of file Op_Dift_VEF_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Dift_VEF_Face & Op_Dift_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
self_cast() [2/2]
Op_Dift_VEF_Face & Op_Dift_VEF_Face::self_cast (Objet_U & r) static
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
taille_memoire()
unsigned Op_Dift_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_VEF_Face_Var.
Definition at line 35 of file Op_Dift_VEF_Face.cpp.
Member Data Documentation
diffusivite_
Ref_Champ_base Op_Dift_VEF_Face::diffusivite_ protected
Definition at line 85 of file Op_Dift_VEF_Face.h.
Referenced by Op_Dift_Stab_VEF_Face_Var::associer_diffusivite(), Op_Dift_standard_VEF_Face_Var::associer_diffusivite(), associer_diffusivite(), and diffusivite().
grad_
DoubleTab Op_Dift_VEF_Face::grad_ mutable protected
grad DoubleTab grad_transp_;
Definition at line 87 of file Op_Dift_VEF_Face.h.
Referenced by Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), ajouter_cas_vectoriel(), and contribue_au_second_membre().
info_obj
const Type_info Op_Dift_VEF_Face::info_obj static
Definition at line 32 of file Op_Dift_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Dift_VEF_Face.h
src/VEF/Operateurs/Op_Dift_VEF_Face.cpp