TRUST: Terme_Source_Canal_RANS_LES_VDF_Face Class Reference
Terme_Source_Canal_RANS_LES_VDF_Face Class Reference
#include <Terme_Source_Canal_RANS_LES_VDF_Face.h>
Public Member Functions
Terme_Source_Canal_RANS_LES_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Terme_Source_Canal_RANS_LES_VDF_Face () override
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
void init_calcul_moyenne_spat ()
void init ()
DoubleTab norme_vit (void) const
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void moy_spat (DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &)
void calculer_integrale_temporelle (DoubleVect &, const DoubleVect &)
void ecriture_moy_spat (DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &)
void ecriture_moy_temp (DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, DoubleVect &, const double)
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Canal_RANS_LES_VDF_Face & self_cast (Objet_U &)
static const Terme_Source_Canal_RANS_LES_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
int moyenne
int cpt
int compteur_reprise
double alpha_tau
double Ly
double f_start
double t_av
int Nxy
int Nyy
int Nzy
DoubleTab tau
DoubleTab U_RANS
DoubleVect umoy_spat
DoubleVect umoy_x
DoubleVect umoy_y
DoubleVect umoy_z
DoubleVect umoy
DoubleVect utemp_gliss
DoubleVect utemp
DoubleVect utemp_sum
DoubleVect Yu
DoubleVect Yv
DoubleVect Yw
Coordonnees des points ou est definie la vitesse.
IntVect compt_x
IntVect compt_y
IntVect compt_z
Nombre de points a meme Y pour chaque grandeur.
IntVect corresp_u
IntVect corresp_v
IntVect corresp_w
Correspondance numerotation globale -> numerotation locale dans Yxx.
Nom nom_pb_rans
Detailed Description
Definition at line 38 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Canal_RANS_LES_VDF_Face()
Terme_Source_Canal_RANS_LES_VDF_Face::Terme_Source_Canal_RANS_LES_VDF_Face ()
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
~Terme_Source_Canal_RANS_LES_VDF_Face()
Terme_Source_Canal_RANS_LES_VDF_Face::~Terme_Source_Canal_RANS_LES_VDF_Face () override
Definition at line 34 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
// Le destructeur est appele a l'initialisation alors
// la sauvegarde du champ se fait hors initialisation
  if(umoy.size()!=0)
    {
      SFichier vit_sauv ("utemp_sum.dat");
      vit_sauv << utemp_sum;
      SFichier vit_sauv2 ("umoy.dat");
      vit_sauv2 << umoy;
    }
}
References TRUSTVect< _TYPE_ >::size(), umoy, and utemp_sum.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 1065 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_faces = zone_VDF.nb_faces();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const double tps = mon_equation->schema_temps().temps_courant();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  //  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double vol=0;
  SFichier fic_f("f.dat", ios::app);
  SFichier fic_finst("finst.dat", ios::app);
  //double mbf = 0.; //terme de forcage instantanne ponctuel
  //   double mbf2 = 0.; //terme de forcage moyenne
  //   int cpt2=0;
  //  static double beta=1000;
  // Calcul de la norme des vitesses au centre des elements
  DoubleTab norm=norme_vit();
  if((tps>dt_min)&&(tps>f_start))
    {
      for(int num_face = 0 ; num_face<nb_faces ; num_face++)
        {
          vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
          secmem(num_face) += ((U_RANS(num_face)-umoy(num_face))/(tau(num_face)*dt))
                              *(U_RANS(num_face)/norm(num_face))*vol;
          //                mbf2 += (((U_RANS(num_face)-umoy(num_face))
          //                         *(U_RANS(num_face)/norm(num_face)))
          //                        /(tau(num_face)*dt))*vol;
          //                cpt2++;
        }
      //mbf2 = mbf2/cpt2;
    }//fin if f_start
}
References f_start, la_zone_VDF, MorEqn::mon_equation, Zone_VF::nb_faces(), norme_vit(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Zone_VF::porosite_face(), Equation_base::schema_temps(), tau, Schema_Temps_base::temps_courant(), U_RANS, umoy, Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
associer_pb()
void Terme_Source_Canal_RANS_LES_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 165 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  ;
}
associer_zones()
void Terme_Source_Canal_RANS_LES_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 158 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Source_Canal_RANS_LES_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 1113 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References Source_base::ajouter().
calculer_integrale_temporelle()
void Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle (DoubleVect & moy_temp, const DoubleVect & moy)
Definition at line 547 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  double dt_v = mon_equation->schema_temps().pas_de_temps();
  if(je_suis_maitre())
    moy_temp.ajoute(dt_v,moy);
}
References TRUSTVect< _TYPE_ >::ajoute(), Process::je_suis_maitre(), MorEqn::mon_equation, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by mettre_a_jour().
cree_instance()
Objet_U * Terme_Source_Canal_RANS_LES_VDF_Face::cree_instance () static
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
dimensionner_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 58 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
{}
duplique()
int Terme_Source_Canal_RANS_LES_VDF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
ecriture_moy_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_spat (DoubleVect & champ_spat_x, DoubleVect & champ_spat_y, DoubleVect & champ_spat_z, DoubleVect & champ_spat_x_2, DoubleVect & champ_spat_y_2, DoubleVect & champ_spat_z_2)
Definition at line 554 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const double tps = mon_equation->schema_temps().temps_courant();
  Nom temps = Nom(tps);
  Nom nom_ficx ="moy_spat_force_x_";
  nom_ficx+= temps;
  nom_ficx+= ".dat";
  SFichier ficx(nom_ficx);
  Nom nom_ficy ="moy_spat_force_y_";
  nom_ficy+= temps;
  nom_ficy+= ".dat";
  SFichier ficy(nom_ficy);
  Nom nom_ficz ="moy_spat_force_z_";
  nom_ficz+= temps;
  nom_ficz+= ".dat";
  SFichier ficz(nom_ficz);
  for(int i=0 ; i<Nxy ; i++)
    ficx << Yu[i] << " " << champ_spat_x[i] << " " << sqrt(champ_spat_x_2[i]-champ_spat_x[i]*champ_spat_x[i]) << finl;
  for(int i=0 ; i<Nyy ; i++)
    ficy << Yv[i] << " " << champ_spat_y[i] << " " << sqrt(champ_spat_y_2[i]-champ_spat_y[i]*champ_spat_y[i]) << finl;
  for(int i=0 ; i<Nzy ; i++)
    ficz << Yw[i] << " " << champ_spat_z[i] << " " << sqrt(champ_spat_z_2[i]-champ_spat_z[i]*champ_spat_z[i]) << finl;
}
References finl, MorEqn::mon_equation, Nxy, Nyy, Nzy, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Yu, Yv, and Yw.
Referenced by mettre_a_jour().
ecriture_moy_temp()
void Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_temp (DoubleVect & champ_temp_x, DoubleVect & champ_temp_y, DoubleVect & champ_temp_z, DoubleVect & champ_temp_x_2, DoubleVect & champ_temp_y_2, DoubleVect & champ_temp_z_2, const double dt)
Definition at line 584 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const double tps = mon_equation->schema_temps().temps_courant();
  Nom temps = Nom(tps);
  Nom nom_ficx ="moy_temp_force_x_";
  nom_ficx+= temps;
  nom_ficx+= ".dat";
  SFichier ficx(nom_ficx);
  Nom nom_ficy ="moy_temp_force_y_";
  nom_ficy+= temps;
  nom_ficy+= ".dat";
  SFichier ficy(nom_ficy);
  Nom nom_ficz ="moy_temp_force_z_";
  nom_ficz+= temps;
  nom_ficz+= ".dat";
  SFichier ficz(nom_ficz);
  for(int i=0 ; i<Nxy ; i++)
    ficx << Yu[i] << " " << champ_temp_x[i]/dt << " " << sqrt(champ_temp_x_2[i]-champ_temp_x[i]*champ_temp_x[i])/dt << finl;
  for(int i=0 ; i<Nyy ; i++)
    ficy << Yv[i] << " " << champ_temp_y[i]/dt << " " << sqrt(champ_temp_y_2[i]-champ_temp_y[i]*champ_temp_y[i])/dt << finl;
  for(int i=0 ; i<Nzy ; i++)
    ficz << Yw[i] << " " << champ_temp_z[i]/dt << " " << sqrt(champ_temp_z_2[i]-champ_temp_z[i]*champ_temp_z[i])/dt << finl;
}
References finl, MorEqn::mon_equation, Nxy, Nyy, Nzy, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Yu, Yv, and Yw.
Referenced by mettre_a_jour().
get_info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
has_interface_blocs()
int Terme_Source_Canal_RANS_LES_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 60 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Face::info () static
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
init()
void Terme_Source_Canal_RANS_LES_VDF_Face::init ()
Definition at line 170 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  int nb_faces = zone_VDF.nb_faces();
  const double tps = mon_equation->schema_temps().temps_courant();
  int nb_elems = zone_VDF.nb_elem();
  int nb_faces_y = zone_VDF.nb_faces_Y();
  int Ny = nb_elems/(nb_faces_y-nb_elems);
  SFichier fic_moyx("moyx.dat");
  SFichier fic_moyy("moyy.dat");
  SFichier fic_moyz("moyz.dat");
  SFichier fic_ransx("ransx.dat");
  SFichier fic_ransy("ransy.dat");
  SFichier fic_ransz("ransz.dat");
  tau.resize(nb_faces);
  U_RANS.resize(nb_faces);
  umoy_spat.resize(nb_faces);
// champ_spat.resize(nb_faces);
  umoy_spat.resize(nb_faces);
  umoy_spat.resize(nb_faces);
  if (nom_pb_rans == "non_couple")
    {
      SFichier fic_verif("verif.RANS");
      EFichier fic_vit("vitesse_RANS.dat");
      for(int num_face=0 ; num_face<nb_faces ; num_face++)
        {
          int face;
          fic_vit >> face ;
          fic_vit >> U_RANS(face) ;
          fic_verif << face << " " << U_RANS(face) << finl;
        }
    }
  for(int num_face=0 ; num_face<nb_faces ; num_face++)
    {
      tau(num_face) = alpha_tau;
    }
  umoy_x.resize(Ny);
  umoy_y.resize(Ny+1);
  umoy_z.resize(Ny);
  umoy_x = 0.;
  umoy_y = 0.;
  umoy_z = 0.;
  init_calcul_moyenne_spat();
  utemp_gliss.resize(nb_faces);
  utemp.resize(nb_faces);
  utemp_gliss = 0.;
  utemp_gliss.resize(nb_faces);
  utemp.resize(nb_faces);
  utemp_sum.resize(nb_faces);
  utemp_gliss = 0.;
  utemp = 0.;
  utemp_sum = 0.;
  umoy.resize(nb_faces);
// Reprise
  if (tps > f_start)
    {
      EFichier vit_umoy ("utemp_sum.dat");
      EFichier vit_umoy2 ("umoy.dat");
      SFichier vit_reprise ("LES.reprise");
      SFichier vit_reprise2 ("LES2.reprise");
      int trash;
      vit_umoy >> trash;
      Cerr << "trash = " << trash << finl;
      vit_umoy2 >> trash;
      Cerr << "trash = " << trash << finl;
      for(int num_face = 0 ; num_face<nb_faces ; num_face++)
        {
          vit_umoy >> utemp_sum(num_face);
          vit_umoy2 >> umoy(num_face);
          vit_reprise << num_face << " " << utemp_sum(num_face) << finl;
          vit_reprise2 << num_face << " " << umoy(num_face) << finl;
        }
    }
  cpt = 0;
  compteur_reprise = 0;
}//fin init
References alpha_tau, Cerr, compteur_reprise, cpt, f_start, finl, Equation_base::inconnue(), init_calcul_moyenne_spat(), MorEqn::mon_equation, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VDF::nb_faces_Y(), nom_pb_rans, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Equation_base::schema_temps(), tau, Schema_Temps_base::temps_courant(), U_RANS, umoy, umoy_spat, umoy_x, umoy_y, umoy_z, utemp, utemp_gliss, utemp_sum, and Champ_Inc::zone_dis_base().
Referenced by readOn().
init_calcul_moyenne_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat ()
< nombre de y pour umoy
Definition at line 267 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  Cerr << "Debut initialisation des tableaux de moyenne spatiale..." << finl;
// On va initialiser les differents parametres membres de la classe
// utiles au calcul des differentes moyennes
// Initialisation de : Yu,Yv,Yw + compt_x,compt_y,compt_z
// + corresp_u,corresp_v,corresp_w
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xv = zone_VDF.xv();
  int nb_faces = zone_VDF.nb_faces();
  int nb_elems = zone_VDF.zone().nb_elem();
  int nb_faces_y = zone_VDF.nb_faces_Y();
  int Ny; //Nombre de maille en y + 1 (=nombre de faces)
  Ny = nb_elems/(nb_faces_y-nb_elems);
  Nxy = Ny;
  Nyy = Ny+1;
  Nzy = Ny;
  const IntVect& orientation = zone_VDF.orientation();
  int num_face,j,ori,indic,indicv,indicw,trouve;
  double y;
  j=0;
  indic = 0;
  indicv = 0;
  indicw = 0;
// dimensionnement aux valeurs rentrees dans le jeu de donnees
  Yu.resize(Nxy);
  Yv.resize(Nyy);
  Yw.resize(Nzy);
  compt_x.resize(Nxy);
  compt_y.resize(Nyy);
  compt_z.resize(Nzy);
// champ_spat.resize(nb_faces);
// champ_spat_x.resize(Nxy);
// champ_spat_y.resize(Nyy);
// champ_spat_z.resize(Nzy);
// champ_spat_x_2.resize(Nxy);
// champ_spat_y_2.resize(Nyy);
// champ_spat_z_2.resize(Nzy);
  corresp_u.resize(nb_faces);
  corresp_v.resize(nb_faces);
  corresp_w.resize(nb_faces);
// initialisation
  Yu = -100.;
  Yv = -100.;
  Yw = -100.;
  compt_x = 0;
  compt_y = 0;
  compt_z = 0;
  corresp_u = -1;
  corresp_v = -1;
  corresp_w = -1;
// remplissage des tableaux ci-dessus
// Pour le calcul de u, v, w sur les plans d hmogeneite
  for (num_face=0; num_face<nb_faces; num_face++)
    {
      ori = orientation(num_face);
      switch(ori)
        {
        case 0 :
          {
            y = xv(num_face,1);
            trouve = 0;
            for (j=0; j<indic+1; j++)
              {
                if(y==Yu[j])
                  {
                    corresp_u[num_face] = j;
                    compt_x[j] ++;
                    j=indic+1;
                    trouve = 1;
                    break;
                  }
              }
            if (trouve==0)
              {
                corresp_u[num_face] = indic;
                Yu[indic]=y;
                compt_x[indic] ++;
                indic++;
              }
            break;
          }
        case 1 :
          {
            y = xv(num_face,1);
            trouve = 0;
            for (j=0; j<indicv+1; j++)
              {
                if(y==Yv[j])
                  {
                    corresp_v[num_face] = j;
                    compt_y[j] ++;
                    j = indicv+1;
                    trouve = 1;
                    break;
                  }
              }
            if (trouve==0)
              {
                corresp_v[num_face] = indicv;
                Yv[indicv]=y;
                compt_y[indicv] ++;
                indicv++;
              }
            break;
          }
        case 2 :
          {
            y = xv(num_face,1);
            trouve = 0;
            for (j=0; j<indicw+1; j++)
              {
                if(y==Yw[j])
                  {
                    corresp_w[num_face] = j;
                    compt_z[j] ++;
                    j = indicw+1;
                    trouve = 1;
                    break;
                  }
              }
            if (trouve==0)
              {
                Yw[indicw]=y;
                corresp_w[num_face] = indicw;
                compt_z[indicw] ++;
                indicw++;
              }
            break;
          }
        default :
          {
            Cerr << "Cas de figure impossible!!" << finl;
            exit();
            break;
          }
        }
    }
  Nxy = indic;  //!< nombre de y pour umoy
  Nyy = indicv;
  Nzy = indicw;
  Cerr << "Initialisation des tableaux de moyenne spatiale : OK" << finl;
}
References Cerr, compt_x, compt_y, compt_z, corresp_u, corresp_v, corresp_w, Process::exit(), finl, Equation_base::inconnue(), MorEqn::mon_equation, Zone::nb_elem(), Zone_VF::nb_faces(), Zone_VDF::nb_faces_Y(), Nxy, Nyy, Nzy, Zone_VDF::orientation(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Zone_VF::xv(), Yu, Yv, Yw, Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by init().
mettre_a_jour()
void Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 615 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
// Cerr << "Je suis dans le mettre_a_jour" << finl;
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double tps = mon_equation->schema_temps().temps_courant();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  const IntVect& orientation = zone_VDF.orientation();
  int nb_elems = zone_VDF.nb_elem();
  int nb_faces = zone_VDF.nb_faces();
  int nb_faces_x = zone_VDF.nb_faces_X();
  int nb_faces_y = zone_VDF.nb_faces_Y();
  int nb_faces_z = zone_VDF.nb_faces_Z();
// static double duree = 0;
  double vit;
  SFichier fic_moyx("moyx.dat");
  SFichier fic_moyy("moyy.dat");
  SFichier fic_moyz("moyz.dat");
  SFichier fic_f("f.dat", ios::app);
  SFichier fic_fface("force_face.dat", ios::app);
  const DoubleTab& xv = zone_VDF.xv();
  //****************************************************
  //******* MaJ de la vitesse cible (RANS) ***********
  //**************************************************
  if(nom_pb_rans != "non_couple")
    {
      REF(Probleme_base) pb_rans;
      Objet_U& obj=Interprete::objet(nom_pb_rans);
      if( sub_type(Probleme_base, obj) )
        {
          pb_rans = ref_cast(Probleme_base, obj);
        }
      U_RANS = pb_rans.valeur().equation(0).inconnue().valeurs();
    }
  //***************************************************
  if(moyenne==0)
    {
      if(tps>(f_start))
        {
          //******************************************************
          //*************** MOYENNE SPATIALE *********************
          //******************************************************
          int num_face,Nx, Ny, Nz, j;
          umoy_x = 0;
          umoy_y = 0;
          umoy_z = 0;
          Nx = nb_elems/(nb_faces_x-nb_elems); //nbre de maille
          Ny = nb_elems/(nb_faces_y-nb_elems);
          Nz = nb_elems/(nb_faces_z-nb_elems);
          for (num_face=0; num_face<nb_faces; num_face++)
            {
              int ori = orientation[num_face];
              vit = vitesse[num_face];
              if (ori==0)
                {
                  j=corresp_u[num_face];
                  umoy_x[j] += vit/((Nx+1)*Nz);
                }
              else if (ori==1)
                {
                  j=corresp_v[num_face];
                  umoy_y[j] += vit/(Nx*Nz);
                }
              else if (ori==2)
                {
                  j=corresp_w[num_face];
                  umoy_z[j] += vit/(Nx*(Nz+1));
                }
            }
          //       // Ecriture des profils moyens
          int i;
          for (i=0 ; i<Ny ; i++)
            {
              fic_moyx << i << " " << umoy_x(i) << finl;
            }
          for (i=0 ; i<Ny+1 ; i++)
            {
              fic_moyy << i << " " << umoy_y(i) << finl;
            }
          for (i=0 ; i<Ny ; i++)
            {
              fic_moyz << i << " " << umoy_z(i) << finl;
            }
          // Redistribution du profil moyen spatial sur tout le champ de vitesse
          for(num_face = 0 ; num_face<nb_faces ; num_face++)
            {
              int ori = orientation(num_face);
              if (ori==0)
                {
                  j = corresp_u(num_face);
                  umoy(num_face) = umoy_x(j);
                }
              else if (ori==1)
                {
                  j = corresp_v(num_face);
                  umoy(num_face) = umoy_y(j);
                }
              else if (ori==2)
                {
                  j = corresp_w(num_face);
                  umoy(num_face) = umoy_z(j);
                }
              else
                Cerr << "Erreur orientation dans la redistribution de la moy. spat. de SouCanRANS_LESVDFFa" << finl;
            }
          //******************************************************
          //************** FIN MOYENNE SPATIALE ******************
          //******************************************************
        }
    }//fin if moyenne = 0
  else if(moyenne==1)
    {
      //****************************************************************
      //*************** MOYENNE TEMPORELLE GLISSANTE *******************
      //****************************************************************
      //Initialisation de la moyenne temp glissante
      //avec une moyenne temporelle classique
      //       if(/*(tps>(f_start-t_av))&&*/(tps<f_start))
      //         {
      //           if (cpt==0)
      //             {
      //               for (int num_face=0;num_face<nb_faces;num_face++)
      //                 {
      //                   utemp_gliss(num_face) = vitesse(num_face)*(tps-(f_start-t_av));
      //                   umoy(num_face) = vitesse(num_face);
      //                 }
      //               cpt = 1;
      //             }
      //           else
      //             {
      //               for (int num_face=0;num_face<nb_faces;num_face++)
      //                 {
      //                   utemp_gliss(num_face) += vitesse(num_face)*dt;
      //                   umoy(num_face) = utemp_gliss(num_face)/(tps-(f_start-t_av));
      //                 }
      //             }
      //         }
      //Calcul d'une premiere moyenne temporelle significative
      //       if((tps>(f_start-t_av))&&(tps<f_start))
      //         {
      //           if (cpt==0)
      //             {
      //               for (int num_face=0;num_face<nb_faces;num_face++)
      //                 {
      //                   utemp_sum(num_face) = vitesse(num_face)*(tps-(f_start-t_av)+dt);
      //                   umoy(num_face) = vitesse(num_face);
      //                 }
      //               cpt = 3;
      //             }
      //           else
      //             {
      //               for (int num_face=0;num_face<nb_faces;num_face++)
      //                 {
      //                   utemp_sum(num_face) += vitesse(num_face)*dt;
      //                   umoy(num_face) = utemp_sum(num_face)/(tps-(f_start-t_av)+dt);
      //                 }
      //             }
      //           //fic_f << tps << " " << utemp_sum(123) << " " << umoy(123) << finl;
      //         }
      //Calcul de la moyenne temporelle glissante
      //t_av est le temps d'integration de la moyenne temp glissante
      //       if(tps>=f_start)
      //         {
      //           for (int num_face=0 ; num_face<nb_faces ; num_face++)
      //             {
      //               if(cpt==1)
      //                 {
      //                   umoy(num_face) = vitesse(num_face);
      //                 }
      //               else if(tps <= t_av)
      //                 {
      //                   umoy(num_face) = (dt/tps)*vitesse(num_face)
      //                     +(1-(dt/tps))*umoy(num_face);
      //                   cpt=2;
      //                 }
      //               else
      //                 {
      //                   umoy(num_face) = (dt/t_av)*vitesse(num_face)
      //                     +(1-(dt/t_av))*umoy(num_face);
      //                 }
      //             }
      //         }
      if(tps>dt_min)
        {
          if (cpt==0)
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  utemp_sum(num_face) = vitesse(num_face)*dt;
                  umoy(num_face) = vitesse(num_face);
                }
              cpt++;
            }
          else if (tps <= t_av)
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  utemp_sum(num_face) += vitesse(num_face)*dt;
                  umoy(num_face) = utemp_sum(num_face)/(tps-dt_min);
                }
            }
          else
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  umoy(num_face) = (dt/t_av)*vitesse(num_face)
                                   +(1-(dt/t_av))*umoy(num_face);
                }
            }
          fic_f << tps << " " << dt << " " << tps-dt_min << " "<< utemp_sum(123);
          fic_f << " " << umoy(123) << " " << vitesse(123) << " " << U_RANS(123) << finl;
        }
      //****************************************************************
      //*************** FIN MOYENNE TEMPORELLE GLISSANTE ***************
      //****************************************************************
    }// fin moyenne = 1
  else if(moyenne==2)
    {
      //******************************************************
      //*************** MOYENNE TEMPORELLE *******************
      //******************************************************
      //Calcul d'une premiere moyenne temporelle significative
      //       if((tps>=f_start)/*&&(tps<f_start)*/)
      //         {
      //           if (cpt==0)
      //             {
      //               for (int num_face=0;num_face<nb_faces;num_face++)
      //                 {
      //                   //utemp_sum(num_face) = vitesse(num_face)*(tps-f_start+dt);
      //                   umoy(num_face) = vitesse(num_face);
      //                 }
      //               cpt = 3;
      //             }
      //           else
      //             {
      //           for (int num_face=0;num_face<nb_faces;num_face++)
      //             {
      //               utemp_sum(num_face) += vitesse(num_face)*dt;
      //               umoy(num_face) = utemp_sum(num_face)/(tps-f_start+dt);
      //             }
      //            }
      //fic_f << tps << " " << utemp_sum(123) << " " << umoy(123) << finl;
      //         }
      if(tps>dt_min)
        {
          if (cpt==0)
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  utemp_sum(num_face) = vitesse(num_face)*dt;
                  umoy(num_face) = vitesse(num_face);
                }
              cpt++;
            }
          else
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  utemp_sum(num_face) += vitesse(num_face)*dt;
                  umoy(num_face) = utemp_sum(num_face)/(tps-dt_min);
                }
            }
          fic_f << tps << " " << dt << " " << tps-dt_min << " "<< utemp_sum(123);
          fic_f << " " << umoy(123) << " " << vitesse(123) << " " << U_RANS(123) << finl;
        }
      //       if(tps>=f_start)
      //         {
      //           for (int num_face=0;num_face<nb_faces;num_face++)
      //             {
      //                 utemp_sum(num_face) += dt*vitesse(num_face);
      //                 umoy(num_face)=utemp_sum(num_face)/(tps-f_start+dt);
      //             }
      //           cpt=4;
      //         }
      //***********************************************************
      //*************** FIN MOYENNE TEMPORELLE  ***************
      //*******************************************************
    }
  else if(moyenne==3)
    {
      if (tps>0)
        {
          if (cpt==0)
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  //                   duree=100*dt;
                  //                   utemp_sum(num_face) = vitesse(num_face)*duree;
                  //                   duree-=dt;
                  //                   umoy(num_face) = utemp_sum(num_face)/(tps-dt_min+duree);
                  //                   Cerr << "nb_faces = "<< nb_faces << finl;
                  //                   Cerr << "num_face = "<< num_face << finl;
                  utemp_sum(num_face) = vitesse(num_face)*dt;
                  umoy(num_face) = vitesse(num_face);
                }
              cpt ++;
            }
          else
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                {
                  utemp_sum(num_face) += vitesse(num_face)*dt;
                  umoy(num_face) = utemp_sum(num_face)/(tps-dt_min+dt);
                }
            }
        }
    }
  else
    {
      Cerr << "moyenne = " << moyenne << finl;
      Cerr << "Probleme pour le choix du type de moyenne" << finl;
    }
  compteur_reprise++;
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  DoubleVect force(nb_faces);
  DoubleVect force_x(nb_faces);
  DoubleVect force_y(nb_faces);
  DoubleVect force_z(nb_faces);
  DoubleVect force_x_2(nb_faces);
  DoubleVect force_y_2(nb_faces);
  DoubleVect force_z_2(nb_faces);
  DoubleVect force_x_temp(nb_faces);
  DoubleVect force_y_temp(nb_faces);
  DoubleVect force_z_temp(nb_faces);
  DoubleVect force_x_temp_2(nb_faces);
  DoubleVect force_y_temp_2(nb_faces);
  DoubleVect force_z_temp_2(nb_faces);
  double vol=0;
  DoubleTab norm=norme_vit();
  for(int num_face = 0 ; num_face<nb_faces ; num_face++)
    {
      vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
      force(num_face) = ((U_RANS(num_face)-umoy(num_face))/(dt))
                        *(U_RANS(num_face)/norm(num_face))*vol;
    }
  moy_spat(force, force_x, force_y, force_z, force_x_2, force_y_2, force_z_2);
  calculer_integrale_temporelle(force_x_temp, force_x);
  calculer_integrale_temporelle(force_y_temp, force_y);
  calculer_integrale_temporelle(force_z_temp, force_z);
  calculer_integrale_temporelle(force_x_temp_2, force_x_2);
  calculer_integrale_temporelle(force_y_temp_2, force_y_2);
  calculer_integrale_temporelle(force_z_temp_2, force_z_2);
  // Voir Schema_Temps_base::limpr pour information sur epsilon et modf
  double i, j, epsilon = 1.e-8;
  double dt_post_inst=2.;
  double tps_stats=10.;
  modf((tps+dt)/dt_post_inst + epsilon, &i);
  modf(tps/dt_post_inst + epsilon, &j);
  if(i>j)
    {
      ecriture_moy_spat(force_x, force_y, force_z, force_x_2, force_y_2, force_z_2);
      if(tps>tps_stats)
        ecriture_moy_temp(force_x_temp, force_y_temp, force_z_temp,
                          force_x_temp_2, force_y_temp_2, force_z_temp_2, tps-tps_stats);
    }
  //////////////////////////////////////////
  //developpement a nettoyer apres la these
  //////////////////////////////////////////
  int num_face = 123;
  static int cpt_sonde=0;
  if(cpt_sonde==0)
    {
      for(int face = 0 ; face<nb_faces ; face++)
        {
          if((xv(face,1) > 1.1)&&(xv(face,1) < 0.9)&&(orientation(face)==0))
            num_face=face;
        }
      fic_fface << "# " << num_face << " "<< orientation(num_face)
                << " " << xv(num_face,0) << " " << xv(num_face,1) <<  " " << xv(num_face,2) << finl;
      fic_f << "# " << num_face << " "<< orientation(num_face)
            << " " << xv(num_face,0) << " " << xv(num_face,1) <<  " " << xv(num_face,2) << finl;
      cpt_sonde++;
    }
  fic_fface <<  tps << " " << vitesse(num_face) << " " << force(num_face) << finl;
  //////////////////////////////////////////////////////////
}//fin mettre_a_jour
References calculer_integrale_temporelle(), Cerr, compteur_reprise, corresp_u, corresp_v, corresp_w, cpt, ecriture_moy_spat(), ecriture_moy_temp(), f_start, finl, Equation_base::inconnue(), la_zone_VDF, MorEqn::mon_equation, moy_spat(), moyenne, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VDF::nb_faces_X(), Zone_VDF::nb_faces_Y(), Zone_VDF::nb_faces_Z(), nom_pb_rans, norme_vit(), Interprete::objet(), Zone_VDF::orientation(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Zone_VF::porosite_face(), REF, ref_cast, Equation_base::schema_temps(), sub_type, t_av, Schema_Temps_base::temps_courant(), U_RANS, umoy, umoy_x, umoy_y, umoy_z, utemp_sum, Ref_Zone_VDF::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes_entrelaces(), and Zone_VF::xv().
moy_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat (DoubleVect & champ, DoubleVect & champ_spat_x, DoubleVect & champ_spat_y, DoubleVect & champ_spat_z, DoubleVect & champ_spat_x_2, DoubleVect & champ_spat_y_2, DoubleVect & champ_spat_z_2)
Definition at line 484 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntVect& orientation = zone_VDF.orientation();
  int nb_faces = zone_VDF.nb_faces();
  int j=-1;
  compt_x=0;
  compt_y=0;
  compt_z=0;
  for (int num_face=0; num_face<nb_faces; num_face++)
    {
      int ori = orientation[num_face];
      if(ori==0)
        {
          j=corresp_u[num_face];
          champ_spat_x[j] += champ(num_face);
          champ_spat_x_2[j] += champ(num_face)*champ(num_face);
          compt_x[j]++;
        }
      if(ori==1)
        {
          j=corresp_v[num_face];
          champ_spat_y[j] += champ(num_face);
          champ_spat_y_2[j] += champ(num_face)*champ(num_face);
          compt_y[j]++;
        }
      if(ori==2)
        {
          j=corresp_w[num_face];
          champ_spat_z[j] += champ(num_face);
          champ_spat_z_2[j] += champ(num_face)*champ(num_face);
          compt_z[j]++;
        }
    }
  for(j=0; j<Nxy; j++)
    {
      champ_spat_x[j] = champ_spat_x[j]/compt_x[j];
      champ_spat_x_2[j] = champ_spat_x_2[j]/compt_x[j];
    }
  for(j=0; j<Nyy; j++)
    {
      champ_spat_y[j] = champ_spat_y[j]/compt_y[j];
      champ_spat_y_2[j] = champ_spat_y_2[j]/compt_y[j];
    }
  for(j=0; j<Nzy; j++)
    {
      champ_spat_z[j] = champ_spat_z[j]/compt_z[j];
      champ_spat_z_2[j] = champ_spat_z_2[j]/compt_z[j];
    }
}
References compt_x, compt_y, compt_z, corresp_u, corresp_v, corresp_w, la_zone_VDF, Zone_VF::nb_faces(), Nxy, Nyy, Nzy, Zone_VDF::orientation(), and Ref_Zone_VDF::valeur().
Referenced by mettre_a_jour().
norme_vit()
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit (void) const
Definition at line 431 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elems = zone_VDF.nb_elem();
  int nb_faces = zone_VDF.nb_faces();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  DoubleVect norme_vit_elem(nb_elems);
  norme_vit_elem.resize(nb_faces);
  double vit1, vit2, vit3;
  DoubleTab norme(nb_faces);
  for(int num_elem = 0 ; num_elem<nb_elems ; num_elem++)
    {
// WARNING 3D ONLY !!!!!!
      int face1 = elem_faces(num_elem,0);
      int face2 = elem_faces(num_elem,3);
      int face3 = elem_faces(num_elem,1);
      int face4 = elem_faces(num_elem,4);
      int face5 = elem_faces(num_elem,2);
      int face6 = elem_faces(num_elem,5);
// Cerr << "face1 = "<<face1<<finl;
// Cerr << "face2 = "<<face2<<finl;
// Cerr << "U_RANS(face1) = "<< U_RANS(face1) <<finl;
// Cerr << "U_RANS(face2) = "<< U_RANS(face2) <<finl;
      vit1 = 0.5*(U_RANS(face1)+U_RANS(face2));
      vit2 = 0.5*(U_RANS(face3)+U_RANS(face4));
      vit3 = 0.5*(U_RANS(face5)+U_RANS(face6));
      norme_vit_elem(num_elem) = sqrt(vit1*vit1 + vit2*vit2 + vit3*vit3);
    }
// Redistribution de la norme sur les faces
  for(int num_face = 0 ; num_face<nb_faces ; num_face++)
    {
      int elem0 = face_voisins(num_face,0);
      int elem1 = face_voisins(num_face,1);
      if(elem0==-1)
        norme(num_face) = norme_vit_elem(elem1);
      else if(elem1==-1)
        norme(num_face) = norme_vit_elem(elem0);
      else
        norme(num_face) = 0.5*(norme_vit_elem(elem0)+norme_vit_elem(elem1));
    }
  return norme;
}
References Zone_VF::elem_faces(), Zone_VF::face_voisins(), la_zone_VDF, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), norme(), TRUSTVect< _TYPE_ >::resize(), U_RANS, and Ref_Zone_VDF::valeur().
Referenced by ajouter_blocs(), and mettre_a_jour().
printOn()
Sortie & Terme_Source_Canal_RANS_LES_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 51 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_RANS_LES_VDF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 60 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
{
  int compteur = 0;
  Motcle mot_lu;
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  nom_pb_rans="non_couple";
  t_av=-1;
  f_start = 0.;
  moyenne = 0;//valeur par defaut
// 0 => moyenne spatiale
// 1 => moyenne temporelle glissante (moyenne en alpha)
// 2 => moyenne temporelle commence a t=f_start-t_av
// 3 => moyenne temporelle commence a t=0 (mettre valeur positive a t_av dans .data)
  Motcles les_mots(6);
  {
    les_mots[0]="alpha_tau"; //coeff de relaxation du terme source
    les_mots[1]="Ly"; //Hauteur du canal plan (utile pour la moyenne spatiale)
    les_mots[2]="f_start"; //temps a partir duquel le terme source est active
    les_mots[3]="t_av"; //temps de prise de moyenne (moyenne temporelle glissante)
    les_mots[4]="type_moyenne"; //temps de prise de moyenne (moyenne temporelle glissante)
    les_mots[5]="nom_pb_rans";
  }
  is >> mot_lu;
  if(mot_lu != acc_ouverte)
    {
      Cerr << "On attendait { a la place de " << mot_lu
           << " lors de la lecture des parametres de la loi de paroi " << finl;
    }
  is >> mot_lu;
  while(mot_lu != acc_fermee)
    {
      int rang=les_mots.search(mot_lu);
      switch(rang)
        {
        case 0 :
          is >> alpha_tau;
          Cerr << "alpha_tau = " << alpha_tau << finl;
          compteur++;
          break;
        case 1  :
          is >> Ly;
          Cerr << "Ly = "<< Ly << finl;
          compteur++;
          break;
        case 2  :
          is >> f_start;
          Cerr << "f_start = "<< f_start << finl;
          compteur++;
          break;
        case 3  :
          is >> t_av;
          Cerr << "t_av = " << t_av << finl;
          Cerr << "type_moyenne : " << moyenne << finl;
          if((moyenne==1)&&(t_av<=0))
            {
              Cerr << "La periode en temps de la moyenne temporelle glissante est non precisee !"
                   << finl;
              exit();
            }
          compteur++;
          break;
        case 4  :
          is >> moyenne;
          Cerr << "type_moyenne : " << moyenne << finl;
          if((moyenne==1)&&(t_av<=0))
            {
              Cerr << "La periode en temps de la moyenne temporelle glissante est non precisee !"
                   << finl;
              exit();
            }
          compteur++;
          break;
        case 5  :
          is >> nom_pb_rans;
          compteur++;
          break;
        default :
          {
            Cerr << mot_lu << " n'est pas un mot compris" << finl;
            Cerr << "Les mots compris sont : " << les_mots << finl;
            exit();
          }
        }
      is >> mot_lu;
    }
  Cerr << "nom_pb_rans = " << nom_pb_rans << finl;
  Cerr << compteur << " motcles ont ete lus dans le readOn" << finl;
  init();
  return is;
}
References alpha_tau, Cerr, compteur, Process::exit(), f_start, finl, init(), Ly, moyenne, nom_pb_rans, Motcles::search(), and t_av.
self_cast() [1/2]
const Terme_Source_Canal_RANS_LES_VDF_Face & Terme_Source_Canal_RANS_LES_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
self_cast() [2/2]
Terme_Source_Canal_RANS_LES_VDF_Face & Terme_Source_Canal_RANS_LES_VDF_Face::self_cast (Objet_U & r) static
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Canal_RANS_LES_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Terme_Source_Canal_RANS_LES_VDF_Face.cpp.
Member Data Documentation
alpha_tau
double Terme_Source_Canal_RANS_LES_VDF_Face::alpha_tau private
Definition at line 73 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and readOn().
compt_x
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::compt_x private
Definition at line 97 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), and moy_spat().
compt_y
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::compt_y private
Definition at line 97 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), and moy_spat().
compt_z
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::compt_z private
Nombre de points a meme Y pour chaque grandeur.
Definition at line 97 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), and moy_spat().
compteur_reprise
int Terme_Source_Canal_RANS_LES_VDF_Face::compteur_reprise private
Definition at line 72 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and mettre_a_jour().
corresp_u
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::corresp_u private
Definition at line 98 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), mettre_a_jour(), and moy_spat().
corresp_v
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::corresp_v private
Definition at line 98 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), mettre_a_jour(), and moy_spat().
corresp_w
IntVect Terme_Source_Canal_RANS_LES_VDF_Face::corresp_w private
Correspondance numerotation globale -> numerotation locale dans Yxx.
Definition at line 98 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init_calcul_moyenne_spat(), mettre_a_jour(), and moy_spat().
cpt
int Terme_Source_Canal_RANS_LES_VDF_Face::cpt private
Definition at line 72 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and mettre_a_jour().
f_start
double Terme_Source_Canal_RANS_LES_VDF_Face::f_start private
Definition at line 74 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and readOn().
info_obj
const Type_info Terme_Source_Canal_RANS_LES_VDF_Face::info_obj static
Definition at line 40 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Source_Canal_RANS_LES_VDF_Face::la_zone_Cl_VDF protected
Definition at line 68 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by associer_zones().
la_zone_VDF
Ref_Zone_VDF Terme_Source_Canal_RANS_LES_VDF_Face::la_zone_VDF protected
Definition at line 67 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ajouter_blocs(), associer_zones(), mettre_a_jour(), moy_spat(), and norme_vit().
Ly
double Terme_Source_Canal_RANS_LES_VDF_Face::Ly private
Definition at line 73 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by readOn().
moyenne
int Terme_Source_Canal_RANS_LES_VDF_Face::moyenne private
Definition at line 71 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by mettre_a_jour(), and readOn().
nom_pb_rans
Nom Terme_Source_Canal_RANS_LES_VDF_Face::nom_pb_rans private
Definition at line 100 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), mettre_a_jour(), and readOn().
Nxy
int Terme_Source_Canal_RANS_LES_VDF_Face::Nxy private
Definition at line 76 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), init_calcul_moyenne_spat(), and moy_spat().
Nyy
int Terme_Source_Canal_RANS_LES_VDF_Face::Nyy private
Definition at line 76 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), init_calcul_moyenne_spat(), and moy_spat().
Nzy
int Terme_Source_Canal_RANS_LES_VDF_Face::Nzy private
Definition at line 76 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), init_calcul_moyenne_spat(), and moy_spat().
t_av
double Terme_Source_Canal_RANS_LES_VDF_Face::t_av private
Definition at line 74 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by mettre_a_jour(), and readOn().
tau
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Face::tau private
Definition at line 78 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ajouter_blocs(), and init().
U_RANS
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Face::U_RANS private
Definition at line 79 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and norme_vit().
umoy
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::umoy private
Definition at line 82 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and ~Terme_Source_Canal_RANS_LES_VDF_Face().
umoy_spat
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::umoy_spat private
Definition at line 81 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init().
umoy_x
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::umoy_x private
Definition at line 81 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and mettre_a_jour().
umoy_y
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::umoy_y private
Definition at line 82 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and mettre_a_jour().
umoy_z
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::umoy_z private
Definition at line 82 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), and mettre_a_jour().
utemp
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::utemp private
Definition at line 94 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init().
utemp_gliss
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::utemp_gliss private
Definition at line 94 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init().
utemp_sum
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::utemp_sum private
Definition at line 94 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by init(), mettre_a_jour(), and ~Terme_Source_Canal_RANS_LES_VDF_Face().
Yu
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::Yu private
Definition at line 96 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), and init_calcul_moyenne_spat().
Yv
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::Yv private
Definition at line 96 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), and init_calcul_moyenne_spat().
Yw
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Face::Yw private
Coordonnees des points ou est definie la vitesse.
Definition at line 96 of file Terme_Source_Canal_RANS_LES_VDF_Face.h.
Referenced by ecriture_moy_spat(), ecriture_moy_temp(), and init_calcul_moyenne_spat().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Canal_RANS_LES_VDF_Face.h
src/VDF/Sources/Terme_Source_Canal_RANS_LES_VDF_Face.cpp