TRUST: Sortie_libre_Text_H_ext Class Reference
Sortie_libre_Text_H_ext Class Reference
classe Neumann_sortie_libre
Cette classe represente une frontiere ouverte sans vitesse imposee
Pour les equations de Navier_Stokes on impose necessairement
la pression sur une telle frontiere
Pour traiter l'hydraulique, on derive donc de la classe
Neumann_sortie_libre la classe Sortie_libre_pression_imposee
Les conditions aux limites de type Neumann_sortie_libre ou des
types derives se traduisent par des flux diffusifs nuls.
En revanche, le traitement des flux convectifs impose de connaitre
le champ convecte a l'exterieur de la frontiere en cas de re-entree
de fluide. C'est pourquoi la classe porte un Champ_front<br>(membre le_champ_ext).
Dans les operateurs de calcul, les conditions aux limites
de type Neumann_sortie_libre et des types derives seront traites
de maniere identique
#include <Sortie_libre_Text_H_ext.h>
Public Member Functions
Sortie_libre_Text_H_ext ()
~Sortie_libre_Text_H_ext ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual double val_ext (int i) const
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
virtual double val_ext (int i, int j) const
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_Text_H_ext sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration ou bien indetermine.
void bascule_cond_lim_en_enthalpie ()
void bascule_cond_lim_en_temperature ()
double flux_impose (int i) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere.
double flux_impose (int i, int j) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Sortie_libre_Text_H_ext & self_cast (Objet_U &)
static const
Sortie_libre_Text_H_ext & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Protected Attributes
Champ_front le_champ_Text
Champ_front le_champ_hext
int type_cond_lim
Detailed Description
classe Neumann_sortie_libre
Cette classe represente une frontiere ouverte sans vitesse imposee
Pour les equations de Navier_Stokes on impose necessairement
la pression sur une telle frontiere
Pour traiter l'hydraulique, on derive donc de la classe
Neumann_sortie_libre la classe Sortie_libre_pression_imposee
Les conditions aux limites de type Neumann_sortie_libre ou des
types derives se traduisent par des flux diffusifs nuls.
En revanche, le traitement des flux convectifs impose de connaitre
le champ convecte a l'exterieur de la frontiere en cas de re-entree
de fluide. C'est pourquoi la classe porte un Champ_front<br>(membre le_champ_ext).
Dans les operateurs de calcul, les conditions aux limites
de type Neumann_sortie_libre et des types derives seront traites
de maniere identique
Definition at line 52 of file Sortie_libre_Text_H_ext.h.
Constructor & Destructor Documentation
Sortie_libre_Text_H_ext::Sortie_libre_Text_H_ext ()
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
Sortie_libre_Text_H_ext::~Sortie_libre_Text_H_ext ()
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
Member Function Documentation
void Sortie_libre_Text_H_ext::bascule_cond_lim_en_enthalpie () [inline]
Definition at line 76 of file Sortie_libre_Text_H_ext.h.
References type_cond_lim.
{
  type_cond_lim = 1;
}
void Sortie_libre_Text_H_ext::bascule_cond_lim_en_temperature () [inline]
Definition at line 81 of file Sortie_libre_Text_H_ext.h.
References type_cond_lim.
{
  type_cond_lim = 0;
}
int Sortie_libre_Text_H_ext::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_Text_H_ext sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Definition at line 326 of file Sortie_libre_Text_H_ext.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle KEPS="Transport_Keps";
  Motcle Thermique="Thermique";
  Motcle Concentration="Concentration";
  Motcle indetermine="indetermine";
  if ( (dom_app==KEPS) || (dom_app==indetermine) ||
       (dom_app==Thermique) || (dom_app==Concentration) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Sortie_libre_Text_H_ext::cree_instance () [static]
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
int Sortie_libre_Text_H_ext::duplique () const [virtual]
Implements Neumann.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
double Sortie_libre_Text_H_ext::flux_impose (int i, int j) const [virtual]
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 281 of file Sortie_libre_Text_H_ext.cpp.
References DoubleTab::dimension(), le_champ_hext, le_champ_Text, type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Condition limite en temperature
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en temperature2"<<finl;
      if (le_champ_Text.valeurs().dimension(0)==1)
        return le_champ_Text(0,j);
      else
        return le_champ_Text(i,j);
    }
  else
    {
// Condition limite en enthalpie
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en enthalpie2"<<finl;
      if (le_champ_hext.valeurs().dimension(0)==1)
        return le_champ_hext(0,j);
      else
        return le_champ_hext(i,j);
    }
}
double Sortie_libre_Text_H_ext::flux_impose (int i) const [virtual]
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 230 of file Sortie_libre_Text_H_ext.cpp.
References Cerr, DoubleTab::dimension(), Process::exit(), finl, le_champ_hext, le_champ_Text, DoubleVect::size(), type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en temperature"<<finl;
      if (le_champ_Text.valeurs().size()==1)
        return le_champ_Text(0,0);
      else if (le_champ_Text.valeurs().dimension(1)==1)
        return le_champ_Text(i,0);
      else
        Cerr << "Sortie_libre_Text_H_ext::flux_impose" << finl;
      exit();
      return 0.;
    }
  else
    {
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en enthalpie"<<finl;
      if (le_champ_hext.valeurs().size()==1)
        return le_champ_hext(0,0);
      else if (le_champ_hext.valeurs().dimension(1)==1)
        return le_champ_hext(i,0);
      else
        Cerr << "Sortie_libre_Text_H_ext::flux impose" << finl;
      exit();
      return 0.;
    }
}
const Type_info * Sortie_libre_Text_H_ext::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
const Type_info * Sortie_libre_Text_H_ext::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
Sortie & Sortie_libre_Text_H_ext::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann.
Definition at line 43 of file Sortie_libre_Text_H_ext.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Sortie_libre_Text_H_ext::readOn (Entree & s) [protected, virtual]
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann.
Definition at line 67 of file Sortie_libre_Text_H_ext.cpp.
References Cerr, Process::exit(), finl, Cond_lim_base::le_champ_front, le_champ_hext, le_champ_Text, Objet_U::que_suis_je(), Motcles::search(), and Deriv_::typer().
{
  le_champ_front.typer("Champ_front_uniforme");
  le_champ_Text.typer("Champ_front_uniforme");
  le_champ_hext.typer("Champ_front_uniforme");
  Motcle motlu;
  Motcles les_motcles(5);
  {
    les_motcles[0] = "T_ext";
    les_motcles[1] = "C_ext";
    les_motcles[2] = "K_Eps_ext";
    les_motcles[3] = "H_ext";
    les_motcles[4] = "Y_ext";
  }
  Motcle accfermee="}";
  Motcle accouverte="{";
  s >> motlu;
  int rang;
  if (motlu != accouverte)
    {
      Cerr << "On attendait une { dans la lecture de l'interface " << finl;
      exit();
    }
  s >> motlu;
  while(motlu != accfermee)
    {
      rang = les_motcles.search(motlu);
      switch(rang)
        {
        case 0:
          {
            s >> le_champ_Text;
            break;
          }
        case 1:
        case 2:
        case 3:
        case 4:
          {
            s >> le_champ_hext;
            break;
          }
        default:
          {
            Cerr << "Erreur a la lecture de la condition aux limites de type: " << finl;
            Cerr << que_suis_je() << finl;
            Cerr << "On attendait " << les_motcles << " a la place de " <<  motlu << finl;
            exit();
          }
        }
      s >> motlu;
    }
  return s;
}
Sortie_libre_Text_H_ext & Sortie_libre_Text_H_ext::self_cast (Objet_U & r) [static]
Reimplemented from Neumann.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
const Sortie_libre_Text_H_ext & Sortie_libre_Text_H_ext::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Neumann.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
unsigned Sortie_libre_Text_H_ext::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Sortie_libre_Text_H_ext.cpp.
double Sortie_libre_Text_H_ext::val_ext (int i) const [virtual]
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Definition at line 140 of file Sortie_libre_Text_H_ext.cpp.
References Cerr, DoubleTab::dimension(), Process::exit(), finl, le_champ_hext, le_champ_Text, DoubleVect::size(), type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en temperature"<<finl;
      if (le_champ_Text.valeurs().size()==1)
        return le_champ_Text(0,0);
      else if (le_champ_Text.valeurs().dimension(1)==1)
        return le_champ_Text(i,0);
      else
        Cerr << "Sortie_libre_Text_H_ext::val_ext" << finl;
      exit();
      return 0.;
    }
  else
    {
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en enthalpie"<<finl;
      if (le_champ_hext.valeurs().size()==1)
        return le_champ_hext(0,0);
      else if (le_champ_hext.valeurs().dimension(1)==1)
        return le_champ_hext(i,0);
      else
        Cerr << "Sortie_libre_Text_H_ext::val_ext" << finl;
      exit();
      return 0.;
    }
}
double Sortie_libre_Text_H_ext::val_ext (int i, int j) const [virtual]
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Definition at line 189 of file Sortie_libre_Text_H_ext.cpp.
References DoubleTab::dimension(), le_champ_hext, le_champ_Text, type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Condition limite en temperature
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en temperature2"<<finl;
      if (le_champ_Text.valeurs().dimension(0)==1)
        return le_champ_Text(0,j);
      else
        return le_champ_Text(i,j);
    }
  else
    {
// Condition limite en enthalpie
// Cerr<<"Sortie_libre_Text_H_ext Condition limite en enthalpie2"<<finl;
      if (le_champ_hext.valeurs().dimension(0)==1)
        return le_champ_hext(0,j);
      else
        return le_champ_hext(i,j);
    }
}
Member Data Documentation
const Type_info Sortie_libre_Text_H_ext::info_obj [static]
Reimplemented from Neumann.
Definition at line 55 of file Sortie_libre_Text_H_ext.h.
Champ_front Sortie_libre_Text_H_ext::le_champ_hext [protected]
Definition at line 70 of file Sortie_libre_Text_H_ext.h.
Referenced by flux_impose(), readOn(), and val_ext().
Champ_front Sortie_libre_Text_H_ext::le_champ_Text [protected]
Definition at line 69 of file Sortie_libre_Text_H_ext.h.
Referenced by flux_impose(), readOn(), and val_ext().
int Sortie_libre_Text_H_ext::type_cond_lim [protected]
Definition at line 71 of file Sortie_libre_Text_H_ext.h.
Referenced by bascule_cond_lim_en_enthalpie(), bascule_cond_lim_en_temperature(), flux_impose(), and val_ext().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Sortie_libre_Text_H_ext.h
src/ThHyd/Incompressible/Cond_Lim/Sortie_libre_Text_H_ext.cpp