TRUST: Eval_Echange_Himp_VDF_Elem Class Reference
Eval_Echange_Himp_VDF_Elem Class Reference
#include <Eval_Echange_Himp_VDF_Elem.h>
Public Member Functions
Eval_Echange_Himp_VDF_Elem ()
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &) const
void associer_champs (const Champ_Inc &, const Champ_Inc &, const double)
void mettre_a_jour () override
Public Member Functions inherited from Evaluateur_Source_VDF_Elem
Evaluateur_Source_VDF_Elem ()
Evaluateur_Source_VDF_Elem (const Evaluateur_Source_VDF_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Protected Attributes
Ref_Champ_Inc T
Ref_Champ_Inc T_voisin
DoubleTab Tcourant
DoubleTab Tvois
double h_
Protected Attributes inherited from Evaluateur_Source_VDF_Elem
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 23 of file Eval_Echange_Himp_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Echange_Himp_VDF_Elem()
Eval_Echange_Himp_VDF_Elem::Eval_Echange_Himp_VDF_Elem () inline
Definition at line 26 of file Eval_Echange_Himp_VDF_Elem.h.
: h_(-1.) { }
Member Function Documentation
associer_champs()
void Eval_Echange_Himp_VDF_Elem::associer_champs (const Champ_Inc & tc, const Champ_Inc & tv, const double dh) inline
Definition at line 37 of file Eval_Echange_Himp_VDF_Elem.h.
{
  this->h_ = dh;
  T = tc;
  T_voisin = tv;
  Tcourant.ref(T->valeurs());
  mettre_a_jour();
}
References h_, mettre_a_jour(), TRUSTTab< _TYPE_ >::ref(), T, T_voisin, Tcourant, and Champ_Inc::valeurs().
Referenced by Source_Echange_Th_VDF::associer_pb().
calculer_terme_source()
template<typename Type_Double > void Eval_Echange_Himp_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
Definition at line 53 of file Eval_Echange_Himp_VDF_Elem.h.
{
  const int size = source.size_array();
  for (int i = 0; i < size; i++) source[i] = h_*(Tvois(num_elem,i)-Tcourant(num_elem,i)) * volumes(num_elem)*porosite_vol(num_elem);
}
References h_, Evaluateur_Source_VDF_Elem::porosite_vol, Tcourant, Tvois, and Evaluateur_Source_VDF_Elem::volumes.
mettre_a_jour()
void Eval_Echange_Himp_VDF_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 46 of file Eval_Echange_Himp_VDF_Elem.h.
{
  Tcourant.ref(T->valeurs());
  Tvois.ref(T_voisin->valeurs());
}
References TRUSTTab< _TYPE_ >::ref(), T, T_voisin, Tcourant, Tvois, and Champ_Inc::valeurs().
Referenced by associer_champs().
Member Data Documentation
h_
double Eval_Echange_Himp_VDF_Elem::h_ protected
Definition at line 34 of file Eval_Echange_Himp_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
T
Ref_Champ_Inc Eval_Echange_Himp_VDF_Elem::T protected
Definition at line 32 of file Eval_Echange_Himp_VDF_Elem.h.
Referenced by associer_champs(), and mettre_a_jour().
T_voisin
Ref_Champ_Inc Eval_Echange_Himp_VDF_Elem::T_voisin protected
Definition at line 32 of file Eval_Echange_Himp_VDF_Elem.h.
Referenced by associer_champs(), and mettre_a_jour().
Tcourant
DoubleTab Eval_Echange_Himp_VDF_Elem::Tcourant protected
Definition at line 33 of file Eval_Echange_Himp_VDF_Elem.h.
Referenced by associer_champs(), calculer_terme_source(), and mettre_a_jour().
Tvois
DoubleTab Eval_Echange_Himp_VDF_Elem::Tvois protected
Definition at line 33 of file Eval_Echange_Himp_VDF_Elem.h.
Referenced by calculer_terme_source(), and mettre_a_jour().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Echange_Himp_VDF_Elem.h