TRUST: Terme_Boussinesq_VDF_Face Class Reference
Terme_Boussinesq_VDF_Face Class Reference
class Terme_Boussinesq_scalaire_VDF_Face
Terme Source de Boussinesq pour une dicretisation VDF
#include <Terme_Boussinesq_VDF_Face.h>
Public Member Functions
Terme_Boussinesq_VDF_Face ()
~Terme_Boussinesq_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Boussinesq_VDF_Face & self_cast (Objet_U &)
static const
Terme_Boussinesq_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Detailed Description
class Terme_Boussinesq_scalaire_VDF_Face
Terme Source de Boussinesq pour une dicretisation VDF
Definition at line 36 of file Terme_Boussinesq_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Boussinesq_VDF_Face::Terme_Boussinesq_VDF_Face ()
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
Terme_Boussinesq_VDF_Face::~Terme_Boussinesq_VDF_Face ()
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Terme_Boussinesq_VDF_Face::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 58 of file Terme_Boussinesq_VDF_Face.cpp.
References Objet_U::axi, Terme_Boussinesq_base::beta(), Terme_Boussinesq_base::check(), Objet_U::dimension, MorEqn::equation(), Terme_Boussinesq_base::equation_scalaire(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Terme_Boussinesq_base::gravite(), Equation_base::inconnue(), Convection_Diffusion_std::inconnue(), la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), DoubleVect::line_size(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Terme_Boussinesq_base::Scalaire0(), sub_type, Neumann_sortie_libre::val_ext(), Dirichlet::val_imp(), valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), and Equation_base::zone_Cl_dis().
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const Zone_Cl_VDF& zone_Cl_VDF_hyd = la_zone_Cl_VDF.valeur();
  const Zone_Cl_dis& zone_Cl_scal = equation_scalaire().zone_Cl_dis();
  const Zone_Cl_VDF& zone_Cl_VDF_scal = ref_cast(Zone_Cl_VDF,zone_Cl_scal.valeur());
  const DoubleTab& param = equation_scalaire().inconnue().valeurs();
  const DoubleTab& beta_valeurs = beta().valeur().valeurs();
  const DoubleVect& grav = gravite().valeurs();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntVect& orientation = zone_VDF.orientation();
  const DoubleTab& xv = zone_VDF.xv();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const DoubleTab& vitesse = equation().inconnue().valeurs();
  DoubleVect g(dimension);
  g = grav;
  int nb_dim = param.line_size();
// Verifie la validite de T0:
  check();
// Boucle sur les conditions limites pour traiter les faces de bord
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
      const Cond_lim& la_cl = zone_Cl_VDF_hyd.les_conditions_limites(n_bord);
      const Cond_lim& la_cl_scal = zone_Cl_VDF_scal.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          if (sub_type(Neumann_sortie_libre,la_cl_scal.valeur()))
            {
              const Neumann_sortie_libre& la_cl_neumann_scal = ref_cast(Neumann_sortie_libre, la_cl_scal.valeur());
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
                  int outlet;
                  int elem = face_voisins(num_face,0);
                  if (elem==-1)
                    {
                      outlet = (vitesse(num_face)<0?1:0);
                      elem = face_voisins(num_face,1);
                    }
                  else
                    outlet = (vitesse(num_face)>0?1:0);
                  double coef=0;
                  for (int dim=0; dim<nb_dim; dim++)
                    {
                      double param_face = (outlet ? valeur(param,elem,dim) : 0.5*(valeur(param,elem,dim)+la_cl_neumann_scal.val_ext(num_face-ndeb,dim)));
                      coef += valeur(beta_valeurs,elem,elem,dim)*(Scalaire0(dim)-param_face);
                    }
                  if (axi)
                    {
                      double cos_teta = cos(xv(num_face,1));
                      double sin_teta = sin(xv(num_face,1));
                      g(0) = grav(0)*cos_teta + grav(1)*sin_teta;
                      g(1) = grav(1)*cos_teta - grav(0)*sin_teta;
                    }
                  double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
                  int ncomp = orientation(num_face);
                  resu(num_face)+= coef*g(ncomp)*vol;
                }
            }
          else if (sub_type(Dirichlet,la_cl_scal.valeur()))
            {
              const Dirichlet& la_cl_diri_scal = ref_cast(Dirichlet,la_cl_scal.valeur());
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
                  int outlet;
                  int elem = face_voisins(num_face,0);
                  if (elem==-1)
                    {
                      outlet = (vitesse(num_face)<0?1:0);
                      elem = face_voisins(num_face,1);
                    }
                  else
                    outlet = (vitesse(num_face)>0?1:0);
                  double coef=0;
                  for (int dim=0; dim<nb_dim; dim++)
                    {
                      double param_face = (outlet ? valeur(param,elem,dim) : 0.5*(valeur(param,elem,dim)+la_cl_diri_scal.val_imp(num_face-ndeb,dim)));
                      coef += valeur(beta_valeurs,elem,elem,dim)*(Scalaire0(dim)-param_face);
                    }
                  if (axi)
                    {
                      double cos_teta = cos(xv(num_face,1));
                      double sin_teta = sin(xv(num_face,1));
                      g(0) = grav(0)*cos_teta + grav(1)*sin_teta;
                      g(1) = grav(1)*cos_teta - grav(0)*sin_teta;
                    }
                  double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
                  int ncomp = orientation(num_face);
                  resu(num_face)+= coef*g(ncomp)*vol;
                }
            }
        }
      else
        {
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              int elem = face_voisins(num_face,0);
              if (elem == -1) elem = face_voisins(num_face,1);
              double coef = 0;
              for (int dim=0; dim<nb_dim; dim++)
                {
                  double param_face = valeur(param,elem,dim);
                  coef += valeur(beta_valeurs,elem,elem,dim)*(Scalaire0(dim)-param_face);
                }
              if (axi)
                {
                  double cos_teta = cos(xv(num_face,1));
                  double sin_teta = sin(xv(num_face,1));
                  g(0) = grav(0)*cos_teta + grav(1)*sin_teta;
                  g(1) = grav(1)*cos_teta - grav(0)*sin_teta;
                }
              int ncomp = orientation(num_face);
              double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              resu(num_face) += coef*g(ncomp)*vol;
            }
        }
    }
// Boucle sur les faces internes
  int ndeb = zone_VDF.premiere_face_int();
  int nb_faces = zone_VDF.nb_faces();
  for (int num_face=ndeb; num_face<nb_faces; num_face++)
    {
      int elem1 = face_voisins(num_face,0);
      int elem2 = face_voisins(num_face,1);
      double coef = 0;
      for (int dim=0; dim<nb_dim; dim++)
        {
          double param_face = 0.5*(valeur(param,elem1,dim)+valeur(param,elem2,dim));
          coef += valeur(beta_valeurs,elem1,elem2,dim)*(Scalaire0(dim)-param_face);
        }
      if (axi)
        {
          double cos_teta = cos(xv(num_face,1));
          double sin_teta = sin(xv(num_face,1));
          g(0) = grav(0)*cos_teta + grav(1)*sin_teta;
          g(1) = grav(1)*cos_teta - grav(0)*sin_teta;
        }
      int ncomp = orientation(num_face);
      double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
      resu(num_face) += coef*g(ncomp)*vol;
    }
  return resu;
}
void Terme_Boussinesq_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 51 of file Terme_Boussinesq_VDF_Face.cpp.
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
Objet_U * Terme_Boussinesq_VDF_Face::cree_instance () [static]
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
int Terme_Boussinesq_VDF_Face::duplique () const [virtual]
Implements Terme_Boussinesq_base.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
const Type_info * Terme_Boussinesq_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Boussinesq_base.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
const Type_info * Terme_Boussinesq_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Boussinesq_base.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
Sortie & Terme_Boussinesq_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Boussinesq_base.
Definition at line 40 of file Terme_Boussinesq_VDF_Face.cpp.
{
  return Terme_Boussinesq_base::printOn(s);
}
Entree & Terme_Boussinesq_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Boussinesq_base.
Definition at line 46 of file Terme_Boussinesq_VDF_Face.cpp.
{
  return Terme_Boussinesq_base::readOn(s);
}
const Terme_Boussinesq_VDF_Face & Terme_Boussinesq_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Boussinesq_base.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
Terme_Boussinesq_VDF_Face & Terme_Boussinesq_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Boussinesq_base.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
unsigned Terme_Boussinesq_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 35 of file Terme_Boussinesq_VDF_Face.cpp.
Member Data Documentation
const Type_info Terme_Boussinesq_VDF_Face::info_obj [static]
Reimplemented from Terme_Boussinesq_base.
Definition at line 39 of file Terme_Boussinesq_VDF_Face.h.
Ref_Zone_Cl_VDF Terme_Boussinesq_VDF_Face::la_zone_Cl_VDF [protected]
Definition at line 48 of file Terme_Boussinesq_VDF_Face.h.
Referenced by ajouter(), and associer_zones().
Ref_Zone_VDF Terme_Boussinesq_VDF_Face::la_zone_VDF [protected]
Definition at line 47 of file Terme_Boussinesq_VDF_Face.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Boussinesq_VDF_Face.h
src/VDF/Sources/Terme_Boussinesq_VDF_Face.cpp