TRUST: Terme_Source_inc Class Reference
Terme_Source_inc Class Reference
#include <Terme_Source_inc.h>
Public Member Functions
void associer_eqn (const Navier_Stokes_std &)
const Navier_Stokes_std & eq_hydraulique () const
void mettre_a_jour (double temps)
Protected Member Functions
Entree & lire_donnees (Entree &)
Protected Attributes
Ref_Navier_Stokes_std eq_hydraulique_
int impr
Detailed Description
Definition at line 25 of file Terme_Source_inc.h.
Member Function Documentation
associer_eqn()
void Terme_Source_inc::associer_eqn (const Navier_Stokes_std & eq_hyd)
Definition at line 20 of file Terme_Source_inc.cpp.
{
  eq_hydraulique_ = eq_hyd;
}
References eq_hydraulique_.
Referenced by Terme_Source_inc_VDF_Face::associer_pb().
eq_hydraulique()
const Navier_Stokes_std & Terme_Source_inc::eq_hydraulique () const inline
Definition at line 45 of file Terme_Source_inc.h.
{
  return eq_hydraulique_.valeur();
}
References eq_hydraulique_, and Ref_Navier_Stokes_std::valeur().
lire_donnees()
Entree & Terme_Source_inc::lire_donnees (Entree & is) protected
Definition at line 26 of file Terme_Source_inc.cpp.
{
  Cerr << "Source_inc::lire_donnees" << finl;
// Initialisation
// u_etoile = 1.;
// h = 1.;
// coeff = 1;
// dir_source = 1;
  impr = 0;
// Fin Init
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{", mot="impr";
  is >> motlu;
  if(motlu != accolade_ouverte)
    {
      Cerr << "On attendait { a la place de " << motlu
           << " lors de la lecture de inc " << finl;
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      if (motlu==mot)
        {
          impr = 1;
          is >> motlu;
        }
      else
        {
          Cerr << "Le mot lu : " <<  motlu << " n'est pas compris dans Source_inc" << finl;
          Cerr << "Le mot compris est :  impr " << finl;
          Process::exit();
        }
    }
  return is;
}
References Cerr, Process::exit(), finl, and impr.
Referenced by Terme_Source_inc_VDF_Face::readOn().
mettre_a_jour()
void Terme_Source_inc::mettre_a_jour (double temps) inline
Definition at line 31 of file Terme_Source_inc.h.
  {
    ;
  }
Referenced by Terme_Source_inc_VDF_Face::mettre_a_jour().
Member Data Documentation
eq_hydraulique_
Ref_Navier_Stokes_std Terme_Source_inc::eq_hydraulique_ protected
Definition at line 37 of file Terme_Source_inc.h.
Referenced by associer_eqn(), and eq_hydraulique().
impr
int Terme_Source_inc::impr protected
Definition at line 40 of file Terme_Source_inc.h.
Referenced by lire_donnees().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_inc.h
src/VDF/Sources/Terme_Source_inc.cpp