TRUST: Dilate Class Reference
Dilate Class Reference
Classe Dilate
x->alpha x.
#include <Dilate.h>
Public Member Functions
Dilate ()
~Dilate ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Fonction principale de l'interprete Dilate
Structure du jeu de donnee (en dimension 2) :
Dilate dom alpha.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Dilate & self_cast (Objet_U &)
static const Dilate & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
Detailed Description
Classe Dilate
x->alpha x.
Definition at line 40 of file Dilate.h.
Constructor & Destructor Documentation
Dilate::Dilate ()
Definition at line 26 of file Dilate.cpp.
Dilate::~Dilate ()
Definition at line 26 of file Dilate.cpp.
Member Function Documentation
Objet_U * Dilate::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Dilate.cpp.
int Dilate::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 26 of file Dilate.cpp.
const Type_info * Dilate::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Dilate.cpp.
const Type_info * Dilate::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Dilate.cpp.
Entree & Dilate::interpreter_ (Entree & is) [virtual]
Fonction principale de l'interprete Dilate
Structure du jeu de donnee (en dimension 2) :
Dilate dom alpha.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 84 of file Dilate.cpp.
References Interprete_geometrique_base::associer_domaine(), Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::le_nom(), Domaine::les_sommets(), and Process::nproc().
{
  double alpha;
  associer_domaine(is);
  is >> alpha;
  if (Process::nproc()>1)
    {
      Cerr << "Dilate can not be use in parallel." << finl;
      Cerr << "Put rather this interpreter in the " << finl;
      Cerr << "data file of the mesh splitter." << finl;
      exit();
    }
  DoubleTab& coord=domaine().les_sommets();
  coord*=alpha;
  Cerr << "Expands the domain " << domaine().le_nom() << " of a factor " << alpha << finl;
  return is;
}
Sortie & Dilate::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 43 of file Dilate.cpp.
{
  return Interprete::printOn(os);
}
Entree & Dilate::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 63 of file Dilate.cpp.
{
  return Interprete::readOn(is);
}
Dilate & Dilate::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Dilate.cpp.
const Dilate & Dilate::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Dilate.cpp.
unsigned Dilate::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Dilate.cpp.
Member Data Documentation
const Type_info Dilate::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 42 of file Dilate.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Dilate.h
src/Kernel/Geometrie/Dilate.cpp