TRUST: Entree_fluide_temperature_imposee_H Class Reference
Entree_fluide_temperature_imposee_H Class Reference
classe Entree_fluide_temperature_imposee_H
Cas particulier de la classe Entree_fluide_temperature_imposee
pour une equation ayant l'enthalpie en inconnue
#include <Entree_fluide_temperature_imposee_H.h>
Public Member Functions
Entree_fluide_temperature_imposee_H ()
~Entree_fluide_temperature_imposee_H ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
Complete les conditions aux limites.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
double val_imp (int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere.
double val_imp (int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Entree_fluide_temperature_imposee_H & self_cast (Objet_U &)
static const
Entree_fluide_temperature_imposee_H & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Attributes
Ref_Fluide_Dilatable_base le_fluide
Detailed Description
classe Entree_fluide_temperature_imposee_H
Cas particulier de la classe Entree_fluide_temperature_imposee
pour une equation ayant l'enthalpie en inconnue
Definition at line 39 of file Entree_fluide_temperature_imposee_H.h.
Constructor & Destructor Documentation
Entree_fluide_temperature_imposee_H::Entree_fluide_temperature_imposee_H ()
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
Entree_fluide_temperature_imposee_H::~Entree_fluide_temperature_imposee_H ()
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
Member Function Documentation
int Entree_fluide_temperature_imposee_H::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 108 of file Entree_fluide_temperature_imposee_H.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique="Thermique_H";
  if ( (dom_app==Thermique))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
void Entree_fluide_temperature_imposee_H::completer (void) [virtual]
Complete les conditions aux limites.
Reimplemented from Cond_lim_base.
Definition at line 82 of file Entree_fluide_temperature_imposee_H.cpp.
References le_fluide, Cond_lim_base::ma_zone_cl_dis, Cond_lim_base::modifier_val_imp, and ref_cast.
{
  le_fluide = ref_cast(Fluide_Dilatable_base,ma_zone_cl_dis->equation().milieu());
  modifier_val_imp = 1;
}
Objet_U * Entree_fluide_temperature_imposee_H::cree_instance () [static]
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
int Entree_fluide_temperature_imposee_H::duplique () const [virtual]
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
const Type_info * Entree_fluide_temperature_imposee_H::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
const Type_info * Entree_fluide_temperature_imposee_H::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
Sortie & Entree_fluide_temperature_imposee_H::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 44 of file Entree_fluide_temperature_imposee_H.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Entree_fluide_temperature_imposee_H::readOn (Entree & s) [protected, virtual]
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 63 of file Entree_fluide_temperature_imposee_H.cpp.
{
  return Entree_fluide_temperature_imposee::readOn(s);
}
const Entree_fluide_temperature_imposee_H & Entree_fluide_temperature_imposee_H::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
Entree_fluide_temperature_imposee_H & Entree_fluide_temperature_imposee_H::self_cast (Objet_U & r) [static]
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
unsigned Entree_fluide_temperature_imposee_H::taille_memoire () const [virtual]
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 28 of file Entree_fluide_temperature_imposee_H.cpp.
double Entree_fluide_temperature_imposee_H::val_imp (int i) const [virtual]
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Dirichlet.
Definition at line 136 of file Entree_fluide_temperature_imposee_H.cpp.
References Process::abort(), Cerr, DoubleTab::dimension(), finl, Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, DoubleVect::size(), and Champ_front::valeurs().
{
  if (le_champ_front.valeurs().size()==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(0,0));
      else
        return le_champ_front(0,0);
    }
  else if (le_champ_front.valeurs().dimension(1)==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(i,0));
      else
        return le_champ_front(i,0);
    }
  else
    Cerr << "Temperature_imposee_paroi_H::val_imp erreur" << finl;
  abort();
  return 0.;
}
double Entree_fluide_temperature_imposee_H::val_imp (int i, int j) const [virtual]
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Dirichlet.
Definition at line 179 of file Entree_fluide_temperature_imposee_H.cpp.
References DoubleTab::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, and Champ_front::valeurs().
{
  if (le_champ_front.valeurs().dimension(0)==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(0,j));
      else
        return le_champ_front(0,j);
    }
  else
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(i,j));
      else
        return le_champ_front(i,j);
    }
}
Member Data Documentation
const Type_info Entree_fluide_temperature_imposee_H::info_obj [static]
Reimplemented from Entree_fluide_temperature_imposee.
Definition at line 41 of file Entree_fluide_temperature_imposee_H.h.
Ref_Fluide_Dilatable_base Entree_fluide_temperature_imposee_H::le_fluide [protected]
Definition at line 50 of file Entree_fluide_temperature_imposee_H.h.
Referenced by completer(), and val_imp().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Cond_Lim/Entree_fluide_temperature_imposee_H.h
src/ThHyd/Dilatable/Common/Cond_Lim/Entree_fluide_temperature_imposee_H.cpp