TRUST: Tetraedriser_homogene_compact Class Reference
Tetraedriser_homogene_compact Class Reference
#include <Tetraedriser_homogene_compact.h>
Public Member Functions
Tetraedriser_homogene_compact ()
~Tetraedriser_homogene_compact ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void decoupe (Zone &, Faces &, IntTab &, IntTab &, int) const
virtual void trianguler (Zone &) const
int creer_sommet (Domaine &, Zone &, DoubleTab &, IntTab &, IntTab &, int, IntTab &, int &, int, int &, IntTab &, int &) const
virtual int dimension_application () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Tetraedriser_homogene_compact & self_cast (Objet_U &)
static const
Tetraedriser_homogene_compact & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 41 of file Tetraedriser_homogene_compact.h.
Constructor & Destructor Documentation
Tetraedriser_homogene_compact::Tetraedriser_homogene_compact ()
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
Tetraedriser_homogene_compact::~Tetraedriser_homogene_compact ()
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
Member Function Documentation
Objet_U * Tetraedriser_homogene_compact::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
int Tetraedriser_homogene_compact::creer_sommet (Domaine & dom, Zone & zone, DoubleTab & new_soms, IntTab & elem_traite, IntTab & new_soms_old_elems, int NbSom, IntTab & sommets, int & compteur, int oldnbsom, int & nbnewsoms, IntTab & fait_sommet, int & nface) const
< On verifie que le sommet rattache a une face n'a pas ete cree ulterieurement
Definition at line 123 of file Tetraedriser_homogene_compact.cpp.
References Domaine::coord_sommets().
Referenced by trianguler().
{
  int _out=-1;
  if(NbSom==4) //!< On verifie que le sommet rattache a une face n'a pas ete cree ulterieurement
    {
      int permut,som;
      do
        {
          permut=0;
          for(int j=1; j<4; j++)
            {
              if( sommets[j]<sommets[j-1] )
                {
                  som=sommets[j-1];
                  sommets[j-1]=sommets[j];
                  sommets[j]=som;
                  permut++;
                }
            }
        }
      while(permut);
      for (int i=0 ; i<nface ; i++)
        if (fait_sommet(i,0)==sommets[0] && fait_sommet(i,1)==sommets[1] && fait_sommet(i,2)==sommets[2]) return fait_sommet(i,3);
    }
  const DoubleTab& coord_sommets=dom.coord_sommets();
  double x=0,y=0,z=0;
  for (int ii=0 ; ii<NbSom ; ii++)
    {
      x += coord_sommets(sommets(ii),0);
      y += coord_sommets(sommets(ii),1);
      z += coord_sommets(sommets(ii),2);
    }
  x /= NbSom;
  y /= NbSom;
  z /= NbSom;
  _out = oldnbsom + nbnewsoms;
  new_soms(compteur, 0) = x;
  new_soms(compteur, 1) = y;
  new_soms(compteur, 2) = z;
  nbnewsoms++;
  compteur++;
  if(NbSom==4)
    {
      fait_sommet(nface,  0)=sommets[0];
      fait_sommet(nface,  1)=sommets[1];
      fait_sommet(nface,  2)=sommets[2];
      fait_sommet(nface,  3)=_out;
// Cerr << sommets(0) << " " << sommets(1) << " " << sommets(2) << " " << _out << finl;
      nface++;
    }
  return _out;
}
void Tetraedriser_homogene_compact::decoupe (Zone & zone, Faces & faces, IntTab & new_soms_old_elems, IntTab & fait_sommet, int nface) const
Definition at line 39 of file Tetraedriser_homogene_compact.cpp.
References Cerr, IntTab::dimension(), Process::exit(), finl, Faces::les_sommets(), IntTab::ref(), IntTab::resize(), and Faces::voisins().
Referenced by trianguler().
{
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  assert(sommets.dimension(1)==4);
  IntTab nouveaux(4*nb_faces, 3);
  faces.voisins().resize(4*nb_faces, 2);
  faces.voisins()=-1;
  IntVect indice(5);
  for(int i=0; i<nb_faces; i++)
    {
      indice(0) = sommets(i,0);
      indice(1) = sommets(i,1);
      indice(2) = sommets(i,2);
      indice(3) = sommets(i,3);
      int i0=indice(0);
      int i1=indice(1);
      int i2=indice(2);
      int i3=indice(3);
      int i4=-1;
// on remet un peu d'ordre dans les indices
      int permut,ind;
      do
        {
          permut=0;
          for(int j=1; j<4; j++)
            {
              if( indice[j]<indice[j-1] )
                {
                  ind=indice[j-1];
                  indice[j-1]=indice[j];
                  indice[j]=ind;
                  permut++;
                }
            }
        }
      while(permut);
      for (int ii=0 ; ii<nface ; ii++)
        {
          if ( fait_sommet(ii,0)==indice[0] && fait_sommet(ii,1)==indice[1] && fait_sommet(ii,2)==indice[2] )
            {
              i4=fait_sommet(ii,3);
              break;
            }
        }
      if(indice(4)<0)
        {
// Cerr << indice(0) << " " << indice(1) << " " << indice(2)  << finl;
          Cerr << " FALSE " << finl;
          exit();
        }
      assert(indice(4)>=0);
      nouveaux(i,0) = i0;
      nouveaux(i,1) = i1;
      nouveaux(i,2) = i4;
      nouveaux(nb_faces+i,0) = i1;
      nouveaux(nb_faces+i,1) = i3;
      nouveaux(nb_faces+i,2) = i4;
      nouveaux(2*nb_faces+i,0) = i3;
      nouveaux(2*nb_faces+i,1) = i2;
      nouveaux(2*nb_faces+i,2) = i4;
      nouveaux(3*nb_faces+i,0) = i2;
      nouveaux(3*nb_faces+i,1) = i0;
      nouveaux(3*nb_faces+i,2) = i4;
    }
  sommets.ref(nouveaux);
}
int Tetraedriser_homogene_compact::dimension_application () const [inline, virtual]
Implements Triangulation_base.
Definition at line 54 of file Tetraedriser_homogene_compact.h.
{
  return 3;
}
int Tetraedriser_homogene_compact::duplique () const [virtual]
Implements Triangulation_base.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
const Type_info * Tetraedriser_homogene_compact::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
const Type_info * Tetraedriser_homogene_compact::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
Sortie & Tetraedriser_homogene_compact::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 27 of file Tetraedriser_homogene_compact.cpp.
{
  return Interprete::printOn(os);
}
Entree & Tetraedriser_homogene_compact::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 32 of file Tetraedriser_homogene_compact.cpp.
{
  return Interprete::readOn(is);
}
const Tetraedriser_homogene_compact & Tetraedriser_homogene_compact::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Triangulation_base.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
Tetraedriser_homogene_compact & Tetraedriser_homogene_compact::self_cast (Objet_U & r) [static]
Reimplemented from Triangulation_base.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
unsigned Tetraedriser_homogene_compact::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file Tetraedriser_homogene_compact.cpp.
void Tetraedriser_homogene_compact::trianguler (Zone & zone) const [virtual]
< PQ : 04-03 : dimensionnement de fait_sommet a 3*nbs (a revoir si insuffisant)
Implements Triangulation_base.
Definition at line 197 of file Tetraedriser_homogene_compact.cpp.
References Cerr, compteur, Zone::construit_octree(), creer_sommet(), decoupe(), DoubleTab::dimension(), IntTab::dimension(), Zone::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), LIST_CURSEUR, Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_som(), Objet_U::que_suis_je(), IntTab::ref(), DoubleTab::resize(), Faces::triangle_3D, Zone::type_elem(), Faces::typer(), and Zone::typer().
{
  if  ((zone.type_elem()->que_suis_je() == "Hexaedre")
       ||(zone.type_elem()->que_suis_je() == "Hexaedre_VEF"))
    {
      IntTab& les_elems = zone.les_elems();
      int oldsz = les_elems.dimension(0);
      int nbs = zone.nb_som();
      IntTab elem_traite(oldsz);
      int oldnbsom = zone.nb_som();
      IntTab new_elems(24*oldsz, 4);
// pour chaque cube, liste des nouveaux sommets qu'il contient :
      IntTab new_soms_old_elems(oldsz,7);
      IntTab sommets(8);
      Domaine& dom = zone.domaine();
      int compteur = 0;
      int nbnewsoms = 0;
      int nface = 0;
      int i;
      Cerr << " NB ELEM : " << oldsz << " NB NODE : " << nbs << finl;
      IntTab fait_sommet(3*nbs,4); //!< PQ : 04-03 : dimensionnement de fait_sommet a 3*nbs (a revoir si insuffisant)
      fait_sommet=-1;
// Construction de l'Octree sur la grille "VDF" de base
      zone.construit_octree();
// On dimensionne une premiere fois le tableau des sommets avec la dimension maximun
// puis on redimensionnera seulement a la fin par la dimension exacte
      DoubleTab& sommets_dom = dom.les_sommets();
// 8 pour les nouveaux sommets et 8 pour les anciens sommets =16
      int dim_som_max=16*oldsz;
      int dim_som_old=sommets_dom.dimension(0);
      sommets_dom.resize(dim_som_max,3);
      IntTab indice(8);
      DoubleTab new_soms(7, 3);
      for(i=0; i< oldsz; i++)
        {
          if (nface>=3*nbs)
            {
              Cerr << " The sizing of the array fait_sommet in Tetraedriser_homogene_compact::Trianguler is inappropriate " << finl;
              exit();
            }
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int i3=les_elems(i,3);
          int i4=les_elems(i,4);
          int i5=les_elems(i,5);
          int i6=les_elems(i,6);
          int i7=les_elems(i,7);
          compteur = 0;
// Definition des nouveaux sommets : creation des barycentres
// centre de l'hexaedre
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i2;
          sommets(3)=i3;
          sommets(4)=i4;
          sommets(5)=i5;
          sommets(6)=i6;
          sommets(7)=i7;
          indice(0)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 8, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces bas (0-1-3-2)
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i3;
          sommets(3)=i2;
          indice(1)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces haut (4-5-7-6)
          sommets(0)=i4;
          sommets(1)=i5;
          sommets(2)=i7;
          sommets(3)=i6;
          indice(4)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces avant (0-1-5-4)
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i5;
          sommets(3)=i4;
          indice(3)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces arriere (2-3-7-6)
          sommets(0)=i2;
          sommets(1)=i3;
          sommets(2)=i7;
          sommets(3)=i6;
          indice(6)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces gauche (0-2-6-4)
          sommets(0)=i0;
          sommets(1)=i2;
          sommets(2)=i6;
          sommets(3)=i4;
          indice(2)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// centres des faces droite (1-3-7-5)
          sommets(0)=i1;
          sommets(1)=i3;
          sommets(2)=i7;
          sommets(3)=i5;
          indice(5)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4, sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface);
// Liste des nouveaux sommets pour cet ancien cube
          for (int t=0; t<7; t++)
            {
              new_soms_old_elems(i, t) = indice(t);
              if(indice(t)<0)
                {
                  Cerr << "Error negative index" << finl;
                  exit();
                }
              for(int s=0; s<t; s++)
                if(indice(s)==indice(t))
                  {
                    Cerr << "Error repeated index" << finl;
                    exit();
                  }
            }
          for(int j=0; j<compteur; j++)
            for(int k=0; k<3; k++)
              sommets_dom(dim_som_old+j,k)=new_soms(j,k) ;
          dim_som_old += compteur;
// L'element en cours a ete "traite" en entier
          elem_traite(i) = 1;
// pyramide bas (base : 0-1-3-2)
          new_elems(i, 0) = les_elems(i,0);
          new_elems(i, 1) = les_elems(i,1);
          new_elems(i, 2) = indice(1);
          new_elems(i, 3) = indice(0);
          new_elems(i+oldsz, 0) = les_elems(i,1);
          new_elems(i+oldsz, 1) = les_elems(i,3);
          new_elems(i+oldsz, 2) = indice(1);
          new_elems(i+oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
          new_elems(i+2*oldsz, 0) = les_elems(i,3);
          new_elems(i+2*oldsz, 1) = les_elems(i,2);
          new_elems(i+2*oldsz, 2) = indice(1);
          new_elems(i+2*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
          new_elems(i+3*oldsz, 0) = les_elems(i,2);
          new_elems(i+3*oldsz, 1) = les_elems(i,0);
          new_elems(i+3*oldsz, 2) = indice(1);
          new_elems(i+3*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
// pyramide haut (base : 4-5-7-6)
          new_elems(i+4*oldsz, 0) = les_elems(i,4);
          new_elems(i+4*oldsz, 1) = les_elems(i,5);
          new_elems(i+4*oldsz, 2) = indice(4);
          new_elems(i+4*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+4*oldsz,1);
          new_elems(i+5*oldsz, 0) = les_elems(i,5);
          new_elems(i+5*oldsz, 1) = les_elems(i,7);
          new_elems(i+5*oldsz, 2) = indice(4);
          new_elems(i+5*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+5*oldsz,1);
          new_elems(i+6*oldsz, 0) = les_elems(i,7);
          new_elems(i+6*oldsz, 1) = les_elems(i,6);
          new_elems(i+6*oldsz, 2) = indice(4);
          new_elems(i+6*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+6*oldsz,1);
          new_elems(i+7*oldsz, 0) = les_elems(i,6);
          new_elems(i+7*oldsz, 1) = les_elems(i,4);
          new_elems(i+7*oldsz, 2) = indice(4);
          new_elems(i+7*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+7*oldsz,1);
// pyramide avant (base : 0-1-5-4)
          new_elems(i+8*oldsz, 0) = les_elems(i,0);
          new_elems(i+8*oldsz, 1) = les_elems(i,1);
          new_elems(i+8*oldsz, 2) = indice(3);
          new_elems(i+8*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+8*oldsz,1);
          new_elems(i+9*oldsz, 0) = les_elems(i,1);
          new_elems(i+9*oldsz, 1) = les_elems(i,5);
          new_elems(i+9*oldsz, 2) = indice(3);
          new_elems(i+9*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+9*oldsz,1);
          new_elems(i+10*oldsz, 0) = les_elems(i,5);
          new_elems(i+10*oldsz, 1) = les_elems(i,4);
          new_elems(i+10*oldsz, 2) = indice(3);
          new_elems(i+10*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+10*oldsz,1);
          new_elems(i+11*oldsz, 0) = les_elems(i,4);
          new_elems(i+11*oldsz, 1) = les_elems(i,0);
          new_elems(i+11*oldsz, 2) = indice(3);
          new_elems(i+11*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+11*oldsz,1);
// pyramide arriere (base : 2-3-7-6)
          new_elems(i+12*oldsz, 0) = les_elems(i,2);
          new_elems(i+12*oldsz, 1) = les_elems(i,3);
          new_elems(i+12*oldsz, 2) = indice(6);
          new_elems(i+12*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+12*oldsz,1);
          new_elems(i+13*oldsz, 0) = les_elems(i,3);
          new_elems(i+13*oldsz, 1) = les_elems(i,7);
          new_elems(i+13*oldsz, 2) = indice(6);
          new_elems(i+13*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+13*oldsz,1);
          new_elems(i+14*oldsz, 0) = les_elems(i,7);
          new_elems(i+14*oldsz, 1) = les_elems(i,6);
          new_elems(i+14*oldsz, 2) = indice(6);
          new_elems(i+14*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+14*oldsz,1);
          new_elems(i+15*oldsz, 0) = les_elems(i,6);
          new_elems(i+15*oldsz, 1) = les_elems(i,2);
          new_elems(i+15*oldsz, 2) = indice(6);
          new_elems(i+15*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+15*oldsz,1);
// pyramide gauche (base : 0-2-6-4)
          new_elems(i+16*oldsz, 0) = les_elems(i,0);
          new_elems(i+16*oldsz, 1) = les_elems(i,2);
          new_elems(i+16*oldsz, 2) = indice(2);
          new_elems(i+16*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+16*oldsz,1);
          new_elems(i+17*oldsz, 0) = les_elems(i,2);
          new_elems(i+17*oldsz, 1) = les_elems(i,6);
          new_elems(i+17*oldsz, 2) = indice(2);
          new_elems(i+17*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+17*oldsz,1);
          new_elems(i+18*oldsz, 0) = les_elems(i,6);
          new_elems(i+18*oldsz, 1) = les_elems(i,4);
          new_elems(i+18*oldsz, 2) = indice(2);
          new_elems(i+18*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+18*oldsz,1);
          new_elems(i+19*oldsz, 0) = les_elems(i,4);
          new_elems(i+19*oldsz, 1) = les_elems(i,0);
          new_elems(i+19*oldsz, 2) = indice(2);
          new_elems(i+19*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+19*oldsz,1);
// pyramide droite (base : 1-3-7-5)
          new_elems(i+20*oldsz, 0) = les_elems(i,1);
          new_elems(i+20*oldsz, 1) = les_elems(i,3);
          new_elems(i+20*oldsz, 2) = indice(5);
          new_elems(i+20*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+20*oldsz,1);
          new_elems(i+21*oldsz, 0) = les_elems(i,3);
          new_elems(i+21*oldsz, 1) = les_elems(i,7);
          new_elems(i+21*oldsz, 2) = indice(5);
          new_elems(i+21*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+21*oldsz,1);
          new_elems(i+22*oldsz, 0) = les_elems(i,7);
          new_elems(i+22*oldsz, 1) = les_elems(i,5);
          new_elems(i+22*oldsz, 2) = indice(5);
          new_elems(i+22*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+22*oldsz,1);
          new_elems(i+23*oldsz, 0) = les_elems(i,5);
          new_elems(i+23*oldsz, 1) = les_elems(i,1);
          new_elems(i+23*oldsz, 2) = indice(5);
          new_elems(i+23*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+23*oldsz,1);
        }
      sommets_dom.resize(dim_som_old,3);
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      Cerr << "We have split the cubes..." << finl;
      zone.invalide_octree();
      zone.typer("Tetraedre");
      {
        Cerr << "Splitting of the boundaries" << finl;
        LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface);
            ++curseur;
          }
      }
      {
// Les Raccords
        Cerr << "Splitting of the connectors" << finl;
        LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
        while(curseur)
          {
            Faces& les_faces=curseur.valeur()->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface);
            ++curseur;
          }
      }
      {
// Les Faces internes
        Cerr << "Splitting of the internal faces" << finl;
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface);
            ++curseur;
          }
      }
      Cerr<<"END of Tetraedriser_homogene_compact..."<<finl;
      Cerr<<"  1 NbElem="<<zone.les_elems().dimension(0)<<"  NbNod="<<zone.nb_som()<<finl;
    }
  else
    {
      Cerr << "We do not yet know how to Tetraedriser_homogene_compact the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
}
Member Data Documentation
const Type_info Tetraedriser_homogene_compact::info_obj [static]
Reimplemented from Triangulation_base.
Definition at line 43 of file Tetraedriser_homogene_compact.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Tetraedriser_homogene_compact.h
src/Kernel/Geometrie/Tetraedriser_homogene_compact.cpp