TRUST: Entree_fluide_V2_impose Class Reference
Entree_fluide_V2_impose Class Reference
classe Entree_fluide_V2_impose
Cas particulier de la classe Dirichlet_entree_fluide
pour les fluctuation de vitesse du modele K_Eps_V2 imposee.
C'est le meme type de classe que Entree_fluide_concentration_imposee
en imposant des grandeurs turbulentes.
Impose les valeurs de V2 d'entree du fluide dans une
equation de type Transport_V2
#include <Entree_fluide_V2_impose.h>
Public Member Functions
Entree_fluide_V2_impose ()
~Entree_fluide_V2_impose ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_K_Eps_impose sont compatibles
avec une equation dont le domaine est le Transport_Keps
ou bien indetermine.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Entree_fluide_V2_impose & self_cast (Objet_U &)
static const
Entree_fluide_V2_impose & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Cond_lim_base::readOn(Entree&)
Detailed Description
classe Entree_fluide_V2_impose
Cas particulier de la classe Dirichlet_entree_fluide
pour les fluctuation de vitesse du modele K_Eps_V2 imposee.
C'est le meme type de classe que Entree_fluide_concentration_imposee
en imposant des grandeurs turbulentes.
Impose les valeurs de V2 d'entree du fluide dans une
equation de type Transport_V2
Definition at line 44 of file Entree_fluide_V2_impose.h.
Constructor & Destructor Documentation
Entree_fluide_V2_impose::Entree_fluide_V2_impose ()
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
Entree_fluide_V2_impose::~Entree_fluide_V2_impose ()
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
Member Function Documentation
int Entree_fluide_V2_impose::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_K_Eps_impose sont compatibles
avec une equation dont le domaine est le Transport_Keps
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Definition at line 88 of file Entree_fluide_V2_impose.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle V2="Transport_V2";
  Motcle indetermine="indetermine";
  if ( (dom_app==V2) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Entree_fluide_V2_impose::cree_instance () [static]
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
int Entree_fluide_V2_impose::duplique () const [virtual]
Implements Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
const Type_info * Entree_fluide_V2_impose::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
const Type_info * Entree_fluide_V2_impose::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
Sortie & Entree_fluide_V2_impose::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 44 of file Entree_fluide_V2_impose.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Entree_fluide_V2_impose::readOn (Entree & s) [protected, virtual]
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 63 of file Entree_fluide_V2_impose.cpp.
{
  return Cond_lim_base::readOn(s);
}
const Entree_fluide_V2_impose & Entree_fluide_V2_impose::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
Entree_fluide_V2_impose & Entree_fluide_V2_impose::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
unsigned Entree_fluide_V2_impose::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Entree_fluide_V2_impose.cpp.
Member Data Documentation
const Type_info Entree_fluide_V2_impose::info_obj [static]
Reimplemented from Dirichlet_entree_fluide.
Definition at line 47 of file Entree_fluide_V2_impose.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_V2_impose.h
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_V2_impose.cpp