TRUST: Rotationnel_Champ_Face Class Reference
Rotationnel_Champ_Face Class Reference
classe Rotationnel_Champ_Face
#include <Rotationnel_Champ_Face.h>
Public Member Functions
Rotationnel_Champ_Face ()
~Rotationnel_Champ_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_Face & mon_champ () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face &)
void me_calculer (double)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Rotationnel_Champ_Face & self_cast (Objet_U &)
static const
Rotationnel_Champ_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Face mon_champ_
Detailed Description
classe Rotationnel_Champ_Face
Definition at line 37 of file Rotationnel_Champ_Face.h.
Constructor & Destructor Documentation
Rotationnel_Champ_Face::Rotationnel_Champ_Face ()
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
Rotationnel_Champ_Face::~Rotationnel_Champ_Face ()
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
Member Function Documentation
void Rotationnel_Champ_Face::associer_champ (const Champ_Face & un_champ)
Definition at line 45 of file Rotationnel_Champ_Face.cpp.
References mon_champ_.
Referenced by VDF_discretisation::creer_champ_vorticite(), and VDF_discretisation::vorticite().
{
  mon_champ_= un_champ;
}
Objet_U * Rotationnel_Champ_Face::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
int Rotationnel_Champ_Face::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
const Type_info * Rotationnel_Champ_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
const Type_info * Rotationnel_Champ_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
void Rotationnel_Champ_Face::me_calculer (double tps) [virtual]
Implements Champ_Rotationnel.
Definition at line 50 of file Rotationnel_Champ_Face.cpp.
References mon_champ_, and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
  mon_champ_->calculer_rotationnel_ordre2_centre_element(valeurs());
}
void Rotationnel_Champ_Face::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 61 of file Rotationnel_Champ_Face.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
const Champ_Face & Rotationnel_Champ_Face::mon_champ () const [inline]
Definition at line 56 of file Rotationnel_Champ_Face.h.
{
  return mon_champ_.valeur();
}
Sortie & Rotationnel_Champ_Face::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 32 of file Rotationnel_Champ_Face.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Rotationnel_Champ_Face::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 40 of file Rotationnel_Champ_Face.cpp.
{
  return s ;
}
const Rotationnel_Champ_Face & Rotationnel_Champ_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
Rotationnel_Champ_Face & Rotationnel_Champ_Face::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
unsigned Rotationnel_Champ_Face::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 26 of file Rotationnel_Champ_Face.cpp.
Member Data Documentation
const Type_info Rotationnel_Champ_Face::info_obj [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 42 of file Rotationnel_Champ_Face.h.
Ref_Champ_Face Rotationnel_Champ_Face::mon_champ_ [protected]
Definition at line 53 of file Rotationnel_Champ_Face.h.
Referenced by associer_champ(), and me_calculer().
The documentation for this class was generated from the following files:
src/VDF/Champs/Rotationnel_Champ_Face.h
src/VDF/Champs/Rotationnel_Champ_Face.cpp