TRUST: Postraitement_lata Class Reference
Postraitement_lata Class Reference
:
Classe de postraitement des champs euleriens au format lata.
On peut l'utiliser sans creer d'instance de la classe:
Pour creer un fichier valide, il faut faire:
(initialisation) ecrire_entete(...)
ecrire_zone(..., zone1, ...)
[ecrire_zone(..., zone2, ...)]
[... ]
(pour chaque dt) ecrire_temps(..., temps, ...)
ecrire_champ(..., valeurs, ...)
[ecrire_champ(..., valeurs, ...)]
[... ]
Lors des appels aux fonctions statiques, si comm_group == 0,
on ecrit un fichier de postraitement par processeur, sinon on
creee un fichier unique partage.
Si on cree une instance de la classe, l'entete du fichier
est ecrite lors du premier appel a "postraitement".
#include <Postraitement_lata.h>
Public Types
enum Format { ASCII , BINAIRE }
enum Type_Champ { CHAMP =0 , STATISTIQUE =1 }
Public Types inherited from Postraitement_base
enum Format { ASCII , BINAIRE }
enum Type_Champ { CHAMP =0 , STATISTIQUE =1 }
enum Localisation { SOMMETS =0 , ELEMENTS =1 , FACES =2 }
enum Type_Post { ERREUR =-1 , ENTIER =0 , REEL =1 , DOUBLE =2 }
Public Member Functions
~Postraitement_lata ()
Destroy me ... muahahahaha.
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Postraitement_lata ()
Constructeur par defaut: initialisation des membres avec des valeurs
par defaut.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void postraiter (int forcer) override
Ecrit l'entete si ca n'a pas ete fait, puis, si le temps est ecoule,
post-traite les champs demandes. Le temps actuel est le temps
attribue lors du dernier appel a mettre_a_jour du postraitement.
void completer () override
Public Member Functions inherited from Postraitement_base
~Postraitement_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Postraitement_base ()
virtual void associer_nom_et_pb_base (const Nom &, const Probleme_base &)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void postraiter (int forcer)=0
virtual void mettre_a_jour (double temps)
virtual void init ()
virtual void finir ()
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual void completer ()=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Postraitement_lata & self_cast (Objet_U &)
static const Postraitement_lata & self_cast (const Objet_U &)
static void ecrire_entete (const Nom &basename, const Nom &discretisation, Format format=ASCII, const Comm_Group *comm_group=0)
static void ecrire_temps (const Nom &basename, const double temps, Format format=ASCII, const Comm_Group *comm_group=0)
static void ecrire_zone (const Nom &basename, const Zone &, Format format=ASCII, const Comm_Group *comm_group=0, const Zone_dis_base *la_zone_dis=0)
static void ecrire_champ (const Nom &basename, const Nom &nom_du_champ, Type_Champ type, char type_char, const Nom &nom_domaine, const Nom &nom_probleme, double temps, Localisation localisation, const DoubleTab &data, Format format=ASCII, const Comm_Group *comm_group=0)
static const Nom & extension_lata ()
Renvoie l'extension conventionnelle des fichiers lata : ".lata".
static const char * remove_path (const char *filename)
Renvoie le nom d'un fichier sans le path :
on enleve les caracteres avant le dernier /.
static int finir_lata (const Nom &basename, const Comm_Group *comm_group=0)
Static Public Member Functions inherited from Postraitement_base
static const Type_info * info ()
static Postraitement_base & self_cast (Objet_U &)
static const Postraitement_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Postraitement_base
static const Type_info info_obj
static const char *const demande_description = "DESCRIPTION"
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Appel a Postraitement_base::readOn.
void lire_format (Entree &)
lecture du format d'enregistrement (ascii ou binaire)
void lire_champs (Entree &is)
lecture d'une liste de champs a postraiter
On attend ceci :
champs sommets|elements|faces (le mot cle champs a deja ete lu)
{
nom_du_champ
[ nom_du_champ ]
[ ... ]
}
Les champs lus sont ajoutes a la liste correspondante (sommets, elements, ...),
les doublons sont retires.
Le nom du champ doit etre compris par le probleme (pb.comprend_champ(...))
Attention: les champs postraites aux faces doivent etre discretises aux faces
(pas d'interpolation, on postraite le champ tel quel).
int dt_post_ecoule (double &dt_post_, double temps_dernier_post)
renvoie 1 si l'intervalle de temps demande entre deux
postraitements est ecoule.
void postraiter_liste_champs (Localisation loc, const Motcles &liste)
Evident...
Parametre: loc
valeurs autorisees: SOMMETS, ou ELEMENTS ou FACES
Parametre: liste
une liste de champs compris par le probleme.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom lata_basename_
Format format_
int fichiers_multiples_
int entete_ok_
int skip_header_
double dt_post_
Parser_U fdt_post
double temps_dernier_post_
Motcles liste_champs_aux_sommets
Motcles liste_champs_aux_elements
Motcles liste_champs_aux_faces
Sortie * verbose_stream_
Protected Attributes inherited from Postraitement_base
Nom le_nom_
Ref_Probleme_base mon_probleme
double temps_
Private Attributes
Postraitement_lata_private_data * private_data_
Detailed Description
:
Classe de postraitement des champs euleriens au format lata.
On peut l'utiliser sans creer d'instance de la classe:
Pour creer un fichier valide, il faut faire:
(initialisation) ecrire_entete(...)
ecrire_zone(..., zone1, ...)
[ecrire_zone(..., zone2, ...)]
[... ]
(pour chaque dt) ecrire_temps(..., temps, ...)
ecrire_champ(..., valeurs, ...)
[ecrire_champ(..., valeurs, ...)]
[... ]
Lors des appels aux fonctions statiques, si comm_group == 0,
on ecrit un fichier de postraitement par processeur, sinon on
creee un fichier unique partage.
Si on cree une instance de la classe, l'entete du fichier
est ecrite lors du premier appel a "postraitement".
Definition at line 48 of file Postraitement_lata.h.
Member Enumeration Documentation
Format
enum Postraitement_lata::Format
Enumerator
ASCII
BINAIRE
Definition at line 58 of file Postraitement_lata.h.
{ ASCII, BINAIRE };
Type_Champ
enum Postraitement_lata::Type_Champ
Enumerator
CHAMP
STATISTIQUE
Definition at line 59 of file Postraitement_lata.h.
{ CHAMP=0, STATISTIQUE=1 };
Constructor & Destructor Documentation
~Postraitement_lata()
Postraitement_lata::~Postraitement_lata ()
Destroy me ... muahahahaha.
Definition at line 220 of file Postraitement_lata.cpp.
{
  delete private_data_;
}
References private_data_.
Postraitement_lata()
Postraitement_lata::Postraitement_lata ()
Constructeur par defaut: initialisation des membres avec des valeurs
par defaut.
Definition at line 203 of file Postraitement_lata.cpp.
{
// Les donnees privees de la classe:
  private_data_ = new Postraitement_lata_private_data;
// Quelques valeurs par defaut
  lata_basename_ = Objet_U::nom_du_cas();
  format_ = BINAIRE;
  fichiers_multiples_ = 0;
  entete_ok_ = 0;
  skip_header_ = 0;
  dt_post_ = 0.;
  temps_dernier_post_ = -1E40;
  verbose_stream_ = 0;
}
References BINAIRE, dt_post_, entete_ok_, fichiers_multiples_, format_, lata_basename_, Objet_U::nom_du_cas(), private_data_, skip_header_, temps_dernier_post_, and verbose_stream_.
Member Function Documentation
completer()
void Postraitement_lata::completer () inline override virtual
Implements Postraitement_base.
Definition at line 56 of file Postraitement_lata.h.
{}
cree_instance()
Objet_U * Postraitement_lata::cree_instance () static
Definition at line 36 of file Postraitement_lata.cpp.
dt_post_ecoule()
int Postraitement_lata::dt_post_ecoule (double & dt_post_, double temps_dernier_post) protected
renvoie 1 si l'intervalle de temps demande entre deux
postraitements est ecoule.
Definition at line 597 of file Postraitement_lata.cpp.
{
  if (dt_post<=temps_ - temps_dernier_post_ || dt_post==0)
    return 1;
  else
    {
      fdt_post.setVar("t",temps_);
      dt_post = fdt_post.eval();
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      double i, j, epsilon = 1.e-8;
      modf(temps_/dt_post + epsilon, &i);
      modf(temps_dernier_post/dt_post + epsilon, &j);
      return ( i>j );
    }
}
References Parser_U::eval(), fdt_post, Parser_U::setVar(), Postraitement_base::temps_, and temps_dernier_post_.
Referenced by postraiter().
duplique()
int Postraitement_lata::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Postraitement_lata.cpp.
ecrire_champ()
void Postraitement_lata::ecrire_champ (const Nom & basename, const Nom & nom_du_champ, Type_Champ type, char type_char, const Nom & nom_domaine, const Nom & nom_probleme, double temps, Localisation localisation, const DoubleTab & data, Format format = ASCII, const Comm_Group * comm_group = 0) static
Definition at line 137 of file Postraitement_lata.cpp.
{
  Format_Post_Lata::Options_Para option;
  if (comm_group)
    option = Format_Post_Lata::SINGLE_FILE;
  else
    option = Format_Post_Lata::MULTIPLE_FILES;
  Format_Post_Lata::Format fmt;
  if (format == ASCII)
    fmt = Format_Post_Lata::ASCII;
  else
    fmt = Format_Post_Lata::BINAIRE;
  Nom loc;
  switch (localisation)
    {
    case SOMMETS:
      loc = "SOM";
      break;
    case ELEMENTS:
      loc = "ELEM";
      break;
    case FACES:
      loc = "FACES";
      break;
    }
  Format_Post_Lata_V1::ecrire_champ_lata_V1(nom_du_champ,
                                            nom_domaine,
                                            loc,
                                            valeurs,
                                            temps,
                                            basename,
                                            fmt,
                                            option);
}
References Format_Post_Lata::ASCII, ASCII, Format_Post_Lata::BINAIRE, Format_Post_Lata_V1::ecrire_champ_lata_V1(), Postraitement_base::ELEMENTS, Postraitement_base::FACES, Format_Post_Lata::MULTIPLE_FILES, Format_Post_Lata::SINGLE_FILE, and Postraitement_base::SOMMETS.
Referenced by dump_lata(), postraiter_decoupage(), and postraiter_liste_champs().
ecrire_entete()
void Postraitement_lata::ecrire_entete (const Nom & basename, const Nom & discretisation, Format format = ASCII, const Comm_Group * comm_group = 0) static
Definition at line 61 of file Postraitement_lata.cpp.
{
  Format_Post_Lata::Options_Para option;
  if (comm_group)
    option = Format_Post_Lata::SINGLE_FILE;
  else
    option = Format_Post_Lata::MULTIPLE_FILES;
  Format_Post_Lata_V1::ecrire_entete_lata_V1(basename,
                                             option,
                                             1 /* est le premier post */);
}
References Format_Post_Lata_V1::ecrire_entete_lata_V1(), Format_Post_Lata::MULTIPLE_FILES, and Format_Post_Lata::SINGLE_FILE.
Referenced by dump_lata(), postraiter(), and postraiter_decoupage().
ecrire_temps()
void Postraitement_lata::ecrire_temps (const Nom & basename, const double temps, Format format = ASCII, const Comm_Group * comm_group = 0) static
Definition at line 116 of file Postraitement_lata.cpp.
{
  Format_Post_Lata::Options_Para option;
  if (comm_group)
    option = Format_Post_Lata::SINGLE_FILE;
  else
    option = Format_Post_Lata::MULTIPLE_FILES;
  Format_Post_Lata::Status status = Format_Post_Lata::INITIALIZED;
  double t = temps;
  Format_Post_Lata::ecrire_temps_lata(temps,
                                      t,
                                      basename,
                                      status,
                                      option);
}
References Format_Post_Lata::ecrire_temps_lata(), Format_Post_Lata::INITIALIZED, Format_Post_Lata::MULTIPLE_FILES, and Format_Post_Lata::SINGLE_FILE.
Referenced by dump_lata(), postraiter(), and postraiter_decoupage().
ecrire_zone()
void Postraitement_lata::ecrire_zone (const Nom & basename, const Zone & , Format format = ASCII, const Comm_Group * comm_group = 0, const Zone_dis_base * la_zone_dis = 0) static
Definition at line 77 of file Postraitement_lata.cpp.
{
  Format_Post_Lata::Options_Para option;
  if (comm_group)
    option = Format_Post_Lata::SINGLE_FILE;
  else
    option = Format_Post_Lata::MULTIPLE_FILES;
  Format_Post_Lata::Format fmt;
  if (format == ASCII)
    fmt = Format_Post_Lata::ASCII;
  else
    fmt = Format_Post_Lata::BINAIRE;
  Format_Post_Lata_V1::ecrire_domaine_lata_V1(la_zone.domaine().le_nom(),
                                              la_zone.type_elem().valeur().que_suis_je(),
                                              Objet_U::dimension,
                                              la_zone.domaine().les_sommets(),
                                              la_zone.les_elems(),
                                              Format_Post_Lata::INITIALIZED,
                                              basename,
                                              fmt,
                                              option);
  if (la_zone_dis)
    {
      Format_Post_Lata_V1::ecrire_faces_lata_V1(basename,
                                                fmt,
                                                option,
                                                la_zone.domaine().le_nom(),
                                                la_zone_dis->face_sommets(),
                                                ref_cast(Zone_VF, *la_zone_dis).elem_faces(),
                                                la_zone.domaine().les_sommets().dimension(0));
    }
}
References Format_Post_Lata::ASCII, ASCII, Format_Post_Lata::BINAIRE, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Zone_dis_base::face_sommets(), Format_Post_Lata::INITIALIZED, Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Format_Post_Lata::MULTIPLE_FILES, Objet_U::que_suis_je(), ref_cast, Format_Post_Lata::SINGLE_FILE, Zone::type_elem(), and Deriv_Elem_geom_base::valeur().
Referenced by dump_lata(), postraiter(), and postraiter_decoupage().
extension_lata()
const Nom & Postraitement_lata::extension_lata () static
Renvoie l'extension conventionnelle des fichiers lata : ".lata".
Definition at line 43 of file Postraitement_lata.cpp.
{
  static const Nom extension_(".lata");
  return extension_;
}
finir_lata()
int Postraitement_lata::finir_lata (const Nom & basename, const Comm_Group * comm_group = 0) static
Definition at line 184 of file Postraitement_lata.cpp.
{
  Format_Post_Lata::Options_Para option;
  if (comm_group)
    option = Format_Post_Lata::SINGLE_FILE;
  else
    option = Format_Post_Lata::MULTIPLE_FILES;
  Format_Post_Lata_V1::finir_lata_V1(basename,
                                     option,
                                     1);
  return 1;
}
References Format_Post_Lata_V1::finir_lata_V1(), Format_Post_Lata::MULTIPLE_FILES, and Format_Post_Lata::SINGLE_FILE.
Referenced by postraiter_decoupage().
get_info()
const Type_info * Postraitement_lata::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Postraitement_base.
Definition at line 36 of file Postraitement_lata.cpp.
info()
const Type_info * Postraitement_lata::info () static
Definition at line 36 of file Postraitement_lata.cpp.
lire_champs()
void Postraitement_lata::lire_champs (Entree & is) protected
lecture d'une liste de champs a postraiter
On attend ceci :
champs sommets|elements|faces (le mot cle champs a deja ete lu)
{
nom_du_champ
[ nom_du_champ ]
[ ... ]
}
Les champs lus sont ajoutes a la liste correspondante (sommets, elements, ...),
les doublons sont retires.
Le nom du champ doit etre compris par le probleme (pb.comprend_champ(...))
Attention: les champs postraites aux faces doivent etre discretises aux faces
(pas d'interpolation, on postraite le champ tel quel).
Definition at line 318 of file Postraitement_lata.cpp.
{
  Motcle motcle;
  is >> motcle;
  Localisation loc = SOMMETS;
  if (motcle == "sommets")
    loc = SOMMETS;
  else if (motcle == "elements")
    loc = ELEMENTS;
  else if (motcle == "faces")
    loc = FACES;
  else
    {
      Cerr << "Error in Postraitement_lata::lire_champs :" << finl;
      Cerr << " We read : " << motcle << finl;
      Cerr << " We expected \"sommets\", \"elements\" or \"faces\" after \"champs\"" << finl;
      exit();
    }
  Motcles& liste =
    (loc == SOMMETS) ? liste_champs_aux_sommets
    : (loc == ELEMENTS) ? liste_champs_aux_elements
    : liste_champs_aux_faces;
  is >> motcle;
  if (motcle != "{")
    {
      Cerr << "Error in Postraitement_lata::lire_champs :" << finl;
      Cerr << " We read : " << motcle << finl;
      Cerr << " We expected { after sommets/elements/faces." << finl;
      exit();
    }
  Probleme_base& pb = mon_probleme.valeur();
  REF(Champ_base) refch_base;
  while (1)
    {
      is >> motcle;
      if (motcle == "}")
        break;
      Noms liste_noms;
      pb.get_noms_champs_postraitables(liste_noms);
      pb.creer_champ(motcle);
      int ok=0;
      for (int i=0; i<liste_noms.size(); i++)
        if (Motcle(liste_noms[i])==motcle) ok=1;
      if (!ok)
        {
          Cerr << "Error in Postraitement_lata::lire_champs :\n";
          Cerr << " The field " << motcle;
          Cerr << " is not understood by the problem " << pb.le_nom() << finl;
          exit();
        }
// Si un champ aux faces est demande, il faut que le champ d'origine
// soit aux faces (on ne sait pas interpoler le champ)
      if (loc == FACES)
        {
          refch_base = pb.get_champ(motcle);
          const int nb_valeurs =
            refch_base.valeur().valeurs().dimension(0);
          const int nb_faces =
            pb.domaine_dis().zone_dis(0).valeur().face_sommets().dimension(0);
          if (nb_valeurs != nb_faces)
            {
              Cerr << "Error in Postraitement_lata::lire_champs :\n";
              Cerr << " The field " << motcle;
              Cerr << " can not be postprocessed to the faces.\n";
              Cerr << " (Fields allowed: only fields discretized to the faces)" << finl;
              exit();
            }
        }
      if (!liste.contient_(motcle))
        liste.add(motcle);
    }
}
References liste::add(), Cerr, Probleme_base::creer_champ(), TRUSTTab< _TYPE_ >::dimension(), Probleme_base::domaine_dis(), Postraitement_base::ELEMENTS, Process::exit(), Zone_dis_base::face_sommets(), Postraitement_base::FACES, finl, Probleme_base::get_champ(), Probleme_base::get_noms_champs_postraitables(), Probleme_base::le_nom(), liste_champs_aux_elements, liste_champs_aux_faces, liste_champs_aux_sommets, Postraitement_base::mon_probleme, REF, vect_impl::size(), Postraitement_base::SOMMETS, Ref_Probleme_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Proto::valeurs(), and Domaine_dis::zone_dis().
Referenced by lire_motcle_non_standard().
lire_format()
void Postraitement_lata::lire_format (Entree & is) protected
lecture du format d'enregistrement (ascii ou binaire)
Definition at line 288 of file Postraitement_lata.cpp.
{
  Motcle motcle;
  is >> motcle;
  if (motcle == "ascii")
    format_ = ASCII;
  else if (motcle == "binaire")
    format_ = BINAIRE;
  else
    {
      Cerr << "Postraitement_lata::lire_format" << finl;
      Cerr << " We expected \"ascii\" or \"binaire\" after format." << finl;
      Cerr << " We found " << motcle << finl;
      exit();
    }
}
References ASCII, BINAIRE, Cerr, Process::exit(), finl, and format_.
Referenced by lire_motcle_non_standard().
lire_motcle_non_standard()
int Postraitement_lata::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Postraitement_base.
Definition at line 253 of file Postraitement_lata.cpp.
{
  if (mot=="format")
    {
      lire_format(is);
      return 1;
    }
  else if (mot=="champs|fields")
    {
      lire_champs(is);
      return 1;
    }
  else if (mot=="print")
    {
      if (Process::je_suis_maitre()) verbose_stream_ = &Cerr;
      return 1;
    }
  else if (mot=="dt_post")
    {
      Nom expression;
      is >> expression;
      Cerr << expression;
      fdt_post.setNbVar(1);
      fdt_post.setString(expression);
      fdt_post.addVar("t");
      fdt_post.parseString();
      dt_post_ = fdt_post.eval();
      return 1;
    }
  else
    return Postraitement_base::lire_motcle_non_standard(mot,is);
  return 1;
}
References Parser_U::addVar(), Cerr, dt_post_, Parser_U::eval(), fdt_post, Process::je_suis_maitre(), lire_champs(), lire_format(), Postraitement_base::lire_motcle_non_standard(), Parser_U::parseString(), Parser_U::setNbVar(), Parser_U::setString(), and verbose_stream_.
postraiter()
void Postraitement_lata::postraiter (int forcer) override virtual
Ecrit l'entete si ca n'a pas ete fait, puis, si le temps est ecoule,
post-traite les champs demandes. Le temps actuel est le temps
attribue lors du dernier appel a mettre_a_jour du postraitement.
Implements Postraitement_base.
Definition at line 535 of file Postraitement_lata.cpp.
{
  /*
            if (verbose_stream_) {
            *verbose_stream_ << "Postraitement_lata::postraiter nom:" << le_nom();
            *verbose_stream_ << " fichier:" << lata_basename_ << finl;
            } */
  const Comm_Group * comm_group = 0;
  if (fichiers_multiples_ == 0)
    comm_group = & PE_Groups::groupe_TRUST();
  if (! skip_header_)
    {
      if (! entete_ok_)
        {
// Ecriture de l'entete du fichier
          if (verbose_stream_)
            *verbose_stream_ << " Ecriture de l'entete." << finl;
          ecrire_entete(lata_basename_,
                        mon_probleme.valeur().discretisation().que_suis_je(),
                        format_,
                        comm_group);
          if (verbose_stream_)
            *verbose_stream_ << " Ecriture de la zone." << finl;
// S'il y a des champs aux faces a postraiter, ecrire les faces
          const Zone_dis_base * zone_dis_baseptr = 0;
          if (liste_champs_aux_faces.size() > 0)
            zone_dis_baseptr = & mon_probleme.valeur().domaine_dis().zone_dis(0).valeur();
          ecrire_zone(lata_basename_,
                      mon_probleme.valeur().domaine().zone(0),
                      format_,
                      comm_group,
                      zone_dis_baseptr);
          entete_ok_ = 1;
        }
    }
  if (! forcer)
    if (! dt_post_ecoule(dt_post_, temps_dernier_post_))
// L'intervalle de temps entre postraitements n'est pas ecoule
      return;
  if (! skip_header_)
    {
      if (verbose_stream_)
        *verbose_stream_ << " Ecriture du temps : " << temps_ << finl;
      ecrire_temps(lata_basename_,
                   temps_,
                   format_,
                   comm_group);
    }
  postraiter_liste_champs(SOMMETS, liste_champs_aux_sommets);
  postraiter_liste_champs(ELEMENTS, liste_champs_aux_elements);
  if (liste_champs_aux_faces.size() > 0)
    postraiter_liste_champs(FACES, liste_champs_aux_faces);
  temps_dernier_post_ = temps_;
}
References Probleme_base::discretisation(), Probleme_base::domaine(), Probleme_base::domaine_dis(), dt_post_, dt_post_ecoule(), ecrire_entete(), ecrire_temps(), ecrire_zone(), Postraitement_base::ELEMENTS, entete_ok_, Postraitement_base::FACES, fichiers_multiples_, finl, format_, PE_Groups::groupe_TRUST(), lata_basename_, liste_champs_aux_elements, liste_champs_aux_faces, liste_champs_aux_sommets, Postraitement_base::mon_probleme, postraiter_liste_champs(), Objet_U::que_suis_je(), vect_impl::size(), skip_header_, Postraitement_base::SOMMETS, Postraitement_base::temps_, temps_dernier_post_, Ref_Probleme_base::valeur(), Deriv_Zone_dis_base::valeur(), verbose_stream_, Domaine::zone(), and Domaine_dis::zone_dis().
postraiter_liste_champs()
void Postraitement_lata::postraiter_liste_champs (Localisation loc, const Motcles & liste) protected
Evident...
Parametre: loc
valeurs autorisees: SOMMETS, ou ELEMENTS ou FACES
Parametre: liste
une liste de champs compris par le probleme.
< nom du champ
< type
< champ instationnaire
Definition at line 402 of file Postraitement_lata.cpp.
{
  if (verbose_stream_)
    {
      *verbose_stream_ << "Postraitement_lata::postraiter_liste_champs ";
      switch(loc)
        {
        case SOMMETS:
          *verbose_stream_ << "sommets" << finl;
          break;
        case ELEMENTS:
          *verbose_stream_ << "elements" << finl;
          break;
        case FACES:
          *verbose_stream_ << "faces" << finl;
          break;
        default:
          Cerr << "Localization " << (int)loc << " not recognized in Postraitement_lata::postraiter_liste_champs" << finl;
          exit();
        }
    }
  const Comm_Group * comm_group = 0;
  if (fichiers_multiples_ == 0)
    comm_group = & PE_Groups::groupe_TRUST();
  const int nb_champs = liste.size();
  if (nb_champs == 0)
    return;
// Postraitement des champs :
  const Probleme_base& pb          = mon_probleme.valeur();
  const Zone&           la_zone     = pb.domaine().zone(0);
  const Zone_dis_base&  zone_dis    = pb.domaine_dis().zone_dis(0).valeur();
  const int          nb_elem     = la_zone.nb_elem();
  const int          nb_sommets  = la_zone.nb_som();
  DoubleTab&            valeurs             = private_data_->valeurs;
  DoubleTab&            centres_de_gravites = private_data_->centres_de_gravites;
  IntVect&              les_polys           = private_data_->les_polys;
  REF(Champ_base) &     le_champ            = private_data_->le_champ;
  if (loc == ELEMENTS)
    {
//
// Ouille... faut calculer ca ???
//
      const Zone_VF& zvf = ref_cast(Zone_VF,zone_dis);
      centres_de_gravites = zvf.xp();
      les_polys.resize(nb_elem);
      int i;
      for (i = 0; i < nb_elem; i++)
        les_polys(i) = i;
    }
  for (int i = 0; i < nb_champs; i++)
    {
      const Motcle nom_du_champ = liste[i];
      if (verbose_stream_)
        *verbose_stream_ << "Postraitement du champ " << nom_du_champ << finl;
      le_champ = pb.get_champ(nom_du_champ);
      {
        if (loc == FACES)
          valeurs.resize(0);
        else if (loc == SOMMETS )
          {
            int dimension0 = (loc==SOMMETS) ? nb_sommets : nb_elem;
            const int dimension1 = le_champ.valeur().nb_comp();
            valeurs.resize(dimension0, dimension1);
          }
        else
          {
            int dimension0 = (loc==SOMMETS) ? nb_sommets : nb_elem;
            if (le_champ.valeur().nb_comp() == 1)
              valeurs.resize(dimension0);
            else
              {
                const int dimension1 = le_champ.valeur().nb_comp();
                valeurs.resize(dimension0, dimension1);
              }
          }
      }
      DoubleTab * valeurs_a_ecrire = 0;
      switch (loc)
        {
        case SOMMETS:
// Interpolation du champ aux sommets
          le_champ.valeur().valeur_aux_sommets(pb.domaine(), valeurs);
          valeurs_a_ecrire = &valeurs;
          break;
        case ELEMENTS:
// Interpolation du champ aux elements
          le_champ.valeur().valeur_aux_elems(centres_de_gravites, les_polys, valeurs);
          valeurs_a_ecrire = &valeurs;
          break;
        case FACES:
// Pour un champ aux faces, aucune interpolation, on ecrit le tableau tel quel.
          valeurs_a_ecrire = &le_champ.valeur().valeurs();
          break;
        default:
          exit();
        }
      ecrire_champ(lata_basename_,
                   nom_du_champ, //!< nom du champ
                   CHAMP,  //!< type
                   'I',    //!< champ instationnaire
                   pb.domaine().le_nom(),
                   pb.le_nom(),
                   temps_,
                   loc,
                   *valeurs_a_ecrire,
                   format_,
                   comm_group);
    }
// On libere la memoire des tableaux temporaires
// (mais on garde les objets)
// valeurs.resize(0);
  valeurs.reset();
  centres_de_gravites.resize(0);
  les_polys.resize(0);
}
References Postraitement_lata_private_data::centres_de_gravites, Cerr, CHAMP, Probleme_base::domaine(), Probleme_base::domaine_dis(), ecrire_champ(), Postraitement_base::ELEMENTS, Process::exit(), Postraitement_base::FACES, fichiers_multiples_, finl, format_, Probleme_base::get_champ(), PE_Groups::groupe_TRUST(), lata_basename_, Postraitement_lata_private_data::le_champ, Probleme_base::le_nom(), Domaine::le_nom(), Postraitement_lata_private_data::les_polys, Postraitement_base::mon_probleme, Zone::nb_elem(), Zone::nb_som(), private_data_, REF, ref_cast, TRUSTTab< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), liste::size(), Postraitement_base::SOMMETS, Postraitement_base::temps_, Ref_Probleme_base::valeur(), Deriv_Zone_dis_base::valeur(), Postraitement_lata_private_data::valeurs, verbose_stream_, Zone_VF::xp(), Domaine::zone(), and Domaine_dis::zone_dis().
Referenced by postraiter().
printOn()
Sortie & Postraitement_lata::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Postraitement_base.
Definition at line 232 of file Postraitement_lata.cpp.
{
  return os;
}
readOn()
Entree & Postraitement_lata::readOn (Entree & is) override protected virtual
Appel a Postraitement_base::readOn.
Reimplemented from Postraitement_base.
Definition at line 226 of file Postraitement_lata.cpp.
{
  Postraitement_base::readOn(is);
  return is;
}
References Postraitement_base::readOn().
remove_path()
const char * Postraitement_lata::remove_path (const char * filename) static
Renvoie le nom d'un fichier sans le path :
on enleve les caracteres avant le dernier /.
Definition at line 52 of file Postraitement_lata.cpp.
{
  int i = strlen(filename);
  while (i > 0 && filename[i-1] != '/')
    i--;
  return filename + i;
}
self_cast() [1/2]
const Postraitement_lata & Postraitement_lata::self_cast (const Objet_U & r) static
Definition at line 36 of file Postraitement_lata.cpp.
self_cast() [2/2]
Postraitement_lata & Postraitement_lata::self_cast (Objet_U & r) static
Definition at line 36 of file Postraitement_lata.cpp.
set_param()
void Postraitement_lata::set_param (Param & param) override virtual
Implements Postraitement_base.
Definition at line 237 of file Postraitement_lata.cpp.
{
// Nom msg;
// msg = "Post-processing period for ";
// msg += que_suis_je();
// msg += " must be greater or equal to 0.";
// param.ajouter_condition("value_of_dt_post_ge_0",msg);
  param.ajouter("nom_fichier",&lata_basename_);
  param.ajouter("fichiers_multiples",&fichiers_multiples_);
  param.ajouter("skip_header",&skip_header_);
  param.ajouter_non_std("format",(this));
  param.ajouter_non_std("champs|fields",(this));
  param.ajouter_non_std("print",(this));
  param.ajouter_non_std("dt_post",(this));
}
References Param::ajouter(), Param::ajouter_non_std(), fichiers_multiples_, lata_basename_, and skip_header_.
taille_memoire()
unsigned Postraitement_lata::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Postraitement_lata.cpp.
Member Data Documentation
dt_post_
double Postraitement_lata::dt_post_ protected
Definition at line 91 of file Postraitement_lata.h.
Referenced by lire_motcle_non_standard(), Postraitement_lata(), and postraiter().
entete_ok_
int Postraitement_lata::entete_ok_ protected
Definition at line 85 of file Postraitement_lata.h.
Referenced by Postraitement_lata(), and postraiter().
fdt_post
Parser_U Postraitement_lata::fdt_post protected
Definition at line 93 of file Postraitement_lata.h.
Referenced by dt_post_ecoule(), and lire_motcle_non_standard().
fichiers_multiples_
int Postraitement_lata::fichiers_multiples_ protected
Definition at line 83 of file Postraitement_lata.h.
Referenced by Postraitement_lata(), postraiter(), postraiter_liste_champs(), and set_param().
format_
Format Postraitement_lata::format_ protected
Definition at line 81 of file Postraitement_lata.h.
Referenced by lire_format(), Postraitement_lata(), postraiter(), and postraiter_liste_champs().
info_obj
const Type_info Postraitement_lata::info_obj static
Definition at line 50 of file Postraitement_lata.h.
lata_basename_
Nom Postraitement_lata::lata_basename_ protected
Definition at line 79 of file Postraitement_lata.h.
Referenced by Postraitement_lata(), postraiter(), postraiter_liste_champs(), and set_param().
liste_champs_aux_elements
Motcles Postraitement_lata::liste_champs_aux_elements protected
Definition at line 98 of file Postraitement_lata.h.
Referenced by lire_champs(), and postraiter().
liste_champs_aux_faces
Motcles Postraitement_lata::liste_champs_aux_faces protected
Definition at line 99 of file Postraitement_lata.h.
Referenced by lire_champs(), and postraiter().
liste_champs_aux_sommets
Motcles Postraitement_lata::liste_champs_aux_sommets protected
Definition at line 97 of file Postraitement_lata.h.
Referenced by lire_champs(), and postraiter().
private_data_
Postraitement_lata_private_data* Postraitement_lata::private_data_ private
Definition at line 104 of file Postraitement_lata.h.
Referenced by Postraitement_lata(), postraiter_liste_champs(), and ~Postraitement_lata().
skip_header_
int Postraitement_lata::skip_header_ protected
Definition at line 89 of file Postraitement_lata.h.
Referenced by Postraitement_lata(), postraiter(), and set_param().
temps_dernier_post_
double Postraitement_lata::temps_dernier_post_ protected
Definition at line 95 of file Postraitement_lata.h.
Referenced by dt_post_ecoule(), Postraitement_lata(), and postraiter().
verbose_stream_
Sortie* Postraitement_lata::verbose_stream_ protected
Definition at line 101 of file Postraitement_lata.h.
Referenced by lire_motcle_non_standard(), Postraitement_lata(), postraiter(), and postraiter_liste_champs().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Postraitement_lata.h
src/Kernel/Framework/Postraitement_lata.cpp