TRUST: Champ_front_calc Class Reference
Champ_front_calc Class Reference
classe Champ_front_calc
Classe derivee de Champ_front_var qui represente les
champs a la frontiere obtenus en prenant la trace
d'un objet de type Champ_Inc (champ inconnue d'une equation)
#include <Champ_front_calc.h>
Public Member Functions
~Champ_front_calc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_calc ()
void completer () override
int initialiser (double, const Champ_Inc_base &) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
void associer_ch_inc_base (const Champ_Inc_base &)
Associe le champ inconnue a l'objet.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Non code.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ
On prend juste la trace du champ inconnue au pas de
temps auquel il se situe.
WEC : verifier qu'on prend l'inconnue au bon temps !
void creer (const Nom &, const Nom &, const Motcle &)
Cree l'objet Champ_front_calc representant la trace d'un champ
inconnue sur une frontiere a partir des noms:
- du probleme portant l'inconnue
- du bord concerne (la frontiere)
- de l'inconnue.
void verifier (const Cond_lim_base &la_cl) const override
const Champ_Inc_base & inconnue () const
Renvoie le champ inconnue associe.
const Nom & nom_bord_oppose () const
Renvoie le nom du bord sur lequel on calcule la trace.
const Equation_base & equation () const
Renvoie l'equation associee a l'inconnue dont on prend
la trace.
const Milieu_base & milieu () const
Renvoie le milieu associe a l'equation qui porte
le champ inconnue dont on prend la trace.
const Zone_dis_base & zone_dis () const
Renvoie la zone discretisee associee a l'equation
qui porte le champ inconnue dont on prend la trace.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions au limites discretisees
portee par l'equation qui porte le champ inconnue
dont on prend la trace.
const Frontiere_dis_base & front_dis () const
Renvoie la frontiere discretisee correspondante
au domaine sur lequel prend la trace.
void set_distant (int d)
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_calc & self_cast (Objet_U &)
static const Champ_front_calc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
Lit le nom d'un probleme, le nom d'un bord et
le nom d'un champ inconnue a partir d'un flot d'entree.
Cree ensuite le champ de frontiere correspondant.
Format:
Champ_front_calc nom_probleme nom_bord nom_champ.
Protected Member Functions inherited from Ch_front_var_instationnaire_dep
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_front_var_instationnaire
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Champ_Inc_base l_inconnue
L'inconnue du probleme oppose.
Nom nom_autre_bord_
Nom nom_autre_pb_
Nom du bord et du probleme oppose.
int distant_
par defaut distant_ vaut 1
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_calc
Classe derivee de Champ_front_var qui represente les
champs a la frontiere obtenus en prenant la trace
d'un objet de type Champ_Inc (champ inconnue d'une equation)
Definition at line 40 of file Champ_front_calc.h.
Constructor & Destructor Documentation
~Champ_front_calc()
Champ_front_calc::~Champ_front_calc ()
Definition at line 26 of file Champ_front_calc.cpp.
Champ_front_calc()
Champ_front_calc::Champ_front_calc ()
Definition at line 28 of file Champ_front_calc.cpp.
{
  set_distant(1);
}
References set_distant().
Member Function Documentation
affecter_()
Champ_front_base & Champ_front_calc::affecter_ (const Champ_front_base & ch) override virtual
Non code.
Returns
Champ_front_base&
Signification:
Contraintes:
Implements Champ_front_base.
Definition at line 207 of file Champ_front_calc.cpp.
{
  return *this;
}
associer_ch_inc_base()
void Champ_front_calc::associer_ch_inc_base (const Champ_Inc_base & inco)
Associe le champ inconnue a l'objet.
Definition at line 187 of file Champ_front_calc.cpp.
{
  l_inconnue = inco;
}
References l_inconnue.
completer()
void Champ_front_calc::completer () override virtual
Reimplemented from Champ_front_base.
Reimplemented in Champ_front_calc_interne.
Definition at line 141 of file Champ_front_calc.cpp.
{
// Check/initialize Raccord boundaries in parallel:
  if (nproc()>1)
    {
      const Zone_dis_base& zone_dis_opposee = front_dis().zone_dis();
      const Zone_dis_base& zone_dis_locale = frontiere_dis().zone_dis();
      const Frontiere& frontiere_opposee = front_dis().frontiere();
      const Frontiere& frontiere_locale = frontiere_dis().frontiere();
      if (distant_ && !sub_type(Raccord_distant_homogene, frontiere_opposee))
        {
          const Nom& nom_domaine_oppose = zone_dis_opposee.zone().domaine().le_nom();
          Cerr << "Error, the boundary " << frontiere_opposee.le_nom() << " should be a Raccord." << finl;
          Cerr << "Add in your data file between the definition and the partition of the domain " << nom_domaine_oppose << " :" << finl;
          Cerr << "Modif_bord_to_raccord " << nom_domaine_oppose << " " << frontiere_opposee.le_nom() << finl;
          exit();
        }
      if (distant_==1)
        {
          Raccord_distant_homogene& raccord_distant = ref_cast_non_const(Raccord_distant_homogene, frontiere_opposee);
          if (!raccord_distant.est_initialise())
            raccord_distant.initialise(frontiere_locale, zone_dis_locale, zone_dis_opposee);
        }
    }
}
References Cerr, distant_, Zone::domaine(), Raccord_distant_homogene::est_initialise(), Process::exit(), finl, front_dis(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Raccord_distant_homogene::initialise(), Domaine::le_nom(), Frontiere::le_nom(), Process::nproc(), ref_cast_non_const, sub_type, Zone_dis_base::zone(), and Frontiere_dis_base::zone_dis().
Referenced by Champ_front_calc_interne::completer().
cree_instance()
Objet_U * Champ_front_calc::cree_instance () static
Definition at line 26 of file Champ_front_calc.cpp.
creer()
void Champ_front_calc::creer (const Nom & nom_pb, const Nom & nom_bord, const Motcle & nom_inco)
Cree l'objet Champ_front_calc representant la trace d'un champ
inconnue sur une frontiere a partir des noms:
- du probleme portant l'inconnue
- du bord concerne (la frontiere)
- de l'inconnue.
Definition at line 110 of file Champ_front_calc.cpp.
{
  nom_autre_pb_ = nom_pb;
  nom_autre_bord_ = nom_bord;
  REF(Probleme_base) autre_pb;
  Objet_U& ob=Interprete::objet(nom_autre_pb_);
  if(sub_type(Probleme_base, ob))
    {
      autre_pb = ref_cast(Probleme_base, ob);
    }
  else
    {
      Cerr << "We did not find problem with name " << nom_pb << finl;
      exit();
    }
  REF(Champ_base) rch;
  rch = autre_pb->get_champ(nom_inco);
  if (sub_type(Champ_Inc_base,rch.valeur()))
    {
      l_inconnue=ref_cast(Champ_Inc_base, rch.valeur()) ;
      fixer_nb_comp(rch.valeur().nb_comp());
    }
  else
    {
      Cerr << autre_pb->le_nom() << " did not have unknown field with name " << nom_inco << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, Field_base::fixer_nb_comp(), l_inconnue, nom_autre_bord_, nom_autre_pb_, Interprete::objet(), REF, ref_cast, and sub_type.
Referenced by Echange_interne_global_impose::completer(), Echange_interne_impose::completer(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), PlaqThVDF::mettre_a_jour(), readOn(), and Echange_contact_VDF::readOn().
duplique()
int Champ_front_calc::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_front_calc_interne.
Definition at line 26 of file Champ_front_calc.cpp.
equation()
const Equation_base & Champ_front_calc::equation () const
Renvoie l'equation associee a l'inconnue dont on prend
la trace.
Returns
Equation_base&
Signification: l'equation associee a l'inconnue dont on prend
la trace
Contraintes: reference constante
Definition at line 294 of file Champ_front_calc.cpp.
{
  if (l_inconnue.non_nul()==0)
    {
      Cerr << "\nError in Champ_front_calc::equation() : not able to return the equation !" << finl;
      Process::exit();
    }
  return inconnue().equation();
}
References Cerr, MorEqn::equation(), Process::exit(), finl, inconnue(), l_inconnue, and O_U_Ptr::non_nul().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Op_Diff_VDF_base::init_op_ext(), Echange_contact_VDF::initialiser(), milieu(), and zone_Cl_dis().
front_dis()
const Frontiere_dis_base & Champ_front_calc::front_dis () const
Renvoie la frontiere discretisee correspondante
au domaine sur lequel prend la trace.
Returns
Frontiere_dis_base&
Signification: frontiere discretisee correspondante
au domaine sur lequel prend la trace
Contraintes: reference constante
Definition at line 385 of file Champ_front_calc.cpp.
{
  return zone_dis().frontiere_dis(nom_autre_bord_);
}
References Zone_dis_base::frontiere_dis(), nom_autre_bord_, and zone_dis().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), completer(), Champ_front_calc_interne::completer(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_VDF::initialiser(), and Echange_contact_VDF::verifier_correspondance().
get_info()
const Type_info * Champ_front_calc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_calc_interne.
Definition at line 26 of file Champ_front_calc.cpp.
inconnue()
const Champ_Inc_base & Champ_front_calc::inconnue () const
Renvoie le champ inconnue associe.
Returns
Champ_Inc_base&
Signification: le champ inconnue associe
Contraintes: reference constante
Definition at line 254 of file Champ_front_calc.cpp.
{
  return l_inconnue.valeur();
}
References l_inconnue, and Ref_Champ_Inc_base::valeur().
Referenced by equation(), and zone_dis().
info()
const Type_info * Champ_front_calc::info () static
Definition at line 26 of file Champ_front_calc.cpp.
initialiser()
int Champ_front_calc::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 167 of file Champ_front_calc.cpp.
{
  Ch_front_var_instationnaire_dep::initialiser(temps, inco);
  return 1;
}
References Ch_front_var_instationnaire_dep::initialiser().
Referenced by Echange_contact_VDF::initialiser().
mettre_a_jour()
void Champ_front_calc::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ
On prend juste la trace du champ inconnue au pas de
temps auquel il se situe.
WEC : verifier qu'on prend l'inconnue au bon temps !
Reimplemented from Champ_front_base.
Reimplemented in Champ_front_calc_interne.
Definition at line 230 of file Champ_front_calc.cpp.
{
  assert (nom_autre_bord_ != "??") ;
  DoubleTab& tab=valeurs_au_temps(temps);
  const Frontiere_dis_base& frontiere_dis_opposee = zone_dis().frontiere_dis(nom_bord_oppose());
  l_inconnue->trace(frontiere_dis_opposee,tab,temps,distant_ /* distant */);
}
References distant_, Zone_dis_base::frontiere_dis(), l_inconnue, nom_autre_bord_, nom_bord_oppose(), Champ_Inc_base::trace(), Champ_front_var_instationnaire::valeurs_au_temps(), and zone_dis().
Referenced by Champ_front_calc_interne::mettre_a_jour().
milieu()
const Milieu_base & Champ_front_calc::milieu () const
Renvoie le milieu associe a l'equation qui porte
le champ inconnue dont on prend la trace.
Returns
Milieu_base&
Signification: le milieu associe a l'equation qui porte
le champ inconnue dont on prend la trace
Contraintes: reference constante
Definition at line 320 of file Champ_front_calc.cpp.
{
  return equation().milieu();
}
References equation(), and Equation_base::milieu().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::initialiser(), and Echange_contact_VDF::mettre_a_jour().
nom_bord_oppose()
const Nom & Champ_front_calc::nom_bord_oppose () const
Renvoie le nom du bord sur lequel on calcule la trace.
Returns
Nom&
Signification: le nom du bord sur lequel on calcule la trace
Contraintes: reference constante
Definition at line 273 of file Champ_front_calc.cpp.
{
  return nom_autre_bord_;
}
References nom_autre_bord_.
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), and mettre_a_jour().
printOn()
Sortie & Champ_front_calc::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_calc_interne.
Definition at line 48 of file Champ_front_calc.cpp.
{
  return os;
}
readOn()
Entree & Champ_front_calc::readOn (Entree & is) override protected virtual
Lit le nom d'un probleme, le nom d'un bord et
le nom d'un champ inconnue a partir d'un flot d'entree.
Cree ensuite le champ de frontiere correspondant.
Format:
Champ_front_calc nom_probleme nom_bord nom_champ.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_calc_interne.
Definition at line 71 of file Champ_front_calc.cpp.
{
  Motcle nom_inco;
  is >> nom_autre_pb_ >> nom_autre_bord_ >> nom_inco;
  creer(nom_autre_pb_, nom_autre_bord_, nom_inco);
  return is;
}
References creer(), nom_autre_bord_, and nom_autre_pb_.
Referenced by Champ_front_calc_interne::readOn().
self_cast() [1/2]
const Champ_front_calc & Champ_front_calc::self_cast (const Objet_U & r) static
Definition at line 26 of file Champ_front_calc.cpp.
self_cast() [2/2]
Champ_front_calc & Champ_front_calc::self_cast (Objet_U & r) static
Definition at line 26 of file Champ_front_calc.cpp.
set_distant()
void Champ_front_calc::set_distant (int d) inline
Definition at line 63 of file Champ_front_calc.h.
  {
    distant_=d ;
  };
References distant_.
Referenced by Champ_front_calc(), and Champ_front_calc_interne::Champ_front_calc_interne().
taille_memoire()
unsigned Champ_front_calc::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_front_calc_interne.
Definition at line 26 of file Champ_front_calc.cpp.
verifier()
void Champ_front_calc::verifier (const Cond_lim_base & la_cl) const override virtual
Reimplemented from Champ_front_base.
Definition at line 391 of file Champ_front_calc.cpp.
{
}
zone_Cl_dis()
const Zone_Cl_dis_base & Champ_front_calc::zone_Cl_dis () const
Renvoie la zone des conditions au limites discretisees
portee par l'equation qui porte le champ inconnue
dont on prend la trace.
Returns
Zone_Cl_dis_base&
Signification: la zone des conditions au limites discretisees
portee par l'equation qui porte le champ inconnue
dont on prend la trace
Contraintes: reference constante
Definition at line 364 of file Champ_front_calc.cpp.
{
  return equation().zone_Cl_dis().valeur();
}
References equation(), Deriv_Zone_Cl_dis_base::valeur(), and Equation_base::zone_Cl_dis().
zone_dis()
const Zone_dis_base & Champ_front_calc::zone_dis () const
Renvoie la zone discretisee associee a l'equation
qui porte le champ inconnue dont on prend la trace.
Returns
Zone_dis_base&
Signification: la zone discretisee associee a l'equation
qui porte le champ inconnue dont on prend la trace
Contraintes: reference constante
Definition at line 341 of file Champ_front_calc.cpp.
{
  return inconnue().zone_dis_base();
}
References inconnue(), and Champ_base::zone_dis_base().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), front_dis(), Echange_contact_VDF::initialiser(), mettre_a_jour(), and Echange_contact_VDF::verifier_correspondance().
Member Data Documentation
distant_
int Champ_front_calc::distant_ protected
par defaut distant_ vaut 1
Definition at line 70 of file Champ_front_calc.h.
Referenced by completer(), mettre_a_jour(), and set_distant().
info_obj
const Type_info Champ_front_calc::info_obj static
Definition at line 43 of file Champ_front_calc.h.
l_inconnue
Ref_Champ_Inc_base Champ_front_calc::l_inconnue protected
L'inconnue du probleme oppose.
Definition at line 68 of file Champ_front_calc.h.
Referenced by associer_ch_inc_base(), creer(), equation(), inconnue(), and mettre_a_jour().
nom_autre_bord_
Nom Champ_front_calc::nom_autre_bord_ protected
Definition at line 69 of file Champ_front_calc.h.
Referenced by creer(), front_dis(), mettre_a_jour(), nom_bord_oppose(), and readOn().
nom_autre_pb_
Nom Champ_front_calc::nom_autre_pb_ protected
Nom du bord et du probleme oppose.
Definition at line 69 of file Champ_front_calc.h.
Referenced by creer(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_calc.h
src/Kernel/Champs/Champ_front_calc.cpp