TRUST: Aretes Class Reference
Aretes Class Reference
#include <Aretes.h>
Public Member Functions
Aretes ()
~Aretes ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Aretes (int n)
void affecter (int &, int, int, int, int, int, int, int, const ArrOfInt &)
IntTab & faces ()
Aretes_H.
void dimensionner (int)
void trier (int &, int &, int &, int &)
void trier_pour_debog (int &, int &, int &, int &, const DoubleTab &)
void calculer_centre_de_gravite (Zone_VDF &zone)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Aretes & self_cast (Objet_U &)
static const Aretes & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void swap (int, int)
Private Attributes
IntTab faces_
IntVect type1_
IntVect type2_
Detailed Description
Definition at line 29 of file Aretes.h.
Constructor & Destructor Documentation
Aretes() [1/2]
Aretes::Aretes ()
Definition at line 19 of file Aretes.cpp.
~Aretes()
Aretes::~Aretes ()
Definition at line 19 of file Aretes.cpp.
Aretes() [2/2]
Aretes::Aretes (int n) inline
Definition at line 51 of file Aretes.h.
                           : faces_(n,4),type1_(n),type2_(n)
{
}
Member Function Documentation
affecter()
void Aretes::affecter (int & numero_a, int dir, int type, int nb_face, int f1, int f2, int f3, int f4, const ArrOfInt & est_une_plaque)
Definition at line 51 of file Aretes.cpp.
{
  int nb_plaques = 0;
  nb_plaques += f1>=0 ? est_une_plaque[f1] : 0;
  nb_plaques += f2>=0 ? est_une_plaque[f2] : 0;
  nb_plaques += f3>=0 ? est_une_plaque[f3] : 0;
  nb_plaques += f4>=0 ? est_une_plaque[f4] : 0;
  int coin = -1 ;
  int bord = 0 ;
  if (type>0)
    {
      if (nb_plaques!=0) return;
      if( (f1<nb_face) || (f2<nb_face) || (f3<nb_face) || (f4<nb_face) )
        numero_a++;
      else
        return;
    }
  if (type==bord)
    {
      if( (f1<nb_face) || (f2<nb_face) || (f3<nb_face) )
        numero_a++;
      else
        return;
    }
  if (type==coin)
    {
      if( (f1<nb_face) && (f2<nb_face) && (f3<nb_face) && (f4<nb_face) )
        numero_a++;
      else
        return;
    }
  faces_(numero_a, 0)=f1;
  faces_(numero_a, 1)=f2;
  faces_(numero_a, 2)=f3;
  faces_(numero_a, 3)=f4;
  type1_(numero_a)=dir;
  type2_(numero_a)=type;
  if(type >0)
    {
      assert(faces_(numero_a, 0) !=-1);
      assert(faces_(numero_a, 1) !=-1);
      assert(faces_(numero_a, 2) !=-1);
      assert(faces_(numero_a, 3) !=-1);
    }
}
References f1, f2, faces_, type1_, and type2_.
Referenced by Zone_VDF::genere_aretes().
calculer_centre_de_gravite()
void Aretes::calculer_centre_de_gravite (Zone_VDF & zone)
< arete interne ou mixte
< arete bord ou coin
< arete interne ou mixte
< arete bord ou coin
Definition at line 100 of file Aretes.cpp.
{
  const IntTab& so = zone.face_sommets();
  const DoubleTab& co = zone.zone().domaine().les_sommets();
  DoubleTab& xa_ = zone.xa();
  int i,j,k;
  int f0=-1,f1=-1,s00,s01,s10,s11;
  int type;
  int nb_aretes = faces_.dimension(0);
// const IntVect& orient =  zone.orientation();
// Calcul des ccordonnees de l'arete
  if(dimension==2)
    {
      xa_.resize(nb_aretes,2);
      for(i=0; i<nb_aretes; i++)
        {
          type = type2_(i);
          if((type==2)||(type==1)) //!< arete interne ou mixte
            {
              f0 = faces_(i,0);
              s00 = so(f0,0);
              s01 = so(f0,1);
              f1 = faces_(i,1);
              s10 = so(f1,0);
              s11 = so(f1,1);
              if((s00==s10)||(s00==s11))
                {
                  xa_(i,0) = co(s00,0);
                  xa_(i,1) = co(s00,1);
                }
              else if((s01==s10)||(s01==s11))
                {
                  xa_(i,0) = co(s01,0);
                  xa_(i,1) = co(s01,1);
                }
              else
                {
                  Cerr<<"Erreur on a pas trouve de sommets communs"<<finl;
                  exit();
                }
            }
          else if((type == 0)||(type == -1)) //!< arete bord ou coin
            {
              for(j=0; j<4; j++)
                {
                  f0=faces_(i,j);
                  if(f0!=-1) break;
                }
              assert(j<4);
              k=j+1;
              s00 = so(f0,0);
              s01 = so(f0,1);
              for(j=k; j<4; j++)
                {
                  f1=faces_(i,j);
                  if(f1!=-1) break;
                }
              assert(j<4);
              s10 = so(f1,0);
              s11 = so(f1,1);
              if((s00==s10)||(s00==s11))
                {
                  xa_(i,0) = co(s00,0);
                  xa_(i,1) = co(s00,1);
                }
              else if((s01==s10)||(s01==s11))
                {
                  xa_(i,0) = co(s01,0);
                  xa_(i,1) = co(s01,1);
                }
              else
                {
                  Cerr<<"Erreur on a pas trouve de sommets communs"<<finl;
                  exit();
                }
            }
        }
    }
  else if(dimension==3)
    {
      xa_.resize(nb_aretes,3);
      for(i=0; i<nb_aretes; i++)
        {
          type = type2_(i);
          if((type==2)||(type==1)) //!< arete interne ou mixte
            {
              f0 = faces_(i,0);
              f1 = faces_(i,1);
              int s0,s1,s0j;
              int deux;
              for(j=0; j<4; j++)
                {
                  s0j=so(f0,j);
                  for(k=0; k<4; k++)
                    if(s0j==so(f1,k)) break;
                  if(k<4) break;
                }
              assert(j<4);
              s0 = s0j;
              deux = j+1;
              for(j=deux; j<4; j++)
                {
                  s0j=so(f0,j);
                  for(k=0; k<4; k++)
                    if(s0j==so(f1,k)) break;
                  if(k<4) break;
                }
              assert(j<4);
              s1 = s0j;
              xa_(i,0) = (co(s0,0)+co(s1,0))/2.0;
              xa_(i,1) = (co(s0,1)+co(s1,1))/2.0;
              xa_(i,2) = (co(s0,2)+co(s1,2))/2.0;
            }
          else if((type == 0)||(type == -1)) //!< arete bord ou coin
            {
              int f,fdeux;
              int s0,s1,s0j;
              int deux;
              for(f=0; f<4; f++)
                {
                  f0=faces_(i,f);
                  if(f0!=-1) break;
                }
              assert(f<4);
              fdeux=f+1;
              for(f=fdeux; f<4; f++)
                {
                  f1=faces_(i,f);
                  if(f1!=-1) break;
                }
              for(j=0; j<4; j++)
                {
                  s0j=so(f0,j);
                  for(k=0; k<4; k++)
                    if(s0j==so(f1,k)) break;
                  if(k<4) break;
                }
              assert(j<4);
              s0 = s0j;
              deux = j+1;
              for(j=deux; j<4; j++)
                {
                  s0j=so(f0,j);
                  for(k=0; k<4; k++)
                    if(s0j==so(f1,k)) break;
                  if(k<4) break;
                }
              assert(j<4);
              s1 = s0j;
              xa_(i,0) = (co(s0,0)+co(s1,0))/2.0;
              xa_(i,1) = (co(s0,1)+co(s1,1))/2.0;
              xa_(i,2) = (co(s0,2)+co(s1,2))/2.0;
            }
        }
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Process::exit(), f1, Zone_VF::face_sommets(), faces_, finl, Domaine::les_sommets(), TRUSTTab< _TYPE_ >::resize(), type2_, Zone_VF::xa(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Aretes::cree_instance () static
Definition at line 19 of file Aretes.cpp.
dimensionner()
void Aretes::dimensionner (int n)
Definition at line 259 of file Aretes.cpp.
{
  faces_.resize(n,4);
  type1_.resize(n);
  type2_.resize(n) ;
}
References faces_, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), type1_, and type2_.
Referenced by Zone_VDF::genere_aretes().
duplique()
int Aretes::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Aretes.cpp.
faces()
IntTab & Aretes::faces () inline
Aretes_H.
Definition at line 62 of file Aretes.h.
References faces_.
Referenced by Zone_VDF::genere_aretes().
get_info()
const Type_info * Aretes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 19 of file Aretes.cpp.
info()
const Type_info * Aretes::info () static
Definition at line 19 of file Aretes.cpp.
printOn()
Sortie & Aretes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Aretes.cpp.
{
  s << "Aretes " << finl;
  s << faces_ << finl;
  s << type1_ << finl;
  s << type2_ << finl;
  return s;
}
References faces_, finl, type1_, and type2_.
readOn()
Entree & Aretes::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Aretes.cpp.
{
  return s ;
}
self_cast() [1/2]
const Aretes & Aretes::self_cast (const Objet_U & r) static
Definition at line 19 of file Aretes.cpp.
self_cast() [2/2]
Aretes & Aretes::self_cast (Objet_U & r) static
Definition at line 19 of file Aretes.cpp.
swap()
void Aretes::swap (int a1, int a2) private
Definition at line 269 of file Aretes.cpp.
{
  int tmp;
  tmp = faces_(a1, 0);
  faces_(a1, 0) = faces_(a2, 0);
  faces_(a2, 0)=tmp;
  tmp = faces_(a1, 1);
  faces_(a1, 1) = faces_(a2, 1);
  faces_(a2, 1)=tmp;
  tmp = faces_(a1, 2);
  faces_(a1, 2) = faces_(a2, 2);
  faces_(a2, 2)=tmp;
  tmp = faces_(a1, 3);
  faces_(a1, 3) = faces_(a2, 3);
  faces_(a2, 3)=tmp;
  tmp = type1_(a1);
  type1_(a1)=type1_(a2);
  type1_(a2)=tmp;
  tmp = type2_(a1);
  type2_(a1)=type2_(a2);
  type2_(a2)=tmp;
}
References faces_, type1_, and type2_.
Referenced by trier(), and trier_pour_debog().
taille_memoire()
unsigned Aretes::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Aretes.cpp.
trier()
void Aretes::trier (int & nb_aretes_coin, int & nb_aretes_bord, int & nb_aretes_mixte, int & nb_aretes_interne)
Definition at line 297 of file Aretes.cpp.
{
//
  nb_aretes_coin=nb_aretes_bord=nb_aretes_mixte=nb_aretes_interne=0;
  int coin = -1 ;
  int bord = 0 ;
  int mixte = 1 ;
  int interne = 2 ;
  int nb_aretes = type1_.size();
  int courante=0;
  int arete;
  while( (courante<nb_aretes)&&(type2_(courante)==coin) )
    {
      courante++;
      nb_aretes_coin++;
    }
  for(arete=courante; arete<nb_aretes; arete++)
    {
      if(type2_(arete)==coin)
        {
          swap(arete, courante);
          while( (courante<nb_aretes)&&(type2_(courante)==coin) )
            {
              courante++;
              nb_aretes_coin++;
            }
// arete=courante;
        }
    }
  while( (courante<nb_aretes)&&(type2_(courante)==bord) )
    {
      courante++;
      nb_aretes_bord++;
    }
  for(arete=courante; arete<nb_aretes; arete++)
    {
      if(type2_(arete)==bord)
        {
          swap(arete, courante);
          assert(type2_(courante) == bord);
          while( (courante<nb_aretes)&&(type2_(courante)==bord) )
            {
              courante++;
              nb_aretes_bord++;
            }
// arete=courante;
        }
    }
  while( (courante<nb_aretes)&&(type2_(courante)==mixte) )
    {
      courante++;
      nb_aretes_mixte++;
    }
  for(arete=courante; arete<nb_aretes; arete++)
    {
      if(type2_(arete)==mixte)
        {
          swap(arete, courante);
          assert(faces_(courante, 0) !=-1);
          assert(faces_(courante, 1) !=-1);
          assert(faces_(courante, 2) !=-1);
          assert(faces_(courante, 3) !=-1);
          while( (courante<nb_aretes)&&(type2_(courante)==mixte) )
            {
              courante++;
              nb_aretes_mixte++;
            }
// arete=courante;
        }
    }
  while( (courante<nb_aretes)&&(type2_(courante)==interne) )
    {
      courante++;
      nb_aretes_interne++;
    }
  for(arete=courante; arete<nb_aretes; arete++)
    {
      if(type2_(arete)==interne)
        {
          swap(arete, courante);
          assert(faces_(courante, 0) !=-1);
          assert(faces_(courante, 1) !=-1);
          assert(faces_(courante, 2) !=-1);
          assert(faces_(courante, 3) !=-1);
          while( (courante<nb_aretes)&&(type2_(courante)==interne) )
            {
              courante++;
              nb_aretes_interne++;
            }
// arete=courante;
        }
    }
}
References faces_, TRUSTVect< _TYPE_ >::size(), swap(), type1_, and type2_.
Referenced by Zone_VDF::genere_aretes().
trier_pour_debog()
void Aretes::trier_pour_debog (int & nb_aretes_coin, int & nb_aretes_bord, int & nb_aretes_mixte, int & nb_aretes_interne, const DoubleTab & xv)
Definition at line 392 of file Aretes.cpp.
{
  ArrOfDouble XVref(dimension),XVref2(dimension);
  int nb_aretes = type1_.size();
  int arete;
  for (int boucle=0; boucle<3; boucle++)
    {
      int deb=nb_aretes - nb_aretes_interne;
      int fin=nb_aretes;
      if (boucle==1)
        {
          fin=deb;
          deb-=nb_aretes_mixte;
        }
      else if (boucle==2)
        {
          fin=deb;
          deb-=  nb_aretes_bord;
        }
      for ( arete=deb; arete<fin; arete++)
        {
          if ((boucle==2)&&(type2_(arete)!=0))
            {
              Cerr<<"gros pb "<<arete<<finl;
              exit();
            }
          int ref=faces_(arete,0);
          for (int i=0; i<dimension; i++) XVref[i]=xv(ref,i);
          int marq=-1;
          int ref2;
          for (int arete2=arete; arete2<fin; arete2++)
            {
              ref2=faces_(arete2,0);
              for (int i=0; i<dimension; i++) XVref2[i]=xv(ref2,i);
              int test=-1;
// int testsa=-1;
              if (dimension==2)
                {
                  if (sup_strict(XVref2[1],XVref[1])) test=1;
                  else if ((XVref2[1]==XVref[1])&&(sup_strict(XVref2[0],XVref[0]))) test=0;
                }
              else if (dimension==3)
                {
                  if (XVref2[2]>XVref[2]) test=2;
                  else if  (XVref2[2]==XVref[2])
                    {
                      if (XVref2[1]>XVref[1]) test=1;
                      else if ((XVref2[1]==XVref[1])&&(XVref2[0]>XVref[0])) test=0;
                    }
                }
              if (test!=-1)
                {
                  marq=arete2;
                  XVref=XVref2;
                }
            }
          if (marq!=-1) swap(arete,marq);
        }
    }
  for (arete=nb_aretes - nb_aretes_interne; arete<nb_aretes*0; arete++)
    {
      Cerr <<me()<<" arete "<<arete<<" "<< faces_(arete,0)<<" "<< faces_(arete,1)<<" "<< faces_(arete,2)<<" "<< faces_(arete,3)<<finl;
    }
}
References Cerr, Objet_U::dimension, Process::exit(), faces_, finl, Process::me(), TRUSTVect< _TYPE_ >::size(), sup_strict(), swap(), test(), type1_, and type2_.
Referenced by Zone_VDF::genere_aretes().
Member Data Documentation
faces_
IntTab Aretes::faces_ private
Definition at line 43 of file Aretes.h.
Referenced by affecter(), calculer_centre_de_gravite(), dimensionner(), faces(), printOn(), swap(), trier(), and trier_pour_debog().
info_obj
const Type_info Aretes::info_obj static
Definition at line 31 of file Aretes.h.
type1_
IntVect Aretes::type1_ private
Definition at line 44 of file Aretes.h.
Referenced by affecter(), dimensionner(), printOn(), swap(), trier(), and trier_pour_debog().
type2_
IntVect Aretes::type2_ private
Definition at line 44 of file Aretes.h.
Referenced by affecter(), calculer_centre_de_gravite(), dimensionner(), printOn(), swap(), trier(), and trier_pour_debog().
The documentation for this class was generated from the following files:
src/VDF/Elements/Aretes.h
src/VDF/Elements/Aretes.cpp