TRUST: Taux_cisaillement_P0_VDF Class Reference
Taux_cisaillement_P0_VDF Class Reference
classe Taux_cisaillement_P0_VDF
#include <Taux_cisaillement_P0_VDF.h>
Public Member Functions
Taux_cisaillement_P0_VDF ()
~Taux_cisaillement_P0_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face &, const Zone_Cl_dis_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Taux_cisaillement_P0_VDF & self_cast (Objet_U &)
static const
Taux_cisaillement_P0_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Private Attributes
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Ref_Champ_Face vitesse_
Detailed Description
classe Taux_cisaillement_P0_VDF
Definition at line 34 of file Taux_cisaillement_P0_VDF.h.
Constructor & Destructor Documentation
Taux_cisaillement_P0_VDF::Taux_cisaillement_P0_VDF ()
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
Taux_cisaillement_P0_VDF::~Taux_cisaillement_P0_VDF ()
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
Member Function Documentation
void Taux_cisaillement_P0_VDF::associer_champ (const Champ_Face & la_vitesse, const Zone_Cl_dis_base & la_zone_Cl_dis_base)
Definition at line 47 of file Taux_cisaillement_P0_VDF.cpp.
References la_zone_Cl_VDF, ref_cast, and vitesse_.
Referenced by VDF_discretisation::taux_cisaillement().
{
  la_zone_Cl_VDF  = ref_cast(Zone_Cl_VDF, la_zone_Cl_dis_base);
  vitesse_= la_vitesse;
}
Objet_U * Taux_cisaillement_P0_VDF::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
int Taux_cisaillement_P0_VDF::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
const Type_info * Taux_cisaillement_P0_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
const Type_info * Taux_cisaillement_P0_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
void Taux_cisaillement_P0_VDF::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
< Shear rate
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 53 of file Taux_cisaillement_P0_VDF.cpp.
References Champ_base::changer_temps(), la_zone_Cl_VDF, Champ_Fonc_P0_VDF::la_zone_VDF, Ref_Zone_Cl_VDF::valeur(), Ref_Champ_Face::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and vitesse_.
{
  int nb_elem = la_zone_VDF->nb_elem();
  DoubleVect tmp(nb_elem);
  vitesse_->calcul_S_barre(vitesse_.valeur().valeurs(),tmp,la_zone_Cl_VDF.valeur());
  DoubleTab& S = valeurs(); //!< Shear rate
  for (int i=0; i<nb_elem; i++)
    S(i) = sqrt(tmp(i));
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
Sortie & Taux_cisaillement_P0_VDF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 34 of file Taux_cisaillement_P0_VDF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Taux_cisaillement_P0_VDF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 42 of file Taux_cisaillement_P0_VDF.cpp.
{
  return s ;
}
Taux_cisaillement_P0_VDF & Taux_cisaillement_P0_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
const Taux_cisaillement_P0_VDF & Taux_cisaillement_P0_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
unsigned Taux_cisaillement_P0_VDF::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 28 of file Taux_cisaillement_P0_VDF.cpp.
Member Data Documentation
const Type_info Taux_cisaillement_P0_VDF::info_obj [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 38 of file Taux_cisaillement_P0_VDF.h.
Ref_Zone_Cl_VDF Taux_cisaillement_P0_VDF::la_zone_Cl_VDF [private]
Definition at line 47 of file Taux_cisaillement_P0_VDF.h.
Referenced by associer_champ(), and mettre_a_jour().
Ref_Champ_Face Taux_cisaillement_P0_VDF::vitesse_ [private]
Definition at line 48 of file Taux_cisaillement_P0_VDF.h.
Referenced by associer_champ(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VDF/Champs/Taux_cisaillement_P0_VDF.h
src/VDF/Champs/Taux_cisaillement_P0_VDF.cpp