TRUST: Debog Class Reference
Debog Class Reference
#include <Debog.h>
Static Public Member Functions
static int active ()
renvoie 1 si on est en mode Debog, 0 sinon
static void verifier (const char *const msg, double)
static void verifier (const char *const msg, int)
static void verifier (const char *const msg, const DoubleVect &)
static void verifier (const char *const msg, const IntVect &)
static void verifier_bord (const char *const msg, const DoubleVect &arr, int num_deb)
static void verifier (const char *const msg, const Champ_Inc &)
static void verifier (const char *const msg, const Champ_Inc_base &)
static void verifier_indices_items (const char *const msg, const MD_Vector &, const IntVect &)
teste le contenu du vecteur v en supposant qu'il contient des
indices d'items associes au descripteur md. Exemple: face_keps_imposee_
Les valeurs negatives doivent etre identiques a la reference,
les valeurs positives ou nulles sont interpretees comme un indice et
doivent etre egale a l'indice de reference apres renumerotation.
static void set_nom_pb_actuel (const Nom &nom)
static void verifier_getref (const char *const msg, double val, double &refval)
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable.
static void verifier_getref (const char *const msg, int val, int &refval)
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable.
static void verifier_getref (const char *const msg, const DoubleVect &val, DoubleVect &refval)
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable. x and ref can point to the same object.
static void verifier_getref (const char *const msg, const IntVect &val, IntVect &refval)
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable. x and ref can point to the same object.
static void verifier_Mat_elems (const char *const msg, const Matrice_Base &la_matrice)
static void verifier_matrice (const char *const msg, const Matrice_Base &, const MD_Vector &md_lignes, const MD_Vector &md_colonnes)
Detailed Description
Definition at line 27 of file Debog.h.
Member Function Documentation
active()
int Debog::active () static
renvoie 1 si on est en mode Debog, 0 sinon
Definition at line 66 of file Debog.cpp.
{
  return Debog_Pb::get_debog_instance().non_nul();
}
References Debog_Pb::get_debog_instance(), and O_U_Ptr::non_nul().
Referenced by Zone_VEF_PreP1b::construire_renum_arete_perio(), and Zone_VEF_PreP1b::modifier_pour_Cl().
set_nom_pb_actuel()
void Debog::set_nom_pb_actuel (const Nom & nom) static
Definition at line 49 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->set_nom_pb_actuel(nom);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::set_nom_pb_actuel().
Referenced by Probleme_base::calculer_pas_de_temps(), Probleme_base::computeTimeStep(), Probleme_base::finir(), Probleme_base::initialize(), Probleme_base::initTimeStep(), Probleme_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Probleme_base::postraiter(), Probleme_base::presentTime(), Probleme_base::reprendre(), Probleme_base::sauvegarder(), Probleme_base::sauver(), Probleme_base::solveTimeStep(), Probleme_base::terminate(), Probleme_base::updateGivenFields(), and Probleme_base::validateTimeStep().
verifier() [1/6]
void Debog::verifier (const char *const msg, const Champ_Inc & x) static
Definition at line 37 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x->valeurs());
}
References Debog_Pb::get_debog_instance(), Champ_Inc::valeurs(), and Debog_Pb::verifier().
verifier() [2/6]
void Debog::verifier (const char *const msg, const Champ_Inc_base & x) static
Definition at line 43 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x.valeurs());
}
References Debog_Pb::get_debog_instance(), Champ_Inc_base::valeurs(), and Debog_Pb::verifier().
verifier() [3/6]
void Debog::verifier (const char *const msg, const DoubleVect & x) static
Definition at line 87 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier() [4/6]
void Debog::verifier (const char *const msg, const IntVect & x) static
Definition at line 101 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier() [5/6]
void Debog::verifier (const char *const msg, double x) static
Definition at line 20 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Grad_EF::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_EF::ajouter_sous_cond_template(), Solveur_Masse_base::appliquer(), Solveur_Masse_EF::appliquer_impl(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Q1NC::cal_rot_ordre1(), Op_Dift_standard_VEF_Face::calcul_divergence(), Loi_Etat_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_Cp(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_masse_molaire(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Equation_base::calculer_pas_de_temps(), EOS_Tools_VDF::calculer_rho_face_np1(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Equation_base::completer(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), exemple_champ_non_homogene(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Champ_P1iP1B_implementation::filtrage(), Champ_P1NC_implementation::filtrer_L2(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Piso::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Navier_Stokes_std::mettre_a_jour(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_EF::modifier_solution(), Assembleur_P_PolyMAC::modifier_solution(), Equation_base::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), EOS_Tools_VDF::secmembre_divU_Z(), EOS_Tools_VEF::secmembre_divU_Z(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), and verifier().
verifier() [6/6]
void Debog::verifier (const char *const msg, int x) static
Definition at line 26 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier_bord()
void Debog::verifier_bord (const char *const msg, const DoubleVect & arr, int num_deb) static
Definition at line 32 of file Debog.cpp.
{
// Ne fait rien
}
Referenced by Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour().
verifier_getref() [1/4]
void Debog::verifier_getref (const char *const msg, const DoubleVect & val, DoubleVect & refval) static
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable. x and ref can point to the same object.
Definition at line 95 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x, &ref);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier_getref() [2/4]
void Debog::verifier_getref (const char *const msg, const IntVect & val, IntVect & refval) static
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable. x and ref can point to the same object.
Definition at line 109 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x, &ref);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier_getref() [3/4]
void Debog::verifier_getref (const char *const msg, double val, double & refval) static
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable.
Definition at line 73 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x, &ref);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
Referenced by Zone_VEF_PreP1b::modifier_pour_Cl().
verifier_getref() [4/4]
void Debog::verifier_getref (const char *const msg, int val, int & refval) static
like verifier(), but, in "read\&compare" mode, put the reference
value found in the file in the ref variable.
Definition at line 81 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier(msg, x, &ref);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier().
verifier_indices_items()
void Debog::verifier_indices_items (const char *const msg, const MD_Vector & md, const IntVect & v) static
teste le contenu du vecteur v en supposant qu'il contient des
indices d'items associes au descripteur md. Exemple: face_keps_imposee_
Les valeurs negatives doivent etre identiques a la reference,
les valeurs positives ou nulles sont interpretees comme un indice et
doivent etre egale a l'indice de reference apres renumerotation.
Definition at line 60 of file Debog.cpp.
{
// pas code
}
Referenced by Zone_VEF_PreP1b::construire_renum_arete_perio(), and Zone_VEF_PreP1b::modifier_pour_Cl().
verifier_Mat_elems()
void Debog::verifier_Mat_elems (const char *const msg, const Matrice_Base & la_matrice) static
Definition at line 115 of file Debog.cpp.
{
  if (Debog_Pb::get_debog_instance().non_nul())
    Debog_Pb::get_debog_instance()->verifier_Mat_elems(msg, la_matrice);
}
References Debog_Pb::get_debog_instance(), and Debog_Pb::verifier_Mat_elems().
verifier_matrice()
static void Debog::verifier_matrice (const char *const msg, const Matrice_Base & , const MD_Vector & md_lignes, const MD_Vector & md_colonnes) static
The documentation for this class was generated from the following files:
src/Kernel/Framework/Debog.h
src/Kernel/Framework/Debog.cpp