TRUST: Aire_interfaciale Class Reference
Aire_interfaciale Class Reference
classe Aire_interfaciale
Equation de transport de l'aire interfaciale
#include <Aire_interfaciale.h>
Public Member Functions
~Aire_interfaciale ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Aire_interfaciale ()
void associer_fluide (const Fluide_base &)
const Champ_Inc & inconnue () const override
Champ_Inc & inconnue () override
void discretiser () override
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
const Milieu_base & milieu () const override
Milieu_base & milieu () override
void associer_milieu_base (const Milieu_base &) override
int impr (Sortie &os) const override
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
void mettre_a_jour (double temps) override
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
int positive_unkown () override
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
const Motcle & domaine_application () const override
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Aire_interfaciale & self_cast (Objet_U &)
static const Aire_interfaciale & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Inc l_inco_ch
Champ_Fonc diametre_bulles
Ref_Fluide_base le_fluide
int n_l =-1
Number of the liquid phase (the one where no IA is stored)
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Aire_interfaciale
Equation de transport de l'aire interfaciale
Definition at line 31 of file Aire_interfaciale.h.
Constructor & Destructor Documentation
~Aire_interfaciale()
Aire_interfaciale::~Aire_interfaciale ()
Definition at line 41 of file Aire_interfaciale.cpp.
Aire_interfaciale()
Aire_interfaciale::Aire_interfaciale ()
Definition at line 41 of file Aire_interfaciale.cpp.
Member Function Documentation
associer_fluide()
void Aire_interfaciale::associer_fluide (const Fluide_base & un_fluide)
Definition at line 125 of file Aire_interfaciale.cpp.
{
  le_fluide = un_fluide;
}
References le_fluide.
Referenced by associer_milieu_base().
associer_milieu_base()
void Aire_interfaciale::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
Definition at line 69 of file Aire_interfaciale.cpp.
{
  const Fluide_base& un_fluide = ref_cast(Fluide_base,un_milieu);
  associer_fluide(un_fluide);
}
References associer_fluide(), and ref_cast.
cree_instance()
Objet_U * Aire_interfaciale::cree_instance () static
Definition at line 41 of file Aire_interfaciale.cpp.
discretiser()
void Aire_interfaciale::discretiser () override virtual
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
Reimplemented from Equation_base.
Definition at line 75 of file Aire_interfaciale.cpp.
{
  int nb_valeurs_temp = schema_temps().nb_valeurs_temporelles();
  double temps = schema_temps().temps_courant();
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  int N = ref_cast(Pb_Multiphase, probleme()).nb_phases();
  Cerr << "Interfacial area discretization" << finl;
// On utilise temperature pour la directive car discretisation identique
  dis.discretiser_champ("temperature",zone_dis(),"interfacial_area","m-1", N,nb_valeurs_temp,temps,l_inco_ch);//une aire interfaciale par phase
  l_inco_ch.valeur().fixer_nature_du_champ(multi_scalaire);
  l_inco_ch.valeur().fixer_nom_compo(0, Nom("tau"));
  champs_compris_.ajoute_champ(l_inco_ch);
  Cerr << "Bubble diameter discretization" << finl;
// On utilise temperature pour la directive car discretisation identique
  Noms noms(N), unites(N);
  noms[0] = "diametre_bulles";
  unites[0] = "m";
  Motcle typeChamp = "champ_elem" ;
  const Zone_dis& z = ref_cast(Zone_dis, probleme().domaine_dis().zone_dis(0));
  dis.discretiser_champ(typeChamp, z.valeur(), multi_scalaire, noms , unites, N, 0, diametre_bulles);
  champs_compris_.ajoute_champ(diametre_bulles);
  Equation_base::discretiser();
  Cerr << "Echelle_temporelle_turbulente::discretiser() ok" << finl;
}
References Champs_compris::ajoute_champ(), Cerr, Equation_base::champs_compris_, diametre_bulles, Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), l_inco_ch, multi_scalaire, Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::probleme(), ref_cast, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Equation_base::zone_dis().
domaine_application()
const Motcle & Aire_interfaciale::domaine_application () const override virtual
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
Returns
Motcle&
Signification: le nom du domaine d'aplication
Contraintes: reference constante
Reimplemented from Equation_base.
Definition at line 119 of file Aire_interfaciale.cpp.
{
  static Motcle mot("Interfacial_area");
  return mot;
}
duplique()
int Aire_interfaciale::duplique () const override virtual
Implements Objet_U.
Definition at line 41 of file Aire_interfaciale.cpp.
get_info()
const Type_info * Aire_interfaciale::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 41 of file Aire_interfaciale.cpp.
impr()
int Aire_interfaciale::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 114 of file Aire_interfaciale.cpp.
{
  return Equation_base::impr(os);
}
References Equation_base::impr().
inconnue() [1/2]
const Champ_Inc & Aire_interfaciale::inconnue () const inline override virtual
Implements Convection_Diffusion_std.
Definition at line 70 of file Aire_interfaciale.h.
{
  return l_inco_ch;
}
References l_inco_ch.
Referenced by mettre_a_jour().
inconnue() [2/2]
Champ_Inc & Aire_interfaciale::inconnue () inline override virtual
Implements Convection_Diffusion_std.
Definition at line 75 of file Aire_interfaciale.h.
{
  return l_inco_ch;
}
References l_inco_ch.
info()
const Type_info * Aire_interfaciale::info () static
Definition at line 41 of file Aire_interfaciale.cpp.
mettre_a_jour()
void Aire_interfaciale::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
Reimplemented from Equation_base.
Definition at line 142 of file Aire_interfaciale.cpp.
{
  Convection_Diffusion_std::mettre_a_jour(temps);
  int i, n, N = ref_cast(Pb_Multiphase, probleme()).nb_phases();
  const DoubleTab& alpha = probleme().get_champ("alpha").passe(), &a_i = inconnue().passe();
  DoubleTab& d_b = diametre_bulles.valeurs();
  diametre_bulles.mettre_a_jour(temps);
  for (n = 0; n < N; n++)
    for (i = 0; i < d_b.dimension_tot(0); i++)
      if (n != n_l)
        d_b(i, n) = std::max(1.e-8, ((a_i(i, n)>1.e-6) ? 6 * alpha(i, n)/a_i(i, n) : 0));
  for (i = 0; i < d_b.dimension_tot(0); i++) d_b(i, n_l) = 0;
}
References diametre_bulles, TRUSTTab< _TYPE_ >::dimension_tot(), Probleme_base::get_champ(), inconnue(), Equation_base::mettre_a_jour(), Champ_Fonc::mettre_a_jour(), n_l, Champ_Proto::passe(), Champ_Inc::passe(), Equation_base::probleme(), ref_cast, and Champ_Fonc::valeurs().
milieu() [1/2]
const Milieu_base & Aire_interfaciale::milieu () const override virtual
Implements Equation_base.
Definition at line 104 of file Aire_interfaciale.cpp.
{
  return le_fluide.valeur();
}
References le_fluide, and Ref_Fluide_base::valeur().
milieu() [2/2]
Milieu_base & Aire_interfaciale::milieu () override virtual
Implements Equation_base.
Definition at line 109 of file Aire_interfaciale.cpp.
{
  return le_fluide.valeur();
}
References le_fluide, and Ref_Fluide_base::valeur().
nombre_d_operateurs()
int Aire_interfaciale::nombre_d_operateurs () const inline override virtual
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
Returns
int
Signification: le nombre d'operateurs de l'equation
Contraintes: toujours egal a 2
Reimplemented from Convection_Diffusion_std.
Definition at line 51 of file Aire_interfaciale.h.
  {
    return 1;
  }
operateur() [1/2]
const Operateur & Aire_interfaciale::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Returns
Operateur&
Signification: l'operateur specifie
Contraintes: reference constante
Reimplemented from Convection_Diffusion_std.
Definition at line 130 of file Aire_interfaciale.cpp.
{
  if (i) Cerr << "Aire_interfaciale : wrong operator number " << i << finl, Process::exit();
  return terme_convectif;
}
References Cerr, Process::exit(), finl, and Convection_Diffusion_std::terme_convectif.
operateur() [2/2]
Operateur & Aire_interfaciale::operateur (int i) override virtual
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
Returns
Operateur&
Signification: l'operateur specifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 136 of file Aire_interfaciale.cpp.
{
  if (i) Cerr << "Aire_interfaciale : wrong operator number " << i << finl, Process::exit();
  return terme_convectif;
}
References Cerr, Process::exit(), finl, and Convection_Diffusion_std::terme_convectif.
positive_unkown()
int Aire_interfaciale::positive_unkown () inline override virtual
Reimplemented from Equation_base.
Definition at line 49 of file Aire_interfaciale.h.
{return 1;};
printOn()
Sortie & Aire_interfaciale::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 43 of file Aire_interfaciale.cpp.
{
  return Convection_Diffusion_std::printOn(is);
}
References Convection_Diffusion_std::printOn().
readOn()
Entree & Aire_interfaciale::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 48 of file Aire_interfaciale.cpp.
{
  assert(l_inco_ch.non_nul());
  assert(le_fluide.non_nul());
  Convection_Diffusion_std::readOn(is);
  terme_convectif.set_fichier("Convection_interfacial_area");
  terme_convectif.set_description((Nom)"interfacial area transfer rate=Integral(-A*u*ndS) [kg] if SI units used");
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, probleme()) ? &ref_cast(Pb_Multiphase, probleme()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) Process::exit(que_suis_je() + " : not needed for single-phase flow!");
  for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
    if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : liquid phase not found!");
  if (pbm->has_correlation("diametre_bulles")) Process::exit(que_suis_je() + " : the interfacial area equation sets bubble diameter, there cannot be an exterior correlation !");
  return is;
}
References Nom::debute_par(), Process::exit(), Pb_Multiphase::has_correlation(), l_inco_ch, le_fluide, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), O_U_Ptr::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), Convection_Diffusion_std::readOn(), ref_cast, Operateur::set_description(), Operateur::set_fichier(), sub_type, and Convection_Diffusion_std::terme_convectif.
self_cast() [1/2]
const Aire_interfaciale & Aire_interfaciale::self_cast (const Objet_U & r) static
Definition at line 41 of file Aire_interfaciale.cpp.
self_cast() [2/2]
Aire_interfaciale & Aire_interfaciale::self_cast (Objet_U & r) static
Definition at line 41 of file Aire_interfaciale.cpp.
taille_memoire()
unsigned Aire_interfaciale::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 41 of file Aire_interfaciale.cpp.
Member Data Documentation
diametre_bulles
Champ_Fonc Aire_interfaciale::diametre_bulles protected
Definition at line 63 of file Aire_interfaciale.h.
Referenced by discretiser(), and mettre_a_jour().
info_obj
const Type_info Aire_interfaciale::info_obj static
Definition at line 33 of file Aire_interfaciale.h.
l_inco_ch
Champ_Inc Aire_interfaciale::l_inco_ch protected
Definition at line 62 of file Aire_interfaciale.h.
Referenced by discretiser(), inconnue(), and readOn().
le_fluide
Ref_Fluide_base Aire_interfaciale::le_fluide protected
Definition at line 65 of file Aire_interfaciale.h.
Referenced by associer_fluide(), milieu(), and readOn().
n_l
int Aire_interfaciale::n_l =-1 protected
Number of the liquid phase (the one where no IA is stored)
Definition at line 67 of file Aire_interfaciale.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Equations/Aire_interfaciale.h
src/ThHyd/Multiphase/Equations/Aire_interfaciale.cpp