TRUST: Deriv_Correlation_base Class Reference
Deriv_Correlation_base Class Reference
#include <Correlation.h>
Public Member Functions
~Deriv_Correlation_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Correlation_base ()
Deriv_Correlation_base (const Deriv_Correlation_base &)
const Correlation_base & valeur () const
Correlation_base & valeur ()
const Correlation_base * operator-> () const
Correlation_base * operator-> ()
const Deriv_Correlation_base & operator= (const Correlation_base &)
const Deriv_Correlation_base & operator= (const Deriv_Correlation_base &)
operator const Correlation_base & () const
operator Correlation_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Correlation_base & self_cast (Objet_U &)
static const
Deriv_Correlation_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Correlation_base * pointeur_
Detailed Description
Definition at line 42 of file Correlation.h.
Constructor & Destructor Documentation
Deriv_Correlation_base::~Deriv_Correlation_base ()
Definition at line 25 of file Correlation.cpp.
Deriv_Correlation_base::Deriv_Correlation_base ()
Definition at line 25 of file Correlation.cpp.
Deriv_Correlation_base::Deriv_Correlation_base (const Deriv_Correlation_base & t)
Definition at line 25 of file Correlation.cpp.
Member Function Documentation
Objet_U * Deriv_Correlation_base::cree_instance () [static]
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
int Deriv_Correlation_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
const Type_info * Deriv_Correlation_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
const Type_info & Deriv_Correlation_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Correlation.cpp.
const Type_info * Deriv_Correlation_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
Deriv_Correlation_base::operator const Correlation_base & () const
Definition at line 25 of file Correlation.cpp.
Deriv_Correlation_base::operator Correlation_base & ()
Definition at line 25 of file Correlation.cpp.
const Correlation_base * Deriv_Correlation_base::operator-> () const [inline]
Definition at line 42 of file Correlation.h.
: public DERIV(Correlation_base)
Correlation_base * Deriv_Correlation_base::operator-> () [inline]
Definition at line 42 of file Correlation.h.
: public DERIV(Correlation_base)
const Deriv_Correlation_base & Deriv_Correlation_base::operator= (const Deriv_Correlation_base & t)
Definition at line 25 of file Correlation.cpp.
const Deriv_Correlation_base & Deriv_Correlation_base::operator= (const Correlation_base & t)
Definition at line 25 of file Correlation.cpp.
Sortie & Deriv_Correlation_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
Entree & Deriv_Correlation_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
const Deriv_Correlation_base & Deriv_Correlation_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
Deriv_Correlation_base & Deriv_Correlation_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
void Deriv_Correlation_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Correlation.cpp.
unsigned Deriv_Correlation_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Correlation.
Definition at line 25 of file Correlation.cpp.
const Correlation_base & Deriv_Correlation_base::valeur () const [inline]
Definition at line 42 of file Correlation.h.
Referenced by Masse_CoviMAC_Face::ajouter_blocs(), Masse_CoviMAC_Face::dimensionner_blocs(), and Correlation::typer_lire().
: public DERIV(Correlation_base)
Correlation_base & Deriv_Correlation_base::valeur () [inline]
Definition at line 42 of file Correlation.h.
: public DERIV(Correlation_base)
Member Data Documentation
const Type_info Deriv_Correlation_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Correlation.
Definition at line 42 of file Correlation.h.
Correlation_base* Deriv_Correlation_base::pointeur_ [private]
Definition at line 42 of file Correlation.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Correlation.h
src/ThHyd/Multiphase/Correlations/Correlation.cpp