TRUST: Operateur_negligeable Class Reference
Operateur_negligeable Class Reference
Classe Opnegligeable
Cette classe definit l'interface d'un operateur negligeable
en definissant des methodes ajouter,calculer et mettre_a_jour
qui ne font aucun calcul.
Cette classe est utilisee lors de la definition d'operateurs
negligeable par heritage multiple.
#include <Operateur_negligeable.h>
Public Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
Ajout de la contribution d'un operateur negligeable a
un tableau.
NE FAIT RIEN, renvoie le parametre tableau sans le modifie.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
Initialise le parametre tableau avec la contribution
de l'operateur negligeable: initialise le tableau a ZERO.
void mettre_a_jour (double)
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN.
Protected Member Functions
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
Associe divers objets a un operateurs negligeable: NE FAIT RIEN.
Detailed Description
Classe Opnegligeable
Cette classe definit l'interface d'un operateur negligeable
en definissant des methodes ajouter,calculer et mettre_a_jour
qui ne font aucun calcul.
Cette classe est utilisee lors de la definition d'operateurs
negligeable par heritage multiple.
Definition at line 40 of file Operateur_negligeable.h.
Member Function Documentation
ajouter()
DoubleTab & Operateur_negligeable::ajouter (const DoubleTab & , DoubleTab & x) const inline
Ajout de la contribution d'un operateur negligeable a
un tableau.
NE FAIT RIEN, renvoie le parametre tableau sans le modifie.
Returns
DoubleTab&
Signification: le parametre d'entree x non modifie
Contraintes:
Definition at line 75 of file Operateur_negligeable.h.
{
  return x;
}
Referenced by Op_Diff_negligeable::ajouter().
associer()
void Operateur_negligeable::associer (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc &) inline protected
Associe divers objets a un operateurs negligeable: NE FAIT RIEN.
Definition at line 151 of file Operateur_negligeable.h.
{
}
Referenced by Op_Conv_negligeable::associer(), and Op_Diff_negligeable::associer().
calculer()
DoubleTab & Operateur_negligeable::calculer (const DoubleTab & , DoubleTab & x) const inline
Initialise le parametre tableau avec la contribution
de l'operateur negligeable: initialise le tableau a ZERO.
Returns
DoubleTab&
Signification: le tableau d'entree mis a zero
Contraintes:
Definition at line 101 of file Operateur_negligeable.h.
{
  return x=0.0;
}
Referenced by Op_Diff_negligeable::calculer().
mettre_a_jour()
void Operateur_negligeable::mettre_a_jour (double) inline
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN.
Definition at line 122 of file Operateur_negligeable.h.
{
}
Referenced by Op_Conv_negligeable::mettre_a_jour(), and Op_Diff_negligeable::mettre_a_jour().
The documentation for this class was generated from the following file:
src/Kernel/Operateurs/Operateur_negligeable.h