TRUST: grad_U_Champ_Face Class Reference
grad_U_Champ_Face Class Reference
classe grad_U_Champ_Face
#include <grad_U_Champ_Face.h>
Public Member Functions
grad_U_Champ_Face ()
~grad_U_Champ_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face &)
void me_calculer (double)
void associer_zone_Cl_dis_base (const Zone_Cl_dis_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static grad_U_Champ_Face & self_cast (Objet_U &)
static const grad_U_Champ_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Ref_Champ_Face vitesse_
Detailed Description
classe grad_U_Champ_Face
Definition at line 35 of file grad_U_Champ_Face.h.
Constructor & Destructor Documentation
grad_U_Champ_Face::grad_U_Champ_Face ()
Definition at line 27 of file grad_U_Champ_Face.cpp.
grad_U_Champ_Face::~grad_U_Champ_Face ()
Definition at line 27 of file grad_U_Champ_Face.cpp.
Member Function Documentation
void grad_U_Champ_Face::associer_champ (const Champ_Face & la_vitesse)
Definition at line 46 of file grad_U_Champ_Face.cpp.
References vitesse_.
Referenced by VDF_discretisation::grad_u().
{
  vitesse_= la_vitesse;
}
void grad_U_Champ_Face::associer_zone_Cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [inline]
Definition at line 62 of file grad_U_Champ_Face.h.
References la_zone_Cl_VDF.
Referenced by VDF_discretisation::grad_u().
{
  la_zone_Cl_VDF  = (const Zone_Cl_VDF&) la_zone_Cl_dis_base;
}
Objet_U * grad_U_Champ_Face::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
int grad_U_Champ_Face::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
const Type_info * grad_U_Champ_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
const Type_info * grad_U_Champ_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
void grad_U_Champ_Face::me_calculer (double tps)
Definition at line 51 of file grad_U_Champ_Face.cpp.
References la_zone_Cl_VDF, Ref_Zone_Cl_VDF::valeur(), Ref_Champ_Face::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and vitesse_.
Referenced by mettre_a_jour().
{
  vitesse_->calcul_grad_u(vitesse_.valeur().valeurs(), valeurs(), la_zone_Cl_VDF.valeur());
}
void grad_U_Champ_Face::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 55 of file grad_U_Champ_Face.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
Sortie & grad_U_Champ_Face::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 33 of file grad_U_Champ_Face.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & grad_U_Champ_Face::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 41 of file grad_U_Champ_Face.cpp.
{
  return s ;
}
const grad_U_Champ_Face & grad_U_Champ_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
grad_U_Champ_Face & grad_U_Champ_Face::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
unsigned grad_U_Champ_Face::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file grad_U_Champ_Face.cpp.
Member Data Documentation
const Type_info grad_U_Champ_Face::info_obj [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 39 of file grad_U_Champ_Face.h.
Ref_Zone_Cl_VDF grad_U_Champ_Face::la_zone_Cl_VDF [protected]
Definition at line 51 of file grad_U_Champ_Face.h.
Referenced by associer_zone_Cl_dis_base(), and me_calculer().
Ref_Champ_Face grad_U_Champ_Face::vitesse_ [protected]
Definition at line 52 of file grad_U_Champ_Face.h.
Referenced by associer_champ(), and me_calculer().
The documentation for this class was generated from the following files:
src/VDF/Champs/grad_U_Champ_Face.h
src/VDF/Champs/grad_U_Champ_Face.cpp