TRUST: Objet_a_lire Class Reference
Objet_a_lire Class Reference
#include <Objet_a_lire.h>
Public Types
enum Type {
INTEGER = 0 , DOUBLE = 1 , OBJECT = 2 , FLAG = 3 ,
NON_STD = 4 , DERIV = 5 , ArrOfInt_size_imp = 6 , ArrOfDouble_size_imp = 7 ,
PARAM = 8
}
enum Nature { OPTIONAL = 0 , REQUIRED = 1 }
Public Member Functions
Objet_a_lire ()
~Objet_a_lire ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_entier (int *)
void set_double (double *)
void set_objet (Objet_U *)
void set_arrofint (ArrOfInt *)
void set_arrofdouble (ArrOfDouble *)
void set_deriv (Deriv_ *, const char *prefixe)
Param & create_param (const char *)
void set_flag (int *)
void set_non_std (Objet_U *)
ptrParam & add_dict (const char *, int, const char *=0)
void set_nature (Objet_a_lire::Nature n)
void read (const Motcle &keyword, Entree &is)
void print (Sortie &s) const
const Nom & get_name (void) const
int comprend_name (Motcle &mot) const
Nom get_names_message (void) const
void set_name (const List_Nom &n)
bool is_optional (void) const
bool is_type_simple () const
double get_value () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Objet_a_lire & self_cast (Objet_U &)
static const Objet_a_lire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom name
List_Nom names
Objet_a_lire::Type type
Objet_a_lire::Nature nature
int * int_a_lire
double * double_a_lire
Objet_U * obj_a_lire
Objet_U * objet_lu
ArrOfInt * arrofint_a_lire
ArrOfDouble * arrofdouble_a_lire
int * flag_a_lire
Motcles dictionnaire_noms
ArrOfInt dictionnaire_valeurs
Vect_ptrParam dictionnaire_params
Motcle prefixe_deriv
ptrParam param_interne
Detailed Description
Definition at line 25 of file Objet_a_lire.h.
Member Enumeration Documentation
Nature
enum Objet_a_lire::Nature
Enumerator
OPTIONAL
REQUIRED
Definition at line 33 of file Objet_a_lire.h.
{ OPTIONAL = 0, REQUIRED = 1 };
Type
enum Objet_a_lire::Type
Enumerator
INTEGER
DOUBLE
OBJECT
FLAG
NON_STD
DERIV
ArrOfInt_size_imp
ArrOfDouble_size_imp
PARAM
Definition at line 29 of file Objet_a_lire.h.
            { INTEGER = 0, DOUBLE = 1, OBJECT = 2, FLAG = 3, NON_STD = 4, DERIV = 5, ArrOfInt_size_imp = 6,
              ArrOfDouble_size_imp = 7, PARAM = 8
            };
Constructor & Destructor Documentation
Objet_a_lire()
Objet_a_lire::Objet_a_lire ()
Definition at line 23 of file Objet_a_lire.cpp.
                          : int_a_lire(NULL),double_a_lire(NULL), obj_a_lire(NULL), objet_lu(NULL),arrofint_a_lire(NULL),arrofdouble_a_lire(NULL),flag_a_lire(NULL)
{
}
~Objet_a_lire()
Objet_a_lire::~Objet_a_lire ()
Definition at line 20 of file Objet_a_lire.cpp.
Member Function Documentation
add_dict()
ptrParam & Objet_a_lire::add_dict (const char * nom_option, int valeur, const char * aname = 0)
Definition at line 147 of file Objet_a_lire.cpp.
{
// Le dictionnaire ne fonctionne que pour des parametres de type int:
  assert(int_a_lire != 0);
// L'option ne doit pas encore exister dans le dictionnaire:
  assert(dictionnaire_noms.search(nom_option) < 0);
  dictionnaire_noms.add(nom_option);
  dictionnaire_valeurs.set_smart_resize(1);
  dictionnaire_valeurs.append_array(valeur);
  dictionnaire_params.add(ptrParam());
  ptrParam&  ptr=  dictionnaire_params[dictionnaire_params.size()-1];
  if (aname!=0)
    {
      ptr.create(aname);
    }
  return ptr;
}
References Vect_Motcle::add(), Vect_ptrParam::add(), TRUSTArray< _TYPE_ >::append_array(), ptrParam::create(), dictionnaire_noms, dictionnaire_params, dictionnaire_valeurs, int_a_lire, Motcles::search(), TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), and valeur().
Referenced by Param::dictionnaire(), and Param::dictionnaire_param().
comprend_name()
int Objet_a_lire::comprend_name (Motcle & mot) const
Definition at line 110 of file Objet_a_lire.cpp.
{
  if (mot==name)
    return 1;
// int size=names.size();
  CONST_LIST_CURSEUR(Nom) curseur(names);
  while (curseur)
// for (int i=0; i<size; i++)
    {
// Cerr<<"ici "<<names(i)<<finl;
      if (mot==curseur.valeur())
        {
// Cerr<<names.rang(mot)<<finl;
          mot=name;
          return 1;
        }
      ++curseur;
    }
  return 0;
}
References CONST_LIST_CURSEUR, name, and names.
Referenced by Param::read(), and Param::supprimer().
create_param()
Param & Objet_a_lire::create_param (const char * aname)
Definition at line 85 of file Objet_a_lire.cpp.
{
  type=PARAM;
  param_interne.create(aname);
  return param_interne.valeur();
}
References ptrParam::create(), PARAM, param_interne, type, and ptrParam::valeur().
Referenced by Param::ajouter_param().
cree_instance()
Objet_U * Objet_a_lire::cree_instance () static
Definition at line 20 of file Objet_a_lire.cpp.
duplique()
int Objet_a_lire::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Objet_a_lire.cpp.
get_info()
const Type_info * Objet_a_lire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Objet_a_lire.cpp.
get_name()
const Nom & Objet_a_lire::get_name (void) const
Definition at line 142 of file Objet_a_lire.cpp.
{
  return name;
}
References name.
Referenced by Param::ajouter_param(), Param::check(), Param::get_value(), Param::lire_sans_accolade(), and print().
get_names_message()
Nom Objet_a_lire::get_names_message (void) const
Definition at line 130 of file Objet_a_lire.cpp.
{
  Nom titi(name);
  int size=names.size();
  for (int i=size-1; i>=0; i--)
    {
      titi+=Nom("|");
      titi+=names(i);
    }
  return titi;
}
References name, names, and liste::size().
get_value()
double Objet_a_lire::get_value () const
Definition at line 176 of file Objet_a_lire.cpp.
{
  switch (type)
    {
    case INTEGER :
      return (*int_a_lire);
      break;
    case DOUBLE  :
      return (*double_a_lire);
      break;
    case FLAG    :
      return (*flag_a_lire);
      break;
    default      :
      Cerr<<"get_value not coded for this case"<<finl;
      Process::exit();
      break;
    }
// pour les compilos
  return 0.;
}
References Cerr, DOUBLE, double_a_lire, Process::exit(), finl, FLAG, flag_a_lire, int_a_lire, INTEGER, and type.
Referenced by Param::get_value().
info()
const Type_info * Objet_a_lire::info () static
Definition at line 20 of file Objet_a_lire.cpp.
is_optional()
bool Objet_a_lire::is_optional (void) const
Definition at line 92 of file Objet_a_lire.cpp.
{
  return (nature == OPTIONAL);
}
References nature, and OPTIONAL.
Referenced by Param::check(), and Param::lire_sans_accolade().
is_type_simple()
bool Objet_a_lire::is_type_simple () const
Definition at line 170 of file Objet_a_lire.cpp.
{
// return ((double_a_lire!=NULL)||(int_a_lire!=NULL)||(flag_a_lire!=NULL));
  return ((type==INTEGER)||(type==DOUBLE)||(type==FLAG));
}
References DOUBLE, FLAG, INTEGER, and type.
Referenced by Param::check(), and Param::get_value().
print()
void Objet_a_lire::print (Sortie & s) const
Definition at line 153 of file Param.cpp.
{
  switch (type)
    {
    case INTEGER :
      if (dictionnaire_noms.size() == 0)
        {
          s<< get_name()<<" "<<(*int_a_lire);
        }
      else
        {
          Cerr<<" dico print not coded for this case "<< get_name()<<finl;
          Process::exit();
        }
      break;
    case DOUBLE  :
      s<<get_name()<<" "<< (*double_a_lire);
      break;
    case FLAG    :
      if  (*flag_a_lire) s<<get_name() ;
      break;
    case NON_STD :
      s<< get_name() << " non standard !!!!";
      break;
    default      :
      Cerr<<"print not coded for this case "<< get_name()<<finl;
      Process::exit();
      break;
    }
}
References Cerr, dictionnaire_noms, DOUBLE, Process::exit(), finl, FLAG, flag_a_lire, get_name(), INTEGER, NON_STD, vect_impl::size(), and type.
Referenced by Param::print().
printOn()
Sortie & Objet_a_lire::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file Objet_a_lire.cpp.
{
  return Objet_U::printOn(os);
}
References Objet_U::printOn().
read()
void Objet_a_lire::read (const Motcle & keyword, Entree & is)
Definition at line 199 of file Objet_a_lire.cpp.
{
  switch (type)
    {
    case INTEGER :
      if (dictionnaire_noms.size() == 0)
        {
          is>>*int_a_lire;
        }
      else
        {
          Motcle motlu;
          is >> motlu;
          const int rang = dictionnaire_noms.search(motlu);
          if (rang < 0)
            {
              Cerr << "Error while reading parameter " << name
                   << "\n Found: " << motlu
                   << "\n Expected one on these keywords: " << dictionnaire_noms << finl;
              barrier();
              exit();
            }
          *int_a_lire = dictionnaire_valeurs[rang];
          ptrParam& ptr=dictionnaire_params[rang];
          if (ptr.non_nul())
            {
              ptr.valeur().lire_avec_accolades_depuis(is);
            }
        }
      break;
    case DOUBLE  :
      is >> (*double_a_lire);
      break;
    case OBJECT  :
      is >> (*obj_a_lire);
      break;
    case FLAG    :
      (*flag_a_lire)=1;
      break;
    case NON_STD :
      (*objet_lu).lire_motcle_non_standard(motcle,is);
      break;
    case DERIV   :
      {
        Motcle type_complet(prefixe_deriv);
        Motcle the_type;
        is >> the_type;
        type_complet += the_type;
        Entree_complete is2(type_complet, is);
        is2 >> (*obj_a_lire);
        break;
      }
    case ArrOfInt_size_imp:
      {
        ArrOfInt& arr=*arrofint_a_lire;
        int size=arr.size_array();
// on ne veut pas de taille nulle pour etre sur que l'utilisateur a bien fait dimensionner...
        assert(size>0);
        for (int i=0; i<size; i++) is >>arr[i];
        break;
      }
    case ArrOfDouble_size_imp:
      {
        ArrOfDouble& arr=*arrofdouble_a_lire;
        int size=arr.size_array();
// on ne veut pas de taille nulle pour etre sur que l'utilisateur a bien fait dimensionner...
        assert(size>0);
        for (int i=0; i<size; i++) is >>arr[i];
        break;
      }
    case PARAM:
      {
        param_interne.valeur().lire_avec_accolades_depuis(is);
        break;
      }
    default      :
      Cerr << "Invalid parameter type" << finl;
      Process::exit();
      break;
    }
}
References arrofdouble_a_lire, ArrOfDouble_size_imp, arrofint_a_lire, ArrOfInt_size_imp, Process::barrier(), Cerr, DERIV, dictionnaire_noms, dictionnaire_params, dictionnaire_valeurs, DOUBLE, Process::exit(), finl, FLAG, int_a_lire, INTEGER, Param::lire_avec_accolades_depuis(), name, ptrParam::non_nul(), NON_STD, OBJECT, PARAM, param_interne, prefixe_deriv, Motcles::search(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), type, and ptrParam::valeur().
Referenced by Param::lire_sans_accolade(), and Param::read().
readOn()
Entree & Objet_a_lire::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Objet_a_lire.cpp.
{
  return Objet_U::readOn(is);
}
References Objet_U::readOn().
self_cast() [1/2]
const Objet_a_lire & Objet_a_lire::self_cast (const Objet_U & r) static
Definition at line 20 of file Objet_a_lire.cpp.
self_cast() [2/2]
Objet_a_lire & Objet_a_lire::self_cast (Objet_U & r) static
Definition at line 20 of file Objet_a_lire.cpp.
set_arrofdouble()
void Objet_a_lire::set_arrofdouble (ArrOfDouble * quoi)
Definition at line 59 of file Objet_a_lire.cpp.
{
  arrofdouble_a_lire=quoi;
  type=ArrOfDouble_size_imp;
}
References arrofdouble_a_lire, ArrOfDouble_size_imp, and type.
Referenced by Param::ajouter_arr_size_predefinie().
set_arrofint()
void Objet_a_lire::set_arrofint (ArrOfInt * quoi)
Definition at line 53 of file Objet_a_lire.cpp.
{
  arrofint_a_lire=quoi;
  type=ArrOfInt_size_imp;
}
References arrofint_a_lire, ArrOfInt_size_imp, and type.
Referenced by Param::ajouter_arr_size_predefinie().
set_deriv()
void Objet_a_lire::set_deriv (Deriv_ * quoi, const char * prefixe)
Definition at line 65 of file Objet_a_lire.cpp.
{
  obj_a_lire=quoi;
  type=DERIV;
  prefixe_deriv = prefixe;
}
References DERIV, obj_a_lire, prefixe_deriv, and type.
Referenced by Param::ajouter_deriv().
set_double()
void Objet_a_lire::set_double (double * quoi)
Definition at line 41 of file Objet_a_lire.cpp.
{
  type=DOUBLE;
  double_a_lire=quoi;
}
References DOUBLE, double_a_lire, and type.
Referenced by Param::ajouter().
set_entier()
void Objet_a_lire::set_entier (int * quoi)
Definition at line 35 of file Objet_a_lire.cpp.
{
  type=INTEGER;
  int_a_lire=quoi;
}
References int_a_lire, INTEGER, and type.
Referenced by Param::ajouter().
set_flag()
void Objet_a_lire::set_flag (int * quoi)
Definition at line 72 of file Objet_a_lire.cpp.
{
  flag_a_lire=quoi;
// initialisation du flag a 0
  *flag_a_lire=0;
  type=FLAG;
}
References FLAG, flag_a_lire, and type.
Referenced by Param::ajouter_flag().
set_name()
void Objet_a_lire::set_name (const List_Nom & n)
Definition at line 98 of file Objet_a_lire.cpp.
{
  CONST_LIST_CURSEUR(Nom) curseur(n);
  name=curseur.valeur();
  ++curseur;
  while (curseur)
    {
      names.add(curseur.valeur());
      ++curseur;
    }
}
References List_Nom::add(), CONST_LIST_CURSEUR, name, and names.
Referenced by Param::create_or_get_objet_a_lire().
set_nature()
void Objet_a_lire::set_nature (Objet_a_lire::Nature n)
Definition at line 165 of file Objet_a_lire.cpp.
{
  nature = n;
}
References nature.
Referenced by Param::ajouter(), Param::ajouter_arr_size_predefinie(), Param::ajouter_deriv(), Param::ajouter_flag(), Param::ajouter_non_std(), and Param::ajouter_param().
set_non_std()
void Objet_a_lire::set_non_std (Objet_U * quoi)
Definition at line 80 of file Objet_a_lire.cpp.
{
  objet_lu=quoi;
  type=NON_STD;
}
References NON_STD, objet_lu, and type.
Referenced by Param::ajouter_non_std().
set_objet()
void Objet_a_lire::set_objet (Objet_U * quoi)
Definition at line 47 of file Objet_a_lire.cpp.
{
  obj_a_lire=quoi;
  type=OBJECT;
}
References obj_a_lire, OBJECT, and type.
Referenced by Param::ajouter().
taille_memoire()
unsigned Objet_a_lire::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Objet_a_lire.cpp.
Member Data Documentation
arrofdouble_a_lire
ArrOfDouble* Objet_a_lire::arrofdouble_a_lire protected
Definition at line 65 of file Objet_a_lire.h.
Referenced by read(), and set_arrofdouble().
arrofint_a_lire
ArrOfInt* Objet_a_lire::arrofint_a_lire protected
Definition at line 64 of file Objet_a_lire.h.
Referenced by read(), and set_arrofint().
dictionnaire_noms
Motcles Objet_a_lire::dictionnaire_noms protected
Definition at line 67 of file Objet_a_lire.h.
Referenced by add_dict(), print(), and read().
dictionnaire_params
Vect_ptrParam Objet_a_lire::dictionnaire_params protected
Definition at line 69 of file Objet_a_lire.h.
Referenced by add_dict(), and read().
dictionnaire_valeurs
ArrOfInt Objet_a_lire::dictionnaire_valeurs protected
Definition at line 68 of file Objet_a_lire.h.
Referenced by add_dict(), and read().
double_a_lire
double* Objet_a_lire::double_a_lire protected
Definition at line 62 of file Objet_a_lire.h.
Referenced by get_value(), and set_double().
flag_a_lire
int* Objet_a_lire::flag_a_lire protected
Definition at line 66 of file Objet_a_lire.h.
Referenced by get_value(), print(), and set_flag().
info_obj
const Type_info Objet_a_lire::info_obj static
Definition at line 27 of file Objet_a_lire.h.
int_a_lire
int* Objet_a_lire::int_a_lire protected
Definition at line 61 of file Objet_a_lire.h.
Referenced by add_dict(), get_value(), read(), and set_entier().
name
Nom Objet_a_lire::name protected
Definition at line 57 of file Objet_a_lire.h.
Referenced by comprend_name(), get_name(), get_names_message(), read(), and set_name().
names
List_Nom Objet_a_lire::names protected
Definition at line 58 of file Objet_a_lire.h.
Referenced by comprend_name(), get_names_message(), and set_name().
nature
Objet_a_lire::Nature Objet_a_lire::nature protected
Definition at line 60 of file Objet_a_lire.h.
Referenced by is_optional(), and set_nature().
obj_a_lire
Objet_U* Objet_a_lire::obj_a_lire protected
Definition at line 63 of file Objet_a_lire.h.
Referenced by set_deriv(), and set_objet().
objet_lu
Objet_U * Objet_a_lire::objet_lu protected
Definition at line 63 of file Objet_a_lire.h.
Referenced by set_non_std().
param_interne
ptrParam Objet_a_lire::param_interne protected
Definition at line 71 of file Objet_a_lire.h.
Referenced by create_param(), and read().
prefixe_deriv
Motcle Objet_a_lire::prefixe_deriv protected
Definition at line 70 of file Objet_a_lire.h.
Referenced by read(), and set_deriv().
type
Objet_a_lire::Type Objet_a_lire::type protected
Definition at line 59 of file Objet_a_lire.h.
Referenced by create_param(), get_value(), is_type_simple(), print(), read(), set_arrofdouble(), set_arrofint(), set_deriv(), set_double(), set_entier(), set_flag(), set_non_std(), and set_objet().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Objet_a_lire.h
src/Kernel/Utilitaires/Objet_a_lire.cpp
src/Kernel/Utilitaires/Param.cpp