TRUST: Format_Post_base Class Reference
Format_Post_base Class Reference abstract
Classe de base des formats de postraitements pour les champs<br>(lata, med, lml, meshtv).
Utilisation de la classe par l'interface generique:
-typer un objet format de postraitement
-initialiser l objet format de postraitement
-proceder a des operations de complement et verification
-ecrire un domaine
-ecrire_temps
-ecrire_champ (un type de champ supporte: aux elements ou aux sommets,
ou encore aux faces si on a ecrit les faces du domaine
et si les faces sont supportees par le postraitement)
#include <Format_Post_base.h>
Public Member Functions
Format_Post_base ()
~Format_Post_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()=0
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int initialize_by_default (const Nom &file_basename)
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
virtual int initialize (const Nom &file_basename, const int format, const Nom &option_para)
virtual int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit)
virtual int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post)
virtual int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post)
virtual int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init)
virtual int test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat)
virtual int init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine &domaine)
virtual int finir_ecriture (double temps_courant)
virtual int finir (int &est_le_dernier_post)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
virtual int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post)
virtual int ecrire_temps (const double temps)
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
virtual int ecrire_champ2 (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data, const DoubleTab &coord)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
void postraiter_debug_valeurs_un_instant (const Nom &nom_fich, const Domaine &dom, const Zone_dis_base &zone_dis, double temps_champ, double temps_courant, const Nom &id_champ_post, const Nature_du_champ &nature_champ, const Noms &noms_compos, const Noms &unites, const Motcle &loc_post, const DoubleTab &data, int ncomp=-1, int axi=0, int champ=1, int stat=0, double dt_ch=1., double dt_stat=1., int reprise=0, int est_le_premier_post=1, int est_le_dernier_post=1, double t_init=0., double temps_post=-2)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Format_Post_base & self_cast (Objet_U &)
static const Format_Post_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Classe de base des formats de postraitements pour les champs<br>(lata, med, lml, meshtv).
Utilisation de la classe par l'interface generique:
-typer un objet format de postraitement
-initialiser l objet format de postraitement
-proceder a des operations de complement et verification
-ecrire un domaine
-ecrire_temps
-ecrire_champ (un type de champ supporte: aux elements ou aux sommets,
ou encore aux faces si on a ecrit les faces du domaine
et si les faces sont supportees par le postraitement)
Definition at line 99 of file Format_Post_base.h.
Constructor & Destructor Documentation
Format_Post_base()
Format_Post_base::Format_Post_base ()
Definition at line 19 of file Format_Post_base.cpp.
~Format_Post_base()
Format_Post_base::~Format_Post_base () override
Definition at line 19 of file Format_Post_base.cpp.
Member Function Documentation
completer_post()
int Format_Post_base::completer_post (const Domaine & dom, const int axi, const Nature_du_champ & nature, const int nb_compo, const Noms & noms_compo, const Motcle & loc_post, const Nom & le_nom_champ_post) virtual
Reimplemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 95 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::preparer_post_champ(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Champ_base::completer_post_champ(), and postraiter_debug_valeurs_un_instant().
ecrire_champ()
int Format_Post_base::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) virtual
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, and Format_Post_Med.
Definition at line 213 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_champ(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), latatoother::interpreter(), postraiter_debug_valeurs_un_instant(), traite_bord(), and Moyenne_volumique::traiter_champs().
ecrire_champ2()
int Format_Post_base::ecrire_champ2 (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data, const DoubleTab & coord) virtual
Reimplemented in Format_Post_XYZ.
Definition at line 227 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_champ2(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
ecrire_domaine()
int Format_Post_base::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) virtual
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
Reimplemented in Format_Post_Lml, Format_Post_XYZ, Format_Post_Lata, Format_Post_Lata_V1, and Format_Post_Med.
Definition at line 164 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_domaine(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), ecrire_domaine_dis(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
ecrire_domaine_dis()
int Format_Post_base::ecrire_domaine_dis (const Domaine & domaine, const Ref_Zone_dis_base & zone_dis_base, const int est_le_premier_post) virtual
Reimplemented in Format_Post_Med.
Definition at line 171 of file Format_Post_base.cpp.
{
  return ecrire_domaine(domaine, est_le_premier_post);
}
References ecrire_domaine().
ecrire_entete()
int Format_Post_base::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) virtual
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_Med, and Format_Post_XYZ.
Definition at line 70 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_entete method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
ecrire_item_int()
int Format_Post_base::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_zone, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) virtual
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 257 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_champ_int(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by postraiter_debug_valeurs_un_instant().
ecrire_temps()
int Format_Post_base::ecrire_temps (const double temps) virtual
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
Reimplemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 182 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::ecrire_temps(const double temps)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
finir()
int Format_Post_base::finir (int & est_le_dernier_post) virtual
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 76 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::finir method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
finir_ecriture()
int Format_Post_base::finir_ecriture (double temps_courant) virtual
Definition at line 88 of file Format_Post_base.cpp.
{
  return 1;
}
Referenced by postraiter_debug_valeurs_un_instant().
get_info()
const Type_info * Format_Post_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, Format_Post_Med, Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 19 of file Format_Post_base.cpp.
info()
const Type_info * Format_Post_base::info () static
Definition at line 19 of file Format_Post_base.cpp.
init_ecriture()
int Format_Post_base::init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine & domaine) virtual
Definition at line 82 of file Format_Post_base.cpp.
{
  return 1;
}
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
initialize()
int Format_Post_base::initialize (const Nom & file_basename, const int format, const Nom & option_para) virtual
Reimplemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 58 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::initialize(" << file_basename
       << ")\n method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), and latatoother::interpreter().
initialize_by_default()
int Format_Post_base::initialize_by_default (const Nom & file_basename) virtual
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
Reimplemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 51 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::initialize_by_default(" << file_basename
       << ")\n method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
lire_motcle_non_standard()
int Format_Post_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Reimplemented in Format_Post_Lata.
Definition at line 38 of file Format_Post_base.cpp.
{
  Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
  exit();
  return -1;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
modify_file_basename()
int Format_Post_base::modify_file_basename (const Nom file_basename, const int a_faire, const double tinit) virtual
Reimplemented in Format_Post_Lata.
Definition at line 65 of file Format_Post_base.cpp.
{
  return 0;
}
postraiter_debug_valeurs_un_instant()
void Format_Post_base::postraiter_debug_valeurs_un_instant (const Nom & nom_fich, const Domaine & dom, const Zone_dis_base & zone_dis, double temps_champ, double temps_courant, const Nom & id_champ_post, const Nature_du_champ & nature_champ, const Noms & noms_compos, const Noms & unites, const Motcle & loc_post, const DoubleTab & data, int ncomp = -1, int axi = 0, int champ = 1, int stat = 0, double dt_ch = 1., double dt_stat = 1., int reprise = 0, int est_le_premier_post = 1, int est_le_dernier_post = 1, double t_init = 0., double temps_post = -2)
< Identifiant
< localisation
< reference
< Identifiant
< localisation
< reference
Definition at line 295 of file Format_Post_base.cpp.
{
  const Nom& id_domaine = dom.le_nom();
  const int nb_compo = noms_compos.size();
  DoubleTab valeurs_tmp;
  int dim0 = data.dimension(0);
  int nb_dim_val = 1;
  if (ncomp==-1)
    {
      if (data.nb_dim()>1)
        {
          nb_dim_val = data.dimension(1);
          valeurs_tmp.resize(dim0,nb_dim_val);
          for (int i=0; i<dim0; i++)
            for (int j=0; j<nb_dim_val; j++)
              valeurs_tmp(i,j) = data(i,j);
        }
      else
        {
          valeurs_tmp.resize(dim0,nb_dim_val);
          for (int i=0; i<dim0; i++)
            valeurs_tmp(i,0) = data(i);
        }
    }
  else
    {
      valeurs_tmp.resize(dim0);
      if (data.nb_dim()>1)
        {
          int nb_comp = data.dimension(1);
          for (int i=0; i<dim0; i++)
            for (int j=0; j<nb_comp; j++)
              if (j==ncomp)
                valeurs_tmp(i) = data(i,j);
        }
      else
        valeurs_tmp = data;
    }
  initialize_by_default(nom_fich);
  test_coherence(champ,stat,dt_ch,dt_stat);
  ecrire_entete(temps_courant,reprise,est_le_premier_post);
  preparer_post(id_domaine,est_le_premier_post,reprise,t_init);
  completer_post(dom,is_axi,nature_champ,nb_compo,noms_compos,loc_post,id_champ_post);
  ecrire_domaine(dom,est_le_premier_post);
  if (loc_post=="FACES")
    {
      const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis);
      const IntTab& faces_sommets = zone_vf.face_sommets();
      const int nb_sommets = dom.nb_som();
      const int nb_faces = faces_sommets.dimension(0);
      ecrire_item_int("FACES", //!< Identifiant
                      dom.le_nom(),
                      dom.zone(0).le_nom(),
                      "FACES", //!< localisation
                      "SOMMETS", //!< reference
                      faces_sommets,
                      nb_sommets);
      const IntTab& elem_faces = zone_vf.elem_faces();
      ecrire_item_int("ELEM_FACES", //!< Identifiant
                      dom.le_nom(),
                      dom.zone(0).le_nom(),
                      "ELEMENTS", //!< localisation
                      "FACES", //!< reference
                      elem_faces,
                      nb_faces);
    }
  ecrire_temps(temps_courant);
  init_ecriture(temps_courant,temps_post,est_le_premier_post,dom);
  Nom nature("scalar");
  if (nature_champ==vectoriel) nature="vector";
  ecrire_champ(dom,unites,noms_compos,ncomp,temps_champ,temps_courant,id_champ_post,id_domaine,loc_post,nature,valeurs_tmp);
  finir_ecriture(temps_courant);
  finir(est_le_dernier_post);
}
References completer_post(), TRUSTTab< _TYPE_ >::dimension(), ecrire_champ(), ecrire_domaine(), ecrire_entete(), ecrire_item_int(), ecrire_temps(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), finir(), finir_ecriture(), init_ecriture(), initialize_by_default(), Domaine::le_nom(), Zone::le_nom(), TRUSTTab< _TYPE_ >::nb_dim(), Domaine::nb_som(), preparer_post(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), test_coherence(), vectoriel, and Domaine::zone().
preparer_post()
int Format_Post_base::preparer_post (const Nom & id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) virtual
Reimplemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Definition at line 106 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::preparer_post(...)\n"
       << " method not coded for " << que_suis_je() << finl;
  return 0;
}
References Cerr, finl, and Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), latatoother::interpreter(), and postraiter_debug_valeurs_un_instant().
printOn()
Sortie & Format_Post_base::printOn (Sortie & x) const override protected virtual
erreur => exit
Reimplemented from Objet_U.
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, Format_Post_Med, Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 22 of file Format_Post_base.cpp.
{
  Cerr << "Format_Post_base::printOn : error" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Format_Post_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, Format_Post_Med, Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 29 of file Format_Post_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" post-processing format object"<<finl;
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Cerr, finl, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Format_Post_Lata::readOn(), Format_Post_Lml::readOn(), Format_Post_XYZ::readOn(), and Format_Post_Med::readOn().
reset()
virtual void Format_Post_base::reset () pure virtual
Implemented in Format_Post_Lata, Format_Post_Lata_V1, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
self_cast() [1/2]
const Format_Post_base & Format_Post_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Format_Post_base.cpp.
self_cast() [2/2]
Format_Post_base & Format_Post_base::self_cast (Objet_U & r) static
Definition at line 19 of file Format_Post_base.cpp.
set_param()
virtual void Format_Post_base::set_param (Param & param) pure virtual
Implemented in Format_Post_Lata, Format_Post_Lml, Format_Post_XYZ, and Format_Post_Med.
Referenced by readOn().
test_coherence()
int Format_Post_base::test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat) virtual
Definition at line 117 of file Format_Post_base.cpp.
{
  if (stat && champs && !est_egal(dt_stat,dt_ch))
    {
      Cerr << "Error!" << finl;
      Cerr << "You try to write unknown fields and statistic fields with a different time period (dt_post):" << finl;
      Cerr << "-----------------------------" << finl;
      Cerr << "Champs dt_post " << dt_ch << finl;
      Cerr << "Statistiques dt_post " << dt_stat << finl;
      Cerr << "-----------------------------" << finl;
      Cerr << "It is not possible in the same postprocessing block." << finl;
      Cerr << "Try to use different postprocessing blocks, one for the unknown fields" << finl;
      Cerr << "and one for the statistic fields." << finl;
      exit();
    }
  return 1;
}
References Cerr, est_egal(), Process::exit(), and finl.
Referenced by postraiter_debug_valeurs_un_instant().
Member Data Documentation
info_obj
const Type_info Format_Post_base::info_obj static
Definition at line 101 of file Format_Post_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post_base.h
src/Kernel/Framework/Format_Post_base.cpp