TRUST: Debog_Pb Class Reference
Debog_Pb Class Reference
#include <Debog_Pb.h>
Public Member Functions
Debog_Pb ()
~Debog_Pb ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void verifier (const char *const msg, double, double *refvalue=0)
void verifier (const char *const msg, const DoubleVect &, DoubleVect *refvalue=0)
if arr_ref is not null and if mode_db_ is "read\&compare", we put the reference
value found in the file in arr_ref. arr_ref and arr can point to the same object.
void verifier (const char *const msg, int, int *refvalue=0)
void verifier (const char *const msg, const IntVect &, IntVect *refvalue=0)
if arr_ref is not null and if mode_db_ is "read\&compare", we put the reference
value found in the file in arr_ref. arr_ref and arr can point to the same object.
void set_nom_pb_actuel (const Nom &nom)
void verifier_matrice (const char *const msg, const Matrice_Base &, const MD_Vector &md_lignes, const MD_Vector &md_colonnes)
md_lignes: descripteur des indices de lignes (cad descripteur du vecteur b dans A*x=b)
mb_colonnes: idem, indices colonnes (cad descripteur du vecteur x dans A*x=b)
void verifier_Mat_elems (const char *const msg, const Matrice_Base &la_matrice)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Debog_Pb & self_cast (Objet_U &)
static const Debog_Pb & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Ref_Debog_Pb & get_debog_instance ()
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Debog_Pb (const Debog_Pb &)
int test_ignore_msg (const char *const msg)
void goto_msg (const char *const msg)
void write_geometry_data ()
void register_item (const MD_Vector &md, const Nom &id)
void add_renum_item (const DoubleTab &coord_ref, const DoubleTab &coord_par, const MD_Vector &md, const Nom &id)
void read_geometry_data ()
void ecrire_partie (const DoubleVect &arr)
void ecrire_partie (const IntVect &arr)
void ecrire_gen (const char *const msg, const DoubleVect &arr, int num_deb=-1)
void ecrire_gen (const char *const msg, const IntVect &arr, int num_deb=-1)
const IntVect & find_renum_vector (const MD_Vector &, Nom &id) const
void verifier_partie_std (const DoubleVect &reference, const DoubleVect &arr, DoubleVect *arr_ref=0)
void verifier_partie_std (const IntVect &reference, const IntVect &arr, IntVect *arr_ref=0)
void verifier_partie (const DoubleVect &reference, const DoubleVect &arr, DoubleVect *arr_ref=0)
void verifier_partie (const IntVect &reference, const IntVect &arr, IntVect *arr_ref=0)
void verifier_gen (const char *const msg, const DoubleVect &arr, DoubleVect *arr_ref=0)
void verifier_gen (const char *const msg, const IntVect &arr, IntVect *arr_ref=0)
void error_function ()
methode appelee des qu'une erreur est trouvee dans l'espace reel.
(utile pour poser un breakpoint dans gdb)
Protected Attributes
int debog_msg_count_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Nom fichier_domaine_
Nom fichier_faces_
Nom fichier_debog_
fichier contenant les valeurs a relire
double seuil_absolu_
double seuil_relatif_
Motcles msg_a_ignorer_
int mode_db_
int exit_on_error_
Vect_MD_Vector known_md_
Noms renum_id_
Vect_IntVect renum_array_
SFichier write_debog_data_file_
EFichier debog_data_file_
SFichier log_file_
EcrFicCollecte detailed_log_file_
Nom nom_pb_actuel_
Static Protected Attributes
static Ref_Debog_Pb instance_debog_
Detailed Description
Definition at line 40 of file Debog_Pb.h.
Constructor & Destructor Documentation
Debog_Pb::Debog_Pb ()
Definition at line 77 of file Debog.cpp.
Debog_Pb::~Debog_Pb ()
Definition at line 77 of file Debog.cpp.
Debog_Pb::Debog_Pb (const Debog_Pb &) [protected]
< invalide
Definition at line 136 of file Debog.cpp.
References Process::exit().
                                 : Objet_U()
{
  exit(); //!< invalide
}
Member Function Documentation
void Debog_Pb::add_renum_item (const DoubleTab & coord_ref, const DoubleTab & coord_par, const MD_Vector & md, const Nom & id) [protected]
Definition at line 311 of file Debog.cpp.
References Vect_IntVect::add(), Octree_Double::build_nodes(), Cerr, creer_tableau_distribue(), DoubleTab::dimension(), DoubleTab::dimension_tot(), Process::exit(), finl, Array_base::NOCOPY_NOINIT, Objet_U::precision_geom, register_item(), renum_array_, Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), ArrOfInt::set_smart_resize(), vect_impl::size(), ArrOfInt::size_array(), and IntVect::size_totale().
Referenced by read_geometry_data().
{
  register_item(md, id);
  const double epsilon = Objet_U::precision_geom;
// On cree un octree contenant les points du domaine de reference
// et on cherche chaque point du domaine local dans cet octree.
  Octree_Double octree;
  octree.build_nodes(coord_ref, 1 /* include_virtual_items */);
// Add a new renum array:
  renum_array_.add(IntVect());
  IntVect& renum = renum_array_[renum_array_.size()-1];
  MD_Vector_tools::creer_tableau_distribue(md, renum, Array_base::NOCOPY_NOINIT);
  if (renum.size_totale() != coord_par.dimension_tot(0))
    {
      Cerr << "Internal error in Debog::add_renum_item: coordinate array does not match md descriptor" << finl;
      exit();
    }
  const int dim = coord_par.dimension(1);
  ArrOfDouble center(dim);
  ArrOfInt elements;
  elements.set_smart_resize(1);
  const int n = renum.size_totale();
  for (int i = 0; i < n; i++)
    {
      for (int j = 0; j < dim; j++)
        center[j] = coord_par(i,j);
      octree.search_elements_box(center, epsilon, elements);
// la premiere recherche renvoie tous les sommets potentiellement proches.
// il faut faire ensuite un test sur chaque sommet:
      octree.search_nodes_close_to(center, coord_ref, elements, epsilon);
      const int k = elements.size_array();
      if (k != 1)
        {
          Cerr << "Debog::add_renum_item: Error. Id=" << id
               << "\n Item with following coordinates was found " << k << " times within epsilon=" << epsilon
               << "\n in the reference geometry: " << center << finl;
          exit();
        }
// renum[i] is the index of the i-th local item in the reference geometry
      renum[i] = elements[0];
    }
}
Objet_U * Debog_Pb::cree_instance () [static]
Definition at line 77 of file Debog.cpp.
int Debog_Pb::duplique () const [virtual]
Implements Objet_U.
Definition at line 77 of file Debog.cpp.
void Debog_Pb::ecrire_gen (const char *const msg, const DoubleVect & arr, int num_deb = -1) [protected]
Definition at line 665 of file Debog.cpp.
References Cerr, debog_msg_count_, DoubleTab::dimension(), ecrire_partie(), finl, DoubleVect::get_md_vector(), Process::je_suis_maitre(), DoubleVect::line_size(), DoubleTab::nb_dim(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), ref_cast, space, sub_type, MD_Vector::valeur(), and write_debog_data_file_.
Referenced by verifier().
{
  if (!arr.get_md_vector().non_nul())
    {
      Cerr << "WARNING in Debog::ecrire: array has no parallel metadata" << finl;
      Cerr << " (message: " << msg << ")" << finl;
      return;
    }
  Sortie& os = write_debog_data_file_;
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  const int ls = arr.line_size();
  if (Process::je_suis_maitre())
    {
      os << "msg : " << debog_msg_count_ << " : " << msg << " FinMsg " << finl;
      Cerr << "DEBOG: writing array, message " << debog_msg_count_ << " : " << msg << finl;
      if (num_deb >= 0)
        os << num_deb << finl;
// Dump array header:
      if (sub_type(DoubleTab, arr))
        {
// Header for DoubleTab:
          const DoubleTab& tab = ref_cast(DoubleTab, arr);
          const int n =  tab.nb_dim();
          os << n << finl;
// total number of lines:
          os << md.nb_items_seq_tot();
// other dimensions:
          for (int i = 1; i < n; i++)
            os << space << tab.dimension(i);
          os << finl;
        }
// Header of ArrayOfDouble:
      os << md.nb_items_seq_tot() * ls << finl;
    }
  ecrire_partie(arr);
}
void Debog_Pb::ecrire_gen (const char *const msg, const IntVect & arr, int num_deb = -1) [protected]
Definition at line 978 of file Debog.cpp.
References Cerr, debog_msg_count_, IntTab::dimension(), ecrire_partie(), finl, IntVect::get_md_vector(), Process::je_suis_maitre(), IntVect::line_size(), IntTab::nb_dim(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), ref_cast, space, sub_type, MD_Vector::valeur(), and write_debog_data_file_.
{
  if (!arr.get_md_vector().non_nul())
    {
      Cerr << "WARNING in Debog::ecrire: array has no parallel metadata" << finl;
      Cerr << " (message: " << msg << ")" << finl;
      return;
    }
  Sortie& os = write_debog_data_file_;
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  const int ls = arr.line_size();
  if (Process::je_suis_maitre())
    {
      os << "msg : " << debog_msg_count_ << " : " << msg << " FinMsg " << finl;
      Cerr << "DEBOG: writing array, message " << debog_msg_count_ << " : " << msg << finl;
      if (num_deb >= 0)
        os << num_deb << finl;
// Dump array header:
      if (sub_type(IntTab, arr))
        {
// Header for DoubleTab:
          const IntTab& tab = ref_cast(IntTab, arr);
          const int n =  tab.nb_dim();
          os << n << finl;
// total number of lines:
          os << md.nb_items_seq_tot();
// other dimensions:
          for (int i = 1; i < n; i++)
            os << space << tab.dimension(i);
          os << finl;
        }
// Header of ArrayOfDouble:
      os << md.nb_items_seq_tot() * ls << finl;
    }
  ecrire_partie(arr);
}
void Debog_Pb::ecrire_partie (const IntVect & arr) [protected]
Definition at line 956 of file Debog.cpp.
References ArrOfInt::addr(), ecrire_partie(), IntVect::get_md_vector(), IntVect::line_size(), Sortie::put(), ConstIntTab_parts::size(), ArrOfInt::size_array(), sub_type, MD_Vector::valeur(), and write_debog_data_file_.
{
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  if (sub_type(MD_Vector_std, md))
    {
      const int ls = arr.line_size();
      write_debog_data_file_.put(arr.addr(), arr.size_array(), ls);
    }
  else if (sub_type(MD_Vector_composite, md))
    {
// This way, each processor writes each part sequentially
// part1proc1, part1proc2, ... part2proc1, part2proc2, etc...
      ConstIntTab_parts parts(arr);
      const int n = parts.size();
      for (int i = 0; i < n; i++)
        {
          const IntTab& t = parts[i];
          ecrire_partie(t);
        }
    }
}
void Debog_Pb::ecrire_partie (const DoubleVect & arr) [protected]
Definition at line 643 of file Debog.cpp.
References ArrOfDouble::addr(), DoubleVect::get_md_vector(), DoubleVect::line_size(), Sortie::put(), ConstDoubleTab_parts::size(), ArrOfDouble::size_array(), sub_type, MD_Vector::valeur(), and write_debog_data_file_.
Referenced by ecrire_gen(), and ecrire_partie().
{
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  if (sub_type(MD_Vector_std, md))
    {
      const int ls = arr.line_size();
      write_debog_data_file_.put(arr.addr(), arr.size_array(), ls);
    }
  else if (sub_type(MD_Vector_composite, md))
    {
// This way, each processor writes each part sequentially
// part1proc1, part1proc2, ... part2proc1, part2proc2, etc...
      ConstDoubleTab_parts parts(arr);
      const int n = parts.size();
      for (int i = 0; i < n; i++)
        {
          const DoubleTab& t = parts[i];
          ecrire_partie(t);
        }
    }
}
void Debog_Pb::error_function () [protected]
methode appelee des qu'une erreur est trouvee dans l'espace reel.
(utile pour poser un breakpoint dans gdb)
Definition at line 68 of file Debog.cpp.
References Cerr, Process::exit(), exit_on_error_, and finl.
Referenced by verifier(), and verifier_partie_std().
{
  if (exit_on_error_)
    {
      Cerr << "Error found in Debog_Pb (see debog.log files)" << finl;
      exit();
    }
}
const IntVect & Debog_Pb::find_renum_vector (const MD_Vector & mdv, Nom & id) const [protected]
Definition at line 447 of file Debog.cpp.
References IntVect::get_md_vector(), renum_array_, RENUM_ARRAY_NOT_FOUND, renum_id_, and vect_impl::size().
Referenced by verifier_matrice(), and verifier_partie_std().
{
  const int n = renum_array_.size();
  for (int i = 0; i < n; i++)
    {
      const IntVect& renum = renum_array_[i];
      if (renum.get_md_vector() == mdv)
        {
          id = renum_id_[i];
          return renum;
        }
    }
  throw RENUM_ARRAY_NOT_FOUND;
}
static Ref_Debog_Pb& Debog_Pb::get_debog_instance () [inline, static]
Definition at line 53 of file Debog_Pb.h.
References instance_debog_.
Referenced by Debog::active(), Debog::set_nom_pb_actuel(), Debog::verifier(), Debog::verifier_getref(), and Debog::verifier_Mat_elems().
  {
    return instance_debog_;
  }
const Type_info * Debog_Pb::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 77 of file Debog.cpp.
void Debog_Pb::goto_msg (const char *const msg) [protected]
< copie sans les espaces avant/apres
Definition at line 214 of file Debog.cpp.
References Cerr, debog_data_file_, debog_msg_count_, Nom::debute_par(), detailed_log_file_, Process::exit(), Nom::finit_par(), finl, Process::je_suis_maitre(), log_file_, mode_db_, Nom::prefix(), and Nom::suffix().
Referenced by verifier(), and verifier_gen().
{
  assert(mode_db_==1);
  Nom dummy;
  Nom n;
  int num;
  Nom msg(message); //!< copie sans les espaces avant/apres
  while (msg.debute_par(" "))
    msg.suffix(" ");
  while (msg.finit_par(" "))
    msg.prefix(" ");
  while(1)
    {
// read until we find a "msg" word:
      do
        {
          debog_data_file_ >> dummy;
        }
      while (dummy != "msg");
      debog_data_file_ >> dummy;
      if (dummy != ":")
        {
          Cerr << "Error in Debog_Pb::goto_msg(" << msg << ")\n invalid data in DEBOG file" << finl;
          exit();
        }
      num = -1;
      debog_data_file_ >> num;
      debog_data_file_ >> dummy;
      if (dummy != ":")
        {
          Cerr << "Error in Debog_Pb::goto_msg(" << msg << ")\n invalid data in DEBOG file" << finl;
          exit();
        }
      n = "";
      while(1)
        {
          debog_data_file_ >> dummy;
          if (dummy == "FinMsg")
            break;
          n += dummy;
          n += " ";
        }
      if (n.debute_par(msg))
        break;
      if (Process::je_suis_maitre())
        {
          log_file_ << "Skipping message " << n << " (looking for " << msg << ")" << finl;
        }
    }
  if (Process::je_suis_maitre())
    {
      log_file_ << "Reading message " << num << "(file) "
                << debog_msg_count_ << "(current) " << msg << finl;
    }
  detailed_log_file_ << "Reading message " << num << "(file) "
                     << debog_msg_count_ << "(current) " << msg << finl;
}
const Type_info * Debog_Pb::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 77 of file Debog.cpp.
Sortie & Debog_Pb::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 130 of file Debog.cpp.
References Process::exit().
{
  exit();
  return os;
}
void Debog_Pb::read_geometry_data () [protected]
< sommets
< centres des elements Il faut passer dans un groupe monoprocesseur pour Domaine::readOn:
< Liste de 1 processeur contenant le proc 0
< non utilise
< non utilise
Definition at line 361 of file Debog.cpp.
References add_renum_item(), Elem_geom_base::calculer_centres_gravite(), Domaine::coord_sommets(), PE_Groups::create_group(), DERIV, Probleme_base::domaine(), Probleme_base::domaine_dis(), PE_Groups::enter_group(), envoyer_broadcast(), Entree::ERROR_EXCEPTION, PE_Groups::exit_group(), fichier_domaine_, fichier_faces_, IntVect::get_md_vector(), DoubleVect::get_md_vector(), Process::je_suis_maitre(), Zone::les_elems(), Zone_VF::md_vector_aretes(), Zone_VF::md_vector_faces(), Entree_Fichier_base::precision(), ref_cast, ref_pb_, Entree::set_error_action(), DoubleTab::set_md_vector(), Deriv_Zone_dis_base::valeur(), Ref_Probleme_base::valeur(), Zone_VF::xa(), Zone_VF::xp(), Zone_VF::xv(), Domaine::zone(), and Domaine_dis::zone_dis().
Referenced by readOn().
{
  const Domaine& dom = ref_pb_.valeur().domaine();
  const Zone_dis_base& zd = ref_pb_.valeur().domaine_dis().zone_dis(0).valeur();
  const Zone_VF& zvf = ref_cast(Zone_VF, zd);
  {
    DoubleTab coord_som_seq; //!< sommets
    DoubleTab xp_seq; //!< centres des elements Il faut passer dans un groupe monoprocesseur pour Domaine::readOn:
//
    {
      DERIV(Comm_Group) group;
      ArrOfInt liste_procs(1); //!< Liste de 1 processeur contenant le proc 0
      PE_Groups::create_group(liste_procs, group, 1);
      if (PE_Groups::enter_group(group.valeur()))
        {
          EFichier f(fichier_domaine_);
          Domaine dom_seq;
          f >> dom_seq;
          coord_som_seq = dom_seq.coord_sommets();
          const Elem_geom_base& elem = dom_seq.zone(0).type_elem().valeur();
          elem.calculer_centres_gravite(xp_seq);
          PE_Groups::exit_group();
        }
    }
// Tous les processeurs recoivent les coordonnees des sommets de reference
// (detruire le descripteur sinon printOn refuse d'envoyer le vecteur)
    coord_som_seq.set_md_vector(MD_Vector());
    envoyer_broadcast(coord_som_seq, 0);
// Idem avec les centres des elements
    xp_seq.set_md_vector(MD_Vector());
    envoyer_broadcast(xp_seq, 0);
// Calculer les renumerotations:
    const DoubleTab& coord_som = dom.coord_sommets();
    const MD_Vector& md_som = dom.coord_sommets().get_md_vector();
    add_renum_item(coord_som_seq, coord_som, md_som, "SOM");
    const DoubleTab& xp = zvf.xp();
// Le tableau xp n'a pas de structure parallele, on la prend dans les elements...
    const MD_Vector& md_elem = dom.zone(0).les_elems().get_md_vector();
    add_renum_item(xp_seq, xp, md_elem, "ELEM");
  }
  {
    DoubleTab xv_seq;
    DoubleTab xa_seq;
    int avec_aretes = 1;
    if (Process::je_suis_maitre())
      {
        EFichier f(fichier_faces_);
        f.precision(20);
        {
          IntTab elem_faces;
          f >> elem_faces; //!< non utilise
        }
        f >> xv_seq;
        {
          IntTab face_voisins;
          f >> face_voisins; //!< non utilise
        }
        f.set_error_action(Entree::ERROR_EXCEPTION);
        try
          {
            f >> xa_seq;
          }
        catch (Entree_Sortie_Error)
          {
            avec_aretes = 0;
          }
      }
    envoyer_broadcast(xv_seq, 0);
    const DoubleTab& xv = zvf.xv();
    const MD_Vector& md_face = zvf.md_vector_faces();
    add_renum_item(xv_seq, xv, md_face, "FACE");
    envoyer_broadcast(avec_aretes, 0);
    if (avec_aretes)
      {
        envoyer_broadcast(xa_seq, 0);
        const DoubleTab& xa = zvf.xa();
        const MD_Vector& md_arete = zvf.md_vector_aretes();
        add_renum_item(xa_seq, xa, md_arete, "ARETE");
      }
  }
}
Entree & Debog_Pb::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 141 of file Debog.cpp.
References Param::ajouter(), Cerr, debog_data_file_, debog_msg_count_, detailed_log_file_, Param::dictionnaire(), Probleme_base::domaine_dis(), Entree::ERROR_EXIT, Process::exit(), exit_on_error_, fichier_debog_, fichier_domaine_, fichier_faces_, finl, instance_debog_, Process::je_suis_maitre(), Param::lire_avec_accolades(), log_file_, mode_db_, msg_a_ignorer_, nom_pb_, Domaine_dis::nombre_de_zones(), Interprete::objet(), EcrFicCollecte::ouvrir(), Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Objet_U::que_suis_je(), read_geometry_data(), ref_cast, ref_pb_, Param::REQUIRED, Entree::set_error_action(), Sortie_Fichier_base::setf(), seuil_absolu_, seuil_relatif_, sub_type, write_debog_data_file_, and write_geometry_data().
{
  fichier_domaine_ = "dom.debog";
  fichier_faces_ = "faces.debog";
  fichier_debog_ = "DEBOG";
  seuil_relatif_ = 1e-10;
  seuil_absolu_ = 1e-10;
  exit_on_error_ = 0;
  {
    Param param(que_suis_je());
    param.ajouter("nom_pb", &nom_pb_, Param::REQUIRED);
    param.ajouter("fichier_domaine", &fichier_domaine_);
    param.ajouter("fichier_faces", &fichier_faces_);
    param.ajouter("fichier_debog", &fichier_debog_);
    param.ajouter("seuil_absolu", &seuil_absolu_);
    param.ajouter("seuil_relatif", &seuil_relatif_);
    param.ajouter("ignorer_messages", &msg_a_ignorer_);
    param.ajouter("mode_db", &mode_db_, Param::REQUIRED);
    param.dictionnaire("write", 0);
    param.dictionnaire("read", 1);
    param.ajouter("exit_on_error", &exit_on_error_);
    param.lire_avec_accolades(is);
  }
  Objet_U& obj = Interprete::objet(nom_pb_);
  if (!sub_type(Probleme_base, obj))
    {
      Cerr << "Error in Debog::interpreter: " << obj << " is not a Problem_base object" << finl;
      exit();
    }
  Probleme_base& pb = ref_cast(Probleme_base, obj);
  if (pb.domaine_dis().nombre_de_zones() == 0)
    {
      Cerr<<finl;
      Cerr<<"WARNING, problem in Debog"<<finl;
      Cerr<<"It's maybe because you have put"<<finl;
      Cerr<<"the command line Debog before to have associated"<<finl;
      Cerr<<"the discretization to the problem."<<finl;
    }
  ref_pb_ = pb;
  if (mode_db_ == 0)
    {
// Ecriture:
      write_geometry_data();
      write_debog_data_file_.ouvrir(fichier_debog_);
      write_debog_data_file_.setf(ios::scientific);
      write_debog_data_file_.precision(20);
    }
  else
    {
      read_geometry_data();
      debog_data_file_.ouvrir(fichier_debog_);
      debog_data_file_.set_error_action(Entree::ERROR_EXIT);
    }
  if (Process::je_suis_maitre())
    log_file_.ouvrir("debog.log");
  detailed_log_file_.ouvrir("debog_detail.log");
  debog_msg_count_ = 0;
  instance_debog_ = *this;
  return is;
}
void Debog_Pb::register_item (const MD_Vector & md, const Nom & id) [protected]
Definition at line 304 of file Debog.cpp.
References Vect_Nom::add(), Vect_MD_Vector::add(), known_md_, and renum_id_.
Referenced by add_renum_item(), and write_geometry_data().
{
  known_md_.add(md);
  renum_id_.add(id);
}
Debog_Pb & Debog_Pb::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Definition at line 77 of file Debog.cpp.
const Debog_Pb & Debog_Pb::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Definition at line 77 of file Debog.cpp.
void Debog_Pb::set_nom_pb_actuel (const Nom & nom)
Definition at line 565 of file Debog.cpp.
References nom_pb_actuel_.
Referenced by Debog::set_nom_pb_actuel().
{
  nom_pb_actuel_ = nom;
}
unsigned Debog_Pb::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 77 of file Debog.cpp.
int Debog_Pb::test_ignore_msg (const char *const msg) [protected]
Definition at line 209 of file Debog.cpp.
References msg_a_ignorer_, and Motcles::rang().
Referenced by verifier(), and verifier_gen().
{
  return msg_a_ignorer_.rang(msg) >= 0;
}
void Debog_Pb::verifier (const char *const msg, double x, double * refvalue = 0)
Definition at line 462 of file Debog.cpp.
References Cerr, debog_break_test(), debog_data_file_, debog_msg_count_, detailed_log_file_, error_function(), finl, goto_msg(), Process::je_suis_maitre(), log_file_, max(), mode_db_, Process::mp_sum(), nom_pb_, nom_pb_actuel_, seuil_absolu_, seuil_relatif_, test_ignore_msg(), and write_debog_data_file_.
Referenced by Debog::verifier(), Debog::verifier_getref(), and verifier_matrice().
{
  if (nom_pb_ != nom_pb_actuel_)
    return;
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  debog_break_test(debog_msg_count_);
  if (mode_db_ == 0)
    {
// write
      Sortie& os = write_debog_data_file_;
      Cerr << "DEBOG: writing scalar, message " << debog_msg_count_ << " : " << msg << finl;
      os << "msg : " << debog_msg_count_ << " : " << msg << " FinMsg " << finl;
      os << x << finl;
    }
  else
    {
// read and compare
      goto_msg(msg);
      double y;
      debog_data_file_ >> y;
      const double adim = max(fabs(x), fabs(y));
      const double delta = fabs(x-y);
      double err = 0;
      if (delta >= seuil_absolu_ && delta / adim >= seuil_relatif_)
        {
          err = delta;
          detailed_log_file_ << " ECART (double) reference=" << y
                             << " calcul=" << x
                             << " relative error=" << delta
                             << " (adim=" << adim << ")" << finl;
        }
      err = mp_sum(err);
      if (Process::je_suis_maitre())
        {
          const char *ok = (err > 0.) ? " ERROR       " : " OK           ";
          log_file_ << ok << " : comparing double: reference=" << y << " deltamax=" << err << finl;
          if (err > 0.)
            error_function();
        }
      if (ref_value)
        {
          if (Process::je_suis_maitre())
            log_file_ << "                Request reference value" << finl;
          *ref_value = y;
        }
    }
  debog_msg_count_++;
}
void Debog_Pb::verifier (const char *const msg, const DoubleVect & arr, DoubleVect * refvalue = 0)
if arr_ref is not null and if mode_db_ is "read\&compare", we put the reference
value found in the file in arr_ref. arr_ref and arr can point to the same object.
Definition at line 919 of file Debog.cpp.
References debog_break_test(), debog_msg_count_, ecrire_gen(), mode_db_, nom_pb_, nom_pb_actuel_, test_ignore_msg(), and verifier_gen().
{
  if (nom_pb_ != nom_pb_actuel_)
    return;
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  debog_break_test(debog_msg_count_);
  if(mode_db_ == 0)
    {
      ecrire_gen(msg, arr);
    }
  else
    {
      verifier_gen(msg, arr, arr_ref);
    }
  debog_msg_count_++;
}
void Debog_Pb::verifier (const char *const msg, int x, int * refvalue = 0)
Definition at line 516 of file Debog.cpp.
References Cerr, debog_break_test(), debog_data_file_, debog_msg_count_, detailed_log_file_, error_function(), finl, goto_msg(), Process::je_suis_maitre(), log_file_, mode_db_, Process::mp_sum(), nom_pb_, nom_pb_actuel_, test_ignore_msg(), and write_debog_data_file_.
{
  if (nom_pb_ != nom_pb_actuel_)
    return;
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  debog_break_test(debog_msg_count_);
  if (mode_db_ == 0)
    {
// write
      Sortie& os = write_debog_data_file_;
      Cerr << "DEBOG: writing scalar, message " << debog_msg_count_ << " : " << msg << finl;
      os << "msg : " << debog_msg_count_ << " : " << msg << " FinMsg " << finl;
      os << x << finl;
    }
  else
    {
// read and compare
      goto_msg(msg);
      int y;
      debog_data_file_ >> y;
      int err = ((x - y) != 0);
      if (err)
        {
          detailed_log_file_ << " ECART (int) reference=" << y
                             << " calcul=" << x << finl;
        }
      err = mp_sum(err);
      if (Process::je_suis_maitre())
        {
          const char *ok = (err > 0.) ? " ERROR       " : " OK           ";
          log_file_ << ok << " : comparing int: reference=" << y << finl;
          if (err)
            error_function();
        }
      if (ref_value)
        {
          if (Process::je_suis_maitre())
            log_file_ << "                Request reference value" << finl;
          *ref_value = y;
        }
    }
  debog_msg_count_++;
}
void Debog_Pb::verifier (const char *const msg, const IntVect & arr, IntVect * refvalue = 0)
if arr_ref is not null and if mode_db_ is "read\&compare", we put the reference
value found in the file in arr_ref. arr_ref and arr can point to the same object.
Definition at line 1201 of file Debog.cpp.
References debog_break_test(), debog_msg_count_, ecrire_gen(), mode_db_, nom_pb_, nom_pb_actuel_, test_ignore_msg(), and verifier_gen().
{
  if (nom_pb_ != nom_pb_actuel_)
    return;
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  debog_break_test(debog_msg_count_);
  if(mode_db_ == 0)
    {
      ecrire_gen(msg, arr);
    }
  else
    {
      verifier_gen(msg, arr, arr_ref);
    }
  debog_msg_count_++;
}
void Debog_Pb::verifier_gen (const char *const msg, const DoubleVect & arr, DoubleVect * arr_ref = 0) [protected]
Definition at line 879 of file Debog.cpp.
References Cerr, debog_data_file_, detailed_log_file_, Process::exit(), finl, DoubleVect::get_md_vector(), goto_msg(), Process::je_suis_maitre(), DoubleVect::line_size(), log_file_, MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), ArrOfDouble::size_array(), sub_type, test_ignore_msg(), MD_Vector::valeur(), and verifier_partie().
Referenced by verifier().
{
  if (!arr.get_md_vector().non_nul())
    {
      Cerr << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      if (Process::je_suis_maitre())
        log_file_ << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      detailed_log_file_ << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      return;
    }
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  goto_msg(msg);
  if (sub_type(DoubleTab, arr))
    {
// read tab header
      ArrOfInt dims;
      debog_data_file_ >> dims;
    }
  DoubleVect reference;
  debog_data_file_ >> reference;
  const int n = reference.size_array();
  const int nb_items_seq = arr.get_md_vector().valeur().nb_items_seq_tot();
  const int ls = arr.line_size();
  if (n != nb_items_seq * ls)
    {
      Cerr << "Error in Debog_Pb::verifier_gen : wrong sequential size " << n
           << " (expected " << nb_items_seq * ls << ")" << finl;
      exit();
    }
  verifier_partie(reference, arr, arr_ref);
}
void Debog_Pb::verifier_gen (const char *const msg, const IntVect & arr, IntVect * arr_ref = 0) [protected]
Definition at line 1161 of file Debog.cpp.
References Cerr, debog_data_file_, detailed_log_file_, Process::exit(), finl, IntVect::get_md_vector(), goto_msg(), Process::je_suis_maitre(), IntVect::line_size(), log_file_, MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), ArrOfInt::size_array(), sub_type, test_ignore_msg(), MD_Vector::valeur(), and verifier_partie().
{
  if (!arr.get_md_vector().non_nul())
    {
      Cerr << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      if (Process::je_suis_maitre())
        log_file_ << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      detailed_log_file_ << "WARNING in Debog::verifier_gen: array has no parallel metadata. Not checked\n (message: " << msg << ")" << finl;
      return;
    }
  if (test_ignore_msg(msg))
    {
// Ignorer ce test
      return;
    }
  goto_msg(msg);
  if (sub_type(IntTab, arr))
    {
// read tab header
      ArrOfInt dims;
      debog_data_file_ >> dims;
    }
  IntVect reference;
  debog_data_file_ >> reference;
  const int n = reference.size_array();
  const int nb_items_seq = arr.get_md_vector().valeur().nb_items_seq_tot();
  const int ls = arr.line_size();
  if (n != nb_items_seq * ls)
    {
      Cerr << "Error in Debog_Pb::verifier_gen : wrong sequential size " << n
           << " (expected " << nb_items_seq * ls << ")" << finl;
      exit();
    }
  verifier_partie(reference, arr, arr_ref);
}
void Debog_Pb::verifier_Mat_elems (const char *const msg, const Matrice_Base & la_matrice)
Definition at line 1296 of file Debog.cpp.
References Cerr, Process::exit(), finl, known_md_, renum_id_, vect_impl::size(), and verifier_matrice().
Referenced by Debog::verifier_Mat_elems().
{
// Cherche le md_vecteur des elements
  const int n = renum_id_.size();
  int i;
  for (i = 0; i < n; i++)
    {
      if (renum_id_[i] == "ELEM")
        break;
    }
  if (i == n)
    {
      Cerr << "Error in Debog_Pb::verifier_Mat_elems no registered MD_Vector for ELEM type" << finl;
      exit();
    }
  const MD_Vector& md = known_md_[i];
  verifier_matrice(msg, la_matrice, md, md);
}
void Debog_Pb::verifier_matrice (const char *const msg, const Matrice_Base & matrice, const MD_Vector & md_lignes, const MD_Vector & md_colonnes)
md_lignes: descripteur des indices de lignes (cad descripteur du vecteur b dans A*x=b)
mb_colonnes: idem, indices colonnes (cad descripteur du vecteur x dans A*x=b)
Definition at line 1241 of file Debog.cpp.
References creer_tableau_distribue(), find_renum_vector(), mode_db_, Matrice_Base::multvect(), MD_Vector_base::nb_items_seq_tot(), IntVect::size_totale(), sz, MD_Vector::valeur(), and verifier().
Referenced by verifier_Mat_elems().
{
// Attention: cette implementation ne marche que pour les types md_colonnes enregistres dans renum_array_
// (cad types simples sommets, elements, faces, aretes, et pas les MD_Vector_composite)
// et uniquement pour linesize==1 (une ligne et une colonne de la matrice par item)
// Pour chaque colonne i de la matrice, ecriture du produit matrice * vecteur_i
// avec vecteur_i[j] = (i==j);
  DoubleVect vecteur_i;
  DoubleVect tmp;
  MD_Vector_tools::creer_tableau_distribue(md_colonnes, vecteur_i);
  MD_Vector_tools::creer_tableau_distribue(md_lignes, tmp);
  Nom id;
// Boucle sur les items sequentiels du vecteur x de A*x=b
  const int nb_colonnes = md_colonnes.valeur().nb_items_seq_tot();
  for (int i = 0; i < nb_colonnes; i++)
    {
      int renum_i;
      if (mode_db_ == 0)
        {
          renum_i = i;
        }
      else
        {
// Recherche l'indice local correspondant a l'indice sequentiel i
// Si i est un item virtuel on le prend quand meme: vecteur_i aura son espace virtuel a jour
// Si i n'existe pas sur ce processeur, on met -1
          renum_i = -1;
// Renum_colonnes[j] est l'indice dans le vecteur de reference sequentiel de l'item j sur ce processeur
          const IntVect& renum_colonnes = find_renum_vector(md_colonnes, id);
          const int sz = renum_colonnes.size_totale();
          for (int j = 0; j < sz; j++)
            {
              if (renum_colonnes[j] == i)
                {
                  renum_i = j;
                  break;
                }
            }
        }
      if (renum_i >= 0)
        vecteur_i[renum_i] = 1.;
      matrice.multvect(vecteur_i, tmp);
      Nom msg2(msg);
      msg2 += " produit avec base ";
      msg2 += Nom(i);
      verifier(msg2, tmp);
      if (renum_i >= 0)
        vecteur_i[renum_i] = 0.;
    }
}
void Debog_Pb::verifier_partie (const IntVect & reference, const IntVect & arr, IntVect * arr_ref = 0) [protected]
Definition at line 1125 of file Debog.cpp.
References IntVect::get_md_vector(), IntVect::line_size(), MD_Vector_base::nb_items_seq_tot(), IntTab::ref_array(), ref_cast_non_const, ConstIntTab_parts::size(), sub_type, MD_Vector::valeur(), verifier_partie(), and verifier_partie_std().
{
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  if (sub_type(MD_Vector_std, md))
    {
      verifier_partie_std(reference, arr, arr_ref);
    }
  else if (sub_type(MD_Vector_composite, md))
    {
// This way, each processor writes each part sequentially
// part1proc1, part1proc2, ... part2proc1, part2proc2, etc...
      ConstIntTab_parts parts(arr);
      IntTab ref_part;
      const int n = parts.size();
      int index = 0;
      for (int i = 0; i < n; i++)
        {
// Construction de la sous-partie de reference:
// (le tableau de reference contient toutes les valeurs sequentielles, sous-partie
// par sous-partie, la taille de la sous-partie est egale au nombre total
// d'items sequentiels multiplie par le linesize de la sous-partie)
// Attention, toutes les sous-parties n'ont pas forcement la meme linesize
          const IntTab& part = parts[i];
          const int sequential_size = part.get_md_vector().valeur().nb_items_seq_tot();
          const int line_size = part.line_size();
// ref_array() veut un tableau non const, mais on va l'utiliser uniquement en const...
          ArrOfInt& cast_array = ref_cast_non_const(ArrOfInt, reference);
          ref_part.ref_array(cast_array, index, sequential_size * line_size);
// Appel recursif pour la sous-partie:
          verifier_partie(ref_part, part, arr_ref);
          index += sequential_size * line_size;
        }
    }
}
void Debog_Pb::verifier_partie (const DoubleVect & reference, const DoubleVect & arr, DoubleVect * arr_ref = 0) [protected]
Definition at line 843 of file Debog.cpp.
References DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector_base::nb_items_seq_tot(), DoubleTab::ref_array(), ref_cast_non_const, ConstDoubleTab_parts::size(), sub_type, MD_Vector::valeur(), and verifier_partie_std().
Referenced by verifier_gen(), and verifier_partie().
{
  const MD_Vector_base& md = arr.get_md_vector().valeur();
  if (sub_type(MD_Vector_std, md))
    {
      verifier_partie_std(reference, arr, arr_ref);
    }
  else if (sub_type(MD_Vector_composite, md))
    {
// This way, each processor writes each part sequentially
// part1proc1, part1proc2, ... part2proc1, part2proc2, etc...
      ConstDoubleTab_parts parts(arr);
      DoubleTab ref_part;
      const int n = parts.size();
      int index = 0;
      for (int i = 0; i < n; i++)
        {
// Construction de la sous-partie de reference:
// (le tableau de reference contient toutes les valeurs sequentielles, sous-partie
// par sous-partie, la taille de la sous-partie est egale au nombre total
// d'items sequentiels multiplie par le linesize de la sous-partie)
// Attention, toutes les sous-parties n'ont pas forcement la meme linesize
          const DoubleTab& part = parts[i];
          const int sequential_size = part.get_md_vector().valeur().nb_items_seq_tot();
          const int line_size = part.line_size();
// ref_array() veut un tableau non const, mais on va l'utiliser uniquement en const...
          ArrOfDouble& cast_array = ref_cast_non_const(ArrOfDouble, reference);
          ref_part.ref_array(cast_array, index, sequential_size * line_size);
// Appel recursif pour la sous-partie:
          verifier_partie(ref_part, part, arr_ref);
          index += sequential_size * line_size;
        }
    }
}
void Debog_Pb::verifier_partie_std (const DoubleVect & reference, const DoubleVect & arr, DoubleVect * arr_ref = 0) [protected]
< indice dans "arr"
< indice dans "reference"
< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
< indice dans "arr"
< indice dans "reference"
< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
Definition at line 705 of file Debog.cpp.
References ArrOfDouble::addr(), Cerr, detailed_log_file_, DMAXFLOAT, error_function(), Process::exit(), find_renum_vector(), finl, DoubleVect::get_md_vector(), Process::je_suis_maitre(), DoubleVect::line_size(), local_max_abs_vect(), log_file_, max(), message(), Process::mp_max(), mp_max_abs_vect(), seuil_absolu_, seuil_relatif_, IntVect::size(), IntVect::size_totale(), and VECT_REAL_ITEMS.
Referenced by verifier_partie().
{
  Nom identificateur;
// Recherche du descripteur du tableau arr parmi les descripteurs connus
  const IntVect& renum = find_renum_vector(arr.get_md_vector(), identificateur);
// Calcul d'une valeur de reference pour adimensionnaliser:
// Le tableau reference est sequentiel: tous les processeurs ont le meme
  const double adim1 = local_max_abs_vect(reference);
// Le tableau arr est parallele. On calcule la reference en utilisant uniquement
// la partie reele (eventuellement la partie virtuelle a le droit de ne pas etre a jour)
  const double adim2 = mp_max_abs_vect(arr, VECT_REAL_ITEMS);
  const double adim = max(adim1, adim2);
  if (seuil_absolu_ <= 0.)
    {
      Cerr << "Error in Debog.cpp verifier_partie_std: seuil_absolu <= 0" << finl;
      Process::exit();
    }
  if (adim < seuil_absolu_)
    {
// Toutes les valeurs sont inferieures au seuil absolu => ok
      if (Process::je_suis_maitre())
        {
          log_file_ << " OK            : All values below seuil_absolu_ ("
                    << seuil_absolu_ << ") id=" << identificateur << finl;
          detailed_log_file_ << " OK            : All values below seuil_absolu_ ("
                             << seuil_absolu_ << ") id=" << identificateur << finl;
        }
      return;
    }
  const int ls = arr.line_size();
  int i = 0;
  double max_err_items_reels = 0;
  double max_err_items_virt = 0;
  int outbounds = 0;
// items reels, puis items virtuels
  for (int step = 0; step < 2; step++)
    {
      int n;
      const char * message;
      if (step == 0)
        {
          n = renum.size();
          message = " (item reel)";
        }
      else
        {
          n = renum.size_totale();
          message = " (item virtuel)";
        }
      double max_err = 0;
      const double *arr_ptr = arr.addr();
      for (; i < n; i++)
        {
          const int i1 = i * ls; //!< indice dans "arr"
          const int i2 = renum[i] * ls; //!< indice dans "reference"
          for (int j = 0; j < ls; j++)
            {
              const double x = arr_ptr[i1+j]; //!< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
              const double y = reference[i2+j];
// Comparaison de x et y
              const double delta = fabs(x-y) / adim;
              max_err = max(max_err, delta);
// pour les items reels, indiquer si on est hors bornes:
              if (step==0 && !(x>=-DMAXFLOAT && x<=DMAXFLOAT))
                outbounds = 1;
              if (delta > seuil_relatif_)
                {
                  detailed_log_file_ << " ECART reference[" << i2+j << "]=" << y
                                     << " calcul[" << i1+j << "]=" << x;
                  detailed_log_file_ << " relative error=" << delta
                                     << " (adim=" << adim << ")" << message << finl;
                }
            }
        }
      max_err = Process::mp_max(max_err);
      if (step == 0)
        max_err_items_reels = max_err;
      else
        max_err_items_virt = max_err;
    }
  const char * resu = 0;
  int call_error_function = 0;
  double seuil = seuil_relatif_;
  if (max_err_items_reels <= seuil)
    {
      if (max_err_items_virt <= seuil)
        resu = "OK           ";
      else
        resu = "OK REAL ONLY ";
    }
  else
    {
      call_error_function = 1;
      if (!outbounds)
        resu = "ERROR        ";
      else
        resu = "ERROR(DMAXFLT)";
    }
  if (Process::je_suis_maitre())
    {
      log_file_ << " " << resu << " : Max relative error " << max_err_items_reels
                << " (max ref value=" << adim << ") id=" << identificateur << finl;
    }
  detailed_log_file_ << " " << resu << " : Max relative error " << max_err_items_reels
                     << " (max ref value=" << adim << ") id=" << identificateur << finl;
  if (call_error_function)
    error_function();
  if (arr_reference)
    {
      DoubleVect& arr_ref = *arr_reference;
      if (arr_ref.line_size() != ls || !(arr_ref.get_md_vector() == arr.get_md_vector()))
        {
          Cerr << "Error in Debog_Pb::verifier_partie_std: the array provided to store the reference value\n"
               << " does not have the same size/descriptor as the source array" << finl;
          Process::exit();
        }
      if (Process::je_suis_maitre())
        log_file_ << "                 Return reference value (including virtual items)" << finl;
      const int n = renum.size_totale();
      double *arr_ptr = arr_ref.addr();
      for (int ibis = 0; ibis < n; ibis++)
        {
          const int i1 = ibis * ls; //!< indice dans "arr"
          const int i2 = renum[ibis] * ls; //!< indice dans "reference"
          for (int j = 0; j < ls; j++)
            {
              const double y = reference[i2+j];
              arr_ptr[i1+j] = y; //!< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
            }
        }
    }
}
void Debog_Pb::verifier_partie_std (const IntVect & reference, const IntVect & arr, IntVect * arr_ref = 0) [protected]
< indice dans "arr"
< indice dans "reference"
< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
< indice dans "arr"
< indice dans "reference"
< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
Definition at line 1018 of file Debog.cpp.
References ArrOfInt::addr(), Cerr, detailed_log_file_, error_function(), Process::exit(), find_renum_vector(), finl, IntVect::get_md_vector(), Process::je_suis_maitre(), IntVect::line_size(), log_file_, message(), Process::mp_max(), IntVect::size(), and IntVect::size_totale().
{
  Nom identificateur;
// Recherche du descripteur du tableau arr parmi les descripteurs connus
  const IntVect& renum = find_renum_vector(arr.get_md_vector(), identificateur);
  const int ls = arr.line_size();
  int i = 0;
  int max_err_items_reels = 0;
  int max_err_items_virt = 0;
  int outbounds = 0;
// items reels, puis items virtuels
  for (int step = 0; step < 2; step++)
    {
      int n;
      const char * message;
      if (step == 0)
        {
          n = renum.size();
          message = " (item reel)";
        }
      else
        {
          n = renum.size_totale();
          message = " (item virtuel)";
        }
      int max_err = 0;
      const int *arr_ptr = arr.addr();
      for (; i < n; i++)
        {
          const int i1 = i * ls; //!< indice dans "arr"
          const int i2 = renum[i] * ls; //!< indice dans "reference"
          for (int j = 0; j < ls; j++)
            {
              const int x = arr_ptr[i1+j]; //!< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
              const int y = reference[i2+j];
// Comparaison de x et y
// For integers, values must match exactly !
              if (x != y)
                {
                  detailed_log_file_ << " ECART reference[" << i2+j << "]=" << y
                                     << " calcul[" << i1+j << "]=" << x << message << finl;
                  max_err = 1;
                }
            }
        }
      max_err = ::mp_max(max_err);
      if (step == 0)
        max_err_items_reels = max_err;
      else
        max_err_items_virt = max_err;
    }
  const char * resu = 0;
  int call_error_function = 0;
  int seuil = 0;
  if (max_err_items_reels <= seuil)
    {
      if (max_err_items_virt <= seuil)
        resu = "OK           ";
      else
        resu = "OK REAL ONLY ";
    }
  else
    {
      call_error_function = 1;
      if (!outbounds)
        resu = "ERROR        ";
      else
        resu = "ERROR(DMAXFLT)";
    }
  if (Process::je_suis_maitre())
    {
      log_file_ << " " << resu << " : integer field " << identificateur << finl;
    }
  detailed_log_file_ << " " << resu << " : integer field " << identificateur << finl;
  if (call_error_function)
    error_function();
  if (arr_reference)
    {
      IntVect& arr_ref = *arr_reference;
      if (arr_ref.line_size() != ls || !(arr_ref.get_md_vector() == arr.get_md_vector()))
        {
          Cerr << "Error in Debog_Pb::verifier_partie_std: the array provided to store the reference value\n"
               << " does not have the same size/descriptor as the source array" << finl;
          Process::exit();
        }
      if (Process::je_suis_maitre())
        log_file_ << "                 Return reference value (including virtual items)" << finl;
      const int n = renum.size_totale();
      int *arr_ptr = arr_ref.addr();
      for (int ibis = 0; ibis < n; ibis++)
        {
          const int i1 = ibis * ls; //!< indice dans "arr"
          const int i2 = renum[ibis] * ls; //!< indice dans "reference"
          for (int j = 0; j < ls; j++)
            {
              const int y = reference[i2+j];
              arr_ptr[i1+j] = y; //!< ne pas passer par operator[] pour ne pas planter sur DMAXFLOAT
            }
        }
    }
}
void Debog_Pb::write_geometry_data () [protected]
Definition at line 273 of file Debog.cpp.
References Cerr, Probleme_base::domaine(), Probleme_base::domaine_dis(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), fichier_domaine_, fichier_faces_, finl, Zone_VF::md_vector_aretes(), Zone::md_vector_elements(), Zone_VF::md_vector_faces(), Domaine::md_vector_sommets(), MD_Vector::non_nul(), Process::nproc(), Sortie_Fichier_base::precision(), ref_cast, ref_pb_, register_item(), Deriv_Zone_dis_base::valeur(), Ref_Probleme_base::valeur(), Zone_VF::xa(), Zone_VF::xv(), Domaine::zone(), and Domaine_dis::zone_dis().
Referenced by readOn().
{
  if (Process::nproc() > 1)
    {
      Cerr << "Error in Debog.cpp: cannot write geometry data in parallel." << finl;
      Process::exit();
    }
  const Domaine& dom = ref_pb_.valeur().domaine();
  const Zone_dis_base& zd = ref_pb_.valeur().domaine_dis().zone_dis(0).valeur();
  const Zone_VF& zvf = ref_cast(Zone_VF, zd);
  {
    SFichier f(fichier_domaine_);
    f.precision(20);
    f << dom;
  }
  {
    SFichier f(fichier_faces_);
    f.precision(20);
    f << zvf.elem_faces();
    f << zvf.xv();
    f << zvf.face_voisins();
    if (zvf.xa().dimension(0) > 0)
      f << zvf.xa();
  }
  register_item(dom.md_vector_sommets(), "SOM");
  register_item(dom.zone(0).md_vector_elements(), "ELEM");
  register_item(zvf.md_vector_faces(), "FACE");
  if (zvf.md_vector_aretes().non_nul())
    register_item(zvf.md_vector_aretes(), "ARETES");
}
Member Data Documentation
EFichier Debog_Pb::debog_data_file_ [protected]
Definition at line 113 of file Debog_Pb.h.
Referenced by goto_msg(), readOn(), verifier(), and verifier_gen().
int Debog_Pb::debog_msg_count_ [protected]
Definition at line 84 of file Debog_Pb.h.
Referenced by ecrire_gen(), goto_msg(), readOn(), and verifier().
EcrFicCollecte Debog_Pb::detailed_log_file_ [protected]
Definition at line 117 of file Debog_Pb.h.
Referenced by goto_msg(), readOn(), verifier(), verifier_gen(), and verifier_partie_std().
int Debog_Pb::exit_on_error_ [protected]
Definition at line 97 of file Debog_Pb.h.
Referenced by error_function(), and readOn().
Nom Debog_Pb::fichier_debog_ [protected]
fichier contenant les valeurs a relire
Definition at line 89 of file Debog_Pb.h.
Referenced by readOn().
Nom Debog_Pb::fichier_domaine_ [protected]
Definition at line 87 of file Debog_Pb.h.
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
Nom Debog_Pb::fichier_faces_ [protected]
Definition at line 88 of file Debog_Pb.h.
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
const Type_info Debog_Pb::info_obj [static]
Reimplemented from Objet_U.
Definition at line 42 of file Debog_Pb.h.
Ref_Debog_Pb Debog_Pb::instance_debog_ [static, protected]
Definition at line 121 of file Debog_Pb.h.
Referenced by get_debog_instance(), and readOn().
Vect_MD_Vector Debog_Pb::known_md_ [protected]
Definition at line 101 of file Debog_Pb.h.
Referenced by register_item(), and verifier_Mat_elems().
SFichier Debog_Pb::log_file_ [protected]
Definition at line 115 of file Debog_Pb.h.
Referenced by goto_msg(), readOn(), verifier(), verifier_gen(), and verifier_partie_std().
int Debog_Pb::mode_db_ [protected]
Definition at line 95 of file Debog_Pb.h.
Referenced by goto_msg(), readOn(), verifier(), and verifier_matrice().
Motcles Debog_Pb::msg_a_ignorer_ [protected]
Definition at line 93 of file Debog_Pb.h.
Referenced by readOn(), and test_ignore_msg().
Nom Debog_Pb::nom_pb_ [protected]
Definition at line 85 of file Debog_Pb.h.
Referenced by readOn(), and verifier().
Nom Debog_Pb::nom_pb_actuel_ [protected]
Definition at line 119 of file Debog_Pb.h.
Referenced by set_nom_pb_actuel(), and verifier().
Ref_Probleme_base Debog_Pb::ref_pb_ [protected]
Definition at line 86 of file Debog_Pb.h.
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
Vect_IntVect Debog_Pb::renum_array_ [protected]
Definition at line 108 of file Debog_Pb.h.
Referenced by add_renum_item(), and find_renum_vector().
Noms Debog_Pb::renum_id_ [protected]
Definition at line 103 of file Debog_Pb.h.
Referenced by find_renum_vector(), register_item(), and verifier_Mat_elems().
double Debog_Pb::seuil_absolu_ [protected]
Definition at line 90 of file Debog_Pb.h.
Referenced by readOn(), verifier(), and verifier_partie_std().
double Debog_Pb::seuil_relatif_ [protected]
Definition at line 91 of file Debog_Pb.h.
Referenced by readOn(), verifier(), and verifier_partie_std().
SFichier Debog_Pb::write_debog_data_file_ [protected]
Definition at line 111 of file Debog_Pb.h.
Referenced by ecrire_gen(), ecrire_partie(), readOn(), and verifier().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Debog_Pb.h
src/Kernel/Framework/Debog.cpp