TRUST: Fluide_Weakly_Compressible Class Reference
Fluide_Weakly_Compressible Class Reference
classe Fluide_Weakly_Compressible
Cette classe represente un d'un fluide faiblement compressible
c'est a dire heritant de Fluide_Dilatable_base
#include <Fluide_Weakly_Compressible.h>
Public Member Functions
~Fluide_Weakly_Compressible ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Weakly_Compressible ()
void set_param (Param &param) override
void completer (const Probleme_base &) override
Complete le fluide avec les champs inconnus associes au probleme.
void preparer_pas_temps () override
Prepare le pas de temps.
void prepare_pressure_edo () override
void write_mean_edo (double) override
void checkTraitementPth (const Zone_Cl_dis &) override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void abortTimeStep () override
void calculer_pression_tot () override
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
void update_pressure_fields (double) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
const Champ_Don & pression_hydro () const
Champ_Don & pression_hydro ()
const Champ_Don & pression_eos () const
Champ_Don & pression_eos ()
const Champ_Don & fraction_massique_nonresolue () const
Champ_Don & fraction_massique_nonresolue ()
const DoubleTab & pression_th_tab () const
Tab Pression thermodynamique.
DoubleTab & pression_th_tab ()
Tab Pression thermodynamique.
const DoubleTab & pression_thn_tab () const
Tab Pression thermodynamique a l'etape precedente.
DoubleTab & pression_thn_tab ()
Tab Pression thermodynamique a l'etape precedente.
void secmembre_divU_Z (DoubleTab &tab_W) const override
void set_pression_th_tab (DoubleTab &Pth_tab)
void set_resume_flag ()
bool use_total_pressure ()
bool use_hydrostatic_pressure ()
bool use_pth_xyz ()
bool use_total_hydro_pressure ()
bool use_saved_data ()
bool use_grad_pression_eos ()
Public Member Functions inherited from Fluide_Dilatable_base
~Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Dilatable_base ()
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
void set_Cp (double)
Complete le fluide avec un Cp constant.
void update_rho_cp (double temps) override
void creer_champs_non_lus () override
void initialiser_radiatives (const double temps)
void warn_syntax_Sutherland ()
int initialiser (const double temps) override
Initialise les parametres du fluide.
const DoubleTab & temperature () const
Renvoie le tableau des valeurs de le temperature.
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
Champ_Don & ch_temperature ()
virtual void calculer_pression_tot ()
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
virtual void preparer_pas_temps ()
Prepare le pas de temps.
void abortTimeStep () override
void set_param (Param &param) override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void mettre_a_jour (double) override
virtual void update_pressure_fields (double)
void preparer_calcul () override
Prepare le fluide au calcul.
virtual void completer (const Probleme_base &)
Complete le fluide avec les champs inconnus associes au probleme.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void checkTraitementPth (const Zone_Cl_dis &)=0
virtual void prepare_pressure_edo ()=0
virtual void write_mean_edo (double)=0
virtual void secmembre_divU_Z (DoubleTab &) const =0
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Nom type_fluide () const
const Loi_Etat & loi_etat () const
Loi_Etat & loi_etat ()
const Champ_Inc & inco_chaleur () const
Champ_Inc & inco_chaleur ()
const Champ_Inc & vitesse () const
const Champ_Don & pression_tot () const
Champ_Don & pression_tot ()
const Champ_Don & mu_sur_Schmidt () const
Champ_Don & mu_sur_Schmidt ()
const Champ_Don & nu_sur_Schmidt () const
Champ_Don & nu_sur_Schmidt ()
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
void calculer_coeff_T ()
void initialiser_inco_ch ()
void calculer_Cp ()
void calculer_lambda ()
void calculer_mu ()
void calculer_nu () override
void calculer_alpha () override
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void calculer_mu_sur_Sc ()
void calculer_nu_sur_Sc ()
void calculer_masse_volumique ()
void set_pression_th (double Pth)
int getTraitementPth () const
double pression_th () const
Pression thermodynamique.
double pression_thn () const
Pression thermodynamique a l'etape precedente.
double pression_th1 () const
Pression thermodynamique calculee pour conserver la masse.
double calculer_H (double hh) const
Probleme_base & get_problem ()
const DoubleTab & rho_discvit () const
const DoubleTab & rho_face_n () const
const DoubleTab & rho_face_np1 () const
void calculer_rho_face (const DoubleTab &tab_rho)
void divu_discvit (DoubleTab &secmem1, DoubleTab &secmem2)
double moyenne_vol (const DoubleTab &A) const
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_Weakly_Compressible & self_cast (Objet_U &)
static const Fluide_Weakly_Compressible & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_Dilatable_base
static const Type_info * info ()
static Fluide_Dilatable_base & self_cast (Objet_U &)
static const Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_Dilatable_base
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void mettre_a_jour_bis ()
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
virtual void remplir_champ_pression_tot (int n, const DoubleTab &PHydro, DoubleTab &PTot)=0
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don Pth_xyz_
Champ_Don pression_hydro_
Champ_Don pression_eos_
Champ_Don unsolved_species_
DoubleTab Pth_tab_
DoubleTab Pth_n_tab_
DoubleTab P_NS_
int use_total_pressure_
int use_hydrostatic_pressure_
int use_grad_pression_eos_
int sim_resumed_
double time_activate_ptot_
Protected Attributes inherited from Fluide_Dilatable_base
int traitement_PTh
flag pour le traitement de la pression thermo
double Pth_
double Pth_n
double Pth1
Ref_Champ_Inc inco_chaleur_
Ref_Champ_Inc vitesse_
Ref_Champ_Inc pression_
Ref_Probleme_base le_probleme_
Champ_Don pression_tot_
Champ_Don mu_sur_Sc
Champ_Don nu_sur_Sc
Champ_Don rho_gaz
Champ_Don rho_comme_v
Loi_Etat loi_etat_
EOS_Tools eos_tools_
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Private Member Functions
void calculer_pression_hydro ()
Calcule la pression hydrostatique = rho*g*z.
void initialiser_pth ()
void initialiser_pth_xyz (const Probleme_base &pb)
void initialiser_pth_for_EOS (const Probleme_base &pb)
void remplir_champ_pression_tot (int n, const DoubleTab &PHydro, DoubleTab &PTot) override
void remplir_champ_pression_for_EOS ()
Calcule la pression utilisee dans les lois d'etat WC.
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Detailed Description
classe Fluide_Weakly_Compressible
Cette classe represente un d'un fluide faiblement compressible
c'est a dire heritant de Fluide_Dilatable_base
Definition at line 33 of file Fluide_Weakly_Compressible.h.
Constructor & Destructor Documentation
~Fluide_Weakly_Compressible()
Fluide_Weakly_Compressible::~Fluide_Weakly_Compressible ()
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
Fluide_Weakly_Compressible()
Fluide_Weakly_Compressible::Fluide_Weakly_Compressible ()
Definition at line 36 of file Fluide_Weakly_Compressible.cpp.
                                                       : use_total_pressure_(0), use_hydrostatic_pressure_(0),
  use_grad_pression_eos_(1), sim_resumed_(0), time_activate_ptot_(-1.) {}
Member Function Documentation
abortTimeStep()
void Fluide_Weakly_Compressible::abortTimeStep () override virtual
Reimplemented from Fluide_Dilatable_base.
Definition at line 295 of file Fluide_Weakly_Compressible.cpp.
{
  Fluide_Dilatable_base::abortTimeStep();
  Pth_tab_ = Pth_n_tab_;
}
References Fluide_Dilatable_base::abortTimeStep(), Pth_n_tab_, and Pth_tab_.
calculer_pression_hydro()
void Fluide_Weakly_Compressible::calculer_pression_hydro () private
Calcule la pression hydrostatique = rho*g*z.
Definition at line 358 of file Fluide_Weakly_Compressible.cpp.
{
  DoubleTab& tab_Phydro = pression_hydro_.valeurs();
  const Zone_dis_base& zone_dis= pression_-> zone_dis_base();
  const Zone_VF& zone = ref_cast(Zone_VF, zone_dis);
  int is_VDF = zone_dis.que_suis_je() == "Zone_VDF" ? 1 : 0;
  const DoubleTab& centres_de_gravites = is_VDF ? zone.xp() : zone.xv();
  const DoubleTab& tab_rho = rho_np1(), grav = gravite().valeurs();
  const int n = tab_Phydro.dimension_tot(0);
  assert (n ==  tab_rho.dimension_tot(0) && a_gravite());
  for (int i=0 ; i<n ; i++)
    {
      double gz=0.;
      for (int dir=0; dir<dimension; dir++) gz+=centres_de_gravites(i,dir)*grav(0,dir);
      tab_Phydro(i) =  tab_rho(i)*gz;
    }
  if (use_total_hydro_pressure()) remplir_champ_pression_for_EOS();
}
References Milieu_base::a_gravite(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Milieu_base::gravite(), Fluide_Dilatable_base::pression_, pression_hydro_, Objet_U::que_suis_je(), ref_cast, remplir_champ_pression_for_EOS(), Fluide_Dilatable_base::rho_np1(), use_total_hydro_pressure(), Champ_Don::valeurs(), Champ_Don_base::valeurs(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by update_pressure_fields().
calculer_pression_tot()
void Fluide_Weakly_Compressible::calculer_pression_tot () override virtual
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
Reimplemented from Fluide_Dilatable_base.
Definition at line 329 of file Fluide_Weakly_Compressible.cpp.
{
  Fluide_Dilatable_base::calculer_pression_tot();
  if (use_total_hydro_pressure()) remplir_champ_pression_for_EOS();
}
References Fluide_Dilatable_base::calculer_pression_tot(), remplir_champ_pression_for_EOS(), and use_total_hydro_pressure().
checkTraitementPth()
void Fluide_Weakly_Compressible::checkTraitementPth (const Zone_Cl_dis & zone_cl) override virtual
Implements Fluide_Dilatable_base.
Definition at line 240 of file Fluide_Weakly_Compressible.cpp.
{
// TODO : FIXME : we should be able to use this in closed cavities too !!
  int pression_imposee=0;
  int size=zone_cl.les_conditions_limites().size();
  assert(size!=0);
  for (int n=0; n<size; n++)
    {
      const Cond_lim& la_cl = zone_cl.les_conditions_limites(n);
      if (sub_type(Neumann_sortie_libre, la_cl.valeur())) pression_imposee=1;
    }
  if (!pression_imposee)
    {
      Cerr << "At least one open boundary is currently required for the weakly compressible problem !" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, Zone_Cl_dis::les_conditions_limites(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by completer().
completer()
void Fluide_Weakly_Compressible::completer (const Probleme_base & pb) override virtual
Complete le fluide avec les champs inconnus associes au probleme.
< TODO : check if it is generic
< pression_xyz not specified in data file
< soit initialiser
< soit reprendre
Reimplemented from Fluide_Dilatable_base.
Definition at line 100 of file Fluide_Weakly_Compressible.cpp.
{
  Cerr<<"Fluide_Weakly_Compressible::completer" << finl;
// XXX : currently we support only open configurations if use_total_hydro_pressure
// THERE IS A PROBLEM HERE
// TODO : FIXME
  if (use_total_hydro_pressure()) checkTraitementPth(pb.equation(0).zone_Cl_dis());
  if (Pth_xyz_.non_nul())
    {
      if (Pth_xyz_->que_suis_je() != "Champ_Fonc_xyz" ) //!< TODO : check if it is generic
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "Pression_xyz should be defined with Champ_Fonc_xyz !" << finl;
          Process::exit();
        }
      if (Pth_ != -1 || Pth_n != -1)
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "You can not specify both pression_xyz and pression_thermo !" << finl;
          Process::exit();
        }
      if (use_total_hydro_pressure())
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "You need to define pression_thermo when using the flags use_total_pressure or use_hydrostatic_pressure !" << finl;
          Process::exit();
        }
    }
  else //!< pression_xyz not specified in data file
    {
      if (Pth_ != -1) Pth_n = Pth_;
      else
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "You need to specify either pression_xyz or pression_thermo !" << finl;
          Process::exit();
        }
      if ( use_total_pressure_ && time_activate_ptot_==-1. )
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "You should define time_activate_ptot when using the flag use_total_pressure !" << finl;
          Process::exit();
        }
      if ( use_total_pressure_ && use_hydrostatic_pressure_ )
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "Not possible to activate the two flags use_total_pressure and use_hydrostatic_pressure at same time !" << finl;
          Process::exit();
        }
      if ( use_hydrostatic_pressure_ && !a_gravite() )
        {
          Cerr << "Error in your data file : This is not allowed !"<< finl;
          Cerr << "Not possible to activate the flag use_hydrostatic_pressure without defining a gravity vector !" << finl;
          Process::exit();
        }
    }
// XXX : On l'a besoin pour initialiser rho ...
  if ( !use_saved_data() ) initialiser_pth_for_EOS(pb); //!< soit  initialiser
  else pression_eos_.valeurs() = Pth_tab_; //!< soit  reprendre
  Fluide_Dilatable_base::completer(pb);
  mettre_a_jour_bis();
}
References Milieu_base::a_gravite(), Cerr, checkTraitementPth(), Fluide_Dilatable_base::completer(), Probleme_base::equation(), Process::exit(), finl, initialiser_pth_for_EOS(), mettre_a_jour_bis(), O_U_Ptr::non_nul(), pression_eos_, Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n, Pth_tab_, Pth_xyz_, Objet_U::que_suis_je(), time_activate_ptot_, use_hydrostatic_pressure_, use_saved_data(), use_total_hydro_pressure(), use_total_pressure_, Champ_Don::valeurs(), and Equation_base::zone_Cl_dis().
cree_instance()
Objet_U * Fluide_Weakly_Compressible::cree_instance () static
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
discretiser()
void Fluide_Weakly_Compressible::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_Dilatable_base.
Definition at line 259 of file Fluide_Weakly_Compressible.cpp.
{
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
  double temps=pb.schema_temps().temps_courant();
// In *_Melange_Binaire_WC we do not even have a temperature variable ...
// it is the species mass fraction Y1... Although named ch_temperature
  Champ_Don& ch_TK = ch_temperature();
  if (pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_WC" || pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_Turbulent_WC")
    dis.discretiser_champ("temperature",zone_dis,"fraction_massique","neant",1,temps,ch_TK);
  else
    dis.discretiser_champ("temperature",zone_dis,"temperature","K",1,temps,ch_TK);
  if (type_fluide()!="Gaz_Parfait")
    loi_etat()->champs_compris().ajoute_champ(ch_TK);
  Fluide_Dilatable_base::discretiser(pb,dis);
// XXX XXX : Champs pour WC : comme la temperature car elem en VDF et faces en VEF
  Champ_Don& phydro = pression_hydro();
  dis.discretiser_champ("temperature",zone_dis,"pression_hydro","Pa",1,temps,phydro);
  champs_compris_.ajoute_champ(phydro);
  Champ_Don& peos = pression_eos();
  dis.discretiser_champ("temperature",zone_dis,"pression_eos","Pa",1,temps,peos);
  champs_compris_.ajoute_champ(peos);
// Seulement pour multi-especes
  if (pb.que_suis_je()=="Pb_Thermohydraulique_Especes_WC")
    {
      Champ_Don& yn = fraction_massique_nonresolue();
      dis.discretiser_champ("temperature",zone_dis,"fraction_massique_nonresolue","neant",1,temps,yn);
      champs_compris_.ajoute_champ(yn);
    }
}
References Champs_compris::ajoute_champ(), Fluide_Dilatable_base::ch_temperature(), Milieu_base::champs_compris_, Fluide_Dilatable_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), fraction_massique_nonresolue(), Fluide_Dilatable_base::loi_etat(), pression_eos(), pression_hydro(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Fluide_Dilatable_base::type_fluide(), and Equation_base::zone_dis().
duplique()
int Fluide_Weakly_Compressible::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
fraction_massique_nonresolue() [1/2]
Champ_Don & Fluide_Weakly_Compressible::fraction_massique_nonresolue () inline
Definition at line 57 of file Fluide_Weakly_Compressible.h.
{ return unsolved_species_; }
References unsolved_species_.
fraction_massique_nonresolue() [2/2]
const Champ_Don & Fluide_Weakly_Compressible::fraction_massique_nonresolue () const inline
Definition at line 56 of file Fluide_Weakly_Compressible.h.
{ return unsolved_species_; }
References unsolved_species_.
Referenced by Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), discretiser(), and Loi_Etat_Multi_GP_WC::initialiser_inco_ch().
get_info()
const Type_info * Fluide_Weakly_Compressible::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
info()
const Type_info * Fluide_Weakly_Compressible::info () static
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
initialiser_pth()
void Fluide_Weakly_Compressible::initialiser_pth () private
Definition at line 215 of file Fluide_Weakly_Compressible.cpp.
{
  Cerr<<"Initializing the thermo-dynamic pressure ..." << finl;
// Pth_tab_ doit avoir meme dimensions que rho (elem en VDF et faces en VEF)
  Pth_tab_ = masse_volumique().valeurs();
  const int n = Pth_tab_.dimension_tot(0);
  for (int i=0; i<n; i++) Pth_tab_(i) = Pth_;
  Pth_n_tab_ = Pth_tab_;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), finl, Milieu_base::masse_volumique(), Fluide_Dilatable_base::Pth_, Pth_n_tab_, Pth_tab_, and Champ::valeurs().
Referenced by initialiser_pth_for_EOS().
initialiser_pth_for_EOS()
void Fluide_Weakly_Compressible::initialiser_pth_for_EOS (const Probleme_base & pb) private
Definition at line 184 of file Fluide_Weakly_Compressible.cpp.
{
  if (use_pth_xyz()) initialiser_pth_xyz(pb);
  else initialiser_pth();
  pression_eos_.valeurs() = Pth_tab_;
}
References initialiser_pth(), initialiser_pth_xyz(), pression_eos_, Pth_tab_, use_pth_xyz(), and Champ_Don::valeurs().
Referenced by completer().
initialiser_pth_xyz()
void Fluide_Weakly_Compressible::initialiser_pth_xyz (const Probleme_base & pb) private
< VDF or VEF ??
Definition at line 192 of file Fluide_Weakly_Compressible.cpp.
{
  Cerr<<"Initializing the thermo-dynamic pressure Pth_xyz ..." << finl;
  int isVDF = 0; //!< VDF or VEF ??
  if (pb.equation(0).discretisation().que_suis_je()=="VDF") isVDF = 1;
// We know that mu is always stored on elems and that Champ_Don rho_xyz_ is evaluated on elements
  assert (Pth_xyz_->valeurs().size() == viscosite_dynamique().valeurs().size());
  if (isVDF)
    {
// Disc VDF => Pth_xyz_ on elems => we do nothing
      Pth_tab_=Pth_n_tab_=Pth_xyz_->valeurs();
    }
  else
    {
// we use rho for affecter because the field is on the faces in VEF (as rho)
      Champ_base& ch_rho = masse_volumique().valeur();
      ch_rho.affecter_(Pth_xyz_);
      Pth_tab_=Pth_n_tab_=ch_rho.valeurs();
    }
}
References Champ_base::affecter_(), Cerr, Equation_base::discretisation(), Probleme_base::equation(), finl, Milieu_base::masse_volumique(), Pth_n_tab_, Pth_tab_, Pth_xyz_, Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::size(), Deriv_Champ_base::valeur(), Champ_Don::valeurs(), Champ_Proto::valeurs(), and Fluide_base::viscosite_dynamique().
Referenced by initialiser_pth_for_EOS().
lire_motcle_non_standard()
int Fluide_Weakly_Compressible::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Fluide_Dilatable_base.
Definition at line 63 of file Fluide_Weakly_Compressible.cpp.
{
  if (mot=="Traitement_PTh")
    {
      Motcle trait;
      is >> trait;
// TODO : FIXME : should have CONSERVATION_MASSE too !!
      Motcles les_options(1);
      {
        les_options[0] = "constant";
      }
      traitement_PTh=les_options.search(trait);
      if (traitement_PTh == -1)
        {
          Cerr<< trait << " is not understood as an option of the keyword " << mot <<finl;
          Cerr<< "One of the following options was expected : " << les_options << finl;
          Process::exit();
        }
      return 1;
    }
  else return Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
}
References Cerr, Process::exit(), finl, Fluide_Dilatable_base::lire_motcle_non_standard(), Motcles::search(), and Fluide_Dilatable_base::traitement_PTh.
mettre_a_jour_bis()
void Fluide_Weakly_Compressible::mettre_a_jour_bis () protected
Definition at line 172 of file Fluide_Weakly_Compressible.cpp.
{
  assert(pression_eos_.non_nul());
  pression_eos_.mettre_a_jour(le_probleme_->schema_temps().temps_courant());
  if (pression_hydro_.non_nul())
    pression_hydro_.mettre_a_jour(le_probleme_->schema_temps().temps_courant());
  if (unsolved_species_.non_nul())
    unsolved_species_.mettre_a_jour(le_probleme_->schema_temps().temps_courant());
}
References Fluide_Dilatable_base::le_probleme_, Champ_Don::mettre_a_jour(), O_U_Ptr::non_nul(), pression_eos_, pression_hydro_, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and unsolved_species_.
Referenced by completer().
prepare_pressure_edo()
void Fluide_Weakly_Compressible::prepare_pressure_edo () override virtual
Implements Fluide_Dilatable_base.
Definition at line 230 of file Fluide_Weakly_Compressible.cpp.
{
  /* Do nothing */
}
preparer_pas_temps()
void Fluide_Weakly_Compressible::preparer_pas_temps () override virtual
Prepare le pas de temps.
Reimplemented from Fluide_Dilatable_base.
Definition at line 225 of file Fluide_Weakly_Compressible.cpp.
{
  Fluide_Dilatable_base::preparer_pas_temps();
}
References Fluide_Dilatable_base::preparer_pas_temps().
pression_eos() [1/2]
Champ_Don & Fluide_Weakly_Compressible::pression_eos () inline
Definition at line 55 of file Fluide_Weakly_Compressible.h.
{ return pression_eos_; }
References pression_eos_.
pression_eos() [2/2]
const Champ_Don & Fluide_Weakly_Compressible::pression_eos () const inline
Definition at line 54 of file Fluide_Weakly_Compressible.h.
{ return pression_eos_; }
References pression_eos_.
Referenced by discretiser().
pression_hydro() [1/2]
Champ_Don & Fluide_Weakly_Compressible::pression_hydro () inline
Definition at line 53 of file Fluide_Weakly_Compressible.h.
{ return pression_hydro_; }
References pression_hydro_.
pression_hydro() [2/2]
const Champ_Don & Fluide_Weakly_Compressible::pression_hydro () const inline
Definition at line 52 of file Fluide_Weakly_Compressible.h.
{ return pression_hydro_; }
References pression_hydro_.
Referenced by discretiser().
pression_th_tab() [1/2]
DoubleTab & Fluide_Weakly_Compressible::pression_th_tab () inline
Tab Pression thermodynamique.
Definition at line 59 of file Fluide_Weakly_Compressible.h.
References Pth_tab_.
pression_th_tab() [2/2]
const DoubleTab & Fluide_Weakly_Compressible::pression_th_tab () const inline
Tab Pression thermodynamique.
Definition at line 58 of file Fluide_Weakly_Compressible.h.
References Pth_tab_.
Referenced by Source_WC_Chaleur::ajouter_(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
pression_thn_tab() [1/2]
DoubleTab & Fluide_Weakly_Compressible::pression_thn_tab () inline
Tab Pression thermodynamique a l'etape precedente.
Definition at line 61 of file Fluide_Weakly_Compressible.h.
References Pth_n_tab_.
pression_thn_tab() [2/2]
const DoubleTab & Fluide_Weakly_Compressible::pression_thn_tab () const inline
Tab Pression thermodynamique a l'etape precedente.
Definition at line 60 of file Fluide_Weakly_Compressible.h.
References Pth_n_tab_.
Referenced by Source_WC_Chaleur::ajouter_().
printOn()
Sortie & Fluide_Weakly_Compressible::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 39 of file Fluide_Weakly_Compressible.cpp.
{
  os << que_suis_je() << finl;
  Fluide_Dilatable_base::ecrire(os);
  return os;
}
References Milieu_base::ecrire(), finl, and Objet_U::que_suis_je().
readOn()
Entree & Fluide_Weakly_Compressible::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 46 of file Fluide_Weakly_Compressible.cpp.
{
  Fluide_Dilatable_base::readOn(is);
  return is;
}
References Fluide_Dilatable_base::readOn().
remplir_champ_pression_for_EOS()
void Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS () private
Calcule la pression utilisee dans les lois d'etat WC.
< present dt
Definition at line 392 of file Fluide_Weakly_Compressible.cpp.
{
  if (use_total_pressure())
    {
      double t0= le_probleme_->schema_temps().temps_courant(), t1 = le_probleme_->schema_temps().temps_futur(1);
// time to activate ptot and change the eos pressure
      if ( t0 < time_activate_ptot_ && t1 > time_activate_ptot_ )
        for (int i=0 ; i<Pth_tab_.dimension_tot(0) ; i++) Pth_tab_(i,0) = P_NS_(i,0) + Pth_;
    }
  else if (use_hydrostatic_pressure())
    {
      if ( le_probleme_->schema_temps().nb_pas_dt() ==0 && use_saved_data() ) { /* do nothing &  use saved data */ }
      else
        {
          Pth_tab_ = pression_hydro_.valeurs();
          const int n = Pth_tab_.dimension_tot(0);
          for (int i=0 ; i<n ; i++) Pth_tab_(i) += Pth_; //!< present dt
        }
    }
  else
    {
      Cerr << "The method Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS() should not be called !" << finl;
      Process::exit();
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, Fluide_Dilatable_base::le_probleme_, Schema_Temps_base::nb_pas_dt(), P_NS_, pression_hydro_, Fluide_Dilatable_base::Pth_, Pth_tab_, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_futur(), time_activate_ptot_, use_hydrostatic_pressure(), use_saved_data(), use_total_pressure(), and Champ_Don::valeurs().
Referenced by calculer_pression_hydro(), and calculer_pression_tot().
remplir_champ_pression_tot()
void Fluide_Weakly_Compressible::remplir_champ_pression_tot (int n, const DoubleTab & PHydro, DoubleTab & PTot) override private virtual
Implements Fluide_Dilatable_base.
Definition at line 335 of file Fluide_Weakly_Compressible.cpp.
{
  P_NS_ = PHydro;
  if ( use_pth_xyz() )
    for (int i=0 ; i<n ; i++) PTot(i,0) = PHydro(i,0) + Pth_tab_(i,0);
  else
    for (int i=0 ; i<n ; i++) PTot(i,0) = PHydro(i,0) + Pth_;
}
References P_NS_, Fluide_Dilatable_base::Pth_, Pth_tab_, and use_pth_xyz().
secmembre_divU_Z()
void Fluide_Weakly_Compressible::secmembre_divU_Z (DoubleTab & tab_W) const inline override virtual
Implements Fluide_Dilatable_base.
Definition at line 62 of file Fluide_Weakly_Compressible.h.
{ eos_tools_->secmembre_divU_Z(tab_W); }
References Fluide_Dilatable_base::eos_tools_.
self_cast() [1/2]
const Fluide_Weakly_Compressible & Fluide_Weakly_Compressible::self_cast (const Objet_U & r) static
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
self_cast() [2/2]
Fluide_Weakly_Compressible & Fluide_Weakly_Compressible::self_cast (Objet_U & r) static
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
set_param()
void Fluide_Weakly_Compressible::set_param (Param & param) override virtual
< XD_ADD_P double Initial thermo-dynamic pressure used in the assosciated state law.
< XD_ADD_P field_base Initial thermo-dynamic pressure used in the assosciated state law. It should be defined with as a Champ_Fonc_xyz.
< XD_ADD_P int Flag (0 or 1) used to activate and use the total pressure in the assosciated state law. The default value of this Flag is 0.
< XD_ADD_P int Flag (0 or 1) used to activate and use the hydro-static pressure in the assosciated state law. The default value of this Flag is 0.
< XD_ADD_P int Flag (0 or 1) used to specify whether or not the gradient of the thermo-dynamic pressure will be taken into account in the source term of the temperature equation (case of a non-uniform pressure). The default value of this Flag is 1 which means that the gradient is used in the source.
< XD_ADD_P double Time (in seconds) at which the total pressure will be used in the assosciated state law.
Reimplemented from Fluide_Dilatable_base.
Definition at line 52 of file Fluide_Weakly_Compressible.cpp.
{
  Fluide_Dilatable_base::set_param(param);
  param.ajouter("pression_thermo",&Pth_); //!< XD_ADD_P double Initial thermo-dynamic pressure used in the assosciated state law.
  param.ajouter("pression_xyz",&Pth_xyz_); //!< XD_ADD_P field_base Initial thermo-dynamic pressure used in the assosciated state law. It should be defined with as a Champ_Fonc_xyz.
  param.ajouter("use_total_pressure",&use_total_pressure_); //!< XD_ADD_P int Flag (0 or 1) used to activate and use the total pressure in the assosciated state law. The default value of this Flag is 0.
  param.ajouter("use_hydrostatic_pressure",&use_hydrostatic_pressure_); //!< XD_ADD_P int Flag (0 or 1) used to activate and use the hydro-static pressure in the assosciated state law. The default value of this Flag is 0.
  param.ajouter("use_grad_pression_eos",&use_grad_pression_eos_); //!< XD_ADD_P int Flag (0 or 1) used to specify whether or not the gradient of the thermo-dynamic pressure will be taken into account in the source term of the temperature equation (case of a non-uniform pressure). The default value of this Flag is 1 which means that the gradient is used in the source.
  param.ajouter("time_activate_ptot",&time_activate_ptot_); //!< XD_ADD_P double Time (in seconds) at which the total pressure will be used in the assosciated state law.
}
References Param::ajouter(), Fluide_Dilatable_base::Pth_, Pth_xyz_, Fluide_Dilatable_base::set_param(), time_activate_ptot_, use_grad_pression_eos_, use_hydrostatic_pressure_, and use_total_pressure_.
set_pression_th_tab()
void Fluide_Weakly_Compressible::set_pression_th_tab (DoubleTab & Pth_tab) inline
Definition at line 63 of file Fluide_Weakly_Compressible.h.
{ Pth_n_tab_ = Pth_tab_ = Pth_tab; }
References Pth_n_tab_, and Pth_tab_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
set_resume_flag()
void Fluide_Weakly_Compressible::set_resume_flag () inline
Definition at line 64 of file Fluide_Weakly_Compressible.h.
{ sim_resumed_ = 1; }
References sim_resumed_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
taille_memoire()
unsigned Fluide_Weakly_Compressible::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Fluide_Weakly_Compressible.cpp.
update_pressure_fields()
void Fluide_Weakly_Compressible::update_pressure_fields (double temps) override virtual
< previous dt
Reimplemented from Fluide_Dilatable_base.
Definition at line 301 of file Fluide_Weakly_Compressible.cpp.
{
  Pth_n_tab_= Pth_tab_; //!< previous dt
  Fluide_Dilatable_base::update_pressure_fields(temps);
  if (a_gravite())
    {
      calculer_pression_hydro();
      pression_hydro_.mettre_a_jour(temps);
    }
// for post-processing
  pression_eos_.valeurs() = Pth_tab_;
  pression_eos_.mettre_a_jour(temps);
}
References Milieu_base::a_gravite(), calculer_pression_hydro(), Champ_Don::mettre_a_jour(), pression_eos_, pression_hydro_, Pth_n_tab_, Pth_tab_, Fluide_Dilatable_base::update_pressure_fields(), and Champ_Don::valeurs().
use_grad_pression_eos()
bool Fluide_Weakly_Compressible::use_grad_pression_eos () inline
Definition at line 70 of file Fluide_Weakly_Compressible.h.
{ return use_grad_pression_eos_; }
References use_grad_pression_eos_.
Referenced by Source_WC_Chaleur::ajouter_().
use_hydrostatic_pressure()
bool Fluide_Weakly_Compressible::use_hydrostatic_pressure () inline
Definition at line 66 of file Fluide_Weakly_Compressible.h.
{ return use_hydrostatic_pressure_; }
References use_hydrostatic_pressure_.
Referenced by remplir_champ_pression_for_EOS().
use_pth_xyz()
bool Fluide_Weakly_Compressible::use_pth_xyz () inline
Definition at line 67 of file Fluide_Weakly_Compressible.h.
{ return Pth_xyz_.non_nul(); }
References O_U_Ptr::non_nul(), and Pth_xyz_.
Referenced by initialiser_pth_for_EOS(), and remplir_champ_pression_tot().
use_saved_data()
bool Fluide_Weakly_Compressible::use_saved_data () inline
Definition at line 69 of file Fluide_Weakly_Compressible.h.
{ return sim_resumed_; }
References sim_resumed_.
Referenced by completer(), and remplir_champ_pression_for_EOS().
use_total_hydro_pressure()
bool Fluide_Weakly_Compressible::use_total_hydro_pressure () inline
Definition at line 68 of file Fluide_Weakly_Compressible.h.
{ return (use_total_pressure_||use_hydrostatic_pressure_); }
References use_hydrostatic_pressure_, and use_total_pressure_.
Referenced by Source_WC_Chaleur::ajouter_(), calculer_pression_hydro(), calculer_pression_tot(), and completer().
use_total_pressure()
bool Fluide_Weakly_Compressible::use_total_pressure () inline
Definition at line 65 of file Fluide_Weakly_Compressible.h.
{ return use_total_pressure_; }
References use_total_pressure_.
Referenced by remplir_champ_pression_for_EOS().
write_mean_edo()
void Fluide_Weakly_Compressible::write_mean_edo (double t) override virtual
Implements Fluide_Dilatable_base.
Definition at line 235 of file Fluide_Weakly_Compressible.cpp.
{
  /* Do nothing */
}
Member Data Documentation
info_obj
const Type_info Fluide_Weakly_Compressible::info_obj static
Definition at line 35 of file Fluide_Weakly_Compressible.h.
P_NS_
DoubleTab Fluide_Weakly_Compressible::P_NS_ protected
Definition at line 75 of file Fluide_Weakly_Compressible.h.
Referenced by remplir_champ_pression_for_EOS(), and remplir_champ_pression_tot().
pression_eos_
Champ_Don Fluide_Weakly_Compressible::pression_eos_ protected
Definition at line 74 of file Fluide_Weakly_Compressible.h.
Referenced by completer(), initialiser_pth_for_EOS(), mettre_a_jour_bis(), pression_eos(), and update_pressure_fields().
pression_hydro_
Champ_Don Fluide_Weakly_Compressible::pression_hydro_ protected
Definition at line 74 of file Fluide_Weakly_Compressible.h.
Referenced by calculer_pression_hydro(), mettre_a_jour_bis(), pression_hydro(), remplir_champ_pression_for_EOS(), and update_pressure_fields().
Pth_n_tab_
DoubleTab Fluide_Weakly_Compressible::Pth_n_tab_ protected
Definition at line 75 of file Fluide_Weakly_Compressible.h.
Referenced by abortTimeStep(), initialiser_pth(), initialiser_pth_xyz(), pression_thn_tab(), set_pression_th_tab(), and update_pressure_fields().
Pth_tab_
DoubleTab Fluide_Weakly_Compressible::Pth_tab_ protected
Definition at line 75 of file Fluide_Weakly_Compressible.h.
Referenced by abortTimeStep(), completer(), initialiser_pth(), initialiser_pth_for_EOS(), initialiser_pth_xyz(), pression_th_tab(), remplir_champ_pression_for_EOS(), remplir_champ_pression_tot(), set_pression_th_tab(), and update_pressure_fields().
Pth_xyz_
Champ_Don Fluide_Weakly_Compressible::Pth_xyz_ protected
Definition at line 74 of file Fluide_Weakly_Compressible.h.
Referenced by completer(), initialiser_pth_xyz(), set_param(), and use_pth_xyz().
sim_resumed_
int Fluide_Weakly_Compressible::sim_resumed_ protected
Definition at line 76 of file Fluide_Weakly_Compressible.h.
Referenced by set_resume_flag(), and use_saved_data().
time_activate_ptot_
double Fluide_Weakly_Compressible::time_activate_ptot_ protected
Definition at line 77 of file Fluide_Weakly_Compressible.h.
Referenced by completer(), remplir_champ_pression_for_EOS(), and set_param().
unsolved_species_
Champ_Don Fluide_Weakly_Compressible::unsolved_species_ protected
Definition at line 74 of file Fluide_Weakly_Compressible.h.
Referenced by fraction_massique_nonresolue(), and mettre_a_jour_bis().
use_grad_pression_eos_
int Fluide_Weakly_Compressible::use_grad_pression_eos_ protected
Definition at line 76 of file Fluide_Weakly_Compressible.h.
Referenced by set_param(), and use_grad_pression_eos().
use_hydrostatic_pressure_
int Fluide_Weakly_Compressible::use_hydrostatic_pressure_ protected
Definition at line 76 of file Fluide_Weakly_Compressible.h.
Referenced by completer(), set_param(), use_hydrostatic_pressure(), and use_total_hydro_pressure().
use_total_pressure_
int Fluide_Weakly_Compressible::use_total_pressure_ protected
Definition at line 76 of file Fluide_Weakly_Compressible.h.
Referenced by completer(), set_param(), use_total_hydro_pressure(), and use_total_pressure().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Milieu/Fluide_Weakly_Compressible.h
src/ThHyd/Dilatable/Weakly_Compressible/Milieu/Fluide_Weakly_Compressible.cpp