TRUST: Rotationnel_Champ_P1_EF Class Reference
Rotationnel_Champ_P1_EF Class Reference
#include <Rotationnel_Champ_P1_EF.h>
Public Member Functions
Rotationnel_Champ_P1_EF ()
~Rotationnel_Champ_P1_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_P1_EF & mon_champ () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_P1_EF &)
void me_calculer (double)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Rotationnel_Champ_P1_EF & self_cast (Objet_U &)
static const
Rotationnel_Champ_P1_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_P1_EF mon_champ_
Detailed Description
Definition at line 32 of file Rotationnel_Champ_P1_EF.h.
Constructor & Destructor Documentation
Rotationnel_Champ_P1_EF::Rotationnel_Champ_P1_EF ()
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
Rotationnel_Champ_P1_EF::~Rotationnel_Champ_P1_EF ()
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
Member Function Documentation
void Rotationnel_Champ_P1_EF::associer_champ (const Champ_P1_EF & un_champ)
Definition at line 45 of file Rotationnel_Champ_P1_EF.cpp.
References mon_champ_.
{
  mon_champ_= un_champ;
}
Objet_U * Rotationnel_Champ_P1_EF::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
int Rotationnel_Champ_P1_EF::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
const Type_info * Rotationnel_Champ_P1_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
const Type_info * Rotationnel_Champ_P1_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
void Rotationnel_Champ_P1_EF::me_calculer (double tps) [virtual]
Implements Champ_Rotationnel.
Definition at line 50 of file Rotationnel_Champ_P1_EF.cpp.
References Process::abort(), Cerr, and finl.
Referenced by mettre_a_jour().
{
// Cerr<<"Rotationnel_Champ_P1_EF::me_calculer"<<finl;
// mon_champ_->calculer_rotationnel_ordre2_centre_element(valeurs());
// mon_champ_->cal_rot_ordre1(valeurs());
  Cerr << __FILE__ << (int)__LINE__ << "Rotationnel_Champ_P1_EF::me_calculer : ERROR : the curl of a P1 vector fields in a FE context has not been implemented yet." << finl;
  abort();
}
void Rotationnel_Champ_P1_EF::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 54 of file Rotationnel_Champ_P1_EF.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
}
const Champ_P1_EF & Rotationnel_Champ_P1_EF::mon_champ () const [inline]
Definition at line 49 of file Rotationnel_Champ_P1_EF.h.
{
  return mon_champ_.valeur();
}
Sortie & Rotationnel_Champ_P1_EF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 32 of file Rotationnel_Champ_P1_EF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Rotationnel_Champ_P1_EF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 40 of file Rotationnel_Champ_P1_EF.cpp.
{
  return s ;
}
const Rotationnel_Champ_P1_EF & Rotationnel_Champ_P1_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
Rotationnel_Champ_P1_EF & Rotationnel_Champ_P1_EF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
unsigned Rotationnel_Champ_P1_EF::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 26 of file Rotationnel_Champ_P1_EF.cpp.
Member Data Documentation
const Type_info Rotationnel_Champ_P1_EF::info_obj [static]
Reimplemented from Champ_Fonc_P0_EF.
Definition at line 35 of file Rotationnel_Champ_P1_EF.h.
Ref_Champ_P1_EF Rotationnel_Champ_P1_EF::mon_champ_ [protected]
Definition at line 46 of file Rotationnel_Champ_P1_EF.h.
Referenced by associer_champ().
The documentation for this class was generated from the following files:
src/EF/Champs/Rotationnel_Champ_P1_EF.h
src/EF/Champs/Rotationnel_Champ_P1_EF.cpp