TRUST: Op_Dift_VDF_var_Face_Axi Class Reference
Op_Dift_VDF_var_Face_Axi Class Reference
class Op_Dift_VDF_var_Face_Axi
Cette classe represente l'operateur de diffusion global (diffusions
laminaire et turbulente) associe aux equations de quantite de mouvement
en coordonnees cylindriques.
La discretisation est VDF
Le champ diffuse est un Champ_Face
Le champ de diffusivite laminaire est variable
Cette classe n'utilise ni iterateur ni evaluateur (il y avait
trop de termes supplementaires dus aux coordonnees cylindriques)
#include <Op_Dift_VDF_var_Face_Axi.h>
Public Member Functions
Op_Dift_VDF_var_Face_Axi ()
~Op_Dift_VDF_var_Face_Axi ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void associer_diffusivite (const Champ_base &)
associe le champ de diffusivite
void associer_diffusivite_turbulente (const Champ_Fonc &)
void associer_loipar (const Turbulence_paroi &)
const Champ_base & diffusivite () const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
ajoute la contribution de la diffusion au second membre resu
renvoie resu
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
calcule la contribution de la diffusion, la range dans resu
renvoie resu
double calculer_dt_stab () const
Calcul dt_stab.
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Dift_VDF_var_Face_Axi & self_cast (Objet_U &)
static const
Op_Dift_VDF_var_Face_Axi & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Mod_turb_hyd_base le_modele_turbulence
Ref_Champ_Face inconnue
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
Ref_Champ_base diffusivite_
DoubleTab tau_tan
DoubleVect surface
DoubleVect volumes_entrelaces
IntVect orientation
DoubleVect porosite
DoubleTab xp
DoubleTab xv
IntTab Qdm
IntTab face_voisins
IntTab elem_faces
IntVect type_arete_bord
Detailed Description
class Op_Dift_VDF_var_Face_Axi
Cette classe represente l'operateur de diffusion global (diffusions
laminaire et turbulente) associe aux equations de quantite de mouvement
en coordonnees cylindriques.
La discretisation est VDF
Le champ diffuse est un Champ_Face
Le champ de diffusivite laminaire est variable
Cette classe n'utilise ni iterateur ni evaluateur (il y avait
trop de termes supplementaires dus aux coordonnees cylindriques)
Definition at line 53 of file Op_Dift_VDF_var_Face_Axi.h.
Constructor & Destructor Documentation
Op_Dift_VDF_var_Face_Axi::Op_Dift_VDF_var_Face_Axi ()
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
Op_Dift_VDF_var_Face_Axi::~Op_Dift_VDF_var_Face_Axi ()
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
Member Function Documentation
DoubleTab & Op_Dift_VDF_var_Face_Axi::ajouter (const DoubleTab & inco, DoubleTab & resu) const [virtual]
ajoute la contribution de la diffusion au second membre resu
renvoie resu
< paroi-paroi
< fluide-fluide
< paroi-fluide
< bord d'equation R = cte
< bord d'equation teta = cte
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Reimplemented from Op_Dift_VDF_base.
Definition at line 113 of file Op_Dift_VDF_var_Face_Axi.cpp.
References Cerr, Champ_Face_get_val_imp_face_bord(), diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, elem_faces, MorEqn::equation(), Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, inconnue, la_zcl_vdf, la_zone_vdf, Zone_VDF::nb_aretes(), Zone_VDF::nb_aretes_bord(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Zone_VF::premiere_face_bord(), Qdm, ref_cast_non_const, Equation_base::schema_temps(), surface, TypeAreteBordVDF::SYM_SYM, tau_tan, Schema_Temps_base::temps_courant(), type_arete_bord, Ref_Champ_Face::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Fonc::valeurs(), volumes_entrelaces, and xv.
Referenced by calculer().
{
  if (inco.nb_dim() > 1)
    {
      Cerr << "Erreur dans Op_Dift_VDF_var_Face_Axi::ajouter" << finl;
      Cerr << "On ne sait pas traiter la diffusion d'un Champ_Face a plusieurs inconnues" << finl;
      exit();
    }
  double temps=equation().schema_temps().temps_courant();
  ref_cast_non_const(Op_Dift_VDF_var_Face_Axi, (*this)).mettre_a_jour(temps);
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
// int nb_elem = zvdf.nb_elem();
// int nb_aretes = zvdf.nb_aretes();
  const DoubleVect& visco_lam = diffusivite_->valeurs();
  const DoubleVect& visco_turb = diffusivite_turbulente()->valeurs();
  double d_visco_turb,d_visco_lam;
  const DoubleTab& tau_diag = inconnue->tau_diag();
  const DoubleTab& tau_croises = inconnue->tau_croises();
  ref_cast_non_const(Champ_Face,inconnue.valeur()).calculer_dercov_axi(zclvdf);
// Boucle sur les elements pour traiter les facettes situees
// a l'interieur des elements
  int fx0,fx1,fy0,fy1;
  double flux_X,flux_Y;
  double coef_laplacien_axi, visc_elem;
  for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
    {
      fx0 = elem_faces(num_elem,0);
      fx1 = elem_faces(num_elem,dimension);
      fy0 = elem_faces(num_elem,1);
      fy1 = elem_faces(num_elem,1+dimension);
      visc_elem = visco_lam(num_elem) + 2*visco_turb(num_elem);
      flux_X = (visc_elem*tau_diag(num_elem,0))*0.5*(surface(fx0)+surface(fx1));
      flux_Y = (visc_elem*tau_diag(num_elem,1))*0.5*(surface(fy0)+surface(fy1));
      resu(fx0) += flux_X;
      resu(fx1) += flux_X;
      resu(fy0) += flux_Y;
      resu(fy1) += flux_Y;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
      coef_laplacien_axi = -0.5*(tau_diag(num_elem,1)*visc_elem);
      resu[fx0] += coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
      resu[fx1] += coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
    }
  if (dimension == 3)
    {
      int fz0,fz1;
      double flux_Z;
      for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
        {
          fz0 = elem_faces(num_elem,2);
          fz1 = elem_faces(num_elem,2+dimension);
          visc_elem = visco_lam(num_elem) + 2*visco_turb(num_elem);
          flux_Z = (visc_elem*tau_diag(num_elem,2))*0.5*(surface(fz0)+surface(fz1));
          resu[fz0] += flux_Z;
          resu[fz1] -= flux_Z;
        }
    }
// Boucle sur les bord pour traiter les faces de type sortie_libre
  int ndeb, nfin;
// Boucle sur les aretes bord
  int n_arete;
  ndeb = zvdf.premiere_arete_bord();
  nfin = ndeb + zvdf.nb_aretes_bord();
  int ori1,ori3,n_type,fac1,fac2,fac3,signe;
  double tau12,tau21,tau13,tau31,tau23,tau32;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI: //!< paroi-paroi
          {
            double flux0;
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            ori1 = orientation(fac1);
            ori3 = orientation(fac3);
            int rang1 = (fac1-zvdf.premiere_face_bord());
            int rang2 = (fac2-zvdf.premiere_face_bord());
            double vit = inco(fac3);
            double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf)+
                                  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf));
// Calcul du frottement identique a celui de TRIOVF:
// On calcule la moyenne des u_star et on l'eleve au carre
// On calcule la moyenne des surfaces
            double tau_tan_1 = tau_tan(rang1,ori3) ;
            double tau_tan_2 = tau_tan(rang2,ori3) ;
// double tau = 0.5*(sqrt(tau_tan_1) + sqrt(tau_tan_2));
            double tau = 0.5*(tau_tan_1 + tau_tan_2 );
            double surf = 0.5*(surface(fac1)+surface(fac2));
            double coef = tau*tau*surf;
// Autre solution pour le calcul du frottement:
// On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
// double tau1 = tau_tan(rang1,ori3)*0.5*surface(fac1);
// double tau2 = tau_tan(rang2,ori3)*0.5*surface(fac2);
// double coef = tau1+tau2;
            int signe_terme;
            if ( vit < vit_imp )
              signe_terme = 1;
            else
              signe_terme = -1;
// flux = signe_terme*coef;
// YB : 30/01/2004 :
// Elimination de la determination du signe du flux parietal par l'evaluateur de l'operateur de diffusion,
// en contre-partie le cisaillement parietal fournit par la loi paroi est signe (voir modif dans distances_VDF.cpp)
            signe_terme = 1;
// Fin modif YB
            flux0 = signe_terme*coef;
            resu[fac3]+= flux0;
            break;
          }
        case TypeAreteBordVDF::FLUIDE_FLUIDE: //!< fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE: //!< paroi-fluide
          {
            double flux1;
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            int ori1b = orientation(fac1);
            int ori3b = orientation(fac3);
            d_visco_turb = 0.5*(visco_turb(face_voisins(fac3,0))
                                + visco_turb(face_voisins(fac3,1)));
            d_visco_lam = 0.5*(visco_lam(face_voisins(fac3,0))
                               + visco_lam(face_voisins(fac3,1)));
            if (ori1b == 0) //!< bord d'equation R = cte
              {
                if (ori3b == 1)
                  {
                    tau12 = tau_croises(n_arete,0);
                    tau21 = tau_croises(n_arete,1);
                    flux1 = (d_visco_lam*tau12 + d_visco_turb*(tau12+tau21))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 2)
                  {
                    assert (ori3b == 2) ;
                    tau13 = tau_croises(n_arete,0);
                    tau31 = tau_croises(n_arete,1);
                    flux1 = (d_visco_lam*tau13 + d_visco_turb*(tau13+tau31))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3]+=signe*flux1;
// Calcul de flux1_2 a coder
// resu[fac1] += flux1_2;
// resu[fac2] -= flux1_2;
              }
            else if (ori1b == 1) //!< bord d'equation teta = cte
              {
                if (ori3b == 0)
                  {
                    double flux2;
                    tau21 = tau_croises(n_arete,0);
                    tau12 = tau_croises(n_arete,1);
                    flux2 = (d_visco_lam*tau21 + d_visco_turb*(tau12+tau21))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux2;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
                    coef_laplacien_axi = 0.5*(d_visco_lam*tau21 + d_visco_turb*(tau12+tau21));
                    resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                    resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                  }
                else if (ori3b == 2) //!< flux de tau23 a travers le bord
                  {
                    double flux3;
                    tau23 = tau_croises(n_arete,0);
                    tau32 = tau_croises(n_arete,1);
                    flux3 = (d_visco_lam*tau23 + d_visco_turb*(tau23+tau32))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux3;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux4;
                if (ori3b == 0)
                  {
                    tau31 = tau_croises(n_arete,0);
                    tau13 = tau_croises(n_arete,1);
                    flux4 = (d_visco_lam*tau31 + d_visco_turb*(tau13+tau31))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3b == 1);
                    tau32 = tau_croises(n_arete,0);
                    tau23 = tau_croises(n_arete,1);
                    flux4 = (d_visco_lam*tau32 + d_visco_turb*(tau23+tau32))
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
// ATTENTION GROSSE CORRECTION LA PARANTHESE SUIVANTE ETAIT
// MAL PLACEE
// }
                resu[fac3] += signe*flux4;
              }
            break;
          }
        case TypeAreteBordVDF::SYM_SYM:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
  int fac4;
// Boucle sur les aretes mixtes
// Sur les aretes mixtes les termes croises du tenseur de Reynolds
// sont nuls: il ne reste donc que la diffusion laminaire
  ndeb = zvdf.premiere_arete_mixte();
  nfin = zvdf.premiere_arete_interne();
  int element;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
      d_visco_lam = 0;
      if ((element=face_voisins(fac3,0)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac3,1)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac4,0)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac4,0)) != -1)
        d_visco_lam+=visco_lam(element);
      d_visco_lam/=3.0;
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
          tau12 = tau_croises(n_arete,0);
          tau21 = tau_croises(n_arete,1);
// flux de mu_lam*tau21
// sur la facette a cheval sur les faces fac1 et fac2
          flux1 = d_visco_lam*tau21*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux1;
          resu(fac4) -= flux1;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*d_visco_lam*tau21;
          resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
// flux de mu_lam*tau12
// sur la facette a cheval sur les faces fac3 et fac4
          flux1 = d_visco_lam*tau12*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux1;
          resu(fac2) -= flux1;
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          double flux2;
          tau23 = tau_croises(n_arete,0);
          tau32 = tau_croises(n_arete,1);
// flux de mu_lam*tau32
// sur la facette a cheval sur les faces fac1 et fac2
          flux2 = d_visco_lam*tau32*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux2;
          resu(fac4) -= flux2;
// flux de mu_lam*tau23
// sur la facette a cheval sur les faces fac3 et fac4
          flux2 = d_visco_lam*tau23*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux2;
          resu(fac2) -= flux2;
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          double flux3;
          tau13 = tau_croises(n_arete,0);
          tau31 = tau_croises(n_arete,1);
// flux de mu_lam*tau31
// sur la facette a cheval sur les faces fac1 et fac2
          flux3 = d_visco_lam*tau31*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux3;
          resu(fac4) -= flux3;
// flux de mu_lam*tau13
// sur la facette a cheval sur les faces fac3 et fac4
          flux3 = d_visco_lam*tau13*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux3;
          resu(fac2) -= flux3;
        }
    }
// Boucle sur les aretes internes
  ndeb = zvdf.premiere_arete_interne();
  nfin = zvdf.nb_aretes();
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
// Calcul de la viscosite turbulente au milieu de l'arete
      d_visco_turb = 0.25*(visco_turb(face_voisins(fac3,0)) + visco_turb(face_voisins(fac3,1))
                           + visco_turb(face_voisins(fac4,0)) + visco_turb(face_voisins(fac4,1)));
      d_visco_lam = 0.25*(visco_lam(face_voisins(fac3,0)) + visco_lam(face_voisins(fac3,1))
                          + visco_lam(face_voisins(fac4,0)) + visco_lam(face_voisins(fac4,1)));
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
          tau12 = tau_croises(n_arete,0);
          tau21 = tau_croises(n_arete,1);
// flux de mu_lam*tau21 + mu_turb*(tau21+tau12)
// sur la facette a cheval sur les faces fac1 et fac2
          flux1 = (d_visco_lam*tau21 + d_visco_turb*(tau21+tau12))
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux1;
          resu(fac4) -= flux1;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*(d_visco_lam*tau21 + d_visco_turb*(tau21+tau12));
          resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
// flux de mu_lam*tau12 + mu_turb*(tau21+tau12)
// sur la facette a cheval sur les faces fac3 et fac4
          flux1 = (d_visco_lam*tau12 + d_visco_turb*(tau12+tau21))
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux1;
          resu(fac2) -= flux1;
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          double flux2;
          tau23 = tau_croises(n_arete,0);
          tau32 = tau_croises(n_arete,1);
// flux de mu_lam*tau32 + mu_turb*(tau32+tau23)
// sur la facette a cheval sur les faces fac1 et fac2
          flux2 = (d_visco_lam*tau32 + d_visco_turb*(tau32+tau23))
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux2;
          resu(fac4) -= flux2;
// flux de mu_lam*tau23 + mu_turb*(tau32+tau23)
// sur la facette a cheval sur les faces fac3 et fac4
          flux2 = (d_visco_lam*tau23 + d_visco_turb*(tau32+tau23))
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux2;
          resu(fac2) -= flux2;
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          double flux3;
          tau13 = tau_croises(n_arete,0);
          tau31 = tau_croises(n_arete,1);
// flux de  mu_lam*tau31 + mu_turb*(tau31+tau13)
// sur la facette a cheval sur les faces fac1 et fac2
          flux3 = (d_visco_lam*tau31 + d_visco_turb*(tau31+tau13))
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux3;
          resu(fac4) -= flux3;
// flux de mu_lam*tau13 + mu_turb*(tau13+tau31)
// sur la facette a cheval sur les faces fac3 et fac4
          flux3 = (d_visco_lam*tau13 + d_visco_turb*(tau31+tau13))
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux3;
          resu(fac2) -= flux3;
        }
    }
  return resu;
}
void Op_Dift_VDF_var_Face_Axi::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const
< paroi-paroi
< fluide-fluide
< paroi-fluide
< bord d'equation R = cte
< bord d'equation teta = cte
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
< if (ori3 == 1) flux de tau32 a travers le bord
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Definition at line 634 of file Op_Dift_VDF_var_Face_Axi.cpp.
References Cerr, coeff, diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, elem_faces, MorEqn::equation(), Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), inconnue, la_zcl_vdf, la_zone_vdf, Zone_VDF::nb_aretes(), Zone_VDF::nb_aretes_bord(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Qdm, ref_cast_non_const, Equation_base::schema_temps(), surface, TypeAreteBordVDF::SYM_SYM, Schema_Temps_base::temps_courant(), type_arete_bord, Ref_Champ_Face::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Fonc::valeurs(), volumes_entrelaces, and xv.
Referenced by contribuer_a_avec().
{
  if (inco.nb_dim() > 1)
    {
      Cerr << "Erreur dans Op_Dift_VDF_Face_Axi::ajouter" << finl;
      Cerr << "On ne sait pas traiter la diffusion d'un Champ_Face a plusieurs inconnues" << finl;
      exit();
    }
  double temps=equation().schema_temps().temps_courant();
  ref_cast_non_const(Op_Dift_VDF_var_Face_Axi, (*this)).mettre_a_jour(temps);
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
// int nb_elem = zvdf.nb_elem();
// int nb_aretes = zvdf.nb_aretes();
  int l;
  IntVect& tab1 = matrice.get_set_tab1();
  IntVect& tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  const DoubleVect& visco_lam = diffusivite_->valeurs();
  const DoubleVect& visco_turb = diffusivite_turbulente()->valeurs();
  double d_visco_turb,d_visco_lam;
  const DoubleTab& tau_diag = inconnue->tau_diag();
// DoubleTab& tau_croises = inconnue->tau_croises();
  ref_cast_non_const(Champ_Face,inconnue.valeur()).calculer_dercov_axi(zclvdf);
// Boucle sur les elements pour traiter les facettes situees
// a l'interieur des elements
  int fx0,fx1,fy0,fy1;
  double flux_X,flux_Y;
  double coef_laplacien_axi, visc_elem;
  for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
    {
      fx0 = elem_faces(num_elem,0);
      fx1 = elem_faces(num_elem,dimension);
      fy0 = elem_faces(num_elem,1);
      fy1 = elem_faces(num_elem,1+dimension);
      visc_elem = visco_lam(num_elem) + 2*visco_turb(num_elem);
      flux_X = (visc_elem*tau_diag(num_elem,0))*0.5*(surface(fx0)+surface(fx1));
      flux_Y = (visc_elem*tau_diag(num_elem,1))*0.5*(surface(fy0)+surface(fy1));
      for (l=tab1[fx0]-1; l<tab1[fx0+1]-1; l++)
        {
          if (tab2[l]-1==fx0)
            coeff[l]+=flux_X;
          if (tab2[l]-1==fx1)
            coeff[l]-=flux_X;
        }
      for (l=tab1[fx1]-1; l<tab1[fx1+1]-1; l++)
        {
          if (tab2[l]-1==fx0)
            coeff[l]-=flux_X;
          if (tab2[l]-1==fx1)
            coeff[l]+=flux_X;
        }
      for (l=tab1[fy0]-1; l<tab1[fy0+1]-1; l++)
        {
          if (tab2[l]-1==fy0)
            coeff[l]+=flux_Y;
          if (tab2[l]-1==fy1)
            coeff[l]-=flux_Y;
        }
      for (l=tab1[fy1]-1; l<tab1[fy1+1]-1; l++)
        {
          if (tab2[l]-1==fy0)
            coeff[l]-=flux_Y;
          if (tab2[l]-1==fy1)
            coeff[l]+=flux_Y;
        }
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
      coef_laplacien_axi = -0.5*(tau_diag(num_elem,1)*visc_elem);
      for (l=tab1[fx0]-1; l<tab1[fx0+1]-1; l++)
        {
          if (tab2[l]-1==fx0)
            coeff[l]+= coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
        }
      for (l=tab1[fx1]-1; l<tab1[fx1+1]-1; l++)
        {
          if (tab2[l]-1==fx1)
            coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
        }
    }
  if (dimension == 3)
    {
      int fz0,fz1;
      double flux_Z;
      for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
        {
          fz0 = elem_faces(num_elem,2);
          fz1 = elem_faces(num_elem,2+dimension);
          visc_elem = visco_lam(num_elem) + 2*visco_turb(num_elem);
          flux_Z = (visc_elem*tau_diag(num_elem,2))*0.5*(surface(fz0)+surface(fz1));
          for (l=tab1[fz0]-1; l<tab1[fz0+1]-1; l++)
            {
              if (tab2[l]-1==fz0)
                coeff[l]+=flux_Z;
              if (tab2[l]-1==fz1)
                coeff[l]-=flux_Z;
            }
          for (l=tab1[fz1]-1; l<tab1[fz1+1]-1; l++)
            {
              if (tab2[l]-1==fz0)
                coeff[l]-=flux_Z;
              if (tab2[l]-1==fz1)
                coeff[l]+=flux_Z;
            }
        }
    }
// Boucle sur les bord pour traiter les faces de type sortie_libre
  int ndeb, nfin;
// Boucle sur les aretes bord
  int n_arete;
  ndeb = zvdf.premiere_arete_bord();
  nfin = ndeb + zvdf.nb_aretes_bord();
  int ori1,ori3,n_type,fac1,fac2,fac3,signe;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI: //!< paroi-paroi
          {
            break;
          }
        case TypeAreteBordVDF::FLUIDE_FLUIDE: //!< fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE: //!< paroi-fluide
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            int ori1b = orientation(fac1);
            int ori3b = orientation(fac3);
            d_visco_turb = 0.5*(visco_turb(face_voisins(fac3,0))
                                + visco_turb(face_voisins(fac3,1)));
            d_visco_lam = 0.5*(visco_lam(face_voisins(fac3,0))
                               + visco_lam(face_voisins(fac3,1)));
            if (ori1b == 0) //!< bord d'equation R = cte
              {
                double flux1;
                if (ori3b == 1)
                  {
                    flux1 = (d_visco_lam+ d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 2)
                  {
                    assert(ori3b == 2) ;
                    flux1 = (d_visco_lam + d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
                  {
                    if (tab2[l]-1==fac3)
                      coeff[l]+=signe*flux1;
                  }
// Calcul de flux1_2 a coder
// resu[fac1] += flux1_2;
// resu[fac2] -= flux1_2;
              }
            else if (ori1b == 1) //!< bord d'equation teta = cte
              {
                if (ori3b == 0)
                  {
                    double flux2;
                    flux2 = (d_visco_lam + d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
                      {
                        if (tab2[l]-1==fac3)
                          coeff[l]+=signe*flux2;
                      }
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
                    coef_laplacien_axi = 0.5*(d_visco_lam + d_visco_turb);
                    for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
                      {
                        if (tab2[l]-1==fac1)
                          coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                      }
                    for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
                      {
                        if (tab2[l]-1==fac2)
                          coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                      }
                  }
                else if (ori3b == 2) //!< flux de tau23 a travers le bord
                  {
                    double flux3;
                    flux3 = (d_visco_lam + d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
                      {
                        if (tab2[l]-1==fac3)
                          coeff[l]+=signe*flux3;
                      }
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux4;
                if (ori3b == 0)
                  {
                    flux4 = (d_visco_lam + d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else//!< if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3b == 1) ;
                    flux4 = (d_visco_lam+ d_visco_turb)
                            *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
// ATTENTION GROSSE CORRECTION LA PARANTHESE SUIVANTE ETAIT
// MAL PLACEE
// }
                for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
                  {
                    if (tab2[l]-1==fac3)
                      coeff[l]+=signe*flux4;
                  }
              }
            break;
          }
        case TypeAreteBordVDF::SYM_SYM:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
  int fac4;
// Boucle sur les aretes mixtes
// Sur les aretes mixtes les termes croises du tenseur de Reynolds
// sont nuls: il ne reste donc que la diffusion laminaire
  ndeb = zvdf.premiere_arete_mixte();
  nfin = zvdf.premiere_arete_interne();
  int element;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
      d_visco_lam = 0;
      if ((element=face_voisins(fac3,0)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac3,1)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac4,0)) != -1)
        d_visco_lam+=visco_lam(element);
      if ((element=face_voisins(fac4,0)) != -1)
        d_visco_lam+=visco_lam(element);
      d_visco_lam/=3.0;
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
// flux de mu_lam*tau21
// sur la facette a cheval sur les faces fac1 et fac2
          flux1 = d_visco_lam*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux1;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux1;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux1;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux1;
            }
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*d_visco_lam;
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac2)
                coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
            }
// flux de mu_lam*tau12
// sur la facette a cheval sur les faces fac3 et fac4
          flux1 = d_visco_lam*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux1;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux1;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux1;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux1;
            }
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          double flux2;
// flux de mu_lam*tau32
// sur la facette a cheval sur les faces fac1 et fac2
          flux2 = d_visco_lam*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux2;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux2;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux2;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux2;
            }
// flux de mu_lam*tau23
// sur la facette a cheval sur les faces fac3 et fac4
          flux2 = d_visco_lam*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux2;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux2;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux2;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux2;
            }
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
// flux de mu_lam*tau31
// sur la facette a cheval sur les faces fac1 et fac2
          double flux3;
          flux3 = d_visco_lam*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux3;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux3;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux3;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux3;
            }
// flux de mu_lam*tau13
// sur la facette a cheval sur les faces fac3 et fac4
          flux3 = d_visco_lam*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux3;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux3;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux3;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux3;
            }
        }
    }
// Boucle sur les aretes internes
  ndeb = zvdf.premiere_arete_interne();
  nfin = zvdf.nb_aretes();
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
// Calcul de la viscosite turbulente au milieu de l'arete
      d_visco_turb = 0.25*(visco_turb(face_voisins(fac3,0)) + visco_turb(face_voisins(fac3,1))
                           + visco_turb(face_voisins(fac4,0)) + visco_turb(face_voisins(fac4,1)));
      d_visco_lam = 0.25*(visco_lam(face_voisins(fac3,0)) + visco_lam(face_voisins(fac3,1))
                          + visco_lam(face_voisins(fac4,0)) + visco_lam(face_voisins(fac4,1)));
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
// flux de mu_lam*tau21 + mu_turb*(tau21+tau12)
// sur la facette a cheval sur les faces fac1 et fac2
          double flux1;
          flux1 = (d_visco_lam + d_visco_turb)
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux1;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux1;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux1;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux1;
            }
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*(d_visco_lam + d_visco_turb);
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac2)
                coeff[l]+=coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
            }
// flux de mu_lam*tau12 + mu_turb*(tau21+tau12)
// sur la facette a cheval sur les faces fac3 et fac4
          flux1 = (d_visco_lam + d_visco_turb)
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux1;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux1;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux1;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux1;
            }
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
// flux de mu_lam*tau32 + mu_turb*(tau32+tau23)
// sur la facette a cheval sur les faces fac1 et fac2
          double flux2;
          flux2 = (d_visco_lam + d_visco_turb)
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux2;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux2;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux2;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux2;
            }
// flux de mu_lam*tau23 + mu_turb*(tau32+tau23)
// sur la facette a cheval sur les faces fac3 et fac4
          flux2 = (d_visco_lam + d_visco_turb)
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux2;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux2;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux2;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux2;
            }
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
// flux de  mu_lam*tau31 + mu_turb*(tau31+tau13)
// sur la facette a cheval sur les faces fac1 et fac2
          double flux3;
          flux3 = (d_visco_lam+ d_visco_turb)
                  *0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          for (l=tab1[fac3]-1; l<tab1[fac3+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]+=flux3;
              if (tab2[l]-1==fac4)
                coeff[l]-=flux3;
            }
          for (l=tab1[fac4]-1; l<tab1[fac4+1]-1; l++)
            {
              if (tab2[l]-1==fac3)
                coeff[l]-=flux3;
              if (tab2[l]-1==fac4)
                coeff[l]+=flux3;
            }
// flux de mu_lam*tau13 + mu_turb*(tau13+tau31)
// sur la facette a cheval sur les faces fac3 et fac4
          flux3 = (d_visco_lam + d_visco_turb)
                  *0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          for (l=tab1[fac1]-1; l<tab1[fac1+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]+=flux3;
              if (tab2[l]-1==fac2)
                coeff[l]-=flux3;
            }
          for (l=tab1[fac2]-1; l<tab1[fac2+1]-1; l++)
            {
              if (tab2[l]-1==fac1)
                coeff[l]-=flux3;
              if (tab2[l]-1==fac2)
                coeff[l]+=flux3;
            }
        }
    }
}
void Op_Dift_VDF_var_Face_Axi::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) [virtual]
complete l'iterateur et l'evaluateur
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 40 of file Op_Dift_VDF_var_Face_Axi.cpp.
References Zone_VF::elem_faces(), elem_faces, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), face_voisins, inconnue, la_zcl_vdf, la_zone_vdf, Zone_VDF::orientation(), orientation, porosite, Zone_VF::porosite_face(), Zone_VDF::Qdm(), Qdm, IntTab::ref(), DoubleTab::ref(), IntVect::ref(), DoubleVect::ref(), ref_cast, surface, type_arete_bord, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Zone_VF::volumes_entrelaces(), volumes_entrelaces, Zone_VF::xp(), xp, Zone_VF::xv(), and xv.
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  const Champ_Face& inco = ref_cast(Champ_Face,ch_transporte.valeur());
  la_zone_vdf = zvdf;
  la_zcl_vdf = zclvdf;
  inconnue = inco;
  surface.ref(zvdf.face_surfaces());
  volumes_entrelaces.ref(zvdf.volumes_entrelaces());
  orientation.ref(zvdf.orientation());
  porosite.ref(zvdf.porosite_face());
  xp.ref(zvdf.xp());
  xv.ref(zvdf.xv());
  Qdm.ref(zvdf.Qdm());
  face_voisins.ref(zvdf.face_voisins());
  elem_faces.ref(zvdf.elem_faces());
  type_arete_bord.ref(zclvdf.type_arete_bord());
}
void Op_Dift_VDF_var_Face_Axi::associer_diffusivite (const Champ_base & diffu) [virtual]
associe le champ de diffusivite
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 77 of file Op_Dift_VDF_var_Face_Axi.cpp.
References diffusivite_.
{
  diffusivite_ = diffu;
}
void Op_Dift_VDF_var_Face_Axi::associer_diffusivite_turbulente (const Champ_Fonc & visc_turb)
Reimplemented from Op_Diff_Turbulent_base.
Definition at line 87 of file Op_Dift_VDF_var_Face_Axi.cpp.
{
  Op_Diff_Turbulent_base::associer_diffusivite_turbulente(visc_turb);
}
void Op_Dift_VDF_var_Face_Axi::associer_loipar (const Turbulence_paroi & loi_paroi)
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 92 of file Op_Dift_VDF_var_Face_Axi.cpp.
{
// loipar = loi_paroi;
}
void Op_Dift_VDF_var_Face_Axi::associer_modele_turbulence (const Mod_turb_hyd_base & mod)
Definition at line 97 of file Op_Dift_VDF_var_Face_Axi.cpp.
References le_modele_turbulence.
Referenced by completer().
{
  le_modele_turbulence    = mod;
}
DoubleTab & Op_Dift_VDF_var_Face_Axi::calculer (const DoubleTab & inco, DoubleTab & resu) const [virtual]
calcule la contribution de la diffusion, la range dans resu
renvoie resu
Reimplemented from Op_Diff_VDF_base.
Definition at line 623 of file Op_Dift_VDF_var_Face_Axi.cpp.
References ajouter().
{
  resu=0;
  return ajouter(inco,resu);
}
double Op_Dift_VDF_var_Face_Axi::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 1362 of file Op_Dift_VDF_var_Face_Axi.cpp.
References la_zone_vdf, and Ref_Zone_VDF::valeur().
{
  return Op_Dift_VDF_Face_base::calculer_dt_stab(la_zone_vdf.valeur()) ;
}
void Op_Dift_VDF_var_Face_Axi::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_VDF_base.
Definition at line 64 of file Op_Dift_VDF_var_Face_Axi.cpp.
References associer_modele_turbulence(), Champ_Face::dimensionner_tenseur_Grad(), MorEqn::equation(), Equation_base::get_modele(), Equation_base::inconnue(), ref_cast, TURBULENCE, Ref_Objet_U::valeur(), and Deriv_Champ_Inc_base::valeur().
{
  Op_Dift_VDF_base::completer();
  Equation_base& eqn_hydr = equation();
  Champ_Face& vitesse = ref_cast(Champ_Face,eqn_hydr.inconnue().valeur());
  vitesse.dimensionner_tenseur_Grad();
  const RefObjU& modele_turbulence = eqn_hydr.get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  associer_modele_turbulence(mod_turb);
}
void Op_Dift_VDF_var_Face_Axi::contribue_au_second_membre (DoubleTab & resu) const
< paroi-paroi
< fluide-fluide
< paroi-fluide
Definition at line 1264 of file Op_Dift_VDF_var_Face_Axi.cpp.
References Cerr, Champ_Face_get_val_imp_face_bord(), MorEqn::equation(), Process::exit(), TypeAreteBordVDF::FLUIDE_FLUIDE, inconnue, la_zcl_vdf, la_zone_vdf, Zone_VDF::nb_aretes_bord(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, Zone_VDF::premiere_arete_bord(), Zone_VF::premiere_face_bord(), Qdm, ref_cast_non_const, Equation_base::schema_temps(), surface, TypeAreteBordVDF::SYM_SYM, tau_tan, Schema_Temps_base::temps_courant(), type_arete_bord, Ref_Champ_Face::valeur(), and Ref_Zone_VDF::valeur().
Referenced by contribuer_au_second_membre().
{
  double temps=equation().schema_temps().temps_courant();
  ref_cast_non_const(Op_Dift_VDF_var_Face_Axi, (*this)).mettre_a_jour(temps);
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
// const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
// int nb_elem = zvdf.nb_elem();
// int nb_aretes = zvdf.nb_aretes();
// const DoubleVect& visco_lam = diffusivite_->valeurs();
// const DoubleVect& visco_turb = diffusivite_turbulente()->valeurs();
// Boucle sur les elements pour traiter les facettes situees
// a l'interieur des elements
// Boucle sur les aretes bord
  int n_arete;
  int ndeb = zvdf.premiere_arete_bord();
  int nfin = ndeb + zvdf.nb_aretes_bord();
  double flux;
  int ori3,n_type,fac1,fac2,fac3;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI: //!< paroi-paroi
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            ori3 = orientation(fac3);
            int rang1 = (fac1-zvdf.premiere_face_bord());
            int rang2 = (fac2-zvdf.premiere_face_bord());
            double vit = inconnue.valeur()(fac3);
            double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf)+
                                  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf));
// Calcul du frottement identique a celui de TRIOVF:
// On calcule la moyenne des u_star et on l'eleve au carre
// On calcule la moyenne des surfaces
            double tau = 0.5*(sqrt(tau_tan(rang1,ori3)) + sqrt(tau_tan(rang2,ori3)));
            double surf = 0.5*(surface(fac1)+surface(fac2));
            double coef = tau*tau*surf;
// Autre solution pour le calcul du frottement:
// On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
// double tau1 = tau_tan(rang1,ori3)*0.5*surface(fac1);
// double tau2 = tau_tan(rang2,ori3)*0.5*surface(fac2);
// double coef = tau1+tau2;
            int signe_terme;
            if ( vit < vit_imp )
              signe_terme = 1;
            else
              signe_terme = -1;
// YB : 30/01/2004 :
// Elimination de la determination du signe du flux parietal par l'evaluateur de l'operateur de diffusion,
// en contre-partie le cisaillement parietal fournit par la loi paroi est signe (voir modif dans distances_VDF.cpp)
            signe_terme = 1;
// Fin modif YB
// flux = signe_terme*coef;
            flux = signe_terme*coef;
            resu[fac3]+= flux;
            break;
          }
        case TypeAreteBordVDF::FLUIDE_FLUIDE: //!< fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE: //!< paroi-fluide
        case TypeAreteBordVDF::SYM_SYM:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
}
void Op_Dift_VDF_var_Face_Axi::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Op_Dift_VDF_base.
Definition at line 113 of file Op_Dift_VDF_var_Face_Axi.h.
References ajouter_contribution().
{
  ajouter_contribution(inco, matrice);
}
void Op_Dift_VDF_var_Face_Axi::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Op_Dift_VDF_base.
Definition at line 122 of file Op_Dift_VDF_var_Face_Axi.h.
References contribue_au_second_membre().
{
  contribue_au_second_membre(resu);
}
Objet_U * Op_Dift_VDF_var_Face_Axi::cree_instance () [static]
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
const Champ_base & Op_Dift_VDF_var_Face_Axi::diffusivite () const [virtual]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 82 of file Op_Dift_VDF_var_Face_Axi.cpp.
References diffusivite_.
{
  return diffusivite_;
}
void Op_Dift_VDF_var_Face_Axi::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 101 of file Op_Dift_VDF_var_Face_Axi.h.
{
  Op_VDF_Face::dimensionner(la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice);
}
int Op_Dift_VDF_var_Face_Axi::duplique () const [virtual]
Implements Op_Dift_VDF_Face_base.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
const Type_info * Op_Dift_VDF_var_Face_Axi::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
const Type_info * Op_Dift_VDF_var_Face_Axi::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
void Op_Dift_VDF_var_Face_Axi::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 105 of file Op_Dift_VDF_var_Face_Axi.cpp.
References le_modele_turbulence, O_U_Ptr::non_nul(), DoubleTab::ref(), and tau_tan.
{
  if (le_modele_turbulence->loi_paroi().non_nul())
    {
      tau_tan.ref(le_modele_turbulence->loi_paroi()->Cisaillement_paroi());
    }
}
void Op_Dift_VDF_var_Face_Axi::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 105 of file Op_Dift_VDF_var_Face_Axi.h.
References la_zcl_vdf, la_zone_vdf, Ref_Zone_Cl_VDF::valeur(), and Ref_Zone_VDF::valeur().
{
  Op_VDF_Face::modifier_pour_Cl( la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice,  secmem);
}
Sortie & Op_Dift_VDF_var_Face_Axi::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 30 of file Op_Dift_VDF_var_Face_Axi.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Dift_VDF_var_Face_Axi::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 35 of file Op_Dift_VDF_var_Face_Axi.cpp.
{
  return s ;
}
const Op_Dift_VDF_var_Face_Axi & Op_Dift_VDF_var_Face_Axi::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
Op_Dift_VDF_var_Face_Axi & Op_Dift_VDF_var_Face_Axi::self_cast (Objet_U & r) [static]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
unsigned Op_Dift_VDF_var_Face_Axi::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Op_Dift_VDF_var_Face_Axi.cpp.
Member Data Documentation
Ref_Champ_base Op_Dift_VDF_var_Face_Axi::diffusivite_ [protected]
Definition at line 83 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer_diffusivite(), and diffusivite().
IntTab Op_Dift_VDF_var_Face_Axi::elem_faces [protected]
Definition at line 94 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
IntTab Op_Dift_VDF_var_Face_Axi::face_voisins [protected]
Definition at line 93 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
Ref_Champ_Face Op_Dift_VDF_var_Face_Axi::inconnue [protected]
Definition at line 80 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
const Type_info Op_Dift_VDF_var_Face_Axi::info_obj [static]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 55 of file Op_Dift_VDF_var_Face_Axi.h.
Ref_Zone_Cl_VDF Op_Dift_VDF_var_Face_Axi::la_zcl_vdf [protected]
Definition at line 82 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), contribue_au_second_membre(), and modifier_pour_Cl().
Ref_Zone_VDF Op_Dift_VDF_var_Face_Axi::la_zone_vdf [protected]
Definition at line 81 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), calculer_dt_stab(), contribue_au_second_membre(), and modifier_pour_Cl().
Ref_Mod_turb_hyd_base Op_Dift_VDF_var_Face_Axi::le_modele_turbulence [protected]
Definition at line 79 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by associer_modele_turbulence(), and mettre_a_jour().
IntVect Op_Dift_VDF_var_Face_Axi::orientation [protected]
Definition at line 88 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Dift_VDF_var_Face_Axi::porosite [protected]
Definition at line 89 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
IntTab Op_Dift_VDF_var_Face_Axi::Qdm [protected]
Definition at line 92 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Dift_VDF_var_Face_Axi::surface [protected]
Definition at line 86 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleTab Op_Dift_VDF_var_Face_Axi::tau_tan [protected]
Definition at line 85 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), contribue_au_second_membre(), and mettre_a_jour().
IntVect Op_Dift_VDF_var_Face_Axi::type_arete_bord [protected]
Definition at line 95 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Dift_VDF_var_Face_Axi::volumes_entrelaces [protected]
Definition at line 87 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
DoubleTab Op_Dift_VDF_var_Face_Axi::xp [protected]
Definition at line 90 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by associer().
DoubleTab Op_Dift_VDF_var_Face_Axi::xv [protected]
Definition at line 91 of file Op_Dift_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_var_Face_Axi.h
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_var_Face_Axi.cpp