TRUST: Champ_Generique_Gradient Class Reference
Champ_Generique_Gradient Class Reference
class Champ_Generique_Gradient
Champ destine a post-traiter le gradient d un champ generique
La classe porte un operateur statistique "gradient"
#include <Champ_Generique_Gradient.h>
Public Member Functions
Champ_Generique_Gradient ()
~Champ_Generique_Gradient ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Motcle get_directive_pour_discr () const
virtual const Champ_base & get_champ (Champ &espace_stockage) const
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const
const Operateur_base & Operateur () const
Operateur_base & Operateur ()
void completer (const Postraitement_base &post)
void nommer_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Generique_Gradient & self_cast (Objet_U &)
static const
Champ_Generique_Gradient & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Operateur_Grad Op_Grad_
Detailed Description
class Champ_Generique_Gradient
Champ destine a post-traiter le gradient d un champ generique
La classe porte un operateur statistique "gradient"
Definition at line 45 of file Champ_Generique_Gradient.h.
Constructor & Destructor Documentation
Champ_Generique_Gradient::Champ_Generique_Gradient ()
Definition at line 29 of file Champ_Generique_Gradient.cpp.
Champ_Generique_Gradient::~Champ_Generique_Gradient ()
Definition at line 29 of file Champ_Generique_Gradient.cpp.
Member Function Documentation
void Champ_Generique_Gradient::completer (const Postraitement_base & post) [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 43 of file Champ_Generique_Gradient.cpp.
References Operateur_base::associer_eqn(), MorEqn::associer_eqn(), Cerr, Probleme_base::equation(), Process::exit(), finl, Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Operateur_Grad::l_op_base(), Equation_base::le_nom(), O_U_Ptr::le_nom(), Field_base::le_nom(), Probleme_base::nombre_d_equations(), Op_Grad_, Objet_U::que_suis_je(), ref_cast, sub_type, Operateur_Grad::typer(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Probleme_base& Pb = get_ref_pb_base();
  if (sub_type(Champ_Generique_refChamp,get_source(0)))
    {
      Champ espace_stockage;
      const Champ_base& mon_champ = get_source(0).get_champ(espace_stockage);
      if (sub_type(Champ_Inc_base,mon_champ))
        {
          const Champ_Inc_base& mon_champ_inc = ref_cast(Champ_Inc_base,mon_champ);
          if ( (mon_champ_inc.le_nom()=="pression") || ((mon_champ_inc.le_nom()!="vitesse") && (mon_champ_inc.que_suis_je()=="Champ_P1NC"))
               || ((mon_champ_inc.le_nom()!="vitesse") && (mon_champ_inc.que_suis_je()=="Champ_P0_VDF")) )
            {
// On recupere l equation alors qu elle n est pas encore associee au Champ_Inc
// On parcours les equatiosn du probleme et on identifie celle qui correspond au champ inconnu
              int nb_eq = Pb.nombre_d_equations();
              int i=0;
              while (i<nb_eq)
                {
                  const Equation_base& eq_test = Pb.equation(i);
                  if ((eq_test.inconnue().le_nom() == mon_champ_inc.le_nom()) || ((i==0) && (mon_champ_inc.le_nom()=="pression") &&
                                                                                  (eq_test.le_nom()!="Conduction")))
                    break;
                  i++;
                }
              const Equation_base& eqn = Pb.equation(i);
              Op_Grad_.associer_eqn(eqn);
              Op_Grad_.typer();
              Op_Grad_.l_op_base().associer_eqn(eqn);
              const Zone_dis& zdis = eqn.zone_dis();
              const Zone_Cl_dis& zcl = eqn.zone_Cl_dis();
              const Champ_Inc& inco = eqn.inconnue();
              Op_Grad_->associer(zdis, zcl, inco);
            }
          else
            {
              Cerr<<"We can apply a Champ_Generique_Gradient only to the pressure field"<<finl;
              Cerr<<"or to a field of type Champ_P1NC or Champ_P0_VDF at one component"<<finl;
              exit();
            }
        }
      else
        {
          Cerr<<"We can apply a Champ_Generique_Gradient only to an unknown field of the problem"<<finl;
          exit();
        }
    }
}
Objet_U * Champ_Generique_Gradient::cree_instance () [static]
Definition at line 29 of file Champ_Generique_Gradient.cpp.
int Champ_Generique_Gradient::duplique () const [virtual]
Implements Champ_Generique_Operateur_base.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
const Champ_base & Champ_Generique_Gradient::get_champ (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 118 of file Champ_Generique_Gradient.cpp.
References Solveur_Masse::appliquer(), Operateur_Grad::calculer(), Cerr, Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Objet_U::dimension, DoubleVect::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), finl, Champ_Generique_base::get_champ(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), O_U_Ptr::non_nul(), Op_Grad_, Objet_U::que_suis_je(), Equation_base::solv_masse(), Deriv_Champ_base::valeur(), Deriv_Operateur_Grad_base::valeur(), Champ::valeurs(), Champ_Proto::valeurs(), and vectoriel.
{
  Champ source_espace_stockage;
  const Champ_base& source = get_source(0).get_champ(source_espace_stockage);
  if (Op_Grad_.non_nul())
    {
      Champ_Fonc es_tmp;
      espace_stockage = creer_espace_stockage(vectoriel,dimension,es_tmp);
      Op_Grad_.calculer(source.valeurs(),espace_stockage.valeurs());
      Nom type_op = Op_Grad_.valeur().que_suis_je();
      if ((type_op!="Op_Grad_P1NC_to_P0") && (type_op!="Op_Grad_P0_to_Face"))
        Op_Grad_.equation().solv_masse().appliquer(espace_stockage.valeurs());
    }
  else
    {
      const Noms nom = get_source(0).get_property("nom");
      Cerr<<"We can apply a Champ_Generique_Gradient only to the pressure field"<<finl;
      Cerr<<"or to a field of type Champ_P1NC or Champ_P0_VDF at one component"<<finl;
      Cerr<<"The space of storage of field treated here "<<nom[0]<<" is of type"<<source.que_suis_je()<<finl;
      exit();
    }
  DoubleTab& espace_valeurs = espace_stockage->valeurs();
  espace_valeurs.echange_espace_virtuel();
  return espace_stockage.valeur();
}
const Champ_base & Champ_Generique_Gradient::get_champ_without_evaluation (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 100 of file Champ_Generique_Gradient.cpp.
References Cerr, Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Objet_U::dimension, Process::exit(), finl, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), O_U_Ptr::non_nul(), Op_Grad_, Deriv_Champ_base::valeur(), and vectoriel.
{
  if (Op_Grad_.non_nul())
    {
      Champ_Fonc es_tmp;
      espace_stockage = creer_espace_stockage(vectoriel,dimension,es_tmp);
    }
  else
    {
      const Noms nom = get_source(0).get_property("nom");
      Cerr<<"We can apply a Champ_Generique_Gradient only to the pressure field"<<finl;
      Cerr<<"or to a field of type Champ_P1NC or Champ_P0_VDF at one component"<<finl;
      exit();
    }
  return espace_stockage.valeur();
}
const Motcle Champ_Generique_Gradient::get_directive_pour_discr () const [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 250 of file Champ_Generique_Gradient.cpp.
References Op_Grad_, Objet_U::que_suis_je(), and Deriv_Operateur_Grad_base::valeur().
{
  Motcle directive;
  Nom type_op = Op_Grad_.valeur().que_suis_je();
  if (type_op=="Op_Grad_P1NC_to_P0")
    directive = "champ_elem";
  else
    directive = "gradient_pression";
  return directive;
}
const Type_info * Champ_Generique_Gradient::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
Entity Champ_Generique_Gradient::get_localisation (const int index = -1) const [virtual]
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 220 of file Champ_Generique_Gradient.cpp.
References Cerr, ELEMENT, FACE, finl, Champ_Generique_base::nom_post_, Op_Grad_, Objet_U::que_suis_je(), and Deriv_Operateur_Grad_base::valeur().
{
  Entity loc;
  Nom type_op = Op_Grad_.valeur().que_suis_je();
  if ((type_op=="Op_Grad_P1NC_to_P0") && (index <= 0))
    loc = ELEMENT;
  else if ((type_op=="Op_Grad_P0_to_Face") && (index <= 0))
    loc=FACE;
  else
    {
      Cerr << "Error of type : Gradient operator " << type_op << " is not possible for the defined field " << nom_post_ << finl;
      throw Champ_Generique_erreur("INVALID");
    }
  return loc;
}
const Noms Champ_Generique_Gradient::get_property (const Motcle & query) const [virtual]
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 148 of file Champ_Generique_Gradient.cpp.
References Objet_U::dimension, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Motcles::search().
{
// Creation des composantes serait a faire de maniere dynamique (Gradient_...)
  Motcles motcles(2);
  motcles[0] = "composantes";
  motcles[1] = "unites";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        /*
          const Noms compo_cibles = get_source(0).get_property("composantes");
          ///int size = compo_cibles.size();
          ///const Noms nom = get_source(0).get_property("nom");
          ///Nom nom_champ = nom[0];
          Nom nom_champ = "pression";
          //Valable si Champ_Fonc_P1NC
          Noms mots(dimension);
          Nom compo_temp="gradient_";
          for (int i=0; i<dimension; i++) {
          if (i==0) {
          mots[i] = compo_temp+nom_champ +"X";
          }
          else if (i==1) {
          mots[i] = compo_temp+nom_champ +"Y";;
          }
          else if (i==2) {
          mots[i] = compo_temp+nom_champ +"Z";
          }
          }
          return mots;
          break;
// Actuellement choix fait d ajouter simplement numero de composante
        */
        int nb_comp = dimension;
        Noms compo(nb_comp);
        for (int i=0; i<nb_comp; i++)
          {
            Nom nume(i);
            compo[i] = nom_post_+nume;
          }
        return compo;
        break;
      }
    case 1:
      {
        Noms unites(dimension);
        Noms source_unites = get_source(0).get_property("unites");
        for (int i=0; i<dimension; i++)
          {
            unites[i] = source_unites[0]+"/m";
          }
        return unites;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
const Type_info * Champ_Generique_Gradient::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
void Champ_Generique_Gradient::nommer_source () [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 237 of file Champ_Generique_Gradient.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_post_source =  "Gradient_";
      nom_post_source +=  nom_champ_source;
      nommer(nom_post_source);
    }
}
Operateur_base & Champ_Generique_Gradient::Operateur () [inline, virtual]
Implements Champ_Generique_Operateur_base.
Definition at line 74 of file Champ_Generique_Gradient.h.
References Op_Grad_, and Deriv_Operateur_Grad_base::valeur().
{
  return Op_Grad_.valeur();
}
const Operateur_base & Champ_Generique_Gradient::Operateur () const [inline, virtual]
Implements Champ_Generique_Operateur_base.
Definition at line 69 of file Champ_Generique_Gradient.h.
References Op_Grad_, and Deriv_Operateur_Grad_base::valeur().
{
  return Op_Grad_.valeur();
}
Sortie & Champ_Generique_Gradient::printOn (Sortie & os) const [protected, virtual]
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 32 of file Champ_Generique_Gradient.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Generique_Gradient::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 37 of file Champ_Generique_Gradient.cpp.
{
  Champ_Generique_Operateur_base::readOn(s);
  return s ;
}
Champ_Generique_Gradient & Champ_Generique_Gradient::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
const Champ_Generique_Gradient & Champ_Generique_Gradient::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
unsigned Champ_Generique_Gradient::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Champ_Generique_Gradient.cpp.
Member Data Documentation
const Type_info Champ_Generique_Gradient::info_obj [static]
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 48 of file Champ_Generique_Gradient.h.
Operateur_Grad Champ_Generique_Gradient::Op_Grad_ [protected]
Definition at line 65 of file Champ_Generique_Gradient.h.
Referenced by completer(), get_champ(), get_champ_without_evaluation(), get_directive_pour_discr(), get_localisation(), and Operateur().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Gradient.h
src/Kernel/Champs/Champ_Generique_Gradient.cpp