TRUST: DoubleTrav Class Reference
DoubleTrav Class Reference
Tableau de travail a n entrees pour n<= 4
C'est un DoubleTab avec allocation dans un pool de memoire gere par
la_memoire. L'allocation initiale est realisee avec alloc_temp_storage.
#include <DoubleTrav.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTrav ()
DoubleTrav (int n)
DoubleTrav (int n1, int n2)
DoubleTrav (int n1, int n2, int n3)
DoubleTrav (int n1, int n2, int n3, int n4)
DoubleTrav (const DoubleTab &)
ATTENTION: non standard, voir la description !!!
DoubleTrav (const DoubleVect &)
ATTENTION: non standard, voir la description !!!
DoubleTrav (const DoubleTrav &)
ATTENTION: non standard, voir la description !!! Operateurs copie.
DoubleTrav & operator= (const DoubleTrav &)
Operateur copie (on ne veut pas l'operateur par defaut)
DoubleTrav & operator= (const DoubleTab &)
Operateur copie d'un tableau (copie structure ET contenu)
DoubleTrav & operator= (const DoubleVect &)
Operateur copie d'un tableau (copie structure ET contenu)
DoubleTrav & operator= (double d)
Comme on surcharge l'operateur copie, il faut redefinir celui-la aussi.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static DoubleTrav & self_cast (Objet_U &)
static const DoubleTrav & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Appel a DoubleTab::printOn.
virtual Entree & readOn (Entree &)
Appel a DoubleTab::readOn.
Detailed Description
Tableau de travail a n entrees pour n<= 4
C'est un DoubleTab avec allocation dans un pool de memoire gere par
la_memoire. L'allocation initiale est realisee avec alloc_temp_storage.
Definition at line 40 of file DoubleTrav.h.
Constructor & Destructor Documentation
DoubleTrav::DoubleTrav ()
Definition at line 51 of file DoubleTrav.cpp.
References ArrOfDouble::set_mem_storage(), and ArrOfDouble::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
}
DoubleTrav::DoubleTrav (int n)
Definition at line 57 of file DoubleTrav.cpp.
References DoubleTab::resize(), ArrOfDouble::set_mem_storage(), and ArrOfDouble::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n);
}
DoubleTrav::DoubleTrav (int n1, int n2)
Definition at line 64 of file DoubleTrav.cpp.
References DoubleTab::resize(), ArrOfDouble::set_mem_storage(), and ArrOfDouble::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2);
}
DoubleTrav::DoubleTrav (int n1, int n2, int n3)
Definition at line 74 of file DoubleTrav.cpp.
References DoubleTab::resize(), ArrOfDouble::set_mem_storage(), and ArrOfDouble::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2, n3);
}
DoubleTrav::DoubleTrav (int n1, int n2, int n3, int n4)
Definition at line 81 of file DoubleTrav.cpp.
References DoubleTab::resize(), ArrOfDouble::set_mem_storage(), and ArrOfDouble::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2, n3, n4);
}
DoubleTrav::DoubleTrav (const DoubleTab & tab)
ATTENTION: non standard, voir la description !!!
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 90 of file DoubleTrav.cpp.
References DoubleTab::copy(), Array_base::NOCOPY_NOINIT, operator=(), ArrOfDouble::set_mem_storage(), ArrOfDouble::TEMP_STORAGE, and zero_double.
{
  set_mem_storage(TEMP_STORAGE);
  DoubleTab::copy(tab, Array_base::NOCOPY_NOINIT);
  DoubleTab::operator=(zero_double);
}
DoubleTrav::DoubleTrav (const DoubleVect & tab)
ATTENTION: non standard, voir la description !!!
Constructeur par copie
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 112 of file DoubleTrav.cpp.
References DoubleVect::get_md_vector(), DoubleVect::line_size(), Array_base::NOCOPY_NOINIT, operator=(), DoubleTab::resize(), DoubleVect::set_line_size_(), DoubleTab::set_md_vector(), ArrOfDouble::set_mem_storage(), ArrOfDouble::size_array(), ArrOfDouble::TEMP_STORAGE, and zero_double.
{
  set_mem_storage(TEMP_STORAGE);
  set_line_size_(tab.line_size());
  DoubleTab::resize(tab.size_array(), Array_base::NOCOPY_NOINIT);
  set_md_vector(tab.get_md_vector());
  DoubleTab::operator=(zero_double);
}
DoubleTrav::DoubleTrav (const DoubleTrav & tab)
ATTENTION: non standard, voir la description !!! Operateurs copie.
Constructeur par copie
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 101 of file DoubleTrav.cpp.
References DoubleTab::copy(), Array_base::NOCOPY_NOINIT, operator=(), ArrOfDouble::set_mem_storage(), ArrOfDouble::TEMP_STORAGE, and zero_double.
                                           :DoubleTab()
{
  set_mem_storage(TEMP_STORAGE);
  DoubleTab::copy(tab, Array_base::NOCOPY_NOINIT);
  DoubleTab::operator=(zero_double);
}
Member Function Documentation
Objet_U * DoubleTrav::cree_instance () [static]
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
int DoubleTrav::duplique () const [virtual]
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
const Type_info * DoubleTrav::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
const Type_info * DoubleTrav::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
DoubleTrav & DoubleTrav::operator= (const DoubleTab & tab)
Operateur copie d'un tableau (copie structure ET contenu)
Reimplemented from DoubleTab.
Definition at line 131 of file DoubleTrav.cpp.
References operator=().
{
// ATTENTION: note aux programmeurs
// La declaration de cet operateur est indispensable, sinon
// DoubleTab b;
// DoubleTrav a;
// a = b
// est traduit en
// DoubleTrav tmp(b); // copie la structure mais met les valeurs a zero
// a.operator=(tmp);
  DoubleTab::operator=(tab);
  return *this;
}
DoubleTrav & DoubleTrav::operator= (const DoubleTrav & tab)
Operateur copie (on ne veut pas l'operateur par defaut)
Definition at line 123 of file DoubleTrav.cpp.
Referenced by DoubleTrav(), and operator=().
{
  DoubleTab::operator=(tab);
  return *this;
}
DoubleTrav & DoubleTrav::operator= (double d)
Comme on surcharge l'operateur copie, il faut redefinir celui-la aussi.
Reimplemented from DoubleTab.
Definition at line 161 of file DoubleTrav.cpp.
References operator=().
{
  DoubleTab::operator=(d);
  return *this;
}
DoubleTrav & DoubleTrav::operator= (const DoubleVect & tab)
Operateur copie d'un tableau (copie structure ET contenu)
Reimplemented from DoubleTab.
Definition at line 146 of file DoubleTrav.cpp.
References operator=().
{
// ATTENTION: note aux programmeurs
// La declaration de cet operateur est indispensable, sinon
// DoubleTab b;
// DoubleTrav a;
// a = b
// est traduit en
// DoubleTrav tmp(b); // copie la structure mais met les valeurs a zero
// a.operator=(tmp);
  DoubleTab::operator=(tab);
  return *this;
}
Sortie & DoubleTrav::printOn (Sortie & x) const [protected, virtual]
Appel a DoubleTab::printOn.
Reimplemented from DoubleTab.
Definition at line 36 of file DoubleTrav.cpp.
{
  DoubleTab::printOn(os);
  return os;
}
Entree & DoubleTrav::readOn (Entree & is) [protected, virtual]
Appel a DoubleTab::readOn.
Reimplemented from DoubleTab.
Definition at line 43 of file DoubleTrav.cpp.
{
  DoubleTab::readOn(is);
  return is;
}
DoubleTrav & DoubleTrav::self_cast (Objet_U & r) [static]
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
const DoubleTrav & DoubleTrav::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
unsigned DoubleTrav::taille_memoire () const [virtual]
Reimplemented from DoubleTab.
Definition at line 29 of file DoubleTrav.cpp.
Member Data Documentation
const Type_info DoubleTrav::info_obj [static]
Reimplemented from DoubleTab.
Definition at line 42 of file DoubleTrav.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/DoubleTrav.h
src/Kernel/Math/DoubleTrav.cpp