TRUST: Op_Conv_EF_Stab_CoviMAC_Elem Class Reference
Op_Conv_EF_Stab_CoviMAC_Elem Class Reference
: class Op_Conv_EF_Stab_CoviMAC_Elem
<Description of class Op_Conv_EF_Stab_CoviMAC_Elem>
#include <Op_Conv_EF_Stab_CoviMAC_Elem.h>
Public Member Functions
Op_Conv_EF_Stab_CoviMAC_Elem ()
~Op_Conv_EF_Stab_CoviMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void preparer_calcul ()
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
double calculer_dt_stab () const
Calcul dt_stab.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
void creer_champ (const Motcle &motlu)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Op_Conv_EF_Stab_CoviMAC_Elem & self_cast (Objet_U &)
static const
Op_Conv_EF_Stab_CoviMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
double alpha
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
std::vector< Champ_Inc > cc_phases_
Motcles noms_cc_phases_
std::vector< Champ_Inc > vd_phases_
Motcles noms_vd_phases_
std::vector< Champ_Inc > x_phases_
Motcles noms_x_phases_
Detailed Description
: class Op_Conv_EF_Stab_CoviMAC_Elem
<Description of class Op_Conv_EF_Stab_CoviMAC_Elem>
Definition at line 37 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Constructor & Destructor Documentation
Op_Conv_EF_Stab_CoviMAC_Elem::Op_Conv_EF_Stab_CoviMAC_Elem ()
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
Op_Conv_EF_Stab_CoviMAC_Elem::~Op_Conv_EF_Stab_CoviMAC_Elem ()
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
Member Function Documentation
void Op_Conv_EF_Stab_CoviMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
double Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 125 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References IntTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Op_Conv_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), max(), min(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Ref_Zone_CoviMAC::valeur(), Op_Conv_CoviMAC_base::vitesse_, and Zone_VF::volumes().
{
  double dt = 1e10;
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face(), &ve = zone.volumes(), &pe = zone.porosite_elem();
  const DoubleTab& vit = vitesse_->valeurs(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  int i, e, f, n, N = vit.line_size();
  DoubleTrav flux(N); //somme des flux pf * |f| * vf
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) for (n = 0; n < N; n++)
          flux(n) += pf(f) * fs(f) * max((e == f_e(f, 1) ? 1 : -1) * vit(f, n), 0.); //seul le flux entrant dans e compte
      for (n = 0; n < N; n++) if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) dt = min(dt, pe(e) * ve(e) / flux(n));
    }
  return Process::mp_min(dt);
}
void Op_Conv_EF_Stab_CoviMAC_Elem::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 55 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
{ }; //of course
Objet_U * Op_Conv_EF_Stab_CoviMAC_Elem::cree_instance () [static]
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
void Op_Conv_EF_Stab_CoviMAC_Elem::creer_champ (const Motcle & motlu) [virtual]
Reimplemented from Operateur_base.
Definition at line 218 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References Champs_compris::ajoute_champ(), cc_phases_, Operateur_base::champs_compris_, Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Motcles::rang(), vd_phases_, and x_phases_.
{
  Op_Conv_CoviMAC_base::creer_champ(motlu);
  int i = noms_cc_phases_.rang(motlu), j = noms_vd_phases_.rang(motlu), k = noms_x_phases_.rang(motlu);
  if (i >= 0 && !cc_phases_[i].non_nul())
    {
      equation().discretisation().discretiser_champ("vitesse", equation().zone_dis(), noms_cc_phases_[i], "kg/m2/s",dimension, 1, 0, cc_phases_[i]);
      champs_compris_.ajoute_champ(cc_phases_[i]);
    }
  if (j >= 0 && !vd_phases_[j].non_nul())
    {
      equation().discretisation().discretiser_champ("vitesse", equation().zone_dis(), noms_vd_phases_[j], "m/s",dimension, 1, 0, vd_phases_[j]);
      champs_compris_.ajoute_champ(vd_phases_[j]);
    }
  if (k >= 0 && !x_phases_[k].non_nul())
    {
      equation().discretisation().discretiser_champ("temperature", equation().zone_dis(), noms_x_phases_[k], "m/s",1, 1, 0, x_phases_[k]);
      champs_compris_.ajoute_champ(x_phases_[k]);
    }
}
void Op_Conv_EF_Stab_CoviMAC_Elem::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Conv_EF_Stab_CoviMAC_Elem::duplique () const [virtual]
Implements Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
const Type_info * Op_Conv_EF_Stab_CoviMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
int Op_Conv_EF_Stab_CoviMAC_Elem::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
  {
    return 1;
  };
const Type_info * Op_Conv_EF_Stab_CoviMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
void Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
< E Saikali : m-1 car si M > 1, on obtient m = M à la fin de la boucle...
Reimplemented from Operateur_base.
Definition at line 239 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References alpha, cc_phases_, Equation_base::champ_convecte(), Champ_Inc_base::changer_temps(), Objet_U::dimension, MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Conv_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Champ_Face_CoviMAC::update_ve(), valeur(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), vd_phases_, Op_Conv_CoviMAC_base::vitesse_, and x_phases_.
{
  Op_Conv_CoviMAC_base::mettre_a_jour(temps);
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins();
  const Champ_Inc_base& cc = equation().champ_convecte();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces();
  const DoubleTab& vit = vitesse_->valeurs(), &vcc = equation().champ_convecte().valeurs(), bcc = cc.valeur_aux_bords(), &alp = equation().inconnue().valeurs();
  DoubleTab balp;
  if (vd_phases_.size()) balp = equation().inconnue().valeur().valeur_aux_bords();
  int i, e, f, d, D = dimension, n, m, N = vcc.line_size(), nf_tot = zone.nb_faces_tot(), M = vit.line_size();
  DoubleTrav cc_f(N); //valeur du champ convecte aux faces
  /* flux aux bords */
  for (f = 0; f < zone.premiere_face_int(); f++)
    {
      for (cc_f = 0, i = 0; i < 2; i++) for (e = f_e(f, i), n = 0, m = 0; n < N; n++, m += (M > 1))
          cc_f(n) +=  (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * (e >= 0 ? vcc(e, n) : bcc(f, n));
      const int mm = ( m == 0 ) ? m : m-1; //!< E Saikali : m-1 car si M > 1, on obtient m = M à la fin de la boucle...
      for (n = 0; n < N; n++) flux_bords_(f, n) = pf(f) * fs(f) * vit(f, mm) * cc_f(n);
    }
  if (cc_phases_.size()) for (n = 0, m = 0; n < N; n++, m += (M > 1)) if (cc_phases_[n].non_nul()) /* mise a jour des champs de debit */
        {
          Champ_Face_CoviMAC& c_ph = ref_cast(Champ_Face_CoviMAC, cc_phases_[n].valeur());
          DoubleTab& v_ph = c_ph.valeurs();
          /* on remplit la partie aux faces, puis on demande au champ d'interpoler aux elements */
          for (f = 0; f < zone.nb_faces(); f++)
            {
              for (v_ph(f) = 0, i = 0; i < 2; i++)
                v_ph(f) += (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * ((e = f_e(f, i)) >= 0 ? vcc(e, n) : bcc(f, n));
              v_ph(f) *= vit(f, m);
            }
          c_ph.update_ve(v_ph); //interpolation face -> element d'ordre 1 (sans matrices)
          for (f = 0; f < zone.nb_faces(); f++) v_ph(f) *= pf(f);
          for (e = 0; e < zone.nb_elem(); e++) for (d = 0; d < D; d++) v_ph(nf_tot + D * e + d) *= pe(e); //pour repasser en debitant
          c_ph.changer_temps(temps);
        }
  if (vd_phases_.size()) for (n = 0, m = 0; n < N; n++, m += (M > 1)) if (vd_phases_[n].non_nul()) /* mise a jour des champs de vitesse debitante */
        {
          Champ_Face_CoviMAC& c_ph = ref_cast(Champ_Face_CoviMAC, vd_phases_[n].valeur());
          DoubleTab& v_ph = c_ph.valeurs();
          /* on remplit la partie aux faces, puis on demande au champ d'interpoler aux elements */
          for (f = 0; f < zone.nb_faces(); f++)
            {
              for (v_ph(f) = 0, i = 0; i < 2; i++)
                v_ph(f) += (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * ((e = f_e(f, i)) >= 0 ? alp(e, n) : balp(f, n));
              v_ph(f) *= vit(f, m);
            }
          c_ph.update_ve(v_ph); //interpolation face -> element d'ordre 1 (sans matrices)
          for (f = 0; f < zone.nb_faces(); f++) v_ph(f) *= pf(f);
          for (e = 0; e < zone.nb_elem(); e++) for (d = 0; d < D; d++) v_ph(nf_tot + D * e + d) *= pe(e); //pour repasser en debitant
          c_ph.changer_temps(temps);
        }
  DoubleTrav G(N), v2(N);
  double Gt;
  if (x_phases_.size()) for (e = 0; e < zone.nb_elem(); e++) //titre : aux elements
      {
        for (v2 = 0, d = 0; d < D; d++) for (n = 0; n < N; n++) v2(n) += std::pow(vit(nf_tot + D * e + d, n), 2);
        for (Gt = 0, n = 0; n < N; Gt += G(n), n++) G(n) = vcc(e, n) * sqrt(v2(n));
        for (n = 0; n < N; n++) if (x_phases_[n].non_nul()) x_phases_[n]->valeurs()(e) = Gt ? G(n) / Gt : 0;
      }
  if (x_phases_.size()) for (n = 0; n < N; n++) if (x_phases_[n].non_nul()) x_phases_[n]->changer_temps(temps);
}
void Op_Conv_EF_Stab_CoviMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 44 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
{ };
void Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul (void) [virtual]
Reimplemented from Operateur_base.
Definition at line 112 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References Cerr, Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::inconnue(), Equation_base::init_champ_convecte(), Zone_CoviMAC::init_equiv(), Zone::joint(), Op_Conv_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), Zone::nb_joints(), Zone_VF::premiere_face_int(), DoubleTab::resize(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
{
  Op_Conv_CoviMAC_base::preparer_calcul();
  /* au cas ou... */
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  zone.init_equiv(), equation().init_champ_convecte();
  flux_bords_.resize(zone.premiere_face_int(), equation().inconnue().valeurs().line_size());
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 2)
    Cerr << "Op_Conv_EF_Stab_CoviMAC_Elem : largeur de joint insuffisante (minimum 2)!" << finl, Process::exit();
}
Sortie & Op_Conv_EF_Stab_CoviMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 54 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
{
  Op_Conv_CoviMAC_base::printOn( os );
  return os;
}
Entree & Op_Conv_EF_Stab_CoviMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 72 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References Champs_compris::ajoute_nom_compris(), Param::ajouter(), alpha, cc_phases_, Operateur_base::champs_compris_, vect_impl::dimensionner(), MorEqn::equation(), Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Objet_U::que_suis_je(), ref_cast, sub_type, vd_phases_, and x_phases_.
{
  Op_Conv_CoviMAC_base::readOn( is );
  if (que_suis_je() == "Op_Conv_EF_Stab_CoviMAC_Elem_CoviMAC") //on n'est pas dans Op_Conv_Amont/Centre
    {
      Param param(que_suis_je());
      param.ajouter("alpha", &alpha);            //!< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
      param.lire_avec_accolades_depuis(is);
    }
  if (sub_type(Masse_Multiphase, equation())) //convection dans Masse_Multiphase -> champs de debit / titre
    {
      const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, equation().probleme());
      noms_cc_phases_.dimensionner(pb.nb_phases()), cc_phases_.resize(pb.nb_phases());
      noms_vd_phases_.dimensionner(pb.nb_phases()), vd_phases_.resize(pb.nb_phases());
      noms_x_phases_.dimensionner(pb.nb_phases()),   x_phases_.resize(pb.nb_phases());
      for (int i = 0; i < pb.nb_phases(); i++)
        {
          champs_compris_.ajoute_nom_compris(noms_cc_phases_[i] = Nom("debit_") + pb.nom_phase(i));
          champs_compris_.ajoute_nom_compris(noms_vd_phases_[i] = Nom("vitesse_debitante_") + pb.nom_phase(i));
          champs_compris_.ajoute_nom_compris(noms_x_phases_[i] = Nom("titre_") + pb.nom_phase(i));
        }
    }
  return is;
}
Op_Conv_EF_Stab_CoviMAC_Elem & Op_Conv_EF_Stab_CoviMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
const Op_Conv_EF_Stab_CoviMAC_Elem & Op_Conv_EF_Stab_CoviMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
unsigned Op_Conv_EF_Stab_CoviMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
Member Data Documentation
double Op_Conv_EF_Stab_CoviMAC_Elem::alpha
Definition at line 61 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by Travail_pression_CoviMAC::ajouter_blocs(), mettre_a_jour(), Op_Conv_Centre_CoviMAC_Elem::readOn(), Op_Conv_Amont_CoviMAC_Elem::readOn(), and readOn().
std::vector<Champ_Inc> Op_Conv_EF_Stab_CoviMAC_Elem::cc_phases_ [protected]
Definition at line 65 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
const Type_info Op_Conv_EF_Stab_CoviMAC_Elem::info_obj [static]
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Elem, and Op_Conv_Centre_CoviMAC_Elem.
Definition at line 40 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Motcles Op_Conv_EF_Stab_CoviMAC_Elem::noms_cc_phases_ [protected]
Definition at line 66 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), and readOn().
Motcles Op_Conv_EF_Stab_CoviMAC_Elem::noms_vd_phases_ [protected]
Definition at line 68 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), and readOn().
Motcles Op_Conv_EF_Stab_CoviMAC_Elem::noms_x_phases_ [protected]
Definition at line 70 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), and readOn().
std::vector<Champ_Inc> Op_Conv_EF_Stab_CoviMAC_Elem::vd_phases_ [protected]
Definition at line 67 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
std::vector<Champ_Inc> Op_Conv_EF_Stab_CoviMAC_Elem::x_phases_ [protected]
Definition at line 69 of file Op_Conv_EF_Stab_CoviMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Elem.h
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Elem.cpp