TRUST: Deriv_Format_Post_base Class Reference
Deriv_Format_Post_base Class Reference
#include <Format_Post.h>
Public Member Functions
~Deriv_Format_Post_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Format_Post_base ()
Deriv_Format_Post_base (const Deriv_Format_Post_base &)
const Format_Post_base & valeur () const
Format_Post_base & valeur ()
const Format_Post_base * operator-> () const
Format_Post_base * operator-> ()
const Deriv_Format_Post_base & operator= (const Format_Post_base &)
const Deriv_Format_Post_base & operator= (const Deriv_Format_Post_base &)
operator const Format_Post_base & () const
operator Format_Post_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Format_Post_base & self_cast (Objet_U &)
static const
Deriv_Format_Post_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Format_Post_base * pointeur_
Detailed Description
Definition at line 26 of file Format_Post.h.
Constructor & Destructor Documentation
Deriv_Format_Post_base::~Deriv_Format_Post_base ()
Definition at line 27 of file Format_Post.cpp.
Deriv_Format_Post_base::Deriv_Format_Post_base ()
Definition at line 27 of file Format_Post.cpp.
Deriv_Format_Post_base::Deriv_Format_Post_base (const Deriv_Format_Post_base & t)
Definition at line 27 of file Format_Post.cpp.
Member Function Documentation
Objet_U * Deriv_Format_Post_base::cree_instance () [static]
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
int Deriv_Format_Post_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
const Type_info * Deriv_Format_Post_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
const Type_info & Deriv_Format_Post_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 27 of file Format_Post.cpp.
const Type_info * Deriv_Format_Post_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
Deriv_Format_Post_base::operator const Format_Post_base & () const
Definition at line 27 of file Format_Post.cpp.
Deriv_Format_Post_base::operator Format_Post_base & ()
Definition at line 27 of file Format_Post.cpp.
const Format_Post_base * Deriv_Format_Post_base::operator-> () const [inline]
Definition at line 26 of file Format_Post.h.
: public DERIV(Format_Post_base)
Format_Post_base * Deriv_Format_Post_base::operator-> () [inline]
Definition at line 26 of file Format_Post.h.
: public DERIV(Format_Post_base)
const Deriv_Format_Post_base & Deriv_Format_Post_base::operator= (const Deriv_Format_Post_base & t)
Definition at line 27 of file Format_Post.cpp.
const Deriv_Format_Post_base & Deriv_Format_Post_base::operator= (const Format_Post_base & t)
Definition at line 27 of file Format_Post.cpp.
Sortie & Deriv_Format_Post_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
Entree & Deriv_Format_Post_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
const Deriv_Format_Post_base & Deriv_Format_Post_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
Deriv_Format_Post_base & Deriv_Format_Post_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
void Deriv_Format_Post_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 27 of file Format_Post.cpp.
unsigned Deriv_Format_Post_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Format_Post.
Definition at line 27 of file Format_Post.cpp.
const Format_Post_base & Deriv_Format_Post_base::valeur () const [inline]
Definition at line 26 of file Format_Post.h.
Referenced by Postraiter_domaine::ecrire(), latatoother::interpreter(), and Ecrire_Champ_MED::interpreter().
: public DERIV(Format_Post_base)
Format_Post_base & Deriv_Format_Post_base::valeur () [inline]
Definition at line 26 of file Format_Post.h.
: public DERIV(Format_Post_base)
Member Data Documentation
const Type_info Deriv_Format_Post_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Format_Post.
Definition at line 26 of file Format_Post.h.
Format_Post_base* Deriv_Format_Post_base::pointeur_ [private]
Definition at line 26 of file Format_Post.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post.h
src/Kernel/Framework/Format_Post.cpp