TRUST: Convection_Diffusion_Chaleur_WC Class Reference
Convection_Diffusion_Chaleur_WC Class Reference
classe Convection_Diffusion_Chaleur_WC
Cas particulier de Convection_Diffusion_Chaleur_Fluide_Dilatable_base pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
#include <Convection_Diffusion_Chaleur_WC.h>
Public Member Functions
Convection_Diffusion_Chaleur_WC ()
~Convection_Diffusion_Chaleur_WC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi)
void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
const Champ_base & vitesse_pour_transport ()
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual int sauvegarder (Sortie &) const
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
virtual int reprendre (Entree &)
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend l'inconnue de la chaleur et la pression thermodynamique.
const Operateur_Grad & operateur_gradient_WC () const
bool is_generic ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Chaleur_WC & self_cast (Objet_U &)
static const
Convection_Diffusion_Chaleur_WC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
void calculer_div_u_ou_div_rhou (DoubleTab &res) const
encore une fois desole
Protected Attributes
Operateur_Grad Op_Grad_WC_
Detailed Description
classe Convection_Diffusion_Chaleur_WC
Cas particulier de Convection_Diffusion_Chaleur_Fluide_Dilatable_base pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
Definition at line 41 of file Convection_Diffusion_Chaleur_WC.h.
Constructor & Destructor Documentation
Convection_Diffusion_Chaleur_WC::Convection_Diffusion_Chaleur_WC ()
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
Convection_Diffusion_Chaleur_WC::~Convection_Diffusion_Chaleur_WC ()
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
Member Function Documentation
void Convection_Diffusion_Chaleur_WC::calculer_div_u_ou_div_rhou (DoubleTab & res) const [protected, virtual]
encore une fois desole
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 91 of file Convection_Diffusion_Chaleur_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
{
  Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(Div,*this);
}
void Convection_Diffusion_Chaleur_WC::completer (void) [virtual]
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
< en fait c'est Equation_base::completer() mais on sais pas un jour ...
< [ABN]: In case of Front-Tracking, mass solver mass might be uninitialized ...
Reimplemented from Equation_base.
Definition at line 72 of file Convection_Diffusion_Chaleur_WC.cpp.
References Operateur_base::associer_eqn(), MorEqn::associer_eqn(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Operateur_Grad::l_op_base(), Op_Grad_WC_, Operateur_Grad::typer(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::completer(); //!< en fait c'est Equation_base::completer() mais on sais pas un jour ...
// initialiser l'operateur grad
  Op_Grad_WC_.associer_eqn(*this);
  Op_Grad_WC_.typer();
  Op_Grad_WC_.l_op_base().associer_eqn(*this);
  const Zone_dis& zdis = zone_dis();
  const Zone_Cl_dis& zcl = zone_Cl_dis();
  const Champ_Inc& inco = inconnue();
  Op_Grad_WC_->associer(zdis, zcl, inco);
}
Objet_U * Convection_Diffusion_Chaleur_WC::cree_instance () [static]
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
int Convection_Diffusion_Chaleur_WC::duplique () const [virtual]
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
const Type_info * Convection_Diffusion_Chaleur_WC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
const Type_info * Convection_Diffusion_Chaleur_WC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
bool Convection_Diffusion_Chaleur_WC::is_generic () [inline, virtual]
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 59 of file Convection_Diffusion_Chaleur_WC.h.
{ return true; }
int Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 47 of file Convection_Diffusion_Chaleur_WC.cpp.
References List_Source::add(), Cerr, Equation_base::discretisation(), finl, Equation_base::les_sources, Objet_U::que_suis_je(), and Source::typer_direct().
{
  if (mot=="convection")
    {
      Convection_Diffusion_Chaleur_Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
// l'equation de la chaleur en quasi compressible contient un terme source dP_tot/dt
      Cerr << "Source term creation of the energy equation :"<< finl;
      Source t;
      Source& so=les_sources.add(t);
      Nom type_so = "Source_WC_Chaleur_";
      Nom disc = discretisation().que_suis_je();
      if (disc=="VEFPreP1B") disc = "VEF";
      type_so += disc;
      so.typer_direct(type_so);
      so->associer_eqn(*this);
      Cerr<<so->que_suis_je()<<finl;
      Cerr << "Typing of the convection operator : ";
      return 1;
    }
  else
    return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
  return 1;
}
const Operateur_Grad& Convection_Diffusion_Chaleur_WC::operateur_gradient_WC () const [inline]
Definition at line 58 of file Convection_Diffusion_Chaleur_WC.h.
References Op_Grad_WC_.
Referenced by Source_WC_Chaleur_VEF::compute_interpolate_gradP().
{ return Op_Grad_WC_;}
int Convection_Diffusion_Chaleur_WC::preparer_calcul (void) [virtual]
Tout ce qui ne depend pas des autres problemes eventuels.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 96 of file Convection_Diffusion_Chaleur_WC.cpp.
References Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul();
  return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee();
}
Sortie & Convection_Diffusion_Chaleur_WC::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 31 of file Convection_Diffusion_Chaleur_WC.cpp.
{
  return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::printOn(is);
}
Entree & Convection_Diffusion_Chaleur_WC::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 36 of file Convection_Diffusion_Chaleur_WC.cpp.
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(is);
  return is;
}
int Convection_Diffusion_Chaleur_WC::reprendre (Entree & is) [virtual]
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend l'inconnue de la chaleur et la pression thermodynamique.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 107 of file Convection_Diffusion_Chaleur_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, Convection_Diffusion_Fluide_Dilatable_base::le_fluide, Equation_base::probleme(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Ref_Fluide_Dilatable_base::valeur().
{
  double temps = schema_temps().temps_courant();
  return Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(is,temps,*this,le_fluide.valeur(),l_inco_ch,probleme());
}
int Convection_Diffusion_Chaleur_WC::sauvegarder (Sortie & os) const [virtual]
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Returns:
int
Signification: le code de retour de Champ_Inc::sauvegarder()
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 102 of file Convection_Diffusion_Chaleur_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_base::le_fluide, Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), and Ref_Fluide_Dilatable_base::valeur().
{
  return Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(os,*this,le_fluide.valeur());
}
const Convection_Diffusion_Chaleur_WC & Convection_Diffusion_Chaleur_WC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
Convection_Diffusion_Chaleur_WC & Convection_Diffusion_Chaleur_WC::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
void Convection_Diffusion_Chaleur_WC::set_param (Param & titi) [virtual]
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 42 of file Convection_Diffusion_Chaleur_WC.cpp.
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::set_param(param);
}
unsigned Convection_Diffusion_Chaleur_WC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Convection_Diffusion_Chaleur_WC.cpp.
const Champ_base & Convection_Diffusion_Chaleur_WC::vitesse_pour_transport () [virtual]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 86 of file Convection_Diffusion_Chaleur_WC.cpp.
{
  return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport();
}
Member Data Documentation
const Type_info Convection_Diffusion_Chaleur_WC::info_obj [static]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 43 of file Convection_Diffusion_Chaleur_WC.h.
Operateur_Grad Convection_Diffusion_Chaleur_WC::Op_Grad_WC_ [protected]
Definition at line 63 of file Convection_Diffusion_Chaleur_WC.h.
Referenced by completer(), and operateur_gradient_WC().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Convection_Diffusion_Chaleur_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Convection_Diffusion_Chaleur_WC.cpp