TRUST: Eval_Amont_VDF_Elem Class Reference
Eval_Amont_VDF_Elem Class Reference
class Eval_Amont_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour la methode EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
#include <Eval_Amont_VDF_Elem.h>
Public Member Functions
Eval_Amont_VDF_Elem ()
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_face (const DoubleTab &, int, const Symetrie &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_faces_interne (const DoubleTab &, int) const
void flux_face (const DoubleTab &, int, const Symetrie &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
void coeffs_face (int, int, const Symetrie &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, double &aii, double &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Periodique &, double &aii, double &ajj) const
void coeffs_face (int, int, const NSCBC &, double &aii, double &ajj) const
void coeffs_faces_interne (int, double &aii, double &ajj) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Echange_global_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Symetrie &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Periodique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const NSCBC &, int) const
double coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int) const
double secmem_face (int, const Symetrie &, int) const
double secmem_face (int, const Neumann_sortie_libre &, int) const
double secmem_face (int, const Dirichlet_entree_fluide &, int) const
double secmem_face (int, const Dirichlet_paroi_fixe &, int) const
double secmem_face (int, const Dirichlet_paroi_defilante &, int) const
double secmem_face (int, const Neumann_paroi_adiabatique &, int) const
double secmem_face (int, const Neumann_paroi &, int) const
double secmem_face (int, int, int, const Echange_externe_impose &, int) const
double secmem_face (int, const Echange_global_impose &, int) const
double secmem_face (int, const Periodique &, int) const
double secmem_face (int, const NSCBC &, int) const
double secmem_faces_interne (int) const
void coeffs_face (int, int, const Symetrie &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Periodique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_faces_interne (int, DoubleVect &aii, DoubleVect &ajj) const
void secmem_face (int, const Symetrie &, int, DoubleVect &) const
void secmem_face (int, const Neumann_sortie_libre &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_entree_fluide &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_fixe &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_defilante &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi_adiabatique &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi &, int, DoubleVect &) const
void secmem_face (int, int, int, const Echange_externe_impose &, int, DoubleVect &) const
void secmem_face (int, const Echange_global_impose &, int, DoubleVect &) const
void secmem_face (int, const Periodique &, int, DoubleVect &) const
void secmem_faces_interne (int, DoubleVect &flux) const
Detailed Description
class Eval_Amont_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour la methode EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
See also:
Eval_Conv_VDF
Definition at line 52 of file Eval_Amont_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Amont_VDF_Elem::Eval_Amont_VDF_Elem () [inline]
Definition at line 204 of file Eval_Amont_VDF_Elem.h.
{
}
Member Function Documentation
int Eval_Amont_VDF_Elem::calculer_flux_faces_echange_externe_impose () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 211 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_echange_global_impose () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 220 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_entree_fluide () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 229 of file Eval_Amont_VDF_Elem.h.
{
  return 1;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_NSCBC () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 300 of file Eval_Amont_VDF_Elem.h.
{
  return 1;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_paroi () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 238 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_paroi_adiabatique () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 247 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_paroi_defilante () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 256 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_paroi_fixe () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 265 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_periodique () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 292 of file Eval_Amont_VDF_Elem.h.
{
  return 1;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_sortie_libre () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 274 of file Eval_Amont_VDF_Elem.h.
{
  return 1;
}
int Eval_Amont_VDF_Elem::calculer_flux_faces_symetrie () const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 283 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Symetrie & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 759 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Symetrie & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 963 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, double & aii, double & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 659 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          aii = psc;
          ajj = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          ajj = -psc;
          aii = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1398 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1370 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1343 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1068 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = psc;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
      else
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = -psc;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
      else
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1175 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = psc;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
      else
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = -psc;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
      else
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, double & aii, double & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 345 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (i != -1)
    {
      if (psc > 0)
        {
          aii = psc;
          ajj = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          ajj = -psc;
          aii = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1261 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1289 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 480 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1316 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 448 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 607 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Periodique & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1000 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
// int i = elem(face,0);
// int j = elem(face,1);
  if (psc > 0)
    {
      for(k=0; k<aii.size(); k++)
        aii(k) = psc;
      for(k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for(k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for(k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 576 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 513 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 544 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const Periodique & la_cl, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 797 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
void Eval_Amont_VDF_Elem::coeffs_face (int face, int , const NSCBC & la_cl, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 856 of file Eval_Amont_VDF_Elem.h.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Eval_Amont_VDF_Elem::coeffs_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 380 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = surface[face]*porosite[face];
  double flux;
  double val_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_imp;
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face]>0)
        flux = psc*val_imp;
      else
        flux = psc*inco[n1];
    }
  return flux;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 453 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 485 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 518 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 549 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 581 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 612 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 694 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = surface(face)*porosite(face);
  double val_ext = la_cl.val_ext(face-num1);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_ext;
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face] > 0)
        flux = psc*val_ext;
      else
        flux = psc*inco[n1];
    }
  return flux;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Symetrie & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 764 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 816 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = surface(face)*porosite(face);
  double flux;
  if (dt_vitesse[face] > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return flux;
}
double Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const NSCBC & la_cl, int num1) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 864 of file Eval_Amont_VDF_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0.;
  Cerr<<"Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_VDF_Elem::coeffs_faces_interne (int face, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1434 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      for(k=0; k<aii.size(); k++)
        aii(k) = psc;
      for(k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for(k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for(k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Elem::coeffs_faces_interne (int face, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 907 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
double Eval_Amont_VDF_Elem::coeffs_faces_interne_bloc_vitesse (const DoubleTab & inco, int face) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 924 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = surface(face)*porosite(face);
  double flux;
  if (dt_vitesse[face] > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return flux;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 535 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1360 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1388 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 567 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 750 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 598 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 629 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double val_ext = la_cl.val_ext(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_ext;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux = psc*val_ext;
      else
        flux = psc*inco[n1];
    }
  return -flux;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 782 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double flux;
  if (psc > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return -flux;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const NSCBC & la_cl, int num1) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 843 of file Eval_Amont_VDF_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0.;
  Cerr<<"Eval_Amont_VDF_Elem::flux_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 953 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 313 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  double flux;
  double val_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_imp;
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        flux = psc*val_imp;
      else
        flux = psc*inco[n1];
    }
  return -flux;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int num1, DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 980 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int elem1 = elem_(face,0);
  int elem2 = elem_(face,1);
  if (psc > 0)
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(elem1,k);
  else
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(elem2,k);
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 471 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1278 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1144 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (n0 != -1)
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1037 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1333 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1306 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1251 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 439 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 504 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 1415 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (psc > 0)
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(n0,k);
  else
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(n1,k);
}
double Eval_Amont_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face) const [inline]
Reimplemented in Eval_Quick_VDF_Elem.
Definition at line 893 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double flux;
  if (psc > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return -flux;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Periodique & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1027 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Neumann_paroi & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1351 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1269 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 495 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::secmem_face (int face, const NSCBC & la_cl, int num1) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 877 of file Eval_Amont_VDF_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0;
  Cerr<<"Eval_Amont_VDF_Elem::secmem_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Symetrie & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 971 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Neumann_paroi & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 590 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Echange_global_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 558 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Symetrie & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 773 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 527 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1115 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
}
void Eval_Amont_VDF_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1221 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1324 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 411 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  double flux;
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_imp(face-num1);
      else
        flux = 0;
    }
  else   //!< j != -1
    {
      if (psc>0)
        flux = psc*la_cl.val_imp(face-num1);
      else
        flux = 0;
    }
  return -flux;
}
double Eval_Amont_VDF_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 724 of file Eval_Amont_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_ext(face-num1);
      else
        flux = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux = psc*la_cl.val_ext(face-num1);
      else
        flux = 0;
    }
  return -flux;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 462 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
double Eval_Amont_VDF_Elem::secmem_face (int face, const Periodique & la_cl, int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 832 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1297 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1378 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
void Eval_Amont_VDF_Elem::secmem_face (int , const Echange_global_impose & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1406 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 621 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
void Eval_Amont_VDF_Elem::secmem_faces_interne (int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1459 of file Eval_Amont_VDF_Elem.h.
{
  ;
}
double Eval_Amont_VDF_Elem::secmem_faces_interne (int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 938 of file Eval_Amont_VDF_Elem.h.
{
  return 0;
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Amont_VDF_Elem.h