TRUST: Terme_Source_Canal_RANS_LES_VEF_Face Class Reference
Terme_Source_Canal_RANS_LES_VEF_Face Class Reference
class Terme_Source_Canal_RANS_LES_VEF_Face Cette classe concerne un terme source calcule en partie grace
a un calcul RANS preliminaire et applique au calcul LES en cours
#include <Terme_Source_Canal_RANS_LES_VEF_Face.h>
Public Member Functions
Terme_Source_Canal_RANS_LES_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Terme_Source_Canal_RANS_LES_VEF_Face () override
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void init ()
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Canal_RANS_LES_VEF_Face & self_cast (Objet_U &)
static const Terme_Source_Canal_RANS_LES_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
int moyenne
int dir
Nom dir_nom
axe
double alpha_tau
double Ly
double u_tau
double nu
double rayon
double t_moy_start
double f_start
double f_tot
int u_target
DoubleTab U_RANS
DoubleTab utemp
DoubleTab utemp_sum
Detailed Description
class Terme_Source_Canal_RANS_LES_VEF_Face Cette classe concerne un terme source calcule en partie grace
a un calcul RANS preliminaire et applique au calcul LES en cours
Definition at line 30 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Canal_RANS_LES_VEF_Face()
Terme_Source_Canal_RANS_LES_VEF_Face::Terme_Source_Canal_RANS_LES_VEF_Face ()
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
~Terme_Source_Canal_RANS_LES_VEF_Face()
Terme_Source_Canal_RANS_LES_VEF_Face::~Terme_Source_Canal_RANS_LES_VEF_Face () override
Definition at line 38 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
// Le destructeur est appele a l'initialisation alors
// la sauvegarde du champ se fait hors initialisation
  if(utemp.size()!=0)
    {
      SFichier fic ("utemp.dat");
      fic << utemp;
    }
}
References TRUSTVect< _TYPE_ >::size(), and utemp.
Member Function Documentation
ajouter()
DoubleTab & Terme_Source_Canal_RANS_LES_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 403 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  int nb_faces = zone_VEF.nb_faces();
  const DoubleVect& porosite_surf = zone_VEF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const double tps = mon_equation->schema_temps().temps_courant();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  //   DoubleTab resu_old(U_RANS);
  //   DoubleTab utemp_bar(utemp);
  //   if (sub_type(Champ_P1NC,mon_equation->inconnue().valeur()))
  //   {
  //    const Champ_P1NC& Ch = ref_cast(Champ_P1NC,mon_equation->inconnue().valeur());
  //    Ch.filtrer_L2(U_RANS_bar);
  //    Ch.filtrer_L2(utemp_bar);
  //   }
  double vol = 0.;
  SFichier fic_f("forcing_term.dat", ios::app);
  SFichier fic_finst("finst.dat", ios::app);
  double mbf0 = 0.; // mean body force
  double mbf1 = 0.; // mean body force
  double mbf2 = 0.; // mean body force
  double mbf = 0.; //body force
  static int cpt = 0;
  double coef=1.;
  double scaling=0.;
  if((tps>f_start)||((moyenne==3)&&(tps>dt_min)&&(tps>f_start)))
    {
      cpt++;
      if (tps < f_tot) coef*=(tps-f_start)/(f_tot-f_start);
      for(int num_face = 0 ; num_face<nb_faces ; num_face++)
        {
          vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
          for(int comp=0; comp<3; comp++)
            {
              scaling=U_RANS(num_face,comp)/((U_RANS(num_face,0)*U_RANS(num_face,0)
                                              +U_RANS(num_face,1)*U_RANS(num_face,1)
                                              +U_RANS(num_face,2)*U_RANS(num_face,2))+1e-10);
              //                    if(cpt > 150)
              //                      resu(num_face,comp)=resu_old(num_face,comp);
              //                    else
              //                      {
              resu(num_face,comp) = scaling*coef*((U_RANS(num_face,comp)-utemp(num_face,comp))/(alpha_tau*dt))*vol;
              //f(num_face,comp) = /*coef**/((U_RANS_bar(num_face,comp)-utemp_bar(num_face,comp))/(alpha_tau*dt))*vol;
              //                        resu_old(num_face,comp)=resu(num_face,comp);
              //                      }
            }
          mbf0 += resu(num_face,0);
          mbf1 += resu(num_face,1);
          mbf2 += resu(num_face,2);
        }
      mbf0/=nb_faces;
      mbf1/=nb_faces;
      mbf2/=nb_faces;
      int num_face=123;
      scaling=U_RANS(num_face,0)/((U_RANS(num_face,0)*U_RANS(num_face,0)
                                   +U_RANS(num_face,1)*U_RANS(num_face,1)
                                   +U_RANS(num_face,2)*U_RANS(num_face,2))+1e-10);
      mbf = scaling*((U_RANS(num_face,0)-utemp(num_face,0))/(alpha_tau*dt))*vol;
      fic_finst << tps << " " << mbf << " " <<  U_RANS(num_face,0)
                << " " << utemp(num_face,0) << "  " << vitesse(num_face,0)
                << " " << scaling << finl;
      fic_f << tps << " " << mbf0 << " " << mbf1 <<" " << mbf2 << finl;
      if (sub_type(Champ_P1NC,mon_equation->inconnue().valeur()))
        {
          const Champ_P1NC& Ch = ref_cast(Champ_P1NC,mon_equation->inconnue().valeur());
          Ch.filtrer_resu(resu);
        }
    }//fin if f_start
  return resu;
}
References alpha_tau, f_start, f_tot, Champ_P1NC::filtrer_resu(), finl, Equation_base::inconnue(), la_zone_VEF, MorEqn::mon_equation, moyenne, Zone_VF::nb_faces(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Zone_VF::porosite_face(), ref_cast, Equation_base::schema_temps(), sub_type, Schema_Temps_base::temps_courant(), U_RANS, utemp, Deriv_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), and Zone_VF::volumes_entrelaces().
Referenced by calculer().
associer_pb()
void Terme_Source_Canal_RANS_LES_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 202 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  ;
}
associer_zones()
void Terme_Source_Canal_RANS_LES_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 195 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Source_Canal_RANS_LES_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 495 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
cree_instance()
Objet_U * Terme_Source_Canal_RANS_LES_VEF_Face::cree_instance () static
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
duplique()
int Terme_Source_Canal_RANS_LES_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
get_info()
const Type_info * Terme_Source_Canal_RANS_LES_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
info()
const Type_info * Terme_Source_Canal_RANS_LES_VEF_Face::info () static
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
init()
void Terme_Source_Canal_RANS_LES_VEF_Face::init ()
< Ecriture du champ target
< Lecture du champ target
< champ target : fonction analytique
Definition at line 207 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  int nb_faces = zone_VEF.nb_faces();
  const DoubleTab& xv = zone_VEF.xv();
  const double tps = mon_equation->schema_temps().temps_courant();
  double x1,x2;
  int comp1=0;
  int comp2=0;
  U_RANS.resize(nb_faces,3);
  U_RANS=0.;
  utemp.resize(nb_faces,3);
  utemp = 0.;
  utemp_sum.resize(nb_faces,3);
  utemp_sum = 0.;
  if (tps > t_moy_start )
    {
      EFichier fic1 ("utemp.dat");
      fic1 >> utemp;
// int trash;
// fic1 >> trash;
// for(int num_face = 0 ; num_face<nb_faces ; num_face++)
// {
// fic1 >> utemp(num_face,0) >> utemp(num_face,1) >> utemp(num_face,2);
// }
    }
  if(u_target==1) //!< Ecriture du champ target
    {
      SFichier fic ("utarget.dat");
      for(int num_face=0 ; num_face<nb_faces ; num_face++)
        {
          fic << vitesse(num_face,0) << vitesse(num_face,1) << vitesse(num_face,2);
        }
    }
  if(u_target==2) //!< Lecture du champ target
    {
      EFichier fic ("vitesse_RANS.dat");
      SFichier ficv ("verif_target.dat");
      for(int num_face=0 ; num_face<nb_faces ; num_face++)
        {
          fic >> U_RANS(num_face,0) >> U_RANS(num_face,1) >> U_RANS(num_face,2);
          ficv << U_RANS(num_face,0) << " " << U_RANS(num_face,1) << " " << U_RANS(num_face,2) << finl;
        }
    }
  else //!< champ target : fonction analytique
    {
      if(dir==0)
        {
          comp1=1 ;
          comp2=2 ;
        }
      if(dir==1)
        {
          comp1=0 ;
          comp2=2 ;
        }
      if(dir==2)
        {
          comp1=0 ;
          comp2=1 ;
        }
      for(int num_face=0 ; num_face<nb_faces ; num_face++)
        {
          x1=xv(num_face,comp1);
          x2=xv(num_face,comp2);
          U_RANS(num_face,dir)= u_tau*(2.44*log((rayon-sqrt(x1*x1+x2*x2))*u_tau/nu)+5.32) ;
// FAT : HOT : U_RANS(num_face)= 0.1145*(2.44*log((0.077-sqrt(y*y+z*z))*0.1145/1.52e-7)+5.1) ;
// FAT : COLD: U_RANS(num_face)= 0.029*(2.44*log((0.077-sqrt(y*y+x*x))*0.029/6.45e-7)+5.1) ;
        }
      if( dir_nom=="-X" || dir_nom=="-Y" || dir_nom=="-Z") U_RANS*=-1.;
    }
}//fin init
References dir, dir_nom, finl, Equation_base::inconnue(), MorEqn::mon_equation, Zone_VF::nb_faces(), nu, rayon, ref_cast, TRUSTTab< _TYPE_ >::resize(), Equation_base::schema_temps(), t_moy_start, Schema_Temps_base::temps_courant(), U_RANS, u_target, u_tau, utemp, utemp_sum, Champ_Inc::valeurs(), Zone_VF::xv(), and Champ_Inc::zone_dis_base().
Referenced by readOn().
mettre_a_jour()
void Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 300 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
// Cerr << "Je suis dans le mettre_a_jour" << finl;
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
// const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  const double tps = mon_equation->schema_temps().temps_courant();
  int nb_faces = zone_VEF.nb_faces();
  static int cpt=0;
  static double duree=0;
  if(moyenne==1)
    {
      Cerr << "code en VDF, necessite codage VEF ? " << finl;
      exit();
    }//!< fin moyenne = 1
  else if(moyenne==2)
    {
      //******************************************************
      //*************** MOYENNE TEMPORELLE *******************
      //******************************************************
      if(tps>=t_moy_start)
        {
          double DT_moy=(tps-dt)-t_moy_start;
          utemp*=DT_moy;
          for (int num_face=0; num_face<nb_faces; num_face++)
            for(int comp=0; comp<3; comp++)
              {
                utemp(num_face,comp) += dt*vitesse(num_face,comp);
              }
          utemp/=(DT_moy+dt);
          //           int face=123;
          //           SFichier fic_temp("utemp.dat", ios::app);
          //           SFichier fic_inst("uinst.dat", ios::app);
          //           fic_temp << tps << "  " <<  utemp(face,0) << "  "
          //                    << xv(face,0) << "  " << xv(face,1) << "  " <<  xv(face,2) << finl;
          //           fic_inst << tps << "  " << vitesse(face,0) << finl;
        }
      //***********************************************************
      //*************** FIN MOYENNE TEMPORELLE  ***************
      //*******************************************************
    }
  else if(moyenne==3)
    {
      //********************************************************************************
      //*************** MOYENNE TEMPORELLE (debut t=0 ou presque...) *******************
      //********************************************************************************
      if(tps>0)
        {
          if(cpt==0)
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                for(int comp=0; comp<3; comp++)
                  {
                    duree=400*dt;
                    utemp_sum(num_face,comp) = U_RANS(num_face,comp)*duree;
                    duree-=dt;
                    utemp(num_face,comp) = utemp_sum(num_face,comp)/(tps-dt_min+duree);
                    utemp_sum(num_face,comp) += dt*vitesse(num_face,comp);
                    utemp(num_face,comp) = vitesse(num_face,comp);
                  }
              cpt++;
            }
          else
            {
              for (int num_face=0; num_face<nb_faces; num_face++)
                for(int comp=0; comp<3; comp++)
                  {
                    utemp_sum(num_face,comp) += dt*vitesse(num_face,comp);
                    utemp(num_face,comp) = utemp_sum(num_face,comp)/(tps-dt_min+dt+duree);
                  }
            }
        }
    }
  else
    {
      Cerr << "moyenne = " << moyenne << finl;
      Cerr << "Probleme pour le choix du type de moyenne" << finl;
    }
}//fin mettre_a_jour
References Cerr, Process::exit(), finl, Equation_base::inconnue(), la_zone_VEF, MorEqn::mon_equation, moyenne, Zone_VF::nb_faces(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::schema_temps(), t_moy_start, Schema_Temps_base::temps_courant(), U_RANS, utemp, utemp_sum, Ref_Zone_VEF::valeur(), and Champ_Inc::valeurs().
printOn()
Sortie & Terme_Source_Canal_RANS_LES_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 53 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_RANS_LES_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< 0: moyenne spatiale 1: moyenne temp. glissante 2: moyenne temporelle
< direction de forcage de l'ecoulement
< vitesse de frottement theorique
< viscosite moleculaire
< rayon du cylindre
< cle pour champ target : 1=stockage 2=lecture
Reimplemented from Source_base.
Definition at line 62 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
{
  int compteur = 0;
  Motcle mot_lu;
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  u_target = 0;
  f_start = 0.;
  moyenne = 0;//valeur par defaut
// 0 => moyenne spatiale
// 1 => moyenne temporelle glissante (moyenne en alpha)
// 2 => moyenne temporelle
// 3 => moyenne temporelle t=0
  Motcles les_mots(11);
  {
    les_mots[0]="alpha_tau";   //coeff de relaxation du terme source
    les_mots[1]="Ly";          //Hauteur du canal plan (utile pour la moyenne spatiale)
    les_mots[2]="t_moy_start"; //temps de demarrage de la moyenne
    les_mots[3]="f_start";     //temps a partir duquel le terme source commence a etre active (pondere)
    les_mots[4]="f_tot";       //temps a partir duquel le terme source est totalement applique
    les_mots[5]="type_moyenne";//!< 0: moyenne spatiale 1: moyenne temp. glissante 2: moyenne temporelle
    les_mots[6]="dir";         //!< direction de forcage de l'ecoulement
    les_mots[7]="u_tau";       //!< vitesse de frottement theorique
    les_mots[8]="nu";          //!< viscosite moleculaire
    les_mots[9]="rayon";       //!< rayon du cylindre
    les_mots[10]="u_target";   //!< cle pour  champ target  : 1=stockage 2=lecture
  }
  is >> mot_lu;
  if(mot_lu != acc_ouverte)
    {
      Cerr << "On attendait { a la place de " << mot_lu
           << " lors de la lecture des parametres de la loi de paroi " << finl;
    }
  is >> mot_lu;
  while(mot_lu != acc_fermee)
    {
      int rang=les_mots.search(mot_lu);
      switch(rang)
        {
        case 0 :
          is >> alpha_tau;
          Cerr << "alpha_tau = " << alpha_tau << finl;
          compteur++;
          break;
        case 1  :
          is >> Ly;
          Cerr << "Ly = "<< Ly << finl;
          compteur++;
          break;
        case 2  :
          is >> t_moy_start;
          Cerr << " t_moy_start = "<< t_moy_start << finl;
          compteur++;
          break;
        case 3  :
          is >> f_start;
          Cerr << " f_start = "<< f_start << finl;
          compteur++;
          break;
        case 4  :
          is >> f_tot;
          Cerr << " f_tot = "<< f_tot << finl;
          compteur++;
          break;
        case 5  :
          is >> moyenne;
          Cerr << "type_moyenne : " << moyenne << finl;
          if(moyenne==0)
            {
              Cerr << " Pertinence de la moyenne spatiale en VEF ? -> ARRET (non code)" << finl;
              exit();
            }
          if(moyenne==1)
            {
              Cerr << " YOUNES, YOUNES !!! !"  << finl;
              Cerr << " YOUNES EST PARTI !!!"  << finl;
              exit();
            }
          compteur++;
          break;
        case 6  :
          is >> dir_nom;
          if     ( (dir_nom=="-X") || (dir_nom=="+X") ) dir=0;
          else if( (dir_nom=="-Y") || (dir_nom=="+Y") ) dir=1;
          else if( (dir_nom=="-Z") || (dir_nom=="+Z") ) dir=2;
          else
            {
              Cerr << " ERROR when reading direction for forcing term " << finl;
              Cerr << " 'dir' parameter has to be selected among following list : +X, -X, +Y, -Y, +Z or -Z " << finl;
              exit();
            }
          Cerr << " forcage suivant l'axe : " << dir_nom << " -> composante : " << dir <<finl;
          compteur++;
          break;
        case 7  :
          is >> u_tau;
          Cerr << "vitesse de frottement : " << u_tau << finl;
          compteur++;
          break;
        case 8  :
          is >> nu;
          Cerr << "viscosite moleculaire : " << nu << finl;
          compteur++;
          break;
        case 9  :
          is >> rayon;
          Cerr << "rayon : " << rayon << finl;
          compteur++;
          break;
        case 10  :
          is >> u_target;
          Cerr << " u_target: " << u_target << finl;
          compteur++;
          break;
        default :
          {
            Cerr << mot_lu << " n'est pas un mot compris par Source_Canal_RANS_LES_VEF_P1NC" << finl;
            Cerr << "Les mots compris sont : " << les_mots << finl;
            exit();
          }
        }
      is >> mot_lu;
    }
  Cerr << compteur << " motcles ont ete lus dans le readOn de Source_Canal_RANS_LES_VEF_P1NC" << finl;
  init();
  return is;
}
References alpha_tau, Cerr, compteur, dir, dir_nom, Process::exit(), f_start, f_tot, finl, init(), Ly, moyenne, nu, rayon, Motcles::search(), t_moy_start, u_target, and u_tau.
self_cast() [1/2]
const Terme_Source_Canal_RANS_LES_VEF_Face & Terme_Source_Canal_RANS_LES_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
self_cast() [2/2]
Terme_Source_Canal_RANS_LES_VEF_Face & Terme_Source_Canal_RANS_LES_VEF_Face::self_cast (Objet_U & r) static
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Canal_RANS_LES_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Terme_Source_Canal_RANS_LES_VEF_Face.cpp.
Member Data Documentation
alpha_tau
double Terme_Source_Canal_RANS_LES_VEF_Face::alpha_tau private
Definition at line 52 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), and readOn().
dir
int Terme_Source_Canal_RANS_LES_VEF_Face::dir private
Definition at line 50 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
dir_nom
Nom Terme_Source_Canal_RANS_LES_VEF_Face::dir_nom private
axe
Definition at line 51 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
f_start
double Terme_Source_Canal_RANS_LES_VEF_Face::f_start private
Definition at line 53 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), and readOn().
f_tot
double Terme_Source_Canal_RANS_LES_VEF_Face::f_tot private
Definition at line 53 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), and readOn().
info_obj
const Type_info Terme_Source_Canal_RANS_LES_VEF_Face::info_obj static
Definition at line 32 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Terme_Source_Canal_RANS_LES_VEF_Face::la_zone_Cl_VEF protected
Definition at line 46 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by associer_zones().
la_zone_VEF
Ref_Zone_VEF Terme_Source_Canal_RANS_LES_VEF_Face::la_zone_VEF protected
Definition at line 45 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), associer_zones(), and mettre_a_jour().
Ly
double Terme_Source_Canal_RANS_LES_VEF_Face::Ly private
Definition at line 52 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by readOn().
moyenne
int Terme_Source_Canal_RANS_LES_VEF_Face::moyenne private
Definition at line 49 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), mettre_a_jour(), and readOn().
nu
double Terme_Source_Canal_RANS_LES_VEF_Face::nu private
Definition at line 52 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
rayon
double Terme_Source_Canal_RANS_LES_VEF_Face::rayon private
Definition at line 52 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
t_moy_start
double Terme_Source_Canal_RANS_LES_VEF_Face::t_moy_start private
Definition at line 53 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), mettre_a_jour(), and readOn().
U_RANS
DoubleTab Terme_Source_Canal_RANS_LES_VEF_Face::U_RANS private
Definition at line 56 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), init(), and mettre_a_jour().
u_target
int Terme_Source_Canal_RANS_LES_VEF_Face::u_target private
Definition at line 54 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
u_tau
double Terme_Source_Canal_RANS_LES_VEF_Face::u_tau private
Definition at line 52 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and readOn().
utemp
DoubleTab Terme_Source_Canal_RANS_LES_VEF_Face::utemp private
Definition at line 57 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by ajouter(), init(), mettre_a_jour(), and ~Terme_Source_Canal_RANS_LES_VEF_Face().
utemp_sum
DoubleTab Terme_Source_Canal_RANS_LES_VEF_Face::utemp_sum private
Definition at line 58 of file Terme_Source_Canal_RANS_LES_VEF_Face.h.
Referenced by init(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Canal_RANS_LES_VEF_Face.h
src/VEF/Sources/Terme_Source_Canal_RANS_LES_VEF_Face.cpp