TRUST: EcritureLectureSpecial Class Reference
EcritureLectureSpecial Class Reference
#include <EcritureLectureSpecial.h>
Public Member Functions
EcritureLectureSpecial ()
~EcritureLectureSpecial ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &fich) override
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcritureLectureSpecial & self_cast (Objet_U &)
static const EcritureLectureSpecial & self_cast (const Objet_U &)
static void lecture_special (Champ_base &ch, Entree &fich)
simple appel a EcritureLectureSpecial::lecture_special
(const Zone_VF& zvf,Entree& fich,int nbval, DoubleTab& val)
static void lecture_special (const Zone_VF &zvf, Entree &fich, DoubleTab &val)
codage de la relecture d'un champ a partir d'un fichier special
positions,valeurs
static int ecriture_special (const Champ_base &ch, Sortie &fich)
simple appel a EcritureLectureSpecial::ecriture_special
(const Zone_VF& zvf,Sortie& fich,int nbval,const DoubleTab& val)
apres avoir recupere le tableau val
static int ecriture_special (const Zone_VF &zvf, Sortie &fich, const DoubleTab &val)
codage de l'ecriture des positions et des valeurs de val
static int is_lecture_special ()
indique si le format special a ete demande en lecture
active par reprise xyz ....
static int is_ecriture_special (int &special, int &a_faire)
indique si le format special a ete demande en lecture
active par sauvegarde xyz ....
si le mode ecriture est special c.a.d si format de sauvegarde xyz
alors special =1 a_faire=je_suis_maitre
sinon special=0 , a_faire=1
static Nom & get_Output ()
Renvoie le mode d'ecriture utilise<br>(pour pouvoir le modifier).
Cette methode est statique.
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static int Active =1
static int mode_ecr =-1
static int mode_lec =0
static Nom Input ="LecFicDiffuseBin"
"EFichierBin" was the past (<=1.6.9) and "LecFicPartageMPIIO" is may be the future
static Nom Output ="EcrFicPartageMPIIO"
"EcrFicPartageBin" was the past (<=1.6.9) and "EcrFicPartageMPIIO" is after 1.7.0
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 42 of file EcritureLectureSpecial.h.
Constructor & Destructor Documentation
EcritureLectureSpecial()
EcritureLectureSpecial::EcritureLectureSpecial ()
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
~EcritureLectureSpecial()
EcritureLectureSpecial::~EcritureLectureSpecial ()
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
Member Function Documentation
cree_instance()
Objet_U * EcritureLectureSpecial::cree_instance () static
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
duplique()
int EcritureLectureSpecial::duplique () const override virtual
Reimplemented from Interprete.
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
ecriture_special() [1/2]
int EcritureLectureSpecial::ecriture_special (const Champ_base & ch, Sortie & fich) static
simple appel a EcritureLectureSpecial::ecriture_special
(const Zone_VF& zvf,Sortie& fich,int nbval,const DoubleTab& val)
apres avoir recupere le tableau val
Definition at line 137 of file EcritureLectureSpecial.cpp.
{
  const Zone_VF& zvf = ref_cast(Zone_VF, ch.zone_dis_base());
  const DoubleTab& val = ch.valeurs();
  return ecriture_special(zvf, fich, val);
}
References ecriture_special(), ref_cast, Champ_Proto::valeurs(), and Champ_base::zone_dis_base().
Referenced by ecriture_special(), Champ_Fonc_base::sauvegarder(), and Champ_Inc_base::sauvegarder().
ecriture_special() [2/2]
int EcritureLectureSpecial::ecriture_special (const Zone_VF & zvf, Sortie & fich, const DoubleTab & val) static
codage de l'ecriture des positions et des valeurs de val
Definition at line 251 of file EcritureLectureSpecial.cpp.
{
  const MD_Vector& md = val.get_md_vector();
  if (!md.non_nul())
    {
      Cerr << "EcritureLectureSpecial::ecriture_special: error, cannot save an array with no metadata" << finl;
      Process::exit();
    }
  const int nb_items_seq = md.valeur().nb_items_seq_tot();
  if (nb_items_seq == 0)
    return 0;
  const int nb_dim = val.nb_dim();
  const int nb_comp = (nb_dim == 2) ? val.dimension(1) : 1;
  const int dim = Objet_U::dimension;
  const int n = nb_items_seq * (nb_comp + dim);
  if (Process::je_suis_maitre())
    {
      fich << (int)1 << finl;
      fich       << n << finl ;
      fich << (int)1 << finl;
      fich << n << finl ;
      fich << n <<finl;
    }
  int bytes = ecriture_special_part2(zvf, fich, val);
  if (Process::je_suis_maitre())
    {
      fich << n << finl;
      fich << (int)0 << finl;
      fich << (int)0 << finl;
      fich << (int)0 << finl;
      fich << (int)1 << finl;
      fich << (int)0 << finl;
      fich << n << finl;
      fich << finl;
      fich << (int)1 << finl;
      fich << (int)0 << finl;
      fich << (int)0 <<finl;
    }
  fich.syncfile();
  return bytes;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, ecriture_special_part2(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Process::je_suis_maitre(), TRUSTTab< _TYPE_ >::nb_dim(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), Sortie::syncfile(), and MD_Vector::valeur().
get_info()
const Type_info * EcritureLectureSpecial::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
get_Output()
Nom & EcritureLectureSpecial::get_Output () static
Renvoie le mode d'ecriture utilise<br>(pour pouvoir le modifier).
Cette methode est statique.
Definition at line 554 of file EcritureLectureSpecial.cpp.
{
  static Nom option=Output;
// disable MPIIO in sequential mode
  if (Output=="EcrFicPartageMPIIO" && Process::nproc()==1) option="EcrFicPartageBin";
// disable MPIIO if TRUST_DISABLE_MPIIO=1
  char* theValue = getenv("TRUST_DISABLE_MPIIO");
  if (theValue != NULL)
    {
      if (option=="EcrFicPartageMPIIO" && strcmp(theValue,"1")==0) option="EcrFicPartageBin";
    }
  return option;
}
References Process::nproc(), and Output.
Referenced by ecrit(), Probleme_base::sauver(), and Probleme_base::sauver_xyz().
info()
const Type_info * EcritureLectureSpecial::info () static
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
interpreter()
Entree & EcritureLectureSpecial::interpreter (Entree & fich) override virtual
Reimplemented from Interprete.
Definition at line 71 of file EcritureLectureSpecial.cpp.
{
  Nom option;
  is >> option;
  if (option=="EFichierBin" || option=="LecFicDiffuseBin" || option=="LecFicPartageMPIIO")
    {
      Input=option;
      Cerr << "EcritureLectureSpecial::Input set to " << option << finl;
    }
  else if (option=="EcrFicPartageMPIIO" || option=="EcrFicPartageBin")
    {
      Active=1;
      Output=option;
      Cerr << "EcritureLectureSpecial::Output set to " << option << finl;
    }
  else if (option=="0")
    Active=0;
  else if (option=="1")
    Active=1;
  else
    {
      Cerr << "\"EcritureLectureSpecial " << option << "\" is unknown." << finl;
      Process::exit();
    }
  Cerr << "EcritureLectureSpecial::Active set to " << Active << finl;
  return is;
}
References Active, Cerr, Process::exit(), finl, Input, and Output.
is_ecriture_special()
int EcritureLectureSpecial::is_ecriture_special (int & special, int & a_faire) static
indique si le format special a ete demande en lecture
active par sauvegarde xyz ....
si le mode ecriture est special c.a.d si format de sauvegarde xyz
alors special =1 a_faire=je_suis_maitre
sinon special=0 , a_faire=1
< mode_ecr n'est pas positionne
Definition at line 114 of file EcritureLectureSpecial.cpp.
{
  special=0;
  a_faire=1;
  assert(mode_ecr>=0); //!< mode_ecr n'est pas positionne
  if (mode_ecr)
    {
      special=1;
      a_faire=Process::je_suis_maitre();
    }
  return mode_ecr;
}
References Process::je_suis_maitre(), and mode_ecr.
Referenced by Mod_turb_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_nul::sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
is_lecture_special()
int EcritureLectureSpecial::is_lecture_special () static
indique si le format special a ete demande en lecture
active par reprise xyz ....
Definition at line 102 of file EcritureLectureSpecial.cpp.
{
  return mode_lec;
}
References mode_lec.
Referenced by Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
lecture_special() [1/2]
void EcritureLectureSpecial::lecture_special (Champ_base & ch, Entree & fich) static
simple appel a EcritureLectureSpecial::lecture_special
(const Zone_VF& zvf,Entree& fich,int nbval, DoubleTab& val)
Definition at line 307 of file EcritureLectureSpecial.cpp.
{
  const Zone_VF& zvf=ref_cast(Zone_VF,ch.zone_dis_base());
  DoubleTab& val = ch.valeurs();
  lecture_special(zvf, fich, val);
}
References lecture_special(), ref_cast, Champ_Proto::valeurs(), and Champ_base::zone_dis_base().
Referenced by lecture_special(), Mod_turb_hyd_base::lire_distance_paroi(), Champ_Fonc_base::reprendre(), and Champ_Inc_base::reprendre().
lecture_special() [2/2]
void EcritureLectureSpecial::lecture_special (const Zone_VF & zvf, Entree & fich, DoubleTab & val) static
codage de la relecture d'un champ a partir d'un fichier special
positions,valeurs
Definition at line 521 of file EcritureLectureSpecial.cpp.
{
  const MD_Vector& md_vect = val.get_md_vector();
  if (!md_vect.non_nul())
    {
      Cerr << "EcritureLectureSpecial::ecriture_special: error, cannot save an array with no metadata" << finl;
      Process::exit();
    }
  const int nb_items_seq = md_vect.valeur().nb_items_seq_tot();
  if (nb_items_seq == 0)
    return;
  int bidon;
  fich >> bidon >> bidon >> bidon >> bidon >> bidon;
  int ntot = lecture_special_part2(zvf, fich, val);
  if (ntot != nb_items_seq)
    {
      Cerr << "Internal error in EcritureLectureSpecial::lecture_special" << finl;
      exit();
    }
  fich >> bidon >> bidon >> bidon >> bidon >> bidon >> bidon >> bidon >> bidon >> bidon >> bidon;
// On met a jour les parties virtuelles du tableau val
  val.echange_espace_virtuel();
}
References Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), lecture_special_part2(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), and MD_Vector::valeur().
printOn()
Sortie & EcritureLectureSpecial::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 60 of file EcritureLectureSpecial.cpp.
{
  return os;
}
readOn()
Entree & EcritureLectureSpecial::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 65 of file EcritureLectureSpecial.cpp.
{
  return is;
}
self_cast() [1/2]
const EcritureLectureSpecial & EcritureLectureSpecial::self_cast (const Objet_U & r) static
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
self_cast() [2/2]
EcritureLectureSpecial & EcritureLectureSpecial::self_cast (Objet_U & r) static
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
taille_memoire()
unsigned EcritureLectureSpecial::taille_memoire () const override virtual
Reimplemented from Interprete.
Definition at line 38 of file EcritureLectureSpecial.cpp.
{
Member Data Documentation
Active
int EcritureLectureSpecial::Active =1 static
Definition at line 55 of file EcritureLectureSpecial.h.
Referenced by Probleme_base::allocation(), Probleme_base::finir(), interpreter(), and Probleme_base::preparer_calcul().
info_obj
const Type_info EcritureLectureSpecial::info_obj static
Definition at line 44 of file EcritureLectureSpecial.h.
Input
Nom EcritureLectureSpecial::Input ="LecFicDiffuseBin" static
"EFichierBin" was the past (<=1.6.9) and "LecFicPartageMPIIO" is may be the future
Definition at line 58 of file EcritureLectureSpecial.h.
Referenced by interpreter(), Probleme_base::readOn(), and Champ_Fonc_reprise::readOn().
mode_ecr
int EcritureLectureSpecial::mode_ecr =-1 static
Definition at line 56 of file EcritureLectureSpecial.h.
Referenced by is_ecriture_special(), Probleme_base::sauver(), and Probleme_base::sauver_xyz().
mode_lec
int EcritureLectureSpecial::mode_lec =0 static
Definition at line 57 of file EcritureLectureSpecial.h.
Referenced by is_lecture_special(), Probleme_base::readOn(), and Champ_Fonc_reprise::readOn().
Output
Nom EcritureLectureSpecial::Output ="EcrFicPartageMPIIO" static
"EcrFicPartageBin" was the past (<=1.6.9) and "EcrFicPartageMPIIO" is after 1.7.0
Definition at line 59 of file EcritureLectureSpecial.h.
Referenced by get_Output(), and interpreter().
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/EcritureLectureSpecial.h
src/Kernel/VF/Zones/EcritureLectureSpecial.cpp