TRUST: Octree Class Reference
Octree Class Reference
Classe Octree.
#include <Octree.h>
Public Member Functions
Octree ()
virtual ~Octree ()
Destructeur: appelle Octree::detruire().
Octree (const Octree &)
Octree (int n, Octree *mon_pere, const ArrOfInt &val, const OctreeLoc &loc)
virtual int rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const
virtual int rang_elem_depuis_loc (const OctreeLoc &, int prems, double x, double y=0, double z=0) const
virtual const Zone & zone () const
Renvoie une reference sur la zone associe a l'octree.
void construire (int, const ArrOfInt &, const OctreeLoc &, Octree *p=0)
int niveau () const
virtual int taille () const
Renvoie la taille de l'octree.
virtual Sortie & printOn (Sortie &is) const
virtual Entree & readOn (Entree &is)
NE FAIT RIEN.
Static Public Member Functions
static int nombre_d_octrees ()
Renvoie le nombre d'octree.
Protected Member Functions
void detruire ()
Detruit l'octree.
Methode appelee par le destructeur.
void ranger_elem_1D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double)
void ranger_elem_2D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double)
void ranger_elem_3D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double, double)
double get_epsilon () const
Protected Attributes
Octree ** les_octrees
Octree * pere
Detailed Description
Classe Octree.
Definition at line 56 of file Octree.h.
Constructor & Destructor Documentation
Octree() [1/3]
Octree::Octree () inline
Definition at line 59 of file Octree.h.
:les_octrees(0), pere(0) {}
Referenced by construire(), and taille().
~Octree()
Octree::~Octree () virtual
Destructeur: appelle Octree::detruire().
Definition at line 178 of file Octree.cpp.
{
  detruire();
}
References detruire().
Octree() [2/3]
Octree::Octree (const Octree &) inline
Definition at line 61 of file Octree.h.
:les_octrees(0), pere(0) {}
Octree() [3/3]
Octree::Octree (int n, Octree * mon_pere, const ArrOfInt & val, const OctreeLoc & loc) inline
Definition at line 62 of file Octree.h.
  {
    construire(n, val, loc, mon_pere);
  }
References construire().
Member Function Documentation
construire()
void Octree::construire (int nb_octrees, const ArrOfInt & Tab, const OctreeLoc & loc, Octree * p = 0)
Definition at line 800 of file Octree.cpp.
{
  static int nb_octree=0;
  static int level=0;
  nb_octree++;
  int nb_elem=Tab.size_array();
  pere=pe;
  les_octrees=new Octree*[nb_octrees];
  if(niveau()>level)
    {
      level=niveau();
      Process::Journal() << "Octree: level=" << level
                         << " nb_elem=" << nb_elem << finl;
      if(level > 100) Process::exit();
    }
  if(nb_elem<=NbCasesParNoeuds)
    {
      for(int i=0; i<nb_octrees; i++)
        {
          les_octrees[i]=0;
        }
      les_octrees[0]=new OctreeFloor(this, Tab, loc);
    }
  else
    {
// else
      const Zone& z=zone();
      const Domaine& dom=z.domaine();
      IntVects SousTab(nb_octrees);
      ArrOfInt compteur(nb_octrees);
      int nb_som_elem=z.nb_som_elem();
      int i;
      const IntTab& les_elems=z.les_elems();
      const DoubleTab& coord_sommets=dom.coord_sommets();
      for(i=0; i<nb_octrees; i++)
        SousTab[i].resize(nb_elem);
      double xmil=(loc.xmin+loc.xmax)/2;
      double ymil=(loc.ymin+loc.ymax)/2;
      double zmil=(loc.zmin+loc.zmax)/2;
      ArrOfInt ok(nb_octrees);
      for(int elem=0; elem<nb_elem; elem++)
        {
          i=Tab[elem];
          ok=0;
          switch(Objet_U::dimension)
            {
            case 1:
              ranger_elem_1D(ok, elem, i , nb_som_elem, coord_sommets,
                             les_elems, compteur, SousTab, xmil);
              break;
            case 2:
              ranger_elem_2D(ok, elem, i , nb_som_elem, coord_sommets,
                             les_elems, compteur, SousTab, xmil, ymil);
              break;
            case 3:
              ranger_elem_3D(ok, elem, i ,nb_som_elem, coord_sommets,
                             les_elems, compteur, SousTab, xmil, ymil, zmil);
              break;
            default:
              Cerr << "Space dimension " << Objet_U::dimension << " incorrect" << finl;
              Process::exit();
            }
        }
      for(i=0; i<nb_octrees; i++)
        {
          les_octrees[i]=0;
          OctreeLoc loci;
          loci.construire(loc, i, xmil, ymil, zmil);
          SousTab[i].resize(compteur[i]);
          if(compteur[i]==nb_elem)
            {
              les_octrees[i]=new OctreeFloor(this, SousTab[i], loci);
            }
          else if(compteur[i]>NbCasesParNoeuds)
            {
              les_octrees[i]=new Octree(nb_octrees, this, SousTab[i], loci);
            }
          else if(compteur[i]!=0)
            {
              les_octrees[i]=new OctreeFloor(this, SousTab[i], loci);
            }
        }
// Cerr << "On continue dans cette direction" << finl;
    }
}
References Cerr, compteur, OctreeLoc::construire(), Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Process::exit(), finl, Process::Journal(), Zone::les_elems(), les_octrees, Zone::nb_som_elem(), NbCasesParNoeuds, niveau(), Octree(), pere, ranger_elem_1D(), ranger_elem_2D(), ranger_elem_3D(), TRUSTArray< _TYPE_ >::size_array(), OctreeLoc::xmax, OctreeLoc::xmin, OctreeLoc::ymax, OctreeLoc::ymin, OctreeLoc::zmax, OctreeLoc::zmin, and zone().
Referenced by OctreeRoot::construire(), and Octree().
detruire()
void Octree::detruire () protected
Detruit l'octree.
Methode appelee par le destructeur.
Definition at line 906 of file Octree.cpp.
{
  if(les_octrees==0)
    return;
  int nb_octrees=Octree::nombre_d_octrees();
  for(int i=0; i<nb_octrees; i++)
    if(les_octrees[i])
      delete les_octrees[i];
  delete[] les_octrees;
  les_octrees=0;
}
References les_octrees, and nombre_d_octrees().
Referenced by OctreeRoot::construire(), OctreeRoot::invalide(), and ~Octree().
get_epsilon()
double Octree::get_epsilon () const protected
Definition at line 540 of file Octree.cpp.
{
  return zone().domaine().epsilon();
}
References Zone::domaine(), Domaine::epsilon(), and zone().
Referenced by OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), OctreeRoot::rang_elem_depuis(), OctreeRoot::rang_sommet(), and ranger_elem_3D().
niveau()
int Octree::niveau () const
Returns
int
Signification:
Contraintes:
Definition at line 932 of file Octree.cpp.
{
  int i=0;
  if (pere==0) return i;
  return (pere->niveau()+1);
}
References niveau(), and pere.
Referenced by construire(), niveau(), and printOn().
nombre_d_octrees()
int Octree::nombre_d_octrees () static
Renvoie le nombre d'octree.
Returns
int
Signification: le nombre d'octree
Contraintes: il y en a 2^{dimension d'espace}
Definition at line 383 of file Octree.cpp.
{
  int nb_octrees;
  switch(Objet_U::dimension)
    {
    case 1:
      nb_octrees=2;
      break;
    case 2:
      nb_octrees=4;
      break;
    case 3:
      nb_octrees=8;
      break;
    default :
      nb_octrees=0;
      break;
    }
  return nb_octrees;
}
References Objet_U::dimension.
Referenced by OctreeRoot::construire(), detruire(), printOn(), rang_elem_depuis_loc(), rang_elem_loc(), and taille().
printOn()
Sortie & Octree::printOn (Sortie & is) const virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented in OctreeFloor, and OctreeRoot.
Definition at line 43 of file Octree.cpp.
{
  int nb_octrees=Octree::nombre_d_octrees();
  int i;
  is << finl << "--------------------------------" << finl;
  is << "niveau : " << niveau() << " taille : " << taille() << finl;
  for(i=0; i<nb_octrees; i++)
    {
      if(les_octrees[i]!=0)
        {
          les_octrees[i]->printOn(is);
        }
      else
        is << "vide" << " ";
    }
  return is << finl;
}
References finl, les_octrees, niveau(), nombre_d_octrees(), printOn(), and taille().
Referenced by printOn(), OctreeFloor::printOn(), and OctreeRoot::printOn().
rang_elem_depuis_loc()
int Octree::rang_elem_depuis_loc (const OctreeLoc & loc, int prems, double x, double y = 0, double z = 0) const virtual
Returns
int
Signification:
Contraintes:
Reimplemented in OctreeFloor.
Definition at line 495 of file Octree.cpp.
{
  int element=-1;
  int j=1;
  while(j<nombre_d_octrees())
    {
      if(les_octrees[j]!=0)
        break;
      else
        j++;
    }
  if(j<nombre_d_octrees())
    {
      int i=loc.direction(x, y, z);
      OctreeLoc loci;
      loci.construire(loc, i);
      if(les_octrees[i]==0)
        return -1;
      element = les_octrees[i]->rang_elem_depuis_loc(loci, prems, x, y, z);
    }
  else
    element = les_octrees[0]->rang_elem_depuis_loc(loc, prems, x, y, z);
  return element;
}
References OctreeLoc::construire(), OctreeLoc::direction(), les_octrees, nombre_d_octrees(), and rang_elem_depuis_loc().
Referenced by OctreeRoot::rang_elem_depuis(), rang_elem_depuis_loc(), and OctreeRoot::rang_elems_sommet().
rang_elem_loc()
int Octree::rang_elem_loc (const OctreeLoc & loc, double x, double y = 0, double z = 0) const virtual
Returns
int
Signification:
Contraintes:
Reimplemented in OctreeFloor.
Definition at line 433 of file Octree.cpp.
{
  int element=-1;
  int j=1;
  while(j<nombre_d_octrees())
    {
      if(les_octrees[j]!=0)
        break;
      else
        j++;
    }
  if(j<nombre_d_octrees())
    {
      int i=loc.direction(x, y, z);
      OctreeLoc loci;
      loci.construire(loc, i);
      if(les_octrees[i]==0)
        {
          return -1;
        }
      element = les_octrees[i]->rang_elem_loc(loci, x, y, z);
    }
  else
    element = les_octrees[0]->rang_elem_loc(loc, x, y, z);
  return element;
}
References OctreeLoc::construire(), OctreeLoc::direction(), les_octrees, nombre_d_octrees(), and rang_elem_loc().
Referenced by OctreeRoot::rang_elem(), and rang_elem_loc().
ranger_elem_1D()
void Octree::ranger_elem_1D (ArrOfInt & ok, int elem, int i, int nb_som_elem, const DoubleTab & coord, const IntTab & elems, ArrOfInt & compteur, IntVects & SousTab, double xmil) protected
Definition at line 544 of file Octree.cpp.
{
  for(int som=0; som<nb_som_elem; som++)
    {
      int sommet=elems(i,som);
      assert(sommet>=0);
      if(coord(sommet,0)<xmil)
        {
          if(!ok[GaucheArriereBas])
            {
              SousTab[GaucheArriereBas][compteur[GaucheArriereBas]]=i;
              compteur[GaucheArriereBas]++;
              ok[GaucheArriereBas]=1;
            }
        }
      else
        {
          if(!ok[DroitArriereBas])
            {
              SousTab[DroitArriereBas][compteur[DroitArriereBas]]=i;
              compteur[DroitArriereBas]++;
              ok[DroitArriereBas]=1;
            }
        }
    }
}
References compteur, DroitArriereBas, and GaucheArriereBas.
Referenced by construire().
ranger_elem_2D()
void Octree::ranger_elem_2D (ArrOfInt & ok, int elem, int i, int nb_som_elem, const DoubleTab & coord, const IntTab & elems, ArrOfInt & compteur, IntVects & SousTab, double xmil, double ymil) protected
Definition at line 714 of file Octree.cpp.
{
  double xmin=DMAXFLOAT, xmax=-DMAXFLOAT;
  double ymin=xmin, ymax=xmax;
  for(int som=0; som<nb_som_elem; som++)
    {
      int sommet=elems(i,som);
// assert(sommet>=0);
// GF dans le cas dde polyedre le tableau elem est surdimensionne et peut contenir des -1
      if (sommet>=0)
        {
          xmin=std::min(xmin, coord(sommet,0));
          xmax=std::max(xmax, coord(sommet,0));
          ymin=std::min(ymin, coord(sommet,1));
          ymax=std::max(ymax, coord(sommet,1));
        }
    }
  range2D(xmin, ymin, xmil, ymil, ok, SousTab, compteur, i);
  range2D(xmin, ymax, xmil, ymil, ok, SousTab, compteur, i);
  range2D(xmax, ymin, xmil, ymil, ok, SousTab, compteur, i);
  range2D(xmax, ymax, xmil, ymil, ok, SousTab, compteur, i);
}
References compteur, DMAXFLOAT, and range2D().
Referenced by construire().
ranger_elem_3D()
void Octree::ranger_elem_3D (ArrOfInt & ok, int elem, int i, int nb_som_elem, const DoubleTab & coord, const IntTab & elems, ArrOfInt & compteur, IntVects & SousTab, double xmil, double ymil, double zmil) protected
Definition at line 739 of file Octree.cpp.
{
  double epsilon=get_epsilon();
  double xmin=DMAXFLOAT, xmax=-DMAXFLOAT;
  double ymin=xmin, ymax=xmax;
  double zmin=xmin, zmax=xmax;
  for(int som=0; som<nb_som_elem; som++)
    {
      int sommet=elems(i,som);
// assert(sommet>=0);
// GF dans le cas dde polyedre le tableau elem est surdimensionne et peut contenir des -1
      if (sommet>=0)
        {
          xmin=std::min(xmin, coord(sommet,0))-epsilon;
          xmax=std::max(xmax, coord(sommet,0))+epsilon;
          ymin=std::min(ymin, coord(sommet,1))-epsilon;
          ymax=std::max(ymax, coord(sommet,1))+epsilon;
          zmin=std::min(zmin, coord(sommet,2))-epsilon;
          zmax=std::max(zmax, coord(sommet,2))+epsilon;
        }
    }
  range3D(xmin, ymin, zmin, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmin, ymax, zmin, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmax, ymin, zmin, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmax, ymax, zmin, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmin, ymin, zmax, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmin, ymax, zmax, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmax, ymin, zmax, xmil, ymil, zmil, ok, SousTab, compteur, i);
  range3D(xmax, ymax, zmax, xmil, ymil, zmil, ok, SousTab, compteur, i);
}
References compteur, DMAXFLOAT, get_epsilon(), and range3D().
Referenced by construire().
readOn()
Entree & Octree::readOn (Entree & is) virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented in OctreeRoot, and OctreeFloor.
Definition at line 75 of file Octree.cpp.
{
  return is;
}
Referenced by OctreeRoot::readOn(), and OctreeFloor::readOn().
taille()
int Octree::taille () const virtual
Renvoie la taille de l'octree.
Returns
unsigned
Signification: la taille de l'octree
Contraintes:
Reimplemented in OctreeFloor.
Definition at line 954 of file Octree.cpp.
{
  int nb_octrees=Octree::nombre_d_octrees();
  unsigned la_taille = sizeof(Octree);
  for(int i=0; i<nb_octrees; i++)
    if(les_octrees[i]!=0)
      la_taille+= les_octrees[i]->taille();
  return la_taille;
}
References les_octrees, nombre_d_octrees(), Octree(), and taille().
Referenced by printOn(), and taille().
zone()
const Zone & Octree::zone () const virtual
Renvoie une reference sur la zone associe a l'octree.
Returns
Zone&
Signification: reference sur la zone associe a l'octree
Contraintes: reference constante
Reimplemented in OctreeRoot.
Definition at line 536 of file Octree.cpp.
{
  return pere->zone();
}
References pere, and zone().
Referenced by construire(), get_epsilon(), OctreeFloor::rang_elem_depuis_loc(), OctreeFloor::rang_elem_loc(), and zone().
Member Data Documentation
les_octrees
Octree** Octree::les_octrees protected
Definition at line 83 of file Octree.h.
Referenced by construire(), OctreeFloor::construire(), detruire(), printOn(), rang_elem_depuis_loc(), rang_elem_loc(), and taille().
pere
Octree* Octree::pere protected
Definition at line 84 of file Octree.h.
Referenced by OctreeRoot::construire(), construire(), OctreeFloor::construire(), niveau(), and zone().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree.h
src/Kernel/Geometrie/Octree.cpp