TRUST: Terme_Boussinesq_base Class Reference
Terme_Boussinesq_base Class Reference
Classe Terme_Boussinesq_base
Cette classe represente le terme de gravite qui figure dans l'equation
de la dynamique divisee par la masse volumique de reference.
On est dans le cadre de l'hypothese de Boussinesq:la masse volumique est
supposee constante et egale a sa valeur de reference sauf dans le terme
des forces de volumes ou on prend en compte une petite variation de la
masse volumique en fonction d'un ou de plusieurs scalaires transportes
par l'ecoulement (la temperature et/ou une ou plusieurs concentrations).
Cas particulier de Terme_Boussinesq_base pour la temperature
Le terme de gravite a pour expression: beta*(T-T0) ou beta
represente la dilatabilite de la masse volumique et T0 une valeur
de reference pour la temperature
Cas particulier de Terme_Boussinesq_base pour une concentration
Le terme de gravite a pour expression : beta*(C-C0)
ou (beta[0]*(C[0]-C0[0]) + .....+ beta[i]*(C[i]-C0[i])) dans
le cas d'un vecteur de concentrations
beta represente la variation de la masse volumique en fonction
de la concentration du constituant et C0 une valeur de reference
pour la concentration.
#include <Terme_Boussinesq_base.h>
Public Member Functions
Terme_Boussinesq_base ()
~Terme_Boussinesq_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &pb)
const Champ_Don_base & gravite () const
int verification () const
double Scalaire0 (int i) const
const Champ_Don & beta () const
const Convection_Diffusion_std & equation_scalaire () const
DoubleTab & calculer (DoubleTab &resu) const
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Boussinesq_base & self_cast (Objet_U &)
static const
Terme_Boussinesq_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Entree & lire_donnees (Entree &)
Lit les parametres du terme source a partir d'un flot d'entree.
void check () const
Protected Attributes
Ref_Champ_Don_base la_gravite_
int verif_
ArrOfDouble Scalaire0_
T0=Scalaire0_(0) ou C0(i)=Scalaire0_(i)
Nom NomScalaire_
Temperature ou Concentration.
Vect_Parser_U fct_Scalaire0_
Ref_Champ_Don beta_
Ref_Convection_Diffusion_std equation_scalaire_
Detailed Description
Classe Terme_Boussinesq_base
Cette classe represente le terme de gravite qui figure dans l'equation
de la dynamique divisee par la masse volumique de reference.
On est dans le cadre de l'hypothese de Boussinesq:la masse volumique est
supposee constante et egale a sa valeur de reference sauf dans le terme
des forces de volumes ou on prend en compte une petite variation de la
masse volumique en fonction d'un ou de plusieurs scalaires transportes
par l'ecoulement (la temperature et/ou une ou plusieurs concentrations).
Cas particulier de Terme_Boussinesq_base pour la temperature
Le terme de gravite a pour expression: beta*(T-T0) ou beta
represente la dilatabilite de la masse volumique et T0 une valeur
de reference pour la temperature
Cas particulier de Terme_Boussinesq_base pour une concentration
Le terme de gravite a pour expression : beta*(C-C0)
ou (beta[0]*(C[0]-C0[0]) + .....+ beta[i]*(C[i]-C0[i])) dans
le cas d'un vecteur de concentrations
beta represente la variation de la masse volumique en fonction
de la concentration du constituant et C0 une valeur de reference
pour la concentration.
Definition at line 60 of file Terme_Boussinesq_base.h.
Constructor & Destructor Documentation
Terme_Boussinesq_base::Terme_Boussinesq_base ()
Definition at line 28 of file Terme_Boussinesq_base.cpp.
Terme_Boussinesq_base::~Terme_Boussinesq_base ()
Definition at line 28 of file Terme_Boussinesq_base.cpp.
Member Function Documentation
void Terme_Boussinesq_base::associer_pb (const Probleme_base & pb) [virtual]
< by default it is invalid
< only used for the error message
Implements Source_base.
Definition at line 44 of file Terme_Boussinesq_base.cpp.
References Process::abort(), beta_, Fluide_base::beta_c(), Milieu_base::beta_t(), Cerr, MorEqn::equation(), Probleme_base::equation(), equation_scalaire_, Process::exit(), finl, Milieu_base::gravite(), Equation_base::inconnue(), la_gravite_, O_U_Ptr::le_nom(), Probleme_base::nombre_d_equations(), NomScalaire_, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and ref_cast.
{
  int ok=0;
  int n_eq=pb.nombre_d_equations();
  for (int eq=0; eq<n_eq; eq++)
    {
      const Equation_base& eqn=pb.equation(eq);
      if (eqn.inconnue().le_nom()==NomScalaire_)
        {
          ok=1;
          equation_scalaire_ = ref_cast(Convection_Diffusion_std,eqn);
        }
    }
  if (ok==0)
    {
      Cerr << "Error. The Boussinesq source term can't be defined on a problem of kind " << pb.que_suis_je() << finl;
      Process::exit();
    }
// Fill la_gravite_ and beta_ attributes
  const Fluide_base& fluide=ref_cast(Fluide_base,equation().milieu());
  la_gravite_=fluide.gravite();
// this variable indicates if the beta field is valid or not
  int valid_beta_field = 0; //!< by default it is invalid
  Nom beta_field_name="??"; //!< only used for the error message
  if (NomScalaire_=="temperature")
    {
      valid_beta_field = fluide.beta_t( ).non_nul( );
      beta_field_name = "thermal expansion value (beta_th)";
      beta_=fluide.beta_t();
    }
  else if (NomScalaire_=="concentration")
    {
      valid_beta_field = fluide.beta_c( ).non_nul( );
      beta_field_name = "volume expansion coefficient values in concentration (beta_co)";
      beta_=fluide.beta_c();
    }
  if( ! valid_beta_field )
    {
      Cerr << "Error. Boussinesq source term is not able to access to the "<<beta_field_name<<" associated to the fluid."<<finl;
      Cerr << "Please check your data file. " << finl;
      Cerr << "Aborting..."<<finl;
      Process::abort( );
    }
}
const Champ_Don& Terme_Boussinesq_base::beta () const [inline]
Definition at line 79 of file Terme_Boussinesq_base.h.
References beta_, and Ref_Champ_Don::valeur().
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), and Terme_Boussinesq_PolyMAC_Face::ajouter().
  {
    return beta_.valeur();
  } ;
DoubleTab& Terme_Boussinesq_base::calculer (DoubleTab & resu) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 87 of file Terme_Boussinesq_base.h.
References Source_base::ajouter().
  {
    resu=0;
    return ajouter(resu);
  };
void Terme_Boussinesq_base::check () const [inline, protected]
Definition at line 114 of file Terme_Boussinesq_base.h.
References Cerr, Probleme_base::domaine(), equation_scalaire(), Process::exit(), finl, inf_ou_egal(), Domaine::le_nom(), mp_moyenne_vect(), Equation_base::probleme(), Scalaire0(), sub_type, and sup_ou_egal().
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), and Terme_Boussinesq_PolyMAC_Face::ajouter().
{
// Pas de verification autre qu'au premier pas de temps, si verification pas desactivee et uniquement pour la temperature
  if (equation_scalaire().probleme().schema_temps().nb_pas_dt()>0 || equation_scalaire().probleme().reprise_effectuee() || verif_==0 || !sub_type(Convection_Diffusion_Temperature,equation_scalaire())) return;
// Nouveau : on verifie que moyenne(T)==T0 au demarrage du calcul uniquement
  const double& T0 = Scalaire0(0);
  double moyenne_T = mp_moyenne_vect(equation_scalaire().inconnue().valeurs());
  if (inf_ou_egal(moyenne_T,T0-10) || sup_ou_egal(moyenne_T,T0+10))
    {
      Cerr << "New criteria in TRUST for the Boussinesq source term definition:" << finl;
      Cerr << "To avoid an incorrect choice for T0 value" << finl;
      Cerr << "the initial average temperature on the domain " << equation_scalaire().probleme().domaine().le_nom() << finl;
      Cerr << "should be between +/-10 degrees around T0 value." << finl;
      Cerr << "The initial average temperature is : " << moyenne_T << finl;
      Cerr << "T0 value is : " << T0 << finl;
      Cerr << "So, you need to change T0 or the initial temperature field to respect this criteria defined by default." << finl;
      Cerr << "If you want to overcome this criteria, which it is not recommended," << finl;
      Cerr << "you can specify, into the Boussinesq source term definition, the option:" << finl;
      Cerr << "verif_boussinesq 0" << finl;
      Process::exit();
    }
}
virtual int Terme_Boussinesq_base::duplique () const [pure virtual]
Implements Source_base.
Implemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
const Convection_Diffusion_std& Terme_Boussinesq_base::equation_scalaire () const [inline]
Definition at line 83 of file Terme_Boussinesq_base.h.
References equation_scalaire_, and Ref_Convection_Diffusion_std::valeur().
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter(), and check().
  {
    return equation_scalaire_.valeur();
  };
const Type_info * Terme_Boussinesq_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 28 of file Terme_Boussinesq_base.cpp.
const Champ_Don_base& Terme_Boussinesq_base::gravite () const [inline]
Definition at line 67 of file Terme_Boussinesq_base.h.
References la_gravite_, and Ref_Champ_Don_base::valeur().
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), and Terme_Boussinesq_PolyMAC_Face::ajouter().
  {
    return la_gravite_.valeur();
  };
const Type_info * Terme_Boussinesq_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 28 of file Terme_Boussinesq_base.cpp.
Entree & Terme_Boussinesq_base::lire_donnees (Entree & is) [protected]
Lit les parametres du terme source a partir d'un flot d'entree.
Definition at line 108 of file Terme_Boussinesq_base.cpp.
References Cerr, vect_impl::dimensionner(), Process::exit(), fct_Scalaire0_, finl, NomScalaire_, read(), ArrOfDouble::resize(), Scalaire0_, Motcles::search(), and verif_.
Referenced by readOn().
{
  Cerr << "Reading Boussinesq source term parameters." << finl;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  verif_=1;
  Motcles les_mots(3);
  {
    les_mots[0]="T0";
    les_mots[1]="C0";
    les_mots[2]="verif_boussinesq";
  }
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error: { is waited instead of " << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  while (motlu!= accolade_fermee)
    {
      int rang = les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
// Temperature
            NomScalaire_="temperature";
            fct_Scalaire0_.dimensionner(1);
            Scalaire0_.resize(1);
            read(is, fct_Scalaire0_[0]);
            break;
          }
        case 1 :
          {
// Concentration
            NomScalaire_="concentration";
            int dim;
            is >> dim;
            fct_Scalaire0_.dimensionner(dim);
            Scalaire0_.resize(dim);
            for (int i=0; i<dim; i++)
              read(is, fct_Scalaire0_[i]);
            break;
          }
        case 2 :
          {
            is >> verif_;
            break;
          }
        default :
          {
            Cerr << "Error: " << motlu << " is not recognized." << finl;
            Cerr << "Possible keywords:" << finl;
            Cerr << les_mots << finl;
            Process::exit();
          }
        }
      is >> motlu;
    }
  return is;
}
void Terme_Boussinesq_base::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 92 of file Terme_Boussinesq_base.h.
References fct_Scalaire0_, Scalaire0_, and ArrOfDouble::size_array().
  {
    for (int i=0; i<Scalaire0_.size_array(); i++)
      {
        fct_Scalaire0_[i].setVar(0,temps);
        Scalaire0_[i] = fct_Scalaire0_[i].eval();
      }
  };
Sortie & Terme_Boussinesq_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 31 of file Terme_Boussinesq_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Boussinesq_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 37 of file Terme_Boussinesq_base.cpp.
References lire_donnees().
{
  return lire_donnees(s);
}
double Terme_Boussinesq_base::Scalaire0 (int i) const [inline]
Definition at line 75 of file Terme_Boussinesq_base.h.
References Scalaire0_.
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter(), and check().
  {
    return Scalaire0_(i);
  };
const Terme_Boussinesq_base & Terme_Boussinesq_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 28 of file Terme_Boussinesq_base.cpp.
Terme_Boussinesq_base & Terme_Boussinesq_base::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 28 of file Terme_Boussinesq_base.cpp.
int Terme_Boussinesq_base::verification () const [inline]
Definition at line 71 of file Terme_Boussinesq_base.h.
References verif_.
  {
    return verif_;
  };
Member Data Documentation
Ref_Champ_Don Terme_Boussinesq_base::beta_ [protected]
Definition at line 108 of file Terme_Boussinesq_base.h.
Referenced by associer_pb(), and beta().
Ref_Convection_Diffusion_std Terme_Boussinesq_base::equation_scalaire_ [protected]
Definition at line 109 of file Terme_Boussinesq_base.h.
Referenced by associer_pb(), and equation_scalaire().
Vect_Parser_U Terme_Boussinesq_base::fct_Scalaire0_ [protected]
Definition at line 107 of file Terme_Boussinesq_base.h.
Referenced by lire_donnees(), and mettre_a_jour().
const Type_info Terme_Boussinesq_base::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Terme_Boussinesq_CoviMAC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Boussinesq_VDF_Face, Terme_Boussinesq_VEF_Face, and Terme_Boussinesq_VEFPreP1B_Face.
Definition at line 62 of file Terme_Boussinesq_base.h.
Ref_Champ_Don_base Terme_Boussinesq_base::la_gravite_ [protected]
Definition at line 99 of file Terme_Boussinesq_base.h.
Referenced by associer_pb(), and gravite().
Nom Terme_Boussinesq_base::NomScalaire_ [protected]
Temperature ou Concentration.
Definition at line 106 of file Terme_Boussinesq_base.h.
Referenced by associer_pb(), and lire_donnees().
ArrOfDouble Terme_Boussinesq_base::Scalaire0_ [protected]
T0=Scalaire0_(0) ou C0(i)=Scalaire0_(i)
Definition at line 105 of file Terme_Boussinesq_base.h.
Referenced by lire_donnees(), mettre_a_jour(), and Scalaire0().
int Terme_Boussinesq_base::verif_ [protected]
Definition at line 104 of file Terme_Boussinesq_base.h.
Referenced by lire_donnees(), and verification().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Terme_Boussinesq_base.h
src/ThHyd/Incompressible/Sources/Terme_Boussinesq_base.cpp