TRUST: Champ_front_softanalytique Class Reference
Champ_front_softanalytique Class Reference
classe Champ_front_softanalytique
Classe derivee de Champ_front_var qui represente les
champs aux frontieres analytiques en espace et constants dans
le temps
Nouveau champ frontiere
il permet de mettre en champ frontiere un parametre qui depend d'une
fonction. Cette fonction est rentree dans le jeu de donnees sous
la forme d'une chaine de caracteres. Pas besoin de recompilation
comme avec la classe Champ_front_analytique qui utilise une
fonction codee en dur.
#include <Champ_front_softanalytique.h>
Public Member Functions
Champ_front_softanalytique ()
~Champ_front_softanalytique ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
void valeur_a (DoubleVect &position, DoubleVect &valeur)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_softanalytique & self_cast (Objet_U &)
static const
Champ_front_softanalytique & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
virtual Entree & readOn (Entree &)
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_softanalytique nb_compo vrel_1 ... [vrel_i].
Private Attributes
Vect_Parser_U fxyz
Detailed Description
classe Champ_front_softanalytique
Classe derivee de Champ_front_var qui represente les
champs aux frontieres analytiques en espace et constants dans
le temps
Nouveau champ frontiere
il permet de mettre en champ frontiere un parametre qui depend d'une
fonction. Cette fonction est rentree dans le jeu de donnees sous
la forme d'une chaine de caracteres. Pas besoin de recompilation
comme avec la classe Champ_front_analytique qui utilise une
fonction codee en dur.
Definition at line 46 of file Champ_front_softanalytique.h.
Constructor & Destructor Documentation
Champ_front_softanalytique::Champ_front_softanalytique ()
Definition at line 27 of file Champ_front_softanalytique.cpp.
Champ_front_softanalytique::~Champ_front_softanalytique ()
Definition at line 27 of file Champ_front_softanalytique.cpp.
Member Function Documentation
Objet_U * Champ_front_softanalytique::cree_instance () [static]
Definition at line 27 of file Champ_front_softanalytique.cpp.
int Champ_front_softanalytique::duplique () const [virtual]
Implements Ch_front_var_stationnaire.
Definition at line 27 of file Champ_front_softanalytique.cpp.
const Type_info * Champ_front_softanalytique::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_stationnaire.
Definition at line 27 of file Champ_front_softanalytique.cpp.
const Type_info * Champ_front_softanalytique::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_stationnaire.
Definition at line 27 of file Champ_front_softanalytique.cpp.
int Champ_front_softanalytique::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_var.
Definition at line 111 of file Champ_front_softanalytique.cpp.
References Objet_U::dimension, DoubleVect::echange_espace_virtuel(), Champ_front_base::frontiere_dis(), fxyz, Champ_front_var::initialiser(), Field_base::nb_comp(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, Champ_front_base::valeurs(), Zone_VF::xv(), and Champ_front_base::zone_dis().
{
  if (!Ch_front_var_stationnaire::initialiser(temps,inco))
    return 0;
  int dim=nb_comp();
  double x,y,z;
// int nbsf=faces.nb_som_faces();
  int k;
  DoubleTab& tab=valeurs();
  const Zone_VF& zone_vf=ref_cast(Zone_VF,frontiere_dis().zone_dis());
  const DoubleTab& xv=zone_vf.xv();
  const Front_VF& le_bord = ref_cast(Front_VF,frontiere_dis());
  int nb_faces_bord_tot=le_bord.nb_faces_tot();
  for (int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
    {
      int face = le_bord.num_face(ind_face);
      x=y=z=0;
      x=xv(face,0);
      if(dimension>1)
        y=xv(face,1);
      if(dimension>2)
        z=xv(face,2);
      for( k=0; k<dim; k++)
        {
          fxyz[k].setVar("x",x);
          fxyz[k].setVar("y",y);
          fxyz[k].setVar("z",z);
          tab(ind_face,k)=fxyz[k].eval();
// Cout << " x y z " << x << " " << y << " " << z << " " << tab(i,k) << finl;
        }
    }
  tab.echange_espace_virtuel();
  return 1;
}
Sortie & Champ_front_softanalytique::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_stationnaire.
Definition at line 45 of file Champ_front_softanalytique.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  /*  int dim =   nb_comp();
      for (int i = 0;i<dim;i++)
      {
      os << fxyz[i]->getString();
      }
      return os;*/
// Cout << " Dans printOn !!!!!!!!!!!!!!!!!!!!!!" << finl;
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_softanalytique::readOn (Entree & is) [protected, virtual]
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_softanalytique nb_compo vrel_1 ... [vrel_i].
Returns:
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_stationnaire.
Definition at line 79 of file Champ_front_softanalytique.cpp.
References Cerr, vect_impl::dimensionner(), finl, Field_base::fixer_nb_comp(), fxyz, Champ_Proto::lire_dimension(), and Objet_U::que_suis_je().
{
// Cout << "Dans  Champ_front_softanalytique.readOn !!!!!!!!!" << finl;
  int dim;
  dim=lire_dimension(is,que_suis_je());
  fixer_nb_comp(dim);
  fxyz.dimensionner(dim);
// Cout << "dim = " << dim << finl;
  for (int i = 0; i<dim; i++)
    {
      Nom tmp;
// Cout << "i = " << i << finl;
      is >> tmp;
// Cout << "fonc = " << tmp << finl;
      Cerr << "Reading and interpretation of the function " << tmp << finl;
      fxyz[i].setNbVar(3);
      fxyz[i].setString(tmp);
      fxyz[i].addVar("x");
      fxyz[i].addVar("y");
      fxyz[i].addVar("z");
      fxyz[i].parseString();
      Cerr << "Interpretation of the function " << tmp << " Ok" << finl;
// Cout << "end = " << tmp << finl;
    }
  return is;
}
const Champ_front_softanalytique & Champ_front_softanalytique::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_stationnaire.
Definition at line 27 of file Champ_front_softanalytique.cpp.
Champ_front_softanalytique & Champ_front_softanalytique::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_stationnaire.
Definition at line 27 of file Champ_front_softanalytique.cpp.
unsigned Champ_front_softanalytique::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Champ_front_softanalytique.cpp.
void Champ_front_softanalytique::valeur_a (DoubleVect & position, DoubleVect & valeur)
Definition at line 152 of file Champ_front_softanalytique.cpp.
References Objet_U::dimension, fxyz, Field_base::nb_comp(), DoubleVect::resize(), and DoubleVect::size().
{
  assert(position.size() == Objet_U::dimension);
  double x = position[0];
  double y = position[1];
  double z = 0.;
  if (Objet_U::dimension == 3) z = position[2];
  int dim = nb_comp();
  valeur.resize(dim);
  for (int k=0; k<dim; k++)
    {
      fxyz[k].setVar("x",x);
      fxyz[k].setVar("y",y);
      fxyz[k].setVar("z",z);
      valeur[k] = fxyz[k].eval();
    }
  return;
}
Member Data Documentation
Vect_Parser_U Champ_front_softanalytique::fxyz [private]
Definition at line 55 of file Champ_front_softanalytique.h.
Referenced by initialiser(), readOn(), and valeur_a().
const Type_info Champ_front_softanalytique::info_obj [static]
Reimplemented from Ch_front_var_stationnaire.
Definition at line 48 of file Champ_front_softanalytique.h.
The documentation for this class was generated from the following files:
src/Kernel/VF/Champs/Champ_front_softanalytique.h
src/Kernel/VF/Champs/Champ_front_softanalytique.cpp