TRUST: Raccord_distant_homogene Class Reference
Raccord_distant_homogene Class Reference
#include <Raccord_distant_homogene.h>
Public Member Functions
~Raccord_distant_homogene ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Raccord_distant_homogene ()
IntTab & Tab_Envoi ()
ArrOfInt & Tab_Recep ()
Nom & nom_frontiere_voisine ()
int & est_initialise ()
double & e ()
const int & est_initialise () const
const double & e () const
void trace_elem_distant (const DoubleTab &, DoubleTab &) const override
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux elements du domaine distant.
void trace_face_distant (const DoubleTab &, DoubleTab &) const override
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux faces.
void trace_face_distant (const DoubleVect &, DoubleVect &) const override
Retourne dans le DoubleVect x la trace sur le raccord distant du DoubleVect y localise aux faces du raccord distant.
void completer ()
void initialise (const Frontiere &, const Zone_dis_base &, const Zone_dis_base &)
Initialise le raccord distant avec la frontiere et la zone discretisee opposees au raccord distant, et la zone discretisee du raccord distant.
Public Member Functions inherited from Raccord_distant
Raccord_distant ()
~Raccord_distant () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Raccord_base
Raccord_base ()
~Raccord_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Frontiere
Frontiere ()
~Frontiere () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe la frontiere a la zone dont elle depend.
const Zone & zone () const
Renvoie la Zone associee a la frontiere.
(version const)
Zone & zone ()
Renvoie la Zone associee a la frontiere.
void nommer (const Nom &) override
Donne un nom a la frontiere.
void ajouter_faces (const IntTab &)
Ajoute une (ou plusieurs) face(s) a la frontiere,
la (les) face(s) est (sont) specifiee(s) par un tableau
contenant les numeros des sommets.
void typer_faces (const Motcle &)
Type les faces de la frontiere.
void typer_faces (const Type_Face &)
Type les faces de la frontiere.
const Faces & faces () const
Renvoie les faces de la frontiere<br>(version const)
Faces & faces ()
Renvoie les faces de la frontiere.
IntTab & les_sommets_des_faces ()
Renvoie les sommets des faces de la frontiere.
const IntTab & les_sommets_des_faces () const
Renvoie les sommets des faces de la frontiere.
int nb_faces () const
Renvoie le nombre de faces de la frontiere.
void dimensionner (int)
Dimensionne la frontiere, i.e. fixe
son nombre de faces.
const Nom & le_nom () const override
Renvoie le nom de la frontiere.
void renum (const IntVect &)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void add (const Frontiere &)
Ajoute les sommets (et faces) de la frontiere
passee en parametre a l'objet (Frontiere).
int nb_faces_virt () const
int face_virt (int i) const
int num_premiere_face () const
void fixer_num_premiere_face (int)
const ArrOfInt & get_faces_virt () const
ArrOfInt & get_faces_virt ()
const double & get_aire () const
void set_aire (double &aire)
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par face de cette frontiere
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void trace_elem_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux elements y.
virtual void trace_face_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_face_local (const DoubleVect &, DoubleVect &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_elem_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_som_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleVect &, DoubleVect &) const
virtual void trace_som_local (const DoubleTab &y, DoubleTab &x) const
Renvoie la trace sur la frontiere du tableau aux noeuds y.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Raccord_distant_homogene & self_cast (Objet_U &)
static const Raccord_distant_homogene & self_cast (const Objet_U &)
Static Public Member Functions inherited from Raccord_distant
static const Type_info * info ()
static Raccord_distant & self_cast (Objet_U &)
static const Raccord_distant & self_cast (const Objet_U &)
Static Public Member Functions inherited from Raccord_base
static const Type_info * info ()
static Raccord_base & self_cast (Objet_U &)
static const Raccord_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Frontiere
static const Type_info * info ()
static Frontiere & self_cast (Objet_U &)
static const Frontiere & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Raccord_distant
static const Type_info info_obj
Static Public Attributes inherited from Raccord_base
static const Type_info info_obj
Static Public Attributes inherited from Frontiere
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Raccord_distant::printOn(Sortie&)
(+ finl)
Entree & readOn (Entree &) override
Simple appel a: Raccord_distant::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a: Raccord_base::printOn(Sortie&)
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Simple appel a: Frontiere::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Frontiere::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit la frontiere sur un flot de sortie.
On ecrit:
le nom de la frontiere
les faces.
Entree & readOn (Entree &) override
Lit les specification d'une frontiere
a partir d'un flot d'entree.
On lit:
le nom
les faces.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
const IntTab & Tab_Envoi () const
const ArrOfInt & Tab_Recep () const
Private Attributes
IntTab tab_envoi
ArrOfInt tab_recep
Nom nom_frontiere_voisine_
int est_initialise_
double e_
ArrOfInt send_pe_list_
ArrOfInt recv_pe_list_
Detailed Description
Definition at line 20 of file Raccord_distant_homogene.h.
Constructor & Destructor Documentation
~Raccord_distant_homogene()
Raccord_distant_homogene::~Raccord_distant_homogene ()
Definition at line 33 of file Raccord_distant_homogene.cpp.
Raccord_distant_homogene()
Raccord_distant_homogene::Raccord_distant_homogene ()
Definition at line 95 of file Raccord_distant_homogene.cpp.
                                                   : est_initialise_(0),e_(0)
{}
Member Function Documentation
completer()
void Raccord_distant_homogene::completer (void)
Definition at line 216 of file Raccord_distant_homogene.cpp.
{
  const IntTab& send_data = Tab_Envoi();
  const ArrOfInt& recv_data = Tab_Recep();
  const int n1 = send_data.dimension(0);
  const int n2 = recv_data.size_array();
  send_pe_list_.set_smart_resize(1);
  recv_pe_list_.set_smart_resize(1);
  const int nbproc = Process::nproc();
  ArrOfBit flags(nbproc);
  flags = 0;
  for (int i = 0; i < n1; i++)
    {
      const int pe = send_data(i, 0);
      if (!flags.testsetbit(pe))
        send_pe_list_.append_array(pe);
    }
  flags = 0;
  for (int i = 0; i < n2; i++)
    {
      const int pe = recv_data[i];
      if (!flags.testsetbit(pe))
        recv_pe_list_.append_array(pe);
    }
  send_pe_list_.ordonne_array();
  recv_pe_list_.ordonne_array();
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::dimension(), Process::nproc(), TRUSTArray< _TYPE_ >::ordonne_array(), recv_pe_list_, send_pe_list_, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Tab_Envoi(), Tab_Recep(), and ArrOfBit::testsetbit().
Referenced by initialise().
cree_instance()
Objet_U * Raccord_distant_homogene::cree_instance () static
Definition at line 33 of file Raccord_distant_homogene.cpp.
duplique()
int Raccord_distant_homogene::duplique () const override virtual
Implements Objet_U.
Definition at line 33 of file Raccord_distant_homogene.cpp.
e() [1/2]
double & Raccord_distant_homogene::e () inline
Definition at line 116 of file Raccord_distant_homogene.h.
{
  return e_;
}
References e_.
Referenced by initialise().
e() [2/2]
const double & Raccord_distant_homogene::e () const inline
Definition at line 125 of file Raccord_distant_homogene.h.
{
  return e_;
}
References e_.
est_initialise() [1/2]
int & Raccord_distant_homogene::est_initialise () inline
Definition at line 28 of file Raccord_distant_homogene.h.
  {
    return est_initialise_;
  };
References est_initialise_.
Referenced by Champ_front_calc::completer(), initialise(), trace_elem_distant(), and trace_face_distant().
est_initialise() [2/2]
const int & Raccord_distant_homogene::est_initialise () const inline
Definition at line 120 of file Raccord_distant_homogene.h.
{
  return est_initialise_;
}
References est_initialise_.
get_info()
const Type_info * Raccord_distant_homogene::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Raccord_distant.
Definition at line 33 of file Raccord_distant_homogene.cpp.
info()
const Type_info * Raccord_distant_homogene::info () static
Definition at line 33 of file Raccord_distant_homogene.cpp.
initialise()
void Raccord_distant_homogene::initialise (const Frontiere & opposed_boundary, const Zone_dis_base & opposed_zone_dis, const Zone_dis_base & zone_dis)
Initialise le raccord distant avec la frontiere et la zone discretisee opposees au raccord distant, et la zone discretisee du raccord distant.
Definition at line 246 of file Raccord_distant_homogene.cpp.
{
  Raccord_distant_homogene& raccord_distant = *this;
  if(raccord_distant.est_initialise())
    {
      Cerr << "Remote connection " << raccord_distant.le_nom() << " already initialized." << finl;
      Cerr << "Error, contact TRUST support." << finl;
      exit();
    }
  int dim=Objet_U::dimension;
  raccord_distant.nom_frontiere_voisine()=opposed_boundary.le_nom();
  const Zone_VF& zone_dis_vf = ref_cast(Zone_VF, zone_dis);
// On va identifier les faces par leur centres de gravite
  int parts = Process::nproc();
  DoubleTabs remote_xv(parts);
  int prem_face2 = raccord_distant.num_premiere_face();
  int nb_face2   = raccord_distant.nb_faces();
  int moi = Process::me();
  remote_xv[moi].resize(nb_face2,dim);
  for (int ind_face=0 ; ind_face < nb_face2 ; ind_face++)
    {
      int face = prem_face2 + ind_face;
      for (int j=0 ; j<dim ; j++)
        remote_xv[moi](ind_face,j) = zone_dis_vf.xv(face,j);
    }
// Puis on echange les tableaux des centres de gravites
// envoi des tableaux
  for (int p = 0; p < parts; p++)
    envoyer_broadcast(remote_xv[p], p);
  ArrsOfInt racc_vois(parts);
  for (int p = 0; p < parts; p++)
    racc_vois[p].set_smart_resize(1);
#ifdef MEDCOUPLING_
// On traite les informations, chaque proc connait tous les XV
// Si le proc porte un morceau du raccord_distant
  int prem_face1 = opposed_boundary.num_premiere_face();
  int nb_face1   = opposed_boundary.nb_faces();
  if (nb_face1>0)
    {
      const Zone_VF& opposed_zone_dis_vf = ref_cast(Zone_VF,opposed_zone_dis);
      const DoubleTab& local_xv = opposed_zone_dis_vf.xv();
      ArrOfInt& Recep=raccord_distant.Tab_Recep();
      Recep.resize_array(nb_face1);
// double tolerance = 1e-8; //not very tolerant, are we?
      double tolerance = Objet_U::precision_geom * 100 ; //default value 1e-8 not very tolerant, are we?
// DataArrayDoubles des xv locaux et de tous les remote_xv (a la suite)
      std::vector<MCAuto<DataArrayDouble> > vxv(parts);
      std::vector<const DataArrayDouble*> cvxv(parts);
      for (int p = 0; p < parts; p++)
        {
          vxv[p] = DataArrayDouble::New();
          vxv[p]->useExternalArrayWithRWAccess(remote_xv[p].addr(), remote_xv[p].dimension(0), remote_xv[p].dimension(1));
          cvxv[p] = vxv[p];
        }
      MCAuto<DataArrayDouble> remote_xvs(DataArrayDouble::Aggregate(cvxv)), local_xvs(DataArrayDouble::New());
      local_xvs->alloc(nb_face1, dim);
      for (int ind_face = 0; ind_face < nb_face1; ind_face++)
        for (int j = 0; j < dim; j++)
          local_xvs->setIJ(ind_face, j, local_xv(prem_face1 + ind_face, j));
// indices des points de remote_xvs les plus proches de chaque point de local_xv
      MCAuto<DataArrayInt> glob_idx(DataArrayInt::New());
      glob_idx = remote_xvs->findClosestTupleId(local_xvs);
// pour chaque face de local_xv : controle de la tolerance, remplissage de tableau
      for (int ind_face = 0, face1 = prem_face1; ind_face<nb_face1; ind_face++, face1++)
        {
// retour de l'indice global (glob_idx(ind_face)) au couple (proc, ind_face2)
          int proc = 0, ind_face2 = glob_idx->getIJ(ind_face, 0);
          while (ind_face2 >= remote_xv[proc].dimension(0)) ind_face2 -= remote_xv[proc].dimension(0), proc++;
          assert(ind_face2 < remote_xv[proc].dimension(0));
// controle de la tolerance
          double distance2 = 0;
          for (int j=0; j<dim; j++)
            {
              double x1=local_xv(face1,j);
              double x2=remote_xv[proc](ind_face2,j);
              distance2 += (x1-x2)*(x1-x2);
            }
          if (distance2 > tolerance * tolerance)
            {
              Cerr << "Warning, there is no remote face found on the local boundary " << opposed_boundary.le_nom() << " for the face local number " << ind_face << " (";
              for (int j=0; j<dim; j++) Cerr << " " << local_xv(face1,j);
              Cerr << " )" << finl << "the nearest face on the remote boundary " << raccord_distant.le_nom() << " is the face " << ind_face2 << " (";
              for (int j=0; j<dim; j++) Cerr << " " << remote_xv[proc](ind_face2,j);
              Cerr << " )" << finl << "which is located at a distance of " << sqrt(distance2) << " and it is above the geometric tolerance " << tolerance << finl;
              Cerr << "Check your mesh or contact TRUST support." << finl;
              Process::exit();
            }
// remplissage des tableaux
          Recep[ind_face]=proc;
          racc_vois[proc].append_array(ind_face2);
        }
    }
#else
  Cerr<<"Raccord_distant_homogene needs TRUST compiled with MEDCoupling."<<finl;
  exit();
#endif
  ArrsOfInt facteurs(Process::nproc());
  envoyer_all_to_all(racc_vois, facteurs);
  IntTab& Envoi = raccord_distant.Tab_Envoi();
  if (nb_face2 > 0)
    Envoi.resize(nb_face2, 2);
  int ind = 0;
  for (int p = 0; p < parts; p++)
    {
      const ArrOfInt& facteur = facteurs[p];
      const int sz = facteur.size_array();
      for (int d=0 ; d<sz ; d++)
        {
          Envoi(ind,0) = p;
          Envoi(ind,1) = facteur[d];
          ind++;
        }
    }
  raccord_distant.e() = 0;
  raccord_distant.est_initialise() = 1;
  raccord_distant.completer();
  Cerr <<"Initialize the remote connection " << zone_dis.zone().domaine().le_nom() << "/" << raccord_distant.le_nom() << "<-" << opposed_zone_dis.zone().domaine().le_nom() << "/" << opposed_boundary.le_nom() << finl;
}
References Cerr, completer(), Objet_U::dimension, Zone::domaine(), e(), envoyer_all_to_all(), envoyer_broadcast(), est_initialise(), Process::exit(), finl, Domaine::le_nom(), Frontiere::le_nom(), Process::me(), Frontiere::nb_faces(), nom_frontiere_voisine(), Process::nproc(), Frontiere::num_premiere_face(), Objet_U::precision_geom, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), Tab_Envoi(), Tab_Recep(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by Champ_front_calc::completer(), and Champ_front_contact_VEF::completer().
nom_frontiere_voisine()
Nom & Raccord_distant_homogene::nom_frontiere_voisine () inline
Definition at line 111 of file Raccord_distant_homogene.h.
{
  return nom_frontiere_voisine_;
}
References nom_frontiere_voisine_.
Referenced by initialise().
printOn()
Sortie & Raccord_distant_homogene::printOn (Sortie & s) const override protected virtual
Simple appel a: Raccord_distant::printOn(Sortie&)
(+ finl)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Raccord_distant.
Definition at line 50 of file Raccord_distant_homogene.cpp.
{
  Raccord_distant::printOn(s) << finl;
  s << (int)1 <<finl;
  s << tab_envoi << finl;
  s << tab_recep << finl;
  s << nom_frontiere_voisine_ << finl;
  s << est_initialise_ << finl;
  s << e_ << finl;
  return s;
}
References e_, est_initialise_, finl, nom_frontiere_voisine_, Raccord_distant::printOn(), tab_envoi, and tab_recep.
readOn()
Entree & Raccord_distant_homogene::readOn (Entree & s) override protected virtual
Simple appel a: Raccord_distant::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Raccord_distant.
Definition at line 79 of file Raccord_distant_homogene.cpp.
{
  Raccord_distant::readOn(s) ;
  int flag;
  s >> flag;
  if(flag==1)
    {
      s >> tab_envoi;
      s >> tab_recep;
      s >> nom_frontiere_voisine_;
      s >> est_initialise_;
      s >> e_;
    }
  return s;
}
References e_, est_initialise_, nom_frontiere_voisine_, Raccord_distant::readOn(), tab_envoi, and tab_recep.
self_cast() [1/2]
const Raccord_distant_homogene & Raccord_distant_homogene::self_cast (const Objet_U & r) static
Definition at line 33 of file Raccord_distant_homogene.cpp.
self_cast() [2/2]
Raccord_distant_homogene & Raccord_distant_homogene::self_cast (Objet_U & r) static
Definition at line 33 of file Raccord_distant_homogene.cpp.
Tab_Envoi() [1/2]
IntTab & Raccord_distant_homogene::Tab_Envoi () inline
Definition at line 65 of file Raccord_distant_homogene.h.
{
  return tab_envoi;
}
References tab_envoi.
Referenced by completer(), initialise(), trace_elem_distant(), and trace_face_distant().
Tab_Envoi() [2/2]
const IntTab & Raccord_distant_homogene::Tab_Envoi () const inline private
Definition at line 69 of file Raccord_distant_homogene.h.
{
  return tab_envoi;
}
References tab_envoi.
Tab_Recep() [1/2]
ArrOfInt & Raccord_distant_homogene::Tab_Recep () inline
Definition at line 88 of file Raccord_distant_homogene.h.
{
  return tab_recep;
}
References tab_recep.
Referenced by completer(), initialise(), trace_elem_distant(), and trace_face_distant().
Tab_Recep() [2/2]
const ArrOfInt & Raccord_distant_homogene::Tab_Recep () const inline private
Definition at line 92 of file Raccord_distant_homogene.h.
{
  return tab_recep;
}
References tab_recep.
taille_memoire()
unsigned Raccord_distant_homogene::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 33 of file Raccord_distant_homogene.cpp.
trace_elem_distant()
void Raccord_distant_homogene::trace_elem_distant (const DoubleTab & y, DoubleTab & x) const override virtual
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux elements du domaine distant.
Reimplemented from Frontiere.
Definition at line 100 of file Raccord_distant_homogene.cpp.
{
  assert(est_initialise());
  const int nb_compo_= y.line_size();
  const IntTab& send_data = Tab_Envoi();
  const ArrOfInt& recv_data = Tab_Recep();
  const Faces& lesfaces = faces();
  const int n1 = send_data.dimension(0);
  const int n2 = recv_data.size_array();
// On dimensionne x si ce n'est pas fait
  if (x.size_array()==0 && n2!=0)
    x.resize(n2, nb_compo_);
  else if (x.dimension(0) != n2)
    {
      Cerr << "Call to Frontiere::trace_elem with a DoubleTab x not located on boundary faces." << finl;
      Process::exit();
    }
  Schema_Comm schema;
  schema.set_send_recv_pe_list(send_pe_list_, recv_pe_list_);
  schema.begin_comm();
  for (int i = 0; i < n1; i++)
    {
      const int pe_dest = send_data(i, 0);
      const int face  = send_data(i, 1);
      int item = lesfaces.voisin(face,0);
      if (item == -1)
        item = lesfaces.voisin(face,1);
      for (int j=0; j<nb_compo_; j++)
        schema.send_buffer(pe_dest) << y(item,j);
    }
  schema.echange_taille_et_messages();
  for (int i = 0; i < n2; i++)
    {
      const int pe_source = recv_data[i];
      for(int j=0; j<nb_compo_; j++)
        schema.recv_buffer(pe_source) >> x(i,j);
    }
  schema.end_comm();
}
References Schema_Comm::begin_comm(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), est_initialise(), Process::exit(), Frontiere::faces(), finl, TRUSTVect< _TYPE_ >::line_size(), Schema_Comm::recv_buffer(), recv_pe_list_, TRUSTTab< _TYPE_ >::resize(), Schema_Comm::send_buffer(), send_pe_list_, Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_ >::size_array(), Tab_Envoi(), Tab_Recep(), and Faces::voisin().
trace_face_distant() [1/2]
void Raccord_distant_homogene::trace_face_distant (const DoubleTab & y, DoubleTab & x) const override virtual
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux faces.
Reimplemented from Frontiere.
Definition at line 146 of file Raccord_distant_homogene.cpp.
{
  assert(est_initialise());
  int n, N = y.line_size();
  const IntTab& send_data = Tab_Envoi();
  const ArrOfInt& recv_data = Tab_Recep();
  const int n1 = send_data.dimension(0);
  const int n2 = recv_data.size_array();
// On dimensionne x si ce n'est pas fait
  if (x.size_array()==0 && n2!=0)
    {
      if (y.nb_dim() == 2) x.resize(n2, y.dimension(1));
      else if (y.nb_dim() == 3) x.resize(n2, y.dimension(1), y.dimension(2));
      else if (y.nb_dim() == 4) x.resize(n2, y.dimension(1), y.dimension(2), y.dimension(3));
    }
  Schema_Comm schema;
  schema.set_send_recv_pe_list(send_pe_list_, recv_pe_list_);
  schema.begin_comm();
  for (int i = 0; i < n1; i++)
    {
      const int pe_dest = send_data(i, 0);
      const int face  = num_premiere_face() + send_data(i, 1);
      for (n = 0; n < N; n++) schema.send_buffer(pe_dest) << y.addr()[N * face + n];
    }
  schema.echange_taille_et_messages();
  for (int i = 0; i < n2; i++)
    {
      const int pe_source = recv_data[i];
      for (n = 0; n < N; n++) schema.recv_buffer(pe_source) >> x.addr()[N * i + n];
    }
  schema.end_comm();
}
References TRUSTArray< _TYPE_ >::addr(), Schema_Comm::begin_comm(), TRUSTTab< _TYPE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), est_initialise(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Frontiere::num_premiere_face(), Schema_Comm::recv_buffer(), recv_pe_list_, TRUSTTab< _TYPE_ >::resize(), Schema_Comm::send_buffer(), send_pe_list_, Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_ >::size_array(), Tab_Envoi(), and Tab_Recep().
trace_face_distant() [2/2]
void Raccord_distant_homogene::trace_face_distant (const DoubleVect & y, DoubleVect & x) const override virtual
Retourne dans le DoubleVect x la trace sur le raccord distant du DoubleVect y localise aux faces du raccord distant.
Reimplemented from Frontiere.
Definition at line 184 of file Raccord_distant_homogene.cpp.
{
// Verifie que l'on passe bien un tableau aux faces du raccord
  assert(y.size()==nb_faces());
  assert(est_initialise());
  const IntTab& send_data = Tab_Envoi();
  const ArrOfInt& recv_data = Tab_Recep();
  const int n1 = send_data.dimension(0);
  const int n2 = recv_data.size_array();
// On dimensionne x si ce n'est pas fait
  if (x.size_array()==0 && n2!=0)
    x.resize(n2);
  Schema_Comm schema;
  schema.set_send_recv_pe_list(send_pe_list_, recv_pe_list_);
  schema.begin_comm();
  for (int i = 0; i < n1; i++)
    {
      const int pe_dest = send_data(i, 0);
      const int face  = send_data(i, 1);
      schema.send_buffer(pe_dest) << y(face);
    }
  schema.echange_taille_et_messages();
  for (int i = 0; i < n2; i++)
    {
      const int pe_source = recv_data[i];
      schema.recv_buffer(pe_source) >> x(i);
    }
  schema.end_comm();
}
References Schema_Comm::begin_comm(), TRUSTTab< _TYPE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), est_initialise(), Frontiere::nb_faces(), Schema_Comm::recv_buffer(), recv_pe_list_, TRUSTVect< _TYPE_ >::resize(), Schema_Comm::send_buffer(), send_pe_list_, Schema_Comm::set_send_recv_pe_list(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), Tab_Envoi(), and Tab_Recep().
Member Data Documentation
e_
double Raccord_distant_homogene::e_ private
Definition at line 47 of file Raccord_distant_homogene.h.
Referenced by e(), printOn(), and readOn().
est_initialise_
int Raccord_distant_homogene::est_initialise_ private
Definition at line 46 of file Raccord_distant_homogene.h.
Referenced by est_initialise(), printOn(), and readOn().
info_obj
const Type_info Raccord_distant_homogene::info_obj static
Definition at line 22 of file Raccord_distant_homogene.h.
nom_frontiere_voisine_
Nom Raccord_distant_homogene::nom_frontiere_voisine_ private
Definition at line 45 of file Raccord_distant_homogene.h.
Referenced by nom_frontiere_voisine(), printOn(), and readOn().
recv_pe_list_
ArrOfInt Raccord_distant_homogene::recv_pe_list_ private
Definition at line 50 of file Raccord_distant_homogene.h.
Referenced by completer(), trace_elem_distant(), and trace_face_distant().
send_pe_list_
ArrOfInt Raccord_distant_homogene::send_pe_list_ private
Definition at line 49 of file Raccord_distant_homogene.h.
Referenced by completer(), trace_elem_distant(), and trace_face_distant().
tab_envoi
IntTab Raccord_distant_homogene::tab_envoi private
Definition at line 43 of file Raccord_distant_homogene.h.
Referenced by printOn(), readOn(), and Tab_Envoi().
tab_recep
ArrOfInt Raccord_distant_homogene::tab_recep private
Definition at line 44 of file Raccord_distant_homogene.h.
Referenced by printOn(), readOn(), and Tab_Recep().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raccord_distant_homogene.h
src/Kernel/Geometrie/Raccord_distant_homogene.cpp