TRUST: Couplage_U Class Reference
Couplage_U Class Reference
class Couplage_U
Cette classe implemente Probleme_U dans le cas d'un probleme composite
couplant plusieurs Probleme_U.
#include <Couplage_U.h>
Public Member Functions
Couplage_U ()
~Couplage_U ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
int limpr () const override
Doit-on imprimer les statistiques d'execution maintenant ?
int lsauv () const override
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
void sauver () const override
Sauvegarder l'etat du probleme sur disque.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
void addProblem (Probleme_U &)
Append a problem to the list.
int nb_problemes () const
Number of problems.
const Probleme_U & probleme (int i) const
Access by index (const)
Probleme_U & probleme (int i)
Access by index.
const Probleme_U & probleme (const Nom &nom_pb) const
Access by name (const)
Probleme_U & probleme (const Nom &nom_pb)
Access by name.
int indice_probleme (const Nom &nom_pb) const
Index from name.
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Couplage_U & self_cast (Objet_U &)
static const Couplage_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Probleme_U
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
List_Ref_Probleme_U problems
Additional Inherited Members
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Detailed Description
class Couplage_U
Cette classe implemente Probleme_U dans le cas d'un probleme composite
couplant plusieurs Probleme_U.
Definition at line 34 of file Couplage_U.h.
Constructor & Destructor Documentation
Couplage_U()
Couplage_U::Couplage_U ()
Definition at line 20 of file Couplage_U.cpp.
~Couplage_U()
Couplage_U::~Couplage_U ()
Definition at line 20 of file Couplage_U.cpp.
Member Function Documentation
abortTimeStep()
void Couplage_U::abortTimeStep () override virtual
Aborts the resolution of the current time step.
Reimplemented from Probleme_U.
Definition at line 87 of file Couplage_U.cpp.
{
  for(int i=0; i<nb_problemes(); i++)
    probleme(i).abortTimeStep();
}
References Probleme_U::abortTimeStep(), nb_problemes(), and probleme().
addProblem()
void Couplage_U::addProblem (Probleme_U & pb) inline
Append a problem to the list.
Definition at line 108 of file Couplage_U.h.
{
  problems.add(pb);
}
References List_Ref_Probleme_U::add(), and problems.
Referenced by Probleme_Couple::ajouter().
cree_instance()
Objet_U * Couplage_U::cree_instance () static
Definition at line 20 of file Couplage_U.cpp.
duplique()
int Couplage_U::duplique () const override virtual
Implements Objet_U.
Reimplemented in Probleme_Couple, and Pbc_MED.
Definition at line 20 of file Couplage_U.cpp.
findInputField()
Ref_Field_base Couplage_U::findInputField (const Nom & name) const override virtual
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Returns
REF(Field_base)
Signification: found <=> non_nul(), then points to a Champ_Input_Proto of that name.
Contraintes:
Reimplemented from Probleme_U.
Definition at line 165 of file Couplage_U.cpp.
{
  REF(Field_base) ch;
  for (int i=0; i<nb_problemes(); i++)
    {
      ch=probleme(i).findInputField(name);
      if (ch.non_nul())
        return ch;
    }
  return ch;
}
References Probleme_U::findInputField(), nb_problemes(), probleme(), and REF.
findOutputField()
Ref_Champ_Generique_base Couplage_U::findOutputField (const Nom & name) const override virtual
Reimplemented from Probleme_U.
Definition at line 176 of file Couplage_U.cpp.
{
  REF(Champ_Generique_base) ch;
  for (int i=0; i<nb_problemes(); i++)
    {
      ch=probleme(i).findOutputField(name);
      if (ch.non_nul())
        return ch;
    }
  return ch;
}
References Probleme_U::findOutputField(), nb_problemes(), probleme(), and REF.
futureTime()
double Couplage_U::futureTime () const override virtual
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Returns
double
Signification: future time
Contraintes:
Reimplemented from Probleme_U.
Definition at line 159 of file Couplage_U.cpp.
{
  assert(nb_problemes()>0);
  return probleme(0).futureTime();
}
References Probleme_U::futureTime(), nb_problemes(), and probleme().
get_info()
const Type_info * Couplage_U::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Probleme_Couple, and Pbc_MED.
Definition at line 20 of file Couplage_U.cpp.
getInputFieldsNames()
void Couplage_U::getInputFieldsNames (Noms & noms) const override virtual
This method is used to find the names of input fields understood by the Problem.
Reimplemented from Probleme_U.
Definition at line 108 of file Couplage_U.cpp.
{
  for (int i=0; i<nb_problemes(); i++)
    probleme(i).getInputFieldsNames(noms);
}
References Probleme_U::getInputFieldsNames(), nb_problemes(), and probleme().
getOutputFieldsNames()
void Couplage_U::getOutputFieldsNames (Noms & noms) const override virtual
This method is used to find the names of output fields understood by the Problem.
Reimplemented from Probleme_U.
Definition at line 114 of file Couplage_U.cpp.
{
  for (int i=0; i<nb_problemes(); i++)
    probleme(i).getOutputFieldsNames(noms);
}
References Probleme_U::getOutputFieldsNames(), nb_problemes(), and probleme().
indice_probleme()
int Couplage_U::indice_probleme (const Nom & nom_pb) const
Index from name.
Definition at line 209 of file Couplage_U.cpp.
{
  int i=0;
  while ((i< nb_problemes()))
    {
      if(probleme(i).le_nom()==nom_pb)
        {
          return i;
        }
      i++;
    }
  Cerr << "Problem " << nom_pb
       << " not found in Couplage_U " << le_nom() << finl;
  exit();
// Avoid compiler warning
  return 0;
}
References Cerr, Process::exit(), finl, Probleme_U::le_nom(), nb_problemes(), and probleme().
Referenced by probleme().
info()
const Type_info * Couplage_U::info () static
Definition at line 20 of file Couplage_U.cpp.
initialize()
void Couplage_U::initialize () override virtual
This method is called once at the beginning, before any other one of
the interface Problem.
Reimplemented from Probleme_U.
Reimplemented in Probleme_Couple.
Definition at line 29 of file Couplage_U.cpp.
{
  for(int i=0; i<nb_problemes(); i++)
    probleme(i).initialize();
}
References Probleme_U::initialize(), nb_problemes(), and probleme().
Referenced by Probleme_Couple::initialize().
initTimeStep()
bool Couplage_U::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Reimplemented from Probleme_U.
Reimplemented in Probleme_Couple.
Definition at line 47 of file Couplage_U.cpp.
{
  bool ok=true;
  for(int i=0; i<nb_problemes(); i++)
    ok = ok && probleme(i).initTimeStep(dt);
  return ok;
}
References Probleme_U::initTimeStep(), nb_problemes(), and probleme().
Referenced by Probleme_Couple::initTimeStep().
isStationary()
bool Couplage_U::isStationary () const override virtual
Tells if the Problem unknowns have changed during the last time step.
Returns
bool
Signification: true=stationary, false=not stationary
Contraintes:
Reimplemented from Probleme_U.
Definition at line 73 of file Couplage_U.cpp.
{
  bool stat=true;
  for(int i=0; i<nb_problemes(); i++)
    stat = stat && probleme(i).isStationary();
  return stat;
}
References Probleme_U::isStationary(), nb_problemes(), and probleme().
iterateTimeStep()
bool Couplage_U::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
Returns
bool
Signification: true=OK, false=unable to converge
Contraintes:
Reimplemented from Probleme_U.
Reimplemented in Probleme_Couple.
Definition at line 94 of file Couplage_U.cpp.
{
  bool ok=true;
  converged=true;
  for(int i=0; i<nb_problemes(); i++)
    {
      bool cv;
      ok = ok && probleme(i).iterateTimeStep(cv);
      converged = converged && cv;
    }
  return ok;
}
References Probleme_U::iterateTimeStep(), nb_problemes(), and probleme().
limpr()
int Couplage_U::limpr () const override virtual
Doit-on imprimer les statistiques d'execution maintenant ?
Reimplemented from Probleme_U.
Definition at line 129 of file Couplage_U.cpp.
{
  bool ok=false;
  for(int i=0; i<nb_problemes(); i++)
    ok = ok || probleme(i).limpr();
  return ok;
}
References Probleme_U::limpr(), nb_problemes(), and probleme().
lsauv()
int Couplage_U::lsauv () const override virtual
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
Reimplemented from Probleme_U.
Definition at line 137 of file Couplage_U.cpp.
{
  bool ok=false;
  for(int i=0; i<nb_problemes(); i++)
    ok = ok || probleme(i).lsauv();
  return ok;
}
References Probleme_U::lsauv(), nb_problemes(), and probleme().
nb_problemes()
int Couplage_U::nb_problemes () const inline
Number of problems.
Definition at line 113 of file Couplage_U.h.
{
  return problems.size();
}
References problems, and liste::size().
Referenced by abortTimeStep(), Probleme_Couple::ajouter(), Probleme_Couple::associer_sch_tps_base(), Probleme_Couple::computeTimeStep(), Probleme_Couple::discretiser(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), findInputField(), findOutputField(), futureTime(), getInputFieldsNames(), getOutputFieldsNames(), indice_probleme(), initialize(), Probleme_Couple::initialize(), initTimeStep(), Discretiser::interpreter(), isStationary(), iterateTimeStep(), Probleme_Couple::iterateTimeStep(), limpr(), lsauv(), postraiter(), presentTime(), Probleme_Couple::printOn(), Probleme_Couple::readOn(), Pbc_MED::readOn(), sauver(), Probleme_Couple::schema_temps(), setStationary(), Probleme_Couple::solveTimeStep(), terminate(), updateGivenFields(), and validateTimeStep().
postraiter()
int Couplage_U::postraiter (int force = 1) override virtual
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Probleme_U.
Definition at line 121 of file Couplage_U.cpp.
{
  int ok=1;
  for(int i=0; i<nb_problemes(); i++)
    ok = ok && probleme(i).postraiter(force);
  return ok;
}
References nb_problemes(), Probleme_U::postraiter(), and probleme().
Referenced by Pbc_MED::readOn().
presentTime()
double Couplage_U::presentTime () const override virtual
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
Returns
double
Signification: present time
Contraintes:
Reimplemented from Probleme_U.
Definition at line 41 of file Couplage_U.cpp.
{
  assert(nb_problemes()>0);
  return probleme(0).presentTime();
}
References nb_problemes(), Probleme_U::presentTime(), and probleme().
printOn()
Sortie & Couplage_U::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Probleme_Couple, and Pbc_MED.
Definition at line 198 of file Couplage_U.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
probleme() [1/4]
Probleme_U & Couplage_U::probleme (const Nom & nom_pb) inline
Access by name.
Definition at line 134 of file Couplage_U.h.
{
  return probleme(indice_probleme(nom_pb));
}
References indice_probleme(), and probleme().
probleme() [2/4]
const Probleme_U & Couplage_U::probleme (const Nom & nom_pb) const inline
Access by name (const)
Definition at line 129 of file Couplage_U.h.
{
  return probleme(indice_probleme(nom_pb));
}
References indice_probleme(), and probleme().
probleme() [3/4]
Probleme_U & Couplage_U::probleme (int i) inline
Access by index.
Definition at line 118 of file Couplage_U.h.
{
  return problems(i);
}
References problems.
probleme() [4/4]
const Probleme_U & Couplage_U::probleme (int i) const inline
Access by index (const)
Definition at line 123 of file Couplage_U.h.
{
  return problems(i);
}
References problems.
Referenced by abortTimeStep(), Probleme_Couple::ajouter(), Probleme_Couple::associer_sch_tps_base(), Probleme_Couple::computeTimeStep(), Probleme_Couple::discretiser(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), findInputField(), findOutputField(), futureTime(), getInputFieldsNames(), getOutputFieldsNames(), indice_probleme(), initialize(), Probleme_Couple::initialize(), initTimeStep(), Discretiser::interpreter(), isStationary(), iterateTimeStep(), Probleme_Couple::iterateTimeStep(), limpr(), lsauv(), postraiter(), presentTime(), Probleme_Couple::printOn(), probleme(), Pbc_MED::readOn(), sauver(), Probleme_Couple::schema_temps(), setStationary(), Probleme_Couple::solveTimeStep(), terminate(), updateGivenFields(), and validateTimeStep().
readOn()
Entree & Couplage_U::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Probleme_Couple, and Pbc_MED.
Definition at line 203 of file Couplage_U.cpp.
{
  return s ;
}
sauver()
void Couplage_U::sauver () const override virtual
Sauvegarder l'etat du probleme sur disque.
Reimplemented from Probleme_U.
Definition at line 145 of file Couplage_U.cpp.
{
  for(int i=0; i<nb_problemes(); i++)
    probleme(i).sauver();
}
References nb_problemes(), probleme(), and Probleme_U::sauver().
self_cast() [1/2]
const Couplage_U & Couplage_U::self_cast (const Objet_U & r) static
Definition at line 20 of file Couplage_U.cpp.
self_cast() [2/2]
Couplage_U & Couplage_U::self_cast (Objet_U & r) static
Definition at line 20 of file Couplage_U.cpp.
setStationary()
void Couplage_U::setStationary (bool) override virtual
Tells to the Problem that stationary is reached or not.
Reimplemented from Probleme_U.
Definition at line 81 of file Couplage_U.cpp.
{
  for(int i=0; i<nb_problemes(); i++)
    probleme(i).setStationary(flag);
}
References nb_problemes(), probleme(), and Probleme_U::setStationary().
taille_memoire()
unsigned Couplage_U::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Probleme_Couple, and Pbc_MED.
Definition at line 20 of file Couplage_U.cpp.
terminate()
void Couplage_U::terminate () override virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Reimplemented from Probleme_U.
Definition at line 35 of file Couplage_U.cpp.
{
  for(int i=0; i< nb_problemes(); i++)
    probleme(i).terminate();
}
References nb_problemes(), probleme(), and Probleme_U::terminate().
updateGivenFields()
bool Couplage_U::updateGivenFields () override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
true=OK, false=error
Signification:
Contraintes:
Reimplemented from Probleme_U.
Reimplemented in Probleme_Couple.
Definition at line 151 of file Couplage_U.cpp.
{
  bool ok=true;
  for(int i=0; i<nb_problemes(); i++)
    ok = ok && probleme(i).updateGivenFields();
  return ok;
}
References nb_problemes(), probleme(), and Probleme_U::updateGivenFields().
validateTimeStep()
void Couplage_U::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
Reimplemented from Probleme_U.
Definition at line 67 of file Couplage_U.cpp.
{
  for(int i=0; i<nb_problemes(); i++)
    probleme(i).validateTimeStep();
}
References nb_problemes(), probleme(), and Probleme_U::validateTimeStep().
Member Data Documentation
info_obj
const Type_info Couplage_U::info_obj static
Definition at line 36 of file Couplage_U.h.
problems
List_Ref_Probleme_U Couplage_U::problems private
Definition at line 102 of file Couplage_U.h.
Referenced by addProblem(), nb_problemes(), and probleme().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Couplage_U.h
src/Kernel/Framework/Couplage_U.cpp