TRUST: Op_Diff_RotRot Class Reference
Op_Diff_RotRot Class Reference
#include <Op_Diff_RotRot.h>
Public Member Functions
Op_Diff_RotRot ()
~Op_Diff_RotRot ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
int tester () const
int calculer_vorticite (DoubleTab &, const DoubleTab &) const
int assembler_matrice (Matrice &)
IntList sommets_pour_element (int numero_elem) const
IntList elements_pour_sommet (int numero_som) const
IntList sommets_voisins (int numero_som, const IntList &liste) const
double remplir_elem_elem_EF (const int numero_elem) const
double remplir_elem_som_EF (const int numero_elem, const int numero_som) const
double remplir_som_elem_EF (const int numero_elem, const int numero_som) const
double remplir_som_som_EF (const int numero_som, const int sommet_voisin, const IntList &) const
void Tri (IntList &liste_a_trier) const
DoubleTab vecteur_normal (const int face, const int elem) const
const Zone_VEF_PreP1b & zone_Vef () const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_RotRot & self_cast (Objet_U &)
static const Op_Diff_RotRot & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Champ_Inc vorticite_
Matrice matrice_vorticite_
Op_Rot_VEFP1B rot_
Op_Curl_VEFP1B curl_
SolveurSys solveur_
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Uniforme diffusivite_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
Definition at line 30 of file Op_Diff_RotRot.h.
Constructor & Destructor Documentation
Op_Diff_RotRot()
Op_Diff_RotRot::Op_Diff_RotRot ()
Definition at line 29 of file Op_Diff_RotRot.cpp.
~Op_Diff_RotRot()
Op_Diff_RotRot::~Op_Diff_RotRot ()
Definition at line 29 of file Op_Diff_RotRot.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_RotRot::ajouter (const DoubleTab & vitesse, DoubleTab & diffusion) const override virtual
Reimplemented from Operateur_base.
Definition at line 101 of file Op_Diff_RotRot.cpp.
{
  Cerr << "je suis dans OpDiffRotRot" << finl;
  DoubleTab curl(matrice_vorticite_.valeur().ordre());
// Marche car Champ_Inc est mutable
  curl_.calculer(vitesse,curl);
// curl=-1*curl;
  calculer_vorticite(vorticite_.valeurs(),curl);
  rot_.calculer(vorticite_.valeurs(),diffusion);
  Cerr << "je sors de OpDiffRotRot" << finl;
  return diffusion;
}
References Op_Curl_VEFP1B::calculer(), Op_Rot_VEFP1B::calculer(), calculer_vorticite(), Cerr, curl_, finl, matrice_vorticite_, Matrice_Base::ordre(), rot_, Deriv_Matrice_Base::valeur(), Champ_Inc::valeurs(), and vorticite_.
Referenced by calculer().
assembler_matrice()
int Op_Diff_RotRot::assembler_matrice (Matrice & matrice)
Definition at line 179 of file Op_Diff_RotRot.cpp.
{
  const Zone& zone = zone_Vef().zone();
  int colonne_a_remplir_tab2,colonne_a_remplir_coeff;
  int nombre_coeff_non_nuls;
  Cerr << "Assemblage de la matrice de vorticite en cours..." << finl;
  matrice.typer("Matrice_Morse_Sym");
// Matrice_Morse& la_matrice=(Matrice_Morse&) matrice.valeur();
// On dimensionne la matrice de maniere convenable.
// La matrice est carree et de taille (nombre_elem+nombre_som)
// Le nombre de coeff non nuls n'excedent pas
// (2* (dimension+1) + 1)* nb_elem + (nb_som-1) * (nb_som-1)
// ATTENTION: une BASE de mon espace est les fonctions indicatrices
// des elements + les fonctions chapeaux - 1 de ces fonctions
// Sinon la somme des toutes les fontions chapeaux - la somme
// de toutes les fonctions indicatrices = 0
// Par defaut, on enleve la derniere fonction chapeau pour
// former notre base.
// Cf. Papier dans Latex/Vorticity
  nombre_coeff_non_nuls = (2*dimension + 3) * zone.nb_elem()
                          + (zone.nb_som()-1)* (zone.nb_som()-1);
// la_matrice.dimensionner(zone.nb_elem()+zone.nb_som()-1,nombre_coeff_non_nuls);
  Matrice_Morse la_matrice(zone.nb_elem()+ zone.nb_som()-1,nombre_coeff_non_nuls);
// Au cas ou la matrice existe deja dans un fichier
  Nom nomfic("Vorticite.sv");
  LecFicDistribueBin vorticite;
  int fic_vorticite_existe;
  if(vorticite.ouvrir(nomfic)) fic_vorticite_existe=1;
  else fic_vorticite_existe=0;
  if(fic_vorticite_existe)
    {
      Cerr << "Relecture de la matrice de vorticite sur le fichier: "
           << nomfic << finl;
      vorticite >> la_matrice;
      vorticite.close();
      Cerr << "Fin de la relecture de la matrice de vorticite." << finl;
      return 1;
    }
  Cerr << "Assemblage de la matrice de vorticite " << nomfic << finl;
// Maintenant on remplit la matrice ligne par ligne
// On rappelle que les elements et les sommets sont numerotes
// a partir de 0.
// Mais les indices de colonnes et de lignes des tableaux
// d'une matrice morse FORTRAN commencent a 1.
// Ex de construction: matrice[numerotation_C++] = numerotation_FORTRAN
// Parametres importants pour remplir les tableaux
  nombre_coeff_non_nuls = 1;
  colonne_a_remplir_tab2 = 0; //pour le C++
  colonne_a_remplir_coeff = 0; //pour le C++
// On commence par remplir les lignes de la sous-matrice
// de taille nb_elem * (nb_elem + nb_som) : cf. structure de la matrice
  for (int numero_elem = 0; numero_elem < zone.nb_elem(); numero_elem++)
    {
// Pour un element donne "numero_elem", on calcule la liste
// des sommets qui appartiennent a cet element.
      IntList sommets_pour_elem = sommets_pour_element(numero_elem);
      Tri(sommets_pour_elem); //tableau trie
// On remplit tab1
      la_matrice.get_set_tab1()(numero_elem) = nombre_coeff_non_nuls;
// On remplit tab2 et coeff
// Les nb_elem premiers elements de la ligne "numero_elem"
// a cause du FORTRAN
      la_matrice.get_set_tab2()(colonne_a_remplir_tab2) = numero_elem + 1;
      la_matrice.get_set_coeff()(colonne_a_remplir_coeff) =
        remplir_elem_elem_EF(numero_elem);
// On incremente nb_coeff_non_nuls car on vient de remplir
// une ligne par l'un de ces elements non nul
      nombre_coeff_non_nuls++;
// On incremente les compteurs puisque l'on vient de remplir
// des cases du tableau
      colonne_a_remplir_tab2++;
      colonne_a_remplir_coeff++;
// Les nb_som elements de la ligne "numero_elem"
      for (int i = 0; i < zone.nb_som_elem(); i++)
        {
// Si ce "sommet_pour_elem[i]" est different du numero
// du dernier sommet alors on stocke le bon coefficient
          if (sommets_pour_elem[i] != zone.nb_som()-1)
            {
              la_matrice.get_set_tab2()(colonne_a_remplir_tab2) =
                zone.nb_elem()+sommets_pour_elem[i]+1; //pour FORTRAN
              la_matrice.get_set_coeff()(colonne_a_remplir_coeff) =
                remplir_elem_som_EF(numero_elem,sommets_pour_elem[i]);
// On incremente nb_coeff_non_nuls car on vient de remplir
// une ligne avec l'un de ces elements non nul
              nombre_coeff_non_nuls++;
// Enfin on incremente les colonne_* pour eviter de reecrire
// sur des coefficients deja stockes
              colonne_a_remplir_tab2++;
              colonne_a_remplir_coeff++;
            }
        }
// Pas besoin de modifier les entiers nombre_coeff_non_nuls et
// colonne_* : ils sont a la bonne valeur.
    }
// On remplit les lignes de la sous-matrice de taille
// nb_som *(nb_elem+nb_som) :cf. structure de la matrice
  for (int numero_som = 0; numero_som < zone.nb_som()-1; numero_som++)
    {
// On stocke les tableaux qui nous sont utiles
// Ainsi que leur taille respective
      IntList Elem_pour_sommet = elements_pour_sommet(numero_som);
      IntList Sommets_voisins = sommets_voisins(numero_som,Elem_pour_sommet);
      Tri(Elem_pour_sommet); //liste triee
      Tri(Sommets_voisins); //liste triee
// On remplit tab1
// pour FORTRAN
      la_matrice.get_set_tab1()(zone.nb_elem()+numero_som) = nombre_coeff_non_nuls;
// On remplit tab2 et coeff
// Les nb_elem premiers elements de la ligne "numero_som"
      for (int i=0; i < Elem_pour_sommet.size(); i++)
        {
// A cause du FORTRAN
          la_matrice.get_set_tab2()(colonne_a_remplir_tab2) = Elem_pour_sommet[i]+1;
          la_matrice.get_set_coeff()(colonne_a_remplir_coeff) =
            remplir_som_elem_EF(Elem_pour_sommet[i],numero_som);
// On incremente nb_coeff_non_nuls car on vient de remplir
// une ligne avec l'un de ces elements non nul
          nombre_coeff_non_nuls++;
// On incremente convenablement les indices de colonnes
          colonne_a_remplir_tab2++;
          colonne_a_remplir_coeff++;
        }
// Pas besoin de modifier les entiers nb_coeff_non_nuls et
// colonne_* : ils sont a la bonne valeur.
// Les nb_som elements de la ligne "numero_som"
      for (int i=0; i < Sommets_voisins.size(); i++)
        {
// On recupere le numero global du sommet_voisin
          int numero_som_global = Sommets_voisins[i];
// Et si "numero_som_global" est different du numero
// du dernier sommet, alors on stocke le bon coefficient
          if (numero_som_global != zone.nb_som()-1)
            {
// A cause du FORTRAN
              la_matrice.get_set_tab2()(colonne_a_remplir_tab2) =
                zone.nb_elem()+Sommets_voisins[i]+1;
              la_matrice.get_set_coeff()(colonne_a_remplir_coeff) =
                remplir_som_som_EF(numero_som,Sommets_voisins[i],Elem_pour_sommet);
// On incremente nb_coeff_non_nuls car on vient de remplir
// une ligne avec l'un de ces elements non nul
              nombre_coeff_non_nuls++;
// On incremente les indices
              colonne_a_remplir_tab2++;
              colonne_a_remplir_coeff++;
            }
        }
// Pas besoin d'incrementer nombre_coeff_non_nuls et colonne_*
// : ils sont deja a la bonne valeur
    }
// Par convention pour les matrices morses, le dernier element
// de tab1 est tab1[zone.nb_elem()+zone.nb_som()+1] et vaut
// le nombre total de coefficients non nuls +1
// soit avec notre algorithme: nombre_coeff_non_nuls
  la_matrice.get_set_tab1()(zone.nb_elem()+zone.nb_som()-1) = nombre_coeff_non_nuls;
// if(Debog::mode_db==2) Debog::save_matrix_seq(la_matrice);
// else if(Debog::mode_db==3)
// Debog::save_and_distribute_matrix_seq(la_matrice);
  Matrice_Morse_Sym& la_matrice_sym = ref_cast(Matrice_Morse_Sym,
                                               matrice.valeur());
  la_matrice_sym = la_matrice;
  Cerr << "Fin de l'assemblage de la matrice de vorticite. " << finl;
  return 1;
}
References Cerr, Entree_Fichier_base::close(), Objet_U::dimension, elements_pour_sommet(), finl, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Zone::nb_elem(), Zone::nb_som(), Zone::nb_som_elem(), LecFicDistribue::ouvrir(), ref_cast, remplir_elem_elem_EF(), remplir_elem_som_EF(), remplir_som_elem_EF(), remplir_som_som_EF(), TRUSTList< _TYPE_ >::size(), sommets_pour_element(), sommets_voisins(), Tri(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), Zone_dis_base::zone(), and zone_Vef().
Referenced by associer().
associer()
void Op_Diff_RotRot::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc & inco) override virtual
Implements Operateur_base.
Definition at line 49 of file Op_Diff_RotRot.cpp.
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF, zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  curl_.associer(zone_dis,zone_Cl_dis,inco);
  rot_.associer(zone_dis,zone_Cl_dis,inco);
//
// On definit le champ vorticite
  vorticite_.typer("Champ_P1_isoP1Bulle");
  Champ_P1_isoP1Bulle& vorticite =
    ref_cast(Champ_P1_isoP1Bulle,vorticite_.valeur());
  vorticite.associer_zone_dis_base(zvef);
  vorticite.nommer("vorticite");
  if (dimension == 2) vorticite.fixer_nb_comp(1);
  else vorticite.fixer_nb_comp(dimension);
  int nb_tot = zvef.nb_elem() + zvef.nb_som() -1;
  vorticite.fixer_nb_valeurs_nodales(nb_tot);
  vorticite.fixer_unite("s-1");
//
  solveur_.typer("Solv_GCP");
  Precond p;
  p.typer("SSOR");
  ref_cast(Solv_GCP,solveur.valeur()).set_precond(p);
  assembler_matrice(matrice_vorticite_);
  tester();
}
References assembler_matrice(), Op_Curl_VEFP1B::associer(), Op_Rot_VEFP1B::associer(), Champ_P1_isoP1Bulle::associer_zone_dis_base(), curl_, Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), la_zcl_vef, la_zone_vef, matrice_vorticite_, Zone_dis_base::nb_elem(), Zone_dis_base::nb_som(), Field_base::nommer(), ref_cast, rot_, Operateur_base::solveur, solveur_, tester(), Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_SolveurSys_base::valeur(), and vorticite_.
associer_diffusivite()
void Op_Diff_RotRot::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
Definition at line 648 of file Op_Diff_RotRot.cpp.
{
  diffusivite_ = ref_cast(Champ_Uniforme, diffu);
}
References diffusivite_, and ref_cast.
calculer()
DoubleTab & Op_Diff_RotRot::calculer (const DoubleTab & vitesse, DoubleTab & diffusion) const override virtual
Reimplemented from Operateur_base.
Definition at line 91 of file Op_Diff_RotRot.cpp.
{
  diffusion = 0;
  return ajouter(vitesse,diffusion);
}
References ajouter().
calculer_vorticite()
int Op_Diff_RotRot::calculer_vorticite (DoubleTab & solution, const DoubleTab & curl) const
Definition at line 119 of file Op_Diff_RotRot.cpp.
{
  const Zone& zone = zone_Vef().zone();
  static int nb_appel2=0;
// Resolution en vorticite: on ne considere que le cas
// sequentiel pour le moment.
// Pour le cas parallele, il faut s'inspirer de la classe N_S.cpp.
  if (Process::nproc()==1)
    {
// On considere que la matrice de vorticite est une matrice
// morse par defaut, et on applique la methode inverse()
// pour resoudre le systeme lineaire.
      const Matrice_Morse_Sym& la_matrice=ref_cast(Matrice_Morse_Sym,
                                                   matrice_vorticite_.valeur());
// Matrice_Morse& la_matrice = (Matrice_Morse&) matrice_vorticite_.valeur();
      DoubleTab solution_temporaire(la_matrice.ordre());
      assert(solution_temporaire.size() == solution.size()-1);
      assert(curl.size() == solution_temporaire.size());
// On resoud un systeme lineaire pour calculer la vorticite
// La vorticite est alors stockee dans la variable solution
// la_matrice.inverse(curl,solution_temporaire,1e-15);
      Solv_GCP& solv = ref_cast_non_const(Solv_GCP,solveur_.valeur());
      solv.set_seuil(1e-17);
      solv.resoudre_systeme(la_matrice,curl,solution_temporaire);
// On recopie les valeurs de solution temoraire dans solution
// Une case n'est pas remplie: on le fait plus tard.
      for (int i=0; i<solution_temporaire.size(); i++)
        solution[i]=solution_temporaire[i];
// On remplit le dernier element de "solution"
      int sommet = zone.nb_som()-1;
      for (int i=0; i<curl_.elem_som_size(sommet); i++)
        solution[sommet] +=
          solution_temporaire[curl_.elements_pour_sommet(sommet,i)];
      nb_appel2++;
    }
  return 1;
}
References curl_, Op_Curl_VEFP1B::elem_som_size(), Op_Curl_VEFP1B::elements_pour_sommet(), matrice_vorticite_, Zone::nb_som(), Process::nproc(), Matrice_Morse::ordre(), ref_cast, ref_cast_non_const, Solv_GCP::resoudre_systeme(), solv_iteratif::set_seuil(), TRUSTVect< _TYPE_ >::size(), solveur_, Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Zone_dis_base::zone(), and zone_Vef().
Referenced by ajouter().
cree_instance()
Objet_U * Op_Diff_RotRot::cree_instance () static
Definition at line 29 of file Op_Diff_RotRot.cpp.
diffusivite()
const Champ_base & Op_Diff_RotRot::diffusivite () const override virtual
Implements Operateur_Diff_base.
Definition at line 653 of file Op_Diff_RotRot.cpp.
{
  return diffusivite_;
}
References diffusivite_.
duplique()
int Op_Diff_RotRot::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Op_Diff_RotRot.cpp.
elements_pour_sommet()
IntList Op_Diff_RotRot::elements_pour_sommet (int numero_som) const
Definition at line 407 of file Op_Diff_RotRot.cpp.
{
  IntList resultat;
  int numero_global_som;
  const Zone& zone = zone_Vef().zone();
// Par precaution mais normalement inutile
  if (! resultat.est_vide() ) resultat.vide();
// Pas tres efficace mais marche quelle que soit la dimension:
// on boucle sur les elements, on regarde pour chaque element
// ses sommets, puis on compare ces sommets au parametre d'entree
// et si l'un d'eux coincide avec le parametre d'entree, on stocke
// l'element.
  for (int numero_elem = 0 ; numero_elem < zone.nb_elem() ; numero_elem++)
    for (int numero_som = 0 ; numero_som < zone.nb_som_elem() ; numero_som++)
      {
        numero_global_som = zone.sommet_elem(numero_elem,numero_som);
        if ( numero_sommet == numero_global_som )
          resultat.add_if_not(numero_elem);
      }
  return resultat;
}
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTListElem< _TYPE_ >::est_vide(), Zone::nb_elem(), Zone::nb_som_elem(), Zone::sommet_elem(), TRUSTList< _TYPE_ >::vide(), Zone_dis_base::zone(), and zone_Vef().
Referenced by assembler_matrice().
get_info()
const Type_info * Op_Diff_RotRot::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 29 of file Op_Diff_RotRot.cpp.
info()
const Type_info * Op_Diff_RotRot::info () static
Definition at line 29 of file Op_Diff_RotRot.cpp.
printOn()
Sortie & Op_Diff_RotRot::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 33 of file Op_Diff_RotRot.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_RotRot::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 39 of file Op_Diff_RotRot.cpp.
{
  return s ;
}
remplir_elem_elem_EF()
double Op_Diff_RotRot::remplir_elem_elem_EF (const int numero_elem) const
Definition at line 500 of file Op_Diff_RotRot.cpp.
{
  return 1.*zone_Vef().volumes(numero_elem);
}
References Zone_VF::volumes(), and zone_Vef().
Referenced by assembler_matrice().
remplir_elem_som_EF()
double Op_Diff_RotRot::remplir_elem_som_EF (const int numero_elem, const int numero_som) const
Definition at line 509 of file Op_Diff_RotRot.cpp.
{
  return (1.*zone_Vef().volumes(numero_elem)/(dimension+1));
}
References Objet_U::dimension, and zone_Vef().
Referenced by assembler_matrice().
remplir_som_elem_EF()
double Op_Diff_RotRot::remplir_som_elem_EF (const int numero_elem, const int numero_som) const
Definition at line 521 of file Op_Diff_RotRot.cpp.
{
  return (1.*zone_Vef().volumes(numero_elem)/(dimension+1));
}
References Objet_U::dimension, and zone_Vef().
Referenced by assembler_matrice().
remplir_som_som_EF()
double Op_Diff_RotRot::remplir_som_som_EF (const int numero_som, const int sommet_voisin, const IntList & elem_voisins) const
Definition at line 533 of file Op_Diff_RotRot.cpp.
{
  double resultat = 0.;
  int test = 0;
// Premier test: si numero_som = sommet_voisin
// Alors on peut tout de suite retourner le resultat
  if (numero_som == sommet_voisin)
    {
      for (int i=0; i<elem_voisins.size(); i++)
        {
          resultat += zone_Vef().volumes(elem_voisins[i]);
        }
// On tient compte de la dimension dans nos calculs
      resultat *= 2./((dimension+1)*(dimension+2));
      return resultat;
    }
// Sinon:
// On calcule la contribution au resultat
  for (int i=0; i<elem_voisins.size() ; i++)
    {
      if (sommets_pour_element(elem_voisins[i]).contient(sommet_voisin))
        {
          resultat += zone_Vef().volumes(elem_voisins[i]);
          test++;
        }
    }
// On tient compte de la dimension dans laquelle on evolue
  resultat *= 1./((dimension+1)*(dimension+2));
// On verifier que sommet_voisin etait bien dans le voisinage de numero_voisin
  if (test == 0)
    {
      Cerr << "Erreur Op_Diff_RotRot::remplir_som_som_EF." << finl;
      Cerr << "sommet_voisin n'est pas dans le voisinage de numero_voisin."
           << finl;
      Cerr << "Sortie du programme." << finl;
      Process::exit();
    }
  return resultat;
}
References Cerr, TRUSTList< _TYPE_ >::contient(), Objet_U::dimension, Process::exit(), finl, TRUSTList< _TYPE_ >::size(), sommets_pour_element(), test(), Zone_VF::volumes(), and zone_Vef().
Referenced by assembler_matrice().
self_cast() [1/2]
const Op_Diff_RotRot & Op_Diff_RotRot::self_cast (const Objet_U & r) static
Definition at line 29 of file Op_Diff_RotRot.cpp.
self_cast() [2/2]
Op_Diff_RotRot & Op_Diff_RotRot::self_cast (Objet_U & r) static
Definition at line 29 of file Op_Diff_RotRot.cpp.
sommets_pour_element()
IntList Op_Diff_RotRot::sommets_pour_element (int numero_elem) const
Definition at line 386 of file Op_Diff_RotRot.cpp.
{
  IntList resultat;
  int numero_global_sommet = 0;
  const Zone& zone = zone_Vef().zone();
// Par precaution mais normalement inutile
  if (! resultat.est_vide() ) resultat.vide();
  for (int i=0 ; i< zone.nb_som_elem() ; i++)
    {
      numero_global_sommet = zone.sommet_elem(numero_elem,i);
      resultat.add_if_not(numero_global_sommet);
    }
  return resultat;
}
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTListElem< _TYPE_ >::est_vide(), Zone::nb_som_elem(), Zone::sommet_elem(), TRUSTList< _TYPE_ >::vide(), Zone_dis_base::zone(), and zone_Vef().
Referenced by assembler_matrice(), and remplir_som_som_EF().
sommets_voisins()
IntList Op_Diff_RotRot::sommets_voisins (int numero_som, const IntList & liste) const
Definition at line 438 of file Op_Diff_RotRot.cpp.
{
  IntList resultat;
  int numero_global_som;
  const Zone& zone = zone_Vef().zone();
// Il suffit de recuperer les sommets des elements de "liste"
// puis de les comparer a "numero_som" et de les conserver
// sans doublon.
  for (int numero_elem_loc = 0 ; numero_elem_loc<liste.size(); numero_elem_loc++)
    for (int numero_som = 0; numero_som < zone.nb_som_elem() ; numero_som++)
      {
        numero_global_som =
          zone.sommet_elem(liste[numero_elem_loc],numero_som);
        resultat.add_if_not(numero_global_som); //contient "numero_sommet"
      }
// Cerr << "Affichage de sommets_voisins pour numero_som " << numero_sommet
// << finl;
// for (int i=0;i<resultat.size();i++)
// Cerr << resultat[i] << finl;
  return resultat;
}
References TRUSTList< _TYPE_ >::add_if_not(), Zone::nb_som_elem(), liste::size(), Zone::sommet_elem(), Zone_dis_base::zone(), and zone_Vef().
Referenced by assembler_matrice().
taille_memoire()
unsigned Op_Diff_RotRot::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Op_Diff_RotRot.cpp.
tester()
int Op_Diff_RotRot::tester () const
Definition at line 601 of file Op_Diff_RotRot.cpp.
{
// const Zone& zone = zone_Vef().zone();
// if (vorticite_.valeur().nb_valeurs_nodales() !=
// zone.nb_elem()+zone.nb_som()-1)
// {
// Cerr << "Probleme dans la definition de la vorticite." << finl;
// Cerr << "Le nombre de composante enregistree n'est pas le bon." << finl;
// Process::exit();
// }
// Test de la matrice de vorticite
  const Matrice_Morse_Sym& la_matrice=ref_cast(Matrice_Morse_Sym,
                                               matrice_vorticite_.valeur());
  Solv_GCP& solv = ref_cast_non_const(Solv_GCP,solveur_.valeur());
  DoubleTab resultat(la_matrice.ordre());
  DoubleTab resultat1(la_matrice.ordre());
  DoubleTab secmem(la_matrice.ordre());
  DoubleTab secmem1(la_matrice.ordre());
  secmem = 0.;
  secmem[0]=-0.25;
  secmem[4]=-0.0833333;
  secmem[5]=-0.0833333;
  secmem1 = 1e-10 + 1e-15;
  SFichier fic("Matrice.test");
  la_matrice.imprimer_formatte(fic);
  resultat = 0.;
  solv.set_seuil(1e-17);
  solv.resoudre_systeme(la_matrice,secmem,resultat);
  Cerr << "Resultat de l'inversion" << finl;
  for (int i=0; i<8; i++)
    Cerr << resultat[i] << " ; ";
  Cerr << finl;
  solv.resoudre_systeme(la_matrice,secmem1,resultat);
  Cerr << "Resultat de l'inversion" << finl;
  for (int i=0; i<8; i++)
    Cerr << resultat[i] << " ; ";
  Cerr << finl;
  return 1;
}
References Cerr, finl, Matrice_Morse_Sym::imprimer_formatte(), matrice_vorticite_, Matrice_Morse::ordre(), ref_cast, ref_cast_non_const, Solv_GCP::resoudre_systeme(), solv_iteratif::set_seuil(), solveur_, Deriv_Matrice_Base::valeur(), and Deriv_SolveurSys_base::valeur().
Referenced by associer().
Tri()
void Op_Diff_RotRot::Tri (IntList & liste_a_trier) const
Definition at line 467 of file Op_Diff_RotRot.cpp.
{
  if (liste_a_trier.est_vide())
    {
      Cerr << "Erreur dans Op_Diff_RotRot::Tri()." << finl;
      Cerr << "La liste a trier est vide: sortie du programme." << finl;
      Process::exit();
    }
  IntList temporaire;
  int minimum;
  while ( !liste_a_trier.est_vide() )
    {
      minimum = liste_a_trier[0];
      for (int i = 0; i < liste_a_trier.size(); i++)
        minimum = (minimum <= liste_a_trier[i] ? minimum : liste_a_trier[i]);
      temporaire.add_if_not(minimum);
      liste_a_trier.suppr(minimum);
    }
  for (int i = 0 ; i < temporaire.size() ; i++)
    liste_a_trier.add_if_not(temporaire[i]);
}
References TRUSTList< _TYPE_ >::add_if_not(), Cerr, TRUSTListElem< _TYPE_ >::est_vide(), Process::exit(), finl, minimum(), TRUSTList< _TYPE_ >::size(), and TRUSTList< _TYPE_ >::suppr().
Referenced by assembler_matrice().
vecteur_normal()
DoubleTab Op_Diff_RotRot::vecteur_normal (const int face, const int elem) const
Definition at line 586 of file Op_Diff_RotRot.cpp.
{
  assert(dimension == 2);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  DoubleTab le_vecteur_normal(dimension);
  for (int composante = 0; composante<dimension; composante++)
    le_vecteur_normal(composante) = zone_VEF.face_normales(face,composante)
                                    * zone_VEF.oriente_normale(face,elem);
  return le_vecteur_normal;
}
References composante(), Objet_U::dimension, Zone_VEF::face_normales(), la_zone_vef, Zone_VEF::oriente_normale(), and Ref_Zone_VEF::valeur().
zone_Vef()
const Zone_VEF_PreP1b & Op_Diff_RotRot::zone_Vef () const
Definition at line 44 of file Op_Diff_RotRot.cpp.
{
  return ref_cast(Zone_VEF_PreP1b, la_zone_vef.valeur());
}
References la_zone_vef, ref_cast, and Ref_Zone_VEF::valeur().
Referenced by assembler_matrice(), calculer_vorticite(), elements_pour_sommet(), remplir_elem_elem_EF(), remplir_elem_som_EF(), remplir_som_elem_EF(), remplir_som_som_EF(), sommets_pour_element(), and sommets_voisins().
Member Data Documentation
curl_
Op_Curl_VEFP1B Op_Diff_RotRot::curl_ protected
Definition at line 114 of file Op_Diff_RotRot.h.
Referenced by ajouter(), associer(), and calculer_vorticite().
diffusivite_
Ref_Champ_Uniforme Op_Diff_RotRot::diffusivite_ protected
Definition at line 121 of file Op_Diff_RotRot.h.
Referenced by associer_diffusivite(), and diffusivite().
info_obj
const Type_info Op_Diff_RotRot::info_obj static
Definition at line 33 of file Op_Diff_RotRot.h.
la_zcl_vef
Ref_Zone_Cl_VEF Op_Diff_RotRot::la_zcl_vef protected
Definition at line 120 of file Op_Diff_RotRot.h.
Referenced by associer().
la_zone_vef
Ref_Zone_VEF Op_Diff_RotRot::la_zone_vef protected
Definition at line 119 of file Op_Diff_RotRot.h.
Referenced by associer(), vecteur_normal(), and zone_Vef().
matrice_vorticite_
Matrice Op_Diff_RotRot::matrice_vorticite_ protected
Definition at line 111 of file Op_Diff_RotRot.h.
Referenced by ajouter(), associer(), calculer_vorticite(), and tester().
rot_
Op_Rot_VEFP1B Op_Diff_RotRot::rot_ protected
Definition at line 113 of file Op_Diff_RotRot.h.
Referenced by ajouter(), and associer().
solveur_
SolveurSys Op_Diff_RotRot::solveur_ protected
Definition at line 116 of file Op_Diff_RotRot.h.
Referenced by associer(), calculer_vorticite(), and tester().
vorticite_
Champ_Inc Op_Diff_RotRot::vorticite_ mutable protected
Definition at line 110 of file Op_Diff_RotRot.h.
Referenced by ajouter(), and associer().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Diff_RotRot.h
src/P1NCP1B/Operateurs/Op_Diff_RotRot.cpp