TRUST: Perte_Charge_Directionnelle_VEF_P1NC Class Reference
Perte_Charge_Directionnelle_VEF_P1NC Class Reference
#include <Perte_Charge_Directionnelle_VEF_P1NC.h>
Public Member Functions
Perte_Charge_Directionnelle_VEF_P1NC ()
~Perte_Charge_Directionnelle_VEF_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Directionnelle_VEF_P1NC & self_cast (Objet_U &)
static const
Perte_Charge_Directionnelle_VEF_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const
Protected Attributes
Champ_Don v
Vecteur directeur de la perte de charge.
Private Attributes
Parser_U lambda
Parser cree et detruit par l'objet.
Detailed Description
du/dt = - volume * lambda(Re,x,y,z,t) * u.(v / ||v||) * (v / ||v||) * ||u|| / (2 * Dh)
Lecture des arguments :
Perte_Charge_Directionnelle_VEF_P1NC diametre_hydraulique { lambda expression(Re,x,y,z,t) diam_hydr champ_don direction champ_don [sous_zone nom] }
! Perte de charge directionnelle (selon un vecteur unitaire v)
Definition at line 45 of file Perte_Charge_Directionnelle_VEF_P1NC.h.
Constructor & Destructor Documentation
Perte_Charge_Directionnelle_VEF_P1NC::Perte_Charge_Directionnelle_VEF_P1NC ()
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
Perte_Charge_Directionnelle_VEF_P1NC::~Perte_Charge_Directionnelle_VEF_P1NC ()
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
Member Function Documentation
void Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const [protected, virtual]
Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds Retourne le resultat calcule dans p_charge.
Avantage : bonne factorisation. Inconvenient : cout de l'appel d'une methode virtuelle a l'interieur d'une boucle.
Parameters:
u La vitesse a la face courante. 2 ou 3 composantes
pos toto
t titi
norme_u La norme de la vitesse a la face courante
dh Le diametre hydraulique a la face courante (tire de diam_hydr)
nu la viscosite cinematique
reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
coeff_ortho coefficient dans la direction orthogonale
coeff_long coefficient dans la direction longitudinale
u_l vitesse dans la direction longitudinale
v_valeur direction_longitudinale p_charge a 2 ou 3 composantes La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur) ! Appele pour chaque face par ajouter()
Implements Perte_Charge_VEF.
Definition at line 145 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
References Objet_U::dimension, Parser_U::eval(), lambda, Parser_U::setVar(), v, Deriv_Champ_Don_base::valeur(), and Champ_base::valeur_a().
{
// Calcul de lambda
  lambda.setVar(0,reynolds);
  lambda.setVar(1,t);
  lambda.setVar(2,pos[0]);
  if (dimension>1)
    lambda.setVar(3,pos[1]);
  if (dimension>2)
    lambda.setVar(4,pos[2]);
// Calcul de v et ||v||^2
// DoubleVect v_valeur(dimension);
  double vcarre=0;
  v.valeur().valeur_a(pos,v_valeur);
  for (int dim=0; dim<dimension; dim++)
    vcarre+=v_valeur[dim]*v_valeur[dim];
  v_valeur/=sqrt(vcarre);
// Calcul de u.v
  double scal=0;
  for (int dim=0; dim<dimension; dim++)
    scal+=u[dim]*v_valeur[dim];
  /*
  // Calcul du resultat
  for (int dim=0;dim<dimension;dim++)
  p_charge[dim] = -lambda.eval()*scal*v_valeur[dim]*norme_u/2./dh;
  */
  u_l=scal;
  coeff_long=lambda.eval()*norme_u/2./dh;
  coeff_ortho=0;
}
Objet_U * Perte_Charge_Directionnelle_VEF_P1NC::cree_instance () [static]
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
int Perte_Charge_Directionnelle_VEF_P1NC::duplique () const [virtual]
Implements Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
const Type_info * Perte_Charge_Directionnelle_VEF_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
const Type_info * Perte_Charge_Directionnelle_VEF_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
void Perte_Charge_Directionnelle_VEF_P1NC::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 51 of file Perte_Charge_Directionnelle_VEF_P1NC.h.
References Perte_Charge_VEF::diam_hydr, Champ_Don::mettre_a_jour(), and v.
  {
    diam_hydr->mettre_a_jour(temps);
    v.mettre_a_jour(temps);
  }
Sortie & Perte_Charge_Directionnelle_VEF_P1NC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 33 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
References finl, and Objet_U::que_suis_je().
{
  return s << que_suis_je() << finl;
}
Entree & Perte_Charge_Directionnelle_VEF_P1NC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
< lambda
< diam_hydr
< sous_zone
< direction
< non compris
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 44 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
References Parser_U::addVar(), Cerr, Perte_Charge_VEF::diam_hydr, Objet_U::dimension, Process::exit(), finl, Perte_Charge_VEF::implicite_, lambda, Champ_Don::nb_comp(), Perte_Charge_VEF::nom_sous_zone, Parser_U::parseString(), Objet_U::que_suis_je(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Perte_Charge_VEF::sous_zone, and v.
{
  Cerr << "Perte_Charge_Directionnelle_VEF_P1NC::readOn " << finl;
  sous_zone=false;
  int lambda_ok=0;
// Definition des mots-cles
  Motcles les_mots(5);
  les_mots[0] = "lambda";
  les_mots[1] = "diam_hydr";
  les_mots[2] = "sous_zone";
  les_mots[3] = "direction";
  les_mots[4] = "implicite";
// Lecture et interpretation
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  s >> motlu;
  while (motlu != accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'un " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  s >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :   //!< lambda
          {
            lambda_ok=1;
            Nom tmp;
            s >> tmp;
            Cerr << "Lecture et interpretation de la fonction " << tmp << " ... ";
            lambda.setNbVar(2+dimension);
            lambda.setString(tmp);
            lambda.addVar("Re");
            lambda.addVar("t");
            lambda.addVar("x");
            if (dimension>1)
              lambda.addVar("y");
            if (dimension>2)
              lambda.addVar("z");
            lambda.parseString();
            Cerr << " Ok" << finl;
            break;
          }
        case 1: //!< diam_hydr
          s >> diam_hydr;
          break;
        case 2: //!< sous_zone
          s >> nom_sous_zone;
          sous_zone=true;
          break;
        case 3: //!< direction
          s >> v;
          break;
        case 4:
          {
            s>>implicite_;
            break;
          }
        default : //!< non compris
          Cerr << "Mot cle \"" << motlu << "\" non compris lors de la lecture d'un "
               << que_suis_je() << finl;
          exit();
        }
      s >> motlu;
    }
// Verification de la coherence
  if (lambda_ok==0)
    {
      Cerr << "Il faut definir l'expression lamba(Re)" << finl;
      exit();
    }
  if (diam_hydr->nb_comp()!=1)
    {
      Cerr << "Il faut definir le champ diam_hydr a une composante" << finl;
      exit();
    }
  if (v->nb_comp()!=dimension)
    {
      Cerr << "Il faut definir le champ direction a " << dimension << " composantes" << finl;
      exit();
    }
  Cerr << "Fin de Perte_Charge_Directionnelle_VEF_P1NC::readOn" << finl;
  return s;
}
Perte_Charge_Directionnelle_VEF_P1NC & Perte_Charge_Directionnelle_VEF_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
const Perte_Charge_Directionnelle_VEF_P1NC & Perte_Charge_Directionnelle_VEF_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
unsigned Perte_Charge_Directionnelle_VEF_P1NC::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 27 of file Perte_Charge_Directionnelle_VEF_P1NC.cpp.
Member Data Documentation
const Type_info Perte_Charge_Directionnelle_VEF_P1NC::info_obj [static]
Reimplemented from Perte_Charge_VEF.
Reimplemented in Perte_Charge_Directionnelle_QC_VEF_P1NC.
Definition at line 47 of file Perte_Charge_Directionnelle_VEF_P1NC.h.
Parser_U Perte_Charge_Directionnelle_VEF_P1NC::lambda [mutable, private]
Parser cree et detruit par l'objet.
Definition at line 67 of file Perte_Charge_Directionnelle_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), and readOn().
Champ_Don Perte_Charge_Directionnelle_VEF_P1NC::v [protected]
Vecteur directeur de la perte de charge.
Definition at line 64 of file Perte_Charge_Directionnelle_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Sources/Perte_Charge_Directionnelle_VEF_P1NC.h
src/VEF/Sources/Perte_Charge_Directionnelle_VEF_P1NC.cpp