TRUST: Source_Generique_VEF Class Reference
Source_Generique_VEF Class Reference
class Source_Generique_VEF<br>.SECTION voir Source_Generique_base
#include <Source_Generique_VEF.h>
Public Member Functions
Source_Generique_VEF ()
~Source_Generique_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Nom localisation_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Generique_VEF & self_cast (Objet_U &)
static const Source_Generique_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zcl_VEF
Detailed Description
class Source_Generique_VEF<br>.SECTION voir Source_Generique_base
Definition at line 34 of file Source_Generique_VEF.h.
Constructor & Destructor Documentation
Source_Generique_VEF::Source_Generique_VEF ()
Definition at line 30 of file Source_Generique_VEF.cpp.
Source_Generique_VEF::~Source_Generique_VEF ()
Definition at line 30 of file Source_Generique_VEF.cpp.
Member Function Documentation
DoubleTab & Source_Generique_VEF::ajouter (DoubleTab & resu) const [virtual]
Implements Source_Generique_base.
Definition at line 44 of file Source_Generique_VEF.cpp.
References Source_Generique_base::ch_source_, Cond_lim::frontiere_dis(), la_zcl_VEF, la_zone_VEF, DoubleVect::line_size(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Champ_Proto::valeurs().
{
  Champ espace_stockage;
  const Champ_base& champ_calc = ch_source_->get_champ(espace_stockage);
  const DoubleTab& valeurs_calc = champ_calc.valeurs();
  int nb_faces = la_zone_VEF->nb_faces();
  const DoubleVect& vol_entrelaces = la_zone_VEF->volumes_entrelaces();
  const DoubleVect& vol_entrelaces_Cl = la_zcl_VEF->volumes_entrelaces_Cl();
  const DoubleVect& poro_face = la_zone_VEF->porosite_face();
  int nb_front_cl = la_zone_VEF->nb_front_Cl();
  int premiere_face_interne = la_zone_VEF->premiere_face_int();
  int num_face;
  int nb_comp = resu.line_size();
  for (int num_cl =0; num_cl<nb_front_cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl_VEF->les_conditions_limites(num_cl);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if ((sub_type(Dirichlet,la_cl.valeur()))
          ||
          (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
        ;
      else
        for (num_face=ndeb; num_face<nfin; num_face++)
          {
            for (int nc=0; nc<nb_comp; nc++)
              resu(num_face,nc) += valeurs_calc(num_face,nc)*vol_entrelaces_Cl(num_face)*poro_face(num_face);
          }
    }
  for (num_face=premiere_face_interne; num_face<nb_faces; num_face++)
    for (int nc=0; nc<nb_comp; nc++)
      resu(num_face,nc) += valeurs_calc(num_face,nc)*vol_entrelaces(num_face)*poro_face(num_face);
  return resu;
}
void Source_Generique_VEF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl_dis) [virtual]
Implements Source_Generique_base.
Definition at line 86 of file Source_Generique_VEF.cpp.
References la_zcl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_VEF = ref_cast(Zone_VEF,zone_dis.valeur());
  la_zcl_VEF = ref_cast(Zone_Cl_VEF,zcl_dis.valeur());
}
Objet_U * Source_Generique_VEF::cree_instance () [static]
Definition at line 30 of file Source_Generique_VEF.cpp.
int Source_Generique_VEF::duplique () const [virtual]
Implements Source_Generique_base.
Definition at line 30 of file Source_Generique_VEF.cpp.
const Type_info * Source_Generique_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VEF.cpp.
const Type_info * Source_Generique_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VEF.cpp.
Nom Source_Generique_VEF::localisation_source () [virtual]
Implements Source_Generique_base.
Definition at line 93 of file Source_Generique_VEF.cpp.
{
  return "faces";
}
Sortie & Source_Generique_VEF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 33 of file Source_Generique_VEF.cpp.
References Objet_U::que_suis_je().
{
  return os << que_suis_je() ;
}
Entree & Source_Generique_VEF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 38 of file Source_Generique_VEF.cpp.
{
  Source_Generique_base::readOn(is);
  return is;
}
Source_Generique_VEF & Source_Generique_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VEF.cpp.
const Source_Generique_VEF & Source_Generique_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VEF.cpp.
unsigned Source_Generique_VEF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Source_Generique_VEF.cpp.
Member Data Documentation
const Type_info Source_Generique_VEF::info_obj [static]
Reimplemented from Source_Generique_base.
Definition at line 37 of file Source_Generique_VEF.h.
Ref_Zone_Cl_VEF Source_Generique_VEF::la_zcl_VEF [protected]
Definition at line 48 of file Source_Generique_VEF.h.
Referenced by ajouter(), and associer_zones().
Ref_Zone_VEF Source_Generique_VEF::la_zone_VEF [protected]
Definition at line 47 of file Source_Generique_VEF.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/VEF/Sources/Source_Generique_VEF.h
src/VEF/Sources/Source_Generique_VEF.cpp