TRUST: Type_info Class Reference
Type_info Class Reference
modelise une information de type pour les Objet_U
#include <Type_info.h>
Public Member Functions
~Type_info ()
Type_info (const char *name, Objet_U *(*f)(), int nb_bases=0, const Type_info **bases=0)
Constructeur par un nom, une fonction et un tableau de meres.
La fonction permet de creer une instance du bon type.
Type_info (const char *name, int nb_bases=0, const Type_info **bases=0)
Constructeur par un nom, un tableau de meres.
const Nom & name () const
int can_cast (const Type_info *p) const
Exploration de la hierarchie des types
retourne 1 si p pointe sur un sous type du type considere.
int same (const Type_info *p) const
Renvoie 1 si this==p, 0 sinon.
int same (const Nom &) const
Comparaison sur le nom d'un type
Retourne 1 si les chaines de caracteres des noms du type considere et du nom indique sont identiques
Retour 0 sinon.
int has_base (const Type_info *p, int direct=0) const
Test d'appartenance d'un type dans les types de bases du type considere
si direct == 0
renvoie 1 si (*p) fait partie des bases de (*this)
renvoie 0 sinon.
si direct != 0
renvoie 1 si (*p) fait partie des bases de (*this)
ou des meres directes ou non de (*this)
renvoie 0 sinon.
int has_base (const Nom &, int direct=0) const
Test d'appartenance d'un type dans les types de bases du type considere
Le type a rechercher est identifie par son nom
si direct == 0
renvoie 1 si le type de nom name fait partie des bases de (*this)
renvoie 0 sinon.
si direct != 0
renvoie 1 si le type de nom name fait partie des bases de (*this)
ou des meres directes ou non de (*this)
renvoie 0 sinon.
Sortie & bases (Sortie &) const
Ecriture des bases du type considere sur un flot de sortie.
Objet_U * instance () const
Cree une instance de la classe associee au type_info.
int instanciable () const
Renvoie 1 si le type associe est instanciable (cree_instance non nul)
renvoie 0 sinon.
Static Public Member Functions
static Sortie & hierarchie (Sortie &)
Ecriture de toute la hierarchie du type considere sur un flix de sortie.
static int est_un_type (const char *)
Test d'existence d'une classe du type indique
si il existe une classe T dont le Type_info a
le nom nom, alors est_un_type renvoie 1
renvoie le pointeur nul sinon.
static int les_sous_types (const Nom &, Noms &sous_types)
Donne les noms des sous-types, un type mere etant donne par son nom.
static int les_sous_types (const Type_info &, Noms &sous_types)
Donne les noms des sous-types, un type mere etant donne.
static const Type_info * type_info_from_name (const char *type_name)
Methode statique qui renvoie un pointeur vers le Type_info
dont le nom est "type_name". Si type_name n'est pas un type,
renvoie un pointeur nul.
static Objet_U * instance (const char *typ)
Instanciation d'un Objet_U du type indique
S'il existe une classe T dont le Type_info a
le nom typ, alors instance renvoie un pointeur
sur une nouvelle instance de T.
renvoie le pointeur nul sinon.
Private Member Functions
Type_info (Type_info &)
Type_info & operator= (Type_info &)
Constructeur par copie invalide.
void ajouter_type (const Type_info &type_info)
Methode statique appelee par les constructeurs de Type_info pour
ajouter un nouveau type a la liste des types enregistres.
Verifie que le nom du type n'existe pas encore.
Static Private Member Functions
static int search_type_info_name (const char *nom, int &index)
Recherche le type de nom "nom" dans la liste de types enregistres
par une recherche binaire.
On compare les chaines converties en majuscules.
On range dans "index" l'indice du type, s'il a ete trouve
et sinon l'indice du type juste apres (dans ce cas, on a
les_types[index-1]->n < nom < les_types[index]->n)
Si le type a ete trouve on renvoie 1, sinon 0.
Private Attributes
const char * names_
Nom * name_
(eg: A)
Nom * synonym_name_
(eg: B) Object synonym:
Synonyme_info * synonym_
Synonym.
int nb_bases_
const Type_info ** b
Objet_U *(* cree_instance)()
Static Private Attributes
static const Type_info ** les_types =0
static int * types_homonymes =0
static int nb_classes =0
static int les_types_memsize =0
Detailed Description
modelise une information de type pour les Objet_U
Definition at line 32 of file Type_info.h.
Constructor & Destructor Documentation
~Type_info()
Type_info::~Type_info ()
Definition at line 67 of file Type_info.cpp.
{
// On cherche ou retirer le type dans le tableau :
  int index;
  int existe_deja = search_type_info_name(name(), index);
  if (existe_deja)
    {
      for (int i = index; i<nb_classes-1; i++)
        {
          les_types[i] = les_types[i+1];
          types_homonymes[i] = types_homonymes[i+1];
        }
      nb_classes--;
    }
  if (name_)
    {
      delete name_;
      name_=0;
      delete synonym_;
      synonym_=0;
      delete synonym_name_;
      synonym_name_=0;
    }
  if ((nb_classes==0)&& (les_types_memsize!=0))
    {
      delete [] les_types;
      delete [] types_homonymes;
      les_types_memsize=0;
    }
}
References les_types, les_types_memsize, name(), name_, nb_classes, search_type_info_name(), synonym_, synonym_name_, and types_homonymes.
Type_info() [1/3]
Type_info::Type_info (const char * name, Objet_U *(*)() f, int nb_bases = 0, const Type_info ** bases = 0)
Constructeur par un nom, une fonction et un tableau de meres.
La fonction permet de creer une instance du bon type.
Definition at line 212 of file Type_info.cpp.
                                                  :
  names_(un_nom),
  name_((Nom*) 0),
  synonym_name_((Nom*) 0),
  nb_bases_(nb_base),
  b(the_bases),
  cree_instance(f)
{
  if(un_nom == 0)
    {
      Cerr << "Type_info::Type_info(const char* nom,Objet_U* (*f)()...)\n";
      Cerr << " Error : name == 0" << finl;
      assert(0);
      Process::exit();
    }
  ajouter_type(*this);
}
References ajouter_type(), Cerr, Process::exit(), and finl.
Type_info() [2/3]
Type_info::Type_info (const char * name, int nb_bases = 0, const Type_info ** bases = 0)
Constructeur par un nom, un tableau de meres.
Definition at line 163 of file Type_info.cpp.
                                                                                 :
  names_(un_nom),
  name_((Nom*)0),
  synonym_name_((Nom*) 0),
  nb_bases_(nb_base),
  b(the_bases),
  cree_instance(0)
{
  if(un_nom == 0)
    {
      Cerr << "Type_info::Type_info(const char* nom,Objet_U* (*f)()...)\n";
      Cerr << " Error : name == 0" << finl;
      assert(0);
      Process::exit();
    }
  ajouter_type(*this);
}
References ajouter_type(), Cerr, Process::exit(), and finl.
Type_info() [3/3]
Type_info::Type_info (Type_info &) inline private
Definition at line 64 of file Type_info.h.
{}; //!< Constructeur par copie invalide
Member Function Documentation
ajouter_type()
void Type_info::ajouter_type (const Type_info & type_info) private
Methode statique appelee par les constructeurs de Type_info pour
ajouter un nouveau type a la liste des types enregistres.
Verifie que le nom du type n'existe pas encore.
< Start loop
< End loop
Definition at line 237 of file Type_info.cpp.
{
// Split type_info.names_ into A if | is found (eg: n=A|B)
// and add a synonym B
  Nom A("");
  Nom B("");
  int synonym_found=0;
  int i = 0;
  unsigned char c;
  do //!< Start loop
    {
      c = type_info.names_[i];
// Find a |
      if (c==124)
        {
          if (synonym_found==1)
            {
              Cerr << "More than 1 synonym found in " << type_info.names_ << finl;
              Cerr << "Not supported yet !" << finl;
              Process::exit();
            }
          else
            {
              synonym_found=1;
              i++;
              c = type_info.names_[i];
              if (c==0)
                {
                  Cerr << "Error in a classname which can't finished by | : " << type_info.names_ << finl;
                  Process::exit();
                }
            }
        }
// Build the synonym name:
      if (synonym_found)
        B+=c;
      else
        A+=c;
      i++;
    }
  while (c!=0); //!< End loop
  name_ = new Nom(A);
  if (synonym_found)
    {
// Commented cause too verbose:
// Cerr << "Keyword " << A << " has a synonym: " << B << finl;
      synonym_name_ = new Nom(B);
      synonym_ = new Synonyme_info(synonym_name_->getChar(),name_->getChar());
    }
// Verifie qu'il y a assez de place dans le tableau :
  if (les_types_memsize <= nb_classes + 1)
    {
      static const int INCREMENT = 512;
// Plus assez de place dans le tableau: on redimensionne.
      les_types_memsize += INCREMENT;
      const Type_info** nouveau = new const Type_info*[les_types_memsize];
      for (int j = 0; j < nb_classes; j++)
        nouveau[j] = les_types[j];
      delete[] les_types;
      les_types = nouveau;
      int * temp = new int[les_types_memsize];
      for (int j = 0; j < nb_classes; j++)
        temp[j] = types_homonymes[j];
      delete[] types_homonymes;
      types_homonymes = temp;
    }
// On cherche ou mettre le type dans le tableau :
  int existe_deja=Synonyme_info::est_un_synonyme(type_info.name());
  if (existe_deja)
    {
      Cerr<<" class "<<type_info.name()<<" already exists as a synonym which is forbidden!!!!"<<finl;
      Process::exit();
    }
  int index;
  existe_deja = search_type_info_name(type_info.name(), index);
  if (existe_deja)
    {
      types_homonymes[index] = 1;
// GF: si on a un homonyme que la macro string_macro_trio fonctionne
// on a un pb sauf pour les iterateurs
      if (strcmp(string_macro_trio("VECT",titi),"VECT"))
        {
          if (strncmp(type_info.name(),"Iterateur_",10))
            {
              Cerr<<" type "<<type_info.name()<<" is in double and it is not allowed!!!!"<<finl;
              Process::exit();
            }
        }
    }
  else
    {
// Ajout du type dans le tableau a l'indice "index":
      for (int j = nb_classes; j > index; j--)
        {
          les_types[j] = les_types[j-1];
          types_homonymes[j] = types_homonymes[j-1];
        }
      les_types[index] = &type_info;
      types_homonymes[index] = 0;
      nb_classes++;
    }
}
References Cerr, Synonyme_info::est_un_synonyme(), Process::exit(), finl, Nom::getChar(), les_types, les_types_memsize, name(), name_, names_, nb_classes, search_type_info_name(), string_macro_trio, synonym_, synonym_name_, and types_homonymes.
Referenced by Type_info().
bases()
Sortie & Type_info::bases (Sortie & os) const
Ecriture des bases du type considere sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Definition at line 357 of file Type_info.cpp.
{
  int i= nb_bases_;
  while(i--)
    os << b[i]->name() << " ";
  return os << finl;
}
References b, finl, name(), and nb_bases_.
Referenced by hierarchie().
can_cast()
int Type_info::can_cast (const Type_info * p) const inline
Exploration de la hierarchie des types
retourne 1 si p pointe sur un sous type du type considere.
Returns
int
Signification: 1 si p pointe sur un sous type du type considere, 0 sinon
Contraintes:
Definition at line 113 of file Type_info.h.
{
  return ( (same(p)) || (p->has_base(this)) );
}
References has_base(), and same().
Referenced by O_U_Ptr::check_O_U_Ptr_type().
est_un_type()
int Type_info::est_un_type (const char * nom) static
Test d'existence d'une classe du type indique
si il existe une classe T dont le Type_info a
le nom nom, alors est_un_type renvoie 1
renvoie le pointeur nul sinon.
Returns
int
Signification: code de retour (0 ou 1)
Contraintes:
Definition at line 457 of file Type_info.cpp.
{
  const Type_info * type = type_info_from_name(nom);
  return (type != 0);
}
References type_info_from_name().
Referenced by Synonyme_info::ajouter_synonyme(), and les_sous_types().
has_base() [1/2]
int Type_info::has_base (const Nom & aname, int direct = 0) const
Test d'appartenance d'un type dans les types de bases du type considere
Le type a rechercher est identifie par son nom
si direct == 0
renvoie 1 si le type de nom name fait partie des bases de (*this)
renvoie 0 sinon.
si direct != 0
renvoie 1 si le type de nom name fait partie des bases de (*this)
ou des meres directes ou non de (*this)
renvoie 0 sinon.
Returns
int
Signification: code de retour (0 ou 1)
Contraintes:
Definition at line 550 of file Type_info.cpp.
{
// recherche de aname dans b
// si trouve return 1
// sinon si pas direct return 0;
// sinon recherche dans les bases de b
// Modif B. Mathieu: comparaison des adresses du Type_info uniquement,
// pas du nom du type.
  const Type_info * type = type_info_from_name(aname);
  int resultat = has_base(type, direct);
  return resultat;
}
References has_base(), and type_info_from_name().
has_base() [2/2]
int Type_info::has_base (const Type_info * p, int direct = 0) const
Test d'appartenance d'un type dans les types de bases du type considere
si direct == 0
renvoie 1 si (*p) fait partie des bases de (*this)
renvoie 0 sinon.
si direct != 0
renvoie 1 si (*p) fait partie des bases de (*this)
ou des meres directes ou non de (*this)
renvoie 0 sinon.
Returns
int
Signification: code de retour (0 ou 1)
Contraintes:
Definition at line 489 of file Type_info.cpp.
{
// recherche de p->name() dans b
// si trouve return 1
// sinon si pas direct return 0;
// sinon recherche dans les bases de b
// Modif de B. Mathieu: test uniquement sur l'adresse du type_info,
// pas sur le nom du type...
  if (p == 0)
    {
      return 0;
    }
  else
    {
      if (p == this)
        {
          return 1;
        }
      else
        {
          for (int i = 0; i < nb_bases_; i++)
            if (b[i] == p)
              return 1;
          if (!direct)
            {
// Verifier les ancetres de niveau superieur
              for (int i = 0; i < nb_bases_; i++)
                if (b[i]->has_base(p, direct)) return 1;
            }
        }
    }
  return 0;
}
References b, has_base(), and nb_bases_.
Referenced by can_cast(), has_base(), les_sous_types(), Deriv_::typer(), and Discretisation_base::verifie_sous_type().
hierarchie()
Sortie & Type_info::hierarchie (Sortie & os) static
Ecriture de toute la hierarchie du type considere sur un flix de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Definition at line 379 of file Type_info.cpp.
{
  os << "There is " << nb_classes << " classes:" << finl;
  int i= nb_classes;
  while(i--)
    {
      os << les_types[i]->name() << " inherits from ";
      les_types[i]->bases(os);
    }
  return os << flush;
}
References bases(), finl, les_types, name(), and nb_classes.
Referenced by Process::exit().
instance() [1/2]
Objet_U * Type_info::instance () const
Cree une instance de la classe associee au type_info.
Definition at line 427 of file Type_info.cpp.
{
  if (cree_instance == 0)
    {
      Cerr << "Error in Type_info::instance()\n";
      Cerr << " The type " << name() << " is not instantiable" << finl;
      assert(0);
      Process::exit();
    }
  Objet_U * ainstance = (*cree_instance)();
  return ainstance;
}
References Cerr, cree_instance, Process::exit(), finl, and name().
Referenced by instance(), and Deriv_::typer().
instance() [2/2]
Objet_U * Type_info::instance (const char * typ) static
Instanciation d'un Objet_U du type indique
S'il existe une classe T dont le Type_info a
le nom typ, alors instance renvoie un pointeur
sur une nouvelle instance de T.
renvoie le pointeur nul sinon.
Returns
Objet_U*
Signification: pointeur sur un nouvel Objet_U du type typ
Contraintes:
Definition at line 410 of file Type_info.cpp.
{
  const Type_info * le_type = type_info_from_name(typ);
  Objet_U * instance;
  if (le_type)
    instance = le_type->instance();
  else
    instance = 0;
  return instance;
}
References instance(), and type_info_from_name().
instanciable()
int Type_info::instanciable () const
Renvoie 1 si le type associe est instanciable (cree_instance non nul)
renvoie 0 sinon.
Definition at line 702 of file Type_info.cpp.
{
  return (cree_instance != 0);
}
References cree_instance.
Referenced by Deriv_::typer().
les_sous_types() [1/2]
int Type_info::les_sous_types (const Nom & type, Noms & sous_types) static
Donne les noms des sous-types, un type mere etant donne par son nom.
Returns
int
Signification: nombre de sous-types retournes
Contraintes:
Definition at line 650 of file Type_info.cpp.
{
  if (!est_un_type(type))
    {
      Cerr << type << "is not a type recognized by TRUST Unitaire " << finl;
      Process::exit();
    }
  int i= nb_classes;
  while(i--)
    {
      const Type_info& mere = *les_types[i];
      if( les_types[i]->same(type) )
        {
          return les_sous_types(mere, sous_types);
        }
    }
  return 0;
}
References Cerr, est_un_type(), Process::exit(), finl, les_sous_types(), les_types, nb_classes, and same().
Referenced by les_sous_types(), and Pb_Multiphase::lire_equations().
les_sous_types() [2/2]
int Type_info::les_sous_types (const Type_info & mere, Noms & les_sous_types) static
Donne les noms des sous-types, un type mere etant donne.
Returns
int
Signification: nombre de sous-types retournes
Contraintes:
Definition at line 599 of file Type_info.cpp.
{
  int compteur=0;
  int i= nb_classes;
// Modif B. Mathieu: name() ne renvoie plus un static.
  const Nom& nom_mere = mere.name();
// Cerr << "---------" << (const char*) nom_mere << finl;
  while(i--)
    {
      if( les_types[i]->has_base(nom_mere, 0) )
        if (!les_types[i]->same(nom_mere))
          {
            compteur++;
          }
    }
// Cerr << compteur << finl ;
  if(compteur==0) return 0;
  les_sous_types.dimensionner(compteur);
  compteur=0;
  i= nb_classes;
  while(i--)
    {
      if( les_types[i]->has_base(nom_mere, 0) )
        if (!les_types[i]->same(nom_mere))
          {
            les_sous_types[compteur++]=les_types[i]->name();
          }
    }
  return compteur;
}
References compteur, has_base(), les_sous_types(), les_types, name(), nb_classes, and same().
name()
const Nom & Type_info::name () const inline
Definition at line 39 of file Type_info.h.
  {
    return *name_;
  };
References name_.
Referenced by ajouter_type(), bad_ref_cast(), bases(), O_U_Ptr::check_O_U_Ptr_type(), hierarchie(), instance(), Objet_U::le_type(), les_sous_types(), Objet_U::que_suis_je(), same(), search_type_info_name(), Deriv_::typer(), and ~Type_info().
operator=()
Type_info & Type_info::operator= (Type_info &) private
Constructeur par copie invalide.
Operateur= invalide
same() [1/2]
int Type_info::same (const Nom & other_name) const
Comparaison sur le nom d'un type
Retourne 1 si les chaines de caracteres des noms du type considere et du nom indique sont identiques
Retour 0 sinon.
Definition at line 568 of file Type_info.cpp.
{
  return strcmp(name(),other_name)==0;
}
References name().
same() [2/2]
int Type_info::same (const Type_info * p) const
Renvoie 1 si this==p, 0 sinon.
Definition at line 575 of file Type_info.cpp.
{
  return (this == p);
}
Referenced by can_cast(), and les_sous_types().
search_type_info_name()
int Type_info::search_type_info_name (const char * nom, int & index) static private
Recherche le type de nom "nom" dans la liste de types enregistres
par une recherche binaire.
On compare les chaines converties en majuscules.
On range dans "index" l'indice du type, s'il a ete trouve
et sinon l'indice du type juste apres (dans ce cas, on a
les_types[index-1]->n < nom < les_types[index]->n)
Si le type a ete trouve on renvoie 1, sinon 0.
Definition at line 106 of file Type_info.cpp.
{
  assert(nom != 0);
// [imin..imax] est l'intervalle ou se trouve l'index recherche
  int imin = 0;
  int imax = nb_classes;
  while (imax > imin)
    {
// On a toujours milieu < imax
      int milieu = (imin + imax) / 2;
      int comparaison = strcmp_uppercase(nom, les_types[milieu]->name());
      if (comparaison == 0)
        {
          index = milieu;
          return 1;
        }
      if (comparaison < 0)
        {
// nom < les_types[milieu]
// l'index recherche est donc inferieur ou egal a "milieu"
          imax = milieu;
        }
      else
        {
// nom > les_types[milieu]
// l'index recherche est donc strictement superieur a "milieu"
          imin = milieu + 1;
        }
    }
  index = imax;
  return 0;
}
References les_types, name(), nb_classes, and strcmp_uppercase().
Referenced by ajouter_type(), type_info_from_name(), and ~Type_info().
type_info_from_name()
const Type_info * Type_info::type_info_from_name (const char * type_name) static
Methode statique qui renvoie un pointeur vers le Type_info
dont le nom est "type_name". Si type_name n'est pas un type,
renvoie un pointeur nul.
Definition at line 674 of file Type_info.cpp.
{
  const Type_info * type_info = 0;
  if (type_name != 0)
    {
      int index;
      if (search_type_info_name(type_name, index))
        {
          if (types_homonymes[index] == 0)
            {
              type_info = les_types[index];
            }
          else
            {
// Le type est enregistre mais le nom correspond
// a plusieurs types...
              Cerr << "const Type_info * Type_info::type_info_from_name(const char * type_name)\n";
              Cerr << " The type " << type_name << " has several homonymous\n";
              Cerr << " We doing as if the type is unknown..." << finl;
            }
        }
    }
  return type_info;
}
References Cerr, finl, les_types, search_type_info_name(), and types_homonymes.
Referenced by est_un_type(), has_base(), instance(), Deriv_::typer(), and Discretisation_base::verifie_sous_type().
Member Data Documentation
b
const Type_info** Type_info::b private
Definition at line 80 of file Type_info.h.
Referenced by bases(), and has_base().
cree_instance
Objet_U *(* Type_info::cree_instance) () private
Definition at line 83 of file Type_info.h.
Referenced by instance(), and instanciable().
les_types
const Type_info ** Type_info::les_types =0 static private
Definition at line 87 of file Type_info.h.
Referenced by ajouter_type(), hierarchie(), les_sous_types(), search_type_info_name(), type_info_from_name(), and ~Type_info().
les_types_memsize
int Type_info::les_types_memsize =0 static private
Definition at line 95 of file Type_info.h.
Referenced by ajouter_type(), and ~Type_info().
name_
Nom* Type_info::name_ mutable private
(eg: A)
Definition at line 72 of file Type_info.h.
Referenced by ajouter_type(), name(), and ~Type_info().
names_
const char* Type_info::names_ private
Definition at line 70 of file Type_info.h.
Referenced by ajouter_type().
nb_bases_
int Type_info::nb_bases_ private
Definition at line 78 of file Type_info.h.
Referenced by bases(), and has_base().
nb_classes
int Type_info::nb_classes =0 static private
Definition at line 92 of file Type_info.h.
Referenced by ajouter_type(), hierarchie(), les_sous_types(), search_type_info_name(), and ~Type_info().
synonym_
Synonyme_info* Type_info::synonym_ private
Synonym.
Definition at line 75 of file Type_info.h.
Referenced by ajouter_type(), and ~Type_info().
synonym_name_
Nom* Type_info::synonym_name_ mutable private
(eg: B) Object synonym:
Definition at line 73 of file Type_info.h.
Referenced by ajouter_type(), and ~Type_info().
types_homonymes
int * Type_info::types_homonymes =0 static private
Definition at line 90 of file Type_info.h.
Referenced by ajouter_type(), type_info_from_name(), and ~Type_info().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Type_info.h
src/Kernel/Utilitaires/Type_info.cpp