TRUST: Precond Class Reference
Precond Class Reference
#include <Precond.h>
Public Member Functions
Precond ()
~Precond ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int preconditionner (const Matrice_Base &, const DoubleVect &, DoubleVect &)
int supporte_matrice_morse_sym ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Precond & self_cast (Objet_U &)
static const Precond & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 40 of file Precond.h.
Constructor & Destructor Documentation
Precond::Precond ()
Definition at line 26 of file Precond.cpp.
Precond::~Precond ()
Definition at line 26 of file Precond.cpp.
Member Function Documentation
Objet_U * Precond::cree_instance () [static]
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
int Precond::duplique () const [virtual]
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
const Type_info * Precond::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
const Type_info * Precond::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
int Precond::preconditionner (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) [inline]
Definition at line 53 of file Precond.h.
References Precond_base::preconditionner(), and Deriv_Precond_base::valeur().
Referenced by PrecondA::preconditionner_(), Solv_GCP_NS::resoudre_systeme(), and Solv_Gen::solve().
{
// B.M. pour ne pas modifier le comportement d'origine, debrancher le champ si on passe
// par cette methode:
  Precond_base& p = valeur();
  return p.preconditionner(matrice,secmem,solution);
}
Sortie & Precond::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Precond_base.
Definition at line 28 of file Precond.cpp.
References DERIV.
{
  return DERIV(Precond_base)::printOn(s);
}
Entree & Precond::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Precond_base.
Definition at line 34 of file Precond.cpp.
References DERIV.
{
  return DERIV(Precond_base)::readOn(is);
}
const Precond & Precond::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
Precond & Precond::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
int Precond::supporte_matrice_morse_sym () [inline]
Definition at line 47 of file Precond.h.
References Precond_base::supporte_matrice_morse_sym(), and Deriv_Precond_base::valeur().
Referenced by Solv_GCP::supporte_matrice_morse_sym().
  {
    return valeur().supporte_matrice_morse_sym();
  };
unsigned Precond::taille_memoire () const [virtual]
Reimplemented from Deriv_Precond_base.
Definition at line 26 of file Precond.cpp.
Member Data Documentation
const Type_info Precond::info_obj [static]
Reimplemented from Deriv_Precond_base.
Definition at line 42 of file Precond.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Precond.h
src/Kernel/Math/SolvSys/Precond.cpp