TRUST: TRUSTList_Curseur< _TYPE_ > Class Template Reference
TRUSTList_Curseur< _TYPE_ > Class Template Reference
: List_Curseur de reels int/double precision
#include <TRUSTList.h>
Public Member Functions
TRUSTList_Curseur (const TRUSTList< _TYPE_ > &a_list)
TRUSTList_Curseur (const TRUSTListElem< _TYPE_ > &a_list)
operator bool () const
Teste si le curseur est non nul.
void operator++ ()
_TYPE_ valeur () const
_TYPE_ & valeur ()
void operator= (const TRUSTList< _TYPE_ > &a_list)
const TRUSTListElem< _TYPE_ > & list () const
TRUSTListElem< _TYPE_ > & list ()
Private Attributes
TRUSTListElem< _TYPE_ > * curseur
Detailed Description
template<typename _TYPE_>
class TRUSTList_Curseur< _TYPE_ >
: List_Curseur de reels int/double precision
Definition at line 93 of file TRUSTList.h.
Constructor & Destructor Documentation
TRUSTList_Curseur() [1/2]
template<typename _TYPE_ > TRUSTList_Curseur< _TYPE_ >::TRUSTList_Curseur (const TRUSTList< _TYPE_ > & a_list) inline
Definition at line 96 of file TRUSTList.h.
: curseur(&(TRUSTListElem<_TYPE_>&) a_list) { if (a_list.est_vide()) curseur = 0; }
References TRUSTList_Curseur< _TYPE_ >::curseur, and TRUSTListElem< _TYPE_ >::est_vide().
TRUSTList_Curseur() [2/2]
template<typename _TYPE_ > TRUSTList_Curseur< _TYPE_ >::TRUSTList_Curseur (const TRUSTListElem< _TYPE_ > & a_list) inline
Definition at line 97 of file TRUSTList.h.
: curseur(&(TRUSTListElem<_TYPE_>&) a_list) { if (a_list.est_vide()) curseur = 0; }
References TRUSTList_Curseur< _TYPE_ >::curseur, and TRUSTListElem< _TYPE_ >::est_vide().
Member Function Documentation
list() [1/2]
template<typename _TYPE_ > TRUSTListElem< _TYPE_ > & TRUSTList_Curseur< _TYPE_ >::list () inline
Definition at line 117 of file TRUSTList.h.
{ return *curseur; }
References TRUSTList_Curseur< _TYPE_ >::curseur.
list() [2/2]
template<typename _TYPE_ > const TRUSTListElem< _TYPE_ > & TRUSTList_Curseur< _TYPE_ >::list () const inline
Definition at line 116 of file TRUSTList.h.
{ return *curseur; }
References TRUSTList_Curseur< _TYPE_ >::curseur.
Referenced by TRUSTList< _TYPE_ >::printOn(), and TRUSTList< _TYPE_ >::suppr().
operator bool()
template<typename _TYPE_ > TRUSTList_Curseur< _TYPE_ >::operator bool () const inline
Teste si le curseur est non nul.
Definition at line 99 of file TRUSTList.h.
References TRUSTList_Curseur< _TYPE_ >::curseur.
operator++()
template<typename _TYPE_ > void TRUSTList_Curseur< _TYPE_ >::operator++ () inline
Definition at line 102 of file TRUSTList.h.
{ curseur = curseur->est_dernier() ? 0 : &(curseur->suivant()); }
References TRUSTList_Curseur< _TYPE_ >::curseur.
operator=()
template<typename _TYPE_ > void TRUSTList_Curseur< _TYPE_ >::operator= (const TRUSTList< _TYPE_ > & a_list) inline
Definition at line 109 of file TRUSTList.h.
  {
    curseur = (&(TRUSTListElem<_TYPE_>&) a_list);
    if (a_list.est_vide()) curseur = 0;
  }
References TRUSTList_Curseur< _TYPE_ >::curseur, and TRUSTListElem< _TYPE_ >::est_vide().
valeur() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTList_Curseur< _TYPE_ >::valeur () inline
Definition at line 106 of file TRUSTList.h.
{ return curseur->valeur(); }
References TRUSTList_Curseur< _TYPE_ >::curseur.
valeur() [2/2]
template<typename _TYPE_ > _TYPE_ TRUSTList_Curseur< _TYPE_ >::valeur () const inline
Definition at line 105 of file TRUSTList.h.
{ return curseur->valeur(); }
References TRUSTList_Curseur< _TYPE_ >::curseur.
Referenced by TRUSTList< _TYPE_ >::calcule_min_max(), Faces::compare(), TRUSTList< _TYPE_ >::contient(), VerifierCoin::interpreter_(), TRUSTList< _TYPE_ >::operator[](), TRUSTList< _TYPE_ >::printOn(), TRUSTList< _TYPE_ >::rang(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), and TRUSTList< _TYPE_ >::suppr().
Member Data Documentation
curseur
template<typename _TYPE_ > TRUSTListElem<_TYPE_>* TRUSTList_Curseur< _TYPE_ >::curseur private
Definition at line 120 of file TRUSTList.h.
Referenced by TRUSTList_Curseur< _TYPE_ >::list(), TRUSTList_Curseur< _TYPE_ >::operator bool(), TRUSTList_Curseur< _TYPE_ >::operator++(), TRUSTList_Curseur< _TYPE_ >::operator=(), TRUSTList_Curseur< _TYPE_ >::TRUSTList_Curseur(), and TRUSTList_Curseur< _TYPE_ >::valeur().
The documentation for this class was generated from the following file:
src/Kernel/Math/TRUSTList.h