TRUST: Ref_Front_VF Class Reference
Ref_Front_VF Class Reference
#include <Ref_Front_VF.h>
Public Member Functions
~Ref_Front_VF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Front_VF ()
Ref_Front_VF (const Front_VF &)
Ref_Front_VF (const Ref_Front_VF &)
const Front_VF & valeur () const
Front_VF & valeur ()
const Front_VF * operator-> () const
Front_VF * operator-> ()
const Ref_Front_VF & operator= (const Front_VF &)
const Ref_Front_VF & operator= (const Ref_Front_VF &)
operator const Front_VF & () const
operator Front_VF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Front_VF & self_cast (Objet_U &)
static const Ref_Front_VF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Front_VF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Front_VF.h.
Constructor & Destructor Documentation
Ref_Front_VF::~Ref_Front_VF ()
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF::Ref_Front_VF ()
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF::Ref_Front_VF (const Front_VF & t)
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF::Ref_Front_VF (const Ref_Front_VF & t)
Definition at line 26 of file Ref_Front_VF.cpp.
Member Function Documentation
Objet_U * Ref_Front_VF::cree_instance () [static]
Definition at line 26 of file Ref_Front_VF.cpp.
int Ref_Front_VF::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
const Type_info * Ref_Front_VF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
const Type_info & Ref_Front_VF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Front_VF.cpp.
const Type_info * Ref_Front_VF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF::operator const Front_VF & () const
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF::operator Front_VF & ()
Definition at line 26 of file Ref_Front_VF.cpp.
const Front_VF * Ref_Front_VF::operator-> () const [inline]
Definition at line 28 of file Ref_Front_VF.h.
Front_VF * Ref_Front_VF::operator-> () [inline]
Definition at line 28 of file Ref_Front_VF.h.
const Ref_Front_VF & Ref_Front_VF::operator= (const Ref_Front_VF & t)
Definition at line 26 of file Ref_Front_VF.cpp.
const Ref_Front_VF & Ref_Front_VF::operator= (const Front_VF & t)
Definition at line 26 of file Ref_Front_VF.cpp.
Sortie & Ref_Front_VF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
Entree & Ref_Front_VF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
const Ref_Front_VF & Ref_Front_VF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
Ref_Front_VF & Ref_Front_VF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Front_VF.cpp.
void Ref_Front_VF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Front_VF.cpp.
unsigned Ref_Front_VF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Front_VF.cpp.
const Front_VF & Ref_Front_VF::valeur () const [inline]
Definition at line 28 of file Ref_Front_VF.h.
Referenced by Champ_front_contact_VEF::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), and Champ_front_contact_VEF::verifier_scalaire_bord().
Front_VF & Ref_Front_VF::valeur () [inline]
Definition at line 28 of file Ref_Front_VF.h.
Member Data Documentation
const Type_info Ref_Front_VF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Front_VF.h.
Front_VF* Ref_Front_VF::pointeur_ [private]
Definition at line 28 of file Ref_Front_VF.h.
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Ref_Front_VF.h
src/Kernel/VF/Zones/Ref_Front_VF.cpp