TRUST: Eval_Puiss_Th_QC_EF Class Reference
Eval_Puiss_Th_QC_EF Class Reference
#include <Eval_Puiss_Th_QC_EF.h>
Public Member Functions
Eval_Puiss_Th_QC_EF ()
void completer () override
void associer_puissance (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_EF_Som
Evaluateur_Source_EF_Som ()
Evaluateur_Source_EF_Som (const Evaluateur_Source_EF_Som &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
Public Member Functions inherited from Evaluateur_Source_EF
Evaluateur_Source_EF ()
virtual ~Evaluateur_Source_EF ()
Evaluateur_Source_EF (const Evaluateur_Source_EF &)
void associer_zones (const Zone_EF &, const Zone_Cl_EF &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Protected Attributes inherited from Evaluateur_Source_EF
Ref_Zone_EF la_zone
Ref_Zone_Cl_EF la_zone_cl
Detailed Description
Definition at line 25 of file Eval_Puiss_Th_QC_EF.h.
Constructor & Destructor Documentation
Eval_Puiss_Th_QC_EF()
Eval_Puiss_Th_QC_EF::Eval_Puiss_Th_QC_EF () inline
Definition at line 49 of file Eval_Puiss_Th_QC_EF.h.
{}
Member Function Documentation
associer_puissance()
void Eval_Puiss_Th_QC_EF::associer_puissance (const Champ_Don & Q)
Definition at line 26 of file Eval_Puiss_Th_QC_EF.cpp.
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
References la_puissance, puissance, TRUSTTab< _TYPE_ >::ref(), and Champ_Don::valeurs().
Referenced by Puissance_Thermique_QC_EF::associer_pb().
calculer_terme_source_standard() [1/2]
double Eval_Puiss_Th_QC_EF::calculer_terme_source_standard (int num_elem) const inline override virtual
Implements Evaluateur_Source_EF_Som.
Definition at line 59 of file Eval_Puiss_Th_QC_EF.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    source = puissance(0,0) ;
  else
    {
      if (puissance.nb_dim()==1)
        source = puissance(num_elem);
      else
        source = puissance(num_elem,0);
    }
  return (source);
}
References la_puissance, TRUSTTab< _TYPE_ >::nb_dim(), puissance, sub_type, Deriv_Champ_Don_base::valeur(), and Ref_Champ_Don::valeur().
Referenced by calculer_terme_source_standard().
calculer_terme_source_standard() [2/2]
void Eval_Puiss_Th_QC_EF::calculer_terme_source_standard (int num_elem, DoubleVect & d) const inline override virtual
Implements Evaluateur_Source_EF_Som.
Definition at line 51 of file Eval_Puiss_Th_QC_EF.h.
{
  Cerr<<"Non code"<<__FILE__<<(int)__LINE__<<finl;
  Process::exit();
  throw;
  return calculer_terme_source_standard(num_elem,d);
}
References calculer_terme_source_standard(), Cerr, Process::exit(), and finl.
completer()
void Eval_Puiss_Th_QC_EF::completer (void) override virtual
Reimplemented from Evaluateur_Source_EF_Som.
Definition at line 20 of file Eval_Puiss_Th_QC_EF.cpp.
{
  Evaluateur_Source_EF_Som::completer();
// nb_som_elem_=(la_zone->zone().nb_som_elem());
}
References Evaluateur_Source_EF_Som::completer().
mettre_a_jour()
void Eval_Puiss_Th_QC_EF::mettre_a_jour () override virtual
Implements Evaluateur_Source_EF.
Definition at line 32 of file Eval_Puiss_Th_QC_EF.cpp.
{
}
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Puiss_Th_QC_EF::la_puissance protected
Definition at line 39 of file Eval_Puiss_Th_QC_EF.h.
Referenced by associer_puissance(), and calculer_terme_source_standard().
puissance
DoubleTab Eval_Puiss_Th_QC_EF::puissance protected
Definition at line 40 of file Eval_Puiss_Th_QC_EF.h.
Referenced by associer_puissance(), and calculer_terme_source_standard().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/EF/Eval_Puiss_Th_QC_EF.h
src/ThHyd/Dilatable/Quasi_Compressible/EF/Eval_Puiss_Th_QC_EF.cpp