TRUST: Field_base Class Reference
Field_base Class Reference
#include <Field_base.h>
Public Member Functions
~Field_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)
void nommer (const Nom &)
Donne un nom au champ.
const Nom & le_nom () const
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension
que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les
composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom
et peuvent etre differentes pour chaque composante
du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les
composantes ont la meme unite.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enumere) Nature_du_champ est defini dans Ch_base.h.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
Definition at line 46 of file Field_base.h.
Constructor & Destructor Documentation
Field_base::~Field_base ()
Definition at line 25 of file Field_base.cpp.
Field_base::Field_base ()
Definition at line 27 of file Field_base.cpp.
                       :
  nb_compo_(0),
  nature_(scalaire)
{}
Field_base::Field_base (const Field_base & other)
Member Function Documentation
void Field_base::add_synonymous (const Nom & nom) [inline]
Definition at line 100 of file Field_base.h.
References Vect_Nom::add(), and noms_synonymes_.
Referenced by Champ_front::add_synonymous(), Navier_Stokes_std::discretiser(), and Convection_Diffusion_Espece_Multi_base::readOn().
{
  noms_synonymes_.add(nom);
}
virtual int Field_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Nature_du_champ Field_base::fixer_nature_du_champ (Nature_du_champ n) [virtual]
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enumere) Nature_du_champ est defini dans Ch_base.h.
Returns:
Nature_du_champ
Signification: la nature du champ
Contraintes:
Definition at line 383 of file Field_base.cpp.
References nature_.
Referenced by Masse_VEF_P1NC::ajouter_masse(), Solveur_Masse_EF::ajouter_masse(), Champ_base::Champ_base(), Masse_Multiphase::discretiser(), Energie_Multiphase::discretiser(), Milieu_base::discretiser(), VEF_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), CoviMAC_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), EF_discretisation::discretiser_champ_fonc_don(), CoviMAC_discretisation::discretiser_champ_fonc_don(), fixer_nb_comp(), fixer_unite(), fixer_unites(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), and CoviMAC_discretisation::grad_u().
{
  return nature_ = n;
}
void Field_base::fixer_nb_comp (int i) [virtual]
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension
que l'espace.
Returns:
void
Definition at line 95 of file Field_base.cpp.
References Objet_U::dimension, vect_impl::dimensionner(), fixer_nature_du_champ(), multi_scalaire, nb_compo_, noms_compo_, and vectoriel.
Referenced by Op_Diff_RotRot::associer(), EOS_Tools_VDF::associer_zones(), Discretisation_base::champ_fixer_membres_communs(), Champ_front_contact_VEF::connectivity_failed(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), Champ_front_calc::creer(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), Champ_Don_base::dimensionner(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), Champ::fixer_nb_comp(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), CoviMAC_discretisation::modifier_champ_tabule(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), Champ_front_tangentiel_VEF::readOn(), Champ_front_fonc_gradient_VEF::readOn(), Champ_front_contact_VEF::readOn(), Champ_front_fonc_gradient_VDF::readOn(), Dirichlet_paroi_fixe::readOn(), Champ_front_synt::readOn(), Champ_front_pression_from_u::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Champ_front_debit_QC::readOn(), Champ_front_softanalytique::readOn(), Champ_front_recyclage::readOn(), Champ_front_MED::readOn(), Champ_front_var::readOn(), Ch_front_var_instationnaire_dep::readOn(), Champ_som_lu::readOn(), Init_par_partie::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Tabule_Morceaux::readOn(), Champ_front_xyz_debit::readOn(), Champ_front_uniforme::readOn(), Champ_front_txyz::readOn(), Champ_front_tangentiel::readOn(), Champ_front_Tabule::readOn(), Champ_front_t::readOn(), Champ_front_normal::readOn(), Champ_front_lu::readOn(), Champ_Front_Fonction::readOn(), Champ_front_fonc_pois_tube::readOn(), Champ_front_fonc_pois_ipsn::readOn(), Champ_front_debit::readOn(), Champ_front_bruite::readOn(), Champ_Fonc_Tabule::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Champ_Fonc_Fonction::readOn(), Champ_Don_Fonc_txyz::readOn(), Ch_front_Vortex::readOn(), VDF_discretisation::reynolds_maille(), Champ_input_P0::set_nb_comp(), Ch_input_uniforme::set_nb_comp(), Ch_front_input_uniforme::set_nb_comp(), Ch_front_input::set_nb_comp(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_1D::vitesse(), VDF_discretisation::vorticite(), VEF_discretisation::y_plus(), and VDF_discretisation::y_plus().
{
// Interdiction de changer la nature du champ une fois
// le nb_valeurs_nodales fixe.
  nb_compo_ = i ;
  noms_compo_.dimensionner(i);
  if(i==dimension)
    fixer_nature_du_champ(vectoriel);
  else if(i>dimension)
    fixer_nature_du_champ(multi_scalaire);
}
const Nom & Field_base::fixer_nom_compo (int i, const Nom & nom) [virtual]
Fixe le nom de la i-eme composante du champ.
Returns:
Nom&
Signification: le nom de i-eme composante du champ
Contraintes: reference constante
Definition at line 166 of file Field_base.cpp.
References nb_comp(), and noms_compo_.
Referenced by VDF_discretisation::courant_maille(), VDF_discretisation::creer_champ_vorticite(), Masse_Multiphase::discretiser(), Energie_Multiphase::discretiser(), Champ::fixer_nom_compo(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VDF_discretisation::reynolds_maille(), and VDF_discretisation::vorticite().
{
  assert(i<nb_comp());
  return noms_compo_[i]=nom;
}
const Nom & Field_base::fixer_nom_compo (const Nom & nom) [virtual]
Fixe le nom d'un champ scalaire.
Returns:
Nom&
Signification: le nom du champ scalaire
Contraintes: reference constante
Definition at line 207 of file Field_base.cpp.
References vect_impl::dimensionner_force(), nb_comp(), nommer(), and noms_compo_.
{
  assert(nb_comp()==1);
  nommer(nom);
  noms_compo_.dimensionner_force(1);
  return noms_compo_[0]=nom;
}
const Noms & Field_base::fixer_noms_compo (const Noms & noms) [virtual]
Fixe le nom des composantes du champ.
Returns:
Noms&
Signification: le tableau des noms des composantes du champ
Contraintes: reference constante
Definition at line 122 of file Field_base.cpp.
References noms_compo_.
Referenced by Discretisation_base::champ_fixer_membres_communs(), Champ_base::corriger_unite_nom_compo(), VEF_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), CoviMAC_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), EF_discretisation::discretiser_champ_fonc_don(), CoviMAC_discretisation::discretiser_champ_fonc_don(), and Champ::fixer_noms_compo().
{
  return noms_compo_=noms;
}
const Nom & Field_base::fixer_unite (int i, const Nom & nom) [virtual]
Specifie l'unite de la i-eme composante du champ.
Returns:
Nom&
Signification: le type de l'unite de la i-eme composante du champ
Contraintes: reference constante
Definition at line 298 of file Field_base.cpp.
References fixer_nature_du_champ(), multi_scalaire, and unite_.
{
  fixer_nature_du_champ(multi_scalaire);
  return unite_[i]=nom;
}
const Nom & Field_base::fixer_unite (const Nom & nom) [virtual]
Specifie l'unite d'un champ scalaire ou dont toutes les
composantes ont la meme unite.
Returns:
Nom&
Signification: l'unite du champ
Contraintes: reference constante
Definition at line 339 of file Field_base.cpp.
References vect_impl::dimensionner_force(), and unite_.
Referenced by Op_Diff_RotRot::associer(), Champ_base::Champ_base(), Discretisation_base::champ_fixer_membres_communs(), VDF_discretisation::courant_maille(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), Champ::fixer_unite(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Discretisation_base::nommer_completer_champ_physique(), VDF_discretisation::reynolds_maille(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_1D::vitesse(), VDF_discretisation::vorticite(), VEF_discretisation::y_plus(), and VDF_discretisation::y_plus().
{
  unite_.dimensionner_force(1);
  return unite_[0]=nom;
}
const Noms & Field_base::fixer_unites (const Noms & noms) [virtual]
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom
et peuvent etre differentes pour chaque composante
du champ.
Returns:
Noms&
Signification: les noms des unites des composantes du champ
Contraintes: reference constante
Definition at line 252 of file Field_base.cpp.
References vect_impl::dimensionner_force(), fixer_nature_du_champ(), multi_scalaire, nb_comp(), and unite_.
Referenced by VEF_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), CoviMAC_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), EF_discretisation::discretiser_champ_fonc_don(), CoviMAC_discretisation::discretiser_champ_fonc_don(), and Champ::fixer_unites().
{
  unite_.dimensionner_force(nb_comp());
  fixer_nature_du_champ(multi_scalaire);
  return unite_=noms;
}
const Type_info * Field_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 25 of file Field_base.cpp.
const Noms & Field_base::get_synonyms () const [inline]
Definition at line 95 of file Field_base.h.
References noms_synonymes_.
Referenced by Champ_Generique_refChamp::get_property(), Champ_front::get_synonyms(), Champs_compris::has_champ(), and rebuild_liste_noms().
{
  return noms_synonymes_;
}
const Type_info * Field_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 25 of file Field_base.cpp.
const Nom & Field_base::le_nom () const [virtual]
Renvoie le nom du champ.
Returns:
Nom&
Signification: le nom du champ
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 56 of file Field_base.cpp.
References nom_.
Referenced by Probleme_base::addInputField(), Champ_implementation_P0::affecter_(), Champ_Fonc_Tabule::affecter_(), Champs_compris::ajoute_champ(), Travail_pression_CoviMAC::ajouter_blocs(), Terme_Source_Acceleration_VEF_Face::associer_champ_rho(), Terme_Source_Acceleration_VDF_Face::associer_champ_rho(), Source_base::associer_champ_rho(), Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Operateur_Conv_base::associer_norme_vitesse(), Champ_base::associer_zone_dis_base(), Equation_base::calculer_champ_conserve(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Fluide_base::calculer_e_int(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Chimie::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Extraction::completer(), composante(), Champ_front_contact_VEF::connectivity_failed(), Champ_base::corriger_unite_nom_compo(), Champ_Fonc_MED::creer(), Pb_MED::creer_champ(), QDM_Multiphase::dimensionner_blocs(), Equation_base::discretiser(), Convection_Diffusion_Temperature::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_refChamp::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_refChamp::get_localisation(), Champ_input_P0::get_name(), Ch_input_uniforme::get_name(), Ch_front_input_uniforme::get_name(), Ch_front_input::get_name(), Champ_Generique_refChamp::get_ref_connectivity(), Ch_front_input_P1::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), Ch_front_input_uniforme::getTemplate(), Ch_front_input::getTemplate(), Champs_compris::has_champ(), Source_PDF_EF::impr(), Echange_contact_CoviMAC::initialiser(), Ecrire_Champ_MED::interpreter(), Piso::iterer_NS(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Champ_front::le_nom(), Champ::le_nom(), Champ_Fonc_MED::lire(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Champ_Inc_base::mettre_a_jour(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), nom_compo(), Champ_Generique_refChamp::nommer_source(), Y_plus_Champ_P1NC::printOn(), Taux_cisaillement_P0_VEF::printOn(), Rotationnel_Champ_Q1NC::printOn(), Rotationnel_Champ_P1NC::printOn(), h_conv_Champ_P1NC::printOn(), grad_U_Champ_P1NC::printOn(), grad_T_Champ_P1NC::printOn(), Critere_Q_Champ_P1NC::printOn(), Correlation_Vec_Sca_VEF::printOn(), Champ_Q1NC::printOn(), Champ_P1NC::printOn(), Champ_P0_VEF::printOn(), Champ_Fonc_Tabule_P0_VEF::printOn(), Champ_Fonc_Q1NC::printOn(), Champ_Fonc_Q1_VEF::printOn(), Champ_Fonc_P1NC::printOn(), Champ_Fonc_P1_VEF::printOn(), Champ_Fonc_P0_VEF::printOn(), Y_plus_Champ_Face::printOn(), Taux_cisaillement_P0_VDF::printOn(), Rotationnel_Champ_Face::printOn(), Reynolds_maille_Champ_Face::printOn(), grad_U_Champ_Face::printOn(), Critere_Q_Champ_Face::printOn(), Courant_maille_Champ_Face::printOn(), Correlation_Vec_Sca_VDF::printOn(), Champ_P0_VDF::printOn(), Champ_Fonc_Tabule_P0_VDF::printOn(), Champ_Fonc_Q1_VDF::printOn(), Champ_Fonc_P1_VDF::printOn(), Champ_Fonc_P0_VDF::printOn(), Champ_Fonc_Face::printOn(), Champ_Face::printOn(), grad_U_Champ_Face_PolyMAC::printOn(), Champ_Q1_PolyMAC::printOn(), Champ_P1_PolyMAC::printOn(), Champ_P0_PolyMAC::printOn(), Champ_Fonc_Tabule_P0_PolyMAC::printOn(), Champ_Fonc_Q1_PolyMAC::printOn(), Champ_Fonc_P1_PolyMAC::printOn(), Champ_Fonc_P0_PolyMAC::printOn(), Champ_Fonc_Face_PolyMAC::printOn(), Champ_Face_PolyMAC::printOn(), Champ_Fonc_P1_isoP1Bulle::printOn(), Champ_Fonc_reprise::printOn(), Champ_Fonc_Q1_MED::printOn(), Champ_Fonc_P1_MED::printOn(), Champ_Fonc_P0_MED::printOn(), Champ_Fonc_MED::printOn(), Champ_front_var_instationnaire::printOn(), Champ_front_var::printOn(), Champ_front_base::printOn(), Champ_base::printOn(), Ch_front_var_stationnaire::printOn(), Ch_front_var_instationnaire_indep::printOn(), Ch_front_var_instationnaire_dep::printOn(), Champ_P1_iso::printOn(), Champ_Inc_Q1_base::printOn(), Champ_Inc_P1_base::printOn(), Champ_Inc_P0_base::printOn(), Champ_Fonc_Q1_base::printOn(), Champ_Fonc_P1_base::printOn(), Champ_Fonc_P0_base::printOn(), Champ_front_fonc_pois_tube::printOn(), Champ_front_fonc_pois_ipsn::printOn(), Champ_front_fonc::printOn(), Rotationnel_Champ_Q1_EF::printOn(), Rotationnel_Champ_P1_EF::printOn(), Champ_Q1_EF::printOn(), Champ_P1_EF::printOn(), Champ_P0_EF::printOn(), Champ_Fonc_Tabule_P0_EF::printOn(), Champ_Fonc_Q1_EF::printOn(), Champ_Fonc_P1_EF::printOn(), Champ_Fonc_P0_EF::printOn(), grad_U_Champ_Face_CoviMAC::printOn(), Champ_Q1_CoviMAC::printOn(), Champ_P1_CoviMAC::printOn(), Champ_P0_CoviMAC::printOn(), Champ_Fonc_Tabule_P0_CoviMAC::printOn(), Champ_Fonc_Q1_CoviMAC::printOn(), Champ_Fonc_P1_CoviMAC::printOn(), Champ_Fonc_P0_CoviMAC::printOn(), Champ_Fonc_Face_CoviMAC::printOn(), Champ_Face_CoviMAC::printOn(), Champ_Fonc_reprise::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Sutherland::readOn(), rebuild_liste_noms(), Moyenne_volumique::traiter_champs(), Champ_Inc_base::valeur_aux_bords(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), valeur_P1_L2(), Equation_base::verifie_ch_init_nb_comp(), and Champ_base::zone_dis_base().
{
  return nom_;
}
Nature_du_champ Field_base::nature_du_champ () const [inline]
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
Returns:
Nature_du_champ
Signification: la nature du champ
Contraintes:
Definition at line 138 of file Field_base.h.
References nature_.
Referenced by Op_Dift_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_EF::ajouter(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_Generique_Transformation::completer(), Champ_base::completer_post_champ(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_CoviMAC::imposer_cond_lim(), Postraitement::init(), Op_VEF_Face::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Postraitement::postraiter_champs(), Champ_Generique_Transformation::preparer_macro(), Zone_Cl_EF::remplir_type_elem_Cl(), Moyenne_volumique::traiter_champs(), Champ_Post_Operateur_Eqn::verification_cas_compo(), and Equation_base::verifie_ch_init_nb_comp().
{
  return nature_;
}
int Field_base::nb_comp () const [inline]
Renvoie le nombre de composantes du champ.
Returns:
int
Signification: le nombre de composantes du champ
Contraintes:
Definition at line 119 of file Field_base.h.
References nb_compo_.
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Source_Scalaire_EF::ajouter(), Milieu_base::associer_gravite(), Champ_Tabule_Morceaux::calculer_champ_tabule_morceaux(), Terme_Source_Constituant::completer(), Op_Moyenne::completer(), Op_Ecart_type::completer(), Op_Correlation::completer(), Source_base::completer(), Champ_Generique_Transformation::completer(), Champ_base::completer_post_champ(), Champ_Q1NC::compo_normale_sortante(), Champ_P1NC::compo_normale_sortante(), Equation_base::ecrire_fichier_xyz(), fixer_nom_compo(), fixer_unites(), Champ_Generique_modifier_pour_QC::get_champ(), Pb_MED::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Post_Operateur_Eqn::get_property(), Ch_front_input_P1::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), Ch_front_input_uniforme::getTemplate(), Ch_front_input::getTemplate(), Champs_compris::has_champ(), Zone_Cl_VEF::imposer_cond_lim(), Champ_Q4_implementation::imprime_Q4(), Postraitement::init(), Echange_contact_PolyMAC::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_var::initialiser(), Champ_front_instationnaire_base::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_lu::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Terme_Puissance_Thermique::lire_donnees(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_front_synt::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), CoviMAC_discretisation::modifier_champ_tabule(), Op_VEF_Face::modifier_flux(), Champ_Fonc_P0_VEF::moyenne(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_VDF::moyenne(), Champ_Fonc_P0_PolyMAC::moyenne(), Champ_Fonc_P0_EF::moyenne(), Champ_Fonc_P0_CoviMAC::moyenne(), Champ_front::nb_comp(), Champ_Don::nb_comp(), Champ::nb_comp(), nom_compo(), Champ_P1NC::norme_H1(), Postraitement_lata::postraiter_liste_champs(), Champ_Generique_Transformation::preparer_macro(), Champ_front_MED::readOn(), Source_Scalaire_EF::readOn(), Terme_Source_Qdm_Face_CoviMAC::readOn(), rebuild_liste_noms(), Champ_Face_PolyMAC::trace(), Champ_Face_CoviMAC::trace(), Moyenne_volumique::traiter_champs(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Champ_front_softanalytique::valeur_a(), Champ_Uniforme::valeur_a(), Champ_base::valeur_a_compo(), Champ_Q1NC_impl::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_implementation_sommet_base::valeur_a_elem(), Champ_implementation_P0::valeur_a_elem(), Champ_Uniforme::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_implementation_sommet_base::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_base::valeur_aux_compo(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_CoviMAC::valeur_aux_faces(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_Post_Operateur_Eqn::verification_cas_compo(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Equation_base::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Champ_Q1NC::verifie_valeurs_cl(), and Champ_P1NC::verifie_valeurs_cl().
{
  return nb_compo_ ;
}
const Nom & Field_base::nom_compo () const
Renvoie le nom d'un champ scalaire.
Returns:
Nom&
Signification: le nom du champ scalaire
Contraintes: reference constante
Definition at line 229 of file Field_base.cpp.
References le_nom(), and nb_comp().
Referenced by Champ_base::corriger_unite_nom_compo().
{
  assert(nb_comp()==1);
  return le_nom();
}
const Nom & Field_base::nom_compo (int i) const
Renvoie le nom de la ieme composante du champ.
Returns:
Nom& nom
Signification: le nom de i-eme composante du champ
Contraintes: reference constante
Definition at line 187 of file Field_base.cpp.
References nb_comp(), and noms_compo_.
Referenced by Champs_compris::has_champ(), Champ::nom_compo(), and rebuild_liste_noms().
{
  assert(i<nb_comp());
  return noms_compo_[i];
}
void Field_base::nommer (const Nom & name) [virtual]
Donne un nom au champ.
Reimplemented from Objet_U.
Definition at line 75 of file Field_base.cpp.
References nom_.
Referenced by Op_Diff_RotRot::associer(), Champ_base::Champ_base(), Discretisation_base::champ_fixer_membres_communs(), Champ_front_contact_VEF::connectivity_failed(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), Pb_MED::creer_champ(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), fixer_nom_compo(), Discret_Thermique::Fluctu_Temperature(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), Champ_front::nommer(), Champ_Fonc::nommer(), Champ::nommer(), Discretisation_base::nommer_completer_champ_physique(), Champ_Fonc_MED::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), VDF_discretisation::reynolds_maille(), Champ_input_P0::set_name(), Ch_input_uniforme::set_name(), Ch_front_input_uniforme::set_name(), Ch_front_input::set_name(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_1D::vitesse(), VDF_discretisation::vorticite(), VEF_discretisation::y_plus(), and VDF_discretisation::y_plus().
{
  nom_ = name ;
}
const Noms & Field_base::noms_compo () const
Renvoie le tableau des noms des composantes du champ.
Returns:
Noms&
Signification: les noms des composantes du champ
Contraintes: reference constante
Definition at line 141 of file Field_base.cpp.
References noms_compo_.
Referenced by Terme_Source_Constituant::completer(), Op_Correlation::completer(), Champ_base::completer_post_champ(), composante(), Postraitement::creer_champ_post_stat(), Champ_Generique_refChamp::get_property(), Ecrire_Champ_MED::interpreter(), Champ::noms_compo(), and Moyenne_volumique::traiter_champs().
{
  return noms_compo_;
}
Sortie & Field_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 32 of file Field_base.cpp.
{
  return s;
}
Entree & Field_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 37 of file Field_base.cpp.
{
  return is;
}
Field_base & Field_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 25 of file Field_base.cpp.
const Field_base & Field_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 25 of file Field_base.cpp.
const Nom & Field_base::unite () const
Renvoie l'unite d'un champ scalaire dont toutes les
composantes ont la meme unite.
Returns:
Nom&
Signification: l'unite (commune) des composantes du champ
Contraintes: reference constante
Definition at line 361 of file Field_base.cpp.
References vect_impl::size(), and unite_.
Referenced by Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Operateur_Conv_base::associer_norme_vitesse(), Op_Moyenne::completer(), Op_Ecart_type::completer(), and Champ::unite().
{
  assert(unite_.size() == 1);
  return unite_[0];
}
const Nom & Field_base::unite (int i) const
Renvoie l'unite de la i-eme composante du champ.
Returns:
Nom&
Signification: l'unite de la i-eme composante du champ
Contraintes: reference constante
Definition at line 319 of file Field_base.cpp.
References unite_.
{
  return unite_[i];
}
const Noms & Field_base::unites () const
Renvoie les unites des composantes du champ.
Returns:
Noms&
Signification: les noms des unites des composantes du champ
Contraintes: reference constante
Definition at line 273 of file Field_base.cpp.
References unite_.
Referenced by Op_Moyenne::completer(), Op_Ecart_type::completer(), Champ_Generique_refChamp::get_property(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::traiter_champs(), and Champ::unites().
{
  return unite_;
}
Member Data Documentation
const Type_info Field_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Champ_Face_CoviMAC, Champ_Fonc_Face_CoviMAC, Champ_Fonc_P0_CoviMAC, Champ_Fonc_P1_CoviMAC, Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, Champ_P0_CoviMAC, Champ_P1_CoviMAC, Champ_Q1_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Ch_input_uniforme, Champ_Don_Fonc_txyz, Champ_Don_Fonc_xyz, Champ_Don_lu, Champ_Fonc_Fonction, Sutherland, Champ_Fonc_Fonction_txyz, Champ_Fonc_Fonction_txyz_Morceaux, Champ_Fonc_Morceaux, Champ_Fonc_t, Champ_Fonc_Tabule, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_xyz_debit, champ_init_canal_sinal, Champ_input_P0, Champ_Tabule_Morceaux, Champ_Tabule_Temps, Champ_Uniforme, Champ_Uniforme_inst, Champ_Uniforme_Morceaux, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_Morceaux_Tabule_Temps, Champ_val_tot_sur_vol_base, Init_par_partie, Tayl_Green, Ch_front_input_P1, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_P1_iso, Champ_som_lu, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_base, Champ_Don_base, Champ_Fonc_base, Champ_front_base, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P0_PolyMAC, Champ_Fonc_P1_PolyMAC, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, Champ_P0_PolyMAC, Champ_P1_PolyMAC, Champ_Q1_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 48 of file Field_base.h.
Nature_du_champ Field_base::nature_ [protected]
Definition at line 92 of file Field_base.h.
Referenced by fixer_nature_du_champ(), and nature_du_champ().
int Field_base::nb_compo_ [protected]
Definition at line 91 of file Field_base.h.
Referenced by Champ_P1NC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_post(), Champ_base::Champ_base(), Champ_base::corriger_unite_nom_compo(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Champ_val_tot_sur_vol_base::evaluer(), fixer_nb_comp(), Champ_Fonc_Face::fixer_nb_valeurs_nodales(), Champ_Face::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Don_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_CoviMAC::fixer_nb_valeurs_nodales(), Champ_Face_CoviMAC::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1_VEF::imprime(), Champ_P0_VDF::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Q1_PolyMAC::imprime(), Champ_P1_PolyMAC::imprime(), Champ_P0_PolyMAC::imprime(), Champ_Fonc_Q1_PolyMAC::imprime(), Champ_Fonc_P1_PolyMAC::imprime(), Champ_Q1_EF::imprime(), Champ_P1_EF::imprime(), Champ_P0_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_Fonc_P1_EF::imprime(), Champ_Q1_CoviMAC::imprime(), Champ_P1_CoviMAC::imprime(), Champ_P0_CoviMAC::imprime(), Champ_Fonc_Q1_CoviMAC::imprime(), Champ_Fonc_P1_CoviMAC::imprime(), Champ_front_recyclage::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::mettre_a_jour(), nb_comp(), Champ_Fonc_reprise::readOn(), Champ_Tabule_Temps::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Champ_input_P0::setValue(), Champ_som_lu_VDF::valeur_a(), Champ_som_lu::valeur_a(), champ_init_canal_sinal::valeur_a(), Champ_Don_Fonc_xyz::valeur_a(), Champ_Don_Fonc_txyz::valeur_a(), Champ_Don_Fonc_xyz::valeur_a_compo(), Champ_Uniforme_Morceaux::valeur_a_elem(), Champ_Fonc_Morceaux::valeur_a_elem(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem(), Champ_Don_lu::valeur_a_elem(), Champ_Uniforme_Morceaux::valeur_a_elem_compo(), Champ_Fonc_Morceaux::valeur_a_elem_compo(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem_compo(), Champ_Don_lu::valeur_a_elem_compo(), Champ_Don_Fonc_xyz::valeur_a_elem_compo(), champ_init_canal_sinal::valeur_aux(), Champ_Don_Fonc_txyz::valeur_aux(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu_VDF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Fonc_Morceaux::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Don_lu::valeur_aux_elems(), Champ_front_instationnaire_base::valeurs_face(), Champ_front_base::valeurs_face(), and Champ_front_uniforme::valeurs_face().
Nom Field_base::nom_ [protected]
Definition at line 87 of file Field_base.h.
Referenced by le_nom(), nommer(), Champ_base::readOn(), Champ_Inc_base::reprendre(), Champ_Fonc_base::reprendre(), Champ_Inc_base::sauvegarder(), and Champ_Fonc_base::sauvegarder().
Noms Field_base::noms_compo_ [protected]
Definition at line 89 of file Field_base.h.
Referenced by fixer_nb_comp(), fixer_nom_compo(), fixer_noms_compo(), nom_compo(), and noms_compo().
Noms Field_base::noms_synonymes_ [protected]
Definition at line 88 of file Field_base.h.
Referenced by add_synonymous(), and get_synonyms().
Noms Field_base::unite_ [protected]
Definition at line 90 of file Field_base.h.
Referenced by Champ_base::corriger_unite_nom_compo(), fixer_unite(), fixer_unites(), unite(), and unites().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Field_base.h
src/Kernel/Framework/Field_base.cpp