TRUST: Op_Dift_standard_VEF_Face Class Reference
Op_Dift_standard_VEF_Face Class Reference
class Op_Dift_standard_VEF_Face
#include <Op_Dift_standard_VEF_Face.h>
Public Member Functions
Op_Dift_standard_VEF_Face ()
~Op_Dift_standard_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void calcul_divergence (DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const Zone_Cl_VEF &, const Zone_VEF &, DoubleTab &, int) const
void ajouter_cas_vectoriel (const DoubleTab &, DoubleTab &, DoubleTab &, const DoubleTab &, const DoubleTab &, const Zone_Cl_VEF &, const Zone_VEF &, const DoubleTab &, int) const
Public Member Functions inherited from Op_Dift_VEF_Face
Op_Dift_VEF_Face ()
~Op_Dift_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
double diffusivite (int) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_cl (const DoubleTab &, Matrice_Morse &, const DoubleTab &, const DoubleTab &, const DoubleVect &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleVect &inconnue, DoubleVect &resu, DoubleTab &flux_bords, const DoubleVect &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleTab &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Dift_VEF_base
Op_Dift_VEF_base ()
~Op_Dift_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_borne_locale (DoubleVect &, double, double) const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_standard_VEF_Face & self_cast (Objet_U &)
static const Op_Dift_standard_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_VEF_Face & self_cast (Objet_U &)
static const Op_Dift_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_base
static const Type_info * info ()
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Dift_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Champ_Inc divergence_U
int grad_Ubar
int nu_lu
int nut_lu
int nu_transp_lu
int nut_transp_lu
int filtrer_resu
Protected Attributes inherited from Op_Dift_VEF_Face
Ref_Champ_base diffusivite_
DoubleTab grad_
grad DoubleTab grad_transp_;
Protected Attributes inherited from Op_Dift_VEF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_standard_VEF_Face
Definition at line 29 of file Op_Dift_standard_VEF_Face.h.
Constructor & Destructor Documentation
Op_Dift_standard_VEF_Face()
Op_Dift_standard_VEF_Face::Op_Dift_standard_VEF_Face ()
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
~Op_Dift_standard_VEF_Face()
Op_Dift_standard_VEF_Face::~Op_Dift_standard_VEF_Face ()
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_standard_VEF_Face::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 316 of file Op_Dift_standard_VEF_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleTab& nu_turb=diffusivite_turbulente()->valeurs();
  DoubleTab nu(nu_turb);
  remplir_nu(nu);
  const int nb_comp = resu.line_size();
  ajouter_cas_vectoriel(inconnue, resu, flux_bords_,nu, nu_turb, zone_Cl_VEF, zone_VEF, tau_tan_,nb_comp);
  modifier_flux(*this);
  return resu;
}
References ajouter_cas_vectoriel(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Operateur_base::flux_bords_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Op_VEF_Face::modifier_flux(), Op_Diff_VEF_base::remplir_nu(), Op_Dift_VEF_base::tau_tan_, Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Champ_Fonc::valeurs().
ajouter_cas_vectoriel()
void Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel (const DoubleTab & vitesse, DoubleTab & resu, DoubleTab & tab_flux_bords, const DoubleTab & nu, const DoubleTab & nu_turb, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, const DoubleTab & tau_tan, int nbr_comp) const
Definition at line 86 of file Op_Dift_standard_VEF_Face.cpp.
{
// on cast grad et grad_transp pour pouvoir les modifier
// on utilise plus les static car pb avec plusieurs pbs
  DoubleTab& grad=ref_cast_non_const(DoubleTab,  grad_);
  Debog::verifier("Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel : resu 0 ",resu);
  DoubleVect n(Objet_U::dimension);
  DoubleVect t(Objet_U::dimension);
  DoubleTrav Tgrad(Objet_U::dimension,Objet_U::dimension);
  assert(nbr_comp>1);
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nbr_comp);
  tab_flux_bords=0.;
// Construction du tableau grad_
  if(!grad.get_md_vector().non_nul())
    {
      grad.resize(0, Objet_U::dimension, Objet_U::dimension);
      zone_VEF.zone().creer_tableau_elements(grad);
    }
// *** CALCUL DU GRADIENT ***
  DoubleTab ubar(vitesse);
  if(grad_Ubar)
    ref_cast(Champ_P1NC,inconnue_.valeur()).filtrer_L2(ubar);
  Champ_P1NC::calcul_gradient(ubar,grad,zone_Cl_VEF);
  if (le_modele_turbulence.valeur().utiliser_loi_paroi())
    Champ_P1NC::calcul_duidxj_paroi(grad,nu,nu_turb,tau_tan,zone_Cl_VEF);
  grad.echange_espace_virtuel();
// *** CALCUL DE LA DIFFUSION ***
  Debog::verifier("Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel : grad 1 ",grad);
// calcul_divergence(resu_div,grad,gradt,nu_div,nut_div,zone_Cl_VEF,zone_VEF,flux_bords,nb_comp);
// calcul_divergence(resu_div,grad,grad,nu_div,nut_div,zone_Cl_VEF,zone_VEF,flux_bords,nb_comp);
  calcul_divergence(resu,grad,grad,nu,nu_turb,zone_Cl_VEF,zone_VEF,flux_bords_,nbr_comp);
  Debog::verifier("Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel : resu 1 ",resu);
  if(filtrer_resu)
    {
      ref_cast(Champ_P1NC,inconnue_.valeur()).filtrer_resu(resu);
    }
}
References calcul_divergence(), Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), Zone::creer_tableau_elements(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), filtrer_resu, Operateur_base::flux_bords_, TRUSTVect< _TYPE_ >::get_md_vector(), Op_Dift_VEF_Face::grad_, grad_Ubar, Op_Diff_VEF_base::inconnue_, Op_Dift_VEF_base::le_modele_turbulence, Zone_VF::nb_faces_bord(), MD_Vector::non_nul(), ref_cast, ref_cast_non_const, TRUSTTab< _TYPE_ >::resize(), Mod_turb_hyd_base::utiliser_loi_paroi(), Ref_Champ_Inc_base::valeur(), Ref_Mod_turb_hyd_base::valeur(), Debog::verifier(), and Zone_dis_base::zone().
Referenced by ajouter().
calcul_divergence()
void Op_Dift_standard_VEF_Face::calcul_divergence (DoubleTab & dif, const DoubleTab & grad, const DoubleTab & gradt, const DoubleTab & nu, const DoubleTab & nu_turb, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, DoubleTab & tab_flux_bords, int nbr_comp) const
< PQ : valable en regime turbulent d'apres profil lineaire de la vitesse dans la sous couche visqueuse
< Pour les autres conditions aux limites
< PQ : en attendant de faire mieux
Definition at line 149 of file Op_Dift_standard_VEF_Face.cpp.
{
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normale = zone_VEF.face_normales();
// const DoubleVect& vol = zone_VEF.volumes();
  int nb_faces = zone_VEF.nb_faces();
// int face_int = zone_VEF.premiere_face_int();
  int num_cl;
  int num_face0,elem10, elem2;
  int i,j;
  double nu1,nu2;
  double nu1t,nu2t;
  double flux;
  double c1=0., c2=0., c3=0., c4=0.;
  if(nu_lu)                c1=1.;
  if(nut_lu)                c2=1.;
  if(nu_transp_lu)        c3=1.;
  if(nut_transp_lu)        c4=1.;
// Traitement des bords
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence dif 0 ",dif);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  int nb_cl=les_cl.size();
  for (num_cl=0; num_cl<nb_cl; num_cl++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(num_cl);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elem_faces = zone_VEF.elem_faces();
      int nb_faces_b=le_bord.nb_faces();
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + nb_faces_b;
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          IntVect fait(nb_faces_b);
          fait = 0;
          for (num_face0=num1; num_face0<num2; num_face0++)
            {
              int face_associee=la_cl_perio.face_associee(num_face0-num1);
              if (fait(num_face0-num1) == 0)
                {
                  fait(num_face0-num1) = 1;
                  fait(face_associee) = 1;
                  elem10 = face_voisins(num_face0,0);
                  elem2 = face_voisins(num_face0,1);
                  nu1 = c1*nu[elem10]+c2*nu_turb[elem10];
                  nu2 = c1*nu[elem2]+c2*nu_turb[elem2];
                  nu1t= c3*nu[elem10]+c4*nu_turb[elem10];
                  nu2t= c3*nu[elem2]+c4*nu_turb[elem2];
                  for (i=0; i<nbr_comp; i++)
                    for (j=0; j<nbr_comp; j++)
                      {
                        dif(num_face0,i) -= face_normale(num_face0,j)*
                                            (nu1*grad(elem10,i,j)+nu1t*gradt(elem10,j,i)
                                             -(nu2*grad(elem2,i,j)+nu2t*gradt(elem2,j,i)));
// Cerr << num_face << " " << i << dif(num_face,i) << finl;
                      }
                  for (i=0; i<nbr_comp; i++)
                    dif(face_associee+num1,i)=dif(num_face0,i);
// dif(num_face,num_comp) -= 0.5*ori*face_normale(num_face,num_comp2)*(2*nu*Sij(elem,num_comp,num_comp2));
// Patrick : le coefficient 0.5 dans l'ancienne formulation est incorrect : les faces periodiques ne sont traitees qu'UNE fois
                }
            } //!< Fin de la boucle sur les faces
        } //!< Fin du cas periodique
      else if ( (sub_type(Dirichlet,la_cl.valeur()))
                || (sub_type(Dirichlet_homogene,la_cl.valeur()))
              )
        {
          if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
              sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) )
            {
              for (num_face0=num1; num_face0<num2; num_face0++)
                {
                  int elem1=face_voisins(num_face0,0);
                  nu1 = c1*nu[elem1]+c2*nu_turb[elem1];
                  nu1t= c3*nu[elem1]+c4*nu_turb[elem1];
                  for (i=0; i<nbr_comp; i++)
                    {
                      flux=0.;
                      for (j=0; j<nbr_comp; j++)
                        flux +=face_normale(num_face0,j)*(nu1*grad(elem1,i,j)+nu1t*gradt(elem1,j,i));
                      dif(num_face0,i) = 0.; //!< PQ : valable en regime turbulent d'apres profil lineaire de la vitesse dans la sous couche visqueuse
                      tab_flux_bords(num_face0,i) -= flux;
                    }
                } //!< Fin de la boucle sur les faces
            } //!< Fin du cas paroi fixe ou defilante
          else  //On est en Dirichlet ou Dirichlet homogene : Boucle speciale car les volumes de controle sont modifies
            {
// Cerr << "Si on passe la , on est mal!!! : Ce n'est pas code!!!" << finl;
            } //!< Fin du traitement des CL de type Dirichlet ou Dirichlet homogene hors paroi_fixe paroi_defilante
        } //!< Fin du traitement des CL de type Dirichlet ou Dirichlet homogene
      else //!< Pour les autres conditions aux limites
        {
          for (int num_face=num1; num_face<num2; num_face++)
            {
              int elem1=face_voisins(num_face,0);
              nu1 = c1*nu[elem1]+c2*nu_turb[elem1];
              nu1t= c3*nu[elem1]+c4*nu_turb[elem1];
              for (i=0; i<nbr_comp; i++)
                {
                  flux=0.;
                  for (j=0; j<nbr_comp; j++)
                    flux +=face_normale(num_face,j)*(nu1*grad(elem1,i,j)+nu1t*gradt(elem1,j,i));
                  dif(num_face,i) = 0.; //!< PQ : en attendant de faire mieux
                  tab_flux_bords(num_face,i) -= flux;
                }
            }
        }
    } //!< Fin du traitement des CL
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence dif 1 ",dif);
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence nu 1 ",nu);
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence nu_turb 1 ",nu_turb);
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence grad 1 ",grad);
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence gradt 1 ",gradt);
//
  for (num_face0=zone_VEF.premiere_face_int(); num_face0<nb_faces; num_face0++)
    {
      elem10 = face_voisins(num_face0,0);
      elem2 = face_voisins(num_face0,1);
      nu1 = c1*nu[elem10]+c2*nu_turb[elem10];
      nu2 = c1*nu[elem2]+c2*nu_turb[elem2];
      nu1t= c3*nu[elem10]+c4*nu_turb[elem10];
      nu2t= c3*nu[elem2]+c4*nu_turb[elem2];
      for (i=0; i<nbr_comp; i++)
        for (j=0; j<nbr_comp; j++)
          dif(num_face0,i) -= face_normale(num_face0,j)*
                              (nu1*grad(elem10,i,j)+nu1t*gradt(elem10,j,i)
                               -(nu2*grad(elem2,i,j)+nu2t*gradt(elem2,j,i)));
// (nu1*grad(elem1,i,j)+nu1t*gradt(elem1,j,i)-(i==j)*dst*nu1*div(elem1)
// -(nu2*grad(elem2,i,j)+nu2t*gradt(elem2,j,i)-(i==j)*dst*nu1*div(elem2)));
// dif(num_face,num_comp) -= ori*face_normale(num_face,num_comp2)*(2*nu*Sij(elem,num_comp,num_comp2));
    } //!< Fin de la boucle sur les faces internes
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence dif 2 ",dif);
  dif.echange_espace_virtuel();
  Debog::verifier("Op_Dift_standard_VEF_Face::calcul_divergence dif 3 ",dif);
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), nu_lu, nu_transp_lu, Front_VF::num_premiere_face(), nut_lu, nut_transp_lu, Zone_VF::premiere_face_int(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), and Debog::verifier().
Referenced by ajouter_cas_vectoriel().
cree_instance()
Objet_U * Op_Dift_standard_VEF_Face::cree_instance () static
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
duplique()
int Op_Dift_standard_VEF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_standard_VEF_Face_Var.
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
get_info()
const Type_info * Op_Dift_standard_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_standard_VEF_Face_Var.
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
info()
const Type_info * Op_Dift_standard_VEF_Face::info () static
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
printOn()
Sortie & Op_Dift_standard_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_standard_VEF_Face_Var.
Definition at line 35 of file Op_Dift_standard_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_standard_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_standard_VEF_Face_Var.
Definition at line 43 of file Op_Dift_standard_VEF_Face.cpp.
{
  Cerr<<"je suis dans Op_Dift_standard_VEF_Face::readOn"<<finl;
  grad_Ubar=1;
  nu_lu=1;
  nut_lu=1;
  nu_transp_lu=1;
  nut_transp_lu=1;
  filtrer_resu=1;
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motlu;
  is >> motlu;
  while (motlu!=accfermee)
    {
      if (motlu=="defaut_bar")
        {
          is >> motlu;
          break;
        }
      else if (motlu=="grad_Ubar")
        is >> grad_Ubar;
      else if (motlu=="nu")
        is >> nu_lu;
      else if (motlu=="nut")
        is >> nut_lu;
      else if (motlu=="nu_transp")
        is >> nu_transp_lu;
      else if (motlu=="nut_transp")
        is >> nut_transp_lu;
      else if (motlu=="filtrer_resu")
        is >> filtrer_resu;
      else
        {
          Cerr << motlu << "n'est pas compris par " << que_suis_je() << finl;
          exit();
        }
      is >> motlu;
    }
  Cerr << "grad_Ubar " << grad_Ubar << " nu_lu " << nu_lu <<" nut_lu " <<  nut_lu <<" nu_transp_lu " <<  nu_transp_lu <<" nut_transp_lu " <<  nut_transp_lu <<" filtrer_resu " <<  filtrer_resu << finl;
  return is ;
}
References Cerr, Process::exit(), filtrer_resu, finl, grad_Ubar, nu_lu, nu_transp_lu, nut_lu, nut_transp_lu, and Objet_U::que_suis_je().
Referenced by Op_Dift_standard_VEF_Face_Var::readOn().
self_cast() [1/2]
const Op_Dift_standard_VEF_Face & Op_Dift_standard_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
self_cast() [2/2]
Op_Dift_standard_VEF_Face & Op_Dift_standard_VEF_Face::self_cast (Objet_U & r) static
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
taille_memoire()
unsigned Op_Dift_standard_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_standard_VEF_Face_Var.
Definition at line 26 of file Op_Dift_standard_VEF_Face.cpp.
Member Data Documentation
divergence_U
Ref_Champ_Inc Op_Dift_standard_VEF_Face::divergence_U protected
Definition at line 42 of file Op_Dift_standard_VEF_Face.h.
filtrer_resu
int Op_Dift_standard_VEF_Face::filtrer_resu protected
Definition at line 49 of file Op_Dift_standard_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
grad_Ubar
int Op_Dift_standard_VEF_Face::grad_Ubar protected
Definition at line 44 of file Op_Dift_standard_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
info_obj
const Type_info Op_Dift_standard_VEF_Face::info_obj static
Definition at line 31 of file Op_Dift_standard_VEF_Face.h.
nu_lu
int Op_Dift_standard_VEF_Face::nu_lu protected
Definition at line 45 of file Op_Dift_standard_VEF_Face.h.
Referenced by calcul_divergence(), and readOn().
nu_transp_lu
int Op_Dift_standard_VEF_Face::nu_transp_lu protected
Definition at line 47 of file Op_Dift_standard_VEF_Face.h.
Referenced by calcul_divergence(), and readOn().
nut_lu
int Op_Dift_standard_VEF_Face::nut_lu protected
Definition at line 46 of file Op_Dift_standard_VEF_Face.h.
Referenced by calcul_divergence(), and readOn().
nut_transp_lu
int Op_Dift_standard_VEF_Face::nut_transp_lu protected
Definition at line 48 of file Op_Dift_standard_VEF_Face.h.
Referenced by calcul_divergence(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Dift_standard_VEF_Face.h
src/VEF/Operateurs/Op_Dift_standard_VEF_Face.cpp