TRUST: IntTab Class Reference
IntTab Class Reference
Tableau a n entrees pour n<= 4
Repose sur un IntVect avec calculs de l'indice corespondant
Voir les commentaires de IntVect.
#include <IntTab.h>
Public Member Functions
~IntTab ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
IntTab ()
IntTab (const IntTab &)
IntTab (int n)
IntTab (int n1, int n2)
IntTab (int n1, int n2, int n3)
IntTab (int n1, int n2, int n3, int n4)
virtual void ref (const IntVect &)
fait pointer le tableau sur le vecteur v et en associant
la meme structure parallele.
Attention, si line_size du vecteur v est different de 1,
on cree un tableau bidimensionnel (on peut avoir un vecteur
de ce type si on copie un Tab dans un Vect puis on prend
une ref sur ce Vect).
virtual void ref (const IntTab &)
fait pointer le tableau sur le tableau t
en recuperant la structure parallele. Attention,
on fige le tableau qui ne pourra plus etre resize
virtual void ref_data (int *ptr, int size)
identique a DoubleVect::ref_data()
virtual void ref_array (ArrOfInt &, int start=0, int sz=-1)
identique a DoubleVect::ref_array()
(cree un tableau monodimensionnel sans structure parallele)
Attention, le tableau source et destination sont figes (resize interdit)
(voir ArrOfInt::
virtual void ref_tab (IntTab &, int start_line=0, int nb_lines=-1)
fait pointer le tableau sur une sous-partie du tableau t
definie par la valeur du premier indice et ne nombre de "lignes" du tableau
a recuperer (une ligne = toutes les valeurs tab(i,j,k,...) pour un i donne).
Le nombre de dimensions du tableau est le meme que pour t,
les dimension(i) pour i>=1 sont les memes et dimension(0) = nb_lines.
virtual void reset ()
met le tableau dans l'etat obtenu par le constructeur par defaut
voir IntVect::reset()
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle qui force le tableau a changer de taille.
Change aussi nb_dim_ a 1. Equivalent a IntTab::resize(n, opt)
void resize_dim0 (int n, Array_base::Resize_Options opt=COPY_INIT)
change la dimension[0] du tableau en conservant les autres.
void resize (int n, Array_base::Resize_Options opt=COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un IntTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
void resize (int n1, int n2, Array_base::Resize_Options opt=COPY_INIT)
void resize (int n1, int n2, int n3, Array_base::Resize_Options opt=COPY_INIT)
void resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt=COPY_INIT)
void resize (const ArrOfInt &tailles, Array_base::Resize_Options opt=COPY_INIT)
redimensionne le tableau (nb_dim_ sera egal a tailles.size_array()
et dimension(i) a tailles[i].
IntTab & operator= (const IntTab &)
copie la structure et les valeurs du tableau src
Restrictions et preconditions identiques a IntVect::operator=(const IntVect & v)
IntTab & operator= (const IntVect &)
copie la structure et les valeurs de src.
Attention: appel invalide si src est un type derive de Vect
(sinon quoi faire, un tableau unidimensionnel, ou une copie de la structure ?)
IntTab & operator= (const FIntTab &)
IntTab & operator= (int d)
idem que ArrOfInt::operator=(int)
void copy (const IntTab &, Array_base::Resize_Options opt=COPY_INIT)
int & operator() (const ArrOfInt &indice)
int operator() (const ArrOfInt &indice) const
int & operator[] (int i)
operateur [] retourne le ieme element du tableau
const int & operator[] (int i) const
operateur [] retourne le ieme element du tableau
int & operator() (int i)
idem operator[]
const int & operator() (int i) const
int & operator() (int i1, int i2)
const int & operator() (int i1, int i2) const
int & operator() (int i1, int i2, int i3)
const int & operator() (int i1, int i2, int i3) const
int & operator() (int i1, int i2, int i3, int i4)
const int & operator() (int i1, int i2, int i3, int i4) const
int dimension (int) const
Returns one of the "real" dimensions of the multi-dimensionnal array,
as defined by:
dimension(0) = size_reelle() / line_size(), or 0 if line_size()==0
and, for i >= 1:
dimension(i) is equal to dimension_tot(i)
If size_reelle_ok() returns 0, it is invalid to ask for dimension(0). You can only ask for
dimension_tot(0) (see IntVect::size_reelle_ok())
int dimension_tot (int) const
Returns the total dimensions of the multi-dimensionnal array, including
virtual items (used in parallel distributed arrays)
int nb_dim () const
Returns the number of dimensions of the array (>= 1)
virtual void set_md_vector (const MD_Vector &)
associe le md_vector au vecteur (voir IntVect::set_md_vector())
dimension(0) sera initialise a md_vector...get_nb_items_reels().
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
virtual void ecrit (Sortie &) const
ecriture des valeurs du tableau "raw" sans structure parallele
void append_line (int)
Adds 1 to dimension_tot(0) and puts a in the added line.
void append_line (int, int)
Adds 1 to dimension_tot(0) and puts a and b in the added line.
void append_line (int, int, int)
Like append_line(i,j), but for arrays with line_size()==3.
void append_line (int, int, int, int)
Like append_line(i,j), but for arrays with line_size()==4.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static IntTab & self_cast (Objet_U &)
static const IntTab & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
ecriture d'un tableau sequentiel
(idem que IntVect::printOn() on ne sait pas quoi faire de pertinent
pour un tableau distribue).
virtual Entree & readOn (Entree &)
lecture d'un tableau sequentiel
Private Attributes
int nb_dim_
int dimensions_ [MAXDIM_TAB]
int dimension_tot_0_
Detailed Description
Tableau a n entrees pour n<= 4
Repose sur un IntVect avec calculs de l'indice corespondant
Voir les commentaires de IntVect.
Definition at line 49 of file IntTab.h.
Constructor & Destructor Documentation
IntTab::~IntTab ()
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
IntTab::IntTab ()
Definition at line 122 of file IntTab.cpp.
References dimensions_, and init_dimensions().
               :
  nb_dim_(1), dimension_tot_0_(0)
{
  init_dimensions(dimensions_);
  dimensions_[0] = 0;
}
IntTab::IntTab (const IntTab & dbt)
Definition at line 129 of file IntTab.cpp.
References dimensions_, and MAXDIM_TAB.
                                :
  IntVect(dbt),
  nb_dim_(dbt.nb_dim_),
  dimension_tot_0_(dbt.dimension_tot_0_)
{
  for (int i = 0; i < MAXDIM_TAB; i++)
    dimensions_[i] = dbt.dimensions_[i];
}
IntTab::IntTab (int n)
Definition at line 140 of file IntTab.cpp.
References dimensions_, and init_dimensions().
  : IntVect(n PARAM_X2),
    nb_dim_(1),
    dimension_tot_0_(n)
{
  init_dimensions(dimensions_);
  dimensions_[0] = n;
}
IntTab::IntTab (int n1, int n2)
Definition at line 149 of file IntTab.cpp.
References Cerr, dimensions_, Process::exit(), finl, init_dimensions(), and IntVect::set_line_size_().
  : IntVect(n1*n2 PARAM_X2),
    nb_dim_(2),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0);
  if (n1*n2<0)
    {
      Cerr << "n1*n2 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << finl;
      exit();
    }
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  set_line_size_(n2);
}
IntTab::IntTab (int n1, int n2, int n3)
Definition at line 184 of file IntTab.cpp.
References Cerr, dimensions_, Process::exit(), finl, init_dimensions(), and IntVect::set_line_size_().
  : IntVect(n1*n2*n3 PARAM_X2),
    nb_dim_(3),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0 && n3 >= 0);
  if (n1*n2*n3<0)
    {
      Cerr << "n1*n2*n3 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << " and n3=" << n3 << finl;
      exit();
    }
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  dimensions_[2]=n3;
  set_line_size_(n2*n3);
}
IntTab::IntTab (int n1, int n2, int n3, int n4)
Definition at line 202 of file IntTab.cpp.
References Cerr, dimensions_, Process::exit(), finl, init_dimensions(), and IntVect::set_line_size_().
  : IntVect(n1*n2*n3*n4 PARAM_X2),
    nb_dim_(4),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
  if (n1*n2*n3*n4<0)
    {
      Cerr << "n1*n2*n3*n4 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << " and n3=" << n3 << " and n3=" << n3 << finl;
      exit();
    }
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  dimensions_[2]=n3;
  dimensions_[3]=n4;
  set_line_size_(n2*n3*n4);
}
Member Function Documentation
void IntTab::append_line (int a) [inline]
Adds 1 to dimension_tot(0) and puts a in the added line.
Definition at line 261 of file IntTab.h.
References ArrOfInt::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, IntVect::line_size(), IntVect::resize_vect_(), and ArrOfInt::size_array().
Referenced by SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Zone::creer_aretes(), Op_Grad_VDF_Face::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Div_CoviMAC::dimensionner(), Masse_CoviMAC_Face::dimensionner_blocs(), QDM_Multiphase::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), Matrice_Dense::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Zone_PolyMAC::init_m2solv(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Zone_CoviMAC::init_stencils(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Zone_PolyMAC::init_we_2d(), Zone_PolyMAC::init_we_3d(), and Traduction_Indice_Global_Local::initialiser().
{
  assert(line_size() == 1);
  assert(dimension_tot_0_ * line_size() == size_array());
  const int n = dimension_tot_0_;
  dimensions_[0] = ++dimension_tot_0_;
  IntVect::resize_vect_(n+1, COPY_NOINIT);
  int * ptr = addr() + n;
  ptr[0] = a;
}
void IntTab::append_line (int a, int b) [inline]
Adds 1 to dimension_tot(0) and puts a and b in the added line.
Definition at line 274 of file IntTab.h.
References ArrOfInt::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, IntVect::line_size(), IntVect::resize_vect_(), and ArrOfInt::size_array().
{
  assert(line_size() == 2);
  assert(dimension_tot_0_ * line_size() == size_array());
  const int n = dimension_tot_0_ * 2;
  dimensions_[0] = ++dimension_tot_0_;
  IntVect::resize_vect_(n+2, COPY_NOINIT);
  int * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
}
void IntTab::append_line (int a, int b, int c) [inline]
Like append_line(i,j), but for arrays with line_size()==3.
Definition at line 287 of file IntTab.h.
References ArrOfInt::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, IntVect::line_size(), IntVect::resize_vect_(), and ArrOfInt::size_array().
{
  assert(line_size() == 3);
  assert(dimension_tot_0_  * line_size() == size_array());
  const int n = dimension_tot_0_ * 3;
  dimensions_[0] = ++dimension_tot_0_;
  IntVect::resize_vect_(n+3, COPY_NOINIT);
  int * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
}
void IntTab::append_line (int a, int b, int c, int d) [inline]
Like append_line(i,j), but for arrays with line_size()==4.
Definition at line 301 of file IntTab.h.
References ArrOfInt::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, IntVect::line_size(), IntVect::resize_vect_(), and ArrOfInt::size_array().
{
  assert(line_size() == 4);
  assert(dimension_tot_0_  * line_size() == size_array());
  const int n = dimension_tot_0_ * 4;
  dimensions_[0] = ++dimension_tot_0_;
  IntVect::resize_vect_(n+4, COPY_NOINIT);
  int * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
  ptr[3] = d;
}
void IntTab::copy (const IntTab & src, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 499 of file IntTab.cpp.
References CHECK_LINE_SIZE, IntVect::copy_(), dimension_tot_0_, dimensions_, MAXDIM_TAB, and nb_dim_.
Referenced by Convection_Diffusion_Temperature::calcul_indic_pena_global(), Zone_VEF_PreP1b::construire_ok_arete(), echanger_tableau_aretes(), IntTrav::IntTrav(), and operator=().
{
  if (&src != this)
    {
      IntVect::copy_(src, opt);
      nb_dim_ = src.nb_dim_;
      for (int i = 0; i < MAXDIM_TAB; i++)
        dimensions_[i] = src.dimensions_[i];
      dimension_tot_0_ = src.dimension_tot_0_;
      assert(CHECK_LINE_SIZE);
    }
}
Objet_U * IntTab::cree_instance () [static]
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
int IntTab::dimension (int i) const [inline]
Returns one of the "real" dimensions of the multi-dimensionnal array,
as defined by:
dimension(0) = size_reelle() / line_size(), or 0 if line_size()==0
and, for i >= 1:
dimension(i) is equal to dimension_tot(i)
If size_reelle_ok() returns 0, it is invalid to ask for dimension(0). You can only ask for
dimension_tot(0) (see IntVect::size_reelle_ok())
Definition at line 233 of file IntTab.h.
References dimensions_, and nb_dim_.
Referenced by Frontiere::add(), BlocData::add_bloc(), BlocData::add_faces(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Perte_Charge_PolyMAC::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Faces::ajouter(), Op_Grad_EF::ajouter(), ajouter_bord(), Sonde::ajouter_bords(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Polyedre::ajouter_elements(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Faces_builder::ajouter_une_face(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_EF::assembler_mat(), auto_build_joints(), Octree_Int::build(), build_cells(), Refine_Mesh::build_edges(), build_edges(), Octree_Double::build_elements(), build_frontier(), Refine_Mesh::build_incidence_from_node_to_edges(), Matrix_tools::build_morse_matrix(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_nodes(), build_nodes(), Octree_Int::build_octree_recursively(), Matrice_Bloc::build_stencil(), Matrix_tools::build_symmetric_morse_matrix(), build_triofield(), Ch_front_input::buildSommetsFaces(), Domaine::buildUFacesMesh(), Aretes::calculer_centre_de_gravite(), Polyedre::calculer_centres_gravite(), calculer_centres_gravite(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), Triangle::calculer_normales(), Tetraedre::calculer_normales(), Rectangle::calculer_normales(), Hexaedre::calculer_normales(), Op_Conv_EF_VEF_P1NC_Stab::calculer_senseur(), Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v1(), Faces::calculer_surfaces(), calculer_vecteur_2faces(), Polyedre::calculer_volumes(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::check_faces_periodiques(), check_internal_diagonal_for_tetrahedron(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), Zone::check_zone(), Reordonner_faces_periodiques::chercher_direction_perio(), chercher_elems_voisins_faces(), Faces_builder::chercher_face_element(), Traduction_Indice_Global_Local::chercher_table_inverse(), choose_internal_diagonal_for_tetrahedron(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Raccord_distant_homogene::completer(), Periodique::completer(), Zones::comprimer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), compute_global_connex_components(), compute_graph_connex_components(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), Zone::construire_elem_virt_pe_num(), DomaineCutter::construire_elements_distants_ssdom(), construire_elems_sous_domaine(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), construire_liste_sommets_sousdomaine(), Zone_VF::construire_num_fac_loc(), Zone_VEF_PreP1b::construire_ok_arete(), Scatter::construire_structures_paralleles(), Polyedre::contient(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), convert_domain_to_Domaine(), coord_barycentrique(), coord_barycentrique_P1(), coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_tetraedre(), coord_barycentrique_P1_triangle(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), create_listb_from_domaine2(), create_listb_from_xyz(), Zone::creer_aretes(), Remove_elem::creer_faces(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Faces_builder::creer_faces_reeles(), Tetraedriser_homogene_fin::decoupe(), Tetraedriser_homogene_compact::decoupe(), decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Matrice_Morse::dimensionner(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_CoviMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), disp_it(), echanger_tableau_aretes(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Debog_Pb::ecrire_gen(), Format_Post_Lata::ecrire_item_int(), Format_Post_Lml::ecrire_item_int_lml(), ensure_positive_volumes_for_tetrahedron(), ensure_positive_volumes_for_triangle(), Matrix_tools::extend_matrix_stencil(), TroisDto2D::extraire_2D(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder_en3::extruder(), Extruder_en20::extruder(), Extruder::extruder(), Extruder::extruder_hexa(), Zone_VF::face_virt_pe_num(), Faces_builder::faces_element_reference(), Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), find_joint_faces(), Champ_implementation_Q1::form_function(), Champ_implementation_P1::form_function(), Polygone::get_nb_som_elem_max(), Polyedre::get_nb_som_elem_max(), Matrice_Dense::get_stencil(), Matrice_Bloc::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Base::get_stencil_size(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Ch_front_input_P1::getTemplate(), Champ_input_P0::getTemplate(), Ch_front_input::getTemplate(), histogramme_angle(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_partiellement(), Zone::indice_elements(), Champ_P0_PolyMAC::init_cl(), Champ_Face_PolyMAC::init_cl(), Zone_CoviMAC::init_equiv(), Zone::init_faces_virt_bord(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Zone_CoviMAC::init_stencils(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Champ_Face_CoviMAC::init_ve2(), Zone_PolyMAC::init_we(), Zone_PolyMAC::init_we_2d(), Zone_PolyMAC::init_we_3d(), Echange_contact_PolyMAC::initialiser(), Traduction_Indice_Global_Local::initialiser(), DomaineCutter::initialiser(), Sonde_Int::initialiser(), Sonde::initialiser(), Integrer_champ_med::interpreter(), Raffiner_isotrope_parallele::interpreter(), MaillerParallel::interpreter(), VerifierCoin::interpreter_(), Extraire_plan::interpreter_(), Extraire_domaine::interpreter_(), Matrix_tools::is_diagonal_stencil(), Matrix_tools::is_normalized_stencil(), Matrix_tools::is_normalized_symmetric_stencil(), Matrix_tools::is_null_stencil(), Postraitement_lata::lire_champs(), lit(), Zone_VF::marquer_faces_double_contrib(), Zones::merge(), Champ_Don_Fonc_txyz::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), modifieP1P1neumann(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_EF_base::modifier_pour_Cl(), multiplier_diviser_rho(), Zone::nb_aretes(), Zone::nb_elem(), Zone_VF::nb_faces(), Faces::nb_faces(), Zone_VF::nb_som_face(), Faces::nb_som_faces(), NettoieNoeuds::nettoie(), Discretisation_tools::nodes_to_cells(), Polyedre_PolyMAC::normale(), Polyedre_CoviMAC::normale(), Zone_VF::numero_face_local(), OrienteFacesBord::oriente_faces_bord(), Zone_PolyMAC::orthocentrer(), parcourir_epaisseurs_elements(), Convection_Diffusion_Temperature::penalisation_L2(), Polyedriser::polyedriser(), Sonde_Int::postraiter(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeRoot::rang_arete(), Champ_Don_Fonc_xyz::readOn(), Remove_elem::recreer_faces(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Remove_elem::remplir_liste(), Zone_Cl_EF::remplir_type_elem_Cl(), Zone::renum(), Frontiere::renum(), Reordonner_faces_periodiques::renum_som_perio(), reorder_vertices(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), reordonner_vdf(), Reorienter_triangles::Reorienter(), Reorienter_tetraedres::Reorienter(), search_connex_components_local(), Octree_Int::search_elements(), Octree_Int::search_elements_box(), tableau_trier_retirer_doublons(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Raccord_distant_homogene::trace_elem_distant(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_som_local(), traite_bord(), Convection_Diffusion_Temperature::transport_ibc(), tri_lexicographique_tableau(), Trianguler_H::trianguler(), Trianguler_fin::trianguler(), Trianguler::trianguler(), Tetraedriser_par_prisme::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser::trianguler(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_implementation_Q1::value_interpolation(), and Format_Post_Lata::write_inttab().
{
  assert(i >= 0 && i < nb_dim_);
// Si dimension_[0] == -1, c'est que c'est un vecteur distribue et que l'attribut size() est invalide.
// Il faut alors utiliser dimension_tot pour ce tableau.
  assert(dimensions_[i] >= 0);
  return dimensions_[i];
}
int IntTab::dimension_tot (int i) const [inline]
Returns the total dimensions of the multi-dimensionnal array, including
virtual items (used in parallel distributed arrays)
Definition at line 244 of file IntTab.h.
References dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by Octree_Double::build_elements(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), calculer_centres_gravite(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), construire_elems_sous_domaine(), Scatter::construire_espace_virtuel_traduction(), corriger(), Zone::creer_aretes(), Elem_geom_base::creer_faces_elem(), Zone_VDF::discretiser(), Zone_PolyMAC::discretiser(), echanger_tableau_aretes(), ecrit(), Zone::init_faces_virt_bord(), init_parts(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Sonde::initialiser(), lit(), Zone::nb_aretes_tot(), Zone::nb_elem_tot(), Zone_VF::nb_faces_tot(), Faces::nb_faces_tot(), parcourir_epaisseurs_elements(), Polygone::rebuild_index(), Polyedre::remplir_Nodes_glob(), Reordonner_faces_periodiques::renum_som_perio(), search_connex_components_local(), tri_lexicographique_tableau_indirect(), and Champ_implementation_P1::value_interpolation().
{
  assert(i >= 0 && i < nb_dim_);
  if (i == 0)
    return dimension_tot_0_;
  else
    return dimensions_[i];
}
int IntTab::duplique () const [virtual]
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
void IntTab::ecrit (Sortie & os) const [virtual]
ecriture des valeurs du tableau "raw" sans structure parallele
< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
Reimplemented from IntVect.
Definition at line 567 of file IntTab.cpp.
References dimension_tot(), dimensions_, finl, nb_dim_, and Sortie::put().
Referenced by Faces::ecrit(), Zone_VDF::printOn(), Zone_VF::printOn(), and Sous_zone_VF::printOn().
{
  os << nb_dim_ << finl;
  if (nb_dim_ > 0)
    os.put(dimensions_, nb_dim_, nb_dim_);
  ArrOfInt tmp(nb_dim_);
  for (int i = 0; i < nb_dim_; i++)
    tmp[i] = dimension_tot(i);
  os << tmp;
  IntVect::ecrit(os);
}
const Type_info * IntTab::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
const Type_info * IntTab::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
Referenced by operator=(), and ref().
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
void IntTab::jump (Entree & is) [virtual]
Reimplemented from IntVect.
Definition at line 579 of file IntTab.cpp.
References lit().
{
  IntTab::lit(is, 0 /* Do not resize&read the array */);
}
void IntTab::lit (Entree & is, int resize_and_read = 1) [virtual]
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
Reimplemented from IntVect.
Definition at line 588 of file IntTab.cpp.
References Cerr, dimension(), dimension_tot(), Process::exit(), finl, IntVect::get_md_vector(), nb_dim_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), resize(), ArrOfInt::size_array(), and IntVect::size_reelle_ok().
Referenced by jump(), Faces::lit(), Zone_VDF::readOn(), Zone_VF::readOn(), and Sous_zone_VF::readOn().
{
  ArrOfInt tmp;
  is >> tmp;
  int ok = 1;
  if (tmp.size_array() != nb_dim_)
    ok = 0;
  if (ok)
    {
      if (size_reelle_ok() && dimension(0) != tmp[0])
        ok = 0;
      for (int i = 1; i < nb_dim_; i++)
        if (dimension(i) != tmp[i])
          ok = 0;
    }
  is >> tmp;
  if (ok && tmp.size_array() != nb_dim_)
    ok = 0;
  if (ok)
    for (int i = 0; i < nb_dim_; i++)
      if (dimension_tot(i) != tmp[i])
        ok = 0;
// Autorisation ancien format des champs scalaire 183:
  if (tmp.size_array()==1 && nb_dim_==2 && dimension(1)==1 && dimension_tot(0) == tmp[0])
    ok = 1;
  if (resize_and_read)
    {
      if (size_array() == 0 && (!get_md_vector().non_nul()))
        {
          resize(tmp, NOCOPY_NOINIT);
        }
      else
        {
          if (!ok)
            {
// Si on cherche a relire un tableau de taille inconnue, le tableau doit
// etre reset() a l'entree. On n'aura pas la structure parallele du tableau !
              Cerr << "Error in IntTab::lit: array has wrong dimensions" << finl;
              exit();
            }
        }
    }
  IntVect::lit(is,resize_and_read);
}
int IntTab::nb_dim () const [inline]
Returns the number of dimensions of the array (>= 1)
Definition at line 254 of file IntTab.h.
References nb_dim_.
Referenced by Frontiere::add(), Matrice_Morse::dimensionner(), disp_it(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Debog_Pb::ecrire_gen(), Ch_front_input_P1::getTemplate(), Ch_front_input::getTemplate(), init_parts(), and Format_Post_Lata::write_inttab().
{
  return nb_dim_;
}
int & IntTab::operator() (int i) [inline]
idem operator[]
Reimplemented from ArrOfInt.
Definition at line 159 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return IntVect::operator[](i);
}
const int & IntTab::operator() (int i) const [inline]
Reimplemented from ArrOfInt.
Definition at line 166 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return IntVect::operator[](i);
}
int & IntTab::operator() (int i1, int i2) [inline]
Definition at line 173 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return IntVect::operator[](i1*dimensions_[1]+i2);
}
const int & IntTab::operator() (int i1, int i2) const [inline]
Definition at line 181 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return IntVect::operator[](i1*dimensions_[1]+i2);
}
int & IntTab::operator() (int i1, int i2, int i3) [inline]
Definition at line 189 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return IntVect::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
const int & IntTab::operator() (int i1, int i2, int i3) const [inline]
Definition at line 198 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return IntVect::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
int & IntTab::operator() (int i1, int i2, int i3, int i4) [inline]
Definition at line 207 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return IntVect::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
const int & IntTab::operator() (int i1, int i2, int i3, int i4) const [inline]
Definition at line 216 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return IntVect::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
int & IntTab::operator() (const ArrOfInt & indice)
Definition at line 512 of file IntTab.cpp.
References nb_dim_, and ArrOfInt::size_array().
Referenced by operator()().
{
  assert(indice.size_array() == nb_dim_);
#if MAXDIM_TAB != 4
#error Mettre a jour le code pour MAXDIM_TAB ici
#endif
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
int IntTab::operator() (const ArrOfInt & indice) const
Definition at line 530 of file IntTab.cpp.
References nb_dim_, operator()(), and ArrOfInt::size_array().
{
  assert(indice.size_array() == nb_dim_);
#if MAXDIM_TAB != 4
#error Mettre a jour le code pour MAXDIM_TAB ici
#endif
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
IntTab & IntTab::operator= (const IntTab & src)
copie la structure et les valeurs du tableau src
Restrictions et preconditions identiques a IntVect::operator=(const IntVect & v)
Reimplemented in IntTrav.
Definition at line 454 of file IntTab.cpp.
References copy().
Referenced by operator=().
{
  copy(src);
  return *this;
}
IntTab & IntTab::operator= (int x)
idem que ArrOfInt::operator=(int)
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 493 of file IntTab.cpp.
References operator=().
{
  IntVect::operator=(d);
  return *this;
}
IntTab& IntTab::operator= (const FIntTab &)
IntTab & IntTab::operator= (const IntVect & src)
copie la structure et les valeurs de src.
Attention: appel invalide si src est un type derive de Vect
(sinon quoi faire, un tableau unidimensionnel, ou une copie de la structure ?)
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 463 of file IntTab.cpp.
References CHECK_LINE_SIZE, IntVect::copy_(), dimension_tot_0_, dimensions_, IntVect::get_info(), info(), IntVect::line_size(), nb_dim_, ArrOfInt::size_array(), IntVect::size_reelle(), IntVect::size_reelle_ok(), and sz.
{
  assert(src.get_info() == IntVect::info());
  IntVect::copy_(src);
// Idem que dans ref(IntVect) pour le nombre de dimensions du tableau cree
  const int l = src.line_size();
  if (l == 1)
    {
      nb_dim_ = 1;
    }
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (src.size_reelle_ok())
    {
      int sz = src.size_reelle();
      dimensions_[0] = sz / l;
      assert(sz % l == 0);
    }
  else
    {
      dimensions_[0] = -1;
    }
  dimension_tot_0_ = size_array() / l;
  assert(CHECK_LINE_SIZE);
  return *this;
}
const int & IntTab::operator[] (int i) const [inline]
operateur [] retourne le ieme element du tableau
Reimplemented from ArrOfInt.
Definition at line 152 of file IntTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return IntVect::operator[](i);
}
int & IntTab::operator[] (int i) [inline]
operateur [] retourne le ieme element du tableau
Reimplemented from ArrOfInt.
Definition at line 145 of file IntTab.h.
References dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by operator()(), and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return IntVect::operator[](i);
}
Sortie & IntTab::printOn (Sortie & x) const [protected, virtual]
ecriture d'un tableau sequentiel
(idem que IntVect::printOn() on ne sait pas quoi faire de pertinent
pour un tableau distribue).
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 46 of file IntTab.cpp.
References ArrOfInt::addr(), Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, IntVect::get_md_vector(), IntVect::line_size(), nb_dim_, Process::nproc(), Sortie::put(), ArrOfInt::size_array(), and sz.
{
  assert(CHECK_LINE_SIZE);
  if (nproc() > 1 && get_md_vector().non_nul())
    {
      Cerr << "Error in IntTab::printOn: try to print a parallel vector" << finl;
      exit();
    }
  os << nb_dim_ << finl;
  assert(dimensions_[0] == dimension_tot_0_);
  if (nb_dim_ > 0)
    os.put(dimensions_, nb_dim_, nb_dim_);
  const int sz = size_array();
  os << sz << finl;
  const int l_size = line_size();
  const int *data = addr();
  if (sz > 0)
    os.put(data, sz, l_size);
  return os;
}
Entree & IntTab::readOn (Entree & is) [protected, virtual]
lecture d'un tableau sequentiel
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 70 of file IntTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, Entree::get(), IntVect::get_md_vector(), MAXDIM_TAB, nb_dim_, IntVect::set_line_size_(), and ArrOfInt::size_array().
{
  if (get_md_vector().non_nul())
    {
// Que veut-on faire si on lit dans un vecteur ayant deja une structure parallele ?
      Cerr << "Error in IntTab::readOn: vector has a parallel structure" << finl;
      exit();
    }
  is >> nb_dim_;
  if (nb_dim_ < 1 || nb_dim_ > MAXDIM_TAB)
    {
      Cerr << "Error in IntTab::readOn: wrong nb_dim_ = " << nb_dim_ << finl;
      exit();
    }
  is.get(dimensions_, nb_dim_);
  if (dimensions_[0] < 0)
    {
      Cerr << "Error in IntTab::readOn: wrong dimension(0) = " << dimensions_[0] << finl;
      exit();
    }
  int l_size = 1;
  for (int i = 1; i < nb_dim_; i++)
    {
      if (dimensions_[i] < 0)
        {
          Cerr << "Error in IntTab::readOn: wrong dimension(" << i << ") = " << dimensions_[i] << finl;
          exit();
        }
      l_size *= dimensions_[i];
    }
  dimension_tot_0_ = dimensions_[0];
  IntVect::readOn(is);
  set_line_size_(l_size);
  if (dimension_tot_0_ * l_size != size_array())
    {
      Cerr << "Error in IntTab::readOn: wrong size_array " << size_array()
           << ", expected " << dimension_tot_0_ * l_size << finl;
      exit();
    }
  assert(CHECK_LINE_SIZE);
  return is;
}
void IntTab::ref (const IntVect & v) [virtual]
fait pointer le tableau sur le vecteur v et en associant
la meme structure parallele.
Attention, si line_size du vecteur v est different de 1,
on cree un tableau bidimensionnel (on peut avoir un vecteur
de ce type si on copie un Tab dans un Vect puis on prend
une ref sur ce Vect).
Reimplemented from IntVect.
Definition at line 229 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, IntVect::get_info(), info(), IntVect::line_size(), nb_dim_, ArrOfInt::size_array(), IntVect::size_reelle(), IntVect::size_reelle_ok(), and sz.
Referenced by Op_Dift_VDF_var_Face_Axi::associer(), Op_Dift_VDF_Face_Axi::associer(), Op_Diff_VDF_var_Face_Axi::associer(), Op_Diff_VDF_Face_Axi::associer(), Op_Grad_VDF_Face::associer(), Op_Grad_P0_to_Face::associer(), Op_Grad_PolyMAC_Face::associer(), Evaluateur_VDF::associer_zones(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_PolyMAC::associer_zones(), Evaluateur_Source_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Remove_elem::creer_faces(), Tetraedriser_homogene_fin::decoupe(), Tetraedriser_homogene_compact::decoupe(), decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Zone_VF::discretiser(), Evaluateur_PolyMAC::Evaluateur_PolyMAC(), Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face(), Evaluateur_VDF::Evaluateur_VDF(), ExtrudeParoi::extrude(), Extruder_en3::extruder(), Extruder_en20::extruder(), Extruder::extruder(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), Zone_VDF::genere_aretes(), init_parts(), OrienteFacesBord::oriente_faces_bord(), Raffiner_anisotrope::Raffiner_anisotrope_(), Remove_elem::recreer_faces(), ref(), Remove_elem::Remove_elem_(), T_It_PolyMAC_Elem< _TYPE_ >::T_It_PolyMAC_Elem(), T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem(), T_It_VDF_Face< _TYPE_ >::T_It_VDF_Face(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Trianguler_H::trianguler(), Trianguler_fin::trianguler(), Trianguler::trianguler(), Tetraedriser_par_prisme::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
{
  assert(v.get_info() == IntVect::info());
  IntVect::ref(v);
  const int l = v.line_size();
// Attention:
// En prenant la ref, on est oblige de conserver l'attribut line_size
// du Vect (sinon echange_espace_virtuel ne fonctionnera pas car
// on n'aura pas le bon facteur multiplicatif des items geometriques)
// Si on voulait creer un tableau monodimensionnel avec line_size > 1,
// le tableau devient invalide car on n'a plus line_size = produit des
// dimensions > 1.
// On peut le faire a condition de laisser tomber le md_vector_ en
// faisant  tab.ref_array(v) au lieu de  tab.ref(v)
  if (l == 1)
    {
      nb_dim_ = 1;
    }
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (v.size_reelle_ok())
    {
      int sz = v.size_reelle();
      dimensions_[0] = sz / l;
    }
  else
    {
      dimensions_[0] = -1;
    }
  dimension_tot_0_ = size_array() / l;
  assert(CHECK_LINE_SIZE);
}
void IntTab::ref (const IntTab & src) [virtual]
fait pointer le tableau sur le tableau t
en recuperant la structure parallele. Attention,
on fige le tableau qui ne pourra plus etre resize
Definition at line 268 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, MAXDIM_TAB, nb_dim_, and ref().
{
  IntVect::ref(src);
  nb_dim_ = src.nb_dim_;
  for (int i = 0; i < MAXDIM_TAB; i++)
    dimensions_[i] = src.dimensions_[i];
  dimension_tot_0_ = src.dimension_tot_0_;
  assert(CHECK_LINE_SIZE);
}
void IntTab::ref_array (ArrOfInt & src, int start = 0, int sz = -1) [virtual]
identique a DoubleVect::ref_array()
(cree un tableau monodimensionnel sans structure parallele)
Attention, le tableau source et destination sont figes (resize interdit)
(voir ArrOfInt::
< pas sz qui peut valoir -1
Reimplemented from IntVect.
Definition at line 292 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, IntVect::get_md_vector(), nb_dim_, ArrOfInt::size_array(), and IntVect::size_reelle().
Referenced by init_parts(), ref_tab(), and Debog_Pb::verifier_partie().
{
  IntVect::ref_array(src, start, sz);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = size_array(); //!< pas sz qui peut valoir -1
  assert(CHECK_LINE_SIZE);
}
void IntTab::ref_data (int * ptr, int size) [virtual]
identique a DoubleVect::ref_data()
Reimplemented from IntVect.
Definition at line 279 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, IntVect::get_md_vector(), nb_dim_, ArrOfInt::size_array(), and IntVect::size_reelle().
{
  IntVect::ref_data(ptr, new_size);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = new_size;
  assert(CHECK_LINE_SIZE);
}
void IntTab::ref_tab (IntTab & t, int start_line = 0, int nb_lines = -1) [virtual]
fait pointer le tableau sur une sous-partie du tableau t
definie par la valeur du premier indice et ne nombre de "lignes" du tableau
a recuperer (une ligne = toutes les valeurs tab(i,j,k,...) pour un i donne).
Le nombre de dimensions du tableau est le meme que pour t,
les dimension(i) pour i>=1 sont les memes et dimension(0) = nb_lines.
Definition at line 306 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, IntVect::get_md_vector(), IntVect::line_size(), MAXDIM_TAB, nb_dim_, ref_array(), IntVect::set_line_size_(), ArrOfInt::size_array(), and IntVect::size_reelle().
{
  if (nb_lines < 0)
    nb_lines = t.dimension_tot_0_ - start_line;
  assert(start_line >= 0 && nb_lines >= 0 && start_line + nb_lines <= t.dimension_tot_0_);
  const int l_size = t.line_size();
  IntVect::ref_array(t, start_line * l_size, nb_lines * l_size);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  set_line_size_(l_size);
  nb_dim_ = t.nb_dim_;
  dimension_tot_0_ = nb_lines;
  dimensions_[0] = nb_lines;
  for (int i = 1; i < MAXDIM_TAB; i++)
    dimensions_[i] = t.dimensions_[i];
  assert(CHECK_LINE_SIZE);
}
void IntTab::reset () [virtual]
met le tableau dans l'etat obtenu par le constructeur par defaut
voir IntVect::reset()
Reimplemented from IntVect.
Definition at line 325 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by Champ_Generique_Extraction::completer(), SSOR::prepare_(), Remove_elem::recreer_faces(), Traduction_Indice_Global_Local::reset(), Octree_Int::reset(), Joint_Items::reset(), and Faces_builder::reset().
{
  nb_dim_ = 1;
  dimensions_[0] = 0;
  dimension_tot_0_ = 0;
  IntVect::reset();
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize (int n, Array_base::Resize_Options opt = COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un IntTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
Reimplemented from IntVect.
Definition at line 353 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, nb_dim_, IntVect::resize_vect_(), and IntVect::set_line_size_().
Referenced by Frontiere::add(), BlocData::add_bloc(), add_sommets_communs(), Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Polyedre::ajouter_elements(), ajouter_joint(), Faces_builder::ajouter_une_face(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Octree_Int::build(), build_cells(), Refine_Mesh::build_edges(), build_edges(), Octree_Double::build_elements(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Octree_Double::build_nodes(), Matrice_Bloc::build_stencil(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Scatter::calculer_renum_items_communs(), Quadrangle_VEF::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Op_Dift_Stab_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Champ_Generique_Extraction::completer(), Champ_front_calc_interne::completer(), Zones::comprimer(), compute_global_connex_components(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Zone::construire_elem_virt_pe_num(), construire_elems_sous_domaine(), Zone_VF::construire_face_virt_pe_num(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), Zone_VF::construire_num_fac_loc(), Matrice_Morse::construire_sous_bloc(), convert_domain_to_Domaine(), corriger_type(), Zone::creer_aretes(), Zone_VDF::creer_elements_fictifs(), Remove_elem::creer_faces(), Faces_builder::creer_faces_reeles(), Tetraedriser_homogene_fin::decoupe(), Tetraedriser_homogene_compact::decoupe(), decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Aretes::dimensionner(), Op_Div_PolyMAC::dimensionner(), Faces::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Zone_VF::discretiser(), Sous_zone_VF::discretiser(), Ensemble_Lagrange_base::Ensemble_Lagrange_base(), Matrix_tools::extend_matrix_stencil(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt(), Extruder::extruder_dvt_hexa(), ExtrudeBord::extruder_hexa_old(), Zone_CoviMAC::fgrad(), fill_tab_2(), fill_tab_2_new(), fill_tab_3(), find_joint_faces(), Matrice_Nulle::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Diagonale::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Bloc::get_stencil(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Tetraedre::get_tab_aretes_sommets_locaux(), Triangle::get_tab_faces_sommets_locaux(), Tetraedre::get_tab_faces_sommets_locaux(), Segment::get_tab_faces_sommets_locaux(), Rectangle::get_tab_faces_sommets_locaux(), Quadrangle_VEF::get_tab_faces_sommets_locaux(), Prisme::get_tab_faces_sommets_locaux(), Polygone::get_tab_faces_sommets_locaux(), Polyedre::get_tab_faces_sommets_locaux(), Point::get_tab_faces_sommets_locaux(), Hexaedre_VEF::get_tab_faces_sommets_locaux(), Hexaedre::get_tab_faces_sommets_locaux(), Hexa_VEF::Hexa_VEF(), Echange_contact_Correlation_VEF::init(), Sonde::init_bords(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Champ_P0_PolyMAC::init_cl(), Champ_Face_PolyMAC::init_cl(), Zone_CoviMAC::init_equiv(), Zone::init_faces_virt_bord(), Champ_P0_CoviMAC::init_fcl(), Champ_Face_CoviMAC::init_fcl(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Op_Diff_CoviMAC_base::init_op_ext(), init_parts(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Zone_CoviMAC::init_stencils(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Champ_Face_CoviMAC::init_ve2(), Zone_PolyMAC::init_we(), Zone_PolyMAC::init_we_2d(), Zone_PolyMAC::init_we_3d(), Raccord_distant_homogene::initialise(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Traduction_Indice_Global_Local::initialiser(), Sonde_Int::initialiser(), Raffiner_isotrope_parallele::interpreter(), VerifierCoin::interpreter_(), Lire_Tgrid::interpreter_(), Lire_Ideas::interpreter_(), Extraire_plan::interpreter_(), Extraire_domaine::interpreter_(), IntTrav::IntTrav(), Pave::lire_front(), Pave::lire_Noeuds(), lit(), Faces::lit(), Zones::merge(), Zone_PolyMAC::orthocentrer(), SSOR::prepare_(), Quadri_VEF::Quadri_VEF(), Faces::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Remove_elem::recreer_faces(), Remove_elem::Remove_elem_(), Zone_VF::remplir_face_numero_bord(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Scatter::reordonner_faces_de_joint(), resize_tab(), Tetra_VEF::Tetra_VEF(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Tri_VEF::Tri_VEF(), Trianguler_fin::trianguler(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), and Champ_implementation_Q1::value_interpolation().
{
  assert(n >= 0);
  set_line_size_(1);
  IntVect::resize_vect_(n, opt);
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = n;
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize (const ArrOfInt & tailles, Array_base::Resize_Options opt = COPY_INIT)
redimensionne le tableau (nb_dim_ sera egal a tailles.size_array()
et dimension(i) a tailles[i].
Definition at line 423 of file IntTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, MAXDIM_TAB, nb_dim_, IntVect::resize_vect_(), IntVect::set_line_size_(), and ArrOfInt::size_array().
{
  nb_dim_ = tailles.size_array();
  if (nb_dim_ <= 0 || nb_dim_ > MAXDIM_TAB)
    {
      Cerr << "Internal error in IntTab::resize(const ArrOfInt & tailles, ...) \n"
           << " wrong dimensions number " << nb_dim_ << finl;
      exit();
    }
  int l_size = 1;
  for (int i = 0; i < nb_dim_; i++)
    {
      const int n = tailles[i];
      dimensions_[i] = n;
      if (i > 0)
        l_size *= n;
      if (n < 0)
        {
          Cerr << "Internal error in IntTab::resize(const ArrOfInt & tailles, ...) \n"
               << " wrong dimensions: " << tailles << finl;
          exit();
        }
    }
  dimension_tot_0_ = dimensions_[0];
  set_line_size_(l_size);
  resize_vect_(dimensions_[0] * l_size, opt);
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize (int n1, int n2, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 363 of file IntTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, nb_dim_, IntVect::resize_vect_(), and IntVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0);
  set_line_size_(n2);
  int new_size = n * n2;
  if (new_size<0)
    {
      Cerr << "n1*n2 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << finl;
      exit();
    }
  IntVect::resize_vect_(new_size, opt);
  nb_dim_ = 2;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 400 of file IntTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, nb_dim_, IntVect::resize_vect_(), and IntVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
  set_line_size_(n2 * n3 * n4);
  int new_size = n * n2 * n3 * n4;
  if (new_size<0)
    {
      Cerr << "n1*n2*n3*n4 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << " and n3=" << n3 << " and n4=" << n4 << finl;
      exit();
    }
  IntVect::resize_vect_(new_size, opt);
  nb_dim_ = 4;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  dimensions_[3] = n4;
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize (int n1, int n2, int n3, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 381 of file IntTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, nb_dim_, IntVect::resize_vect_(), and IntVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0);
  set_line_size_(n2 * n3);
  int new_size = n * n2 * n3;
  if (new_size<0)
    {
      Cerr << "n1*n2*n3 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << " and n3=" << n3 << finl;
      exit();
    }
  IntVect::resize_vect_(new_size, opt);
  nb_dim_ = 3;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize_dim0 (int n, Array_base::Resize_Options opt = COPY_INIT)
change la dimension[0] du tableau en conservant les autres.
Definition at line 344 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, IntVect::line_size(), IntVect::resize_vect_(), and ArrOfInt::size_array().
Referenced by Octree_Int::build_octree_recursively(), find_joint_faces(), and resize_tab_lines().
{
  assert(n >= 0);
  assert(dimension_tot_0_ * line_size() == size_array());
  IntVect::resize_vect_(n * line_size(), opt);
  dimensions_[0] = dimension_tot_0_ = n;
  assert(CHECK_LINE_SIZE);
}
void IntTab::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle qui force le tableau a changer de taille.
Change aussi nb_dim_ a 1. Equivalent a IntTab::resize(n, opt)
Reimplemented from IntVect.
Definition at line 336 of file IntTab.cpp.
References CHECK_LINE_SIZE, and resize().
{
  resize(n, opt);
  assert(CHECK_LINE_SIZE);
}
const IntTab & IntTab::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
IntTab & IntTab::self_cast (Objet_U & r) [static]
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
void IntTab::set_md_vector (const MD_Vector & md_vector) [virtual]
associe le md_vector au vecteur (voir IntVect::set_md_vector())
dimension(0) sera initialise a md_vector...get_nb_items_reels().
Reimplemented from IntVect.
Definition at line 553 of file IntTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, MD_Vector_base::get_nb_items_reels(), MD_Vector::non_nul(), and MD_Vector::valeur().
Referenced by Scatter::construire_structures_paralleles(), Zone::creer_aretes(), init_parts(), Scatter::init_sequential_domain(), IntTrav::IntTrav(), SSOR::prepare_(), Champ_Fonc_MED::readOn(), and Scatter::uninit_sequential_domain().
{
  int dim0 = dimension_tot_0_;
  if (md_vector.non_nul())
    {
// renvoie -1 si l'appel et invalide:
      dim0 = md_vector.valeur().get_nb_items_reels();
    }
  dimensions_[0] = dim0;
  assert(CHECK_LINE_SIZE);
// a appeler meme pour un md_vector nul (pour remettre size_reelle_):
  IntVect::set_md_vector(md_vector);
}
unsigned IntTab::taille_memoire () const [virtual]
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 31 of file IntTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
Member Data Documentation
int IntTab::dimension_tot_0_ [private]
Definition at line 127 of file IntTab.h.
Referenced by append_line(), copy(), dimension_tot(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), resize(), resize_dim0(), and set_md_vector().
int IntTab::dimensions_[MAXDIM_TAB] [private]
Definition at line 122 of file IntTab.h.
Referenced by append_line(), copy(), dimension(), dimension_tot(), ecrit(), IntTab(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), resize(), resize_dim0(), and set_md_vector().
const Type_info IntTab::info_obj [static]
Reimplemented from IntVect.
Reimplemented in IntTrav.
Definition at line 51 of file IntTab.h.
int IntTab::nb_dim_ [private]
Definition at line 119 of file IntTab.h.
Referenced by copy(), dimension(), dimension_tot(), ecrit(), lit(), nb_dim(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), and resize().
The documentation for this class was generated from the following files:
src/Kernel/Math/IntTab.h
src/Kernel/Math/IntTab.cpp