TRUST: Deriv_Modele_turbulence_scal_base Class Reference
Deriv_Modele_turbulence_scal_base Class Reference
class Modele_turbulence_scal
Cette classe represente n'importe quelle classe
derivee de Modele_turbulence_scal_base
#include <Modele_turbulence_scal.h>
Public Member Functions
~Deriv_Modele_turbulence_scal_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Modele_turbulence_scal_base ()
Deriv_Modele_turbulence_scal_base (const Deriv_Modele_turbulence_scal_base &)
const Modele_turbulence_scal_base & valeur () const
Modele_turbulence_scal_base & valeur ()
const Modele_turbulence_scal_base * operator-> () const
Modele_turbulence_scal_base * operator-> ()
const
Deriv_Modele_turbulence_scal_base & operator= (const Modele_turbulence_scal_base &)
const
Deriv_Modele_turbulence_scal_base & operator= (const Deriv_Modele_turbulence_scal_base &)
operator const Modele_turbulence_scal_base & () const
operator Modele_turbulence_scal_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Modele_turbulence_scal_base & self_cast (Objet_U &)
static const
Deriv_Modele_turbulence_scal_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Modele_turbulence_scal_base * pointeur_
Detailed Description
class Modele_turbulence_scal
Cette classe represente n'importe quelle classe
derivee de Modele_turbulence_scal_base
Definition at line 34 of file Modele_turbulence_scal.h.
Constructor & Destructor Documentation
Deriv_Modele_turbulence_scal_base::~Deriv_Modele_turbulence_scal_base ()
Definition at line 27 of file Modele_turbulence_scal.cpp.
Deriv_Modele_turbulence_scal_base::Deriv_Modele_turbulence_scal_base ()
Definition at line 27 of file Modele_turbulence_scal.cpp.
Deriv_Modele_turbulence_scal_base::Deriv_Modele_turbulence_scal_base (const Deriv_Modele_turbulence_scal_base & t)
Definition at line 27 of file Modele_turbulence_scal.cpp.
Member Function Documentation
Objet_U * Deriv_Modele_turbulence_scal_base::cree_instance () [static]
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
int Deriv_Modele_turbulence_scal_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Type_info * Deriv_Modele_turbulence_scal_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Type_info & Deriv_Modele_turbulence_scal_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Type_info * Deriv_Modele_turbulence_scal_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
Deriv_Modele_turbulence_scal_base::operator const Modele_turbulence_scal_base & () const
Definition at line 27 of file Modele_turbulence_scal.cpp.
Deriv_Modele_turbulence_scal_base::operator Modele_turbulence_scal_base & ()
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Modele_turbulence_scal_base * Deriv_Modele_turbulence_scal_base::operator-> () const [inline]
Definition at line 34 of file Modele_turbulence_scal.h.
: public MorEqn, public DERIV(Modele_turbulence_scal_base)
Modele_turbulence_scal_base * Deriv_Modele_turbulence_scal_base::operator-> () [inline]
Definition at line 34 of file Modele_turbulence_scal.h.
: public MorEqn, public DERIV(Modele_turbulence_scal_base)
const Deriv_Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::operator= (const Deriv_Modele_turbulence_scal_base & t)
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Deriv_Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::operator= (const Modele_turbulence_scal_base & t)
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
Sortie & Deriv_Modele_turbulence_scal_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
Entree & Deriv_Modele_turbulence_scal_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Deriv_Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
Deriv_Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
void Deriv_Modele_turbulence_scal_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 27 of file Modele_turbulence_scal.cpp.
unsigned Deriv_Modele_turbulence_scal_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Modele_turbulence_scal.
Definition at line 27 of file Modele_turbulence_scal.cpp.
const Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::valeur () const [inline]
Definition at line 34 of file Modele_turbulence_scal.h.
Referenced by Modele_turbulence_scal::completer(), Modele_turbulence_scal::conductivite_turbulente(), Modele_turbulence_scal::discretiser(), Modele_turbulence_scal::imprimer(), Modele_turbulence_scal::loi_paroi(), Modele_turbulence_scal::loi_paroi_non_nulle(), Modele_turbulence_scal::mettre_a_jour(), Modele_turbulence_scal::preparer_calcul(), Modele_turbulence_scal::printOn(), Modele_turbulence_scal::readOn(), Modele_turbulence_scal::reprendre(), and Modele_turbulence_scal::sauvegarder().
: public MorEqn, public DERIV(Modele_turbulence_scal_base)
Modele_turbulence_scal_base & Deriv_Modele_turbulence_scal_base::valeur () [inline]
Definition at line 34 of file Modele_turbulence_scal.h.
: public MorEqn, public DERIV(Modele_turbulence_scal_base)
Member Data Documentation
const Type_info Deriv_Modele_turbulence_scal_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Modele_turbulence_scal.
Definition at line 34 of file Modele_turbulence_scal.h.
Modele_turbulence_scal_base* Deriv_Modele_turbulence_scal_base::pointeur_ [private]
Definition at line 34 of file Modele_turbulence_scal.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal.h
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal.cpp