TRUST: Traitement_particulier_NS_Pression_VEF Class Reference
Traitement_particulier_NS_Pression_VEF Class Reference
classe Traitement_particulier_NS_Pression_VEF
Cette classe permet de faire les traitements particuliers
pour les calculs de la pression
#include <Traitement_particulier_NS_Pression_VEF.h>
Public Member Functions
~Traitement_particulier_NS_Pression_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Traitement_particulier_NS_Pression_VEF ()
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
void post_traitement_particulier (void) override
Entree & lire (Entree &) override
Public Member Functions inherited from Traitement_particulier_NS_Pression
Traitement_particulier_NS_Pression ()
~Traitement_particulier_NS_Pression () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &) override
void associer_eqn (const Equation_base &) override
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
void sauver_stat (void) const override
void reprendre_stat (void) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_Pression_VEF & self_cast (Objet_U &)
static const Traitement_particulier_NS_Pression_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_Pression
static const Type_info * info ()
static Traitement_particulier_NS_Pression & self_cast (Objet_U &)
static const Traitement_particulier_NS_Pression & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_Pression
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Traitement_particulier_NS_Pression
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Champ_P1_isoP1Bulle ch_p
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Private Member Functions
void post_traitement_particulier_calcul_pression ()
Private Attributes
int c_pression
Detailed Description
classe Traitement_particulier_NS_Pression_VEF
Cette classe permet de faire les traitements particuliers
pour les calculs de la pression
Definition at line 38 of file Traitement_particulier_NS_Pression_VEF.h.
Constructor & Destructor Documentation
~Traitement_particulier_NS_Pression_VEF()
Traitement_particulier_NS_Pression_VEF::~Traitement_particulier_NS_Pression_VEF ()
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
Traitement_particulier_NS_Pression_VEF()
Traitement_particulier_NS_Pression_VEF::Traitement_particulier_NS_Pression_VEF ()
Definition at line 22 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  /*
    Noms& nom=champs_compris_.liste_noms_compris();
    nom.dimensionner(1);
    nom[0]="Pression_porosite";
  */
}
Member Function Documentation
a_pour_Champ_Fonc()
int Traitement_particulier_NS_Pression_VEF::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const inline
Definition at line 75 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  if (mot == "Pression_porosite")
    {
      ch_ref = ch_p;
      return 1 ;
    }
  return 0 ;
}
References ch_p.
comprend_champ()
int Traitement_particulier_NS_Pression_VEF::comprend_champ (const Motcle & mot) const inline
Definition at line 69 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  if (mot == "Pression_porosite") return 1 ;
  return 0 ;
}
cree_instance()
Objet_U * Traitement_particulier_NS_Pression_VEF::cree_instance () static
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
duplique()
int Traitement_particulier_NS_Pression_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
get_info()
const Type_info * Traitement_particulier_NS_Pression_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
info()
const Type_info * Traitement_particulier_NS_Pression_VEF::info () static
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
lire()
Entree & Traitement_particulier_NS_Pression_VEF::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 86 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motbidon, motlu;
  c_pression = 0 ;
  is >> motbidon ;
  Motcles les_mots(1);
  {
    les_mots[0] = "Pression_porosite";
  }
  if (motbidon == accouverte)
    {
// is >> motlu;
      while(motlu != accfermee)
        {
          is >> motlu;
          int rang=les_mots.search(motlu);
          switch(rang)
            {
            case 0 :
              {
                Cerr << " Lire Pression_porosite " << finl;
                const Zone_dis_base& zdis=mon_equation->inconnue().zone_dis_base();
                const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdis);
// const Probleme_base& pb = mon_equation->probleme();
                const int nb_elem = zone_VEF.nb_elem() ;
                ch_p.associer_zone_dis_base(zdis);
                ch_p.nommer("Pression_porosite");
                ch_p.fixer_nb_comp(1);
                ch_p.fixer_nb_valeurs_nodales(nb_elem);
                ch_p.fixer_unite("Pa.m3/kg");
                c_pression = 1 ;
                champs_compris_.ajoute_champ(ch_p);
                break ;
              }
            default :
              {
                if (motlu == accfermee)
                  {
                    break ;
                  }
                else
                  {
                    Cerr << "Erreur dans la lecture de Traitement_particulier_Brech_VEF" << finl;
                    Cerr << "Les mots cles possibles sont : calcul_flux ou Richardson " << finl;
                    Cerr << "Vous avez lu :" << motlu << finl;
                    exit();
                    break;
                  }
              }
            }
        }
      is >> motlu;
      if (motlu != accfermee)
        {
          Cerr << "Erreur dans la lecture de Traitement_particulier_NS_Brech_VEF 1 ";
          Cerr << "On attendait une } et pas " << motlu << finl;
          exit();
        }
    }
  return is;
}
References Champs_compris::ajoute_champ(), Champ_P1_isoP1Bulle::associer_zone_dis_base(), c_pression, Cerr, ch_p, Traitement_particulier_NS_base::champs_compris_, Process::exit(), finl, Field_base::fixer_nb_comp(), Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Motcles::search(), and Champ_Inc::zone_dis_base().
post_traitement_particulier()
void Traitement_particulier_NS_Pression_VEF::post_traitement_particulier (void) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 159 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  if (c_pression == 1 ) post_traitement_particulier_calcul_pression() ;
}
References c_pression, and post_traitement_particulier_calcul_pression().
post_traitement_particulier_calcul_pression()
void Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression () private
< car div =-B Correction du second membre d'apres les conditions aux limites :
Definition at line 166 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  const Zone_VEF& zvef=ref_cast(Zone_VEF, mon_equation->zone_dis().valeur());
  const DoubleVect& porosite_face = zvef.porosite_face();
  int i,comp;
  int nb_face = zvef.nb_faces();
  Operateur_Div divergence = mon_equation->operateur_divergence();
  Operateur_Grad gradient = mon_equation->operateur_gradient();
  SolveurSys solveur_pression_ = mon_equation->solveur_pression();
  DoubleTab& pression=mon_equation->pression().valeurs();
  DoubleTab& vitesse=mon_equation->vitesse().valeurs();
  DoubleTab gradP(vitesse);
  DoubleTab inc_pre(pression);
  DoubleTab secmem(pression);
  DoubleTab grad_temp(vitesse);
  inc_pre  = 0. ;
  secmem = 0. ;
  gradP = 0. ;
  grad_temp = 0. ;
  gradient.calculer(mon_equation->pression().valeurs(),gradP);
// on veut BM-1Bt(psi*Pression)
  mon_equation->solv_masse().appliquer(gradP);
  for(i=0; i<nb_face; i++)
    {
      for (comp=0; comp<dimension; comp++)
        grad_temp(i,comp) = gradP(i,comp)/porosite_face(i);
    }
// mon_equation->solv_masse().appliquer(grad_temp);
  divergence.calculer(grad_temp, secmem);
  secmem *= -1; //!< car div =-B Correction du second membre d'apres les conditions aux limites :
//
  mon_equation->assembleur_pression().valeur().modifier_secmem(secmem);
// solveur_pression_.resoudre_systeme(mon_equation->matrice_pression().valeur(),secmem, inc_pre,mon_equation->pression().valeur());
  solveur_pression_.resoudre_systeme(mon_equation->matrice_pression().valeur(),secmem, inc_pre);
  DoubleVect& la_pression_porosite = ch_p.valeurs();
  la_pression_porosite = pression;
// Cerr << " la_pression_porosite = pression " << la_pression_porosite  << finl;
// Cerr << " inc_pre " << inc_pre << finl;
  la_pression_porosite += inc_pre;
// Cerr << "la_pression " << mon_equation->pression().valeurs() << finl;
// Cerr << "ch_p.valeurs() " << ch_p.valeurs() << finl;
// const Zone_VEF& zvef=ref_cast(Zone_VEF, mon_equation->zone_dis().valeur());
// const DoubleVect& porosite_face = zvef.porosite_face();
// int i,comp;
// int nb_face = zvef.nb_faces();
// Champ_Inc la_pression = mon_equation->pression();
// Champ_Inc la_vitesse =  mon_equation->vitesse();
// Operateur_Div divergence = mon_equation->operateur_divergence();
// Operateur_Grad gradient = mon_equation->operateur_gradient();
// SolveurSys solveur_pression_ = mon_equation->solveur_pression();
// DoubleTab& pression=la_pression.valeurs();
// DoubleTrav gradP(la_vitesse.valeurs());
// DoubleTrav inc_pre(pression);
// //  DoubleVect& inc_pre = ch_p.valeurs();
// //   inc_pre  = 0. ;
// DoubleTrav secmem(pression);
// gradient.calculer(la_pression,gradP);
// // Cerr << "gradP " << gradP << finl;
// //on veut BM-1Bt(psi*Pression)
// mon_equation->solv_masse().appliquer(gradP);
// DoubleTrav grad_temp(la_vitesse.valeurs());
// for(i=0; i<nb_face; i++)
// {
// for (comp=0; comp<dimension; comp++)
// grad_temp(i,comp) = gradP(i,comp)/porosite_face(i);
// }
// divergence.calculer(grad_temp, secmem);
// secmem *= -1; // car div =-B
// solveur_pression_.resoudre_systeme(mon_equation->matrice_pression().valeur(),secmem, inc_pre, la_pression.valeur());
// // Cerr << "la pression " << pression << finl;
// //Cerr << "inc_pre " << inc_pre << finl;
// DoubleVect& la_pression_porosite = ch_p.valeurs();
// la_pression_porosite = inc_pre ;
// Cerr << "la_pression_porosite" << la_pression_porosite << finl;
// Cerr << "ch_p.valeurs() " << ch_p.valeurs() << finl;
}
References Solveur_Masse::appliquer(), Navier_Stokes_std::assembleur_pression(), Operateur_Div::calculer(), Operateur_Grad::calculer(), ch_p, Objet_U::dimension, Navier_Stokes_std::matrice_pression(), Assembleur_base::modifier_secmem(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Zone_VF::porosite_face(), Navier_Stokes_std::pression(), ref_cast, SolveurSys::resoudre_systeme(), Equation_base::solv_masse(), Navier_Stokes_std::solveur_pression(), Deriv_Assembleur_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_Matrice_Base::valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Navier_Stokes_std::vitesse(), and Equation_base::zone_dis().
Referenced by post_traitement_particulier().
printOn()
Sortie & Traitement_particulier_NS_Pression_VEF::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 44 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_Pression_VEF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 64 of file Traitement_particulier_NS_Pression_VEF.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_NS_Pression_VEF & Traitement_particulier_NS_Pression_VEF::self_cast (const Objet_U & r) static
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_Pression_VEF & Traitement_particulier_NS_Pression_VEF::self_cast (Objet_U & r) static
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_Pression_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Traitement_particulier_NS_Pression_VEF.cpp.
Member Data Documentation
c_pression
int Traitement_particulier_NS_Pression_VEF::c_pression private
Definition at line 61 of file Traitement_particulier_NS_Pression_VEF.h.
Referenced by lire(), and post_traitement_particulier().
ch_p
Champ_P1_isoP1Bulle Traitement_particulier_NS_Pression_VEF::ch_p protected
Definition at line 55 of file Traitement_particulier_NS_Pression_VEF.h.
Referenced by a_pour_Champ_Fonc(), lire(), and post_traitement_particulier_calcul_pression().
info_obj
const Type_info Traitement_particulier_NS_Pression_VEF::info_obj static
Definition at line 40 of file Traitement_particulier_NS_Pression_VEF.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Traitement_particulier_NS_Pression_VEF.h
src/P1NCP1B/Traitement_particulier_NS_Pression_VEF.cpp