TRUST: Op_Conv_AmontNew_VEF_Face Class Reference
Op_Conv_AmontNew_VEF_Face Class Reference
class Op_Conv_AmontNew_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type AmontNew
Les methodes pour l'implicite sont codees.
#include <Op_Conv_AmontNew_VEF_Face.h>
Public Member Functions
Op_Conv_AmontNew_VEF_Face ()
~Op_Conv_AmontNew_VEF_Face ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_AmontNew_VEF_Face & self_cast (Objet_U &)
static const
Op_Conv_AmontNew_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Op_Conv_AmontNew_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type AmontNew
Les methodes pour l'implicite sont codees.
Definition at line 48 of file Op_Conv_AmontNew_VEF_Face.h.
Constructor & Destructor Documentation
Op_Conv_AmontNew_VEF_Face::Op_Conv_AmontNew_VEF_Face ()
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
Op_Conv_AmontNew_VEF_Face::~Op_Conv_AmontNew_VEF_Face ()
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
Member Function Documentation
DoubleTab & Op_Conv_AmontNew_VEF_Face::ajouter (const DoubleTab & transporte, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Definition at line 83 of file Op_Conv_AmontNew_VEF_Face.cpp.
References Elem_VEF::calcul_vc(), Cerr, compteur, convbis(), Objet_U::dimension, DoubleTab::dimension(), Zone_VF::elem_faces(), Process::exit(), f1, f2, Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VEF::facette_normales(), finl, Op_Conv_VEF_base::fluent, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Op_VEF_Face::modifier_flux(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), Elem_VEF::nb_facette(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Elem_geom::nb_som_face(), Zone_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Objet_U::que_suis_je(), Zone_VEF::rang_elem_non_std(), ref_cast, DoubleTab::resize(), Zone::sommet_elem(), sub_type, Zone::type_elem(), Zone_VEF::type_elem(), type_elem(), Zone_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Deriv_Elem_VEF_base::valeur(), Deriv_Elem_geom_base::valeur(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Ref_Zone_Cl_VEF::valeur(), Champ_base::valeur_a_sommet_compo(), Op_Conv_VEF_base::vitesse(), Op_Conv_VEF_base::vitesse_, Zone_VF::volumes(), and Zone_dis_base::zone().
{
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleTab& facette_normales = zone_VEF.facette_normales();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const Zone& zone = zone_VEF.zone();
  const Elem_VEF& type_elem=zone_VEF.type_elem();
  const int nfa7 = type_elem.nb_facette();
  int nb_faces_tot=zone_VEF.nb_faces_tot();
  int nb_elem_tot = zone_VEF.nb_elem_tot();
  const DoubleVect& volumes=zone_VEF.volumes();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const DoubleTab& normales_facettes_Cl = zone_Cl_VEF.normales_facettes_Cl();
  int ncomp_ch_transporte;
  if (transporte.nb_dim() == 1)
    ncomp_ch_transporte=1;
  else
    ncomp_ch_transporte= transporte.dimension(1);
  DoubleTab TbarK(nb_elem_tot, ncomp_ch_transporte);
  DoubleTab Ttilde1(nb_faces_tot, ncomp_ch_transporte);
  DoubleTab Ttilde2(nb_faces_tot, ncomp_ch_transporte);
  int f, j=0;
//
// calcul des Ttilde :
//
  for(f=0; f<nb_faces_tot; f++)
    {
      int elem=face_voisins(f,0);
      if(ncomp_ch_transporte>1)
        for(j=0; j<ncomp_ch_transporte; j++)
          TbarK(elem, j)+=transporte(f, j);
      else
        TbarK(elem, 0)+=transporte(f);
      elem=face_voisins(f,1);
      if(elem>-1)
        {
          if(ncomp_ch_transporte>1)
            for(j=0; j<ncomp_ch_transporte; j++)
              TbarK(elem, j)+=transporte(f, j);
          else
            TbarK(elem, 0)+=transporte(f);
        }
    }
  double x=1./(dimension+1);
  for(f=0; f<nb_faces_tot; f++)
    {
      int elem=face_voisins(f,0);
      if(ncomp_ch_transporte>1)
        for(j=0; j<ncomp_ch_transporte; j++)
          Ttilde1(f, j)=x*(TbarK(elem, j)-transporte(f, j));
      else
        Ttilde1(f, j)=x*(TbarK(elem, j)-transporte(f));
      elem=face_voisins(f,1);
      if(elem>-1)
        if(ncomp_ch_transporte>1)
          for(j=0; j<ncomp_ch_transporte; j++)
            Ttilde2(f, j)+=x*(TbarK(elem, j)-transporte(f, j));
        else
          Ttilde2(f, j)+=x*(TbarK(elem, j)-transporte(f));
      else if(ncomp_ch_transporte>1)
        Ttilde2(f, j)=transporte(f, j);
      else
        Ttilde2(f, j)=transporte(f);
    }
// On recree les chocs ...
  for(f=0; f<nb_faces_tot; f++)
    {
      int elem2=face_voisins(f,1);
      if(elem2>-1)
        {
          int elem1=face_voisins(f,0);
          double alpha=volumes(elem1)/(volumes(elem1)+volumes(elem2));
          for(j=0; j<ncomp_ch_transporte; j++)
            {
              double epsilon;
              double Tfj;
              {
                if(ncomp_ch_transporte>1)
                  Tfj=transporte(f, j);
                else
                  Tfj=transporte(f);
                if( ( (Tfj<Ttilde1(f, j)) &&
                      (Tfj<Ttilde2(f, j)) ) ||
                    ( (Tfj>Ttilde1(f, j)) &&
                      (Tfj>Ttilde2(f, j)) ) )
                  {
                    Ttilde1(f, j)=Ttilde2(f, j)=Tfj;
                  }
                else
                  {
                    if(Ttilde1(f, j)<Ttilde2(f, j))
                      {
                        epsilon=(Tfj-alpha*Ttilde1(f, j)+
                                 (1-alpha)*Ttilde2(f, j))/alpha;
                        Ttilde2(f, j)-=epsilon;
                        Ttilde1(f, j)=(Tfj-(1-alpha)*Ttilde2(f, j))
                                      /alpha;
                      }
                    else
                      {
                        epsilon=(Tfj-(1-alpha)*Ttilde2(f, j)+
                                 alpha*Ttilde1(f, j))/(1-alpha);
                        Ttilde1(f, j)-=epsilon;
                        Ttilde2(f, j)=(Tfj-alpha*Ttilde1(f, j))
                                      /(1-alpha);
                      }
                    Cerr << "!!" << finl;
                  }
              }
            }
        }
      else if(ncomp_ch_transporte>1)
        for(j=0; j<ncomp_ch_transporte; j++)
          Ttilde1(f, j)=Ttilde2(f, j)=transporte(f, j);
      else
        Ttilde1(f, 0)=Ttilde2(f, 0)=transporte(f);
    }
// pas d'inversion de pente :
  for(int elem=0; elem<nb_elem_tot; elem++)
    {
      for(int f1=0; f1<dimension; f1++)
        {
          int face1=elem_faces(elem,f1);
          int i1=0;
          if(face_voisins(face1,0)!=elem)
            i1=1;
          for(int f2=f1; f2<dimension+1; f2++)
            {
              int face2=elem_faces(elem,f2);
              int i2=0;
              if(face_voisins(face2,0)!=elem)
                i2=1;
              for(j=0; j<ncomp_ch_transporte; j++)
                {
                  double Tfj1;
                  if(ncomp_ch_transporte>1)
                    Tfj1=transporte(face1, j);
                  else
                    Tfj1=transporte(face1);
                  double Tfj2;
                  if(ncomp_ch_transporte>1)
                    Tfj2=transporte(face2, j);
                  else
                    Tfj2=transporte(face2);
                  double T1=Ttilde1(face1, j);
                  if (i1==1)
                    T1=Ttilde2(face1, j);
                  double T2=Ttilde1(face2, j);
                  if (i2==1)
                    T2=Ttilde2(face2, j);
// double Tbar=0.5*(Tfj1+Tfj2);
                  if((T1-T2)*(Tfj1-Tfj2)<1.e-12)
                    {
                      if (i1==0)
                        Ttilde1(face1, j)=Tfj1;
                      else
                        Ttilde2(face1, j)=Tfj1;
                      if (i2==0)
                        Ttilde1(face2, j)=Tfj2;
                      else
                        Ttilde2(face2, j)=Tfj2;
                    }
                }
            }
        }
    }
// calcul des flux ...
  int nfac = zone.nb_faces_elem();
  int nsom = zone.nb_som_elem();
  int nb_som_facette = zone.type_elem().nb_som_face();
  const Elem_geom_base& elem_geom = zone.type_elem().valeur();
  if ( sub_type(Hexaedre_VEF,elem_geom))
    {
      Process::exit();
    }
  const Elem_VEF_base& type_elemvef= zone_VEF.type_elem().valeur();
  int istetra=0;
  Nom nom_elem=type_elemvef.que_suis_je();
  if ((nom_elem=="Tetra_VEF")||(nom_elem=="Tri_VEF"))
    istetra=1;
  double psc;
  int poly,face_adj,fa7,i,n_bord;
  int num_face, rang ,itypcl;
  int num10,num20,num_som;
  if (transporte.nb_dim() == 1)
    ncomp_ch_transporte=1;
  else
    ncomp_ch_transporte= transporte.dimension(1);
  IntVect face(nfac);
  DoubleVect vs(dimension);
  DoubleVect vc(dimension);
  DoubleTab vsom(nsom,dimension);
  DoubleVect cc(dimension);
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
  fluent_ = 0;
// Traitement particulier pour les faces de periodicite
  int nb_faces_perio = 0;
// Boucle pour compter le nombre de faces de periodicite
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          nb_faces_perio += le_bord.nb_faces();
        }
    }
  DoubleTab tab;
  if (ncomp_ch_transporte == 1)
    tab.resize(nb_faces_perio);
  else
    tab.resize(nb_faces_perio,ncomp_ch_transporte);
// Boucle pour remplir tab
  nb_faces_perio=0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
// const Periodique& la_cl_perio = (Periodique&) la_cl.valeur();
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              if (ncomp_ch_transporte == 1)
                tab(nb_faces_perio) = resu(num_face);
              else
                for (int comp=0; comp<ncomp_ch_transporte; comp++)
                  tab(nb_faces_perio,comp) = resu(num_face,comp);
              nb_faces_perio++;
            }
        }
    }
  IntVect compteur(nsom);
  compteur = 0;
  vsom=0.;
// Les polyedres non standard sont ranges en 2 groupes dans la Zone_VEF:
// - polyedres bords et joints
// - polyedres bords et non joints
// On traite les polyedres en suivant l'ordre dans lequel ils figurent
// dans la zone
// boucle sur les polys
  for (poly=0; poly<nb_elem_tot; poly++)
    {
      rang = rang_elem_non_std(poly);
      if (rang==-1)
        itypcl=0;
      else
        itypcl=zone_Cl_VEF.type_elem_Cl(rang);
// calcul des numeros des faces du polyedre
      for (face_adj=0; face_adj<nfac; face_adj++)
        face[face_adj]= elem_faces(poly,face_adj);
// on conserve cette partie
      for (j=0; j<dimension; j++)
        {
          vs[j] = la_vitesse(face[0],j)*porosite_face(face[0]);
          for (i=1; i<nfac; i++)
            vs[j]+= la_vitesse(face[i],j)*porosite_face(face[i]);
        }
// calcul de la vitesse aux sommets des polyedres
// int ncomp;
      if (istetra==1)
        {
          for (j=0; j<nsom; j++)
            {
              for (int ncomp=0; ncomp<Objet_U::dimension; ncomp++)
                vsom(j,ncomp) =vs[ncomp] - Objet_U::dimension*la_vitesse(face[j],ncomp)*porosite_face(face[j]);
            }
        }
      else
        {
// pour que cela soit valide avec les hexa
// On va utliser les fonctions de forme implementees dans la classe Champs_P1_impl ou Champs_Q1_impl
          int ncomp;
          for (j=0; j<nsom; j++)
            {
              num_som = zone.sommet_elem(poly,j);
              for (ncomp=0; ncomp<dimension; ncomp++)
                {
                  vsom(j,ncomp) = la_vitesse.valeur_a_sommet_compo(num_som,poly,ncomp);
                }
            }
        }
// calcul de vc
      zone_VEF.type_elem().calcul_vc(face,vc,vs,vsom,vitesse(), itypcl,porosite_face);
// for (j=0; j<dimension; j++) vc(j) =  vs(j)/nfac ;
      type_elem.calcul_vc(face,vc,vs,vsom,vitesse(),
                          itypcl,porosite_face);
// Boucle sur les facettes du polyedre
      for (fa7=0; fa7<nfa7; fa7++)
        {
          if (rang==-1)
            for (i=0; i<dimension; i++)
              cc[i] = facette_normales(poly,fa7,i);
          else
            for (i=0; i<dimension; i++)
              cc[i] = normales_facettes_Cl(rang,fa7,i);
// On applique le schema de convection a chaque sommet de la facette
// On traite le ou les sommets qui sont aussi des sommets du polyedre
          const IntTab& KEL=type_elem->KEL();
          for (i=0; i<nb_som_facette-1; i++)
            {
              psc =0;
              for (j=0; j<dimension; j++)
                {
                  psc+= vsom(KEL(i+2,fa7),j)*cc[j];
                }
              type_elem.calcul_vc(face,vc,vs,vsom,vitesse(),itypcl,porosite_face);
// Boucle sur les facettes du polyedre
              psc /= nb_som_facette;
              num10 = face[KEL(0,fa7)];
              num20 = face[KEL(1,fa7)];
              double T1, T2;
              for(int comp=0; comp<ncomp_ch_transporte; comp++)
                {
                  if(face_voisins(num10,0)==poly)
                    T1 = Ttilde1(num10, comp);
                  else
                    T1 = Ttilde2(num10, comp);
                  if(face_voisins(num20,0)==poly)
                    T2 = Ttilde1(num20, comp);
                  else
                    T2 = Ttilde2(num20, comp);
                  if( (transporte(num20)-transporte(num10)) * (T1-transporte(num10)) < 0)
                    convbis(psc,num10,num20,T1, T2, comp,
                            ncomp_ch_transporte,
                            resu,fluent_);
                }
            }
// On traite le sommet confondu avec le centre de gravite du polyedre
          psc=0;
          for (j=0; j<dimension; j++)
            psc += vc[j]*cc[j];
          psc /= nb_som_facette;
          num10 = face[KEL(0,fa7)];
          num20 = face[KEL(1,fa7)];
          double T1, T2;
          for(int comp=0; comp<ncomp_ch_transporte; comp++)
            {
              if(face_voisins(num10,0)==poly)
                T1 = Ttilde1(num10, comp);
              else
                T1 = Ttilde2(num10, comp);
              if(face_voisins(num20,0)==poly)
                T2 = Ttilde1(num20, comp);
              else
                T2 = Ttilde2(num20, comp);
              convbis(psc,num10,num20,T1, T2, comp,
                      ncomp_ch_transporte,
                      resu,fluent_);
            }
        }
    } //!< fin de la boucle
  int voisine;
  nb_faces_perio = 0;
  double diff1,diff2;
// Dimensionnement du tableau des flux convectifs au bord du domaine
// de calcul
  DoubleTab& flux_b = ref_cast(DoubleTab, flux_bords_);
  flux_b.resize(zone_VEF.nb_faces_bord(),ncomp_ch_transporte);
  flux_b = 0.;
// Boucle sur les bords pour traiter les conditions aux limites
// il y a prise en compte d'un terme de convection pour les
// conditions aux limites de Neumann_sortie_libre seulement
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre =
            ref_cast(Neumann_sortie_libre, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              psc =0;
              for (i=0; i<dimension; i++)
                psc += la_vitesse(num_face,i)*face_normales(num_face,i)*porosite_face(num_face);
              if (psc>0)
                if (ncomp_ch_transporte == 1)
                  {
                    resu(num_face) -= psc*transporte(num_face);
                    flux_b(num_face,0) -= psc*transporte(num_face);
                  }
                else
                  for (i=0; i<ncomp_ch_transporte; i++)
                    {
                      resu(num_face,i) -= psc*transporte(num_face,i);
                      flux_b(num_face,i) -= psc*transporte(num_face,i);
                    }
              else
                {
                  if (ncomp_ch_transporte == 1)
                    {
                      resu(num_face) -= psc*la_sortie_libre.val_ext(num_face-num1);
                      flux_b(num_face,0) -= psc*la_sortie_libre.val_ext(num_face-num1);
                    }
                  else
                    for (i=0; i<ncomp_ch_transporte; i++)
                      {
                        resu(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                        flux_b(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                      }
                  fluent_[num_face] -= psc;
                }
            }
        }
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio =  ref_cast(Periodique, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          IntVect fait(le_bord.nb_faces());
          fait = 0;
          for (num_face=num1; num_face<num2; num_face++)
            {
              if (fait[num_face-num1] == 0)
                {
                  voisine = la_cl_perio.face_associee(num_face-num1) + num1;
                  if (ncomp_ch_transporte == 1)
                    {
                      diff1 = resu(num_face)-tab(nb_faces_perio);
                      diff2 = resu(voisine)-tab(nb_faces_perio+voisine-num_face);
                      resu(voisine)  += diff1;
                      resu(num_face) += diff2;
                      flux_b(voisine,0) += diff1;
                      flux_b(num_face,0) += diff2;
                    }
                  else
                    for (int comp=0; comp<ncomp_ch_transporte; comp++)
                      {
                        diff1 = resu(num_face,comp)-tab(nb_faces_perio,comp);
                        diff2 = resu(voisine,comp)-tab(nb_faces_perio+voisine-num_face,comp);
                        resu(voisine,comp)  += diff1;
                        resu(num_face,comp) += diff2;
                        flux_b(voisine,comp) += diff1;
                        flux_b(num_face,comp) += diff2;
                      }
                  fait[num_face-num1]= 1;
                  fait[voisine-num1] = 1;
                }
              nb_faces_perio++;
            }
        }
    }
  modifier_flux(*this);
  return resu;
}
virtual int Op_Conv_AmontNew_VEF_Face::duplique () const [pure virtual]
Implements Op_Conv_VEF_base.
const Type_info * Op_Conv_AmontNew_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VEF_base.
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
const Type_info * Op_Conv_AmontNew_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VEF_base.
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
Sortie & Op_Conv_AmontNew_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_VEF_base.
Definition at line 32 of file Op_Conv_AmontNew_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_AmontNew_VEF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_VEF_base.
Definition at line 40 of file Op_Conv_AmontNew_VEF_Face.cpp.
{
  return s ;
}
const Op_Conv_AmontNew_VEF_Face & Op_Conv_AmontNew_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_VEF_base.
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
Op_Conv_AmontNew_VEF_Face & Op_Conv_AmontNew_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_VEF_base.
Definition at line 26 of file Op_Conv_AmontNew_VEF_Face.cpp.
Member Data Documentation
const Type_info Op_Conv_AmontNew_VEF_Face::info_obj [static]
Reimplemented from Op_Conv_VEF_base.
Definition at line 51 of file Op_Conv_AmontNew_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_AmontNew_VEF_Face.h
src/VEF/Operateurs/Op_Conv_AmontNew_VEF_Face.cpp