TRUST: Option_CoviMAC Class Reference
Option_CoviMAC Class Reference
#include <Option_CoviMAC.h>
Public Member Functions
Option_CoviMAC ()
~Option_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Fonction principale de l'interprete Option_CoviMAC
Lit la dimension d'espace du probleme.
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int test_mot (const Motcle &mot) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Option_CoviMAC & self_cast (Objet_U &)
static const Option_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
static int interp_ve1 = 0
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
Detailed Description
Definition at line 30 of file Option_CoviMAC.h.
Constructor & Destructor Documentation
Option_CoviMAC::Option_CoviMAC ()
Definition at line 27 of file Option_CoviMAC.cpp.
Option_CoviMAC::~Option_CoviMAC ()
Definition at line 27 of file Option_CoviMAC.cpp.
Member Function Documentation
Objet_U * Option_CoviMAC::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
int Option_CoviMAC::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
const Type_info * Option_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
const Type_info * Option_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
Entree & Option_CoviMAC::interpreter (Entree & is) [virtual]
Fonction principale de l'interprete Option_CoviMAC
Lit la dimension d'espace du probleme.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 87 of file Option_CoviMAC.cpp.
References Param::ajouter_non_std(), Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
{
  Param param(que_suis_je());
  param.ajouter_non_std("interp_ve1",(this));     //chaine Use first-order face->cell velocity interpolation. By default, it is not activated
  param.lire_avec_accolades_depuis(is);
  return is;
}
int Option_CoviMAC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Objet_U.
Definition at line 95 of file Option_CoviMAC.cpp.
References interp_ve1.
{
  if (mot=="interp_ve1") interp_ve1 = 1;
  else return -1;
  return 1;
}
Sortie & Option_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 47 of file Option_CoviMAC.cpp.
{
  return Interprete::printOn(os);
}
Entree & Option_CoviMAC::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 67 of file Option_CoviMAC.cpp.
{
  return Interprete::readOn(is);
}
const Option_CoviMAC & Option_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
Option_CoviMAC & Option_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
unsigned Option_CoviMAC::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Option_CoviMAC.cpp.
int Option_CoviMAC::test_mot (const Motcle & mot) const
Member Data Documentation
const Type_info Option_CoviMAC::info_obj [static]
Reimplemented from Interprete.
Definition at line 32 of file Option_CoviMAC.h.
int Option_CoviMAC::interp_ve1 = 0 [static]
Definition at line 39 of file Option_CoviMAC.h.
Referenced by Masse_CoviMAC_Face::corriger_solution(), and lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/CoviMAC/Option_CoviMAC.h
src/CoviMAC/Option_CoviMAC.cpp