TRUST: Op_Conv_VDF< OP_TYPE > Class Template Reference
Op_Conv_VDF< OP_TYPE > Class Template Reference
#include <Op_Conv_VDF.h>
Protected Member Functions
void dimensionner_elem (Matrice_Morse &matrice) const
void dimensionner_bloc_vitesse_elem (Matrice_Morse &matrice) const
void modifier_pour_Cl_elem (Matrice_Morse &matrice, DoubleTab &secmem) const
void dimensionner_face (Matrice_Morse &matrice) const
void modifier_pour_Cl_face (Matrice_Morse &matrice, DoubleTab &secmem) const
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_CONV_ELEM, void >::type associer_impl (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis, const Champ_Inc &ch_transporte)
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_CONV_FACE, void >::type associer_impl (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis, const Champ_Inc &ch_vit)
template<typename EVAL_TYPE >
void associer_vitesse_impl (const Champ_base &ch_vit)
template<typename EVAL_TYPE >
const Champ_base & vitesse_impl () const
template<typename EVAL_TYPE >
Champ_base & vitesse_impl ()
Private Member Functions
const Iterateur_VDF & iter_ () const
Iterateur_VDF & iter_ ()
template<typename EVAL_TYPE , bool is_QUICK, bool is_CENTRE4>
EVAL_TYPE & associer_ (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis)
Additional Inherited Members
Public Member Functions inherited from Op_VDF_Elem
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void dimensionner_bloc_vitesse (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Public Member Functions inherited from Op_VDF_Face
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Detailed Description
template<typename OP_TYPE>
class Op_Conv_VDF< OP_TYPE >
Definition at line 25 of file Op_Conv_VDF.h.
Member Function Documentation
associer_()
template<typename OP_TYPE > template<typename EVAL_TYPE , bool is_QUICK, bool is_CENTRE4> EVAL_TYPE & Op_Conv_VDF< OP_TYPE >::associer_ (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) inline private
< Et ouiiiiiiiii
< Mais ouiiiiiiiiiiii
Definition at line 85 of file Op_Conv_VDF.h.
  {
    const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
    const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
    iter_()->associer(zvdf,zclvdf,static_cast<OP_TYPE&>(*this)); //!< Et ouiiiiiiiii
    EVAL_TYPE& eval_conv = static_cast<EVAL_TYPE&> (iter_()->evaluateur()); //!< Mais ouiiiiiiiiiiii
    eval_conv.associer_zones(zvdf, zclvdf );
    if (is_QUICK || is_CENTRE4)
      if ( Process::nproc()>1 && zvdf.zone().nb_joints() && zvdf.zone().joint(0).epaisseur()<2)
        {
          Cerr << "Overlapping width (given by larg_joint option) of  " << zvdf.zone().joint(0).epaisseur() << finl;
          Cerr << "is not enough for Quick scheme in VDF parallel calculation." << finl;
          Cerr << "Please, partition your mesh with an overlapping width of 2 with larg_joint option." << finl;
          Process::exit();
        }
    return eval_conv;
  }
References Iterateur_VDF::associer(), Cerr, Joint::epaisseur(), Iterateur_VDF::evaluateur(), Process::exit(), finl, Op_Conv_VDF< OP_TYPE >::iter_(), Zone::joint(), Zone::nb_joints(), Process::nproc(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
associer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_CONV_ELEM, void >::type Op_Conv_VDF< OP_TYPE >::associer_impl (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) inline protected
< Cheerssssssssss !!!
Definition at line 40 of file Op_Conv_VDF.h.
  {
    constexpr bool is_QUICK = std::is_same<EVAL_TYPE,Eval_Quick_VDF_Elem>::value, is_CENTRE4 = std::is_same<EVAL_TYPE,Eval_Centre4_VDF_Elem>::value;
    const Champ_P0_VDF& inco = ref_cast(Champ_P0_VDF,ch_transporte.valeur());
    associer_<EVAL_TYPE,is_QUICK,is_CENTRE4>(zone_dis,zone_cl_dis).associer_inconnue(inco); //!< Cheerssssssssss !!!
  }
References ref_cast, and Deriv_Champ_Inc_base::valeur().
associer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_CONV_FACE, void >::type Op_Conv_VDF< OP_TYPE >::associer_impl (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_vit) inline protected
< Cheerssssssssss !!!
Definition at line 49 of file Op_Conv_VDF.h.
  {
    constexpr bool is_QUICK = std::is_same<EVAL_TYPE,Eval_Quick_VDF_Face>::value, is_CENTRE4 = std::is_same<EVAL_TYPE,Eval_Centre4_VDF_Face>::value;
    const Champ_Face& vit = ref_cast(Champ_Face,ch_vit.valeur());
    associer_<EVAL_TYPE,is_QUICK,is_CENTRE4>(zone_dis,zone_cl_dis).associer_inconnue(vit); //!< Cheerssssssssss !!!
  }
References ref_cast, and Deriv_Champ_Inc_base::valeur().
associer_vitesse_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > void Op_Conv_VDF< OP_TYPE >::associer_vitesse_impl (const Champ_base & ch_vit) inline protected
Definition at line 57 of file Op_Conv_VDF.h.
  {
    const Champ_Face& vit = ref_cast(Champ_Face, ch_vit);
    EVAL_TYPE& eval_conv = static_cast<EVAL_TYPE&>(iter_()->evaluateur());
    eval_conv.associer(vit);
  }
References Iterateur_VDF::evaluateur(), Op_Conv_VDF< OP_TYPE >::iter_(), and ref_cast.
dimensionner_bloc_vitesse_elem()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::dimensionner_bloc_vitesse_elem (Matrice_Morse & matrice) const inline protected
Definition at line 30 of file Op_Conv_VDF.h.
{ Op_VDF_Elem::dimensionner_bloc_vitesse(iter_()->zone(), iter_()->zone_Cl(), matrice); }
References Op_VDF_Elem::dimensionner_bloc_vitesse(), and Op_Conv_VDF< OP_TYPE >::iter_().
dimensionner_elem()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::dimensionner_elem (Matrice_Morse & matrice) const inline protected
Definition at line 29 of file Op_Conv_VDF.h.
{ Op_VDF_Elem::dimensionner(iter_()->zone(), iter_()->zone_Cl(), matrice); }
References Op_VDF_Elem::dimensionner(), and Op_Conv_VDF< OP_TYPE >::iter_().
dimensionner_face()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::dimensionner_face (Matrice_Morse & matrice) const inline protected
Definition at line 34 of file Op_Conv_VDF.h.
{ Op_VDF_Face::dimensionner(iter_()->zone(), iter_()->zone_Cl(), matrice); }
References Op_VDF_Face::dimensionner(), and Op_Conv_VDF< OP_TYPE >::iter_().
iter_() [1/2]
template<typename OP_TYPE > Iterateur_VDF & Op_Conv_VDF< OP_TYPE >::iter_ () inline private
Definition at line 81 of file Op_Conv_VDF.h.
{ return static_cast<OP_TYPE *>(this)->get_iter(); }
iter_() [2/2]
template<typename OP_TYPE > const Iterateur_VDF & Op_Conv_VDF< OP_TYPE >::iter_ () const inline private
Definition at line 80 of file Op_Conv_VDF.h.
{ return static_cast<const OP_TYPE *>(this)->get_iter(); }
Referenced by Op_Conv_VDF< OP_TYPE >::associer_(), Op_Conv_VDF< OP_TYPE >::associer_vitesse_impl(), Op_Conv_VDF< OP_TYPE >::dimensionner_bloc_vitesse_elem(), Op_Conv_VDF< OP_TYPE >::dimensionner_elem(), Op_Conv_VDF< OP_TYPE >::dimensionner_face(), Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_elem(), Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_face(), and Op_Conv_VDF< OP_TYPE >::vitesse_impl().
modifier_pour_Cl_elem()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_elem (Matrice_Morse & matrice, DoubleTab & secmem) const inline protected
Definition at line 31 of file Op_Conv_VDF.h.
{ Op_VDF_Elem::modifier_pour_Cl(iter_()->zone(), iter_()->zone_Cl(), matrice, secmem); }
References Op_Conv_VDF< OP_TYPE >::iter_(), and Op_VDF_Elem::modifier_pour_Cl().
modifier_pour_Cl_face()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_face (Matrice_Morse & matrice, DoubleTab & secmem) const inline protected
Definition at line 35 of file Op_Conv_VDF.h.
{ Op_VDF_Face::modifier_pour_Cl(iter_()->zone(), iter_()->zone_Cl(), matrice, secmem); }
References Op_Conv_VDF< OP_TYPE >::iter_(), and Op_VDF_Face::modifier_pour_Cl().
vitesse_impl() [1/2]
template<typename OP_TYPE > template<typename EVAL_TYPE > Champ_base & Op_Conv_VDF< OP_TYPE >::vitesse_impl () inline protected
Definition at line 72 of file Op_Conv_VDF.h.
  {
    EVAL_TYPE& eval_conv = static_cast<EVAL_TYPE&>(iter_()->evaluateur());
    return eval_conv.vitesse();
  }
References Iterateur_VDF::evaluateur(), and Op_Conv_VDF< OP_TYPE >::iter_().
vitesse_impl() [2/2]
template<typename OP_TYPE > template<typename EVAL_TYPE > const Champ_base & Op_Conv_VDF< OP_TYPE >::vitesse_impl () const inline protected
Definition at line 65 of file Op_Conv_VDF.h.
  {
    const EVAL_TYPE& eval_conv = static_cast<const EVAL_TYPE&>(iter_()->evaluateur());
    return eval_conv.vitesse();
  }
References Iterateur_VDF::evaluateur(), and Op_Conv_VDF< OP_TYPE >::iter_().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Op_Conv/Op_Conv_VDF.h