TRUST: Op_Conv_VDF_base Class Reference
Op_Conv_VDF_base Class Reference
class Op_Conv_VDF_base
Classe de base des operateurs de convection VDF
#include <Op_Conv_VDF_base.h>
Public Member Functions
Op_Conv_VDF_base ()
~Op_Conv_VDF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Conv_VDF_base (const Iterateur_VDF_base &)
constructeur
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &resu) const
ajoute la contribution de la convection au second membre resu
renvoie resu
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const
calcule la contribution de la convection, la range dans resu
renvoie resu
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
virtual const Champ_base & vitesse () const =0
virtual Champ_base & vitesse ()=0
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double calculer_dt_stab () const
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_VDF_base & self_cast (Objet_U &)
static const Op_Conv_VDF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Iterateur_VDF iter
Detailed Description
class Op_Conv_VDF_base
Classe de base des operateurs de convection VDF
Definition at line 47 of file Op_Conv_VDF_base.h.
Constructor & Destructor Documentation
Op_Conv_VDF_base::Op_Conv_VDF_base ()
Definition at line 31 of file Op_Conv_VDF_base.cpp.
Op_Conv_VDF_base::~Op_Conv_VDF_base ()
Definition at line 31 of file Op_Conv_VDF_base.cpp.
Op_Conv_VDF_base::Op_Conv_VDF_base (const Iterateur_VDF_base & iter_base) [inline]
constructeur
Definition at line 81 of file Op_Conv_VDF_base.h.
                                                                             :
  iter(iter_base)
{}
Member Function Documentation
DoubleTab & Op_Conv_VDF_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
ajoute la contribution de la convection au second membre resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 88 of file Op_Conv_VDF_base.h.
References Iterateur_VDF::ajouter(), and iter.
{
  return iter.ajouter(inco, resu);
}
void Op_Conv_VDF_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zcl) [virtual]
Reimplemented from Operateur_base.
Definition at line 354 of file Op_Conv_VDF_base.cpp.
References Iterateur_VDF_base::associer_zone_cl_dis(), iter, and Deriv_Iterateur_VDF_base::valeur().
{
  iter.valeur().associer_zone_cl_dis(zcl);
}
DoubleTab & Op_Conv_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
calcule la contribution de la convection, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 120 of file Op_Conv_VDF_base.h.
References Iterateur_VDF::calculer(), and iter.
{
  return iter.calculer(inco, resu);
}
void Op_Conv_VDF_base::calculer_dt_local (DoubleTab & dt_face) const [virtual]
Reimplemented from Operateur_base.
Definition at line 145 of file Op_Conv_VDF_base.cpp.
References diviser_par_rho_si_dilatable(), DoubleVect::echange_espace_virtuel(), MorEqn::equation(), est_egal(), face_associee, Periodique::face_associee(), Zone_VF::face_surfaces(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), iter, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), min(), DoubleVect::mp_max_abs_vect(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, DoubleVect::size(), sub_type, sup_strict(), Deriv_Cond_lim_base::valeur(), Champ_Inc::valeurs(), vitesse(), Zone_VF::volumes_entrelaces(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  const Zone_VDF& zone_VDF = iter.zone();
  const Zone_Cl_VDF& zone_Cl_VDF = iter.zone_Cl();
  const DoubleVect& volumes_entrelaces= zone_VDF.volumes_entrelaces();
  const DoubleVect& face_surfaces = zone_VDF.face_surfaces();
// const DoubleVect& vit= vitesse_pour_pas_de_temps_.valeur().valeurs();
  const DoubleVect& vit=equation().inconnue().valeurs();
  DoubleTrav fluent(volumes_entrelaces);
// Remplissage du tableau fluent
// On traite les bords
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if ( sub_type(Dirichlet_entree_fluide,la_cl.valeur())
           || sub_type(Neumann_sortie_libre,la_cl.valeur())  )
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int  num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (int face=num1; face<num2; face++)
            {
              double value = vit[face]*face_surfaces(face);
              if (value >0)
                fluent[face] = value;
              else
                fluent[face] -= value;
            }
        }
    }
// Boucle sur les faces internes pour remplir fluent
  int zone_VDF_nb_faces=zone_VDF.nb_faces();
  int premiere_face=zone_VDF.premiere_face_int();
  for (int face=premiere_face; face<zone_VDF_nb_faces; face++)
    {
      double value = vit[face]*face_surfaces(face);
      if (value >0)
        fluent[face] = value;
      else
        fluent[face] -= value;
    }
// Calcul du pas de temps de stabilite a partir du tableau fluent
  if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
    diviser_par_rho_si_dilatable(fluent,equation().milieu());
  dt_face=(volumes_entrelaces);
// Boucle sur les faces de bords
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      for (int num_face=ndeb; num_face<nfin; num_face++)
        {
          if( sup_strict(fluent[num_face], 1.e-16) )
            dt_face(num_face)= volumes_entrelaces(num_face)/fluent[num_face];
          else
            dt_face(num_face) = -1.;
        }
    }
// Boucle sur les faces internes
  for (int num_face=premiere_face; num_face<zone_VDF_nb_faces; num_face++)
    {
      if( sup_strict(fluent[num_face], 1.e-16) )
        dt_face(num_face)= volumes_entrelaces(num_face)/fluent[num_face];
      else
        dt_face(num_face) = -1.;
    }
  double max_dt_local= dt_face.mp_max_abs_vect();
  int taille= dt_face.size();
  for(int i=0; i<taille; i++)
    {
      if(! sup_strict(dt_face(i), 1.e-16))
        {
          dt_face(i) = max_dt_local;
        }
    }
  dt_face.echange_espace_virtuel();
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord=le_bord.nb_faces();
          for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
            {
              int ind_face_associee = la_cl_perio.face_associee(ind_face);
              int face = le_bord.num_face(ind_face);
              int face_associee = le_bord.num_face(ind_face_associee);
              if (!est_egal(dt_face(face),dt_face(face_associee),1.e-8))
                {
                  dt_face(face) = min(dt_face(face),dt_face(face_associee));
                }
            }
        }
    }
  dt_face.echange_espace_virtuel();
// dt_conv_locaux=dt_face;
}
double Op_Conv_VDF_base::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
< (elem2 != -1)
Reimplemented from Operateur_base.
Definition at line 65 of file Op_Conv_VDF_base.cpp.
References Zone::creer_tableau_elements(), diviser_par_rho_si_dilatable(), DMINFLOAT, MorEqn::equation(), eval_fluent(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_Conv_base::fixer_dt_stab_conv(), Cond_lim::frontiere_dis(), iter, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, ref_cast_non_const, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Champ_base::valeur(), Champ_Proto::valeurs(), vitesse(), Operateur_Conv_base::vitesse_pour_pas_de_temps_, Zone_VF::volumes(), Zone_dis_base::zone(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  const Zone_VDF& zone_VDF = iter.zone();
  const Zone_Cl_VDF& zone_Cl_VDF = iter.zone_Cl();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const DoubleVect& volumes = zone_VDF.volumes();
  const DoubleVect& face_surfaces = zone_VDF.face_surfaces();
  const DoubleVect& vit_associe = vitesse().valeurs();
  const DoubleVect& vit= (vitesse_pour_pas_de_temps_.non_nul()?vitesse_pour_pas_de_temps_.valeur().valeurs(): vit_associe);
  DoubleTab fluent;
// fluent est initialise a zero par defaut:
  zone_VDF.zone().creer_tableau_elements(fluent);
// Remplissage du tableau fluent
  double psc;
  int num1,num2,face;
  int elem1;
// On traite les bords
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if ( sub_type(Dirichlet_entree_fluide,la_cl.valeur())
           || sub_type(Neumann_sortie_libre,la_cl.valeur())  )
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          num1 = le_bord.num_premiere_face();
          num2 = num1 + le_bord.nb_faces();
          for (face=num1; face<num2; face++)
            {
              psc = vit[face]*face_surfaces(face);
              if ( (elem1 = face_voisins(face,0)) != -1)
                {
                  if (psc < 0)
                    fluent[elem1] -= psc;
                }
              else //!< (elem2 != -1)
                if (psc > 0)
                  fluent[face_voisins(face,1)] += psc;
            }
        }
    }
// Boucle sur les faces internes pour remplir fluent
  int zone_VDF_nb_faces=zone_VDF.nb_faces();
  int premiere_face=zone_VDF.premiere_face_int();
  for (face=premiere_face; face<zone_VDF_nb_faces; face++)
    {
      psc = vit[face]*face_surfaces(face);
      eval_fluent(psc,face_voisins(face,0),face_voisins(face,1),fluent);
    }
// Calcul du pas de temps de stabilite a partir du tableau fluent
  if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
    diviser_par_rho_si_dilatable(fluent,equation().milieu());
  double dt_stab = 1.e30;
  int zone_VDF_nb_elem=zone_VDF.nb_elem();
// dt_stab = min (1 / (|U|/dx + |V|/dy + |W|/dz))
  for (int num_poly=0; num_poly<zone_VDF_nb_elem; num_poly++)
    {
      double dt_elem = volumes(num_poly)/(fluent[num_poly]+DMINFLOAT);
      if (dt_elem<dt_stab)
        dt_stab = dt_elem;
    }
  dt_stab = Process::mp_min(dt_stab);
// astuce pour contourner le type const de la methode
  Op_Conv_VDF_base& op =ref_cast_non_const(Op_Conv_VDF_base, *this);
  op.fixer_dt_stab_conv(dt_stab);
  return dt_stab;
}
void Op_Conv_VDF_base::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const [virtual]
< (elem2 != -1)
Reimplemented from Operateur_base.
Definition at line 262 of file Op_Conv_VDF_base.cpp.
References diviser_par_rho_si_dilatable(), MorEqn::equation(), eval_fluent(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), iter, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Zone::nb_elem_tot(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Champ_Proto::valeurs(), Champ::valeurs(), vitesse(), Zone_VF::volumes(), Zone_dis_base::zone(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      es_valeurs = 1.e30;
      const Zone_VDF& zone_VDF = iter.zone();
      const Zone_Cl_VDF& zone_Cl_VDF = iter.zone_Cl();
      const IntTab& face_voisins = zone_VDF.face_voisins();
      const DoubleVect& volumes = zone_VDF.volumes();
      const DoubleVect& face_surfaces = zone_VDF.face_surfaces();
      const DoubleVect& vit = vitesse().valeurs();
      DoubleTrav fluent(zone_VDF.zone().nb_elem_tot());
// Remplissage du tableau fluent
      fluent = 0;
      double psc;
      int num1,num2,face;
      int elem1;
// On traite les bords
      for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
          if ( sub_type(Dirichlet_entree_fluide,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur())  )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              num1 = le_bord.num_premiere_face();
              num2 = num1 + le_bord.nb_faces();
              for (face=num1; face<num2; face++)
                {
                  psc = vit[face]*face_surfaces(face);
                  if ( (elem1 = face_voisins(face,0)) != -1)
                    {
                      if (psc < 0)
                        fluent[elem1] -= psc;
                    }
                  else //!< (elem2 != -1)
                    if (psc > 0)
                      fluent[face_voisins(face,1)] += psc;
                }
            }
        }
// Boucle sur les faces internes pour remplir fluent
      int zone_VDF_nb_faces=zone_VDF.nb_faces();
      for (face=zone_VDF.premiere_face_int(); face<zone_VDF_nb_faces; face++)
        {
          psc = vit[face]*face_surfaces(face);
          eval_fluent(psc,face_voisins(face,0),face_voisins(face,1),fluent);
        }
// fluent.echange_espace_virtuel();
      if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
        diviser_par_rho_si_dilatable(fluent,equation().milieu());
      int zone_VDF_nb_elem=zone_VDF.nb_elem();
      for (int num_poly=0; num_poly<zone_VDF_nb_elem; num_poly++)
        {
          es_valeurs(num_poly) = volumes(num_poly)/(fluent[num_poly]+1.e-30);
        }
// double dt_min = mp_min_vect(es_valeurs);
// assert(dt_min==calculer_dt_stab());
    }
  else
    Operateur_Conv_base::calculer_pour_post(espace_stockage,option,comp);
}
void Op_Conv_VDF_base::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 349 of file Op_Conv_VDF_base.cpp.
References Iterateur_VDF::completer_(), and iter.
{
  Operateur_base::completer();
  iter.completer_();
}
void Op_Conv_VDF_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 96 of file Op_Conv_VDF_base.h.
References Iterateur_VDF::ajouter_contribution(), and iter.
{
  iter.ajouter_contribution(inco, matrice);
}
void Op_Conv_VDF_base::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 111 of file Op_Conv_VDF_base.h.
References Iterateur_VDF::contribuer_au_second_membre(), and iter.
{
  iter.contribuer_au_second_membre(resu);
}
void Op_Conv_VDF_base::contribuer_bloc_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 102 of file Op_Conv_VDF_base.h.
References Iterateur_VDF::ajouter_contribution_vitesse(), and iter.
{
  iter.ajouter_contribution_vitesse(inco, matrice);
}
virtual int Op_Conv_VDF_base::duplique () const [pure virtual]
Implements Operateur_Conv_base.
Implemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
const Type_info * Op_Conv_VDF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 31 of file Op_Conv_VDF_base.cpp.
Motcle Op_Conv_VDF_base::get_localisation_pour_post (const Nom & option) const [virtual]
Reimplemented from Operateur_base.
Definition at line 339 of file Op_Conv_VDF_base.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "elem";
  else
    return Operateur_Conv_base::get_localisation_pour_post(option);
  return loc;
}
int Op_Conv_VDF_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 359 of file Op_Conv_VDF_base.cpp.
References Iterateur_VDF::impr(), and iter.
{
  return iter.impr(os);
}
const Type_info * Op_Conv_VDF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 31 of file Op_Conv_VDF_base.cpp.
Sortie & Op_Conv_VDF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 36 of file Op_Conv_VDF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_VDF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 44 of file Op_Conv_VDF_base.cpp.
{
  return s ;
}
Op_Conv_VDF_base & Op_Conv_VDF_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 31 of file Op_Conv_VDF_base.cpp.
const Op_Conv_VDF_base & Op_Conv_VDF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 31 of file Op_Conv_VDF_base.cpp.
virtual const Champ_base& Op_Conv_VDF_base::vitesse () const [pure virtual]
Implemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Referenced by calculer_dt_local(), calculer_dt_stab(), and calculer_pour_post().
virtual Champ_base& Op_Conv_VDF_base::vitesse () [pure virtual]
Implemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Member Data Documentation
const Type_info Op_Conv_VDF_base::info_obj [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, and Op_Conv_Quick_VDF_Face.
Definition at line 50 of file Op_Conv_VDF_base.h.
Iterateur_VDF Op_Conv_VDF_base::iter [protected]
Definition at line 71 of file Op_Conv_VDF_base.h.
Referenced by ajouter(), Op_Conv_Quick_VDF_Face::associer(), Op_Conv_Quick_VDF_Elem::associer(), Op_Conv_Centre_VDF_Face::associer(), Op_Conv_centre_VDF_Elem::associer(), Op_Conv_centre4_VDF_Face::associer(), Op_Conv_centre4_VDF_Elem::associer(), Op_Conv_Amont_VDF_Face::associer(), Op_Conv_Amont_VDF_Elem::associer(), Op_Conv_Quick_VDF_Face_Axi::associer(), Op_Conv_Quick_VDF_Face::associer_vitesse(), Op_Conv_Quick_VDF_Elem::associer_vitesse(), Op_Conv_Centre_VDF_Face::associer_vitesse(), Op_Conv_centre_VDF_Elem::associer_vitesse(), Op_Conv_centre4_VDF_Face::associer_vitesse(), Op_Conv_centre4_VDF_Elem::associer_vitesse(), Op_Conv_Amont_VDF_Face::associer_vitesse(), Op_Conv_Amont_VDF_Elem::associer_vitesse(), Op_Conv_Quick_VDF_Face_Axi::associer_vitesse(), associer_zone_cl_dis(), calculer(), calculer_dt_local(), calculer_dt_stab(), calculer_pour_post(), completer(), contribuer_a_avec(), contribuer_au_second_membre(), contribuer_bloc_vitesse(), Op_Conv_Quick_VDF_Face::dimensionner(), Op_Conv_Quick_VDF_Elem::dimensionner(), Op_Conv_Centre_VDF_Face::dimensionner(), Op_Conv_centre_VDF_Elem::dimensionner(), Op_Conv_Amont_VDF_Face::dimensionner(), Op_Conv_Amont_VDF_Elem::dimensionner(), Op_Conv_centre_VDF_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_VDF_Elem::dimensionner_bloc_vitesse(), impr(), Op_Conv_Quick_VDF_Face::modifier_pour_Cl(), Op_Conv_Quick_VDF_Elem::modifier_pour_Cl(), Op_Conv_Centre_VDF_Face::modifier_pour_Cl(), Op_Conv_centre_VDF_Elem::modifier_pour_Cl(), Op_Conv_Amont_VDF_Face::modifier_pour_Cl(), Op_Conv_Amont_VDF_Elem::modifier_pour_Cl(), Op_Conv_Quick_VDF_Face::vitesse(), Op_Conv_Quick_VDF_Elem::vitesse(), Op_Conv_Centre_VDF_Face::vitesse(), Op_Conv_centre_VDF_Elem::vitesse(), Op_Conv_centre4_VDF_Face::vitesse(), Op_Conv_centre4_VDF_Elem::vitesse(), Op_Conv_Amont_VDF_Face::vitesse(), Op_Conv_Amont_VDF_Elem::vitesse(), and Op_Conv_Quick_VDF_Face_Axi::vitesse().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Conv_VDF_base.h
src/VDF/Operateurs/Op_Conv_VDF_base.cpp