TRUST: Modele_Permeabilite Class Reference
Modele_Permeabilite Class Reference
classe Modele_Permeabilite
Classe generique pour un modele de permeabilite.
#include <Modele_Permeabilite.h>
Public Member Functions
Modele_Permeabilite ()
~Modele_Permeabilite ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
double getK (double porosite) const
Appel a l'objet sous-jacent.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Modele_Permeabilite & self_cast (Objet_U &)
static const Modele_Permeabilite & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le type du modele sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Detailed Description
classe Modele_Permeabilite
Classe generique pour un modele de permeabilite.
Definition at line 38 of file Modele_Permeabilite.h.
Constructor & Destructor Documentation
Modele_Permeabilite::Modele_Permeabilite ()
Definition at line 27 of file Modele_Permeabilite.cpp.
Modele_Permeabilite::~Modele_Permeabilite ()
Definition at line 27 of file Modele_Permeabilite.cpp.
Member Function Documentation
Objet_U * Modele_Permeabilite::cree_instance () [static]
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
int Modele_Permeabilite::duplique () const [virtual]
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
const Type_info * Modele_Permeabilite::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
double Modele_Permeabilite::getK (double porosite) const [inline]
Appel a l'objet sous-jacent.
Renvoie la valeur de la permeabilite
Parameters:
porosite la valeur de la porosite
Definition at line 67 of file Modele_Permeabilite.h.
References Modele_Permeabilite_base::getK(), and Deriv_Modele_Permeabilite_base::valeur().
Referenced by Eval_Forchheimer_VEF_Face::calculer_terme_source(), Eval_Darcy_VEF_Face::calculer_terme_source(), Eval_Forchheimer_VDF_Face::calculer_terme_source(), and Eval_Darcy_VDF_Face::calculer_terme_source().
{
  return valeur().getK(porosite);
}
const Type_info * Modele_Permeabilite::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
Sortie & Modele_Permeabilite::printOn (Sortie & s) const [protected, virtual]
Imprime le type du modele sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 43 of file Modele_Permeabilite.cpp.
References DERIV.
{
  return DERIV(Modele_Permeabilite_base)::printOn(s);
}
Entree & Modele_Permeabilite::readOn (Entree & s) [protected, virtual]
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 65 of file Modele_Permeabilite.cpp.
{
  return s;
}
Modele_Permeabilite & Modele_Permeabilite::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
const Modele_Permeabilite & Modele_Permeabilite::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
unsigned Modele_Permeabilite::taille_memoire () const [virtual]
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 27 of file Modele_Permeabilite.cpp.
Member Data Documentation
const Type_info Modele_Permeabilite::info_obj [static]
Reimplemented from Deriv_Modele_Permeabilite_base.
Definition at line 41 of file Modele_Permeabilite.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Modele_Permeabilite.h
src/ThHyd/Incompressible/Modele_Permeabilite.cpp