TRUST: Eval_Dift_VDF_Multi_inco_var Class Reference
Eval_Dift_VDF_Multi_inco_var Class Reference
class Eval_Dift_VDF_Multi_inco_var
Cette classe represente un evaluateur de flux diffusif total<br>(laminaire et turbulent) pour un vecteur d'inconnues
avec une diffusivite par inconnue.
Le champ de diffusivite associe a chaque inconnue n'est pas constant.
#include <Eval_Dift_VDF_Multi_inco_var.h>
Public Member Functions
void mettre_a_jour () override
void associer_diff_turb (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double get_equivalent_distance (int boundary_index, int local_face) const override
Public Member Functions inherited from Eval_Diff_VDF_Multi_inco_var
void mettre_a_jour () override
void associer (const Champ_base &) override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Public Member Functions inherited from Eval_Turbulence
virtual ~Eval_Turbulence ()
virtual void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
virtual void init_ind_fluctu_term ()
void update_equivalent_distance ()
Protected Attributes
Ref_Champ_Fonc diffusivite_turbulente_
DoubleVect dv_diffusivite_turbulente
Protected Attributes inherited from Eval_Diff_VDF_Multi_inco_var
Ref_Champ_base diffusivite_
DoubleTab dt_diffusivite
Protected Attributes inherited from Eval_Turbulence
Ref_Turbulence_paroi_scal loipar
DoubleVects equivalent_distance
Additional Inherited Members
Protected Member Functions inherited from Eval_Diff_VDF_Multi_inco_var
double dist_face (int, int, int) const
Detailed Description
class Eval_Dift_VDF_Multi_inco_var
Cette classe represente un evaluateur de flux diffusif total<br>(laminaire et turbulent) pour un vecteur d'inconnues
avec une diffusivite par inconnue.
Le champ de diffusivite associe a chaque inconnue n'est pas constant.
See also
Eval_Diff_VDF_Multi_inco_var
Definition at line 31 of file Eval_Dift_VDF_Multi_inco_var.h.
Member Function Documentation
associer_diff_turb()
void Eval_Dift_VDF_Multi_inco_var::associer_diff_turb (const Champ_Fonc & diff_turb) inline
Definition at line 76 of file Eval_Dift_VDF_Multi_inco_var.h.
{
  diffusivite_turbulente_=diff_turb;
  dv_diffusivite_turbulente.ref(diff_turb.valeurs());
}
References diffusivite_turbulente_, dv_diffusivite_turbulente, TRUSTVect< _TYPE_ >::ref(), and Champ_Fonc::valeurs().
compute_heq_impl()
double Eval_Dift_VDF_Multi_inco_var::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 52 of file Eval_Dift_VDF_Multi_inco_var.h.
  {
    const double heq_lam = Eval_Diff_VDF_Multi_inco_var::compute_heq_impl(d0, i, d1, j, compo);
    const double heq_turb= 0.5*(dv_diffusivite_turbulente(i)+dv_diffusivite_turbulente(j))/(d1+d0);
    return heq_lam + heq_turb;
  }
References Eval_Diff_VDF_Multi_inco_var::compute_heq_impl(), and dv_diffusivite_turbulente.
diffusivite_turbulente()
const Champ_Fonc & Eval_Dift_VDF_Multi_inco_var::diffusivite_turbulente () const inline
Definition at line 37 of file Eval_Dift_VDF_Multi_inco_var.h.
{ return diffusivite_turbulente_.valeur(); }
References diffusivite_turbulente_, and Ref_Champ_Fonc::valeur().
get_equivalent_distance()
double Eval_Dift_VDF_Multi_inco_var::get_equivalent_distance (int boundary_index, int local_face) const inline override virtual
Reimplemented from Eval_Diff_VDF.
Definition at line 59 of file Eval_Dift_VDF_Multi_inco_var.h.
  {
    return equivalent_distance[boundary_index](local_face);
  }
References Eval_Turbulence::equivalent_distance.
mettre_a_jour()
void Eval_Dift_VDF_Multi_inco_var::mettre_a_jour () inline override virtual
< from Eval_Turbulence
Reimplemented from Eval_Diff_VDF_Multi_inco_var.
Definition at line 70 of file Eval_Dift_VDF_Multi_inco_var.h.
{
  Eval_Diff_VDF_Multi_inco_var::mettre_a_jour();
  update_equivalent_distance();  //!< from Eval_Turbulence
}
References Eval_Diff_VDF_Multi_inco_var::mettre_a_jour(), and Eval_Turbulence::update_equivalent_distance().
nu_1_impl()
double Eval_Dift_VDF_Multi_inco_var::nu_1_impl (int i, int compo) const inline
Definition at line 40 of file Eval_Dift_VDF_Multi_inco_var.h.
  {
    const double nu_lam = Eval_Diff_VDF_Multi_inco_var::nu_1_impl(i,compo);
    const double nu_turb = dv_diffusivite_turbulente(i);
    return nu_lam+nu_turb;
  }
References dv_diffusivite_turbulente, and Eval_Diff_VDF_Multi_inco_var::nu_1_impl().
nu_2_impl()
double Eval_Dift_VDF_Multi_inco_var::nu_2_impl (int i, int compo) const inline
Definition at line 47 of file Eval_Dift_VDF_Multi_inco_var.h.
  {
    return Eval_Diff_VDF_Multi_inco_var::nu_2_impl(i,compo);
  }
References Eval_Diff_VDF_Multi_inco_var::nu_2_impl().
Member Data Documentation
diffusivite_turbulente_
Ref_Champ_Fonc Eval_Dift_VDF_Multi_inco_var::diffusivite_turbulente_ protected
Definition at line 66 of file Eval_Dift_VDF_Multi_inco_var.h.
Referenced by associer_diff_turb(), and diffusivite_turbulente().
dv_diffusivite_turbulente
DoubleVect Eval_Dift_VDF_Multi_inco_var::dv_diffusivite_turbulente protected
Definition at line 67 of file Eval_Dift_VDF_Multi_inco_var.h.
Referenced by associer_diff_turb(), compute_heq_impl(), and nu_1_impl().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Dift_VDF_Multi_inco_var.h