TRUST: Traitement_particulier_NS_canal_VDF Class Reference
Traitement_particulier_NS_canal_VDF Class Reference
classe Traitement_particulier_NS_canal_VDF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
#include <Traitement_particulier_NS_canal_VDF.h>
Public Member Functions
Traitement_particulier_NS_canal_VDF ()
~Traitement_particulier_NS_canal_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & lire (const Motcle &, Entree &)
Entree & lire (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Traitement_particulier_NS_canal_VDF & self_cast (Objet_U &)
static const
Traitement_particulier_NS_canal_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
virtual Entree & readOn (Entree &)
void remplir_Y (DoubleVect &, DoubleVect &, int &) const
void remplir_Tab_recap (IntTab &) const
void calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab &) const
void calculer_moyenne_spatiale_nut (DoubleTab &) const
void calculer_moyenne_spatiale_Temp (DoubleTab &) const
Detailed Description
classe Traitement_particulier_NS_canal_VDF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
Definition at line 42 of file Traitement_particulier_NS_canal_VDF.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_canal_VDF::Traitement_particulier_NS_canal_VDF ()
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
Traitement_particulier_NS_canal_VDF::~Traitement_particulier_NS_canal_VDF ()
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
Member Function Documentation
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut (DoubleTab & val_moy) const [protected, virtual]
Implements Traitement_particulier_NS_canal.
Definition at line 332 of file Traitement_particulier_NS_canal_VDF.cpp.
References Equation_base::get_modele(), Traitement_particulier_NS_base::mon_equation, Zone::nb_elem(), ref_cast, Traitement_particulier_NS_canal::Tab_recap, TURBULENCE, Ref_Objet_U::valeur(), Ref_Navier_Stokes_std::valeur(), Champ_Fonc::valeurs(), Mod_turb_hyd_base::viscosite_turbulente(), and Zone_dis_base::zone().
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
// const DoubleTab& xp = zone_VDF.xp();
  const RefObjU& modele_turbulence = mon_equation.valeur().get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  const DoubleTab& nu_t = mod_turb.viscosite_turbulente()->valeurs();
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem,i;
// double y;
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
// y=xp(num_elem,1);
      i= Tab_recap(num_elem,2);
      val_moy(i,12) += nu_t[num_elem];
    }
}
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp (DoubleTab & val_moy) const [protected, virtual]
Implements Traitement_particulier_NS_canal.
Definition at line 355 of file Traitement_particulier_NS_canal_VDF.cpp.
References Objet_U::dimension, Zone_VF::elem_faces(), Traitement_particulier_NS_base::mon_equation, Zone::nb_elem(), ref_cast, Traitement_particulier_NS_canal::Tab_recap, Traitement_particulier_NS_canal::Temp, Ref_Champ_base::valeur(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
// const DoubleTab& xp = zone_VDF.xp();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const DoubleTab& temperature = Temp.valeur().valeurs();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double u,v,wl,T;
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem,i;
  int face_x_0,face_x_1,face_y_0,face_y_1,face_z_0,face_z_1;
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
// y=xp(num_elem,1);
      T = temperature[num_elem];
      face_x_0 = elem_faces(num_elem,0);
      face_x_1 = elem_faces(num_elem,dimension);
      face_y_0 = elem_faces(num_elem,1);
      face_y_1 = elem_faces(num_elem,1+dimension);
      u = .5*(vitesse[face_x_0]+vitesse[face_x_1]);
      v = .5*(vitesse[face_y_0]+vitesse[face_y_1]);
      i=Tab_recap(num_elem,2);
// for (i=0; i<Ny; i++)     if(est_egal(y,Y[i])) break;
      val_moy(i,13) += T;
      val_moy(i,14) += T*T;
      val_moy(i,15) += u*T;
      val_moy(i,16) += v*T;
      if(dimension==3)
        {
          face_z_0 = elem_faces(num_elem,2);
          face_z_1 = elem_faces(num_elem,2+dimension);
          wl = .5*(vitesse[face_z_0]+vitesse[face_z_1]);
          val_moy(i,17) += wl*T;
        }
    }
}
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab & val_moy) const [protected, virtual]
Implements Traitement_particulier_NS_canal.
Definition at line 260 of file Traitement_particulier_NS_canal_VDF.cpp.
References Objet_U::dimension, DoubleTab::dimension(), Zone_VF::elem_faces(), Milieu_base::masse_volumique(), Traitement_particulier_NS_base::mon_equation, Zone::nb_elem(), ref_cast, Traitement_particulier_NS_canal::Tab_recap, Champ_Proto::valeurs(), Fluide_base::viscosite_dynamique(), and Zone_dis_base::zone().
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
// const DoubleTab& xp = zone_VDF.xp();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double u,v,wl;
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem,i;
  int face_x_0,face_y_0,face_y_1,face_z_0;
  const Fluide_base& le_fluide = ref_cast(Fluide_base,mon_equation->milieu());
  const DoubleTab& visco_dyn = le_fluide.viscosite_dynamique();
  const DoubleTab& tab_rho_elem = le_fluide.masse_volumique().valeurs();
  int taille_mu=visco_dyn.dimension(0);
  int taille_rho=tab_rho_elem.dimension(0);
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
// y=xp(num_elem,1);
      face_x_0 = elem_faces(num_elem,0);
// face_x_1 = elem_faces(num_elem,dimension);
      face_y_0 = elem_faces(num_elem,1);
      face_y_1 = elem_faces(num_elem,1+dimension);
// PQ : 12/10 : pour eviter de moyenner localement la vitesse u et w
// on fait le choix de "deplacer" celles-ci
// du centre de la face au centre de l'element
// en se basant sur le principe que l'ecoulement est homogene
// suivant les plans xz
// Pour v, la moyenne s'impose si l'on veut revenir au centre des elements
// u = .5*(vitesse[face_x_0]+vitesse[face_x_1]);
      u = vitesse[face_x_0];
      v = .5*(vitesse[face_y_0]+vitesse[face_y_1]);
      i= Tab_recap(num_elem,2);
      val_moy(i,0) += u;
      val_moy(i,1) += v;
      val_moy(i,3) += u*u;
      val_moy(i,4) += v*v;
      val_moy(i,6) += u*v;
      if(dimension==2)   val_moy(i,9) += sqrt(u*u);      //vitesse tangentielle pour calcul du frottement
      if(dimension==3)
        {
          face_z_0 = elem_faces(num_elem,2);
// face_z_1 = elem_faces(num_elem,2+dimension);
// w = .5*(vitesse[face_z_0]+vitesse[face_z_1]);
          wl = vitesse[face_z_0];
          val_moy(i,2) += wl;
          val_moy(i,5) += wl*wl;
          val_moy(i,7) += u*wl;
          val_moy(i,8) += v*wl;
          val_moy(i,9) += sqrt(u*u+wl*wl);      //vitesse tangentielle pour calcul du frottement
        }
      if (taille_rho==1)  val_moy(i,10) += tab_rho_elem(0,0);
      else                val_moy(i,10) += tab_rho_elem[num_elem];
      if (taille_mu==1)   val_moy(i,11) += visco_dyn(0,0);
      else                val_moy(i,11) += visco_dyn[num_elem];
    }
}
Objet_U * Traitement_particulier_NS_canal_VDF::cree_instance () [static]
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
int Traitement_particulier_NS_canal_VDF::duplique () const [virtual]
Implements Traitement_particulier_NS_canal.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
const Type_info * Traitement_particulier_NS_canal_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
const Type_info * Traitement_particulier_NS_canal_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
Entree & Traitement_particulier_NS_canal_VDF::lire (Entree & is) [virtual]
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 73 of file Traitement_particulier_NS_canal_VDF.cpp.
References lire().
{
  return Traitement_particulier_NS_canal::lire(is);
}
Entree& Traitement_particulier_NS_canal_VDF::lire (const Motcle & , Entree &)
Referenced by lire().
Sortie & Traitement_particulier_NS_canal_VDF::printOn (Sortie & is) const [protected, virtual]
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 48 of file Traitement_particulier_NS_canal_VDF.cpp.
{
  return is;
}
Entree & Traitement_particulier_NS_canal_VDF::readOn (Entree & is) [protected, virtual]
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 68 of file Traitement_particulier_NS_canal_VDF.cpp.
{
  return is;
}
void Traitement_particulier_NS_canal_VDF::remplir_Tab_recap (IntTab & Tab_rec) const [protected, virtual]
< element de test pour les ficitfs
< nombre total d'elements (reel + fict)
< tableau des elements deja effectue
< compteurs
< On dimenssione le tableau.
< boucle sur les elements fictifs
< si l'element en dessus est un element reel alors
< on affecte la meme valeur aux deux case haut et bas
< on garde la valeur de i pour ne pas reefectuer la boucle a chaque pas de temps.
< on affecte la meme valeur aux deux case haut et bas
< on garde la valeur de i pour ne pas reefectuer la boucle a chaque pas de temps.
< on utilise le compteur q qui ne nous sert plus pour verifier si on a trouver un equivalent.
< trouve est une case trop grand, mais plutot que de le redimentionner on utilise le critere taille -1
< on met fixe q qui ne peu repondre au prochain test. // correction on fixe q =0 car c'etais un faux probleme.
< faux si elem_test=-1 sinon remplit avec l'element en dessous
< on le traite alors comme un virtuel
< faux si elem_test=-1 sinon remplit avec l'element au dessus
< on le traite alors comme un virtuel
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 144 of file Traitement_particulier_NS_canal_VDF.cpp.
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), Zone_VDF::elem_voisin(), est_egal(), finl, Traitement_particulier_NS_base::mon_equation, Zone::nb_elem(), Zone::nb_elem_tot(), Traitement_particulier_NS_canal::Ny, ref_cast, IntTab::resize(), IntVect::size(), Zone_VF::xp(), Traitement_particulier_NS_canal::Y, and Zone_dis_base::zone().
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xp = zone_VDF.xp();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  int face; //recepteur des faces
  int elem_test,elem_test2; //!< element de test pour les ficitfs
  int nb_elem_tot = zone_VDF.zone().nb_elem_tot(); //!< nombre total d'elements (reel + fict)
  int nb_elems = zone_VDF.zone().nb_elem();
  IntTab trouve(1);//!< tableau des elements deja effectue
  double y=0;
  int i,num_elem; //!< compteurs
  int q=1; //Curseur pour les tableau haut
  trouve[0]=0;
  Tab_rec.resize(nb_elems,3); //!< On dimenssione le tableau.
  for (num_elem=nb_elems; num_elem<nb_elem_tot; num_elem++) //!< boucle sur les elements fictifs
    {
      face = elem_faces(num_elem,1+dimension);
      elem_test=zone_VDF.elem_voisin(num_elem,face,0);
      face = elem_faces(num_elem,1);
      elem_test2=zone_VDF.elem_voisin(num_elem,face,1);
      if ((elem_test>0) && (elem_test<nb_elems)) //!< si l'element en dessus est un element reel alors
        {
          trouve[q-1]=elem_test;
          q =q +1;
          trouve.resize(q);
          Tab_rec(elem_test,0)=num_elem; //!< on affecte la meme valeur aux deux case haut et bas
          Tab_rec(elem_test,1)=num_elem; //ainsi la fonction qui calcul les valeurs voie un element normal.
          y=xp(elem_test,1);
          for (i=0; i<Ny; i++)
            {
              if(est_egal(y,Y[i]))
                break;
            }
          Tab_rec(elem_test,2)=i; //!< on garde la valeur de i pour ne pas reefectuer la boucle a chaque pas de temps.
        }
      else if ((elem_test2<nb_elems)&&(elem_test2>0)) //sinon si l'element en dessous est un element reel alors
        {
          trouve[q-1]=elem_test2;
          q =q +1;
          trouve.resize(q);
          Tab_rec(elem_test2,0)=num_elem; //!< on affecte la meme valeur aux deux case haut et bas
          Tab_rec(elem_test2,1)=num_elem; //ainsi la fonction qui calcul les valeurs voie un element normal.
          y=xp(elem_test2,1);
          for (i=0; i<Ny; i++)
            {
              if(est_egal(y,Y[i]))
                break;
            }
          Tab_rec(elem_test2,2)=i; //!< on garde la valeur de i pour ne pas reefectuer la boucle a chaque pas de temps.
        }
// sinon rien
    }
  Cerr << "Traitement particulier canal : Il y a une amelioration a apporter aux face de bord !! " << finl;
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
      q=0;//!< on utilise le compteur q qui ne nous sert plus pour verifier si on a trouver un equivalent.
      for(i=0; i<(trouve.size()-1); i++) //!< trouve est une case trop grand, mais plutot que de le redimentionner on utilise le critere taille -1
        if(num_elem==trouve[i])
          {
            q = 0;  //!< on met fixe q qui ne peu repondre au prochain test. // correction on fixe q =0 car c'etais un faux probleme.
            break;
          }
// en realite lambda explose a l'interface.
      if(q==0) //
        {
          face=elem_faces(num_elem,1); //face inferieure
          elem_test=zone_VDF.elem_voisin(num_elem,face,1);
          if (elem_test+1)
            {
              Tab_rec(num_elem,1)=elem_test; //!< faux si elem_test=-1 sinon remplit avec l'element en dessous
            }
          else
            {
              Tab_rec(num_elem,1)=zone_VDF.elem_voisin(num_elem,elem_faces(num_elem,1+dimension),0); //!< on le traite alors comme un virtuel
            }
          face= elem_faces(num_elem,1+dimension); //face superieure
          elem_test=zone_VDF.elem_voisin(num_elem,face,0);
          if (elem_test+1)
            {
              Tab_rec(num_elem,0)=elem_test; //!< faux si elem_test=-1 sinon remplit avec l'element au dessus
            }
          else
            {
              Tab_rec(num_elem,0)=zone_VDF.elem_voisin(num_elem,elem_faces(num_elem,1),1); //!< on le traite alors comme un virtuel
            }
          y = xp(num_elem,1);
          for (i=0; i<Ny; i++)
            if(est_egal(y,Y[i])) break;
          Tab_rec(num_elem,2)=i;
        }
    }
}
void Traitement_particulier_NS_canal_VDF::remplir_Y (DoubleVect & tab_Y, DoubleVect & tab_compt, int & nNy) const [protected, virtual]
Implements Traitement_particulier_NS_canal.
Definition at line 78 of file Traitement_particulier_NS_canal_VDF.cpp.
References est_egal(), Traitement_particulier_NS_base::mon_equation, Zone::nb_elem(), ref_cast, DoubleVect::resize(), Zone_VF::xp(), and Zone_dis_base::zone().
{
// On va initialiser les differents parametres membres de la classe
// utiles au calcul des differentes moyennes
// Initialisation de : Y, compt
  const Zone_dis_base& zdisbase = mon_equation->inconnue().zone_dis_base();
  const Zone_VF& zone_VF = ref_cast(Zone_VF, zdisbase);
  const DoubleTab& xp = zone_VF.xp();
  int nb_elems = zone_VF.zone().nb_elem();
  int num_elem,j,indic,trouve;
  double y;
  j=0;
  indic = 0;
  tab_Y.resize(1);
  tab_compt.resize(1);
  tab_Y = -100.;
  tab_compt = 0;
// Remplissage du tableau Y
//
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
      y = xp(num_elem,1);
      trouve = 0;
      for (j=0; j<indic+1; j++)
        {
          if(est_egal(y,tab_Y[j]))
            {
              tab_compt[j] ++;
              j=indic+1;
              trouve = 1;
              break;
            }
        }
      if (trouve==0)
        {
          tab_Y[indic]=y;
          tab_compt[indic] ++;
          indic++;
          tab_Y.resize(indic+1);
          tab_Y(indic)=-100.;
          tab_compt.resize(indic+1);
        }
    }
  nNy = indic;
  tab_Y.resize(nNy);
  tab_compt.resize(nNy);
}
const Traitement_particulier_NS_canal_VDF & Traitement_particulier_NS_canal_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
Traitement_particulier_NS_canal_VDF & Traitement_particulier_NS_canal_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
unsigned Traitement_particulier_NS_canal_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Traitement_particulier_NS_canal_VDF.cpp.
Member Data Documentation
const Type_info Traitement_particulier_NS_canal_VDF::info_obj [static]
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 44 of file Traitement_particulier_NS_canal_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Traitement_particulier_NS_canal_VDF.h
src/VDF/Traitement_particulier_NS_canal_VDF.cpp