TRUST: Memoire Class Reference
Memoire Class Reference
La memoire de Trio-U.
#include <Memoire.h>
Public Member Functions
int add (Objet_U *)
Ajoute un Objet_U dans la Memoire de TRUST.
int suppr (int)
Suppression de la memoire de l'Objet_U de numero num
L'Objet_U n'est pas supprime, seul son pointeur dans la memoire l'est.
Objet_U & objet_u (int)
Retoune une reference sur l'Objet_U de rang num dans la memoire.
const Objet_U & objet_u (int) const
Retoune une reference constante sur l'Objet_U de rang num dans la memoire.
Objet_U * objet_u_ptr (int)
Retoune un pointeur sur l'Objet_U de rang num dans la memoire.
const Objet_U * objet_u_ptr (int) const
Retoune un pointeur constant sur l'Objet_U de rang num dans la memoire.
int rang (const Nom &type, const Nom &nom) const
Retourne le rang dans la memoire de l'objet de type et de nom indiques.
int rang (const Nom &nom) const
Retourne le rang dans la memoire de l'objet de nom indique.
void compacte ()
Compacte la memoire
Ce compactage est effectue automatiquement lorsqu'il devient necessaire.
~Memoire ()
Destruction de la memoire
Supprime les zone de travail pour les Objet_U, les double et les int
Sort (exit) avec un code 0.
Double_ptr_trav * add_trav_double (int n)
Ajoute une zone de travail "double" dans la memoire.
Int_ptr_trav * add_trav_int (int n)
Ajoute une zone de travail "int" dans la memoire.
template<typename _TYPE_ >
std::enable_if< std::is_same< _TYPE_, double >::value, TRUST_ptr_trav< _TYPE_ > * >::type add_trav (int n)
template<typename _TYPE_ >
std::enable_if< std::is_same< _TYPE_, int >::value, TRUST_ptr_trav< _TYPE_ > * >::type add_trav (int n)
int verifie () const
Verifie le contenu de toutes les cases de la memoire.
int imprime () const
Imprime un etat sur la memoire sur la sortie des erreurs.
Static Public Member Functions
static Memoire & Instance ()
Retourne un pointeur sur l'instance de la memoire
Cree un nouvel objet memoire si aucune instance n'a deja ete creee.
Protected Member Functions
Memoire ()
Constructeur
Initialize une zone de travail pour les Objet_U, les "double" et les "int".
Private Attributes
int size
Memoire_ptr * data
Double_ptr_trav * trav_double
Int_ptr_trav * trav_int
Static Private Attributes
static int step =4096
static int prems =0
static Memoire * _instance = 0
Friends
Sortie & operator<< (Sortie &, const Memoire &)
Operateur d'affichage d'un etat de la memoire mem sur le flot de sortie os.
Detailed Description
La memoire de Trio-U.
Definition at line 25 of file Memoire.h.
Constructor & Destructor Documentation
~Memoire()
Memoire::~Memoire ()
Destruction de la memoire
Supprime les zone de travail pour les Objet_U, les double et les int
Sort (exit) avec un code 0.
Definition at line 679 of file Memoire.cpp.
{
// GF on a deja tout detruit avant.
  return;
  if (data)
    {
      int i;
      for(i=0; i<size; i++)
        if(! data[i].libre())
          {
            Cerr << finl;
            Cerr << i << " ";
            const Objet_U& obj=objet_u(i);
            Cerr << " :: ";
            Cerr << "TYPE :" << obj.le_type() << finl;
          }
      delete[] data;
      delete trav_double;
      delete trav_int;
      data=0;
    }
  Cerr << "Memory destruction " << finl;
  Cerr << "Max Memory Size : " << max_sz_mem << finl;
  Cerr << "Memory size min : " << min_sz_mem << finl;
  Cerr << "Memory size used in Ko : " << (max_sz_mem-min_sz_mem)/1024 << finl;
  Process::exit();
}
References Cerr, data, Process::exit(), finl, Objet_U::le_type(), max_sz_mem, min_sz_mem, objet_u(), size, trav_double, and trav_int.
Memoire()
Memoire::Memoire () protected
Constructeur
Initialize une zone de travail pour les Objet_U, les "double" et les "int".
Definition at line 68 of file Memoire.cpp.
                 : size(step), data(new Memoire_ptr[step]),
  trav_double(new Double_ptr_trav()), trav_int(new Int_ptr_trav())
{
// Cerr << "prems="<<prems<<" step="<<step<<finl;
  for(int i=prems; i<size; i++)
    data[i].next=i+1;
// minfo = mallinfo();
// min_sz_mem = minfo.arena;
// max_sz_mem = min_sz_mem;
}
References data, next(), prems, and size.
Referenced by Instance().
Member Function Documentation
add()
int Memoire::add (Objet_U * obj)
Ajoute un Objet_U dans la Memoire de TRUST.
Returns
int
Signification: le numero affecte a l'objet dans la memoire
Contraintes:
Definition at line 95 of file Memoire.cpp.
{
  assert(_instance != 0);
  compteur++;
  if(prems<size)
    {
      const int num=prems;
      assert(data[num].libre());
      data[num].set(obj);
      prems=data[num].next;
      data[num].next = -1;
      assert(prems>=0);
// minfo = mallinfo();
// int sz_mem = minfo.arena;
// if(sz_mem > max_sz_mem) max_sz_mem = sz_mem;
      return num;
    }
  int old_size=size;
  int i;
  size*=2;
// Cerr<<"size "<<size<<" "<<size/step<<finl;
  Memoire_ptr* newdata=new Memoire_ptr[size];
  if(!newdata)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  Memoire_ptr  newptr(obj);
  for(i=0; i<old_size; i++)
    {
      newdata[i]=data[i];
      data[i].set(0);
    }
  newdata[old_size]=newptr;
  for(i=old_size; i<size; i++)
    newdata[i].next=i+1;
  if(data)
    delete[] data;
  data=newdata;
  prems=old_size+1;
// minfo = mallinfo();
// int sz_mem = minfo.arena;
// if(sz_mem > max_sz_mem) max_sz_mem = sz_mem;
  return old_size;
}
References _instance, Cerr, compteur, data, Process::exit(), finl, Memoire_ptr::next, next(), prems, Memoire_ptr::set(), and size.
Referenced by Objet_U::Objet_U().
add_trav() [1/2]
template<typename _TYPE_ > std::enable_if< std::is_same< _TYPE_, double >::value, TRUST_ptr_trav< _TYPE_ > * >::type Memoire::add_trav (int n) inline
Definition at line 46 of file Memoire.h.
{ return add_trav_double(n); }
References add_trav_double().
add_trav() [2/2]
template<typename _TYPE_ > std::enable_if< std::is_same< _TYPE_, int >::value, TRUST_ptr_trav< _TYPE_ > * >::type Memoire::add_trav (int n) inline
Definition at line 50 of file Memoire.h.
{ return add_trav_int(n); }
References add_trav_int().
add_trav_double()
Double_ptr_trav * Memoire::add_trav_double (int n) inline
Ajoute une zone de travail "double" dans la memoire.
Returns
Double_ptr_trav*
Signification: pointeur sur la zone creee
Contraintes:
Definition at line 83 of file Memoire.h.
{
  return trav_double->add(n);
}
References TRUST_ptr_trav< _TYPE_ >::add(), and trav_double.
Referenced by add_trav().
add_trav_int()
Int_ptr_trav * Memoire::add_trav_int (int n) inline
Ajoute une zone de travail "int" dans la memoire.
Returns
Int_ptr_trav*
Signification: pointeur sur la zone creee
Contraintes:
Definition at line 102 of file Memoire.h.
{
  return trav_int->add(n);
}
References TRUST_ptr_trav< _TYPE_ >::add(), and trav_int.
Referenced by add_trav().
compacte()
void Memoire::compacte ()
Compacte la memoire
Ce compactage est effectue automatiquement lorsqu'il devient necessaire.
Definition at line 433 of file Memoire.cpp.
{
// Cerr << "On compacte la memoire " << finl;
// Cerr << "size prems " << size << " " << prems << finl;
// Cerr << "avant" << finl;
  int i, compte=0;
  int* newnum=new int[size];
  if(!newnum)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  for(i=0; i<size; i++)
    if(data[i].libre())
      newnum[i]=-1;
    else
      newnum[i]=compte++;
  for(i=0; i<size; i++)
    if(newnum[i]>-1)
      {
        objet_u(i).change_num(newnum);
      }
  Memoire_ptr* newdata=new Memoire_ptr[compte];
  if(!newdata)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  for(i=0; i< size; i++)
    if(newnum[i]>-1)
      newdata[newnum[i]]=data[i];
  delete[] data;
  delete[] newnum;
  data=newdata;
  size=prems=compte;
  for(i=0; i<size; i++)
    data[i].next=i+1;
  verifie();
// Cerr << "la memoire est compactee" << finl;
// Cerr << "size prems " << size << " " << prems << finl;
}
References Cerr, Objet_U::change_num(), data, Process::exit(), finl, next(), objet_u(), prems, size, and verifie().
Referenced by suppr().
imprime()
int Memoire::imprime () const
Imprime un etat sur la memoire sur la sortie des erreurs.
Returns
int
Signification: code de retour; retourne toujours 1
Contraintes:
Definition at line 490 of file Memoire.cpp.
{
  assert(prems <=size);
  int i, tmp=0;
  for(i=0; i<size; i++)
    if(! data[i].libre()) tmp++;
  Cerr << "\n There are " << size << " memory squares";
  Cerr << "\n of which " << tmp << " ==(const char*)" << compteur << " are used" << finl;
  for(i=0; i<size; i++)
    {
      Cerr << i << " :: " << flush;
      if(! (data[i].libre()) )
        {
          const Objet_U& obj=data[i].obj();
          if (obj.numero() != i)
            Cerr << "error";
          else
            {
              Cerr << "TYPE :" << obj.le_type()<< flush;
              if (sub_type(O_U_Ptr, obj))
                {
                  const O_U_Ptr& x=ref_cast(O_U_Ptr, obj);
                  Cerr << " key: " << x << flush;
                }
              else
                Cerr << " NAME : " << obj.le_nom() << flush;
              Cerr << " address : " << (long)(&(obj))<< flush;
              Cerr << " SIZE : " << (int)(obj.taille_memoire())<< " octets "<< flush;
            }
        }
      else
        Cerr << "free ";
      Cerr << finl;
    }
  return 1;
}
References Cerr, compteur, data, finl, Objet_U::le_nom(), Objet_U::le_type(), Objet_U::numero(), Memoire_ptr::obj(), prems, ref_cast, size, sub_type, and Objet_U::taille_memoire().
Referenced by verifie().
Instance()
Memoire & Memoire::Instance () static
Retourne un pointeur sur l'instance de la memoire
Cree un nouvel objet memoire si aucune instance n'a deja ete creee.
Returns
Memoire*
Signification: pointeur sur l'instance de la memoire
Contraintes:
Definition at line 43 of file Memoire.cpp.
{
  if (_instance == 0)
    {
      _instance = new Memoire;
    }
  return *_instance;
}
References _instance, and Memoire().
Referenced by MD_Vector::copy(), O_U_Ptr::get_O_U_Ptr(), O_U_Ptr::get_O_U_Ptr_check(), Objet_U::Objet_U(), O_U_Ptr::recopie(), VTRUSTdata< _TYPE_ >::VTRUSTdata(), and Objet_U::~Objet_U().
objet_u() [1/2]
Objet_U & Memoire::objet_u (int num)
Retoune une reference sur l'Objet_U de rang num dans la memoire.
Returns
Objet_U&
Signification: reference sur l'Objet_U trouve
Contraintes:
Definition at line 290 of file Memoire.cpp.
{
  assert(num >=0);
  assert(num < size);
  assert(!data[num].libre());
  Objet_U& objet = data[num].obj();
  const int num_obj = objet.numero();
  if (num_obj != num)
    {
      Cerr << "Error in Objet_U & Memoire::objet_u(int num) " << finl;
      Cerr << " num                       = " << num << finl;
      std::cerr << " data[num].o_ptr           = " << &objet << std::endl;
      Cerr << " data[num].o_ptr->numero() = " << num_obj << finl;
      assert(0);
      Process::exit();
    }
  return objet;
}
References Cerr, data, Process::exit(), finl, Objet_U::numero(), Memoire_ptr::obj(), and size.
Referenced by compacte(), O_U_Ptr::get_O_U_Ptr(), O_U_Ptr::get_O_U_Ptr_check(), O_U_Ptr::recopie(), and ~Memoire().
objet_u() [2/2]
const Objet_U & Memoire::objet_u (int num) const
Retoune une reference constante sur l'Objet_U de rang num dans la memoire.
Returns
const Objet_U&
Signification: reference sur l'Objet_U trouve
Contraintes:
Definition at line 326 of file Memoire.cpp.
{
  assert(num >=0);
  assert(num < size);
  assert(!data[num].libre());
  Objet_U& objet = data[num].obj();
  const int num_obj = objet.numero();
  if (num_obj != num)
    {
      Cerr << "Error in const Objet_U & Memoire::objet_u(int num) " << finl;
      Cerr << " num                       = " << num << finl;
      std::cerr << " data[num].o_ptr           = " << &objet << std::endl;
      Cerr << " data[num].o_ptr->numero() = " << num_obj << finl;
      assert(0);
      Process::exit();
    }
  return objet;
}
References Cerr, data, Process::exit(), finl, Objet_U::numero(), Memoire_ptr::obj(), and size.
objet_u_ptr() [1/2]
Objet_U * Memoire::objet_u_ptr (int num)
Retoune un pointeur sur l'Objet_U de rang num dans la memoire.
Returns
Objet_U&
Signification: reference sur l'Objet_U trouve
Contraintes:
Definition at line 362 of file Memoire.cpp.
{
  assert(num >=0);
  assert(num < size);
  assert(!data[num].libre());
  Objet_U& objet = data[num].obj();
  const int num_obj = objet.numero();
  if (num_obj != num)
    {
      Cerr << "Error in Objet_U * Memoire::objet_u(int num) " << finl;
      Cerr << " num                       = " << num << finl;
      std::cerr << " data[num].o_ptr           = " << &objet << std::endl;
      Cerr << " data[num].o_ptr->numero() = " << num_obj << finl;
      assert(0);
      Process::exit();
    }
  return &objet;
}
References Cerr, data, Process::exit(), finl, Objet_U::numero(), Memoire_ptr::obj(), and size.
Referenced by MD_Vector::copy().
objet_u_ptr() [2/2]
const Objet_U * Memoire::objet_u_ptr (int num) const
Retoune un pointeur constant sur l'Objet_U de rang num dans la memoire.
Returns
Objet_U&
Signification: reference sur l'Objet_U trouve
Contraintes:
Definition at line 398 of file Memoire.cpp.
{
  assert(num >=0);
  assert(num < size);
  assert(!data[num].libre());
  Objet_U& objet = data[num].obj();
  const int num_obj = objet.numero();
  if (num_obj != num)
    {
      Cerr << "Error in const Objet_U * Memoire::objet_u(int num) " << finl;
      Cerr << " num                       = " << num << finl;
      std::cerr << " data[num].o_ptr           = " << &objet << std::endl;
      Cerr << " data[num].o_ptr->numero() = " << num_obj << finl;
      assert(0);
      Process::exit();
    }
  return &objet;
}
References Cerr, data, Process::exit(), finl, Objet_U::numero(), Memoire_ptr::obj(), and size.
rang() [1/2]
int Memoire::rang (const Nom & nom) const
Retourne le rang dans la memoire de l'objet de nom indique.
Returns
int
Signification: le rang de l'objet s'il est trouve dans la memoire, -1 sinon
Contraintes:
Definition at line 260 of file Memoire.cpp.
{
  Memoire_ptr* x=data;
  for(int i=0; i<size; i++)
    if( !( x->libre() ) )
      {
        if (((x->obj()).le_nom())==nom)
          return i;
        x++;
      }
  return -1;
}
References data, Memoire_ptr::libre(), Memoire_ptr::obj(), and size.
rang() [2/2]
int Memoire::rang (const Nom & type, const Nom & nom) const
Retourne le rang dans la memoire de l'objet de type et de nom indiques.
Returns
int
Signification: le rang de l'objet s'il est trouve dans la memoire, -1 sinon
Contraintes:
Definition at line 231 of file Memoire.cpp.
{
  Memoire_ptr* x=data;
  for(int i=0; i<size; i++)
    {
      if( !( x->libre() ) )
        if ( ((x->obj()).que_suis_je()==type) &&
             ((x->obj()).le_nom()==nom) )
          return i;
      x++;
    }
  return -1;
}
References data, Memoire_ptr::libre(), Memoire_ptr::obj(), and size.
suppr()
int Memoire::suppr (int num)
Suppression de la memoire de l'Objet_U de numero num
L'Objet_U n'est pas supprime, seul son pointeur dans la memoire l'est.
Returns
int
Signification: code de retour, retourne toujours 1
Contraintes:
Definition at line 157 of file Memoire.cpp.
{
// Cerr << "Suppression de " << num << finl;
  assert(!data[num].libre());
  data[num].next=prems;
  prems=num;
  data[num].set(0);
  compteur--;
  if((size>4*compteur)&&(size>step))
// if((size-compteur)>step)
    {
      compacte();
    }
  /*
    static int deb=0;
    if (compteur >500) deb=1;
    if ((deb)&&(compteur<3))
    {
    Cerr<<"here "<<compteur<<finl;
    int i;
    for(i=0; i<size; i++)
    if(! data[i].libre())
    {
    Cerr << finl;
    Cerr << i << " ";
    const Objet_U& obj=objet_u(i);
    Cerr << " :: ";
    Cerr << "TYPE :" << obj.le_type()<<finl;
    if(sub_type(Nom,obj)) Cerr << " NAME : " << obj.le_nom() <<finl;
    }
    }
  */
// GF quand on n'a plus d'objet_u on detruit tout
  if (compteur==0)
    {
// Cerr<<"delete data"<<finl;
      if (data)
        {
          delete[] data;
          delete trav_double;
          delete trav_int;
          data=0;
          delete _instance;
          _instance=0;
        }
    }
  return 1;
}
References _instance, compacte(), compteur, data, Memoire_ptr::next, prems, Memoire_ptr::set(), size, step, trav_double, and trav_int.
Referenced by Objet_U::~Objet_U().
verifie()
int Memoire::verifie () const
Verifie le contenu de toutes les cases de la memoire.
Returns
int
Signification: code de retour; retourne toujours 1
Contraintes:
Definition at line 542 of file Memoire.cpp.
{
  assert(prems <=size);
  for(int i=0; i<size; i++)
    {
      if(! (data[i].libre()) )
        {
          if ((data[i].obj()).numero() != i)
            {
              Cerr << "ERROR at the square " << i << finl;
              imprime();
              Process::exit();
            }
        }
    }
  return 1;
}
References Cerr, data, Process::exit(), finl, imprime(), prems, and size.
Referenced by compacte().
Friends And Related Function Documentation
operator<<
Sortie & operator<< (Sortie & , const Memoire &) friend
Operateur d'affichage d'un etat de la memoire mem sur le flot de sortie os.
Returns
Sortie& le flot de sortie modifie
Signification:
Contraintes:
Definition at line 580 of file Memoire.cpp.
{
  int i;
  int total=0;
  int tmp=0;
  int tmp1=0;
  for(i=0; i<mem.size; i++)
    if(! mem.data[i].libre()) tmp++;
  os << "\n il y a " << mem.size << " cases memoires";
  os << "\n dont " << tmp << " ==(const char*)" << compteur << " sont occupees" << finl;
  for(i=0; i<mem.size; i++)
    if(! mem.data[i].libre())
      {
        os << i << " ";
        const Objet_U& obj=mem.objet_u(i);
        os << " :: ";
        os << "TYPE :" << obj.le_type();
        if(sub_type(Nom,obj)) os << " NOM : " << obj.le_nom() ;
        os << " adresse : " << (long)(&(obj));
        const ArrOfInt* intA = dynamic_cast<const ArrOfInt*>(&obj);
        if(intA)
          {
            const ArrOfInt& toto = *intA;
            tmp = obj.taille_memoire() + (int) ((toto.size_array()*sizeof(int))/toto.ref_count());
            os << " TAILLE ArrOfInt : " << tmp<< " octets ";
            const IntVect* intV = dynamic_cast<const IntVect*>(&obj);
            if(intV)
              {
                const IntVect& titi = *intV;
                tmp1 = obj.taille_memoire() + (int) ((titi.size()*sizeof(int))/titi.ref_count());
                os << " dont : " << (tmp-tmp1) << " octets virtuels ";
              }
            os << "\n";
          }
        else
          {
            const ArrOfDouble* intAD = dynamic_cast<const ArrOfDouble*>(&obj);
            if(intAD)
              {
                const ArrOfDouble& toto = *intAD;
                tmp = obj.taille_memoire() + (int) ((toto.size_array()*sizeof(double))/toto.ref_count());
                os << " TAILLE ArrOfDouble : " << tmp<< " octets ";
                /* PL: Plante en P1Bulle donc je commente
                 * const DoubleVect* intVD = dynamic_cast<const DoubleVect*>(&obj);
                   if(intVD){
                   const DoubleVect& titi = *intVD;
                   tmp1 = obj.taille_memoire() + (int) ((titi.size()*sizeof(double))/titi.ref_count());
                   os << " dont : " << (tmp-tmp1) << " octets virtuels ";
                   } */
                os << "\n";
              }
            else
              {
                /*
                  if(sub_type(Matrice_Morse_Sym,obj)){
                  const Matrice_Morse_Sym& toto = ref_cast(Matrice_Morse_Sym,obj);
                  tmp = obj.taille_memoire() +
                  (int) (toto.nb_lignes()*sizeof(int)) +
                  (int) ((toto.nb_coeff()+1)*sizeof(int)) +
                  (int) (toto.nb_coeff()*sizeof(double));
                  os << " TAILLE Matrice_Morse_Sym : " << tmp<< " octets ";
                  os << "\n";
                  }
                  else
                */
                os << " TAILLE : " << (tmp=obj.taille_memoire())<< " octets \n ";
              }
          }
        total += tmp;
        os.flush();
      }
  os << "Taille memoire max: " <<  max_sz_mem << finl;
  os << "Taille memoire min: " <<  min_sz_mem << finl;
  os << "Taille memoire occupee en Mo: " <<  (max_sz_mem-min_sz_mem)/1024/1024 << finl;
  return os << "Occupation taille memoire totale en Mo: " << total/1024/1024 << finl;
}
Member Data Documentation
_instance
Memoire * Memoire::_instance = 0 static private
Definition at line 63 of file Memoire.h.
Referenced by add(), Instance(), and suppr().
data
Memoire_ptr* Memoire::data private
Definition at line 58 of file Memoire.h.
Referenced by add(), compacte(), imprime(), Memoire(), objet_u(), objet_u_ptr(), rang(), suppr(), verifie(), and ~Memoire().
prems
int Memoire::prems =0 static private
Definition at line 60 of file Memoire.h.
Referenced by add(), compacte(), imprime(), Memoire(), suppr(), and verifie().
size
int Memoire::size private
Definition at line 57 of file Memoire.h.
Referenced by add(), compacte(), imprime(), Memoire(), objet_u(), objet_u_ptr(), rang(), suppr(), verifie(), and ~Memoire().
step
int Memoire::step =4096 static private
Definition at line 59 of file Memoire.h.
Referenced by suppr().
trav_double
Double_ptr_trav* Memoire::trav_double private
Definition at line 61 of file Memoire.h.
Referenced by add_trav_double(), suppr(), and ~Memoire().
trav_int
Int_ptr_trav* Memoire::trav_int private
Definition at line 62 of file Memoire.h.
Referenced by add_trav_int(), suppr(), and ~Memoire().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Memoire.h
src/Kernel/Utilitaires/Memoire.cpp