TRUST: Discret_Thyd Class Reference
Discret_Thyd Class Reference
classe Discret_Thyd
Cette classe est la classe de base representant une discretisation
spatiale appliquee aux problemes de thermo-hydrauliques.
Les methodes virtuelles pures sont a implementer dans les classes
derivees pour typer et discretiser les champs portes par les
equations liees a la discretisation.
#include <Discret_Thyd.h>
Public Member Functions
Discret_Thyd ()
~Discret_Thyd () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void vitesse (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void translation (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void entcor (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void pression (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void pression_en_pa (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void divergence_U (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void gradient_P (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void concentration (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int=1, const Nom nom_champ="concentration") const
void porosite_volumique (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void diametre_hydraulique_elem (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void diametre_hydraulique_face (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void section_passage (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
virtual void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void grad_u (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
virtual void y_plus (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void grad_T (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch) const
virtual void h_conv (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch, Motcle &nom, int temp_ref) const
virtual void critere_Q (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void reynolds_maille (const Zone_dis &, const Fluide_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void courant_maille (const Zone_dis &, const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void estimateur_aposteriori (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, const Champ_Inc &, const Champ_Don &, Champ_Fonc &) const
virtual void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
Public Member Functions inherited from Discret_Thermique
Discret_Thermique ()
~Discret_Thermique () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void flux_neutronique (const Schema_Temps_base &sch, Zone_dis &z, Champ_Inc &ch, int nb_comp=1) const
void Fluctu_Temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void Flux_Chaleur_Turb (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
Public Member Functions inherited from Discretisation_base
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Discret_Thyd & self_cast (Objet_U &)
static const Discret_Thyd & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thermique
static const Type_info * info ()
static Discret_Thermique & self_cast (Objet_U &)
static const Discret_Thermique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discretisation_base
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thermique
static const Type_info info_obj
Static Public Attributes inherited from Discretisation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Public Types inherited from Discretisation_base
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Static Protected Attributes inherited from Discretisation_base
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Detailed Description
classe Discret_Thyd
Cette classe est la classe de base representant une discretisation
spatiale appliquee aux problemes de thermo-hydrauliques.
Les methodes virtuelles pures sont a implementer dans les classes
derivees pour typer et discretiser les champs portes par les
equations liees a la discretisation.
Definition at line 52 of file Discret_Thyd.h.
Constructor & Destructor Documentation
Discret_Thyd()
Discret_Thyd::Discret_Thyd ()
Definition at line 25 of file Discret_Thyd.cpp.
~Discret_Thyd()
Discret_Thyd::~Discret_Thyd () override
Definition at line 25 of file Discret_Thyd.cpp.
Member Function Documentation
concentration()
void Discret_Thyd::concentration (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch, int nb_constituants = 1, const Nom nom_champ = "concentration") const
Definition at line 342 of file Discret_Thyd.cpp.
{
  Cerr << "Concentration discretization " << finl;
  discretiser_champ("temperature",z.valeur(),nom_champ,"%",nb_constituants,sch.nb_valeurs_temporelles(),sch.temps_courant(),ch);
  ch->nommer(nom_champ);
  if (nb_constituants > 1)
    {
      ch->fixer_nature_du_champ(multi_scalaire);
      Noms noms(nb_constituants);
      for (int i=0; i<nb_constituants; i++)
        {
          noms[i] = nom_champ;
          Nom param(i);
          noms[i] += param;
          ch->fixer_nom_compo(i, noms[i]);
        }
    }
}
References Cerr, Discretisation_base::discretiser_champ(), finl, multi_scalaire, Schema_Temps_base::nb_valeurs_temporelles(), Objet_U::nommer(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Convection_Diffusion_Concentration::discretiser().
courant_maille()
virtual void Discret_Thyd::courant_maille (const Zone_dis & , const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const inline virtual
Reimplemented in VDF_discretisation.
Definition at line 92 of file Discret_Thyd.h.
  {
    Cerr << "Courant_maille keyword not available for this discretization." << finl;
    Process::exit();
  }
References Cerr, Process::exit(), and finl.
Referenced by Navier_Stokes_std::creer_champ().
creer_champ_vorticite()
void Discret_Thyd::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented in EF_discretisation, PolyMAC_discretisation, PolyMAC_P0_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 161 of file Discret_Thyd.cpp.
{
  Cerr << "Discret_Thyd::creer_champ_vorticite() does nothing" << finl;
  Cerr <<  que_suis_je() << "needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
critere_Q()
void Discret_Thyd::critere_Q (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented in VDF_discretisation, EF_discretisation, PolyMAC_discretisation, and VEF_discretisation.
Definition at line 194 of file Discret_Thyd.cpp.
{
// pour le VDF, on a besoin de la Zone_Cl_dis, mais pas pour le VEF
// -->> on passe quand meme l argument mais on n en fait rien!!!
  Cerr << "Discret_Thyd::critere_Q() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
diametre_hydraulique_elem()
void Discret_Thyd::diametre_hydraulique_elem (const Zone_dis & z, const Schema_Temps_base & sch, Champ_Fonc & ch) const
Definition at line 236 of file Discret_Thyd.cpp.
{
  Cerr << "Hydraulic diameter elem field discretization" << finl;
  const Zone_VF& zone_VF=ref_cast(Zone_VF, z.valeur());
  discretiser_champ("champ_elem",zone_VF,"diametre_hydraulique","m",1,sch.temps_courant(),ch);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,ch.valeur());
  ch_fonc.valeurs().ref(zone_VF.diametre_hydraulique_elem());
}
References Cerr, Zone_VF::diametre_hydraulique_elem(), Discretisation_base::discretiser_champ(), finl, TRUSTTab< _TYPE_ >::ref(), ref_cast, Schema_Temps_base::temps_courant(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Don_base::valeurs().
diametre_hydraulique_face()
void Discret_Thyd::diametre_hydraulique_face (const Zone_dis & z, const Schema_Temps_base & sch, Champ_Fonc & ch) const
Definition at line 245 of file Discret_Thyd.cpp.
{
  Cerr << "Hydraulic diameter face field discretization" << finl;
  const Zone_VF& zone_VF=ref_cast(Zone_VF, z.valeur());
  discretiser_champ("champ_face",zone_VF,"diametre_hydraulique_face","m",1,sch.temps_courant(),ch);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,ch.valeur());
  ch_fonc.valeurs().ref(zone_VF.diametre_hydraulique_face());
}
References Cerr, Zone_VF::diametre_hydraulique_face(), Discretisation_base::discretiser_champ(), finl, TRUSTTab< _TYPE_ >::ref(), ref_cast, Schema_Temps_base::temps_courant(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Don_base::valeurs().
distance_paroi_globale()
void Discret_Thyd::distance_paroi_globale (const Schema_Temps_base & , Zone_dis & , Champ_Fonc &) const virtual
Reimplemented in PolyMAC_discretisation.
Definition at line 274 of file Discret_Thyd.cpp.
{
  Cerr << "Discret_Thyd::distance_paroi() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
divergence_U()
void Discret_Thyd::divergence_U (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 118 of file Discret_Thyd.cpp.
{
  Cerr << "Velocity divergence discretization" << finl;
  discretiser_champ("divergence_vitesse",z.valeur(), "divergence_U", "m3/s", 1,1,
                    sch.temps_courant(),ch);
}
References Cerr, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Navier_Stokes_std::discretiser().
entcor()
void Discret_Thyd::entcor (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Definition at line 87 of file Discret_Thyd.cpp.
{
  Cerr << "Entcor discretization" << finl;
  discretiser_champ("vitesse",z.valeur(),"entcor","m/s",dimension,
                    sch.temps_courant(),ch);
}
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
estimateur_aposteriori()
virtual void Discret_Thyd::estimateur_aposteriori (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , const Champ_Inc & , const Champ_Don & , Champ_Fonc &) const inline virtual
Definition at line 98 of file Discret_Thyd.h.
  {
    Cerr << "estimateur_aposteriori keyword not available for this discretization." << finl;
    Cerr << "You should use it with the VEF_Aposteriori_discretisation !! " << finl;
    Process::exit();
  }
References Cerr, Process::exit(), and finl.
get_info()
const Type_info * Discret_Thyd::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 25 of file Discret_Thyd.cpp.
grad_T()
void Discret_Thyd::grad_T (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & eqn, Champ_Fonc & ch) const virtual
Reimplemented in EF_discretisation, PolyMAC_discretisation, and VEF_discretisation.
Definition at line 281 of file Discret_Thyd.cpp.
{
  Cerr << "Discret_Thyd::grad_T() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::creer_champ().
grad_u()
void Discret_Thyd::grad_u (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const virtual
Reimplemented in VDF_discretisation, VEF_discretisation, PolyMAC_discretisation, and PolyMAC_P0_discretisation.
Definition at line 335 of file Discret_Thyd.cpp.
{
  Cerr << "\nDiscret_Thyd::grad_u() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
gradient_P()
void Discret_Thyd::gradient_P (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 128 of file Discret_Thyd.cpp.
{
  Cerr << "Pressure gradient discretization" << finl;
  discretiser_champ("gradient_pression",z.valeur(), "gradient_pression", "m/s2", dimension,1,
                    sch.temps_courant(),ch);
}
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Navier_Stokes_std::discretiser().
h_conv()
void Discret_Thyd::h_conv (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & eqn, Champ_Fonc & ch, Motcle & nom, int temp_ref) const virtual
Reimplemented in EF_discretisation, PolyMAC_discretisation, and VEF_discretisation.
Definition at line 288 of file Discret_Thyd.cpp.
{
  Cerr << "Discret_Thyd::h_conv() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::creer_champ().
info()
const Type_info * Discret_Thyd::info () static
Definition at line 25 of file Discret_Thyd.cpp.
porosite_volumique()
void Discret_Thyd::porosite_volumique (const Zone_dis & z, const Schema_Temps_base & sch, Champ_Fonc & ch) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Definition at line 228 of file Discret_Thyd.cpp.
{
  Cerr << "Volumic porosity field discretization" << finl;
  const Zone_VF& zone_VF=ref_cast(Zone_VF, z.valeur());
  discretiser_champ("champ_elem",zone_VF,"porosite_volumique",".",1,sch.temps_courant(),ch);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,ch.valeur());
  ch_fonc.valeurs().ref(zone_VF.porosite_elem());
}
References Cerr, Discretisation_base::discretiser_champ(), finl, Zone_VF::porosite_elem(), TRUSTTab< _TYPE_ >::ref(), ref_cast, Schema_Temps_base::temps_courant(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Don_base::valeurs().
Referenced by Navier_Stokes_std::creer_champ().
pression()
void Discret_Thyd::pression (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 97 of file Discret_Thyd.cpp.
{
  Cerr << "Pressure discretization" << finl;
  discretiser_champ("pression",z.valeur(),"pression","Pa.m3/kg",1,
                    sub_type(Schema_Implicite_base, sch) ? ref_cast(Schema_Implicite_base, sch).solveur()->nb_valeurs_temporelles_pression() : 1,
                    sch.temps_courant(),ch);
}
References Cerr, Discretisation_base::discretiser_champ(), finl, ref_cast, sub_type, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Navier_Stokes_std::discretiser().
pression_en_pa()
void Discret_Thyd::pression_en_pa (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 107 of file Discret_Thyd.cpp.
{
  Cerr << "Pressure pa discretization" << finl;
  discretiser_champ("pression",z.valeur(),"pression_pa","Pa",1,
                    sub_type(Schema_Implicite_base, sch) ? ref_cast(Schema_Implicite_base, sch).solveur()->nb_valeurs_temporelles_pression() : 1,
                    sch.temps_courant(),ch);
}
References Cerr, Discretisation_base::discretiser_champ(), finl, ref_cast, sub_type, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Navier_Stokes_std::discretiser().
printOn()
Sortie & Discret_Thyd::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 42 of file Discret_Thyd.cpp.
{
  return s;
}
proprietes_physiques_fluide_Ostwald()
void Discret_Thyd::proprietes_physiques_fluide_Ostwald (const Zone_dis & , Fluide_Ostwald & , const Navier_Stokes_std & , const Champ_Inc &) const virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented in EF_discretisation, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 325 of file Discret_Thyd.cpp.
{
  Cerr << "Discret_Thyd::proprietes_physiques_fluide_Ostwald() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Fluide_Ostwald::discretiser().
readOn()
Entree & Discret_Thyd::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 62 of file Discret_Thyd.cpp.
{
  return s ;
}
reynolds_maille()
virtual void Discret_Thyd::reynolds_maille (const Zone_dis & , const Fluide_base & , const Champ_Inc & , Champ_Fonc &) const inline virtual
Reimplemented in VDF_discretisation.
Definition at line 86 of file Discret_Thyd.h.
  {
    Cerr << "Reynolds_maille keyword not available for this discretization." << finl;
    Process::exit();
  }
References Cerr, Process::exit(), and finl.
Referenced by Navier_Stokes_std::creer_champ().
section_passage()
void Discret_Thyd::section_passage (const Zone_dis & z, const Schema_Temps_base & sch, Champ_Fonc & ch) const
Definition at line 254 of file Discret_Thyd.cpp.
{
  Cerr << "Section passage field discretization" << finl;
  const Zone_VF& zone_VF=ref_cast(Zone_VF, z.valeur());
  discretiser_champ("champ_face",zone_VF,"section_passage","m2",dimension,sch.temps_courant(),ch);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,ch.valeur());
  DoubleVect& tab=ch_fonc.valeurs();
  tab.inject_array(zone_VF.section_passage_face());
// tab = zone_VF.section_passage_face();
}
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, TRUSTArray< _TYPE_ >::inject_array(), ref_cast, Zone_VF::section_passage_face(), Schema_Temps_base::temps_courant(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Don_base::valeurs().
self_cast() [1/2]
const Discret_Thyd & Discret_Thyd::self_cast (const Objet_U & r) static
Definition at line 25 of file Discret_Thyd.cpp.
self_cast() [2/2]
Discret_Thyd & Discret_Thyd::self_cast (Objet_U & r) static
Definition at line 25 of file Discret_Thyd.cpp.
taux_cisaillement()
virtual void Discret_Thyd::taux_cisaillement (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const inline virtual
Reimplemented in PolyMAC_P0_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 105 of file Discret_Thyd.h.
  {
    Cerr << "Taux_cisaillement keyword not available for this discretization." << finl;
    Process::exit();
  }
References Cerr, Process::exit(), and finl.
Referenced by Navier_Stokes_std::creer_champ().
translation()
void Discret_Thyd::translation (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Definition at line 77 of file Discret_Thyd.cpp.
{
  Cerr << "Translation discretization" << finl;
  discretiser_champ("vitesse",z.valeur(),"translation","m/s",dimension,
                    sch.temps_courant(),ch);
}
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
vitesse()
void Discret_Thyd::vitesse (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch, int nb_comp = 1) const
Definition at line 66 of file Discret_Thyd.cpp.
{
  Cerr << "Velocity discretization" << finl;
  discretiser_champ("vitesse",z.valeur(),"vitesse","m/s",dimension * nb_comp,sch.nb_valeurs_temporelles(),
                    sch.temps_courant(),ch);
}
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::nb_valeurs_temporelles(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Navier_Stokes_Fluide_Dilatable_base::discretiser(), Navier_Stokes_std::discretiser_vitesse(), and QDM_Multiphase::discretiser_vitesse().
y_plus()
void Discret_Thyd::y_plus (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const virtual
Reimplemented in VDF_discretisation, EF_discretisation, PolyMAC_discretisation, and VEF_discretisation.
Definition at line 265 of file Discret_Thyd.cpp.
{
// pour le VDF, on a besoin de la Zone_Cl_dis, mais pas pour le VEF
// -->> on passe quand meme l argument mais on n en fait rien!!!
  Cerr << "Discret_Thyd::y_plus() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
Member Data Documentation
info_obj
const Type_info Discret_Thyd::info_obj static
Definition at line 54 of file Discret_Thyd.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Discret_Thyd.h
src/ThHyd/Incompressible/Discret_Thyd.cpp