TRUST: interface_CALCULSI Class Reference
interface_CALCULSI Class Reference
#include <interface_CALCULSI.h>
Public Member Functions
void initialiser_les_commons ()
void init ()
void init_sans_initialiser_les_commons ()
void check_common ()
void compare_common ()
void set_param (Param &)
void dump (Sortie &)
void init_from_common ()
void init_from_file (const Nom &)
void Compute (const int nbnn, const ArrOfDouble &co3d, const ArrOfDouble &poro, const int ip, const int npgau, const ArrOfDouble &xgau, const ArrOfDouble &frgau, const ArrOfDouble &dfrgau, const ArrOfDouble &poigau, ArrOfDouble &detj, const ArrOfDouble &cnorme, ArrOfDouble &si) const
Detailed Description
Definition at line 23 of file interface_CALCULSI.h.
Member Function Documentation
check_common()
void interface_CALCULSI::check_common ()
Definition at line 47 of file interface_CALCULSI.cpp.
{
}
compare_common()
void interface_CALCULSI::compare_common ()
Definition at line 51 of file interface_CALCULSI.cpp.
{
}
Compute()
void interface_CALCULSI::Compute (const int nbnn, const ArrOfDouble & co3d, const ArrOfDouble & poro, const int ip, const int npgau, const ArrOfDouble & xgau, const ArrOfDouble & frgau, const ArrOfDouble & dfrgau, const ArrOfDouble & poigau, ArrOfDouble & detj, const ArrOfDouble & cnorme, ArrOfDouble & si) const
Definition at line 55 of file interface_CALCULSI.cpp.
{
  F77NAME(CALCULSI)(&nbnn,  co3d.addr(),  poro.addr(), &ip, &npgau,  xgau.addr(),  frgau.addr(),  dfrgau.addr(),  poigau.addr(),  detj.addr(),  cnorme.addr(),  si.addr());
}
References TRUSTArray< _TYPE_ >::addr(), and F77NAME.
Referenced by ajouter_bord().
dump()
void interface_CALCULSI::dump (Sortie & os)
Definition at line 67 of file interface_CALCULSI.cpp.
{
  Param param("interface_CALCULSI");
  set_param(param);
  param.print(os);
}
References Param::print(), and set_param().
init()
void interface_CALCULSI::init ()
Definition at line 36 of file interface_CALCULSI.cpp.
{
  initialiser_les_commons();
  init_sans_initialiser_les_commons();
}
References init_sans_initialiser_les_commons(), and initialiser_les_commons().
init_from_common()
void interface_CALCULSI::init_from_common ()
Definition at line 44 of file interface_CALCULSI.cpp.
{
}
init_from_file()
void interface_CALCULSI::init_from_file (const Nom & nom_fic)
Definition at line 59 of file interface_CALCULSI.cpp.
{
  LecFicDiffuse entree(nom_fic);
  Param param("interface_CALCULSI");
  set_param(param);
  param.read(entree);
}
References Param::read(), and set_param().
init_sans_initialiser_les_commons()
void interface_CALCULSI::init_sans_initialiser_les_commons ()
Definition at line 41 of file interface_CALCULSI.cpp.
{
}
Referenced by init().
initialiser_les_commons()
void interface_CALCULSI::initialiser_les_commons ()
Definition at line 33 of file interface_CALCULSI.cpp.
{
}
Referenced by init().
set_param()
void interface_CALCULSI::set_param (Param & param)
Definition at line 74 of file interface_CALCULSI.cpp.
{
}
Referenced by dump(), and init_from_file().
The documentation for this class was generated from the following files:
src/EF/fortran/interface_CALCULSI.h
src/EF/fortran/interface_CALCULSI.cpp