TRUST: Eval_Diff_VDF_Multi_inco_var Class Reference
Eval_Diff_VDF_Multi_inco_var Class Reference
class Eval_Diff_VDF_Multi_inco_var
Cette classe represente un evaluateur de flux diffusif
pour un vecteur d'inconnues avec une diffusivite par
inconnue. Le champ de diffusivite associe a chaque inconnue n'est pas constant.
#include <Eval_Diff_VDF_Multi_inco_var.h>
Public Member Functions
void mettre_a_jour () override
void associer (const Champ_base &) override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Protected Member Functions
double dist_face (int, int, int) const
Protected Attributes
Ref_Champ_base diffusivite_
DoubleTab dt_diffusivite
Detailed Description
class Eval_Diff_VDF_Multi_inco_var
Cette classe represente un evaluateur de flux diffusif
pour un vecteur d'inconnues avec une diffusivite par
inconnue. Le champ de diffusivite associe a chaque inconnue n'est pas constant.
See also
Evaluateur_VDF
Definition at line 31 of file Eval_Diff_VDF_Multi_inco_var.h.
Member Function Documentation
associer()
void Eval_Diff_VDF_Multi_inco_var::associer (const Champ_base & diffu) inline override virtual
Implements Eval_Diff_VDF.
Definition at line 53 of file Eval_Diff_VDF_Multi_inco_var.h.
{
  diffusivite_ = ref_cast(Champ_base,diffu);
  dt_diffusivite.ref(diffu.valeurs());
}
References diffusivite_, dt_diffusivite, TRUSTTab< _TYPE_ >::ref(), ref_cast, and Champ_Proto::valeurs().
compute_heq_impl()
double Eval_Diff_VDF_Multi_inco_var::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 42 of file Eval_Diff_VDF_Multi_inco_var.h.
  {
    return 1./(d0/dt_diffusivite(i,compo) + d1/dt_diffusivite(j,compo));
  }
References dt_diffusivite.
Referenced by Eval_Dift_VDF_Multi_inco_var::compute_heq_impl().
dist_face()
double Eval_Diff_VDF_Multi_inco_var::dist_face (int , int , int) const inline protected
get_diffusivite()
const Champ_base & Eval_Diff_VDF_Multi_inco_var::get_diffusivite () const inline override virtual
Implements Eval_Diff_VDF.
Definition at line 37 of file Eval_Diff_VDF_Multi_inco_var.h.
{ return diffusivite_ ; }
References diffusivite_.
mettre_a_jour()
void Eval_Diff_VDF_Multi_inco_var::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
Reimplemented in Eval_Dift_VDF_Multi_inco_var.
Definition at line 35 of file Eval_Diff_VDF_Multi_inco_var.h.
{ }
Referenced by Eval_Dift_VDF_Multi_inco_var::mettre_a_jour().
nu_1_impl()
double Eval_Diff_VDF_Multi_inco_var::nu_1_impl (int i, int compo) const inline
Definition at line 40 of file Eval_Diff_VDF_Multi_inco_var.h.
{ return dt_diffusivite(i, compo); }
References dt_diffusivite.
Referenced by Eval_Dift_VDF_Multi_inco_var::nu_1_impl().
nu_2_impl()
double Eval_Diff_VDF_Multi_inco_var::nu_2_impl (int i, int compo) const inline
Definition at line 41 of file Eval_Diff_VDF_Multi_inco_var.h.
{ return dt_diffusivite(i, compo); }
References dt_diffusivite.
Referenced by Eval_Dift_VDF_Multi_inco_var::nu_2_impl().
Member Data Documentation
diffusivite_
Ref_Champ_base Eval_Diff_VDF_Multi_inco_var::diffusivite_ protected
Definition at line 48 of file Eval_Diff_VDF_Multi_inco_var.h.
Referenced by associer(), and get_diffusivite().
dt_diffusivite
DoubleTab Eval_Diff_VDF_Multi_inco_var::dt_diffusivite protected
Definition at line 49 of file Eval_Diff_VDF_Multi_inco_var.h.
Referenced by associer(), compute_heq_impl(), nu_1_impl(), and nu_2_impl().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Diff_VDF_Multi_inco_var.h