TRUST: VerifierCoin Class Reference
VerifierCoin Class Reference
classe VerifierCoin
Interprete qui resoud un probleme:
[DANS LE JEU DE DONNEES] VerifierCoin pb
#include <VerifierCoin.h>
Public Member Functions
VerifierCoin ()
~VerifierCoin ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete:
resoudre un probleme
On cherche dynamiquement le type du probleme a resoudre
on resoud le probleme et on effectue les postraitements.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static VerifierCoin & self_cast (Objet_U &)
static const VerifierCoin & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static int expert_only =0
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a:
Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
classe VerifierCoin
Interprete qui resoud un probleme:
[DANS LE JEU DE DONNEES] VerifierCoin pb
Definition at line 33 of file VerifierCoin.h.
Constructor & Destructor Documentation
VerifierCoin()
VerifierCoin::VerifierCoin ()
Definition at line 24 of file VerifierCoin.cpp.
~VerifierCoin()
VerifierCoin::~VerifierCoin ()
Definition at line 24 of file VerifierCoin.cpp.
Member Function Documentation
cree_instance()
Objet_U * VerifierCoin::cree_instance () static
Definition at line 24 of file VerifierCoin.cpp.
duplique()
int VerifierCoin::duplique () const override virtual
Reimplemented from Interprete.
Definition at line 24 of file VerifierCoin.cpp.
get_info()
const Type_info * VerifierCoin::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 24 of file VerifierCoin.cpp.
info()
const Type_info * VerifierCoin::info () static
Definition at line 24 of file VerifierCoin.cpp.
interpreter_()
Entree & VerifierCoin::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete:
resoudre un probleme
On cherche dynamiquement le type du probleme a resoudre
on resoud le probleme et on effectue les postraitements.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< -1 indice de fin de fichier
< inversion des sommets
< creation d'un nouveau sommet au centre de gravite de l'element
Implements Interprete_geometrique_base.
Definition at line 87 of file VerifierCoin.cpp.
{
// XD verifiercoin interprete verifiercoin -1 This keyword subdivides inconsistent 2D/3D cells used with VEFPreP1B discretization. Must be used before the mesh is discretized. NL1 The Read_file option can be used only if the file.decoupage_som was previously created by TRUST. This option, only in 2D, reverses the common face at two cells (at least one is inconsistent), through the nodes opposed. In 3D, the option has no effect. NL2 The expert_only option deactivates, into the VEFPreP1B divergence operator, the test of inconsistent cells.
// XD  attr domain_name  ref_domaine dom 0 Name of the domaine
// XD  attr bloc verifiercoin_bloc bloc 0 not_set
// XD  verifiercoin_bloc objet_lecture nul 1 not_set
// XD  attr Read_file|Lire_fichier chaine filename 1 name of the *.decoupage_som file
// XD  attr expert_only rien expert_only 1 to not check the mesh
  associer_domaine(is);
  Domaine& dom=domaine();
  Zone& zone=dom.zone(0);
  if (zone.type_elem()->que_suis_je() != "Triangle" && zone.type_elem()->que_suis_je() != "Tetraedre")
    {
      Cerr << "Error for "<<que_suis_je() <<" interpreter : it can be applied only for triangular or tetraedral meshing." << finl;
      exit();
    }
  Nom decoup_som("");
  Param param(que_suis_je());
  param.ajouter("Lire_fichier|Read_file",&decoup_som);
  param.ajouter_flag("expert_only",&expert_only);
  param.lire_avec_accolades_depuis(is);
  int lecture_decoupage_som=(decoup_som!=""?1:0);
  if (Process::nproc()>1 && expert_only==0)
    {
      Cerr << que_suis_je() << " interpreter can be used only for sequential calculation." << finl;
      Cerr << "For parallel calculation, please use "<< que_suis_je() <<" interpreter" << finl;
      Cerr << "during the domain partitioning step." << finl;
      exit();
    }
// Pas de changement du maillage si option expert_only utilise
  Journal() << "expert_only= " << expert_only << finl;
  if (!expert_only)
    {
      Scatter::uninit_sequential_domain(dom);
      DoubleTab xp;
      zone.calculer_centres_gravite(xp);
      DoubleTab& sommets = dom.les_sommets();
      int nbsom=sommets.dimension(0);
      IntTab& les_elems=zone.les_elems();
      int nbelem=zone.nb_elem();
      int elem,ns,ns1,ne,somm;
      IntLists sommets_associes(nbsom);
      IntLists elements_associes(nbsom);
      IntVect test_double(nbsom);
      test_double=0;
// On parcourt les elements et pour un element ne, on parcourt ses sommets. Pour chaque sommet on detecte les
// sommets "voisins". Une fois tous les elements parcourus, s il n y a pas un doublon dans les sommets voisins
// d un sommet somm, il faut decouper l element (ou les elements) qui porte ce sommet.
      ne=0;
      while (ne<nbelem)
        {
          ns=0;
          while (ns<dimension+1)
            {
              somm = les_elems(ne,ns);
              elements_associes[somm].add_if_not(ne);
              ns1=0;
              while ((ns1<dimension+1) && (test_double(somm)==0))
                {
                  if (les_elems(ne,ns1)!=somm)
                    {
                      if (sommets_associes[somm].contient(les_elems(ne,ns1)))
                        test_double(somm)=1;
                      else
                        sommets_associes[somm].add(les_elems(ne,ns1));
                    }
                  ns1++;
                }
              ns++;
            }
          ne++;
        }
// On decoupe les elements pour le sommet qui pose probleme
// PQ : 25/05/07
// - soit de maniere automatique (tout sommet rattache qu'a un seul element)
// - soit a partir d'une liste de sommets (liste generee lors d'un pre-calcul et tenant compte du type de CL)
// avec comme option de decoupage dans ce cas (lue dans le fichier "decoupage_som") :
//
// 0 : decoupage traditionnel (centre de gravite)
// 1 : decoupage en passant par le sommet oppose de l'element voisin
      int option_decoupage=-1;
      int somm_lu,elem_opp,somm_opp,somm1,somm2;
      int dim_cas,nbsom_cas;
      LecFicDiffuse fic;
      if (lecture_decoupage_som)
        {
          Cerr<<"The file" << decoup_som <<" is checked before reading."<<finl;
          fic.ouvrir(decoup_som);
          if(fic.good())
            {
              fic >> option_decoupage;
              fic >> dim_cas;
              fic >> nbsom_cas;
              if(dim_cas!=dimension)
                {
                  Cerr << "Error for " <<que_suis_je()<<"::interpreter_" << finl;
                  Cerr << "The file " << decoup_som << " is planned for a case of dimension " << dim_cas << "D" << finl;
                  Cerr << "while the considered domain " << dom.le_nom() << " has a dimension " << dimension << "D." << finl;
                  Process::exit();
                }
              if(nbsom!=nbsom_cas)
                {
                  Cerr << "Error for " <<que_suis_je()<<"::interpreter_" << finl;
                  Cerr << "The nodes number (" <<nbsom_cas<< ") readen in the file " << decoup_som << finl;
                  Cerr << "dot not correspond to those of the meshing (" << nbsom << ")" << finl;
                  Cerr << "Please check that the file you have specified " << decoup_som << finl;
                  Cerr << "is the one to consider for this meshing." << finl;
                  Process::exit();
                }
            }
          else
            {
              Cerr << "Error for " <<que_suis_je()<<"::interpreter_" << finl;
              Cerr << "Problem while trying to open the file " << decoup_som << finl;
              Process::exit();
            }
          Cerr << "option_decoupage " << option_decoupage << finl;
        }
      for (somm=0; somm<nbsom; somm++)
        {
// On decoupe les elements pour le sommet qui pose probleme
          if (test_double(somm)==0)
            {
              if(lecture_decoupage_som)
                {
                  fic >> somm_lu >> somm_opp >> somm1 >> somm2;
                  if (dimension==3)
                    {
                      int somm3;
                      fic >> somm3;
                    }
                  fic >> elem >> elem_opp;
                  if(somm_lu!=-1) somm = somm_lu; //!< -1 indice de fin de fichier
                  if(nbsom<=somm)
                    {
                      Cerr << "Error in VerifierCoin::interpreter" << finl;
                      Cerr << "The node " << somm << " is not found." << finl;
                      Cerr << "Check the .Zones files are up to date with your mesh file." << finl;
                      Process::exit();
                    }
                }
              Cerr<<"-> VerifierCoin is applied on the node "<<somm<< " of coordinates: ";
              for(int dir=0; dir<dimension; dir++) Cerr<<sommets(somm,dir)<<" ";
              Cerr<<"..."<<finl;
              IntList_Curseur liste_elem(elements_associes[somm]);
              int size_elem= elements_associes[somm].size();
              if (option_decoupage==1 && dimension==2 && somm_lu!=-1)  //!< inversion des sommets
                {
                  les_elems(elem,0) = somm ;
                  les_elems(elem,1) = somm_opp ;
                  les_elems(elem,2) = somm1 ;
                  les_elems(elem_opp,0) = somm ;
                  les_elems(elem_opp,1) = somm_opp ;
                  les_elems(elem_opp,2) = somm2 ;
                }
              else //!< creation d'un nouveau sommet au centre de gravite de l'element
                {
                  for (int k=0; k<size_elem; k++)
                    {
                      elem=liste_elem.valeur();
// On cree un sommet au centre de gravite de l'element
                      int nouveau_sommet=sommets.dimension(0);
                      sommets.resize(nouveau_sommet+1, dimension);
                      for(int j=0; j<dimension; j++)
                        sommets(nouveau_sommet,j)=xp(elem,j);
// On divise l'element elem en dimension+1 elements
                      int oldsz=les_elems.dimension(0);
                      les_elems.resize(oldsz+dimension, dimension+1);
                      Cerr << "-> The element number " << elem <<" is cut in " << dimension+1 << " elements." << finl;
// On recupere les sommets de l'element elem
                      int i0=les_elems(elem,0);
                      int i1=les_elems(elem,1);
                      int i2=les_elems(elem,2);
// On affecte les sommets aux nouveaux elements
                      les_elems(elem,0)=i0;
                      les_elems(elem,1)=i1;
                      les_elems(elem,2)=nouveau_sommet;
                      les_elems(oldsz,0)=i1;
                      les_elems(oldsz,1)=i2;
                      les_elems(oldsz,2)=nouveau_sommet;
                      les_elems(oldsz+1,0)=i0;
                      les_elems(oldsz+1,1)=i2;
                      les_elems(oldsz+1,2)=nouveau_sommet;
                      if (dimension==3)
{
                          int i3=les_elems(elem,3);
                          les_elems(elem,3)=i3;
                          les_elems(oldsz,3)=i3;
                          les_elems(oldsz+1,3)=i3;
                          les_elems(oldsz+2,0)=i0;
                          les_elems(oldsz+2,1)=i1;
                          les_elems(oldsz+2,2)=i2;
                          les_elems(oldsz+2,3)=nouveau_sommet;
                        }
                      mettre_a_jour_sous_zone(zone,elem,oldsz,dimension);
                      ++liste_elem;
                    }
                }//!< option_decoupage
            }
        }
      Scatter::init_sequential_domain(dom);
    }
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Interprete_geometrique_base::associer_domaine(), Zone::calculer_centres_gravite(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), expert_only, finl, Lec_Diffuse_base::good(), Scatter::init_sequential_domain(), Process::Journal(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Param::lire_avec_accolades_depuis(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_elem(), Process::nproc(), LecFicDiffuse::ouvrir(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::resize(), TRUSTLists< _TYPE_ >::size(), Zone::type_elem(), Scatter::uninit_sequential_domain(), TRUSTList_Curseur< _TYPE_ >::valeur(), and Domaine::zone().
printOn()
Sortie & VerifierCoin::printOn (Sortie & os) const override protected virtual
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 43 of file VerifierCoin.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & VerifierCoin::readOn (Entree & is) override protected virtual
Simple appel a:
Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 64 of file VerifierCoin.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const VerifierCoin & VerifierCoin::self_cast (const Objet_U & r) static
Definition at line 24 of file VerifierCoin.cpp.
self_cast() [2/2]
VerifierCoin & VerifierCoin::self_cast (Objet_U & r) static
Definition at line 24 of file VerifierCoin.cpp.
taille_memoire()
unsigned VerifierCoin::taille_memoire () const override virtual
Reimplemented from Interprete.
Definition at line 24 of file VerifierCoin.cpp.
Member Data Documentation
expert_only
int VerifierCoin::expert_only =0 static
Definition at line 38 of file VerifierCoin.h.
Referenced by Op_Div_VEFP1B_Elem::degres_liberte(), and interpreter_().
info_obj
const Type_info VerifierCoin::info_obj static
Definition at line 35 of file VerifierCoin.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/VerifierCoin.h
src/VEF/Zones/VerifierCoin.cpp