TRUST: Quadrangle_VEF Class Reference
Quadrangle_VEF Class Reference
Classe Quadrangle_VEF
Cette classe represente l'element geometrique Quadrangle_VEF.
Un Quadrangle_VEF a 4 faces, 4 sommets et un seul type de face ayant
2 sommets par face.
#include <Quadrangle_VEF.h>
Public Member Functions
Quadrangle_VEF ()
~Quadrangle_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int nb_som () const override
Renvoie le nombre de sommets d'un Quadrangle_VEF: 4.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 0, car l'element geometrique
Quadrangle_VEF n'est pas de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un Quadrangle_VEF = "GOLGOTH24".
int contient (const ArrOfDouble &, int) const override
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un Quadrangle_VEF n'a qu'un seul type de face.
void reordonner () override
Reordonne.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
voir ElemGeomBase::get_tab_faces_sommets_locaux
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Quadrangle_VEF & self_cast (Objet_U &)
static const Quadrangle_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Quadrangle_VEF
Cette classe represente l'element geometrique Quadrangle_VEF.
Un Quadrangle_VEF a 4 faces, 4 sommets et un seul type de face ayant
2 sommets par face.
Definition at line 33 of file Quadrangle_VEF.h.
Constructor & Destructor Documentation
Quadrangle_VEF()
Quadrangle_VEF::Quadrangle_VEF ()
Definition at line 45 of file Quadrangle_VEF.cpp.
~Quadrangle_VEF()
Quadrangle_VEF::~Quadrangle_VEF ()
Definition at line 45 of file Quadrangle_VEF.cpp.
Member Function Documentation
calculer_volumes()
void Quadrangle_VEF::calculer_volumes (DoubleVect & volumes) const override virtual
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 237 of file Quadrangle_VEF.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const DoubleTab& coord = zone.domaine().coord_sommets();
  int S0,S1,S2,S3;
  ArrOfDouble xg(dimension);
  IntTab face_sommet_global;
  face_sommet_global.resize(4,2);
  DoubleTab pos(3,dimension);
  int numface;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      S0 = zone.sommet_elem(num_poly,0);
      S1 = zone.sommet_elem(num_poly,1);
      S2 = zone.sommet_elem(num_poly,2);
      S3 = zone.sommet_elem(num_poly,3);
// on construit le tableau de travail face_sommet_global
// les faces seront ordonnee suivant Xmin, Xmax, Ymin, Ymax, Zmin,Zmax
// toujours en gardant la numerotation de TRUST
      face_sommet_global(0,0) =S0;
      face_sommet_global(0,1) =S2;
      face_sommet_global(1,0) =S0;
      face_sommet_global(1,1) =S1;
      face_sommet_global(2,0) =S1;
      face_sommet_global(2,1) =S3;
      face_sommet_global(3,0) =S3;
      face_sommet_global(3,1) =S2;
// calcul du centre de gravite de l'element
      for (int j=0; j<dimension; j++)
        pos(0,j)=(coord(S0,j)+coord(S1,j)+coord(S2,j)+coord(S3,j))*0.25;
      double v = 0.;
// boucle sur les faces de l'element que l'on decoupe en 4 triangles.
// constitue des deux sommets de la face consideree et du centre de gravite de l'element
      for(numface=0; numface<nb_faces(0); numface++)
        {
          for (int i=0; i<2; i++)
            {
              int Si = face_sommet_global(numface,i);
              for (int j=0; j<dimension; j++)
                pos(i+1,j) = coord(Si,j);
            }
          v += aire_triangle(pos);
        }
      volumes[num_poly] = v;
    }
}
References aire_triangle(), Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), nb_faces(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [1/2]
int Quadrangle_VEF::contient (const ArrOfDouble & pos, int element) const override virtual
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element ielem
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 137 of file Quadrangle_VEF.cpp.
{
  assert(pos.size_array()==2);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som1 = zone.sommet_elem(element,1);
  int som2 = zone.sommet_elem(element,2);
  int som3 = zone.sommet_elem(element,3);
// On regarde tout d'abord si le point cherche n'est pas un des
// sommets du quadrangle
  if( (est_egal(dom.coord(som0,0),pos[0]) && est_egal(dom.coord(som0,1),pos[1]))
      || (est_egal(dom.coord(som1,0),pos[0]) && est_egal(dom.coord(som1,1),pos[1]))
      || (est_egal(dom.coord(som2,0),pos[0]) && est_egal(dom.coord(som2,1),pos[1]))
      || (est_egal(dom.coord(som3,0),pos[0]) && est_egal(dom.coord(som3,1),pos[1])) )
    return 1;
  double prod,p0,p1,p2,p3;
// Calcul de prod = 01 vectoriel 02 selon z
  prod = (dom.coord(som1,0)-dom.coord(som0,0))*(dom.coord(som2,1)-dom.coord(som0,1))
         - (dom.coord(som1,1)-dom.coord(som0,1))*(dom.coord(som2,0)-dom.coord(som0,0));
  double signe;
  if (prod >= 0)
    signe = 1;
  else
    signe = -1;
// Calcul de p0 = 0M vectoriel 1M selon z
  p0 = (pos[0]-dom.coord(som0,0))*(pos[1]-dom.coord(som1,1))
       - (pos[1]-dom.coord(som0,1))*(pos[0]-dom.coord(som1,0));
  p0 *= signe;
// Calcul de p1 = 1M vectoriel 3M selon z
  p1 = (pos[0]-dom.coord(som1,0))*(pos[1]-dom.coord(som3,1))
       - (pos[1]-dom.coord(som1,1))*(pos[0]-dom.coord(som3,0));
  p1 *= signe;
// Calcul de p2 = 3M vectoriel 2M selon z
  p2 = (pos[0]-dom.coord(som3,0))*(pos[1]-dom.coord(som2,1))
       - (pos[1]-dom.coord(som3,1))*(pos[0]-dom.coord(som2,0));
  p2 *= signe;
// Calcul de p3 = 2M vectoriel 0M selon z
  p3 = (pos[0]-dom.coord(som2,0))*(pos[1]-dom.coord(som0,1))
       - (pos[1]-dom.coord(som2,1))*(pos[0]-dom.coord(som0,0));
  p3 *= signe;
  double epsilon=std::fabs(prod)*Objet_U::precision_geom;
  if ((p0>-epsilon) && (p1>-epsilon) && (p2>-epsilon) && (p3>-epsilon))
    return 1;
  else
    return 0;
}
References Domaine::coord(), Zone::domaine(), est_egal(), Elem_geom_base::ma_zone, Objet_U::precision_geom, prod(), TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [2/2]
int Quadrangle_VEF::contient (const ArrOfInt & som, int element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 210 of file Quadrangle_VEF.cpp.
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,2)==som[2])&&
      (zone.sommet_elem(element,3)==som[3]))
    return 1;
  else
    return 0;
}
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
cree_instance()
Objet_U * Quadrangle_VEF::cree_instance () static
Definition at line 45 of file Quadrangle_VEF.cpp.
duplique()
int Quadrangle_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 45 of file Quadrangle_VEF.cpp.
est_structure()
int Quadrangle_VEF::est_structure () const inline override virtual
Renvoie toujours 0, car l'element geometrique
Quadrangle_VEF n'est pas de type structure.
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 304 of file Quadrangle_VEF.h.
{
  return 0;
}
face_sommet()
int Quadrangle_VEF::face_sommet (int i, int j) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 154 of file Quadrangle_VEF.h.
{
  assert(i<4);
  switch(i)
    {
    case 0:
      return face_sommet0(j);
    case 1:
      return face_sommet1(j);
    case 2:
      return face_sommet2(j);
    case 3:
      return face_sommet3(j);
    default :
      return -1;
    }
}
References face_sommet0(), face_sommet1(), face_sommet2(), and face_sommet3().
face_sommet0()
int Quadrangle_VEF::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Returns
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 187 of file Quadrangle_VEF.h.
{
// face_sommet0(0)=0
// face_sommet0(1)=2
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet1()
int Quadrangle_VEF::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Returns
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 216 of file Quadrangle_VEF.h.
{
// face_sommet1(0)=0
// face_sommet1(1)=1
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet2()
int Quadrangle_VEF::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Returns
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 245 of file Quadrangle_VEF.h.
{
// face_sommet2(0)=1
// face_sommet2(1)=3
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i+1;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet3()
int Quadrangle_VEF::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Returns
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 273 of file Quadrangle_VEF.h.
{
// face_sommet3(0)=2;
// face_sommet3(1)=3;
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return i+2;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
get_info()
const Type_info * Quadrangle_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 45 of file Quadrangle_VEF.cpp.
get_tab_faces_sommets_locaux()
int Quadrangle_VEF::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base.
Definition at line 394 of file Quadrangle_VEF.cpp.
{
  faces_som_local.resize(4,2);
  for (int i=0; i<4; i++)
    for (int j=0; j<2; j++)
      faces_som_local(i,j) = faces_sommets_quadra[i][j];
  return 1;
}
References faces_sommets_quadra, and TRUSTTab< _TYPE_ >::resize().
info()
const Type_info * Quadrangle_VEF::info () static
Definition at line 45 of file Quadrangle_VEF.cpp.
nb_faces()
int Quadrangle_VEF::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns
int
Signification: le nombre de faces de type i
Contraintes: toujours egal a 4 (si i=0)
Implements Elem_geom_base.
Definition at line 96 of file Quadrangle_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return 4;
}
References Cerr, Process::exit(), and finl.
Referenced by calculer_volumes().
nb_som()
int Quadrangle_VEF::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un Quadrangle_VEF: 4.
Returns
int
Signification: le nombre de sommets d'un Quadrangle_VEF
Contraintes: toujours egal a 4
Implements Elem_geom_base.
Definition at line 75 of file Quadrangle_VEF.h.
{
  return 4;
}
nb_som_face()
int Quadrangle_VEF::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Contraintes: toujours egal a 2 (si i=0)
Implements Elem_geom_base.
Definition at line 123 of file Quadrangle_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return 2;
}
References Cerr, Process::exit(), and finl.
nom_lml()
const Nom & Quadrangle_VEF::nom_lml () const override virtual
Renvoie le nom LML d'un Quadrangle_VEF = "GOLGOTH24".
Returns
Nom&
Signification: toujours egal a "GOLGOTH24"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 102 of file Quadrangle_VEF.cpp.
{
// static Nom nom="GOLGOTH24";
  static Nom nom="VOXEL8";
  if (dimension==3) nom="QUADRANGLE_3D";
  return nom;
}
References Objet_U::dimension.
printOn()
Sortie & Quadrangle_VEF::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 62 of file Quadrangle_VEF.cpp.
{
  return s;
}
readOn()
Entree & Quadrangle_VEF::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 82 of file Quadrangle_VEF.cpp.
{
  return s;
}
reordonner()
void Quadrangle_VEF::reordonner () override virtual
Reordonne.
Reimplemented from Elem_geom_base.
Definition at line 309 of file Quadrangle_VEF.cpp.
{
  Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  IntTab& elem=zone.les_elems();
  ArrOfInt S(4);
  ArrOfInt NS(4);
  DoubleTab co(4,2);
  int num_poly;
  const int nb_elem=zone.nb_elem();
  for (num_poly=0; num_poly<nb_elem; num_poly++)
    {
      for(int i=0; i<4; i++)
        {
          S[i] = elem(num_poly,i);
        }
// adaptation de Hexaedre_VEF ::reordonne
      const DoubleTab& coord=dom.les_sommets();
      DoubleTab v(3,3);
      for (int i=1; i<4; i++)
        for (int dir=0; dir<2; dir++)
          v(i-1,dir)=coord(S[i],dir)-coord(S[0],dir);
      ArrOfDouble prod_(3);
      int opp=-1;
      for (int op=0; op<3; op++)
        {
          DoubleTab prod_v(3,3);
          for (int i=0; i<3; i++)
            {
// prod_v(i,0)=v(op,1)*v(i,2)-v(op,2)*v(i,1);
// prod_v(i,1)=v(op,2)*v(i,0)-v(op,0)*v(i,2);
              prod_v(i,2)=v(op,0)*v(i,1)-v(op,1)*v(i,0);
            }
// Cerr<<prod_v<<finl;
          double prod=0;
          int i1=-1,i2=-1;
          if (op==0)
            {
              i1=1;
              i2=2;
            }
          else if (op==1)
            {
              i1=0;
              i2=2;
            }
          else if (op==2)
            {
              i1=0;
              i2=1;
            }
          for (int dir=0; dir<3; dir++)
            prod+=(prod_v(i1,dir)*prod_v(i2,dir));
          prod_[op]=prod;
          if (prod<0)
            {
              if (opp!=-1)
                {
                  op=2;
// on a deux produits negatifs on ne fait rien
                }
              opp=op;
            }
        }
      if (opp!=2)
        {
          int i2=2;
          int i1=1;
          int i3=3;
          int i2b=i2;
          if (opp==0) i2b=i1;
          int tmp=elem(num_poly,i2b);
          elem(num_poly,i2b)=elem(num_poly,i3);
          elem(num_poly,i3)=tmp;
          Cerr << "Permutation of local nodes "<<i2b<<" and "<<i3<<" on the element " <<num_poly<<" prod "<<prod_<<finl;
        }
    }
}
References Cerr, Zone::domaine(), finl, Zone::les_elems(), Domaine::les_sommets(), Elem_geom_base::ma_zone, Zone::nb_elem(), prod(), and Ref_Zone::valeur().
self_cast() [1/2]
const Quadrangle_VEF & Quadrangle_VEF::self_cast (const Objet_U & r) static
Definition at line 45 of file Quadrangle_VEF.cpp.
self_cast() [2/2]
Quadrangle_VEF & Quadrangle_VEF::self_cast (Objet_U & r) static
Definition at line 45 of file Quadrangle_VEF.cpp.
taille_memoire()
unsigned Quadrangle_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 45 of file Quadrangle_VEF.cpp.
type_face()
Type_Face Quadrangle_VEF::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un Quadrangle_VEF n'a qu'un seul type de face.
Returns
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::segment_2D (si i=0)
Implements Elem_geom_base.
Definition at line 325 of file Quadrangle_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF quadrangle (Quadrangle_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return Faces::segment_2D;
}
References Cerr, Process::exit(), finl, and Faces::segment_2D.
Member Data Documentation
info_obj
const Type_info Quadrangle_VEF::info_obj static
Definition at line 36 of file Quadrangle_VEF.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Quadrangle_VEF.h
src/Kernel/Geometrie/Quadrangle_VEF.cpp