TRUST: String2 Class Reference
String2 Class Reference
: class String2
Cette classe encapsule une chaine de caracteres simple.
Contrairement a "Nom", elle ne derive pas de Objet_U.
(Utilisee par la classe Parser)
#include <String2.h>
Public Member Functions
String2 ()
String2 (const char *)
String2 (const String2 &ss)
String2 (String2 *ss)
~String2 ()
int length ()
char * toChar ()
const char * toChar () const
int compare (const String2 &ss) const
int compare (const String2 *ss) const
String2 * substring (int i0, int i1)
Private Attributes
char * s
Friends
class StringTokenizer
Sortie & operator<< (Sortie &os, const String2 &c)
Detailed Description
: class String2
Cette classe encapsule une chaine de caracteres simple.
Contrairement a "Nom", elle ne derive pas de Objet_U.
(Utilisee par la classe Parser)
Definition at line 32 of file String2.h.
Constructor & Destructor Documentation
String2::String2 ()
Definition at line 26 of file String2.cpp.
References s.
Referenced by substring().
{
  s = new char[2];
  s[0]='0';
  s[1]='\0';
}
String2::String2 (const char * ss)
Definition at line 33 of file String2.cpp.
References convertit_en_majuscule(), and s.
{
  s = new char[strlen(ss)+1];
  strcpy(s,ss);
  convertit_en_majuscule(s);
}
String2::String2 (const String2 & ss)
Definition at line 45 of file String2.cpp.
References s.
{
  s = new char[strlen(ss.s)+1];
  strcpy(s,ss.s);
}
String2::String2 (String2 * ss)
Definition at line 51 of file String2.cpp.
References s.
{
  s = new char[strlen(ss->s)+1];
  strcpy(s,ss->s);
}
String2::~String2 ()
Definition at line 40 of file String2.cpp.
References s.
{
  delete[] s;
}
Member Function Documentation
int String2::compare (const String2 & ss) const [inline]
Definition at line 52 of file String2.h.
References s.
  {
    return strcmp(s,ss.s);
  };
int String2::compare (const String2 * ss) const [inline]
Definition at line 56 of file String2.h.
References s.
  {
    return strcmp(s,ss->s);
  };
int String2::length () [inline]
Definition at line 40 of file String2.h.
References s.
  {
    return strlen(s);
  };
String2 * String2::substring (int i0, int i1)
Definition at line 58 of file String2.cpp.
References s, and String2().
{
  char* ss = new char[i1-i0+1];
  for (int i=i0; i<i1; i++)
    ss[i]=s[i];
  String2* str=new String2(ss);
  delete[] ss;
  return str;
}
char* String2::toChar () [inline]
Definition at line 44 of file String2.h.
References s.
Referenced by Parser::searchCst(), and Parser::searchFunc().
  {
    return s;
  };
const char* String2::toChar () const [inline]
Definition at line 48 of file String2.h.
References s.
  {
    return s;
  };
Friends And Related Function Documentation
Sortie& operator<< (Sortie & os, const String2 & c) [friend]
Definition at line 74 of file String2.cpp.
{
  return os << c.s;
}
friend class StringTokenizer [friend]
Definition at line 64 of file String2.h.
Member Data Documentation
char* String2::s [private]
Definition at line 67 of file String2.h.
Referenced by StringTokenizer::check_GRP(), compare(), length(), operator<<(), String2(), StringTokenizer::StringTokenizer(), substring(), toChar(), and ~String2().
The documentation for this class was generated from the following files:
src/Kernel/Math/String2.h
src/Kernel/Math/String2.cpp