TRUST: Op_Diff_VDF_Elem_base Class Reference
Op_Diff_VDF_Elem_base Class Reference
class Op_Diff_VDF_Elem_base
Cette classe represente l'operateur de diffusion associe a une equation de transport.
La discretisation est VDF. Le champ diffuse est scalaire. Le champ de diffusivite est uniforme
L'iterateur associe est de type Iterateur_VDF_Elem. L'evaluateur associe est de type Eval_Diff_VDF_const_Elem
#include <Op_Diff_VDF_Elem_base.h>
Public Member Functions
~Op_Diff_VDF_Elem_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_VDF_Elem_base (const Iterateur_VDF_base &iterateur)
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const override
void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
Public Member Functions inherited from Op_Diff_VDF_base
Op_Diff_VDF_base ()
~Op_Diff_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_VDF_base (const Iterateur_VDF_base &iter_base)
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual void calculer_flux_bord (const DoubleTab &inco) const
const Iterateur_VDF & get_iter () const
Iterateur_VDF & get_iter ()
int has_interface_blocs () const override
void init_op_ext () const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VDF_Elem
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void dimensionner_bloc_vitesse (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Static Public Member Functions
static const Type_info * info ()
static Op_Diff_VDF_Elem_base & self_cast (Objet_U &)
static const Op_Diff_VDF_Elem_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VDF_base
static const Type_info * info ()
static Op_Diff_VDF_base & self_cast (Objet_U &)
static const Op_Diff_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VDF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Diff_VDF_base
Iterateur_VDF iter
int op_ext_init_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Diff_VDF_Elem_base
Cette classe represente l'operateur de diffusion associe a une equation de transport.
La discretisation est VDF. Le champ diffuse est scalaire. Le champ de diffusivite est uniforme
L'iterateur associe est de type Iterateur_VDF_Elem. L'evaluateur associe est de type Eval_Diff_VDF_const_Elem
Definition at line 29 of file Op_Diff_VDF_Elem_base.h.
Constructor & Destructor Documentation
~Op_Diff_VDF_Elem_base()
Op_Diff_VDF_Elem_base::~Op_Diff_VDF_Elem_base () override
Definition at line 25 of file Op_Diff_VDF_Elem_base.cpp.
Op_Diff_VDF_Elem_base()
Op_Diff_VDF_Elem_base::Op_Diff_VDF_Elem_base (const Iterateur_VDF_base & iterateur) inline
Definition at line 34 of file Op_Diff_VDF_Elem_base.h.
                                                                    : Op_Diff_VDF_base(iterateur)
  {
    declare_support_masse_volumique(1);
  }
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
ajouter_blocs()
void Op_Diff_VDF_Elem_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
Definition at line 176 of file Op_Diff_VDF_Elem_base.cpp.
{
  statistiques().begin_count(diffusion_counter_);
  if (!op_ext_init_) init_op_ext();
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  int n_ext = op_ext.size(); //pour la thermique monolithique
  std::vector<Matrice_Morse *> mat(n_ext);
  std::vector<const DoubleTab *> inco(n_ext); //inconnues
  mat[0] = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
  inco[0] = semi_impl.count(nom_inco) ? &semi_impl.at(nom_inco) : &op_ext[0]->equation().inconnue().valeur().valeurs();
  if(mat[0]) iter.ajouter_contribution(*inco[0], *mat[0]);
  iter.ajouter(*inco[0],secmem);
  if (equation().domaine_application() == Motcle("Hydraulique"))
// On est dans le cas des equations de Navier_Stokes
    {
// Ajout du terme supplementaire en V/(R*R) dans le cas des coordonnees axisymetriques
      if(Objet_U::bidim_axi == 1)
        {
          const Zone_VDF& zvdf=iter.zone();
          const DoubleTab& xv=zvdf.xv();
          const IntVect& ori=zvdf.orientation();
          const IntTab& face_voisins=zvdf.face_voisins();
          const DoubleVect& volumes_entrelaces=zvdf.volumes_entrelaces();
          int face, nb_faces=zvdf.nb_faces();//, cst;
          DoubleTrav diffu_tot(zvdf.nb_elem_tot());
          double db_diffusivite;
          Nom nom_eq=equation().que_suis_je();
          if ((nom_eq == "Navier_Stokes_standard")||(nom_eq == "Navier_Stokes_QC")||(nom_eq == "Navier_Stokes_FT_Disc"))
            {
              const Eval_Diff_VDF& eval=dynamic_cast<const Eval_Diff_VDF&> (iter.evaluateur());
              const Champ_base& ch_diff=eval.get_diffusivite();
              const DoubleTab& tab_diffusivite=ch_diff.valeurs();
              if (tab_diffusivite.size() == 1)
                diffu_tot = tab_diffusivite(0,0);
              else
                diffu_tot = tab_diffusivite;
              for(face=0; face<nb_faces; face++)
                if(ori(face)==0)
                  {
                    int elem1=face_voisins(face,0);
                    int elem2=face_voisins(face,1);
                    if(elem1==-1)
                      db_diffusivite=diffu_tot(elem2);
                    else if (elem2==-1)
                      db_diffusivite=diffu_tot(elem1);
                    else
                      db_diffusivite=0.5*(diffu_tot(elem2)+diffu_tot(elem1));
                    double r= xv(face,0);
                    if(r>=1.e-24)
                      {
                        if(mat[0]) (*mat[0])(face,face)+=db_diffusivite*volumes_entrelaces(face)/(r*r);
                        secmem(face) -=(*inco[0])(face)*db_diffusivite*volumes_entrelaces(face)/(r*r);
                      }
                  }
            }
          else if (equation().que_suis_je() == "Navier_Stokes_Interface_avec_trans_masse" ||
                   equation().que_suis_je() == "Navier_Stokes_Interface_sans_trans_masse" ||
                   equation().que_suis_je() == "Navier_Stokes_Front_Tracking" ||
                   equation().que_suis_je() == "Navier_Stokes_Front_Tracking_BMOL")
            {
// Voir le terme source axi dans Interfaces/VDF
            }
          else
            {
              Cerr << "Probleme dans Op_Diff_VDF_base::contribuer_a_avec  avec le type de l'equation" << finl;
              Cerr << "on n'a pas prevu d'autre cas que Navier_Stokes_std" << finl;
              exit();
            }
        }
    }
  for (int i = 1; i < n_ext; i++)
    {
      std::string nom_mat = nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString();
      mat[i] = matrices.count(nom_mat) ? matrices.at(nom_mat) : NULL;
      if(mat[i])
        {
          inco[i] = semi_impl.count(nom_mat) ? &semi_impl.at(nom_mat) : &op_ext[i]->equation().inconnue().valeur().valeurs();
          contribuer_termes_croises(*inco[i], op_ext[i]->equation().probleme(), op_ext[i]->equation().inconnue().valeurs(), *mat[i]);
        }
    }
  statistiques().end_count(diffusion_counter_);
}
References Iterateur_VDF::ajouter(), Iterateur_VDF::ajouter_contribution(), Statistiques::begin_count(), Objet_U::bidim_axi, Cerr, contribuer_termes_croises(), diffusion_counter_, Statistiques::end_count(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Process::exit(), Zone_VF::face_voisins(), finl, Eval_Diff_VDF::get_diffusivite(), Nom::getString(), Equation_base::inconnue(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VDF_base::iter, O_U_Ptr::le_nom(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Operateur_Diff_base::op_ext, Op_Diff_VDF_base::op_ext_init_, Zone_VDF::orientation(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::size(), statistiques(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), and Iterateur_VDF::zone().
calculer_dt_stab()
double Op_Diff_VDF_Elem_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 30 of file Op_Diff_VDF_Elem_base.cpp.
{
// Calcul du pas de temps de stabilite :
//
// - La  diffusivite est uniforme donc :
//
// dt_stab = 1/(2*diffusivite*Max(coef(elem)))
//
// avec:
// coef = 1/(dx*dx) + 1/(dy*dy) + 1/(dz*dz)
//
// i decrivant l'ensemble des elements du maillage
//
// Rq : On ne balaie pas l'ensemble des elements puisque
// le max de coeff est atteint sur l'element qui realise
// a la fois le min de dx le min de dy et le min de dz
  double dt_stab = DMAXFLOAT;
  const Zone_VDF& zone_VDF = iter.zone();
  const DoubleTab& diffu = has_champ_masse_volumique() ? diffusivite().valeurs() : diffusivite_pour_pas_de_temps().valeurs();
  if (sub_type(Champ_Uniforme,diffusivite_pour_pas_de_temps()) && !has_champ_masse_volumique())
    {
// GF le max permet de traiter le multi_inco
      double alpha=max_array(diffu);
      double coef = 1/(zone_VDF.h_x()*zone_VDF.h_x()) + 1/(zone_VDF.h_y()*zone_VDF.h_y());
      if (dimension == 3) coef += 1/(zone_VDF.h_z()*zone_VDF.h_z());
      if (alpha==0) dt_stab = DMAXFLOAT;
      else dt_stab = 0.5/(alpha*coef);
    }
  else
    {
      double alpha_loc;
      const int nb_elem = diffu.dimension(0);
      for (int elem = 0 ; elem < nb_elem; elem++)
        {
          double h = 0;
          for (int i=0 ; i<dimension; i++)
            {
              double l = zone_VDF.dim_elem(elem,i);
              h += 1./(l*l);
            }
          alpha_loc = diffu(elem,0);
          for (int ncomp=1; ncomp<diffu.dimension(1); ncomp++) alpha_loc = std::max(alpha_loc,diffu(elem,ncomp));
          if (has_champ_masse_volumique())
            {
              const DoubleTab& rho = get_champ_masse_volumique().valeurs();
              alpha_loc/= rho(elem);
            }
          double dt_loc = 0.5/((alpha_loc+DMINFLOAT)*h);
          if (dt_loc<dt_stab) dt_stab = dt_loc;
        }
    }
  return Process::mp_min(dt_stab);
}
References Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Zone_VDF::dim_elem(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMAXFLOAT, DMINFLOAT, Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Zone_VDF::h_x(), Zone_VDF::h_y(), Zone_VDF::h_z(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_VDF_base::iter, max_array(), Process::mp_min(), sub_type, Champ_Proto::valeurs(), and Iterateur_VDF::zone().
contribuer_termes_croises()
void Op_Diff_VDF_Elem_base::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const override virtual
Reimplemented from Operateur_base.
Definition at line 90 of file Op_Diff_VDF_Elem_base.cpp.
{
  const Zone_VDF& zone = iter.zone();
  const IntTab& f_e = zone.face_voisins();
  const Zone_Cl_VDF& zcl = iter.zone_Cl();
  int l;
// boucle sur les cl pour trouver un paroi_contact
  for (int i = 0; i < zone.nb_front_Cl(); i++)
    {
      const Cond_lim& la_cl = zcl.les_conditions_limites(i);
      if (!la_cl.valeur().que_suis_je().debute_par("Paroi_Echange_contact")) continue; //pas un Echange_contact
      const Echange_contact_VDF& cl = ref_cast(Echange_contact_VDF, la_cl.valeur());
      if (cl.nom_autre_pb() != autre_pb.le_nom()) continue; //not our problem
      std::map<int, std::pair<int, int>> f2e;
      const Front_VF& fvf = ref_cast(Front_VF, cl.frontiere_dis());
      for (int j = 0; j < cl.item.dimension(0); j++)
        if ((l = cl.item(j)) >= 0)
          {
            int f = fvf.num_face(j);
            int e = f_e(f, 0) == -1 ? f_e(f, 1) : f_e(f, 0);
            f2e[f] = std::make_pair(e, l);
          }
      iter.ajouter_contribution_autre_pb(inco, matrice, la_cl, f2e);
    }
}
References Iterateur_VDF::ajouter_contribution_autre_pb(), Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Echange_contact_VDF::item, Op_Diff_VDF_base::iter, Probleme_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_front_Cl(), Echange_contact_VDF::nom_autre_pb(), Front_VF::num_face(), Objet_U::que_suis_je(), ref_cast, Deriv_Cond_lim_base::valeur(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
Referenced by ajouter_blocs().
dimensionner_blocs()
void Op_Diff_VDF_Elem_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
Definition at line 149 of file Op_Diff_VDF_Elem_base.cpp.
{
  if (!op_ext_init_) init_op_ext();
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  int n_ext = op_ext.size(); //pour la thermique monolithique
  std::vector<Matrice_Morse *> mat(n_ext);
  std::vector<int> N(n_ext); //nombre de composantes par probleme de op_ext
  for (int i = 0; i < n_ext; i++)
    {
      N[i] = op_ext[i]->equation().inconnue().valeurs().line_size();
      std::string nom_mat = i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco;
      mat[i] = matrices.count(nom_mat) ? matrices.at(nom_mat) : NULL;
      if(!mat[i]) continue;
      Matrice_Morse mat2;
      if(i==0) Op_VDF_Elem::dimensionner(iter.zone(), iter.zone_Cl(), mat2);
      else
        {
          int nl = N[0] * iter.zone().nb_elem_tot();
          int nc = N[i] * op_ext[i]->equation().zone_dis()->nb_elem_tot();
          dimensionner_termes_croises(mat2, op_ext[i]->equation().probleme(),nl, nc);
        }
      mat[i]->nb_colonnes() ? *mat[i] += mat2 : *mat[i] = mat2;
    }
}
References Op_VDF_Elem::dimensionner(), dimensionner_termes_croises(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VDF_base::iter, O_U_Ptr::le_nom(), Zone_dis_base::nb_elem_tot(), Operateur_Diff_base::op_ext, Op_Diff_VDF_base::op_ext_init_, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
dimensionner_termes_croises()
void Op_Diff_VDF_Elem_base::dimensionner_termes_croises (Matrice_Morse & matrice, const Probleme_base & autre_pb, int nl, int nc) const override virtual
Reimplemented from Operateur_base.
Definition at line 118 of file Op_Diff_VDF_Elem_base.cpp.
{
  const Champ_P0_VDF& ch = ref_cast(Champ_P0_VDF, equation().inconnue().valeur());
  const Zone_VDF& zone = iter.zone();
  const IntTab& f_e = zone.face_voisins();
  const Conds_lim& cls = iter.zone_Cl().les_conditions_limites();
  int i, j, l, f, n, N = ch.valeurs().line_size();
  IntTab stencil(0, 2);
  stencil.set_smart_resize(1);
  for (i = 0; i < cls.size(); i++)
    if (sub_type(Echange_contact_VDF, cls[i].valeur()))
      {
        const Echange_contact_VDF& cl = ref_cast(Echange_contact_VDF, cls[i].valeur());
        if (cl.nom_autre_pb() != autre_pb.le_nom()) continue; //not our problem
        /* stencil */
        const Front_VF& fvf = ref_cast(Front_VF, cl.frontiere_dis());
        for (j = 0; j < cl.item.dimension(0); j++)
          if ((l = cl.item(j)) >= 0)
            {
              f = fvf.num_face(j);
              int e = f_e(f, 0) == -1 ? f_e(f, 1) : f_e(f, 0);
              for (n = 0; n < N; n++) stencil.append_line(N * e + n, N * l + n);
            }
      }
  tableau_trier_retirer_doublons(stencil);
  Matrix_tools::allocate_morse_matrix(nl, nc, stencil, matrice);
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Echange_contact_VDF::item, Op_Diff_VDF_base::iter, Probleme_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Echange_contact_VDF::nom_autre_pb(), Front_VF::num_face(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), sub_type, tableau_trier_retirer_doublons(), valeur(), Champ_Inc_base::valeurs(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
Referenced by dimensionner_blocs().
get_info()
const Type_info * Op_Diff_VDF_Elem_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, and Op_Diff_VDF_Multi_inco_var_Elem_Axi.
Definition at line 25 of file Op_Diff_VDF_Elem_base.cpp.
info()
const Type_info * Op_Diff_VDF_Elem_base::info () static
Definition at line 25 of file Op_Diff_VDF_Elem_base.cpp.
modifier_pour_Cl()
void Op_Diff_VDF_Elem_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 42 of file Op_Diff_VDF_Elem_base.h.
{ Op_VDF_Elem::modifier_pour_Cl(iter.zone(), iter.zone_Cl(), matrice, secmem); }
References Op_Diff_VDF_base::iter, Op_VDF_Elem::modifier_pour_Cl(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
printOn()
Sortie & Op_Diff_VDF_Elem_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, and Op_Diff_VDF_Multi_inco_var_Elem_Axi.
Definition at line 27 of file Op_Diff_VDF_Elem_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VDF_Elem_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, and Op_Diff_VDF_Multi_inco_var_Elem_Axi.
Definition at line 28 of file Op_Diff_VDF_Elem_base.cpp.
{ return s ; }
self_cast() [1/2]
const Op_Diff_VDF_Elem_base & Op_Diff_VDF_Elem_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Op_Diff_VDF_Elem_base.cpp.
self_cast() [2/2]
Op_Diff_VDF_Elem_base & Op_Diff_VDF_Elem_base::self_cast (Objet_U & r) static
Definition at line 25 of file Op_Diff_VDF_Elem_base.cpp.
Member Data Documentation
info_obj
const Type_info Op_Diff_VDF_Elem_base::info_obj static
Definition at line 31 of file Op_Diff_VDF_Elem_base.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Diff_VDF_Elem_base.h
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Diff_VDF_Elem_base.cpp