TRUST: Sortie_Brute Class Reference
Sortie_Brute Class Reference
This derived class of Sortie stacks whatever it receives in an internal binary buffer.
Data can be accessed through get_data().
#include <Sortie_Brute.h>
Public Member Functions
Sortie_Brute ()
~Sortie_Brute () override
const char * get_data () const
returns a pointer to the internal data. The data is valid as long as no other write operation is done on
the Sortie_Brute object.
unsigned get_size () const
int set_bin (int bin) override
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Protected Attributes
std::string string_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
This derived class of Sortie stacks whatever it receives in an internal binary buffer.
Data can be accessed through get_data().
Definition at line 28 of file Sortie_Brute.h.
Constructor & Destructor Documentation
Sortie_Brute()
Sortie_Brute::Sortie_Brute ()
< deletion in Sortie destructor
Definition at line 23 of file Sortie_Brute.cpp.
                           :
  Sortie()
{
  set_bin(1);
  ostringstream *os = new ostringstream();  //!< deletion in Sortie destructor
  set_ostream(os);
}
References set_bin(), and Sortie::set_ostream().
~Sortie_Brute()
Sortie_Brute::~Sortie_Brute () override
Definition at line 31 of file Sortie_Brute.cpp.
{
}
Member Function Documentation
get_data()
const char * Sortie_Brute::get_data () const
returns a pointer to the internal data. The data is valid as long as no other write operation is done on
the Sortie_Brute object.
Definition at line 38 of file Sortie_Brute.cpp.
{
  const ostringstream& os = static_cast< const ostringstream& >(get_ostream());
  string_ = std::string(os.str());
  return string_.c_str();
}
References Sortie::get_ostream(), and string_.
get_size()
unsigned Sortie_Brute::get_size () const
Definition at line 45 of file Sortie_Brute.cpp.
{
  const ostringstream& os = static_cast< const ostringstream& >(get_ostream());
  return os.str().size();
}
References Sortie::get_ostream().
Referenced by DomaineCutter::ecrire_zones().
set_bin()
int Sortie_Brute::set_bin (int bin) override virtual
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Reimplemented from Sortie.
Definition at line 51 of file Sortie_Brute.cpp.
{
  if (bin != 1)
    {
      Cerr << "Error in Sortie_Brute::set_bin(int bin) : only binary format supported. Use SChaine otherwise." << finl;
      Process::exit();
    }
  Sortie::set_bin(bin);
  return bin;
}
References Cerr, Process::exit(), finl, and Sortie::set_bin().
Referenced by Sortie_Brute().
Member Data Documentation
string_
std::string Sortie_Brute::string_ mutable protected
Definition at line 38 of file Sortie_Brute.h.
Referenced by get_data().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Sortie_Brute.h
src/Kernel/Utilitaires/Sortie_Brute.cpp