TRUST: Perte_Charge_Circulaire_QC_VEF_P1NC Class Reference
Perte_Charge_Circulaire_QC_VEF_P1NC Class Reference
#include <Source_QC_VEF_P1NC.h>
Public Member Functions
Perte_Charge_Circulaire_QC_VEF_P1NC ()
~Perte_Charge_Circulaire_QC_VEF_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
copie de ajouter sauf la derniere ligne
DoubleTab & ajouter (DoubleTab &) const
Appelle perte_charge pour chaque face ou cela est necessaire.
DoubleTab & ajouter_mere (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Circulaire_QC_VEF_P1NC & self_cast (Objet_U &)
static const
Perte_Charge_Circulaire_QC_VEF_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 59 of file Source_QC_VEF_P1NC.h.
Constructor & Destructor Documentation
Perte_Charge_Circulaire_QC_VEF_P1NC::Perte_Charge_Circulaire_QC_VEF_P1NC ()
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
Perte_Charge_Circulaire_QC_VEF_P1NC::~Perte_Charge_Circulaire_QC_VEF_P1NC ()
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_Circulaire_QC_VEF_P1NC::ajouter (DoubleTab & resu) const [virtual]
Appelle perte_charge pour chaque face ou cela est necessaire.
< viscosite cinematique
< centres de gravite des faces
Reimplemented from Perte_Charge_VEF.
Definition at line 36 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Perte_Charge_Circulaire_QC_VEF_P1NC >::ajouter_impl().
Referenced by ajouter_mere().
{ return ajouter_impl(resu); }
DoubleTab & Perte_Charge_Circulaire_QC_VEF_P1NC::ajouter_mere (DoubleTab & resu) const
Definition at line 35 of file Source_QC_VEF_P1NC.cpp.
References ajouter().
{ return Perte_Charge_Circulaire_VEF_P1NC::ajouter(resu); }
void Perte_Charge_Circulaire_QC_VEF_P1NC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
copie de ajouter sauf la derniere ligne
< La perte de charge n'est pas implicitee, on quitte
< viscosite cinematique
< centres de gravite des faces
Reimplemented from Perte_Charge_VEF.
Definition at line 37 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Perte_Charge_Circulaire_QC_VEF_P1NC >::contribuer_a_avec_impl().
{ contribuer_a_avec_impl(resu,mat); }
Objet_U * Perte_Charge_Circulaire_QC_VEF_P1NC::cree_instance () [static]
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
int Perte_Charge_Circulaire_QC_VEF_P1NC::duplique () const [virtual]
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Perte_Charge_Circulaire_QC_VEF_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Perte_Charge_Circulaire_QC_VEF_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
Sortie & Perte_Charge_Circulaire_QC_VEF_P1NC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 33 of file Source_QC_VEF_P1NC.cpp.
{ return Perte_Charge_Circulaire_VEF_P1NC::printOn(os); }
Entree & Perte_Charge_Circulaire_QC_VEF_P1NC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 34 of file Source_QC_VEF_P1NC.cpp.
{  return Perte_Charge_Circulaire_VEF_P1NC::readOn(is); }
const Perte_Charge_Circulaire_QC_VEF_P1NC & Perte_Charge_Circulaire_QC_VEF_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
Perte_Charge_Circulaire_QC_VEF_P1NC & Perte_Charge_Circulaire_QC_VEF_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
unsigned Perte_Charge_Circulaire_QC_VEF_P1NC::taille_memoire () const [virtual]
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 32 of file Source_QC_VEF_P1NC.cpp.
Member Data Documentation
const Type_info Perte_Charge_Circulaire_QC_VEF_P1NC::info_obj [static]
Reimplemented from Perte_Charge_Circulaire_VEF_P1NC.
Definition at line 61 of file Source_QC_VEF_P1NC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.cpp