TRUST: ArrOfInt Class Reference
ArrOfInt Class Reference
Represente un tableau d'elements de type int.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0
(etat obtenu par le constructeur par defaut, detach_array()
et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure Vdbldata, data_==p->data_
et size_array_ <= p->size_. A la destruction du tableau, si
p->ref_count_ est nul on libere la memoire.
data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs
ArrOfInt (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier ArrOfInt a utiliser une zone de memoire
la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire
n'est pas liberee a la destruction du ArrOfInt.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir
pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value".
Priere de supposer desormais que les tableaux ne sont pas initialises
par defaut.
#include <ArrOfInt.h>
Public Types
enum Storage { STANDARD, TEMP_STORAGE }
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
~ArrOfInt ()
Destructeur : appelle detach_array()
ArrOfInt ()
Constructeur par defaut: cree un tableau "detache",
soit p_==0, data_==0, size_array_==0, smart_resize_==0.
ArrOfInt (int size)
Cree un tableau de taille n avec allocation standard (voir set_mem_storage).
Le tableau est rempli avec zero par defaut. Pour creer un tableau non initialise, utiliser:
ArrOfInt toto;
toto.resize_array(n, NOCOPY_NOINIT);
Parametre: int n
Signification: taille du tableau.
ArrOfInt (const ArrOfInt &)
Constructeur par copie. On alloue une nouvelle zone de memoire
et on copie le contenu du tableau (il s'agit d'un "deep copy").
L'attribut smart_resize_ est copie aussi.
Si le tableau A est de taille nulle, on cree un tableau "detache",
sinon on cree un tableau "normal".
Parametre: const ArrOfInt& A
Signification: le tableau a copier.
void resize_array (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
appel a ArrOfInt::resize_array()
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Si l'objet est de type ArrOfInt, appel a resize_array(n)
Prerequis: le tableau doit etre "resizable" (voir resize_array()).
S'il est d'un type derive (Vect ou Tab), il ne doit pas avoir de descripteur
parallele si la taille est effectivement modifiee.
void set_smart_resize (int flag)
Change le mode l'allocation memoire: reallocation d'un tableau
a chaque changement de taille (flag = 0) ou reallocation
uniquement si la taille augmente et par doublement de la taille
du tableau (flag = 1).
void set_mem_storage (const Storage storage)
Change le mode d'allocation memoire lors des resize<br>(voir VIntdata et Int_ptr_trav)
Exemple pour creer un tableau avec allocation temporaire:
DoubleTab tab; // Creation d'un tableau vide
tab.set_mem_storage(TEMP_STORAGE); // Changement de mode d'allocation
tab.resize(n); // Allocation memoire.
Storage get_mem_storage () const
Renvoie le mode d'allocation du tableau (qui sera utilise
lors du prochain resize si changement de taille).
(voir VIntdata et Int_ptr_trav)
virtual void ref_data (int *ptr, int size)
Fait pointer le tableau vers la zone de memoire "data_".
On detache la zone de memoire existante. Le tableau devient
de type "ref_data". Attention : ptr doit etre non nul.
La taille est initialisee avec size.
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Pour faire une ref sur un tableau parallele utiliser IntVect::ref()
Parametre: int*
Signification: le tableau a recuperer. Si pointeur nul alors size
doit etre nulle aussi et le tableau reste detache
Parametre: int size
Signification: le nombre d'elements du tableau.
virtual void ref_array (ArrOfInt &, int start=0, int sz=-1)
Fait pointer le tableau vers les memes donnees qu'un tableau
existant. Le tableau sera du meme type que le tableau m ("detache",
"normal"). Le tableau m ne doit pas etre de type "ref_data"
Attention, le tableau source et *this sont ensuite figes (resize_array()
interdit).
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Parametre: const ArrOfInt& m
Signification: le tableau a referencer (pas de type "ref_data"
et different de *this !!!)
ArrOfInt & operator= (const ArrOfInt &)
Copie les donnees du tableau m.
Si "m" n'a pas la meme taille que "*this", on fait un resize_array.
Ensuite, on copie les valeurs de "m" dans "*this".
Le type de tableau (methode d'allocation) n'est pas copie.
virtual void reset ()
Remet le tableau dans l'etat obtenu avec le constructeur par defaut
(libere la memoire mais conserve le mode d'allocation memoire actuel)
ArrOfInt & operator= (int valeur)
x est affecte a toutes les cases
int & operator[] (int i)
operateur [] retourne le ieme element du tableau
const int & operator[] (int i) const
operateur [] retourne le ieme element du tableau
int & operator() (int i)
idem operator[]
const int & operator() (int i) const
const int * addr () const
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Attention, l'adresse peut changer apres un appel
a resize_array(), ref_data, ref_array, ...
int * addr ()
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
int size_array () const
Renvoie la taille du tableau (nombre d'elements declares
a la construction ou a resize_array()).
C'est le nombre d'elements accessibles a operator[].
int ref_count () const
Retourne le nombre de references des donnees du tableau
si le tableau est "normal", -1 s'il est "detache" ou "ref_data".
void append_array (int valeur)
Ajoute une case en fin de tableau et y stocke la "valeur".
ArrOfInt & operator+= (const ArrOfInt &)
Addition case a case sur toutes les cases du tableau.
ArrOfInt & operator+= (const int)
ajoute la meme valeur a toutes les cases du tableau
ArrOfInt & operator-= (const ArrOfInt &)
Soustraction case a case sur toutes les cases du tableau
Parametre: const ArrOfInt& y
Signification: tableau de meme taille que *this.
ArrOfInt & operator-= (const int)
soustrait la meme valeur a toutes les cases
ArrOfInt & inject_array (const ArrOfInt &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
ArrOfInt & copy_array (const ArrOfInt &)
appelle operator=(a)
ArrOfInt & operator= (const FArrOfInt &)
void ordonne_array ()
Tri des valeurs du tableau dans l'ordre croissant.
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
void array_trier_retirer_doublons ()
Tri des valeurs du tableau dans l'ordre croissant et suppresion des doublons
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ArrOfInt & self_cast (Objet_U &)
static const ArrOfInt & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture du tableau sur "os" :
ecrit le nombre d'elements suivi des valeurs du tableau.
virtual Entree & readOn (Entree &)
Lecture d'un tableau dans un flot d'entree
Lit le nombre d'elements suivi des elements eux-memes.
void attach_array (const ArrOfInt &a, int start=0, int size=-1)
Amene le tableau dans l'etat "normal", "detache" ou "ref_array"
en associant une sous-zone de memoire du tableau m, definie par start et size
Si size < 0, on prend le tableau m jusqu'a la fin.
int detach_array ()
Amene le tableau dans l'etat "detache". C'est a dire:
Si le tableau est "detache" :
* ne rien faire
Si le tableau est "normal" :
* decremente le nombre de references a *p
* detruit *p si p->ref_count==0
* annule p_, data_ et size_array_
Si le tableau est "ref_data" :
* annule data_ et size_array_.
void fill_default_value (Array_base::Resize_Options opt, int first, int nb)
Remplit "nb" cases consecutives du tableau a partir de la case "first"
avec une valeur par defaut.
Cette fonction est appelee lors d'un resize pour initialiser les
cases nouvellement creees.
Le comportement depend actuellement du type de tableau :
* Tableau de type "smart_resize":
* en mode debug (macro NDEBUG non definie) le tableau est initialise
avec une valeur invalide.
* en optimise, le tableau n'est pas initialise
* Tableau normal :
Le tableau est initialise avec la valeur 0. Ce comportement est choisi
pour des raisons de compatibilite avec l'implementation precedente.
Cette specification pourrait etre modifiee prochainement pour des raisons
de performances (pour ne pas avoir a initialiser inutilement les tableaux).
DONC: il faut supposer desormais que les nouvelles cases ne sont pas
initialisees lors d'un resize.
Parametre: first
Signification: premiere case a initialiser.
Contrainte: (nb==0) ou (0 <= first < memory_size_)
Parametre: nb
Signification: nombre de cases a initialiser.
Contrainte: (nb==0) ou (0 < nb <= memory_size_ - first)
void resize_array_ (int n, Array_base::Resize_Options opt=COPY_INIT)
methode protegee de changement de taille, appelable par
les classes derivees (idem que resize_array() mais sans condition sur le
type derive de l'objet)
Private Member Functions
void memory_resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
Si besoin, alloue une nouvelle zone de memoire,
copie les donnees et efface l'ancienne zone de memoire.
Attention, on suppose que cette methode est appelee par
resize_array().
Attention: si ref_count_>1, l'appel a resize_array() est
autorise uniquement si la nouvelle taille est identique
a la precedente (auquel cas on ne fait rien)
Si ref_count_ == 1, l'appel est invalide si p_->data_ est
different de data_ (le tableau a ete construit avec ref_array()
avec start > 0)
Private Attributes
VIntdata * p_
int * data_
int size_array_
int memory_size_
int smart_resize_
Storage storage_type_
Detailed Description
Represente un tableau d'elements de type int.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0
(etat obtenu par le constructeur par defaut, detach_array()
et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure Vdbldata, data_==p->data_
et size_array_ <= p->size_. A la destruction du tableau, si
p->ref_count_ est nul on libere la memoire.
data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs
ArrOfInt (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier ArrOfInt a utiliser une zone de memoire
la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire
n'est pas liberee a la destruction du ArrOfInt.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir
pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value".
Priere de supposer desormais que les tableaux ne sont pas initialises
par defaut.
Definition at line 71 of file ArrOfInt.h.
Member Enumeration Documentation
enum ArrOfInt::Storage
Enumerator:
STANDARD
TEMP_STORAGE
Definition at line 101 of file ArrOfInt.h.
{ STANDARD, TEMP_STORAGE };
Constructor & Destructor Documentation
ArrOfInt::~ArrOfInt ()
Destructeur : appelle detach_array()
< Paranoia: si size_array_==-1, c'est un zombie
Definition at line 317 of file ArrOfInt.cpp.
References detach_array(), and size_array_.
{
  detach_array();
  size_array_ = -1; //!< Paranoia: si size_array_==-1, c'est un zombie
}
ArrOfInt::ArrOfInt ()
Constructeur par defaut: cree un tableau "detache",
soit p_==0, data_==0, size_array_==0, smart_resize_==0.
Definition at line 326 of file ArrOfInt.cpp.
                   :
  p_(0),
  data_(0),
  size_array_(0),
  memory_size_(0),
  smart_resize_(0),
  storage_type_(STANDARD)
{
}
ArrOfInt::ArrOfInt (int size)
Cree un tableau de taille n avec allocation standard (voir set_mem_storage).
Le tableau est rempli avec zero par defaut. Pour creer un tableau non initialise, utiliser:
ArrOfInt toto;
toto.resize_array(n, NOCOPY_NOINIT);
Parametre: int n
Signification: taille du tableau.
Definition at line 343 of file ArrOfInt.cpp.
References Array_base::COPY_INIT, data_, fill_default_value(), VIntdata::get_data(), p_, and STANDARD.
                        :
  p_(0),
  data_(0),
  size_array_(n),
  memory_size_(n),
  smart_resize_(0),
  storage_type_(STANDARD)
{
  if (n)
    {
      p_ = new VIntdata(n, STANDARD);
      data_ = p_->get_data();
      fill_default_value(COPY_INIT, 0, n);
    }
}
ArrOfInt::ArrOfInt (const ArrOfInt & A)
Constructeur par copie. On alloue une nouvelle zone de memoire
et on copie le contenu du tableau (il s'agit d'un "deep copy").
L'attribut smart_resize_ est copie aussi.
Si le tableau A est de taille nulle, on cree un tableau "detache",
sinon on cree un tableau "normal".
Parametre: const ArrOfInt& A
Signification: le tableau a copier.
Definition at line 391 of file ArrOfInt.cpp.
References data_, VIntdata::get_data(), inject_array(), memory_size_, p_, size_array(), size_array_, smart_resize_, STANDARD, and storage_type_.
                                   : Array_base()
{
  const int size = A.size_array();
  if (size > 0)
    {
// Creation d'un tableau "normal"
      storage_type_ = STANDARD;
      p_ = new VIntdata(size, STANDARD);
      data_ = p_->get_data();
      size_array_ = size;
      memory_size_ = size;
      smart_resize_ = A.smart_resize_;
      inject_array(A);
    }
  else
    {
// Creation d'un tableau "detache"
      p_ = 0;
      data_ = 0;
      size_array_ = 0;
      memory_size_ = 0;
      smart_resize_ = 0;
      storage_type_ = STANDARD;
    }
}
Member Function Documentation
const int * ArrOfInt::addr () const [inline]
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Attention, l'adresse peut changer apres un appel
a resize_array(), ref_data, ref_array, ...
Returns:
const int*
Signification: pointeur sur le premier element du tableau
Definition at line 371 of file ArrOfInt.h.
References data_.
Referenced by add_to_vect_blocs(), add_to_vect_items(), affecte_int_avec_inttab(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Morse::ajouter_multvect_(), IntTab::append_line(), SETS::assembler(), Domaine::buildUFacesMesh(), carre(), Scatter::Chercher_Correspondance(), Solv_Cholesky::Cholesky(), interface_CALCULBIJ::Compute(), Partitionneur_Tranche::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Metis::construire_partition(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), Matrice_Morse::diagmulmat(), disp_ia(), disp_it(), disp_m(), Debog_Pb::ecrire_partie(), DomaineCutter::ecrire_zones(), envoyer_all_to_all(), exchange_data(), ILU::factoriser(), get_seq_flags(), ILU::ilu(), ILU::ilut(), Traduction_Indice_Global_Local::initialiser(), inject_array(), Decouper_multi::interpreter(), Lire_Ideas::interpreter_(), invalidate_data(), Matrice_Morse::inverse(), Matrice_Dense::inverse(), SolvElem_Gmres::iteration(), SolvElem_BiCGStab::iteration(), Matrice_Morse::largeur_de_bande(), Champ_Fonc_MED::lire(), IntVect::lit(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), max_to_vect_items(), Chimie::mettre_a_jour(), mincol1_to_vect_items(), mp_collective_op(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operator+(), operator==(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), IntTab::printOn(), racine_carree(), read_from_vect_blocs(), read_from_vect_items(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), Matrice_Morse_Sym::renumerote(), Solv_Petsc::resoudre_systeme(), tab_divide_any_shape_(), tab_multiply_any_shape_(), traite_diagonale(), tri_lexicographique_tableau(), tri_lexicographique_tableau_indirect(), trier_index_colonne_i(), Debog_Pb::verifier_partie_std(), Format_Post_Lata::write_inttab(), write_to_vect_blocs(), and write_to_vect_items().
{
  return data_;
}
int * ArrOfInt::addr () [inline]
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Returns:
const int*
Signification: la zone memoire du tableau
Definition at line 382 of file ArrOfInt.h.
References data_.
{
  return data_;
}
void ArrOfInt::append_array (int valeur) [inline]
Ajoute une case en fin de tableau et y stocke la "valeur".
Definition at line 355 of file ArrOfInt.h.
References Array_base::COPY_NOINIT, data_, resize_array(), size_array_, smart_resize_, and valeur().
Referenced by Schema_Comm_Vecteurs::add(), Objet_a_lire::add_dict(), MD_Vector_composite::add_part(), Sonde::ajouter_bords(), Scatter::ajouter_joints(), append_global_md(), MD_Vector_base2::append_item_to_blocs(), Polygone::build_reduced(), Polyedre::build_reduced(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::check_consistancy_remote_items(), Raccord_distant_homogene::completer(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), construire_liste_faces_sous_domaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), DomaineCutter::construire_sommets_joints_ssdom(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), creer_md_vect_renum(), DomaineCutter::ecrire_zones(), extract_blocs(), Domaine_bord::extraire_domaine_bord(), Octree_Zone::find_elements(), find_matching_coordinates(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Create_domain_from_sous_zone::interpreter_(), Scatter::mergeDomains(), parcourir_epaisseurs_elements(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Scatter::reordonner_faces_de_joint(), search_connex_components_local(), and Octree_Int::search_elements_box_floor().
{
  assert(smart_resize_);
  const int n = size_array_;
  resize_array(size_array_+1, COPY_NOINIT);
  data_[n] = valeur;
}
void ArrOfInt::array_trier_retirer_doublons ()
Tri des valeurs du tableau dans l'ordre croissant et suppresion des doublons
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Definition at line 911 of file ArrOfInt.cpp.
References data_, ordonne_array(), resize_array(), and size_array_.
Referenced by Scatter::mergeDomains().
{
  const int size_ = size_array_;
  if (size_ <= 0)
    return;
// Tri dans l'ordre croissant
  ordonne_array();
// Retire les doublons (codage optimise en pointeurs)
  int last_value = *data_;
  int *src = data_ + 1;
  int *dest = data_ + 1;
  for (int i = size_ - 1; i != 0; i--)
    {
      int x = *(src++);
      if (x != last_value)
        {
          *(dest++) = x;
          last_value = x;
        }
    }
  int new_size_ = dest - data_;
  resize_array(new_size_);
}
void ArrOfInt::attach_array (const ArrOfInt & a, int start = 0, int size = -1) [protected]
Amene le tableau dans l'etat "normal", "detache" ou "ref_array"
en associant une sous-zone de memoire du tableau m, definie par start et size
Si size < 0, on prend le tableau m jusqu'a la fin.
Definition at line 1042 of file ArrOfInt.cpp.
References VIntdata::add_one_ref(), data_, memory_size_, p_, size_array(), size_array_, and smart_resize_.
Referenced by IntVect::ref(), and ref_array().
{
// Le tableau doit etre detache
  assert(data_ == 0 && p_ == 0);
// Le tableau doit etre different de *this
  assert(&m != this);
  if (size < 0)
    size = m.size_array_ - start;
  assert(start >= 0 && size >=0 && start + size <= m.size_array_);
  if (m.size_array() > 0)
    {
      p_ = m.p_;
      if (p_)
        p_->add_one_ref();
      data_ = m.data_ + start;
      size_array_ = size;
      memory_size_ = m.memory_size_ - start;
      smart_resize_ = m.smart_resize_;
    }
  else
    {
// Cas particulier ou on attache un tableau de taille nulle:
// en theorie, c'est pareil qu'un tableau de taille non nulle, MAIS
// dans les operateurs (ex:Op_Dift_VDF_Face_Axi), une ref est construite
// avant que le tableau ne prenne sa taille definitive. Donc, pour ne pas
// empecher le resize, il ne faut pas attacher le tableau s'il n'a pas
// encore la bonne taille. Solution propre: reecrire les operateurs pour
// qu'ils ne prennent pas une ref avant que le tableau ne soit valide
// et faire p_ = m.p_ dans tous les cas.
// Process::Journal() << "Warning ArrOfInt::attach_array(m), m.size_array()==0, on n attache pas le tableau" << finl;
    }
}
ArrOfInt & ArrOfInt::copy_array (const ArrOfInt & a)
appelle operator=(a)
Definition at line 501 of file ArrOfInt.cpp.
References operator=().
{
  operator=(a);
  return *this;
}
Objet_U * ArrOfInt::cree_instance () [static]
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
{
int ArrOfInt::detach_array () [protected]
Amene le tableau dans l'etat "detache". C'est a dire:
Si le tableau est "detache" :
* ne rien faire
Si le tableau est "normal" :
* decremente le nombre de references a *p
* detruit *p si p->ref_count==0
* annule p_, data_ et size_array_
Si le tableau est "ref_data" :
* annule data_ et size_array_.
Returns:
int
Signification: 1 si les donnees du tableau ont ete supprimees
Definition at line 1002 of file ArrOfInt.cpp.
References data_, memory_size_, p_, size_array_, and VIntdata::suppr_one_ref().
Referenced by memory_resize(), IntVect::ref(), ref_array(), ref_data(), reset(), and ~ArrOfInt().
{
  int retour = 0;
  if (p_)
    {
// Le tableau est de type "normal"
// Si la zone de memoire n'est plus utilisee par personne,
// on la detruit.
      if ((p_->suppr_one_ref()) == 0)
        {
          delete p_;
          retour = 1;
        }
      p_ = 0;
    }
  data_ = 0;
  size_array_ = 0;
  memory_size_ = 0;
  return retour;
}
int ArrOfInt::duplique () const [virtual]
Implements Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
{
void ArrOfInt::fill_default_value (Array_base::Resize_Options opt, int first, int nb) [protected]
Remplit "nb" cases consecutives du tableau a partir de la case "first"
avec une valeur par defaut.
Cette fonction est appelee lors d'un resize pour initialiser les
cases nouvellement creees.
Le comportement depend actuellement du type de tableau :
* Tableau de type "smart_resize":
* en mode debug (macro NDEBUG non definie) le tableau est initialise
avec une valeur invalide.
* en optimise, le tableau n'est pas initialise
* Tableau normal :
Le tableau est initialise avec la valeur 0. Ce comportement est choisi
pour des raisons de compatibilite avec l'implementation precedente.
Cette specification pourrait etre modifiee prochainement pour des raisons
de performances (pour ne pas avoir a initialiser inutilement les tableaux).
DONC: il faut supposer desormais que les nouvelles cases ne sont pas
initialisees lors d'un resize.
Parametre: first
Signification: premiere case a initialiser.
Contrainte: (nb==0) ou (0 <= first < memory_size_)
Parametre: nb
Signification: nombre de cases a initialiser.
Contrainte: (nb==0) ou (0 < nb <= memory_size_ - first)
Definition at line 651 of file ArrOfInt.cpp.
References Array_base::COPY_INIT, data_, and memory_size_.
Referenced by ArrOfInt(), and memory_resize().
{
  assert((nb == 0) || (first >= 0 && first < memory_size_));
  assert((nb == 0) || (nb > 0 && nb <= memory_size_ - first));
  int * data = data_;
  assert(data!=0 || nb==0);
  data += first;
  if (opt != COPY_INIT)
    {
// On initialise uniquement en mode debug
#ifndef NDEBUG
      static const int INT_INVALIDE = INT_MIN;
      for (int i = 0; i < nb; i++)
        data[i] = INT_INVALIDE;
#endif
    }
  else
    {
// Comportement pour les tableaux normaux : compatibilite avec la
// version precedente : on initialise avec 0.
      for (int i = 0; i < nb; i++)
        data[i] = (int) 0;
    }
}
const Type_info * ArrOfInt::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
Referenced by IntVect::copy(), and resize_array().
{
enum ArrOfInt::Storage ArrOfInt::get_mem_storage () const
Renvoie le mode d'allocation du tableau (qui sera utilise
lors du prochain resize si changement de taille).
(voir VIntdata et Int_ptr_trav)
Definition at line 433 of file ArrOfInt.cpp.
References storage_type_.
{
  return storage_type_;
}
const Type_info * ArrOfInt::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
Referenced by resize_array().
{
ArrOfInt & ArrOfInt::inject_array (const ArrOfInt & source, int nb_elements = -1, int first_element_dest = 0, int first_element_source = 0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
Returns:
ArrOfInt&
Signification: *this
Contraintes:
Definition at line 1098 of file ArrOfInt.cpp.
References addr(), data_, and size_array().
Referenced by append_array_to_array(), ArrOfInt(), Zone_VF::construire_face_virt_pe_num(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), IntVect::copy(), IntVect::copy_(), Static_Int_Lists::copy_list_to_array(), envoyer_all_to_all(), ExtrudeParoi::extrude(), Champ_front_recyclage::mettre_a_jour(), operator=(), Solv_GCP::prepare_data(), Static_Int_Lists::set(), and Static_Int_Lists::set_data().
{
  assert(&source != this);
  assert(nb_elements >= -1);
  assert(first_element_dest >= 0);
  assert(first_element_source >= 0);
  if (nb_elements < 0)
    nb_elements = source.size_array();
  assert(first_element_source + nb_elements <= source.size_array());
  assert(first_element_dest + nb_elements <= size_array());
  if (nb_elements > 0)
    {
      int * addr_dest = data_ + first_element_dest;
      const int * addr_source = source.addr() + first_element_source;
// PL: On utilise le memcpy car c'est VRAIMENT plus rapide (10% +vite sur RNR_G20)
      memcpy(addr_dest , addr_source, nb_elements * sizeof(int));
      /*
        int i;
        for (i = 0; i < nb_elements; i++) {
        addr_dest[i] = addr_source[i];
        } */
    }
  return *this;
}
void ArrOfInt::memory_resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) [private]
Si besoin, alloue une nouvelle zone de memoire,
copie les donnees et efface l'ancienne zone de memoire.
Attention, on suppose que cette methode est appelee par
resize_array().
Attention: si ref_count_>1, l'appel a resize_array() est
autorise uniquement si la nouvelle taille est identique
a la precedente (auquel cas on ne fait rien)
Si ref_count_ == 1, l'appel est invalide si p_->data_ est
different de data_ (le tableau a ete construit avec ref_array()
avec start > 0)
Definition at line 542 of file ArrOfInt.cpp.
References Array_base::COPY_INIT, data_, detach_array(), fill_default_value(), VIntdata::get_data(), VIntdata::get_size(), memory_size_, Array_base::NOCOPY_NOINIT, p_, ref_count(), size_array_, smart_resize_, and storage_type_.
Referenced by resize_array_().
{
  assert(new_size >= 0);
// Si new_size==size_array_, on ne fait rien, c'est toujours autorise
  if (new_size == size_array_)
    return;
// Sinon, il faut que le resize soit autorise, c'est a dire
// - soit le tableau est detache
// - soit le tableau est normal et il n'y a pas d'autre reference au tableau
  assert((data_ == 0) || ((p_ != 0) && (p_->get_data() == data_) && (ref_count() == 1)));
// Occupation memoire de l'ancien tableau:
  int old_mem_size = memory_size_;
  assert((!p_) || (p_->get_size() == memory_size_));
  assert(memory_size_ >= size_array_);
// Occupation memoire du nouveau tableau :
// Si smart_resize, on prend au moins deux fois la taille
// precedente, ou new_size
  int new_mem_size = new_size;
  if (smart_resize_)
    {
      if (new_size <= old_mem_size)
        new_mem_size = old_mem_size;
      else if (new_size < old_mem_size * 2)
        new_mem_size = old_mem_size * 2;
      else if (new_size > old_mem_size && old_mem_size > INT_MAX / 2)
        new_mem_size = INT_MAX;
    }
  if (new_mem_size != old_mem_size)
    {
// detach_array() efface le contenu de size_array_. On le met de cote:
      const int old_size_array = size_array_;
      if (new_mem_size == 0)
        {
// La nouvelle taille est nulle, on cree un tableau "detache"
          detach_array();
        }
      else
        {
// Allocation d'une nouvelle zone
          VIntdata * new_p = new VIntdata(new_mem_size, storage_type_);
          int * new_data = new_p->get_data();
// Raccourci si le tableau etait "detache", inutile de copier
// les anciennes donnees. On copie si COPY_OLD est demande
          int copy_size = 0;
          if (data_ != 0)
            {
// Calcul du nombre d'elements a copier vers la nouvelle
// zone de memoire : c'est le min de l'ancienne et de
// la nouvelle taille.
              if (opt != NOCOPY_NOINIT)
                {
                  copy_size = size_array_;
                  if (new_size < copy_size)
                    copy_size = new_size;
// Copie des valeurs dans le nouveau tableau
                  for (int i = 0; i < copy_size; i++)
                    new_data[i] = data_[i];
                }
// Destruction de l'ancienne zone (si plus aucune reference)
              detach_array();
            }
// On attache la nouvelle zone de memoire
          p_ = new_p;
          data_ = new_data;
          memory_size_ = new_mem_size;
// Initialisation des cases supplementaires avec une valeur par defaut
          fill_default_value(opt, copy_size, new_mem_size - copy_size);
// Restaure l'ancienne valeur de size_array_
          size_array_ = old_size_array;
        }
    }
  else
    {
// Pas de reallocation, initialisation si besoin
      if (opt == COPY_INIT && new_size > size_array_)
        {
          fill_default_value(opt, size_array_, new_size - size_array_);
        }
    }
}
int & ArrOfInt::operator() (int i) [inline]
idem operator[]
Reimplemented in IntTab.
Definition at line 327 of file ArrOfInt.h.
References operator[]().
{
  return operator[](i);
}
const int & ArrOfInt::operator() (int i) const [inline]
Reimplemented in IntTab.
Definition at line 332 of file ArrOfInt.h.
References operator[]().
{
  return operator[](i);
}
ArrOfInt & ArrOfInt::operator+= (const ArrOfInt & y)
Addition case a case sur toutes les cases du tableau.
Returns:
ArrOfInt&
Signification: *this
Contraintes:
Definition at line 1157 of file ArrOfInt.cpp.
References data_, and size_array().
{
  assert(size_array()==y.size_array());
  int* dx = data_;
  const int* dy = y.data_;
  const int n = size_array();
  for (int i=0; i<n; i++)
    dx[i] += dy[i];
  return *this;
}
ArrOfInt & ArrOfInt::operator+= (const int dy)
ajoute la meme valeur a toutes les cases du tableau
Returns:
ArrOfInt
Signification: *this
Contraintes:
Reimplemented in IntVect.
Definition at line 1182 of file ArrOfInt.cpp.
References data_, and size_array().
{
  int * data = data_;
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] += dy;
  return *this;
}
ArrOfInt & ArrOfInt::operator-= (const int dy)
soustrait la meme valeur a toutes les cases
Returns:
ArrOfInt &
Signification: *this
Reimplemented in IntVect.
Definition at line 1212 of file ArrOfInt.cpp.
References data_, and size_array().
{
  int * data = data_;
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] -= dy;
  return *this;
}
ArrOfInt & ArrOfInt::operator-= (const ArrOfInt & y)
Soustraction case a case sur toutes les cases du tableau
Parametre: const ArrOfInt& y
Signification: tableau de meme taille que *this.
Returns:
ArrOfInt&
Signification: *this
Definition at line 1196 of file ArrOfInt.cpp.
References data_, and size_array().
{
  const int size = size_array();
  assert(size == y.size_array());
  int * data = data_;
  const int * data_y = y.data_;
  for (int i=0; i < size; i++)
    data[i] -= data_y[i];
  return *this;
}
ArrOfInt & ArrOfInt::operator= (const ArrOfInt & m)
Copie les donnees du tableau m.
Si "m" n'a pas la meme taille que "*this", on fait un resize_array.
Ensuite, on copie les valeurs de "m" dans "*this".
Le type de tableau (methode d'allocation) n'est pas copie.
Returns:
ArrOfInt&
Signification: *this
Definition at line 468 of file ArrOfInt.cpp.
References inject_array(), Array_base::NOCOPY_NOINIT, resize_array(), and size_array().
Referenced by copy_array().
{
  if (&m != this)
    {
      const int new_size = m.size_array();
// On utilise la methode resize_array() qui teste le type derive de l'objet
// (resize interdit sur un type derive)
      resize_array(new_size, NOCOPY_NOINIT);
      inject_array(m);
    }
  return *this;
}
ArrOfInt & ArrOfInt::operator= (int x) [inline]
x est affecte a toutes les cases
Returns:
ArrOfInt&
Signification: *this
Contraintes:
Reimplemented in IntTab, IntTrav, and IntVect.
Definition at line 288 of file ArrOfInt.h.
References data_, and size_array_.
{
  const int n = size_array_;
  int *data = data_;
  for (int i = 0; i < n; i++)
    {
      data[i] = x;
    }
  return *this;
}
ArrOfInt& ArrOfInt::operator= (const FArrOfInt &)
const int & ArrOfInt::operator[] (int i) const [inline]
operateur [] retourne le ieme element du tableau
Reimplemented in IntTab.
Definition at line 319 of file ArrOfInt.h.
References data_, and size_array_.
{
  assert(i >= 0 && i < size_array_);
  return data_[i];
}
int & ArrOfInt::operator[] (int i) [inline]
operateur [] retourne le ieme element du tableau
Reimplemented in IntTab.
Definition at line 306 of file ArrOfInt.h.
References data_, and size_array_.
Referenced by operator()().
{
  assert(i >= 0 && i < size_array_);
  return data_[i];
}
void ArrOfInt::ordonne_array ()
Tri des valeurs du tableau dans l'ordre croissant.
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Definition at line 897 of file ArrOfInt.cpp.
References data_, fonction_compare_arrofint_ordonner(), and size_array_.
Referenced by array_trier_retirer_doublons(), array_trier_retirer_doublons(), auto_build_joints(), Scatter::calculer_espace_distant(), Schema_Comm::check_send_recv_pe_list(), Raccord_distant_homogene::completer(), OctreeFloor::construire(), DomaineCutter::construire_elements_distants_ssdom(), Scatter::corriger_espace_distant_elements_perio(), Schema_Comm_Vecteurs::end_init(), Matrice_Morse::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Remove_elem::recreer_faces(), Remove_elem::remplir_liste(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), reordonner_vdf(), tri_lexicographique_tableau(), Scatter::trier_les_joints(), and Static_Int_Lists::trier_liste().
{
  const int size = size_array_;
  if (size > 1)
    {
      int * data = data_;
      qsort(data, size, sizeof(int),
            fonction_compare_arrofint_ordonner);
    }
}
Sortie & ArrOfInt::printOn (Sortie & os) const [protected, virtual]
Ecriture du tableau sur "os" :
ecrit le nombre d'elements suivi des valeurs du tableau.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 264 of file ArrOfInt.cpp.
References data_, finl, Sortie::put(), size_array(), and sz.
{
  int sz=size_array();
  os << sz << finl;
  if (sz > 0)
    {
      const int* v = data_;
      os.put(v,sz,sz);
    }
  return os;
}
Entree & ArrOfInt::readOn (Entree & is) [protected, virtual]
Lecture d'un tableau dans un flot d'entree
Lit le nombre d'elements suivi des elements eux-memes.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 291 of file ArrOfInt.cpp.
References Cerr, data_, Process::exit(), finl, Entree::get(), resize_array_(), and sz.
{
  int sz;
  is >> sz;
  if (sz >= 0)
    {
// Appel a la methode sans precondition sur le type derive
// (car readOn est virtuelle, les autres proprietes seront initialisees correctement)
      resize_array_(sz);
      if (sz > 0)
        {
          int* v = data_;
          is.get(v,sz);
        }
    }
  else
    {
      Cerr << "Error in ArrOfInt:readOn : size = " << sz << finl;
      assert(0);
      exit();
    }
  return is;
}
void ArrOfInt::ref_array (ArrOfInt & m, int start = 0, int size = -1) [virtual]
Fait pointer le tableau vers les memes donnees qu'un tableau
existant. Le tableau sera du meme type que le tableau m ("detache",
"normal"). Le tableau m ne doit pas etre de type "ref_data"
Attention, le tableau source et *this sont ensuite figes (resize_array()
interdit).
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Parametre: const ArrOfInt& m
Signification: le tableau a referencer (pas de type "ref_data"
et different de *this !!!)
Returns:
ArrOfInt&
Signification: *this
Contraintes:
Reimplemented in IntTab, and IntVect.
Definition at line 952 of file ArrOfInt.cpp.
References attach_array(), and detach_array().
Referenced by Traduction_Indice_Global_Local::traduire_espace_virtuel(), and Static_Int_Lists::trier_liste().
{
  assert(&m != this);
// La condition 'm n'est pas de type "ref_data"' est necessaire pour
// attach_array().
  detach_array();
  attach_array(m, start, size);
}
int ArrOfInt::ref_count () const
Retourne le nombre de references des donnees du tableau
si le tableau est "normal", -1 s'il est "detache" ou "ref_data".
Returns:
int
Signification: ref_count_
Definition at line 1134 of file ArrOfInt.cpp.
References p_, and VIntdata::ref_count().
Referenced by memory_resize(), operator<<(), and resize_array_().
{
  if (p_)
    return p_->ref_count();
  else
    return -1;
}
void ArrOfInt::ref_data (int * ptr, int size) [virtual]
Fait pointer le tableau vers la zone de memoire "data_".
On detache la zone de memoire existante. Le tableau devient
de type "ref_data". Attention : ptr doit etre non nul.
La taille est initialisee avec size.
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Pour faire une ref sur un tableau parallele utiliser IntVect::ref()
Parametre: int*
Signification: le tableau a recuperer. Si pointeur nul alors size
doit etre nulle aussi et le tableau reste detache
Parametre: int size
Signification: le nombre d'elements du tableau.
Returns:
ArrOfInt&
Signification: *this
< Pour passer les tests si on resize a la meme taille
Reimplemented in IntTab, and IntVect.
Definition at line 976 of file ArrOfInt.cpp.
References data_, detach_array(), memory_size_, and size_array_.
Referenced by Partitionneur_Tranche::construire_partition(), Schema_Comm_Vecteurs::get_next_area_int(), and Solv_GCP::prepare_data().
{
  assert(ptr != 0 || size == 0);
  assert(size >= 0);
  detach_array();
  data_ = ptr;
  size_array_ = size;
  memory_size_ = size; //!< Pour passer les tests si on resize a la meme taille
}
void ArrOfInt::reset () [virtual]
Remet le tableau dans l'etat obtenu avec le constructeur par defaut
(libere la memoire mais conserve le mode d'allocation memoire actuel)
Reimplemented in IntTab, and IntVect.
Definition at line 452 of file ArrOfInt.cpp.
References detach_array().
Referenced by Domaine_bord::extraire_domaine_bord(), Domaine::read_vertices(), Domaine::readOn(), Octree_Int::reset(), Joint_Items::reset(), and DomaineCutter_Correspondance::reset().
{
  detach_array();
}
void ArrOfInt::resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) [inline]
appel a ArrOfInt::resize_array()
Reimplemented in IntTab, and IntVect.
Definition at line 248 of file ArrOfInt.h.
References resize_array().
Referenced by Partitionneur_Tranche::associer_domaine(), Polyedre::compute_virtual_index(), construire_elems_sous_domaine(), init_parts(), MD_Vector_std::MD_Vector_std(), and Champ_Fonc_MED::readOn().
{
  resize_array(new_size, opt);
}
void ArrOfInt::resize_array (int new_size, Array_base::Resize_Options opt = COPY_INIT) [inline]
Definition at line 240 of file ArrOfInt.h.
References get_info(), info(), resize_array_(), and size_array_.
Referenced by RTabInt::add(), CSR_Builder::add_coeff(), Op_Conv_VEF_Face::ajouter(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), append_array(), append_array_to_array(), append_blocs(), append_global_md(), append_items(), array_calculer_intersection(), array_retirer_elements(), array_smart_allocate(), array_trier_retirer_doublons(), array_trier_retirer_doublons(), auto_build_joints(), Schema_Comm_Vecteurs::begin_init(), Octree_Int::build(), Octree_Int::build_octree_floor(), Octree_Int::build_octree_recursively(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_renum_sans_doublons(), Partitionneur_Tranche::chercher_direction_perio(), chercher_elems_voisins_faces(), Terme_Source_Rappel_T_VEF_Face::completer(), Periodique::completer(), compute_global_connex_components(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_sommets_sousdomaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Parmetis::construire_partition(), Zone_VEF_PreP1b::construire_renum_arete_perio(), DomaineCutter::construire_sommets_joints_ssdom(), construit_connectivite_sommet(), Static_Int_Lists::copy_list_to_array(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_reeles(), Zone_VEF::creer_faces_virtuelles_non_std(), Zone_PolyMAC::creer_faces_virtuelles_non_std(), Zone_EF::creer_faces_virtuelles_non_std(), creer_md_vect_renum(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), DomaineCutter::ecrire_zones(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), extract_blocs(), ILU::factoriser(), find_adjacent_elements(), Octree_Zone::find_elements(), find_matching_coordinates(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), MD_Vector_tools::get_sequential_items_flags(), Matrice_Morse::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Zone::init_faces_virt_bord(), Comm_Group::init_group(), Comm_Group::init_group_trio(), init_parts(), init_simple_md_vector(), Raccord_distant_homogene::initialise(), Ch_front_Vortex::initialiser(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Remove_Invalid_Internal_Boundaries::interpreter_(), Lire_Tgrid::interpreter_(), lire_special(), Assembleur_P_VDF::liste_faces_periodiques(), Op_EF_base::marque_elem(), Zone_VF::marquer_faces_double_contrib(), MD_Vector_std::MD_Vector_std(), Chimie::mettre_a_jour(), mon_construire_correspondance_items_par_coordonnees(), operator=(), parcourir_epaisseurs_elements(), OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), OctreeRoot::rang_elem_depuis(), OctreeRoot::rang_elems_sommet(), OctreeRoot::rang_sommet(), Sous_Zone::readOn(), Probleme_Couple::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), remplir_marqueur_sommet_neumann(), Zone_Cl_EF::remplir_type_elem_Cl(), Matrice_Morse_Sym::renumerote(), Static_Int_Lists::reset(), RTabInt::resize(), resize(), resize_tab(), reverse_send_recv_pe_list(), RTabInt::RTabInt(), search_connex_components_local(), Octree_Int::search_elements_box(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), Static_Int_Lists::set(), Static_Int_Lists::set_list_sizes(), tri_lexicographique_tableau_indirect(), trier(), and trier_abs().
{
// Si le tableau change de taille, il doit etre du type ArrOfInt
  assert(new_size == size_array_ || get_info() == ArrOfInt::info());
  resize_array_(new_size, opt);
}
void ArrOfInt::resize_array_ (int n, Array_base::Resize_Options opt = COPY_INIT) [inline, protected]
methode protegee de changement de taille, appelable par
les classes derivees (idem que resize_array() mais sans condition sur le
type derive de l'objet)
Definition at line 256 of file ArrOfInt.h.
References Array_base::COPY_INIT, data_, memory_resize(), memory_size_, p_, ref_count(), size_array_, and smart_resize_.
Referenced by IntVect::copy_(), readOn(), resize_array(), and IntVect::resize_vect_().
{
  assert(new_size >= 0);
// Soit le tableau est detache (data_==0), soit il est normal (p_!=0)
// S'il est normal, il ne faut pas qu'il y ait d'autre reference au tableau,
// ou alors la taille ne doit pas changer.
  assert(new_size == size_array_ || data_ == 0 || (p_ != 0 && ref_count() == 1));
// Le seul cas ou on n'appelle pas memory_resize est le suivant:
// le tableau est smart_resize
// ET la taille reste inferieure ou egale a la taille allouee
// ET on ne veut pas initialiser les nouvelles cases
  if ((opt == COPY_INIT) || (new_size > memory_size_) || (smart_resize_ == 0))
// attention, il existe un cas ou memory_resize realloue un buffer meme si size_array_==new_size:
// si on est passe de smart_resize=1 a smart_resize=0, on realloue juste ce qu'il faut.
    memory_resize(new_size, opt);
  size_array_ = new_size;
}
void ArrOfInt::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Si l'objet est de type ArrOfInt, appel a resize_array(n)
Prerequis: le tableau doit etre "resizable" (voir resize_array()).
S'il est d'un type derive (Vect ou Tab), il ne doit pas avoir de descripteur
parallele si la taille est effectivement modifiee.
Reimplemented in IntTab, and IntVect.
Definition at line 513 of file ArrOfInt.cpp.
References resize_array().
Referenced by Zone::chercher_elements(), and Champ_front_recyclage::initialiser().
{
  resize_array(n, opt);
}
const ArrOfInt & ArrOfInt::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
{
ArrOfInt & ArrOfInt::self_cast (Objet_U & r) [static]
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
{
void ArrOfInt::set_mem_storage (const Storage storage)
Change le mode d'allocation memoire lors des resize<br>(voir VIntdata et Int_ptr_trav)
Exemple pour creer un tableau avec allocation temporaire:
DoubleTab tab; // Creation d'un tableau vide
tab.set_mem_storage(TEMP_STORAGE); // Changement de mode d'allocation
tab.resize(n); // Allocation memoire.
Definition at line 424 of file ArrOfInt.cpp.
References storage_type_.
Referenced by IntTrav::IntTrav().
{
  storage_type_ = storage;
}
void ArrOfInt::set_smart_resize (int flag)
Change le mode l'allocation memoire: reallocation d'un tableau
a chaque changement de taille (flag = 0) ou reallocation
uniquement si la taille augmente et par doublement de la taille
du tableau (flag = 1).
Definition at line 443 of file ArrOfInt.cpp.
References smart_resize_.
Referenced by Objet_a_lire::add_dict(), MD_Vector_composite::add_part(), Debog_Pb::add_renum_item(), Domaine::ajouter(), Sonde::ajouter_bords(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), append_global_md(), array_smart_allocate(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Octree_Int::build(), build_edges(), build_frontier(), Polygone::build_reduced(), Polyedre::build_reduced(), Calcul_integrale_locale::Calcul_integrale_locale(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::calculer_renum_items_communs(), calculer_renum_sans_doublons(), Scatter::check_consistancy_remote_items(), Raccord_distant_homogene::completer(), compute_global_connex_components(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Faces_builder::creer_faces_reeles(), creer_md_vect_renum(), Op_Grad_VDF_Face::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Div_CoviMAC::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Masse_CoviMAC_Face::dimensionner_blocs(), QDM_Multiphase::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Schema_Comm::echange_taille(), DomaineCutter::ecrire_zones(), Matrix_tools::extend_matrix_stencil(), extract_blocs(), Domaine_bord::extraire_domaine_bord(), Zone_CoviMAC::fgrad(), find_joint_faces(), find_matching_coordinates(), Matrice_Morse::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Champ_implementation_P1::init_from_file(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Zone_PolyMAC::init_m2solv(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Zone_CoviMAC::init_stencils(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Champ_Face_CoviMAC::init_ve2(), Zone_PolyMAC::init_we_2d(), Zone_PolyMAC::init_we_3d(), Champ_front_recyclage::initialiser(), Traduction_Indice_Global_Local::initialiser(), Remove_Invalid_Internal_Boundaries::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), lire_special(), MD_Vector_std::MD_Vector_std(), Scatter::mergeDomains(), Champ_front_recyclage::mettre_a_jour(), parcourir_epaisseurs_elements(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), Schema_Comm::Schema_Comm(), Schema_Comm_Vecteurs::Schema_Comm_Vecteurs(), and search_connex_components_local().
{
  assert(flag == 0 || flag == 1);
  smart_resize_ = flag;
}
int ArrOfInt::size_array () const [inline]
Renvoie la taille du tableau (nombre d'elements declares
a la construction ou a resize_array()).
C'est le nombre d'elements accessibles a operator[].
Returns:
int
Definition at line 342 of file ArrOfInt.h.
References size_array_.
Referenced by Schema_Comm_Vecteurs::add(), RTabInt::add(), CSR_Builder::add_coeff(), Debog_Pb::add_renum_item(), add_sommets_communs(), add_to_vect_blocs(), add_to_vect_items(), Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), affecte_int_avec_inttab(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Op_Conv_VEF_Face::ajouter(), Domaine::ajouter(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), ajouter_joints(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Faces_builder::ajouter_une_face(), append_array_to_array(), append_blocs(), append_global_md(), MD_Vector_base2::append_item_to_blocs(), append_items(), IntTab::append_line(), array_bsearch(), array_calculer_intersection(), array_retirer_doublons(), array_retirer_elements(), array_trier_retirer_doublons(), ArrOfInt(), attach_array(), auto_build_joints(), Schema_Comm_Vecteurs::begin_comm(), Octree_Int::build(), Refine_Mesh::build_edges(), build_frontier(), Octree_Int::build_octree_floor(), Octree_Int::build_octree_recursively(), Polygone::build_reduced(), Polyedre::build_reduced(), Calcul_integrale_locale::calculer(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), calculer_renum_sans_doublons(), carre(), Schema_Comm_Vecteurs::check_buffers_full(), Scatter::check_consistancy_remote_items(), Faces_builder::check_erreur_faces(), check_espace_virtuel_vect(), check_index_data(), Schema_Comm_Vecteurs::check_next_area(), check_PE_in_list(), Schema_Comm::check_send_recv_pe_list(), Scatter::Chercher_Correspondance(), Zone::chercher_elements(), chercher_elems_voisins_faces(), Matrice_Morse_Sym::compacte(), Raccord_distant_homogene::completer(), Periodique::completer(), compute_global_connex_components(), compute_graph_connex_components(), Polyedre::compute_virtual_index(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Octree::construire(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), construire_elems_sous_domaine(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), construire_liste_sommets_sousdomaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), Partitionneur_Partition::construire_partition(), Zone_VEF_PreP1b::construire_renum_arete_perio(), DomaineCutter::construire_sommets_joints_ssdom(), Segment::contient(), Point::contient(), IntVect::copy(), IntVect::copy_(), corriger(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), PE_Groups::create_group(), create_listb_geom(), create_listb_naif(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Zone_VEF::creer_faces_virtuelles_non_std(), Zone_PolyMAC::creer_faces_virtuelles_non_std(), Zone_EF::creer_faces_virtuelles_non_std(), creer_md_vect_renum(), MD_Vector_tools::creer_md_vect_renum_auto(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), Matrice_Morse::dimensionner(), disp_ia(), dump_lata(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), Decouper::ecrire(), Debog_Pb::ecrire_partie(), DomaineCutter::ecrire_zones(), Op_EF_base::elem_contribue(), SETS::eliminer(), Schema_Comm::end_comm(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), est_un_coin(), Schema_Comm_Vecteurs::exchange(), exchange_data(), MD_Vector_tools::extend(), extract_blocs(), find_adjacent_elements(), find_cl_face(), Refine_Mesh::find_edge(), find_in_array(), find_joint_faces(), find_matching_coordinates(), Static_Int_Lists::get_nb_lists(), get_seq_flags(), Matrice_Morse::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Polyedre::get_tab_faces_sommets_locaux(), imax_array(), imin_array(), Sonde::init_bords(), Champ_implementation_P1::init_from_file(), Comm_Group_Noparallel::init_group(), Comm_Group::init_group(), init_parts(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Traduction_Indice_Global_Local::initialiser(), DomaineCutter::initialiser(), Partitionneur_Tranche::initialiser(), Sonde::initialiser(), initialize_comm_(), inject_array(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Remove_Invalid_Internal_Boundaries::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), DecoupeBord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), IntTrav::IntTrav(), invalidate_data(), Probleme_Couple::iterateTimeStep(), Zone_VEF_PreP1b::lecture_ok_arete(), IntVect::line_size(), Champ_Fonc_MED::lire(), lire_special(), Perte_Charge_Singuliere::lire_surfaces(), IntVect::lit(), IntTab::lit(), local_carre_norme_tab(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_tab(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), max_abs_array(), max_array(), max_to_vect_items(), MD_Vector_std::MD_Vector_std(), meme_point(), Scatter::mergeDomains(), Champ_front_recyclage::mettre_a_jour(), Sonde::mettre_a_jour_bords(), min_abs_array(), min_array(), mincol1_to_vect_items(), Zone_VEF_PreP1b::modifier_pour_Cl(), mon_construire_correspondance_items_par_coordonnees(), mp_collective_op(), Front_VF::nb_faces_tot(), Frontiere::nb_faces_virt(), next(), Front_VF::num_local_face(), IntTab::operator()(), DoubleTab::operator()(), operator+=(), operator-=(), operator<<(), IntTab::operator=(), operator=(), operator==(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), parcourir_epaisseurs_elements(), Solv_GCP::prepare_data(), MD_Vector_std::prepare_send_data(), IntTab::printOn(), printOn(), MD_Vector_std::process_recv_data(), racine_carree(), OctreeFloor::rang_elem_depuis_loc(), OctreeFloor::rang_elem_loc(), Objet_a_lire::read(), read_from_vect_blocs(), read_from_vect_items(), Champ_Fonc_MED::readOn(), MD_Vector_std::readOn(), IntVect::readOn(), IntTab::readOn(), IntTab::ref(), IntVect::ref_array(), IntTab::ref_array(), IntTab::ref_data(), IntTab::ref_tab(), Raffiner_Simplexes::refine_domain(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), remplir_coordsommets_sous_domaine(), remplir_items_non_calcules_(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Zone::renum_joint_common_items(), Matrice_Morse_Sym::renumerote(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), Scatter::reordonner_faces_de_joint(), reordonner_vdf(), Precond_local::res_syst_loc_hybride(), RTabInt::resize(), IntVect::resize(), IntTab::resize(), DoubleTab::resize(), IntTab::resize_dim0(), Comm_Group_Noparallel::reverse_send_recv_list(), reverse_send_recv_pe_list(), search_connex_components_local(), Octree_Int::search_elements_box(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), Comm_Group_Noparallel::send_recv_start(), Comm_Group_MPI::send_recv_start(), Static_Int_Lists::set(), Static_Int_Lists::set_data(), Static_Int_Lists::set_list_sizes(), IntVect::set_md_vector(), IntVect::size_reelle(), IntVect::size_totale(), sort(), SSOR::ssor(), tab_divide_any_shape_(), tab_multiply_any_shape_(), OctreeFloor::taille(), Raccord_distant_homogene::trace_elem_distant(), Raccord_distant_homogene::trace_face_distant(), Traduction_Indice_Global_Local::traduire_indice_global_vers_local(), tri_lexicographique_tableau_indirect(), trier(), trier_abs(), trier_index_colonne_i(), Static_Int_Lists::trier_liste(), Champ_som_lu_VDF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu_VDF::valeur_aux_elems_compo(), Champ_som_lu::valeur_aux_elems_compo(), Champ_implementation_Q1::value_interpolation(), Champ_implementation_P1::value_interpolation(), Zone_VEF_PreP1b::verifie_ok_arete(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Debog_Pb::verifier_gen(), write_to_vect_blocs(), and write_to_vect_items().
{
  return size_array_;
}
unsigned ArrOfInt::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 38 of file ArrOfInt.cpp.
{
Member Data Documentation
int* ArrOfInt::data_ [private]
Definition at line 176 of file ArrOfInt.h.
Referenced by addr(), append_array(), array_trier_retirer_doublons(), ArrOfInt(), attach_array(), detach_array(), fill_default_value(), inject_array(), memory_resize(), operator+=(), operator-=(), operator=(), operator[](), ordonne_array(), printOn(), readOn(), ref_data(), and resize_array_().
const Type_info ArrOfInt::info_obj [static]
Reimplemented from Array_base.
Reimplemented in Esp_Dist, IntTab, IntTrav, and IntVect.
Definition at line 74 of file ArrOfInt.h.
int ArrOfInt::memory_size_ [private]
Definition at line 185 of file ArrOfInt.h.
Referenced by ArrOfInt(), attach_array(), detach_array(), fill_default_value(), memory_resize(), ref_data(), and resize_array_().
VIntdata* ArrOfInt::p_ [private]
Definition at line 168 of file ArrOfInt.h.
Referenced by ArrOfInt(), attach_array(), detach_array(), memory_resize(), ref_count(), and resize_array_().
int ArrOfInt::size_array_ [private]
Definition at line 180 of file ArrOfInt.h.
Referenced by append_array(), array_trier_retirer_doublons(), ArrOfInt(), attach_array(), detach_array(), memory_resize(), operator=(), operator[](), ordonne_array(), ref_data(), resize_array(), resize_array_(), size_array(), and ~ArrOfInt().
int ArrOfInt::smart_resize_ [private]
Definition at line 191 of file ArrOfInt.h.
Referenced by append_array(), ArrOfInt(), attach_array(), memory_resize(), resize_array_(), and set_smart_resize().
Storage ArrOfInt::storage_type_ [private]
Definition at line 195 of file ArrOfInt.h.
Referenced by ArrOfInt(), get_mem_storage(), memory_resize(), and set_mem_storage().
The documentation for this class was generated from the following files:
src/Kernel/Math/ArrOfInt.h
src/Kernel/Math/ArrOfInt.cpp