TRUST: Op_Conv_CoviMAC_base Class Reference
Op_Conv_CoviMAC_base Class Reference
class Op_Conv_CoviMAC_base
Classe de base des operateurs de convection VDF
#include <Op_Conv_CoviMAC_base.h>
Public Member Functions
Op_Conv_CoviMAC_base ()
~Op_Conv_CoviMAC_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const
calcule la contribution de la convection, la range dans resu
renvoie resu
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &)
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void associer_vitesse (const Champ_base &)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_CoviMAC_base & self_cast (Objet_U &)
static const Op_Conv_CoviMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_CoviMAC la_zone_poly_
Ref_Zone_Cl_CoviMAC la_zcl_poly_
Ref_Champ_Face_CoviMAC vitesse_
Detailed Description
class Op_Conv_CoviMAC_base
Classe de base des operateurs de convection VDF
Definition at line 48 of file Op_Conv_CoviMAC_base.h.
Constructor & Destructor Documentation
Op_Conv_CoviMAC_base::Op_Conv_CoviMAC_base ()
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
Op_Conv_CoviMAC_base::~Op_Conv_CoviMAC_base ()
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
Member Function Documentation
void Op_Conv_CoviMAC_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl, const Champ_Inc &) [virtual]
Implements Operateur_base.
Definition at line 162 of file Op_Conv_CoviMAC_base.cpp.
References la_zcl_poly_, la_zone_poly_, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_poly_ = ref_cast(Zone_CoviMAC,zone_dis.valeur());
  la_zcl_poly_ = ref_cast(Zone_Cl_CoviMAC,zcl.valeur());
}
void Op_Conv_CoviMAC_base::associer_vitesse (const Champ_base & ch) [virtual]
Implements Operateur_Conv_base.
Definition at line 245 of file Op_Conv_CoviMAC_base.cpp.
References ref_cast, and vitesse_.
{
  vitesse_= ref_cast(Champ_Face_CoviMAC, ch);
}
void Op_Conv_CoviMAC_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zcl) [virtual]
Reimplemented from Operateur_base.
Definition at line 157 of file Op_Conv_CoviMAC_base.cpp.
References la_zcl_poly_, and ref_cast.
{
  la_zcl_poly_ = ref_cast(Zone_Cl_CoviMAC,zcl);
}
DoubleTab & Op_Conv_CoviMAC_base::calculer (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
calcule la contribution de la convection, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 84 of file Op_Conv_CoviMAC_base.h.
References Operateur_base::ajouter().
{
  resu=0;
  return ajouter(inco,resu);
}
void Op_Conv_CoviMAC_base::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Face.
Definition at line 152 of file Op_Conv_CoviMAC_base.cpp.
{
  Operateur_base::completer();
}
virtual int Op_Conv_CoviMAC_base::duplique () const [pure virtual]
Implements Operateur_Conv_base.
Implemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
const Type_info * Op_Conv_CoviMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
int Op_Conv_CoviMAC_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 168 of file Op_Conv_CoviMAC_base.cpp.
References Sortie::add_col(), Objet_U::dimension, DoubleTab::dimension(), MorEqn::equation(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Process::je_suis_maitre(), la_zcl_poly_, la_zone_poly_, Frontiere_dis_base::le_nom(), Process::mp_sum(), DoubleTab::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), ref_cast, Probleme_base::schema_temps(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
{
  if (flux_bords_.nb_dim() != 2) return 0;
  const int impr_bord=(la_zone_poly_->zone().Bords_a_imprimer().est_vide() ? 0:1);
  SFichier Flux_div;
  ouvrir_fichier(Flux_div,"",je_suis_maitre());
  EcrFicPartage Flux_face;
  ouvrir_fichier_partage(Flux_face,"",impr_bord);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  double temps = sch.temps_courant();
  if (je_suis_maitre()) Flux_div.add_col(temps);
  int nb_compo=flux_bords_.dimension(1);
// On parcours les frontieres pour sommer les flux par frontiere dans le tableau flux_bord
  DoubleVect flux_bord(nb_compo);
  DoubleVect bilan(nb_compo);
  bilan = 0;
  for (int num_cl=0; num_cl<la_zone_poly_->nb_front_Cl(); num_cl++)
    {
      flux_bord=0;
      const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      for (int face=ndeb; face<nfin; face++)
        for(int k=0; k<nb_compo; k++)
          flux_bord(k)+=flux_bords_(face, k);
      for(int k=0; k<nb_compo; k++)
        flux_bord(k)=Process::mp_sum(flux_bord(k));
      if(je_suis_maitre())
        {
          for(int k=0; k<nb_compo; k++)
            {
// Ajout pour impression sur fichiers separes
              Flux_div.add_col(flux_bord(k));
              bilan(k)+=flux_bord(k);
            }
        }
    }
  if(je_suis_maitre())
    {
      for(int k=0; k<nb_compo; k++)
        {
          Flux_div.add_col(bilan(k));
        }
      Flux_div << finl;
    }
  for (int num_cl=0; num_cl<la_zone_poly_->nb_front_Cl(); num_cl++)
    {
      const Frontiere_dis_base& la_fr = la_zcl_poly_->les_conditions_limites(num_cl).frontiere_dis();
      const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      if (la_zone_poly_->zone().Bords_a_imprimer().contient(la_fr.le_nom()))
        {
          Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps " << temps << " : " << finl;
          for (int face=ndeb; face<nfin; face++)
            {
              if (dimension==2)
                Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " flux=" ;
              else if (dimension==3)
                Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " z= " << la_zone_poly_->xv(face,2) << " flux=" ;
              for(int k=0; k<nb_compo; k++)
                Flux_face << " " << flux_bords_(face, k);
              Flux_face << finl;
            }
          Flux_face.syncfile();
        }
    }
  return 1;
}
const Type_info * Op_Conv_CoviMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
Sortie & Op_Conv_CoviMAC_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 42 of file Op_Conv_CoviMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_CoviMAC_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 50 of file Op_Conv_CoviMAC_base.cpp.
{
  return s ;
}
const Op_Conv_CoviMAC_base & Op_Conv_CoviMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
Op_Conv_CoviMAC_base & Op_Conv_CoviMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 37 of file Op_Conv_CoviMAC_base.cpp.
Member Data Documentation
const Type_info Op_Conv_CoviMAC_base::info_obj [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 51 of file Op_Conv_CoviMAC_base.h.
Ref_Zone_Cl_CoviMAC Op_Conv_CoviMAC_base::la_zcl_poly_ [protected]
Definition at line 70 of file Op_Conv_CoviMAC_base.h.
Referenced by associer(), associer_zone_cl_dis(), and impr().
Ref_Zone_CoviMAC Op_Conv_CoviMAC_base::la_zone_poly_ [protected]
Definition at line 69 of file Op_Conv_CoviMAC_base.h.
Referenced by Travail_pression_CoviMAC::ajouter_blocs(), associer(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::completer(), QDM_Multiphase::dimensionner_blocs(), impr(), Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour(), and Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul().
Ref_Champ_Face_CoviMAC Op_Conv_CoviMAC_base::vitesse_ [protected]
Definition at line 71 of file Op_Conv_CoviMAC_base.h.
Referenced by Travail_pression_CoviMAC::ajouter_blocs(), associer_vitesse(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), QDM_Multiphase::dimensionner_blocs(), and Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Conv_CoviMAC_base.h
src/CoviMAC/Operateurs/Op_Conv_CoviMAC_base.cpp