TRUST: Source_Fluide_Dilatable_VEF_Proto Class Reference
Source_Fluide_Dilatable_VEF_Proto Class Reference
#include <Source_Fluide_Dilatable_VEF_Proto.h>
Protected Member Functions
void associer_zones_impl (const Zone_dis &zone, const Zone_Cl_dis &zone_cl)
void associer_volume_porosite_impl (const Zone_dis &zone, DoubleVect &volumes, DoubleVect &porosites)
void ajouter_impl (const Equation_base &eqn, const DoubleVect &g, const int dimension, const double rho_m, const DoubleTab &tab_rho, DoubleTab &resu) const
Protected Attributes
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_Cl
Detailed Description
Definition at line 27 of file Source_Fluide_Dilatable_VEF_Proto.h.
Member Function Documentation
ajouter_impl()
void Source_Fluide_Dilatable_VEF_Proto::ajouter_impl (const Equation_base & eqn, const DoubleVect & g, const int dimension, const double rho_m, const DoubleTab & tab_rho, DoubleTab & resu) const protected
Definition at line 39 of file Source_Fluide_Dilatable_VEF_Proto.cpp.
{
  const int nb_faces = la_zone->nb_faces(), premiere_face_interne = la_zone->premiere_face_int();
  const DoubleVect& volumes_entrelaces = la_zone->volumes_entrelaces();
  const DoubleVect& porosite_face = la_zone->porosite_face();
  const IntTab& face_voisins = la_zone->face_voisins();
  const DoubleTab& face_normales = la_zone->face_normales(), xp = la_zone->xp(), xv = la_zone->xv();
  if (eqn.discretisation().que_suis_je()=="VEF")
    {
// Boucle faces bord
      for (int num_cl=0 ; num_cl<la_zone->nb_front_Cl() ; num_cl++)
        {
          const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(num_cl);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
          if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
            {
              for (int face=ndeb ; face<nfin ; face++)
                {
                  int elem1 = face_voisins(face,0);
                  if (elem1==-1)  elem1 = face_voisins(face,1);
                  for (int comp=0 ; comp< Objet_U::dimension ; comp++)
                    {
                      double delta_coord = (xv(face,comp) - xp(elem1,comp));
                      for (int i=0 ; i<dimension ; i++)
                        resu(face,i) += (tab_rho(face)-rho_m)*delta_coord*face_normales(face,i)*g(comp);
                    }
                }
            }
          else if (sub_type(Periodique,la_cl.valeur()))
            {
              for (int face=premiere_face_interne ; face<nb_faces; face++)
                {
                  int elem1 = face_voisins(face,0), elem2 = face_voisins(face,1);
                  for (int comp=0 ; comp<dimension ; comp++)
                    {
                      double delta_coord = (xp(elem2,comp) - xp(elem1,comp));
                      for (int i=0 ; i<dimension ; i++)
                        resu(face,i) += (tab_rho(face)-rho_m)*delta_coord*face_normales(face,i)*g(comp);
                    }
                }
            }
        }
// Boucle faces internes
      for (int face=premiere_face_interne ; face<nb_faces; face++)
        {
          int elem1 = face_voisins(face,0), elem2 = face_voisins(face,1);
          for (int comp=0 ; comp<dimension ; comp++)
            {
              double delta_coord = (xp(elem2,comp) - xp(elem1,comp));
              for (int i=0 ; i<dimension ; i++)
                resu(face,i) += (tab_rho(face)-rho_m)*delta_coord*face_normales(face,i)*g(comp);
            }
        }
    }
  else if (eqn.discretisation().que_suis_je()=="VEFPreP1B")
    {
// Boucle faces bord
      for (int num_cl=0 ; num_cl<la_zone->nb_front_Cl() ; num_cl++)
        {
          const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(num_cl);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
          if (sub_type(Neumann_sortie_libre,la_cl.valeur())||sub_type(Symetrie,la_cl.valeur())||sub_type(Periodique,la_cl.valeur()))
            {
              for (int face=ndeb ; face<nfin ; face++)
                for (int comp=0 ; comp<dimension ; comp++)
                  resu(face,comp) += (tab_rho(face)-rho_m)*volumes_entrelaces(face)*porosite_face(face)*g(comp);
            }
        }
// Boucle faces internes
      for (int face=premiere_face_interne ; face<nb_faces; face++)
        for (int comp=0 ; comp<dimension ; comp++)
          resu(face,comp) += (tab_rho(face)-rho_m)*volumes_entrelaces(face)*porosite_face(face)*g(comp);
    }
  else
    {
      Cerr<<"La discretisation "<<eqn.discretisation().que_suis_je()<<" n'est pas reconnue dans Source_Fluide_Dilatable_VEF_Proto"<<finl;
      Process::exit();
    }
}
References Cerr, Objet_U::dimension, Equation_base::discretisation(), Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), la_zone, la_zone_Cl, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Zone_VF::volumes_entrelaces(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by Source_QC_Gravite_VEF::ajouter(), and Source_WC_Gravite_VEF::ajouter().
associer_volume_porosite_impl()
void Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl (const Zone_dis & zone, DoubleVect & volumes, DoubleVect & porosites) protected
Definition at line 33 of file Source_Fluide_Dilatable_VEF_Proto.cpp.
{
  volumes.ref(ref_cast(Zone_VF,zone.valeur()).volumes_entrelaces());
  porosites.ref(ref_cast(Zone_VF,zone.valeur()).porosite_face());
}
References TRUSTVect< _TYPE_ >::ref(), ref_cast, and Deriv_Zone_dis_base::valeur().
Referenced by Source_QC_Chaleur_VEF::associer_zones(), and Source_WC_Chaleur_VEF::associer_zones().
associer_zones_impl()
void Source_Fluide_Dilatable_VEF_Proto::associer_zones_impl (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) protected
Definition at line 27 of file Source_Fluide_Dilatable_VEF_Proto.cpp.
{
  la_zone = ref_cast(Zone_VEF,zone.valeur());
  la_zone_Cl = ref_cast(Zone_Cl_VEF,zone_cl.valeur());
}
References la_zone, la_zone_Cl, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by Source_QC_Gravite_VEF::associer_zones(), and Source_WC_Gravite_VEF::associer_zones().
Member Data Documentation
la_zone
Ref_Zone_VEF Source_Fluide_Dilatable_VEF_Proto::la_zone protected
Definition at line 34 of file Source_Fluide_Dilatable_VEF_Proto.h.
Referenced by ajouter_impl(), and associer_zones_impl().
la_zone_Cl
Ref_Zone_Cl_VEF Source_Fluide_Dilatable_VEF_Proto::la_zone_Cl protected
Definition at line 35 of file Source_Fluide_Dilatable_VEF_Proto.h.
Referenced by ajouter_impl(), and associer_zones_impl().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/VEF/Source_Fluide_Dilatable_VEF_Proto.h
src/ThHyd/Dilatable/Common/VEF/Source_Fluide_Dilatable_VEF_Proto.cpp