TRUST: Hexa_PolyMAC Class Reference
Hexa_PolyMAC Class Reference
#include <Hexa_PolyMAC.h>
Public Member Functions
~Hexa_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Hexa_PolyMAC ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
remplit le tableau face_normales dans la Zone_PolyMAC
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Hexa_PolyMAC & self_cast (Objet_U &)
static const Hexa_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 29 of file Hexa_PolyMAC.h.
Constructor & Destructor Documentation
Hexa_PolyMAC::~Hexa_PolyMAC ()
Definition at line 26 of file Hexa_PolyMAC.cpp.
Hexa_PolyMAC::Hexa_PolyMAC ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
Definition at line 44 of file Hexa_PolyMAC.cpp.
{
}
Member Function Documentation
void Hexa_PolyMAC::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl) const
Definition at line 184 of file Hexa_PolyMAC.cpp.
{
  vc[0] = vs[0]/6;
  vc[1] = vs[1]/6;
  vc[2] = vs[2]/6;
}
void Hexa_PolyMAC::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
Definition at line 198 of file Hexa_PolyMAC.cpp.
References DoubleVect::size().
{
  int j,dim=xg.size();
  for (j=0; j<dim; j++)
    xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j)+x(4,j)+x(5,j)+x(6,j)+x(7,j))*0.125;
  idirichlet=0;
}
Objet_U * Hexa_PolyMAC::cree_instance () [static]
Definition at line 26 of file Hexa_PolyMAC.cpp.
int Hexa_PolyMAC::duplique () const [virtual]
Implements Elem_PolyMAC_base.
Definition at line 26 of file Hexa_PolyMAC.cpp.
const Type_info * Hexa_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 26 of file Hexa_PolyMAC.cpp.
const Type_info * Hexa_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 26 of file Hexa_PolyMAC.cpp.
void Hexa_PolyMAC::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [virtual]
remplit le tableau face_normales dans la Zone_PolyMAC
Implements Elem_PolyMAC_base.
Definition at line 51 of file Hexa_PolyMAC.cpp.
References Domaine::coord_sommets(), and Zone::domaine().
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  double x1,y1,z1,x2,y2,z2;
  double nx,ny,nz;
  int f0,no4;
  int elem1;
// on a les 4 sommets de la face
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  int n2 = Face_sommets(num_Face,2);
  int n3 = Face_sommets(num_Face,3);
// on va decouper la face en deux triangles
// on initialise Face_normales(num_face,dimension) a 0
// car on va sommer les deux face_normale des triangles
  Face_normales(num_Face,0) =  0;
  Face_normales(num_Face,1) =  0;
  Face_normales(num_Face,2) =  0;
// on prend les sommet S1,S2 et S4
  x1 = les_coords(n0,0) - les_coords(n1,0);
  y1 = les_coords(n0,1) - les_coords(n1,1);
  z1 = les_coords(n0,2) - les_coords(n1,2);
  x2 = les_coords(n3,0) - les_coords(n1,0);
  y2 = les_coords(n3,1) - les_coords(n1,1);
  z2 = les_coords(n3,2) - les_coords(n1,2);
  nx = (y1*z2 - y2*z1)/2;
  ny = (-x1*z2 + x2*z1)/2;
  nz = (x1*y2 - x2*y1)/2;
// Orientation de la normale de elem1 vers elem2
// pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  elem1=Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no4 = Face_sommets(f0,0)) != n0    &&   no4 != n1
       &&   no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,1)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,2)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else
    no4 = Face_sommets(f0,3);
  x1 = les_coords(no4,0) - les_coords(n0,0);
  y1 = les_coords(no4,1) - les_coords(n0,1);
  z1 = les_coords(no4,2) - les_coords(n0,2);
  if ( (nx*x1+ny*y1+nz*z1) > 0 )
    {
      Face_normales(num_Face,0) +=  -nx;
      Face_normales(num_Face,1) +=  -ny;
      Face_normales(num_Face,2) +=  -nz;
    }
  else
    {
      Face_normales(num_Face,0) += nx;
      Face_normales(num_Face,1) += ny;
      Face_normales(num_Face,2) += nz;
    }
// on prend les sommet S1,S4 et S3
  x1 = les_coords(n0,0) - les_coords(n2,0);
  y1 = les_coords(n0,1) - les_coords(n2,1);
  z1 = les_coords(n0,2) - les_coords(n2,2);
  x2 = les_coords(n3,0) - les_coords(n2,0);
  y2 = les_coords(n3,1) - les_coords(n2,1);
  z2 = les_coords(n3,2) - les_coords(n2,2);
  nx = (y1*z2 - y2*z1)/2;
  ny = (-x1*z2 + x2*z1)/2;
  nz = (x1*y2 - x2*y1)/2;
// Orientation de la normale de elem1 vers elem2
// pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  elem1=Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no4 = Face_sommets(f0,0)) != n0    &&   no4 != n1
       &&   no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,1)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,2)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else
    no4 = Face_sommets(f0,3);
  x1 = les_coords(no4,0) - les_coords(n0,0);
  y1 = les_coords(no4,1) - les_coords(n0,1);
  z1 = les_coords(no4,2) - les_coords(n0,2);
  if ( (nx*x1+ny*y1+nz*z1) > 0 )
    {
      Face_normales(num_Face,0) +=  -nx;
      Face_normales(num_Face,1) +=  -ny;
      Face_normales(num_Face,2) +=  -nz;
    }
  else
    {
      Face_normales(num_Face,0) += nx;
      Face_normales(num_Face,1) += ny;
      Face_normales(num_Face,2) += nz;
    }
}
Sortie & Hexa_PolyMAC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 30 of file Hexa_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Hexa_PolyMAC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 35 of file Hexa_PolyMAC.cpp.
{
  return s ;
}
Hexa_PolyMAC & Hexa_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Elem_PolyMAC_base.
Definition at line 26 of file Hexa_PolyMAC.cpp.
const Hexa_PolyMAC & Hexa_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_PolyMAC_base.
Definition at line 26 of file Hexa_PolyMAC.cpp.
unsigned Hexa_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Hexa_PolyMAC.cpp.
Member Data Documentation
const Type_info Hexa_PolyMAC::info_obj [static]
Reimplemented from Elem_PolyMAC_base.
Definition at line 32 of file Hexa_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Hexa_PolyMAC.h
src/PolyMAC/Zones/Hexa_PolyMAC.cpp