TRUST: Interpolation_IBM_power_law_tbl Class Reference
Interpolation_IBM_power_law_tbl Class Reference
: class Interpolation_IBM_power_law_tbl
<Description of class Interpolation_IBM_power_law_tbl>
#include <Interpolation_IBM_power_law_tbl.h>
Public Member Functions
Interpolation_IBM_power_law_tbl ()
~Interpolation_IBM_power_law_tbl ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double get_A_pwl ()
double get_B_pwl ()
double get_y_c_p_pwl ()
Public Member Functions inherited from Interpolation_IBM_elem_fluid
Interpolation_IBM_elem_fluid ()
~Interpolation_IBM_elem_fluid ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretise (const Discretisation_base &, Zone_dis_base &la_zone_EF) override
Public Member Functions inherited from Interpolation_IBM_base
Interpolation_IBM_base ()
~Interpolation_IBM_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void discretise (const Discretisation_base &, Zone_dis_base &)
double get_impr ()
void set_param (Param &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interpolation_IBM_power_law_tbl & self_cast (Objet_U &)
static const Interpolation_IBM_power_law_tbl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interpolation_IBM_elem_fluid
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interpolation_IBM_elem_fluid & self_cast (Objet_U &)
static const Interpolation_IBM_elem_fluid & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interpolation_IBM_base
static const Type_info * info ()
static Interpolation_IBM_base & self_cast (Objet_U &)
static const Interpolation_IBM_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interpolation_IBM_elem_fluid
static const Type_info info_obj
Static Public Attributes inherited from Interpolation_IBM_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interpolation_IBM_elem_fluid
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual void computeFluidElems (Zone_dis_base &)
void set_param (Param &)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double A_pwl_ = 8.3
double B_pwl_ = 1./7.
double y_c_p_pwl_ = 11.81
Protected Attributes inherited from Interpolation_IBM_elem_fluid
Champ_Don fluid_points_lu_
Champ_Don fluid_points_
Champ_Don fluid_elems_lu_
Champ_Don fluid_elems_
Protected Attributes inherited from Interpolation_IBM_base
Champ_Don solid_points_lu_
Champ_Don solid_points_
Champ_Don corresp_elems_lu_
Champ_Don corresp_elems_
int impr_ =0
Default value.
Detailed Description
: class Interpolation_IBM_power_law_tbl
<Description of class Interpolation_IBM_power_law_tbl>
Definition at line 32 of file Interpolation_IBM_power_law_tbl.h.
Constructor & Destructor Documentation
Interpolation_IBM_power_law_tbl()
Interpolation_IBM_power_law_tbl::Interpolation_IBM_power_law_tbl ()
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
~Interpolation_IBM_power_law_tbl()
Interpolation_IBM_power_law_tbl::~Interpolation_IBM_power_law_tbl ()
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
Member Function Documentation
cree_instance()
Objet_U * Interpolation_IBM_power_law_tbl::cree_instance () static
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
duplique()
int Interpolation_IBM_power_law_tbl::duplique () const override virtual
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
get_A_pwl()
double Interpolation_IBM_power_law_tbl::get_A_pwl () inline
Definition at line 38 of file Interpolation_IBM_power_law_tbl.h.
  {
    return  A_pwl_;
  };
References A_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl().
get_B_pwl()
double Interpolation_IBM_power_law_tbl::get_B_pwl () inline
Definition at line 42 of file Interpolation_IBM_power_law_tbl.h.
  {
    return  B_pwl_;
  };
References B_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl().
get_info()
const Type_info * Interpolation_IBM_power_law_tbl::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
get_y_c_p_pwl()
double Interpolation_IBM_power_law_tbl::get_y_c_p_pwl () inline
Definition at line 46 of file Interpolation_IBM_power_law_tbl.h.
  {
    return y_c_p_pwl_;
  };
References y_c_p_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl().
info()
const Type_info * Interpolation_IBM_power_law_tbl::info () static
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
printOn()
Sortie & Interpolation_IBM_power_law_tbl::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 21 of file Interpolation_IBM_power_law_tbl.cpp.
{
  Interpolation_IBM_elem_fluid::printOn( os );
  return os;
}
References Interpolation_IBM_elem_fluid::printOn().
readOn()
Entree & Interpolation_IBM_power_law_tbl::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 27 of file Interpolation_IBM_power_law_tbl.cpp.
{
  Interpolation_IBM_elem_fluid::readOn( is );
  return is;
}
References Interpolation_IBM_elem_fluid::readOn().
self_cast() [1/2]
const Interpolation_IBM_power_law_tbl & Interpolation_IBM_power_law_tbl::self_cast (const Objet_U & r) static
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
self_cast() [2/2]
Interpolation_IBM_power_law_tbl & Interpolation_IBM_power_law_tbl::self_cast (Objet_U & r) static
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
taille_memoire()
unsigned Interpolation_IBM_power_law_tbl::taille_memoire () const override virtual
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 18 of file Interpolation_IBM_power_law_tbl.cpp.
Member Data Documentation
A_pwl_
double Interpolation_IBM_power_law_tbl::A_pwl_ = 8.3 protected
Definition at line 52 of file Interpolation_IBM_power_law_tbl.h.
Referenced by get_A_pwl().
B_pwl_
double Interpolation_IBM_power_law_tbl::B_pwl_ = 1./7. protected
Definition at line 53 of file Interpolation_IBM_power_law_tbl.h.
Referenced by get_B_pwl().
info_obj
const Type_info Interpolation_IBM_power_law_tbl::info_obj static
Definition at line 35 of file Interpolation_IBM_power_law_tbl.h.
y_c_p_pwl_
double Interpolation_IBM_power_law_tbl::y_c_p_pwl_ = 11.81 protected
Definition at line 54 of file Interpolation_IBM_power_law_tbl.h.
Referenced by get_y_c_p_pwl().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_power_law_tbl.h
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_power_law_tbl.cpp