TRUST: Eval_Source_C_VEF_Face Class Reference
Eval_Source_C_VEF_Face Class Reference
#include <Eval_Source_C_VEF_Face.h>
Public Member Functions
Eval_Source_C_VEF_Face ()
void completer () override
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
double calculer_terme_source_non_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
void calculer_terme_source_non_standard (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_VEF_Face
Evaluateur_Source_VEF_Face ()
Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual double calculer_terme_source_non_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
virtual void calculer_terme_source_non_standard (int, DoubleVect &) const =0
void changer_volumes_entrelaces_Cl (DoubleVect &) override
Public Member Functions inherited from Evaluateur_Source_VEF
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Protected Attributes
Ref_Champ_Don la_source_constituant
DoubleTab source_constituant
IntTab face_voisins
DoubleVect volumes
int nb_faces_elem
Protected Attributes inherited from Evaluateur_Source_VEF_Face
DoubleVect volumes_entrelaces
DoubleVect volumes_entrelaces_Cl
DoubleVect porosite_surf
IntTab face_voisins
Protected Attributes inherited from Evaluateur_Source_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
Definition at line 26 of file Eval_Source_C_VEF_Face.h.
Constructor & Destructor Documentation
Eval_Source_C_VEF_Face()
Eval_Source_C_VEF_Face::Eval_Source_C_VEF_Face () inline
Definition at line 54 of file Eval_Source_C_VEF_Face.h.
{}
Member Function Documentation
associer_champs()
void Eval_Source_C_VEF_Face::associer_champs (const Champ_Don & Q)
Definition at line 28 of file Eval_Source_C_VEF_Face.cpp.
{
  la_source_constituant = Q;
  source_constituant.ref(Q.valeurs());
}
References la_source_constituant, TRUSTTab< _TYPE_ >::ref(), source_constituant, and Champ_Don::valeurs().
Referenced by Terme_Source_Constituant_VEF_Face::associer_pb().
calculer_terme_source_non_standard() [1/2]
double Eval_Source_C_VEF_Face::calculer_terme_source_non_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 67 of file Eval_Source_C_VEF_Face.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    source = source_constituant(0,0)*volumes_entrelaces_Cl(num_face);
  else
    {
      if (face_voisins(num_face,1) != -1)
        source = (source_constituant(face_voisins(num_face,0),0)*volumes(face_voisins(num_face,0)) + source_constituant(face_voisins(num_face,1),0)*volumes(face_voisins(num_face,1)))/nb_faces_elem;
      else
        source = source_constituant(face_voisins(num_face,0),0)*volumes(face_voisins(num_face,0))/nb_faces_elem;
    }
  return (source*porosite_surf(num_face));
}
References face_voisins, la_source_constituant, nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_non_standard() [2/2]
void Eval_Source_C_VEF_Face::calculer_terme_source_non_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 99 of file Eval_Source_C_VEF_Face.h.
{
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    {
      source.inject_array(source_constituant);
      source *= volumes_entrelaces_Cl(num_face)*porosite_surf(num_face);
    }
  else
    {
      int size=source.size();
      for (int i=0; i<size; i++)
        if (face_voisins(num_face,1) != -1)
          source(i) = (source_constituant(face_voisins(num_face,0),i)*volumes(face_voisins(num_face,0))+source_constituant(face_voisins(num_face,1),i)*volumes(face_voisins(num_face,1)))/nb_faces_elem
                      *porosite_surf(num_face);
        else
          source(i) = source_constituant(face_voisins(num_face,0),i)*volumes(face_voisins(num_face,0))*porosite_surf(num_face)/nb_faces_elem;
    }
}
References face_voisins, TRUSTArray< _TYPE_ >::inject_array(), la_source_constituant, nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, TRUSTVect< _TYPE_ >::size(), source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_standard() [1/2]
double Eval_Source_C_VEF_Face::calculer_terme_source_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 56 of file Eval_Source_C_VEF_Face.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    source = source_constituant(0,0)*volumes_entrelaces(num_face);
  else
    source = (source_constituant(face_voisins(num_face,0),0)*volumes(face_voisins(num_face,0)) + source_constituant(face_voisins(num_face,1),0)*volumes(face_voisins(num_face,1)))/nb_faces_elem;
  return (source*porosite_surf(num_face));
}
References face_voisins, la_source_constituant, nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces.
calculer_terme_source_standard() [2/2]
void Eval_Source_C_VEF_Face::calculer_terme_source_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 83 of file Eval_Source_C_VEF_Face.h.
{
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    {
      source.inject_array(source_constituant);
      source *= volumes_entrelaces(num_face)*porosite_surf(num_face);
    }
  else
    {
      int size=source.size();
      for (int i=0; i<size; i++)
        source(i) = (source_constituant(face_voisins(num_face,0),i)*volumes(face_voisins(num_face,0))+source_constituant(face_voisins(num_face,1),i)*volumes(face_voisins(num_face,1)))/nb_faces_elem
                    *porosite_surf(num_face);
    }
}
References face_voisins, TRUSTArray< _TYPE_ >::inject_array(), la_source_constituant, nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, TRUSTVect< _TYPE_ >::size(), source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces.
completer()
void Eval_Source_C_VEF_Face::completer (void) override virtual
Implements Evaluateur_Source_VEF.
Definition at line 20 of file Eval_Source_C_VEF_Face.cpp.
{
  Evaluateur_Source_VEF_Face::completer();
  face_voisins.ref(la_zone->face_voisins());
  volumes.ref(la_zone->volumes());
  nb_faces_elem=la_zone->zone().nb_faces_elem();
}
References Evaluateur_Source_VEF_Face::completer(), Zone_VF::face_voisins(), face_voisins, Evaluateur_Source_VEF::la_zone, Zone::nb_faces_elem(), nb_faces_elem, TRUSTTab< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::ref(), Zone_VF::volumes(), volumes, and Zone_dis_base::zone().
mettre_a_jour()
void Eval_Source_C_VEF_Face::mettre_a_jour () override virtual
Implements Evaluateur_Source_VEF.
Definition at line 34 of file Eval_Source_C_VEF_Face.cpp.
{
}
Member Data Documentation
face_voisins
IntTab Eval_Source_C_VEF_Face::face_voisins protected
Definition at line 44 of file Eval_Source_C_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
la_source_constituant
Ref_Champ_Don Eval_Source_C_VEF_Face::la_source_constituant protected
Definition at line 42 of file Eval_Source_C_VEF_Face.h.
Referenced by associer_champs(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
nb_faces_elem
int Eval_Source_C_VEF_Face::nb_faces_elem protected
Definition at line 46 of file Eval_Source_C_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
source_constituant
DoubleTab Eval_Source_C_VEF_Face::source_constituant protected
Definition at line 43 of file Eval_Source_C_VEF_Face.h.
Referenced by associer_champs(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
volumes
DoubleVect Eval_Source_C_VEF_Face::volumes protected
Definition at line 45 of file Eval_Source_C_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
The documentation for this class was generated from the following files:
src/VEF/Sources/Evaluateurs/Eval_Source_C_VEF_Face.h
src/VEF/Sources/Evaluateurs/Eval_Source_C_VEF_Face.cpp