TRUST: NSCBC Class Reference
NSCBC Class Reference
classe
#include <NSCBC.h>
Public Member Functions
NSCBC ()
~NSCBC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_contribution_valeurs_propres (double temps)
int compatible_avec_eqn (const Equation_base &eqn) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Champ_front & flux_aretes ()
const Champ_front & flux_aretes () const
DoubleTab & val_propre_face ()
const DoubleTab & val_propre_face () const
DoubleTab & val_propre_arete ()
const DoubleTab & val_propre_arete () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static NSCBC & self_cast (Objet_U &)
static const NSCBC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Protected Attributes
Champ_front flux_aretes_
DoubleTab val_propre_face_
DoubleTab val_propre_arete_
Detailed Description
classe
Definition at line 37 of file NSCBC.h.
Constructor & Destructor Documentation
NSCBC::NSCBC ()
Definition at line 28 of file NSCBC.cpp.
NSCBC::~NSCBC ()
Definition at line 28 of file NSCBC.cpp.
Member Function Documentation
void NSCBC::calculer_contribution_valeurs_propres (double temps) [virtual]
Definition at line 81 of file NSCBC.cpp.
References Cerr, Process::exit(), and finl.
Referenced by mettre_a_jour().
{
  Cerr<<"la methode NSCBC::calculer_contribution_valeurs_propres "<<finl;
  Cerr<<"n'est pas codee"<<finl;
  Cerr<<"on ne devrait pas passer par la classe NSCBC mais une de ses"<<finl;
  Cerr<<"classes filles : NSCBC_SG_parfaitement_absorbante, ..."<<finl;
  exit();
}
int NSCBC::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Definition at line 111 of file NSCBC.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * NSCBC::cree_instance () [static]
Definition at line 28 of file NSCBC.cpp.
int NSCBC::duplique () const [virtual]
Implements Neumann.
Definition at line 28 of file NSCBC.cpp.
Champ_front & NSCBC::flux_aretes () [inline]
Definition at line 82 of file NSCBC.h.
References flux_aretes_.
{
  return flux_aretes_;
}
const Champ_front & NSCBC::flux_aretes () const [inline]
Definition at line 87 of file NSCBC.h.
References flux_aretes_.
{
  return flux_aretes_;
}
const Type_info * NSCBC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann.
Definition at line 28 of file NSCBC.cpp.
const Type_info * NSCBC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann.
Definition at line 28 of file NSCBC.cpp.
void NSCBC::mettre_a_jour (double temps) [virtual]
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Definition at line 75 of file NSCBC.cpp.
References calculer_contribution_valeurs_propres().
{
  Neumann::mettre_a_jour(temps);
  calculer_contribution_valeurs_propres(temps);
}
Sortie & NSCBC::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann.
Definition at line 45 of file NSCBC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & NSCBC::readOn (Entree & s) [protected, virtual]
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann.
Definition at line 69 of file NSCBC.cpp.
{
  return s;
}
NSCBC & NSCBC::self_cast (Objet_U & r) [static]
Reimplemented from Neumann.
Definition at line 28 of file NSCBC.cpp.
const NSCBC & NSCBC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Neumann.
Definition at line 28 of file NSCBC.cpp.
unsigned NSCBC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file NSCBC.cpp.
DoubleTab & NSCBC::val_propre_arete () [inline]
Definition at line 72 of file NSCBC.h.
References val_propre_arete_.
{
  return val_propre_arete_;
}
const DoubleTab & NSCBC::val_propre_arete () const [inline]
Definition at line 77 of file NSCBC.h.
References val_propre_arete_.
{
  return val_propre_arete_;
}
const DoubleTab & NSCBC::val_propre_face () const [inline]
Definition at line 67 of file NSCBC.h.
References val_propre_face_.
{
  return val_propre_face_;
}
DoubleTab & NSCBC::val_propre_face () [inline]
Definition at line 62 of file NSCBC.h.
References val_propre_face_.
{
  return val_propre_face_;
}
Member Data Documentation
Champ_front NSCBC::flux_aretes_ [protected]
Definition at line 56 of file NSCBC.h.
Referenced by flux_aretes().
const Type_info NSCBC::info_obj [static]
Reimplemented from Neumann.
Definition at line 40 of file NSCBC.h.
DoubleTab NSCBC::val_propre_arete_ [protected]
Definition at line 58 of file NSCBC.h.
Referenced by val_propre_arete().
DoubleTab NSCBC::val_propre_face_ [protected]
Definition at line 57 of file NSCBC.h.
Referenced by val_propre_face().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/NSCBC.h
src/ThHyd/Incompressible/Cond_Lim/NSCBC.cpp