TRUST: List_Ref_Espece Class Reference
List_Ref_Espece Class Reference
classe Loi_Etat_Multi_GP_QC
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
#include <Loi_Etat_Multi_GP_QC.h>
Public Member Functions
List_Ref_Espece ()
~List_Ref_Espece ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Ref_Espece (const Ref_Espece &t)
List_Ref_Espece (const List_Ref_Espece &t)
Ref_Espece & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Ref_Espece & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Ref_Espece & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Ref_Espece & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Ref_Espece & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Ref_Espece & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Ref_Espece & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Ref_Espece & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Ref_Espece & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Ref_Espece & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Ref_Espece & operator= (const Ref_Espece &t)
Ref_Espece * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Ref_Espece & operator= (const List_Ref_Espece &)
List_Ref_Espece & add (const List_Ref_Espece &)
Ref_Espece & add (const Ref_Espece &)
List_Ref_Espece & inserer (const List_Ref_Espece &)
Ref_Espece & inserer (const Ref_Espece &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Ref_Espece & operator+= (const List_Ref_Espece &)
List_Ref_Espece & operator+= (const Ref_Espece &)
Ref_Espece & add_if_not (const Ref_Espece &)
Ref_Espece & add_if_not (const char *const)
List_Ref_Espece & search (const Ref_Espece &) const
List_Ref_Espece & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Ref_Espece & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Ref_Espece & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Ref_Espece & dernier () const
Renvoie le dernier element de la liste.
List_Ref_Espece & dernier ()
Renvoie le dernier element de la liste.
List_Ref_Espece & operator-= (const Ref_Espece &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Ref_Espece &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Ref_Espece &) const
void suppr (const Ref_Espece &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Ref_Espece & self_cast (Objet_U &)
static const List_Ref_Espece & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Ref_Espece &) const
Detailed Description
classe Loi_Etat_Multi_GP_QC
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
Constructor & Destructor Documentation
List_Ref_Espece::List_Ref_Espece ()
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
List_Ref_Espece::~List_Ref_Espece ()
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
List_Ref_Espece::List_Ref_Espece (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece::List_Ref_Espece (const List_Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Member Function Documentation
List_Ref_Espece & List_Ref_Espece::add (const List_Ref_Espece & a_list) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
Referenced by Loi_Etat_Multi_GP_QC::associer_espece().
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::add (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::add_if_not (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::add_if_not (const char * const t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
int List_Ref_Espece::contient (const Ref_Espece & t) const [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
int List_Ref_Espece::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Objet_U * List_Ref_Espece::cree_instance () [static]
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
const List_Ref_Espece& List_Ref_Espece::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Ref_Espece & List_Ref_Espece::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
int List_Ref_Espece::duplique () const [virtual]
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
int List_Ref_Espece::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
int List_Ref_Espece::est_egal_a (const List_Ref_Espece &) const [inline, protected]
const Type_info * List_Ref_Espece::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
const Type_info * List_Ref_Espece::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
List_Ref_Espece & List_Ref_Espece::inserer (const List_Ref_Espece & a_list) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::inserer (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
const Ref_Espece & List_Ref_Espece::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
const Ref_Espece & List_Ref_Espece::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::operator+= (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::operator+= (const List_Ref_Espece & a_list) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::operator-= (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece * List_Ref_Espece::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::operator= (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::operator= (const List_Ref_Espece & a_list) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
const Ref_Espece & List_Ref_Espece::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
const Ref_Espece & List_Ref_Espece::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Sortie & List_Ref_Espece::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
int List_Ref_Espece::rang (const Ref_Espece & t) const [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Entree & List_Ref_Espece::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
List_Ref_Espece & List_Ref_Espece::search (const Ref_Espece & t) const [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
const List_Ref_Espece & List_Ref_Espece::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
List_Ref_Espece & List_Ref_Espece::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
const List_Ref_Espece & List_Ref_Espece::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
List_Ref_Espece & List_Ref_Espece::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
void List_Ref_Espece::suppr (const Ref_Espece & t) [inline]
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
void List_Ref_Espece::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
unsigned List_Ref_Espece::taille_memoire () const [virtual]
Reimplemented from liste.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
const Ref_Espece & List_Ref_Espece::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
: public Loi_Etat_Multi_GP_base
Ref_Espece & List_Ref_Espece::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
Referenced by Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), and Loi_Etat_Multi_GP_QC::calculer_tab_Cp().
: public Loi_Etat_Multi_GP_base
Member Data Documentation
const Type_info List_Ref_Espece::info_obj [static]
Reimplemented from liste.
Definition at line 40 of file Loi_Etat_Multi_GP_QC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Multi_GP_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Multi_GP_QC.cpp