TRUST: MaillerParallel Class Reference
MaillerParallel Class Reference
#include <MaillerParallel.h>
Public Member Functions
MaillerParallel ()
~MaillerParallel ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &is) override
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static MaillerParallel & self_cast (Objet_U &)
static const MaillerParallel & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 22 of file MaillerParallel.h.
Constructor & Destructor Documentation
MaillerParallel()
MaillerParallel::MaillerParallel ()
Definition at line 35 of file MaillerParallel.cpp.
~MaillerParallel()
MaillerParallel::~MaillerParallel ()
Definition at line 35 of file MaillerParallel.cpp.
Member Function Documentation
cree_instance()
Objet_U * MaillerParallel::cree_instance () static
Definition at line 35 of file MaillerParallel.cpp.
duplique()
int MaillerParallel::duplique () const override virtual
Implements Objet_U.
Definition at line 35 of file MaillerParallel.cpp.
get_info()
const Type_info * MaillerParallel::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 35 of file MaillerParallel.cpp.
info()
const Type_info * MaillerParallel::info () static
Definition at line 35 of file MaillerParallel.cpp.
interpreter()
Entree & MaillerParallel::interpreter (Entree & is) override virtual
< Nb total de noeuds dans la direction i
Reimplemented from Interprete.
Definition at line 526 of file MaillerParallel.cpp.
{
  if (dimension != 3)
    {
      Cerr << "Error: Mailler_Parallel is only coded for dimension 3" << finl;
      barrier();
      exit();
    }
  Nom      nom_domaine;
  ArrOfInt nb_noeuds;
  ArrOfInt decoupage;
  int   epaisseur_joint;
  ArrOfInt perio(3);
  Noms fonctions_coord(3);
  Noms nom_bords_min(3);
  Noms nom_bords_max(3);
  nom_bords_min[0] = "xmin";
  nom_bords_min[1] = "ymin";
  nom_bords_min[2] = "zmin";
  nom_bords_max[0] = "xmax";
  nom_bords_max[1] = "ymax";
  nom_bords_max[2] = "zmax";
  Noms fichier_coord(3);
  IntTab mapping;
  {
    Param param(que_suis_je());
    param.ajouter("domain", &nom_domaine, Param::REQUIRED);
    param.ajouter("nb_nodes", &nb_noeuds, Param::REQUIRED);
    param.ajouter("splitting", &decoupage, Param::REQUIRED);
    param.ajouter("ghost_thickness", &epaisseur_joint, Param::REQUIRED);
    param.ajouter_flag("perio_x", &perio[0]);
    param.ajouter_flag("perio_y", &perio[1]);
    param.ajouter_flag("perio_z", &perio[2]);
    param.ajouter("function_coord_x", &fonctions_coord[0]);
    param.ajouter("function_coord_y", &fonctions_coord[1]);
    param.ajouter("function_coord_z", &fonctions_coord[2]);
    param.ajouter("file_coord_x", &fichier_coord[0]);
    param.ajouter("file_coord_y", &fichier_coord[1]);
    param.ajouter("file_coord_z", &fichier_coord[2]);
    param.ajouter("boundary_xmin", &nom_bords_min[0]);
    param.ajouter("boundary_xmax", &nom_bords_max[0]);
    param.ajouter("boundary_ymin", &nom_bords_min[1]);
    param.ajouter("boundary_ymax", &nom_bords_max[1]);
    param.ajouter("boundary_zmin", &nom_bords_min[2]);
    param.ajouter("boundary_zmax", &nom_bords_max[2]);
    param.ajouter("mapping", &mapping);
    param.lire_avec_accolades(is);
  }
  ArrsOfDouble coord_ijk(3);
  for (int dir=0; dir<3; dir++)
    {
      const int n = nb_noeuds[dir];
      ArrOfDouble& coord = coord_ijk[dir];
      coord.resize_array(n);
      Cerr << "Building coordinates for direction " << dir << finl;
      if (fonctions_coord[dir] != "??")
        {
          Nom chaine = fonctions_coord[dir];
          Cerr << " Interpreting expression " << chaine << finl;
          Parser_U p;
          Noms noms_dir(3);
          noms_dir[0]="X";
          noms_dir[1]="Y";
          noms_dir[2]="Z";
          p.setNbVar(1);
          p.setString(chaine);
          p.addVar(noms_dir[dir]);
          p.parseString();
          for (int i = 0; i < n; i++)
            {
              p.setVar(0, (double) i / (double) (nb_noeuds[dir]-1));
              coord[i] = p.eval();
              if (i > 0 && coord[i] <= coord[i-1])
                {
                  Cerr << "Error in fonctions_coord parameter " << chaine << " : must be strictly increasing" << finl;
                  Process::exit();
                }
            }
          Cerr << " Build mesh covering [ " << coord[0] << " , " << coord[n-1] << " ]" << finl;
        }
      else if (fichier_coord[dir] != "??")
        {
          Cerr << " Reading file " << fichier_coord[dir] << finl;
          if (Process::je_suis_maitre())
            {
              EFichier f(fichier_coord[dir]);
              for (int i = 0; i < n; i++)
                f >> coord[i];
            }
          envoyer_broadcast(coord, 0);
          Cerr << " Found mesh covering [ " << coord[0] << " , " << coord[n-1] << " ]" << finl;
        }
      else
        {
          Cerr << " Uniform mesh covering [0,1]" << finl;
          for (int i = 0; i < n; i++)
            {
              coord[i] = (double) i / (double)(n-1);
            }
        }
    }
  Objet_U& obj = objet(nom_domaine);
  if(!sub_type(Domaine, obj))
    {
      Cerr << "obj : " << nom_domaine << " is not an object of type Domaine !" << finl;
      exit();
    }
  Domaine& domaine = ref_cast(Domaine, obj);
  const int numproc = Process::me();
  static Stat_Counter_Id stats = statistiques().new_counter(0 /* Level */, "Mailler_Parallel", 0 /* Group */);
  const int dim = Objet_U::dimension;
  if (nb_noeuds.size_array() != dim)
    {
      Cerr << "MaillerParallel::construire_domaine wrong dimension for nb_noeuds : nb_noeuds=" << nb_noeuds << finl;
      barrier();
      exit();
    }
  if (decoupage.size_array() != dim)
    {
      Cerr << "MaillerParallel::construire_domaine wrong dimension for nb_noeuds : nb_noeuds=" << nb_noeuds << finl;
      barrier();
      exit();
    }
  {
    int n = 1;
    for (int i = 0; i < dim; i++)
      n *= decoupage[i];
    if (n != Process::nproc())
      {
        Cerr << "MaillerParallel::construire_domaine decoupage does not match nproc" << finl;
        barrier();
        exit();
      }
  }
  statistiques().begin_count(stats);
// Position du bloc correspondant a numproc dans le decoupage i,j,k:
  ArrOfInt i_proc(dim);
  if (mapping.dimension(0) == 0)
    {
// Pas de mapping fourni, on prend decoupe par defaut
      int i;
      int reste = numproc;
      for (i = 0; i < dim; i++)
        {
// Nombre de parties dans la direction dim_2:
          const int n_parties = decoupage[i];
// Position du processeur courant dans cette direction:
          i_proc[i] = reste % n_parties;
          reste = reste / n_parties;
        }
    }
  else
    {
      if (mapping.dimension(0) != Process::nproc() || mapping.dimension(1) != 3)
        {
          Cerr << "Error: processor mapping should be of dimension " << Process::nproc() <<  " x 3" << finl;
          Process::exit();
        }
      i_proc[0] = mapping(numproc,0);
      i_proc[1] = mapping(numproc,1);
      i_proc[2] = mapping(numproc,2);
    }
// Indice du premier element du bloc associe au processeur dans la direction i:
// Attention, en cas de periodique, i_premier_element sera negatif.
  ArrOfInt i_premier_element(dim);
// Taille du bloc associe au processeur
  ArrOfInt nb_elements(dim);
  {
    int i;
    for (i = 0; i < dim; i++)
      {
        const int nb_elem_tot = nb_noeuds[i] - 1; //!< Nb total de noeuds dans la direction i
        i_premier_element[i] = nb_elem_tot * i_proc[i] / decoupage[i];
        const int i_dernier_element = nb_elem_tot * (i_proc[i] + 1) / decoupage[i] - 1;
        nb_elements[i] = i_dernier_element - i_premier_element[i] + 1;
        if (perio[i] && decoupage[i] > 1)
          {
            int decalage = nb_elem_tot / decoupage[i] / 2;
            i_premier_element[i] -= decalage;
          }
      }
  }
// On cree une zone pour le domaine
  Zone empty_zone;
  Zone& zone = domaine.add(empty_zone);
// Nom de la zone
  {
    Nom nom_zone("Proc");
    nom_zone += Nom(numproc);
    nom_zone += "sur";
    nom_zone += Nom(Process::nproc());
    zone.nommer(nom_zone);
  }
  zone.associer_domaine(domaine);
  {
    Elem_geom& elem = zone.type_elem();
    switch(dim)
      {
      case 3:
        elem.typer("Hexaedre");
        break;
      default:
        Cerr << "MaillerParallel::construire_domaine  erreur" << finl;
        exit();
      }
    elem.valeur().associer_zone(zone);
  }
  BlocData data;
  Noms liste_bords_perio;
  Bords& bords = zone.faces_bord();
  data.bord_xmin_ = nom_bords_min;
  data.bord_xmax_ = nom_bords_max;
  for (int dir = 0; dir < 3; dir++)
    {
      Nom nomdir;
      if (dir == 0) nomdir = "x";
      else if (dir == 1) nomdir = "y";
      else nomdir = "z";
      if (perio[dir])
        {
          data.bord_xmax_[dir] = data.bord_xmin_[dir];
          bords.add(Bord()).nommer(data.bord_xmin_[dir]);
        }
      else
        {
          bords.add(Bord()).nommer(data.bord_xmin_[dir]);
          bords.add(Bord()).nommer(data.bord_xmax_[dir]);
        }
    }
  data.xmax_tot_ = nb_noeuds;
  ArrOfInt nblocs(3);
  nblocs= 1;
  for (int i = 0; i < 3; i++)
    {
      if (i_premier_element[i] < 0)
        nblocs[i] = 2;
    }
  int num_bord;
  for (num_bord = 0; num_bord < bords.size(); num_bord++)
    {
      Bord& bord = bords[num_bord];
      bord.associer_zone(zone);
      bord.faces().typer(zone.type_elem().valeur().type_face());
// important pour dimensionner le linesize du tableau des faces pour les frontieres vides
      bord.faces().dimensionner(0);
    }
  ArrOfInt ibloc(3);
  for (ibloc[0] = 0; ibloc[0] < nblocs[0]; ibloc[0]++)
    {
      for (ibloc[1] = 0; ibloc[1]  < nblocs[1]; ibloc[1]++)
        {
          for (ibloc[2] = 0; ibloc[2]  < nblocs[2]; ibloc[2]++)
            {
              data.xmin_.resize_array(3);
              data.xmax_.resize_array(3);
              for (int dir = 0; dir < 3; dir++)
                {
                  data.xmin_[dir] = i_premier_element[dir];
                  data.xmax_[dir] = i_premier_element[dir] + nb_elements[dir] + 1;
                  if (nblocs[dir] > 1)
                    {
                      if (ibloc[dir] == 0)
                        data.xmin_[dir] = 0;
                      else
{
                          data.xmin_[dir] += data.xmax_tot_[dir] - 1;
                          data.xmax_[dir] = data.xmax_tot_[dir];
                        }
                    }
                }
              Process::Journal() << "add bloc xmin=" << data.xmin_ << "xmax=" << data.xmax_ << "xtot=" << data.xmax_tot_;
              data.add_bloc(domaine, coord_ijk);
            }
        }
    }
  {
    for (int d = 0; d < 3; d++)
      {
        if (perio[d])
          {
            ArrOfDouble dir(3);
            dir[d] = coord_ijk[d][nb_noeuds[d]-1] - coord_ijk[d][0];
            IntTab& faces = domaine.zone(0).bord(nom_bords_min[d]).faces().les_sommets();
            double epsilon = precision_geom;
            Reordonner_faces_periodiques::reordonner_faces_periodiques(domaine, faces, dir, epsilon);
          }
      }
  }
  auto_build_joints(domaine.zone(0), epaisseur_joint);
  statistiques().end_count(stats);
  double maxtime = mp_max(statistiques().last_time(stats));
  if (Process::je_suis_maitre())
    Cerr << "Ending of the construction of the zones, time:" << maxtime << finl;
  if (nproc() > 1)
    {
      statistiques().begin_count(stats);
      Scatter::construire_correspondance_sommets_par_coordonnees(domaine);
      Scatter::calculer_renum_items_communs(domaine.zone(0).faces_joint(), Joint::SOMMET);
      statistiques().end_count(stats);
      maxtime = mp_max(statistiques().last_time(stats));
      Cerr << "Scatter::construire_correspondance_sommets_par_coordonnees fin, time:"
           << maxtime << finl;
      statistiques().begin_count(stats);
      Scatter::construire_structures_paralleles(domaine, liste_bords_perio);
      statistiques().end_count(stats);
      maxtime = mp_max(statistiques().last_time(stats));
      Cerr << "Scatter::construire_structures_paralleles, time:" << maxtime << finl;
    }
  else
    {
      Scatter::init_sequential_domain(domaine);
    }
  domaine.zone(0).nommer(domaine.le_nom());
  Cerr << "MaillerParallel::construire_domaine : end" << finl;
  return is;
}
References List_Bord::add(), Domaine::add(), BlocData::add_bloc(), Parser_U::addVar(), Param::ajouter(), Param::ajouter_flag(), Zone::associer_domaine(), Elem_geom_base::associer_zone(), Frontiere::associer_zone(), auto_build_joints(), Process::barrier(), Statistiques::begin_count(), Zone::bord(), BlocData::bord_xmax_, BlocData::bord_xmin_, Scatter::calculer_renum_items_communs(), Cerr, Scatter::construire_correspondance_sommets_par_coordonnees(), Scatter::construire_structures_paralleles(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Faces::dimensionner(), Statistiques::end_count(), envoyer_broadcast(), Parser_U::eval(), Process::exit(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_joint(), finl, Scatter::init_sequential_domain(), Process::je_suis_maitre(), Process::Journal(), Domaine::le_nom(), Faces::les_sommets(), Param::lire_avec_accolades(), Process::me(), Process::mp_max(), Statistiques::new_counter(), Objet_U::nommer(), Zone::nommer(), Process::nproc(), Interprete::objet(), Parser_U::parseString(), Objet_U::precision_geom, Objet_U::que_suis_je(), ref_cast, Reordonner_faces_periodiques::reordonner_faces_periodiques(), Param::REQUIRED, TRUSTArray< _TYPE_ >::resize_array(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), Joint::SOMMET, statistiques(), sub_type, Zone::type_elem(), Elem_geom_base::type_face(), Deriv_::typer(), Faces::typer(), Deriv_Elem_geom_base::valeur(), BlocData::xmax_, BlocData::xmax_tot_, BlocData::xmin_, and Domaine::zone().
printOn()
Sortie & MaillerParallel::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 42 of file MaillerParallel.cpp.
{
  return os;
}
readOn()
Entree & MaillerParallel::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 37 of file MaillerParallel.cpp.
{
  return is;
}
self_cast() [1/2]
const MaillerParallel & MaillerParallel::self_cast (const Objet_U & r) static
Definition at line 35 of file MaillerParallel.cpp.
self_cast() [2/2]
MaillerParallel & MaillerParallel::self_cast (Objet_U & r) static
Definition at line 35 of file MaillerParallel.cpp.
taille_memoire()
unsigned MaillerParallel::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 35 of file MaillerParallel.cpp.
Member Data Documentation
info_obj
const Type_info MaillerParallel::info_obj static
Definition at line 24 of file MaillerParallel.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/MaillerParallel.h
src/Kernel/Geometrie/MaillerParallel.cpp