TRUST: Eval_Puiss_Th_QC_VEF_Face Class Reference
Eval_Puiss_Th_QC_VEF_Face Class Reference
#include <Eval_Puiss_Th_QC_VEF_Face.h>
Public Member Functions
Eval_Puiss_Th_QC_VEF_Face ()
void completer () override
void associer_puissance (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
double calculer_terme_source_non_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
void calculer_terme_source_non_standard (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_VEF_Face
Evaluateur_Source_VEF_Face ()
Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual double calculer_terme_source_non_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
virtual void calculer_terme_source_non_standard (int, DoubleVect &) const =0
void changer_volumes_entrelaces_Cl (DoubleVect &) override
Public Member Functions inherited from Evaluateur_Source_VEF
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
IntTab face_voisins
DoubleVect volumes
int nb_faces_elem
Protected Attributes inherited from Evaluateur_Source_VEF_Face
DoubleVect volumes_entrelaces
DoubleVect volumes_entrelaces_Cl
DoubleVect porosite_surf
IntTab face_voisins
Protected Attributes inherited from Evaluateur_Source_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
Definition at line 33 of file Eval_Puiss_Th_QC_VEF_Face.h.
Constructor & Destructor Documentation
Eval_Puiss_Th_QC_VEF_Face()
Eval_Puiss_Th_QC_VEF_Face::Eval_Puiss_Th_QC_VEF_Face () inline
Definition at line 62 of file Eval_Puiss_Th_QC_VEF_Face.h.
{}
Member Function Documentation
associer_puissance()
void Eval_Puiss_Th_QC_VEF_Face::associer_puissance (const Champ_Don & Q)
Definition at line 27 of file Eval_Puiss_Th_QC_VEF_Face.cpp.
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
References la_puissance, puissance, TRUSTTab< _TYPE_ >::ref(), and Champ_Don::valeurs().
Referenced by Terme_Puissance_Thermique_QC_VEF_Face::associer_pb().
calculer_terme_source_non_standard() [1/2]
double Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 91 of file Eval_Puiss_Th_QC_VEF_Face.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    source = puissance(0,0)*volumes_entrelaces_Cl(num_face) ;
  else
    {
      double P0,P1;
      int elem0 = face_voisins(num_face,0);
      int elem1 = face_voisins(num_face,1);
      double V0 = volumes(elem0);
      double V1 = (elem1 != -1?volumes(elem1):0);
      if (puissance.nb_dim()==1)
        {
          P0 = puissance(elem0);
          P1 = (elem1 != -1?puissance(elem1):0);
        }
      else
        {
          P0 = puissance(elem0,0);
          P1 = (elem1 != -1?puissance(elem1,0):0);
        }
      source = (P0*V0 + P1*V1) / nb_faces_elem;
    }
  return (source*porosite_surf(num_face));
}
References face_voisins, la_puissance, TRUSTTab< _TYPE_ >::nb_dim(), nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, puissance, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_non_standard() [2/2]
void Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard (int , DoubleVect &) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 124 of file Eval_Puiss_Th_QC_VEF_Face.h.
{
  ;
}
calculer_terme_source_standard() [1/2]
double Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 64 of file Eval_Puiss_Th_QC_VEF_Face.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    source = puissance(0,0)*volumes_entrelaces(num_face) ;
  else
    {
      double P0,P1;
      int elem0 = face_voisins(num_face,0);
      int elem1 = face_voisins(num_face,1);
      double V0 = volumes(elem0);
      double V1 = volumes(elem1);
      if (puissance.nb_dim()==1)
        {
          P0 = puissance(elem0);
          P1 = puissance(elem1);
        }
      else
        {
          P0 = puissance(elem0,0);
          P1 = puissance(elem1,0);
        }
      source = (P0*V0 + P1*V1) / nb_faces_elem;
    }
  return (source*porosite_surf(num_face));
}
References face_voisins, la_puissance, TRUSTTab< _TYPE_ >::nb_dim(), nb_faces_elem, Evaluateur_Source_VEF_Face::porosite_surf, puissance, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), volumes, and Evaluateur_Source_VEF_Face::volumes_entrelaces.
calculer_terme_source_standard() [2/2]
void Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard (int , DoubleVect &) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 118 of file Eval_Puiss_Th_QC_VEF_Face.h.
{
  ;
}
completer()
void Eval_Puiss_Th_QC_VEF_Face::completer (void) override virtual
Implements Evaluateur_Source_VEF.
Definition at line 19 of file Eval_Puiss_Th_QC_VEF_Face.cpp.
{
  Evaluateur_Source_VEF_Face::completer();
  face_voisins.ref(la_zone->face_voisins());
  volumes.ref(la_zone->volumes());
  nb_faces_elem=la_zone->zone().nb_faces_elem();
}
References Evaluateur_Source_VEF_Face::completer(), Zone_VF::face_voisins(), face_voisins, Evaluateur_Source_VEF::la_zone, Zone::nb_faces_elem(), nb_faces_elem, TRUSTTab< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::ref(), Zone_VF::volumes(), volumes, and Zone_dis_base::zone().
mettre_a_jour()
void Eval_Puiss_Th_QC_VEF_Face::mettre_a_jour () override virtual
Implements Evaluateur_Source_VEF.
Definition at line 33 of file Eval_Puiss_Th_QC_VEF_Face.cpp.
{
}
Member Data Documentation
face_voisins
IntTab Eval_Puiss_Th_QC_VEF_Face::face_voisins protected
Definition at line 51 of file Eval_Puiss_Th_QC_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
la_puissance
Ref_Champ_Don Eval_Puiss_Th_QC_VEF_Face::la_puissance protected
Definition at line 49 of file Eval_Puiss_Th_QC_VEF_Face.h.
Referenced by associer_puissance(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
nb_faces_elem
int Eval_Puiss_Th_QC_VEF_Face::nb_faces_elem protected
Definition at line 53 of file Eval_Puiss_Th_QC_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
puissance
DoubleTab Eval_Puiss_Th_QC_VEF_Face::puissance protected
Definition at line 50 of file Eval_Puiss_Th_QC_VEF_Face.h.
Referenced by associer_puissance(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
volumes
DoubleVect Eval_Puiss_Th_QC_VEF_Face::volumes protected
Definition at line 52 of file Eval_Puiss_Th_QC_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and completer().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Eval_Puiss_Th_QC_VEF_Face.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Eval_Puiss_Th_QC_VEF_Face.cpp