TRUST: grad_U_Champ_Face_PolyMAC Class Reference
grad_U_Champ_Face_PolyMAC Class Reference
classe grad_U_Champ_Face_PolyMAC
#include <grad_U_Champ_Face_PolyMAC.h>
Public Member Functions
grad_U_Champ_Face_PolyMAC ()
~grad_U_Champ_Face_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face_PolyMAC &)
void me_calculer (double)
void associer_zone_Cl_dis_base (const Zone_Cl_dis_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static grad_U_Champ_Face_PolyMAC & self_cast (Objet_U &)
static const
grad_U_Champ_Face_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
Ref_Champ_Face_PolyMAC vitesse_
Detailed Description
classe grad_U_Champ_Face_PolyMAC
Definition at line 36 of file grad_U_Champ_Face_PolyMAC.h.
Constructor & Destructor Documentation
grad_U_Champ_Face_PolyMAC::grad_U_Champ_Face_PolyMAC ()
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
grad_U_Champ_Face_PolyMAC::~grad_U_Champ_Face_PolyMAC ()
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
Member Function Documentation
void grad_U_Champ_Face_PolyMAC::associer_champ (const Champ_Face_PolyMAC & la_vitesse)
Definition at line 46 of file grad_U_Champ_Face_PolyMAC.cpp.
References vitesse_.
Referenced by PolyMAC_discretisation::grad_u().
{
  vitesse_= la_vitesse;
}
void grad_U_Champ_Face_PolyMAC::associer_zone_Cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [inline]
Definition at line 63 of file grad_U_Champ_Face_PolyMAC.h.
References la_zone_Cl_PolyMAC.
Referenced by PolyMAC_discretisation::grad_u().
{
  la_zone_Cl_PolyMAC  = (const Zone_Cl_PolyMAC&) la_zone_Cl_dis_base;
}
Objet_U * grad_U_Champ_Face_PolyMAC::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
int grad_U_Champ_Face_PolyMAC::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
const Type_info * grad_U_Champ_Face_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
const Type_info * grad_U_Champ_Face_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
void grad_U_Champ_Face_PolyMAC::me_calculer (double tps)
Definition at line 51 of file grad_U_Champ_Face_PolyMAC.cpp.
References Ref_Champ_Face_PolyMAC::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and vitesse_.
Referenced by mettre_a_jour().
{
  vitesse_->interp_gve(vitesse_.valeur().valeurs(), valeurs());
}
void grad_U_Champ_Face_PolyMAC::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 56 of file grad_U_Champ_Face_PolyMAC.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
Sortie & grad_U_Champ_Face_PolyMAC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 33 of file grad_U_Champ_Face_PolyMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & grad_U_Champ_Face_PolyMAC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 41 of file grad_U_Champ_Face_PolyMAC.cpp.
{
  return s ;
}
const grad_U_Champ_Face_PolyMAC & grad_U_Champ_Face_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
grad_U_Champ_Face_PolyMAC & grad_U_Champ_Face_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
unsigned grad_U_Champ_Face_PolyMAC::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 27 of file grad_U_Champ_Face_PolyMAC.cpp.
Member Data Documentation
const Type_info grad_U_Champ_Face_PolyMAC::info_obj [static]
Reimplemented from Champ_Fonc_P0_PolyMAC.
Definition at line 40 of file grad_U_Champ_Face_PolyMAC.h.
Ref_Zone_Cl_PolyMAC grad_U_Champ_Face_PolyMAC::la_zone_Cl_PolyMAC [protected]
Definition at line 52 of file grad_U_Champ_Face_PolyMAC.h.
Referenced by associer_zone_Cl_dis_base().
Ref_Champ_Face_PolyMAC grad_U_Champ_Face_PolyMAC::vitesse_ [protected]
Definition at line 53 of file grad_U_Champ_Face_PolyMAC.h.
Referenced by associer_champ(), and me_calculer().
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/grad_U_Champ_Face_PolyMAC.h
src/PolyMAC/Champs/grad_U_Champ_Face_PolyMAC.cpp