TRUST: ArrOfFloat Class Reference
ArrOfFloat Class Reference
#include <ArrOfFloat.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ArrOfFloat ()
Construit un tableau vide.
ArrOfFloat (int n)
Constructeur d'un tableau vide de taille n.
Le tableau n'est pas initialise.
ArrOfFloat (const ArrOfFloat &array)
Constructeur par copie.
const ArrOfFloat & operator= (const ArrOfFloat &array)
Operateur copie (deep copy)
~ArrOfFloat () override
Destructeur.
float & operator[] (int i) const
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
float & operator[] (int i)
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
void ordonne_array ()
ArrOfFloat & inject_array (const ArrOfFloat &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
int size_array () const
Renvoie le nombre de valeurs dans le tableau.
float * addr ()
const float * addr () const
void resize_array (int size)
Changement de taille du tableau, en cas d'augmentation,
le contenu des nouveaux elements est indefini.
const ArrOfFloat & operator*= (const float)
muliplie toutes les cases par dy
const ArrOfFloat & operator/= (const float)
divise toutes les cases par dy
const ArrOfFloat & operator= (const float)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ArrOfFloat & self_cast (Objet_U &)
static const ArrOfFloat & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Entree & readOn (Entree &) override
Lecture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
void mem_resize (int size)
Augmentation de taille du tableau (appele uniquement si l'espace
memoire est insuffisant et qu'il faut reallouer de la memoire).
Les anciennes donnees sont recopiees dans le nouveau tableau,
le contenu des elements nouveaux est indefini.
void invalidate (int first_element, int nb_elements)
remplit nb_elements consecutifs du tableau avec une valeur invalide
en commencant par l'indice first_element.
Il faut first_element >= 0 et first_element+nb_elements <= memory_size_.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
float * data_
int size_
Nombre d'elements du tableau.
int memory_size_
Taille allouee (on a memory_size_ >= size_)
Static Protected Attributes
static const int grow_factor_num_ = 2
static const int grow_factor_denom_ = 1
Detailed Description
Definition at line 21 of file ArrOfFloat.h.
Constructor & Destructor Documentation
ArrOfFloat() [1/3]
ArrOfFloat::ArrOfFloat ()
Construit un tableau vide.
Definition at line 26 of file ArrOfFloat.cpp.
                       :
  data_(0), size_(0), memory_size_(0)
{
}
ArrOfFloat() [2/3]
ArrOfFloat::ArrOfFloat (int n)
Constructeur d'un tableau vide de taille n.
Le tableau n'est pas initialise.
Definition at line 33 of file ArrOfFloat.cpp.
                            :
  data_(0), size_(0), memory_size_(0)
{
  resize_array(n);
}
References resize_array().
ArrOfFloat() [3/3]
ArrOfFloat::ArrOfFloat (const ArrOfFloat & array)
Constructeur par copie.
Definition at line 40 of file ArrOfFloat.cpp.
                                              : Objet_U(array),
  data_(0), size_(0), memory_size_(0)
{
  operator=(array);
}
References operator=().
~ArrOfFloat()
ArrOfFloat::~ArrOfFloat () override
Destructeur.
< Paranoia... mais ca peut servir s'il reste une ref a ce tableau
Definition at line 73 of file ArrOfFloat.cpp.
{
  if (data_)
    delete [] data_;
  data_ = 0; //!< Paranoia... mais ca peut servir s'il reste une ref a ce tableau
  size_ = 0;
  memory_size_ = 0;
}
References data_, memory_size_, and size_.
Member Function Documentation
addr() [1/2]
float * ArrOfFloat::addr ()
Definition at line 106 of file ArrOfFloat.cpp.
{
  return data_;
}
References data_.
Referenced by inject_array(), operator*=(), operator/=(), and ordonne_array().
addr() [2/2]
const float * ArrOfFloat::addr () const
Definition at line 111 of file ArrOfFloat.cpp.
{
  return data_;
}
References data_.
cree_instance()
Objet_U * ArrOfFloat::cree_instance () static
Definition at line 20 of file ArrOfFloat.cpp.
duplique()
int ArrOfFloat::duplique () const override virtual
Implements Objet_U.
Reimplemented in FloatTab.
Definition at line 20 of file ArrOfFloat.cpp.
get_info()
const Type_info * ArrOfFloat::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in FloatTab.
Definition at line 20 of file ArrOfFloat.cpp.
info()
const Type_info * ArrOfFloat::info () static
Definition at line 20 of file ArrOfFloat.cpp.
inject_array()
ArrOfFloat & ArrOfFloat::inject_array (const ArrOfFloat & source, int nb_elements = -1, int first_element_dest = 0, int first_element_source = 0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
Returns
ArrOfDouble&
Signification: *this
Contraintes:
Definition at line 216 of file ArrOfFloat.cpp.
{
  assert(&source != this);
  assert(nb_elements >= -1);
  assert(first_element_dest >= 0);
  assert(first_element_source >= 0);
  if (nb_elements < 0)
    nb_elements = source.size_array();
  assert(first_element_source + nb_elements <= source.size_array());
  assert(first_element_dest + nb_elements <= size_array());
  if (nb_elements > 0)
    {
      float * addr_dest = addr() + first_element_dest;
      const float * addr_source = source.addr() + first_element_source;
// PL: On utilise le memcpy car c'est VRAIMENT plus rapide (10% +vite sur RNR_G20)
      memcpy(addr_dest , addr_source, nb_elements * sizeof(float));
      /*
        int i;
        for (i = 0; i < nb_elements; i++) {
        addr_dest[i] = addr_source[i];
        } */
    }
  return *this;
}
References addr(), and size_array().
invalidate()
void ArrOfFloat::invalidate (int first_element, int nb_elements) protected
remplit nb_elements consecutifs du tableau avec une valeur invalide
en commencant par l'indice first_element.
Il faut first_element >= 0 et first_element+nb_elements <= memory_size_.
Definition at line 147 of file ArrOfFloat.cpp.
{
  /* static const float VALEUR_INVALIDE =
     (__extension__ ((union {
     int __l __attribute__((__mode__(__DI__)));
// Ceci represente un NAN. N'importe quelle operation avec ca fait encore un NAN.
// Si c'est pas portable, on peut remplacer par DMAXFLOAT sur les autres machines.
     float __d; }) { __l: 0x7ff7ffffffffffffULL }).__d);; */
// static const float VALEUR_INVALIDE = 0x7ff7ffffffffffffULL ;
  static const float VALEUR_INVALIDE = nan("1");
  const int n = first_element + nb_elements;
  assert(first_element >= 0 && n <= memory_size_);
// On utilise "memcpy" et non "=" car "=" peut provoquer une exception
// si la copie passe par le fpu.
  for (int i = first_element; i < n; i++)
    memcpy(data_+i, & VALEUR_INVALIDE, sizeof(float));
}
References data_, and memory_size_.
Referenced by resize_array().
mem_resize()
void ArrOfFloat::mem_resize (int size) protected
Augmentation de taille du tableau (appele uniquement si l'espace
memoire est insuffisant et qu'il faut reallouer de la memoire).
Les anciennes donnees sont recopiees dans le nouveau tableau,
le contenu des elements nouveaux est indefini.
Definition at line 87 of file ArrOfFloat.cpp.
{
  assert(size > size_);
  int newsize = size * grow_factor_num_ / grow_factor_denom_;
  float * newdata = new float[newsize];
// Copier les anciennes donnees dans le nouveau tableau
  if (size_ > 0)
    memcpy(newdata, data_, size_ * sizeof(float));
// Effacer l'ancien tableau
  if (data_)
    delete [] data_;
  data_ = newdata;
  memory_size_ = newsize;
  size_ = size;
}
References data_, grow_factor_denom_, grow_factor_num_, memory_size_, and size_.
Referenced by resize_array().
operator*=()
const ArrOfFloat & ArrOfFloat::operator*= (const float dy)
muliplie toutes les cases par dy
Returns
ArrOfFloat &
Signification: *this
Definition at line 251 of file ArrOfFloat.cpp.
{
  float * data = addr();
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] *= dy;
  return *this;
}
References addr(), and size_array().
operator/=()
const ArrOfFloat & ArrOfFloat::operator/= (const float dy)
divise toutes les cases par dy
Returns
ArrOfFloat &
Signification: *this
Definition at line 265 of file ArrOfFloat.cpp.
{
// En theorie: les deux lignes suivantes sont plus efficaces, mais
// cela produit des differences sur certains cas tests
// (Hyd_C_VEF_Smago et Lambda_var_VEF_turb). Ca veut dire qu'il y
// a un probleme autre part mais pour l'instant on laisse l'ancien
// codage.
// const float i_dy = 1. / dy;
// operator*=(i_dy);
  float * data = addr();
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] /= dy;
  return *this;
}
References addr(), and size_array().
operator=() [1/2]
const ArrOfFloat & ArrOfFloat::operator= (const ArrOfFloat & array)
Operateur copie (deep copy)
< Self assignment, why not...
Definition at line 48 of file ArrOfFloat.cpp.
{
  if (&array == this) //!< Self assignment, why not...
    return *this;
  if (array.size_ > memory_size_)
    {
      if (data_)
        delete [] data_;
      data_ = new float[array.size_];
      memory_size_ = array.size_;
    }
  if (array.size_ > 0)
    memcpy(data_, array.data_, array.size_ * sizeof(float));
  size_ = array.size_;
  return *this;
}
References data_, memory_size_, and size_.
Referenced by ArrOfFloat(), and FloatTab::operator=().
operator=() [2/2]
const ArrOfFloat & ArrOfFloat::operator= (const float x)
Definition at line 65 of file ArrOfFloat.cpp.
{
  for (int i = 0; i < size_; i++)
    data_[i] = x;
  return *this;
}
References data_, and size_.
operator[]() [1/2]
float & ArrOfFloat::operator[] (int i) inline
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
Definition at line 67 of file ArrOfFloat.h.
{
  assert(i >= 0 && i < size_);
  return data_[i];
}
References data_, and size_.
operator[]() [2/2]
float & ArrOfFloat::operator[] (int i) const inline
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
Definition at line 60 of file ArrOfFloat.h.
{
  assert(i >= 0 && i < size_);
  return data_[i];
}
References data_, and size_.
ordonne_array()
void ArrOfFloat::ordonne_array ()
Definition at line 181 of file ArrOfFloat.cpp.
{
  const int size = size_array();
  if (size > 1)
    {
      float * data = addr();
      qsort(data, size, sizeof(float),
            fonction_compare_arroffloat_ordonner);
    }
}
References addr(), fonction_compare_arroffloat_ordonner(), and size_array().
printOn()
Sortie & ArrOfFloat::printOn (Sortie & x) const override protected virtual
Ecriture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Reimplemented from Objet_U.
Reimplemented in FloatTab.
Definition at line 136 of file ArrOfFloat.cpp.
{
  os << size_ << finl;
  if (size_ > 0)
    os.put(data_, size_, size_);
  return os;
}
References data_, finl, Sortie::put(), and size_.
readOn()
Entree & ArrOfFloat::readOn (Entree & is) override protected virtual
Lecture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Reimplemented from Objet_U.
Reimplemented in FloatTab.
Definition at line 120 of file ArrOfFloat.cpp.
{
  int mysize;
  is >> mysize;
// Resize en deux fois pour ne pas faire de memcpy inutile
  size_ = 0;
  resize_array(mysize);
  if (mysize > 0)
    is.get(data_, mysize);
  return is;
}
References data_, Entree::get(), resize_array(), and size_.
resize_array()
void ArrOfFloat::resize_array (int size) inline
Changement de taille du tableau, en cas d'augmentation,
le contenu des nouveaux elements est indefini.
Definition at line 81 of file ArrOfFloat.h.
{
  assert(size >= 0);
  if (size > memory_size_)
    mem_resize(size);
#ifndef NDEBUG
// En mode debug, on remplit les nouvelles entrees avec des valeurs invalides
  if (size > size_)
    invalidate(size_, size - size_);
#endif
  size_ = size;
}
References invalidate(), mem_resize(), memory_size_, and size_.
Referenced by ArrOfFloat(), readOn(), FloatTab::readOn(), and FloatTab::resize().
self_cast() [1/2]
const ArrOfFloat & ArrOfFloat::self_cast (const Objet_U & r) static
Definition at line 20 of file ArrOfFloat.cpp.
self_cast() [2/2]
ArrOfFloat & ArrOfFloat::self_cast (Objet_U & r) static
Definition at line 20 of file ArrOfFloat.cpp.
size_array()
int ArrOfFloat::size_array () const inline
Renvoie le nombre de valeurs dans le tableau.
Definition at line 74 of file ArrOfFloat.h.
{
  return size_;
}
References size_.
Referenced by inject_array(), operator*=(), operator/=(), and ordonne_array().
taille_memoire()
unsigned ArrOfFloat::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in FloatTab.
Definition at line 20 of file ArrOfFloat.cpp.
Member Data Documentation
data_
float* ArrOfFloat::data_ protected
Definition at line 50 of file ArrOfFloat.h.
Referenced by addr(), latatoother::interpreter(), invalidate(), mem_resize(), FloatTab::operator()(), operator=(), operator[](), printOn(), FloatTab::printOn(), readOn(), FloatTab::readOn(), and ~ArrOfFloat().
grow_factor_denom_
const int ArrOfFloat::grow_factor_denom_ = 1 static protected
Definition at line 54 of file ArrOfFloat.h.
Referenced by mem_resize().
grow_factor_num_
const int ArrOfFloat::grow_factor_num_ = 2 static protected
Definition at line 53 of file ArrOfFloat.h.
Referenced by mem_resize().
info_obj
const Type_info ArrOfFloat::info_obj static
Definition at line 23 of file ArrOfFloat.h.
memory_size_
int ArrOfFloat::memory_size_ protected
Taille allouee (on a memory_size_ >= size_)
Definition at line 52 of file ArrOfFloat.h.
Referenced by invalidate(), mem_resize(), operator=(), resize_array(), and ~ArrOfFloat().
size_
int ArrOfFloat::size_ protected
Nombre d'elements du tableau.
Definition at line 51 of file ArrOfFloat.h.
Referenced by mem_resize(), operator=(), operator[](), printOn(), FloatTab::printOn(), readOn(), FloatTab::readOn(), resize_array(), size_array(), and ~ArrOfFloat().
The documentation for this class was generated from the following files:
src/Kernel/Math/ArrOfFloat.h
src/Kernel/Math/ArrOfFloat.cpp