TRUST: Eval_Dirac_VEF_Face Class Reference
Eval_Dirac_VEF_Face Class Reference
#include <Eval_Dirac_VEF_Face.h>
Public Member Functions
Eval_Dirac_VEF_Face ()
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
double calculer_terme_source_non_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
void calculer_terme_source_non_standard (int, DoubleVect &) const override
void associer_nb_elem_dirac (int)
Public Member Functions inherited from Evaluateur_Source_VEF_Face
Evaluateur_Source_VEF_Face ()
Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual double calculer_terme_source_non_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
virtual void calculer_terme_source_non_standard (int, DoubleVect &) const =0
void changer_volumes_entrelaces_Cl (DoubleVect &) override
Public Member Functions inherited from Evaluateur_Source_VEF
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Public Attributes
DoubleVect le_point
Protected Attributes
Ref_Champ_Don la_puissance
double puissance
Ref_Zone ma_zone
double nb_dirac
Protected Attributes inherited from Evaluateur_Source_VEF_Face
DoubleVect volumes_entrelaces
DoubleVect volumes_entrelaces_Cl
DoubleVect porosite_surf
IntTab face_voisins
Protected Attributes inherited from Evaluateur_Source_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
Definition at line 31 of file Eval_Dirac_VEF_Face.h.
Constructor & Destructor Documentation
Eval_Dirac_VEF_Face()
Eval_Dirac_VEF_Face::Eval_Dirac_VEF_Face () inline
Definition at line 60 of file Eval_Dirac_VEF_Face.h.
:puissance(-123.),nb_dirac(-123.) {}
Member Function Documentation
associer_champs()
void Eval_Dirac_VEF_Face::associer_champs (const Champ_Don & Q)
Definition at line 21 of file Eval_Dirac_VEF_Face.cpp.
{
  la_puissance = Q;
  puissance = Q(0);
}
References la_puissance, and puissance.
Referenced by Source_Dirac_VEF_Face::associer_pb().
associer_nb_elem_dirac()
void Eval_Dirac_VEF_Face::associer_nb_elem_dirac (int n)
Definition at line 33 of file Eval_Dirac_VEF_Face.cpp.
{
  nb_dirac = 1./n;
// Cout << "Nb Dirac = " << n << finl;
}
References nb_dirac.
Referenced by Source_Dirac_VEF_Face::associer_zones().
calculer_terme_source_non_standard() [1/2]
double Eval_Dirac_VEF_Face::calculer_terme_source_non_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 97 of file Eval_Dirac_VEF_Face.h.
{
  int elem;
  if (face_voisins(num_face,1)==-1)
    {
      elem = face_voisins(num_face,0);
    }
  else
    {
      elem = face_voisins(num_face,1);
    }
  int test =  ma_zone.valeur().type_elem().contient(le_point,elem) ;
  if (test == 1)
    {
      assert(nb_dirac!=-123.);
      assert(puissance!=-123.);
      double source =  nb_dirac*puissance;
      return source;
    }
  else
    {
      return 0;
    }
}
References Elem_geom::contient(), Evaluateur_Source_VEF_Face::face_voisins, le_point, ma_zone, nb_dirac, puissance, test(), Zone::type_elem(), and Ref_Zone::valeur().
calculer_terme_source_non_standard() [2/2]
void Eval_Dirac_VEF_Face::calculer_terme_source_non_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 123 of file Eval_Dirac_VEF_Face.h.
{
  Cerr << "Eval_Dirac_VEF_Face::calculer_terme_source_non_standard(int num_face, DoubleVect& source) is not available." << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
calculer_terme_source_standard() [1/2]
double Eval_Dirac_VEF_Face::calculer_terme_source_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 63 of file Eval_Dirac_VEF_Face.h.
{
// on recuperre l'element associe a cette face
  int elem;
  if (face_voisins(num_face,1)==-1)
    {
      elem = face_voisins(num_face,0);
    }
  else
    {
      elem = face_voisins(num_face,1);
    }
  int test =  ma_zone.valeur().type_elem().contient(le_point,elem) ;
  if (test == 1)
    {
      assert(nb_dirac!=-123.);
      assert(puissance!=-123.);
      double source =  nb_dirac*puissance;
      return source;
    }
  else
    {
      return 0;
    }
}
References Elem_geom::contient(), Evaluateur_Source_VEF_Face::face_voisins, le_point, ma_zone, nb_dirac, puissance, test(), Zone::type_elem(), and Ref_Zone::valeur().
calculer_terme_source_standard() [2/2]
void Eval_Dirac_VEF_Face::calculer_terme_source_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 92 of file Eval_Dirac_VEF_Face.h.
{
  ;
}
mettre_a_jour()
void Eval_Dirac_VEF_Face::mettre_a_jour () override virtual
Implements Evaluateur_Source_VEF.
Definition at line 27 of file Eval_Dirac_VEF_Face.cpp.
{
  puissance= la_puissance.valeur()(0);
  ma_zone = la_zone.valeur().zone();
}
References la_puissance, Evaluateur_Source_VEF::la_zone, ma_zone, puissance, Ref_Champ_Don::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Dirac_VEF_Face::la_puissance protected
Definition at line 48 of file Eval_Dirac_VEF_Face.h.
Referenced by associer_champs(), and mettre_a_jour().
le_point
DoubleVect Eval_Dirac_VEF_Face::le_point
Definition at line 45 of file Eval_Dirac_VEF_Face.h.
Referenced by Source_Dirac_VEF_Face::associer_pb(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
ma_zone
Ref_Zone Eval_Dirac_VEF_Face::ma_zone protected
Definition at line 50 of file Eval_Dirac_VEF_Face.h.
Referenced by calculer_terme_source_non_standard(), calculer_terme_source_standard(), and mettre_a_jour().
nb_dirac
double Eval_Dirac_VEF_Face::nb_dirac protected
Definition at line 51 of file Eval_Dirac_VEF_Face.h.
Referenced by associer_nb_elem_dirac(), calculer_terme_source_non_standard(), and calculer_terme_source_standard().
puissance
double Eval_Dirac_VEF_Face::puissance protected
Definition at line 49 of file Eval_Dirac_VEF_Face.h.
Referenced by associer_champs(), calculer_terme_source_non_standard(), calculer_terme_source_standard(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VEF/Sources/Evaluateurs/Eval_Dirac_VEF_Face.h
src/VEF/Sources/Evaluateurs/Eval_Dirac_VEF_Face.cpp