TRUST: MD_Vector Class Reference
MD_Vector Class Reference
:
Cette classe est un DERIV mais l'objet pointe est partage entre plusieurs
instances de cette classe. L'objet pointe ne peut etre accede qu'en "const"
et n'est accessible que par des instances de MD_Vector. Donc
il n'existe pas de moyen d'y acceder en "non const" autrement qu'avec un cast.
La methode attach() et le constructeur par copie rattachent le pointeur a une
instance existante deja attachee a un pointeur.
La methode attach_detach() s'approprie l'objet pointe par le DERIV et detache
l'objet du DERIV. C'est la seule facon de "construire" les objets MD_Vector
(evite une copie, et permet d'assurer que le MD_Vect ne peut plus etre modifie
une fois que qu'il a ete attache a un MD_Vector)
ATTENTION: la securite de la methode repose
sur le fait que l'instance pointee par MD_Vector n'est accessible nulle part
ailleurs que par des objets MD_Vector. NE PAS AJOUTER de methode
attach(const MD_Vector_base &), cela casse la securite de la classe !!! (B.Mathieu)
inline d'un maximum de methodes pour ne pas penaliser les tableaux non distribues,
tout en evitant d'inclure MD_Vector_base.h
#include <MD_Vector.h>
Public Member Functions
MD_Vector ()
MD_Vector (const MD_Vector &)
constructeur par copie, associe le pointeur au meme objet que
la source et incremente le compteur de references, partie inline pour traiter
le cas ou la source est nulle
~MD_Vector ()
detache le pointeur s'il n'est pas nul.
inline pour ne pas penaliser les tableaux non distribues.
MD_Vector & operator= (const MD_Vector &)
idem que attach(src)
void attach (const MD_Vector &)
Detache le pointeur et attache au meme objet que src,
puis incremente le compteur de ref (si le pointeur est non nul).
void copy (const MD_Vector_base &)
construction d'un objet MD_Vector par copie d'un
objet existant. C'est la methode recommandee pour creer un objet MD_Vector
(autrement que par copie d'un autre MD_Vector)
int non_nul () const
const MD_Vector_base & valeur () const
void detach ()
Detache le pointeur de l'objet pointe et decremente le compteur de ref.
Si le compteur est nul, detruit l'objet.
int operator== (const MD_Vector &) const
renvoie 1 si les structures sont identiques, 0 sinon
int operator!= (const MD_Vector &) const
reponse inverse de ==
Private Member Functions
void detach_ ()
methode non inline pour detacher l'objet pointe.
void attach_ (const MD_Vector &)
methode non inline pour attacher l'objet en parametre.
Private Attributes
const MD_Vector_base * ptr_
Detailed Description
:
Cette classe est un DERIV mais l'objet pointe est partage entre plusieurs
instances de cette classe. L'objet pointe ne peut etre accede qu'en "const"
et n'est accessible que par des instances de MD_Vector. Donc
il n'existe pas de moyen d'y acceder en "non const" autrement qu'avec un cast.
La methode attach() et le constructeur par copie rattachent le pointeur a une
instance existante deja attachee a un pointeur.
La methode attach_detach() s'approprie l'objet pointe par le DERIV et detache
l'objet du DERIV. C'est la seule facon de "construire" les objets MD_Vector
(evite une copie, et permet d'assurer que le MD_Vect ne peut plus etre modifie
une fois que qu'il a ete attache a un MD_Vector)
ATTENTION: la securite de la methode repose
sur le fait que l'instance pointee par MD_Vector n'est accessible nulle part
ailleurs que par des objets MD_Vector. NE PAS AJOUTER de methode
attach(const MD_Vector_base &), cela casse la securite de la classe !!! (B.Mathieu)
inline d'un maximum de methodes pour ne pas penaliser les tableaux non distribues,
tout en evitant d'inclure MD_Vector_base.h
Definition at line 52 of file MD_Vector.h.
Constructor & Destructor Documentation
MD_Vector::MD_Vector () [inline]
Definition at line 55 of file MD_Vector.h.
: ptr_(0) {};
MD_Vector::MD_Vector (const MD_Vector & src) [inline]
constructeur par copie, associe le pointeur au meme objet que
la source et incremente le compteur de references, partie inline pour traiter
le cas ou la source est nulle
Definition at line 84 of file MD_Vector.h.
References attach_(), and ptr_.
                                                :
  ptr_(0)
{
  if (src.ptr_)
    attach_(src);
}
MD_Vector::~MD_Vector () [inline]
detache le pointeur s'il n'est pas nul.
inline pour ne pas penaliser les tableaux non distribues.
Definition at line 120 of file MD_Vector.h.
References detach_(), and ptr_.
{
  if (ptr_)
    detach_();
}
Member Function Documentation
void MD_Vector::attach (const MD_Vector & src) [inline]
Detache le pointeur et attache au meme objet que src,
puis incremente le compteur de ref (si le pointeur est non nul).
< sinon a.attach(a) risque de detruire le pointeur !
Definition at line 101 of file MD_Vector.h.
References attach_(), detach_(), and ptr_.
Referenced by operator=().
{
  if (this == &src)
    return; //!< sinon a.attach(a) risque de detruire le pointeur !
  if (ptr_)
    detach_();
  if (src.ptr_)
    attach_(src);
}
void MD_Vector::attach_ (const MD_Vector & src) [private]
methode non inline pour attacher l'objet en parametre.
Definition at line 58 of file MD_Vector.cpp.
References non_nul(), and ptr_.
Referenced by attach(), and MD_Vector().
{
  assert(ptr_ == 0);
  assert(src.non_nul());
  ptr_ = src.ptr_;
  (ptr_->ref_count_)++;
}
void MD_Vector::copy (const MD_Vector_base & src)
construction d'un objet MD_Vector par copie d'un
objet existant. C'est la methode recommandee pour creer un objet MD_Vector
(autrement que par copie d'un autre MD_Vector)
Definition at line 31 of file MD_Vector.cpp.
References detach(), MD_Vector_base::duplique(), Memoire::Instance(), Memoire::objet_u_ptr(), ptr_, and MD_Vector_base::ref_count_.
Referenced by Scatter::construire_md_vector(), Zone::creer_aretes(), MD_Vector_tools::creer_md_vect_renum(), Zone_PolyMAC::discretiser(), Zone_CoviMAC::discretiser(), Zone_VEF_PreP1b::discretiser_suite(), MD_Vector_tools::extend(), Scatter::init_sequential_domain(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), MD_Vector_composite::readOn(), and MD_Vector_tools::restore_vector_with_md().
{
  detach();
  int num_obj = src.duplique();
  ptr_ = (MD_Vector_base *) Memoire::Instance().objet_u_ptr(num_obj);
  assert(ptr_->ref_count_ == 0);
  ptr_->ref_count_ = 1;
}
void MD_Vector::detach () [inline]
Detache le pointeur de l'objet pointe et decremente le compteur de ref.
Si le compteur est nul, detruit l'objet.
Definition at line 93 of file MD_Vector.h.
References detach_(), and ptr_.
Referenced by copy(), IntVect::detach_vect(), DoubleVect::detach_vect(), IntVect::ref_array(), DoubleVect::ref_array(), IntVect::ref_data(), DoubleVect::ref_data(), IntVect::reset(), DoubleVect::reset(), and Traduction_Indice_Global_Local::reset().
{
  if (ptr_)
    detach_();
}
void MD_Vector::detach_ () [private]
methode non inline pour detacher l'objet pointe.
Definition at line 42 of file MD_Vector.cpp.
References ptr_, and MD_Vector_base::ref_count_.
Referenced by attach(), detach(), and ~MD_Vector().
{
  assert(ptr_);
  int& count = ptr_->ref_count_;
  assert(count > 0);
  count--;
  if (count == 0)
    {
// Detruit l'objet pointe:
      delete ptr_;
    }
  ptr_ = 0;
}
int MD_Vector::non_nul () const [inline]
Definition at line 63 of file MD_Vector.h.
References ptr_.
Referenced by MD_Vector_composite::add_part(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), SETS::assembler(), attach_(), Zone::calculer_volumes(), Zone_VEF::calculer_volumes_entrelaces(), carre(), IntVect::copy(), DoubleVect::copy(), IntVect::copy_(), DoubleVect::copy_(), MD_Vector_tools::creer_md_vect_renum(), MD_Vector_tools::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), MD_Vector_tools::echange_espace_virtuel(), Debog_Pb::ecrire_gen(), EcritureLectureSpecial::ecriture_special(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Zone::init_faces_virt_bord(), init_parts(), invalidate_data(), EcritureLectureSpecial::lecture_special(), IntTab::lit(), DoubleTab::lit(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), Zone::md_vector_elements(), Zone_VEF_PreP1b::md_vector_p1b(), mp_moyenne_vect(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), SSOR::prepare_(), IntVect::printOn(), DoubleVect::printOn(), racine_carree(), IntVect::readOn(), DoubleVect::readOn(), Op_Diff_VEF_base::remplir_nu(), IntVect::resize_vect_(), DoubleVect::resize_vect_(), IntVect::set_line_size_(), DoubleVect::set_line_size_(), IntVect::set_md_vector(), IntTab::set_md_vector(), DoubleVect::set_md_vector(), DoubleTab::set_md_vector(), IntVect::size_reelle(), DoubleVect::size_reelle(), tab_divide_any_shape(), tab_divide_any_shape_(), tab_multiply_any_shape(), tab_multiply_any_shape_(), tri_lexicographique_tableau(), tri_lexicographique_tableau_indirect(), Op_Diff_PolyMAC_base::update_nu(), Debog_Pb::verifier_gen(), and Debog_Pb::write_geometry_data().
  {
    return (ptr_ != 0);
  }
int MD_Vector::operator!= (const MD_Vector & md) const
reponse inverse de ==
Definition at line 79 of file MD_Vector.cpp.
References operator==().
{
// B.M.: je code exactement ce qui est dit au dessus (des fois que == change un jour...)
  return !operator==(md);
}
MD_Vector & MD_Vector::operator= (const MD_Vector & src) [inline]
idem que attach(src)
Definition at line 112 of file MD_Vector.h.
References attach().
{
  attach(src);
  return *this;
}
int MD_Vector::operator== (const MD_Vector & md) const
renvoie 1 si les structures sont identiques, 0 sinon
Definition at line 67 of file MD_Vector.cpp.
References ptr_.
Referenced by operator!=().
{
// Pour l'instant, test tres restrictif: les deux structures sont
// identiques si et seulement si les pointeurs sont identiques,
// (autrement dit la deuxieme a ete creee par copie de la premiere)
// Si on veut debrancher le systeme de reference multiple et dupliquer
// les structures a la copie, il faut faire le test complet d'egalite
// sur toute la structure !
  return ptr_ == md.ptr_;
}
const MD_Vector_base& MD_Vector::valeur () const [inline]
Definition at line 67 of file MD_Vector.h.
References ptr_.
Referenced by MD_Vector_composite::add_part(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Traitement_particulier_NS_THI_new::calcul_nb_som_dir(), carre(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Scatter::construire_espace_virtuel_traduction(), Zone_VEF_PreP1b::construire_ok_arete(), MD_Vector_tools::creer_md_vect_renum(), creer_tableau_distribue(), MD_Vector_tools::dump_vector_with_md(), echange_espace_virtuel_(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), EcritureLectureSpecial::ecriture_special(), ecriture_special_part2(), MD_Vector_tools::extend(), MD_Vector_tools::get_sequential_items_flags(), Zone_VF::info_elem_som(), init_parts(), Traduction_Indice_Global_Local::initialiser(), invalidate_data(), Zone_VEF_PreP1b::lecture_ok_arete(), EcritureLectureSpecial::lecture_special(), lecture_special_part2(), local_carre_norme_tab(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_tab(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), mp_moyenne_vect(), Zone_VF::nb_faces_bord_tot(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), SSOR::prepare_(), Solv_GCP::prepare_data(), MD_Vector_composite::printOn(), racine_carree(), Solv_GCP::resoudre_(), IntVect::set_md_vector(), IntTab::set_md_vector(), DoubleVect::set_md_vector(), DoubleTab::set_md_vector(), tab_divide_any_shape_(), tab_multiply_any_shape_(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_matrice(), and Debog_Pb::verifier_partie().
  {
    assert(ptr_);
    return *ptr_;
  }
Member Data Documentation
const MD_Vector_base* MD_Vector::ptr_ [private]
Definition at line 78 of file MD_Vector.h.
Referenced by attach(), attach_(), copy(), detach(), detach_(), MD_Vector(), non_nul(), operator==(), valeur(), and ~MD_Vector().
The documentation for this class was generated from the following files:
src/Kernel/Math/MD_Vector.h
src/Kernel/Math/MD_Vector.cpp