TRUST: Op_Curl_VEFP1B Class Reference
Op_Curl_VEFP1B Class Reference
#include <Op_Curl_VEFP1B.h>
Public Member Functions
Op_Curl_VEFP1B ()
~Op_Curl_VEFP1B ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab vecteur_normal (const int face, const int elem) const
int elements_pour_sommet ()
int elements_pour_sommet (const int sommet, const int indice) const
int elem_som_size (const int sommet) const
const Zone_VEF_PreP1b & zone_Vef () const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Curl_VEFP1B & self_cast (Objet_U &)
static const Op_Curl_VEFP1B & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
IntLists elements_pour_sommet_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
Definition at line 28 of file Op_Curl_VEFP1B.h.
Constructor & Destructor Documentation
Op_Curl_VEFP1B()
Op_Curl_VEFP1B::Op_Curl_VEFP1B ()
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
~Op_Curl_VEFP1B()
Op_Curl_VEFP1B::~Op_Curl_VEFP1B ()
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Curl_VEFP1B::ajouter (const DoubleTab & vitesse, DoubleTab & curl) const override virtual
Reimplemented from Operateur_base.
Definition at line 82 of file Op_Curl_VEFP1B.cpp.
{
  Cerr << "Je suis dans operateur curl" << finl;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone& zone = zone_VEF.zone();
// int prems=zone_VEF.premiere_face_int();
  if ( dimension != 2 )
    {
      Cerr << "Pour l'instant seule la 2D est etudiee. " << finl;
      Process::exit();
    }
  int face0=0,face1=0,face2=0;
  int numero_triangle=0;
  int face_globale=0,face_opp=0;
  DoubleTab vecteur_normal0(dimension);
  DoubleTab vecteur_normal1(dimension);
  DoubleTab vecteur_normal2(dimension);
// On traite les faces internes i.e. sans conditions aux limites
// ATTENTION: la base de la vorticite c'est: l'ensemble des
// fonctions indicatrices des elements + l'ensemble des fonctions
// chapeaux du P1 moins la derniere de ces fonctions de forme
// Partie P0 de la vorticite
  for (int numero_elem = 0; numero_elem < zone.nb_elem(); numero_elem++)
    {
// REM: on peut generaliser cette partie a la 3D en
// faisant une boucle avec zone.nb_faces_element()
// Il nous faut d'abord les numeros des 3 faces
// qui appartiennent a cet element K
      face0 = zone_VEF.elem_faces(numero_elem,0);
      face1 = zone_VEF.elem_faces(numero_elem,1);
      face2 = zone_VEF.elem_faces(numero_elem,2);
// Ensuite, il nous faut les vecteurs tangents de
// ces trois faces.
      vecteur_normal0 = vecteur_normal(face0,numero_elem);
      vecteur_normal1 = vecteur_normal(face1,numero_elem);
      vecteur_normal2 = vecteur_normal(face2,numero_elem);
      int modulo;
      for (int composante=0; composante<dimension; composante++)
        {
// La partie P0 a ete teste avec les fonctions (1,0);
// (0,1);(x,0) et (0,x).
// Tous les resultats sont corrects
          modulo = (composante+1)%2;
          curl(numero_elem) +=  pow(-1.,modulo) * (
                                  vitesse(face0,composante)*vecteur_normal0(modulo)+
                                  vitesse(face1,composante)*vecteur_normal1(modulo)+
                                  vitesse(face2,composante)*vecteur_normal2(modulo) );
        }
      Cerr << "Element curl(" << numero_elem << ") " << curl(numero_elem) << finl;
    }
// Partie P1 de la vorticite
  for (int numero_som = 0; numero_som < zone.nb_som()-1; numero_som++)
    {
      for (int num_loc_elem = 0; num_loc_elem < elem_som_size(numero_som);
           num_loc_elem++)
        {
// for num_loc_elem
// On recupere le numero global du triangle
          numero_triangle = elements_pour_sommet(numero_som,num_loc_elem);
// On recupere le numero global de la face opposee a "numero_som"
// dans le triangle "numero_triangle"
          face_opp=zone_VEF.numero_sommet_local(numero_som,numero_triangle);
          face_opp=zone_VEF.elem_faces(numero_triangle,face_opp);
// On recupere le vecteur normal de cette face opposee.
          vecteur_normal1=vecteur_normal(face_opp,numero_triangle);
          for (int num_loc_face = 0 ; num_loc_face < zone.nb_faces_elem();
               num_loc_face++)
            {
// for num_loc_face
// On recupere le numero global de la face "num_loc_face"
              face_globale=zone_VEF.elem_faces(numero_triangle,num_loc_face);
// //Si "face_globale" est une arete interne alors on effectue le bon
// //traitement
// if (face_globale >= zone_VEF.premiere_face_int())
              {
// On calcule les vecteurs normaux associes a ces faces.
                vecteur_normal0=vecteur_normal(face_globale,numero_triangle);
// Enfin on calcule la contribution au curl de chacune de
// ces faces pour chacun des 2 triangles.
                int modulo;
                for (int composante=0; composante<dimension; composante++)
                  {
// Partie P1 teste avec les fonctions (1,0);(0,1)
// (x,0) et (0,x).
// Tous les tests sont corrects
                    modulo = (composante+1)%2;
// Partie (lambda_s,curl u)
                    curl(zone.nb_elem()+numero_som) += -pow(-1.,modulo) *
                                                       1./(dimension+1) *
                                                       vitesse(face_globale,composante) *
                                                       vecteur_normal0(modulo);
// Partie (rot lambda_s, u)
                    curl(zone.nb_elem()+numero_som) += pow(-1.,modulo)*
                                                       1./(dimension*(dimension+1))*
                                                       vitesse(face_globale,composante)*
                                                       vecteur_normal1(modulo);
                  }
              } //!< fin du if
            }//!< fin du for num_loc_face
          /* Pour le moment, on ne travaille que sur des vitesse H10 */
          /* C'est le travail de these */
          /* Par consequent, inutile de traiter les faces du bord */
        }//!< fin du for num_loc_elem
      Cerr << "Sommet curl(" << numero_som << ") " << curl(zone.nb_elem()+numero_som) << finl;
    }//!< fin du for sur les sommets
  Cerr << "je sors de OpCurl" << finl;
  return curl;
}
References Cerr, composante(), Objet_U::dimension, Zone_VF::elem_faces(), elem_som_size(), elements_pour_sommet(), Process::exit(), finl, la_zone_vef, Zone::nb_elem(), Zone::nb_faces_elem(), Zone::nb_som(), Zone_VF::numero_sommet_local(), Ref_Zone_VEF::valeur(), vecteur_normal(), and Zone_dis_base::zone().
Referenced by calculer().
associer()
void Op_Curl_VEFP1B::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc & inco) override virtual
Implements Operateur_base.
Definition at line 64 of file Op_Curl_VEFP1B.cpp.
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF, zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  elements_pour_sommet();
}
References elements_pour_sommet(), la_zcl_vef, la_zone_vef, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by Op_Diff_RotRot::associer().
calculer()
DoubleTab & Op_Curl_VEFP1B::calculer (const DoubleTab & vitesse, DoubleTab & curl) const override virtual
Reimplemented from Operateur_base.
Definition at line 76 of file Op_Curl_VEFP1B.cpp.
{
  curl = 0;
  return ajouter(vitesse,curl);
}
References ajouter().
Referenced by Op_Diff_RotRot::ajouter().
cree_instance()
Objet_U * Op_Curl_VEFP1B::cree_instance () static
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
duplique()
int Op_Curl_VEFP1B::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
elem_som_size()
int Op_Curl_VEFP1B::elem_som_size (const int sommet) const
Definition at line 270 of file Op_Curl_VEFP1B.cpp.
{
  return elements_pour_sommet_[sommet].size();
}
References elements_pour_sommet_, and TRUSTLists< _TYPE_ >::size().
Referenced by ajouter(), and Op_Diff_RotRot::calculer_vorticite().
elements_pour_sommet() [1/2]
int Op_Curl_VEFP1B::elements_pour_sommet ()
Definition at line 245 of file Op_Curl_VEFP1B.cpp.
{
  const Zone& zone = la_zone_vef.valeur().zone();
  int numero_global_som;
  elements_pour_sommet_.dimensionner(zone.nb_som());
  for (int numero_elem = 0; numero_elem < zone.nb_elem(); numero_elem++)
    for (int numero_som_loc=0; numero_som_loc < zone.nb_som_elem(); numero_som_loc++)
      {
        numero_global_som = zone.sommet_elem(numero_elem,numero_som_loc);
        elements_pour_sommet_[numero_global_som].add_if_not(numero_elem);
      }
  return 1;
}
References TRUSTLists< _TYPE_ >::dimensionner(), elements_pour_sommet_, la_zone_vef, Zone::nb_elem(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter(), associer(), and Op_Diff_RotRot::calculer_vorticite().
elements_pour_sommet() [2/2]
int Op_Curl_VEFP1B::elements_pour_sommet (const int sommet, const int indice) const
Definition at line 263 of file Op_Curl_VEFP1B.cpp.
{
  return elements_pour_sommet_[sommet][indice];
}
References elements_pour_sommet_.
get_info()
const Type_info * Op_Curl_VEFP1B::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_base.
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
info()
const Type_info * Op_Curl_VEFP1B::info () static
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
printOn()
Sortie & Op_Curl_VEFP1B::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 29 of file Op_Curl_VEFP1B.cpp.
{
  return s;
}
readOn()
Entree & Op_Curl_VEFP1B::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 33 of file Op_Curl_VEFP1B.cpp.
{
  return is;
}
self_cast() [1/2]
const Op_Curl_VEFP1B & Op_Curl_VEFP1B::self_cast (const Objet_U & r) static
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
self_cast() [2/2]
Op_Curl_VEFP1B & Op_Curl_VEFP1B::self_cast (Objet_U & r) static
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
taille_memoire()
unsigned Op_Curl_VEFP1B::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Op_Curl_VEFP1B.cpp.
vecteur_normal()
DoubleTab Op_Curl_VEFP1B::vecteur_normal (const int face, const int elem) const
Definition at line 227 of file Op_Curl_VEFP1B.cpp.
{
  assert(dimension == 2);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  DoubleTab le_vecteur_normal(dimension);
  for (int composante = 0; composante<dimension; composante++)
    le_vecteur_normal(composante) = zone_VEF.face_normales(face,composante)
                                    * zone_VEF.oriente_normale(face,elem);
  return le_vecteur_normal;
}
References composante(), Objet_U::dimension, Zone_VEF::face_normales(), la_zone_vef, Zone_VEF::oriente_normale(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
zone_Vef()
const Zone_VEF_PreP1b & Op_Curl_VEFP1B::zone_Vef () const
Definition at line 39 of file Op_Curl_VEFP1B.cpp.
{
  return ref_cast(Zone_VEF_PreP1b, la_zone_vef.valeur());
}
References la_zone_vef, ref_cast, and Ref_Zone_VEF::valeur().
Member Data Documentation
elements_pour_sommet_
IntLists Op_Curl_VEFP1B::elements_pour_sommet_ protected
Definition at line 57 of file Op_Curl_VEFP1B.h.
Referenced by elem_som_size(), and elements_pour_sommet().
info_obj
const Type_info Op_Curl_VEFP1B::info_obj static
Definition at line 31 of file Op_Curl_VEFP1B.h.
la_zcl_vef
Ref_Zone_Cl_VEF Op_Curl_VEFP1B::la_zcl_vef protected
Definition at line 56 of file Op_Curl_VEFP1B.h.
Referenced by associer().
la_zone_vef
Ref_Zone_VEF Op_Curl_VEFP1B::la_zone_vef protected
Definition at line 55 of file Op_Curl_VEFP1B.h.
Referenced by ajouter(), associer(), elements_pour_sommet(), vecteur_normal(), and zone_Vef().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Curl_VEFP1B.h
src/P1NCP1B/Operateurs/Op_Curl_VEFP1B.cpp