TRUST: Ref_Zone_VF Class Reference
Ref_Zone_VF Class Reference
#include <Ref_Zone_VF.h>
Public Member Functions
~Ref_Zone_VF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_VF ()
Ref_Zone_VF (const Zone_VF &)
Ref_Zone_VF (const Ref_Zone_VF &)
const Zone_VF & valeur () const
Zone_VF & valeur ()
const Zone_VF * operator-> () const
Zone_VF * operator-> ()
const Ref_Zone_VF & operator= (const Zone_VF &)
const Ref_Zone_VF & operator= (const Ref_Zone_VF &)
operator const Zone_VF & () const
operator Zone_VF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_VF & self_cast (Objet_U &)
static const Ref_Zone_VF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_VF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_VF.h.
Constructor & Destructor Documentation
Ref_Zone_VF::~Ref_Zone_VF ()
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF::Ref_Zone_VF ()
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF::Ref_Zone_VF (const Zone_VF & t)
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF::Ref_Zone_VF (const Ref_Zone_VF & t)
Definition at line 25 of file Ref_Zone_VF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_VF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_VF.cpp.
int Ref_Zone_VF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
const Type_info * Ref_Zone_VF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
const Type_info & Ref_Zone_VF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_VF.cpp.
const Type_info * Ref_Zone_VF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF::operator const Zone_VF & () const
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF::operator Zone_VF & ()
Definition at line 25 of file Ref_Zone_VF.cpp.
const Zone_VF * Ref_Zone_VF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_VF.h.
Zone_VF * Ref_Zone_VF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_VF.h.
const Ref_Zone_VF & Ref_Zone_VF::operator= (const Ref_Zone_VF & t)
Definition at line 25 of file Ref_Zone_VF.cpp.
const Ref_Zone_VF & Ref_Zone_VF::operator= (const Zone_VF & t)
Definition at line 25 of file Ref_Zone_VF.cpp.
Sortie & Ref_Zone_VF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
Entree & Ref_Zone_VF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
const Ref_Zone_VF & Ref_Zone_VF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
Ref_Zone_VF & Ref_Zone_VF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VF.cpp.
void Ref_Zone_VF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_VF.cpp.
unsigned Ref_Zone_VF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_VF.cpp.
const Zone_VF & Ref_Zone_VF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_VF.h.
Referenced by Champ_P0_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_CoviMAC::affecter_(), Champ_Face_CoviMAC::affecter_(), Champ_P0_PolyMAC::init_cl(), Champ_P0_CoviMAC::init_fcl(), Champ_Face_CoviMAC::valeur_aux_faces(), Champ_Q1_CoviMAC::zone_CoviMAC(), Champ_P1_CoviMAC::zone_CoviMAC(), Champ_P0_CoviMAC::zone_CoviMAC(), Champ_Fonc_Q1_CoviMAC::zone_CoviMAC(), Champ_Fonc_P1_CoviMAC::zone_CoviMAC(), Champ_Fonc_Q1_VEF::zone_dis_base(), Champ_Fonc_Q1_VDF::zone_dis_base(), Champ_Q1_PolyMAC::zone_dis_base(), Champ_P1_PolyMAC::zone_dis_base(), Champ_P0_PolyMAC::zone_dis_base(), Champ_Fonc_Q1_PolyMAC::zone_dis_base(), Champ_Fonc_P1_PolyMAC::zone_dis_base(), Champ_Fonc_Face_PolyMAC::zone_dis_base(), Champ_Face_PolyMAC::zone_dis_base(), Champ_Q1_EF::zone_dis_base(), Champ_P1_EF::zone_dis_base(), Champ_P0_EF::zone_dis_base(), Champ_Fonc_Q1_EF::zone_dis_base(), Champ_Fonc_P1_EF::zone_dis_base(), Champ_Q1_CoviMAC::zone_dis_base(), Champ_P1_CoviMAC::zone_dis_base(), Champ_P0_CoviMAC::zone_dis_base(), Champ_Fonc_Q1_CoviMAC::zone_dis_base(), Champ_Fonc_P1_CoviMAC::zone_dis_base(), Champ_Fonc_Face_CoviMAC::zone_dis_base(), Champ_Face_CoviMAC::zone_dis_base(), Champ_Q1_EF::zone_EF(), Champ_P1_EF::zone_EF(), Champ_P0_EF::zone_EF(), Champ_Fonc_Q1_EF::zone_EF(), Champ_Fonc_P1_EF::zone_EF(), Champ_Q1_PolyMAC::zone_PolyMAC(), Champ_P1_PolyMAC::zone_PolyMAC(), Champ_P0_PolyMAC::zone_PolyMAC(), Champ_Fonc_Q1_PolyMAC::zone_PolyMAC(), Champ_Fonc_P1_PolyMAC::zone_PolyMAC(), Champ_Fonc_Face_PolyMAC::zone_vf(), Champ_Face_PolyMAC::zone_vf(), Champ_Fonc_Face_CoviMAC::zone_vf(), and Champ_Face_CoviMAC::zone_vf().
Zone_VF & Ref_Zone_VF::valeur () [inline]
Definition at line 28 of file Ref_Zone_VF.h.
Member Data Documentation
const Type_info Ref_Zone_VF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_VF.h.
Zone_VF* Ref_Zone_VF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_VF.h.
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Ref_Zone_VF.h
src/Kernel/VF/Zones/Ref_Zone_VF.cpp