TRUST: TRUSTTab_parts< _TYPE_ > Class Template Reference
TRUSTTab_parts< _TYPE_ > Class Template Reference
This class allows to acces to individual sub-parts of DoubleTab objects that have a MD_Vector_composite descriptor.
#include <TRUSTTab_parts.h>
Public Member Functions
TRUSTTab_parts ()
TRUSTTab_parts (TRUSTVect< _TYPE_ > &)
void initialize (TRUSTVect< _TYPE_ > &)
void reset ()
int size () const
TRUSTTab< _TYPE_ > & operator[] (int i)
const TRUSTTab< _TYPE_ > & operator[] (int i) const
Private Member Functions
TRUSTTab_parts & operator= (const TRUSTTab_parts &)=delete
TRUSTTab_parts (const TRUSTTab_parts &)=delete
Private Attributes
TRUST_Vector< TRUSTTab, _TYPE_ > parts_
Et ouiiiiiiiiiiiiiiii.
Detailed Description
template<typename _TYPE_>
class TRUSTTab_parts< _TYPE_ >
This class allows to acces to individual sub-parts of DoubleTab objects that have a MD_Vector_composite descriptor.
Definition at line 25 of file TRUSTTab_parts.h.
Constructor & Destructor Documentation
TRUSTTab_parts() [1/3]
template<typename _TYPE_ > TRUSTTab_parts< _TYPE_ >::TRUSTTab_parts () inline
Definition at line 28 of file TRUSTTab_parts.h.
{ }
TRUSTTab_parts() [2/3]
template<typename _TYPE_ > TRUSTTab_parts< _TYPE_ >::TRUSTTab_parts (TRUSTVect< _TYPE_ > & vect)
Definition at line 83 of file TRUSTTab_parts.tpp.
{
  init_parts<_TYPE_>(vect, parts_, static_cast<TRUSTTab<_TYPE_>*>(0));
}
TRUSTTab_parts() [3/3]
template<typename _TYPE_ > TRUSTTab_parts< _TYPE_ >::TRUSTTab_parts (const TRUSTTab_parts< _TYPE_ > &) private delete
Member Function Documentation
initialize()
template<typename _TYPE_ > void TRUSTTab_parts< _TYPE_ >::initialize (TRUSTVect< _TYPE_ > & vect)
Definition at line 89 of file TRUSTTab_parts.tpp.
{
  reset();
  init_parts<_TYPE_>(vect, parts_, static_cast<TRUSTTab<_TYPE_>*>(0));
}
operator=()
template<typename _TYPE_ > TRUSTTab_parts & TRUSTTab_parts< _TYPE_ >::operator= (const TRUSTTab_parts< _TYPE_ > &) private delete
operator[]() [1/2]
template<typename _TYPE_ > TRUSTTab< _TYPE_ > & TRUSTTab_parts< _TYPE_ >::operator[] (int i) inline
Definition at line 35 of file TRUSTTab_parts.h.
{ return parts_[i]; }
References TRUSTTab_parts< _TYPE_ >::parts_.
operator[]() [2/2]
template<typename _TYPE_ > const TRUSTTab< _TYPE_ > & TRUSTTab_parts< _TYPE_ >::operator[] (int i) const inline
Definition at line 37 of file TRUSTTab_parts.h.
{ return parts_[i]; }
References TRUSTTab_parts< _TYPE_ >::parts_.
reset()
template<typename _TYPE_ > void TRUSTTab_parts< _TYPE_ >::reset () inline
Definition at line 31 of file TRUSTTab_parts.h.
{ parts_.dimensionner_force(0); }
References vect_impl::dimensionner_force(), and TRUSTTab_parts< _TYPE_ >::parts_.
size()
template<typename _TYPE_ > int TRUSTTab_parts< _TYPE_ >::size () const inline
Definition at line 32 of file TRUSTTab_parts.h.
{ return parts_.size(); }
References TRUSTTab_parts< _TYPE_ >::parts_, and vect_impl::size().
Referenced by Champ_Elem_PolyMAC::affecter_(), lecture_special_part2(), QDM_Multiphase::mettre_a_jour(), PrecondA::preconditionner_(), and SSOR::ssor().
Member Data Documentation
parts_
template<typename _TYPE_ > TRUST_Vector<TRUSTTab,_TYPE_> TRUSTTab_parts< _TYPE_ >::parts_ private
Et ouiiiiiiiiiiiiiiii.
Definition at line 44 of file TRUSTTab_parts.h.
Referenced by TRUSTTab_parts< _TYPE_ >::operator[](), TRUSTTab_parts< _TYPE_ >::reset(), and TRUSTTab_parts< _TYPE_ >::size().
The documentation for this class was generated from the following files:
src/Kernel/Math/TRUSTTab_parts.h
src/Kernel/Math/TRUSTTab_parts.tpp