TRUST: Puissance_Thermique_EF Class Reference
Puissance_Thermique_EF Class Reference
class Puissance_Thermique_EF
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_EF_base
#include <Puissance_Thermique_EF.h>
Public Member Functions
~Puissance_Thermique_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Puissance_Thermique_EF ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
virtual void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Puissance_Thermique_EF & self_cast (Objet_U &)
static const
Puissance_Thermique_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Puissance_Thermique_EF
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_EF_base
Definition at line 44 of file Puissance_Thermique_EF.h.
Constructor & Destructor Documentation
Puissance_Thermique_EF::~Puissance_Thermique_EF ()
Definition at line 28 of file Puissance_Thermique_EF.cpp.
Puissance_Thermique_EF::Puissance_Thermique_EF () [inline]
Definition at line 66 of file Puissance_Thermique_EF.h.
  : Terme_Puissance_Thermique(),Terme_Source_EF_base(It_Sou_EF(Eval_Puiss_Th_EF)())
{
}
Member Function Documentation
void Puissance_Thermique_EF::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 68 of file Puissance_Thermique_EF.cpp.
References Eval_Puiss_Th_EF::associer_champs(), Equation_base::discretisation(), Probleme_base::equation(), Iterateur_Source_EF::evaluateur(), Terme_Source_EF_base::iter, Terme_Puissance_Thermique::la_puissance, O_U_Ptr::le_nom(), Discretisation_base::nommer_completer_champ_physique(), and Equation_base::zone_dis().
{
  const Equation_base& eqn = pb.equation(0);
  eqn.discretisation().nommer_completer_champ_physique(eqn.zone_dis(),la_puissance.le_nom(),"W/m3",la_puissance,pb);
  Eval_Puiss_Th_EF& eval_puis = (Eval_Puiss_Th_EF&) iter.evaluateur();
  eval_puis.associer_champs(la_puissance);
}
void Puissance_Thermique_EF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Definition at line 55 of file Puissance_Thermique_EF.cpp.
References Evaluateur_Source_EF::associer_zones(), Iterateur_Source_EF::evaluateur(), Terme_Source_EF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_EF& zEF = ref_cast(Zone_EF,zone_dis.valeur());
  const Zone_Cl_EF& zclEF = ref_cast(Zone_Cl_EF,zone_cl_dis.valeur());
  iter->associer_zones(zEF, zclEF);
  Eval_Puiss_Th_EF& eval_puis = (Eval_Puiss_Th_EF&) iter.evaluateur();
  eval_puis.associer_zones(zEF, zclEF );
}
Objet_U * Puissance_Thermique_EF::cree_instance () [static]
Definition at line 28 of file Puissance_Thermique_EF.cpp.
int Puissance_Thermique_EF::duplique () const [virtual]
Implements Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
const Type_info * Puissance_Thermique_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
const Type_info * Puissance_Thermique_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
virtual void Puissance_Thermique_EF::mettre_a_jour (double temps) [inline, virtual]
Reimplemented from Terme_Puissance_Thermique.
Definition at line 54 of file Puissance_Thermique_EF.h.
  {
    Terme_Puissance_Thermique::mettre_a_jour(temps);
  }
Sortie & Puissance_Thermique_EF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 35 of file Puissance_Thermique_EF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Puissance_Thermique_EF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 43 of file Puissance_Thermique_EF.cpp.
References Champs_compris::ajoute_champ(), Source_base::champs_compris_, MorEqn::equation(), Terme_Puissance_Thermique::la_puissance, and Terme_Puissance_Thermique::lire_donnees().
{
  const Equation_base& eqn = equation();
  Terme_Puissance_Thermique::lire_donnees(s,eqn);
  champs_compris_.ajoute_champ(la_puissance);
// set_fichier("Puissance_Thermique");
// set_description("Degagement de puissance thermique = Integrale(P*dv)[W]");
  return s;
}
Puissance_Thermique_EF & Puissance_Thermique_EF::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
const Puissance_Thermique_EF & Puissance_Thermique_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
unsigned Puissance_Thermique_EF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Puissance_Thermique_EF.cpp.
Member Data Documentation
const Type_info Puissance_Thermique_EF::info_obj [static]
Reimplemented from Terme_Source_EF_base.
Definition at line 47 of file Puissance_Thermique_EF.h.
The documentation for this class was generated from the following files:
src/EF/Sources/Puissance_Thermique_EF.h
src/EF/Sources/Puissance_Thermique_EF.cpp