TRUST: Perte_Charge_Circulaire_VEF_P1NC Class Reference
Perte_Charge_Circulaire_VEF_P1NC Class Reference
#include <Perte_Charge_Circulaire_VEF_P1NC.h>
Public Member Functions
Perte_Charge_Circulaire_VEF_P1NC ()
~Perte_Charge_Circulaire_VEF_P1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Perte_Charge_VEF
Perte_Charge_VEF ()
~Perte_Charge_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override
Appelle perte_charge pour chaque face ou cela est necessaire.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
copie de ajouter sauf la derniere ligne
DoubleTab & calculer (DoubleTab &) const override
void associer_pb (const Probleme_base &) override
associe le_fluide et la_vitesse
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Perte_Charge_Circulaire_VEF_P1NC & self_cast (Objet_U &)
static const Perte_Charge_Circulaire_VEF_P1NC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Perte_Charge_VEF
static const Type_info * info ()
static Perte_Charge_VEF & self_cast (Objet_U &)
static const Perte_Charge_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Perte_Charge_VEF
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const override
Protected Member Functions inherited from Perte_Charge_VEF
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
associe la_zone_VEF et la_zone_Cl_VEF
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Champ_Don diam_hydr_ortho
Parser_U lambda
Parser_U lambda_ortho
DoubleVect v_valeur
Champ_Don v
Vecteur directeur de la perte de charge.
Additional Inherited Members
Protected Attributes inherited from Perte_Charge_VEF
Champ_Don diam_hydr
Ref_Fluide_base le_fluide
Ref_Champ_Inc_base la_vitesse
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
bool sous_zone
Le terme est-il limite a une sous-zone ?
Nom nom_sous_zone
Nom de la sous-zone, initialise dans readOn()
Ref_Sous_zone_VF la_sous_zone_dis
Initialise dans completer()
int implicite_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Detailed Description
Correspond a la somme d'une perte de charge d'intensite lambda dans la direction de v, et d'une perte de charge d'intensite lambda_ortho pour toute direction orthogonale a v.
Ou de facon equivalente a la somme d'une perte de charge isotrope d'intensite lambda_ortho, et d'une perte de charge directionnelle de vecteur v et d'intensite lamba - lambda_ortho. C'est ainsi que le calcul est code.
du/dt =
lambda_ortho(Re,x,y,z,t) * u * ||u|| / 2 Dh
(lambda(Re,x,y,z,t)-lambda_ortho(Re,x,y,z,t)) u.v * v * ||u|| / 2 Dh ||v||^2
Lecture des arguments :
Perte_Charge_Circulaire_VEF_P1NC diametre_hydraulique { lambda expression(Re,x,y,z,t) lambda_ortho expression(Re,x,y,z,t) diam_hydr champ_don direction champ_don [sous_zone nom] }
! Perte de charge anisotrope (selon un vecteur unitaire v et dans le plan orthogonal a ce vecteur)
Definition at line 51 of file Perte_Charge_Circulaire_VEF_P1NC.h.
Constructor & Destructor Documentation
Perte_Charge_Circulaire_VEF_P1NC()
Perte_Charge_Circulaire_VEF_P1NC::Perte_Charge_Circulaire_VEF_P1NC ()
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
~Perte_Charge_Circulaire_VEF_P1NC()
Perte_Charge_Circulaire_VEF_P1NC::~Perte_Charge_Circulaire_VEF_P1NC ()
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
Member Function Documentation
coeffs_perte_charge()
void Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const override protected virtual
 Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds
 Retourne le resultat calcule dans p_charge.
 Avantage : bonne factorisation.
 Inconvenient : cout de l'appel d'une methode virtuelle a
 l'interieur d'une boucle.
 \param u La vitesse a la face courante. 2 ou 3 composantes
 \param pos toto
 \param t titi
 \param norme_u La norme de la vitesse a la face courante
 \param dh Le diametre hydraulique a la face courante (tire de diam_hydr)
 \param nu la viscosite cinematique
 \param reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
 \param coeff_ortho coefficient dans la direction orthogonale
 \param coeff_long coefficient dans la direction longitudinale
 \param u_l vitesse dans la direction longitudinale
 \param v_valeur direction_longitudinale p_charge a 2 ou 3 composantes
 La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur)
! Appele pour chaque face par ajouter()
< Pour ne pas evaluer 2 fois le parser
Implements Perte_Charge_VEF.
Definition at line 180 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
{
// calcul de dh_ortho
  double dh_ortho=diam_hydr_ortho->valeur_a_compo(pos,0);
// calcul de u.d/||d||
// Calcul de v et ||v||^2
  av_valeur.resize(dimension);
  v.valeur().valeur_a(pos,av_valeur);
// on norme v
  {
    double vcarre=0;
    for (int dim=0; dim<dimension; dim++)
      vcarre+=av_valeur[dim]*av_valeur[dim];
    av_valeur/=sqrt(vcarre);
  }
// Calcul de u.v/||v||
  u_l=0;
  for (int dim=0; dim<dimension; dim++)
    u_l+=u[dim]*av_valeur[dim];
  double u_ortho=sqrt(std::max(norme_u*norme_u-u_l*u_l,0.0));
  /* PL: To avoid a possible division by zero, we replace:
     double nu=norme_u*dh/reynolds;
// calcule de Re_l et Re_ortho
// Calcul du reynolds
     double Re_l=std::fabs(u_l)*dh/nu; */
// By:
  double Re_l=dh*std::fabs(u_l)/nu;
  if(Re_l<1e-10) Re_l=1e-10;
// PL: To avoid a possible division by zero, we replace:
  /* double Re_ortho=u_ortho*dh_ortho/nu; */
// By:
  double Re_ortho=dh_ortho*u_ortho/nu;
  if (Re_ortho<1e-10) Re_ortho=1e-10;
// Calcul de lambda
  lambda.setVar(0,reynolds);
  lambda.setVar(1,Re_l);
  lambda.setVar(2,t);
  lambda.setVar(3,pos[0]);
  if (dimension>1)
    lambda.setVar(4,pos[1]);
  if (dimension>2)
    lambda.setVar(5,pos[2]);
// Calcul de lambda_ortho
  lambda_ortho.setVar(0,reynolds);
  lambda_ortho.setVar(1,Re_ortho);
  lambda_ortho.setVar(2,t);
  lambda_ortho.setVar(3,pos[0]);
  if (dimension>1)
    lambda_ortho.setVar(4,pos[1]);
  if (dimension>2)
    lambda_ortho.setVar(5,pos[2]);
  double l_ortho=lambda_ortho.eval(); //!< Pour ne pas evaluer 2 fois le parser
  double l_long=lambda.eval();
  coeff_ortho=l_ortho*u_ortho/2./dh_ortho;
  coeff_long=l_long *std::fabs(u_l)    /2./dh    ;
}
References diam_hydr_ortho, Objet_U::dimension, Parser_U::eval(), lambda, lambda_ortho, TRUSTVect< _TYPE_ >::resize(), Parser_U::setVar(), v, Deriv_Champ_Don_base::valeur(), and Champ_base::valeur_a().
cree_instance()
Objet_U * Perte_Charge_Circulaire_VEF_P1NC::cree_instance () static
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
duplique()
int Perte_Charge_Circulaire_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
get_info()
const Type_info * Perte_Charge_Circulaire_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
info()
const Type_info * Perte_Charge_Circulaire_VEF_P1NC::info () static
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
mettre_a_jour()
void Perte_Charge_Circulaire_VEF_P1NC::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 57 of file Perte_Charge_Circulaire_VEF_P1NC.h.
  {
    diam_hydr->mettre_a_jour(temps);
    diam_hydr_ortho->mettre_a_jour(temps);
    v.mettre_a_jour(temps);
  }
References Perte_Charge_VEF::diam_hydr, diam_hydr_ortho, Champ_Don::mettre_a_jour(), and v.
printOn()
Sortie & Perte_Charge_Circulaire_VEF_P1NC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
{
  return s << que_suis_je() << finl;
}
References finl, and Objet_U::que_suis_je().
Referenced by Perte_Charge_Circulaire_QC_VEF_P1NC::printOn().
readOn()
Entree & Perte_Charge_Circulaire_VEF_P1NC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< lambda
< diam_hydr
< diam_hydr_ortho
< sous_zone
< direction
< lambda_ortho
< non compris
Reimplemented from Source_base.
Definition at line 43 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
{
  Cerr << "Perte_Charge_Circulaire_VEF_P1NC::readOn " << finl;
  sous_zone=false;
  int lambda_ortho_ok=0;
  int lambda_ok=0;
// Definition des mots-cles
  Motcles les_mots(7);
  les_mots[0] = "lambda";
  les_mots[1] = "diam_hydr";
  les_mots[2] = "sous_zone";
  les_mots[3] = "direction";
  les_mots[4] = "lambda_ortho";
  les_mots[5] = "diam_hydr_ortho";
  les_mots[6] = "implicite";
// Lecture et interpretation
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  s >> motlu;
  while (motlu != accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'un " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  s >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :   //!< lambda
          {
            lambda_ok=1;
            Nom tmp;
            s >> tmp;
            Cerr << "Lecture et interpretation de la fonction " << tmp << " ... ";
            lambda.setNbVar(3+dimension);
            lambda.setString(tmp);
            lambda.addVar("Re_tot");
            lambda.addVar("Re_long");
            lambda.addVar("t");
            lambda.addVar("x");
            if (dimension>1)
              lambda.addVar("y");
            if (dimension>2)
              lambda.addVar("z");
            lambda.parseString();
            Cerr << " Ok" << finl;
            break;
          }
        case 1: //!< diam_hydr
          s >> diam_hydr;
          break;
        case 5: //!< diam_hydr_ortho
          s >> diam_hydr_ortho;
          break;
        case 2: //!< sous_zone
          s >> nom_sous_zone;
          sous_zone=true;
          break;
        case 3: //!< direction
          s >> v;
          break;
        case 4:   //!< lambda_ortho
          {
            lambda_ortho_ok=1;
            Nom tmp;
            s >> tmp;
            Cerr << "Lecture et interpretation de la fonction " << tmp << " ... ";
            lambda_ortho.setNbVar(3+dimension);
            lambda_ortho.setString(tmp);
            lambda_ortho.addVar("Re_tot");
            lambda_ortho.addVar("Re_ortho");
            lambda_ortho.addVar("t");
            lambda_ortho.addVar("x");
            if (dimension>1)
              lambda_ortho.addVar("y");
            if (dimension>2)
              lambda_ortho.addVar("z");
            lambda_ortho.parseString();
            Cerr << " Ok" << finl;
            break;
          }
        case 6:
          {
            s>>implicite_;
            break;
          }
        default : //!< non compris
          Cerr << "Mot cle \"" << motlu << "\" non compris lors de la lecture d'un "
               << que_suis_je() << finl;
          exit();
        }
      s >> motlu;
    }
// Verification de la coherence
  if (lambda_ok==0)
    {
      Cerr << "Il faut definir l'expression lamba(Re_long,Re_tot)" << finl;
      exit();
    }
  if (lambda_ortho_ok==0)
    {
      Cerr << "Il faut definir l'expression lamba_ortho(Re_ortho,Re_tot)" << finl;
      exit();
    }
  if  ((!diam_hydr.non_nul())|| (diam_hydr->nb_comp()!=1))
    {
      Cerr << "Il faut definir le champ diam_hydr a une composante" << finl;
      exit();
    }
  if ((!diam_hydr_ortho.non_nul())|| (diam_hydr_ortho->nb_comp()!=1))
    {
      Cerr << "Il faut definir le champ diam_hydr_ortho a une composante" << finl;
      exit();
    }
  if (v->nb_comp()!=dimension)
    {
      Cerr << "Il faut definir le champ direction a " << dimension << " composantes" << finl;
      exit();
    }
  Cerr << "Fin de Perte_Charge_Circulaire_VEF_P1NC::readOn" << finl;
  return s;
}
References Parser_U::addVar(), Cerr, Perte_Charge_VEF::diam_hydr, diam_hydr_ortho, Objet_U::dimension, Process::exit(), finl, Perte_Charge_VEF::implicite_, lambda, lambda_ortho, Champ_Don::nb_comp(), Perte_Charge_VEF::nom_sous_zone, O_U_Ptr::non_nul(), Parser_U::parseString(), Objet_U::que_suis_je(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Perte_Charge_VEF::sous_zone, and v.
Referenced by Perte_Charge_Circulaire_QC_VEF_P1NC::readOn().
self_cast() [1/2]
const Perte_Charge_Circulaire_VEF_P1NC & Perte_Charge_Circulaire_VEF_P1NC::self_cast (const Objet_U & r) static
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
self_cast() [2/2]
Perte_Charge_Circulaire_VEF_P1NC & Perte_Charge_Circulaire_VEF_P1NC::self_cast (Objet_U & r) static
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
taille_memoire()
unsigned Perte_Charge_Circulaire_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Perte_Charge_Circulaire_VEF_P1NC.cpp.
Member Data Documentation
diam_hydr_ortho
Champ_Don Perte_Charge_Circulaire_VEF_P1NC::diam_hydr_ortho private
Definition at line 72 of file Perte_Charge_Circulaire_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), mettre_a_jour(), and readOn().
info_obj
const Type_info Perte_Charge_Circulaire_VEF_P1NC::info_obj static
Definition at line 53 of file Perte_Charge_Circulaire_VEF_P1NC.h.
lambda
Parser_U Perte_Charge_Circulaire_VEF_P1NC::lambda mutable private
Definition at line 73 of file Perte_Charge_Circulaire_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), and readOn().
lambda_ortho
Parser_U Perte_Charge_Circulaire_VEF_P1NC::lambda_ortho mutable private
Definition at line 74 of file Perte_Charge_Circulaire_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), and readOn().
v
Champ_Don Perte_Charge_Circulaire_VEF_P1NC::v private
Vecteur directeur de la perte de charge.
Definition at line 76 of file Perte_Charge_Circulaire_VEF_P1NC.h.
Referenced by coeffs_perte_charge(), mettre_a_jour(), and readOn().
v_valeur
DoubleVect Perte_Charge_Circulaire_VEF_P1NC::v_valeur mutable private
Definition at line 75 of file Perte_Charge_Circulaire_VEF_P1NC.h.
The documentation for this class was generated from the following files:
src/VEF/Sources/Perte_Charge_Circulaire_VEF_P1NC.h
src/VEF/Sources/Perte_Charge_Circulaire_VEF_P1NC.cpp