TRUST: RegroupeBord Class Reference
RegroupeBord Class Reference
#include <RegroupeBord.h>
Public Member Functions
RegroupeBord ()
~RegroupeBord ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
void regroupe_bord (Domaine &dom, Nom nom, const List_Nom &nlistbord)
void rassemble_bords (Domaine &dom)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static RegroupeBord & self_cast (Objet_U &)
static const RegroupeBord & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 42 of file RegroupeBord.h.
Constructor & Destructor Documentation
RegroupeBord::RegroupeBord ()
Definition at line 25 of file RegroupeBord.cpp.
RegroupeBord::~RegroupeBord ()
Definition at line 25 of file RegroupeBord.cpp.
Member Function Documentation
Objet_U * RegroupeBord::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file RegroupeBord.cpp.
int RegroupeBord::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 25 of file RegroupeBord.cpp.
const Type_info * RegroupeBord::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file RegroupeBord.cpp.
const Type_info * RegroupeBord::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file RegroupeBord.cpp.
Entree & RegroupeBord::interpreter_ (Entree & is) [virtual]
< liste stockant tous les noms de frontiere du domaine
Implements Interprete_geometrique_base.
Definition at line 37 of file RegroupeBord.cpp.
References Frontiere::add(), Interprete_geometrique_base::associer_domaine(), Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Zone::frontiere(), Domaine::le_nom(), Frontiere::le_nom(), LIST, Zone::nb_front_Cl(), regroupe_bord(), and Domaine::zone().
{
  Nom nom;
  LIST(Nom) nlistbord;
  associer_domaine(is);
  is >> nom;
// is>>nlistbord;
// recodage pour ne pas mettre les virgules
  {
    Nom mot;
    is >>mot;
    if (mot!="{")
      {
        Cerr<< "we expected { and not "<<mot<<finl;
        exit();
      }
    is >>mot;
    while (mot!="}")
      {
        nlistbord.add(mot);
        is>>mot;
      }
  }
  Domaine& dom=domaine();
// test pour savoir si la frontiere a regrouper est valide
// i.e : si frontiere est une frontiere du domaine  : on applique regroupe_bord()
  Zone& zone=dom.zone(0);
  LIST(Nom) nlistbord_dom; //!< liste stockant tous les noms de frontiere du domaine
  int nbfr=zone.nb_front_Cl();
  for (int b=0; b<nbfr; b++)
    {
      Frontiere& org=zone.frontiere(b);
      nlistbord_dom.add(org.le_nom());
    }
  for (int i=0; i<nlistbord.size(); i++)
    {
      if (!nlistbord_dom.contient(nlistbord[i]))
        {
          Cerr << "Problem in the RegroupeBord instruction " << finl;
          Cerr << "The boundary named " << nlistbord[i] << " is not a boundary of the domain " << dom.le_nom() << finl;
          exit();
        }
    }
  regroupe_bord(dom,nom,nlistbord);
  return is;
}
Sortie & RegroupeBord::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file RegroupeBord.cpp.
{
  return Interprete::printOn(os);
}
void RegroupeBord::rassemble_bords (Domaine & dom)
Definition at line 89 of file RegroupeBord.cpp.
References Cerr, finl, Zone::frontiere(), Frontiere::le_nom(), LIST, Zone::nb_front_Cl(), regroupe_bord(), and Domaine::zone().
{
  Zone& zone=dom.zone(0);
  int nbfr=zone.nb_front_Cl();
  for (int b=0; b<nbfr; b++)
    {
      Frontiere& org=zone.frontiere(b);
      const Nom& nom_bord=org.le_nom();
      LIST(Nom) listn;
      listn.add(nom_bord);
      regroupe_bord(dom,nom_bord,listn);
// si on a detruit des bords on revient sur b
      if (nbfr!=zone.nb_front_Cl())
        {
          Cerr<<"Boundary "<<nom_bord<<" has been collected"<<finl;
          nbfr=zone.nb_front_Cl();
          b--;
        }
    }
}
Entree & RegroupeBord::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file RegroupeBord.cpp.
{
  return Interprete::readOn(is);
}
void RegroupeBord::regroupe_bord (Domaine & dom, Nom nom, const List_Nom & nlistbord)
< on veut verifie que le suivant n'est pas dans la liste
Definition at line 113 of file RegroupeBord.cpp.
References Zone::bord(), Nom::contient(), Faces::dimensionner(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), Zone::fixer_premieres_faces_frontiere(), Zone::frontiere(), Frontiere::le_nom(), Faces::les_sommets(), Faces::nb_faces(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Faces::nb_som_faces(), Frontiere::nommer(), Zone::raccord(), Zone::rang_frontiere(), liste::size(), List_Raccord::suppr(), List_Bord::suppr(), and Domaine::zone().
Referenced by interpreter_(), and rassemble_bords().
{
  Zone& zone=dom.zone(0);
  int nbfr=zone.nb_front_Cl();
  int nbfacestot=0;
  int prem_b=-1;
  for (int b=0; b<nbfr; b++)
    {
      Frontiere& org=zone.frontiere(b);
      if (nlistbord.contient(org.le_nom()))
        {
          if (prem_b==-1) prem_b=b;
// Frontiere& org=zone.frontiere(b);
          nbfacestot+=org.nb_faces();
        }
    }
  Frontiere& newb=zone.frontiere(prem_b);
  Faces& newfaces=newb.faces();
// newfaces.typer(zone.frontiere(0).faces().type_face());
  int nbsom=newfaces.nb_som_faces();
  int nbfacestot0=newfaces.nb_faces();
  newfaces.dimensionner(nbfacestot);
  IntTab& newsommet=newfaces.les_sommets();
  nbfacestot=nbfacestot0;
  for (int b=0; b<nbfr; b++)
    {
      if (b!=prem_b)
        {
          Frontiere& org=zone.frontiere(b);
          Nom nombord=org.le_nom();
          if (nlistbord.contient(nombord))
            {
              const IntTab& sommets=org.faces().les_sommets();
              int nbface=org.nb_faces();
              for (int fa=0; fa<nbface; fa++)
                for (int s=0; s<nbsom; s++)
                  newsommet(fa+nbfacestot,s)=sommets(fa,s);
              nbfacestot+=org.nb_faces();
            }
        }
    }
  zone.frontiere(prem_b).nommer("bord_a_conserver_coute_que_coute");
  Nom bordcons =zone.frontiere(prem_b).le_nom();
  for (int b=0; b<nbfr; b++)
    {
// la recup des bords et des raccords est dans la boucle
// pour pouvoir supprimer ...
      Bords& listbord=zone.faces_bord();
      Raccords& listrac=zone.faces_raccord();
// const Nom& nombord=nlistbord[b];
      Frontiere& org=zone.frontiere(b);
      const Nom& nombord=org.le_nom();
      if (nlistbord.contient(nombord))
        if (nombord!=bordcons)
          {
            int num_b=zone.rang_frontiere(nombord);
            if (num_b<listbord.size())
              listbord.suppr(zone.bord(nombord));
            else
              listrac.suppr(zone.raccord(nombord));
// on supprime un bord
            nbfr--;
            b--; //!< on veut verifie que le suivant n'est pas dans la liste
          }
    }
  newb.nommer(nom);
  zone.fixer_premieres_faces_frontiere();
}
RegroupeBord & RegroupeBord::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file RegroupeBord.cpp.
const RegroupeBord & RegroupeBord::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file RegroupeBord.cpp.
unsigned RegroupeBord::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file RegroupeBord.cpp.
Member Data Documentation
const Type_info RegroupeBord::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 44 of file RegroupeBord.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/RegroupeBord.h
src/Kernel/Geometrie/RegroupeBord.cpp