TRUST: Eval_Diff_VDF_Elem< DERIVED_T > Class Template Reference
Eval_Diff_VDF_Elem< DERIVED_T > Class Template Reference
#include <Eval_Diff_VDF_Elem.h>
Public Member Functions
double Dist_norm_bord (int face) const
double Dist_face_elem0 (int face, int n0) const
double Dist_face_elem1 (int face, int n1) const
double Dist_norm_bord_externe_VEC (int boundary_index, int global_face, int local_face) const
double Dist_norm_bord_externe_ (int global_face) const
double nu_1 (int i, int compo=0) const
double nu_2 (int i, int compo=0) const
double compute_heq (double, int, double, int, int compo=0) const
int ind_Fluctu_Term () const
double equivalent_distance (int boundary_index, int local_face) const
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
template<typename BC >
double flux_face (const DoubleTab &, int, const BC &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_faces_interne (const DoubleTab &, int) const
template<typename BC >
void coeffs_face (int, int, const BC &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, double &aii, double &ajj) const
void coeffs_face (int, int, const Periodique &, double &aii, double &ajj) const
void coeffs_face (int, int, const NSCBC &, double &aii, double &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, double &aii, double &ajj) const
void coeffs_faces_interne (int, double &aii, double &ajj) const
template<typename BC >
double secmem_face (int, const BC &, int) const
double secmem_face (int, const Dirichlet_entree_fluide &, int) const
double secmem_face (int, const Neumann_paroi &, int) const
double secmem_face (int, const Echange_global_impose &, int) const
double secmem_face (int, int, int, const Echange_externe_impose &, int) const
double secmem_faces_interne (int) const
template<typename BC >
void flux_face (const DoubleTab &, int, const BC &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
template<typename BC >
void coeffs_face (int, int, const BC &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Periodique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_faces_interne (int, DoubleVect &aii, DoubleVect &ajj) const
template<typename BC >
void secmem_face (int, const BC &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_entree_fluide &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_defilante &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_fixe &, int, DoubleVect &) const
void secmem_face (int, const Echange_global_impose &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi &, int, DoubleVect &) const
void secmem_face (int, int, int, const Echange_externe_impose &, int, DoubleVect &) const
void secmem_faces_interne (int, DoubleVect &) const
Static Public Attributes
static constexpr bool IS_MULTD = true
static constexpr bool IS_AXI = false
static constexpr bool IS_DEQUIV = false
static constexpr bool IS_MODIF_DEQ = false
static constexpr bool IS_QUASI = false
static constexpr bool IS_ANISO = false
Detailed Description
template<typename DERIVED_T>
class Eval_Diff_VDF_Elem< DERIVED_T >
Definition at line 31 of file Eval_Diff_VDF_Elem.h.
Member Function Documentation
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_echange_externe_impose () const [inline]
Definition at line 89 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_echange_global_impose () const [inline]
Definition at line 90 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_entree_fluide () const [inline]
Definition at line 91 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_NSCBC () const [inline]
Definition at line 99 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_paroi () const [inline]
Definition at line 92 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_paroi_adiabatique () const [inline]
Definition at line 93 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_paroi_defilante () const [inline]
Definition at line 94 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_paroi_fixe () const [inline]
Definition at line 95 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_periodique () const [inline]
Definition at line 98 of file Eval_Diff_VDF_Elem.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_sortie_libre () const [inline]
Definition at line 96 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T> int Eval_Diff_VDF_Elem< DERIVED_T >::calculer_flux_faces_symetrie () const [inline]
Definition at line 97 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int boundary_index, int face, int local_face, int num1, const Echange_externe_impose & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1122 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and DoubleVect::size().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  double e,h_total_inv;
  int i = elem_(face,0);
  //  int j = elem(face,1);
  //  int ori = orientation(face);
  int k;
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  if (i != -1)
    {
      //      e = la_zone->xv(face,ori) - la_zone->xp(i,ori);
      for (k=0; k<aii.size(); k++)
        {
          const int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
          h_total_inv =  1/la_cl.h_imp(face-num1,k) + e/nu_2(i,l);
          aii(k) = surface(face)/h_total_inv;
        }
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      //e = la_zone->xp(j,ori) - la_zone->xv(face,ori);
      for (k=0; k<ajj.size(); k++)
        {
          const int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
          h_total_inv = 1/la_cl.h_imp(face-num1,k) + e/nu_2(elem_(face,1),l);
          ajj(k) = surface(face)/h_total_inv;
        }
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int num1, const Echange_global_impose & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1246 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and DoubleVect::size().
{
  int i = elem_(face,0);
  //  int j = elem(face,1);
  int k;
  if (i != -1)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = la_cl.h_imp(face-num1,k)*surface(face);
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = la_cl.h_imp(face-num1,k)*surface(face);
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const [inline]
Definition at line 645 of file Eval_Diff_VDF_Elem.h.
{
  aii = ajj = 0;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int , const Periodique & la_cl, double & aii, double & ajj) const [inline]
Definition at line 688 of file Eval_Diff_VDF_Elem.h.
References Periodique::distance().
{
  int i = elem_(face,0);
  int j = elem_(face,1);
  double d0 = la_zone->dist_face_elem0_period(face,i,la_cl.distance());
  double d1 = la_zone->dist_face_elem1_period(face,j,la_cl.distance());
  double heq;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  heq=  compute_heq(d0,i,d1,j,ori);
  aii = ajj = heq*surface(face)*porosite(face);
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int num1, const NSCBC & la_cl, double & aii, double & ajj) const [inline]
Definition at line 743 of file Eval_Diff_VDF_Elem.h.
{
  /*  Cerr<<"Eval_Diff_VDF_var_Elem::coeffs_face n'est pas codee"<<finl;
      Cerr<<"pour la condition NSCBC"<<finl;
      exit();*/
  aii = ajj = 0.;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int num1, const Echange_global_impose & la_cl, double & aii, double & ajj) const [inline]
Definition at line 590 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp().
{
  double h = la_cl.h_imp(face-num1);
  int i = elem_(face,0);
  //  int j = elem(face,1);
  if (i!= -1)
    {
      aii = h*surface(face);
      ajj = 0;
    }
  else
    {
      ajj = h*surface(face);
      aii = 0;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int boundary_index, int face, int local_face, int num1, const Echange_externe_impose & la_cl, double & aii, double & ajj) const [inline]
Definition at line 452 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  double h_total_inv;
  double h_imp = la_cl.h_imp(face-num1);
  double e;
  int i = elem_(face,0);
  //  int j = elem(face,1);
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  double heq;
  if (i != -1)
    {
      if (nu_2(i,ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv =  1.0/h_imp + e/nu_2(i,ori);
          heq = 1.0 / h_total_inv;
        }
      aii = heq*surface(face);
      ajj = 0;
    }
  else
    {
      if (nu_2(elem_(face,1),ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv =  1.0/h_imp + e/nu_2(elem_(face,1),ori);
          heq = 1.0 / h_total_inv;
        }
      ajj = heq*surface(face);
      aii = 0;
    }
}
template<typename DERIVED_T> template<typename BC > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int , int , const BC & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 197 of file Eval_Diff_VDF_Elem.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int num1, const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1306 of file Eval_Diff_VDF_Elem.h.
{
  aii=0.;
  ajj=0.;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 863 of file Eval_Diff_VDF_Elem.h.
References DoubleVect::size().
{
  int k;
  int i = elem_(face,0);
  // int j = elem(face,1);
  double dist = Dist_norm_bord(face);
  if (i != -1)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = surface(face)*porosite(face)*nu_1(i,k)/dist;
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else  // j != -1
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = surface(face)*(porosite(face)*nu_1(elem_(face,1),k))/dist;
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 922 of file Eval_Diff_VDF_Elem.h.
References Process::exit().
{
  // coder dans evbasreyconst comme entree_fluide ????
  assert(0);
  Process::exit();
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int num1, const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 998 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, and DoubleVect::size().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int k;
  double dist = Dist_norm_bord(face);
  if (n0 != -1)
    {
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //          for (k=0; k<aii.size(); k++)
          //            aii(k) =
          //              surface(face)*porosite(face)*nu_1(n0,k)/dv_mvol(n0)/dist;
        }
      else
        {
          for (k=0; k<aii.size(); k++)
            aii(k) =
              surface(face)*porosite(face)*nu_1(n0,k)/dist;
        }
      for (k=0; k<aii.size(); k++)
        ajj(k) =0;
    }
  else  // n1 != -1
    {
      if (n1==-1) Process::exit();
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //          for (k=0; k<ajj.size(); k++)
          //            ajj(k) =
          //              surface(face)*porosite(face)*nu_1(n1,k)/dv_mvol(n1)/dist;
        }
      else
        {
          for (k=0; k<ajj.size(); k++)
            ajj(k) =
              surface(face)*porosite(face)*nu_1(n1,k)/dist;
        }
      for (k=0; k<ajj.size(); k++)
        aii(k) =0.;
    }
}
template<typename DERIVED_T> template<typename BC > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int , int , const BC & , double & aii, double & ajj) const [inline]
Definition at line 135 of file Eval_Diff_VDF_Elem.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int , const Periodique & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1381 of file Eval_Diff_VDF_Elem.h.
References Periodique::distance(), and DoubleVect::size().
{
  int k;
  int i = elem_(face,0);
  int j = elem_(face,1);
  double d0 = la_zone->dist_face_elem0_period(face,i,la_cl.distance());
  double d1 = la_zone->dist_face_elem1_period(face,j,la_cl.distance());
  double heq;
  for (k=0; k<aii.size(); k++)
    {
      heq = compute_heq(d0,i,d1,j,k);
      aii(k) =  heq*surface(face)*porosite(face);
    }
  for (k=0; k<ajj.size(); k++)
    {
      heq = compute_heq(d0,i,d1,j,k);
      ajj(k)=  heq*surface(face)*porosite(face);
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, double & aii, double & ajj) const [inline]
Definition at line 342 of file Eval_Diff_VDF_Elem.h.
{
  int i = elem_(face,0);
  //  int j = elem(face,1);
  double dist = Dist_norm_bord(face);
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (i != -1)
    {
      aii =  porosite(face)*nu_1(i,ori)*surface(face)/dist;
      ajj = 0;
    }
  else   // j != -1
    {
      ajj =  porosite(face)*nu_1(elem_(face,1),ori)*surface(face)/dist;
      aii = 0;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_faces_interne (int face, DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1439 of file Eval_Diff_VDF_Elem.h.
References DoubleVect::size().
{
  int k;
  int i = elem_(face,0);
  int j = elem_(face,1);
  double d0 = Dist_face_elem0(face,i);
  double d1 = Dist_face_elem1(face,j);
  double heq;
  for ( k=0; k<aii.size(); k++)
    {
      int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
      if (nu_1(i,l)==0.0 && nu_2(j,l)==0.0)
        {
          heq = 0.;
        }
      else
        {
          assert(nu_1(i,l)!=0.0);
          assert(nu_2(j,l)!=0.0);
          heq = compute_heq(d0,i,d1,j,l);
        }
      aii(k) = heq*surface(face)*porosite(face);
      ajj(k) = heq*surface(face)*porosite(face);
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_faces_interne (int face, double & aii, double & ajj) const [inline]
Definition at line 777 of file Eval_Diff_VDF_Elem.h.
{
  int i = elem_(face,0);
  int j = elem_(face,1);
  double d0 = Dist_face_elem0(face,i);
  double d1 = Dist_face_elem1(face,j);
  double heq;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (nu_1(i,ori)==0.0 && nu_2(j,ori)==0.0)
    {
      heq = 0.;
    }
  else
    {
      assert(nu_1(i,ori)!=0.0);
      assert(nu_2(j,ori)!=0.0);
      heq = compute_heq(d0,i,d1,j,ori);
    }
  aii = ajj = heq*surface(face)*porosite(face);
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::compute_heq (double d0, int i0, double d1, int i1, int compo = 0) const [inline]
Definition at line 244 of file Eval_Diff_VDF_Elem.h.
{
  double heq = static_cast<const DERIVED_T *>(this)->compute_heq_impl(d0, i0, d1, i1, compo);
  return heq;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem0 (int face, int n0) const [inline]
Definition at line 278 of file Eval_Diff_VDF_Elem.h.
{
  double val = DERIVED_T::IS_AXI ? la_zone->dist_face_elem0_axi(face,n0): la_zone->dist_face_elem0(face,n0);
  return val;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem1 (int face, int n1) const [inline]
Definition at line 285 of file Eval_Diff_VDF_Elem.h.
{
  double val = DERIVED_T::IS_AXI ? la_zone->dist_face_elem1_axi(face,n1): la_zone->dist_face_elem1(face,n1);
  return val;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord (int face) const [inline]
Definition at line 268 of file Eval_Diff_VDF_Elem.h.
{
  double val = DERIVED_T::IS_AXI ? la_zone->dist_norm_bord_axi(face) : la_zone->dist_norm_bord(face);
  if (DERIVED_T::IS_MULTD)
    return val;
  else
    return 2*val;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_ (int global_face) const [inline]
Definition at line 301 of file Eval_Diff_VDF_Elem.h.
{
  assert (!DERIVED_T::IS_DEQUIV);
  return DERIVED_T::IS_AXI ? la_zone->dist_norm_bord_axi(global_face) : la_zone->dist_norm_bord(global_face);
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_VEC (int boundary_index, int global_face, int local_face) const [inline]
Definition at line 292 of file Eval_Diff_VDF_Elem.h.
{
  if (DERIVED_T::IS_DEQUIV)
    return equivalent_distance(boundary_index,local_face);
  else
    return DERIVED_T::IS_AXI ? la_zone->dist_norm_bord_axi(global_face) : la_zone->dist_norm_bord(global_face);
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::equivalent_distance (int boundary_index, int local_face) const [inline]
Definition at line 258 of file Eval_Diff_VDF_Elem.h.
{
  return static_cast<const DERIVED_T *>(this)->get_equivalent_distance(boundary_index,local_face);
}
template<typename DERIVED_T> template<typename BC > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int , const BC & , int , DoubleVect & flux) const [inline]
Definition at line 179 of file Eval_Diff_VDF_Elem.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 814 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, DoubleVect::size(), and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int k;
  double dist = Dist_norm_bord(face);
  if (n0 != -1)
    {
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //        for (k=0; k<flux.size(); k++)
          //          flux(k) = (la_cl.val_imp(face-num1,k)-inco(n0,k))/dv_mvol(n0)
          //                    *surface(face)*porosite(face)*nu_1(n0,k)/dist;
        }
      else
        {
          for (k=0; k<flux.size(); k++)
            flux(k) = (la_cl.val_imp(face-num1,k)-inco(n0,k))
                      *surface(face)*porosite(face)*nu_1(n0,k)/dist;
        }
    }
  else  // n1 != -1
    {
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //        for (k=0; k<flux.size(); k++)
          //          flux(k) = (inco(n1,k)-la_cl.val_imp(face-num1,k))/dv_mvol(n1)
          //                    *surface(face)*porosite(face)*nu_1(n1,k)/dist;
        }
      else
        {
          for (k=0; k<flux.size(); k++)
            flux(k) = (inco(n1,k)-la_cl.val_imp(face-num1,k))
                      *surface(face)*porosite(face)*nu_1(n1,k)/dist;
        }
    }
}
template<typename DERIVED_T> template<typename BC > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int , const BC & , int) const [inline]
Definition at line 120 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
Definition at line 313 of file Eval_Diff_VDF_Elem.h.
References Dirichlet::val_imp().
{
  double T_imp = la_cl.val_imp(face-num1);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  // Olga avait mis :
  // double dist = 2*Dist_norm_bord(face);
  // Pierre dit que :
  double dist = Dist_norm_bord(face);
  double flux;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (n0 != -1)
    {
      flux = (T_imp-inco[n0])*surface(face)/dist;
      flux *= (porosite(face)*nu_1(n0,ori));
    }
  else   // n1 != -1
    {
      flux = (inco[n1]-T_imp)*surface(face)/dist;
      flux*= (porosite(face)*nu_1(n1,ori));
    }
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline]
Definition at line 910 of file Eval_Diff_VDF_Elem.h.
References Process::exit().
{
  // coder dans evbasreyconst comme entree_fluide ????
  assert(0);
  Process::exit();
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int face, const Neumann_paroi & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1294 of file Eval_Diff_VDF_Elem.h.
References Neumann_paroi::flux_impose(), and DoubleVect::size().
{
  int i = elem_(face,0);
  for (int k=0; k<flux.size(); k++)
    flux(k) = ((i != -1) ? 1 : -1) * la_cl.flux_impose(face-num1,k)*surface(face);
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int face, const Neumann_paroi & la_cl, int num1) const [inline]
Definition at line 628 of file Eval_Diff_VDF_Elem.h.
References Neumann_paroi::flux_impose().
{
  int i = elem_(face,0);
  //  int j = elem(face,1);
  double flux;
  if (i != -1)
    flux = la_cl.flux_impose(face-num1)*surface(face);
  else
    flux = -la_cl.flux_impose(face-num1)*surface(face);
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Echange_global_impose & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1219 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, Echange_impose_base::h_imp(), DoubleVect::size(), and Echange_impose_base::T_ext().
{
  if (DERIVED_T::IS_QUASI)
    {
      Cerr<<__FILE__<< " QC BORD non code ligne "<<(int)__LINE__<<finl;
      Process::exit();
    }
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int k;
  if (n0 != -1)
    for (k=0; k<flux.size(); k++)
      flux(k) = la_cl.h_imp(face-num1,k)*(la_cl.T_ext(face-num1,k) - inco(n0,k))
                *surface(face);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = la_cl.h_imp(face-num1,k)*(inco(n1,k) - la_cl.T_ext(face-num1,k))
                *surface(face);
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int boundary_index, int face, int local_face, const Echange_externe_impose & la_cl, int num1) const [inline]
Definition at line 390 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and Echange_impose_base::T_ext().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  double h_total_inv;
  double h_imp = la_cl.h_imp(face-num1);
  double T_ext = la_cl.T_ext(face-num1);
  double e;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
//  Dist_norm_bord_externe(boundary_index,face,local_face);
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  double flux, heq;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  // XXX : E. Saikali 08/03/2021
  // The test of a zero diffusion was not done before. I think it should be like that
  // See always when we use int ori = DERIVED_T::IS_ANISO....
  if (n0 != -1)
    {
      // XXX : Attention for DIFT OPERATORS : nu_2 and not nu_1 (only laminar part)
      if (nu_2(n0,ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv = 1.0/h_imp + e/nu_2(n0,ori);
          heq = 1.0 / h_total_inv;
        }
      flux = heq*(T_ext - inco[n0])*surface(face);
    }
  else
    {
      if (nu_2(n1,ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv = 1.0/h_imp + e/nu_2(n1,ori);
          heq = 1.0 / h_total_inv;
        }
      flux = heq*(inco[n1] - T_ext)*surface(face);
    }
  return flux;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Echange_global_impose & la_cl, int num1) const [inline]
Definition at line 573 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and Echange_impose_base::T_ext().
{
  double h = la_cl.h_imp(face-num1);
  double T_ext = la_cl.T_ext(face-num1);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  if (n0 != -1)
    flux = h*(T_ext - inco[n0])*surface(face);
  else
    flux = h*(inco[n1] - T_ext)*surface(face);
  return flux;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Definition at line 670 of file Eval_Diff_VDF_Elem.h.
References Periodique::distance().
{
  double flux;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double d0 = la_zone->dist_face_elem0_period(face,n0,la_cl.distance());
  double d1 = la_zone->dist_face_elem1_period(face,n1,la_cl.distance());
  double heq;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  heq = compute_heq(d0,n0,d1,n1,ori);
  flux = heq*(inco[n1] - inco[n0])*surface(face)*porosite(face);
  return flux;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int faceD, const NSCBC & la_cl, int ndeb) const [inline]
Definition at line 705 of file Eval_Diff_VDF_Elem.h.
References Zone_VF::elem_faces(), Zone_VF::face_voisins(), Zone_VDF::orientation(), and Zone_VF::xp().
{
  // On evalue le flux au bord a partir des premieres mailles internes
  const Zone_VDF& zvdf = la_zone;
  int oriD = zvdf.orientation(faceD);
  int faceC;
  int elem3;
  int elem0 = zvdf.face_voisins(faceD,0);
  //double signe = -1.;
  if (elem0 == -1)
    {
      elem0 = zvdf.face_voisins(faceD,1);
      faceC = zvdf.elem_faces(elem0,oriD+dimension);
      elem3 = zvdf.face_voisins(faceC,1);
      //  signe = 1.;
    }
  else
    {
      faceC = zvdf.elem_faces(elem0,oriD);
      elem3 = zvdf.face_voisins(faceC,0);
    }
  assert(faceC != faceD);
  assert(elem3 != elem0);
  double d0 = zvdf.xp(elem0,orientation(faceD)) - zvdf.xp(elem3,orientation(faceD));
  double heq;
  int ori = DERIVED_T::IS_ANISO ? oriD : 0;
  heq = (nu_1(elem0,ori)/d0);
  double flux = heq*(inco(elem0) - inco(elem3))*surface(faceD)*porosite(faceD);
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int boundary_index, int face, int local_face, const Echange_externe_impose & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1069 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, Echange_impose_base::h_imp(), DoubleVect::size(), and Echange_impose_base::T_ext().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  if (DERIVED_T::IS_QUASI)
    {
      Cerr<<__FILE__<< " QC BORD non code ligne "<<(int)__LINE__<<finl;
      Process::exit();
    }
  double h_total_inv,e;
  int k;
  //  int ori = orientation(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  if (n0 != -1)
    {
      //e = la_zone->xv(face,ori) - la_zone->xp(n0,ori);
      for (k=0; k<flux.size(); k++)
        {
          const int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
          h_total_inv = 1/la_cl.h_imp(face-num1,k) + e/nu_2(n0,l);
          flux(k) = (la_cl.T_ext(face-num1,k) - inco(n0,k))*surface(face)/h_total_inv;
        }
    }
  else
    {
      //    e = la_zone->xp(n1,ori) - la_zone->xv(face,ori);
      for (k=0; k<flux.size(); k++)
        {
          const int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
          h_total_inv = 1/la_cl.h_imp(face-num1,k) + e/nu_2(n1,l);
          flux(k) = (inco(n1,k) - la_cl.T_ext(face-num1,k))*surface(face)/h_total_inv;
        }
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Dirichlet_paroi_fixe & , int num1, DoubleVect & flux) const [inline]
Definition at line 946 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, and DoubleVect::size().
{
  // coder dans evbasreyconst comme entree_fluide ????
  //
  flux=0;;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int k;
  double dist = Dist_norm_bord(face);
  if (n0 != -1)
    {
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //                for (k=0; k<flux.size(); k++)
          //                  flux(k) = (-inco(n0,k))
          //                            *surface(face)*porosite(face)*nu_1(n0,k)/dv_mvol(n0)/dist;
        }
      else
        {
          for (k=0; k<flux.size(); k++)
            flux(k) = (-inco(n0,k))
                      *surface(face)*porosite(face)*nu_1(n0,k)/dist;
        }
    }
  else  // n1 != -1
    {
      if (DERIVED_T::IS_QUASI)
        {
          //TODO : implement when Diff_K_Eps_QC is templatized
          Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
          Process::exit();
          //                for (k=0; k<flux.size(); k++)
          //                  flux(k) = (inco(n1,k))
          //                            *surface(face)*porosite(face)*nu_1(n1,k)/dv_mvol(n1)/dist;
        }
      else
        {
          for (k=0; k<flux.size(); k++)
            flux(k) = (inco(n1,k))
                      *surface(face)*porosite(face)*nu_1(n1,k)/dist;
        }
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int , DoubleVect & flux) const [inline]
Definition at line 1345 of file Eval_Diff_VDF_Elem.h.
References Cerr, Periodique::distance(), Process::exit(), finl, and DoubleVect::size().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double d0 = la_zone->dist_face_elem0_period(face,n0,la_cl.distance());
  double d1 = la_zone->dist_face_elem1_period(face,n1,la_cl.distance());
  double heq;
  if (DERIVED_T::IS_QUASI)
    {
      //TODO : implement when Diff_K_Eps_QC is templatized
      Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
      Process::exit();
      //            for (int k=0; k<flux.size(); k++)
      //              {
      //                heq = compute_heq(d0,n0,d1,n1,k);
      //                flux(k) = heq*(inco(n1,k)/dv_mvol(n1) - inco(n0,k)/dv_mvol(n0))*surface(face)*porosite(face);
      //              }
    }
  else
    {
      for (int k=0; k<flux.size(); k++)
        {
          heq = compute_heq(d0,n0,d1,n1,k);
          flux(k) = heq*(inco(n1,k) - inco(n0,k))*surface(face)*porosite(face);
        }
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , int , const Neumann_sortie_libre & , int , DoubleVect & flux) const [inline]
Definition at line 1327 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, and DoubleVect::size().
{
  for (int k=0; k<flux.size(); k++)
    {
      if (flux(k)!=0)
        {
          Cerr<<" et OUI"<<finl;
          Process::exit();
        }
    }
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::flux_faces_interne (const DoubleTab & inco, int face) const [inline]
Definition at line 753 of file Eval_Diff_VDF_Elem.h.
{
  double flux,heq;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double d0 = Dist_face_elem0(face,n0);
  double d1 = Dist_face_elem1(face,n1);
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (nu_1(n0,ori)==0.0 && nu_1(n1,ori)==0.0)
    {
      heq = 0.;
    }
  else
    {
      assert(nu_1(n0,ori)!=0.0);
      assert(nu_1(n1,ori)!=0.0);
      heq = compute_heq(d0,n0,d1,n1,ori);
    }
  flux = heq*(inco[n1] - inco[n0])*surface(face)*porosite(face);
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline]
Definition at line 1406 of file Eval_Diff_VDF_Elem.h.
References Cerr, Process::exit(), finl, and DoubleVect::size().
{
  if (DERIVED_T::IS_QUASI)
    {
      //TODO : implement when Diff_K_Eps_QC is templatized
      Cerr << "Diff_K_Eps_QC are not templatized yet !" << finl;
      Process::exit();
    }
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double d0 = Dist_face_elem0(face,n0);
  double d1 = Dist_face_elem1(face,n1);
  double heq;
  for (int k=0; k<flux.size(); k++)
    {
      const int l = DERIVED_T::IS_ANISO ? orientation(face) : k;
      if (nu_1(n0, l) == 0.0 && nu_1(n1, l) == 0.0)
        heq = 0.;
      else
        {
          assert(nu_1(n0, l)!=0.0);
          assert(nu_1(n1, l)!=0.0);
          heq = compute_heq(d0, n0, d1, n1, l);
        }
      flux(k) = heq*(inco(n1,k) - inco(n0,k))*surface(face)*porosite(face);
    }
}
template<typename DERIVED_T > int Eval_Diff_VDF_Elem< DERIVED_T >::ind_Fluctu_Term () const [inline]
Definition at line 252 of file Eval_Diff_VDF_Elem.h.
{
  return static_cast<const DERIVED_T *>(this)->get_ind_Fluctu_Term();
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::nu_1 (int i, int compo = 0) const [inline]
Definition at line 230 of file Eval_Diff_VDF_Elem.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_1_impl(i, compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::nu_2 (int i, int compo = 0) const [inline]
Definition at line 237 of file Eval_Diff_VDF_Elem.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_2_impl(i, compo);
  return nu;
}
template<typename DERIVED_T> template<typename BC > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int , const BC & , int) const [inline]
Definition at line 151 of file Eval_Diff_VDF_Elem.h.
{ return 0; }
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int boundary_index, int face, int local_face, const Echange_externe_impose & la_cl, int num1) const [inline]
Definition at line 512 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and Echange_impose_base::T_ext().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  double h_total_inv;
  double h_imp = la_cl.h_imp(face-num1);
  double T_ext = la_cl.T_ext(face-num1);
  double e;
  int i = elem_(face,0);
  //  int j = elem(face,1);
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  double flux, heq;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (i != -1)
    {
      if (nu_2(i,ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv = 1.0/h_imp + e/nu_2(i,ori);
          heq = 1.0 / h_total_inv;
        }
      flux = heq*T_ext*surface(face);
    }
  else
    {
      if (nu_2(elem_(face,1),ori) == 0.0)
        {
          heq = h_imp; // Should be 0 ??
        }
      else
        {
          h_total_inv = 1.0/h_imp + e/nu_2(elem_(face,1),ori);
          heq = 1.0 / h_total_inv;
        }
      flux = - heq*T_ext*surface(face);
    }
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Echange_global_impose & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1270 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), DoubleVect::size(), and Echange_impose_base::T_ext().
{
  int k;
  double h;
  int i = elem_(face,0);
  //int j = elem(face,1);
  if (i != -1)
    for (k=0; k<flux.size(); k++)
      {
        h = la_cl.h_imp(face-num1,k);
        flux(k) = h*la_cl.T_ext(face-num1,k)*surface(face);
      }
  else
    for (k=0; k<flux.size(); k++)
      {
        h = la_cl.h_imp(face-num1,k);
        flux(k) = -h*la_cl.T_ext(face-num1,k)*surface(face);
      }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Neumann_paroi & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1316 of file Eval_Diff_VDF_Elem.h.
References Neumann_paroi::flux_impose(), and DoubleVect::size().
{
  int i = elem_(face,0);
  for (int k=0; k<flux.size(); k++)
    flux(k) = ((i != -1) ? 1 : -1) * la_cl.flux_impose(face-num1,k)*surface(face);
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int boundary_index, int face, int local_face, const Echange_externe_impose & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 1172 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), DoubleVect::size(), and Echange_impose_base::T_ext().
{
  // C.L de type Echange_externe_impose : 1/h_total = (1/h_imp) + (e/diffusivite)
  // La C.L fournit h_imp ; il faut calculer e/diffusivite
  double e,h_total_inv;
  int k;
  double h_imp;
  int i = elem_(face,0);
  //  int j = elem(face,1);
  //  int ori = orientation(face);
  if (DERIVED_T::IS_MODIF_DEQ)
    {
      e = ind_Fluctu_Term()==1 ? Dist_norm_bord_externe_(face) :
          equivalent_distance(boundary_index,local_face);
    }
  else
    {
      e = DERIVED_T::IS_DEQUIV ? equivalent_distance(boundary_index,local_face) :
          Dist_norm_bord_externe_(face);
    }
  if (i != -1)
    {
      //e = la_zone->xv(face,ori) - la_zone->xp(i,ori);
      for (k=0; k<flux.size(); k++)
        {
          h_imp = la_cl.h_imp(face-num1,k);
          h_total_inv = 1/h_imp + e/nu_2(i,k);
          flux(k) = la_cl.T_ext(face-num1,k) *surface(face)/h_total_inv;
        }
    }
  else
    {
      //e = la_zone->xp(j,ori) - la_zone->xv(face,ori);
      for (k=0; k<flux.size(); k++)
        {
          h_imp = la_cl.h_imp(face-num1,k);
          h_total_inv = 1/h_imp + e/nu_2(elem_(face,1),k);
          flux(k) =  - la_cl.T_ext(face-num1,k)*surface(face)/h_total_inv;
        }
    }
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Neumann_paroi & la_cl, int num1) const [inline]
Definition at line 654 of file Eval_Diff_VDF_Elem.h.
References Neumann_paroi::flux_impose().
{
  int i = elem_(face,0);
  //  int j = elem(face,1);
  double flux;
  if (i != -1)
    flux = la_cl.flux_impose(face-num1)*surface(face);
  else
    flux = -la_cl.flux_impose(face-num1)*surface(face);
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline]
Definition at line 1058 of file Eval_Diff_VDF_Elem.h.
{
  // coder dans evbasreyconst comme entree_fluide ????
  flux=0  ;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 889 of file Eval_Diff_VDF_Elem.h.
References DoubleVect::size(), and Dirichlet::val_imp().
{
  int i = elem_(face,0);
  //  int j = elem(face,1);
  int k;
  double dist = Dist_norm_bord(face);
  if (i != -1)
    for (k=0; k<flux.size(); k++)
      flux(k) = la_cl.val_imp(face-num1,k)
                *surface(face)*porosite(face)*nu_1(i,k)/dist;
  else // j != -1
    for (k=0; k<flux.size(); k++)
      flux(k) = -la_cl.val_imp(face-num1,k)
                *surface(face)*(porosite(face)*nu_1(elem_(face,1),k))/dist;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Echange_global_impose & la_cl, int num1) const [inline]
Definition at line 611 of file Eval_Diff_VDF_Elem.h.
References Echange_impose_base::h_imp(), and Echange_impose_base::T_ext().
{
  double h = la_cl.h_imp(face-num1);
  double T_ext = la_cl.T_ext(face-num1);
  int i = elem_(face,0);
  //  int j = elem(face,1);
  double flux;
  if (i != -1)
    flux = h*T_ext*surface(face);
  else
    flux = -h*T_ext*surface(face);
  return flux;
}
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const [inline]
Definition at line 934 of file Eval_Diff_VDF_Elem.h.
References Process::exit().
{
  // coder dans evbasreyconst comme entree_fluide ????
  assert(0);
  Process::exit();
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
Definition at line 365 of file Eval_Diff_VDF_Elem.h.
References Dirichlet::val_imp().
{
  double T_imp = la_cl.val_imp(face-num1);
  int i = elem_(face,0);
  //  int j = elem(face,1);
  double dist = Dist_norm_bord(face);
  double flux;
  int ori = DERIVED_T::IS_ANISO ? orientation(face) : 0;
  if (i != -1)
    {
      flux = T_imp*surface(face)/dist;
      flux *= porosite(face)*nu_1(i,ori);
    }
  else   // j != -1
    {
      flux = -T_imp*surface(face)/dist;
      flux *= (porosite(face)*nu_1(elem_(face,1),ori));
    }
  return flux;
}
template<typename DERIVED_T> template<typename BC > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face (int , const BC & , int , DoubleVect &) const [inline]
Definition at line 214 of file Eval_Diff_VDF_Elem.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Elem< DERIVED_T >::secmem_faces_interne (int , DoubleVect & flux) const [inline]
Definition at line 1470 of file Eval_Diff_VDF_Elem.h.
References DoubleVect::size().
{
  int k;
  for ( k=0; k<flux.size(); k++)
    {
      flux(k)=0.;
    }
}
template<typename DERIVED_T > double Eval_Diff_VDF_Elem< DERIVED_T >::secmem_faces_interne (int) const [inline]
Definition at line 800 of file Eval_Diff_VDF_Elem.h.
{
  return 0;
}
Member Data Documentation
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_ANISO = false [static]
Reimplemented in Eval_Diff_VDF_var_Elem_aniso.
Definition at line 71 of file Eval_Diff_VDF_Elem.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_AXI = false [static]
Reimplemented in Eval_Diff_VDF_const_Elem_Axi, Eval_Diff_VDF_var_Elem_Axi, Eval_Diff_VDF_Multi_inco_const_Elem_Axi, Eval_Diff_VDF_Multi_inco_var_Elem_Axi, Eval_Dift_VDF_const_Elem_Axi, Eval_Dift_VDF_var_Elem_Axi, Eval_Dift_VDF_Multi_inco_const_Elem_Axi, and Eval_Dift_VDF_Multi_inco_var_Elem_Axi.
Definition at line 67 of file Eval_Diff_VDF_Elem.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_DEQUIV = false [static]
Reimplemented in Eval_Dift_VDF_const_Elem_Axi, Eval_Dift_VDF_var_Elem_Axi, Eval_Dift_VDF_Multi_inco_const_Elem_Axi, Eval_Dift_VDF_Multi_inco_const_Elem, Eval_Dift_VDF_Multi_inco_var_Elem_Axi, and Eval_Dift_VDF_Multi_inco_var_Elem.
Definition at line 68 of file Eval_Diff_VDF_Elem.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_MODIF_DEQ = false [static]
Reimplemented in Eval_Dift_VDF_const_Elem, and Eval_Dift_VDF_var_Elem.
Definition at line 69 of file Eval_Diff_VDF_Elem.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_MULTD = true [static]
Reimplemented in Eval_Diff_VDF_Multi_inco_const_Elem_Axi, Eval_Diff_VDF_Multi_inco_const_Elem, Eval_Diff_VDF_Multi_inco_var_Elem_Axi, Eval_Diff_VDF_Multi_inco_var_Elem, Eval_Dift_VDF_Multi_inco_const_Elem_Axi, Eval_Dift_VDF_Multi_inco_const_Elem, Eval_Dift_VDF_Multi_inco_var_Elem_Axi, and Eval_Dift_VDF_Multi_inco_var_Elem.
Definition at line 66 of file Eval_Diff_VDF_Elem.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Elem< DERIVED_T >::IS_QUASI = false [static]
Definition at line 70 of file Eval_Diff_VDF_Elem.h.
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Diff_VDF_Elem.h