TRUST: Porosites Class Reference
Porosites Class Reference
#include <Porosites.h>
Public Member Functions
Porosites ()
~Porosites ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Porosites & self_cast (Objet_U &)
static const Porosites & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 23 of file Porosites.h.
Constructor & Destructor Documentation
Porosites()
Porosites::Porosites ()
Definition at line 24 of file Porosites.cpp.
~Porosites()
Porosites::~Porosites ()
Definition at line 24 of file Porosites.cpp.
Member Function Documentation
cree_instance()
Objet_U * Porosites::cree_instance () static
Definition at line 24 of file Porosites.cpp.
duplique()
int Porosites::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Porosites.cpp.
get_info()
const Type_info * Porosites::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Porosites.cpp.
info()
const Type_info * Porosites::info () static
Definition at line 24 of file Porosites.cpp.
interpreter()
Entree & Porosites::interpreter (Entree & is) override virtual
Reimplemented from Interprete.
Definition at line 35 of file Porosites.cpp.
{
  int i;
  Nom nom_pb, nom_ss_zone;
  is >> nom_pb;
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "We waited an object of type Probleme_base" << finl;
      exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  is >> nom_ss_zone;
  if(! sub_type(Sous_Zone, objet(nom_ss_zone)))
    {
      Cerr << nom_ss_zone << " is of type " << objet(nom_ss_zone).que_suis_je() << finl;
      Cerr << "We waited an object of type Sous_Zone" << finl;
      exit();
    }
  Sous_Zone& ssz=ref_cast(Sous_Zone, objet(nom_ss_zone));
  double porosite_volu=1;
  DoubleVect porosites_surf;
  Param param(que_suis_je());
  param.ajouter("Volumique",&porosite_volu);
  param.ajouter("Surfacique",&porosites_surf);
  param.ajouter_condition("value_of_Volumique_gt_0","Volumic porosity must be greater than 0");
  param.lire_avec_accolades_depuis(is);
  double porsurfmin=porosites_surf.local_min_vect();
  if(porsurfmin<=0)
    {
      Cerr << "You entered a surfacic porosity <=0 " << finl;
      exit();
    }
  const Zone_dis& la_zone_dis = pb.equation(0).zone_dis();
  if (!la_zone_dis.non_nul())
    {
      Cerr << "You must have discretized the problem before defining the porosities" << finl;
      exit();
    }
// On passe par la zone_VF
  Zone_VF& zvf=ref_cast(Zone_VF, pb.equation(0).zone_dis().valeur());
  if (zvf.que_suis_je().debute_par("Zone_VEF"))
    {
      Cerr << "Porosites should no longer be used in VEF." << finl;
      Cerr << "Porosites_champ should be used instead." << finl;
      exit();
    }
  DoubleVect& porosite_elem = zvf.porosite_elem();
  DoubleVect& porosite_face = zvf.porosite_face();
  const IntTab& elem_faces = zvf.elem_faces();
  int nb_faces_elem = zvf.zone().nb_faces_elem();
  int elem;
  if( (porosite_volu!=1) && (porsurfmin!=1) )
    {
      for (i=0; i<ssz.nb_elem_tot(); i++)
        {
          elem = ssz(i);
          porosite_elem(elem)=porosite_volu;
          for (int j=0; j<nb_faces_elem; j++)
            {
              double norme_normale =0;
              int iii;
              for (iii=0; iii<dimension; iii++)
                norme_normale+=zvf.face_normales(elem_faces(elem, j),iii)*zvf.face_normales(elem_faces(elem, j),iii);
              porosite_face(elem_faces(elem, j))=0.;
              for (iii=0; iii<dimension; iii++)
                {
                  porosite_face(elem_faces(elem, j))+= porosites_surf(iii)*std::fabs(zvf.face_normales(elem_faces(elem, j),iii))
                                                       *std::fabs(zvf.face_normales(elem_faces(elem, j),iii))/norme_normale;
                }
            }
        }
    }
  else if(porosite_volu!=1)
    {
      Cerr << " The volumic porosities are used to calculate the surfacic porosities " << finl ;
      for (i=0; i<ssz.nb_elem_tot(); i++)
        {
          elem = ssz(i);
          porosite_elem(elem)=porosite_volu;
        }
      int nb_elem_tot = zvf.zone().nb_elem_tot();
      for (i=0; i<nb_elem_tot; i++)
        {
          for (int j=0; j<nb_faces_elem; j++)
            {
              int face_glob = elem_faces(i, j) ;
              int num_poly_vois = zvf.face_voisins(face_glob,1);
              int num_poly_vois1 = zvf.face_voisins(face_glob,0);
              if ((num_poly_vois != -1) && (num_poly_vois1 != -1))
                porosite_face(face_glob) = (porosite_elem(num_poly_vois1)+porosite_elem(num_poly_vois))/2. ;
              else porosite_face(face_glob) =  porosite_elem(i) ;
            }
        }
    }
  else if(porsurfmin!=1)
    {
      Cerr << " The surfacic porosities are used to calculate the volumic porosities " << finl ;
      for (i=0; i<ssz.nb_elem_tot(); i++)
        {
          elem = ssz(i);
          for (int j=0; j<nb_faces_elem; j++)
            {
              double norme_normale =0;
              int iii;
              for (iii=0; iii<dimension; iii++)
                norme_normale+=zvf.face_normales(elem_faces(elem, j),iii)*zvf.face_normales(elem_faces(elem, j),iii);
              porosite_face(elem_faces(elem, j))=0.;
              for (iii=0; iii<dimension; iii++)
                {
                  porosite_face(elem_faces(elem, j))+= porosites_surf(iii)*zvf.face_normales(elem_faces(elem, j),iii)
                                                       *zvf.face_normales(elem_faces(elem, j),iii)/norme_normale;
                }
            }
        }
    }
  return is;
}
References Param::ajouter(), Param::ajouter_condition(), Cerr, Nom::debute_par(), Objet_U::dimension, Zone_VF::elem_faces(), Probleme_base::equation(), Process::exit(), Zone_VF::face_normales(), Zone_VF::face_voisins(), finl, Param::lire_avec_accolades_depuis(), TRUSTVect< _TYPE_ >::local_min_vect(), Sous_Zone::nb_elem_tot(), Zone::nb_elem_tot(), Zone::nb_faces_elem(), O_U_Ptr::non_nul(), Interprete::objet(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Zone_dis_base::valeur(), Zone_dis_base::zone(), and Equation_base::zone_dis().
printOn()
Sortie & Porosites::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Porosites.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Porosites::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 31 of file Porosites.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Porosites & Porosites::self_cast (const Objet_U & r) static
Definition at line 24 of file Porosites.cpp.
self_cast() [2/2]
Porosites & Porosites::self_cast (Objet_U & r) static
Definition at line 24 of file Porosites.cpp.
taille_memoire()
unsigned Porosites::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Porosites.cpp.
Member Data Documentation
info_obj
const Type_info Porosites::info_obj static
Definition at line 25 of file Porosites.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Porosites.h
src/Kernel/Framework/Porosites.cpp