TRUST: Dirichlet Class Reference
Dirichlet Class Reference
classe Dirichlet
Cette classe est la classe de base de la hierarchie des conditions
aux limites de type Dirichlet.
Une condition aux limites de type Dirichlet impose la valeur
d'un champ inconnue sur une frontiere, ce qui correspond a:
- vitesse imposee pour l'equation de Navier-Stokes
- scalaire impose pour l'equation de transport d'un scalaire
#include <Dirichlet.h>
Public Member Functions
Dirichlet ()
~Dirichlet () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double val_imp (int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp (int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp_au_temps (double temps, int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
virtual double val_imp_au_temps (double temps, int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Dirichlet & self_cast (Objet_U &)
static const Dirichlet & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Dirichlet
Cette classe est la classe de base de la hierarchie des conditions
aux limites de type Dirichlet.
Une condition aux limites de type Dirichlet impose la valeur
d'un champ inconnue sur une frontiere, ce qui correspond a:
- vitesse imposee pour l'equation de Navier-Stokes
- scalaire impose pour l'equation de transport d'un scalaire
Definition at line 38 of file Dirichlet.h.
Constructor & Destructor Documentation
Dirichlet()
Dirichlet::Dirichlet ()
Definition at line 19 of file Dirichlet.cpp.
~Dirichlet()
Dirichlet::~Dirichlet () override
Definition at line 19 of file Dirichlet.cpp.
Member Function Documentation
get_info()
const Type_info * Dirichlet::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Dirichlet_paroi_defilante, Scalaire_impose_paroi, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Temperature_imposee_paroi_H, Dirichlet_entree_fluide, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Paroi_Knudsen_non_negligeable, Temperature_imposee_paroi, Entree_fluide_alpha_impose, and Echange_contact_Correlation_VEF.
Definition at line 19 of file Dirichlet.cpp.
info()
const Type_info * Dirichlet::info () static
Definition at line 19 of file Dirichlet.cpp.
printOn()
Sortie & Dirichlet::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Dirichlet_paroi_defilante, Scalaire_impose_paroi, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Temperature_imposee_paroi_H, Dirichlet_entree_fluide, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Paroi_Knudsen_non_negligeable, Temperature_imposee_paroi, Entree_fluide_alpha_impose, and Echange_contact_Correlation_VEF.
Definition at line 36 of file Dirichlet.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Dirichlet::readOn (Entree & s) override protected virtual
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Dirichlet_paroi_defilante, Scalaire_impose_paroi, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Temperature_imposee_paroi_H, Dirichlet_entree_fluide, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Paroi_Knudsen_non_negligeable, Temperature_imposee_paroi, Entree_fluide_alpha_impose, and Echange_contact_Correlation_VEF.
Definition at line 57 of file Dirichlet.cpp.
{
  return Cond_lim_base::readOn(s);
}
References Cond_lim_base::readOn().
Referenced by Scalaire_impose_paroi::readOn(), and Temperature_imposee_paroi::readOn().
self_cast() [1/2]
const Dirichlet & Dirichlet::self_cast (const Objet_U & r) static
Definition at line 19 of file Dirichlet.cpp.
self_cast() [2/2]
Dirichlet & Dirichlet::self_cast (Objet_U & r) static
Definition at line 19 of file Dirichlet.cpp.
val_imp() [1/2]
double Dirichlet::val_imp (int i) const virtual
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps par defaut du champ_front.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented in Entree_fluide_temperature_imposee_H, Temperature_imposee_paroi_H, and Entree_fluide_T_h_imposee.
Definition at line 78 of file Dirichlet.cpp.
{
  return val_imp_au_temps(le_champ_front->get_temps_defaut(),i);
}
References Cond_lim_base::le_champ_front, and val_imp_au_temps().
Referenced by Terme_Boussinesq_VDF_Face::ajouter_blocs(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Eval_Conv_VDF_Elem< DERIVED_T >::flux_face(), Eval_Diff_VDF_Elem< DERIVED_T >::flux_face(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face(), Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face(), and Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries().
val_imp() [2/2]
double Dirichlet::val_imp (int i, int j) const virtual
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps par defaut du champ_front.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented in Entree_fluide_temperature_imposee_H, Temperature_imposee_paroi_H, and Entree_fluide_T_h_imposee.
Definition at line 104 of file Dirichlet.cpp.
{
  return val_imp_au_temps(le_champ_front->get_temps_defaut(),i,j);
}
References Cond_lim_base::le_champ_front, and val_imp_au_temps().
val_imp_au_temps() [1/2]
double Dirichlet::val_imp_au_temps (double temps, int i) const virtual
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
Reimplemented in Frontiere_ouverte_rho_u_impose.
Definition at line 124 of file Dirichlet.cpp.
{
  const DoubleTab& tab=le_champ_front->valeurs_au_temps(temps);
  if (tab.size()==1)
    return tab(0,0);
  if (tab.line_size()==1)
    return tab(i,0);
  else
    Cerr << "Dirichlet::val_imp error" << finl;
  exit();
  return 0.;
}
References Cerr, Process::exit(), finl, Cond_lim_base::le_champ_front, TRUSTVect< _TYPE_ >::line_size(), and TRUSTVect< _TYPE_ >::size().
Referenced by Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and val_imp().
val_imp_au_temps() [2/2]
double Dirichlet::val_imp_au_temps (double temps, int i, int j) const virtual
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
Reimplemented in Frontiere_ouverte_rho_u_impose.
Definition at line 158 of file Dirichlet.cpp.
{
  const DoubleTab& tab=le_champ_front->valeurs_au_temps(temps);
  if (tab.dimension(0)==1)
    return tab(0,j);
  else
    return tab(i,j);
}
References TRUSTTab< _TYPE_ >::dimension(), and Cond_lim_base::le_champ_front.
verifie_ch_init_nb_comp()
void Dirichlet::verifie_ch_init_nb_comp () const override virtual
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented from Cond_lim_base.
Definition at line 167 of file Dirichlet.cpp.
{
  if (le_champ_front.non_nul())
    {
      const Equation_base& eq = zone_Cl_dis().equation();
      const int nb_comp = le_champ_front.valeur().nb_comp();
      eq.verifie_ch_init_nb_comp_cl(eq.inconnue(),nb_comp, *this);
    }
}
References MorEqn::equation(), Equation_base::inconnue(), Cond_lim_base::le_champ_front, Field_base::nb_comp(), O_U_Ptr::non_nul(), Deriv_Champ_front_base::valeur(), Equation_base::verifie_ch_init_nb_comp_cl(), and Cond_lim_base::zone_Cl_dis().
Member Data Documentation
info_obj
const Type_info Dirichlet::info_obj static
Definition at line 41 of file Dirichlet.h.
The documentation for this class was generated from the following files:
src/Kernel/Cond_Lim/Dirichlet.h
src/Kernel/Cond_Lim/Dirichlet.cpp