TRUST: Tetraedriser_par_prisme Class Reference
Tetraedriser_par_prisme Class Reference
Classe Tetra_par_prisme
Cette classe est un interprete qui sert a lire et executer
la directive Tetra_par_prisme:
Tetra_par_prisme nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage tetraedrique (par prismes) a partir d'un maillage constitue de paves.
#include <Tetraedriser_par_prisme.h>
Public Member Functions
Tetraedriser_par_prisme ()
~Tetraedriser_par_prisme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void trianguler (Zone &) const
Tetraedrise tous les elements d'une zone : transforme
les elements goemetriques de la zone en tetraedres IDENTIQUES
par la methode des prismes.
Pour l'instant on ne sait tetraedriser que des Hexaedre.
(on les coupe en 2).
Les elements sont tetraedrises et tous les bords
sont types en Triangle_3D.
virtual int dimension_application () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Tetraedriser_par_prisme & self_cast (Objet_U &)
static const
Tetraedriser_par_prisme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
Detailed Description
Classe Tetra_par_prisme
Cette classe est un interprete qui sert a lire et executer
la directive Tetra_par_prisme:
Tetra_par_prisme nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage tetraedrique (par prismes) a partir d'un maillage constitue de paves.
Definition at line 42 of file Tetraedriser_par_prisme.h.
Constructor & Destructor Documentation
Tetraedriser_par_prisme::Tetraedriser_par_prisme ()
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
Tetraedriser_par_prisme::~Tetraedriser_par_prisme ()
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
Member Function Documentation
Objet_U * Tetraedriser_par_prisme::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
int Tetraedriser_par_prisme::dimension_application () const [inline, virtual]
Implements Triangulation_base.
Definition at line 52 of file Tetraedriser_par_prisme.h.
{
  return 3;
}
int Tetraedriser_par_prisme::duplique () const [virtual]
Implements Triangulation_base.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
const Type_info * Tetraedriser_par_prisme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
const Type_info * Tetraedriser_par_prisme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
Sortie & Tetraedriser_par_prisme::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 43 of file Tetraedriser_par_prisme.cpp.
{
  return Interprete::printOn(os);
}
Entree & Tetraedriser_par_prisme::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 63 of file Tetraedriser_par_prisme.cpp.
{
  return Interprete::readOn(is);
}
const Tetraedriser_par_prisme & Tetraedriser_par_prisme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Triangulation_base.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
Tetraedriser_par_prisme & Tetraedriser_par_prisme::self_cast (Objet_U & r) [static]
Reimplemented from Triangulation_base.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
unsigned Tetraedriser_par_prisme::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Tetraedriser_par_prisme.cpp.
void Tetraedriser_par_prisme::trianguler (Zone & zone) const [virtual]
Tetraedrise tous les elements d'une zone : transforme
les elements goemetriques de la zone en tetraedres IDENTIQUES
par la methode des prismes.
Pour l'instant on ne sait tetraedriser que des Hexaedre.
(on les coupe en 2).
Les elements sont tetraedrises et tous les bords
sont types en Triangle_3D.
Implements Triangulation_base.
Definition at line 163 of file Tetraedriser_par_prisme.cpp.
References Cerr, decoupe(), IntTab::dimension(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), finl, Zone::les_elems(), LIST_CURSEUR, Interprete_geometrique_base::mettre_a_jour_sous_zone(), Objet_U::que_suis_je(), IntTab::ref(), Faces::triangle_3D, Zone::type_elem(), Faces::typer(), and Zone::typer().
{
  if(zone.type_elem()->que_suis_je() == "Hexaedre")
    {
      zone.typer("Tetraedre");
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      IntTab new_elems(6*oldsz, 4);
      for(int i=0; i< oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int i3=les_elems(i,3);
          int i4=les_elems(i,4);
          int i5=les_elems(i,5);
          int i6=les_elems(i,6);
          int i7=les_elems(i,7);
          {
            new_elems(i,0)=i0;
            new_elems(i,1)=i1;
            new_elems(i,2)=i2;
            new_elems(i,3)=i5;
            new_elems(i+oldsz,0)=i0;
            new_elems(i+oldsz,1)=i2;
            new_elems(i+oldsz,2)=i4;
            new_elems(i+oldsz,3)=i5;
            mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
            new_elems(i+2*oldsz,0)=i1;
            new_elems(i+2*oldsz,1)=i2;
            new_elems(i+2*oldsz,2)=i3;
            new_elems(i+2*oldsz,3)=i5;
            mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
            new_elems(i+3*oldsz,0)=i2;
            new_elems(i+3*oldsz,1)=i3;
            new_elems(i+3*oldsz,2)=i5;
            new_elems(i+3*oldsz,3)=i7;
            mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
            new_elems(i+4*oldsz,0)=i2;
            new_elems(i+4*oldsz,1)=i4;
            new_elems(i+4*oldsz,2)=i5;
            new_elems(i+4*oldsz,3)=i6;
            mettre_a_jour_sous_zone(zone,i,i+4*oldsz,1);
            new_elems(i+5*oldsz,0)=i2;
            new_elems(i+5*oldsz,1)=i5;
            new_elems(i+5*oldsz,2)=i6;
            new_elems(i+5*oldsz,3)=i7;
            mettre_a_jour_sous_zone(zone,i,i+5*oldsz,1);
          }
        }
      les_elems.ref(new_elems);
    }
  else
    {
      Cerr << "We do not yet know how to Tetraedriser_par_prisme the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
    while(curseur)
      {
        Faces& les_faces=curseur->faces();
        les_faces.typer(Faces::triangle_3D);
// decoupe(les_faces);
        decoupe(zone,les_faces);
        ++curseur;
      }
  }
  {
// Les Raccords
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
    while(curseur)
      {
        Faces& les_faces=curseur.valeur()->faces();
        les_faces.typer(Faces::triangle_3D);
// decoupe(les_faces);
        decoupe(zone,les_faces);
        ++curseur;
      }
  }
  {
// Les Faces internes
    LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
    while(curseur)
      {
        Faces& les_faces=curseur->faces();
        les_faces.typer(Faces::triangle_3D);
// decoupe(les_faces);
        decoupe(zone,les_faces);
        ++curseur;
      }
  }
}
Member Data Documentation
const Type_info Tetraedriser_par_prisme::info_obj [static]
Reimplemented from Triangulation_base.
Definition at line 44 of file Tetraedriser_par_prisme.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Tetraedriser_par_prisme.h
src/Kernel/Geometrie/Tetraedriser_par_prisme.cpp