TRUST: Format_Post_Med Class Reference
Format_Post_Med Class Reference
:
Classe de postraitement des champs euleriens au format med.
#include <Format_Post_Med.h>
Public Member Functions
~Format_Post_Med ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
void set_param (Param &param) override
int initialize_by_default (const Nom &file_basename) override
Initialisation de la classe avec des parametres par
defaut.
int initialize (const Nom &file_basename, const int format, const Nom &option_para) override
int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override
int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post) override
int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override
int finir (int &est_le_dernier_post) override
int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post) override
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post) override
voir Format_Post_base::ecrire_domaine
int ecrire_temps (const double temps) override
commence l'ecriture d'un nouveau pas de temps
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx" si ce temps n'a pas encore ete ecrit
int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data) override
voir Format_Post_base::ecrire_champ
int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size) override
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
Format_Post_Med ()
Constructeur par defaut:
Public Member Functions inherited from Format_Post_base
Format_Post_base ()
~Format_Post_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()=0
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int initialize_by_default (const Nom &file_basename)
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
virtual int initialize (const Nom &file_basename, const int format, const Nom &option_para)
virtual int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit)
virtual int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post)
virtual int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post)
virtual int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init)
virtual int test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat)
virtual int init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine &domaine)
virtual int finir_ecriture (double temps_courant)
virtual int finir (int &est_le_dernier_post)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
virtual int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post)
virtual int ecrire_temps (const double temps)
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
virtual int ecrire_champ2 (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data, const DoubleTab &coord)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
void postraiter_debug_valeurs_un_instant (const Nom &nom_fich, const Domaine &dom, const Zone_dis_base &zone_dis, double temps_champ, double temps_courant, const Nom &id_champ_post, const Nature_du_champ &nature_champ, const Noms &noms_compos, const Noms &unites, const Motcle &loc_post, const DoubleTab &data, int ncomp=-1, int axi=0, int champ=1, int stat=0, double dt_ch=1., double dt_stat=1., int reprise=0, int est_le_premier_post=1, int est_le_dernier_post=1, double t_init=0., double temps_post=-2)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Format_Post_Med & self_cast (Objet_U &)
static const Format_Post_Med & self_cast (const Objet_U &)
Static Public Member Functions inherited from Format_Post_base
static const Type_info * info ()
static Format_Post_base & self_cast (Objet_U &)
static const Format_Post_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Format_Post_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier filename_sans_extension
}.
virtual int ecrire_domaine_med (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const Nom &nom_fic, const int est_le_premier_post, Nom &nom_fich)
virtual int ecrire_temps_med (const double temps, Nom &nom_fich)
virtual int ecrire_champ_med (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, const Nom &nom_pdb, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const DoubleTab &data, Nom &nom_fich)
virtual int ecrire_entete_med (Nom &nom_fic, const int est_le_premier_post)
virtual int finir_med (Nom &nom_fic, int &est_le_dernier_post)
virtual int completer_post_med (const Nom &nom_fich2, const Nom &nom1, const Nom &nom2)
virtual int preparer_post_med (const Nom &nom_fich1, const Nom &nom_fich2, const Nom &nom_fich3, const Nom &id_du_domaine, const int est_le_premier_post)
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom med_basename_
EcrMED ecr_med
Detailed Description
:
Classe de postraitement des champs euleriens au format med.
Definition at line 51 of file Format_Post_Med.h.
Constructor & Destructor Documentation
~Format_Post_Med()
Format_Post_Med::~Format_Post_Med ()
Definition at line 22 of file Format_Post_Med.cpp.
Format_Post_Med()
Format_Post_Med::Format_Post_Med ()
Constructeur par defaut:
Definition at line 40 of file Format_Post_Med.cpp.
{
  reset();
}
References reset().
Member Function Documentation
completer_post()
int Format_Post_Med::completer_post (const Domaine & dom, const int axi, const Nature_du_champ & nature, const int nb_compo, const Noms & noms_compo, const Motcle & loc_post, const Nom & le_nom_champ_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 117 of file Format_Post_Med.cpp.
{
  return 1;
  Nom nom_fich2(med_basename_);
  Nom format="med";
  nom_fich2 += ".";
  nom_fich2 += format;
  nom_fich2 += ".med1";
  Nom nom1(le_nom_champ_post);
  nom1 += "_";
  Nom nom2(Nom(loc_post).majuscule());
  nom1 += nom2;
  Nom nom_post(le_nom_champ_post);
  if (loc_post=="SOM")
    {
      nom_post.prefix(dom.le_nom());
      nom_post.prefix("_som_");
      nom_post.prefix("_SOM_");
    }
  else if (loc_post=="ELEM")
    {
      nom_post.prefix(dom.le_nom());
      nom_post.prefix("_ELEM_");
      nom_post.prefix("_elem_");
    }
  else if (loc_post=="FACES")
    {
      nom_post.prefix(dom.le_nom());
      nom_post.prefix("_FACES_");
      nom_post.prefix("_faces_");
    }
  nom_post+="_";
  nom_post+=nom2;
  completer_post_med(nom_fich2,nom_post,nom2);
  return 1;
}
References completer_post_med(), Domaine::le_nom(), med_basename_, and Nom::prefix().
completer_post_med()
int Format_Post_Med::completer_post_med (const Nom & nom_fich2, const Nom & nom1, const Nom & nom2) protected virtual
Definition at line 338 of file Format_Post_Med.cpp.
{
  if (je_suis_maitre())
    {
      SFichier file;
      file.ouvrir(nom_fich2,ios::app);
      file <<nom1<<" "<<nom2<<finl;
    }
  return 1;
}
References finl, Process::je_suis_maitre(), and Sortie_Fichier_base::ouvrir().
Referenced by completer_post().
cree_instance()
Objet_U * Format_Post_Med::cree_instance () static
Definition at line 22 of file Format_Post_Med.cpp.
duplique()
int Format_Post_Med::duplique () const override virtual
Implements Objet_U.
Reimplemented in Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 22 of file Format_Post_Med.cpp.
ecrire_champ()
int Format_Post_Med::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) override virtual
voir Format_Post_base::ecrire_champ
Reimplemented from Format_Post_base.
Definition at line 232 of file Format_Post_Med.cpp.
{
// Attention au sens du compteur
  Nom nom_fich_index(med_basename_);
  nom_fich_index +=".";
  Nom format="med";
  nom_fich_index += format;
  nom_fich_index += ".index";
  Nom nom_fich_ecrit(med_basename_);
  nom_fich_ecrit += ".";
  nom_fich_ecrit += format;
  ecrire_champ_med(domaine,unite_,noms_compo,ncomp,temps_,nom_fich_ecrit,id_champ,id_du_domaine,localisation,valeurs,nom_fich_index);
  return 1;
}
References ecrire_champ_med(), and med_basename_.
Referenced by Champ_front_contact_VEF::connectivity_failed().
ecrire_champ_med()
int Format_Post_Med::ecrire_champ_med (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, const Nom & nom_pdb, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const DoubleTab & data, Nom & nom_fich) protected virtual
Definition at line 428 of file Format_Post_Med.cpp.
{
// compteur est declare en variable locale car toujours fixe a 1
  int compteur;
  Nom fic = nom_pdb.nom_me(me());
// Ce compteur est en fait anciennement passe sous est_le_premier_post_pour_nom_fich_
// et n est pas reellement utilise
  compteur = 1;
  Nom nom_post(id_du_champ);
  Noms noms_compo_courts(noms_compo);
  if (ncomp != -1)
    {
      nom_post = noms_compo[ncomp];
    }
  nom_post.prefix(dom.le_nom());
  Nom nom_dom="";
  for (int i = 0; i < noms_compo.size(); ++i)
    noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getPrefix(dom.le_nom());
  if (loc_post == "SOM")
    {
      nom_post.prefix("_som_");
      nom_post.prefix("_SOM_");
      nom_dom = dom.le_nom();
      for (int i = 0; i < noms_compo.size(); ++i)
        noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getPrefix("_SOM_");
    }
  else if (loc_post == "ELEM")
    {
      nom_post.prefix("_ELEM_");
      nom_post.prefix("_elem_");
      nom_dom = dom.le_nom();
      for (int i = 0; i < noms_compo.size(); ++i)
        noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getPrefix("_ELEM_");
    }
  else if (loc_post == "FACES")
    {
#ifdef MEDCOUPLING_
      nom_post.prefix("_FACES_");
      nom_post.prefix("_faces_");
      nom_dom = dom.getUFacesMesh()->getName();
      for (int i = 0; i < noms_compo.size(); ++i)
        noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getPrefix("_FACES_");
#else
      Cerr << "Post-processing in med format on faces needs MEDCoupling" << finl;
#endif
    }
  if (je_suis_maitre())
    {
// Ouverture du fichier
      SFichier os;
      os.ouvrir(nom_fich, ios::app);
      os << "champ: " << nom_post << " " << nom_dom << " " << loc_post << finl;
    }
  Nom type_elem = dom.zone(0).type_elem()->que_suis_je();
// modif noms compo
  for (int i = 0; i < noms_compo.size(); ++i)
    noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getSuffix(nom_post);
  if (loc_post == "SOM")
    ecr_med.ecrire_champ("CHAMPPOINT", fic, dom, id_du_champ, valeurs, unite_, noms_compo_courts, type_elem, temps_, compteur);
  else if (loc_post == "ELEM")
    ecr_med.ecrire_champ("CHAMPMAILLE", fic, dom, id_du_champ, valeurs, unite_, noms_compo_courts, type_elem, temps_, compteur);
  else if (loc_post == "FACES")
    ecr_med.ecrire_champ("CHAMPFACES", fic, dom, id_du_champ, valeurs, unite_, noms_compo_courts, type_elem, temps_, compteur);
  else
    {
      Cerr << "We do not know to postprocess " << id_du_champ
           << " with the keyword " << loc_post << finl;
      return -1;
    }
  return 1;
}
References Cerr, compteur, ecr_med, EcrMED::ecrire_champ(), finl, Nom::getPrefix(), Nom::getSuffix(), Process::je_suis_maitre(), Domaine::le_nom(), Process::me(), Nom::nom_me(), Sortie_Fichier_base::ouvrir(), Nom::prefix(), Objet_U::que_suis_je(), vect_impl::size(), Zone::type_elem(), type_elem(), and Domaine::zone().
Referenced by ecrire_champ().
ecrire_domaine()
int Format_Post_Med::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) override virtual
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
Reimplemented from Format_Post_base.
Definition at line 188 of file Format_Post_Med.cpp.
{
  const REF(Zone_dis_base) zone_dis_base;
  return ecrire_domaine_dis(domaine, zone_dis_base, est_le_premier_post);
}
References ecrire_domaine_dis(), and REF.
Referenced by Champ_front_contact_VEF::connectivity_failed().
ecrire_domaine_dis()
int Format_Post_Med::ecrire_domaine_dis (const Domaine & domaine, const Ref_Zone_dis_base & zone_dis_base, const int est_le_premier_post) override virtual
voir Format_Post_base::ecrire_domaine
< ok tout va bien
Reimplemented from Format_Post_base.
Definition at line 196 of file Format_Post_Med.cpp.
{
  Nom nom_fich(med_basename_);
  nom_fich +=".";
  Nom format="med";
  nom_fich += format;
  nom_fich += ".index";
  Nom nom_fic_base(med_basename_);
  nom_fic_base += ".";
  nom_fic_base += format;
  Nom nom_fic=nom_fic_base.nom_me(Process::me());
  ecrire_domaine_med(domaine,zone_dis_base,nom_fic,est_le_premier_post,nom_fich);
  return 1; //!< ok tout va bien
}
References ecrire_domaine_med(), Process::me(), med_basename_, and Nom::nom_me().
Referenced by ecrire_domaine().
ecrire_domaine_med()
int Format_Post_Med::ecrire_domaine_med (const Domaine & domaine, const Ref_Zone_dis_base & zone_dis_base, const Nom & nom_fic, const int est_le_premier_post, Nom & nom_fich) protected virtual
Definition at line 395 of file Format_Post_Med.cpp.
{
  int dim = domaine.les_sommets().dimension(1);
  int mode=-1;
  if (est_le_premier_post==0)  mode=0;
  if (je_suis_maitre())
    {
      SFichier s;
      s.ouvrir(nom_fich, ios::app);
      s << "format MED: " << ecr_med.version() << finl;
      s << "dimension: " << dim << finl;
      s << "domaine: " << domaine.le_nom() << finl;
      s << "nb_proc: " << Process::nproc() << finl;
      Cerr << "Opening MED file " << nom_fic << " with " << ecr_med.version() << " format. ";
      if (!ecr_med.getMajorMode()) Cerr << "Try using med_major format if you have issue when opening this file with older Salome versions.";
      Cerr << finl;
    }
  ecr_med.ecrire_domaine_dis(nom_fic,domaine,zone_dis_base,domaine.le_nom(),mode);
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), ecr_med, EcrMED::ecrire_domaine_dis(), finl, EcrMED::getMajorMode(), Process::je_suis_maitre(), Domaine::le_nom(), Domaine::les_sommets(), Process::nproc(), Sortie_Fichier_base::ouvrir(), and EcrMED::version().
Referenced by ecrire_domaine_dis().
ecrire_entete()
int Format_Post_Med::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 93 of file Format_Post_Med.cpp.
{
  Nom nom_fich(med_basename_);
  nom_fich +=".";
  Nom format="med";
  nom_fich += format;
  nom_fich += ".index";
  ecrire_entete_med(nom_fich,est_le_premier_post);
  return 1;
}
References ecrire_entete_med(), and med_basename_.
ecrire_entete_med()
int Format_Post_Med::ecrire_entete_med (Nom & nom_fic, const int est_le_premier_post) protected virtual
Definition at line 272 of file Format_Post_Med.cpp.
{
  if (est_le_premier_post && Process::je_suis_maitre())
    {
      SFichier s(nom_fich);
      s << "Trio_U" << " " << "Version "  << "1" << finl;
      s << nom_du_cas() << finl;
      s << "Trio_U" << finl;
    }
  return 1;
}
References finl, Process::je_suis_maitre(), and Objet_U::nom_du_cas().
Referenced by ecrire_entete().
ecrire_item_int()
int Format_Post_Med::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_zone, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) override virtual
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
Reimplemented from Format_Post_base.
Definition at line 260 of file Format_Post_Med.cpp.
{
  return 1;
}
ecrire_temps()
int Format_Post_Med::ecrire_temps (const double temps) override virtual
commence l'ecriture d'un nouveau pas de temps
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx" si ce temps n'a pas encore ete ecrit
Reimplemented from Format_Post_base.
Definition at line 217 of file Format_Post_Med.cpp.
{
  Nom nom_fich(med_basename_);
  nom_fich +=".";
  Nom format="med";
  nom_fich += format;
  nom_fich += ".index";
  ecrire_temps_med(temps,nom_fich);
  return 1;
}
References ecrire_temps_med(), and med_basename_.
ecrire_temps_med()
int Format_Post_Med::ecrire_temps_med (const double temps, Nom & nom_fich) protected virtual
Definition at line 417 of file Format_Post_Med.cpp.
{
  if (je_suis_maitre())
    {
      SFichier s;
      s.ouvrir(nom_fich,ios::app);
      s << "TEMPS " << temps << finl;
    }
  return 1;
}
References finl, Process::je_suis_maitre(), and Sortie_Fichier_base::ouvrir().
Referenced by ecrire_temps().
finir()
int Format_Post_Med::finir (int & est_le_dernier_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 107 of file Format_Post_Med.cpp.
{
  Nom nom_fic_base(med_basename_);
  nom_fic_base += ".med";
  Nom nom_fic=nom_fic_base.nom_me(Process::me());
  Cerr << "MED file " << nom_fic << " closed. See .index file for more infos." << finl;
  return 1;
}
References Cerr, finl, Process::me(), med_basename_, and Nom::nom_me().
finir_med()
int Format_Post_Med::finir_med (Nom & nom_fic, int & est_le_dernier_post) protected virtual
Definition at line 285 of file Format_Post_Med.cpp.
{
//
  Nom nom_fichier_base = nom_fich;
  nom_fichier_base.prefix(".med.index");
  Nom nom_fichier(nom_fichier_base);
  Nom format = "med";
  nom_fichier += ".";
  nom_fichier += format;
  if (est_le_dernier_post)
    {
      if (je_suis_maitre())
        {
// on veut concatainer les 3 fichiers
          SFichier file3(nom_fichier+".data");
          SFichier file("postmed.data");
          for (int i=0; i<3; i++)
            {
              Nom num(i);
              Nom fic2(nom_fichier);
              fic2+=".med";
              fic2+=num;
              {
                EFichier file2(fic2);
                Nom motlu;
                file2>>motlu;
                while (!file2.eof())
                  {
                    file<<motlu<<" "<<finl;
                    if (motlu!="#")
                      file3<<motlu<<" "<<finl;
                    file2>>motlu;
                  }
              }
            }
        }
      if (Process::je_suis_maitre())
        {
          SFichier s;
          s.ouvrir(nom_fich,ios::app);
          s << "FIN" << finl;
        }
    }
  return 1;
}
References Entree_Fichier_base::eof(), finl, Process::je_suis_maitre(), nom_fichier(), Sortie_Fichier_base::ouvrir(), and Nom::prefix().
get_info()
const Type_info * Format_Post_Med::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 22 of file Format_Post_Med.cpp.
info()
const Type_info * Format_Post_Med::info () static
Definition at line 22 of file Format_Post_Med.cpp.
initialize()
int Format_Post_Med::initialize (const Nom & file_basename, const int format, const Nom & option_para) override virtual
Reimplemented from Format_Post_base.
Definition at line 86 of file Format_Post_Med.cpp.
{
  med_basename_= file_basename;
  return 1;
}
References med_basename_.
initialize_by_default()
int Format_Post_Med::initialize_by_default (const Nom & file_basename) override virtual
Initialisation de la classe avec des parametres par
defaut.
Reimplemented from Format_Post_base.
Definition at line 79 of file Format_Post_Med.cpp.
{
  med_basename_= file_basename;
  return 1;
}
References med_basename_.
Referenced by Champ_front_contact_VEF::connectivity_failed().
preparer_post()
int Format_Post_Med::preparer_post (const Nom & id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override virtual
Reimplemented from Format_Post_base.
Definition at line 160 of file Format_Post_Med.cpp.
{
  return 1;
  Nom nom_fich1(med_basename_);
  Nom nom_fich2(med_basename_);
  Nom nom_fich3(med_basename_);
  Nom format="med";
  nom_fich1 += ".";
  nom_fich1 += format;
  nom_fich1 += ".med0";
  nom_fich2 += ".";
  nom_fich2 += format;
  nom_fich2 += ".med1";
  nom_fich3 += ".";
  nom_fich3 += format;
  nom_fich3 += ".med2";
  preparer_post_med(nom_fich1,nom_fich2,nom_fich3,id_du_domaine,est_le_premier_post);
  return 1;
}
References med_basename_, and preparer_post_med().
preparer_post_med()
int Format_Post_Med::preparer_post_med (const Nom & nom_fich1, const Nom & nom_fich2, const Nom & nom_fich3, const Nom & id_du_domaine, const int est_le_premier_post) protected virtual
Definition at line 351 of file Format_Post_Med.cpp.
{
  Nom nom_fich(nom_fich1);
  nom_fich.prefix(".med0");
  if (je_suis_maitre())
    {
      if (est_le_premier_post)
        {
          SFichier file(nom_fich1);
          file<<"{ Dimension "<<dimension<<finl<<"# export Domaine "<<id_du_domaine<<finl;
        }
      else
        {
          SFichier file(nom_fich1,ios::app);
          file<<" export Domaine "<<id_du_domaine<<finl;
        }
      SFichier file;
      if (est_le_premier_post)
        {
          file.ouvrir(nom_fich2);
          file<<"# \n Pbc_MED pbmed\n Lire pbmed { "<<finl;
        }
      else
        {
          file.ouvrir(nom_fich2,ios::app);
          file<<"} } } , "<<finl;
        }
      file<<nom_fich<<" "<<id_du_domaine<<"  { Postraitement { Champs dt_post 1e-9 {"<<finl;
      if (est_le_premier_post)
        {
          SFichier file2(nom_fich3);
          file2<<"} } } } }"<<finl;
        }
    }
  return 1;
}
References Objet_U::dimension, finl, Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), and Nom::prefix().
Referenced by preparer_post().
printOn()
Sortie & Format_Post_Med::printOn (Sortie & x) const override protected virtual
erreur => exit
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 54 of file Format_Post_Med.cpp.
{
  Cerr << "Format_Post_Meshtv::printOn : error" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Format_Post_Med::readOn (Entree & is) override protected virtual
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier filename_sans_extension
}.
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 66 of file Format_Post_Med.cpp.
{
  Format_Post_base::readOn(is);
  return is;
}
References Format_Post_base::readOn().
Referenced by Format_Post_Med_major::readOn(), and Format_Post_Medfile::readOn().
reset()
void Format_Post_Med::reset () override virtual
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
Implements Format_Post_base.
Definition at line 47 of file Format_Post_Med.cpp.
{
  med_basename_ = "??";
  ecr_med.setMajorMode(false);
}
References ecr_med, med_basename_, and EcrMED::setMajorMode().
Referenced by Format_Post_Med().
self_cast() [1/2]
const Format_Post_Med & Format_Post_Med::self_cast (const Objet_U & r) static
Definition at line 22 of file Format_Post_Med.cpp.
self_cast() [2/2]
Format_Post_Med & Format_Post_Med::self_cast (Objet_U & r) static
Definition at line 22 of file Format_Post_Med.cpp.
set_param()
void Format_Post_Med::set_param (Param & param) override virtual
Implements Format_Post_base.
Definition at line 72 of file Format_Post_Med.cpp.
{
  param.ajouter("nom_fichier",&med_basename_,Param::REQUIRED);
}
References Param::ajouter(), med_basename_, and Param::REQUIRED.
taille_memoire()
unsigned Format_Post_Med::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Format_Post_Med_major, and Format_Post_Medfile.
Definition at line 22 of file Format_Post_Med.cpp.
Member Data Documentation
ecr_med
EcrMED Format_Post_Med::ecr_med protected
Definition at line 90 of file Format_Post_Med.h.
Referenced by ecrire_champ_med(), ecrire_domaine_med(), Format_Post_Med_major::Format_Post_Med_major(), Format_Post_Medfile::Format_Post_Medfile(), and reset().
info_obj
const Type_info Format_Post_Med::info_obj static
Definition at line 53 of file Format_Post_Med.h.
med_basename_
Nom Format_Post_Med::med_basename_ protected
Definition at line 77 of file Format_Post_Med.h.
Referenced by completer_post(), ecrire_champ(), ecrire_domaine_dis(), ecrire_entete(), ecrire_temps(), finir(), initialize(), initialize_by_default(), preparer_post(), reset(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Format_Post_Med.h
src/Kernel/MEDimpl/Format_Post_Med.cpp