TRUST: Schema_Comm Class Reference
Schema_Comm Class Reference
#include <Schema_Comm.h>
Public Member Functions
Schema_Comm ()
Construction d'un nouveau schema de communication.
Schema_Comm (const Schema_Comm &)
Constructeur par copie (nouveau schema place en mode RESET).
Attention : tous les membres du Comm_Group doivent executer
cette fonction simultanement.
~Schema_Comm ()
Destruction d'un schema de communication.
void set_group (const Comm_Group &group)
Obsolete.
const Comm_Group & get_group () const
Renvoie le groupe auquel est associe le schema.
const Schema_Comm & operator= (const Schema_Comm &)
Operateur copie : on copie la liste des processeurs qui
communiquent. Le nouveau schema est place dans l'etat RESET.
Attention : tous les membres du Comm_Group doivent executer
cette fonction simultanement.
void set_send_recv_pe_list (const ArrOfInt &send_pe_list, const ArrOfInt &recv_pe_list, const int me_to_me=0)
Definit la liste des processeurs a qui on va envoyer
et de qui on va recevoir des donnees.
Si me_to_me est non nul, on autorise l'envoi des messages a soi-meme,
sinon non (argument optionnel : par defaut, me_to_me=0)
void begin_comm () const
Statut passe a WRITING Autorise si status_ == WRITING:
Sortie & send_buffer (int num_PE) const
renvoie le buffer correspondant au processeur num_PE pour
y entasser des donnees a envoyer. Le schema doit etre dans l'etat WRITING.
void echange_taille_et_messages () const
Statut passe a EXCHANGED.
void echange_messages (const ArrOfInt &recv_size) const
Statut passe a EXCHANGED Autorise si status_ == EXCHANGED:
Entree & recv_buffer (int num_PE) const
renvoie le buffer correspondant au processeur num_PE pour
y lire les donnees recues. Le schema doit etre dans l'etat EXCHANGED.
void end_comm () const
Statut passe a RESET Accesseurs:
const ArrOfInt & get_send_pe_list () const
const ArrOfInt & get_recv_pe_list () const
void set_all_to_allv_flag (int x)
Protected Types
enum Static_Status { UNINITIALIZED , RESET , WRITING , EXCHANGED }
Protected Member Functions
void echange_taille (const ArrOfInt &send_size, ArrOfInt &recv_size) const
Transmet la taille des messages a envoyer aux processeurs qui
vont les recevoir. La taille est le nombre de bytes des obuffers.
send_pe_list et recv_pe_list doivent etre initialises.
Le schema doit etre dans l'etat WRITING.
void echange_messages (const ArrOfInt &send_size, const ArrOfInt &recv_size) const
Cette methode lance l'echange de donnees entre tous les processeurs.
La taille des messages recus doit etre deja connue.
Le schema passe de WRITING a EXCHANGED.
void check_send_recv_pe_list () const
Verifie que les send/recv_pe_list verifient la propriete
"tu m'ecoutes quand je te parle".
Static Protected Member Functions
static OutputCommBuffer & obuffer (int pe)
Accesseur a un membre du tableau obuffers_ (avec verification)
static InputCommBuffer & ebuffer (int pe)
Accesseur a un membre du tableau ebuffers_ (avec verification)
Protected Attributes
ArrOfInt send_pe_list_
Liste des processeurs a qui envoyer.
ArrOfInt recv_pe_list_
Liste des processeurs de qui recevoir.
int me_to_me_
Drapeau: est-ce qu'on autorise a s'envoyer des messages a soi ?
Ref_Comm_Group ref_group_
Groupe de processeurs qui vont discuter.
int use_all_to_allv_
Drapeau, quel type de communication faut-il utiliser ?
Static Protected Attributes
static Static_Status status_ = UNINITIALIZED
Static Private Attributes
static InOutCommBuffers buffers_
static int n_buffers_ = 0
Detailed Description
Definition at line 76 of file Schema_Comm.h.
Member Enumeration Documentation
Static_Status
enum Schema_Comm::Static_Status protected
Enumerator
UNINITIALIZED
RESET
WRITING
EXCHANGED
Definition at line 114 of file Schema_Comm.h.
{ UNINITIALIZED, RESET, WRITING, EXCHANGED };
Constructor & Destructor Documentation
Schema_Comm() [1/2]
Schema_Comm::Schema_Comm ()
Construction d'un nouveau schema de communication.
Definition at line 55 of file Schema_Comm.cpp.
{
  send_pe_list_.set_smart_resize(1);
  recv_pe_list_.set_smart_resize(1);
  me_to_me_ = 0;
  use_all_to_allv_ = 0;
// Pour verifier plus tard qu'on est toujours dans le bon groupe,
// on conserve une ref au groupe courant.
  ref_group_ = PE_Groups::current_group();
  if (status_ == UNINITIALIZED)
    {
      n_buffers_ = Process::nproc();
      buffers_.obuffers_ = new OutputCommBuffer[n_buffers_];
      buffers_.ebuffers_ = new InputCommBuffer[n_buffers_];
      status_ = RESET;
    }
}
References buffers_, PE_Groups::current_group(), InOutCommBuffers::ebuffers_, me_to_me_, n_buffers_, Process::nproc(), InOutCommBuffers::obuffers_, recv_pe_list_, ref_group_, RESET, send_pe_list_, TRUSTArray< _TYPE_ >::set_smart_resize(), status_, UNINITIALIZED, and use_all_to_allv_.
Schema_Comm() [2/2]
Schema_Comm::Schema_Comm (const Schema_Comm & schema)
Constructeur par copie (nouveau schema place en mode RESET).
Attention : tous les membres du Comm_Group doivent executer
cette fonction simultanement.
Definition at line 83 of file Schema_Comm.cpp.
{
  send_pe_list_.set_smart_resize(1);
  recv_pe_list_.set_smart_resize(1);
  operator= (schema);
}
References operator=(), recv_pe_list_, send_pe_list_, and TRUSTArray< _TYPE_ >::set_smart_resize().
~Schema_Comm()
Schema_Comm::~Schema_Comm ()
Destruction d'un schema de communication.
Definition at line 75 of file Schema_Comm.cpp.
{
}
Member Function Documentation
begin_comm()
void Schema_Comm::begin_comm () const
Statut passe a WRITING Autorise si status_ == WRITING:
Reserve les buffers de comm pour une nouvelle communication.
Le schema passe de RESET a WRITING, on a maintenant le droit
d'appeler send_buffer(). Interdiction d'appeler a nouveau begin_comm
sur tous les objets de comm avant d'avoir fini cette communication
avec end_comm().
Definition at line 158 of file Schema_Comm.cpp.
{
// On verifie qu'une autre communication n'est pas en cours.
  assert (status_ == RESET && ref_group_.non_nul());
  status_ = WRITING;
// On verifie que tous les membres du groupe executent ceci.
// Si ca plante ici, c'est que tous les membres declares ne sont
// pas en train de faire la barriere.
  const Comm_Group& group = ref_group_.valeur();
  assert(&group == &PE_Groups::current_group());
  if (group.check_enabled()) group.barrier(BEGIN_COMM_TAG);
}
References Comm_Group::barrier(), BEGIN_COMM_TAG, Comm_Group::check_enabled(), PE_Groups::current_group(), O_U_Ptr::non_nul(), ref_group_, RESET, status_, Ref_Comm_Group::valeur(), and WRITING.
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
check_send_recv_pe_list()
void Schema_Comm::check_send_recv_pe_list () const protected
Verifie que les send/recv_pe_list verifient la propriete
"tu m'ecoutes quand je te parle".
Definition at line 541 of file Schema_Comm.cpp.
{
  assert(status_ == RESET);
// On verifie que les indices de processeurs sont dans le groupe
  int fail1 = 0;
  const int np = Process::nproc();
  const int n1 = send_pe_list_.size_array();
  int i;
  for (i = 0; i < n1; i++)
    if (send_pe_list_[i] < 0 || send_pe_list_[i] >= np)
      fail1 = 1;
  const int n2 = recv_pe_list_.size_array();
  for (i = 0; i < n2; i++)
    if (recv_pe_list_[i] < 0 || recv_pe_list_[i] >= np)
      fail1 = 1;
  int fail2 = 0;
  ArrOfInt recv_list;
  if (!fail1)
    {
      reverse_send_recv_pe_list(send_pe_list_, recv_list);
// Le tableau recv_pe_list_ n'est pas forcement trie alors que recv_list l'est toujours
// On trie avant de comparer
      ArrOfInt copie(recv_pe_list_);
      copie.ordonne_array();
      fail2 = !(recv_list == copie);
    }
  if (Process::mp_sum(fail1+fail2))
    {
      if (Process::je_suis_maitre())
        Cerr << "Error in Schema_Comm::check_send_recv_pe_list(), see .log files" << finl;
      Process::Journal() << "Error in Schema_Comm::check_send_recv_pe_list() :\n"
                         << "send_list:\n" << send_pe_list_
                         << "recv_list:\n" << recv_pe_list_;
      if (fail1)
        Process::Journal() << "processor ranks not in current group: current group size = " << np;
      else if (fail2)
        Process::Journal() << "recv_list should be this one:\n" << recv_list << finl;
      else
        Process::Journal() << "OK on this processor" << finl;
      Process::barrier();
      Process::exit();
    }
}
References Process::barrier(), Cerr, Process::exit(), finl, Process::je_suis_maitre(), Process::Journal(), Process::mp_sum(), Process::nproc(), TRUSTArray< _TYPE_ >::ordonne_array(), recv_pe_list_, RESET, reverse_send_recv_pe_list(), send_pe_list_, TRUSTArray< _TYPE_ >::size_array(), and status_.
Referenced by set_send_recv_pe_list().
ebuffer()
InputCommBuffer & Schema_Comm::ebuffer (int pe) inline static protected
Accesseur a un membre du tableau ebuffers_ (avec verification)
Definition at line 40 of file Schema_Comm.cpp.
{
  assert(pe >= 0 && pe < n_buffers_);
  return buffers_.ebuffers_[pe];
}
References buffers_, InOutCommBuffers::ebuffers_, and n_buffers_.
Referenced by echange_messages(), end_comm(), and recv_buffer().
echange_messages() [1/2]
void Schema_Comm::echange_messages (const ArrOfInt & recv_size) const
Statut passe a EXCHANGED Autorise si status_ == EXCHANGED:
Cette methode lance l'echange de donnees. On fournit la taille en octets
des messages recus dans recv_size (tableau de la meme taille que recv_pe_list)
En mode check_enabled, on verifie que la taille est correcte.
Definition at line 395 of file Schema_Comm.cpp.
{
  const int n_send = send_pe_list_.size_array();
  ArrOfInt send_size(n_send);
  int i;
  for (i = 0; i < n_send; i++)
    {
      int pe = send_pe_list_[i];
      send_size[i] = obuffer(pe).get_buffer_size();
    }
  if (PE_Groups::current_group().check_enabled())
    {
      ArrOfInt check_recv_size;
      echange_taille(send_size, check_recv_size);
      if (!(check_recv_size == recv_size))
        {
          Cerr << "Error in Schema_Comm::echange_messages : bad recv_size" << finl;
          Process::exit();
        }
    }
  echange_messages(send_size, recv_size);
}
References Cerr, PE_Groups::current_group(), echange_messages(), echange_taille(), Process::exit(), finl, OutputCommBuffer::get_buffer_size(), obuffer(), send_pe_list_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by echange_messages(), and echange_taille_et_messages().
echange_messages() [2/2]
void Schema_Comm::echange_messages (const ArrOfInt & send_size, const ArrOfInt & recv_size) const protected
Cette methode lance l'echange de donnees entre tous les processeurs.
La taille des messages recus doit etre deja connue.
Le schema passe de WRITING a EXCHANGED.
Definition at line 303 of file Schema_Comm.cpp.
{
  assert(status_ == WRITING && ref_group_.non_nul());
  const Comm_Group& group = ref_group_.valeur();
  assert(&group == &PE_Groups::current_group());
// On verifie que tous les membres du groupe executent ceci.
// Si ca plante ici, c'est que tous les membres declares ne sont
// pas en train de faire la barriere.
  if (group.check_enabled()) group.barrier(ECHANGE_MESSAGES_COMM_TAG);
  const int n_send = send_pe_list_.size_array();
  const int n_recv = recv_pe_list_.size_array();
  const char ** send_buffers = new const char* [n_send];
  char ** recv_buffers = new char* [n_recv];
  int i;
  for (i = 0; i < n_recv; i++)
    {
      int pe = recv_pe_list_[i];
      int size = recv_size[i];
      InputCommBuffer& buf = ebuffer(pe);
      recv_buffers[i] = buf.reserve_buffer(size);
    }
  for (i = 0; i < n_send; i++)
    {
      int pe = send_pe_list_[i];
      OutputCommBuffer& buf = obuffer(pe);
// On verifie que la taille des messages en emission est la meme que
// celle enregistree dans send_size_, ce qui garantit que la taille
// en reception est juste elle-aussi.
      assert(send_size[i] == buf.get_buffer_size());
      send_buffers[i] = buf.get_buffer();
    }
  exchange_data(send_pe_list_, send_size, send_buffers,
                recv_pe_list_, recv_size, recv_buffers,
                group,
                use_all_to_allv_);
  delete[] recv_buffers;
  delete[] send_buffers;
// Creation des input streams a partir des buffers recus
  for (i = 0; i < n_recv; i++)
    {
      int pe = recv_pe_list_[i];
      InputCommBuffer& buf = ebuffer(pe);
      buf.create_stream();
    }
// Cas particulier des messages envoyes a moi-meme:
  if (me_to_me_)
    {
      int pe = Process::me();
      InputCommBuffer& buf = ebuffer(pe);
      OutputCommBuffer& obuf = obuffer(pe);
      buf.create_stream_from_output_stream(obuf);
    }
  status_ = EXCHANGED;
}
References Comm_Group::barrier(), buf, Comm_Group::check_enabled(), PE_Groups::current_group(), ebuffer(), ECHANGE_MESSAGES_COMM_TAG, exchange_data(), EXCHANGED, Process::me(), me_to_me_, O_U_Ptr::non_nul(), obuffer(), recv_pe_list_, ref_group_, send_pe_list_, TRUSTArray< _TYPE_ >::size_array(), status_, use_all_to_allv_, Ref_Comm_Group::valeur(), and WRITING.
echange_taille()
void Schema_Comm::echange_taille (const ArrOfInt & send_size, ArrOfInt & recv_size) const protected
Transmet la taille des messages a envoyer aux processeurs qui
vont les recevoir. La taille est le nombre de bytes des obuffers.
send_pe_list et recv_pe_list doivent etre initialises.
Le schema doit etre dans l'etat WRITING.
< Taille d'un int (on echange une taille)
Definition at line 253 of file Schema_Comm.cpp.
{
  static ArrOfInt send_sz;
  static ArrOfInt recv_sz;
  send_sz.set_smart_resize(1);
  recv_sz.set_smart_resize(1);
  assert(status_ == WRITING && ref_group_.non_nul());
  const Comm_Group& group = ref_group_.valeur();
  assert(&group == &PE_Groups::current_group());
// On verifie que tous les membres du groupe executent ceci.
// Si ca plante ici, c'est que tous les membres declares ne sont
// pas en train de faire la barriere.
  if (group.check_enabled()) group.barrier(ECHANGE_MESSAGES_COMM_TAG);
  const int n_send = send_pe_list_.size_array();
  const int n_recv = recv_pe_list_.size_array();
  recv_size.resize_array(n_recv);
  const char ** send_buffers = new const char* [n_send];
  char ** recv_buffers = new char* [n_recv];
  send_sz.resize_array(n_send);   //!< Taille d'un int (on echange une taille)
  send_sz = sizeof(int);
  int i;
  for (i = 0; i < n_send; i++)
    send_buffers[i] = (char*) (& send_size[i]);
  recv_sz.resize_array(n_recv);
  recv_sz = sizeof(int);
  recv_size.resize_array(n_recv);
  for (i = 0; i < n_recv; i++)
    recv_buffers[i] = (char*) (& recv_size[i]);
  exchange_data(send_pe_list_, send_sz, send_buffers,
                recv_pe_list_, recv_sz, recv_buffers,
                group,
                use_all_to_allv_);
  delete[] recv_buffers;
  delete[] send_buffers;
}
References Comm_Group::barrier(), Comm_Group::check_enabled(), PE_Groups::current_group(), ECHANGE_MESSAGES_COMM_TAG, exchange_data(), O_U_Ptr::non_nul(), recv_pe_list_, ref_group_, TRUSTArray< _TYPE_ >::resize_array(), send_pe_list_, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), status_, use_all_to_allv_, Ref_Comm_Group::valeur(), and WRITING.
Referenced by echange_messages(), and echange_taille_et_messages().
echange_taille_et_messages()
void Schema_Comm::echange_taille_et_messages () const
Statut passe a EXCHANGED.
Cette methode lance l'echange de donnees entre tous les processeurs.
La taille des messages recus n'a pas besoin d'etre connue a priori,
on la transmet.
Le schema passe de WRITING a EXCHANGED.
Definition at line 372 of file Schema_Comm.cpp.
{
  static ArrOfInt send_size;
  static ArrOfInt recv_size;
  const int n_send = send_pe_list_.size_array();
  send_size.resize_array(n_send);
  int i;
  for (i = 0; i < n_send; i++)
    {
      int pe = send_pe_list_[i];
      send_size[i] = obuffer(pe).get_buffer_size();
    }
// Methode non optimale: en MPI on pourrait utiliser MPI_Probe mais
// cette methode me parait peu sure.
  echange_taille(send_size, recv_size);
  echange_messages(send_size, recv_size);
}
References echange_messages(), echange_taille(), OutputCommBuffer::get_buffer_size(), obuffer(), TRUSTArray< _TYPE_ >::resize_array(), send_pe_list_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
end_comm()
void Schema_Comm::end_comm () const
Statut passe a RESET Accesseurs:
Vide les buffers et libere les ressources: on
a fini de lire les donnees recues dans les buffers.
Le schema passe de EXCHANGED a RESET.
Definition at line 422 of file Schema_Comm.cpp.
{
  assert(status_ == EXCHANGED && ref_group_.non_nul());
  const Comm_Group& group = ref_group_.valeur();
  assert(&group == &PE_Groups::current_group());
// On verifie que tous les membres du groupe executent ceci.
// Si ca plante ici, c'est que tous les membres declares ne sont
// pas en train de faire la barriere.
  if (group.check_enabled()) group.barrier(END_COMM_TAG);
  int i, n;
  n = send_pe_list_.size_array();
  for (i = 0; i < n; i++)
    {
      int pe = send_pe_list_[i];
      obuffer(pe).clear();
    }
  n = recv_pe_list_.size_array();
  for (i = 0; i < n; i++)
    {
      int pe = recv_pe_list_[i];
      ebuffer(pe).clear();
    }
  if (me_to_me_)
    {
      int pe = Process::me();
      obuffer(pe).clear();
      ebuffer(pe).clear();
    }
  status_ = RESET;
}
References Comm_Group::barrier(), Comm_Group::check_enabled(), InputCommBuffer::clear(), OutputCommBuffer::clear(), PE_Groups::current_group(), ebuffer(), END_COMM_TAG, EXCHANGED, Process::me(), me_to_me_, O_U_Ptr::non_nul(), obuffer(), recv_pe_list_, ref_group_, RESET, send_pe_list_, TRUSTArray< _TYPE_ >::size_array(), status_, and Ref_Comm_Group::valeur().
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
get_group()
const Comm_Group & Schema_Comm::get_group () const
Renvoie le groupe auquel est associe le schema.
Definition at line 122 of file Schema_Comm.cpp.
{
  assert(ref_group_.non_nul());
  return ref_group_.valeur();
}
References O_U_Ptr::non_nul(), ref_group_, and Ref_Comm_Group::valeur().
get_recv_pe_list()
const ArrOfInt & Schema_Comm::get_recv_pe_list () const
Definition at line 506 of file Schema_Comm.cpp.
{
  assert(ref_group_.non_nul());
  return recv_pe_list_;
}
References O_U_Ptr::non_nul(), recv_pe_list_, and ref_group_.
get_send_pe_list()
const ArrOfInt & Schema_Comm::get_send_pe_list () const
Definition at line 500 of file Schema_Comm.cpp.
{
  assert(ref_group_.non_nul());
  return send_pe_list_;
}
References O_U_Ptr::non_nul(), ref_group_, and send_pe_list_.
obuffer()
OutputCommBuffer & Schema_Comm::obuffer (int pe) inline static protected
Accesseur a un membre du tableau obuffers_ (avec verification)
Definition at line 32 of file Schema_Comm.cpp.
{
  assert(pe >= 0 && pe < n_buffers_);
  return buffers_.obuffers_[pe];
}
References buffers_, n_buffers_, and InOutCommBuffers::obuffers_.
Referenced by echange_messages(), echange_taille_et_messages(), end_comm(), and send_buffer().
operator=()
const Schema_Comm & Schema_Comm::operator= (const Schema_Comm & schema)
Operateur copie : on copie la liste des processeurs qui
communiquent. Le nouveau schema est place dans l'etat RESET.
Attention : tous les membres du Comm_Group doivent executer
cette fonction simultanement.
Definition at line 95 of file Schema_Comm.cpp.
{
  assert(status_ == RESET);
  ref_group_ = schema.ref_group_;
  assert(&(ref_group_.valeur()) == &PE_Groups::current_group());
  send_pe_list_ = schema.send_pe_list_;
  recv_pe_list_ = schema.recv_pe_list_;
  me_to_me_     = schema.me_to_me_;
  use_all_to_allv_ = schema.use_all_to_allv_;
  const Comm_Group& group = ref_group_.valeur();
  if (group.check_enabled()) group.barrier(COPY_OPERATOR_TAG);
  return *this;
}
References Comm_Group::barrier(), Comm_Group::check_enabled(), COPY_OPERATOR_TAG, PE_Groups::current_group(), me_to_me_, recv_pe_list_, ref_group_, RESET, send_pe_list_, status_, use_all_to_allv_, and Ref_Comm_Group::valeur().
Referenced by Schema_Comm().
recv_buffer()
Entree & Schema_Comm::recv_buffer (int num_PE) const
renvoie le buffer correspondant au processeur num_PE pour
y lire les donnees recues. Le schema doit etre dans l'etat EXCHANGED.
Definition at line 486 of file Schema_Comm.cpp.
{
// Si l'assert suivant plante, c'est qu'on essaie de
// lire des donnees dans les buffers en dehors du bloc
// echange_xxx();
// ...
// end_comm();
  assert(status_ == EXCHANGED && ref_group_.non_nul());
// On verifie que le PE demande est bien dans la liste
// des PEs declares en reception.
  assert((me_to_me_&&num_PE==Process::me()) || check_PE_in_list(num_PE, recv_pe_list_));
  return ebuffer(num_PE);
}
References check_PE_in_list(), ebuffer(), EXCHANGED, Process::me(), me_to_me_, O_U_Ptr::non_nul(), recv_pe_list_, ref_group_, and status_.
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
send_buffer()
Sortie & Schema_Comm::send_buffer (int num_PE) const
renvoie le buffer correspondant au processeur num_PE pour
y entasser des donnees a envoyer. Le schema doit etre dans l'etat WRITING.
!< echange_xxx();
Definition at line 469 of file Schema_Comm.cpp.
{
// Si l'assert suivant plante, c'est qu'on essaie de
// mettre des donnees dans le buffer en dehors du bloc
// begin_comm();
// ...
  ///!<  echange_xxx();
  assert(status_ == WRITING && ref_group_.non_nul());
// On verifie que le PE demande est bien dans la liste
// des PEs declares en envoi.
  assert((me_to_me_&&num_PE==Process::me()) || check_PE_in_list(num_PE, send_pe_list_));
  return obuffer(num_PE);
}
References check_PE_in_list(), Process::me(), me_to_me_, O_U_Ptr::non_nul(), obuffer(), ref_group_, send_pe_list_, status_, and WRITING.
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
set_all_to_allv_flag()
void Schema_Comm::set_all_to_allv_flag (int x) inline
Definition at line 101 of file Schema_Comm.h.
{ use_all_to_allv_ = x; }
References use_all_to_allv_.
set_group()
void Schema_Comm::set_group (const Comm_Group & group)
Obsolete.
Methode obsolete, le groupe associe au schema est le groupe
courant au moment ou on cree le schema. L'appel a cette methode
n'est valide qu'avec le meme groupe que le groupe d'origine.
La methode ne fait rien.
Definition at line 114 of file Schema_Comm.cpp.
{
  assert(&group == &(ref_group_.valeur()));
  assert(&group == &PE_Groups::current_group());
}
References PE_Groups::current_group(), ref_group_, and Ref_Comm_Group::valeur().
set_send_recv_pe_list()
void Schema_Comm::set_send_recv_pe_list (const ArrOfInt & send_pe_list, const ArrOfInt & recv_pe_list, const int me_to_me = 0)
Definit la liste des processeurs a qui on va envoyer
et de qui on va recevoir des donnees.
Si me_to_me est non nul, on autorise l'envoi des messages a soi-meme,
sinon non (argument optionnel : par defaut, me_to_me=0)
Definition at line 138 of file Schema_Comm.cpp.
{
  assert(status_ == RESET);
  send_pe_list_ = send_pe_list;
  recv_pe_list_ = recv_pe_list;
  me_to_me_ = me_to_me;
// Verification du principe "tu m'ecoutes quand je te parle"
  const Comm_Group& group = ref_group_.valeur();
  assert(&group == &PE_Groups::current_group());
  if (group.check_enabled()) check_send_recv_pe_list();
}
References Comm_Group::check_enabled(), check_send_recv_pe_list(), PE_Groups::current_group(), me_to_me_, recv_pe_list_, ref_group_, RESET, send_pe_list_, status_, and Ref_Comm_Group::valeur().
Referenced by Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::creer_aretes(), creer_md_vect_renum(), envoyer_all_to_all_(), find_matching_coordinates(), mon_construire_correspondance_items_par_coordonnees(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and Raccord_distant_homogene::trace_face_distant().
Member Data Documentation
buffers_
InOutCommBuffers Schema_Comm::buffers_ static private
Definition at line 129 of file Schema_Comm.h.
Referenced by ebuffer(), obuffer(), and Schema_Comm().
me_to_me_
int Schema_Comm::me_to_me_ protected
Drapeau: est-ce qu'on autorise a s'envoyer des messages a soi ?
Definition at line 121 of file Schema_Comm.h.
Referenced by echange_messages(), end_comm(), operator=(), recv_buffer(), Schema_Comm(), send_buffer(), and set_send_recv_pe_list().
n_buffers_
int Schema_Comm::n_buffers_ = 0 static private
Definition at line 130 of file Schema_Comm.h.
Referenced by ebuffer(), obuffer(), and Schema_Comm().
recv_pe_list_
ArrOfInt Schema_Comm::recv_pe_list_ protected
Liste des processeurs de qui recevoir.
Definition at line 120 of file Schema_Comm.h.
Referenced by check_send_recv_pe_list(), echange_messages(), echange_taille(), end_comm(), get_recv_pe_list(), operator=(), recv_buffer(), Schema_Comm(), and set_send_recv_pe_list().
ref_group_
Ref_Comm_Group Schema_Comm::ref_group_ protected
Groupe de processeurs qui vont discuter.
Definition at line 122 of file Schema_Comm.h.
Referenced by begin_comm(), echange_messages(), echange_taille(), end_comm(), get_group(), get_recv_pe_list(), get_send_pe_list(), operator=(), recv_buffer(), Schema_Comm(), send_buffer(), set_group(), and set_send_recv_pe_list().
send_pe_list_
ArrOfInt Schema_Comm::send_pe_list_ protected
Liste des processeurs a qui envoyer.
Definition at line 119 of file Schema_Comm.h.
Referenced by check_send_recv_pe_list(), echange_messages(), echange_taille(), echange_taille_et_messages(), end_comm(), get_send_pe_list(), operator=(), Schema_Comm(), send_buffer(), and set_send_recv_pe_list().
status_
Schema_Comm::Static_Status Schema_Comm::status_ = UNINITIALIZED static protected
Definition at line 115 of file Schema_Comm.h.
Referenced by begin_comm(), check_send_recv_pe_list(), echange_messages(), echange_taille(), end_comm(), Schema_Comm_statique::get_recv_size(), Schema_Comm_statique::get_send_size(), operator=(), recv_buffer(), Schema_Comm(), send_buffer(), and set_send_recv_pe_list().
use_all_to_allv_
int Schema_Comm::use_all_to_allv_ protected
Drapeau, quel type de communication faut-il utiliser ?
Definition at line 124 of file Schema_Comm.h.
Referenced by echange_messages(), echange_taille(), operator=(), Schema_Comm(), and set_all_to_allv_flag().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Schema_Comm.h
src/Kernel/Utilitaires/Schema_Comm.cpp