TRUST: Sortie_libre_pression_moyenne_imposee Class Reference
Sortie_libre_pression_moyenne_imposee Class Reference
classe Sortie_libre_pression_moyenne_imposee
Cette classe derive de Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition de niveau moyen de
pression impose (un gradient peut donc apparaitre).
L'objet de type Champ_bord le_champ_bord contient la pression et la
fonction flux_impose() renvoie les valeurs de cette pression.
champ_ext contient une valeur de la vitesse du fluide a l'exterieur
accessible par la methode val_ext()
#include <Sortie_libre_pression_moyenne_imposee.h>
Public Member Functions
Sortie_libre_pression_moyenne_imposee ()
~Sortie_libre_pression_moyenne_imposee ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_moyenne_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
void completer () override
Complete les conditions aux limites.
void mettre_a_jour (double) override
Met a jour les conditions aux limites.
double flux_impose (int i) const override
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere divise par d_rho.
double flux_impose (int i, int j) const override
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
Public Member Functions inherited from Neumann_sortie_libre
Neumann_sortie_libre ()
~Neumann_sortie_libre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & tab_ext () const override
DoubleTab & tab_ext () override
double val_ext (int i) const override
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
double val_ext (int i, int j) const override
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
Public Member Functions inherited from Neumann_val_ext
Neumann_val_ext ()
~Neumann_val_ext () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual const DoubleTab & tab_ext () const =0
virtual DoubleTab & tab_ext ()=0
virtual double val_ext (int i) const =0
virtual double val_ext (int i, int j) const =0
Public Member Functions inherited from Neumann
Neumann ()
~Neumann () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double flux_impose (int i) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
virtual double flux_impose (int i, int j) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sortie_libre_pression_moyenne_imposee & self_cast (Objet_U &)
static const Sortie_libre_pression_moyenne_imposee & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann_sortie_libre
static Objet_U * cree_instance ()
static const Type_info * info ()
static Neumann_sortie_libre & self_cast (Objet_U &)
static const Neumann_sortie_libre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann_val_ext
static const Type_info * info ()
static Neumann_val_ext & self_cast (Objet_U &)
static const Neumann_val_ext & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann
static const Type_info * info ()
static Neumann & self_cast (Objet_U &)
static const Neumann & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Neumann_sortie_libre
static const Type_info info_obj
Static Public Attributes inherited from Neumann_val_ext
static const Type_info info_obj
Static Public Attributes inherited from Neumann
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit le champ de frontiere a partir d'un flot d'entree : 1 double.
Type le_champ_ext en "Champ_front_uniforme".
Redimmensionne le_champ_ext en fonction de la dimension
de l'espace (dimension)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double d_rho
double Pext_
DoubleVect surfaces
IntTab face_voisins
int nb_faces_
int ndeb_
Protected Attributes inherited from Neumann_sortie_libre
Champ_front le_champ_ext
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Sortie_libre_pression_moyenne_imposee
Cette classe derive de Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition de niveau moyen de
pression impose (un gradient peut donc apparaitre).
L'objet de type Champ_bord le_champ_bord contient la pression et la
fonction flux_impose() renvoie les valeurs de cette pression.
champ_ext contient une valeur de la vitesse du fluide a l'exterieur
accessible par la methode val_ext()
Definition at line 36 of file Sortie_libre_pression_moyenne_imposee.h.
Constructor & Destructor Documentation
Sortie_libre_pression_moyenne_imposee()
Sortie_libre_pression_moyenne_imposee::Sortie_libre_pression_moyenne_imposee ()
Definition at line 25 of file Sortie_libre_pression_moyenne_imposee.cpp.
:d_rho(-123.) {}
~Sortie_libre_pression_moyenne_imposee()
Sortie_libre_pression_moyenne_imposee::~Sortie_libre_pression_moyenne_imposee ()
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
Member Function Documentation
compatible_avec_eqn()
int Sortie_libre_pression_moyenne_imposee::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_moyenne_imposee sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 92 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
completer()
void Sortie_libre_pression_moyenne_imposee::completer (void) override virtual
Complete les conditions aux limites.
Reimplemented from Cond_lim_base.
Definition at line 120 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  if (sub_type(Champ_Uniforme,mil.masse_volumique().valeur()))
    {
      const Champ_Uniforme& rho=ref_cast(Champ_Uniforme,mil.masse_volumique().valeur());
      d_rho = rho(0,0);
    }
  else
    {
      d_rho = -1;
    }
  int i;
  ndeb_ = ref_cast(Front_VF,frontiere_dis()).num_premiere_face();
  nb_faces_ = ref_cast(Front_VF,frontiere_dis()).nb_faces();
  le_champ_front.valeurs().resize(nb_faces_,1);
  DoubleTab& Pimp = le_champ_front.valeurs();
// if (sub_type(Champ_front_uniforme,le_champ_ext.valeur())) {
// double Pext = le_champ_ext.valeurs()(0,0);
  for (i=0 ; i<nb_faces_ ; i++)
    {
      Pimp(i,0) = Pext_;
    }
// } else {
// const DoubleTab& Pext = le_champ_front.valeurs();
// for (i=0 ; i<nb_faces_ ; i++) {
// Pimp(i,0) = Pext(i);
// }
// }
  surfaces.resize(nb_faces_);
  Zone_VF& zvf = ref_cast(Zone_VF,ma_zone_cl_dis->zone_dis().valeur());
  for (i=0 ; i<nb_faces_ ; i++)
    {
      surfaces(i) = zvf.face_surfaces(i+ndeb_);
    }
  face_voisins = zvf.face_voisins();
}
References d_rho, MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), face_voisins, Cond_lim_base::frontiere_dis(), Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), nb_faces_, ndeb_, Pext_, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), sub_type, surfaces, Deriv_Champ_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_front::valeurs(), and Zone_Cl_dis_base::zone_dis().
cree_instance()
Objet_U * Sortie_libre_pression_moyenne_imposee::cree_instance () static
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
duplique()
int Sortie_libre_pression_moyenne_imposee::duplique () const override virtual
Reimplemented from Neumann_sortie_libre.
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
flux_impose() [1/2]
double Sortie_libre_pression_moyenne_imposee::flux_impose (int i) const override virtual
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere divise par d_rho.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 252 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  const Champ_base& rho=mil.masse_volumique().valeur();
  double rho_;
  assert(!est_egal(d_rho,-123.));
  if (d_rho==-1)
    {
      rho_ = rho(i);
    }
  else
    {
      rho_ = d_rho;
    }
  if (le_champ_front.valeurs().size()==1)
    return le_champ_front(0,0)/rho_;
  else if (le_champ_front.valeurs().dimension(1)==1)
    {
      return le_champ_front(i,0)/rho_;
    }
  else
    Cerr << "Neumann::flux_impose erreur" << finl;
  exit();
  return 0.;
}
References Cerr, d_rho, TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), est_egal(), Process::exit(), finl, Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTVect< _TYPE_ >::size(), Deriv_Champ_base::valeur(), and Champ_front::valeurs().
flux_impose() [2/2]
double Sortie_libre_pression_moyenne_imposee::flux_impose (int i, int j) const override virtual
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 302 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  const Champ_base& rho=mil.masse_volumique().valeur();
  double rho_;
  assert(!est_egal(d_rho,-123.));
  if (d_rho==-1)
    {
      rho_ = rho(i);
    }
  else
    {
      rho_ = d_rho;
    }
  if (le_champ_front.valeurs().dimension(0)==1)
    return le_champ_front(0,j)/rho_;
  else
    return le_champ_front(i,j)/rho_;
}
References d_rho, TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), est_egal(), Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), Deriv_Champ_base::valeur(), and Champ_front::valeurs().
get_info()
const Type_info * Sortie_libre_pression_moyenne_imposee::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
info()
const Type_info * Sortie_libre_pression_moyenne_imposee::info () static
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
mettre_a_jour()
void Sortie_libre_pression_moyenne_imposee::mettre_a_jour (double temps) override virtual
Met a jour les conditions aux limites.
Reimplemented from Neumann_sortie_libre.
Definition at line 176 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  Cond_lim_base::mettre_a_jour(temps);
  const DoubleTab& tab_P=ref_cast(Navier_Stokes_std,ma_zone_cl_dis->equation()).pression().valeurs();
  int face,elem, facegl;
  DoubleTab& Pimp = le_champ_front.valeurs();
  double Ptot=0, s,S=0;
  for (face=0 ; face<nb_faces_ ; face++)
    {
      facegl = face+ndeb_;
      elem = face_voisins(facegl,0);
      if (elem==-1)
        elem = face_voisins(facegl,1);
      s = surfaces(face);
      S += s;
      Ptot += s*tab_P(elem);
    }
  Ptot = mp_sum(Ptot);
  S = mp_sum(S);
  Ptot /= S;
// Cerr<<"Sortie_libre_pression_moyenne_imposee::mettre_a_jour"<<finl;
// Cerr<<"  pression interne=";
// for (face=0 ; face<nb_faces_ ; face++) {
// facegl = face+ndeb_;
// elem = face_voisins(facegl,0);
// if (elem==-1)
// elem = face_voisins(facegl,1);
// Cerr<<" P("<<elem<<")="<<tab_P(elem);
// }
// Cerr<<finl;
  Cerr<<"Sortie_libre_pression_moyenne_imposee  pmoy= "<<Ptot<<finl;
  for (face=0 ; face<nb_faces_ ; face++)
    {
      facegl = face+ndeb_;
      elem = face_voisins(facegl,0);
      if (elem==-1)
        elem = face_voisins(facegl,1);
      Pimp(face,0) = tab_P(elem) + (Pext_-Ptot);
    }
// Ptot=0, s,S=0;
// Cerr<<"  Pimp=";
// for (face=0 ; face<nb_faces_ ; face++) {
// Cerr<<" Pimp("<<face<<")="<<le_champ_front(face,0);
// s = surfaces(face);
// S += s;
// Ptot += s*Pimp(face,0);
// }
// Cerr<<finl;
// Cerr<<"  Ptotimp= "<<Ptot/S<<finl;
}
References Cerr, MorEqn::equation(), face_voisins, finl, Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Cond_lim_base::mettre_a_jour(), Process::mp_sum(), nb_faces_, ndeb_, Pext_, ref_cast, surfaces, and Champ_front::valeurs().
printOn()
Sortie & Sortie_libre_pression_moyenne_imposee::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 40 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Sortie_libre_pression_moyenne_imposee::readOn (Entree & s) override protected virtual
Lit le champ de frontiere a partir d'un flot d'entree : 1 double.
Type le_champ_ext en "Champ_front_uniforme".
Redimmensionne le_champ_ext en fonction de la dimension
de l'espace (dimension)
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 62 of file Sortie_libre_pression_moyenne_imposee.cpp.
{
  s >> Pext_;
  le_champ_ext.typer("Champ_front_uniforme");
  le_champ_ext.valeurs().resize(1,dimension);
  le_champ_front.typer("Champ_front_fonc");
  le_champ_front->fixer_nb_comp(1);
  return s ;
}
References Objet_U::dimension, Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, Pext_, TRUSTTab< _TYPE_ >::resize(), Deriv_::typer(), and Champ_front::valeurs().
self_cast() [1/2]
const Sortie_libre_pression_moyenne_imposee & Sortie_libre_pression_moyenne_imposee::self_cast (const Objet_U & r) static
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
self_cast() [2/2]
Sortie_libre_pression_moyenne_imposee & Sortie_libre_pression_moyenne_imposee::self_cast (Objet_U & r) static
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
taille_memoire()
unsigned Sortie_libre_pression_moyenne_imposee::taille_memoire () const override virtual
Reimplemented from Neumann_sortie_libre.
Definition at line 23 of file Sortie_libre_pression_moyenne_imposee.cpp.
Member Data Documentation
d_rho
double Sortie_libre_pression_moyenne_imposee::d_rho protected
Definition at line 50 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), and flux_impose().
face_voisins
IntTab Sortie_libre_pression_moyenne_imposee::face_voisins protected
Definition at line 53 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), and mettre_a_jour().
info_obj
const Type_info Sortie_libre_pression_moyenne_imposee::info_obj static
Definition at line 39 of file Sortie_libre_pression_moyenne_imposee.h.
nb_faces_
int Sortie_libre_pression_moyenne_imposee::nb_faces_ protected
Definition at line 54 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), and mettre_a_jour().
ndeb_
int Sortie_libre_pression_moyenne_imposee::ndeb_ protected
Definition at line 55 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), and mettre_a_jour().
Pext_
double Sortie_libre_pression_moyenne_imposee::Pext_ protected
Definition at line 51 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), mettre_a_jour(), and readOn().
surfaces
DoubleVect Sortie_libre_pression_moyenne_imposee::surfaces protected
Definition at line 52 of file Sortie_libre_pression_moyenne_imposee.h.
Referenced by completer(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Sortie_libre_pression_moyenne_imposee.h
src/ThHyd/Incompressible/Cond_Lim/Sortie_libre_pression_moyenne_imposee.cpp