TRUST: T_It_Sou_VDF_Face< _TYPE_ > Class Template Reference
T_It_Sou_VDF_Face< _TYPE_ > Class Template Reference
#include <T_It_Sou_VDF_Face.h>
Public Member Functions
T_It_Sou_VDF_Face ()
T_It_Sou_VDF_Face (const T_It_Sou_VDF_Face< _TYPE_ > &)
DoubleTab & calculer (DoubleTab &) const override
DoubleTab & ajouter (DoubleTab &) const override
void completer_ () override
Evaluateur_Source_VDF & evaluateur () override
Public Member Functions inherited from Iterateur_Source_VDF_base
Iterateur_Source_VDF_base ()
~Iterateur_Source_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const =0
virtual DoubleTab & calculer (DoubleTab &) const =0
virtual Evaluateur_Source_VDF & evaluateur ()=0
virtual void completer_ ()=0
int equation_divisee_par_rho () const
void associer_zones (const Zone_VDF &, const Zone_Cl_VDF &)
void associer (const Source_base &source)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Protected Member Functions
template<typename Type_Double >
DoubleTab & ajouter_faces_internes (const int, DoubleTab &) const
template<typename Type_Double >
DoubleTab & ajouter_faces_bords (const int, DoubleTab &) const
const int & faces_doubles (int num_face) const
Protected Member Functions inherited from Iterateur_Source_VDF_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
_TYPE_ evaluateur_source_face
int nb_faces
int premiere_face_interne
DoubleTab coef
Protected Attributes inherited from Iterateur_Source_VDF_base
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Ref_Source_base so_base
Private Member Functions
unsigned taille_memoire () const override
int duplique () const override
Additional Inherited Members
Static Public Member Functions inherited from Iterateur_Source_VDF_base
static const Type_info * info ()
static Iterateur_Source_VDF_base & self_cast (Objet_U &)
static const Iterateur_Source_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Iterateur_Source_VDF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
template<class _TYPE_>
class T_It_Sou_VDF_Face< _TYPE_ >
Definition at line 28 of file T_It_Sou_VDF_Face.h.
Constructor & Destructor Documentation
T_It_Sou_VDF_Face() [1/2]
template<class _TYPE_ > T_It_Sou_VDF_Face< _TYPE_ >::T_It_Sou_VDF_Face () inline
Definition at line 44 of file T_It_Sou_VDF_Face.h.
: nb_faces(-1), premiere_face_interne(-1) { }
Referenced by T_It_Sou_VDF_Face< _TYPE_ >::duplique().
T_It_Sou_VDF_Face() [2/2]
template<class _TYPE_ > T_It_Sou_VDF_Face< _TYPE_ >::T_It_Sou_VDF_Face (const T_It_Sou_VDF_Face< _TYPE_ > & iter) inline
Definition at line 64 of file T_It_Sou_VDF_Face.h.
                                                         : Iterateur_Source_VDF_base(iter),
  evaluateur_source_face(iter.evaluateur_source_face),
  nb_faces(iter.nb_faces), premiere_face_interne(iter.premiere_face_interne) { }
Member Function Documentation
ajouter()
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Face< _TYPE_ >::ajouter (DoubleTab & resu) const override virtual
Implements Iterateur_Source_VDF_base.
Definition at line 84 of file T_It_Sou_VDF_Face.h.
{
  ((_TYPE_&) (evaluateur_source_face)).mettre_a_jour();
  assert(resu.nb_dim() < 3);
  const int ncomp = resu.line_size();
  DoubleVect& bilan = so_base->bilan();
  bilan=0;
  const int nb_faces_tot = la_zone.valeur().nb_faces_tot();
  coef.resize(nb_faces_tot,Array_base::NOCOPY_NOINIT);
  coef=1;
  if (equation_divisee_par_rho())
    {
      const Milieu_base& milieu = la_zcl->equation().milieu();
      const Champ_base& rho = milieu.masse_volumique().valeur();
      if (sub_type(Champ_Uniforme,rho)) coef = rho(0,0);
      else
        {
          const DoubleTab& val_rho = rho.valeurs();
          const IntTab& face_vois = la_zone.valeur().face_voisins();
          const DoubleVect& volumes = la_zone.valeur().volumes();
          coef = 0.;
          for (int fac = 0; fac < nb_faces_tot; fac++)
            {
              const int elem1 = face_vois(fac,0), elem2 = face_vois(fac,1);
              double vol = 0.;
              if (elem1 != -1)
                {
                  coef(fac) += val_rho(elem1)*volumes(elem1);
                  vol += volumes(elem1);
                }
              if (elem2 != -1)
                {
                  coef(fac) += val_rho(elem2)*volumes(elem2);
                  vol += volumes(elem2);
                }
              coef(fac) /= vol;
            }
        }
    }
  if (ncomp == 1)
    {
      ajouter_faces_bords<SingleDouble>(ncomp,resu);
      ajouter_faces_internes<SingleDouble>(ncomp,resu);
    }
  else
    {
      ajouter_faces_bords<ArrOfDouble>(ncomp,resu);
      ajouter_faces_internes<ArrOfDouble>(ncomp,resu);
    }
  return resu;
}
References Milieu_base::equation(), face_vois(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTTab< _TYPE_ >::nb_dim(), Array_base::NOCOPY_NOINIT, TRUSTVect< _TYPE_ >::resize(), sub_type, Deriv_Champ_base::valeur(), and Champ_Proto::valeurs().
ajouter_faces_bords()
template<class _TYPE_ > template<typename Type_Double > DoubleTab & T_It_Sou_VDF_Face< _TYPE_ >::ajouter_faces_bords (const int ncomp, DoubleTab & resu) const protected
Definition at line 140 of file T_It_Sou_VDF_Face.h.
{
  Type_Double source(ncomp);
  DoubleVect& bilan = so_base->bilan();
  for (int num_cl = 0; num_cl < la_zone->nb_front_Cl(); num_cl++)
    {
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
      if ( (sub_type(Dirichlet,la_cl.valeur())) || (sub_type(Dirichlet_homogene,la_cl.valeur())) ) { /* Do nothing */ }
      else
        for (int num_face = ndeb; num_face < nfin; num_face++)
          {
            evaluateur_source_face.calculer_terme_source_bord(num_face,source);
            for (int k = 0; k < ncomp; k++)
              {
                resu(num_face,k) += source[k];
                double contribution = (faces_doubles(num_face)==1) ? 0.5 : 1 ;
                bilan(k) += contribution * coef(num_face) * source[k];
              }
          }
    }
  return resu;
}
References Cond_lim::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, and Deriv_Cond_lim_base::valeur().
ajouter_faces_internes()
template<class _TYPE_ > template<typename Type_Double > DoubleTab & T_It_Sou_VDF_Face< _TYPE_ >::ajouter_faces_internes (const int ncomp, DoubleTab & resu) const protected
Definition at line 166 of file T_It_Sou_VDF_Face.h.
{
  Type_Double source(ncomp);
  DoubleVect& bilan = so_base->bilan();
  for (int num_face=premiere_face_interne; num_face<nb_faces; num_face++)
    {
      evaluateur_source_face.calculer_terme_source(num_face,source);
      for (int k=0; k<ncomp; k++)
        {
          resu(num_face,k) += source[k];
          double contribution = (faces_doubles(num_face)==1) ? 0.5 : 1 ;
          bilan(k) += contribution * coef(num_face) * source[k];
        }
    }
  return resu;
}
calculer()
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Face< _TYPE_ >::calculer (DoubleTab & resu) const override virtual
Implements Iterateur_Source_VDF_base.
Definition at line 184 of file T_It_Sou_VDF_Face.h.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
completer_()
template<class _TYPE_ > void T_It_Sou_VDF_Face< _TYPE_ >::completer_ inline override virtual
Implements Iterateur_Source_VDF_base.
Definition at line 70 of file T_It_Sou_VDF_Face.h.
{
  nb_faces = la_zone->nb_faces();
  premiere_face_interne = la_zone->premiere_face_int();
}
duplique()
template<class _TYPE_ > int T_It_Sou_VDF_Face< _TYPE_ >::duplique () const inline override private virtual
Implements Objet_U.
Definition at line 32 of file T_It_Sou_VDF_Face.h.
  {
    T_It_Sou_VDF_Face* xxx = new  T_It_Sou_VDF_Face(*this);
    if(!xxx)
      {
        Cerr << "Not enough memory " << finl;
        exit();
      }
    return xxx->numero();
  }
References Cerr, Process::exit(), finl, Objet_U::numero(), and T_It_Sou_VDF_Face< _TYPE_ >::T_It_Sou_VDF_Face().
evaluateur()
template<class _TYPE_ > Evaluateur_Source_VDF & T_It_Sou_VDF_Face< _TYPE_ >::evaluateur inline override virtual
Implements Iterateur_Source_VDF_base.
Definition at line 77 of file T_It_Sou_VDF_Face.h.
{
  Evaluateur_Source_VDF& eval = static_cast<Evaluateur_Source_VDF&> (evaluateur_source_face);
  return eval;
}
faces_doubles()
template<class _TYPE_ > const int & T_It_Sou_VDF_Face< _TYPE_ >::faces_doubles (int num_face) const inline protected
Definition at line 60 of file T_It_Sou_VDF_Face.h.
{ return la_zone->faces_doubles()[num_face]; }
References Zone_VF::faces_doubles(), and Iterateur_Source_VDF_base::la_zone.
taille_memoire()
template<class _TYPE_ > unsigned T_It_Sou_VDF_Face< _TYPE_ >::taille_memoire () const inline override private virtual
Implements Objet_U.
Definition at line 30 of file T_It_Sou_VDF_Face.h.
{ throw; }
Member Data Documentation
coef
template<class _TYPE_ > DoubleTab T_It_Sou_VDF_Face< _TYPE_ >::coef mutable protected
Definition at line 56 of file T_It_Sou_VDF_Face.h.
evaluateur_source_face
template<class _TYPE_ > _TYPE_ T_It_Sou_VDF_Face< _TYPE_ >::evaluateur_source_face protected
Definition at line 54 of file T_It_Sou_VDF_Face.h.
nb_faces
template<class _TYPE_ > int T_It_Sou_VDF_Face< _TYPE_ >::nb_faces protected
Definition at line 55 of file T_It_Sou_VDF_Face.h.
premiere_face_interne
template<class _TYPE_ > int T_It_Sou_VDF_Face< _TYPE_ >::premiere_face_interne protected
Definition at line 55 of file T_It_Sou_VDF_Face.h.
The documentation for this class was generated from the following file:
src/VDF/Sources/Iterateurs/T_It_Sou_VDF_Face.h