TRUST: DP_Impose_CoviMAC_Face Class Reference
DP_Impose_CoviMAC_Face Class Reference
class DP_Impose_CoviMAC_Face
#include <DP_Impose_CoviMAC_Face.h>
Public Member Functions
DP_Impose_CoviMAC_Face ()
~DP_Impose_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void remplir_num_faces (Entree &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static DP_Impose_CoviMAC_Face & self_cast (Objet_U &)
static const
DP_Impose_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
IntVect sgn
double surf
Detailed Description
class DP_Impose_CoviMAC_Face
See also:
Perte_Charge_CoviMAC_Face
Definition at line 42 of file DP_Impose_CoviMAC_Face.h.
Constructor & Destructor Documentation
DP_Impose_CoviMAC_Face::DP_Impose_CoviMAC_Face ()
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
DP_Impose_CoviMAC_Face::~DP_Impose_CoviMAC_Face ()
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
Member Function Documentation
void DP_Impose_CoviMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Source_base.
Objet_U * DP_Impose_CoviMAC_Face::cree_instance () [static]
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
void DP_Impose_CoviMAC_Face::dimensionner_blocs (matrices_t matrices) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 53 of file DP_Impose_CoviMAC_Face.h.
{}) const { }; //rien
int DP_Impose_CoviMAC_Face::duplique () const [virtual]
Implements Perte_Charge_CoviMAC_Face.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
const Type_info * DP_Impose_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
int DP_Impose_CoviMAC_Face::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 49 of file DP_Impose_CoviMAC_Face.h.
  {
    return 1;
  };
const Type_info * DP_Impose_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
void DP_Impose_CoviMAC_Face::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 117 of file DP_Impose_CoviMAC_Face.cpp.
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Process::me(), Perte_Charge_CoviMAC_Face::num_faces, DoubleVect::resize(), and sgn.
{
  DP_Impose::mettre_a_jour(temps);
  bilan().resize(4); //DP dDP/dQ Q Q0
  bilan()(2) = calculate_Q(equation(), num_faces, sgn) * (Process::me() ? 0 : 1); //pour eviter le sommage en sortie
}
Sortie & DP_Impose_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 36 of file DP_Impose_CoviMAC_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & DP_Impose_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 44 of file DP_Impose_CoviMAC_Face.cpp.
References Cerr, Process::exit(), finl, Perte_Charge_Singuliere::identifiant_, DP_Impose::lire_donnees(), Process::mp_max(), remplir_num_faces(), Source_base::set_description(), Source_base::set_fichier(), sgn, and IntVect::size().
{
  DP_Impose::lire_donnees(s);
  remplir_num_faces(s);
  if (!mp_max(sgn.size()))
    Cerr << "DP_Impose_CoviMAC_Face : champ d'orientation non renseigne!" << finl, Process::exit();
// fichier de sortie
  set_fichier(Nom("DP_") + identifiant_);
  set_description(Nom("DP impose sur la surface ") + identifiant_ + "\nt DP dDP/dQ Q Q0");
  return s;
}
void DP_Impose_CoviMAC_Face::remplir_num_faces (Entree & s)
< not to count several (number of processes) times the same face
Definition at line 65 of file DP_Impose_CoviMAC_Face.cpp.
References Cerr, Zone_VF::creer_tableau_faces(), Probleme_base::domaine(), MorEqn::equation(), Process::exit(), Zone_VF::face_surfaces(), finl, Process::je_suis_maitre(), Perte_Charge_Singuliere::lire_surfaces(), Process::mp_max(), mp_somme_vect(), Zone_dis_base::nb_elem(), Perte_Charge_CoviMAC_Face::num_faces, Equation_base::probleme(), ref_cast, IntVect::resize(), sgn, IntVect::size(), surf, and valeur().
Referenced by readOn().
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_CoviMAC& zone_CoviMAC = ref_cast(Zone_CoviMAC,equation().zone_dis().valeur());
  int taille_bloc = zone_CoviMAC.nb_elem();
  num_faces.resize(taille_bloc);
  lire_surfaces(s,le_domaine,zone_CoviMAC,num_faces, sgn);
// int nfac_tot = mp_sum(num_faces.size());
  int nfac_max = (int)mp_max(num_faces.size()); //!< not to count several (number of processes) times the same face
  if(je_suis_maitre() && nfac_max == 0)
    {
      Cerr << "Error when defining the surface plane for the singular porosity :" << finl;
      Cerr << "No mesh faces has been found for the surface plane." << finl;
      Cerr << "Check the coordinate of the surface plane which should match mesh coordinates." << finl;
      exit();
    }
  DoubleTrav S;
  zone_CoviMAC.creer_tableau_faces(S);
  for (int i = 0; i < num_faces.size(); i++) S(num_faces(i)) = zone_CoviMAC.face_surfaces(num_faces(i));
  surf = mp_somme_vect(S);
}
DP_Impose_CoviMAC_Face & DP_Impose_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
const DP_Impose_CoviMAC_Face & DP_Impose_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
unsigned DP_Impose_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file DP_Impose_CoviMAC_Face.cpp.
Member Data Documentation
const Type_info DP_Impose_CoviMAC_Face::info_obj [static]
Reimplemented from Perte_Charge_CoviMAC_Face.
Definition at line 46 of file DP_Impose_CoviMAC_Face.h.
IntVect DP_Impose_CoviMAC_Face::sgn [protected]
Definition at line 59 of file DP_Impose_CoviMAC_Face.h.
Referenced by mettre_a_jour(), readOn(), and remplir_num_faces().
double DP_Impose_CoviMAC_Face::surf [protected]
Definition at line 60 of file DP_Impose_CoviMAC_Face.h.
Referenced by remplir_num_faces().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/DP_Impose_CoviMAC_Face.h
src/CoviMAC/Sources/DP_Impose_CoviMAC_Face.cpp