TRUST: ScalarRegister Class Reference
ScalarRegister Class Reference
: class ScalarRegister
Providing map of scalars associated with a name inside Probleme_U
Those are typically toggled through the ICoCo API (get/setInputIntValue() get/setDoubleValue()).
#include <ScalarRegister.h>
Public Member Functions
ScalarRegister ()
~ScalarRegister ()
int getOutputIntValue (const Nom &name) const
double getOutputDoubleValue (const Nom &name) const
void setInputIntValue (const Nom &name, const int &val)
void setInputDoubleValue (const Nom &name, const double &val)
Protected Attributes
std::map< std::string, int > int_reg
std::map< std::string, double > double_reg
Detailed Description
: class ScalarRegister
Providing map of scalars associated with a name inside Probleme_U
Those are typically toggled through the ICoCo API (get/setInputIntValue() get/setDoubleValue()).
Definition at line 31 of file ScalarRegister.h.
Constructor & Destructor Documentation
ScalarRegister()
ScalarRegister::ScalarRegister () inline
Definition at line 35 of file ScalarRegister.h.
{}
~ScalarRegister()
ScalarRegister::~ScalarRegister () inline
Definition at line 36 of file ScalarRegister.h.
{}
Member Function Documentation
getOutputDoubleValue()
double ScalarRegister::getOutputDoubleValue (const Nom & name) const
Definition at line 44 of file ScalarRegister.cpp.
{
  std::string nom = name.getString();
  if (double_reg.find(nom)!= double_reg.end())
    return double_reg.at(nom);
  else
    {
      Cerr << "Internal error, register double" << name << " does not exist" << finl;
      Process::exit(-1);
      return 0.;
    }
}
References Cerr, double_reg, Process::exit(), finl, and Nom::getString().
getOutputIntValue()
int ScalarRegister::getOutputIntValue (const Nom & name) const
Definition at line 31 of file ScalarRegister.cpp.
{
  std::string nom = name.getString();
  if (int_reg.find(nom)!= int_reg.end())
    return int_reg.at(nom);
  else
    {
      Cerr << "Internal error, register int" << name << " does not exist!" << finl;
      Process::exit(-1);
      return 0;
    }
}
References Cerr, Process::exit(), finl, Nom::getString(), and int_reg.
Referenced by Probleme_U::getOutputIntValue().
setInputDoubleValue()
void ScalarRegister::setInputDoubleValue (const Nom & name, const double & val)
Definition at line 25 of file ScalarRegister.cpp.
{
  std::string nom = name.getString();
  double_reg[nom] = val;
}
References double_reg, and Nom::getString().
setInputIntValue()
void ScalarRegister::setInputIntValue (const Nom & name, const int & val)
Definition at line 19 of file ScalarRegister.cpp.
{
  std::string nom = name.getString();
  int_reg[nom] = val;
}
References Nom::getString(), and int_reg.
Referenced by Probleme_U::setInputIntValue().
Member Data Documentation
double_reg
std::map<std::string, double> ScalarRegister::double_reg protected
Definition at line 47 of file ScalarRegister.h.
Referenced by getOutputDoubleValue(), and setInputDoubleValue().
int_reg
std::map<std::string, int> ScalarRegister::int_reg protected
Definition at line 46 of file ScalarRegister.h.
Referenced by getOutputIntValue(), and setInputIntValue().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/ScalarRegister.h
src/Kernel/Utilitaires/ScalarRegister.cpp