TRUST: Imprimer_flux_sum Class Reference
Imprimer_flux_sum Class Reference
#include <Imprimer_flux_sum.h>
Public Member Functions
Imprimer_flux_sum ()
~Imprimer_flux_sum ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Imprimer_flux_sum & self_cast (Objet_U &)
static const Imprimer_flux_sum & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 29 of file Imprimer_flux_sum.h.
Constructor & Destructor Documentation
Imprimer_flux_sum::Imprimer_flux_sum ()
Definition at line 28 of file Imprimer_flux_sum.cpp.
Imprimer_flux_sum::~Imprimer_flux_sum ()
Definition at line 28 of file Imprimer_flux_sum.cpp.
Member Function Documentation
Objet_U * Imprimer_flux_sum::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 28 of file Imprimer_flux_sum.cpp.
int Imprimer_flux_sum::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 28 of file Imprimer_flux_sum.cpp.
const Type_info * Imprimer_flux_sum::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Imprimer_flux_sum.cpp.
const Type_info * Imprimer_flux_sum::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Imprimer_flux_sum.cpp.
Entree & Imprimer_flux_sum::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 42 of file Imprimer_flux_sum.cpp.
References Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), Zone::Lire_Bords_a_imprimer_sum(), and Domaine::zone().
{
  associer_domaine(is);
  domaine().zone(0).Lire_Bords_a_imprimer_sum(is);
  return is;
}
Sortie & Imprimer_flux_sum::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file Imprimer_flux_sum.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Imprimer_flux_sum::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 37 of file Imprimer_flux_sum.cpp.
{
  return is;
}
Imprimer_flux_sum & Imprimer_flux_sum::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Imprimer_flux_sum.cpp.
const Imprimer_flux_sum & Imprimer_flux_sum::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Imprimer_flux_sum.cpp.
unsigned Imprimer_flux_sum::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 28 of file Imprimer_flux_sum.cpp.
Member Data Documentation
const Type_info Imprimer_flux_sum::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file Imprimer_flux_sum.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Imprimer_flux_sum.h
src/Kernel/Geometrie/Imprimer_flux_sum.cpp