TRUST: Sortie_libre_Pression_imposee_Orlansky Class Reference
Sortie_libre_Pression_imposee_Orlansky Class Reference
Sortie_libre_Pression_imposee_Orlansky
Cette classe derive de la classe Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition
de gradient de pression impose.
L'objet de type Champ_front le_champ_front contient le gradient
impose. La fonction flux_impose() renvoie une valeur de pression
a l'exterieur calculee a partir du gradient de pression impose
et de la pression a l'interieur du domaine.
#include <Sortie_libre_Pression_imposee_Orlansky.h>
Public Member Functions
Sortie_libre_Pression_imposee_Orlansky ()
~Sortie_libre_Pression_imposee_Orlansky ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void mettre_a_jour (double) override
Effectue une mise a jour en temps de la condition aux limites.
double flux_impose (int) const override
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
double flux_impose (int, int) const override
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Public Member Functions inherited from Neumann_sortie_libre
Neumann_sortie_libre ()
~Neumann_sortie_libre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & tab_ext () const override
DoubleTab & tab_ext () override
double val_ext (int i) const override
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
double val_ext (int i, int j) const override
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
Public Member Functions inherited from Neumann_val_ext
Neumann_val_ext ()
~Neumann_val_ext () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual const DoubleTab & tab_ext () const =0
virtual DoubleTab & tab_ext ()=0
virtual double val_ext (int i) const =0
virtual double val_ext (int i, int j) const =0
Public Member Functions inherited from Neumann
Neumann ()
~Neumann () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double flux_impose (int i) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
virtual double flux_impose (int i, int j) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sortie_libre_Pression_imposee_Orlansky & self_cast (Objet_U &)
static const Sortie_libre_Pression_imposee_Orlansky & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann_sortie_libre
static Objet_U * cree_instance ()
static const Type_info * info ()
static Neumann_sortie_libre & self_cast (Objet_U &)
static const Neumann_sortie_libre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann_val_ext
static const Type_info * info ()
static Neumann_val_ext & self_cast (Objet_U &)
static const Neumann_val_ext & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann
static const Type_info * info ()
static Neumann & self_cast (Objet_U &)
static const Neumann & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Neumann_sortie_libre
static const Type_info info_obj
Static Public Attributes inherited from Neumann_val_ext
static const Type_info info_obj
Static Public Attributes inherited from Neumann
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Champ_P0_VDF pression_interne
Ref_Champ_Face vitesse_interne
DoubleVect pression_temps_moins_un
DoubleVect pression_temps_moins_deux
DoubleVect pression_moins_un_temps_moins_un
DoubleVect pression_moins_un_temps_moins_deux
DoubleVect pression_moins_deux_temps_moins_un
DoubleVect pression_moins_un
DoubleVect pression_moins_deux
DoubleVect VPhiP
DoubleTab vitesse_temps_moins_un
DoubleTab vitesse_temps_moins_deux
DoubleTab vitesse_moins_un_temps_moins_un
DoubleTab vitesse_moins_un_temps_moins_deux
DoubleTab vitesse_moins_deux_temps_moins_un
DoubleTab vitesse_moins_un
DoubleTab vitesse_moins_deux
DoubleTab VPhiV
Protected Attributes inherited from Neumann_sortie_libre
Champ_front le_champ_ext
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Sortie_libre_Pression_imposee_Orlansky
Cette classe derive de la classe Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition
de gradient de pression impose.
L'objet de type Champ_front le_champ_front contient le gradient
impose. La fonction flux_impose() renvoie une valeur de pression
a l'exterieur calculee a partir du gradient de pression impose
et de la pression a l'interieur du domaine.
Definition at line 44 of file Sortie_libre_Pression_imposee_Orlansky.h.
Constructor & Destructor Documentation
Sortie_libre_Pression_imposee_Orlansky()
Sortie_libre_Pression_imposee_Orlansky::Sortie_libre_Pression_imposee_Orlansky ()
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
~Sortie_libre_Pression_imposee_Orlansky()
Sortie_libre_Pression_imposee_Orlansky::~Sortie_libre_Pression_imposee_Orlansky ()
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
Member Function Documentation
compatible_avec_discr()
int Sortie_libre_Pression_imposee_Orlansky::compatible_avec_discr (const Discretisation_base &) const override virtual
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 241 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  if ((discr.que_suis_je() == "VDF") || (discr.que_suis_je() == "VDF_Interface") || (discr.que_suis_je() == "VDF_Front_Tracking") )
    return 1;
  else
    {
      err_pas_compatible(discr);
      return 0;
    }
}
References Cond_lim_base::err_pas_compatible(), and Objet_U::que_suis_je().
compatible_avec_eqn()
int Sortie_libre_Pression_imposee_Orlansky::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
Returns
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 253 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
completer()
void Sortie_libre_Pression_imposee_Orlansky::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Definition at line 55 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  Cerr << "Sortie_libre_Pression_imposee_Orlansky::completer()" << finl;
  const Zone_Cl_dis_base& la_zone_Cl = zone_Cl_dis();
  const Equation_base& eqn = la_zone_Cl.equation();
  const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,eqn);
  const Zone_VDF& zone_vdf = ref_cast(Zone_VDF,eqn.zone_dis().valeur());
  const Champ_P0_VDF& pression = ref_cast(Champ_P0_VDF,eqn_hydr.pression().valeur());
  const Champ_Face& vitesse = ref_cast(Champ_Face,eqn_hydr.inconnue().valeur());
// const IntTab& face_voisins  = zone_vdf.face_voisins();
// const DoubleVect& volumes_entrelaces = zone_vdf.volumes_entrelaces();
// const DoubleVect& face_surfaces = zone_vdf.face_surfaces();
  la_zone_VDF = zone_vdf;
  pression_interne = pression;
  vitesse_interne = vitesse;
  const Front_VF& le_bord = ref_cast(Front_VF,frontiere_dis());
  int nb_faces_loc = le_bord.nb_faces();
// int ndeb = le_bord.num_premiere_face();
  le_champ_front.valeurs().resize(nb_faces_loc);
  le_champ_ext.valeurs().resize(nb_faces_loc, dimension);
  VPhiP.resize(nb_faces_loc);
  VPhiV.resize(nb_faces_loc, dimension);
  pression_temps_moins_un.resize(nb_faces_loc);
  pression_temps_moins_deux.resize(nb_faces_loc);
  pression_moins_un_temps_moins_un.resize(nb_faces_loc);
  pression_moins_un_temps_moins_deux.resize(nb_faces_loc);
  pression_moins_deux_temps_moins_un.resize(nb_faces_loc);
  pression_moins_un.resize(nb_faces_loc);
  pression_moins_deux.resize(nb_faces_loc);
  vitesse_temps_moins_un.resize(nb_faces_loc, dimension);
  vitesse_temps_moins_deux.resize(nb_faces_loc, dimension);
  vitesse_moins_un_temps_moins_un.resize(nb_faces_loc, dimension);
  vitesse_moins_un_temps_moins_deux.resize(nb_faces_loc, dimension);
  vitesse_moins_deux_temps_moins_un.resize(nb_faces_loc, dimension);
  vitesse_moins_un.resize(nb_faces_loc, dimension);
  vitesse_moins_deux.resize(nb_faces_loc, dimension);
  Cerr << "Sortie_libre_Pression_imposee_Orlansky::completer() ok" << finl;
}
References Cerr, Objet_U::dimension, MorEqn::equation(), finl, Cond_lim_base::frontiere_dis(), Navier_Stokes_std::inconnue(), la_zone_VDF, Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, Front_VF::nb_faces(), Navier_Stokes_std::pression(), pression_interne, pression_moins_deux, pression_moins_deux_temps_moins_un, pression_moins_un, pression_moins_un_temps_moins_deux, pression_moins_un_temps_moins_un, pression_temps_moins_deux, pression_temps_moins_un, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_front::valeurs(), vitesse_interne, vitesse_moins_deux, vitesse_moins_deux_temps_moins_un, vitesse_moins_un, vitesse_moins_un_temps_moins_deux, vitesse_moins_un_temps_moins_un, vitesse_temps_moins_deux, vitesse_temps_moins_un, VPhiP, VPhiV, Cond_lim_base::zone_Cl_dis(), and Equation_base::zone_dis().
cree_instance()
Objet_U * Sortie_libre_Pression_imposee_Orlansky::cree_instance () static
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
duplique()
int Sortie_libre_Pression_imposee_Orlansky::duplique () const override virtual
Reimplemented from Neumann_sortie_libre.
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
flux_impose() [1/2]
double Sortie_libre_Pression_imposee_Orlansky::flux_impose (int i) const override virtual
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 228 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  return le_champ_front.valeurs()(face);
}
References Cond_lim_base::le_champ_front, and Champ_front::valeurs().
flux_impose() [2/2]
double Sortie_libre_Pression_imposee_Orlansky::flux_impose (int i, int j) const override virtual
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 233 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  Cerr << "Sortie_libre_Pression_imposee_Orlansky::flux_impose(int  , int )" << finl;
  Cerr << "La pression est un scalaire." << finl;
  return 0.;
}
References Cerr, and finl.
get_info()
const Type_info * Sortie_libre_Pression_imposee_Orlansky::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
info()
const Type_info * Sortie_libre_Pression_imposee_Orlansky::info () static
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
mettre_a_jour()
void Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Neumann_sortie_libre.
Definition at line 99 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
// Cerr << "Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour("
// <<temps<<")"<<finl;
  Cond_lim_base::mettre_a_jour(temps);
  assert(pression_interne.non_nul());
  const Front_VF& le_bord = ref_cast(Front_VF,frontiere_dis());
  int ndeb = le_bord.num_premiere_face();
  int nb_faces_loc = le_bord.nb_faces();
  DoubleTab& pre_bord=le_champ_front.valeurs();
  DoubleTab& vit_ext=le_champ_ext.valeurs();
  const Zone_VDF& zvdf=ref_cast(Zone_VDF,
                                pression_interne->zone_dis_base());
  const DoubleTab& pre=pression_interne->valeurs();
  const DoubleTab& vitesse=vitesse_interne->valeurs();
  int face, compo;
  for (face=ndeb; face<ndeb+nb_faces_loc; face++)
    {
      int i=face-ndeb;
      int ori = zvdf.orientation(face);
      pression_temps_moins_deux(i)=pression_temps_moins_un(i);
      pression_temps_moins_un(i)=pre_bord(i);
      pression_moins_un_temps_moins_deux(i)=
        pression_moins_un_temps_moins_un(i);
      pression_moins_un_temps_moins_un(i)=pression_moins_un(i);
      pression_moins_deux_temps_moins_un(i)=pression_moins_deux(i);
      int elem_un=zvdf.face_voisins(face,0);
      if (elem_un < 0)
        elem_un=zvdf.face_voisins(face,1);
      int face_moins_un = zvdf.elem_faces(elem_un, ori);
      if (face_moins_un==face)
        face_moins_un = zvdf.elem_faces(elem_un, ori+dimension);
      pression_moins_un[i] = pre[elem_un];
      int elem_deux=zvdf.face_voisins(face_moins_un,0);
      if (elem_deux == elem_un)
        elem_deux=zvdf.face_voisins(face_moins_un,1);
      pression_moins_deux[i] = pre[elem_deux];
      double pre_m_un_t_m_deux=pression_moins_un_temps_moins_deux(i);
      double pre_m_deux_t_m_un=pression_moins_deux_temps_moins_un(i);
      double pre_m_un=pression_moins_un(i);
      if( pre_m_un_t_m_deux==pre_m_un )
        VPhiP(i)=0;
      else
        VPhiP(i)=(pre_m_un_t_m_deux-pre_m_un)/
                 (pre_m_un+pre_m_un_t_m_deux-2*pre_m_deux_t_m_un);
      if(VPhiP(i)<=1.e-24) VPhiP(i)=0.0;
      if(VPhiP(i)>1.) VPhiP(i)=1.0;
      assert(VPhiP(i)<1.e12);
      pre_bord[i] = (1-VPhiP(i))/(1+VPhiP(i))*pression_temps_moins_un(i)
                    +  (2*VPhiP(i)/(1+VPhiP(i)))*pression_moins_un(i);
    }
  Debog::verifier_bord("Orlansky::mettre_a_jour() : pre bord  : " , pre_bord,ndeb );
// Debog::verifier_bord("Orlansky::mettre_a_jour() : VPhiP  : " , VPhiP, ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() : VPhiV  avant : " , VPhiV ,ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() : vitesse_moins_un_temps_moins_un : " , vitesse_moins_un_temps_moins_un, ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() : vitesse_moins_deux : " , vitesse_moins_deux, ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() : vitesse_moins_un : " , vitesse_moins_un, ndeb);
  for(compo=0; compo<dimension; compo++)
    for (face=ndeb; face<ndeb+nb_faces_loc; face++)
      {
        int i=face-ndeb;
        int ori = zvdf.orientation(face);
        vitesse_temps_moins_deux(i, compo)=vitesse_temps_moins_un(i, compo);
        vitesse_temps_moins_un(i, compo)=vit_ext(i, compo);
        vitesse_moins_un_temps_moins_deux(i, compo)=vitesse_moins_un_temps_moins_un(i, compo);
        vitesse_moins_un_temps_moins_un(i, compo)=vitesse_moins_un(i, compo);
        vitesse_moins_deux_temps_moins_un(i, compo)=vitesse_moins_deux(i, compo);
        int elem_un=zvdf.face_voisins(face,0);
        if (elem_un < 0)
          elem_un=zvdf.face_voisins(face,1);
        int face_moins_un = zvdf.elem_faces(elem_un, ori);
        if (face_moins_un==face)
          face_moins_un = zvdf.elem_faces(elem_un, ori+dimension);
        double vit=0.5*(vitesse(zvdf.elem_faces(elem_un, compo))
                        +vitesse(zvdf.elem_faces(elem_un, compo+dimension)));
        vitesse_moins_un(i, compo) = vit;
        int elem_deux=zvdf.face_voisins(face_moins_un,0);
        if (elem_deux == elem_un)
          elem_deux=zvdf.face_voisins(face_moins_un,1);
        vit=0.5*(vitesse(zvdf.elem_faces(elem_deux, compo))
                 +vitesse(zvdf.elem_faces(elem_deux, compo+dimension)));
        vitesse_moins_deux(i, compo) = vit;
        double pre_m_un_t_m_deux=vitesse_moins_un_temps_moins_deux(i, compo);
        double pre_m_deux_t_m_un=vitesse_moins_deux_temps_moins_un(i, compo);
        double pre_m_un=vitesse_moins_un(i, compo);
        if( pre_m_un_t_m_deux==pre_m_un )
          VPhiV(i, compo)=0;
        else
          VPhiV(i, compo)=(pre_m_un_t_m_deux-pre_m_un)/
                          (pre_m_un+pre_m_un_t_m_deux-2*pre_m_deux_t_m_un);
        if(VPhiV(i, compo)<=1.e-24) VPhiV(i, compo)=0.0;
        if(VPhiV(i, compo)>1.) VPhiV(i, compo)=1.0;
        assert(VPhiV(i, compo)<1.e12);
        vit_ext(i, compo) = (1-VPhiV(i, compo))/(1+VPhiV(i, compo))*vitesse_temps_moins_un(i, compo)
                            +  (2*VPhiV(i, compo)/(1+VPhiV(i, compo)))*vitesse_moins_un(i, compo);
      }
  Debog::verifier_bord("Orlansky::mettre_a_jour() :  vit_ext : " , vit_ext,ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() : vitesse_moins_un  : " ,vitesse_moins_un ,ndeb);
// Debog::verifier_bord("Orlansky::mettre_a_jour() :  vitesse_moins_deux : " ,vitesse_moins_deux ,ndeb);
  Debog::verifier_bord("Orlansky::mettre_a_jour() : VPhiV  : " , VPhiV ,ndeb);
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, Cond_lim_base::mettre_a_jour(), Front_VF::nb_faces(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), pression_interne, pression_moins_deux, pression_moins_deux_temps_moins_un, pression_moins_un, pression_moins_un_temps_moins_deux, pression_moins_un_temps_moins_un, pression_temps_moins_deux, pression_temps_moins_un, ref_cast, Champ_front::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier_bord(), vitesse_interne, vitesse_moins_deux, vitesse_moins_deux_temps_moins_un, vitesse_moins_un, vitesse_moins_un_temps_moins_deux, vitesse_moins_un_temps_moins_un, vitesse_temps_moins_deux, vitesse_temps_moins_un, VPhiP, VPhiV, and Champ_P0_VDF::zone_dis_base().
printOn()
Sortie & Sortie_libre_Pression_imposee_Orlansky::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Sortie_libre_Pression_imposee_Orlansky::readOn (Entree & s) override protected virtual
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 37 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
{
  le_champ_ext.typer("Champ_front_uniforme");
  le_champ_ext.valeurs().resize(1,dimension);
  le_champ_front.typer("Champ_front_uniforme");
  le_champ_front.valeurs().resize(1,dimension);
  le_champ_front->fixer_nb_comp(1);
  return s;
}
References Objet_U::dimension, Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, TRUSTTab< _TYPE_ >::resize(), Deriv_::typer(), and Champ_front::valeurs().
self_cast() [1/2]
const Sortie_libre_Pression_imposee_Orlansky & Sortie_libre_Pression_imposee_Orlansky::self_cast (const Objet_U & r) static
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
self_cast() [2/2]
Sortie_libre_Pression_imposee_Orlansky & Sortie_libre_Pression_imposee_Orlansky::self_cast (Objet_U & r) static
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
taille_memoire()
unsigned Sortie_libre_Pression_imposee_Orlansky::taille_memoire () const override virtual
Reimplemented from Neumann_sortie_libre.
Definition at line 24 of file Sortie_libre_Pression_imposee_Orlansky.cpp.
Member Data Documentation
info_obj
const Type_info Sortie_libre_Pression_imposee_Orlansky::info_obj static
Definition at line 47 of file Sortie_libre_Pression_imposee_Orlansky.h.
la_zone_VDF
Ref_Zone_VDF Sortie_libre_Pression_imposee_Orlansky::la_zone_VDF protected
Definition at line 60 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer().
pression_interne
Ref_Champ_P0_VDF Sortie_libre_Pression_imposee_Orlansky::pression_interne protected
Definition at line 61 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_moins_deux
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_moins_deux protected
Definition at line 70 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_moins_deux_temps_moins_un
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_moins_deux_temps_moins_un protected
Definition at line 68 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_moins_un
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_moins_un protected
Definition at line 69 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_moins_un_temps_moins_deux
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_moins_un_temps_moins_deux protected
Definition at line 67 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_moins_un_temps_moins_un
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_moins_un_temps_moins_un protected
Definition at line 66 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_temps_moins_deux
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_temps_moins_deux protected
Definition at line 65 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
pression_temps_moins_un
DoubleVect Sortie_libre_Pression_imposee_Orlansky::pression_temps_moins_un protected
Definition at line 64 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_interne
Ref_Champ_Face Sortie_libre_Pression_imposee_Orlansky::vitesse_interne protected
Definition at line 62 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_moins_deux
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_moins_deux protected
Definition at line 79 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_moins_deux_temps_moins_un
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_moins_deux_temps_moins_un protected
Definition at line 77 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_moins_un
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_moins_un protected
Definition at line 78 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_moins_un_temps_moins_deux
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_moins_un_temps_moins_deux protected
Definition at line 76 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_moins_un_temps_moins_un
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_moins_un_temps_moins_un protected
Definition at line 75 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_temps_moins_deux
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_temps_moins_deux protected
Definition at line 74 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
vitesse_temps_moins_un
DoubleTab Sortie_libre_Pression_imposee_Orlansky::vitesse_temps_moins_un protected
Definition at line 73 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
VPhiP
DoubleVect Sortie_libre_Pression_imposee_Orlansky::VPhiP protected
Definition at line 71 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
VPhiV
DoubleTab Sortie_libre_Pression_imposee_Orlansky::VPhiV protected
Definition at line 80 of file Sortie_libre_Pression_imposee_Orlansky.h.
Referenced by completer(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VDF/Cond_Lim/Sortie_libre_Pression_imposee_Orlansky.h
src/VDF/Cond_Lim/Sortie_libre_Pression_imposee_Orlansky.cpp