TRUST: Champ_implementation Class Reference
Champ_implementation Class Reference abstract
#include <Champ_implementation.h>
Public Member Functions
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Protected Member Functions
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Detailed Description
Definition at line 27 of file Champ_implementation.h.
Constructor & Destructor Documentation
~Champ_implementation()
virtual Champ_implementation::~Champ_implementation () inline virtual
Definition at line 30 of file Champ_implementation.h.
{ }
Member Function Documentation
le_champ() [1/2]
virtual const Champ_base & Champ_implementation::le_champ () const protected pure virtual
Implemented in Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, and Champ_Q1NC.
Referenced by Champ_Q1NC_impl::calcule_valeur_a_elem_compo(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_Face_implementation::imprime_Face(), Champ_P1NC_implementation::imprime_P1NC(), Champ_Q4_implementation::imprime_Q4(), Champ_P1NC_implementation::nb_colonnes(), Champ_P1NC_implementation::nb_colonnes_tot(), Champ_Q4_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_impl::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_impl::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), and zone_dis_base().
le_champ() [2/2]
virtual Champ_base & Champ_implementation::le_champ () protected pure virtual
Implemented in Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, and Champ_Q1NC.
remplir_coord_noeuds()
virtual DoubleTab & Champ_implementation::remplir_coord_noeuds (DoubleTab & positions) const pure virtual
Implemented in Champ_P1_isoP1Bulle, Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_impl.
remplir_coord_noeuds_et_polys()
virtual int Champ_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_impl.
valeur_a_elem()
virtual DoubleVect & Champ_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_impl.
valeur_a_elem_compo()
virtual double Champ_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_impl.
valeur_aux_elems()
virtual DoubleTab & Champ_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const pure virtual
Implemented in Champ_Fonc_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q4_implementation, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face_implementation, Champ_P1NC_implementation, and Champ_Q1NC_impl.
valeur_aux_elems_compo()
virtual DoubleVect & Champ_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const pure virtual
Implemented in Champ_Fonc_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q4_implementation, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face_implementation, Champ_P1NC_implementation, and Champ_Q1NC_impl.
valeur_aux_sommets()
virtual DoubleTab & Champ_implementation::valeur_aux_sommets (const Domaine & , DoubleTab &) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q1NC_impl, and Champ_P1NC_implementation.
valeur_aux_sommets_compo()
virtual DoubleVect & Champ_implementation::valeur_aux_sommets_compo (const Domaine & , DoubleVect & , int) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_Face, Champ_Face_implementation, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q1NC_impl, and Champ_P1NC_implementation.
zone()
const Zone & Champ_implementation::zone () const protected
Definition at line 24 of file Champ_implementation.cpp.
{
  return zone_dis_base().zone();
}
References Zone_dis_base::zone(), and zone_dis_base().
Referenced by Champ_P1NC::calculer_integrale_volumique(), Champ_Q4_implementation::imprime_Q4(), Champ_Q4_implementation::remplir_coord_noeuds(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Champ_Q4_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_Q1NC_impl::valeur_a_sommet_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), and Champ_P1NC_implementation::valeur_aux_sommets().
zone_dis_base()
const Zone_dis_base & Champ_implementation::zone_dis_base () const protected virtual
Reimplemented in Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, and Champ_Q1NC.
Definition at line 28 of file Champ_implementation.cpp.
{
  const Champ_base& chbase=le_champ();
  if(sub_type(Champ_Inc_base, chbase))
    {
      const Champ_Inc_base& chi=ref_cast(Champ_Inc_base, chbase);
      return chi.zone_dis_base();
    }
  else if(sub_type(Champ_Fonc_base, chbase))
    {
      const Champ_Fonc_base& chf=ref_cast(Champ_Fonc_base, chbase);
      return chf.zone_dis_base();
    }
  else
    {
      Cerr << le_champ().que_suis_je() << "do not know refer a Zone_dis_base" << finl;
      Process::exit();
// Pour les compilos :
      return zone_dis_base();
    }
}
References Cerr, Process::exit(), finl, le_champ(), Objet_U::que_suis_je(), ref_cast, sub_type, zone_dis_base(), and Champ_base::zone_dis_base().
Referenced by Champ_Face_implementation::remplir_coord_noeuds(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), zone(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation.h
src/Kernel/Champs_dis/Champ_implementation.cpp