TRUST: Fluide_Quasi_Compressible Class Reference
Fluide_Quasi_Compressible Class Reference
classe Fluide_Quasi_Compressible
Cette classe represente un d'un fluide quasi compressible
c'est a dire heritant de fluide dilatable
#include <Fluide_Quasi_Compressible.h>
Public Member Functions
~Fluide_Quasi_Compressible ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Quasi_Compressible ()
void set_param (Param &param) override
void completer (const Probleme_base &) override
Complete le fluide avec les champs inconnus associes au probleme.
void preparer_pas_temps () override
Prepare le pas de temps.
void prepare_pressure_edo () override
void write_mean_edo (double) override
void checkTraitementPth (const Zone_Cl_dis &zone_cl) override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void Resoudre_EDO_PT ()
void secmembre_divU_Z (DoubleTab &) const override
int get_traitement_rho_gravite () const
double masse_totale (double P, const DoubleTab &T)
Public Member Functions inherited from Fluide_Dilatable_base
~Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Dilatable_base ()
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
void set_Cp (double)
Complete le fluide avec un Cp constant.
void update_rho_cp (double temps) override
void creer_champs_non_lus () override
void initialiser_radiatives (const double temps)
void warn_syntax_Sutherland ()
int initialiser (const double temps) override
Initialise les parametres du fluide.
const DoubleTab & temperature () const
Renvoie le tableau des valeurs de le temperature.
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
Champ_Don & ch_temperature ()
virtual void calculer_pression_tot ()
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
virtual void preparer_pas_temps ()
Prepare le pas de temps.
void abortTimeStep () override
void set_param (Param &param) override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void mettre_a_jour (double) override
virtual void update_pressure_fields (double)
void preparer_calcul () override
Prepare le fluide au calcul.
virtual void completer (const Probleme_base &)
Complete le fluide avec les champs inconnus associes au probleme.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void checkTraitementPth (const Zone_Cl_dis &)=0
virtual void prepare_pressure_edo ()=0
virtual void write_mean_edo (double)=0
virtual void secmembre_divU_Z (DoubleTab &) const =0
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Nom type_fluide () const
const Loi_Etat & loi_etat () const
Loi_Etat & loi_etat ()
const Champ_Inc & inco_chaleur () const
Champ_Inc & inco_chaleur ()
const Champ_Inc & vitesse () const
const Champ_Don & pression_tot () const
Champ_Don & pression_tot ()
const Champ_Don & mu_sur_Schmidt () const
Champ_Don & mu_sur_Schmidt ()
const Champ_Don & nu_sur_Schmidt () const
Champ_Don & nu_sur_Schmidt ()
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
void calculer_coeff_T ()
void initialiser_inco_ch ()
void calculer_Cp ()
void calculer_lambda ()
void calculer_mu ()
void calculer_nu () override
void calculer_alpha () override
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void calculer_mu_sur_Sc ()
void calculer_nu_sur_Sc ()
void calculer_masse_volumique ()
void set_pression_th (double Pth)
int getTraitementPth () const
double pression_th () const
Pression thermodynamique.
double pression_thn () const
Pression thermodynamique a l'etape precedente.
double pression_th1 () const
Pression thermodynamique calculee pour conserver la masse.
double calculer_H (double hh) const
Probleme_base & get_problem ()
const DoubleTab & rho_discvit () const
const DoubleTab & rho_face_n () const
const DoubleTab & rho_face_np1 () const
void calculer_rho_face (const DoubleTab &tab_rho)
void divu_discvit (DoubleTab &secmem1, DoubleTab &secmem2)
double moyenne_vol (const DoubleTab &A) const
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_Quasi_Compressible & self_cast (Objet_U &)
static const Fluide_Quasi_Compressible & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_Dilatable_base
static const Type_info * info ()
static Fluide_Dilatable_base & self_cast (Objet_U &)
static const Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_Dilatable_base
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
virtual void remplir_champ_pression_tot (int n, const DoubleTab &PHydro, DoubleTab &PTot)=0
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int traitement_rho_gravite_
0 : gravite = rho*g, 1 : gravite =(rho-rho_moy)*g
double temps_debut_prise_en_compte_drho_dt_
double omega_drho_dt_
EDO_Pression_th EDO_Pth_
Nom output_file_
DoubleTab tab_W_old_
Protected Attributes inherited from Fluide_Dilatable_base
int traitement_PTh
flag pour le traitement de la pression thermo
double Pth_
double Pth_n
double Pth1
Ref_Champ_Inc inco_chaleur_
Ref_Champ_Inc vitesse_
Ref_Champ_Inc pression_
Ref_Probleme_base le_probleme_
Champ_Don pression_tot_
Champ_Don mu_sur_Sc
Champ_Don nu_sur_Sc
Champ_Don rho_gaz
Champ_Don rho_comme_v
Loi_Etat loi_etat_
EOS_Tools eos_tools_
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Private Member Functions
void completer_edo (const Probleme_base &)
void remplir_champ_pression_tot (int n, const DoubleTab &PHydro, DoubleTab &PTot) override
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Detailed Description
classe Fluide_Quasi_Compressible
Cette classe represente un d'un fluide quasi compressible
c'est a dire heritant de fluide dilatable
Definition at line 35 of file Fluide_Quasi_Compressible.h.
Constructor & Destructor Documentation
~Fluide_Quasi_Compressible()
Fluide_Quasi_Compressible::~Fluide_Quasi_Compressible ()
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
Fluide_Quasi_Compressible()
Fluide_Quasi_Compressible::Fluide_Quasi_Compressible ()
Definition at line 47 of file Fluide_Quasi_Compressible.cpp.
                                                     : traitement_rho_gravite_(0),
  temps_debut_prise_en_compte_drho_dt_(-DMAXFLOAT),omega_drho_dt_(1.) { }
Member Function Documentation
checkTraitementPth()
void Fluide_Quasi_Compressible::checkTraitementPth (const Zone_Cl_dis & zone_cl) override virtual
Implements Fluide_Dilatable_base.
Definition at line 63 of file Fluide_Quasi_Compressible.cpp.
{
  /*
   * traitement_PTh=0 => resolution classique de l'edo
   * traitement_PTh=1 => pression calculee pour conserver la masse
   * traitement_PTh=2 => pression laissee cste.
   */
  if (traitement_PTh==0)
    {
      /* Do nothing*/
    }
  else
    {
      int pression_imposee=0;
      int size=zone_cl.les_conditions_limites().size();
      assert(size!=0);
      for (int n=0; n<size; n++)
        {
          const Cond_lim& la_cl = zone_cl.les_conditions_limites(n);
          if (sub_type(Neumann_sortie_libre, la_cl.valeur())) pression_imposee=1;
        }
      if (pression_imposee && traitement_PTh!=2)
        {
          if (Process::je_suis_maitre())
            {
              Cerr << "The Traitement_Pth option selected is not coherent with the boundaries conditions." << finl;
              Cerr << "Traitement_Pth constant must be used for the case of free outlet." << finl;
            }
          Process::exit();
        }
      if (!pression_imposee && traitement_PTh!=1)
        {
          if (Process::je_suis_maitre())
            {
              Cerr << "The Traitement_Pth option selected is not coherent with the boundaries conditions." << finl;
              Cerr << "Traitement_Pth conservation_masse must be used for the case without free outlet." << finl;
            }
          Process::exit();
        }
    }
}
References Cerr, Process::exit(), finl, Process::je_suis_maitre(), Zone_Cl_dis::les_conditions_limites(), sub_type, Fluide_Dilatable_base::traitement_PTh, and Deriv_Cond_lim_base::valeur().
Referenced by EDO_Pression_th_VDF::completer(), and EDO_Pression_th_VEF::completer().
completer()
void Fluide_Quasi_Compressible::completer (const Probleme_base & pb) override virtual
Complete le fluide avec les champs inconnus associes au probleme.
Reimplemented from Fluide_Dilatable_base.
Definition at line 183 of file Fluide_Quasi_Compressible.cpp.
{
  Cerr<<"Fluide_Quasi_Compressible::completer Pth = " << Pth_ << finl;
  if ((loi_etat_->que_suis_je() == "Loi_Etat_rhoT_Gaz_Parfait_QC" || loi_etat_->que_suis_je() == "Loi_Etat_Binaire_Gaz_Parfait_QC" )
      && traitement_PTh == 0)
    {
      Cerr << "The option Traitement_PTh EDO is not allowed with the state law " << loi_etat_->que_suis_je() << finl;
      Cerr << "Set **traitement_pth** constant or conservation_masse in the Fluide_Quasi_Compressible bloc definition." << finl;
      Process::exit();
    }
  Fluide_Dilatable_base::completer(pb);
  if (traitement_PTh != 2) completer_edo(pb);
}
References Cerr, Fluide_Dilatable_base::completer(), completer_edo(), Process::exit(), finl, Fluide_Dilatable_base::loi_etat_, Fluide_Dilatable_base::Pth_, Objet_U::que_suis_je(), and Fluide_Dilatable_base::traitement_PTh.
completer_edo()
void Fluide_Quasi_Compressible::completer_edo (const Probleme_base & pb) private
Definition at line 256 of file Fluide_Quasi_Compressible.cpp.
{
  assert(traitement_PTh != 2);
  Nom typ = pb.equation(0).discretisation().que_suis_je();
  if (typ=="VEFPreP1B") typ = "VEF";
  typ += "_";
// EDO_Pression_th_VDF/VEF_Melange_Binaire not implemented yet
// typer Gaz_Parfait instead to use when traitement_PTh=1...
  if (pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_QC" || pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_Turbulent_QC")
    typ +="Gaz_Parfait";
  else
    typ += loi_etat_->type_fluide();
  EDO_Pth_.typer(typ);
  EDO_Pth_->associer_zones(pb.equation(0).zone_dis(),pb.equation(0).zone_Cl_dis());
  EDO_Pth_->associer_fluide(*this);
  EDO_Pth_->mettre_a_jour_CL(Pth_);
// Write in file
  output_file_ = Objet_U::nom_du_cas();
  output_file_ += "_";
  output_file_ += pb.le_nom();
  output_file_ += ".evol_glob";
  Cerr << "Warning! evol_glob file renamed " << output_file_ << finl;
  if(je_suis_maitre())
    {
      SFichier fic (output_file_);
      fic<<"# Time sum(T*dv)/sum(dv)[K] sum(rho*dv)/sum(dv)[kg/m3] Pth[Pa]"<<finl;
    }
}
References Cerr, Equation_base::discretisation(), EDO_Pth_, Probleme_base::equation(), finl, Process::je_suis_maitre(), Probleme_base::le_nom(), Fluide_Dilatable_base::loi_etat_, Objet_U::nom_du_cas(), output_file_, Fluide_Dilatable_base::Pth_, Objet_U::que_suis_je(), Fluide_Dilatable_base::traitement_PTh, EDO_Pression_th::typer(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by completer().
cree_instance()
Objet_U * Fluide_Quasi_Compressible::cree_instance () static
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
discretiser()
void Fluide_Quasi_Compressible::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_Dilatable_base.
Definition at line 218 of file Fluide_Quasi_Compressible.cpp.
{
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
  double temps=pb.schema_temps().temps_courant();
// In *_Melange_Binaire_QC we do not even have a temperature variable ...
// it is the species mass fraction Y1... Although named ch_temperature
  Champ_Don& ch_TK = ch_temperature();
  if (pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_QC" || pb.que_suis_je()=="Pb_Hydraulique_Melange_Binaire_Turbulent_QC")
    dis.discretiser_champ("temperature",zone_dis,"fraction_massique","neant",1,temps,ch_TK);
  else
    dis.discretiser_champ("temperature",zone_dis,"temperature","K",1,temps,ch_TK);
  if (type_fluide()!="Gaz_Parfait")
    loi_etat().valeur().champs_compris().ajoute_champ(ch_TK);
  Fluide_Dilatable_base::discretiser(pb,dis);
}
References Champs_compris::ajoute_champ(), Fluide_Dilatable_base::ch_temperature(), Loi_Etat_base::champs_compris(), Fluide_Dilatable_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), Fluide_Dilatable_base::loi_etat(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Fluide_Dilatable_base::type_fluide(), Deriv_Loi_Etat_base::valeur(), and Equation_base::zone_dis().
duplique()
int Fluide_Quasi_Compressible::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
get_info()
const Type_info * Fluide_Quasi_Compressible::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
get_traitement_rho_gravite()
int Fluide_Quasi_Compressible::get_traitement_rho_gravite () const inline
Definition at line 52 of file Fluide_Quasi_Compressible.h.
{ return traitement_rho_gravite_; }
References traitement_rho_gravite_.
Referenced by Source_QC_Gravite_VEF::ajouter(), and Source_QC_Gravite_VDF::ajouter_blocs().
info()
const Type_info * Fluide_Quasi_Compressible::info () static
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
lire_motcle_non_standard()
int Fluide_Quasi_Compressible::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Fluide_Dilatable_base.
Definition at line 117 of file Fluide_Quasi_Compressible.cpp.
{
  if (mot=="pression")
    {
      is>>Pth_;
      Pth_n = Pth_;
      rho.typer("Champ_Uniforme");
      DoubleTab& tab_rho=rho.valeurs();
      tab_rho.resize(1,1);
      tab_rho(0,0) = 1.;
      return 1;
    }
  else if (mot=="Traitement_PTh")
    {
      Motcle trait;
      is >> trait;
      Motcles les_options(3);
      {
        les_options[0] = "edo";
        les_options[1] = "conservation_masse";
        les_options[2] = "constant";
      }
      traitement_PTh=les_options.search(trait);
      if (traitement_PTh == -1)
        {
          Cerr<< trait << " is not understood as an option of the keyword " << mot <<finl;
          Cerr<< "One of the following options was expected : " << les_options << finl;
          Process::exit();
        }
      return 1;
    }
  else if (mot=="Traitement_rho_gravite")
    {
      Motcle trait;
      is >> trait;
      Motcles les_options(2);
      {
        les_options[0] = "standard";
        les_options[1] = "moins_rho_moyen";
      }
      traitement_rho_gravite_=les_options.search(trait);
      if (traitement_rho_gravite_ == -1)
        {
          Cerr<< trait << " is not understood as an option of the keyword " << mot <<finl;
          Cerr<< "One of the following options was expected : " << les_options << finl;
          Process::exit();
        }
      return 1;
    }
  else return Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
}
References Cerr, Process::exit(), finl, Fluide_Dilatable_base::lire_motcle_non_standard(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n, TRUSTTab< _TYPE_ >::resize(), Milieu_base::rho, Motcles::search(), Fluide_Dilatable_base::traitement_PTh, traitement_rho_gravite_, Deriv_::typer(), and Champ::valeurs().
masse_totale()
double Fluide_Quasi_Compressible::masse_totale (double P, const DoubleTab & T) inline
Definition at line 53 of file Fluide_Quasi_Compressible.h.
{ return EDO_Pth_->masse_totale(P, T); }
References EDO_Pth_.
prepare_pressure_edo()
void Fluide_Quasi_Compressible::prepare_pressure_edo () override virtual
Implements Fluide_Dilatable_base.
Definition at line 237 of file Fluide_Quasi_Compressible.cpp.
{
  if (traitement_PTh != 2) EDO_Pth_->completer();
  eos_tools_->mettre_a_jour(le_probleme_->schema_temps().temps_courant());
}
References EDO_Pth_, Fluide_Dilatable_base::eos_tools_, Fluide_Dilatable_base::le_probleme_, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and Fluide_Dilatable_base::traitement_PTh.
preparer_pas_temps()
void Fluide_Quasi_Compressible::preparer_pas_temps () override virtual
Prepare le pas de temps.
Reimplemented from Fluide_Dilatable_base.
Definition at line 212 of file Fluide_Quasi_Compressible.cpp.
{
  Fluide_Dilatable_base::preparer_pas_temps();
  if (traitement_PTh != 2 ) EDO_Pth_->mettre_a_jour_CL(Pth_);
}
References EDO_Pth_, Fluide_Dilatable_base::preparer_pas_temps(), Fluide_Dilatable_base::Pth_, and Fluide_Dilatable_base::traitement_PTh.
printOn()
Sortie & Fluide_Quasi_Compressible::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 50 of file Fluide_Quasi_Compressible.cpp.
{
  os << que_suis_je() << finl;
  Fluide_Dilatable_base::ecrire(os);
  return os;
}
References Milieu_base::ecrire(), finl, and Objet_U::que_suis_je().
readOn()
Entree & Fluide_Quasi_Compressible::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Fluide_Dilatable_base.
Definition at line 57 of file Fluide_Quasi_Compressible.cpp.
{
  Fluide_Dilatable_base::readOn(is);
  return is;
}
References Fluide_Dilatable_base::readOn().
remplir_champ_pression_tot()
void Fluide_Quasi_Compressible::remplir_champ_pression_tot (int n, const DoubleTab & PHydro, DoubleTab & PTot) override private virtual
Implements Fluide_Dilatable_base.
Definition at line 288 of file Fluide_Quasi_Compressible.cpp.
{
  for (int i=0 ; i<n ; i++) PTot(i,0) = PHydro(i,0) + Pth_;
}
References Fluide_Dilatable_base::Pth_.
Resoudre_EDO_PT()
void Fluide_Quasi_Compressible::Resoudre_EDO_PT () inline
Definition at line 67 of file Fluide_Quasi_Compressible.h.
{
  Pth_n = Pth_;
  if (traitement_PTh != 2)
    {
      Pth_ = EDO_Pth_->resoudre(Pth_);
      if (Pth_<=0)
        {
          Cerr<<"Error : the pressure calculated by Resoudre_EDO_PT method is negative : "<< Pth_ << finl;
          abort();
        }
      EDO_Pth_->mettre_a_jour_CL(Pth_);
    }
}
References Process::abort(), Cerr, EDO_Pth_, finl, Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n, and Fluide_Dilatable_base::traitement_PTh.
Referenced by Pb_QC_base::solve_pressure_thermo().
secmembre_divU_Z()
void Fluide_Quasi_Compressible::secmembre_divU_Z (DoubleTab & tab_W) const inline override virtual
< Relaxation eventuelle:
Implements Fluide_Dilatable_base.
Definition at line 86 of file Fluide_Quasi_Compressible.h.
{
  double temps=vitesse_->temps();
  if (temps>temps_debut_prise_en_compte_drho_dt_)
    {
      eos_tools_->secmembre_divU_Z(tab_W);
      if (tab_W_old_.size_totale() > 0) //!< Relaxation eventuelle:
        {
          tab_W *= omega_drho_dt_;
          tab_W.ajoute_sans_ech_esp_virt(1-omega_drho_dt_, tab_W_old_);
        }
      tab_W_old_ = tab_W;
    }
  else
    {
      if (je_suis_maitre())
        Cerr<<" The drho_dt term is not taken into account for time smaller than " <<temps_debut_prise_en_compte_drho_dt_<<finl;
      tab_W=0;
    }
}
References TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), Cerr, Fluide_Dilatable_base::eos_tools_, finl, Process::je_suis_maitre(), omega_drho_dt_, TRUSTVect< _TYPE_ >::size_totale(), tab_W_old_, Champ_Inc::temps(), temps_debut_prise_en_compte_drho_dt_, and Fluide_Dilatable_base::vitesse_.
self_cast() [1/2]
const Fluide_Quasi_Compressible & Fluide_Quasi_Compressible::self_cast (const Objet_U & r) static
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
self_cast() [2/2]
Fluide_Quasi_Compressible & Fluide_Quasi_Compressible::self_cast (Objet_U & r) static
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
set_param()
void Fluide_Quasi_Compressible::set_param (Param & param) override virtual
Reimplemented from Fluide_Dilatable_base.
Definition at line 108 of file Fluide_Quasi_Compressible.cpp.
{
  Fluide_Dilatable_base::set_param(param);
  param.ajouter("temps_debut_prise_en_compte_drho_dt",&temps_debut_prise_en_compte_drho_dt_);
  param.ajouter("omega_relaxation_drho_dt",&omega_drho_dt_);
  param.ajouter_non_std("pression",(this),Param::REQUIRED);
  param.ajouter_non_std("Traitement_rho_gravite",(this));
}
References Param::ajouter(), Param::ajouter_non_std(), omega_drho_dt_, Param::REQUIRED, Fluide_Dilatable_base::set_param(), and temps_debut_prise_en_compte_drho_dt_.
taille_memoire()
unsigned Fluide_Quasi_Compressible::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Fluide_Quasi_Compressible.cpp.
write_mean_edo()
void Fluide_Quasi_Compressible::write_mean_edo (double temps) override virtual
Implements Fluide_Dilatable_base.
Definition at line 244 of file Fluide_Quasi_Compressible.cpp.
{
  double Ch_m = eos_tools_->moyenne_vol(inco_chaleur_->valeurs());
  double rhom = eos_tools_->moyenne_vol(rho.valeurs());
  if(je_suis_maitre() && traitement_PTh != 2)
    {
      SFichier fic (output_file_,ios::app);
      fic<<temps <<" "<<Ch_m<<" "<<rhom<<" "<<Pth_<<finl;
    }
}
References Fluide_Dilatable_base::eos_tools_, finl, Fluide_Dilatable_base::inco_chaleur_, Process::je_suis_maitre(), output_file_, Fluide_Dilatable_base::Pth_, Milieu_base::rho, Fluide_Dilatable_base::traitement_PTh, Champ::valeurs(), and Champ_Inc::valeurs().
Member Data Documentation
EDO_Pth_
EDO_Pression_th Fluide_Quasi_Compressible::EDO_Pth_ protected
Definition at line 58 of file Fluide_Quasi_Compressible.h.
Referenced by completer_edo(), masse_totale(), prepare_pressure_edo(), preparer_pas_temps(), and Resoudre_EDO_PT().
info_obj
const Type_info Fluide_Quasi_Compressible::info_obj static
Definition at line 37 of file Fluide_Quasi_Compressible.h.
omega_drho_dt_
double Fluide_Quasi_Compressible::omega_drho_dt_ protected
Definition at line 57 of file Fluide_Quasi_Compressible.h.
Referenced by secmembre_divU_Z(), and set_param().
output_file_
Nom Fluide_Quasi_Compressible::output_file_ protected
Definition at line 59 of file Fluide_Quasi_Compressible.h.
Referenced by completer_edo(), and write_mean_edo().
tab_W_old_
DoubleTab Fluide_Quasi_Compressible::tab_W_old_ mutable protected
Definition at line 60 of file Fluide_Quasi_Compressible.h.
Referenced by secmembre_divU_Z().
temps_debut_prise_en_compte_drho_dt_
double Fluide_Quasi_Compressible::temps_debut_prise_en_compte_drho_dt_ protected
Definition at line 57 of file Fluide_Quasi_Compressible.h.
Referenced by secmembre_divU_Z(), and set_param().
traitement_rho_gravite_
int Fluide_Quasi_Compressible::traitement_rho_gravite_ protected
0 : gravite = rho*g, 1 : gravite =(rho-rho_moy)*g
Definition at line 56 of file Fluide_Quasi_Compressible.h.
Referenced by get_traitement_rho_gravite(), and lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Milieu/Fluide_Quasi_Compressible.h
src/ThHyd/Dilatable/Quasi_Compressible/Milieu/Fluide_Quasi_Compressible.cpp