TRUST: Simpler_Base Class Reference
Simpler_Base Class Reference abstract
#include <Simpler_Base.h>
Public Member Functions
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 72 of file Simpler_Base.h.
Constructor & Destructor Documentation
~Simpler_Base()
Simpler_Base::~Simpler_Base () override
Definition at line 25 of file Simpler_Base.cpp.
Member Function Documentation
assembler_matrice_pression_implicite()
void Simpler_Base::assembler_matrice_pression_implicite (Equation_base & eqn_NS, const Matrice_Morse & matrice, Matrice & matrice_en_pression_2)
Definition at line 216 of file Simpler_Base.cpp.
{
  Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn_NS);
  const IntVect& tab1 = matrice.get_tab1();
  const DoubleVect& coeff = matrice.get_coeff();
  const DoubleTab& present = eqn_NS.inconnue().valeurs();
  int nb_comp = 1;
  int deux_entrees = 0;
  if (present.nb_dim()==2)
    {
      deux_entrees = 1;
      nb_comp = present.dimension(1);
    }
  const Zone_VF& la_zone = ref_cast(Zone_VF,eqnNS.zone_dis().valeur());
  if (deux_entrees==0)
    {
      DoubleVect vol2 = la_zone.volumes_entrelaces();
      int ns = vol2.size();
      for (int i=0; i<ns; i++)
        {
          int idiag = tab1[i*nb_comp]-1;
          double ref = coeff[idiag];
          for (int c=1; c<nb_comp; c++)
            if (!est_egal(ref,coeff[tab1[i*nb_comp+c]-1]))
              {
                Cerr<<"Pb dans Piso sur la diagonale case"<<i<<" comp "<< c<<" ref "<<ref<<" valeurs "<<coeff[tab1[i*nb_comp+c]-1]<<finl;
                exit();
              }
          vol2[i] = coeff[idiag];
        }
      vol2.echange_espace_virtuel();
      eqnNS.assembleur_pression().valeur().assembler_mat(matrice_en_pression_2,vol2,1,1);
    }
  else
    {
      DoubleTab vol2(present);
      int ns = vol2.dimension(0);
      for (int i=0; i<ns; i++)
        for (int c=0; c<nb_comp; c++)
          vol2(i,c) = matrice(i*nb_comp+c,i*nb_comp+c);
      vol2.echange_espace_virtuel();
      eqnNS.assembleur_pression().valeur().assembler_mat(matrice_en_pression_2,vol2,1,1);
    }
  SolveurSys& solveur_pression_ = eqnNS.solveur_pression();
  solveur_pression_.valeur().reinit();
}
References Assembleur_base::assembler_mat(), Navier_Stokes_std::assembleur_pression(), Cerr, coeff, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), est_egal(), Process::exit(), finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Equation_base::inconnue(), TRUSTTab< _TYPE_ >::nb_dim(), ref_cast, SolveurSys_base::reinit(), TRUSTVect< _TYPE_ >::size(), Navier_Stokes_std::solveur_pression(), Deriv_Assembleur_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_SolveurSys_base::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes_entrelaces(), and Equation_base::zone_dis().
Referenced by Piso::iterer_NS(), Simple::iterer_NS(), and Simpler::iterer_NS().
get_and_set_parametre_equation()
Parametre_equation & Simpler_Base::get_and_set_parametre_equation (Equation_base & eqn) override virtual
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Reimplemented from Solveur_Implicite_Base.
Definition at line 169 of file Simpler_Base.cpp.
{
  Parametre_equation& param = eqn.parametre_equation();
  if (!param.non_nul())
    {
      param.typer("Parametre_implicite");
    }
  if (!sub_type(Parametre_implicite,param.valeur()))
    {
      Cerr<<eqn.que_suis_je()<<" has parameters of type "<<param.que_suis_je()<<" not coherent with "<<que_suis_je()<<finl;
      exit();
    }
  Parametre_implicite& param_impl = ref_cast(Parametre_implicite,param.valeur());
// on regarde si il y a des valeurs par defaut a recopier
  if (param_impl.seuil_convergence_implicite()<0)
    param_impl.seuil_convergence_implicite() = param_defaut_.seuil_convergence_implicite();
  if (param_impl.seuil_verification_solveur()<0)
    param_impl.seuil_verification_solveur() = param_defaut_.seuil_verification_solveur();
  if (param_impl.seuil_test_preliminaire_lu()==0)
    param_impl.seuil_test_preliminaire_solveur() = param_defaut_.seuil_test_preliminaire_solveur();
  if (!param_impl.solveur().non_nul())
    param_impl.solveur() = param_defaut_.solveur();
// Some checks:
  if (eqn.probleme().get_coupled())
    {
      if (param_impl.seuil_convergence_implicite()>0.1*DMAXFLOAT)
        {
          Cerr << finl << "Error!" << finl;
          Cerr << "seuil_convergence_implicite option should be defined in your time scheme." << finl;
          Cerr << "It is a mandatory option for a calculation with coupled problems." << finl;
          exit();
        }
    }
  /*
  else if (param_impl.seuil_convergence_implicite()<0.1*DMAXFLOAT)
  {
        Cerr << finl << "Error!" << finl;
  Cerr << "seuil_convergence_implicite option should be NOT be defined in your time scheme" << finl;
  Cerr << "during calculation of a single problem." << finl;
  Cerr << "Remove the option." << finl;
  exit();
  } */
  return param;
}
References Cerr, DMAXFLOAT, Process::exit(), finl, Probleme_base::get_coupled(), O_U_Ptr::non_nul(), param_defaut_, Equation_base::parametre_equation(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, Parametre_implicite::seuil_convergence_implicite(), Parametre_implicite::seuil_test_preliminaire_lu(), Parametre_implicite::seuil_test_preliminaire_solveur(), Parametre_implicite::seuil_verification_solveur(), Parametre_implicite::solveur(), sub_type, Deriv_::typer(), and Deriv_Parametre_equation_base::valeur().
Referenced by get_and_set_parametre_implicite().
get_and_set_parametre_implicite()
Parametre_implicite & Simpler_Base::get_and_set_parametre_implicite (Equation_base & eqn) inline
Definition at line 87 of file Simpler_Base.h.
  {
    return ref_cast(Parametre_implicite, get_and_set_parametre_equation(eqn).valeur());
  }
References get_and_set_parametre_equation(), ref_cast, and valeur().
Referenced by Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Solveur_U_P::iterer_NS().
get_info()
const Type_info * Simpler_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Solveur_U_P.
Definition at line 25 of file Simpler_Base.cpp.
info()
const Type_info * Simpler_Base::info () static
Definition at line 25 of file Simpler_Base.cpp.
iterer_eqn()
bool Simpler_Base::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override pure virtual
Implements Solveur_Implicite_Base.
Implemented in SETS, and Simple.
iterer_NS()
virtual void Simpler_Base::iterer_NS (Equation_base & , DoubleTab & current, DoubleTab & pression, double , Matrice_Morse & , double , DoubleTrav & , int nb_iter, int & converge, int & ok) pure virtual
Implemented in SETS, Piso, Simple, Simpler, and Solveur_U_P.
lire()
virtual Entree & Simpler_Base::lire (const Motcle & , Entree &) protected pure virtual
Implemented in SETS, Piso, and Simple.
Referenced by readOn().
max_iter_implicite() [1/2]
int Simpler_Base::max_iter_implicite () inline
max_iter_implicite() [2/2]
int Simpler_Base::max_iter_implicite () const inline
printOn()
Sortie & Simpler_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Solveur_U_P.
Definition at line 27 of file Simpler_Base.cpp.
{
  return os;
}
Referenced by Simple::printOn().
readOn()
Entree & Simpler_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Solveur_U_P.
Definition at line 32 of file Simpler_Base.cpp.
{
  int is_seuil_resol_lu = 0;
  double seuil_convergence_solveur_prov=-1;
  is_seuil_convg_variable = 0;
  controle_residu_ = 0;
  Motcle accferme = "}";
  Motcle accouverte = "{";
  int le_solveur_est_lu = 0;
  Motcle motlu;
  is >> motlu;
  assert(motlu==accouverte);
  no_qdm_ = 0;
  is >> motlu;
  Nom le_solveur_lu_;
  while(motlu!=accferme )
    {
      if (motlu=="max_iter_implicite")
        {
          Cerr << motlu << finl;
          Cerr << motlu <<" is no more longer understood by Simpler but by the time scheme"<<finl;
          exit();
        }
      else if (motlu=="seuil_convergence_implicite")
        {
          Cerr << motlu << finl;
          is >> param_defaut_.seuil_convergence_implicite();
        }
      else if (motlu=="seuil_convergence_variable")
        {
          Cerr << "Option seuil_convergence_variable is not yet understood." << finl;
          exit();
          Cerr << motlu << finl;
          facteur_convg_ = 100;
          is_seuil_convg_variable = 1;
        }
      else if (motlu=="seuil_generation_solveur")
        {
          Cerr << motlu << finl;
          is_seuil_resol_lu = 1;
          is >> param_defaut_.seuil_generation_solveur();
        }
      else if (motlu=="seuil_verification_solveur")
        {
          Cerr << motlu << finl;
          is >> param_defaut_.seuil_verification_solveur();
        }
      else if (motlu=="seuil_test_preliminaire_solveur")
        {
          Cerr << motlu << finl;
          is >> param_defaut_.seuil_test_preliminaire_solveur();
        }
      else if (motlu=="seuil_convergence_solveur")
        {
          Cerr << motlu << finl;
          is_seuil_resol_lu = 1;
          is >> seuil_convergence_solveur_prov;
        }
      else if (motlu=="nb_it_max")
        {
          is >> param_defaut_.nb_it_max();
        }
      else if (motlu=="controle_residu")
        {
          controle_residu_ = 1;
        }
      else if (motlu=="no_qdm")
        {
          Cerr << motlu << finl;
          no_qdm_ = 1;
        }
      else if (motlu=="solveur")
        {
          le_solveur_est_lu = 1;
          SChaine toto;
// redefinition de motlu pour garder les minuscules/majuscules
          Nom motlubis;
          int nb_acc=0;
          int ok=0;
          while (nb_acc!=0 || !ok)
            {
              is >>motlubis;
              toto<<" "<<motlubis;
              if (motlubis=="}") nb_acc--;
              else if (motlubis=="{")
                {
                  ok=1;
                  nb_acc++;
                };
            }
          le_solveur_lu_ = Nom(toto.get_str());
        }
      else
        {
          lire(motlu,is);
        }
      is >> motlu;
    }
  if (seuil_convergence_solveur_prov>0)
    {
      param_defaut_.set_seuil_solveur_avec_seuil_convergence_solveur(seuil_convergence_solveur_prov);
    }
  if ((is_seuil_resol_lu==0) && (le_solveur_est_lu==0))
    {
      Cerr<<"Neither the solving object nor the threshold seuil_convergence_solveur has been indicated."<<finl;
      Cerr<<"At least one of them (or both) must be specified."<<finl;
      exit();
    }
  if (param_defaut_.seuil_convergence_implicite()<0)
    param_defaut_.seuil_convergence_implicite() = DMAXFLOAT;
  if (param_defaut_.seuil_verification_solveur()<0)
    param_defaut_.seuil_verification_solveur() = DMAXFLOAT;
// on laisse seuil_test_preliminaire <0
  if (le_solveur_est_lu==0)
    {
      SChaine toto;
      toto<<"Gmres { diag seuil "<<param_defaut_.seuil_generation_solveur()<<" nb_it_max "<< param_defaut_.nb_it_max() << " controle_residu " <<controle_residu_<<" } "<<finl;
      le_solveur_lu_=Nom(toto.get_str());
    }
  {
    EChaine titi(le_solveur_lu_);
    titi>> param_defaut_.solveur();
  }
  param_defaut_.solveur().nommer("solveur_implicite");
  return is;
}
References Cerr, controle_residu_, DMAXFLOAT, Process::exit(), facteur_convg_, finl, SChaine::get_str(), is_seuil_convg_variable, lire(), Parametre_implicite::nb_it_max(), no_qdm_, SolveurSys::nommer(), param_defaut_, Parametre_implicite::set_seuil_solveur_avec_seuil_convergence_solveur(), Parametre_implicite::seuil_convergence_implicite(), Parametre_implicite::seuil_generation_solveur(), Parametre_implicite::seuil_test_preliminaire_solveur(), Parametre_implicite::seuil_verification_solveur(), and Parametre_implicite::solveur().
Referenced by Simple::readOn().
self_cast() [1/2]
const Simpler_Base & Simpler_Base::self_cast (const Objet_U & r) static
Definition at line 25 of file Simpler_Base.cpp.
self_cast() [2/2]
Simpler_Base & Simpler_Base::self_cast (Objet_U & r) static
Definition at line 25 of file Simpler_Base.cpp.
Member Data Documentation
controle_residu_
int Simpler_Base::controle_residu_ protected
Definition at line 98 of file Simpler_Base.h.
Referenced by readOn().
facteur_convg_
double Simpler_Base::facteur_convg_ protected
Definition at line 96 of file Simpler_Base.h.
Referenced by readOn().
info_obj
const Type_info Simpler_Base::info_obj static
Definition at line 74 of file Simpler_Base.h.
is_seuil_convg_variable
int Simpler_Base::is_seuil_convg_variable protected
Definition at line 95 of file Simpler_Base.h.
Referenced by Simple::iterer_eqn(), and readOn().
no_qdm_
int Simpler_Base::no_qdm_ protected
Definition at line 97 of file Simpler_Base.h.
Referenced by Simple::iterer_eqn(), and readOn().
param_defaut_
Parametre_implicite Simpler_Base::param_defaut_ protected
Definition at line 94 of file Simpler_Base.h.
Referenced by get_and_set_parametre_equation(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Simpler_Base.h
src/ThHyd/Schemas_Temps/Simpler_Base.cpp