TRUST: Navier_Stokes_Fluide_Dilatable_base Class Reference
Navier_Stokes_Fluide_Dilatable_base Class Reference
classe Navier_Stokes_Fluide_Dilatable_base
Cette classe basse porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide dilatable.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
#include <Navier_Stokes_Fluide_Dilatable_base.h>
Public Member Functions
Navier_Stokes_Fluide_Dilatable_base ()
~Navier_Stokes_Fluide_Dilatable_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void discretiser ()
Dicretise l'equation.
int preparer_calcul ()
Appel Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
const Champ_Don & diffusivite_pour_transport ()
const Champ_base & diffusivite_pour_pas_de_temps ()
const Champ_base & vitesse_pour_transport ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual void completer ()
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual int impr (Sortie &os) const
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
const Champ_Inc & rho_la_vitesse () const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Navier_Stokes_Fluide_Dilatable_base & self_cast (Objet_U &)
static const
Navier_Stokes_Fluide_Dilatable_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
virtual Entree & readOn (Entree &)
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Detailed Description
classe Navier_Stokes_Fluide_Dilatable_base
Cette classe basse porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide dilatable.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Definition at line 56 of file Navier_Stokes_Fluide_Dilatable_base.h.
Constructor & Destructor Documentation
Navier_Stokes_Fluide_Dilatable_base::Navier_Stokes_Fluide_Dilatable_base ()
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
Navier_Stokes_Fluide_Dilatable_base::~Navier_Stokes_Fluide_Dilatable_base ()
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
Member Function Documentation
void Navier_Stokes_Fluide_Dilatable_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) [virtual]
Reimplemented from Equation_base.
Definition at line 159 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl().
{
  Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl(mat_morse,present,secmem);
}
void Navier_Stokes_Fluide_Dilatable_base::assembler_avec_inertie (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) [virtual]
Reimplemented from Equation_base.
Definition at line 164 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl().
{
  Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(*this,mat_morse,present,secmem);
}
void Navier_Stokes_Fluide_Dilatable_base::completer (void) [virtual]
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 88 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Cerr, finl, Navier_Stokes_std::inconnue(), O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
{
  Cerr<<"Navier_Stokes_std::completer"<<finl;
  Navier_Stokes_std::completer();
  Cerr<<"Unknown field type : " << inconnue()->que_suis_je() << finl;
  Cerr<<"Unknown field name : " << inconnue()->le_nom() << finl;
  Cerr<<"Equation type : " << inconnue()->equation().que_suis_je() << finl;
}
DoubleTab & Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco (DoubleTab & derivee) [virtual]
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Reimplemented from Navier_Stokes_std.
Definition at line 154 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl().
{
  return Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(*this,vpoint);
}
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps () [virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 102 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_std::le_fluide.
{
  return le_fluide->viscosite_cinematique();
}
const Champ_Don & Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_transport () [virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 97 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_std::le_fluide.
{
  return le_fluide->viscosite_dynamique();
}
void Navier_Stokes_Fluide_Dilatable_base::discretiser () [virtual]
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
Definition at line 145 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Equation_base::discretisation(), Field_base::nommer(), Objet_U::nommer(), ref_cast, Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Equation_base::schema_temps(), Deriv_Champ_Inc_base::valeur(), Discret_Thyd::vitesse(), and Equation_base::zone_dis().
{
  Navier_Stokes_std::discretiser();
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  dis.vitesse(schema_temps(), zone_dis(), rho_la_vitesse_);
  rho_la_vitesse_.nommer("rho_u");
  rho_la_vitesse_.valeur().nommer("rho_u");
}
virtual int Navier_Stokes_Fluide_Dilatable_base::duplique () const [pure virtual]
Reimplemented from Navier_Stokes_std.
Implemented in Navier_Stokes_QC, and Navier_Stokes_WC.
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::get_champ (const Motcle & nom) const [virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 112 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Milieu_base::get_champ(), Navier_Stokes_std::milieu(), rho_la_vitesse(), and Deriv_Champ_Inc_base::valeur().
{
  if (nom=="rho_u")
    return rho_la_vitesse().valeur();
  try
    {
      return Navier_Stokes_std::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  try
    {
      return milieu().get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
}
const Type_info * Navier_Stokes_Fluide_Dilatable_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
int Navier_Stokes_Fluide_Dilatable_base::impr (Sortie & os) const [virtual]
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
< max|sum(u.ndS)i/(vol(i)/dt)|=max|div(U)i/dt| Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html It is relative errors (normalized by the volume/dt)
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 42 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
{
  Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(*this,os);
  return Navier_Stokes_std::impr(os);
}
const Type_info * Navier_Stokes_Fluide_Dilatable_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
bool Navier_Stokes_Fluide_Dilatable_base::initTimeStep (double dt) [virtual]
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
Returns:
0 en cas d'erreur, 1 sinon
Signification:
Contraintes:
< will be filled
Reimplemented from Navier_Stokes_std.
Definition at line 134 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_std::inconnue(), Navier_Stokes_std::le_fluide, ref_cast, Fluide_Dilatable_base::rho_discvit(), Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Ref_Fluide_base::valeur(), and Champ_Inc::valeurs().
{
  DoubleTab& tab_vitesse=inconnue().valeurs();
  Fluide_Dilatable_base& fluide_dil=ref_cast(Fluide_Dilatable_base,le_fluide.valeur());
  const DoubleTab& tab_rho = fluide_dil.rho_discvit();
  DoubleTab& rhovitesse = rho_la_vitesse_.valeurs(); //!< will be filled
  rho_vitesse_impl(tab_rho,tab_vitesse,rhovitesse);
  return  Navier_Stokes_std::initTimeStep(dt);
}
int Navier_Stokes_Fluide_Dilatable_base::preparer_calcul (void) [virtual]
Appel Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 64 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
{
  return Navier_Stokes_std::preparer_calcul();
}
Sortie & Navier_Stokes_Fluide_Dilatable_base::printOn (Sortie & is) const [protected, virtual]
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 30 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
{
  return Navier_Stokes_std::printOn(is);
}
Entree & Navier_Stokes_Fluide_Dilatable_base::readOn (Entree & is) [protected, virtual]
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 35 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_std::divergence, and Operateur::set_description().
{
  Navier_Stokes_std::readOn(is);
  divergence.set_description((Nom)"Mass flow rate=Integral(rho*u*ndS) [kg.s-1]");
  return is;
}
const Champ_Inc& Navier_Stokes_Fluide_Dilatable_base::rho_la_vitesse () const [inline, virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 77 of file Navier_Stokes_Fluide_Dilatable_base.h.
References Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_.
Referenced by get_champ().
{ return rho_la_vitesse_; }
Navier_Stokes_Fluide_Dilatable_base & Navier_Stokes_Fluide_Dilatable_base::self_cast (Objet_U & r) [static]
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
const Navier_Stokes_Fluide_Dilatable_base & Navier_Stokes_Fluide_Dilatable_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 28 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::vitesse_pour_transport () [virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 107 of file Navier_Stokes_Fluide_Dilatable_base.cpp.
References Navier_Stokes_std::la_vitesse.
{
  return la_vitesse;
}
Member Data Documentation
const Type_info Navier_Stokes_Fluide_Dilatable_base::info_obj [static]
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
Definition at line 58 of file Navier_Stokes_Fluide_Dilatable_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Navier_Stokes_Fluide_Dilatable_base.h
src/ThHyd/Dilatable/Common/Equations/Navier_Stokes_Fluide_Dilatable_base.cpp