TRUST: Masse_VEF_P1NC Class Reference
Masse_VEF_P1NC Class Reference
#include <Masse_VEF_P1NC.h>
Public Member Functions
Masse_VEF_P1NC ()
~Masse_VEF_P1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
DoubleTab & appliquer_impl (DoubleTab &sm) const override
Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const override
DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const override
DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const override
Public Member Functions inherited from Solveur_Masse_base
Solveur_Masse_base ()
~Solveur_Masse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & appliquer (DoubleTab &) const
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual void assembler ()
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse_dt_local (DoubleVect &dt_locaux, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse_dt_local (DoubleVect &dt_locaux, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
void set_name_of_coefficient_temporel (const Nom &)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
int has_coefficient_temporel () const
const Nom & get_name_of_coefficient_temporel () const
virtual DoubleTab & appliquer_impl (DoubleTab &x) const =0
virtual void dimensionner (Matrice_Morse &matrix) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
virtual void completer (void)
virtual void preparer_calcul (void)
void set_penalisation_flag (int pen)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Masse_VEF_P1NC & self_cast (Objet_U &)
static const Masse_VEF_P1NC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Masse_base
static const Type_info * info ()
static Solveur_Masse_base & self_cast (Objet_U &)
static const Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Masse_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Additional Inherited Members
Protected Attributes inherited from Solveur_Masse_base
Nom name_of_coefficient_temporel_
nom du coefficient temporelle
int has_coefficient_temporel_
int penalisation_flag_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 30 of file Masse_VEF_P1NC.h.
Constructor & Destructor Documentation
Masse_VEF_P1NC()
Masse_VEF_P1NC::Masse_VEF_P1NC ()
Definition at line 25 of file Masse_VEF_P1NC.cpp.
~Masse_VEF_P1NC()
Masse_VEF_P1NC::~Masse_VEF_P1NC ()
Definition at line 25 of file Masse_VEF_P1NC.cpp.
Member Function Documentation
ajouter_masse() [1/2]
DoubleTab & Masse_VEF_P1NC::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 185 of file Masse_VEF_P1NC.cpp.
{
  if (penalisation||(la_zone_Cl_VEF.valeur().equation().inconnue()->nature_du_champ()!=vectoriel))
    return Solveur_Masse_base::ajouter_masse(dt,x,y,penalisation);
// Sinon on modifie temporairement la nature du champ pour que appliquer_impl ne projette pas sur n.
  Champ_Inc_base& inco=ref_cast_non_const( Champ_Inc_base,la_zone_Cl_VEF.valeur().equation().inconnue().valeur());
  inco.fixer_nature_du_champ(multi_scalaire);
  Solveur_Masse_base::ajouter_masse(dt,x,y,penalisation);
  inco.fixer_nature_du_champ(vectoriel);
  return x;
}
References Solveur_Masse_base::ajouter_masse(), MorEqn::equation(), Field_base::fixer_nature_du_champ(), Equation_base::inconnue(), la_zone_Cl_VEF, multi_scalaire, ref_cast_non_const, Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and vectoriel.
ajouter_masse() [2/2]
Matrice_Base & Masse_VEF_P1NC::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 170 of file Masse_VEF_P1NC.cpp.
{
  if (penalisation||(la_zone_Cl_VEF.valeur().equation().inconnue()->nature_du_champ()!=vectoriel))
    return Solveur_Masse_base::ajouter_masse(dt,matrice,penalisation);
// Sinon on modifie temporairement la nature du champ pour que appliquer_impl ne projette pas sur n.
  Champ_Inc_base& inco=ref_cast_non_const( Champ_Inc_base,la_zone_Cl_VEF.valeur().equation().inconnue().valeur());
  inco.fixer_nature_du_champ(multi_scalaire);
  Solveur_Masse_base::ajouter_masse(dt,matrice,penalisation);
  inco.fixer_nature_du_champ(vectoriel);
  return matrice;
}
References Solveur_Masse_base::ajouter_masse(), MorEqn::equation(), Field_base::fixer_nature_du_champ(), Equation_base::inconnue(), la_zone_Cl_VEF, multi_scalaire, ref_cast_non_const, Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and vectoriel.
appliquer_impl()
DoubleTab & Masse_VEF_P1NC::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
Definition at line 53 of file Masse_VEF_P1NC.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,la_zone_Cl_VEF.valeur());
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = zone_Cl_VEF.volumes_entrelaces_Cl();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  int nfa = zone_VEF.nb_faces();
  int num_std = zone_VEF.premiere_face_std();
  int num_int = zone_VEF.premiere_face_int();
  int face,comp,elem;
  int nbcomp = sm.line_size();
  if (nfa != sm.dimension(0))
    {
      Cerr << "erreur dans Masse_VEF_P1NC : ";
      Cerr << "nombre de faces :  " << nfa
           << " taille du second membre : " << sm.dimension(0) << finl;
      exit();
    }
// On traite les faces standard qui ne portent pas de conditions aux limites
  for (face=num_std; face<nfa; face++)
    {
// elem1 = face_voisins(face,0);
// elem2 = face_voisins(face,1);
      for (comp=0; comp<nbcomp; comp++)
        sm(face,comp) /= (volumes_entrelaces(face)*porosite_face(face)) ;
    }
// On traite les faces non standard
// les faces des bord sont des faces non standard susceptibles de porter des C.L
// les faces internes non standard ne portent pas de C.L
// On traite les conditions aux limites
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if ( (sub_type(Dirichlet,la_cl.valeur()))
           ||
           (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
// Pour les faces de Dirichlet on met sm a 0
        for (face=num1; face<num2; face++)
          for (comp=0; comp<nbcomp; comp++)
            sm(face,comp) =0;
      else
        if ((sub_type(Symetrie,la_cl.valeur()))&&(zone_Cl_VEF.equation().inconnue()->nature_du_champ()==vectoriel))
          {
            const DoubleTab& normales = zone_VEF.face_normales();
            for (face=num1; face<num2; face++)
              {
                double psc=0;
                double surf=0;
                for (comp=0; comp<nbcomp; comp++)
                  {
                    psc+=sm(face,comp)*normales(face,comp);
                    surf+=normales(face,comp)*normales(face,comp);
                  }
                psc/=surf;
                for(comp=0; comp<dimension; comp++)
                  {
                    sm(face,comp)-=psc*normales(face,comp);
                    sm(face,comp) /= (volumes_entrelaces_Cl(face)*
                                      porosite_face(face));
                  }
              }
          }
        else
          for (face=num1; face<num2; face++)
            {
              elem = face_voisins(face,0);
              if ( elem == -1 )
                {
                  elem = face_voisins(face,1);
                }
              for (comp=0; comp<nbcomp; comp++)
                sm(face,comp) /= (volumes_entrelaces_Cl(face)*porosite_face(face));
            }
    }
// On traite les faces internes non standard
  for (face=num_int; face<num_std; face++)
    {
// elem1 = face_voisins(face,0);
// elem2 = face_voisins(face,1);
      for (comp=0; comp<nbcomp; comp++)
        sm(face,comp) /= (volumes_entrelaces_Cl(face)*porosite_face(face)) ;
    }
// sm.echange_espace_virtuel();
// Debog::verifier("Masse_VEF_P1NC::appliquer, sm=",sm);
  return sm;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Equation_base::inconnue(), la_zone_Cl_VEF, la_zone_VEF, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), vectoriel, Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
associer_zone_cl_dis_base()
void Masse_VEF_P1NC::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 164 of file Masse_VEF_P1NC.cpp.
{
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, la_zone_Cl_dis_base);
}
References la_zone_Cl_VEF, and ref_cast.
associer_zone_dis_base()
void Masse_VEF_P1NC::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 159 of file Masse_VEF_P1NC.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF, la_zone_dis_base);
}
References la_zone_VEF, and ref_cast.
corriger_solution()
DoubleTab & Masse_VEF_P1NC::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 198 of file Masse_VEF_P1NC.cpp.
{
// assert(penalisation_==1);
  return Solveur_Masse_base::corriger_solution( x,  y, incr) ;
}
References Solveur_Masse_base::corriger_solution().
cree_instance()
Objet_U * Masse_VEF_P1NC::cree_instance () static
Definition at line 25 of file Masse_VEF_P1NC.cpp.
duplique()
int Masse_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Masse_VEF_P1NC.cpp.
get_info()
const Type_info * Masse_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 25 of file Masse_VEF_P1NC.cpp.
info()
const Type_info * Masse_VEF_P1NC::info () static
Definition at line 25 of file Masse_VEF_P1NC.cpp.
printOn()
Sortie & Masse_VEF_P1NC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 31 of file Masse_VEF_P1NC.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_VEF_P1NC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 39 of file Masse_VEF_P1NC.cpp.
{
  return s ;
}
self_cast() [1/2]
const Masse_VEF_P1NC & Masse_VEF_P1NC::self_cast (const Objet_U & r) static
Definition at line 25 of file Masse_VEF_P1NC.cpp.
self_cast() [2/2]
Masse_VEF_P1NC & Masse_VEF_P1NC::self_cast (Objet_U & r) static
Definition at line 25 of file Masse_VEF_P1NC.cpp.
taille_memoire()
unsigned Masse_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Masse_VEF_P1NC.cpp.
Member Data Documentation
info_obj
const Type_info Masse_VEF_P1NC::info_obj static
Definition at line 33 of file Masse_VEF_P1NC.h.
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Masse_VEF_P1NC::la_zone_Cl_VEF private
Definition at line 50 of file Masse_VEF_P1NC.h.
Referenced by ajouter_masse(), appliquer_impl(), and associer_zone_cl_dis_base().
la_zone_VEF
Ref_Zone_VEF Masse_VEF_P1NC::la_zone_VEF private
Definition at line 49 of file Masse_VEF_P1NC.h.
Referenced by appliquer_impl(), and associer_zone_dis_base().
The documentation for this class was generated from the following files:
src/VEF/Solveurs/Masse_VEF_P1NC.h
src/VEF/Solveurs/Masse_VEF_P1NC.cpp