TRUST: Ref_Debog_Pb Class Reference
Ref_Debog_Pb Class Reference
#include <Debog_Pb.h>
Public Member Functions
~Ref_Debog_Pb ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Debog_Pb ()
Ref_Debog_Pb (const Debog_Pb &)
Ref_Debog_Pb (const Ref_Debog_Pb &)
const Debog_Pb & valeur () const
Debog_Pb & valeur ()
const Debog_Pb * operator-> () const
Debog_Pb * operator-> ()
const Ref_Debog_Pb & operator= (const Debog_Pb &)
const Ref_Debog_Pb & operator= (const Ref_Debog_Pb &)
operator const Debog_Pb & () const
operator Debog_Pb & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Debog_Pb & self_cast (Objet_U &)
static const Ref_Debog_Pb & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Debog_Pb * pointeur_
Detailed Description
Definition at line 38 of file Debog_Pb.h.
Constructor & Destructor Documentation
Ref_Debog_Pb::~Ref_Debog_Pb ()
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb::Ref_Debog_Pb ()
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb::Ref_Debog_Pb (const Debog_Pb & t)
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb::Ref_Debog_Pb (const Ref_Debog_Pb & t)
Definition at line 80 of file Debog.cpp.
Member Function Documentation
Objet_U * Ref_Debog_Pb::cree_instance () [static]
Definition at line 80 of file Debog.cpp.
int Ref_Debog_Pb::duplique () const [virtual]
Implements Ref_.
Definition at line 80 of file Debog.cpp.
const Type_info * Ref_Debog_Pb::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
const Type_info & Ref_Debog_Pb::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 80 of file Debog.cpp.
const Type_info * Ref_Debog_Pb::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb::operator const Debog_Pb & () const
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb::operator Debog_Pb & ()
Definition at line 80 of file Debog.cpp.
const Debog_Pb * Ref_Debog_Pb::operator-> () const [inline]
Definition at line 38 of file Debog_Pb.h.
: public Objet_U
Debog_Pb * Ref_Debog_Pb::operator-> () [inline]
Definition at line 38 of file Debog_Pb.h.
: public Objet_U
const Ref_Debog_Pb & Ref_Debog_Pb::operator= (const Ref_Debog_Pb & t)
Definition at line 80 of file Debog.cpp.
const Ref_Debog_Pb & Ref_Debog_Pb::operator= (const Debog_Pb & t)
Definition at line 80 of file Debog.cpp.
Sortie & Ref_Debog_Pb::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
Entree & Ref_Debog_Pb::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
const Ref_Debog_Pb & Ref_Debog_Pb::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
Ref_Debog_Pb & Ref_Debog_Pb::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 80 of file Debog.cpp.
void Ref_Debog_Pb::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 80 of file Debog.cpp.
unsigned Ref_Debog_Pb::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 80 of file Debog.cpp.
const Debog_Pb & Ref_Debog_Pb::valeur () const [inline]
Definition at line 38 of file Debog_Pb.h.
Referenced by Debog::set_nom_pb_actuel(), Debog::verifier(), Debog::verifier_getref(), and Debog::verifier_Mat_elems().
: public Objet_U
Debog_Pb & Ref_Debog_Pb::valeur () [inline]
Definition at line 38 of file Debog_Pb.h.
: public Objet_U
Member Data Documentation
const Type_info Ref_Debog_Pb::info_obj [static]
Reimplemented from Ref_.
Definition at line 38 of file Debog_Pb.h.
Debog_Pb* Ref_Debog_Pb::pointeur_ [private]
Definition at line 38 of file Debog_Pb.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Debog_Pb.h
src/Kernel/Framework/Debog.cpp