TRUST: Rectangle_axi Class Reference
Rectangle_axi Class Reference
Classe Rectangle_axi
Cette classe represente la deformee du rectangle dans
le cas d'un maillage en coordonnees cylindriques
Les methodes de la classe Rectangle dont Rectangle_axi derive sont
surchargees pour effectuer les calculs en coordonnees cylindrique.
#include <Rectangle_axi.h>
Public Member Functions
Rectangle_axi ()
~Rectangle_axi ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Nom & nom_lml () const
Renvoie le nom LML d'un rectangle_axi = "VOXEL8".
void reordonner ()
NE FAIT RIEN
A CODER.
Type_Face type_face (int=0) const
Renvoie le i-ieme type de face.
Un rectangle (Axi) n'a qu'un seul type de face.
void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
void calculer_volumes (DoubleVect &) const
Calcule les volumes des elements de la zone associee.
virtual int contient (const ArrOfDouble &, int) const
// Renvoie 1 si l'element ielem de la zone associee a
// l'element geometrique contient le point
// de coordonnees specifiees par le parametre "pos".
// Renvoie 0 sinon.
// Precondition:
// Parametre: DoubleVect& pos
// Signification: coordonnees du point que l'on
// cherche a localiser
// Valeurs par defaut:
// Contraintes: reference constante
// Acces: entree
// Parametre: int ielem
// Signification: le numero de l'element de la zone
// dans lequel on cherche le point.
// Valeurs par defaut:
// Contraintes:
// Acces:
// Retour: int
// Signification: 1 si le point de coordonnees specifiees
// appartient a l'element ielem
// 0 sinon
// Contraintes:
// Exception:
// Effets de bord:
// Postcondition: la methode ne modifie pas l'objet
virtual int contient (const ArrOfInt &, int) const
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Rectangle_axi & self_cast (Objet_U &)
static const Rectangle_axi & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Detailed Description
Classe Rectangle_axi
Cette classe represente la deformee du rectangle dans
le cas d'un maillage en coordonnees cylindriques
Les methodes de la classe Rectangle dont Rectangle_axi derive sont
surchargees pour effectuer les calculs en coordonnees cylindrique.
Definition at line 43 of file Rectangle_axi.h.
Constructor & Destructor Documentation
Rectangle_axi::Rectangle_axi ()
Definition at line 26 of file Rectangle_axi.cpp.
Rectangle_axi::~Rectangle_axi ()
Definition at line 26 of file Rectangle_axi.cpp.
Member Function Documentation
void Rectangle_axi::calculer_centres_gravite (DoubleTab & xp) const [virtual]
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
Reimplemented from Elem_geom_base.
Definition at line 85 of file Rectangle_axi.cpp.
References Domaine::coord(), Objet_U::dimension, M_PI, Elem_geom_base::ma_zone, Rectangle::nb_som(), and DoubleTab::resize().
{
  const IntTab& les_Polys = ma_zone->les_elems();
  const Domaine& le_domaine = ma_zone->domaine();
  int nb_elem = ma_zone->nb_elem();
  int num_som;
  xp.resize(nb_elem,dimension);
  xp=0;
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      double d_teta;
      int i, s;
      d_teta = le_domaine.coord(les_Polys(num_elem,3),1) -
               le_domaine.coord(les_Polys(num_elem,1),1);
      if( d_teta<0 )
        {
// Modif axi !
          for( s=0; s<nb_som(); s++)
            {
              num_som = les_Polys(num_elem,s);
              for( i=0; i<dimension; i++)
                xp(num_elem,i) += le_domaine.coord(num_som,i);
              if(le_domaine.coord(num_som,1) == 0.)
                xp(num_elem,1) += 2*M_PI;
            }
        }
      else
        for( s=0; s<nb_som(); s++)
          {
            num_som = les_Polys(num_elem,s);
            for( i=0; i<dimension; i++)
              xp(num_elem,i) += le_domaine.coord(num_som,i);
          }
    }
  double x=1./nb_som();
  xp*=x;
}
void Rectangle_axi::calculer_volumes (DoubleVect & volumes) const [virtual]
Calcule les volumes des elements de la zone associee.
Reimplemented from Rectangle.
Definition at line 184 of file Rectangle_axi.cpp.
References Domaine::coord(), Zone::domaine(), M_PI, Elem_geom_base::ma_zone, Zone::nb_elem_tot(), DoubleVect::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
{
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double r,dr,d_teta;
  int S1,S2,S4;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      S1 = zone.sommet_elem(num_poly,0);
      S2 = zone.sommet_elem(num_poly,1);
      S4 = zone.sommet_elem(num_poly,3);
      r = 0.5*(dom.coord(S2,0) + dom.coord(S1,0));
      dr = dom.coord(S2,0) - dom.coord(S1,0);
      d_teta = dom.coord(S4,1) - dom.coord(S2,1);
      if (d_teta<0) d_teta+=2.*M_PI;
      volumes[num_poly]= dr*r*d_teta;
    }
}
int Rectangle_axi::contient (const ArrOfInt & pos, int element) const [virtual]
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns:
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Reimplemented from Rectangle.
Definition at line 277 of file Rectangle_axi.cpp.
References contient().
{
  return Rectangle::contient(pos,element);
}
int Rectangle_axi::contient (const ArrOfDouble & pos, int element) const [virtual]
// Renvoie 1 si l'element ielem de la zone associee a
// l'element geometrique contient le point
// de coordonnees specifiees par le parametre "pos".
// Renvoie 0 sinon.
// Precondition:
// Parametre: DoubleVect& pos
// Signification: coordonnees du point que l'on
// cherche a localiser
// Valeurs par defaut:
// Contraintes: reference constante
// Acces: entree
// Parametre: int ielem
// Signification: le numero de l'element de la zone
// dans lequel on cherche le point.
// Valeurs par defaut:
// Contraintes:
// Acces:
// Retour: int
// Signification: 1 si le point de coordonnees specifiees
// appartient a l'element ielem
// 0 sinon
// Contraintes:
// Exception:
// Effets de bord:
// Postcondition: la methode ne modifie pas l'objet
Reimplemented from Rectangle.
Definition at line 233 of file Rectangle_axi.cpp.
References Domaine::coord(), inf_ou_egal(), M_PI, Elem_geom_base::ma_zone, ArrOfDouble::size_array(), and Ref_Zone::valeur().
Referenced by contient().
{
  assert(pos.size_array()==2);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som3 = zone.sommet_elem(element,3);
  double r0,r3,t0,t3;
  r0=dom.coord(som0,0);
  r3=dom.coord(som3,0);
  t0=dom.coord(som0,1);
  t3=dom.coord(som3,1);
  if (t3<t0) t3+=2*M_PI;
  if (    inf_ou_egal(r0,pos[0]) && inf_ou_egal(pos[0],r3)
          && inf_ou_egal(t0,pos[1]) && inf_ou_egal(pos[1],t3) )
    return 1;
  else
    return 0;
}
Objet_U * Rectangle_axi::cree_instance () [static]
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
int Rectangle_axi::duplique () const [virtual]
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
const Type_info * Rectangle_axi::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
const Type_info * Rectangle_axi::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
const Nom & Rectangle_axi::nom_lml () const [virtual]
Renvoie le nom LML d'un rectangle_axi = "VOXEL8".
Returns:
Nom&
Signification: toujours egal a "VOXEL8"
Contraintes: reference constante
Reimplemented from Rectangle.
Definition at line 161 of file Rectangle_axi.cpp.
{
  static Nom nom="VOXEL8";
  return nom;
}
Sortie & Rectangle_axi::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Rectangle.
Definition at line 43 of file Rectangle_axi.cpp.
{
  return s;
}
Entree & Rectangle_axi::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Rectangle.
Definition at line 63 of file Rectangle_axi.cpp.
{
  return s;
}
void Rectangle_axi::reordonner () [virtual]
NE FAIT RIEN
A CODER.
Reimplemented from Rectangle.
Definition at line 141 of file Rectangle_axi.cpp.
{
// A CODER
}
const Rectangle_axi & Rectangle_axi::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
Rectangle_axi & Rectangle_axi::self_cast (Objet_U & r) [static]
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
unsigned Rectangle_axi::taille_memoire () const [virtual]
Reimplemented from Rectangle.
Definition at line 26 of file Rectangle_axi.cpp.
Type_Face Rectangle_axi::type_face (int i = 0) const [inline, virtual]
Renvoie le i-ieme type de face.
Un rectangle (Axi) n'a qu'un seul type de face.
Returns:
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::segment_2D_axi (si i=0)
Reimplemented from Rectangle.
Definition at line 75 of file Rectangle_axi.h.
References Cerr, Process::exit(), finl, and Faces::segment_2D_axi.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A rectangle has not " << i << " types of face" << finl;
      exit();
    }
  return Faces::segment_2D_axi;
}
Member Data Documentation
const Type_info Rectangle_axi::info_obj [static]
Reimplemented from Rectangle.
Definition at line 46 of file Rectangle_axi.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Rectangle_axi.h
src/Kernel/Geometrie/Rectangle_axi.cpp