TRUST: Equation_base Class Reference
Equation_base Class Reference abstract
#include <Equation_base.h>
Public Member Functions
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Private Member Functions
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, int size_terme_mul, const DoubleTab &term_mul)
Solve: (1/dt + M-1*L)*dI = M-1 * secmem
with a Conjugate Gradient matrix-free algorithm by default
L is the diffusion
M is the mass
In : solution=I(n)
Out: solution=dI/dt.
void ecrire_fichier_xyz () const
Ecrit dans un fichier les valeurs du champ specifie
par le mot cle "ecrire_fichier_xyz_valeur".
Private Attributes
ArrOfDouble dt_ecrire_fic_xyz
Motcles nom_champ_xyz
Liste_Noms noms_bord_xyz
IntVect nb_bords_post_xyz
int nombre_champ_xyz
int ecrit_champ_xyz_bin
DoubleVect residu_
DoubleVect residu_initial_
Champ_Fonc field_residu_
DoubleTab NULL_
int disable_equation_residual_ = 0
Parser_U equation_non_resolue_
Value_Input_Int eq_non_resolue_input_
Champ_Inc derivee_en_temps_
int calculate_time_derivative_
Detailed Description
Definition at line 86 of file Equation_base.h.
Constructor & Destructor Documentation
Equation_base()
Equation_base::Equation_base ()
< Valeur par defaut, equation resolue
Definition at line 51 of file Equation_base.cpp.
{
  nombre_champ_xyz=0;
  ecrit_champ_xyz_bin=0;
  sys_invariant_=1;
  implicite_=-1;
  champs_compris_.ajoute_nom_compris("volume_maille");
  Nom expr_equation_non_resolue="0";
  equation_non_resolue_.setNbVar(1);
  equation_non_resolue_.setString(expr_equation_non_resolue); //!< Valeur par defaut, equation resolue
  equation_non_resolue_.addVar("t");
  equation_non_resolue_.parseString();
  set_calculate_time_derivative(0);
}
References Parser_U::addVar(), Champs_compris::ajoute_nom_compris(), champs_compris_, ecrit_champ_xyz_bin, equation_non_resolue_, implicite_, nombre_champ_xyz, Parser_U::parseString(), set_calculate_time_derivative(), Parser_U::setNbVar(), Parser_U::setString(), and sys_invariant_.
~Equation_base()
Equation_base::~Equation_base () override
Definition at line 48 of file Equation_base.cpp.
Member Function Documentation
abortTimeStep()
void Equation_base::abortTimeStep () virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Reimplemented in Navier_Stokes_std, and QDM_Multiphase.
Definition at line 1254 of file Equation_base.cpp.
{
  for (int i=0; i<nombre_d_operateurs(); i++)
    operateur(i).l_op_base().abortTimeStep();
  inconnue()->abortTimeStep();
  if (champ_conserve_.non_nul()) champ_conserve_->abortTimeStep();
  if (champ_convecte_.non_nul()) champ_convecte_->abortTimeStep();
}
References Operateur_base::abortTimeStep(), champ_conserve_, champ_convecte_, inconnue(), Operateur::l_op_base(), nombre_d_operateurs(), O_U_Ptr::non_nul(), and operateur().
Referenced by Schema_Temps_base::abortTimeStep(), Navier_Stokes_std::abortTimeStep(), and QDM_Multiphase::abortTimeStep().
ajouter_termes_croises()
void Equation_base::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const virtual
Definition at line 2332 of file Equation_base.cpp.
{
  for (int i = 0; i < nombre_d_operateurs(); i++)
    operateur(i).l_op_base().ajouter_termes_croises(inco, autre_pb, autre_inco, resu);
}
References Operateur_base::ajouter_termes_croises(), Operateur::l_op_base(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
assembler()
void Equation_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) virtual
< Add source residual first
< Ajout de A*Inco(n) PL (11/04/2018): On aimerait bien calculer la contribution des sources en premier comme dans le cas VIA_CONTRIBUER_AU_SECOND_MEMBRE mais le cas Canal_perio_3D (keps periodique plante: il y'a une erreur de periodicite dans les termes sources du modele KEps...
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Temperature, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 2345 of file Equation_base.cpp.
{
// Test de verification de la methode contribuer_a_avec
  for (int op=0; op<nombre_d_operateurs(); op++)
    operateur(op).l_op_base().tester_contribuer_a_avec(inco, matrice);
// Contribution des operateurs et des sources:
// [Vol/dt+A]Inco(n+1)=somme(residu)+Vol/dt*Inco(n)
// Typiquement: si Op=flux(Inco) alors la matrice implicite A contient une contribution -dflux/dInco
// Exemple: Op flux convectif en VDF:
// Op=T*u*S et A=-d(T*u*S)/dT=-u*S
  const Discretisation_base::type_calcul_du_residu& type_codage=probleme().discretisation().codage_du_calcul_du_residu();
  if (type_codage==Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE)
    {
// On calcule somme(residu) par contribuer_au_second_membre (typiquement CL non implicitees)
// Cette approche necessite de coder 3 methodes (contribuer_a_avec, contribuer_au_second_membre et ajouter pour l'explicite)
      sources().contribuer_a_avec(inco,matrice);
      statistiques().end_count(assemblage_sys_counter_,0,0);
      sources().ajouter(resu);
      statistiques().begin_count(assemblage_sys_counter_);
      matrice.ajouter_multvect(inco, resu); //!< Add source residual first
      for (int op = 0; op < nombre_d_operateurs(); op++)
        {
          operateur(op).l_op_base().contribuer_a_avec(inco, matrice);
          operateur(op).l_op_base().contribuer_au_second_membre(resu);
        }
    }
  else if (type_codage==Discretisation_base::VIA_AJOUTER)
    {
// On calcule somme(residu) par somme(operateur)+sources+A*Inco(n)
// Cette approche necessite de coder seulement deux methodes (contribuer_a_avec et ajouter)
// Donc un peu plus couteux en temps de calcul mais moins de code a ecrire/maintenir
      for (int op=0; op<nombre_d_operateurs(); op++)
        {
          operateur(op).l_op_base().contribuer_a_avec(inco, matrice);
          statistiques().end_count(assemblage_sys_counter_, 0, 0);
          operateur(op).ajouter(resu);
          statistiques().begin_count(assemblage_sys_counter_);
        }
      sources().contribuer_a_avec(inco,matrice);
      statistiques().end_count(assemblage_sys_counter_,0,0);
      sources().ajouter(resu);
      statistiques().begin_count(assemblage_sys_counter_);
      matrice.ajouter_multvect(inco, resu); //!< Ajout de A*Inco(n) PL (11/04/2018): On aimerait bien calculer la contribution des sources en premier comme dans le cas VIA_CONTRIBUER_AU_SECOND_MEMBRE mais le cas Canal_perio_3D (keps periodique plante: il y'a une erreur de periodicite dans les termes sources du modele KEps...
//
//
//
    }
  else
    {
      Cerr << "Unknown value in Equation_base::assembler for " << (unsigned)type_codage << finl;
      Process::exit();
    }
}
References Operateur::ajouter(), Sources::ajouter(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Statistiques::begin_count(), Cerr, Discretisation_base::codage_du_calcul_du_residu(), Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Probleme_base::discretisation(), Statistiques::end_count(), Process::exit(), finl, Operateur::l_op_base(), nombre_d_operateurs(), operateur(), probleme(), sources(), statistiques(), Operateur_base::tester_contribuer_a_avec(), Discretisation_base::VIA_AJOUTER, and Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
Referenced by assembler_avec_inertie().
assembler_avec_inertie()
void Equation_base::assembler_avec_inertie (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base.
Definition at line 2409 of file Equation_base.cpp.
{
  statistiques().begin_count(assemblage_sys_counter_);
  assembler(mat_morse,present,secmem);
  schema_temps().ajouter_inertie(mat_morse,secmem,(*this));
  modifier_pour_Cl(mat_morse,secmem);
  statistiques().end_count(assemblage_sys_counter_);
}
References Schema_Temps_base::ajouter_inertie(), assemblage_sys_counter_, assembler(), Statistiques::begin_count(), Statistiques::end_count(), modifier_pour_Cl(), schema_temps(), and statistiques().
Referenced by Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Solveur_U_P::iterer_NS().
assembler_blocs()
void Equation_base::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const virtual
Reimplemented in Convection_Diffusion_Temperature, and Navier_Stokes_std.
Definition at line 2439 of file Equation_base.cpp.
{
  /* mise a zero */
  secmem = 0;
  for (auto && i_m : matrices) i_m.second->get_set_coeff() = 0;
  /* operateurs, sources, masse */
  for (int i = 0; i < nombre_d_operateurs(); i++)
    operateur(i).l_op_base().ajouter_blocs(matrices, secmem, semi_impl);
  statistiques().end_count(assemblage_sys_counter_, 0, 0);
  statistiques().begin_count(source_counter_);
  for (int i = 0; i < les_sources.size(); i++)
    les_sources(i).valeur().ajouter_blocs(matrices, secmem, semi_impl);
  statistiques().end_count(source_counter_);
  statistiques().begin_count(assemblage_sys_counter_);
  if (!discretisation().que_suis_je().debute_par("PolyMAC"))
    {
      const std::string& nom_inco = inconnue().le_nom().getString();
      Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
      if(mat) mat->ajouter_multvect(inconnue().valeurs(), secmem);
    }
}
References Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Statistiques::begin_count(), discretisation(), Statistiques::end_count(), Nom::getString(), inconnue(), Operateur::l_op_base(), O_U_Ptr::le_nom(), les_sources, nombre_d_operateurs(), operateur(), Objet_U::que_suis_je(), liste::size(), source_counter_, statistiques(), and List_Source::valeur().
Referenced by Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_std::assembler_blocs(), and assembler_blocs_avec_inertie().
assembler_blocs_avec_inertie()
void Equation_base::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) virtual
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
Definition at line 2463 of file Equation_base.cpp.
{
  statistiques().begin_count(assemblage_sys_counter_);
  assembler_blocs(matrices, secmem, semi_impl);
  solv_masse().valeur().set_penalisation_flag(0);
  schema_temps().ajouter_blocs(matrices, secmem, *this);
  if (!discretisation().que_suis_je().debute_par("PolyMAC"))
    {
      const std::string& nom_inco = inconnue().le_nom().getString();
      Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
      modifier_pour_Cl(*mat,secmem);
    }
  statistiques().end_count(assemblage_sys_counter_);
}
References Schema_Temps_base::ajouter_blocs(), assemblage_sys_counter_, assembler_blocs(), Statistiques::begin_count(), discretisation(), Statistiques::end_count(), Nom::getString(), inconnue(), O_U_Ptr::le_nom(), modifier_pour_Cl(), Objet_U::que_suis_je(), schema_temps(), Solveur_Masse_base::set_penalisation_flag(), solv_masse(), statistiques(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Energie_Multiphase::assembler_blocs_avec_inertie(), Masse_Multiphase::assembler_blocs_avec_inertie(), QDM_Multiphase::assembler_blocs_avec_inertie(), Simple::iterer_eqn(), Simple::iterer_eqs(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Solveur_U_P::iterer_NS().
associer_milieu_base()
virtual void Equation_base::associer_milieu_base (const Milieu_base &) pure virtual
Implemented in Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, Conduction, and List_Equations_Scalaires_Passifs_Especes.
Referenced by Equation::associer_milieu_base(), Probleme_base::associer_milieu_base(), Pb_Multiphase::lire_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
associer_milieu_equation()
void Equation_base::associer_milieu_equation () virtual
Reimplemented in List_Equations_Scalaires_Passifs_Especes.
Definition at line 1104 of file Equation_base.cpp.
{
  milieu().associer_equation(this);
}
References Milieu_base::associer_equation(), and milieu().
Referenced by List_Equations_Scalaires_Passifs_Especes::associer_milieu_equation(), Probleme_base::discretiser(), and Pb_Multiphase::lire_equations().
associer_pb_base()
void Equation_base::associer_pb_base (const Probleme_base & pb) virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
Reimplemented in Navier_Stokes_std.
Definition at line 1035 of file Equation_base.cpp.
{
  mon_probleme=pb;
// Modif B. Mathieu : pour le front_tracking, le nom de l'equation
// est donne dans le jeu de donnees lors de l'instanciation de l'objet
// (la methode "nommer" est appelee a ce moment).
// Si l'equation n'est pas instanciee, le nom est vide, on donne
// le nom par defaut qui est defini ci-dessous :
  Nom nom_vide;
  if (nom_ == nom_vide)
    {
      nom_ = pb.le_nom();
      nom_ += que_suis_je();
    }
// fin modif B.M.
  les_sources.associer_eqn(*this);
  int nb_op = nombre_d_operateurs();
  for(int i=0; i<nb_op; i++)
    operateur(i).associer_eqn(*this);
  solveur_masse.associer_eqn(*this);
}
References MorEqn::associer_eqn(), Probleme_base::le_nom(), les_sources, mon_probleme, nom_, nombre_d_operateurs(), operateur(), Objet_U::que_suis_je(), and solveur_masse.
Referenced by Probleme_base::associer(), Navier_Stokes_std::associer_pb_base(), Pb_Multiphase::lire_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
associer_sch_tps_base()
void Equation_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) virtual
S'associe au schema_en_temps.
Definition at line 1123 of file Equation_base.cpp.
{
  le_schema_en_temps=un_schema_en_temps;
}
References le_schema_en_temps.
Referenced by Equation::associer_sch_tps_base(), Probleme_base::associer_sch_tps_base(), Pb_Multiphase::lire_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
associer_zone_dis()
void Equation_base::associer_zone_dis (const Zone_dis & z) virtual
Associe la zone discretisee a l'equation.
Definition at line 1192 of file Equation_base.cpp.
{
  la_zone_dis=z;
}
References la_zone_dis.
Referenced by Probleme_base::discretiser(), Pb_Multiphase::lire_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
avancer()
void Equation_base::avancer (int i = 1) virtual
Definition at line 2220 of file Equation_base.cpp.
{
  inconnue().avancer(i);
  if (champ_conserve_.non_nul()) champ_conserve_->avancer(i);
  if (champ_convecte_.non_nul()) champ_convecte_->avancer(i);
}
References Champ_Inc::avancer(), champ_conserve_, champ_convecte_, inconnue(), and O_U_Ptr::non_nul().
calculate_time_derivative()
int Equation_base::calculate_time_derivative () const inline
Definition at line 279 of file Equation_base.h.
  {
    return calculate_time_derivative_;
  };
References calculate_time_derivative_.
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), discretiser(), initTimeStep(), mettre_a_jour(), and preparer_calcul().
calculer_champ_conserve()
void Equation_base::calculer_champ_conserve (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
Definition at line 2492 of file Equation_base.cpp.
{
  const Equation_base& eqn = ref_cast(Equation_base, obj);
  const Champ_base *coeff = eqn.solv_masse().valeur().has_coefficient_temporel() ? &eqn.get_champ(eqn.solv_masse().valeur().get_name_of_coefficient_temporel()) : NULL; //coeff temporel
  const Champ_Inc_base& inco = eqn.inconnue();
  ConstDoubleTab_parts part(inco.valeurs());
// valeur du champ lui-meme
  val = part[0];
  if (coeff) tab_multiply_any_shape(val, coeff->valeurs());
  bval = inco.valeur_aux_bords();
  if (coeff) tab_multiply_any_shape(bval, coeff->valeur_aux_bords());
  DoubleTab& der = deriv[inco.le_nom().getString()];
  if (coeff) der = coeff->valeurs();
  else der.resize(val.dimension_tot(0), val.line_size()), der = 1;
}
References coeff, TRUSTTab< _TYPE_ >::dimension_tot(), get_champ(), Solveur_Masse_base::get_name_of_coefficient_temporel(), Nom::getString(), Solveur_Masse_base::has_coefficient_temporel(), inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), ref_cast, TRUSTTab< _TYPE_ >::resize(), solv_masse(), tab_multiply_any_shape(), Deriv_Solveur_Masse_base::valeur(), Champ_Inc_base::valeur_aux_bords(), and Champ_Inc_base::valeurs().
Referenced by get_fonc_champ_conserve().
calculer_pas_de_temps()
double Equation_base::calculer_pas_de_temps () const virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
Returns
double
Signification: inverse de la somme des inverses des pas de temps
calcules par les operateurs
Contraintes:
Definition at line 1600 of file Equation_base.cpp.
{
  bool harmonic_calculation = true;
  double dt_op;
  double dt;
  if (harmonic_calculation)
    dt = 0;
  else
    dt = DMAXFLOAT;
  int nb_op = nombre_d_operateurs();
  for(int i=0; i<nb_op; i++)
    {
      if(operateur(i).l_op_base().get_decal_temps()!=1)
        dt_op = operateur(i).calculer_pas_de_temps();
      else
        dt_op = DMAXFLOAT;
      Debog::verifier("Equation_base::calculer_pas_de_temps dt_op 0 ",dt_op);
      Debog::verifier("Equation_base::calculer_pas_de_temps dt ",dt);
      const Operateur_base& op=operateur(i).l_op_base();
      if (sub_type(Operateur_Diff_base,op) && le_schema_en_temps->diffusion_implicite())
        {
// On ne compte pas le pas de temps de diffusion lorsque la diffusion est implicitee
        }
      else if (dt_op>0)
        {
// Une demie-moyenne harmonique est justifiee par le fait que diffusion et convection sont deux phenonomenes qui se cumulent
// L'information a chaque pas de temps ne peut traverser plus d'une maille de calcul donc dt*U + dt*vitesse_diffusion(~alpha/dx) < dx
// donc dt < dx/(U+alpha/dx) = 1/(1/(dx/U)+1/(dx^2/alpha)) : c'est bien une demie moyenne harmonique...
          if (harmonic_calculation)
            dt = dt + 1./dt_op;
          else
// https://en.wikipedia.org/wiki/Numerical_solution_of_the_convection%E2%80%93diffusion_equation
// On pourrait prendre le min de tous les operateurs. Mais attention parfois peut diverger:
// Un cas typique (rare?) Convection.data ecoulement en travers par rapport au maillage VDF et Re(maille)~1
            dt = (dt_op < dt ? dt_op : dt);
        }
      Debog::verifier("Equation_base::calculer_pas_de_temps dt_op 1 ",dt_op);
      if (le_schema_en_temps->limpr())
        {
          if (i == 0)
            {
              Cout << " " << finl;
              Cout << "Printing of the next provisional time steps for the equation: " << que_suis_je() << finl;
            }
          if (sub_type(Operateur_Conv_base,op))
            Cout << "   convective";
          else if (sub_type(Operateur_Diff_base,op))
            Cout << "   diffusive";
          else
            Cout << "   operator ";
          Cout<<" time step : "<< dt_op_bak[i] << finl;
        }
      dt_op_bak[i]=dt_op;
    }
  if (harmonic_calculation)
    {
      if (dt==0.)
        dt = DMAXFLOAT;
      else
        dt = 1./dt;
    }
// Warning sur les premiers pas de temps si l'implicitation de la diffusion
// dans un schema explicite vaut le coup (dt_diff<<min(dt_max,dt_conv))
// On fait le test apres les 10 premiers pas de temps en cas de demarrage avec vitesse nulle
  int nw=100;
  if (le_schema_en_temps->nb_pas_dt()>10 && le_schema_en_temps->nb_pas_dt()<nw && le_schema_en_temps->limpr())
    if (nb_op>1 && dt_op_bak[0]<0.01*std::min(le_schema_en_temps->pas_temps_max(),dt_op_bak[1]) && sub_type(Schema_Euler_explicite,le_schema_en_temps.valeur()) && !le_schema_en_temps->diffusion_implicite())
      {
        Cerr << finl << "**** Advice (printed only on the first " << nw << " time steps) ****" << finl;
        Cerr << "You could use diffusion_implicite option into the Euler scheme to increase the stability time step of the " << this->que_suis_je() << " equation by impliciting the diffusive operator." << finl;
      }
  Debog::verifier("Equation_base::calculer_pas_de_temps dt ",dt);
  return dt;
}
References Operateur::calculer_pas_de_temps(), Cerr, Cout, Schema_Temps_base::diffusion_implicite(), DMAXFLOAT, dt_op_bak, finl, Operateur::l_op_base(), le_schema_en_temps, Schema_Temps_base::limpr(), Schema_Temps_base::nb_pas_dt(), nombre_d_operateurs(), operateur(), Schema_Temps_base::pas_temps_max(), Objet_U::que_suis_je(), sub_type, Ref_Schema_Temps_base::valeur(), and Debog::verifier().
Referenced by Probleme_base::calculer_pas_de_temps(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), iterer_eqn_expl(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), Navier_Stokes_std::preparer_calcul(), and Navier_Stokes_std::projeter().
calculer_pas_de_temps_locaux()
void Equation_base::calculer_pas_de_temps_locaux (DoubleTab & dt_op) const
Definition at line 1683 of file Equation_base.cpp.
{
  int nb_op=nombre_d_operateurs();
  for(int i=0; i<nb_op; i++)
    {
      const Operateur_base& op=operateur(i).l_op_base();
      if (sub_type(Operateur_Conv_base,op))
        {
          if(sub_type(Op_Conv_negligeable, op))
            {
              Cerr<<"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"<<finl;
              Cerr<<"STEADY option is not compatible with the 'CONVECTION { NEGLIGEABLE }' model!"<<finl;
              Cerr << "Please, contact TRUST support." << finl;
              Cerr<<"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"<<finl;
              exit();
            }
          else
            operateur(i).calculer_pas_de_temps_locaux(dt_op);
        }
    }
}
References Operateur::calculer_pas_de_temps_locaux(), Cerr, Process::exit(), finl, Operateur::l_op_base(), nombre_d_operateurs(), operateur(), and sub_type.
champ_conserve()
Champ_Inc_base & Equation_base::champ_conserve () const inline
Definition at line 197 of file Equation_base.h.
  {
    return champ_conserve_.valeur();
  }
References champ_conserve_, and Deriv_Champ_Inc_base::valeur().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_PolyMAC_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Masse_PolyMAC_Elem::dimensionner_blocs(), and initTimeStep().
champ_convecte()
virtual Champ_Inc_base & Equation_base::champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
Definition at line 215 of file Equation_base.h.
  {
    return champ_conserve_.valeur();
  }
References champ_conserve_, and Deriv_Champ_Inc_base::valeur().
Referenced by Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), initTimeStep(), and Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour().
completer()
void Equation_base::completer () virtual
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
< [ABN]: In case of Front-Tracking, mass solver mass might be uninitialized ...
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Navier_Stokes_std, Masse_Multiphase, and QDM_Multiphase.
Definition at line 162 of file Equation_base.cpp.
{
  inconnue().associer_eqn(*this);
  if (la_zone_Cl_dis.non_nul())
    la_zone_Cl_dis->completer();
  inconnue()->associer_zone_cl_dis(la_zone_Cl_dis);
  if (mon_probleme.valeur().get_coupled())
    {
      bool err = false;
      int nb_cl = la_zone_Cl_dis->nb_cond_lim();
      for (int i=0; i<nb_cl; i++)
        {
          const Cond_lim_base& la_cl = la_zone_Cl_dis.valeur().les_conditions_limites(i);
          const Frontiere& la_frontiere = la_cl.frontiere_dis().frontiere();
          bool raccord_found = false;
// VDF and polymac
          if (la_cl.que_suis_je().debute_par("Paroi_Echange_contact") || la_cl.que_suis_je().debute_par("Echange_contact_Rayo"))
            raccord_found = true;
// VEF
          if (la_cl.que_suis_je().debute_par("Scalaire_impose_paroi") || la_cl.que_suis_je().debute_par("paroi_temperature_imposee_rayo") || la_cl.que_suis_je().debute_par("temperature_imposee_paroi"))
            raccord_found = true;
          if ( raccord_found && !sub_type(Raccord_base,la_frontiere))
            {
              Cerr << "====================================================================" << finl;
              Cerr << "Boundary " << la_frontiere.le_nom() << " should be a raccord" << finl;
              Cerr << "Add in your data file between the definition and the partition of the domain " << mon_probleme.valeur().domaine().le_nom() << " : " << finl;
              Cerr << "Modif_bord_to_raccord " << mon_probleme.valeur().domaine().le_nom() << " " << la_frontiere.le_nom() << finl;
              err = true;
            }
        }
      if(err)
        exit();
    }
// Ajout d un element vide qui sera renvoye si pas de modele trouve
  RefObjU mod;
  if (liste_modeles_.size()==0)
    liste_modeles_.add(mod);
// pour les eqns n'appelant pas preparer_calcul
  initialise_residu();
  int nb_op=nombre_d_operateurs();
  Nom msg="Equation_base::completer(), nb_op = " ;
  Debog::verifier(msg, nb_op);
  for(int i=0; i<nb_op; i++)
    operateur(i).completer();
  if (solv_masse().non_nul())  //!< [ABN]: In case of Front-Tracking, mass solver mass might be uninitialized ...
    solv_masse().valeur().completer();
  les_sources.completer();
  schema_temps().completer();
// Determine implicite_ and sys_invariant_ variables:
  implicite_=0;
  for(int i=0; i<nombre_d_operateurs(); i++)
    {
      if(operateur(i).l_op_base().get_decal_temps()==1)
        {
          ++implicite_;
          sys_invariant_*=operateur(i).l_op_base().systeme_invariant();
        }
    }
}
References List_RefObjU::add(), Champ_Inc::associer_eqn(), Cerr, Operateur::completer(), Sources::completer(), Schema_Temps_base::completer(), Solveur_Masse_base::completer(), Nom::debute_par(), Probleme_base::domaine(), Process::exit(), finl, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Probleme_base::get_coupled(), Operateur_base::get_decal_temps(), implicite_, inconnue(), initialise_residu(), Operateur::l_op_base(), la_zone_Cl_dis, Domaine::le_nom(), Frontiere::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), les_sources, liste_modeles_, mon_probleme, Zone_Cl_dis::nb_cond_lim(), nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), Objet_U::que_suis_je(), schema_temps(), liste::size(), solv_masse(), sub_type, sys_invariant_, Operateur_base::systeme_invariant(), Ref_Probleme_base::valeur(), Deriv_Solveur_Masse_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Debog::verifier().
Referenced by Probleme_base::completer(), Convection_Diffusion_Espece_Binaire_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Chaleur_WC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Navier_Stokes_std::completer(), and Masse_Multiphase::completer().
contribuer_termes_croises()
void Equation_base::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const virtual
Definition at line 2338 of file Equation_base.cpp.
{
  for (int i = 0; i < nombre_d_operateurs(); i++)
    operateur(i).l_op_base().contribuer_termes_croises(inco, autre_pb, autre_inco, matrice);
}
References Operateur_base::contribuer_termes_croises(), Operateur::l_op_base(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
corriger_derivee_expl()
DoubleTab & Equation_base::corriger_derivee_expl (DoubleTab & d) virtual
Reimplemented in Navier_Stokes_std.
Definition at line 2204 of file Equation_base.cpp.
{
  return d;
}
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), and Schema_Adams_Moulton_base::modifier_second_membre_full_impl().
corriger_derivee_impl()
DoubleTab & Equation_base::corriger_derivee_impl (DoubleTab & d) virtual
Reimplemented in Navier_Stokes_std.
Definition at line 2208 of file Equation_base.cpp.
{
  return d;
}
Referenced by derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
creer_champ()
void Equation_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Reimplemented in Convection_Diffusion_Temperature, Navier_Stokes_std, QDM_Multiphase, and Conduction.
Definition at line 1432 of file Equation_base.cpp.
{
  if (motlu == "volume_maille")
    {
      if (!volume_maille.non_nul())
        {
          discretisation().volume_maille(schema_temps(),zone_dis(),volume_maille);
          champs_compris_.ajoute_champ(volume_maille);
        }
    }
// pour recuperer une equation const !!!!!
  const Equation_base& me_const =(*this);
  const Nom& nom_inco=me_const.inconnue()->le_nom();
  Nom inco(nom_inco);
  inco += "_residu";
  if (motlu == Motcle(inco))
    {
      if (!field_residu_.non_nul())
        {
          discretisation().residu(zone_dis(),inconnue(),field_residu_);
          champs_compris_.ajoute_champ(field_residu_);
        }
    }
  int nb_op = nombre_d_operateurs();
  for (int i=0; i<nb_op; i++)
    {
      if (operateur(i).op_non_nul())
        operateur(i).l_op_base().creer_champ(motlu);
    }
  LIST_CURSEUR(Source) curseur = les_sources;
  while(curseur)
    {
      if (curseur.valeur().non_nul())
        curseur.valeur()->creer_champ(motlu);
      ++curseur;
    }
}
References Champs_compris::ajoute_champ(), champs_compris_, Operateur_base::creer_champ(), discretisation(), field_residu_, inconnue(), Operateur::l_op_base(), O_U_Ptr::le_nom(), les_sources, LIST_CURSEUR, nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), Discretisation_base::residu(), schema_temps(), List_Source::valeur(), Discretisation_base::volume_maille(), volume_maille, and zone_dis().
Referenced by Probleme_base::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), and Conduction::creer_champ().
derivee_en_temps() [1/2]
virtual Champ_Inc & Equation_base::derivee_en_temps () inline virtual
Definition at line 271 of file Equation_base.h.
  {
    return derivee_en_temps_;
  }
References derivee_en_temps_.
derivee_en_temps() [2/2]
virtual const Champ_Inc & Equation_base::derivee_en_temps () const inline virtual
Definition at line 267 of file Equation_base.h.
  {
    return derivee_en_temps_;
  };
References derivee_en_temps_.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Adams_Moulton_base::changer_temps(), derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), discretiser(), initTimeStep(), mettre_a_jour(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), preparer_calcul(), and Schema_Adams_Moulton_base::update_time_derivative().
derivee_en_temps_conv()
DoubleTab & Equation_base::derivee_en_temps_conv (DoubleTab & secmem, const DoubleTab & solution)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
< derivee=conv(solution_loc)
< secmem+=conv(solution)
Definition at line 1809 of file Equation_base.cpp.
{
  double dt = le_schema_en_temps->pas_de_temps();
  double dt_convection;
  if (le_schema_en_temps->no_conv_subiteration_diffusion_implicite())
    {
// faux mais permet de ne pas sous iterer sur la convection
      dt_convection=1e38;
    }
  else
    dt_convection= operateur(1).calculer_pas_de_temps();
  if(inf_strict(dt_convection,dt))
    {
// Several steps (nstep) are done if the convective time step
// is smaller than the time step (dt) :
      double epsilon = 1.e-10;
      int nstep = (int)((dt / dt_convection)*(1+epsilon)) + 1 ;
      if (( nstep % 2 ) != 0 ) nstep += 1 ;
      double dt_loc = dt/double(nstep) ;
      Cout << "Convection Semi Implicite: Number of Sub-Cycles : " << nstep << " with dt_loc = " << dt_loc << " dt =" << dt << finl ;
      secmem = 0;
      DoubleTab solution_loc(solution) ;
      DoubleTab derivee;
      derivee.copy(secmem, Array_base::NOCOPY_NOINIT);
      for (int i=0; i<nstep; i++)
        {
          derivee = 0. ;
          operateur(1).ajouter(solution_loc, derivee); //!< derivee=conv(solution_loc)
          derivee.echange_espace_virtuel();
          secmem += derivee ;
// Si ce n'est pas la derniere iteration:
          if (i+1 < nstep)
            {
              solveur_masse.appliquer(derivee);
              solution_loc.ajoute(dt_loc, derivee, VECT_REAL_ITEMS);
              solution_loc.echange_espace_virtuel();
            }
        }
      secmem /= double(nstep) ;
      return secmem;
    }
  else
    {
      operateur(1).ajouter(solution, secmem); //!< secmem+=conv(solution)
      return secmem;
    }
}
References TRUSTVect< _TYPE_ >::ajoute(), Operateur::ajouter(), Solveur_Masse::appliquer(), Operateur::calculer_pas_de_temps(), TRUSTTab< _TYPE_ >::copy(), Cout, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, inf_strict(), le_schema_en_temps, Schema_Temps_base::no_conv_subiteration_diffusion_implicite(), Array_base::NOCOPY_NOINIT, operateur(), Schema_Temps_base::pas_de_temps(), solveur_masse, and VECT_REAL_ITEMS.
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Source_PDF_EF::impr(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), and Convection_Diffusion_Temperature::transport_ibc().
derivee_en_temps_inco()
DoubleTab & Equation_base::derivee_en_temps_inco (DoubleTab & derivee) virtual
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Temperature, Navier_Stokes_std, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 840 of file Equation_base.cpp.
{
  derivee=0;
  DoubleTrav secmem(derivee);
// secmem = sum(operators) + sources + equation specific terms
  if (schema_temps().diffusion_implicite())
    {
// Add convection operator only if equation has one
      derivee=inconnue().valeurs();
      if (nombre_d_operateurs()>1)
        derivee_en_temps_conv(secmem, derivee);
    }
  else
    {
// Add all explicit operators
      for(int i=0; i<nombre_d_operateurs(); i++)
        if(operateur(i).l_op_base().get_decal_temps()!=1)
          operateur(i).ajouter(secmem);
    }
  les_sources.ajouter(secmem);
  if (calculate_time_derivative())
    {
// Store dI/dt(n) = M-1 secmem :
      derivee_en_temps().valeurs()=secmem;
      solveur_masse.appliquer(derivee_en_temps().valeurs());
      schema_temps().modifier_second_membre((*this),secmem); //!< Change secmem for some schemes (eg: Adams_Bashforth)
    }
  corriger_derivee_expl(secmem); //!< Add specific term for an equation (eg: -gradP for Navier Stokes)
  if (implicite_==0)
    {
      solveur_masse.appliquer(secmem); //!< M-1 * secmem
      if (schema_temps().diffusion_implicite())
        {
// Solve: (1/dt + M-1*A)*dI = M-1 * secmem
// where A is the diffusion
          Equation_base::Gradient_conjugue_diff_impl(secmem, derivee);
        }
      else
        {
          derivee = secmem;
          derivee.echange_espace_virtuel();
        }
      corriger_derivee_impl(derivee);  //!< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
    }
  else if (implicite_>0)
    {
// TRUST support notices that this part has never been covered...
// implicite
// M dU/dt + AU* = f -BUn;
// U* = Un+dt dU/dt
// (M/dt + A) U* = f -BUn + M/dt Un
//
      double dt=schema_temps().pas_de_temps();
      for(int i=0; i<nombre_d_operateurs(); i++)
        {
// boucle sur les operateurs
          Operateur_base& op=operateur(i).l_op_base();
          if(!op.get_matrice().non_nul())
            op.set_matrice().typer("Matrice_Morse");
          if(op.get_decal_temps()==1)
            {
// if (op.set_matrice().valeur().nb_lignes()<2)
              {
                Matrice_Morse& matrice=ref_cast(Matrice_Morse,op.set_matrice().valeur());
                op.dimensionner(matrice);
                sys_invariant_=0;
              }
              if(!sys_invariant_)
                {
                  Matrice_Morse& matrice=ref_cast(Matrice_Morse, op.set_matrice().valeur());
                  op.contribuer_a_avec(inconnue().valeurs(), matrice);
                  solv_masse().ajouter_masse(dt, op.set_matrice().valeur());
                  if(
                    (op.get_solveur()->que_suis_je()=="Solv_Cholesky")
                    ||
                    (op.get_solveur()->que_suis_je()=="Solv_GCP")
                  )
                    {
                      Matrice_Morse_Sym new_mat(matrice);
                      new_mat.set_est_definie(1);
                      op.set_matrice()=new_mat;
                      ref_cast_non_const(SolveurSys,op.get_solveur())->reinit();
                    }
                }
            }
        }
      if(implicite_==1)
        {
// Un seul operateur implicite.
// On suppose que c'est le premier (la diffusion !!)
          Operateur_base& op=operateur(0).l_op_base();
          Matrice_Base& matrice=op.set_matrice().valeur();
// DoubleTrav secmem(derivee);
          secmem=derivee;
          solv_masse().ajouter_masse(dt, secmem, inconnue().valeurs());
          op.contribuer_au_second_membre(secmem );
          op.set_solveur().resoudre_systeme(matrice,
                                            secmem,
                                            derivee
                                           );
          solv_masse().corriger_solution(derivee,inconnue().valeurs());
          derivee-=inconnue().valeurs();
          derivee/=dt;
// Sert uniquement a calculer les flux sur les bords quand la diffusion est implicitee !
          DoubleTab resu;
          resu=derivee;
          operateur(0).calculer(inconnue().valeurs(), resu);
        }
      else
        {
// plusieurs operateurs implicites ...
          Cerr << "Must be coded ... " << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error in Equation_base::derivee_en_temps_inco" << finl;
      Cerr << "implicite_ = " << implicite_ << " has not been initialized!" << finl;
      Cerr << "May be " << que_suis_je() << "::completer() method doesn't call Equation_base::completer()" << finl;
      Cerr << "Contact TRUST support." << finl;
      Process::exit();
    }
  return derivee;
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::ajouter_masse(), Solveur_Masse::appliquer(), calculate_time_derivative(), Operateur::calculer(), Cerr, Operateur_base::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), corriger_derivee_expl(), corriger_derivee_impl(), Solveur_Masse::corriger_solution(), derivee_en_temps(), derivee_en_temps_conv(), Operateur_base::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Operateur_base::get_decal_temps(), Operateur_base::get_matrice(), Operateur_base::get_solveur(), Gradient_conjugue_diff_impl(), implicite_, inconnue(), Operateur::l_op_base(), les_sources, Schema_Temps_base::modifier_second_membre(), nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), ref_cast, ref_cast_non_const, SolveurSys::resoudre_systeme(), schema_temps(), Matrice_Sym::set_est_definie(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), solv_masse(), solveur_masse, sys_invariant_, Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Champ_Inc::valeurs().
Referenced by Navier_Stokes_std::derivee_en_temps_inco(), derivee_en_temps_inco_transport(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), Schema_Temps_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqn(), iterer_eqn_expl(), and iterer_eqn_expl_diffusion_implicite().
derivee_en_temps_inco_transport()
virtual DoubleTab & Equation_base::derivee_en_temps_inco_transport (DoubleTab & derivee) inline virtual
Definition at line 117 of file Equation_base.h.
  {
    return derivee_en_temps_inco(derivee);
  };
References derivee_en_temps_inco().
dimensionner_blocs()
void Equation_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const virtual
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
Definition at line 2430 of file Equation_base.cpp.
{
  /* operateurs, masse, sources */
  int nb = nombre_d_operateurs();
  for (int op = 0; op < nb; op++) operateur(op).l_op_base().dimensionner_blocs(matrices, semi_impl);
  solv_masse().valeur().dimensionner_blocs(matrices);
  for (int i = 0; i < les_sources.size(); i++) les_sources(i).valeur().dimensionner_blocs(matrices, semi_impl);
}
References Operateur_base::dimensionner_blocs(), Solveur_Masse_base::dimensionner_blocs(), Operateur::l_op_base(), les_sources, nombre_d_operateurs(), operateur(), liste::size(), solv_masse(), List_Source::valeur(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Navier_Stokes_std::dimensionner_blocs(), Energie_Multiphase::dimensionner_blocs(), Masse_Multiphase::dimensionner_blocs(), and SETS::iterer_eqn().
dimensionner_matrice()
void Equation_base::dimensionner_matrice (Matrice_Morse & mat_morse) virtual
< just to be sure ...
Definition at line 2241 of file Equation_base.cpp.
{
  if (matrice_init)
    {
      matrice.get_set_tab1().ref_array(matrice_stockee.get_set_tab1());
      matrice.get_set_tab2().ref_array(matrice_stockee.get_set_tab2());
      matrice.get_set_coeff().ref_array(matrice_stockee.get_set_coeff());
      matrice.set_nb_columns(matrice_stockee.nb_colonnes());
      matrice.sorted_ = matrice_stockee.sorted_;
      return;
    }
  dimensionner_matrice_sans_mem(matrice); //le vrai appel
  matrice.get_set_coeff() = 0.0;  //!< just to be sure ...
  if (probleme().discretisation().que_suis_je().debute_par("PolyMAC") || probleme().discretisation().que_suis_je() == "DDFV")
    {
      matrice.sort_stencil();
      matrice_stockee.get_set_tab1().ref_array(matrice.get_set_tab1());
      matrice_stockee.get_set_tab2().ref_array(matrice.get_set_tab2());
      matrice_stockee.get_set_coeff().ref_array(matrice.get_set_coeff());
      matrice_stockee.set_nb_columns(matrice.nb_colonnes());
      matrice_stockee.sorted_ = 1;
      matrice_init = 1;
    }
}
References dimensionner_matrice_sans_mem(), discretisation(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), matrice_init, matrice_stockee, Matrice_Morse::nb_colonnes(), probleme(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::ref_array(), Matrice_Morse::set_nb_columns(), Matrice_Morse::sort_stencil(), and Matrice_Morse::sorted_.
Referenced by Gradient_conjugue_diff_impl(), Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), and Solveur_U_P::iterer_NS().
dimensionner_matrice_sans_mem()
void Equation_base::dimensionner_matrice_sans_mem (Matrice_Morse & mat_morse) virtual
< memoization
< this only works if the matrix has been given its overall size first
< this only works if the matrix has been given its overall size first
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
Definition at line 2269 of file Equation_base.cpp.
{
// [ABN]: dimensioning of the implicit matrix: it can receive input from:
// - the operators
// - the mass solver
// - the sources
// We proceed in this order, with the idea that operators should take most of the slots in the Morse
// structure. Having the mass solver first would lead (in VDF, EF and VEF) to diagonal slots
// being reserved before sub-diagonal terms. In the Morse structure coefficients would then
// not be ordered by increasing columns number. This is not desirable, notably for EF which seem to
// be sensitive to this ordering (although they should not ....). Some Baltiks too (FLICA5 - thermic part)
// rely on this.
  if (matrice_init) //!< memoization
    {
      matrice.get_set_tab1().ref_array(matrice_stockee.get_set_tab1());
      matrice.get_set_tab2().ref_array(matrice_stockee.get_set_tab2());
      matrice.get_set_coeff().ref_array(matrice_stockee.get_set_coeff());
      matrice.set_nb_columns(matrice_stockee.nb_colonnes());
      return;
    }
  bool isInit = false;
// Operators first (they're likely to take most of the slots in the Morse structure)
  for(int opp=0; opp < nombre_d_operateurs(); opp++)
    {
      if (!isInit)
        operateur(opp).l_op_base().dimensionner(matrice);
      else
        {
          Matrice_Morse mat2;
          operateur(opp).l_op_base().dimensionner(mat2);
          if (mat2.nb_colonnes())
            matrice += mat2;  //!< this only works if the matrix has been given its overall size first
        }
      isInit = isInit || (matrice.nb_colonnes() != 0);
    }
// ... then the mass solver ...
  if (!isInit)
    solv_masse().valeur().dimensionner(matrice);
  else
    {
      Matrice_Morse mat2;
      solv_masse().valeur().dimensionner(mat2);
      matrice += mat2; //!< this only works if the matrix has been given its overall size first
    }
// and finally sources (mass solver has surely done something already so no need for "isInit" test)
  les_sources.dimensionner(matrice);
}
References Operateur_base::dimensionner(), Sources::dimensionner(), Solveur_Masse_base::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Operateur::l_op_base(), les_sources, matrice_init, matrice_stockee, Matrice_Morse::nb_colonnes(), nombre_d_operateurs(), operateur(), TRUSTVect< _TYPE_ >::ref_array(), Matrice_Morse::set_nb_columns(), solv_masse(), and Deriv_Solveur_Masse_base::valeur().
Referenced by dimensionner_matrice(), Navier_Stokes_std::dimensionner_matrice_sans_mem(), Energie_Multiphase::dimensionner_matrice_sans_mem(), and Masse_Multiphase::dimensionner_matrice_sans_mem().
dimensionner_termes_croises()
void Equation_base::dimensionner_termes_croises (Matrice_Morse & matrice, const Probleme_base & autre_pb, int nl, int nc) virtual
Definition at line 2321 of file Equation_base.cpp.
{
  matrice.dimensionner(nl, nc, 0);
  for(int i = 0; i < nombre_d_operateurs(); i++)
    {
      Matrice_Morse mat2;
      operateur(i).l_op_base().dimensionner_termes_croises(mat2, autre_pb, nl, nc);
      if (mat2.nb_colonnes()) matrice += mat2;
    }
}
References Matrice_Morse::dimensionner(), Operateur_base::dimensionner_termes_croises(), Operateur::l_op_base(), Matrice_Morse::nb_colonnes(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
disable_equation_residual()
int Equation_base::disable_equation_residual () const inline
Definition at line 264 of file Equation_base.h.
{ return disable_equation_residual_; };
References disable_equation_residual_.
Referenced by Schema_Temps_base::update_critere_statio().
discretisation()
const Discretisation_base & Equation_base::discretisation () const
Renvoie la discretisation associee a l'equation.
Returns
Discretisation_base&
Signification: a discretisation associee a l'equation
Contraintes: reference constante
Definition at line 1421 of file Equation_base.cpp.
{
  if(!mon_probleme.non_nul())
    {
      Cerr << "Error : " << que_suis_je()
           << "has not been associated to a problem ! " << finl;
      exit();
    }
  return mon_probleme->discretisation();
}
References Cerr, Probleme_base::discretisation(), Process::exit(), finl, mon_probleme, O_U_Ptr::non_nul(), and Objet_U::que_suis_je().
Referenced by Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Convection_Diffusion_Temperature::assembler(), assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_std::assembler_blocs(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Puissance_Thermique_EF::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_base::calculer_valeurs_som_post(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Paroi_Knudsen_non_negligeable::completer(), Navier_Stokes_std::completer(), Fluide_Dilatable_base::completer(), Fluide_Quasi_Compressible::completer_edo(), creer_champ(), Op_Conv_EF_Stab_PolyMAC_Elem::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Fluide_base::creer_e_int(), dimensionner_matrice(), Operateur::discretisation(), discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Navier_Stokes_std::discretiser_assembleur_pression(), Mod_turb_hyd_base::discretiser_corr_visc_turb(), Mod_turb_hyd_base::discretiser_K(), Reaction::discretiser_omega(), Mod_turb_hyd_base::discretiser_visc_turb(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Discretisation_base::get_name_of_type_for(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Cond_lim_utilisateur_base::is_pb_PolyMAC(), Cond_lim_utilisateur_base::is_pb_PolyMAC_P0(), Cond_lim_utilisateur_base::is_pb_VDF(), Simple::iterer_eqn(), Piso::iterer_NS(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Source_Scalaire_EF::readOn(), Mod_turb_hyd::readOn(), Modele_turbulence_scal::readOn(), Turbulence_paroi::readOn(), Turbulence_paroi_scal::readOn(), Modele_turbulence_hyd_nul::readOn(), Mod_turb_hyd_base::sauvegarder(), Solveur_Masse::typer(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), Operateur_Grad::typer(), Operateur_Evanescence::typer(), Source::typer(), and verif_Cl().
discretiser()
void Equation_base::discretiser () virtual
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
Reimplemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, and Conduction.
Definition at line 1074 of file Equation_base.cpp.
{
  discretisation().zone_Cl_dis(zone_dis(), la_zone_Cl_dis);
  la_zone_Cl_dis->associer_eqn(*this);
  la_zone_Cl_dis->associer_inconnue(inconnue());
  solveur_masse.typer();
  solveur_masse->associer_zone_dis_base(zone_dis().valeur());
  solveur_masse->associer_zone_cl_dis_base(la_zone_Cl_dis.valeur());
  if (calculate_time_derivative())
    {
      Motcle directive("temperature");
      if (inconnue().valeur().nature_du_champ()==vectoriel)
        directive="vitesse";
      Nom nom("derivee_en_temps_");
      nom += inconnue().valeur().le_nom();
      Nom unite(inconnue().valeur().unites()[0]);
      unite += "/s";
      discretisation().discretiser_champ(directive,zone_dis().valeur(),nom,unite,
                                         inconnue().valeur().nb_comp(),
                                         schema_temps().nb_valeurs_temporelles(),
                                         schema_temps().temps_courant(),derivee_en_temps());
      champs_compris_.ajoute_champ(derivee_en_temps());
    }
}
References Champs_compris::ajoute_champ(), Zone_Cl_dis::associer_eqn(), calculate_time_derivative(), champs_compris_, derivee_en_temps(), discretisation(), Discretisation_base::discretiser_champ(), inconnue(), la_zone_Cl_dis, Field_base::le_nom(), schema_temps(), solveur_masse, Solveur_Masse::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), valeur(), vectoriel, Discretisation_base::zone_Cl_dis(), and zone_dis().
Referenced by Equation::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Probleme_base::discretiser(), Pb_Multiphase::lire_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
domaine_application()
const Motcle & Equation_base::domaine_application () const virtual
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
Returns
Motcle&
Signification: le nom du domaine d'aplication
Contraintes: reference constante
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, and Conduction.
Definition at line 1745 of file Equation_base.cpp.
{
  static Motcle defaut="indetermine";
  return defaut;
}
Referenced by Dirichlet_paroi_defilante::compatible_avec_eqn(), Scalaire_impose_paroi::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::compatible_avec_eqn(), Echange_externe_impose_H::compatible_avec_eqn(), Entree_fluide_temperature_imposee_H::compatible_avec_eqn(), Neumann_sortie_libre_Temp_H::compatible_avec_eqn(), Temperature_imposee_paroi_H::compatible_avec_eqn(), Sortie_libre_pression_imposee_QC::compatible_avec_eqn(), Dirichlet_paroi_fixe::compatible_avec_eqn(), Entree_fluide_concentration_imposee::compatible_avec_eqn(), Entree_fluide_Fluctu_Temperature_imposee::compatible_avec_eqn(), Entree_fluide_Flux_Chaleur_Turbulente_imposee::compatible_avec_eqn(), Entree_fluide_fraction_massique_imposee::compatible_avec_eqn(), Entree_fluide_T_h_imposee::compatible_avec_eqn(), Entree_fluide_temperature_imposee::compatible_avec_eqn(), Entree_fluide_V2_impose::compatible_avec_eqn(), Entree_fluide_vitesse_imposee::compatible_avec_eqn(), Neumann_paroi::compatible_avec_eqn(), Neumann_paroi_adiabatique::compatible_avec_eqn(), Neumann_paroi_flux_nul::compatible_avec_eqn(), Neumann_sortie_libre::compatible_avec_eqn(), Paroi_Knudsen_non_negligeable::compatible_avec_eqn(), Sortie_libre_pression_imposee::compatible_avec_eqn(), Sortie_libre_pression_moyenne_imposee::compatible_avec_eqn(), Sortie_libre_Text_H_ext::compatible_avec_eqn(), Temperature_imposee_paroi::compatible_avec_eqn(), Entree_fluide_alpha_impose::compatible_avec_eqn(), Echange_couplage_thermique::compatible_avec_eqn(), Echange_impose_base::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_impose::compatible_avec_eqn(), Sortie_libre_Pression_imposee_Orlansky::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_impose_VEF::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_libre_VEF::compatible_avec_eqn(), and Echange_contact_VDF::initialiser().
ecrire_fichier_xyz()
void Equation_base::ecrire_fichier_xyz () const private
Ecrit dans un fichier les valeurs du champ specifie
par le mot cle "ecrire_fichier_xyz_valeur".
< on ne souhaite postraiter que sur certains bords
< int servant a tester si le nom du bord correspond bien au nom d'une frontiere
< on souhaite postraiter sur tout le domaine
Definition at line 405 of file Equation_base.cpp.
{
  for (int numero_champ_xyz=0; numero_champ_xyz<nombre_champ_xyz; numero_champ_xyz++)
    {
      Noms vide;
      const double dt_ecrire_fic = dt_ecrire_fic_xyz[numero_champ_xyz];
      const Motcle& nom_champ = nom_champ_xyz[numero_champ_xyz];
      const int nb_bords_post = nb_bords_post_xyz[numero_champ_xyz];
      const Noms& noms_bord = (nb_bords_post?noms_bord_xyz[numero_champ_xyz]:vide);
      REF(Champ_base) champ_a_ecrire;
      const double temps_courant = le_schema_en_temps->temps_courant();
      const double dt = le_schema_en_temps->pas_de_temps();
      const double tmax = le_schema_en_temps->temps_max();
      const int nb_pas_dt_max = le_schema_en_temps->nb_pas_dt_max();
      const int nb_pas_dt = le_schema_en_temps->nb_pas_dt();
      const int stationnaire_atteint = le_schema_en_temps->stationnaire_atteint();
      int ok;
      if (dt_ecrire_fic<=dt || tmax<=temps_courant || nb_pas_dt_max<=nb_pas_dt || nb_pas_dt<=1 || stationnaire_atteint || le_schema_en_temps.valeur().stop_lu())
        ok=1;
      else
        {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
          double i, j, epsilon = 1.e-8;
          modf(temps_courant/dt_ecrire_fic + epsilon, &i);
          modf((temps_courant-dt)/dt_ecrire_fic + epsilon, &j);
          ok = (i>j);
        }
      int champ_ok = 0;
      int champ_stat = 0;
      REF(Operateur_Statistique_tps_base) op_stat;
      if (ok && dt_ecrire_fic>0)
        {
// On recherche le champ dans le probleme contenant l'equation, et les postraitements
// dans les postraitements ?
          CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur = mon_probleme->postraitements();
          while(curseur && !champ_ok)
            {
              if (sub_type(Postraitement,curseur.valeur().valeur()))
                {
                  const Postraitement& post = ref_cast(Postraitement,curseur.valeur().valeur());
                  if (champ_ok==0)
                    {
                      Motcle nom_test = nom_champ;
// La recherche est faite sur les champs statistiques a partir d un identifiant
// Si le nom indique dans le jeux de donnes est celui d un champ statistiques
// il doit correspondre au nom du champ de postraitement
                      post.champ_fonc(nom_test,champ_a_ecrire,op_stat);
                      if (champ_a_ecrire.non_nul())
{
                          champ_stat = 1;
                          champ_ok = 1;
                        }
                    }
                }
              ++curseur;
            }
          if (champ_ok==0)
// L identifiant correspond ici a un Champ_base
            champ_a_ecrire = mon_probleme.valeur().get_champ(nom_champ);
          int nb_compo = champ_a_ecrire->nb_comp();
          if (nb_bords_post>0) //!< on ne souhaite postraiter que sur certains bords
            {
              int nb_cl = la_zone_Cl_dis->nb_cond_lim();
              for (int j=0; j<nb_bords_post; j++)
                {
                  int count = 0 ; //!< int servant a tester si le nom du bord correspond bien au nom d'une frontiere
                  for (int i=0; i<nb_cl; i++)
                    {
                      const Cond_lim_base& la_cl = la_zone_Cl_dis.valeur().les_conditions_limites(i);
                      const Frontiere& la_frontiere = la_cl.frontiere_dis().frontiere();
                      if (la_frontiere.le_nom() == noms_bord[j])
{
// Construction du nom du fichier
                          Nom nom_fic(probleme().le_nom());
                          nom_fic+="_";
                          nom_fic+=nom_champ;
                          nom_fic+="_";
                          nom_fic+=noms_bord[j];
                          nom_fic+="_";
                          nom_fic+=Nom(temps_courant);
                          nom_fic+=".dat";
                          EcrFicPartage fic;
                          fic.set_bin(ecrit_champ_xyz_bin);
                          fic.ouvrir(nom_fic);
                          fic.setf(ios::scientific);
                          fic.precision(format_precision_geom);
// Construction du tableau pos contenant les centres des faces frontiere
                          const int nb_val = la_frontiere.nb_faces();
                          DoubleTab pos;
                          la_frontiere.faces().calculer_centres_gravite(pos);
// Construction du tableau val contenant les valeurs aux centres des faces
                          DoubleTab val(nb_val,nb_compo);
                          val = 0.;
                          if (champ_stat == 1)
{
                              DoubleTab copie(champ_a_ecrire->valeurs());
                              champ_a_ecrire->valeurs() = op_stat->calculer_valeurs();
                              champ_a_ecrire->valeur_aux(pos, val);
                              champ_a_ecrire->valeurs() = copie;
                            }
                          else
                            champ_a_ecrire->valeur_aux(pos, val);
// Ecriture du fichier
                          int nb_val_tot = Process::mp_sum(nb_val);
                          if (Process::je_suis_maitre())
{
                              if(ecrit_champ_xyz_bin)
                                fic << "binary" << finl;
                              fic  << nb_val_tot << finl;
                            }
                          barrier();
                          fic.lockfile();
                          for (int i2=0; i2<nb_val; i2++)
{
// Ecriture des coordonees
                              for (int j2=0; j2<dimension; j2++)
                                fic << pos(i2,j2) << " ";
// Ecriture des valeurs
                              for (int nb=0; nb<nb_compo; nb++)
                                fic << val(i2,nb) << " " ;
                              fic << finl;
                            }
                          fic.unlockfile();
                          barrier();
                          fic.syncfile();
                          fic.close();
                        }
                      else
{
                          count++;
                        }
                    }
                  if (count==nb_cl)
                    {
                      Cerr << "You try to use the method Ecrire_fichier_xyz_valeur with an unknow name boundary" << finl;
                      Cerr << "The boundary named " << noms_bord[j] << " is not recognized"<< finl;
                      exit();
                    }
                }
            }
          else //!< on souhaite postraiter sur tout le domaine
            {
              Cerr << "The option of post processing the entire domain with Ecrire_fichier_xyz_valeur is now obsolete." <<finl;
              exit();
            }
        }
    }
}
References Process::barrier(), Faces::calculer_centres_gravite(), Cerr, Postraitement::champ_fonc(), EcrFicPartage::close(), CONST_LIST_CURSEUR, DERIV, Objet_U::dimension, dt_ecrire_fic_xyz, ecrit_champ_xyz_bin, Process::exit(), Frontiere::faces(), finl, Objet_U::format_precision_geom, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Probleme_base::get_champ(), Process::je_suis_maitre(), la_zone_Cl_dis, le_nom(), Frontiere::le_nom(), le_schema_en_temps, Zone_Cl_dis_base::les_conditions_limites(), EcrFicPartage::lockfile(), mon_probleme, Process::mp_sum(), nb_bords_post_xyz, Field_base::nb_comp(), Zone_Cl_dis::nb_cond_lim(), Frontiere::nb_faces(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), nom_champ_xyz, nombre_champ_xyz, noms_bord_xyz, EcrFicPartage::ouvrir(), Schema_Temps_base::pas_de_temps(), Probleme_base::postraitements(), EcrFicPartage::precision(), probleme(), REF, ref_cast, EcrFicPartage::set_bin(), Sortie_Fichier_base::setf(), Schema_Temps_base::stationnaire_atteint(), Schema_Temps_base::stop_lu(), sub_type, EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_max(), EcrFicPartage::unlockfile(), Ref_Probleme_base::valeur(), Ref_Schema_Temps_base::valeur(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by imprimer().
equation_non_resolue()
int Equation_base::equation_non_resolue () const virtual
Definition at line 67 of file Equation_base.cpp.
{
  std::string str= equation_non_resolue_.getString();
  std::string str2("INPUT_INT_VALUE");
  if (str.compare(str2)==0)
    {
      Nom name = eq_non_resolue_input_.getName();
      int eq_non_resolue_int = mon_probleme.valeur().getOutputIntValue(name);
      return eq_non_resolue_int;
    }
  else
    {
      double t = le_schema_en_temps->temps_courant();
      equation_non_resolue_.setVar("t",t);
      return (int)equation_non_resolue_.eval();
    }
}
References eq_non_resolue_input_, equation_non_resolue_, Parser_U::eval(), Value_Input_Int::getName(), Probleme_U::getOutputIntValue(), Parser_U::getString(), le_schema_en_temps, mon_probleme, Parser_U::setVar(), Schema_Temps_base::temps_courant(), and Ref_Probleme_base::valeur().
Referenced by Schema_Temps_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), and Simple::iterer_eqn().
expression_residu()
Nom Equation_base::expression_residu () virtual
Definition at line 2542 of file Equation_base.cpp.
{
  int size = residu_.size_array();
  Nom tmp(""),ajout("");
  if (probleme().get_coupled())
    {
      ajout="_";
      ajout+=probleme().le_nom();
    }
  for (int i=0; i<size; i++)
    {
      tmp+="Ri=max";
      tmp+=ajout;
      tmp+="|d";
// Comment nommer de facon claire ET concise
// le champ de l'expression:
      if (size==1)
        {
// Champ scalaire
          tmp+=(Motcle)inconnue().le_nom()[0];
        }
      else
        {
// Champ multiscalaire
          if (inconnue()->nom_compo(0)[0]!=inconnue()->nom_compo(size-1)[0])
            {
// Exemple, champ K_Eps
              tmp+=(Motcle)inconnue()->nom_compo(i)[0];
            }
          else
            {
// Exemple, champ concentration
              tmp+=(Motcle)inconnue().le_nom()[0];
              tmp+=(Nom)i;
            }
        }
      tmp+="/dt|\t ";
    }
  return tmp;
}
References inconnue(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), probleme(), residu_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Schema_Temps_base::initialize().
get_champ()
const Champ_base & Equation_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Convection_Diffusion_Espece_Multi_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Temperature, Navier_Stokes_std, and Conduction.
Definition at line 1473 of file Equation_base.cpp.
{
  REF(Champ_base) ref_champ;
  Nom inco_residu (inconnue()->le_nom());
  inco_residu += "_residu";
  if (nom=="volume_maille")
    {
      Champ_Fonc_base& ch_vol_maille=ref_cast_non_const(Champ_Fonc_base,volume_maille.valeur());
      if (est_different(ch_vol_maille.temps(),inconnue()->temps()))
        ch_vol_maille.mettre_a_jour(inconnue()->temps());
    }
  else if(nom == Motcle(inco_residu))
    {
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,field_residu_.valeur());
      double temps_init = schema_temps().temps_init();
      if (((ch.temps()!=inconnue()->temps()) || (ch.temps()==temps_init)) && (inconnue()->mon_equation_non_nul()))
        {
          ch.mettre_a_jour(inconnue()->temps());
        }
    }
  else
    {
      CONST_LIST_CURSEUR(Champ_Fonc) curseur = list_champ_combi;
      while(curseur)
        {
          const Champ_Fonc& ch = curseur.valeur();
          if (ch.le_nom()==nom && ch.temps()!=inconnue()->temps())
            ref_cast_non_const( Champ_Fonc,ch).mettre_a_jour(inconnue()->temps());
          ++curseur;
        }
    }
  try
    {
      return champs_compris_.get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  try
    {
      return milieu().get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  int nb_op = nombre_d_operateurs();
  for (int i=0; i<nb_op; i++)
    {
      if (operateur(i).op_non_nul())
        try
          {
            return operateur(i).l_op_base().get_champ(nom);
          }
        catch (Champs_compris_erreur)
          {
          }
    }
  CONST_LIST_CURSEUR(Source) curseur = les_sources;
  while(curseur)
    {
      if (curseur.valeur().non_nul())
        try
          {
            return curseur.valeur()->get_champ(nom);
          }
        catch (Champs_compris_erreur)
          {
          }
      ++curseur;
    }
  throw Champs_compris_erreur();
  return ref_champ;
}
References champs_compris_, CONST_LIST_CURSEUR, est_different(), field_residu_, Champs_compris::get_champ(), Milieu_base::get_champ(), Operateur_base::get_champ(), inconnue(), Operateur::l_op_base(), le_nom(), O_U_Ptr::le_nom(), les_sources, list_champ_combi, Champ_Fonc_base::mettre_a_jour(), milieu(), nombre_d_operateurs(), operateur(), REF, ref_cast_non_const, schema_temps(), Champ_base::temps(), Champ_Fonc::temps(), Schema_Temps_base::temps_init(), List_Source::valeur(), Deriv_Champ_Fonc_base::valeur(), and volume_maille.
Referenced by Solveur_Masse_base::appliquer(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), calculer_champ_conserve(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Assembleur_P_PolyMAC::dimensionner_continuite(), Probleme_base::get_champ(), Convection_Diffusion_Espece_Multi_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Conduction::get_champ(), Probleme_base::has_champ(), Op_EF_base::marque_elem(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), and Solveur_Masse_base::set_name_of_coefficient_temporel().
get_fonc_champ_conserve()
virtual std::pair< std::string, fonc_calc_t > Equation_base::get_fonc_champ_conserve () const inline virtual
Reimplemented in Energie_Multiphase, and Masse_Multiphase.
Definition at line 210 of file Equation_base.h.
  {
    return { inconnue().le_nom().getString(), calculer_champ_conserve};
  }
References calculer_champ_conserve(), Nom::getString(), inconnue(), and O_U_Ptr::le_nom().
Referenced by init_champ_conserve().
get_info()
const Type_info * Equation_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, and Conduction.
Definition at line 48 of file Equation_base.cpp.
get_modele()
const RefObjU & Equation_base::get_modele (Type_modele type) const virtual
Definition at line 2213 of file Equation_base.cpp.
{
  return liste_modeles_(0);
}
References liste_modeles_.
Referenced by Op_Dift_VDF_base::ajouter_blocs(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), calculer_h_distant(), calculer_h_local(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Op_Dift_EF_base::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Op_Dift_VEF_base::completer(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Traitement_particulier_NS_Profils::lire(), PlaqThVDF::mettre_a_jour(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Modele_turbulence_scal_base::readOn(), and Turbulence_paroi_scal::readOn().
get_noms_champs_postraitables()
void Equation_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_std, and Conduction.
Definition at line 1555 of file Equation_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<que_suis_je()<<" : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    noms.add(champs_compris_.liste_noms_compris());
  milieu().get_noms_champs_postraitables(noms,opt);
  int nb_op = nombre_d_operateurs();
  for (int i=0; i<nb_op; i++)
    {
      if (operateur(i).op_non_nul())
        operateur(i).l_op_base().get_noms_champs_postraitables(noms,opt);
    }
  CONST_LIST_CURSEUR(Source) curseur = les_sources;
  while(curseur)
    {
      if (curseur.valeur().non_nul())
        curseur.valeur()->get_noms_champs_postraitables(noms,opt);
      ++curseur;
    }
}
References Vect_Nom::add(), Cerr, champs_compris_, CONST_LIST_CURSEUR, DESCRIPTION, finl, Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Operateur::l_op_base(), les_sources, Champs_compris::liste_noms_compris(), milieu(), nombre_d_operateurs(), operateur(), Objet_U::que_suis_je(), and List_Source::valeur().
Referenced by Probleme_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), and Conduction::get_noms_champs_postraitables().
get_residu()
DoubleVect & Equation_base::get_residu () inline
Definition at line 153 of file Equation_base.h.
  {
    return residu_;
  };
References residu_.
Referenced by Schema_Temps_base::update_critere_statio().
Gradient_conjugue_diff_impl() [1/3]
void Equation_base::Gradient_conjugue_diff_impl (DoubleTrav & secmem, DoubleTab & solution) inline
Definition at line 246 of file Equation_base.h.
  {
    return Gradient_conjugue_diff_impl(secmem,solution,0,NULL_);
  };
References Gradient_conjugue_diff_impl(), and NULL_.
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Gradient_conjugue_diff_impl(), and Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star().
Gradient_conjugue_diff_impl() [2/3]
void Equation_base::Gradient_conjugue_diff_impl (DoubleTrav & secmem, DoubleTab & solution, const DoubleTab & terme_mul) inline
Definition at line 250 of file Equation_base.h.
  {
    return Gradient_conjugue_diff_impl(secmem,solution,terme_mul.dimension_tot(0),terme_mul);
  };
References TRUSTTab< _TYPE_ >::dimension_tot(), and Gradient_conjugue_diff_impl().
Gradient_conjugue_diff_impl() [3/3]
void Equation_base::Gradient_conjugue_diff_impl (DoubleTrav & secmem, DoubleTab & solution, int size_terme_mul, const DoubleTab & term_mul) private
Solve: (1/dt + M-1*L)*dI = M-1 * secmem
with a Conjugate Gradient matrix-free algorithm by default
L is the diffusion
M is the mass
In : solution=I(n)
Out: solution=dI/dt.
< I(n) On multiplie secmem par M (qui etait divise par M avant l'appel...)
< A=0 Add diffusion matrix L into matrix
< A=L
< A=M/dt+L
< New matrix but same sparsity
< dI=I(n+1)-I(n)
< dI/dt
< ,VECT_REAL_ITEMS);
< la partie Bord de l'operateur.
< Crank - Nicholson -> 0.5
< residu = Ax
< residu = Ax-B
< z = D-1(Ax-B)
< z = Ax-B
< Il est mieux d'utiliser cette valeur pour entrer dans la boucle car seuil peut etre tres grand si le calcul diverge avant
< On retire la contribution des bords.
< preconditionnement par diag^(-1) sinon z=residu
Definition at line 1866 of file Equation_base.cpp.
{
  if (le_schema_en_temps->impr_diffusion_implicite())
    Cout << "Implicited diffusion algorithm applied on " << que_suis_je() << " equation:" << finl;
  int marq_tot = 0;
  int size_s = sources().size();
  ArrOfInt marq(size_s);
  for (int i = 0; i < size_s; i++)
    {
      if (sub_type(Source_dep_inco_base, sources()(i).valeur()))
        {
          marq[i] = 1;
          marq_tot = 1;
        }
    }
  bool has_diffusion_implicit_solver = parametre_equation().non_nul() &&
                                       sub_type(Parametre_diffusion_implicite, parametre_equation().valeur()) &&
                                       ref_cast(Parametre_diffusion_implicite, parametre_equation().valeur()).solveur().non_nul();
  if (has_diffusion_implicit_solver)
    {
// PL: Solve (M/dt + L)*dI = Secmem(sans diffusion) with a matrix build to use more solvers
      if (marq_tot)
        {
          Cerr << "solveur_dffusion_implicite can't be used yet with source terms depending from the unknowns. " << finl;
          Process::exit();
        }
      if (size_terme_mul)
        {
          Cerr << "solveur_dffusion_implicite can't be used yet with penalization. " << finl;
          Process::exit();
        }
      statistiques().begin_count(assemblage_sys_counter_);
      DoubleTab present(solution); //!< I(n) On multiplie secmem par M (qui etait divise par M avant l'appel...)
//
      DoubleTab copie(secmem);
      secmem = 0;
      solveur_masse.ajouter_masse(1, secmem, copie);
// Build matrix A:
      Matrice_Morse& matrice = ref_cast(Parametre_diffusion_implicite, parametre_equation().valeur()).matrice();
      if (matrice.ordre()==0) dimensionner_matrice(matrice);
      matrice.clean(); //!< A=0 Add diffusion matrix L into matrix
//
      operateur(0).l_op_base().contribuer_a_avec(present, matrice); //!< A=L
      statistiques().end_count(assemblage_sys_counter_);
      operateur(0).ajouter(present, secmem);
      statistiques().begin_count(assemblage_sys_counter_);
      matrice.ajouter_multvect(present, secmem);
// Add M/dt into matrix
      schema_temps().ajouter_inertie(matrice,secmem,(*this)); //!< A=M/dt+L
      modifier_pour_Cl(matrice,secmem);
      statistiques().end_count(assemblage_sys_counter_,0,0);
// Solve to get I(n+1):
      SolveurSys& solveur = ref_cast(Parametre_diffusion_implicite, parametre_equation().valeur()).solveur();
      solveur->reinit(); //!< New matrix but same sparsity
      int niter = solveur.resoudre_systeme(matrice, secmem, solution);
      Cout << "Diffusion operator implicited for the equation " << que_suis_je()
           << " : Conjugate gradient converged in " << niter << " iterations." << finl;
// CHD 230501 : Call to diffusive operator to update flux_bords (boundary fluxes):
      operateur(0).ajouter(inconnue(), secmem);
      solution-=present; //!< dI=I(n+1)-I(n)
      solution/=schema_temps().pas_de_temps(); //!< dI/dt
    }
  else
    {
      statistiques().begin_count(diffusion_implicite_counter_);
// on retire les sources dependantes de l inco ; on les rajoutera apres
      if (marq_tot)
        {
          DoubleTrav toto(secmem);
          statistiques().end_count(diffusion_implicite_counter_,0,0);
          for (int i = 0; i < size_s; i++)
            if (marq[i])
              sources()(i).ajouter(toto);
          statistiques().begin_count(diffusion_implicite_counter_);
          solv_masse().appliquer(toto);
          secmem.ajoute(-1., toto); //!< ,VECT_REAL_ITEMS);
        }
      int n = secmem.size_totale();
      if (solution.size_totale() != n)
        {
          Cerr << "the size of the solution and the second member does not match";
          exit();
        }
// Le nombre maximal d'iteration peut etre desormais borne par niter_max_diff_impl
      int nmax = le_schema_en_temps->niter_max_diffusion_implicite();
      DoubleTab p(solution);
      p = 0;
      DoubleTab phiB(p); //!< la partie Bord de l'operateur.
      DoubleTab resu(p);
      DoubleTab merk(solution);
      double aCKN = 1; //!< Crank - Nicholson -> 0.5
// Calcul de la matrice Diagonale
      int precond_diag = 0;
// On preconditionne par la diagonale si on penalise
// car sinon residu initial trop grand
      if (size_terme_mul) precond_diag = 1;
      double seuil_diffusion_implicite = le_schema_en_temps->seuil_diffusion_implicite();
// Recuperation eventuelle d'options de Parametre_diffusion_implicite
      if (parametre_equation().non_nul() && (sub_type(Parametre_diffusion_implicite, parametre_equation().valeur())))
        {
          const Parametre_diffusion_implicite& param = ref_cast(Parametre_diffusion_implicite,
                                                                parametre_equation().valeur());
          if (param.crank())
            aCKN = 0.5;
          precond_diag = param.precoditionnement_diag();
// Bug fixed : Diagonal preconditionning is fixed with periodic BC (it is OK for a parallel calculation)
// if (precond_diag==1 && Process::nproc()>1)
// {
// Cerr << "Error with the value of preconditionnement_diag option which is set to " << precond_diag << "." << finl;
// Cerr << "The diagonal preconditionning is unavailable for a parallel calculation." << finl;
// Cerr << "The CG used to solve the implicitation of the equation diffusion operator can not preconditioned." << finl;
// Cerr << "So edit your .data file with preconditionnement_diag = 0 and run your case." << finl;
// exit();
// }
          if (param.seuil_diffusion_implicite() > 0)
            seuil_diffusion_implicite = param.seuil_diffusion_implicite();
          if (param.nb_it_max() > 0)
            nmax = param.nb_it_max();
        }
      statistiques().end_count(diffusion_implicite_counter_,0,0);
//
// Preconditionnement
//
      double dt = le_schema_en_temps->pas_de_temps();
      Matrice_Morse_Diag diag;
      if (precond_diag)
        {
          statistiques().begin_count(assemblage_sys_counter_);
          const int nb_case = inconnue().valeurs().dimension_tot(0);
          const int nb_comp = inconnue().valeurs().line_size();
          if (nb_comp * nb_case != n)
            {
              Cerr << "the size of the unknown and the second member does not match" << finl;
              Cerr << "dimension_tot nbdim1 nb_comp = " << nb_case << " " << nb_comp << finl;
              Cerr << "size_totale = " << n << finl;
              exit();
            }
          diag.dimensionne_diag(n);
          operateur(0).l_op_base().contribuer_a_avec(inconnue().valeurs(), diag);
          for (int i = 0; i < size_s; i++)
            if (marq[i])
              sources()(i).valeur().contribuer_a_avec(inconnue().valeurs(), diag);
// La diagonale est proportionnelle au volume de controle....
// Il faut appliquer le solveur_masse
          DoubleTab tempo(inconnue().valeurs());
          for (int ca = 0; ca < nb_case; ca++)
            for (int ncp = 0; ncp < nb_comp; ncp++)
              tempo(ca, ncp) = diag(ca * nb_comp + ncp, ca * nb_comp + ncp);
          solveur_masse.appliquer(tempo);
          tempo.echange_espace_virtuel();
// On inverse... // Crank - Nicholson
// La matrice correspond a - la jacobienne (pour avoir un plus justement, GF)
          for (int ca = 0; ca < nb_case; ca++)
            {
              double tmp = (size_terme_mul ? terme_mul(ca) : 1) / dt;
              for (int ncpa = 0; ncpa < nb_comp; ncpa++)
                diag(ca * nb_comp + ncpa, ca * nb_comp + ncpa) = 1. / (tmp + tempo(ca, ncpa) * aCKN);
            }
          statistiques().end_count(assemblage_sys_counter_);
        }
// On utilise p pour calculer phiB :
      operateur(0).ajouter(p, phiB);
      if (marq_tot)
        {
          for (int i = 0; i < size_s; i++)
            if (marq[i])
              ref_cast(Source_dep_inco_base, sources()(i).valeur()).ajouter_(p, phiB);
        }
      statistiques().begin_count(diffusion_implicite_counter_);
      solveur_masse.appliquer(phiB);
// phiB *= aCKN;  // Crank - Nicholson
// fait maintenant avant l'appel
// solveur_masse.appliquer(secmem);
      DoubleTab sol;
      if (size_terme_mul)
        {
          sol = solution;
          for (int i = 0; i < size_terme_mul; i++)
            sol(i) *= terme_mul(i);
        }
      else
        sol.ref(solution);
      secmem.ajoute(1. / dt, sol, VECT_REAL_ITEMS);
// Stop the counter because operator diffusion is also counted
      statistiques().end_count(diffusion_implicite_counter_, 0, 0);
      operateur(0).ajouter(solution, resu);
      if (marq_tot)
        {
          for (int i = 0; i < size_s; i++)
            if (marq[i])
              ref_cast(Source_dep_inco_base, sources()(i).valeur()).ajouter_(solution, resu);
        }
      statistiques().begin_count(diffusion_implicite_counter_);
      solveur_masse.appliquer(resu);
      resu.echange_espace_virtuel();
      resu *= -1.;
      resu.ajoute(1. / dt, sol, VECT_REAL_ITEMS);
      DoubleTab residu(resu); //!< residu = Ax
      residu -= secmem;      //!< residu = Ax-B
      DoubleTab z;
      if (precond_diag)
        {
          z = residu;
          diag.multvect(residu, z); //!< z = D-1(Ax-B)
        }
      else
        z.ref(residu); //!< z = Ax-B
      p -= z;
      /* Calcul different de initial_residual:
         DoubleTab tmp(secmem);
         if (precond_diag)
         diag.multvect(secmem, tmp);
         else
         tmp.ref(secmem);
      double initial_residual = mp_carre_norme_vect(z); //!< =||Ax(0)-B|| ou ||D-1.(Ax(0)-B)||
         double initial_residual = mp_carre_norme_vect(tmp) ; //!< =||B|| ou ||D-1.B|| */
      if (le_schema_en_temps->impr_diffusion_implicite()) Cout << "Residu(0)=" << initial_residual << finl;
      double seuil = seuil_diffusion_implicite * seuil_diffusion_implicite;
// On calcule un seuil relatif (PL: 18/07/12, j'ai l'impression qu'il y'a une erreur, c'est seuil*=initial_residual;
// En outre, il serait bon de faire residual = sqrt(mp_carre_norme_vect(tmp)) a plusieurs endroits...
      if (initial_residual > seuil)
        seuil = seuil_diffusion_implicite * initial_residual;
      double residual = seuil; //!< Il est mieux d'utiliser cette valeur pour entrer dans la boucle car seuil peut etre tres grand si le calcul diverge avant
      double prodrz_old = mp_prodscal(residu, z);
      DoubleTrav pp(p);
      int niter = 0;
      if (initial_residual != 0)
        while ((residual >= seuil) && (niter++ <= nmax))
          {
            resu = 0.;
            p.echange_espace_virtuel();
// Stop the counter during diffusive operator:
            statistiques().end_count(diffusion_implicite_counter_, 0, 0);
            operateur(0).ajouter(p, resu);
            if (marq_tot)
              {
                for (int i = 0; i < size_s; i++)
                  if (marq[i])
                    ref_cast(Source_dep_inco_base, sources()(i).valeur()).ajouter_(p, resu);
              }
            statistiques().begin_count(diffusion_implicite_counter_);
            solveur_masse.appliquer(resu);
// resu *= aCKN ;  // Crank - Nicholson
            resu.echange_espace_virtuel();
            resu -= phiB;//!< On retire la contribution des bords.
            resu *= -aCKN;
            if (size_terme_mul)
              {
                for (int i = 0; i < size_terme_mul; i++)
                  pp(i) = p(i) * terme_mul(i);
                resu.ajoute(1. / dt, pp, VECT_REAL_ITEMS);
              }
            else
              resu.ajoute(1. / dt, p, VECT_REAL_ITEMS);
            double alfa = prodrz_old / mp_prodscal(resu, p);
// Inutile de faire un echange espace virtuel:
            solution.ajoute(alfa, p, VECT_REAL_ITEMS);
            residu.ajoute(alfa, resu, VECT_REAL_ITEMS);
            if (precond_diag)
              diag.multvect(residu, z); //!< preconditionnement par diag^(-1) sinon z=residu
//
            residual = mp_carre_norme_vect(z);
            if (le_schema_en_temps->impr_diffusion_implicite())
              Cout << "Iteration n=" << niter << " Residu(n)/Residu(0)=" << residual / initial_residual << finl;
            double prodrz_new = mp_prodscal(residu, z);
            p *= (prodrz_new / prodrz_old);
            p -= z;
            prodrz_old = prodrz_new;
// On previent si convergence anormalement longue sur de tres gros cas
            if (niter == 100)
              {
                Cout
                    << "Already 100 iterations of the conjugate gradient solver used for diffusion implicited algorithm."
                    << finl;
                Cout
                    << "The calculation is diverging, may be because of incorrect initial and/or boundary conditions for the equation "
                    << que_suis_je() << finl;
                Cout
                    << "You may also try to stop the calculation and rerun it with a lower facsec, say 0.9 or may be less: 0.5."
                    << finl;
              }
          }
      if ((le_schema_en_temps->no_error_if_not_converged_diffusion_implicite() == 0) && (niter > nmax))
        {
          Cerr << "No convergence of the implicited diffusion algorithm for the equation " << que_suis_je() << " in "
               << nmax << " iterations." << finl;
          Cerr << "Residue : " << residual << " Threshold : " << seuil << finl;
          Cerr << "The problem " << probleme().le_nom() << " has been saved." << finl;
          probleme().sauver();
          Cerr << "The problem is post processed to help you to see where the non convergence is located." << finl;
          probleme().postraiter(1);
          exit();
        }
      else
        Cout << "Diffusion operator implicited for the equation " << que_suis_je()
             << " : Conjugate gradient converged in " << niter << " iterations." << finl;
      solution -= merk;
      solution.echange_espace_virtuel();
// End the counter
      statistiques().end_count(diffusion_implicite_counter_);
// CHD 230501 : Call to diffusive operator to update flux_bords (boundary fluxes):
      resu = 0.;
      operateur(0).ajouter(inconnue(), resu);
      if (marq_tot)
        {
          for (int i = 0; i < size_s; i++)
            if (marq[i])
              ref_cast(Source_dep_inco_base, sources()(i).valeur()).ajouter_(inconnue()->valeurs(), resu);
        }
// Since 1.6.8 returns dI/dt:
      solution/=dt;
    }
}
References TRUSTVect< _TYPE_ >::ajoute(), Operateur::ajouter(), ajouter(), Schema_Temps_base::ajouter_inertie(), Solveur_Masse::ajouter_masse(), Matrice_Base::ajouter_multvect(), Solveur_Masse::appliquer(), assemblage_sys_counter_, Statistiques::begin_count(), Cerr, Matrice_Morse::clean(), Operateur_base::contribuer_a_avec(), Cout, Parametre_diffusion_implicite::crank(), diffusion_implicite_counter_, TRUSTTab< _TYPE_ >::dimension_tot(), Matrice_Morse_Diag::dimensionne_diag(), dimensionner_matrice(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), Process::exit(), finl, Schema_Temps_base::impr_diffusion_implicite(), inconnue(), Operateur::l_op_base(), Probleme_base::le_nom(), le_schema_en_temps, TRUSTVect< _TYPE_ >::line_size(), modifier_pour_Cl(), mp_carre_norme_vect(), mp_prodscal(), Matrice_Base::multvect(), Parametre_diffusion_implicite::nb_it_max(), Schema_Temps_base::niter_max_diffusion_implicite(), Schema_Temps_base::no_error_if_not_converged_diffusion_implicite(), O_U_Ptr::non_nul(), operateur(), Matrice_Morse::ordre(), parametre_equation(), Schema_Temps_base::pas_de_temps(), Probleme_base::postraiter(), Parametre_diffusion_implicite::precoditionnement_diag(), probleme(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), ref_cast, SolveurSys::resoudre_systeme(), Probleme_base::sauver(), schema_temps(), Schema_Temps_base::seuil_diffusion_implicite(), Parametre_diffusion_implicite::seuil_diffusion_implicite(), liste::size(), TRUSTVect< _TYPE_ >::size_totale(), solv_masse(), solveur_masse, sources(), statistiques(), sub_type, valeur(), Champ_Inc::valeurs(), and VECT_REAL_ITEMS.
has_champ_conserve()
int Equation_base::has_champ_conserve () const inline
Definition at line 201 of file Equation_base.h.
  {
    return champ_conserve_.non_nul();
  }
References champ_conserve_, and O_U_Ptr::non_nul().
has_champ_convecte()
virtual int Equation_base::has_champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
Definition at line 219 of file Equation_base.h.
  {
    return champ_conserve_.non_nul();
  }
References champ_conserve_, and O_U_Ptr::non_nul().
has_interface_blocs()
int Equation_base::has_interface_blocs () const virtual
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
Definition at line 2419 of file Equation_base.cpp.
{
  int ok = 1;
  /* operateurs, masse, sources */
  for (int op = 0; op < nombre_d_operateurs(); op++) ok &= operateur(op).l_op_base().has_interface_blocs();
  ok &= solv_masse().valeur().has_interface_blocs();
  for (int i = 0; i < les_sources.size(); i++) ok &= les_sources(i).valeur().has_interface_blocs();
  return ok;
}
References Operateur_base::has_interface_blocs(), Solveur_Masse_base::has_interface_blocs(), Operateur::l_op_base(), les_sources, nombre_d_operateurs(), operateur(), liste::size(), solv_masse(), List_Source::valeur(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Navier_Stokes_std::has_interface_blocs(), Energie_Multiphase::has_interface_blocs(), Masse_Multiphase::has_interface_blocs(), and Simple::iterer_eqn().
impr()
int Equation_base::impr (Sortie & os) const virtual
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented in Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Navier_Stokes_QC, Navier_Stokes_WC, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, QDM_Multiphase, and Conduction.
Definition at line 803 of file Equation_base.cpp.
{
  for(int i=0; i<nombre_d_operateurs(); i++)
    operateur(i).impr(os);
// if (je_suis_maitre() && les_sources.size()>0) os << finl << "Impression des termes sources pour l'equation " << que_suis_je() << " : " << finl;
  les_sources.impr(os);
  return 1;
}
References Sources::impr(), Operateur::impr(), les_sources, nombre_d_operateurs(), and operateur().
Referenced by Convection_Diffusion_Fluide_Dilatable_base::impr(), Convection_Diffusion_Concentration::impr(), Convection_Diffusion_Temperature::impr(), Navier_Stokes_std::impr(), Aire_interfaciale::impr(), Energie_Multiphase::impr(), QDM_Multiphase::impr(), Conduction::impr(), and imprimer().
imprime_residu()
void Equation_base::imprime_residu (SFichier & fic) virtual
Definition at line 2513 of file Equation_base.cpp.
{
  int size = residu_.size_array();
  for (int i=0; i<size; i++)
    {
      fic << residu_(i) << "\t ";
      int nb_unknowns = inconnue().valeurs().dimension_tot(0);
      double residual_limit = ( nb_unknowns == 0 ? DMAXFLOAT : DMAXFLOAT/nb_unknowns);
      if (residu_(i)>residual_limit)
        {
          fic << finl;
          Cerr << "Equation " << le_nom() << " is diverging:" << finl;
          Cerr << "A residual ||dI/dt|| for this equation is bigger than " << residual_limit << " !" << finl;
          Cerr << "Have a look at the " << nom_du_cas() << ".dt_ev file." << finl;
          Process::exit();
        }
    }
// Affichage min/max
  if (schema_temps().impr_extremums() && limpr())
    {
      double vmax = mp_max_vect(inconnue().valeurs());
      double vmin = mp_min_vect(inconnue().valeurs());
      Cout << finl << inconnue().le_nom() << " field [min/max]: ";
      if (je_suis_maitre()) printf("[ %.2e / %.2e ]",vmin,vmax);
      Cout << finl;
    }
}
References Cerr, Cout, TRUSTTab< _TYPE_ >::dimension_tot(), DMAXFLOAT, Process::exit(), finl, inconnue(), Process::je_suis_maitre(), le_nom(), O_U_Ptr::le_nom(), limpr(), mp_max_vect(), mp_min_vect(), Objet_U::nom_du_cas(), residu_, schema_temps(), TRUSTArray< _TYPE_ >::size_array(), and Champ_Inc::valeurs().
Referenced by Schema_Temps_base::validateTimeStep().
imprimer()
void Equation_base::imprimer (Sortie & os) const virtual
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
Definition at line 828 of file Equation_base.cpp.
{
  ecrire_fichier_xyz();
  if (limpr() )
    impr(os);
}
References ecrire_fichier_xyz(), impr(), and limpr().
Referenced by Probleme_base::imprimer().
inconnue() [1/2]
virtual const Champ_Inc & Equation_base::inconnue () const pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, Conduction, and Convection_Diffusion_std.
Referenced by Mod_turb_hyd_base::a_faire(), abortTimeStep(), Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Operateur_base::ajouter(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Acceleration_QC_VDF_Face::ajouter_blocs(), Source_qdm_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_QC_VDF_Face::ajouter_blocs(), Darcy_QC_VDF_Face::ajouter_blocs(), Forchheimer_QC_VDF_Face::ajouter_blocs(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_base::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Schema_Temps_base::ajouter_inertie(), Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_EF::ajouter_masse(), Masse_VEF_P1NC::ajouter_masse(), Solveur_Masse_base::appliquer(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), assembler_blocs(), assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Milieu_base::associer_equation(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Source_Darcy_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Source_Forchheimer_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Source_Darcy_VEF_Face::associer_pb(), Source_Forchheimer_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), avancer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Perte_Charge_Singuliere::calculate_Q(), Source_PDF_base::calculer(), Masse_Multiphase::calculer_alpha_rho(), calculer_champ_conserve(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_VDF_base::calculer_dt_local(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Fluide_reel_base::calculer_masse_volumique(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_VDF::calculer_Teta_paroi(), Source_Neutronique_VDF::calculer_Tmoyenne(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Schema_Adams_Moulton_base::changer_temps(), Schema_Backward_Differentiation_base::changer_temps(), Fluide_reel_base::check_unknown_range(), paroi_contact::complement(), completer(), Operateur::completer(), Operateur_base::completer(), Source_base::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Masse_PolyMAC_P0_Face::completer(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::completer(), Flux_interfacial_PolyMAC::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Decroissance_Radioactive_VEF_Face::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Fluide_Dilatable_base::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Op_Dift_VEF_Face::contribue_au_second_membre(), Operateur_base::contribuer_a_avec(), Source_base::contribuer_a_avec(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Diff_EF::contribuer_au_second_membre(), Op_Dift_EF_Q1::contribuer_au_second_membre(), Operateur_base::contribuer_termes_croises(), Masse_PolyMAC_Face::corriger_solution(), Champ_front_contact_VEF::creer(), creer_champ(), Postraitement::creer_champ_post_moreqn(), Fluide_base::creer_e_int(), derivee_en_temps_inco(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Operateur_base::dimensionner(), Source_base::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Operateur_base::dimensionner_termes_croises(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), expression_residu(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), get_champ(), Champ_Post_Operateur_Eqn::get_champ_without_evaluation(), get_fonc_champ_conserve(), PolyMAC_discretisation::get_name_of_type_for(), Discretisation_base::get_name_of_type_for(), Champ_Post_Operateur_Eqn::get_property(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Gradient_conjugue_diff_impl(), Implicite_Multi_TimeStep_recommencer_pb(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), imprime_residu(), Equation::inconnue(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), init_champ_conserve(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Echange_couplage_thermique::initialiser(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), initTimeStep(), Schema_Temps_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), SETS::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Postraitement::lire_champs_a_postraiter(), lire_cond_init(), mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), Schema_Backward_Differentiation_base::mettre_a_jour_equation(), Milieu_composite::mettre_a_jour_tabs(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_VEF_Face::modifier_flux(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Schema_Adams_Bashforth_base::modifier_second_membre(), Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Op_Diff_VEF_base::phi_psi_diffuse(), Op_Conv_EF_base::phi_u_transportant(), Op_Conv_VEF_base::phi_u_transportant(), preparer_calcul(), Pb_Dilatable_base::preparer_calcul(), printOn(), Source_Scalaire_EF::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), reculer(), Zone_Cl_EF::remplir_type_elem_Cl(), reprendre(), sauvegarder(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), test_imposer_cond_lim(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Op_Diff_PolyMAC_base::update_aux(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_phif(), Champ_Post_Operateur_Eqn::verification_cas_compo(), Dirichlet::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), and Echange_externe_impose::verifie_ch_init_nb_comp().
inconnue() [2/2]
virtual Champ_Inc & Equation_base::inconnue () pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, Conduction, and Convection_Diffusion_std.
info()
const Type_info * Equation_base::info () static
Definition at line 48 of file Equation_base.cpp.
init_champ_conserve()
void Equation_base::init_champ_conserve () const
Definition at line 2479 of file Equation_base.cpp.
{
  if (champ_conserve_.non_nul()) return; //deja fait
  int Nt = inconnue()->nb_valeurs_temporelles(), Nl = inconnue().valeurs().size_reelle_ok() ? inconnue().valeurs().dimension(0) : -1, Nc = inconnue().valeurs().line_size();
// champ_conserve_ : meme type / support que l'inconnue
  discretisation().creer_champ(champ_conserve_, zone_dis().valeur(), inconnue().valeur().que_suis_je(), "N/A", "N/A", Nc, Nl, Nt, schema_temps().temps_courant());
  champ_conserve_->associer_eqn(*this);
  auto nom_fonc = get_fonc_champ_conserve();
  champ_conserve_->nommer(nom_fonc.first);
  champ_conserve_->init_champ_calcule(*this, nom_fonc.second);
}
References Champ_Inc::associer_eqn(), champ_conserve_, Discretisation_base::creer_champ(), TRUSTTab< _TYPE_ >::dimension(), discretisation(), get_fonc_champ_conserve(), inconnue(), TRUSTVect< _TYPE_ >::line_size(), Champ_Inc::nb_valeurs_temporelles(), Objet_U::nommer(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), schema_temps(), TRUSTVect< _TYPE_ >::size_reelle_ok(), valeur(), Champ_Inc::valeurs(), and zone_dis().
Referenced by Masse_PolyMAC_Elem::dimensionner_blocs(), init_champ_convecte(), and Masse_PolyMAC_Elem::preparer_calcul().
init_champ_convecte()
virtual void Equation_base::init_champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
Definition at line 223 of file Equation_base.h.
  {
    init_champ_conserve();
  };
References init_champ_conserve().
Referenced by Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul().
initialise_residu()
void Equation_base::initialise_residu (int size = 0)
Definition at line 2584 of file Equation_base.cpp.
{
  if (size==0)
    size = inconnue().valeurs().line_size();
  residu_.resize(size);
  residu_initial_.resize(size);
  residu_=0;
  residu_initial_=0;
}
References inconnue(), TRUSTVect< _TYPE_ >::line_size(), residu_, residu_initial_, TRUSTVect< _TYPE_ >::resize(), and Champ_Inc::valeurs().
Referenced by completer(), Navier_Stokes_std::completer(), and preparer_calcul().
initTimeStep()
bool Equation_base::initTimeStep (double dt) virtual
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
Returns
0 en cas d'erreur, 1 sinon
Signification:
Contraintes:
Reimplemented in Navier_Stokes_Fluide_Dilatable_base, Navier_Stokes_std, and QDM_Multiphase.
Definition at line 1338 of file Equation_base.cpp.
{
  Schema_Temps_base& sch=schema_temps();
  double temps_present=sch.temps_courant();
// Le pas de temps doit etre celui du schema !!
  assert(sch.pas_de_temps()==dt);
// Pour chaque temps futur
  for (int i=1; i<=sch.nb_valeurs_futures(); i++)
    {
      double tps=sch.temps_futur(i);
// Mise a jour du temps dans l'inconnue
      inconnue()->changer_temps_futur(tps,i);
      if (champ_conserve_.non_nul()) champ_conserve_->changer_temps_futur(tps,i);
      if (champ_convecte_.non_nul()) champ_convecte_->changer_temps_futur(tps,i);
      if (calculate_time_derivative()) derivee_en_temps()->changer_temps_futur(tps,i);
      inconnue()->futur(i)=inconnue()->valeurs();
      if (champ_conserve_.non_nul()) champ_conserve_->futur(i) = champ_conserve().valeurs();
      if (champ_convecte_.non_nul()) champ_convecte_->futur(i) = champ_convecte().valeurs();
      if (calculate_time_derivative()) derivee_en_temps()->futur(i)=derivee_en_temps()->valeurs();
// Mise a jour du temps dans les CL
      zone_Cl_dis()->changer_temps_futur(tps,i);
    }
// Mise a jour du temps par defaut des CLs
  zone_Cl_dis()->set_temps_defaut(sch.temps_defaut());
// Mise a jour des operateurs
  for(int i=0; i<nombre_d_operateurs(); i++)
    operateur(i).mettre_a_jour(temps_present);
// Mise a jour du solveur masse au temps present
  if (solveur_masse.non_nul())
    solveur_masse.mettre_a_jour(temps_present);
  return true;
}
References calculate_time_derivative(), champ_conserve(), champ_conserve_, champ_convecte(), champ_convecte_, derivee_en_temps(), Champ_Inc::futur(), inconnue(), Operateur::mettre_a_jour(), Solveur_Masse::mettre_a_jour(), Schema_Temps_base::nb_valeurs_futures(), nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), schema_temps(), solveur_masse, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), Schema_Temps_base::temps_futur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), and zone_Cl_dis().
Referenced by Probleme_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), and QDM_Multiphase::initTimeStep().
le_nom()
const Nom & Equation_base::le_nom () const inline override virtual
Renvoie le nom de l'equation.
Returns
Nom&
Signification: le nom de l'equation
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 387 of file Equation_base.h.
{
  return nom_;
}
References nom_.
Referenced by Op_Conv_ALE::ajouter(), Champ_Generique_Gradient::completer(), Postraitement::creer_champ_post_moreqn(), ecrire_fichier_xyz(), Champ_P1NC_implementation::filtrer_L2(), get_champ(), imprime_residu(), lire_cond_init(), Champ_Generique_Morceau_Equation::nommer_source(), ouvrir_fichier_pena_th(), List_Equations_Scalaires_Passifs_Especes::readOn(), reprendre(), and verifie_ch_init_nb_comp().
limpr()
int Equation_base::limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
Returns
int
Signification: 1 si il faut effectuer une impression, 0 sinon.
Contraintes:
Definition at line 782 of file Equation_base.cpp.
{
  return le_schema_en_temps->limpr();
}
References le_schema_en_temps, and Schema_Temps_base::limpr().
Referenced by Navier_Stokes_std::corriger_derivee_impl(), imprime_residu(), imprimer(), and Operateur::limpr().
lire()
virtual void Equation_base::lire () inline protected virtual
Definition at line 318 of file Equation_base.h.
  {
    exit();
  };
References Process::exit().
lire_cl()
Entree & Equation_base::lire_cl (Entree & is) protected virtual
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 703 of file Equation_base.cpp.
{
  Cerr << "Reading of boundaries conditions\n";
  if(!la_zone_Cl_dis.non_nul())
    {
      Cerr << "Error while reading boundaries conditions : " <<
           que_suis_je() << finl;
      Cerr << "The Zone_Cl_dis is empty ..." << finl;
      exit();
    }
  is >> la_zone_Cl_dis.valeur();
  return is;
}
References Cerr, Process::exit(), finl, la_zone_Cl_dis, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by lire_motcle_non_standard().
lire_cond_init()
Entree & Equation_base::lire_cond_init (Entree & is) protected virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented in Navier_Stokes_std, and QDM_Multiphase.
Definition at line 648 of file Equation_base.cpp.
{
  Cerr << "Reading of initial conditions\n";
  Nom nom;
  Motcle motlu;
  is >> nom;
  motlu = nom;
  if(motlu!=Motcle("{"))
    {
      Cerr << "We expected a { while reading " << que_suis_je() << finl;
      Cerr << "and not : " << nom << finl;
      exit();
    }
  is >> nom;
  motlu = nom;
  if (motlu != Motcle(inconnue()->le_nom()))
    {
      Cerr << nom << " is not the name of the unknown "
           << inconnue()->le_nom() << finl;
      exit();
    }
  Champ_Don ch_init;
  is >> ch_init;
  const int nb_comp = ch_init.nb_comp();
  verifie_ch_init_nb_comp(inconnue(),nb_comp);
// Cerr<<"inconnue().valeur().que_suis_je() = "<<inconnue().valeur().que_suis_je()<<finl;
  inconnue()->affecter(ch_init.valeur());
  is >> nom;
  motlu = nom;
  if(motlu!=Motcle("}"))
    {
      Cerr << "We expected a } while reading " << que_suis_je() << finl;
      Cerr << "and not : " << nom << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, inconnue(), le_nom(), O_U_Ptr::le_nom(), Champ_Don::nb_comp(), Objet_U::que_suis_je(), Deriv_Champ_Don_base::valeur(), and verifie_ch_init_nb_comp().
Referenced by lire_motcle_non_standard().
lire_motcle_non_standard()
int Equation_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, and Conduction.
Definition at line 314 of file Equation_base.cpp.
{
  if (mot=="sources")
    {
      lire_sources(is);
      return 1;
    }
  else if (mot=="conditions_limites|boundary_conditions")
    {
      lire_cl(is);
      verif_Cl();
      return 1;
    }
  else if (mot=="conditions_initiales|initial_conditions")
    {
      lire_cond_init(is);
      return 1;
    }
  else if ((mot=="ecrire_fichier_xyz_valeur") || (mot=="ecrire_fichier_xyz_valeur_bin"))
    {
      if (mot=="ecrire_fichier_xyz_valeur_bin")
        ecrit_champ_xyz_bin=1;
      dt_ecrire_fic_xyz.resize_array(nombre_champ_xyz+1);
      nb_bords_post_xyz.resize(nombre_champ_xyz+1);
      nb_bords_post_xyz[nombre_champ_xyz]=0;
      Motcle nom_champ;
      is >> nom_champ;
// il faut creer les champs associes au mot clef ecrire_fichier_xyz_valeur ICI
// car dans methode ecrire_fichier_xyz()
// seuls les champs definis via equation ou post-traiment sont creer
      mon_probleme.valeur().creer_champ(nom_champ);
      nom_champ_xyz.add(nom_champ);
      is >> dt_ecrire_fic_xyz[nombre_champ_xyz];
      nombre_champ_xyz++;
      return 1;
    }
  else if (mot=="bords")
    {
      int nb_bords_post;
      is >> nb_bords_post;
      nb_bords_post_xyz[nombre_champ_xyz-1] = nb_bords_post;
      if (nb_bords_post<=0)
        {
          Cerr << " ecrire_fichier_xyz_valeur - bords : the number of boundary on which you want to postprocess must be positive !! " << finl;
          exit();
        }
      Noms noms_bord;
      noms_bord.dimensionner(nb_bords_post);
      for (int i=0; i<nb_bords_post; i++)
        {
          is >> noms_bord[i];
        }
      noms_bord_xyz.add(noms_bord);
      return 1;
    }
  else if (mot=="equation_non_resolue")
    {
// differentiate an entry with an expression from an entry with the keyword eq_non_resoue_input_
// On complete:
      Motcle expr_equation_non_resolue;
      is >> expr_equation_non_resolue;
      equation_non_resolue_.setString(expr_equation_non_resolue);
      if (expr_equation_non_resolue=="INPUT_INT_VALUE")
        is >> eq_non_resolue_input_;
      else
        equation_non_resolue_.parseString();
    }
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References List_Noms::add(), Vect_Motcle::add(), Cerr, Probleme_base::creer_champ(), vect_impl::dimensionner(), dt_ecrire_fic_xyz, ecrit_champ_xyz_bin, eq_non_resolue_input_, equation_non_resolue_, Process::exit(), finl, lire_cl(), lire_cond_init(), lire_sources(), mon_probleme, nb_bords_post_xyz, nom_champ_xyz, nombre_champ_xyz, noms_bord_xyz, Parser_U::parseString(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Parser_U::setString(), Ref_Probleme_base::valeur(), and verif_Cl().
Referenced by Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), and Conduction::lire_motcle_non_standard().
lire_sources()
Entree & Equation_base::lire_sources (Entree & is) protected virtual
Lecture des termes sources dans un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 579 of file Equation_base.cpp.
{
  Cerr << "Reading of source terms" << finl ;
  is >> les_sources;
  return is;
}
References Cerr, finl, and les_sources.
Referenced by lire_motcle_non_standard(), Energie_Multiphase::readOn(), and Masse_Multiphase::readOn().
mettre_a_jour()
void Equation_base::mettre_a_jour (double temps) virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
Reimplemented in Navier_Stokes_std, Aire_interfaciale, QDM_Multiphase, Conduction, and Convection_Diffusion_Concentration.
Definition at line 1214 of file Equation_base.cpp.
{
// On tourne la roue de l'inconnue
// Update the unknown:
  inconnue().mettre_a_jour(temps);
  if (calculate_time_derivative()) derivee_en_temps().mettre_a_jour(temps);
  les_sources.mettre_a_jour(temps);
// On tourne la roue des CLs
// Update the boundary condition:
  if (temps > schema_temps().temps_courant()) zone_Cl_dis()->avancer(temps);
}
References calculate_time_derivative(), derivee_en_temps(), inconnue(), les_sources, Champ_Inc::mettre_a_jour(), Sources::mettre_a_jour(), schema_temps(), and zone_Cl_dis().
Referenced by Simple::iterer_eqs(), Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Conduction::mettre_a_jour(), and Convection_Diffusion_Concentration::mettre_a_jour().
mettre_a_jour_champs_conserves()
void Equation_base::mettre_a_jour_champs_conserves (double temps, int reset = 0) virtual
Definition at line 1229 of file Equation_base.cpp.
{
  if (reset && champ_conserve_.non_nul()) champ_conserve_->reset_champ_calcule(); //force le calcul de toutes les cases
  if (reset && champ_convecte_.non_nul()) champ_convecte_->reset_champ_calcule();
  if (champ_conserve_.non_nul()) champ_conserve_->mettre_a_jour(temps);
  if (champ_convecte_.non_nul()) champ_convecte_->mettre_a_jour(temps);
}
References champ_conserve_, champ_convecte_, Champ_Inc::mettre_a_jour(), and O_U_Ptr::non_nul().
Referenced by Probleme_base::mettre_a_jour(), and Probleme_base::preparer_calcul().
milieu() [1/2]
virtual const Milieu_base & Equation_base::milieu () const pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, and Conduction.
Referenced by T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), associer_milieu_equation(), Perte_Charge_PolyMAC_Face::associer_pb(), Source_QC_QDM_Gen::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_global_impose::champ_exterieur(), Frontiere_ouverte_rho_u_impose::compatible_avec_eqn(), Op_Diff_PolyMAC_P0_base::completer(), Echange_externe_impose_H::completer(), Entree_fluide_temperature_imposee_H::completer(), Frontiere_ouverte_rho_u_impose::completer(), Neumann_sortie_libre_Temp_H::completer(), Temperature_imposee_paroi_H::completer(), Source_Chaleur_Fluide_Dilatable_base::completer(), Source_Gravite_Fluide_Dilatable_base::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_contact_Correlation_VEF::completer(), Champ_Generique_modifier_pour_QC::completer(), Convection_Diffusion_std::diffusivite_pour_transport(), Probleme_base::discretiser(), diviser_par_rho_np1_face(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), get_champ(), Probleme_base::get_champ(), Echange_couplage_thermique::get_dRho_dCp(), get_noms_champs_postraitables(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Probleme_base::has_champ(), Champ_front_pression_from_u::initialiser(), Champ_front_debit_massique::initialiser_coefficient(), Pb_Dilatable_base::iterateTimeStep(), Simple::iterer_eqn(), Piso::iterer_NS(), Simple::iterer_NS(), Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_calc::milieu(), Equation::milieu(), Probleme_base::milieu(), Champ_front_contact_VEF::milieu(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu(), Champ_front_debit_QC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), and Op_Diff_PolyMAC_P0_base::update_nu().
milieu() [2/2]
virtual Milieu_base & Equation_base::milieu () pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, and Conduction.
modifier_pour_Cl()
void Equation_base::modifier_pour_Cl (Matrice_Morse & mat_morse, DoubleTab & secmem) const virtual
Definition at line 2401 of file Equation_base.cpp.
{
  for (int op=0; op<nombre_d_operateurs(); op++)
    {
      operateur(op).l_op_base().modifier_pour_Cl(mat_morse,secmem);
    }
}
References Operateur::l_op_base(), Operateur_base::modifier_pour_Cl(), nombre_d_operateurs(), and operateur().
Referenced by assembler_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), and Gradient_conjugue_diff_impl().
nombre_d_operateurs()
virtual int Equation_base::nombre_d_operateurs () const pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
Referenced by abortTimeStep(), ajouter_termes_croises(), assembler(), assembler_blocs(), associer_pb_base(), calculer_pas_de_temps(), calculer_pas_de_temps_locaux(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), completer(), contribuer_termes_croises(), creer_champ(), Postraitement::creer_champ_post_moreqn(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), dimensionner_termes_croises(), get_champ(), get_noms_champs_postraitables(), has_interface_blocs(), impr(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), initTimeStep(), Postraitement::lire_champs_a_postraiter(), modifier_pour_Cl(), Champ_Generique_Morceau_Equation::morceau(), Equation::nombre_d_operateurs(), nombre_d_operateurs_tot(), preparer_calcul(), printOn(), and updateGivenFields().
nombre_d_operateurs_tot()
int Equation_base::nombre_d_operateurs_tot () const virtual
Reimplemented in Navier_Stokes_std.
Definition at line 2611 of file Equation_base.cpp.
{
  return nombre_d_operateurs();
}
References nombre_d_operateurs().
Referenced by Postraitement::lire_champs_a_postraiter().
nommer()
void Equation_base::nommer (const Nom & nom) override virtual
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
Reimplemented from Objet_U.
Definition at line 1014 of file Equation_base.cpp.
{
  nom_ = un_nom;
}
References nom_.
Referenced by List_Equations_Scalaires_Passifs_Especes::readOn().
operateur() [1/2]
virtual const Operateur & Equation_base::operateur (int) const pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
Referenced by abortTimeStep(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), ajouter_termes_croises(), assembler(), assembler_blocs(), associer_pb_base(), Champ_P1NC::calcul_h_conv(), calculer_pas_de_temps(), calculer_pas_de_temps_locaux(), completer(), Terme_Source_Canal_perio::compute_heat_flux(), contribuer_termes_croises(), creer_champ(), Postraitement::creer_champ_post_moreqn(), derivee_en_temps_conv(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), dimensionner_termes_croises(), Champ_Post_Operateur_Eqn::get_champ(), get_champ(), get_noms_champs_postraitables(), Gradient_conjugue_diff_impl(), has_interface_blocs(), impr(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Op_Diff_VDF_base::init_op_ext(), initTimeStep(), SETS::iterer_eqn(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_nu(), modifier_pour_Cl(), Champ_Generique_Morceau_Equation::morceau(), Champ_Post_Operateur_Eqn::Operateur(), Equation::operateur(), preparer_calcul(), printOn(), and updateGivenFields().
operateur() [2/2]
virtual Operateur & Equation_base::operateur (int) pure virtual
Implemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
operateur_fonctionnel() [1/2]
Operateur & Equation_base::operateur_fonctionnel (int i) virtual
Reimplemented in Navier_Stokes_std.
Definition at line 2603 of file Equation_base.cpp.
{
  Cerr<<"The method operateur_fonctionnel is not coded for equation "<<que_suis_je()<<finl;
  exit();
  throw;
  return Equation_base::operateur_fonctionnel(i);
}
References Cerr, Process::exit(), finl, operateur_fonctionnel(), and Objet_U::que_suis_je().
operateur_fonctionnel() [2/2]
const Operateur & Equation_base::operateur_fonctionnel (int i) const virtual
Reimplemented in Navier_Stokes_std.
Definition at line 2595 of file Equation_base.cpp.
{
  Cerr<<"The method operateur_fonctionnel is not coded for equation "<<que_suis_je()<<finl;
  exit();
  throw;
  return Equation_base::operateur_fonctionnel(i);
}
References Cerr, Process::exit(), finl, operateur_fonctionnel(), and Objet_U::que_suis_je().
Referenced by Postraitement::creer_champ_post_moreqn(), Champ_Generique_Morceau_Equation::morceau(), and operateur_fonctionnel().
parametre_equation() [1/2]
Parametre_equation & Equation_base::parametre_equation () inline
Definition at line 254 of file Equation_base.h.
  {
    return parametre_equation_ ;
  };
References parametre_equation_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), Solveur_Implicite_Base::get_and_set_parametre_equation(), and Gradient_conjugue_diff_impl().
parametre_equation() [2/2]
const Parametre_equation & Equation_base::parametre_equation () const inline
Definition at line 258 of file Equation_base.h.
  {
    return parametre_equation_ ;
  };
References parametre_equation_.
positive_unkown()
virtual int Equation_base::positive_unkown () inline virtual
Reimplemented in Aire_interfaciale.
Definition at line 297 of file Equation_base.h.
{return 0;};
preparer_calcul()
int Equation_base::preparer_calcul () virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Concentration, Navier_Stokes_std, and QDM_Multiphase.
Definition at line 1285 of file Equation_base.cpp.
{
  solveur_masse.valeur().preparer_calcul();
  int nb_op=nombre_d_operateurs();
  for(int i=0; i<nb_op; i++)
    {
      operateur(i).l_op_base().preparer_calcul();
      dt_op_bak.add(0.);
    }
  initialise_residu();
  double temps=schema_temps().temps_courant();
  inconnue()->verifie_valeurs_cl();
  inconnue().changer_temps(temps);
  if (calculate_time_derivative()) derivee_en_temps().changer_temps(temps);
  la_zone_Cl_dis->initialiser(temps);
  Nom msg=que_suis_je();
  msg+=" dans Equation_base::preparer_calcul 1";
  Debog::verifier(msg ,inconnue());
  les_sources.initialiser(temps);
  zone_Cl_dis().imposer_cond_lim(inconnue(),temps);
  inconnue().valeurs().echange_espace_virtuel();
  /* initialisation de parametre_equation() par le schema en temps si celui-ci le permet */
  if (sub_type(Schema_Implicite_base, schema_temps()))
    ref_cast(Schema_Implicite_base, schema_temps()).solveur()->get_and_set_parametre_equation(*this);
  msg=que_suis_je();
  msg+=" dans Equation_base::preparer_calcul ";
  Debog::verifier(msg ,inconnue());
  return 1;
}
References TRUSTList< _TYPE_ >::add(), calculate_time_derivative(), Champ_Inc::changer_temps(), derivee_en_temps(), dt_op_bak, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_Cl_dis::imposer_cond_lim(), inconnue(), initialise_residu(), Sources::initialiser(), Operateur::l_op_base(), la_zone_Cl_dis, les_sources, nombre_d_operateurs(), operateur(), Operateur_base::preparer_calcul(), Solveur_Masse_base::preparer_calcul(), Objet_U::que_suis_je(), ref_cast, schema_temps(), solveur_masse, sub_type, Schema_Temps_base::temps_courant(), Deriv_Solveur_Masse_base::valeur(), Champ_Inc::valeurs(), Debog::verifier(), and zone_Cl_dis().
Referenced by Probleme_base::preparer_calcul(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Concentration::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), and QDM_Multiphase::preparer_calcul().
printOn()
Sortie & Equation_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, and Conduction.
Definition at line 251 of file Equation_base.cpp.
{
  os << nom_ << finl;
  os << solveur_masse;
  os << les_sources;
  os << la_zone_Cl_dis;
  os << inconnue() ;
  for(int i=0; i<nombre_d_operateurs(); i++)
    {
      os << operateur(i).l_op_base();
    }
  return os;
}
References finl, inconnue(), Operateur::l_op_base(), la_zone_Cl_dis, les_sources, nom_, nombre_d_operateurs(), operateur(), and solveur_masse.
Referenced by Convection_Diffusion_std::printOn(), Navier_Stokes_std::printOn(), Transport_Interfaces_base::printOn(), Masse_Multiphase::printOn(), and QDM_Multiphase::printOn().
probleme() [1/2]
Probleme_base & Equation_base::probleme ()
Renvoie le probleme associe a l'equation.
Returns
Probleme_base&
Signification: le probleme associe a l'equation
Contraintes:
Definition at line 986 of file Equation_base.cpp.
{
  return mon_probleme.valeur();
}
References mon_probleme, and Ref_Probleme_base::valeur().
Referenced by Mod_turb_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), assembler(), Convection_Diffusion_Temperature::assembler(), Assembleur_P_PolyMAC::assembler_continuite(), Op_Grad_EF::associer(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), Milieu_base::associer_equation(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Conv_EF::calculer_dt_stab(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Echange_global_impose::champ_exterieur(), Terme_Boussinesq_base::check(), paroi_contact::complement(), paroi_contact_fictif::complement(), Source_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_Turbulent_PolyMAC_P0_Elem::completer(), Op_Diff_Turbulent_PolyMAC_P0_Face::completer(), Perte_Charge_PolyMAC::completer(), Echange_interne_impose::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Source_PDF_EF::compute_pond(), Convection_Diffusion_Concentration::constituant(), Operateur_base::contribuer_termes_croises(), Navier_Stokes_std::corriger_derivee_impl(), Turbulence_paroi_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), dimensionner_matrice(), Operateur_base::dimensionner_termes_croises(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), Mod_turb_hyd_base::discretiser_visc_turb(), QDM_Multiphase::discretiser_vitesse(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), ecrire_fichier_xyz(), expression_residu(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Energie_Multiphase::fluide(), Masse_Multiphase::fluide(), Source_PDF_base::fonct_coeff(), Simpler_Base::get_and_set_parametre_equation(), Convection_Diffusion_Espece_Multi_base::get_champ(), Echange_couplage_thermique::get_dRho_dCp(), Discretisation_base::get_name_of_type_for(), Gradient_conjugue_diff_impl(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Navier_Stokes_std::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Champ_Front_Fonction::initialiser(), Champ_front_contact_VEF::initialiser(), Cond_lim_utilisateur_base::is_pb_rayo(), SETS::iterer_eqn(), Simple::iterer_eqn(), iterer_eqn_expl_diffusion_implicite(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Traitement_particulier_NS_EC::lire(), Mod_turb_hyd_base::lire_distance_paroi(), Terme_Puissance_Thermique::lire_donnees(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Mod_turb_hyd_base::lire_motcle_non_standard(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Navier_Stokes_std::milieu(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_nu(), Operateur_base::modifier_pour_Cl(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Operateur_base::ouvrir_fichier_partage(), ouvrir_fichier_pena_th(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Mod_turb_hyd_base::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Navier_Stokes_std::projeter(), Source_Scalaire_EF::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Zone_Cl_dis_base::readOn(), Modele_turbulence_scal_base::readOn(), Turbulence_paroi_scal::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), QDM_Multiphase::readOn(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Zone_Cl_EF::remplir_type_elem_Cl(), reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Navier_Stokes_std::reprendre(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_nul::sauvegarder(), Operateur_base::set_fichier(), Source_base::set_fichier(), Conduction::solide(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Terme_Source_Canal_perio::source(), Champ_front_contact_VEF::test_faces_coin(), test_imposer_cond_lim(), Perte_Charge_Singuliere::update_K(), Energie_Multiphase::verifie_ch_init_nb_comp_cl(), Convection_Diffusion_std::vitesse_pour_transport(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport(), Convection_Diffusion_Espece_Binaire_base::vitesse_pour_transport(), Convection_Diffusion_Chaleur_QC::vitesse_pour_transport(), Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport(), and Terme_Source_Canal_perio::write_flow_rate().
probleme() [2/2]
const Probleme_base & Equation_base::probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Returns
Probleme_base&
Signification: le probleme associe a l'equation
Contraintes: reference constante
Definition at line 1006 of file Equation_base.cpp.
{
  return mon_probleme.valeur();
}
References mon_probleme, and Ref_Probleme_base::valeur().
readOn()
Entree & Equation_base::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< XD attr disable_equation_residual chaine disable_equation_residual 1 The equation residual will not be used for the problem residual used when checking time convergence or computing dynamic time-step
Reimplemented from Objet_U.
Reimplemented in List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, and Conduction.
Definition at line 287 of file Equation_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" equation"<<finl;
  Param param(que_suis_je());
  set_param(param);
  Nom expr_equation_non_resolue="0";
  param.ajouter("disable_equation_residual",&disable_equation_residual_); //!< XD attr disable_equation_residual chaine disable_equation_residual 1 The equation residual will not be used for the problem residual used when checking time convergence or computing dynamic time-step
  equation_non_resolue_.setString(expr_equation_non_resolue);
  param.lire_avec_accolades_depuis(is);
  matrice_init = 0;
  return is;
}
References Param::ajouter(), Cerr, disable_equation_residual_, equation_non_resolue_, finl, Param::lire_avec_accolades_depuis(), matrice_init, Objet_U::que_suis_je(), set_param(), and Parser_U::setString().
Referenced by Convection_Diffusion_std::readOn(), Navier_Stokes_std::readOn(), Transport_Interfaces_base::readOn(), Masse_Multiphase::readOn(), and Conduction::readOn().
reculer()
void Equation_base::reculer (int i = 1) virtual
Definition at line 2227 of file Equation_base.cpp.
{
  inconnue().reculer(i);
  if (champ_conserve_.non_nul()) champ_conserve_->reculer(i);
  if (champ_convecte_.non_nul()) champ_convecte_->reculer(i);
}
References champ_conserve_, champ_convecte_, inconnue(), O_U_Ptr::non_nul(), and Champ_Inc::reculer().
reprendre()
int Equation_base::reprendre (Entree & fich) override virtual
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Navier_Stokes_std.
Definition at line 754 of file Equation_base.cpp.
{
  double temps = schema_temps().temps_courant();
  Nom field_tag(inconnue().le_nom());
  field_tag += inconnue().valeur().que_suis_je();
  field_tag += probleme().domaine().le_nom();
  field_tag += Nom(temps,probleme().reprise_format_temps());
  avancer_fichier(fich, field_tag);
  inconnue().reprendre(fich);
  return 1;
}
References avancer_fichier(), Probleme_base::domaine(), inconnue(), le_nom(), Domaine::le_nom(), probleme(), Objet_U::que_suis_je(), Champ_Inc::reprendre(), schema_temps(), Schema_Temps_base::temps_courant(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation::reprendre(), Probleme_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Espece_Fluide_Dilatable_base::reprendre(), Navier_Stokes_std::reprendre(), and Convection_Diffusion_std::reprendre_base().
residu_initial()
DoubleVect & Equation_base::residu_initial () inline
Definition at line 157 of file Equation_base.h.
  {
    return residu_initial_;
  };
References residu_initial_.
Referenced by Schema_Temps_base::update_critere_statio().
sauvegarder()
int Equation_base::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Returns
int
Signification: le code de retour de Champ_Inc::sauvegarder()
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Navier_Stokes_std.
Definition at line 731 of file Equation_base.cpp.
{
  return inconnue().sauvegarder(os);
}
References inconnue(), and Champ_Inc::sauvegarder().
Referenced by Equation::sauvegarder(), Probleme_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Convection_Diffusion_Espece_Fluide_Dilatable_base::sauvegarder(), Navier_Stokes_std::sauvegarder(), and Convection_Diffusion_std::sauvegarder_base().
schema_temps() [1/2]
Schema_Temps_base & Equation_base::schema_temps ()
Renvoie le schema en temps associe a l'equation.
Returns
Schema_Temps_base&
Signification: le schema en temps associe a l'equation
Contraintes:
Definition at line 1142 of file Equation_base.cpp.
{
  if(!le_schema_en_temps.non_nul())
    {
      Cerr << "Error : " << que_suis_je()
           << "has not been associated to a time scheme " << finl;
      exit();
    }
  return le_schema_en_temps.valeur();
}
References Cerr, Process::exit(), finl, le_schema_en_temps, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Schema_Temps_base::valeur().
Referenced by Operateur::ajouter(), Op_Dift_VDF_Face_Axi_base::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution(), assembler_avec_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Op_Conv_EF::coefficient_btd(), completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_contact_Correlation_VEF::completer(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Perte_Charge_VEF::contribuer_a_avec(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_std::corriger_derivee_impl(), creer_champ(), Navier_Stokes_std::creer_champ(), derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_spat(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_temp(), get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Turbulence_paroi_base::get_champ(), Gradient_conjugue_diff_impl(), Navier_Stokes_std::impr(), imprime_residu(), Mod_turb_hyd_base::imprimer(), Modele_turbulence_scal_base::imprimer(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Echange_contact_VDF::initialiser(), initTimeStep(), QDM_Multiphase::initTimeStep(), Schema_Temps_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Source_Neutronique::limpr(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Modele_turbulence_scal_base::limpr_nusselt(), Mod_turb_hyd_base::limpr_ustar(), Terme_Source_Acceleration::lire_data(), mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), Champ_P1NC::norme_L2_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2_H1(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), Traitement_particulier_Solide_canal_VDF::post_traitement_particulier(), Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), preparer_calcul(), Convection_Diffusion_Concentration::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), List_Equations_Scalaires_Passifs_Especes::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Navier_Stokes_std::reprendre(), Modele_turbulence_hyd_nul::sauvegarder(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Terme_Source_Canal_perio::source(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), updateGivenFields(), and Terme_Source_Canal_perio::write_flow_rate().
schema_temps() [2/2]
const Schema_Temps_base & Equation_base::schema_temps () const
Renvoie le schema en temps associe a l'equation.
Returns
Schema_Temps_base&
Signification: le schema en temps associe a l'equation
Contraintes: reference constante
Definition at line 1167 of file Equation_base.cpp.
{
  if(!le_schema_en_temps.non_nul())
    {
      Cerr << "Error : " << que_suis_je()
           << "has not been associated to a time scheme " << finl;
      exit();
    }
  return le_schema_en_temps.valeur();
}
References Cerr, Process::exit(), finl, le_schema_en_temps, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Schema_Temps_base::valeur().
self_cast() [1/2]
const Equation_base & Equation_base::self_cast (const Objet_U & r) static
Definition at line 48 of file Equation_base.cpp.
self_cast() [2/2]
Equation_base & Equation_base::self_cast (Objet_U & r) static
Definition at line 48 of file Equation_base.cpp.
set_calculate_time_derivative()
void Equation_base::set_calculate_time_derivative (int i) inline
Definition at line 275 of file Equation_base.h.
  {
    calculate_time_derivative_=i;
  };
References calculate_time_derivative_.
Referenced by Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), and Equation_base().
set_param()
void Equation_base::set_param (Param & titi) protected virtual
< XD attr conditions_limites|boundary_conditions condlims conditions_limites 1 Boundary conditions.
< XD attr conditions_initiales|initial_conditions condinits conditions_initiales 1 Initial conditions.
< XD attr sources sources sources 1 To introduce a source term into an equation (in case of several source terms into the same equation, the blocks corresponding to the various terms need to be separated by a comma)
< XD attr ecrire_fichier_xyz_valeur_bin ecrire_fichier_xyz_valeur_param ecrire_fichier_xyz_valeur_bin 1 This keyword is used to write the values of a field only for some boundaries in a binary file with the following format: n_valeur NL2 x_1 y_1 [z_1] val_1 NL2 ... NL2 x_n y_n [z_n] val_n NL2 The created files are named : pbname_fieldname_[boundaryname]_time.dat
< XD attr ecrire_fichier_xyz_valeur ecrire_fichier_xyz_valeur_param ecrire_fichier_xyz_valeur 1 This keyword is used to write the values of a field only for some boundaries in a text file with the following format: n_valeur NL2 x_1 y_1 [z_1] val_1 NL2 ... NL2 x_n y_n [z_n] val_n NL2 The created files are named : pbname_fieldname_[boundaryname]_time.dat
< XD attr parametre_equation parametre_equation_base parametre_equation 1 Keyword used to specify additional parameters for the equation
< XD attr equation_non_resolue chaine equation_non_resolue 1 The equation will not be solved while condition(t) is verified if equation_non_resolue keyword is used. Exemple: The Navier-Stokes equations are not solved between time t0 and t1. NL2 Navier_Sokes_Standard NL2 { equation_non_resolue (t>t0)*(t<t1) }
Reimplemented in Conduction, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, and Navier_Stokes_std.
Definition at line 302 of file Equation_base.cpp.
{
  param.ajouter_non_std("conditions_limites|boundary_conditions",(this),Param::REQUIRED);  //!< XD attr conditions_limites|boundary_conditions condlims conditions_limites 1 Boundary conditions.
  param.ajouter_non_std("conditions_initiales|initial_conditions",(this),Param::REQUIRED); //!< XD attr conditions_initiales|initial_conditions condinits conditions_initiales 1 Initial conditions.
  param.ajouter_non_std("sources",(this)); //!< XD attr sources sources sources 1 To introduce a source term into an equation (in case of several source terms into the same equation, the blocks corresponding to the various terms need to be separated by a comma)
  param.ajouter_non_std("ecrire_fichier_xyz_valeur_bin",(this)); //!< XD attr ecrire_fichier_xyz_valeur_bin ecrire_fichier_xyz_valeur_param ecrire_fichier_xyz_valeur_bin 1 This keyword is used to write the values of a field only for some boundaries in a binary file with the following format: n_valeur NL2 x_1 y_1 [z_1] val_1 NL2 ... NL2 x_n y_n [z_n] val_n NL2 The created files are named : pbname_fieldname_[boundaryname]_time.dat
  param.ajouter_non_std("ecrire_fichier_xyz_valeur",(this)); //!< XD attr ecrire_fichier_xyz_valeur ecrire_fichier_xyz_valeur_param ecrire_fichier_xyz_valeur 1 This keyword is used to write the values of a field only for some boundaries in a text file with the following format: n_valeur NL2 x_1 y_1 [z_1] val_1 NL2 ... NL2 x_n y_n [z_n] val_n NL2 The created files are named : pbname_fieldname_[boundaryname]_time.dat
  param.ajouter_non_std("bords",(this));
  param.ajouter("parametre_equation",&parametre_equation_); //!< XD attr parametre_equation parametre_equation_base parametre_equation 1 Keyword used to specify additional parameters for the equation
  param.ajouter_non_std("equation_non_resolue",(this)); //!< XD attr equation_non_resolue chaine equation_non_resolue 1 The equation will not be solved while condition(t) is verified if equation_non_resolue keyword is used. Exemple: The Navier-Stokes equations are not solved between time t0 and t1. NL2 Navier_Sokes_Standard NL2 { equation_non_resolue (t>t0)*(t<t1) }
}
References Param::ajouter(), Param::ajouter_non_std(), parametre_equation_, and Param::REQUIRED.
Referenced by readOn(), Conduction::set_param(), Masse_Multiphase::set_param(), Convection_Diffusion_std::set_param(), and Navier_Stokes_std::set_param().
set_residuals()
void Equation_base::set_residuals (DoubleTab r) inline
Definition at line 285 of file Equation_base.h.
  {
    if(field_residu_.non_nul())
      {
        if (field_residu_.valeur().valeurs().dimension_tot(0) == r.dimension_tot(0)) field_residu_.valeur().valeurs() = r;
        else
          {
            DoubleTab_parts parts(r);
            if (parts[0].dimension_tot(0) == field_residu_.valeur().valeurs().dimension_tot(0)) field_residu_.valeur().valeurs() = parts[0];
          }
      }
  };
References TRUSTTab< _TYPE_ >::dimension_tot(), field_residu_, O_U_Ptr::non_nul(), Deriv_Champ_Fonc_base::valeur(), and Champ_Don_base::valeurs().
Referenced by Schema_Temps_base::update_critere_statio().
solv_masse() [1/2]
Solveur_Masse & Equation_base::solv_masse () inline
Renvoie le solveur de masse associe a l'equation.
Returns
Solveur_Masse&
Signification: le solveur de masse associe a l'equation
Contraintes:
Definition at line 449 of file Equation_base.h.
{
  return solveur_masse;
}
References solveur_masse.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Operateur::ajouter(), Schema_Temps_base::ajouter_blocs(), Schema_Temps_base::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), calculer_champ_conserve(), Assembleur_P_VEF::calculer_inv_volume(), calculer_inv_volume(), completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), Champ_Generique_Gradient::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Gradient_conjugue_diff_impl(), has_interface_blocs(), SETS::iterer_NS(), Piso::iterer_NS(), Solveur_U_P::iterer_NS(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Op_Diff_VEFP1NCP1B_Face::test(), Operateur_base::tester_contribuer_a_avec(), Navier_Stokes_std::uzawa(), and verifier_complet().
solv_masse() [2/2]
const Solveur_Masse & Equation_base::solv_masse () const inline
Renvoie le solveur de masse associe a l'equation.
(version const)
Returns
Solveur_Masse&
Signification: le solveur de masse associe a l'equation
Contraintes: reference constante
Definition at line 470 of file Equation_base.h.
{
  return solveur_masse;
}
References solveur_masse.
sources() [1/2]
Sources & Equation_base::sources ()
Renvoie les termes sources asssocies a l'equation.
Returns
Sources&
Signification: la liste des termes sources associees a l'equation
Contraintes:
Definition at line 600 of file Equation_base.cpp.
{
  return les_sources;
}
References les_sources.
Referenced by Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Traitement_particulier_NS_EC::calculer_Ec(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Champ_Post_Operateur_Eqn::get_champ(), Gradient_conjugue_diff_impl(), Navier_Stokes_std::initTimeStep(), Piso::iterer_NS(), Probleme_base::postraiter(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Navier_Stokes_std::readOn(), Energie_Multiphase::readOn(), and Masse_Multiphase::readOn().
sources() [2/2]
const Sources & Equation_base::sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Returns
Sources&
Signification: la liste des termes sources associees a l'equation
Contraintes: reference constante
Definition at line 620 of file Equation_base.cpp.
{
  return les_sources;
}
References les_sources.
updateGivenFields()
bool Equation_base::updateGivenFields () virtual
Definition at line 1379 of file Equation_base.cpp.
{
  Schema_Temps_base& sch=schema_temps();
  double temps_present=sch.temps_courant();
  double temps_futur=temps_present+sch.pas_de_temps();
// Pour chaque temps futur
  for (int i=1; i<=sch.nb_valeurs_futures(); i++)
    {
      double tps=sch.temps_futur(i);
// Calcul des CLs a ce temps.
      zone_Cl_dis().mettre_a_jour(tps);
    }
// Calcul du taux d'accroissement des CLs entre les temps present et futur.
  zone_Cl_dis()->Gpoint(temps_present,temps_futur);
// MaJ des operateurs
  for (int i = 0; i < nombre_d_operateurs(); i++)
    if (operateur(i).op_non_nul())
      operateur(i).l_op_base().mettre_a_jour(temps_present);
// Mise a jour des sources au temps present
  les_sources.mettre_a_jour(temps_present);
  return true;
}
References Operateur::l_op_base(), les_sources, Operateur_base::mettre_a_jour(), Sources::mettre_a_jour(), Zone_Cl_dis::mettre_a_jour(), Schema_Temps_base::nb_valeurs_futures(), nombre_d_operateurs(), Operateur::op_non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), schema_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_futur(), and zone_Cl_dis().
Referenced by Probleme_base::updateGivenFields().
valider_iteration()
void Equation_base::valider_iteration () virtual
Definition at line 1267 of file Equation_base.cpp.
{
}
Referenced by Simple::iterer_eqn(), iterer_eqn_expl(), and iterer_eqn_expl_diffusion_implicite().
verif_Cl()
int Equation_base::verif_Cl () const protected virtual
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
Returns
int
Signification:
Contraintes:
Reimplemented in Navier_Stokes_std.
Definition at line 1722 of file Equation_base.cpp.
{
  const Conds_lim& les_cl=la_zone_Cl_dis->les_conditions_limites();
  les_cl.compatible_avec_eqn(*this);
  return les_cl.compatible_avec_discr(discretisation());
}
References Conds_lim::compatible_avec_discr(), Conds_lim::compatible_avec_eqn(), discretisation(), la_zone_Cl_dis, and Zone_Cl_dis::les_conditions_limites().
Referenced by lire_motcle_non_standard(), and Navier_Stokes_std::verif_Cl().
verifie_ch_init_nb_comp()
void Equation_base::verifie_ch_init_nb_comp (const Champ_Inc_base & ch_ref, const int nb_comp) const virtual
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
Definition at line 1762 of file Equation_base.cpp.
{
  const Nature_du_champ nature = ch_ref.nature_du_champ();
  const int nb_composantes = ch_ref.nb_comp();
  const Nom& nom = ch_ref.le_nom();
  if (nature==scalaire)
    {
      if (nb_comp!=1)
        {
          Cerr<<"The nature of the field "<<nom<<" unknown to the equation name "<<le_nom()<<" is scalar."<<finl;
          Cerr<<"The number of components readed for this field "<<nb_comp<<" is not compatible with its nature."<<finl;
          Cerr<<"We must read only one component for this field."<<finl;
          exit();
        }
    }
  else if (nature==vectoriel)
    {
      if (nb_comp!=Objet_U::dimension)
        {
          Cerr<<"The nature of the field "<<nom<<" unknown to the equation name "<<le_nom()<<" is vector."<<finl;
          Cerr<<"The number of components readed for this field "<<nb_comp<<" is not compatible with its nature."<<finl;
          Cerr<<"It should read "<<Objet_U::dimension<<" components for this field."<<finl;
          exit();
        }
    }
  else if (nature==multi_scalaire)
    {
      if (nb_comp!=nb_composantes)
        {
          Cerr<<"The nature of the field "<<nom<<" unknown to the equation name "<<le_nom()<<" is multiscalar."<<finl;
          Cerr<<"The number of components readed for this field "<<nb_comp<<" does not match the number expected."<<finl;
          Cerr<<"It should read "<<nb_composantes<<" components for this field."<<finl;
          exit();
        }
    }
  else
    {
      Cerr<<"The nature of the field is not recognized"<<finl;
      exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), finl, le_nom(), Field_base::le_nom(), multi_scalaire, Field_base::nature_du_champ(), Field_base::nb_comp(), scalaire, and vectoriel.
Referenced by lire_cond_init(), Navier_Stokes_std::lire_cond_init(), QDM_Multiphase::lire_cond_init(), verifie_ch_init_nb_comp_cl(), and Energie_Multiphase::verifie_ch_init_nb_comp_cl().
verifie_ch_init_nb_comp_cl()
virtual void Equation_base::verifie_ch_init_nb_comp_cl (const Champ_Inc_base & ch_ref, const int nb_comp, const Cond_lim_base & cl) const inline virtual
Reimplemented in Energie_Multiphase.
Definition at line 240 of file Equation_base.h.
  {
    verifie_ch_init_nb_comp(ch_ref, nb_comp);
  }
References verifie_ch_init_nb_comp().
Referenced by Dirichlet::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), and Echange_externe_impose::verifie_ch_init_nb_comp().
zone_Cl_dis() [1/2]
Zone_Cl_dis & Equation_base::zone_Cl_dis () inline virtual
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
Returns
Zone_Cl_dis&
Signification: Zone de condition aux limites discretisee
Contraintes:
Definition at line 408 of file Equation_base.h.
{
  return la_zone_Cl_dis;
}
References la_zone_Cl_dis.
Referenced by Terme_Boussinesq_VDF_Face::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Champ_Ostwald_VEF::calculer_dscald(), Operateur_base::calculer_pour_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Operateur_base::completer(), Source_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Convection_Diffusion_Chaleur_WC::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), Champ_Generique_Gradient::completer(), Fluide_Dilatable_base::completer(), Fluide_Weakly_Compressible::completer(), Fluide_Quasi_Compressible::completer_edo(), Terme_Source_Canal_perio::compute_heat_flux(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Champ_front_fonc_gradient::condition_limite(), Source_WC_Chaleur::correct_grad_boundary(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Op_EF_base::impr(), Op_VEF_Face::impr(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Op_Diff_PolyMAC_Elem::init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Terme_Puissance_Thermique::initialiser_champ_puissance(), initTimeStep(), Probleme_base::initTimeStep(), Probleme_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqs(), SETS::iterer_NS(), Solveur_U_P::iterer_NS(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), mettre_a_jour(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Turbulence_paroi::readOn(), Turbulence_paroi_scal::readOn(), Modele_turbulence_hyd_nul::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Champ_front_contact_VEF::remplir_faces_coin(), Probleme_base::solveTimeStep(), Champ_front_contact_VEF::test_faces_coin(), test_imposer_cond_lim(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), updateGivenFields(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Pb_Hydraulique_Concentration::verifier(), Pb_Thermohydraulique::verifier(), Pb_Thermohydraulique_Concentration::verifier(), Pb_Multiphase::verifier(), Pb_Dilatable_Proto::verifier_impl(), Champ_front_calc::zone_Cl_dis(), Champ_Inc_base::zone_Cl_dis(), and Champ_front_contact_VEF::zone_Cl_dis().
zone_Cl_dis() [2/2]
const Zone_Cl_dis & Equation_base::zone_Cl_dis () const inline virtual
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Returns
Zone_Cl_dis&
Signification: Zone de condition aux limites discretisee
Contraintes: reference constante
Definition at line 429 of file Equation_base.h.
{
  return la_zone_Cl_dis;
}
References la_zone_Cl_dis.
zone_dis() [1/2]
Zone_dis & Equation_base::zone_dis ()
Renvoie la zone discretisee associee a l'equation.
Returns
Zone_dis&
Signification: la zone discretisee asscoiee a l'equation
Contraintes:
Definition at line 100 of file Equation_base.cpp.
{
  if (!la_zone_dis.non_nul())
    {
      Cerr << "There is no object of type Zone_dis yet associated to the equation " << que_suis_je() << finl;
      Cerr << "This means that the problem has not been discretized or" << finl;
      Cerr << "that instruction Discretiser is misplaced" << finl;
      exit();
    }
  return la_zone_dis.valeur();
}
References Cerr, Process::exit(), finl, la_zone_dis, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Zone_dis::valeur().
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), Puissance_Thermique_EF::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Champ_front_contact_VEF::calcul_coeff_amort(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Perte_Charge_Singuliere::calculate_Q(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Operateur_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Operateur_base::completer(), Source_base::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Convection_Diffusion_Chaleur_WC::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Champ_Generique_Gradient::completer(), Champ_Post_Operateur_Eqn::completer(), Fluide_Dilatable_base::completer(), Fluide_Quasi_Compressible::completer_edo(), Terme_Source_Canal_perio::compute_heat_flux(), creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), Turbulence_paroi_base::creer_champ(), QDM_Multiphase::creer_champ(), Fluide_base::creer_e_int(), discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Constituant::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Navier_Stokes_std::discretiser_assembleur_pression(), Reaction::discretiser_omega(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Operateur_base::get_localisation_pour_post(), Op_EF_base::impr(), Op_VEF_Face::impr(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Champ_front_recyclage::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), Diametre_hyd_champ::interpreter(), Porosites::interpreter(), Porosites_champ::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), SETS::iterer_NS(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Probleme_base::preparer_calcul(), List_Equations_Scalaires_Passifs_Especes::readOn(), Zone_Cl_dis_base::readOn(), Turbulence_paroi::readOn(), Turbulence_paroi_scal::readOn(), Modele_turbulence_hyd_nul::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Convection_Diffusion_Temperature::transport_ibc(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Champ_Post_Operateur_Eqn::verification_cas_compo(), and Zone_Cl_dis_base::zone_dis().
zone_dis() [2/2]
const Zone_dis & Equation_base::zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
Returns
Zone_dis&
Signification: la zone discretisee asssociee a l'equation
Contraintes: reference constante
Definition at line 128 of file Equation_base.cpp.
{
  if (!la_zone_dis.non_nul())
    {
      Cerr << "There is no object of type Zone_dis associated to the equation " << que_suis_je() << finl;
      Cerr << "This means that the problem has not been discretized" << finl;
      exit();
    }
  assert(la_zone_dis.non_nul());
  return la_zone_dis.valeur();
}
References Cerr, Process::exit(), finl, la_zone_dis, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Zone_dis::valeur().
Member Data Documentation
calculate_time_derivative_
int Equation_base::calculate_time_derivative_ private
Definition at line 368 of file Equation_base.h.
Referenced by calculate_time_derivative(), and set_calculate_time_derivative().
champ_conserve_
Champ_Inc Equation_base::champ_conserve_ mutable protected
Definition at line 337 of file Equation_base.h.
Referenced by abortTimeStep(), avancer(), champ_conserve(), champ_convecte(), has_champ_conserve(), has_champ_convecte(), init_champ_conserve(), initTimeStep(), mettre_a_jour_champs_conserves(), and reculer().
champ_convecte_
Champ_Inc Equation_base::champ_convecte_ mutable protected
Definition at line 338 of file Equation_base.h.
Referenced by abortTimeStep(), avancer(), Energie_Multiphase::champ_convecte(), Energie_Multiphase::has_champ_convecte(), Energie_Multiphase::init_champ_convecte(), initTimeStep(), mettre_a_jour_champs_conserves(), and reculer().
champs_compris_
Champs_compris Equation_base::champs_compris_ protected
Definition at line 329 of file Equation_base.h.
Referenced by Conduction::Conduction(), Convection_Diffusion_Temperature::Convection_Diffusion_Temperature(), creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Conduction::discretiser(), Equation_base(), get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), Navier_Stokes_std::Navier_Stokes_std(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Masse_Multiphase::readOn(), and QDM_Multiphase::readOn().
derivee_en_temps_
Champ_Inc Equation_base::derivee_en_temps_ private
Definition at line 367 of file Equation_base.h.
Referenced by derivee_en_temps().
disable_equation_residual_
int Equation_base::disable_equation_residual_ = 0 private
Definition at line 362 of file Equation_base.h.
Referenced by disable_equation_residual(), and readOn().
dt_ecrire_fic_xyz
ArrOfDouble Equation_base::dt_ecrire_fic_xyz private
Definition at line 347 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), and lire_motcle_non_standard().
dt_op_bak
DoubleList Equation_base::dt_op_bak mutable protected
Definition at line 314 of file Equation_base.h.
Referenced by calculer_pas_de_temps(), and preparer_calcul().
ecrit_champ_xyz_bin
int Equation_base::ecrit_champ_xyz_bin private
Definition at line 352 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), Equation_base(), and lire_motcle_non_standard().
eq_non_resolue_input_
Value_Input_Int Equation_base::eq_non_resolue_input_ private
Definition at line 364 of file Equation_base.h.
Referenced by equation_non_resolue(), and lire_motcle_non_standard().
equation_non_resolue_
Parser_U Equation_base::equation_non_resolue_ mutable private
Definition at line 363 of file Equation_base.h.
Referenced by Equation_base(), equation_non_resolue(), lire_motcle_non_standard(), and readOn().
field_residu_
Champ_Fonc Equation_base::field_residu_ private
Definition at line 359 of file Equation_base.h.
Referenced by creer_champ(), get_champ(), and set_residuals().
implicite_
int Equation_base::implicite_ protected
Definition at line 324 of file Equation_base.h.
Referenced by completer(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), and Equation_base().
info_obj
const Type_info Equation_base::info_obj static
Definition at line 88 of file Equation_base.h.
la_zone_Cl_dis
Zone_Cl_dis Equation_base::la_zone_Cl_dis protected
Definition at line 306 of file Equation_base.h.
Referenced by completer(), Navier_Stokes_std::completer(), discretiser(), ecrire_fichier_xyz(), lire_cl(), preparer_calcul(), Navier_Stokes_std::preparer_calcul(), printOn(), verif_Cl(), and zone_Cl_dis().
la_zone_dis
Ref_Zone_dis Equation_base::la_zone_dis protected
Definition at line 305 of file Equation_base.h.
Referenced by associer_zone_dis(), and zone_dis().
le_schema_en_temps
Ref_Schema_Temps_base Equation_base::le_schema_en_temps protected
Definition at line 304 of file Equation_base.h.
Referenced by associer_sch_tps_base(), calculer_pas_de_temps(), derivee_en_temps_conv(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), ecrire_fichier_xyz(), equation_non_resolue(), Gradient_conjugue_diff_impl(), Navier_Stokes_std::impr(), Navier_Stokes_std::initTimeStep(), limpr(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projection_a_faire(), Navier_Stokes_std::projeter(), and schema_temps().
les_sources
Sources Equation_base::les_sources protected
Definition at line 303 of file Equation_base.h.
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), associer_pb_base(), completer(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_std::completer(), QDM_Multiphase::completer(), creer_champ(), derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), get_champ(), get_noms_champs_postraitables(), has_interface_blocs(), impr(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), lire_sources(), mettre_a_jour(), preparer_calcul(), printOn(), sources(), and updateGivenFields().
list_champ_combi
Champs_Fonc Equation_base::list_champ_combi protected
Definition at line 330 of file Equation_base.h.
Referenced by get_champ().
liste_modeles_
List_RefObjU Equation_base::liste_modeles_ protected
Definition at line 328 of file Equation_base.h.
Referenced by completer(), and get_modele().
matrice_init
int Equation_base::matrice_init mutable protected
Definition at line 334 of file Equation_base.h.
Referenced by dimensionner_matrice(), dimensionner_matrice_sans_mem(), and readOn().
matrice_stockee
Matrice_Morse Equation_base::matrice_stockee mutable protected
Definition at line 333 of file Equation_base.h.
Referenced by dimensionner_matrice(), and dimensionner_matrice_sans_mem().
mon_probleme
Ref_Probleme_base Equation_base::mon_probleme protected
Definition at line 307 of file Equation_base.h.
Referenced by associer_pb_base(), completer(), discretisation(), ecrire_fichier_xyz(), equation_non_resolue(), lire_motcle_non_standard(), and probleme().
nb_bords_post_xyz
IntVect Equation_base::nb_bords_post_xyz private
Definition at line 350 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), and lire_motcle_non_standard().
nom_
Nom Equation_base::nom_ protected
Definition at line 301 of file Equation_base.h.
Referenced by associer_pb_base(), le_nom(), nommer(), and printOn().
nom_champ_xyz
Motcles Equation_base::nom_champ_xyz private
Definition at line 348 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), and lire_motcle_non_standard().
nombre_champ_xyz
int Equation_base::nombre_champ_xyz private
Definition at line 351 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), Equation_base(), and lire_motcle_non_standard().
noms_bord_xyz
Liste_Noms Equation_base::noms_bord_xyz private
Definition at line 349 of file Equation_base.h.
Referenced by ecrire_fichier_xyz(), and lire_motcle_non_standard().
NULL_
DoubleTab Equation_base::NULL_ mutable private
Definition at line 361 of file Equation_base.h.
Referenced by Gradient_conjugue_diff_impl().
parametre_equation_
Parametre_equation Equation_base::parametre_equation_ protected
Definition at line 325 of file Equation_base.h.
Referenced by parametre_equation(), and set_param().
residu_
DoubleVect Equation_base::residu_ private
Definition at line 356 of file Equation_base.h.
Referenced by expression_residu(), get_residu(), imprime_residu(), and initialise_residu().
residu_initial_
DoubleVect Equation_base::residu_initial_ private
Definition at line 357 of file Equation_base.h.
Referenced by initialise_residu(), and residu_initial().
solveur_masse
Solveur_Masse Equation_base::solveur_masse protected
Definition at line 302 of file Equation_base.h.
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), associer_pb_base(), QDM_Multiphase::completer(), Navier_Stokes_std::corriger_derivee_impl(), derivee_en_temps_conv(), derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), discretiser(), Gradient_conjugue_diff_impl(), initTimeStep(), Conduction::lire_motcle_non_standard(), Navier_Stokes_std::mettre_a_jour(), preparer_calcul(), Navier_Stokes_std::preparer_calcul(), printOn(), Navier_Stokes_std::projeter(), Convection_Diffusion_Temperature::readOn(), and solv_masse().
sys_invariant_
int Equation_base::sys_invariant_ protected
Definition at line 323 of file Equation_base.h.
Referenced by completer(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), and Equation_base().
volume_maille
Champ_Fonc Equation_base::volume_maille protected
Definition at line 326 of file Equation_base.h.
Referenced by creer_champ(), and get_champ().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Equation_base.h
src/Kernel/Framework/Equation_base.cpp