TRUST: Champs_compris Class Reference
Champs_compris Class Reference
#include <Champs_compris.h>
Public Member Functions
Champs_compris ()
~Champs_compris ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
virtual void ajoute_champ (const Champ_base &champ)
virtual void ajoute_nom_compris (const Nom &nom)
virtual const Noms liste_noms_compris () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champs_compris & self_cast (Objet_U &)
static const Champs_compris & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Champ_base liste_champs_
Noms liste_noms_
Noms liste_noms_construits_
Detailed Description
Definition at line 34 of file Champs_compris.h.
Constructor & Destructor Documentation
Champs_compris()
Champs_compris::Champs_compris ()
Definition at line 22 of file Champs_compris.cpp.
~Champs_compris()
Champs_compris::~Champs_compris ()
Definition at line 22 of file Champs_compris.cpp.
Member Function Documentation
ajoute_champ()
void Champs_compris::ajoute_champ (const Champ_base & champ) virtual
Definition at line 191 of file Champs_compris.cpp.
{
  REF(Champ_base) champ_ref;
  champ_ref = champ;
  assert(!liste_champs_.contient(champ_ref));
// GF ne sert a rien le test ne marche pas !!!
// il faut tester si champ est contenu (c.a.d si il ya une reference vers celui-ci
  if (liste_champs_.contient(champ_ref)) abort();
// GF essai brutal ....
  CONST_LIST_CURSEUR(REF(Champ_base)) curseur = liste_champs_;
  Motcle nom_champ_add = champ.le_nom();
  while (curseur)
    {
      const Champ_base& ch= curseur.valeur().valeur();
      const Nom& nom_champ = ch.le_nom();
      if (nom_champ==nom_champ_add)
        {
          Cerr<<champ.le_nom()<<" is already in the list of names of field !!"<<finl;
// exit();
        }
      ++curseur;
    }
  liste_champs_.add(champ_ref);
  Cerr<<"Champs_compris::ajoute_champ " <<champ.le_nom()<<finl;
  rebuild_liste_noms(liste_champs_,liste_noms_,liste_noms_construits_);
}
References Process::abort(), List_Ref_Champ_base::add(), Cerr, CONST_LIST_CURSEUR, List_Ref_Champ_base::contient(), finl, Field_base::le_nom(), liste_champs_, liste_noms_, liste_noms_construits_, rebuild_liste_noms(), and REF.
Referenced by Equation_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_Elem::creer_champ(), Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Navier_Stokes_std::creer_champ(), Turbulence_paroi_base::creer_champ(), QDM_Multiphase::creer_champ(), Equation_base::discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Conduction::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Constituant::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Milieu_composite::discretiser(), Traitement_particulier_NS_Pression_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Terme_Source_Acceleration::lire_data(), Puissance_Thermique_EF::readOn(), Source_Scalaire_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Puissance_Thermique_QC_EF::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Masse_Multiphase::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), and Terme_Puissance_Thermique_VEF_base::readOn().
ajoute_nom_compris()
void Champs_compris::ajoute_nom_compris (const Nom & nom) virtual
Definition at line 220 of file Champs_compris.cpp.
{
  liste_noms_.add(mot);
  rebuild_liste_noms(liste_champs_,liste_noms_,liste_noms_construits_);
}
References Vect_Nom::add(), liste_champs_, liste_noms_, liste_noms_construits_, and rebuild_liste_noms().
Referenced by Conduction::Conduction(), Convection_Diffusion_Temperature::Convection_Diffusion_Temperature(), Equation_base::Equation_base(), Navier_Stokes_std::Navier_Stokes_std(), Op_Conv_EF_Stab_PolyMAC_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), QDM_Multiphase::readOn(), and Turbulence_paroi_base::Turbulence_paroi_base().
cree_instance()
Objet_U * Champs_compris::cree_instance () static
Definition at line 22 of file Champs_compris.cpp.
duplique()
int Champs_compris::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Champs_compris.cpp.
get_champ()
const Champ_base & Champs_compris::get_champ (const Motcle & nom) const virtual
Definition at line 61 of file Champs_compris.cpp.
{
  REF(Champ_base) ref_champ;
  if (has_champ(motcle, ref_champ)) return ref_champ;
  throw Champs_compris_erreur();
  return ref_champ;
}
References has_champ(), and REF.
Referenced by Equation_base::get_champ(), Loi_Fermeture_base::get_champ(), Milieu_base::get_champ(), Operateur_base::get_champ(), Source_base::get_champ(), Loi_Etat_base::get_champ(), Puissance_Thermique_QC_EF::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Marqueur_Lagrange_base::get_champ(), Traitement_particulier_NS_base::get_champ(), Mod_turb_hyd_base::get_champ(), Modele_turbulence_scal_base::get_champ(), Turbulence_paroi_base::get_champ(), Turbulence_paroi_scal_base::get_champ(), Diametre_bulles_champ::get_champ(), Diametre_bulles_constant::get_champ(), and Traitement_particulier_Solide_base::get_champ().
get_info()
const Type_info * Champs_compris::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file Champs_compris.cpp.
has_champ()
bool Champs_compris::has_champ (const Motcle & nom, Ref_Champ_base & ref_champ) const virtual
< case insensitive test
< case insensitive test
< case insensitive test
Definition at line 69 of file Champs_compris.cpp.
{
  if (motcle=="??")
    {
      Cerr<<"Champs_compris::get_champ()"<<finl;
      Cerr<<"No field can be requested using the identifier \'??\'"<<finl;
      exit();
    }
  CONST_LIST_CURSEUR(REF(Champ_base)) curseur = liste_champs_;
  while (curseur)
    {
      ref_champ = curseur.valeur().valeur();
      if (ref_champ.le_nom() == motcle)  //!< case insensitive test
        return true;
      else
        {
          const Noms& syno = ref_champ->get_synonyms();
          int nb_syno = syno.size();
          for (int s = 0; s < nb_syno; s++)
            {
              if (syno[s] == motcle)  //!< case insensitive test
                return true;
            }
          int nb_composantes = ref_champ->nb_comp();
          for (int i = 0; i < nb_composantes; i++)
            {
              if (motcle == ref_champ->nom_compo(i)) //!< case insensitive test
                return true;
            }
        }
      ++curseur;
    }
  return false;
}
References Cerr, CONST_LIST_CURSEUR, Process::exit(), finl, Field_base::get_synonyms(), Field_base::le_nom(), liste_champs_, Field_base::nb_comp(), Field_base::nom_compo(), REF, and vect_impl::size().
Referenced by get_champ(), Loi_Fermeture_base::has_champ(), Operateur_base::has_champ(), and Source_base::has_champ().
info()
const Type_info * Champs_compris::info () static
Definition at line 22 of file Champs_compris.cpp.
liste_noms_compris()
const Noms Champs_compris::liste_noms_compris () const virtual
Definition at line 225 of file Champs_compris.cpp.
{
  Noms liste_noms_prov(liste_noms_construits_);
  rebuild_liste_noms(liste_champs_,liste_noms_,liste_noms_prov,1);
  return liste_noms_prov;
}
References liste_champs_, liste_noms_, liste_noms_construits_, and rebuild_liste_noms().
Referenced by Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Source_base::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), Puissance_Thermique_QC_EF::get_noms_champs_postraitables(), Marqueur_Lagrange_base::get_noms_champs_postraitables(), Traitement_particulier_NS_base::get_noms_champs_postraitables(), Mod_turb_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Turbulence_paroi_base::get_noms_champs_postraitables(), Turbulence_paroi_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), and Traitement_particulier_Solide_base::get_noms_champs_postraitables().
printOn()
Sortie & Champs_compris::printOn (Sortie & os) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Champs_compris.cpp.
{
  return os;
}
readOn()
Entree & Champs_compris::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 56 of file Champs_compris.cpp.
{
  return is;
}
self_cast() [1/2]
const Champs_compris & Champs_compris::self_cast (const Objet_U & r) static
Definition at line 22 of file Champs_compris.cpp.
self_cast() [2/2]
Champs_compris & Champs_compris::self_cast (Objet_U & r) static
Definition at line 22 of file Champs_compris.cpp.
taille_memoire()
unsigned Champs_compris::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Champs_compris.cpp.
Member Data Documentation
info_obj
const Type_info Champs_compris::info_obj static
Definition at line 37 of file Champs_compris.h.
liste_champs_
List_Ref_Champ_base Champs_compris::liste_champs_ protected
Definition at line 52 of file Champs_compris.h.
Referenced by ajoute_champ(), ajoute_nom_compris(), has_champ(), and liste_noms_compris().
liste_noms_
Noms Champs_compris::liste_noms_ protected
Definition at line 53 of file Champs_compris.h.
Referenced by ajoute_champ(), ajoute_nom_compris(), and liste_noms_compris().
liste_noms_construits_
Noms Champs_compris::liste_noms_construits_ protected
Definition at line 54 of file Champs_compris.h.
Referenced by ajoute_champ(), ajoute_nom_compris(), and liste_noms_compris().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champs_compris.h
src/Kernel/Framework/Champs_compris.cpp