TRUST: Discretisation_base Class Reference
Discretisation_base Class Reference abstract
classe Discretisation_base
Cette classe represente un schema de discretisation en espace, qui
sera associe a un probleme. Discretisation_base est la classe
abstraite qui est a la base de la hierarchie des discretisations
en espace.
#include <Discretisation_base.h>
Public Types
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Public Member Functions
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Attributes
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Private Member Functions
void test_demande_description (const Motcle &, const Nom &) const
Cette fonction est un outil pour les trois methodes suivantes...
virtual void modifier_champ_tabule (const Zone_dis_base &zone_dis, Champ_Fonc_Tabule &ch_tab, const Vect_Ref_Champ_base &ch_inc) const
Static Private Member Functions
static void champ_fixer_membres_communs (Champ_base &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps)
Fonction outil pour fixer les membres communs a tous les types
de champs (utilisee dans creer_champ)
Detailed Description
classe Discretisation_base
Cette classe represente un schema de discretisation en espace, qui
sera associe a un probleme. Discretisation_base est la classe
abstraite qui est a la base de la hierarchie des discretisations
en espace.
See also
Probleme_base
Classe abstraite dont toutes les discretisations en espace doivent
deriver.
Methode abstraite:
void zone_Cl_dis(Zone_dis& , Zone_Cl_dis&) const
Definition at line 52 of file Discretisation_base.h.
Member Enumeration Documentation
type_calcul_du_residu
enum Discretisation_base::type_calcul_du_residu
Enumerator
VIA_CONTRIBUER_AU_SECOND_MEMBRE
VIA_AJOUTER
Definition at line 70 of file Discretisation_base.h.
                             { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0,
                               VIA_AJOUTER                     = 1
                             };
Constructor & Destructor Documentation
Discretisation_base()
Discretisation_base::Discretisation_base ()
Definition at line 26 of file Discretisation_base.cpp.
~Discretisation_base()
Discretisation_base::~Discretisation_base () override
Definition at line 26 of file Discretisation_base.cpp.
Member Function Documentation
champ_fixer_membres_communs()
void Discretisation_base::champ_fixer_membres_communs (Champ_base & ch, const Zone_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, double temps) static private
Fonction outil pour fixer les membres communs a tous les types
de champs (utilisee dans creer_champ)
Definition at line 206 of file Discretisation_base.cpp.
{
  ch.associer_zone_dis_base(z);
  ch.nommer(nom);
  ch.fixer_nb_comp(nb_comp);
  if ((nb_comp>1)&& (nb_comp==dimension))
    {
      Noms noms(nb_comp);
      if (!axi)
        {
          noms[0]=nom+"X";
          noms[1]=nom+"Y";
          if (nb_comp>2)
            noms[2]=nom+"Z";
        }
      else
        {
          noms[0]=nom+"R";
          noms[1]=nom+"teta";
          if (nb_comp>2)
            noms[2]=nom+"Z";
        }
      ch.fixer_noms_compo(noms);
    }
  ch.fixer_unite(unite);
  ch.fixer_nb_valeurs_nodales(nb_ddl);
  ch.changer_temps(temps);
}
References Champ_base::associer_zone_dis_base(), Objet_U::axi, Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_base::fixer_nb_valeurs_nodales(), Field_base::fixer_noms_compo(), Field_base::fixer_unite(), and Field_base::nommer().
Referenced by creer_champ().
codage_du_calcul_du_residu()
virtual type_calcul_du_residu Discretisation_base::codage_du_calcul_du_residu (void) const inline virtual
Reimplemented in EF_discretisation, and PolyMAC_discretisation.
Definition at line 74 of file Discretisation_base.h.
  {
    return VIA_AJOUTER;
  }
References VIA_AJOUTER.
Referenced by Equation_base::assembler(), and Convection_Diffusion_Temperature::assembler().
creer_champ() [1/3]
void Discretisation_base::creer_champ (Champ_Don & ch, const Zone_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, double temps, const Nom & directive = nom_vide, const Nom & nom_discretisation = nom_vide) static
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
< Pour contourner le probleme du "static" dans type_info::nom()
Definition at line 291 of file Discretisation_base.cpp.
{
  Nom nomd = nom_discretisation; //!< Pour contourner le probleme du "static" dans type_info::nom()
  ch.typer(type);
  Champ_Don_base& chb = ch.valeur();
  champ_fixer_membres_communs(chb, z, type, nom, unite, nb_comp, nb_ddl, temps);
}
References champ_fixer_membres_communs(), Deriv_::typer(), and Deriv_Champ_Don_base::valeur().
creer_champ() [2/3]
void Discretisation_base::creer_champ (Champ_Fonc & ch, const Zone_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, double temps, const Nom & directive = nom_vide, const Nom & nom_discretisation = nom_vide) static
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
< Pour contourner le probleme du "static" dans type_info::nom()
Definition at line 270 of file Discretisation_base.cpp.
{
  Nom nomd = nom_discretisation; //!< Pour contourner le probleme du "static" dans type_info::nom()
  ch.typer(type);
  Champ_Fonc_base& chb = ch.valeur();
  champ_fixer_membres_communs(chb, z, type, nom, unite, nb_comp, nb_ddl, temps);
}
References champ_fixer_membres_communs(), Deriv_::typer(), and Deriv_Champ_Fonc_base::valeur().
creer_champ() [3/3]
void Discretisation_base::creer_champ (Champ_Inc & ch, const Zone_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom & directive = nom_vide, const Nom & nom_discretisation = nom_vide) static
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
< Pour contourner le probleme du "static" dans type_info::nom()
Definition at line 247 of file Discretisation_base.cpp.
{
  Nom nomd = nom_discretisation; //!< Pour contourner le probleme du "static" dans type_info::nom()
  ch.typer(type);
  Champ_Inc_base& chb = ch.valeur();
  chb.fixer_nb_valeurs_temporelles(nb_pas_dt);
  champ_fixer_membres_communs(chb, z, type, nom, unite, nb_comp, nb_ddl, temps);
}
References champ_fixer_membres_communs(), Champ_Inc_base::fixer_nb_valeurs_temporelles(), Deriv_::typer(), and Deriv_Champ_Inc_base::valeur().
Referenced by EF_discretisation::discretiser_champ(), VEFPreP1B::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), VEFPreP1B::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::grad_T(), Equation_base::init_champ_conserve(), and Energie_Multiphase::init_champ_convecte().
discretiser()
void Discretisation_base::discretiser (Domaine_dis & dom) const virtual
Reimplemented in VEFPreP1B.
Definition at line 321 of file Discretisation_base.cpp.
{
  Nom type="Zone_";
  type+=que_suis_je();
  dom.discretiser(type);
}
References Domaine_dis::discretiser(), and Objet_U::que_suis_je().
Referenced by Probleme_base::discretiser(), and VEFPreP1B::discretiser().
discretiser_champ() [1/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, double temps, Champ_Don & champ) const
Definition at line 93 of file Discretisation_base.cpp.
{
  Noms noms;
  Noms unites;
  noms.add(nom);
  unites.add(unite);
  discretiser_champ(directive, z, scalaire, noms, unites, nb_comp, temps, champ);
}
References Vect_Nom::add(), discretiser_champ(), and scalaire.
Referenced by discretiser_champ().
discretiser_champ() [2/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, double temps, Champ_Fonc & champ) const
Definition at line 81 of file Discretisation_base.cpp.
{
  Noms noms;
  Noms unites;
  noms.add(nom);
  unites.add(unite);
  discretiser_champ(directive, z, scalaire, noms, unites, nb_comp, temps, champ);
}
References Vect_Nom::add(), discretiser_champ(), and scalaire.
discretiser_champ() [3/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const
Definition at line 67 of file Discretisation_base.cpp.
{
  Noms noms;
  Noms unites;
  noms.add(nom);
  unites.add(unite);
  discretiser_champ(directive, z, scalaire, noms, unites, nb_comp, nb_pas_dt, temps, champ, sous_type);
}
References Vect_Nom::add(), discretiser_champ(), and scalaire.
Referenced by Op_Grad_EF::associer(), Source_PDF_EF::associer_pb(), Discret_Thyd::concentration(), Op_Conv_EF_Stab_PolyMAC_Elem::creer_champ(), Navier_Stokes_std::creer_champ(), Turbulence_paroi_base::creer_champ(), QDM_Multiphase::creer_champ(), Fluide_base::creer_e_int(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_Morceau_Equation::creer_espace_stockage(), Discret_Thyd::diametre_hydraulique_elem(), Discret_Thyd::diametre_hydraulique_face(), Interpolation_IBM_hybrid::discretise(), Interpolation_IBM_elem_fluid::discretise(), Interpolation_IBM_mean_gradient::discretise(), Equation_base::discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Aire_interfaciale::discretiser(), Masse_Multiphase::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), Discr_inst::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), Mod_turb_hyd_base::discretiser_corr_visc_turb(), Mod_turb_hyd_base::discretiser_K(), Reaction::discretiser_omega(), Mod_turb_hyd_base::discretiser_visc_turb(), Discret_Thyd::divergence_U(), Discret_Thyd::entcor(), Discret_Thermique::Fluctu_Temperature(), Discret_Thermique::Flux_Chaleur_Turb(), Discret_Thermique::flux_neutronique(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Discret_Thyd::gradient_P(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Discret_Thyd::porosite_volumique(), Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), Source_Scalaire_EF::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Zone_Cl_EF::remplir_type_elem_Cl(), VDF_discretisation::residu(), VEF_discretisation::residu(), Discret_Thyd::section_passage(), Discret_Thermique::temperature(), Discret_Thyd::translation(), Discret_Thyd::vitesse(), and volume_maille().
discretiser_champ() [4/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const virtual
idem
Reimplemented in EF_discretisation, Discr_inst, VEFPreP1B, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 172 of file Discretisation_base.cpp.
{
  test_demande_description(directive, champ.que_suis_je());
// Appel recursif pour produire l'affichage des directives :
  if (directive==demande_description)
    {
      exit();
      throw;
    }
  discretiser_champ(demande_description, z, nature, noms, unites, nb_comp,
                    temps, champ);
}
References demande_description, discretiser_champ(), Process::exit(), Objet_U::que_suis_je(), and test_demande_description().
discretiser_champ() [5/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const virtual
idem
Reimplemented in EF_discretisation, Discr_inst, VEFPreP1B, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 153 of file Discretisation_base.cpp.
{
  test_demande_description(directive, champ.que_suis_je());
// Appel recursif pour produire l'affichage des directives :
  if (directive==demande_description)
    {
      exit();
      throw;
    }
  discretiser_champ(demande_description, z, nature, noms, unites, nb_comp,
                    temps, champ);
}
References demande_description, discretiser_champ(), Process::exit(), Objet_U::que_suis_je(), and test_demande_description().
discretiser_champ() [6/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const virtual
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
Reimplemented in EF_discretisation, Discr_inst, VEFPreP1B, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
Definition at line 134 of file Discretisation_base.cpp.
{
  test_demande_description(directive, champ.que_suis_je());
// Appel recursif pour produire l'affichage des directives :
  if (directive==demande_description)
    {
      exit();
      throw;
    }
  discretiser_champ(demande_description, z, nature, noms, unites, nb_comp,
                    nb_pas_dt, temps, champ, sous_type);
}
References demande_description, discretiser_champ(), Process::exit(), Objet_U::que_suis_je(), and test_demande_description().
discretiser_variables()
void Discretisation_base::discretiser_variables () const virtual
Definition at line 189 of file Discretisation_base.cpp.
{
  Cerr << "Discretisation_base::discretiser_variables() does nothing" << finl;
  Cerr << "and must be overloaded " << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
discretiser_Zone_Cl_dis()
void Discretisation_base::discretiser_Zone_Cl_dis (const Zone_dis & , Zone_Cl_dis &) const virtual
Definition at line 196 of file Discretisation_base.cpp.
{
  Cerr << "Discretisation_base::discretiser_Zone_Cl_dis does nothing" << finl;
  Cerr << "and must be overloaded " << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
get_info()
const Type_info * Discretisation_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Discr_inst, VEFPreP1B, PolyMAC_discretisation, PolyMAC_P0_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 26 of file Discretisation_base.cpp.
get_name_of_type_for()
Nom Discretisation_base::get_name_of_type_for (const Nom & class_operateur, const Nom & type_operteur, const Equation_base & eqn, const Ref_Champ_base & champ_supp = Ref_Champ_base ()) const virtual
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Reimplemented in EF_discretisation, and PolyMAC_discretisation.
Definition at line 387 of file Discretisation_base.cpp.
{
  Nom type;
  if (class_operateur=="Source")
    {
      type = type_operateur;
      Nom disc = eqn.discretisation().que_suis_je();
      int isQC=eqn.probleme().is_dilatable();
      if ((isQC) && ((eqn.que_suis_je()!="Transport_K_Eps")
                     && (eqn.que_suis_je()!="Transport_K_Eps_Bas_Reynolds")
                     && (eqn.que_suis_je()!="Transport_K_Eps_Realisable")
                     && (eqn.que_suis_je()!="Transport_K_Eps_V2")))
        type+="_QC";
// sauf pour le term boussinesq
      if( disc=="VEFPreP1B" )
        {
          if ( (Motcle(type_operateur) == "boussinesq_temperature") || (Motcle(type_operateur) == "boussinesq_concentration") || (Motcle(type_operateur) == "boussinesq") )
            {
              disc="VEFPreP1B" ;
            }
          else
            {
              disc="VEF";
            }
        }
      Nom champ = (eqn.inconnue()->que_suis_je());
      if (champ == "Champ_Q1NC")
        champ = "Champ_P1NC";
      champ.suffix("Champ_");
      type+="_";
      type+=disc;
      {
        type+="_";
        type+=champ;
      }
      return type;
    }
  else if (class_operateur=="Solveur_Masse")
    {
      type="Masse_";
      Nom discr=eqn.discretisation().que_suis_je();
// le Solveur est commun aux discretisations VEF et VEFP1B
      if(discr=="VEFPreP1B" )
        discr="VEF";
      type+=discr;
      Nom type_ch=eqn.inconnue()->que_suis_je();
      if (type_ch == "Champ_Q1NC")
        type_ch = "Champ_P1NC";
      if (type_ch.debute_par("Champ_P0_VDF"))
        type_ch = "Champ_P0_VDF";
      if (type_ch.debute_par("Champ_Face"))
        type_ch = "Champ_Face";
      type_ch.suffix("Champ");
      type+=type_ch;
    }
  else if (class_operateur=="Operateur_Grad")
    {
      type="Op_Grad_";
      Nom type_pb = eqn.probleme().que_suis_je();
      if (type_pb=="Probleme_SG")
        {
          type+=(type_pb.suffix("Probleme_"));
          type+="_";
        }
      Nom discr=eqn.discretisation().que_suis_je();
      type+=discr;
      type+="_";
      Nom type_inco=eqn.inconnue()->que_suis_je();
      if (type_inco == "Champ_Q1NC")
        type_inco = "Champ_P1NC";
      type+=(type_inco.suffix("Champ_"));
// Test pour appliquer un gradient a un Champ_P1NC a une composante en VEF
// Typage a revoir (revison des operateurs)
      if ((eqn.inconnue()->le_nom()!="vitesse") && (eqn.inconnue()->que_suis_je()=="Champ_P1NC"))
        type="Op_Grad_P1NC_to_P0";
// Test pour appliquer un gradient a un Champ_P0 a une composante en VDF
// Typage a revoir (revison des operateurs)
      if ((eqn.inconnue()->le_nom()!="vitesse") && (eqn.inconnue()->que_suis_je()=="Champ_P0_VDF"))
        type="Op_Grad_P0_to_Face";
      return type;
    }
  else if (class_operateur=="Operateur_Div")
    {
      type="Op_Div_";
      Nom discr=eqn.discretisation().que_suis_je();
      Nom type_inco=eqn.inconnue()->que_suis_je();
      type+=discr;
      type+="_";
      if (type_inco == "Champ_Q1NC")
        type_inco = "Champ_P1NC";
      type+=(type_inco.suffix("Champ_"));
    }
  else if (class_operateur=="Operateur_Diff")
    {
      Nom typ(type_operateur);
      if (typ=="standard") typ="";
      Cerr << "We treat the diffusive operator of : "
           << eqn.que_suis_je() << finl;
      type="Op_Diff_";
// const Discretisation_base& discr=eqn.discretisation();
      Nom nom_discr=que_suis_je();
      Cerr << "The discretization used is : "
           << nom_discr << finl;
      assert(champ_sup.non_nul());
      const Champ_base& diffusivite=champ_sup.valeur();
// Typage en fonction de la discretisation
// les operateurs de diffusion sont communs aux discretisations VEF et VEFP1B
      if(nom_discr=="VEFPreP1B")
        nom_discr="VEF";
      type+=nom_discr;
      type+=typ;
// MODIF ELI LAUCOIN (10/12/2007) :
// Je conserve le comportement normal pour le VEF et le VDF
      if ( (nom_discr == "VDF") || (nom_discr == "VEF") )
        {
          Nom nb_inc;
// Modif Elie Saikali (Nov 2020)
          if (diffusivite.nb_comp() == 1 && nom_discr=="VDF")
            nb_inc = "_";
          else if (diffusivite.nb_comp() > 1 && diffusivite.le_nom() == "conductivite")
            nb_inc = "ANISOTROPE_";
          else
            {
              if (nom_discr=="VEF")
                nb_inc = "_";
              else
                nb_inc = "_Multi_inco_";
            }
          type+= nb_inc ;
          Nom type_diff;
          if(sub_type(Champ_Uniforme,diffusivite))
            type_diff="const_";
          else
            type_diff="var_";
          type+= type_diff;
        }
      else
        {
// par contre, je modifie le cas general pour
// eviter de rajouter des cas particuliers
          type += "_";
        }
      Nom type_inco=eqn.inconnue()->que_suis_je();
      type+=(type_inco.suffix("Champ_"));
      if (axi == 1)
        {
          type += "_Axi";
        }
      return type;
    }
  else if (class_operateur=="Operateur_Conv")
    {
      if (Motcle(type_operateur)==Motcle("ALE"))
        {
          type="Op_Conv_";
          type+=type_operateur;
          Nom tiret="_";
          type+= tiret;
          Nom discr=que_suis_je();
          if(discr=="VEFPreP1B")
            discr="VEF";
          type+=discr;
          return type;
        }
      else
        {
          type="Op_Conv_";
          type+=type_operateur;
          Nom tiret="_";
          type+= tiret;
          Nom discr=que_suis_je();
// les operateurs de diffusion sont communs aux discretisations VEF et VEFP1B
          if(discr=="VEFPreP1B" )
            discr="VEF";
          type+=discr;
          if (type_operateur!="KEps_Comp")
            {
              type+= tiret;
              Nom type_inco=eqn.inconnue()->que_suis_je();
              if (type_inco == "Champ_Q1NC")
                type_inco = "Champ_P1NC";
              if (type_inco.debute_par("Champ_P0_VDF"))
                type_inco = "Champ_P0_VDF";
              if (type_inco.debute_par("Champ_Face"))
                type_inco = "Champ_Face";
              type+=(type_inco.suffix("Champ_"));
              if (axi == 1)
                {
                  if(  type_operateur== "quick" )
                    type += "_Axi";
                }
            }
        }
    }
  else
    {
      Cerr<<class_operateur<< " not understood in get_name_of_type_for of  "<<que_suis_je()<<finl;
      Cerr<<__FILE__<<" "<<(int)__LINE__<<finl;
      Process::exit();
    }
  return type;
}
References Objet_U::axi, Cerr, Nom::debute_par(), Equation_base::discretisation(), Process::exit(), finl, Equation_base::inconnue(), Probleme_base::is_dilatable(), Field_base::le_nom(), O_U_Ptr::le_nom(), Field_base::nb_comp(), Equation_base::probleme(), Objet_U::que_suis_je(), sub_type, and Nom::suffix().
Referenced by EF_discretisation::get_name_of_type_for(), PolyMAC_discretisation::get_name_of_type_for(), Solveur_Masse::typer(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), Operateur_Grad::typer(), Operateur_Evanescence::typer(), and Source::typer().
info()
const Type_info * Discretisation_base::info () static
Definition at line 26 of file Discretisation_base.cpp.
modifier_champ_tabule()
void Discretisation_base::modifier_champ_tabule (const Zone_dis_base & zone_dis, Champ_Fonc_Tabule & ch_tab, const Vect_Ref_Champ_base & ch_inc) const private virtual
Reimplemented in VDF_discretisation, VEF_discretisation, EF_discretisation, Discr_inst, and PolyMAC_discretisation.
Definition at line 347 of file Discretisation_base.cpp.
{
  Cerr<<que_suis_je()<<" must overload Discretisation_base::modifier_champ_tabule"<<finl;
  Cerr<<__FILE__<<(int)__LINE__<<" uncoded"<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by nommer_completer_champ_physique().
nommer_completer_champ_physique()
void Discretisation_base::nommer_completer_champ_physique (const Zone_dis_base & zone_vdf, const Nom & nom_champ, const Nom & unite, Champ_base & champ, const Probleme_base & pbi) const
Definition at line 355 of file Discretisation_base.cpp.
{
// on nomme le champ et l'unite
  le_champ.nommer(nom_champ);
  le_champ.fixer_unite(unite);
  if (sub_type(Champ_Fonc_Tabule,le_champ))
    {
      Noms& noms_variables = ref_cast(Champ_Fonc_Tabule, le_champ).noms_champs_parametre();
      Noms& noms_pbs = ref_cast(Champ_Fonc_Tabule, le_champ).noms_problemes();
      VECT(REF(Champ_base)) les_ch_eq;
      for (int i = 0; i < noms_variables.size(); i++)
        {
          REF(Champ_base) champ;
          const Probleme_base& pb_ch = noms_pbs.size() == 0 ? pb : ref_cast(Probleme_base, Interprete::objet(noms_pbs[i]));
          champ = pb_ch.get_champ(Motcle(noms_variables[i]));
          les_ch_eq.add(champ);
        }
      modifier_champ_tabule(zone_dis,ref_cast(Champ_Fonc_Tabule,le_champ), les_ch_eq);
    }
}
References Field_base::fixer_unite(), Probleme_base::get_champ(), modifier_champ_tabule(), Field_base::nommer(), Interprete::objet(), REF, ref_cast, vect_impl::size(), sub_type, and VECT.
Referenced by Puissance_Thermique_EF::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Milieu_base::discretiser(), Constituant::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Terme_Puissance_Thermique::lire_donnees(), and Source_Scalaire_EF::readOn().
printOn()
Sortie & Discretisation_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Discr_inst, VEFPreP1B, PolyMAC_discretisation, PolyMAC_P0_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 37 of file Discretisation_base.cpp.
{
  return os;
}
readOn()
Entree & Discretisation_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Discr_inst, VEFPreP1B, PolyMAC_discretisation, PolyMAC_P0_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 42 of file Discretisation_base.cpp.
{
  return is;
}
residu()
void Discretisation_base::residu (const Zone_dis & , const Champ_Inc & , Champ_Fonc &) const virtual
Reimplemented in VDF_discretisation, VEF_discretisation, and PolyMAC_discretisation.
Definition at line 340 of file Discretisation_base.cpp.
{
  Cerr << "\nDiscret_Thyd::residu() does nothing" << finl;
  Cerr <<  que_suis_je() << " needs to overload it !" << finl;
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Equation_base::creer_champ().
self_cast() [1/2]
const Discretisation_base & Discretisation_base::self_cast (const Objet_U & r) static
Definition at line 26 of file Discretisation_base.cpp.
self_cast() [2/2]
Discretisation_base & Discretisation_base::self_cast (Objet_U & r) static
Definition at line 26 of file Discretisation_base.cpp.
test_demande_description()
void Discretisation_base::test_demande_description (const Motcle & directive, const Nom & type_objet) const private
Cette fonction est un outil pour les trois methodes suivantes...
Definition at line 107 of file Discretisation_base.cpp.
{
  if (directive == Discretisation_base::demande_description)
    {
      Cerr << "Discr_base : none directive understood" << finl;
// On a fait le tour, les descendants on ecrit toutes les directives
// comprises, on s'arrete.
      assert(0);
      exit();
    }
// Si on arrive ici, c'est qu'aucun descendant de la methode n'a compris
// la directive, on provoque l'affichage des directives comprises :
  Cerr << "\nError in Discr_base::discretiser_(..., ";
  Cerr << type_objet << ")\n";
  Cerr << " The discretization " << que_suis_je();
  Cerr << " does not understood the following directive :\n  " << directive;
  Cerr << "\n The understood directives are :\n";
}
References Cerr, demande_description, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by discretiser_champ().
verifie_sous_type()
int Discretisation_base::verifie_sous_type (Nom & type, const Nom & sous_type, const Motcle & directive) const
Definition at line 642 of file Discretisation_base.cpp.
{
  const Type_info * base_info = Type_info::type_info_from_name(sous_type);
  if (base_info)
    {
      if (base_info->has_base(type))
        {
          type = sous_type;
          return 0;
        }
      Cerr << "Error in " << que_suis_je() << " ::discretiser_champ" << finl;
      Cerr << sous_type << " is not a sub type of " << type << " for " << que_suis_je() << " discretization";
      Cerr << "( directive : \""<< directive << "\")"<<finl;
      Process::exit();
    }
  else
    {
      Cerr << "Error in " << que_suis_je() << "::discretiser_champ" << finl;
      Cerr << "Unknown class type " << sous_type << finl;
      Process::exit();
    }
  return -1;
}
References Cerr, Process::exit(), finl, Type_info::has_base(), Objet_U::que_suis_je(), and Type_info::type_info_from_name().
Referenced by PolyMAC_discretisation::discretiser_champ(), and VDF_discretisation::discretiser_champ().
volume_maille()
void Discretisation_base::volume_maille (const Schema_Temps_base & sch, const Zone_dis & z, Champ_Fonc & ch) const
Definition at line 327 of file Discretisation_base.cpp.
{
  Cerr << "Discretization of the field 'volume of meshes'" << finl;
  const Zone_VF& zone_VF=ref_cast(Zone_VF, z.valeur());
  discretiser_champ("champ_elem",zone_VF,"volume_maille","m3",1,sch.temps_courant(),ch);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,ch.valeur());
  DoubleVect& tab=ch_fonc.valeurs();
  tab = zone_VF.volumes();
}
References Cerr, discretiser_champ(), finl, ref_cast, Schema_Temps_base::temps_courant(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
Referenced by Equation_base::creer_champ().
zone_Cl_dis()
virtual void Discretisation_base::zone_Cl_dis (Zone_dis & , Zone_Cl_dis &) const pure virtual
Implemented in Discr_inst, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
Referenced by Equation_base::discretiser().
Member Data Documentation
demande_description
const Motcle Discretisation_base::demande_description = Motcle("demande_description") static protected
Definition at line 158 of file Discretisation_base.h.
Referenced by discretiser_champ(), EF_discretisation::discretiser_champ(), VEFPreP1B::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), VEFPreP1B::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), Discr_inst::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), and test_demande_description().
info_obj
const Type_info Discretisation_base::info_obj static
Definition at line 54 of file Discretisation_base.h.
nom_vide
const Nom Discretisation_base::nom_vide = Nom("-") static protected
Definition at line 159 of file Discretisation_base.h.
Referenced by PolyMAC_discretisation::discretiser_champ(), and VDF_discretisation::discretiser_champ().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Discretisation_base.h
src/Kernel/Framework/Discretisation_base.cpp