TRUST: Champ_Don_Fonc_txyz Class Reference
Champ_Don_Fonc_txyz Class Reference
class Champ_Don_Fonc_txyz
Cette classe represente un champ de donnees fonction
des variables d'espaces x,y,z et du temps. La fonction est fournie
directement dans le jeu de donnees sous la forme d'une expression
mathematique contenant les variables x,y,z (en minuscules)
.......................
#include <Champ_Don_Fonc_txyz.h>
Public Member Functions
Champ_Don_Fonc_txyz ()
~Champ_Don_Fonc_txyz ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void mettre_a_jour (double)
NE FAIT RIEN
Mise a jour en temps.
Champ_base & affecter (const Champ_base &ch)
Provoque une erreur: cela n'a pas de sens
de vouloir effectuer une affectation avec un Champ_Don_Fonc_txyz.
virtual Champ_base & affecter_ (const Champ_base &)
Provoque une erreur !
A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Renvoie la valeur du champ au point specifie
par ses coordonnees.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Don_Fonc_txyz & self_cast (Objet_U &)
static const Champ_Don_Fonc_txyz & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le champ sur un flot d'entree.
Protected Attributes
Ref_Domaine mon_domaine
Detailed Description
class Champ_Don_Fonc_txyz
Cette classe represente un champ de donnees fonction
des variables d'espaces x,y,z et du temps. La fonction est fournie
directement dans le jeu de donnees sous la forme d'une expression
mathematique contenant les variables x,y,z (en minuscules)
.......................
Definition at line 42 of file Champ_Don_Fonc_txyz.h.
Constructor & Destructor Documentation
Champ_Don_Fonc_txyz::Champ_Don_Fonc_txyz ()
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
Champ_Don_Fonc_txyz::~Champ_Don_Fonc_txyz ()
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
Member Function Documentation
Champ_base & Champ_Don_Fonc_txyz::affecter (const Champ_base & ch)
Provoque une erreur: cela n'a pas de sens
de vouloir effectuer une affectation avec un Champ_Don_Fonc_txyz.
Returns:
Champ_base&
Signification:
Contraintes:
Reimplemented from Champ_base.
Definition at line 212 of file Champ_Don_Fonc_txyz.cpp.
References Champ_base::affecter_erreur().
{
  Champ_base::affecter_erreur();
  return *this;
}
Champ_base & Champ_Don_Fonc_txyz::affecter_ (const Champ_base &) [virtual]
Provoque une erreur !
A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Returns:
Champ_base&
Signification:
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 218 of file Champ_Don_Fonc_txyz.cpp.
References sub_type, Champ_Proto::valeurs(), and Champ_Don_base::valeurs().
{
  if(sub_type(Champ_Uniforme, ch))
    valeurs()=ch.valeurs()(0,0);
  else
    valeurs()=ch.valeurs();
  return *this;
}
Objet_U * Champ_Don_Fonc_txyz::cree_instance () [static]
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
int Champ_Don_Fonc_txyz::duplique () const [virtual]
Implements Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
const Type_info * Champ_Don_Fonc_txyz::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
const Type_info * Champ_Don_Fonc_txyz::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
void Champ_Don_Fonc_txyz::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
Mise a jour en temps.
Reimplemented from Champ_Don_base.
Definition at line 158 of file Champ_Don_Fonc_txyz.cpp.
References Champ_base::changer_temps(), Domaine::coord(), IntTab::dimension(), Objet_U::dimension, DoubleVect::echange_espace_virtuel(), Parser_Eval::eval_fct(), Zone::les_elems(), mon_domaine, Zone::nb_elem(), Champ_base::temps(), Ref_Domaine::valeur(), Champ_Don_base::valeurs(), and Domaine::zone().
Referenced by readOn().
{
  changer_temps(t);
  Domaine& domaine=mon_domaine.valeur();
  const Zone& ma_zone = domaine.zone(0);
  const IntTab& les_Polys = ma_zone.les_elems();
  int nb_elems = ma_zone.nb_elem();
  DoubleTab& mes_val = valeurs();
  int num_elem;
  double x,y,z;
  DoubleTab positions(nb_elems,dimension);
  double tps=temps();
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
      x=y=z=0;
      int nb_som = 0;
      for(int s = 0, num_som; s < les_Polys.dimension(1); s++)
        if ((num_som = les_Polys(num_elem,s)) >= 0)
          {
            nb_som++;
            x += domaine.coord(num_som,0);
            y += domaine.coord(num_som,1);
            if (dimension >2 ) z += domaine.coord(num_som,2);
          }
      positions(num_elem,0) = x/nb_som;
      positions(num_elem,1) = y/nb_som;
      if (dimension>2)
        positions(num_elem,2) = z/nb_som;
    }
  eval_fct(positions,tps,mes_val);
  mes_val.echange_espace_virtuel();
}
Sortie & Champ_Don_Fonc_txyz::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 44 of file Champ_Don_Fonc_txyz.cpp.
References DoubleVect::size(), and Champ_Don_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_Don_Fonc_txyz::readOn (Entree & is) [protected, virtual]
Lit le champ sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 69 of file Champ_Don_Fonc_txyz.cpp.
References Cerr, Domaine::creer_tableau_elements(), Champ_Don_base::dimensionner(), finl, Field_base::fixer_nb_comp(), Parser_Eval::fonction(), Champ_Proto::lire_dimension(), mettre_a_jour(), mon_domaine, Zone::nb_elem(), Interprete::objet(), Objet_U::que_suis_je(), ref_cast, Champ_base::temps(), Ref_Domaine::valeur(), Champ_Don_base::valeurs(), VECT, and Domaine::zone().
{
  Nom motlu;
  double t0 = 0.;
  double T= 1;
  int dim;
  dim=-1;
  Nom nom_dom;
  is >> motlu;
  if (motlu == "impulsion_t0")
    {
      is >> t0 ;
      is >> motlu;
      if (motlu == "impulsion_perio")
        {
          is >> T;
          is >> nom_dom;
          dim=lire_dimension(is,que_suis_je());
        }
      else
        {
          nom_dom = motlu;
          dim=lire_dimension(is,que_suis_je());
        }
    }
  else if (motlu == "impulsion_perio")
    {
      is >> T ;
      is >> motlu;
      if (motlu == "impulsion_t0")
        {
          is >> t0;
          is >> nom_dom;
          dim=lire_dimension(is,que_suis_je());
        }
      else
        {
          nom_dom = motlu;
// dim = strtol(motlu.getChar(), (char **)NULL, 10);
          dim=lire_dimension(is,que_suis_je());
        }
    }
  else
    {
      nom_dom = motlu;
      dim=lire_dimension(is,que_suis_je());
    }
  fixer_nb_comp(dim);
  VECT(Parser_U)& fxyz = fonction();
  fxyz.dimensionner(dim);
  for (int i=0; i<dim; i++)
    {
      Nom tmp;
      is >> tmp;
      Cerr << "Reading and interpretation of the function " << tmp << finl;
      fxyz[i].setNbVar(4);
      fxyz[i].setString(tmp);
      fxyz[i].addVar("t");
      fxyz[i].addVar("x");
      fxyz[i].addVar("y");
      fxyz[i].addVar("z");
      fxyz[i].setImpulsion(t0,T);
      fxyz[i].parseString();
      Cerr << "Interpretation of function " << tmp << " Ok" << finl;
    }
  /*
   * On remplit le tableau des valeurs aux elements
   *
   */
  {
    mon_domaine = ref_cast(Domaine, Interprete::objet(nom_dom));
    Domaine& domaine=mon_domaine.valeur();
    const Zone& ma_zone = domaine.zone(0);
    int nb_elems = ma_zone.nb_elem();
    DoubleTab& mes_val = valeurs();
    double tps = temps();
    dimensionner(nb_elems, dim);
    domaine.creer_tableau_elements(mes_val);
    mettre_a_jour(tps);
  }
  return is;
}
Champ_Don_Fonc_txyz & Champ_Don_Fonc_txyz::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
const Champ_Don_Fonc_txyz & Champ_Don_Fonc_txyz::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
unsigned Champ_Don_Fonc_txyz::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Champ_Don_Fonc_txyz.cpp.
DoubleVect & Champ_Don_Fonc_txyz::valeur_a (const DoubleVect & x, DoubleVect & val) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 248 of file Champ_Don_Fonc_txyz.cpp.
References Cerr, Parser_Eval::eval_fct(), Process::exit(), finl, Field_base::nb_compo_, DoubleVect::size(), and Champ_base::temps().
Referenced by valeur_a_elem().
{
  if (val.size() != nb_compo_)
    {
      Cerr << "Error TRUST in Champ_Don_Fonc_txyz::valeur_a()" << finl;
      Cerr << "The DoubleVect val doesn't have the correct size" << finl;
      exit();
    }
  eval_fct(x,temps(),val);
  return val;
}
DoubleVect & Champ_Don_Fonc_txyz::valeur_a_elem (const DoubleVect & x, DoubleVect & val, int le_poly) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 288 of file Champ_Don_Fonc_txyz.cpp.
References valeur_a().
{
  return valeur_a(x,val);
}
double Champ_Don_Fonc_txyz::valeur_a_elem_compo (const DoubleVect & x, int le_poly, int ncomp) const [virtual]
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
double
Signification: la valeur de la composante du champ specifiee au
point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 325 of file Champ_Don_Fonc_txyz.cpp.
References Objet_U::dimension, Parser_Eval::eval_fct(), and Champ_base::temps().
{
  double val;
  DoubleTab positions(1,dimension);
  DoubleVect val_fct(1);
  double tps = temps();
  positions(0,0) = x(0);
  positions(0,1) = x(1);
  if (dimension>2)
    positions(0,2) = x(2);
  eval_fct(positions,tps,val_fct,ncomp);
  val = val_fct(0);
  return val;
}
DoubleTab & Champ_Don_Fonc_txyz::valeur_aux (const DoubleTab & x, DoubleTab & val) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 365 of file Champ_Don_Fonc_txyz.cpp.
References Cerr, DoubleTab::dimension(), Parser_Eval::eval_fct(), Process::exit(), finl, Field_base::nb_compo_, DoubleTab::nb_dim(), and Champ_base::temps().
Referenced by valeur_aux_elems().
{
  if (val.nb_dim() == 1)
    {
      assert(nb_compo_ == 1);
    }
  else if (val.nb_dim() == 2)
    {
      assert(val.dimension(1) == nb_compo_);
    }
  else
    {
      Cerr << "Error TRUST in Champ_Don_Fonc_txyz::valeur_aux_elems()" << finl;
      Cerr << "The DoubleTab val has more than 2 entries" << finl;
      exit();
    }
  eval_fct(x,temps(),val);
  return val;
}
DoubleVect & Champ_Don_Fonc_txyz::valeur_aux_compo (const DoubleTab & x, DoubleVect & val, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 414 of file Champ_Don_Fonc_txyz.cpp.
References Parser_Eval::eval_fct(), and Champ_base::temps().
Referenced by valeur_aux_elems_compo().
{
  eval_fct(x,temps(),val,ncomp);
  return val;
}
DoubleTab & Champ_Don_Fonc_txyz::valeur_aux_elems (const DoubleTab & x, const IntVect & les_polys, DoubleTab & val) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 453 of file Champ_Don_Fonc_txyz.cpp.
References valeur_aux().
{
  return valeur_aux(x,val);
}
DoubleVect & Champ_Don_Fonc_txyz::valeur_aux_elems_compo (const DoubleTab & x, const IntVect & les_polys, DoubleVect & val, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 495 of file Champ_Don_Fonc_txyz.cpp.
References valeur_aux_compo().
{
  return valeur_aux_compo(x,val,ncomp);
}
Member Data Documentation
const Type_info Champ_Don_Fonc_txyz::info_obj [static]
Reimplemented from Champ_Don_base.
Definition at line 45 of file Champ_Don_Fonc_txyz.h.
Ref_Domaine Champ_Don_Fonc_txyz::mon_domaine [protected]
Definition at line 81 of file Champ_Don_Fonc_txyz.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Don_Fonc_txyz.h
src/Kernel/Champs/Champ_Don_Fonc_txyz.cpp