TRUST: MD_Vector_base Class Reference
MD_Vector_base Class Reference abstract
Classe de base des descripteurs de vecteurs distribues.
Voir la documentation des methodes dans MD_Vector_base2 et MD_Vector_std.
#include <MD_Vector_base.h>
Public Member Functions
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_base ()
MD_Vector_base (const MD_Vector_base &)
~MD_Vector_base () override
virtual int get_nb_items_reels () const =0
virtual int get_nb_items_tot () const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual const ArrOfInt & get_items_to_compute () const =0
virtual const ArrOfInt & get_items_to_sum () const =0
virtual int nb_items_seq_tot () const =0
virtual int nb_items_seq_local () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static MD_Vector_base & self_cast (Objet_U &)
static const MD_Vector_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
int ref_count_
Friends
class MD_Vector
Detailed Description
Classe de base des descripteurs de vecteurs distribues.
Voir la documentation des methodes dans MD_Vector_base2 et MD_Vector_std.
Definition at line 29 of file MD_Vector_base.h.
Constructor & Destructor Documentation
MD_Vector_base() [1/2]
MD_Vector_base::MD_Vector_base () inline
Definition at line 33 of file MD_Vector_base.h.
: ref_count_(0) {};
MD_Vector_base() [2/2]
MD_Vector_base::MD_Vector_base (const MD_Vector_base &) inline
Definition at line 35 of file MD_Vector_base.h.
: Objet_U(), ref_count_(0) {};
~MD_Vector_base()
MD_Vector_base::~MD_Vector_base () inline override
Definition at line 36 of file MD_Vector_base.h.
{ }
Member Function Documentation
get_info()
const Type_info * MD_Vector_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in MD_Vector_base2, MD_Vector_composite, and MD_Vector_std.
Definition at line 21 of file MD_Vector.cpp.
get_items_to_compute()
virtual const ArrOfInt & MD_Vector_base::get_items_to_compute () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part(), ajoute_operation_speciale_generic(), ajoute_produit_scalaire(), TRUSTTab< _TYPE_ >::ajoute_produit_tensoriel(), invalidate_data(), local_extrema_vect_generic(), local_max_abs_tab(), local_operations_vect_bis_generic(), local_prodscal(), operation_speciale_tres_generic(), operator_vect_single_generic(), operator_vect_vect_generic(), and remplir_items_non_calcules_().
get_items_to_sum()
virtual const ArrOfInt & MD_Vector_base::get_items_to_sum () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part(), ajoute_operation_speciale_generic(), ajoute_produit_scalaire(), invalidate_data(), local_carre_norme_tab(), local_extrema_vect_generic(), local_operations_vect_bis_generic(), local_prodscal(), operation_speciale_tres_generic(), operator_vect_single_generic(), and operator_vect_vect_generic().
get_nb_items_reels()
virtual int MD_Vector_base::get_nb_items_reels () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part(), Scatter::construire_espace_virtuel_traduction(), creer_tableau_distribue_(), SSOR::prepare_(), Solv_GCP::prepare_data(), TRUSTVect< _TYPE_ >::set_md_vector(), and TRUSTTab< _TYPE_ >::set_md_vector().
get_nb_items_tot()
virtual int MD_Vector_base::get_nb_items_tot () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part(), Scatter::construire_espace_virtuel_traduction(), creer_tableau_distribue_(), MD_Vector_tools::extend(), get_seq_flags(), MD_Vector_tools::get_sequential_items_flags(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), init_parts(), Traduction_Indice_Global_Local::initialiser(), Zone_VF::nb_faces_bord_tot(), Solv_GCP::prepare_data(), and TRUSTVect< _TYPE_ >::set_md_vector().
info()
const Type_info * MD_Vector_base::info () static
Definition at line 21 of file MD_Vector.cpp.
initialize_comm() [1/2]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
Referenced by echange_espace_virtuel_().
initialize_comm() [2/2]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
nb_items_seq_local()
virtual int MD_Vector_base::nb_items_seq_local () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part().
nb_items_seq_tot()
virtual int MD_Vector_base::nb_items_seq_tot () const pure virtual
Implemented in MD_Vector_base2.
Referenced by MD_Vector_composite::add_part(), Traitement_particulier_NS_THI_new::calcul_nb_som_dir(), Zone_VEF_PreP1b::construire_ok_arete(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Debog_Pb::ecrire_gen(), EcritureLectureSpecial::ecriture_special(), Zone_VF::info_elem_som(), EcritureLectureSpecial::lecture_special(), mp_moyenne_vect(), Solv_GCP::resoudre_(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_matrice(), and Debog_Pb::verifier_partie().
prepare_send_data() [1/2]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
Referenced by echange_espace_virtuel_().
prepare_send_data() [2/2]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
printOn()
Sortie & MD_Vector_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in MD_Vector_base2, MD_Vector_composite, and MD_Vector_std.
Definition at line 19 of file MD_Vector_base.cpp.
{ return os; }
process_recv_data() [1/2]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
Referenced by echange_espace_virtuel_().
process_recv_data() [2/2]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_std.
readOn()
Entree & MD_Vector_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in MD_Vector_base2, MD_Vector_composite, and MD_Vector_std.
Definition at line 18 of file MD_Vector_base.cpp.
{ return is; }
self_cast() [1/2]
const MD_Vector_base & MD_Vector_base::self_cast (const Objet_U & r) static
Definition at line 21 of file MD_Vector.cpp.
self_cast() [2/2]
MD_Vector_base & MD_Vector_base::self_cast (Objet_U & r) static
Definition at line 21 of file MD_Vector.cpp.
Friends And Related Function Documentation
MD_Vector
friend class MD_Vector friend
Definition at line 53 of file MD_Vector_base.h.
Referenced by MD_Vector_composite::readOn().
Member Data Documentation
info_obj
const Type_info MD_Vector_base::info_obj static
Definition at line 31 of file MD_Vector_base.h.
ref_count_
int MD_Vector_base::ref_count_ mutable private
Definition at line 55 of file MD_Vector_base.h.
Referenced by MD_Vector::attach_(), MD_Vector::copy(), and MD_Vector::detach_().
The documentation for this class was generated from the following files:
src/Kernel/Math/MD_Vector_base.h
src/Kernel/Math/MD_Vector.cpp
src/Kernel/Math/MD_Vector_base.cpp