TRUST: Elem_CoviMAC Class Reference
Elem_CoviMAC Class Reference
#include <Elem_CoviMAC.h>
Public Member Functions
Elem_CoviMAC ()
~Elem_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Elem_CoviMAC & operator= (const Elem_CoviMAC_base &)
void typer (Nom)
determination du type
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_CoviMAC & self_cast (Objet_U &)
static const Elem_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 42 of file Elem_CoviMAC.h.
Constructor & Destructor Documentation
Elem_CoviMAC::Elem_CoviMAC ()
Definition at line 30 of file Elem_CoviMAC.cpp.
Elem_CoviMAC::~Elem_CoviMAC ()
Definition at line 30 of file Elem_CoviMAC.cpp.
Member Function Documentation
Objet_U * Elem_CoviMAC::cree_instance () [static]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
int Elem_CoviMAC::duplique () const [virtual]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
const Type_info * Elem_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
const Type_info * Elem_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
void Elem_CoviMAC::normale (int num_face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [inline]
Definition at line 69 of file Elem_CoviMAC.h.
References Elem_CoviMAC_base::normale(), and Deriv_Elem_CoviMAC_base::valeur().
Referenced by Zone_CoviMAC::discretiser().
{
  valeur().normale(num_face,Face_normales,Face_sommets,Face_voisins,
                   elem_faces,zone_geom);
}
Elem_CoviMAC & Elem_CoviMAC::operator= (const Elem_CoviMAC_base & elem_base) [inline]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 61 of file Elem_CoviMAC.h.
References DERIV.
{
  DERIV(Elem_CoviMAC_base)::operator=(elem_base);
  return *this;
}
Sortie & Elem_CoviMAC::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 36 of file Elem_CoviMAC.cpp.
References Deriv_Elem_CoviMAC_base::valeur().
{
  return s << valeur() ;
}
Entree & Elem_CoviMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 41 of file Elem_CoviMAC.cpp.
References Cerr, Process::exit(), and finl.
{
  Nom type;
  s >> type;
  if(type == "Tri_CoviMAC")
    *this =  Tri_CoviMAC();
  else if(type == "Tetra_CoviMAC")
    *this =  Tetra_CoviMAC();
  else if(type == "Quadri_CoviMAC")
    *this =  Quadri_CoviMAC();
  else if(type == "Hexa_CoviMAC")
    *this =  Hexa_CoviMAC();
  else
    {
      Cerr << type << " n'est pas un Elem_CoviMAC" << finl;
      exit();
    }
  return s ;
}
const Elem_CoviMAC & Elem_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
Elem_CoviMAC & Elem_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
unsigned Elem_CoviMAC::taille_memoire () const [virtual]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 30 of file Elem_CoviMAC.cpp.
void Elem_CoviMAC::typer (Nom type_elem_geom)
determination du type
Definition at line 63 of file Elem_CoviMAC.cpp.
References Cerr, DERIV, Process::exit(), finl, Objet_U::que_suis_je(), and Deriv_Elem_CoviMAC_base::valeur().
Referenced by Zone_CoviMAC::typer_elem().
{
  Cerr << "Elem_CoviMAC::typer()" << finl ;
  Cerr << "type geometrique : " << type_elem_geom << finl;
  Nom type;
  if(type_elem_geom=="Triangle")
    type="Tri_CoviMAC";
  else if(type_elem_geom=="Tetraedre")
    type="Tetra_CoviMAC";
  else if(type_elem_geom=="Quadrangle")
    type="Quadri_CoviMAC";
  else if(type_elem_geom=="Hexaedre_VEF")
    type="Hexa_CoviMAC";
  else if(type_elem_geom=="Segment")
    type="Segment_CoviMAC";
  else if(type_elem_geom=="Polygone")
    type="Polygone_CoviMAC";
  else if(type_elem_geom=="Polyedre")
    type="Polyedre_CoviMAC";
  else
    {
      Cerr << "probleme de typage dans Elem_CoviMAC::typer" << finl;
      exit();
    }
  DERIV(Elem_CoviMAC_base)::typer(type);
  Cerr << "type retenu : " << valeur().que_suis_je() << finl ;
}
Member Data Documentation
const Type_info Elem_CoviMAC::info_obj [static]
Reimplemented from Deriv_Elem_CoviMAC_base.
Definition at line 44 of file Elem_CoviMAC.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Elem_CoviMAC.h
src/CoviMAC/Zones/Elem_CoviMAC.cpp