TRUST: src/Kernel/Utilitaires/Comm_Group_MPI.cpp File Reference
src/Kernel/Utilitaires/Comm_Group_MPI.cpp File Reference
#include <Comm_Group_MPI.h>
#include <petsc_for_kernel.h>
#include <PE_Groups.h>
#include <stat_counters.h>
#include <Statistiques.h>
#include <vector>
#include <algorithm>
Defines
#define MPI_ENTIER MPI_INT
Functions
static void mpi_print_error (int error_code)
Partie non inline du traitement d'erreur mpi.
Affichage d'un code d'erreur mpi avec MPI_Error_string.
static void mpi_error (int error_code)
Partie inline du traitement d'erreur mpi (on inline le
test: sauf exception, il n'y a pas d'appel de fonction
supplementaire.
Variables
const Type_info * Comm_Group_MPIbases [1] = { &(Comm_Group ::info_obj)}
Define Documentation
#define MPI_ENTIER MPI_INT
Definition at line 37 of file Comm_Group_MPI.cpp.
Referenced by Comm_Group_MPI::barrier(), Process::exit(), Comm_Group_MPI::mp_collective_op(), Comm_Group_MPI::mppartial_sum(), and Comm_Group_MPI::send_recv_start().
Function Documentation
static void mpi_error (int error_code) [inline, static]
Partie inline du traitement d'erreur mpi (on inline le
test: sauf exception, il n'y a pas d'appel de fonction
supplementaire.
Definition at line 74 of file Comm_Group_MPI.cpp.
References mpi_print_error().
Referenced by Comm_Group_MPI::all_to_all(), Comm_Group_MPI::all_to_allv(), Comm_Group_MPI::barrier(), Comm_Group_MPI::broadcast(), Comm_Group_MPI::free(), Comm_Group_MPI::init_group(), Comm_Group_MPI::init_group_trio(), Comm_Group_MPI::mp_collective_op(), Comm_Group_MPI::mppartial_sum(), Comm_Group_MPI::ptop_send_recv(), Comm_Group_MPI::recv(), Comm_Group_MPI::send(), Comm_Group_MPI::send_recv_finish(), Comm_Group_MPI::send_recv_start(), and Comm_Group_MPI::~Comm_Group_MPI().
{
  if (error_code != MPI_SUCCESS)
    mpi_print_error(error_code);
}
static void mpi_print_error (int error_code) [static]
Partie non inline du traitement d'erreur mpi.
Affichage d'un code d'erreur mpi avec MPI_Error_string.
Definition at line 50 of file Comm_Group_MPI.cpp.
References Cerr, Process::exit(), finl, Process::Journal(), and message().
Referenced by mpi_error().
{
  Cerr << "mpi_error in Comm_Group_MPI : error_code = " << error_code << finl;
  Process::Journal() << "mpi_error in Comm_Group_MPI : error_code = " << error_code << finl;
  True_int length = 0;
  char message[MPI_MAX_ERROR_STRING];
  MPI_Error_string(error_code, message, & length);
  if (length > 0)
    {
      Cerr << message << finl;
      Process::Journal() << message << finl;
    }
// Normalement on aurait pris trio_u_world_, mais on n'y a pas acces ici.
// Pour faire abort, en l'occurence, c'est pas grave mais merci de ne pas
// prendre comme exemple...
  assert(0);
  MPI_Abort(MPI_COMM_WORLD,-1);
  Process::exit();
}
Variable Documentation
const Type_info* Comm_Group_MPIbases[1] = { &(Comm_Group ::info_obj)}
Definition at line 30 of file Comm_Group_MPI.cpp.