TRUST: src/Kernel/Utilitaires/communications.cpp File Reference
src/Kernel/Utilitaires/communications.cpp File Reference
#include <communications.h>
#include <communications_array.h>
#include <InOutCommBuffers.h>
#include <Comm_Group.h>
#include <PE_Groups.h>
#include <Schema_Comm.h>
#include <DoubleTabs.h>
#include <Vect_ArrOfInt.h>
#include <Motcle.h>
#include <DerOu_.h>
#include <IntTab.h>
#include <vector>
Functions
template<class T >
int envoyer_buffered_ (const T &objet, int source, int cible, int canal)
Envoi de messages point-to-point synchrone entre la source et la cible.
La fonction envoyer se termine au plus tard lorsque le message a ete
recu par l'instruction "recevoir" correspondante et l'envoi peut etre blocant
(le blocage est force en mode debug, selon Comm_Group::check_enabled())
Ces communications utilisent Comm_Group::send() et Comm_Group::recv()
Exemples d'utilisations possibles:
1) communication point-a-point (processeur 2 vers processeur 5)
if (me() == 2)
envoyer(objet, 5, canal);
else if (me() == 5)
recevoir(objet, 2, canal);
ou de facon equivalente :
envoyer(objet, 2, 5, canal); // ne fait rien sur les processeurs autres que 2
recevoir(objet, 2, 5, canal); // ne fait rien sur les processeurs autres que 5
2) gather : le processeur 0 recupere les donnees de l'objet t de tout le monde
envoyer(t, me(), 0, canal); // Tout le monde envoie au processeur 0, sur le maitre, ne fait rien
if (je_suis_maitre())
for (i = 0; i < nproc(); i++) {
recevoir(t, 0, i; canal); // Si i==0, ne fait rien.
... faire quelque chose avec t
}
3) broadcast : le processeur 0 envoie l'objet a tous les autres processeurs
Il n'est pas necessaire de faire le test "if (je_suis_maitre())"
envoyer(objet, 0, -1, canal); // Les processeurs autres que 0 ignorent l'appel
recevoir(objet, 0, -1, canal);// Le processeur 0 ignore l'appel
Il vaut mieux utiliser envoyer_broadcast() pour cet usage.
4) broadcast : ecriture equivalente
if (je_suis_maitre())
envoyer(objet, -1, canal); // Emission par le maitre a tous les processeurs, sauf lui-meme
else
recevoir(objet, 0, canal); // Reception d'un message du processeur maitre
Il vaut mieux utiliser envoyer_broadcast() pour cet usage.
Dans l'implementation de envoyer_, on encapsule l'objet recu dans un buffer et on envoie le buffer.
Ca marche donc pour les types complexes pourvu que Entree et Sortie sachent lire et ecrire l'objet.
Chaque envoi necessite l'envoi de deux messages : d'abord la taille du buffer, puis le contenu.
template<class T >
int recevoir_buffered_ (T &objet, int source, int cible, int canal)
Reception d'un message en provenance du processeur source.
template<class T >
int envoyer_array_ (const T *objet, int n, int source, int cible, int canal)
template<class T >
int recevoir_array_ (T *objet, int n, int source, int cible, int canal)
int envoyer (const int &t, int source, int cible, int canal)
int envoyer (const long &t, int source, int cible, int canal)
int envoyer (const float &t, int source, int cible, int canal)
int envoyer (const double &t, int source, int cible, int canal)
int envoyer (const Objet_U &t, int source, int cible, int canal)
int envoyer (const int &t, int cible, int canal)
int envoyer (const long &t, int cible, int canal)
int envoyer (const float &t, int cible, int canal)
int envoyer (const double &t, int cible, int canal)
int envoyer (const Objet_U &t, int cible, int canal)
int recevoir (int &t, int source, int cible, int canal)
int recevoir (long &t, int source, int cible, int canal)
int recevoir (float &t, int source, int cible, int canal)
int recevoir (double &t, int source, int cible, int canal)
int recevoir (Objet_U &t, int source, int cible, int canal)
int recevoir (int &t, int source, int canal)
int recevoir (long &t, int source, int canal)
int recevoir (float &t, int source, int canal)
int recevoir (double &t, int source, int canal)
int recevoir (Objet_U &t, int source, int canal)
int envoyer_array (const int *t, int n, int source, int cible, int canal)
int envoyer_array (const long *t, int n, int source, int cible, int canal)
int envoyer_array (const double *t, int n, int source, int cible, int canal)
int envoyer_array (const float *t, int n, int source, int cible, int canal)
int recevoir_array (const int *t, int n, int source, int cible, int canal)
int recevoir_array (const long *t, int n, int source, int cible, int canal)
int recevoir_array (const double *t, int n, int source, int cible, int canal)
int recevoir_array (const float *t, int n, int source, int cible, int canal)
template<class T >
int envoyer_broadcast_ (T *objet, int n, int source)
template<class T >
int envoyer_broadcast_buffered_ (T &objet, int source)
Broadcast de l'objet par le processeur source a tous les autres processeurs.
Fonctionne pour des types complexes supportes par Entree ou Sortie.
int envoyer_broadcast (int &t, int source)
int envoyer_broadcast (long &t, int source)
int envoyer_broadcast (long long &t, int source)
int envoyer_broadcast (float &t, int source)
int envoyer_broadcast (double &t, int source)
int envoyer_broadcast (Objet_U &t, int source)
int envoyer_broadcast_array (int *t, int n, int source)
int envoyer_broadcast_array (long *t, int n, int source)
int envoyer_broadcast_array (float *t, int n, int source)
int envoyer_broadcast_array (double *t, int n, int source)
int envoyer_broadcast_array (char *t, int n, int source)
template<class T >
int envoyer_all_to_all_ (const T &src, T &dest)
int envoyer_all_to_all (const DoubleTabs &src, DoubleTabs &dest)
int envoyer_all_to_all (const Vect_ArrOfInt &src, Vect_ArrOfInt &dest)
int envoyer_all_to_all (const ArrOfInt &src, ArrOfInt &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int envoyer_all_to_all (const ArrOfDouble &src, ArrOfDouble &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int envoyer_all_to_all (std::vector< long long > &src, std::vector< long long > &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int reverse_send_recv_pe_list (const ArrOfInt &src_list, ArrOfInt &dest_list)
Calcule la transposee d'une liste de processeurs:
On construit le tableau dest_list tel que:
x est dans la liste src_list sur le processeur y
si et seulement si
y est dans la liste dest_list sur le processeur x
En pratique, cette fonction permet de calculer la liste des
processeurs qui recoivent des messages si on connait la liste
des processeurs qui envoient des messages, et reciproquement.
Parametre: src_list
Signification: Une liste de numeros de PEs presents dans ce groupe de comm.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Parametre: dest_list
Signification: Le tableau ou stocker le resultat. On le met a la bonne taille
et on le remplit. Les numeros de PEs sont mis dans l'ordre
croissant.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
int mp_max (int x)
renvoie le plus grand int i sur l'ensemble des processeurs du
groupe courant.
int mp_min (int x)
renvoie le plus petit int i sur l'ensemble des processeurs du
groupe courant.
int mppartial_sum (int x)
Calul de la somme partielle de i sur les processeurs 0 a me()-1
(renvoie 0 sur le processeur 0). Voir Comm_Group::mppartial_sum()
void mpsum_multiple (double &x1, double &x2)
static void mp_collective_op (ArrOfInt &x, Comm_Group::Collective_Op op)
static void mp_collective_op (ArrOfDouble &x, Comm_Group::Collective_Op op)
void mp_sum_for_each_item (ArrOfInt &x)
void mp_sum_for_each_item (ArrOfDouble &x)
void mp_min_for_each_item (ArrOfInt &x)
void mp_min_for_each_item (ArrOfDouble &x)
void mp_max_for_each_item (ArrOfInt &x)
void mp_max_for_each_item (ArrOfDouble &x)
void envoyer_all_to_all (const DoubleTab &src, DoubleTab &dest)
On suppose que les tableaux en entree et en sortie
sont tels que dimension(0)==nproc() et que les autres dimensions
sont identiques. On envoie src(0, i, j, ...) au proc 0,
src(0, i, j, ...) au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest(0, i, j, ...) , processeur 1 dans dest(1, i, j, ...) , etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int comm_check_enabled ()
renvoie le drapeau Comm_Group::check_enabled().
Ce drapeau indique si le code tourne en mode DEBUG du parallele.
Dans ce cas, des communications supplementaires ont lieu pour
verifier la coherence du parallelisme et le mode de communication
est force en mode synchrone.
Cette methode permet de tester le drapeau, et s'il est mis de
realiser des verifications supplementaires
int is_parallel_object (const int x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
int is_parallel_object (const double x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
void assert_parallel (const int x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
void assert_parallel (const double x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
template<class T >
int compare (const Objet_U &a, const Objet_U &b, int &erreur)
int is_parallel_object (const Objet_U &obj)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
void assert_parallel (const Objet_U &obj)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs.
Ne fonctionne pas pour tous les types !
Pour l'instant ok pour Noms, Motcles et tableaux.
Function Documentation
void assert_parallel (const int x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
Definition at line 747 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), and Process::Journal().
Referenced by Schema_Temps_base::mettre_a_jour(), and mp_collective_op().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(x))
    {
      Cerr << "Fatal error in assert_parallel(const int x). See log files" << finl;
      Process::Journal() << "Error in assert_parallel(const int x)          )"
                         << "This processor has this value: " << x << finl;
      Process::barrier();
      Process::exit();
    }
}
void assert_parallel (const double x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
Definition at line 763 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), and Process::Journal().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(x))
    {
      Cerr << "Fatal error in assert_parallel(const double x). See log files" << finl;
      Process::Journal() << "Error in assert_parallel(const double x)          )"
                         << "This processor has this value: " << x << finl;
      Process::barrier();
      Process::exit();
    }
}
void assert_parallel (const Objet_U & obj)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs.
Ne fonctionne pas pour tous les types !
Pour l'instant ok pour Noms, Motcles et tableaux.
Definition at line 848 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), Process::Journal(), and Objet_U::que_suis_je().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(obj))
    {
      Cerr << "Fatal error in assert_parallel(const Objet_U & obj): objects do not match, see log files" << finl;
      Process::Journal() << "Error in assert_parallel(const Objet_U & obj)"
                         << "This processor has this object : " << obj.que_suis_je() << finl
                         << obj << finl;
      Process::barrier();
      Process::exit();
    }
}
int comm_check_enabled ()
renvoie le drapeau Comm_Group::check_enabled().
Ce drapeau indique si le code tourne en mode DEBUG du parallele.
Dans ce cas, des communications supplementaires ont lieu pour
verifier la coherence du parallelisme et le mode de communication
est force en mode synchrone.
Cette methode permet de tester le drapeau, et s'il est mis de
realiser des verifications supplementaires
Definition at line 717 of file communications.cpp.
References Comm_Group::check_enabled().
Referenced by Scatter::construire_md_vector().
{
  return Comm_Group::check_enabled();
}
template<class T > int compare (const Objet_U & a, const Objet_U & b, int & erreur)
Definition at line 777 of file communications.cpp.
References ref_cast, and sub_type.
Referenced by Traduction_Indice_Global_Local::chercher_table_inverse(), and Parser::searchVar().
{
  if (sub_type(T, a))
    {
      const T& a_ = ref_cast(T, a);
      const T& b_ = ref_cast(T, b);
      if (! (a_ == b_))
        erreur = 1;
      return 1;
    }
  else
    {
      return 0;
    }
}
int envoyer (const int & t, int source, int cible, int canal)
Definition at line 200 of file communications.cpp.
References envoyer_array_().
Referenced by add_sommets_communs(), Probleme_base::allocation(), Echange_contact_Correlation_VDF::calculer_CL(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), compute_global_connex_components(), mon_main::dowork(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VDF::init_tab_echange(), Sonde::initialiser(), is_parallel_object(), Echange_contact_Correlation_VDF::mettre_a_jour(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), Sous_Zone::readOn(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), and EcrFicPartage::syncfile().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const double & t, int source, int cible, int canal)
Definition at line 214 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const Objet_U & t, int source, int cible, int canal)
Definition at line 218 of file communications.cpp.
References envoyer_buffered_().
{
  return envoyer_buffered_(t, source, cible, canal);
}
int envoyer (const int & t, int cible, int canal)
Definition at line 223 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const long & t, int cible, int canal)
Definition at line 228 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const long & t, int source, int cible, int canal)
Definition at line 205 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const float & t, int cible, int canal)
Definition at line 233 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const double & t, int cible, int canal)
Definition at line 237 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const float & t, int source, int cible, int canal)
Definition at line 210 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const Objet_U & t, int cible, int canal)
Definition at line 241 of file communications.cpp.
References envoyer_buffered_(), and Process::me().
{
  return envoyer_buffered_(t, Process::me(), cible, canal);
}
void envoyer_all_to_all (const DoubleTab & src, DoubleTab & dest)
On suppose que les tableaux en entree et en sortie
sont tels que dimension(0)==nproc() et que les autres dimensions
sont identiques. On envoie src(0, i, j, ...) au proc 0,
src(0, i, j, ...) au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest(0, i, j, ...) , processeur 1 dans dest(1, i, j, ...) , etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 690 of file communications.cpp.
References ArrOfDouble::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), DoubleTab::dimension(), envoyer_all_to_all(), Comm_Group::nproc(), DoubleVect::size(), ArrOfDouble::size_array(), and sz.
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.dimension(0) == grp.nproc());
  assert(dest.dimension(0) == grp.nproc());
  assert(src.size_array() == dest.size_array());
  if (dest.addr() == src.addr())
    {
      DoubleTab tmp(src);
      envoyer_all_to_all(src, tmp);
      dest = tmp;
    }
  else
    {
      const int sz = src.size() / grp.nproc() * sizeof(double);
      grp.all_to_all(src.addr(), dest.addr(), sz);
    }
}
int envoyer_all_to_all (const DoubleTabs & src, DoubleTabs & dest)
Definition at line 452 of file communications.cpp.
References envoyer_all_to_all_(), Process::nproc(), and vect_impl::size().
Referenced by Moyenne_volumique::calculer_convolution(), Domain_Graph::construire_graph_elem_elem(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), MD_Vector_tools::extend(), find_matching_coordinates(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Scatter::lire_domaine(), MD_Vector_std::MD_Vector_std(), Champ_front_recyclage::mettre_a_jour(), and reverse_send_recv_pe_list().
{
// Je mets le assert ici car si on veut faire un envoyer_all_to_all(IntTab)
// le assert doit utiliser size_array()
  assert(src.size() == Process::nproc());
  assert(dest.size() == Process::nproc());
  return envoyer_all_to_all_(src, dest);
}
int envoyer_all_to_all (const Vect_ArrOfInt & src, Vect_ArrOfInt & dest)
Definition at line 461 of file communications.cpp.
References envoyer_all_to_all_(), and Process::nproc().
{
  assert(src.size() == Process::nproc());
  assert(dest.size() == Process::nproc());
  return envoyer_all_to_all_(src, dest);
}
int envoyer_all_to_all (const ArrOfInt & src, ArrOfInt & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 473 of file communications.cpp.
References ArrOfInt::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), ArrOfInt::inject_array(), Array_base::NOCOPY_NOINIT, Comm_Group::nproc(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.size_array() == grp.nproc());
  assert(dest.size_array() == grp.nproc());
  if (src.addr() == dest.addr())
    {
      ArrOfInt tmp;
      tmp.resize_array(grp.nproc(), Array_base::NOCOPY_NOINIT);
      grp.all_to_all(src.addr(), tmp.addr(), sizeof(int));
      dest.inject_array(tmp);
    }
  else
    {
      grp.all_to_all(src.addr(), dest.addr(), sizeof(int));
    }
  return 1;
}
int envoyer_all_to_all (const ArrOfDouble & src, ArrOfDouble & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 497 of file communications.cpp.
References ArrOfDouble::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), ArrOfDouble::inject_array(), Array_base::NOCOPY_NOINIT, Comm_Group::nproc(), ArrOfDouble::resize_array(), and ArrOfDouble::size_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.size_array() == grp.nproc());
  assert(dest.size_array() == grp.nproc());
  if (src.addr() == dest.addr())
    {
      ArrOfDouble tmp;
      tmp.resize_array(grp.nproc(), Array_base::NOCOPY_NOINIT);
      grp.all_to_all(src.addr(), tmp.addr(), sizeof(double));
      dest.inject_array(tmp);
    }
  else
    {
      grp.all_to_all(src.addr(), dest.addr(), sizeof(double));
    }
  return 1;
}
int envoyer_all_to_all (std::vector< long long > & src, std::vector< long long > & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 521 of file communications.cpp.
References Comm_Group::all_to_all(), PE_Groups::current_group(), and Comm_Group::nproc().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(static_cast<int>(src.size()) == grp.nproc());
  assert(static_cast<int>(dest.size()) == grp.nproc());
  if (src.data() == dest.data())
    {
      std::vector<long long> tmp(grp.nproc(),0);
      grp.all_to_all(src.data(), tmp.data(), sizeof(long long));
      dest = tmp;
    }
  else
    {
      grp.all_to_all(src.data(), dest.data(), sizeof(long long));
    }
  return 1;
}
template<class T > int envoyer_all_to_all_ (const T & src, T & dest)
Definition at line 427 of file communications.cpp.
References Schema_Comm::begin_comm(), PE_Groups::current_group(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Comm_Group::nproc(), Comm_Group::rank(), Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), and Schema_Comm::set_send_recv_pe_list().
Referenced by envoyer_all_to_all().
{
  const Comm_Group& grp = PE_Groups::current_group();
  Schema_Comm sch;
  const int nproc = grp.nproc();
  const int moi = grp.rank();
  dest[moi] = src[moi];
  ArrOfInt send_pe_list(1);
  ArrOfInt recv_pe_list(1);
  for (int p = 1; p < nproc; p++)
    {
      const int send_to = (moi + p) % nproc;
      const int recv_from = (moi + nproc - p) % nproc;
      send_pe_list[0] = send_to;
      recv_pe_list[0] = recv_from;
      sch.set_send_recv_pe_list(send_pe_list, recv_pe_list);
      sch.begin_comm();
      sch.send_buffer(send_to) << src[send_to];
      sch.echange_taille_et_messages();
      sch.recv_buffer(recv_from) >> dest[recv_from];
      sch.end_comm();
    }
  return 1;
}
int envoyer_array (const int * t, int n, int source, int cible, int canal)
Definition at line 292 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(t, n, source, cible, canal);
}
int envoyer_array (const long * t, int n, int source, int cible, int canal)
Definition at line 297 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(t, n, source, cible, canal);
}
int envoyer_array (const double * t, int n, int source, int cible, int canal)
Definition at line 302 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(t, n, source, cible, canal);
}
int envoyer_array (const float * t, int n, int source, int cible, int canal)
Definition at line 306 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(t, n, source, cible, canal);
}
template<class T > int envoyer_array_ (const T * objet, int n, int source, int cible, int canal)
Definition at line 133 of file communications.cpp.
References Comm_Group::check_enabled(), PE_Groups::current_group(), Comm_Group::nproc(), Comm_Group::rank(), Comm_Group::send(), and sz.
Referenced by envoyer(), and envoyer_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int moi = grp.rank();
  if (moi == cible)
    return 0;
  if (source != moi && source != -1)
    return 0;
  const char * data = (const char*) objet;
  const int sz   = sizeof(T) * n;
  if (cible < 0)
    {
      const int nbproc = grp.nproc();
      for (int i = 0; i < nbproc; i++)
        {
          if (i != moi)
            {
// En mode check, on verifie que n est bien le meme sur l'expediteur et le recepteur
              if (grp.check_enabled())
                grp.send(i, &sz, sizeof(int), canal);
              if (sz > 0)
                grp.send(i, data, sz, canal);
            }
        }
    }
  else
    {
      if (grp.check_enabled())
        grp.send(cible, &sz, sizeof(int), canal);
      if (sz > 0)
        grp.send(cible, data, sz, canal);
    }
  return 1;
}
int envoyer_broadcast (int & t, int source)
Definition at line 375 of file communications.cpp.
References envoyer_broadcast_().
Referenced by avancer_fichier(), compute_global_connex_components(), Sch_CN_iteratif::convergence(), Partitionneur_base::corriger_elem0_sur_proc0(), corriger_type(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Lec_Diffuse_base::eof(), Lec_Diffuse_base::fail(), Lec_Diffuse_base::get(), Lec_Diffuse_base::good(), Comm_Group::init_group(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), MaillerParallel::interpreter(), is_parallel_object(), Schema_Temps_base::mettre_a_jour(), Lec_Diffuse_base::operator>>(), LecFicDistribue::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDiffuse::ouvrir(), EcrFicCollecte::ouvrir(), EcrFicPartageMPIIO::put(), Debog_Pb::read_geometry_data(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Lec_Diffuse_base::set_bin(), Terme_Source_Canal_perio::source(), and verifier().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (long & t, int source)
Definition at line 380 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (long long & t, int source)
Definition at line 385 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (float & t, int source)
Definition at line 389 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (double & t, int source)
Definition at line 393 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (Objet_U & t, int source)
Definition at line 397 of file communications.cpp.
References envoyer_broadcast_buffered_().
{
  return envoyer_broadcast_buffered_(t, source);
}
template<class T > int envoyer_broadcast_ (T * objet, int n, int source)
Definition at line 330 of file communications.cpp.
References Comm_Group::broadcast(), Cerr, Comm_Group::check_enabled(), PE_Groups::current_group(), Process::exit(), and finl.
Referenced by envoyer_broadcast(), and envoyer_broadcast_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  if (grp.check_enabled())
    {
      int copie_n = n;
      grp.broadcast(&copie_n, sizeof(int), source);
      if (copie_n != n)
        {
          Cerr << "Error in envoyer_broadcast_(T * objet, int n, int source)" << finl;
          Process::exit();
        }
    }
  grp.broadcast(objet, sizeof(T) * n, source);
  return 1;
}
int envoyer_broadcast_array (float * t, int n, int source)
Definition at line 412 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(t, n, source);
}
int envoyer_broadcast_array (int * t, int n, int source)
Definition at line 402 of file communications.cpp.
References envoyer_broadcast_().
Referenced by Lec_Diffuse_base::get().
{
  return envoyer_broadcast_(t, n, source);
}
int envoyer_broadcast_array (long * t, int n, int source)
Definition at line 407 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(t, n, source);
}
int envoyer_broadcast_array (double * t, int n, int source)
Definition at line 416 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(t, n, source);
}
int envoyer_broadcast_array (char * t, int n, int source)
Definition at line 420 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(t, n, source);
}
template<class T > int envoyer_broadcast_buffered_ (T & objet, int source)
Broadcast de l'objet par le processeur source a tous les autres processeurs.
Fonctionne pour des types complexes supportes par Entree ou Sortie.
Definition at line 349 of file communications.cpp.
References Comm_Group::broadcast(), InputCommBuffer::clear(), InputCommBuffer::create_stream(), PE_Groups::current_group(), OutputCommBuffer::get_buffer(), OutputCommBuffer::get_buffer_size(), Comm_Group::rank(), InputCommBuffer::reserve_buffer(), and sz.
Referenced by envoyer_broadcast().
{
  const Comm_Group& grp = PE_Groups::current_group();
  if (grp.rank() == source)
    {
      OutputCommBuffer buffer;
      buffer << objet;
      const char * data = buffer.get_buffer();
      int sz   = buffer.get_buffer_size();
      grp.broadcast(&sz, sizeof(int), source);
      grp.broadcast((char*) data, sz, source);
    }
  else
    {
      int sz;
      grp.broadcast(&sz, sizeof(int), source);
      InputCommBuffer buffer;
      char * data = buffer.reserve_buffer(sz);
      grp.broadcast((char*) data, sz, source);
      buffer.create_stream();
      buffer >> objet;
      buffer.clear();
    }
  return 1;
}
template<class T > int envoyer_buffered_ (const T & objet, int source, int cible, int canal)
Envoi de messages point-to-point synchrone entre la source et la cible.
La fonction envoyer se termine au plus tard lorsque le message a ete
recu par l'instruction "recevoir" correspondante et l'envoi peut etre blocant
(le blocage est force en mode debug, selon Comm_Group::check_enabled())
Ces communications utilisent Comm_Group::send() et Comm_Group::recv()
Exemples d'utilisations possibles:
1) communication point-a-point (processeur 2 vers processeur 5)
if (me() == 2)
envoyer(objet, 5, canal);
else if (me() == 5)
recevoir(objet, 2, canal);
ou de facon equivalente :
envoyer(objet, 2, 5, canal); // ne fait rien sur les processeurs autres que 2
recevoir(objet, 2, 5, canal); // ne fait rien sur les processeurs autres que 5
2) gather : le processeur 0 recupere les donnees de l'objet t de tout le monde
envoyer(t, me(), 0, canal); // Tout le monde envoie au processeur 0, sur le maitre, ne fait rien
if (je_suis_maitre())
for (i = 0; i < nproc(); i++) {
recevoir(t, 0, i; canal); // Si i==0, ne fait rien.
... faire quelque chose avec t
}
3) broadcast : le processeur 0 envoie l'objet a tous les autres processeurs
Il n'est pas necessaire de faire le test "if (je_suis_maitre())"
envoyer(objet, 0, -1, canal); // Les processeurs autres que 0 ignorent l'appel
recevoir(objet, 0, -1, canal);// Le processeur 0 ignore l'appel
Il vaut mieux utiliser envoyer_broadcast() pour cet usage.
4) broadcast : ecriture equivalente
if (je_suis_maitre())
envoyer(objet, -1, canal); // Emission par le maitre a tous les processeurs, sauf lui-meme
else
recevoir(objet, 0, canal); // Reception d'un message du processeur maitre
Il vaut mieux utiliser envoyer_broadcast() pour cet usage.
Dans l'implementation de envoyer_, on encapsule l'objet recu dans un buffer et on envoie le buffer.
Ca marche donc pour les types complexes pourvu que Entree et Sortie sachent lire et ecrire l'objet.
Chaque envoi necessite l'envoi de deux messages : d'abord la taille du buffer, puis le contenu.
Definition at line 74 of file communications.cpp.
References PE_Groups::current_group(), OutputCommBuffer::get_buffer(), OutputCommBuffer::get_buffer_size(), Process::me(), Comm_Group::nproc(), Comm_Group::send(), and sz.
Referenced by envoyer().
{
  const int moi = Process::me();
  if (moi == cible)
    return 0;
  if (source != moi && source != -1)
    return 0;
  OutputCommBuffer buffer;
  buffer << objet;
  const char * data = buffer.get_buffer();
  const int sz   = buffer.get_buffer_size();
  const Comm_Group& grp = PE_Groups::current_group();
  if (cible < 0)
    {
      const int n = grp.nproc();
      for (int i = 0; i < n; i++)
        {
          if (i != moi)
            {
              grp.send(i, &sz, sizeof(int), canal);
              grp.send(i, data, sz, canal);
            }
        }
    }
  else
    {
      grp.send(cible, &sz, sizeof(int), canal);
      grp.send(cible, data, sz, canal);
    }
  return 1;
}
int is_parallel_object (const int x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
Definition at line 724 of file communications.cpp.
References mp_max(), and mp_min().
Referenced by assert_parallel(), and check_frontiere().
{
  const int x1 = mp_min(x);
  const int x2 = mp_max(x);
  return x1 == x2;
}
int is_parallel_object (const double x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
Definition at line 733 of file communications.cpp.
References Comm_Group::COLL_MAX, Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double tab_x[2];
  tab_x[0] = x;
  tab_x[1] = x;
  double tab_y[2];
  Comm_Group::Collective_Op tab_op[] = { Comm_Group::COLL_MIN, Comm_Group::COLL_MAX };
  grp.mp_collective_op(tab_x, tab_y, tab_op, 2);
  return tab_y[0] == tab_y[1];
}
int is_parallel_object (const Objet_U & obj)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
< On a deja trouve une erreur, on recoit les autres messages mais c'est tout...
Definition at line 795 of file communications.cpp.
References Cerr, DERIV, envoyer(), envoyer_broadcast(), erreur(), Process::exit(), finl, Process::je_suis_maitre(), Process::nproc(), Objet_U::que_suis_je(), and recevoir().
{
  int erreur = 0;
  if (Process::je_suis_maitre())
    {
      DERIV(Objet_U) copie;
      const int n = Process::nproc();
      for (int i = 1; i < n; i++)
        {
          recevoir(copie, i, 67 /* tag */);
          if (erreur)
            continue; //!< On a deja trouve une erreur, on recoit les autres messages mais c'est tout...
          const Objet_U& obj2 = copie.valeur();
          if (obj2.que_suis_je() != obj.que_suis_je())
            {
              erreur = 1;
            }
          else
            {
// L'operateur == n'est pas virtuel, on ne peut pas se contenter de comparer avec ==.
// Il faut appeler == pour le sous-type specifique de l'objet.
// L'ordre est important: d'abord le type le plus derive, puis sa classe de base.
              if (compare<IntTab> (obj, obj2, erreur));
              else if (compare<DoubleTab> (obj, obj2, erreur));
              else if (compare<IntVect> (obj, obj2, erreur));
              else if (compare<DoubleVect> (obj, obj2, erreur));
              else if (compare<ArrOfInt> (obj, obj2, erreur));
              else if (compare<ArrOfDouble> (obj, obj2, erreur));
              else if (compare<Motcle> (obj, obj2, erreur));
              else if (compare<Nom> (obj, obj2, erreur));
              else
                {
                  Cerr << "Internal error in is_parallel_objec() : it is not coded for " << obj.que_suis_je() << finl;
                  Process::exit();
                }
            }
        }
    }
  else
    {
// On envoie un objet de type DERIV..
      DERIV(Objet_U) copie(obj);
      envoyer(copie, 0, 67 /* tag */);
    }
  envoyer_broadcast(erreur, 0 /* pe source */);
  return !erreur;
}
static void mp_collective_op (ArrOfInt & x, Comm_Group::Collective_Op op) [static]
Definition at line 629 of file communications.cpp.
References ArrOfInt::addr(), assert_parallel(), PE_Groups::current_group(), Comm_Group::mp_collective_op(), ArrOfInt::size_array(), and sz.
Referenced by mp_max_for_each_item(), mp_min_for_each_item(), and mp_sum_for_each_item().
{
  int sz = x.size_array();
  assert_parallel(sz);
  if (sz > 0)
    {
      int *data = x.addr();
      int *tmp = new int[sz];
      const Comm_Group& grp = PE_Groups::current_group();
      grp.mp_collective_op(data, tmp, sz, op);
      memcpy(data, tmp, sz * sizeof(int));
      delete [] tmp;
    }
}
static void mp_collective_op (ArrOfDouble & x, Comm_Group::Collective_Op op) [static]
Definition at line 644 of file communications.cpp.
References ArrOfDouble::addr(), assert_parallel(), PE_Groups::current_group(), Comm_Group::mp_collective_op(), ArrOfDouble::size_array(), and sz.
{
  int sz = x.size_array();
  assert_parallel(sz);
  if (sz > 0)
    {
      double *data = x.addr();
      double *tmp = new double[sz];
      const Comm_Group& grp = PE_Groups::current_group();
      grp.mp_collective_op(data, tmp, sz, op);
      memcpy(data, tmp, sz * sizeof(double));
      delete [] tmp;
    }
}
int mp_max (int x)
renvoie le plus grand int i sur l'ensemble des processeurs du
groupe courant.
Definition at line 588 of file communications.cpp.
References Comm_Group::COLL_MAX, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by is_parallel_object(), mp_max_abs_vect(), and mp_max_vect().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MAX);
  return y;
}
void mp_max_for_each_item (ArrOfDouble & x)
Definition at line 679 of file communications.cpp.
References Comm_Group::COLL_MAX, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_MAX);
}
void mp_max_for_each_item (ArrOfInt & x)
Definition at line 675 of file communications.cpp.
References Comm_Group::COLL_MAX, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), Sonde::initialiser(), mp_max_abs_tab(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_MAX);
}
int mp_min (int x)
renvoie le plus petit int i sur l'ensemble des processeurs du
groupe courant.
Definition at line 598 of file communications.cpp.
References Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by corriger_type(), Champ_P1NC_implementation::filtrer_resu(), is_parallel_object(), mp_min_abs_vect(), and mp_min_vect().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MIN);
  return y;
}
void mp_min_for_each_item (ArrOfInt & x)
Definition at line 667 of file communications.cpp.
References Comm_Group::COLL_MIN, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_MIN);
}
void mp_min_for_each_item (ArrOfDouble & x)
Definition at line 671 of file communications.cpp.
References Comm_Group::COLL_MIN, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_MIN);
}
void mp_sum_for_each_item (ArrOfInt & x)
Definition at line 659 of file communications.cpp.
References Comm_Group::COLL_SUM, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), T_It_VDF_Face< _TYPE_ >::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Grad_VEF_P1B_Face::impr(), Source_base::impr(), Op_Diff_CoviMAC_base::impr(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), EOS_Tools_VDF::moyenne_vol(), mp_carre_norme_tab(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_SUM);
}
void mp_sum_for_each_item (ArrOfDouble & x)
Definition at line 663 of file communications.cpp.
References Comm_Group::COLL_SUM, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_SUM);
}
int mppartial_sum (int x)
Calul de la somme partielle de i sur les processeurs 0 a me()-1
(renvoie 0 sur le processeur 0). Voir Comm_Group::mppartial_sum()
Definition at line 608 of file communications.cpp.
References Comm_Group::COLL_PARTIAL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), compute_global_connex_components(), Domain_Graph::construire_graph_elem_elem(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), Traduction_Indice_Global_Local::initialiser(), EcrFicPartageMPIIO::put(), and Champ_Fonc_MED::readOn().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_PARTIAL_SUM);
  return y;
}
void mpsum_multiple (double & x1, double & x2)
Definition at line 617 of file communications.cpp.
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Solv_GCP::resoudre_().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double x[2];
  double y[2];
  x[0] = x1;
  x[1] = x2;
  grp.mp_collective_op(x, y, 2, Comm_Group::COLL_SUM);
  x1 = y[0];
  x2 = y[1];
}
int recevoir (long & t, int source, int canal)
Definition at line 274 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (float & t, int source, int canal)
Definition at line 279 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (float & t, int source, int cible, int canal)
Definition at line 256 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (long & t, int source, int cible, int canal)
Definition at line 251 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (int & t, int source, int canal)
Definition at line 269 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (int & t, int source, int cible, int canal)
Definition at line 246 of file communications.cpp.
References recevoir_array_().
Referenced by add_sommets_communs(), Probleme_base::allocation(), Echange_contact_Correlation_VDF::calculer_CL(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), compute_global_connex_components(), mon_main::dowork(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VDF::init_tab_echange(), Sonde::initialiser(), is_parallel_object(), Echange_contact_Correlation_VDF::mettre_a_jour(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), Sous_Zone::readOn(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), and EcrFicPartage::syncfile().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (double & t, int source, int cible, int canal)
Definition at line 260 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (Objet_U & t, int source, int cible, int canal)
Definition at line 264 of file communications.cpp.
References recevoir_buffered_().
{
  return recevoir_buffered_(t, source, cible, canal);
}
int recevoir (Objet_U & t, int source, int canal)
Definition at line 287 of file communications.cpp.
References Process::me(), and recevoir_buffered_().
{
  return recevoir_buffered_(t, source, Process::me(), canal);
}
int recevoir (double & t, int source, int canal)
Definition at line 283 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir_array (const int * t, int n, int source, int cible, int canal)
Definition at line 311 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(t, n, source, cible, canal);
}
int recevoir_array (const float * t, int n, int source, int cible, int canal)
Definition at line 325 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(t, n, source, cible, canal);
}
int recevoir_array (const long * t, int n, int source, int cible, int canal)
Definition at line 316 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(t, n, source, cible, canal);
}
int recevoir_array (const double * t, int n, int source, int cible, int canal)
Definition at line 321 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(t, n, source, cible, canal);
}
template<class T > int recevoir_array_ (T * objet, int n, int source, int cible, int canal)
Definition at line 170 of file communications.cpp.
References Cerr, Comm_Group::check_enabled(), PE_Groups::current_group(), Process::exit(), finl, Comm_Group::rank(), Comm_Group::recv(), and sz.
Referenced by recevoir(), and recevoir_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int moi = grp.rank();
  if (moi == source)
    return 0;
  if (cible != moi && cible != -1)
    return 0;
  const int sz = sizeof(T) * n;
  if (grp.check_enabled())
    {
      int sz_check;
      grp.recv(source, &sz_check, sizeof(int), canal);
      if (sz_check != sz)
        {
          Cerr << "Fatal error in template <class T> int recevoir_array_ : incorrect size\n"
               << " sent=" << sz_check << " expected=" << sz << finl;
          Process::exit();
        }
    }
  char * data = (char*) objet;
  if (sz > 0)
    grp.recv(source, data, sz, canal);
  return 1;
}
template<class T > int recevoir_buffered_ (T & objet, int source, int cible, int canal)
Reception d'un message en provenance du processeur source.
Definition at line 109 of file communications.cpp.
References InputCommBuffer::clear(), InputCommBuffer::create_stream(), PE_Groups::current_group(), Process::me(), Comm_Group::recv(), InputCommBuffer::reserve_buffer(), and sz.
Referenced by recevoir().
{
  const int moi = Process::me();
  if (moi == source)
    return 0;
  if (cible != moi && cible != -1)
    return 0;
  int sz;
  const Comm_Group& grp = PE_Groups::current_group();
  grp.recv(source, &sz, sizeof(int), canal);
  InputCommBuffer buffer;
  char * data = buffer.reserve_buffer(sz);
  grp.recv(source, data, sz, canal);
  buffer.create_stream();
  buffer >> objet;
  buffer.clear();
  return 1;
}
int reverse_send_recv_pe_list (const ArrOfInt & src_list, ArrOfInt & dest_list)
Calcule la transposee d'une liste de processeurs:
On construit le tableau dest_list tel que:
x est dans la liste src_list sur le processeur y
si et seulement si
y est dans la liste dest_list sur le processeur x
En pratique, cette fonction permet de calculer la liste des
processeurs qui recoivent des messages si on connait la liste
des processeurs qui envoient des messages, et reciproquement.
Parametre: src_list
Signification: Une liste de numeros de PEs presents dans ce groupe de comm.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Parametre: dest_list
Signification: Le tableau ou stocker le resultat. On le met a la bonne taille
et on le remplit. Les numeros de PEs sont mis dans l'ordre
croissant.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Definition at line 561 of file communications.cpp.
References PE_Groups::current_group(), envoyer_all_to_all(), max_array(), min_array(), Comm_Group::nproc(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
Referenced by Scatter::ajouter_joints(), Schema_Comm::check_send_recv_pe_list(), and Zone::creer_aretes().
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int np = grp.nproc();
  assert(src_list.size_array() == 0 || max_array(src_list) < np);
  assert(src_list.size_array() == 0 || min_array(src_list) >= 0);
  ArrOfInt flag(np);
  int i;
  const int src_size = src_list.size_array();
  for (i = 0; i < src_size; i++)
    {
      const int pe = src_list[i];
      flag[pe] = 1;
    }
  ArrOfInt flag_recv(np);
  envoyer_all_to_all(flag, flag_recv);
  int n = 0;
  dest_list.resize_array(np);
  for (i = 0; i < np; i++)
    if (flag_recv[i])
      dest_list[n++] = i;
  dest_list.resize_array(n);
  return 1;
}