TRUST: src/ThHyd/Chimie/common_chimie.h File Reference
src/ThHyd/Chimie/common_chimie.h File Reference
Functions
C INCLUDE_FORTRAN integer ncmax parameter (nrmax=50, ncmax=12) integer nr
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction cw (nrmax)
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction aveccontrereaction (nrmax)
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction stochio (nrmax, ncmax)
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction activite (nrmax, ncmax)
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction correction (nrmax)
Variables
C INCLUDE_FORTRAN integer nrmax
C INCLUDE_FORTRAN integer ncmax ncs
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer activite
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision cw
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision stochio
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision tau_mel
C INCLUDE_FORTRAN integer
ncmax
marqueur_espece_en_competition
integer aveccontrereaction
double precision correction
common reaction nr
Function Documentation
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction activite (nrmax , ncmax)
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction aveccontrereaction (nrmax)
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction correction (nrmax)
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), and Schema_Adams_Moulton_base::modifier_second_membre_full_impl().
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction cw (nrmax)
C INCLUDE_FORTRAN integer ncmax parameter (nrmax = 50, ncmax = 12)
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction stochio (nrmax , ncmax)
Variable Documentation
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer activite
Definition at line 4 of file common_chimie.h.
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision cw
Definition at line 4 of file common_chimie.h.
Referenced by Chimie::mettre_a_jour().
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction ncs
Definition at line 4 of file common_chimie.h.
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction nr
Definition at line 4 of file common_chimie.h.
C INCLUDE_FORTRAN integer nrmax
Definition at line 2 of file common_chimie.h.
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision stochio
Definition at line 4 of file common_chimie.h.
C INCLUDE_FORTRAN integer ncmax marqueur_espece_en_competition integer aveccontrereaction double precision correction common reaction tau_mel
Definition at line 4 of file common_chimie.h.
Referenced by DLSODECHIMIES(), and Chimie::mettre_a_jour().