TRUST: src/Kernel/Utilitaires/communications.h File Reference
src/Kernel/Utilitaires/communications.h File Reference
#include <Vect.h>
#include <vector>
Functions
int envoyer (const int &t, int source, int cible, int canal)
int envoyer (const long &t, int source, int cible, int canal)
int envoyer (const float &t, int source, int cible, int canal)
int envoyer (const double &t, int source, int cible, int canal)
int envoyer (const Objet_U &t, int source, int cible, int canal)
int envoyer (const int &t, int cible, int canal)
int envoyer (const long &t, int cible, int canal)
int envoyer (const float &t, int cible, int canal)
int envoyer (const double &t, int cible, int canal)
int envoyer (const Objet_U &t, int cible, int canal)
int recevoir (int &t, int source, int cible, int canal)
int recevoir (long &t, int source, int cible, int canal)
int recevoir (float &t, int source, int cible, int canal)
int recevoir (double &t, int source, int cible, int canal)
int recevoir (Objet_U &t, int source, int cible, int canal)
int recevoir (int &t, int source, int canal)
int recevoir (long &t, int source, int canal)
int recevoir (float &t, int source, int canal)
int recevoir (double &t, int source, int canal)
int recevoir (Objet_U &t, int source, int canal)
int envoyer_broadcast (int &t, int source)
int envoyer_broadcast (long &t, int source)
int envoyer_broadcast (long long &t, int source)
int envoyer_broadcast (float &t, int source)
int envoyer_broadcast (double &t, int source)
int envoyer_broadcast (Objet_U &t, int source)
int mppartial_sum (int i)
Calul de la somme partielle de i sur les processeurs 0 a me()-1
(renvoie 0 sur le processeur 0). Voir Comm_Group::mppartial_sum()
int mp_max (int i)
renvoie le plus grand int i sur l'ensemble des processeurs du
groupe courant.
int mp_min (int i)
renvoie le plus petit int i sur l'ensemble des processeurs du
groupe courant.
void mpsum_multiple (double &x1, double &x2)
void mp_sum_for_each_item (ArrOfInt &)
void mp_sum_for_each_item (ArrOfDouble &)
void mp_max_for_each_item (ArrOfInt &)
void mp_max_for_each_item (ArrOfDouble &)
void mp_min_for_each_item (ArrOfInt &)
void mp_min_for_each_item (ArrOfDouble &)
int envoyer_all_to_all (const DoubleTabs &src, DoubleTabs &dest)
int envoyer_all_to_all (const Vect_ArrOfInt &src, Vect_ArrOfInt &dest)
int envoyer_all_to_all (const ArrOfInt &src, ArrOfInt &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int envoyer_all_to_all (const ArrOfDouble &src, ArrOfDouble &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int envoyer_all_to_all (std::vector< long long > &src, std::vector< long long > &dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
void envoyer_all_to_all (const DoubleTab &src, DoubleTab &dest)
On suppose que les tableaux en entree et en sortie
sont tels que dimension(0)==nproc() et que les autres dimensions
sont identiques. On envoie src(0, i, j, ...) au proc 0,
src(0, i, j, ...) au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest(0, i, j, ...) , processeur 1 dans dest(1, i, j, ...) , etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
int reverse_send_recv_pe_list (const ArrOfInt &src_list, ArrOfInt &dest_list)
Calcule la transposee d'une liste de processeurs:
On construit le tableau dest_list tel que:
x est dans la liste src_list sur le processeur y
si et seulement si
y est dans la liste dest_list sur le processeur x
En pratique, cette fonction permet de calculer la liste des
processeurs qui recoivent des messages si on connait la liste
des processeurs qui envoient des messages, et reciproquement.
Parametre: src_list
Signification: Une liste de numeros de PEs presents dans ce groupe de comm.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Parametre: dest_list
Signification: Le tableau ou stocker le resultat. On le met a la bonne taille
et on le remplit. Les numeros de PEs sont mis dans l'ordre
croissant.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
int comm_check_enabled ()
renvoie le drapeau Comm_Group::check_enabled().
Ce drapeau indique si le code tourne en mode DEBUG du parallele.
Dans ce cas, des communications supplementaires ont lieu pour
verifier la coherence du parallelisme et le mode de communication
est force en mode synchrone.
Cette methode permet de tester le drapeau, et s'il est mis de
realiser des verifications supplementaires
void assert_parallel (const double x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
void assert_parallel (const int x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
void assert_parallel (const Objet_U &obj)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs.
Ne fonctionne pas pour tous les types !
Pour l'instant ok pour Noms, Motcles et tableaux.
int is_parallel_object (const double x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
int is_parallel_object (const int x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
int is_parallel_object (const Objet_U &obj)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
Function Documentation
void assert_parallel (const double x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
Definition at line 763 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), and Process::Journal().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(x))
    {
      Cerr << "Fatal error in assert_parallel(const double x). See log files" << finl;
      Process::Journal() << "Error in assert_parallel(const double x)          )"
                         << "This processor has this value: " << x << finl;
      Process::barrier();
      Process::exit();
    }
}
void assert_parallel (const int x)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs
Definition at line 747 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), and Process::Journal().
Referenced by Schema_Temps_base::mettre_a_jour(), and mp_collective_op().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(x))
    {
      Cerr << "Fatal error in assert_parallel(const int x). See log files" << finl;
      Process::Journal() << "Error in assert_parallel(const int x)          )"
                         << "This processor has this value: " << x << finl;
      Process::barrier();
      Process::exit();
    }
}
void assert_parallel (const Objet_U & obj)
en mode comm_check_enabled(), verifie que le parametre
a la meme valeur sur tous les processeurs.
Ne fonctionne pas pour tous les types !
Pour l'instant ok pour Noms, Motcles et tableaux.
Definition at line 848 of file communications.cpp.
References Process::barrier(), Cerr, Comm_Group::check_enabled(), Process::exit(), finl, is_parallel_object(), Process::Journal(), and Objet_U::que_suis_je().
{
  if (!Comm_Group::check_enabled())
    return;
  if (!is_parallel_object(obj))
    {
      Cerr << "Fatal error in assert_parallel(const Objet_U & obj): objects do not match, see log files" << finl;
      Process::Journal() << "Error in assert_parallel(const Objet_U & obj)"
                         << "This processor has this object : " << obj.que_suis_je() << finl
                         << obj << finl;
      Process::barrier();
      Process::exit();
    }
}
int comm_check_enabled ()
renvoie le drapeau Comm_Group::check_enabled().
Ce drapeau indique si le code tourne en mode DEBUG du parallele.
Dans ce cas, des communications supplementaires ont lieu pour
verifier la coherence du parallelisme et le mode de communication
est force en mode synchrone.
Cette methode permet de tester le drapeau, et s'il est mis de
realiser des verifications supplementaires
Definition at line 717 of file communications.cpp.
References Comm_Group::check_enabled().
Referenced by Scatter::construire_md_vector().
{
  return Comm_Group::check_enabled();
}
int envoyer (const long & t, int source, int cible, int canal)
Definition at line 205 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const double & t, int source, int cible, int canal)
Definition at line 214 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const float & t, int cible, int canal)
Definition at line 233 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const double & t, int cible, int canal)
Definition at line 237 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const Objet_U & t, int cible, int canal)
Definition at line 241 of file communications.cpp.
References envoyer_buffered_(), and Process::me().
{
  return envoyer_buffered_(t, Process::me(), cible, canal);
}
int envoyer (const Objet_U & t, int source, int cible, int canal)
Definition at line 218 of file communications.cpp.
References envoyer_buffered_().
{
  return envoyer_buffered_(t, source, cible, canal);
}
int envoyer (const int & t, int source, int cible, int canal)
Definition at line 200 of file communications.cpp.
References envoyer_array_().
Referenced by add_sommets_communs(), Probleme_base::allocation(), Echange_contact_Correlation_VDF::calculer_CL(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), compute_global_connex_components(), mon_main::dowork(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VDF::init_tab_echange(), Sonde::initialiser(), is_parallel_object(), Echange_contact_Correlation_VDF::mettre_a_jour(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), Sous_Zone::readOn(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), and EcrFicPartage::syncfile().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const float & t, int source, int cible, int canal)
Definition at line 210 of file communications.cpp.
References envoyer_array_().
{
  return envoyer_array_(&t, 1, source, cible, canal);
}
int envoyer (const int & t, int cible, int canal)
Definition at line 223 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer (const long & t, int cible, int canal)
Definition at line 228 of file communications.cpp.
References envoyer_array_(), and Process::me().
{
  return envoyer_array_(&t, 1, Process::me(), cible, canal);
}
int envoyer_all_to_all (const DoubleTabs & src, DoubleTabs & dest)
Definition at line 452 of file communications.cpp.
References envoyer_all_to_all_(), Process::nproc(), and vect_impl::size().
Referenced by Moyenne_volumique::calculer_convolution(), Domain_Graph::construire_graph_elem_elem(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), MD_Vector_tools::extend(), find_matching_coordinates(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Scatter::lire_domaine(), MD_Vector_std::MD_Vector_std(), Champ_front_recyclage::mettre_a_jour(), and reverse_send_recv_pe_list().
{
// Je mets le assert ici car si on veut faire un envoyer_all_to_all(IntTab)
// le assert doit utiliser size_array()
  assert(src.size() == Process::nproc());
  assert(dest.size() == Process::nproc());
  return envoyer_all_to_all_(src, dest);
}
int envoyer_all_to_all (const Vect_ArrOfInt & src, Vect_ArrOfInt & dest)
Definition at line 461 of file communications.cpp.
References envoyer_all_to_all_(), and Process::nproc().
{
  assert(src.size() == Process::nproc());
  assert(dest.size() == Process::nproc());
  return envoyer_all_to_all_(src, dest);
}
int envoyer_all_to_all (const ArrOfInt & src, ArrOfInt & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 473 of file communications.cpp.
References ArrOfInt::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), ArrOfInt::inject_array(), Array_base::NOCOPY_NOINIT, Comm_Group::nproc(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.size_array() == grp.nproc());
  assert(dest.size_array() == grp.nproc());
  if (src.addr() == dest.addr())
    {
      ArrOfInt tmp;
      tmp.resize_array(grp.nproc(), Array_base::NOCOPY_NOINIT);
      grp.all_to_all(src.addr(), tmp.addr(), sizeof(int));
      dest.inject_array(tmp);
    }
  else
    {
      grp.all_to_all(src.addr(), dest.addr(), sizeof(int));
    }
  return 1;
}
int envoyer_all_to_all (const ArrOfDouble & src, ArrOfDouble & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 497 of file communications.cpp.
References ArrOfDouble::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), ArrOfDouble::inject_array(), Array_base::NOCOPY_NOINIT, Comm_Group::nproc(), ArrOfDouble::resize_array(), and ArrOfDouble::size_array().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.size_array() == grp.nproc());
  assert(dest.size_array() == grp.nproc());
  if (src.addr() == dest.addr())
    {
      ArrOfDouble tmp;
      tmp.resize_array(grp.nproc(), Array_base::NOCOPY_NOINIT);
      grp.all_to_all(src.addr(), tmp.addr(), sizeof(double));
      dest.inject_array(tmp);
    }
  else
    {
      grp.all_to_all(src.addr(), dest.addr(), sizeof(double));
    }
  return 1;
}
int envoyer_all_to_all (std::vector< long long > & src, std::vector< long long > & dest)
On suppose que les tableaux en entree et en sortie
sont de taille nproc() . On envoie src[0] au proc 0,
src[1] au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest[0], processeur 1 dans dest[1], etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 521 of file communications.cpp.
References Comm_Group::all_to_all(), PE_Groups::current_group(), and Comm_Group::nproc().
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(static_cast<int>(src.size()) == grp.nproc());
  assert(static_cast<int>(dest.size()) == grp.nproc());
  if (src.data() == dest.data())
    {
      std::vector<long long> tmp(grp.nproc(),0);
      grp.all_to_all(src.data(), tmp.data(), sizeof(long long));
      dest = tmp;
    }
  else
    {
      grp.all_to_all(src.data(), dest.data(), sizeof(long long));
    }
  return 1;
}
void envoyer_all_to_all (const DoubleTab & src, DoubleTab & dest)
On suppose que les tableaux en entree et en sortie
sont tels que dimension(0)==nproc() et que les autres dimensions
sont identiques. On envoie src(0, i, j, ...) au proc 0,
src(0, i, j, ...) au proc 1, etc... la valeur recue du processeur 0 et mise dans
dest(0, i, j, ...) , processeur 1 dans dest(1, i, j, ...) , etc...
Il est autorise d'appeler la fonction avec le meme tableau src et dest.
Definition at line 690 of file communications.cpp.
References ArrOfDouble::addr(), Comm_Group::all_to_all(), PE_Groups::current_group(), DoubleTab::dimension(), envoyer_all_to_all(), Comm_Group::nproc(), DoubleVect::size(), ArrOfDouble::size_array(), and sz.
{
  const Comm_Group& grp = PE_Groups::current_group();
  assert(src.dimension(0) == grp.nproc());
  assert(dest.dimension(0) == grp.nproc());
  assert(src.size_array() == dest.size_array());
  if (dest.addr() == src.addr())
    {
      DoubleTab tmp(src);
      envoyer_all_to_all(src, tmp);
      dest = tmp;
    }
  else
    {
      const int sz = src.size() / grp.nproc() * sizeof(double);
      grp.all_to_all(src.addr(), dest.addr(), sz);
    }
}
int envoyer_broadcast (long long & t, int source)
Definition at line 385 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (int & t, int source)
Definition at line 375 of file communications.cpp.
References envoyer_broadcast_().
Referenced by avancer_fichier(), compute_global_connex_components(), Sch_CN_iteratif::convergence(), Partitionneur_base::corriger_elem0_sur_proc0(), corriger_type(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Lec_Diffuse_base::eof(), Lec_Diffuse_base::fail(), Lec_Diffuse_base::get(), Lec_Diffuse_base::good(), Comm_Group::init_group(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), MaillerParallel::interpreter(), is_parallel_object(), Schema_Temps_base::mettre_a_jour(), Lec_Diffuse_base::operator>>(), LecFicDistribue::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDiffuse::ouvrir(), EcrFicCollecte::ouvrir(), EcrFicPartageMPIIO::put(), Debog_Pb::read_geometry_data(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Lec_Diffuse_base::set_bin(), Terme_Source_Canal_perio::source(), and verifier().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (long & t, int source)
Definition at line 380 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (float & t, int source)
Definition at line 389 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (double & t, int source)
Definition at line 393 of file communications.cpp.
References envoyer_broadcast_().
{
  return envoyer_broadcast_(&t, 1, source);
}
int envoyer_broadcast (Objet_U & t, int source)
Definition at line 397 of file communications.cpp.
References envoyer_broadcast_buffered_().
{
  return envoyer_broadcast_buffered_(t, source);
}
int is_parallel_object (const int x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
Definition at line 724 of file communications.cpp.
References mp_max(), and mp_min().
Referenced by assert_parallel(), and check_frontiere().
{
  const int x1 = mp_min(x);
  const int x2 = mp_max(x);
  return x1 == x2;
}
int is_parallel_object (const double x)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
Definition at line 733 of file communications.cpp.
References Comm_Group::COLL_MAX, Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double tab_x[2];
  tab_x[0] = x;
  tab_x[1] = x;
  double tab_y[2];
  Comm_Group::Collective_Op tab_op[] = { Comm_Group::COLL_MIN, Comm_Group::COLL_MAX };
  grp.mp_collective_op(tab_x, tab_y, tab_op, 2);
  return tab_y[0] == tab_y[1];
}
int is_parallel_object (const Objet_U & obj)
renvoie 1 (sur tous les procs) si le parametre est identique sur tous les procs,
sinon renvoie 0 (sur tous les procs)
< On a deja trouve une erreur, on recoit les autres messages mais c'est tout...
Definition at line 795 of file communications.cpp.
References Cerr, DERIV, envoyer(), envoyer_broadcast(), erreur(), Process::exit(), finl, Process::je_suis_maitre(), Process::nproc(), Objet_U::que_suis_je(), and recevoir().
{
  int erreur = 0;
  if (Process::je_suis_maitre())
    {
      DERIV(Objet_U) copie;
      const int n = Process::nproc();
      for (int i = 1; i < n; i++)
        {
          recevoir(copie, i, 67 /* tag */);
          if (erreur)
            continue; //!< On a deja trouve une erreur, on recoit les autres messages mais c'est tout...
          const Objet_U& obj2 = copie.valeur();
          if (obj2.que_suis_je() != obj.que_suis_je())
            {
              erreur = 1;
            }
          else
            {
// L'operateur == n'est pas virtuel, on ne peut pas se contenter de comparer avec ==.
// Il faut appeler == pour le sous-type specifique de l'objet.
// L'ordre est important: d'abord le type le plus derive, puis sa classe de base.
              if (compare<IntTab> (obj, obj2, erreur));
              else if (compare<DoubleTab> (obj, obj2, erreur));
              else if (compare<IntVect> (obj, obj2, erreur));
              else if (compare<DoubleVect> (obj, obj2, erreur));
              else if (compare<ArrOfInt> (obj, obj2, erreur));
              else if (compare<ArrOfDouble> (obj, obj2, erreur));
              else if (compare<Motcle> (obj, obj2, erreur));
              else if (compare<Nom> (obj, obj2, erreur));
              else
                {
                  Cerr << "Internal error in is_parallel_objec() : it is not coded for " << obj.que_suis_je() << finl;
                  Process::exit();
                }
            }
        }
    }
  else
    {
// On envoie un objet de type DERIV..
      DERIV(Objet_U) copie(obj);
      envoyer(copie, 0, 67 /* tag */);
    }
  envoyer_broadcast(erreur, 0 /* pe source */);
  return !erreur;
}
int mp_max (int i)
renvoie le plus grand int i sur l'ensemble des processeurs du
groupe courant.
Definition at line 588 of file communications.cpp.
References Comm_Group::COLL_MAX, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by is_parallel_object(), mp_max_abs_vect(), and mp_max_vect().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MAX);
  return y;
}
void mp_max_for_each_item (ArrOfInt &)
Definition at line 675 of file communications.cpp.
References Comm_Group::COLL_MAX, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), Sonde::initialiser(), mp_max_abs_tab(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_MAX);
}
void mp_max_for_each_item (ArrOfDouble &)
Definition at line 679 of file communications.cpp.
References Comm_Group::COLL_MAX, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_MAX);
}
int mp_min (int i)
renvoie le plus petit int i sur l'ensemble des processeurs du
groupe courant.
Definition at line 598 of file communications.cpp.
References Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by corriger_type(), Champ_P1NC_implementation::filtrer_resu(), is_parallel_object(), mp_min_abs_vect(), and mp_min_vect().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MIN);
  return y;
}
void mp_min_for_each_item (ArrOfDouble &)
Definition at line 671 of file communications.cpp.
References Comm_Group::COLL_MIN, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_MIN);
}
void mp_min_for_each_item (ArrOfInt &)
Definition at line 667 of file communications.cpp.
References Comm_Group::COLL_MIN, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_MIN);
}
void mp_sum_for_each_item (ArrOfDouble &)
Definition at line 663 of file communications.cpp.
References Comm_Group::COLL_SUM, and mp_collective_op().
{
  mp_collective_op(x, Comm_Group::COLL_SUM);
}
void mp_sum_for_each_item (ArrOfInt &)
Definition at line 659 of file communications.cpp.
References Comm_Group::COLL_SUM, and mp_collective_op().
Referenced by Stat_Results::compute_min_max_avg(), Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), T_It_VDF_Face< _TYPE_ >::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Grad_VEF_P1B_Face::impr(), Source_base::impr(), Op_Diff_CoviMAC_base::impr(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), EOS_Tools_VDF::moyenne_vol(), mp_carre_norme_tab(), and print_stat().
{
  mp_collective_op(x, Comm_Group::COLL_SUM);
}
int mppartial_sum (int i)
Calul de la somme partielle de i sur les processeurs 0 a me()-1
(renvoie 0 sur le processeur 0). Voir Comm_Group::mppartial_sum()
Definition at line 608 of file communications.cpp.
References Comm_Group::COLL_PARTIAL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), compute_global_connex_components(), Domain_Graph::construire_graph_elem_elem(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), Traduction_Indice_Global_Local::initialiser(), EcrFicPartageMPIIO::put(), and Champ_Fonc_MED::readOn().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_PARTIAL_SUM);
  return y;
}
void mpsum_multiple (double & x1, double & x2)
Definition at line 617 of file communications.cpp.
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Solv_GCP::resoudre_().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double x[2];
  double y[2];
  x[0] = x1;
  x[1] = x2;
  grp.mp_collective_op(x, y, 2, Comm_Group::COLL_SUM);
  x1 = y[0];
  x2 = y[1];
}
int recevoir (float & t, int source, int cible, int canal)
Definition at line 256 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (int & t, int source, int canal)
Definition at line 269 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (Objet_U & t, int source, int cible, int canal)
Definition at line 264 of file communications.cpp.
References recevoir_buffered_().
{
  return recevoir_buffered_(t, source, cible, canal);
}
int recevoir (long & t, int source, int canal)
Definition at line 274 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (Objet_U & t, int source, int canal)
Definition at line 287 of file communications.cpp.
References Process::me(), and recevoir_buffered_().
{
  return recevoir_buffered_(t, source, Process::me(), canal);
}
int recevoir (double & t, int source, int canal)
Definition at line 283 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (double & t, int source, int cible, int canal)
Definition at line 260 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (long & t, int source, int cible, int canal)
Definition at line 251 of file communications.cpp.
References recevoir_array_().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int recevoir (float & t, int source, int canal)
Definition at line 279 of file communications.cpp.
References Process::me(), and recevoir_array_().
{
  return recevoir_array_(&t, 1, source, Process::me(), canal);
}
int recevoir (int & t, int source, int cible, int canal)
Definition at line 246 of file communications.cpp.
References recevoir_array_().
Referenced by add_sommets_communs(), Probleme_base::allocation(), Echange_contact_Correlation_VDF::calculer_CL(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), compute_global_connex_components(), mon_main::dowork(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VDF::init_tab_echange(), Sonde::initialiser(), is_parallel_object(), Echange_contact_Correlation_VDF::mettre_a_jour(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), Sous_Zone::readOn(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), and EcrFicPartage::syncfile().
{
  return recevoir_array_(&t, 1, source, cible, canal);
}
int reverse_send_recv_pe_list (const ArrOfInt & src_list, ArrOfInt & dest_list)
Calcule la transposee d'une liste de processeurs:
On construit le tableau dest_list tel que:
x est dans la liste src_list sur le processeur y
si et seulement si
y est dans la liste dest_list sur le processeur x
En pratique, cette fonction permet de calculer la liste des
processeurs qui recoivent des messages si on connait la liste
des processeurs qui envoient des messages, et reciproquement.
Parametre: src_list
Signification: Une liste de numeros de PEs presents dans ce groupe de comm.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Parametre: dest_list
Signification: Le tableau ou stocker le resultat. On le met a la bonne taille
et on le remplit. Les numeros de PEs sont mis dans l'ordre
croissant.
Ce sont les indices des pes dans le groupe courant (0 <= pe < nproc_)
Definition at line 561 of file communications.cpp.
References PE_Groups::current_group(), envoyer_all_to_all(), max_array(), min_array(), Comm_Group::nproc(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
Referenced by Scatter::ajouter_joints(), Schema_Comm::check_send_recv_pe_list(), and Zone::creer_aretes().
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int np = grp.nproc();
  assert(src_list.size_array() == 0 || max_array(src_list) < np);
  assert(src_list.size_array() == 0 || min_array(src_list) >= 0);
  ArrOfInt flag(np);
  int i;
  const int src_size = src_list.size_array();
  for (i = 0; i < src_size; i++)
    {
      const int pe = src_list[i];
      flag[pe] = 1;
    }
  ArrOfInt flag_recv(np);
  envoyer_all_to_all(flag, flag_recv);
  int n = 0;
  dest_list.resize_array(np);
  for (i = 0; i < np; i++)
    if (flag_recv[i])
      dest_list[n++] = i;
  dest_list.resize_array(n);
  return 1;
}