TRUST: src/Kernel/Utilitaires/communications_array.h File Reference
communications_array.h File Reference
#include <Comm_Group.h>
#include <PE_Groups.h>
#include <arch.h>
Functions
template<typename _TYPE_ >
std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type envoyer_array (const _TYPE_ *objet, int n, int source, int cible, int canal)
int envoyer_array (const long *t, int n, int source, int cible, int canal)
template<typename _TYPE_ >
std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type recevoir_array (const _TYPE_ *objet, int n, int source, int cible, int canal)
int recevoir_array (const long *t, int n, int source, int cible, int canal)
template<typename _TYPE_ >
std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type envoyer_broadcast_array (_TYPE_ *objet, int n, int source)
int envoyer_broadcast_array (long *t, int n, int source)
Function Documentation
envoyer_array() [1/2]
template<typename _TYPE_ > std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type envoyer_array (const _TYPE_ * objet, int n, int source, int cible, int canal) inline
Definition at line 32 of file communications_array.h.
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int moi = grp.rank();
  if (moi == cible)
    return 0;
  if (source != moi && source != -1)
    return 0;
  const char *data = (const char*) objet;
  const int sz = sizeof(_TYPE_) * n;
  if (cible < 0)
    {
      const int nbproc = grp.nproc();
      for (int i = 0; i < nbproc; i++)
        {
          if (i != moi)
            {
// En mode check, on verifie que n est bien le meme sur l'expediteur et le recepteur
              if (grp.check_enabled())
                grp.send(i, &sz, sizeof(int), canal);
              if (sz > 0)
                grp.send(i, data, sz, canal);
            }
        }
    }
  else
    {
      if (grp.check_enabled())
        grp.send(cible, &sz, sizeof(int), canal);
      if (sz > 0)
        grp.send(cible, data, sz, canal);
    }
  return 1;
}
References Comm_Group::check_enabled(), PE_Groups::current_group(), Comm_Group::nproc(), Comm_Group::rank(), and Comm_Group::send().
envoyer_array() [2/2]
int envoyer_array (const long * t, int n, int source, int cible, int canal) inline
Definition at line 70 of file communications_array.h.
{
  return envoyer_array<long>(t,n,source,cible,canal);
}
envoyer_broadcast_array() [1/2]
template<typename _TYPE_ > std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type envoyer_broadcast_array (_TYPE_ * objet, int n, int source) inline
Definition at line 114 of file communications_array.h.
{
  const Comm_Group& grp = PE_Groups::current_group();
  if (grp.check_enabled())
    {
      int copie_n = n;
      grp.broadcast(&copie_n, sizeof(int), source);
      if (copie_n != n)
        {
          Cerr << "Error in template<typename _TYPE_> envoyer_broadcast_array !" << finl;
          Process::exit();
        }
    }
  grp.broadcast(objet, sizeof(_TYPE_) * n, source);
  return 1;
}
References Comm_Group::broadcast(), Cerr, Comm_Group::check_enabled(), PE_Groups::current_group(), Process::exit(), and finl.
Referenced by Lec_Diffuse_base::get(), and Lec_Diffuse_base::get_template().
envoyer_broadcast_array() [2/2]
int envoyer_broadcast_array (long * t, int n, int source) inline
Definition at line 132 of file communications_array.h.
{
  return envoyer_broadcast_array<long>(t, n, source);
}
recevoir_array() [1/2]
template<typename _TYPE_ > std::enable_if< std::is_arithmetic< _TYPE_ >::value, int >::type recevoir_array (const _TYPE_ * objet, int n, int source, int cible, int canal) inline
Definition at line 78 of file communications_array.h.
{
  const Comm_Group& grp = PE_Groups::current_group();
  const int moi = grp.rank();
  if (moi == source)
    return 0;
  if (cible != moi && cible != -1)
    return 0;
  const int sz = sizeof(_TYPE_) * n;
  if (grp.check_enabled())
    {
      int sz_check;
      grp.recv(source, &sz_check, sizeof(int), canal);
      if (sz_check != sz)
        {
          Cerr << "Fatal error in template<typename _TYPE_> int recevoir_array : incorrect size\n" << " sent=" << sz_check << " expected=" << sz << finl;
          Process::exit();
        }
    }
  char *data = (char*) objet;
  if (sz > 0)
    grp.recv(source, data, sz, canal);
  return 1;
}
References Cerr, Comm_Group::check_enabled(), PE_Groups::current_group(), Process::exit(), finl, Comm_Group::rank(), and Comm_Group::recv().
recevoir_array() [2/2]
int recevoir_array (const long * t, int n, int source, int cible, int canal) inline
Definition at line 106 of file communications_array.h.
{
  return recevoir_array<long>(t, n, source, cible, canal);
}