TRUST: src/Kernel/Math/ConstDoubleTab_parts.cpp File Reference
src/Kernel/Math/ConstDoubleTab_parts.cpp File Reference
#include <ConstDoubleTab_parts.h>
#include <MD_Vector_composite.h>
#include <IntTab.h>
Functions
static void init_parts (DoubleVect &vect, Vect_DoubleTab &parts, DoubleTab *dummy_type_ptr)
static void init_parts (IntVect &vect, Vect_IntTab &parts, IntTab *dummy_type_ptr)
Function Documentation
static void init_parts (DoubleVect & vect, Vect_DoubleTab & parts, DoubleTab * dummy_type_ptr) [static]
Definition at line 28 of file ConstDoubleTab_parts.cpp.
References MD_Vector_composite::data_, DoubleTab::dimension_tot(), DoubleVect::get_md_vector(), MD_Vector_base::get_nb_items_tot(), DoubleVect::line_size(), max(), DoubleTab::nb_dim(), MD_Vector::non_nul(), MD_Vector_composite::parts_offsets_, DoubleTab::ref(), DoubleTab::ref_array(), ref_cast, DoubleTab::resize(), ArrOfInt::resize(), ArrOfInt::resize_array(), DoubleTab::set_md_vector(), MD_Vector_composite::shapes_, Vect_MD_Vector::size(), ArrOfInt::size_array(), DoubleVect::size_totale(), sub_type, and MD_Vector::valeur().
Referenced by ConstDoubleTab_parts::ConstDoubleTab_parts(), ConstIntTab_parts::ConstIntTab_parts(), DoubleTab_parts::DoubleTab_parts(), IntTab_parts::initialize(), ConstIntTab_parts::initialize(), DoubleTab_parts::initialize(), ConstDoubleTab_parts::initialize(), and IntTab_parts::IntTab_parts().
{
  const MD_Vector& md = vect.get_md_vector();
  if (! md.non_nul() || !sub_type(MD_Vector_composite, md.valeur()))
    {
// Ce n'est pas un tableau a plusieurs sous-parties, on cree juste une
// partie qui pointe sur vect.
      parts.dimensionner(1);
      DoubleTab& part = parts[0];
// On preserve le 'shape' du tableau de depart, si c'est un DoubleTab...
      if (sub_type(DoubleTab, vect))
        part.ref(ref_cast(DoubleTab, vect));
      else
        part.ref(vect);
    }
  else
    {
      ArrOfInt shape;
      const int line_size = vect.line_size();
      if (sub_type(DoubleTab, vect))
        {
          const DoubleTab& tab = ref_cast(DoubleTab, vect);
          const int n = tab.nb_dim();
          shape.resize_array(n);
          for (int i = 0; i < n; i++)
            shape[i] = tab.dimension_tot(i);
        }
      else
        {
          if (line_size == 1)
            {
              shape.resize_array(1);
              shape[0] = vect.size_totale();
            }
          else
            {
              shape.resize_array(2);
              shape[0] = vect.size_totale() / line_size;
              shape[1] = line_size;
            }
        }
      const MD_Vector_composite& mdata = ref_cast(MD_Vector_composite, md.valeur());
      const int n = mdata.data_.size();
      parts.dimensionner(n);
      for (int i = 0, j; i < n; i++)
        {
          ArrOfInt shape_i;
          if (mdata.shapes_[i] == 0) shape_i = shape; //si mdata.shapes_[i] > 0, alors la sous-partie a une dimension mineure en plus
          else for (shape_i.resize(shape.size_array() + 1), shape_i(1) = mdata.shapes_[i], j = 1; j < shape.size_array(); j++) shape_i(j + 1) = shape(j);
          const int offset = mdata.parts_offsets_[i];
          const MD_Vector& md_part = mdata.data_[i];
          shape_i[0] = md_part.valeur().get_nb_items_tot();
          DoubleTab& part = parts[i];
// Fait pointer la zone de memoire sur le sous-tableau (pour l'instant tableau monodimensionnel)
          part.ref_array(vect, offset * line_size, shape_i[0] * line_size * max(mdata.shapes_[i], 1));
// Change le "shape" du tableau pour mettre le nombre de lignes et de colonnes
// (nombre total d'items inchange, donc resize autorise)
          part.resize(shape_i);
// Associe le md_vector
          part.set_md_vector(md_part);
        }
    }
}
static void init_parts (IntVect & vect, Vect_IntTab & parts, IntTab * dummy_type_ptr) [static]
Definition at line 93 of file ConstDoubleTab_parts.cpp.
References MD_Vector_composite::data_, IntTab::dimension_tot(), IntVect::get_md_vector(), MD_Vector_base::get_nb_items_tot(), IntVect::line_size(), max(), IntTab::nb_dim(), MD_Vector::non_nul(), MD_Vector_composite::parts_offsets_, IntTab::ref(), IntTab::ref_array(), ref_cast, IntTab::resize(), ArrOfInt::resize(), ArrOfInt::resize_array(), IntTab::set_md_vector(), MD_Vector_composite::shapes_, Vect_MD_Vector::size(), ArrOfInt::size_array(), IntVect::size_totale(), sub_type, and MD_Vector::valeur().
{
  const MD_Vector& md = vect.get_md_vector();
  if (! md.non_nul() || !sub_type(MD_Vector_composite, md.valeur()))
    {
// Ce n'est pas un tableau a plusieurs sous-parties, on cree juste une
// partie qui pointe sur vect.
      parts.dimensionner(1);
      IntTab& part = parts[0];
// On preserve le 'shape' du tableau de depart, si c'est un DoubleTab...
      if (sub_type(IntTab, vect))
        part.ref(ref_cast(IntTab, vect));
      else
        part.ref(vect);
    }
  else
    {
      ArrOfInt shape;
      const int line_size = vect.line_size();
      if (sub_type(IntTab, vect))
        {
          const IntTab& tab = ref_cast(IntTab, vect);
          const int n = tab.nb_dim();
          shape.resize_array(n);
          for (int i = 0; i < n; i++)
            shape[i] = tab.dimension_tot(i);
        }
      else
        {
          if (line_size == 1)
            {
              shape.resize_array(1);
              shape[0] = vect.size_totale();
            }
          else
            {
              shape.resize_array(2);
              shape[0] = vect.size_totale() / line_size;
              shape[1] = line_size;
            }
        }
      const MD_Vector_composite& mdata = ref_cast(MD_Vector_composite, md.valeur());
      const int n = mdata.data_.size();
      parts.dimensionner(n);
      for (int i = 0, j; i < n; i++)
        {
          ArrOfInt shape_i;
          if (mdata.shapes_[i] == 0) shape_i = shape; //si mdata.shapes_[i] > 0, alors la sous-partie a une dimension mineure en plus
          else for (shape_i.resize(shape.size_array() + 1), shape_i(1) = mdata.shapes_[i], j = 1; j < shape.size_array(); j++) shape_i(j + 1) = shape(j);
          const int offset = mdata.parts_offsets_[i];
          const MD_Vector& md_part = mdata.data_[i];
          shape_i[0] = md_part.valeur().get_nb_items_tot();
          IntTab& part = parts[i];
// Fait pointer la zone de memoire sur le sous-tableau (pour l'instant tableau monodimensionnel)
          part.ref_array(vect, offset * line_size, shape_i[0] * line_size * max(mdata.shapes_[i], 1));
// Change le "shape" du tableau pour mettre le nombre de lignes et de colonnes
// (nombre total d'items inchange, donc resize autorise)
          part.resize(shape_i);
// Associe le md_vector
          part.set_md_vector(md_part);
        }
    }
}