TRUST: src/ThHyd/Incompressible/Equations/Convection_Diffusion_Temperature.cpp File Reference
Convection_Diffusion_Temperature.cpp File Reference
#include <Convection_Diffusion_Temperature.h>
#include <Navier_Stokes_std.h>
#include <Probleme_base.h>
#include <Fluide_Ostwald.h>
#include <Discret_Thyd.h>
#include <Frontiere_dis_base.h>
#include <Param.h>
#include <Transport_Interfaces_base.h>
#include <Fluide_base.h>
#include <TRUSTTrav.h>
#include <SFichier.h>
#include <Zone_VF.h>
#include <Matrice_Morse.h>
#include <Champ_Uniforme.h>
#include <Matrice_Morse_Sym.h>
#include <Statistiques.h>
Functions
int string2int (const char *digit, int &result)
void ouvrir_fichier_pena_th (SFichier &os, const Nom &type, const int flag, const Transport_Interfaces_base &equation)
Variables
Stat_Counter_Id assemblage_sys_counter_
Stat_Counter_Id source_counter_
const Type_info * Convection_Diffusion_Temperaturebases [1] ={ &(Convection_Diffusion_std ::info_obj)}
const Type_info * Vect_RefObjUbases [1] ={ &(vect_impl ::info_obj)}
Function Documentation
ouvrir_fichier_pena_th()
void ouvrir_fichier_pena_th (SFichier & os, const Nom & type, const int flag, const Transport_Interfaces_base & equation)
Definition at line 1362 of file Convection_Diffusion_Temperature.cpp.
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
  Nom fichier=Objet_U::nom_du_cas();
  fichier+="_";
  fichier+=type;
  fichier+="_";
  fichier+=equation.le_nom();
  fichier+=".out";
  const Schema_Temps_base& sch=equation.probleme().schema_temps();
  const int precision=sch.precision_impr();
// On cree le fichier a la premiere impression avec l'en tete
  if (sch.nb_impr()==1 && !equation.probleme().reprise_effectuee())
    {
      os.ouvrir(fichier);
      SFichier& fic=os;
      Nom espace="\t\t";
      fic << (Nom)"# Impression puissance thermique";
      fic << " interface " << equation.le_nom();
      fic << " en W" << "." << finl;
      fic << finl << "# Temps";
      Nom ch=espace;
      ch+="P";
      fic << ch << finl;
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(fichier,ios::app);
    }
  os.precision(precision);
  os.setf(ios::scientific);
}
References finl, Equation_base::le_nom(), Schema_Temps_base::nb_impr(), Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Sortie_Fichier_base::setf().
Referenced by Convection_Diffusion_Temperature::ecrire_fichier_pena_th().
string2int()
int string2int (const char * digit, int & result) inline
Definition at line 372 of file Convection_Diffusion_Temperature.cpp.
{
  result = 0;
// --- Convert each digit char and add into result.
  while (*digit >= '0' && *digit <='9')
    {
      result = (result * 10) + (*digit - '0');
      digit++;
    }
// --- Check that there were no non-digits at end.
  if (*digit != 0)
    {
      return 0;
    }
  return 1;
}
Referenced by Convection_Diffusion_Temperature::creer_champ().
Variable Documentation
assemblage_sys_counter_
Stat_Counter_Id assemblage_sys_counter_ extern
Definition at line 60 of file stat_counters.cpp.
Referenced by Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Temperature::assembler_blocs(), declare_stat_counters(), and print_statistics_analyse().
Convection_Diffusion_Temperaturebases
const Type_info* Convection_Diffusion_Temperaturebases[1] ={ &(Convection_Diffusion_std ::info_obj)}
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
source_counter_
Stat_Counter_Id source_counter_ extern
Definition at line 54 of file stat_counters.cpp.
Referenced by Convection_Diffusion_Temperature::assembler_blocs(), declare_stat_counters(), and print_statistics_analyse().
Vect_RefObjUbases
const Type_info* Vect_RefObjUbases[1] ={ &(vect_impl ::info_obj)}
Definition at line 37 of file Convection_Diffusion_Temperature.cpp.