TRUST: src/Kernel/Framework/Convection_tools.cpp File Reference
src/Kernel/Framework/Convection_tools.cpp File Reference
#include <ArrOfInt.h>
#include <Double.h>
#include <Convection_tools.h>
Functions
double minmod (double grad1, double grad2)
double vanleer (double grad1, double grad2)
double vanalbada (double grad1, double grad2)
double chakravarthy (double grad1, double grad2)
double superbee (double grad1, double grad2)
Function Documentation
double chakravarthy (double grad1, double grad2)
< 1<<beta<<2
Definition at line 53 of file Convection_tools.cpp.
References dmax(), and dmin().
Referenced by Op_Conv_VEF_Face::readOn(), and Op_Conv_Muscl3_VEF_Face::readOn().
{
  /*
    Cerr << " limiteur chakavarthy non preconise (non symetrique) " << finl;
    exit();
    return 0;
  */
  double gradlim=0.;
  if ((grad1*grad2)>0)
    {
      gradlim=dmin(grad1/grad2,1.8); //!< 1<<beta<<2
      gradlim=dmax(gradlim,0.);
      gradlim*=grad2;
    }
  return gradlim;
}
double minmod (double grad1, double grad2)
Definition at line 31 of file Convection_tools.cpp.
References dabs().
Referenced by Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::readOn(), Op_Conv_Muscl_New_VEF_Face::readOn(), and Op_Conv_Muscl3_VEF_Face::readOn().
{
  double gradlim=0.;
  if(grad1*grad2>0.) (dabs(grad1)<dabs(grad2)) ? gradlim=grad1 : gradlim=grad2 ;
  return gradlim;
}
double superbee (double grad1, double grad2)
Definition at line 70 of file Convection_tools.cpp.
References dmax(), and dmin().
Referenced by Op_Conv_VEF_Face::readOn(), and Op_Conv_Muscl3_VEF_Face::readOn().
{
  /*
    Cerr << " limiteur superbee non preconise (source d'instabilites) " << finl;
    exit();
    return 0;
  */
  double gradlim=0.;
  if ((grad1*grad2)>0)
    {
      double gradlim1,gradlim2;
      gradlim1=dmin(2*(grad1/grad2),1);
      gradlim2=dmin(grad1/grad2,2);
      gradlim=dmax(gradlim1,gradlim2);
      gradlim=dmax(gradlim,0.);
      gradlim*=grad2;
    }
  return gradlim;
}
double vanalbada (double grad1, double grad2)
Definition at line 45 of file Convection_tools.cpp.
Referenced by Op_Conv_VEF_Face::readOn(), and Op_Conv_Muscl3_VEF_Face::readOn().
{
  double gradlim=0.;
  if(grad1*grad2>0.) gradlim=grad1*grad2*(grad1+grad2)/(grad1*grad1+grad2*grad2) ;
  return gradlim;
}
double vanleer (double grad1, double grad2)
Definition at line 38 of file Convection_tools.cpp.
Referenced by Op_Conv_VEF_Face::readOn(), Op_Conv_Muscl_VEF_Face::readOn(), and Op_Conv_Muscl3_VEF_Face::readOn().
{
  double gradlim=0.;
  if(grad1*grad2>0.) gradlim=2.*grad1*grad2/(grad1+grad2) ;
  return gradlim;
}