TRUST: src/Kernel/Framework/Debog.cpp File Reference
src/Kernel/Framework/Debog.cpp File Reference
#include <Debog_Pb.h>
#include <Debog.h>
#include <Probleme_base.h>
#include <Equation.h>
#include <Zone_VF.h>
#include <Domaine.h>
#include <Param.h>
#include <MD_Vector_std.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <Octree_Double.h>
#include <ConstDoubleTab_parts.h>
#include <PE_Groups.h>
#include <Interprete_bloc.h>
#include <EChaine.h>
#include <Old_Debog.h>
#include <Matrice_Base.h>
#include <communications.h>
#include <DoubleTab.h>
#include <IntTab.h>
Enumerations
enum Debog_Exceptions { RENUM_ARRAY_NOT_FOUND }
Functions
static void debog_breakpoint ()
void debog_break_test (int msg)
int operator== (const Ref_Debog_Pb &r1, const Ref_Debog_Pb &r2)
Variables
static int msg_debog_breakpoint = 0
const Type_info * Debog_Pbbases [1] = { &(Objet_U ::info_obj)}
const Type_info * Old_Debogbases [1] = { &(Interprete ::info_obj)}
const Type_info * Ref_Debog_Pbbases [1] = { &(Ref_ ::info_obj)}
Enumeration Type Documentation
enum Debog_Exceptions
Enumerator:
RENUM_ARRAY_NOT_FOUND
Definition at line 445 of file Debog.cpp.
{ RENUM_ARRAY_NOT_FOUND };
Function Documentation
void debog_break_test (int msg)
Definition at line 60 of file Debog.cpp.
References debog_breakpoint(), and msg_debog_breakpoint.
Referenced by Debog_Pb::verifier().
{
  if (msg == msg_debog_breakpoint)
    debog_breakpoint();
}
static void debog_breakpoint () [static]
Definition at line 56 of file Debog.cpp.
Referenced by debog_break_test().
{
}
int operator== (const Ref_Debog_Pb & r1, const Ref_Debog_Pb & r2)
Definition at line 80 of file Debog.cpp.
Variable Documentation
const Type_info* Debog_Pbbases[1] = { &(Objet_U ::info_obj)}
Definition at line 77 of file Debog.cpp.
int msg_debog_breakpoint = 0 [static]
Definition at line 55 of file Debog.cpp.
Referenced by debog_break_test().
const Type_info* Old_Debogbases[1] = { &(Interprete ::info_obj)}
Definition at line 79 of file Debog.cpp.
const Type_info* Ref_Debog_Pbbases[1] = { &(Ref_ ::info_obj)}
Definition at line 80 of file Debog.cpp.