TRUST: src/Kernel/Framework/Debog_Pb.tpp File Reference
Debog_Pb.tpp File Reference
Macros
#define Debog_Pb_TPP_included
Functions
void debog_breakpoint ()
void debog_break_test (int msg)
Variables
static int msg_debog_breakpoint = 0
Macro Definition Documentation
Debog_Pb_TPP_included
#define Debog_Pb_TPP_included
Definition at line 17 of file Debog_Pb.tpp.
Function Documentation
debog_break_test()
void debog_break_test (int msg) inline
Definition at line 22 of file Debog_Pb.tpp.
{ if (msg == msg_debog_breakpoint) debog_breakpoint(); }
References debog_breakpoint(), and msg_debog_breakpoint.
Referenced by Debog_Pb::verifier().
debog_breakpoint()
void debog_breakpoint () inline
Definition at line 21 of file Debog_Pb.tpp.
{ }
Referenced by debog_break_test().
Variable Documentation
msg_debog_breakpoint
int msg_debog_breakpoint = 0 static
Definition at line 20 of file Debog_Pb.tpp.
Referenced by debog_break_test().