TRUST: src/Kernel/Geometrie/DecoupeBord.cpp File Reference
DecoupeBord.cpp File Reference
#include <DecoupeBord.h>
#include <EFichier.h>
#include <TRUSTArrays.h>
#include <Param.h>
#include <SFichier.h>
#include <Parser_U.h>
Functions
void create_listb_from_domaine2 (const Domaine &dom1, const Domaine &dom2, const Noms &nomdec)
void create_listb_from_xyz (const Domaine &dom1, const Noms &nomdec, const Noms &expr)
void create_listb_naif (const Domaine &dom1, const Noms &nomdec, const ArrOfInt &nbdec)
void create_listb_geom (const Domaine &dom1, const Noms &nomdec, const ArrOfInt &nbdec)
Variables
const Type_info * DecoupeBordbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
create_listb_from_domaine2()
void create_listb_from_domaine2 (const Domaine & dom1, const Domaine & dom2, const Noms & nomdec)
< centre de gravite face de fr1
< centre de gravite face de fr2
< Generation de Liste_faces_associees
< centre de gravite de la face1 (non divise par nb_som_face)
< Ecriture des fichiers de sortie
Definition at line 35 of file DecoupeBord.cpp.
{
  const DoubleTab& xs1=dom1.coord_sommets();
  const Zone& zone1=dom1.zone(0);
  const DoubleTab& xs2=dom2.coord_sommets();
  const Zone& zone2=dom2.zone(0);
  int nbfr=zone1.nb_front_Cl();
  SFichier listb(dom1.le_nom()+".boundary_list");
  for (int l=0; l<nbfr; l++)
    {
      const Frontiere& fr1=zone1.frontiere(l);
      const Nom& nomfr1=fr1.le_nom();
      int l2=zone2.rang_frontiere(nomfr1);
      if(l2<0)
        {
          Cerr << " The domains " << dom1.le_nom() << " and " << dom2.le_nom() << " do not have the same names of boundaries " << finl;
          Cerr<<nomfr1<<" not found in "<<dom1.le_nom() <<finl;
          Cerr << " Make sure they were generated in a similar way (almost to the mesh size) " << finl;
          Process::exit();
        }
      const Frontiere& fr2=zone2.frontiere(l2);
      if (nomdec.search(nomfr1)!=-1)
        {
          int nbfaces1=fr1.nb_faces();
          const IntTab& sommets_face1 = (ref_cast(Frontiere,fr1)).les_sommets_des_faces();
          int nbfaces2=fr2.nb_faces();
          const IntTab& sommets_face2 = (ref_cast(Frontiere,fr2)).les_sommets_des_faces();
          ArrsOfInt faces_associees(nbfaces2);
          ArrOfDouble xg1(Objet_U::dimension); //!< centre de gravite face de fr1
          ArrOfDouble xg2(Objet_U::dimension); //!< centre de gravite face de fr2
          int face1,face2,i,j;
          int nb_som_face=sommets_face1.dimension(1);
          for (face1=0; face1<nbfaces1; face1++) //!< Generation de Liste_faces_associees
            {
              xg1=0.;
              for (i=0; i<nb_som_face; i++)
                for (j=0; j<Objet_U::dimension; j++)
                  xg1[j]+=xs1(sommets_face1(face1,i),j);  //!< centre de gravite de la face1 (non divise par nb_som_face)
// recherche de la face de dom2 correspondante
              double dist_min=1.e6;
              int           face_min=-1;
              for (face2=0; face2<nbfaces2; face2++)
                {
                  xg2=0.;
                  for (i=0; i<nb_som_face; i++)
                    for (j=0; j<Objet_U::dimension; j++)
                      xg2[j]+=xs2(sommets_face2(face2,i),j);  //centre de gravite de la face2 (non divise par nb_som_face)
                  double dist=0.;
                  for (j=0; j<Objet_U::dimension; j++) dist+=(xg2[j]-xg1[j])*(xg2[j]-xg1[j]);
                  if(dist<dist_min)
                    {
                      dist_min=dist ;
                      face_min=face2;
                    }
                }
              faces_associees[face_min].set_smart_resize(1);
              faces_associees[face_min].append_array(face1);
            }
          for (face2=0; face2<nbfaces2; face2++) //!< Ecriture des fichiers de sortie
            {
              Nom nomfic(nomfr1);
              nomfic+="%";
              Nom n;
              n=face2;
              nomfic+=n;
              SFichier s(nomfic);
              s<<faces_associees[face2]<<finl;
              listb<<nomfic<<finl;
              s.close();
            }
        }
    }
  listb.close();
}
References Cerr, Sortie_Fichier_base::close(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, Zone::frontiere(), Domaine::le_nom(), Frontiere::le_nom(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Zone::rang_frontiere(), ref_cast, Noms::search(), and Domaine::zone().
Referenced by DecoupeBord::interpreter_().
create_listb_from_xyz()
void create_listb_from_xyz (const Domaine & dom1, const Noms & nomdec, const Noms & expr)
< dimensionnement en dur qui devrait suffire
< centre de gravite face de fr1
< Generation de Liste_faces_associees
< centre de gravite de la face1 (non divise par nb_som_face)
< Ecriture des fichiers de sortie
Definition at line 133 of file DecoupeBord.cpp.
{
  int n1=nomdec.size();
  int n2=expr.size();
  if(n1!=n2)
    {
      Cerr<<"The numbers of boundaries in 'bords_a_decouper' and 'condition_geometrique' have to be the same"<<finl;
      Process::exit();
    }
  const DoubleTab& xs1=dom1.coord_sommets();
  const Zone& zone1=dom1.zone(0);
  Parser_U parser;
  parser.setNbVar(Objet_U::dimension);
  parser.addVar("x");
  parser.addVar("y");
  if (Objet_U::dimension==3)
    parser.addVar("z");
  int nbfr=zone1.nb_front_Cl();
  SFichier listb(dom1.le_nom()+".boundary_list");
  for (int l=0; l<nbfr; l++)
    {
      const Frontiere& fr1=zone1.frontiere(l);
      const Nom& nomfr1=fr1.le_nom();
      int inc=nomdec.search(nomfr1);
      if (inc!=-1)
        {
          Nom expr2(expr[inc]);
          parser.setString(expr2);
          parser.parseString();
          int nbfaces1=fr1.nb_faces();
          const IntTab& sommets_face1 = (ref_cast(Frontiere,fr1)).les_sommets_des_faces();
          ArrsOfInt faces_associees(1000); //!< dimensionnement en dur qui devrait suffire
          ArrOfDouble xg1(Objet_U::dimension); //!< centre de gravite face de fr1
          int face1,i,j;
          int nb_som_face=sommets_face1.dimension(1);
          int nb=0;
          for (face1=0; face1<nbfaces1; face1++) //!< Generation de Liste_faces_associees
            {
              xg1=0.;
              for (i=0; i<nb_som_face; i++)
                for (j=0; j<Objet_U::dimension; j++)
                  xg1[j]+=xs1(sommets_face1(face1,i),j);  //!< centre de gravite de la face1 (non divise par nb_som_face)
              xg1/=nb_som_face;
              parser.setVar("x",xg1[0]);
              parser.setVar("y",xg1[1]);
              if (Objet_U::dimension==3)
                parser.setVar("z",xg1[2]);
              double res=parser.eval();
              int face_min=(int)(res+0.5);
              nb=std::max(nb,face_min);
// faces_associees.dimensionner_force(nb+1);
              faces_associees[face_min].set_smart_resize(1);
              faces_associees[face_min].append_array(face1);
// Cerr << face1 << " associee a " << face_min << finl;
            }
          for (int face2=0; face2<nb+1; face2++) //!< Ecriture des fichiers de sortie
            {
              Nom nomfic(nomfr1);
              nomfic+="%";
              Nom n;
              n=face2;
              nomfic+=n;
              SFichier s(nomfic);
              s<<faces_associees[face2]<<finl;
              listb<<nomfic<<finl;
              s.close();
            }
        }
    }
  listb.close();
}
References Parser_U::addVar(), Cerr, Sortie_Fichier_base::close(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Parser_U::eval(), Process::exit(), finl, Zone::frontiere(), Domaine::le_nom(), Frontiere::le_nom(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Parser_U::parseString(), ref_cast, Noms::search(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), vect_impl::size(), and Domaine::zone().
Referenced by create_listb_geom(), and DecoupeBord::interpreter_().
create_listb_geom()
void create_listb_geom (const Domaine & dom1, const Noms & nomdec, const ArrOfInt & nbdec)
< plan x=cste
< plan y=cste
< plan z=cste
Definition at line 278 of file DecoupeBord.cpp.
{
  if((Objet_U::dimension)!=3)
    {
      Cerr<<"nb_parts_geom has been defined for dimension 3 only"<<finl;;
      Process::exit();
    }
  int n1=nomdec.size();
  int n2=nbdec.size_array();
  if((2*n1)!=n2)
    {
      Cerr << "The 'nb_parts_geom' has to be twice the  number of boundaries in 'bords_a_decouper' : check your data file"<<finl;
      Process::exit();
    }
  const DoubleTab& xs=dom1.coord_sommets();
  const Zone& zone=dom1.zone(0);
  int nbfr=zone.nb_front_Cl();
  Parser_U parser;
  parser.setNbVar(3);
  parser.addVar("x");
  parser.addVar("y");
  parser.addVar("z");
  Noms expr_tot(n1);
  for (int l=0; l<nbfr; l++)
    {
      const Frontiere& fr=zone.frontiere(l);
      int nbfaces=fr.nb_faces();
      const Nom& nomfr=fr.le_nom();
      int inc=nomdec.search(nomfr);
      if (inc!=-1)
        {
          int nb1=nbdec[2*inc];
          int nb2=nbdec[2*inc+1];
          if (nbfaces!=0)
            {
// int nbfaces=fr.nb_faces();
              const IntTab& sommets_face = (ref_cast(Frontiere,fr)).les_sommets_des_faces();
              int nb_som_face=dom1.les_sommets().dimension(1);
              ArrOfDouble coord_min(3);
              coord_min=1e6;
              ArrOfDouble coord_max(3);
              coord_max=-1e6;
              for (int face=0; face<nbfaces; face++)
                {
                  for (int i=0; i<nb_som_face; i++)
                    for (int j=0; j<3; j++)
                      {
                        coord_min[j] = std::min(coord_min[j],xs(sommets_face(face,i),j));
                        coord_max[j] = std::max(coord_max[j],xs(sommets_face(face,i),j));
                      }
                }
              Nom expr="0.+";
              if(coord_min[0]==coord_max[0]) //!< plan x=cste
                {
                  double dy=(coord_max[1]-coord_min[1])/nb1;
                  double dz=(coord_max[2]-coord_min[2])/nb2;
                  for (int j=1; j<nb1; j++)
                    {
                      double pas=j*dy;
                      expr+="(y>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                  expr+=Nom(nb1);
                  expr+="*(";
                  for (int k=1; k<nb2; k++)
                    {
                      double pas=k*dz;
                      expr+="(z>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                }
              else if (coord_min[1]==coord_max[1]) //!< plan y=cste
                {
                  double dx=(coord_max[0]-coord_min[0])/nb1;
                  double dz=(coord_max[2]-coord_min[2])/nb2;
                  for (int i=1; i<nb1; i++)
                    {
                      double pas=i*dx;
                      expr+="(x>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                  expr+=Nom(nb1);
                  expr+="*(";
                  for (int k=1; k<nb2; k++)
                    {
                      double pas=k*dz;
                      expr+="(z>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                }
              else if (coord_min[2]==coord_max[2]) //!< plan z=cste
                {
                  double dx=(coord_max[0]-coord_min[0])/nb1;
                  double dy=(coord_max[1]-coord_min[1])/nb2;
                  for (int i=1; i<nb1; i++)
                    {
                      double pas=i*dx;
                      expr+="(x>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                  expr+=Nom(nb1);
                  expr+="*(";
                  for (int j=1; j<nb2; j++)
                    {
                      double pas=j*dy;
                      expr+="(y>";
                      expr+=Nom(pas);
                      expr+=")+";
                    }
                }
              else
                {
                  Cerr <<"the boundary "<<nomfr<<" is not plane : nb_parts_geom can't be used"<<finl;
                  Process::exit();
                }
              expr+="0.)";
              Cerr << "fontiere : "<<nomfr<<" -  expression : " <<expr<<finl;
              parser.setString(expr);
              parser.parseString();
              expr_tot[inc]=expr;
            }//if (nbfaces!=0)
        }//if (inc!=-1)
    }//for (int l=0;l<nbfr;l++)
  Cerr <<"create_listb_from_xyz ....  "<<finl;
  create_listb_from_xyz(dom1,nomdec,expr_tot);
  Cerr <<" ... ok "<<finl;
}
References Parser_U::addVar(), Cerr, Domaine::coord_sommets(), create_listb_from_xyz(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, Zone::frontiere(), Frontiere::le_nom(), Domaine::les_sommets(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Parser_U::parseString(), ref_cast, Noms::search(), Parser_U::setNbVar(), Parser_U::setString(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), and Domaine::zone().
Referenced by DecoupeBord::interpreter_().
create_listb_naif()
void create_listb_naif (const Domaine & dom1, const Noms & nomdec, const ArrOfInt & nbdec)
Definition at line 223 of file DecoupeBord.cpp.
{
  int n1=nomdec.size();
  int n2=nbdec.size_array();
  if(n1!=n2)
    {
      Cerr << "The numbers of boundaries in 'bords_a_decouper' and 'nb_parts_naif' are not the same : check your data file"<<finl;
      Process::exit();
    }
  SFichier listb(dom1.le_nom()+".boundary_list");
  const Zone& zone=dom1.zone(0);
  int nbfr=zone.nb_front_Cl();
  for (int l=0; l<nbfr; l++)
    {
      const Frontiere& fr=zone.frontiere(l);
      int nbfaces=fr.nb_faces();
      int compt=0;
      const Nom& nomfr=fr.le_nom();
      int inc=nomdec.search(nomfr);
      if (inc!=-1)
        {
          int nb=nbdec[inc];
          nb=std::min(nb,nbfaces);
          if (nbfaces!=0)
            {
              int nc=nbfaces/nb;
// Cerr<<nbfaces<<finl;
              if ((nb*nc)<nbfaces) nc++;
// Cerr<<"nc "<<nc<<finl;
              Cerr<<nomfr<<" splitting in "<<nb<<" parts, average number of faces "<<nbfaces/(1.*nb)<<finl;
// Cerr<<"nombre moyen de faces  "<<nc<<" bord decoupe "<<nomfr<<" en "<<nbfaces/nc<<" parties"<<finl;
              for (int i=0; i<nb; i++)
                {
                  if (i==nb-1) nc=nbfaces-compt;
                  IntVect p(nc);
                  for (int j=0; j<nc; j++) p[j]=compt++;
                  Nom nomfic(nomfr);
                  nomfic+="%";
                  Nom n;
                  n=i;
                  nomfic+=n;
                  SFichier s(nomfic);
                  s<<p<<finl;
                  listb<<nomfic<<finl;
                  s.close();
                }
            }
        }
    }
  listb.close();
}
References Cerr, Sortie_Fichier_base::close(), Process::exit(), finl, Zone::frontiere(), Domaine::le_nom(), Frontiere::le_nom(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Noms::search(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), and Domaine::zone().
Referenced by DecoupeBord::interpreter_().
Variable Documentation
DecoupeBordbases
const Type_info* DecoupeBordbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 23 of file DecoupeBord.cpp.