TRUST: src/Kernel/Geometrie/Decoupeur/Decouper.cpp File Reference
Decouper.cpp File Reference
#include <Decouper.h>
#include <Domaine.h>
#include <DomaineCutter.h>
#include <Postraitement_lata.h>
#include <EChaine.h>
#include <SFichier.h>
#include <Param.h>
#include <communications.h>
Functions
static void lire_partitionneur (Deriv_Partitionneur_base &d_part, const Domaine &domaine, Entree &is)
lecture du partitionneur dans le jeu de donnees<br>(lecture du type et des parametres et initialisation de d_part)
static void ecrire_fichier_decoupage (const Nom &nom_fichier_decoupage, const IntVect &elem_part, int &nb_parts_tot)
static void postraiter_decoupage (const Nom &nom_fichier_lata, const Domaine &domaine, const IntVect &elem_part)
static void ecrire_sous_zones (const Nom &nom_zones_decoup, const Decouper::ZonesFileOutputType format, const Domaine &domaine, IntVect &elem_part, const int nb_parties, const int epaisseur_joint, const int reorder, const Noms &bords_periodiques, const Static_Int_Lists *som_raccord)
Variables
const Type_info * Decouperbases [1] ={ &(Interprete ::info_obj)}
Function Documentation
ecrire_fichier_decoupage()
static void ecrire_fichier_decoupage (const Nom & nom_fichier_decoupage, const IntVect & elem_part, int & nb_parts_tot) static
< Fichier ascii
Definition at line 84 of file Decouper.cpp.
{
  Cerr << "Writing of the splitting array at the format IntVect ascii\n"
       << " in the file " << nom_fichier_decoupage
       << "\n(for each element, number of the destination processor)" << finl;
  SFichier file; //!< Fichier ascii
  if (! file.ouvrir(nom_fichier_decoupage))
    {
      Cerr << " Error in the opening of the file." << finl;
      Process::exit();
    }
  file << elem_part;
  file << nb_parts_tot;
}
References Cerr, Process::exit(), finl, and Sortie_Fichier_base::ouvrir().
Referenced by Decouper::ecrire().
ecrire_sous_zones()
static void ecrire_sous_zones (const Nom & nom_zones_decoup, const Decouper::ZonesFileOutputType format, const Domaine & domaine, IntVect & elem_part, const int nb_parties, const int epaisseur_joint, const int reorder, const Noms & bords_periodiques, const Static_Int_Lists * som_raccord) static
Definition at line 135 of file Decouper.cpp.
{
  DomaineCutter cutter;
  cutter.initialiser(domaine, elem_part, nb_parties, epaisseur_joint,
                     bords_periodiques);
// Reflexion provisoire:
// Les joints sont construits dans ecrire_zones -> construire_sous_domaine
// Donc apres renumerotation des PEs et donc de elem_part, il faudrait
// reinitialiser ? Ou bien, tout renumeroter apres le calcul des joints...
// Cela parait mieux...
  cutter.ecrire_zones(nom_zones_decoup, format, elem_part, reorder, som_raccord);
}
References DomaineCutter::ecrire_zones(), and DomaineCutter::initialiser().
Referenced by Decouper::ecrire().
lire_partitionneur()
static void lire_partitionneur (Deriv_Partitionneur_base & d_part, const Domaine & domaine, Entree & is) static
lecture du partitionneur dans le jeu de donnees<br>(lecture du type et des parametres et initialisation de d_part)
Definition at line 65 of file Decouper.cpp.
{
  Nom n;
  is >> n;
  Nom type_partitionneur("Partitionneur_");
  type_partitionneur += n;
  Cerr << " Creation of a partitioner of type: " << type_partitionneur << finl;
  d_part.typer(type_partitionneur);
// En cas d'echec (si le nom du type est invalide) : exit
  if (! d_part.non_nul())
    Process::exit();
// Initialisation des parametres du partitionneur
  Partitionneur_base& part = d_part.valeur();
  part.associer_domaine(domaine);
  is >> part;
}
References Partitionneur_base::associer_domaine(), Cerr, Process::exit(), and finl.
Referenced by Decouper::lire_motcle_non_standard().
postraiter_decoupage()
static void postraiter_decoupage (const Nom & nom_fichier_lata, const Domaine & domaine, const IntVect & elem_part) static
Definition at line 101 of file Decouper.cpp.
{
  Cerr << "Postprocessing of the splitting at the lata format: " << nom_fichier_lata << finl;
  Postraitement_lata::Format format = Postraitement_lata::BINAIRE;
  Postraitement_lata::ecrire_entete(nom_fichier_lata,
                                    "Discretisation_inconnue",
                                    format);
  Postraitement_lata::ecrire_zone(nom_fichier_lata,
                                  domaine.zone(0),
                                  format);
  Postraitement_lata::ecrire_temps(nom_fichier_lata,
                                   0.,
                                   format);
  const int n = elem_part.size_reelle();
  DoubleTab data(n);
  for (int i = 0; i < n; i++)
    data(i) = elem_part[i];
  Postraitement_lata::ecrire_champ(nom_fichier_lata,
                                   Nom("partition"),
                                   Postraitement_lata::CHAMP,
                                   'I',
                                   domaine.le_nom(),
                                   "pb",
                                   0., /* temps */
                                   Postraitement_base::ELEMENTS,
                                   data,
                                   format);
  Postraitement_lata::finir_lata(nom_fichier_lata);
}
References Postraitement_lata::BINAIRE, Cerr, Postraitement_lata::CHAMP, Postraitement_lata::ecrire_champ(), Postraitement_lata::ecrire_entete(), Postraitement_lata::ecrire_temps(), Postraitement_lata::ecrire_zone(), Postraitement_base::ELEMENTS, Postraitement_lata::finir_lata(), finl, Domaine::le_nom(), TRUSTVect< _TYPE_ >::size_reelle(), and Domaine::zone().
Referenced by Decouper::ecrire().
Variable Documentation
Decouperbases
const Type_info* Decouperbases[1] ={ &(Interprete ::info_obj)}
Definition at line 24 of file Decouper.cpp.