TRUST: src/VDF/Zones/distances_VDF.cpp File Reference
distances_VDF.cpp File Reference
#include <distances_VDF.h>
Functions
void moy_2D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double &u)
double norm_2D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double &u)
double norm_2D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double u_paroi, double v_paroi, double &u)
void moy_3D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double &val1, double &val2)
double norm_3D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double &val1, double &val2)
double norm_3D_vit (const DoubleVect &vit, int elem, int iori, const Zone_VDF &zone, double u_paroi, double v_paroi, double w_paroi, double &val1, double &val2)
double norm_vit (const DoubleVect &vit, int elem, int ori, const Zone_VDF &zone, const ArrOfDouble &vit_paroi, ArrOfDouble &val)
Function Documentation
moy_2D_vit()
void moy_2D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double & u)
Definition at line 17 of file distances_VDF.cpp.
{
  int num1,num2;
  if (iori == 0)
    {
      num1 = zone.elem_faces(elem,1);
      num2 = zone.elem_faces(elem,3);
    }
  else if (iori == 1)
    {
      num1 = zone.elem_faces(elem,0);
      num2 = zone.elem_faces(elem,2);
    }
  else
    {
      Cerr << "valeur de iori " << iori << " impossible en 2D" << finl;
      Process::exit();
      num1=num2=-1;
    }
  u=0.5*(vit(num1)+vit(num2));
}
References Cerr, Zone_VF::elem_faces(), Process::exit(), and finl.
Referenced by Champ_front_fonc_gradient_VDF::mettre_a_jour(), and norm_2D_vit().
moy_3D_vit()
void moy_3D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double & val1, double & val2)
Definition at line 87 of file distances_VDF.cpp.
{
  int num1,num2,num3,num4;
  if (iori == 0)
    {
      num1 = zone.elem_faces(elem,1);
      num2 = zone.elem_faces(elem,4);
      num3 = zone.elem_faces(elem,2);
      num4 = zone.elem_faces(elem,5);
    }
  else if (iori == 1)
    {
      num1 = zone.elem_faces(elem,0);
      num2 = zone.elem_faces(elem,3);
      num3 = zone.elem_faces(elem,2);
      num4 = zone.elem_faces(elem,5);
    }
  else if (iori == 2)
    {
      num1 = zone.elem_faces(elem,0);
      num2 = zone.elem_faces(elem,3);
      num3 = zone.elem_faces(elem,1);
      num4 = zone.elem_faces(elem,4);
    }
  else
    {
      Cerr << "valeur de iori " << iori << " impossible en 3D" << finl;
      Process::exit();
      num1=num2=num3=num4=-1;
    }
  val1=0.5*(vit(num1)+vit(num2));
  val2=0.5*(vit(num3)+vit(num4));
}
References Cerr, Zone_VF::elem_faces(), Process::exit(), and finl.
Referenced by Champ_front_fonc_gradient_VDF::mettre_a_jour(), and norm_3D_vit().
norm_2D_vit() [1/2]
double norm_2D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double & u)
Definition at line 39 of file distances_VDF.cpp.
{
  double v;
  moy_2D_vit(vit,elem,iori,zone,v);
  v=std::fabs(v);
  if (v == 0)
    u = 0;
  else
    u = 1;
  return v;
}
References moy_2D_vit().
Referenced by Champ_Face::calcul_y_plus(), and norm_vit().
norm_2D_vit() [2/2]
double norm_2D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double u_paroi, double v_paroi, double & u)
Definition at line 51 of file distances_VDF.cpp.
{
  double vit_paroi;
  if (iori == 0)
    vit_paroi = v_paroi;
  else if (iori == 1)
    vit_paroi = u_paroi;
  else
    {
      Cerr << "valeur de iori " << iori << " impossible en 2D" << finl;
      Process::exit();
      vit_paroi=0;
    }
  double v;
  double n_v;
  moy_2D_vit(vit,elem,iori,zone,v);
// YB:30/01/04:
// Les valeurs du cisaillement parietal sont maintenant signees.
// En considerant les valeurs signees de la projection de la vitesse sur le plan parietal
  v = v - vit_paroi;
  n_v = std::fabs(v);
// Fin modif YB
  if (v == 0)
    u = 0;
  else if (v > 0)
    u = 1;
  else
    u = -1;
  return n_v;
}
References Cerr, Process::exit(), finl, and moy_2D_vit().
norm_3D_vit() [1/2]
double norm_3D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double & val1, double & val2)
Definition at line 121 of file distances_VDF.cpp.
{
  moy_3D_vit(vit,elem,iori,zone,val1,val2);
  double v1 = std::fabs(val1);
  double v2 = std::fabs(val2);
  double norm_vit = sqrt(v1*v1+v2*v2);
  val1 = v1/(norm_vit+DMINFLOAT);
  val2 = v2/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References DMINFLOAT, moy_3D_vit(), and norm_vit().
Referenced by Champ_Face::calcul_y_plus(), and norm_vit().
norm_3D_vit() [2/2]
double norm_3D_vit (const DoubleVect & vit, int elem, int iori, const Zone_VDF & zone, double u_paroi, double v_paroi, double w_paroi, double & val1, double & val2)
Definition at line 132 of file distances_VDF.cpp.
{
  double v1,v2,norm_vit;
  moy_3D_vit(vit,elem,iori,zone,val1,val2);
  if (iori == 0)
    {
      v1 = val1 - u_paroi;
      v2 = val2 - w_paroi;
    }
  else if (iori == 1)
    {
      v1 = val1 - u_paroi;
      v2 = val2 - w_paroi;
    }
  else if (iori == 2)
    {
      v1 = val1 - u_paroi;
      v2 = val2 - v_paroi;
    }
// Fin modif YB
  else
    {
      Cerr << "valeur de iori " << iori << " impossible en 3D" << finl;
      Process::exit();
      v1=v2=0;
    }
  norm_vit = sqrt(v1*v1+v2*v2);
  val1 = v1/(norm_vit+DMINFLOAT);
  val2 = v2/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References Cerr, DMINFLOAT, Process::exit(), finl, moy_3D_vit(), and norm_vit().
norm_vit()
double norm_vit (const DoubleVect & vit, int elem, int ori, const Zone_VDF & zone, const ArrOfDouble & vit_paroi, ArrOfDouble & val)
Definition at line 165 of file distances_VDF.cpp.
{
  if (Objet_U::dimension==3)
    {
      return norm_3D_vit(vit,elem,ori,zone,vit_paroi[0],vit_paroi[1],vit_paroi[2],val[0],val[1]);
    }
  else
    {
      return norm_2D_vit(vit,elem,ori,zone,vit_paroi[0],vit_paroi[1],val[0]);
    }
}
References Objet_U::dimension, norm_2D_vit(), and norm_3D_vit().
Referenced by norm_2D_vit1_k(), norm_2D_vit1_lp(), norm_2D_vit2_k(), norm_3D_vit(), norm_3D_vit1(), norm_3D_vit1_lp(), norm_3D_vit2(), and norm_vit_lp().