TRUST: src/EF/Zones/distances_EF.cpp File Reference
distances_EF.cpp File Reference
#include <distances_EF.h>
#include <Domaine.h>
#include <Motcle.h>
Functions
double norm_3D_vit1 (const DoubleTab &vit, int fac, int num1, const Zone_EF &zone, double &val1, double &val2, double &val3)
double norm_2D_vit1_k (const DoubleTab &vit, int fac, int num1, const Zone_EF &zone, double &val1, double &val2)
double norm_3D_vit2 (const DoubleTab &vit, int fac, int num1, const Zone_EF &zone, double &val1, double &val2, double &val3)
double norm_2D_vit2_k (const DoubleTab &vit, int fac, int num1, const Zone_EF &zone, double &val1, double &val2)
double distance_2D (int fac, int elem, const Zone_EF &zone)
double distance_3D (int fac, int elem, const Zone_EF &zone)
double norm_vit_lp (const ArrOfDouble &vit, int face, const Zone_EF &zone, ArrOfDouble &val)
double norm_vit_lp_k (const DoubleTab &vit, int face, int face_b, const Zone_EF &zone, ArrOfDouble &val, int is_defilante)
double distance_face_elem (int fac, int elem, const Zone_EF &zone)
Function Documentation
distance_2D()
double distance_2D (int fac, int elem, const Zone_EF & zone)
< centre de gravite des elements
< centre de gravite des faces
Definition at line 156 of file distances_EF.cpp.
{
  const DoubleTab& xp = zone.xp();    //!< centre de gravite des elements
  const DoubleTab& xv = zone.xv();    //!< centre de gravite des faces
  const DoubleTab& face_normale = zone.face_normales();
  double r0,r1;
  calcule_r0r1(face_normale,fac,r0,r1);
  double x0=xv(fac,0);
  double y0=xv(fac,1);
  double x1=xp(elem,0);
  double y1=xp(elem,1);
  return fabs(r0*(x1-x0)+r1*(y1-y0));
}
References calcule_r0r1(), Zone_EF::face_normales(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by Champ_P1NC::calcul_y_plus(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), distance_face_elem(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), and Champ_front_contact_VEF::remplir_connect_bords().
distance_3D()
double distance_3D (int fac, int elem, const Zone_EF & zone)
< centre de gravite des elements
< centre de gravite des faces
Definition at line 173 of file distances_EF.cpp.
{
  const DoubleTab& xp = zone.xp();    //!< centre de gravite des elements
  const DoubleTab& xv = zone.xv();    //!< centre de gravite des faces
  const DoubleTab& face_normale = zone.face_normales();
  double r0,r1,r2;
  calcule_r0r1r2(face_normale,fac,r0,r1,r2);
  double x0=xv(fac,0);
  double y0=xv(fac,1);
  double z0=xv(fac,2);
  double x1=xp(elem,0);
  double y1=xp(elem,1);
  double z1=xp(elem,2);
  return fabs(r0*(x1-x0)+r1*(y1-y0)+r2*(z1-z0));
}
References calcule_r0r1r2(), Zone_EF::face_normales(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by Champ_P1NC::calcul_y_plus(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), distance_face_elem(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), and Champ_front_contact_VEF::remplir_connect_bords().
distance_face_elem()
double distance_face_elem (int fac, int elem, const Zone_EF & zone)
Definition at line 230 of file distances_EF.cpp.
{
  int dimension=Objet_U::dimension;
  if (dimension==3)
    return distance_3D(fac,elem,zone);
  else
    return distance_2D(fac,elem,zone);
}
References Objet_U::dimension, distance_2D(), and distance_3D().
norm_2D_vit1_k()
double norm_2D_vit1_k (const DoubleTab & vit, int fac, int num1, const Zone_EF & zone, double & val1, double & val2)
Definition at line 52 of file distances_EF.cpp.
{
  const DoubleTab& face_normale = zone.face_normales();
// fac numero de la face a paroi fixe
  double r0,r1;
  calcule_r0r1(face_normale,fac,r0,r1);
  int nsom = zone.nb_som_face();
  ArrOfDouble vit_face(2);
  vit_face=0.;
  for(int comp=0; comp<2; comp++)
    {
      for(int jsom=0; jsom<nsom; jsom++)
        {
          int num_som = zone.face_sommets(num1, jsom);
          vit_face[comp]+=vit(num_som,comp);
        }
    }
  double v1=vit_face[0]/nsom;
  double v2=vit_face[1]/nsom;
  double norm_vit = vitesse_tangentielle(v1,v2,r0,r1);
  double psc = r0*v1+r1*v2;
// val1 et val2 sont les vitesses tangetentielles
  val1=(v1-psc*r0)/(norm_vit+DMINFLOAT);
  val2=(v2-psc*r1)/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References calcule_r0r1(), DMINFLOAT, Zone_EF::face_normales(), Zone_VF::face_sommets(), Zone_VF::nb_som_face(), norm_vit(), and vitesse_tangentielle().
Referenced by norm_vit_lp_k().
norm_2D_vit2_k()
double norm_2D_vit2_k (const DoubleTab & vit, int fac, int num1, const Zone_EF & zone, double & val1, double & val2)
Definition at line 121 of file distances_EF.cpp.
{
  const DoubleTab& face_normale = zone.face_normales();
// fac numero de la face a paroi defilante
  double r0,r1;
  calcule_r0r1(face_normale,fac,r0,r1);
  int nsom = zone.nb_som_face();
  ArrOfDouble vit_face(2);
  ArrOfDouble vit_face2(2);
  vit_face=0.;
  vit_face2=0.;
  for(int comp=0; comp<2; comp++)
    {
      for(int jsom=0; jsom<nsom; jsom++)
        {
          int num_som = zone.face_sommets(num1, jsom);
          vit_face[comp]+=vit(num_som,comp);
          int num_som2 = zone.face_sommets(fac, jsom);
          vit_face2[comp]+=vit(num_som2,comp);
        }
    }
  double v1=(vit_face[0]-vit_face2[0])/nsom;
  double v2=(vit_face[1]-vit_face2[1])/nsom;
  double norm_vit = vitesse_tangentielle(v1,v2,r0,r1);
// val1 et val2 sont les vitesses tangetentielles
  double psc = r0*v1+r1*v2;
  val1=(v1-psc*r0)/(norm_vit+DMINFLOAT);
  val2=(v2-psc*r1)/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References calcule_r0r1(), DMINFLOAT, Zone_EF::face_normales(), Zone_VF::face_sommets(), Zone_VF::nb_som_face(), norm_vit(), and vitesse_tangentielle().
Referenced by norm_vit_lp_k().
norm_3D_vit1()
double norm_3D_vit1 (const DoubleTab & vit, int fac, int num1, const Zone_EF & zone, double & val1, double & val2, double & val3)
Definition at line 19 of file distances_EF.cpp.
{
  const DoubleTab& face_normale = zone.face_normales();
// fac numero de la face a paroi fixe
  double r0,r1,r2;
  calcule_r0r1r2(face_normale,fac,r0,r1,r2);
  int nsom = zone.nb_som_face();
  ArrOfDouble vit_face(3);
  vit_face=0.;
  for(int comp=0; comp<3; comp++)
    {
      for(int jsom=0; jsom<nsom; jsom++)
        {
          int num_som = zone.face_sommets(num1, jsom);
          vit_face[comp]+=vit(num_som,comp);
        }
    }
  double v1=vit_face[0]/nsom;
  double v2=vit_face[1]/nsom;
  double v3=vit_face[2]/nsom;
  double norm_vit = vitesse_tangentielle(v1,v2,v3,r0,r1,r2);
  double psc = r0*v1+r1*v2+r2*v3;
// val1,val2 val3 sont les vitesses tangentielles
  val1=(v1-psc*r0)/(norm_vit+DMINFLOAT);
  val2=(v2-psc*r1)/(norm_vit+DMINFLOAT);
  val3=(v3-psc*r2)/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References calcule_r0r1r2(), DMINFLOAT, Zone_EF::face_normales(), Zone_VF::face_sommets(), Zone_VF::nb_som_face(), norm_vit(), and vitesse_tangentielle().
Referenced by norm_vit_lp_k().
norm_3D_vit2()
double norm_3D_vit2 (const DoubleTab & vit, int fac, int num1, const Zone_EF & zone, double & val1, double & val2, double & val3)
Definition at line 84 of file distances_EF.cpp.
{
  const DoubleTab& face_normale = zone.face_normales();
// fac numero de la face a paroi defilante
  double r0,r1,r2;
  calcule_r0r1r2(face_normale,fac,r0,r1,r2);
  int nsom = zone.nb_som_face();
  ArrOfDouble vit_face(3);
  ArrOfDouble vit_face2(3);
  vit_face=0.;
  vit_face2=0.;
  for(int comp=0; comp<3; comp++)
    {
      for(int jsom=0; jsom<nsom; jsom++)
        {
          int num_som = zone.face_sommets(num1, jsom);
          vit_face[comp]+=vit(num_som,comp);
          int num_som2 = zone.face_sommets(fac, jsom);
          vit_face2[comp]+=vit(num_som2,comp);
        }
    }
  double v1=(vit_face[0]-vit_face2[0])/nsom;
  double v2=(vit_face[1]-vit_face2[1])/nsom;
  double v3=(vit_face[2]-vit_face2[2])/nsom;
  double norm_vit = vitesse_tangentielle(v1,v2,v3,r0,r1,r2);
// val1,val2 val3 sont les vitesses tangentielles
  double psc = r0*v1+r1*v2+r2*v3;
  val1=(v1-psc*r0)/(norm_vit+DMINFLOAT);
  val2=(v2-psc*r1)/(norm_vit+DMINFLOAT);
  val3=(v3-psc*r2)/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References calcule_r0r1r2(), DMINFLOAT, Zone_EF::face_normales(), Zone_VF::face_sommets(), Zone_VF::nb_som_face(), norm_vit(), and vitesse_tangentielle().
Referenced by norm_vit_lp_k().
norm_vit_lp()
double norm_vit_lp (const ArrOfDouble & vit, int face, const Zone_EF & zone, ArrOfDouble & val)
Definition at line 190 of file distances_EF.cpp.
{
  const DoubleTab& face_normale = zone.face_normales();
  int dim=Objet_U::dimension;
  ArrOfDouble r(dim);
  double psc,norm_vit;
  for(int i=0; i<dim; i++) r[i]=face_normale(face,i);
  r/=norme_array(r);
  psc = dotproduct_array(r,vit);
  if(dim==3) norm_vit = vitesse_tangentielle(vit[0],vit[1],vit[2],r[0],r[1],r[2]);
  else             norm_vit = vitesse_tangentielle(vit[0],vit[1],r[0],r[1]);
  for(int i=0; i<dim; i++) val[i]=(vit[i]-psc*r[i])/(norm_vit+DMINFLOAT);
  return norm_vit;
}
References Objet_U::dimension, DMINFLOAT, dotproduct_array(), Zone_EF::face_normales(), norm_vit(), norme_array(), and vitesse_tangentielle().
norm_vit_lp_k()
double norm_vit_lp_k (const DoubleTab & vit, int face, int face_b, const Zone_EF & zone, ArrOfDouble & val, int is_defilante)
Definition at line 211 of file distances_EF.cpp.
{
  int dimension=Objet_U::dimension;
// assert(face_b<zone.premiere_face_int()); assert a ameliorer ou faces_virt...
  if (is_defilante==0)
    if (dimension==3)
      return norm_3D_vit1(vit,face_b,face,zone,val[0],val[1],val[2]);
    else
      return norm_2D_vit1_k(vit,face_b,face,zone,val[0],val[1]);
  else
    {
      if (dimension==3)
        return norm_3D_vit2(vit,face_b,face,zone,val[0],val[1],val[2]);
      else
        return norm_2D_vit2_k(vit,face_b,face,zone,val[0],val[1]);
    }
}
References Objet_U::dimension, norm_2D_vit1_k(), norm_2D_vit2_k(), norm_3D_vit1(), and norm_3D_vit2().