TRUST: src/ThHyd/Chimie/dlsinterf.h File Reference
dlsinterf.h File Reference
Functions
int F77DECLARE() dlsodechimies (integer *neq, double *y, double *t, double *tout, double *tau_mel, integer *itol, double *rtol, double *atol, double *rwork, integer *lrw, integer *iwork, integer *liw)
int F77DECLARE() DLSODECHIMIES (integer *neq, double *y, double *t, double *tout, double *tau_mel, integer *itol, double *rtol, double *atol, double *rwork, integer *lrw, integer *iwork, integer *liw)
int F77DECLARE() dlsode_chimie_s_old (integer *neq, double *y, double *t, double *tout, integer *itol, double *rtol, double *atol, double *rwork, integer *lrw, integer *iwork, integer *liw)
int F77DECLARE() DLSODE_CHIMIE_S_OLD (integer *neq, double *y, double *t, double *tout, integer *itol, double *rtol, double *atol, double *rwork, integer *lrw, integer *iwork, integer *liw)
int F77DECLARE() inittaillecommon (integer *nreact, integer *ncons)
int F77DECLARE() INITTAILLECOMMON (integer *nreact, integer *ncons)
int F77DECLARE() initreactioncommon (integer *ir, double *pstochio, integer *pactivite, integer *contrereaction)
int F77DECLARE() INITREACTIONCOMMON (integer *ir, double *pstochio, integer *pactivite, integer *contrereaction)
int F77DECLARE() setcwreaction (integer *ir, double *rcw)
int F77DECLARE() SETCWREACTION (integer *ir, double *rcw)
int F77DECLARE() setmarqueur (integer *ir)
int F77DECLARE() SETMARQUEUR (integer *ir)
int F77DECLARE() printcommon (void)
int F77DECLARE() PRINTCOMMON (void)
Function Documentation
dlsode_chimie_s_old()
int F77DECLARE() dlsode_chimie_s_old (integer * neq, double * y, double * t, double * tout, integer * itol, double * rtol, double * atol, double * rwork, integer * lrw, integer * iwork, integer * liw)
Referenced by DLSODE_CHIMIE_S_OLD().
DLSODE_CHIMIE_S_OLD()
int F77DECLARE() DLSODE_CHIMIE_S_OLD (integer * neq, double * y, double * t, double * tout, integer * itol, double * rtol, double * atol, double * rwork, integer * lrw, integer * iwork, integer * liw) inline
Definition at line 37 of file dlsinterf.h.
{
  return F77NAME(dlsode_chimie_s_old)(neq, y, t, tout, itol, rtol, atol, rwork, lrw, iwork, liw);
}
References dlsode_chimie_s_old(), and F77NAME.
dlsodechimies()
int F77DECLARE() dlsodechimies (integer * neq, double * y, double * t, double * tout, double * tau_mel, integer * itol, double * rtol, double * atol, double * rwork, integer * lrw, integer * iwork, integer * liw)
Referenced by DLSODECHIMIES().
DLSODECHIMIES()
int F77DECLARE() DLSODECHIMIES (integer * neq, double * y, double * t, double * tout, double * tau_mel, integer * itol, double * rtol, double * atol, double * rwork, integer * lrw, integer * iwork, integer * liw) inline
Definition at line 24 of file dlsinterf.h.
{
  return F77NAME(dlsodechimies)(neq, y, t, tout, tau_mel,itol, rtol, atol, rwork, lrw, iwork, liw);
}
References dlsodechimies(), and F77NAME.
Referenced by Chimie::mettre_a_jour().
initreactioncommon()
int F77DECLARE() initreactioncommon (integer * ir, double * pstochio, integer * pactivite, integer * contrereaction)
Referenced by INITREACTIONCOMMON().
INITREACTIONCOMMON()
int F77DECLARE() INITREACTIONCOMMON (integer * ir, double * pstochio, integer * pactivite, integer * contrereaction) inline
Definition at line 65 of file dlsinterf.h.
{
  return F77NAME(initreactioncommon)(ir, pstochio, pactivite,contrereaction);
}
References F77NAME, and initreactioncommon().
Referenced by Chimie::mettre_a_jour().
inittaillecommon()
int F77DECLARE() inittaillecommon (integer * nreact, integer * ncons)
Referenced by INITTAILLECOMMON().
INITTAILLECOMMON()
int F77DECLARE() INITTAILLECOMMON (integer * nreact, integer * ncons) inline
Definition at line 51 of file dlsinterf.h.
{
  return F77NAME(inittaillecommon)(nreact, ncons);
}
References F77NAME, and inittaillecommon().
Referenced by Chimie::mettre_a_jour().
printcommon()
int F77DECLARE() printcommon (void)
Referenced by PRINTCOMMON().
PRINTCOMMON()
int F77DECLARE() PRINTCOMMON (void) inline
Definition at line 105 of file dlsinterf.h.
{
  return F77NAME(printcommon)();
}
References F77NAME, and printcommon().
setcwreaction()
int F77DECLARE() setcwreaction (integer * ir, double * rcw)
Referenced by SETCWREACTION().
SETCWREACTION()
int F77DECLARE() SETCWREACTION (integer * ir, double * rcw) inline
Definition at line 79 of file dlsinterf.h.
{
  return F77NAME(setcwreaction)(ir, rcw);
}
References F77NAME, and setcwreaction().
Referenced by Chimie::mettre_a_jour().
setmarqueur()
int F77DECLARE() setmarqueur (integer * ir)
Referenced by SETMARQUEUR().
SETMARQUEUR()
int F77DECLARE() SETMARQUEUR (integer * ir) inline
Definition at line 92 of file dlsinterf.h.
{
  return F77NAME(setmarqueur)(ir);
}
References F77NAME, and setmarqueur().
Referenced by Chimie::mettre_a_jour().