TRUST: src/Kernel/Geometrie/DomaineCutter.cpp File Reference
DomaineCutter.cpp File Reference
#include <DomaineCutter.h>
#include <ArrOfBit.h>
#include <Domaine.h>
#include <Connectivite_som_elem.h>
#include <SFichierBin.h>
#include <Array_tools.h>
#include <Scatter.h>
#include <TRUSTArrays.h>
#include <Sous_Zone.h>
#include <Sparskit.h>
#include <Poly_geom_base.h>
#include <Sortie_Brute.h>
#include <TRUSTVect.h>
#include <FichierHDFPar.h>
#include <communications.h>
Functions
static void construire_liste_sommets_sousdomaine (const int nb_sommets, const IntTab &les_elems, const ArrOfInt &liste_elements, const int i_part, const Static_Int_Lists *som_raccord, ArrOfInt &liste_sommets, ArrOfInt &liste_inverse_sommets)
Creation de la liste des sommets du sous-domaine "partie".
C'est l'ensemble des sommets des elements appartenant a ce sous-domaine.
On ne traite que les elements reels.
Parametre: nb_sommets
Signification: nombre de sommets de la zone globale
Parametre: les_elems
Signification tableau des elements de la zone globale (pour chaque element, numeros de ses sommets)
Parametre: elem_part
Signification: tableau de decoupage (pour chaque element i du domaine global,
elem_part[i] est le numero du sous-domaine auquel il est affecte)
Parametre: partie
Signification: le numero du sous-domaine a construire
Parametre: liste_sommets
Signification: en sortie : liste des sommets du sous-domaine: liste_sommets[i] est
l'indice dans la zone_globale du i-ieme sommet du sous-domaine.
Les indices sont classes dans l'ordre croissant.
Parametre: liste_inverse_sommets
Signification: en sortie : on lui donne la taille nb_sommets et on l'initialise.
liste_inverse_sommet[i] est l'indice du sommet dans le sous-domaine
ou -1 si le sommet i n'est pas dans le sous-domaine)
static void remplir_coordsommets_sous_domaine (const DoubleTab &sommets_glob, const ArrOfInt &liste_sommets, DoubleTab &sommets_loc)
void construire_elems_sous_domaine (const IntTab &elems_zone_globale, const ArrOfInt &liste_elements, const ArrOfInt &liste_inverse_sommets, IntTab &elems_zone_locale, ArrOfInt &liste_inverse_elements)
void construire_liste_faces_sous_domaine (const ArrOfInt &elements_voisins, const IntVect &elem_part, const int partie, const IntTab &faces_sommets, const ArrOfInt &liste_inverse_sommets, IntTab &faces_sommets_partie)
Pour une liste de "faces" de la zone globale, compter le nombre de
faces incluses dans la partie "part" et les copier dans la structure
faces_partie en remplacant les numeros de sommets par les numeros locaux
dans le sous-domaine.
L'ordre des faces est conserve (si une face apparait avant une autre dans
la liste du domaine complet et si elles sont toutes les deux dans la sous-partie,
alors leur ordre est conserve). C'est important pour le periodique
(hypothese qu'il y a correspondance entre la face i et la face i+n/2 du bord
periodique).
Attention: la condition pour qu'une face soit incluse est "la face appartient<br>a un element de la partie voisine". La condition "les sommets des faces sont<br>des sommets de joint" n'est PAS suffisante.
static void ajouter_joints (Zone &zone, const ArrOfInt &voisins, const int epaisseur)
Pour chaque pe mentionne dans le tableau "voisins", si un joint avec ce pe
n'existe par encore dans la zone, ajoute un joint et initialise ce joint avec "epaisseur".
static void parcourir_epaisseurs_elements (const IntTab &elements, const Static_Int_Lists &elem_som, const IntVect &elem_part, ArrOfInt liste_sommets_depart, const int partie_a_ignorer, const int epaisseur, ArrOfInt &liste_elements_trouves)
A partir d'une liste de sommets de depart (liste_sommets_depart), on
parcourt les elements voisins de ces sommets (si epaisseur <= 1),
puis les voisins de ces elements (voisins par un sommet de l'element) si epaisseur <= 2,
puis les voisins des voisins si epaisseur <= 3, etc
Les elements appartenant a la "partie_a_ignorer" ne sont pas parcourus.
Les indices des elements parcourus sont ranges dans liste_elements_trouves.
Cette methode a ete codee pour construire_elements_distants_ssdom()
void calculer_listes_elements_sous_domaines (const IntVect &elem_part, const int nb_parts, const int nbelem, Static_Int_Lists &liste_elems_sous_domaines)
void calculer_elements_voisins_bords (const Domaine &dom, const Static_Int_Lists &som_elem, Static_Int_Lists &voisins, const IntVect &elem_part, const int permissif, Noms &bords_a_pb_)
static void construire_nom_fichier_sous_domaine (const Nom &basename, const int partie, const int nb_parties_, const int original_proc, Nom &fichier)
Build the name of the ".Zones" file for a given proc and a domain.
If partie == -1 a single filename is returned. For example
DOM.Zones
instead of
DOM_0001.Zones.
Variables
const Type_info * DomaineCutterbases [1] ={ &(Objet_U ::info_obj)}
Function Documentation
ajouter_joints()
static void ajouter_joints (Zone & zone, const ArrOfInt & voisins, const int epaisseur) static
Pour chaque pe mentionne dans le tableau "voisins", si un joint avec ce pe
n'existe par encore dans la zone, ajoute un joint et initialise ce joint avec "epaisseur".
Definition at line 390 of file DomaineCutter.cpp.
{
  Joints& joints = zone.faces_joint();
  const int n = voisins.size_array();
  for (int i = 0; i < n; i++)
    {
      const int pe = voisins[i];
      int j;
      const int nb_joints = joints.size();
      for (j = 0; j < nb_joints; j++)
        if (joints[j].PEvoisin() == pe)
          break;
      if (j == nb_joints)
        {
          Cerr << " Adding of a new joint : " << pe << finl;
          Joint& joint = joints.add(Joint());
          joint.nommer(Nom("Joint_")+Nom(pe));
          joint.associer_zone(zone);
          joint.affecte_epaisseur(epaisseur);
          joint.affecte_PEvoisin(pe);
// Ces joints n'auront pas de sommets communs. Met le flag
// d'initialisation a 1.
          joint.set_joint_item(Joint::SOMMET).set_items_communs();
        }
    }
}
References List_Joint::add(), Joint::affecte_epaisseur(), Joint::affecte_PEvoisin(), Frontiere::associer_zone(), Cerr, Zone::faces_joint(), finl, Frontiere::nommer(), Joint_Items::set_items_communs(), Joint::set_joint_item(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), and Joint::SOMMET.
Referenced by DomaineCutter::construire_elements_distants_ssdom().
calculer_elements_voisins_bords()
void calculer_elements_voisins_bords (const Domaine & dom, const Static_Int_Lists & som_elem, Static_Int_Lists & voisins, const IntVect & elem_part, const int permissif, Noms & bords_a_pb_)
Definition at line 997 of file DomaineCutter.cpp.
{
  const Zone& zone = dom.zone(0);
  const int nb_front = zone.nb_front_Cl();
  ArrOfInt nb_faces(nb_front);
  for (int i = 0; i < nb_front; i++)
    nb_faces[i] = zone.frontiere(i).nb_faces();
  voisins.set_list_sizes(nb_faces);
  const int nb_som_face = zone.frontiere(0).faces().nb_som_faces();
  ArrOfInt une_face(nb_som_face);
  ArrOfInt elems_voisins;
  elems_voisins.set_smart_resize(1);
  for (int i = 0; i < nb_front; i++)
    {
      int drap=0;
      const IntTab& faces = zone.frontiere(i).les_sommets_des_faces();
      const int n = nb_faces[i];
      for (int j = 0; j < n; j++)
        {
          for (int k = 0; k < nb_som_face; k++)
            une_face[k] = faces(j, k);
          find_adjacent_elements(som_elem, une_face, elems_voisins);
          const int n_voisins = elems_voisins.size_array();
          if (n_voisins != 1)
            {
              if (drap==0)
                {
                  if (permissif)
                    Cerr << "Message from DomaineCutter.cpp : calculer_elements_voisins_bords\n"
                         << " boundary face "<<  zone.frontiere(i).le_nom()<<" with " << n_voisins << " neighbors." << finl;
                  else
                    Cerr << "Error in DomaineCutter.cpp : calculer_elements_voisins_bords\n"
                         << " boundary face "<<  zone.frontiere(i).le_nom()<<" with " << n_voisins << " neighbors." << finl;
                  bords_a_pb_.add( zone.frontiere(i).le_nom());
                  if (elems_voisins.size_array()==0) Process::exit();
                }
              drap=1;
              if (elem_part[elems_voisins[1]]==1)
                elems_voisins[0]=elems_voisins[1];
              if (permissif==0)
                Process::exit();
            }
          voisins.set_value(i, j, elems_voisins[0]);
        }
    }
}
References Vect_Nom::add(), Cerr, Process::exit(), Frontiere::faces(), find_adjacent_elements(), finl, Zone::frontiere(), Frontiere::le_nom(), Frontiere::les_sommets_des_faces(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Faces::nb_som_faces(), Static_Int_Lists::set_list_sizes(), TRUSTArray< _TYPE_ >::set_smart_resize(), Static_Int_Lists::set_value(), TRUSTArray< _TYPE_ >::size_array(), and Domaine::zone().
Referenced by DomaineCutter::initialiser().
calculer_listes_elements_sous_domaines()
void calculer_listes_elements_sous_domaines (const IntVect & elem_part, const int nb_parts, const int nbelem, Static_Int_Lists & liste_elems_sous_domaines)
Definition at line 973 of file DomaineCutter.cpp.
{
  ArrOfInt sizes(nb_parts);
// Premier passage : comptage
  int i;
  for (i = 0; i < nbelem; i++)
    {
      const int part = elem_part[i];
      sizes[part]++;
    }
  liste_elems_sous_domaines.set_list_sizes(sizes);
// Deuxieme passage : remplissage
  sizes = 0;
  for (i = 0; i < nbelem; i++)
    {
      const int part = elem_part[i];
      const int index = sizes[part]++;
      liste_elems_sous_domaines.set_value(part, index, i);
    }
}
References Static_Int_Lists::set_list_sizes(), and Static_Int_Lists::set_value().
Referenced by DomaineCutter::ecrire_zones(), and DomaineCutter::initialiser().
construire_elems_sous_domaine()
void construire_elems_sous_domaine (const IntTab & elems_zone_globale, const ArrOfInt & liste_elements, const ArrOfInt & liste_inverse_sommets, IntTab & elems_zone_locale, ArrOfInt & liste_inverse_elements)
Definition at line 186 of file DomaineCutter.cpp.
{
  const int nb_elem_tot                = elems_zone_globale.dimension_tot(0);
  const int nb_sommets_par_element = elems_zone_globale.dimension(1);
  liste_inverse_elements.resize(nb_elem_tot,Array_base::NOCOPY_NOINIT);
  liste_inverse_elements = -1;
// Premier passage: comptage du nombre d'elements de la partie
  const int nb_elem_part = liste_elements.size_array();
  elems_zone_locale.resize(nb_elem_part, nb_sommets_par_element);
// Deuxieme passage: remplissage du tableau
  for (int i_elem = 0; i_elem < nb_elem_part; i_elem++)
    {
      int elem = liste_elements[i_elem];
// Nouveau numero de l'element dans la partie
      liste_inverse_elements[elem] = i_elem;
// Copie de l'element avec traduction du numero des sommets en
// numero local dans le sous-domaine
      for (int i = 0; i < nb_sommets_par_element; i++)
        {
          int sommet = elems_zone_globale(elem, i);
          if (sommet<0)
            elems_zone_locale(i_elem, i) =sommet;
          else
            {
              int new_num = liste_inverse_sommets[sommet];
              assert(new_num >= 0);
              elems_zone_locale(i_elem, i) = new_num;
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Array_base::NOCOPY_NOINIT, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by DomaineCutter::construire_sous_domaine().
construire_liste_faces_sous_domaine()
void construire_liste_faces_sous_domaine (const ArrOfInt & elements_voisins, const IntVect & elem_part, const int partie, const IntTab & faces_sommets, const ArrOfInt & liste_inverse_sommets, IntTab & faces_sommets_partie)
Pour une liste de "faces" de la zone globale, compter le nombre de
faces incluses dans la partie "part" et les copier dans la structure
faces_partie en remplacant les numeros de sommets par les numeros locaux
dans le sous-domaine.
L'ordre des faces est conserve (si une face apparait avant une autre dans
la liste du domaine complet et si elles sont toutes les deux dans la sous-partie,
alors leur ordre est conserve). C'est important pour le periodique
(hypothese qu'il y a correspondance entre la face i et la face i+n/2 du bord
periodique).
Attention: la condition pour qu'une face soit incluse est "la face appartient<br>a un element de la partie voisine". La condition "les sommets des faces sont<br>des sommets de joint" n'est PAS suffisante.
< Pour faire append_array...
Definition at line 239 of file DomaineCutter.cpp.
{
  const int nb_faces = faces_sommets.dimension(0);
  const int nb_sommets_par_face = faces_sommets.dimension(1);
  int i;
  assert(elements_voisins.size_array() == nb_faces);
// La liste des faces du tableau faces_sommets a inclure dans le sous-domaine
  ArrOfInt liste_faces;
  liste_faces.set_smart_resize(1); //!< Pour faire append_array...
// Premier passage : on cherche les faces a inclure
  {
    for (i = 0; i < nb_faces; i++)
      {
        int elem = elements_voisins[i];
        const int part = elem_part[elem];
        if (part == partie)
          liste_faces.append_array(i);
      }
  }
  const int nb_faces_part = liste_faces.size_array();
  faces_sommets_partie.resize(nb_faces_part, nb_sommets_par_face);
// Deuxieme passage : stockage des faces et conversion des numeros
// de sommets des faces en numeros locaux dans le sous-domaine.
  for (i = 0; i < nb_faces_part; i++)
    {
      const int i_face = liste_faces[i];
      int j;
      for (j = 0; j < nb_sommets_par_face; j++)
        {
          int sommet = faces_sommets(i_face, j);
          if (sommet>-1)
            {
              int new_num = liste_inverse_sommets[sommet];
              assert(new_num >= 0);
              faces_sommets_partie(i, j) = new_num;
            }
          else
            faces_sommets_partie(i, j) = -1;
        }
    }
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), and DomaineCutter::construire_faces_raccords_ssdom().
construire_liste_sommets_sousdomaine()
static void construire_liste_sommets_sousdomaine (const int nb_sommets, const IntTab & les_elems, const ArrOfInt & liste_elements, const int i_part, const Static_Int_Lists * som_raccord, ArrOfInt & liste_sommets, ArrOfInt & liste_inverse_sommets) static
Creation de la liste des sommets du sous-domaine "partie".
C'est l'ensemble des sommets des elements appartenant a ce sous-domaine.
On ne traite que les elements reels.
Parametre: nb_sommets
Signification: nombre de sommets de la zone globale
Parametre: les_elems
Signification tableau des elements de la zone globale (pour chaque element, numeros de ses sommets)
Parametre: elem_part
Signification: tableau de decoupage (pour chaque element i du domaine global,
elem_part[i] est le numero du sous-domaine auquel il est affecte)
Parametre: partie
Signification: le numero du sous-domaine a construire
Parametre: liste_sommets
Signification: en sortie : liste des sommets du sous-domaine: liste_sommets[i] est
l'indice dans la zone_globale du i-ieme sommet du sous-domaine.
Les indices sont classes dans l'ordre croissant.
Parametre: liste_inverse_sommets
Signification: en sortie : on lui donne la taille nb_sommets et on l'initialise.
liste_inverse_sommet[i] est l'indice du sommet dans le sous-domaine
ou -1 si le sommet i n'est pas dans le sous-domaine)
< On oublie les valeurs precedentes
< On oublie les valeurs precedentes
Definition at line 84 of file DomaineCutter.cpp.
{
  const int nb_elem_part = liste_elements.size_array();
  const int nb_sommets_par_element = les_elems.dimension(1);
// Algorithme : on parcourt les elements: pour les elements de la partie,
// on marque les sommets de l'element par un drapeau.
// Puis on fait une boucle sur les sommets, et ceux dont le drapeau
// est mis sont mis dans la liste.
// D'abord, on compte les sommets de la partie et on
// remplit drapeau_sommet
  ArrOfBit drapeau_sommet(nb_sommets);
  drapeau_sommet = 0;
// Nombre de sommets de la partie "part"
  int nb_sommets_part = 0;
  for (int i_elem = 0; i_elem < nb_elem_part; i_elem++)
    {
      const int elem = liste_elements[i_elem];
      for (int j = 0; j < nb_sommets_par_element; j++)
        {
          int sommet = les_elems(elem, j);
          if (sommet>-1)
            {
              int bit = drapeau_sommet.testsetbit(sommet);
// Si le drapeau n'etait pas mis, cela fait un sommet de plus
              if (! bit)
                nb_sommets_part++;
            }
        }
    }
// sommets a ajouter a cause de som_raccord
  if (som_raccord)
    for (int s = 0; s < som_raccord->get_nb_lists(); s++)
      for (int i = 0; i < som_raccord->get_list_size(s); i++)
        if ((*som_raccord)(s, i) == i_part && !drapeau_sommet.testsetbit(s)) //le sommet est demande par ce proc
          nb_sommets_part++; //si on ne l'a pas deja, on le rajoute
// Remplissage de liste_sommets et liste_inverse_sommets
  liste_sommets.resize_array(0); //!< On oublie les valeurs precedentes
  liste_sommets.resize_array(nb_sommets_part);
  liste_inverse_sommets.resize_array(0); //!< On oublie les valeurs precedentes
  liste_inverse_sommets.resize_array(nb_sommets,Array_base::NOCOPY_NOINIT);
  liste_inverse_sommets = -1;
  int n = 0;
  for (int i = 0; i < nb_sommets; i++)
    {
      if (drapeau_sommet[i])
        {
          liste_sommets[n] = i;
          liste_inverse_sommets[i] = n;
          n++;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Static_Int_Lists::get_list_size(), Static_Int_Lists::get_nb_lists(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), and ArrOfBit::testsetbit().
Referenced by DomaineCutter::construire_sous_domaine().
construire_nom_fichier_sous_domaine()
static void construire_nom_fichier_sous_domaine (const Nom & basename, const int partie, const int nb_parties_, const int original_proc, Nom & fichier) static
Build the name of the ".Zones" file for a given proc and a domain.
If partie == -1 a single filename is returned. For example
DOM.Zones
instead of
DOM_0001.Zones.
Definition at line 1205 of file DomaineCutter.cpp.
{
  fichier = basename;
  if (partie > 100000)
    {
      Cerr << "Error while generating filename: nb_parties_ too large" << finl;
      Process::exit();
    }
  char s[30];
// single file name for all procs (HDF5)
// the number of parts is still included in the file name
// (make_PAR.data needs to know how many zones there are)
  if (partie < 0)
    {
      if (nb_parties_ > 10000)
        sprintf(s, "_p%05d.Zones", (True_int)nb_parties_);
      else
        sprintf(s, "_p%04d.Zones",(True_int) nb_parties_);
    }
  else
    {
      if (nb_parties_ > 10000)
        {
          if(original_proc < 0)
            sprintf(s, "_%05d.Zones", (True_int)partie);
          else
            sprintf(s, "_%05d_%d.Zones", (True_int)partie, (True_int)original_proc);
        }
      else
        {
          if(original_proc < 0)
            sprintf(s, "_%04d.Zones", (True_int)partie);
          else
            sprintf(s, "_%04d_%d.Zones", (True_int)partie, (True_int)original_proc);
        }
    }
  fichier += Nom(s);
}
References Cerr, Process::exit(), and finl.
Referenced by DomaineCutter::ecrire_zones().
parcourir_epaisseurs_elements()
static void parcourir_epaisseurs_elements (const IntTab & elements, const Static_Int_Lists & elem_som, const IntVect & elem_part, ArrOfInt liste_sommets_depart, const int partie_a_ignorer, const int epaisseur, ArrOfInt & liste_elements_trouves) static
A partir d'une liste de sommets de depart (liste_sommets_depart), on
parcourt les elements voisins de ces sommets (si epaisseur <= 1),
puis les voisins de ces elements (voisins par un sommet de l'element) si epaisseur <= 2,
puis les voisins des voisins si epaisseur <= 3, etc
Les elements appartenant a la "partie_a_ignorer" ne sont pas parcourus.
Les indices des elements parcourus sont ranges dans liste_elements_trouves.
Cette methode a ete codee pour construire_elements_distants_ssdom()
< Cet element a deja ete visite Numero de zone de l'element voisin:
< Ne traiter que les elements des autres parties
Definition at line 426 of file DomaineCutter.cpp.
{
  const int nb_sommets = elem_som.get_nb_lists();
  const int nb_elements = elements.dimension_tot(0);
  const int nb_som_elem = elements.dimension(1);
  liste_elements_trouves.set_smart_resize(1);
  liste_elements_trouves.resize_array(0);
  ArrOfBit sommets_parcourus(nb_sommets);
  ArrOfBit elements_parcourus(nb_elements);
  ArrOfInt new_liste;
  liste_sommets_depart.set_smart_resize(1);
  new_liste.set_smart_resize(1);
  sommets_parcourus = 0;
  elements_parcourus = 0;
  {
// Marquage des sommets de depart et construction d'une liste de sommets uniques
    const int sz_liste = liste_sommets_depart.size_array();
    for (int i = 0; i < sz_liste; i++)
      {
        const int sommet = liste_sommets_depart[i];
        if (sommet>-1)
          if (!sommets_parcourus.testsetbit(sommet))
            new_liste.append_array(sommet);
      }
  }
// Boucle sur les epaisseurs successives d'elements autour des sommets de joint.
  for (int ep = 1; ep <= epaisseur; ep++)
    {
      liste_sommets_depart = new_liste;
      new_liste.resize_array(0);
      const int sz_liste = liste_sommets_depart.size_array();
      for (int i_sommet = 0; i_sommet < sz_liste; i_sommet++)
        {
          const int sommet = liste_sommets_depart[i_sommet];
// Parcours des elements voisins de ce sommet :
          const int nb_elems_voisins = elem_som.get_list_size(sommet);
          for (int i_elem = 0; i_elem < nb_elems_voisins; i_elem++)
            {
              const int elem = elem_som(sommet, i_elem);
              if (elements_parcourus[elem])
                continue; //!< Cet element a deja ete visite Numero de zone de l'element voisin:
//
              const int part = elem_part[elem];
              if (part == partie_a_ignorer)
                continue; //!< Ne traiter que les elements des autres parties
              liste_elements_trouves.append_array(elem);
              elements_parcourus.setbit(elem);
// Ajout a la prochaine liste de sommets a traiter les sommets de cet element:
              for (int i = 0; i < nb_som_elem; i++)
                {
                  const int sommet2 = elements(elem, i);
                  if (sommet2>-1)
                    {
                      if (sommets_parcourus.testsetbit(sommet2) == 0)
                        new_liste.append_array(sommet2);
                    }
                }
            }
        }
    }
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Static_Int_Lists::get_list_size(), Static_Int_Lists::get_nb_lists(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), ArrOfBit::setbit(), TRUSTArray< _TYPE_ >::size_array(), and ArrOfBit::testsetbit().
Referenced by DomaineCutter::construire_elements_distants_ssdom().
remplir_coordsommets_sous_domaine()
static void remplir_coordsommets_sous_domaine (const DoubleTab & sommets_glob, const ArrOfInt & liste_sommets, DoubleTab & sommets_loc) static
Definition at line 161 of file DomaineCutter.cpp.
{
  const int nb_som = liste_sommets.size_array();
  const int dim = sommets_glob.dimension(1);
  sommets_loc.resize(nb_som, dim);
  int i;
  for (i = 0; i < nb_som; i++)
    {
      int indice = liste_sommets[i];
      int j;
      for (j = 0; j < dim; j++)
        sommets_loc(i, j) = sommets_glob(indice, j);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by DomaineCutter::construire_sous_domaine().
Variable Documentation
DomaineCutterbases
const Type_info* DomaineCutterbases[1] ={ &(Objet_U ::info_obj)}
Definition at line 32 of file DomaineCutter.cpp.