TRUST: src/Kernel/Geometrie/Decoupeur/Domain_Graph.cpp File Reference
Domain_Graph.cpp File Reference
#include <Domaine.h>
#include <Static_Int_Lists.h>
#include <Connectivite_som_elem.h>
#include <Poly_geom_base.h>
#include <Matrix_tools.h>
#include <Matrice_Morse.h>
#include <Array_tools.h>
#include <communications.h>
#include <Domain_Graph.h>
#include <Partitionneur_base.h>
#include <map>
Functions
static void construire_connectivite_real_som_virtual_elem (const int nb_sommets, const IntTab &les_elems, Static_Int_Lists &som_elem, const IntTab &elem_virt_pe_num, const ArrOfInt &offsets)
Function Documentation
construire_connectivite_real_som_virtual_elem()
static void construire_connectivite_real_som_virtual_elem (const int nb_sommets, const IntTab & les_elems, Static_Int_Lists & som_elem, const IntTab & elem_virt_pe_num, const ArrOfInt & offsets) static
Definition at line 27 of file Domain_Graph.cpp.
{
// Nombre d'elements du domaine
  const int nb_elem = les_elems.dimension_tot(0);
  const int local_nb_elem = les_elems.dimension(0);
// Nombre de sommets par element
  const int nb_sommets_par_element = les_elems.dimension(1);
// Construction d'un tableau initialise a zero : pour chaque sommet,
// nombre d'elements voisins de ce sommet
  ArrOfInt nb_elements_voisins(nb_sommets);
// Premier passage : on calcule le nombre d'elements voisins de chaque
// sommet pour creer la structure de donnees
  int elem, i;
// real elements
  for (elem = 0; elem < nb_elem; elem++)
    {
      for (i = 0; i < nb_sommets_par_element; i++)
        {
          int sommet = les_elems(elem, i);
          if(sommet >= nb_sommets) continue; //skipping virtual node
// GF cas des polyedres
          if (sommet==-1) break;
          nb_elements_voisins[sommet]++;
        }
    }
  som_elem.set_list_sizes(nb_elements_voisins);
// On reutilise le tableau pour stocker le nombre d'elements dans
// chaque liste pendant qu'on la remplit
  nb_elements_voisins = 0;
// Remplissage du tableau des elements voisins.
  for (elem = 0; elem < nb_elem; elem++)
    {
      for (i = 0; i < nb_sommets_par_element; i++)
        {
          int sommet = les_elems(elem, i);
          if(sommet >= nb_sommets) continue;
// GF cas des polyedres
          if (sommet==-1) break;
          int n = (nb_elements_voisins[sommet])++;
          int elem_num_global = -1;
          if(elem>= local_nb_elem)
            {
              int proc_of_elem = elem_virt_pe_num(elem-local_nb_elem, 0);
              int elem_number_on_local_proc = elem_virt_pe_num(elem-local_nb_elem, 1);
              elem_num_global = elem_number_on_local_proc + offsets[proc_of_elem];
            }
          else
            elem_num_global = elem + offsets[Process::me()];
          som_elem.set_value(sommet, n, elem_num_global);
        }
    }
// Tri de toutes les listes dans l'ordre croissant
  som_elem.trier_liste(-1);
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Process::me(), Static_Int_Lists::set_list_sizes(), Static_Int_Lists::set_value(), and Static_Int_Lists::trier_liste().
Referenced by Domain_Graph::construire_graph_elem_elem().