TRUST: src/Kernel/Math/DoubleTab.cpp File Reference
src/Kernel/Math/DoubleTab.cpp File Reference
#include <DoubleTab.h>
#include <math.h>
#include <MD_Vector_base.h>
#include <Ref_DoubleTab.h>
#include <DoubleTabs.h>
#include <communications.h>
Defines
#define CHECK_LINE_SIZE
#define PARAM_X
#define PARAM_X2
Functions
int operator== (const Ref_DoubleTab &r1, const Ref_DoubleTab &r2)
static void init_dimensions (int *tab)
void mp_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void local_carre_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void mp_carre_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void local_max_abs_tab (const DoubleTab &tableau, ArrOfDouble &max_colonne)
void mp_max_abs_tab (const DoubleTab &tableau, ArrOfDouble &max_colonne)
Variables
const Type_info * DoubleTabbases [1] = { &(DoubleVect ::info_obj)}
const Type_info * Ref_DoubleTabbases [1] = { &(Ref_ ::info_obj)}
const Type_info * Vect_DoubleTabbases [1] = { &(vect_impl ::info_obj)}
Define Documentation
#define CHECK_LINE_SIZE
Value:
((line_size() == ((nb_dim_>1)?dimensions_[1]:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
   && (line_size() * dimension_tot_0_ == size_array()))
Definition at line 41 of file DoubleTab.cpp.
Referenced by DoubleTab::copy(), DoubleTab::operator=(), DoubleTab::printOn(), DoubleTab::readOn(), DoubleTab::ref(), DoubleTab::ref_array(), DoubleTab::ref_data(), DoubleTab::ref_tab(), DoubleTab::reset(), DoubleTab::resize(), DoubleTab::resize_dim0(), DoubleTab::resize_tab(), and DoubleTab::set_md_vector().
#define PARAM_X
Definition at line 139 of file DoubleTab.cpp.
#define PARAM_X2
Definition at line 140 of file DoubleTab.cpp.
Function Documentation
static void init_dimensions (int * tab) [inline, static]
Definition at line 116 of file DoubleTab.cpp.
References MAXDIM_TAB.
Referenced by DoubleTab::DoubleTab().
{
#ifndef NDEBUG
  for (int i = 0; i < MAXDIM_TAB; i++)
    tab[i] = -1;
#endif
}
void local_carre_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 607 of file DoubleTab.cpp.
References MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), ArrOfDouble::size_array(), ArrOfInt::size_array(), and MD_Vector::valeur().
Referenced by mp_carre_norme_tab().
{
  const ArrOfInt& blocs = tableau.get_md_vector().valeur().get_items_to_sum();
  const int nblocs = blocs.size_array() >> 1;
  const DoubleVect& vect = tableau;
  const int lsize = vect.line_size();
  assert(lsize == norme_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc];
      const int end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = vect[k++];
              norme_colonne[j] += x*x;
            }
        }
    }
}
void local_max_abs_tab (const DoubleTab & tableau, ArrOfDouble & max_colonne)
Definition at line 636 of file DoubleTab.cpp.
References dabs(), MD_Vector_base::get_items_to_compute(), DoubleVect::get_md_vector(), DoubleVect::line_size(), ArrOfDouble::size_array(), ArrOfInt::size_array(), and MD_Vector::valeur().
Referenced by mp_max_abs_tab().
{
  const ArrOfInt& blocs = tableau.get_md_vector().valeur().get_items_to_compute();
  const int nblocs = blocs.size_array() >> 1;
  const DoubleVect& vect = tableau;
  const int lsize = vect.line_size();
  for (int j = 0; j < lsize; j++)
    max_colonne[j] = 0;
  assert(lsize == max_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc];
      const int end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = dabs(vect[k++]);
              max_colonne[j] = (x > max_colonne[j]) ? x : max_colonne[j];
            }
        }
    }
}
void mp_carre_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 630 of file DoubleTab.cpp.
References local_carre_norme_tab(), and mp_sum_for_each_item().
Referenced by mp_norme_tab().
{
  local_carre_norme_tab(tableau, norme_colonne);
  mp_sum_for_each_item(norme_colonne);
}
void mp_max_abs_tab (const DoubleTab & tableau, ArrOfDouble & max_colonne)
Definition at line 661 of file DoubleTab.cpp.
References local_max_abs_tab(), and mp_max_for_each_item().
Referenced by Navier_Stokes_std::initTimeStep(), and Schema_Temps_base::update_critere_statio().
{
  local_max_abs_tab(tableau, max_colonne);
  mp_max_for_each_item(max_colonne);
}
void mp_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 600 of file DoubleTab.cpp.
References mp_carre_norme_tab(), and ArrOfDouble::size_array().
{
  mp_carre_norme_tab(tableau,norme_colonne);
  for (int c=0; c<norme_colonne.size_array(); c++)
    norme_colonne(c)=sqrt(norme_colonne(c));
}
int operator== (const Ref_DoubleTab & r1, const Ref_DoubleTab & r2)
Definition at line 34 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
Variable Documentation
const Type_info* DoubleTabbases[1] = { &(DoubleVect ::info_obj)}
Definition at line 33 of file DoubleTab.cpp.
const Type_info* Ref_DoubleTabbases[1] = { &(Ref_ ::info_obj)}
Definition at line 34 of file DoubleTab.cpp.
const Type_info* Vect_DoubleTabbases[1] = { &(vect_impl ::info_obj)}
Definition at line 35 of file DoubleTab.cpp.