TRUST: src/Kernel/Math/DoubleVect.h File Reference
src/Kernel/Math/DoubleVect.h File Reference
#include <ArrOfDouble.h>
#include <MD_Vector.h>
#include <Vect.h>
#include <IntVect.h>
Classes
class DoubleVect
Functions
int operator== (const DoubleVect &x, const DoubleVect &y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfDouble<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
int operator!= (const DoubleVect &x, const DoubleVect &y)
int local_imax_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double local_max_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int local_imin_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double local_min_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double mp_max_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double mp_min_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double mp_somme_vect (const DoubleVect &)
double local_max_abs_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double local_min_abs_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double mp_max_abs_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
double mp_min_abs_vect (const DoubleVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
void operator_add (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_add (DoubleVect &resu, const double x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_sub (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_sub (DoubleVect &resu, const double x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_multiply (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_multiply (DoubleVect &resu, const double x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_negate (DoubleVect &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_egal (DoubleVect &resu, double x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_egal (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
double local_prodscal (const DoubleVect &, const DoubleVect &)
Renvoie la somme des x[i]*y[i] pour les items sequentiels sur ce processeur.
(tous les items si pas de structure parallele, sinon voir MD_Vector_base::get_items_to_sum()
double mp_prodscal (const DoubleVect &, const DoubleVect &)
double mp_norme_vect (const DoubleVect &)
double mp_carre_norme_vect (const DoubleVect &)
double local_carre_norme_vect (const DoubleVect &vx)
double mp_moyenne_vect (const DoubleVect &)
void ajoute_alpha_v (DoubleVect &v, double alpha, const DoubleVect &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
void ajoute_carre (DoubleVect &v, double alpha, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute_produit_scalaire (DoubleVect &v, double alpha, const DoubleVect &vx, const DoubleVect &vy, Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree (DoubleVect &v, Mp_vect_options opt=VECT_ALL_ITEMS)
void carre (DoubleVect &v, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_inverse (DoubleVect &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_abs (DoubleVect &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void tab_multiply_any_shape (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void tab_divide_any_shape (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_divide (DoubleVect &resu, const DoubleVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_divide (DoubleVect &resu, const double x, Mp_vect_options opt=VECT_ALL_ITEMS)
Function Documentation
void ajoute_alpha_v (DoubleVect & v, double alpha, const DoubleVect & vx, Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 1531 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by DoubleVect::ajoute(), DoubleVect::ajoute_sans_ech_esp_virt(), and Solv_GCP::resoudre_().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu += alpha * x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void ajoute_carre (DoubleVect & v, double alpha, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1594 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu += alpha * x * x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void ajoute_produit_scalaire (DoubleVect & v, double alpha, const DoubleVect & vx, const DoubleVect & vy, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
< this test is necessary if md is null
Definition at line 1657 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
  assert(vy.line_size() == line_size);
  assert(vy.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vy.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  const double *y_base = vy.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      const double* y_ptr = y_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          const double y = *(y_ptr++);
          double& p_resu = *(resu_ptr++);
          p_resu += alpha * x * y;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void carre (DoubleVect & v, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1782 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu *= p_resu;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
double local_carre_norme_vect (const DoubleVect & vx)
< this test is necessary if md is null
Definition at line 481 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by mp_carre_norme_vect(), and Solv_GCP::resoudre_().
{
  double sum = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( VECT_SEQUENTIAL_ITEMS != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS ||  VECT_SEQUENTIAL_ITEMS == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  sum;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          sum += x * x;
          x_ptr++;
        }
    }
  return  sum;
}
int local_imax_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 716 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  double max_val = (-HUGE_VALL);
  int i_max = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_max;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          if (x > max_val) { i_max = x_ptr - x_base; max_val = x; }
          x_ptr++;
        }
    }
  return  i_max;
}
int local_imin_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 603 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  double min_val = HUGE_VALL;
  int i_min = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_min;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          if (x < min_val) { i_min = x_ptr - x_base; min_val = x; }
          x_ptr++;
        }
    }
  return  i_min;
}
double local_max_abs_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 829 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), mp_max_abs_vect(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Schema_Temps_base::update_critere_statio(), and Debog_Pb::verifier_partie_std().
{
  double max_val = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double xx = fabs(x);
          max_val = (xx > max_val) ? xx : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
double local_max_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 773 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Op_Diff_VEF_base::calculer_pour_post(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Distanceparoi::interpreter_(), mp_max_vect(), Loi_Etat_Multi_GP_QC::rabot(), and traite_bord().
{
  double max_val = (-HUGE_VALL);
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          max_val = (x > max_val) ? x : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
double local_min_abs_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 886 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by modif_par_porosite_si_flag(), and mp_min_abs_vect().
{
  double min_val = HUGE_VALL;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double xx = fabs(x);
          min_val = (xx < min_val) ? xx : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
double local_min_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 660 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), mp_min_vect(), Loi_Etat_Multi_GP_QC::rabot(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
{
  double min_val = HUGE_VALL;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          min_val = (x < min_val) ? x : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
double local_prodscal (const DoubleVect & , const DoubleVect &)
Renvoie la somme des x[i]*y[i] pour les items sequentiels sur ce processeur.
(tous les items si pas de structure parallele, sinon voir MD_Vector_base::get_items_to_sum()
< this test is necessary if md is null
< this test is necessary if md is null
Definition at line 419 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by mp_prodscal(), and Solv_GCP::resoudre_().
{
  double sum = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
  assert(vy.line_size() == line_size);
  assert(vy.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vy.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( VECT_SEQUENTIAL_ITEMS != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS ||  VECT_SEQUENTIAL_ITEMS == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  sum;
    }
  const double *x_base = vx.addr();
  const double *y_base = vy.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const double* x_ptr = x_base + begin_bloc;
      const double* y_ptr = y_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          const double y = *(y_ptr++);
          sum += x * y;
          x_ptr++;
        }
    }
  return  sum;
}
double mp_carre_norme_vect (const DoubleVect &)
Definition at line 537 of file DoubleVect.cpp.
References local_carre_norme_vect(), and Process::mp_sum().
Referenced by RRK2::faire_un_pas_de_temps_eqn_base(), Equation_base::Gradient_conjugue_diff_impl(), mp_norme_vect(), and Solv_GCP::resoudre_().
{
  return Process::mp_sum(local_carre_norme_vect(vx));
}
double mp_max_abs_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 2277 of file DoubleVect.cpp.
References local_max_abs_vect(), and Process::mp_max().
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Zone_EF::calculer_Bij(), Sch_CN_iteratif::convergence(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Navier_Stokes_std::initTimeStep(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Piso::iterer_NS_PolyMAC(), Navier_Stokes_std::mettre_a_jour(), test_imposer_cond_lim(), Operateur_base::tester_contribuer_a_avec(), Schema_Temps_base::update_critere_statio(), and Debog_Pb::verifier_partie_std().
{
  double s = local_max_abs_vect(x, opt);
  s = Process::mp_max(s);
  return s;
}
double mp_max_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 2265 of file DoubleVect.cpp.
References local_max_vect(), and Process::mp_max().
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Zone_EF::calculer_Bij(), Zone_EF::calculer_volumes_sommets(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Loi_Etat_Multi_GP_QC::rabot(), Operateur_base::tester_contribuer_a_avec(), and verifier().
{
  double s = local_max_vect(x, opt);
  s =  Process::mp_max(s);
  return s;
}
double mp_min_abs_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 2283 of file DoubleVect.cpp.
References local_min_abs_vect(), and Process::mp_min().
{
  double s = local_min_abs_vect(x, opt);
  s = Process::mp_min(s);
  return s;
}
double mp_min_vect (const DoubleVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 2271 of file DoubleVect.cpp.
References local_min_vect(), and Process::mp_min().
Referenced by Zone_EF::calculer_Bij(), Op_Dift_VEF_Face::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Zone_EF::calculer_volumes_sommets(), Op_EF_base::dimensionner(), Assembleur_P_PolyMAC::modifier_solution(), Loi_Etat_Multi_GP_QC::rabot(), and Fluide_base::verifier_coherence_champs().
{
  double s = local_min_vect(x, opt);
  s =  Process::mp_min(s);
  return s;
}
double mp_moyenne_vect (const DoubleVect &)
Definition at line 2327 of file DoubleVect.cpp.
References DoubleVect::get_md_vector(), DoubleVect::line_size(), mp_somme_vect(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), Process::nproc(), DoubleVect::size_totale(), and MD_Vector::valeur().
Referenced by Champ_P1_isoP1Bulle::affecter_(), Terme_Boussinesq_base::check(), corriger(), and Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
{
  double s = mp_somme_vect(x);
  double n;
  const MD_Vector& md = x.get_md_vector();
  if (md.non_nul())
    n = md.valeur().nb_items_seq_tot() * x.line_size();
  else
    {
// Coding error: mp_moyenne_vect is used on a not distributed DoubleVect !
      assert(Process::nproc()==1);
      n = x.size_totale();
    }
  return s / n;
}
double mp_norme_vect (const DoubleVect &)
Definition at line 2353 of file DoubleVect.cpp.
References mp_carre_norme_vect().
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Champ_P1NC_implementation::filtrer_H1(), gmres_local(), Matrice_Morse::inverse(), Simple::iterer_eqn(), Simple::iterer_eqs(), Piso::iterer_NS(), PrecondSolv::preconditionner_(), PrecondA::preconditionner_(), Navier_Stokes_std::projeter(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), second_membre(), test_un_solveur(), Navier_Stokes_std::uzawa(), and verifier().
{
  double x = mp_carre_norme_vect(vx);
  x = sqrt(x);
  return x;
}
double mp_prodscal (const DoubleVect & , const DoubleVect &)
Definition at line 2342 of file DoubleVect.cpp.
References local_prodscal(), and Process::mp_sum().
Referenced by Champ_P1NC::calculer_integrale_volumique(), estim_cond(), RRK2::faire_un_pas_de_temps_eqn_base(), gmres_local(), Equation_base::Gradient_conjugue_diff_impl(), Matrice_Morse::inverse(), PrecondA::preconditionner_(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Navier_Stokes_std::uzawa(), and verifier().
{
  return Process::mp_sum(local_prodscal(x, y));
}
double mp_somme_vect (const DoubleVect &)
Definition at line 597 of file DoubleVect.cpp.
References local_somme_vect(), and Process::mp_sum().
Referenced by Perte_Charge_Singuliere::calculate_Q(), Zone::calculer_mon_centre_de_gravite(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Navier_Stokes_std::impr(), Source_PDF_EF::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Domaine::imprimer(), Zone_CoviMAC::init_equiv(), Zone_PolyMAC::init_m2(), Perte_Charge_Singuliere::lire_surfaces(), mp_moyenne_vect(), Zone_PolyMAC::orthocentrer(), DP_Impose_PolyMAC_Face::remplir_num_faces(), and DP_Impose_CoviMAC_Face::remplir_num_faces().
{
  double x = local_somme_vect(vx);
  double y = Process::mp_sum(x);
  return y;
}
int operator!= (const DoubleVect & x, const DoubleVect & y)
Definition at line 364 of file DoubleVect.cpp.
{
  return !(x == y);
}
int operator== (const DoubleVect & x, const DoubleVect & y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfDouble<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
Definition at line 355 of file DoubleVect.cpp.
References DoubleVect::get_md_vector().
{
  if (!(x.get_md_vector() == y.get_md_vector()))
    return 0;
  const ArrOfDouble& ax = x;
  const ArrOfDouble& ay = y;
  return ax == ay;
}
void operator_abs (DoubleVect & resu, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 943 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by DoubleVect::abs().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu = fabs(p_resu);
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_add (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 999 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Simpler::iterer_NS(), IntVect::operator+=(), DoubleVect::operator+=(), and Navier_Stokes_std::preparer_calcul().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu += x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_add (DoubleVect & resu, const double x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1062 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu += x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_divide (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1838 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), Cerr, Process::exit(), finl, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by DoubleVect::operator/=(), and tab_divide_any_shape().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          if (x==0) { Cerr << "Divide by 0 in DoubleVect::operator_divide()" << finl; Process::exit();};
          p_resu /= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_divide (DoubleVect & resu, const double x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2151 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), Cerr, Process::exit(), finl, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          if(x==0.) { Cerr << "Error: divide by 0 in operator_divide." << finl; Process::exit();};
          p_resu /= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (DoubleVect & resu, double x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1412 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by T_It_VDF_Elem< _TYPE_ >::calculer(), T_It_PolyMAC_Elem< _TYPE_ >::calculer(), Zone_VEF_PreP1b::discretiser(), Champ_Q1NC::gradient(), Champ_Q1_EF::gradient(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Matrice_Morse_Sym::multvect_et_prodscal(), SSOR::preconditionner_(), and PrecondSolv::preconditionner_().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu = x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1468 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu = x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_inverse (DoubleVect & resu, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1902 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), Cerr, Process::exit(), finl, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          if (p_resu==0) { Cerr << "Divide by 0 in DoubleVect::operateur_inverse()" << finl; Process::exit();};
          p_resu = 1. / p_resu;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1237 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by IntVect::operator*=(), DoubleVect::operator*=(), PrecondSolv::preconditionner_(), PrecondA::preconditionner_(), tab_divide_any_shape(), and tab_multiply_any_shape().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu *= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (DoubleVect & resu, const double x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1300 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu *= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_negate (DoubleVect & resu, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1356 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by Operateur_Grad_base::multvect(), Solv_GCP::resoudre_(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu = -p_resu;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1118 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by IntVect::operator-=(), DoubleVect::operator-=(), and Solv_GCP::resoudre_().
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      const double* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          p_resu -= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (DoubleVect & resu, const double x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1181 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu -= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void racine_carree (DoubleVect & v, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1726 of file DoubleVect.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), invalidate_data(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const DoubleVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  double *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          double& p_resu = *(resu_ptr++);
          p_resu = sqrt(p_resu);
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void tab_divide_any_shape (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2127 of file DoubleVect.cpp.
References Cerr, Process::exit(), finl, DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), operator_divide(), operator_multiply(), ArrOfDouble::size_array(), and tab_divide_any_shape_().
Referenced by Solveur_Masse_base::appliquer(), Milieu_base::calculer_alpha(), Champ_Q1NC::gradient(), and multiplier_ou_diviser().
{
  if (vx.size_array() == 1 && !vx.get_md_vector().non_nul())
    {
// Produit par une constante
      if (vx[0]==0)
        {
          Cerr << "Divide by 0 in DoubleVect::tab_divide_any_shape()" << finl;
          Process::exit();
        }
      double x = 1. / vx[0];
      operator_multiply(resu, x, opt);
    }
  else if (vx.line_size() == resu.line_size())
    {
// Produit membre a membre
      operator_divide(resu, vx, opt);
    }
  else
    {
// Cas general
      tab_divide_any_shape_(resu, vx, opt);
    }
}
void tab_multiply_any_shape (DoubleVect & resu, const DoubleVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2107 of file DoubleVect.cpp.
References DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), operator_multiply(), ArrOfDouble::size_array(), and tab_multiply_any_shape_().
Referenced by Masse_PolyMAC_Face::appliquer_coef(), Masse_PolyMAC_Elem::appliquer_coef(), Masse_Multiphase::calculer_alpha_rho(), Equation_base::calculer_champ_conserve(), Op_Diff_VEFP1NCP1B_Face::corriger_pour_diffusivite(), modif_par_porosite_si_flag(), multiplier_ou_diviser(), Fluide_Dilatable_base::update_rho_cp(), and Milieu_base::update_rho_cp().
{
  if (vx.size_array() == 1 && !vx.get_md_vector().non_nul())
    {
// Produit par une constante
      double x = vx[0];
      operator_multiply(resu, x, opt);
    }
  else if (vx.line_size() == resu.line_size())
    {
// Produit membre a membre
      operator_multiply(resu, vx, opt);
    }
  else
    {
// Cas general
      tab_multiply_any_shape_(resu, vx, opt);
    }
}