TRUST: src/Kernel/Math/Double.h File Reference
src/Kernel/Math/Double.h File Reference
#include <math.h>
#include <blas1.h>
#include <Objet_U.h>
Defines
#define M_E 2.7182818284590452354
#define M_LOG2E 1.4426950408889634074
#define M_LOG10E 0.43429448190325182765
#define M_LN2 0.69314718055994530942
#define M_LN10 2.30258509299404568402
#define M_PI 3.14159265358979323846
#define M_PI_2 1.57079632679489661923
#define M_PI_4 0.78539816339744830962
#define M_1_PI 0.31830988618379067154
#define M_2_PI 0.63661977236758134308
#define M_2_SQRTPI 1.12837916709551257390
#define M_SQRT2 1.41421356237309504880
#define M_SQRT1_2 0.70710678118654752440
#define DMAXFLOAT 1e+38
#define DMINFLOAT 1e-30
Functions
double carre (double x)
fonctions utiles sur les double
double * prodvect (const double *a, const double *b, double *resu)
double determinant (double a[2], double b[2])
double norme (int n, const double *const a)
double max (double x, double y)
double min (double x, double y)
double dmax (double x, double y)
double dmin (double x, double y)
double dabs (double x)
int est_egal (double x1, double x2, double eps)
int est_egal (double x1, double x2)
int est_different (double x1, double x2, double eps)
int est_different (double x1, double x2)
int inf_ou_egal (double x1, double x2, double eps)
int inf_ou_egal (double x1, double x2)
int inf_strict (double x1, double x2, double eps)
int inf_strict (double x1, double x2)
int sup_strict (double x1, double x2, double eps)
int sup_strict (double x1, double x2)
int sup_ou_egal (double x1, double x2, double eps)
int sup_ou_egal (double x1, double x2)
Define Documentation
#define DMAXFLOAT 1e+38
Definition at line 72 of file Double.h.
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), DoubleList::calcule_min_max(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Operateur::calculer_pas_de_temps(), Equation_base::calculer_pas_de_temps(), Op_Diff_VEF_base::calculer_pour_post(), Champ_P1iP1B_implementation::Champ_P1iP1B_implementation(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Probleme_Couple::computeTimeStep(), Solv_Petsc::create_solver(), TroisDto2D::extraire_2D(), ArrOfDouble::fill_default_value(), Simpler_Base::get_and_set_parametre_implicite(), Solveur_Implicite_Base::get_default_facsec_max(), Solveur_Implicite_Base::get_default_growth_factor(), Domaine::getBoundingBox(), Zone::identifie_item_unique(), Equation_base::imprime_residu(), Sonde::initialiser(), Integrer_champ_med::interpreter(), Test_solveur::interpreter(), Redresser_hexaedres_vdf::interpreter_(), Matrice_Morse::inverse(), Modele_turbulence_scal_base::limpr_nusselt(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEF::modifier_solution(), Assembleur_P_VDF::modifier_solution(), Assembleur_P_EF::modifier_solution(), Assembleur_P_CoviMAC::modifier_solution(), ArrOfDouble::operator[](), Octree::ranger_elem_2D(), Octree::ranger_elem_3D(), Simpler_Base::readOn(), Modele_turbulence_scal_base::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), Schema_Euler_Implicite::readOn(), Probleme_base::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Schema_Temps_base::Schema_Temps_base(), and Debog_Pb::verifier_partie_std().
#define DMINFLOAT 1e-30
Definition at line 75 of file Double.h.
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Champ_P1NC::calcul_duidxj_paroi(), calcul_tab_norme(), Champ_P1NC::calcul_y_plus(), Op_Dift_VEF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Dift_VDF_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Elem::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Reaction::calculer_pas_de_temps(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Schema_Temps_base::corriger_dt_calcule(), RRK2::faire_un_pas_de_temps_eqn_base(), Fram(), Fram4(), Champ_front_var_instationnaire::Gpoint(), Zone_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), norm_2D_vit1(), norm_2D_vit1_k(), norm_2D_vit1_lp(), norm_2D_vit2_k(), norm_3D_vit(), norm_3D_vit1(), norm_3D_vit1_lp(), norm_3D_vit2(), print_statistics_analyse(), projette(), Loi_Etat_Multi_GP_QC::rabot(), Solv_GCP::resoudre_(), and verifier().
#define M_1_PI 0.31830988618379067154
Definition at line 57 of file Double.h.
#define M_2_PI 0.63661977236758134308
Definition at line 60 of file Double.h.
#define M_2_SQRTPI 1.12837916709551257390
Definition at line 63 of file Double.h.
#define M_E 2.7182818284590452354
Definition at line 33 of file Double.h.
#define M_LN10 2.30258509299404568402
Definition at line 45 of file Double.h.
#define M_LN2 0.69314718055994530942
Definition at line 42 of file Double.h.
#define M_LOG10E 0.43429448190325182765
Definition at line 39 of file Double.h.
#define M_LOG2E 1.4426950408889634074
Definition at line 36 of file Double.h.
#define M_PI 3.14159265358979323846
Definition at line 48 of file Double.h.
Referenced by Op_Diff_VDF_var_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter_bord(), Op_Diff_VDF_var_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution_bord(), Assembleur_P_VDF_Q4::assembler(), Zone_VDF::calcul_h(), Changement_phase_Silver_Simpson::calculer(), Zone_EF_axi::calculer_Bij_gen(), Rectangle_axi::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), calculer_centres_gravite(), Champ_Face::calculer_dercov_axi(), Zone_EF_axi::calculer_IPhi(), Faces_VDF::calculer_orientation(), Faces::calculer_surfaces(), Segment_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Zone_VDF::calculer_volumes_entrelaces(), computeAngleBetweenCoplanarVectors(), OctreeRoot::construire(), Rectangle_axi::contient(), Hexaedre_axi::contient(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Ch_front_Vortex::deplacement_vortex(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), Eval_Quick_VDF_Face_Axi::dist_elem(), Eval_Quick_VDF_Face_Axi::dist_face(), Zone_VDF::dist_face_axi(), Zone_VDF::dist_face_elem0_axi(), Zone_VDF::dist_face_elem1_axi(), Zone_VDF::dist_norm_axi(), Zone_VDF::dist_norm_bord_axi(), Zone_VDF::distance_face(), Zone_VDF::distance_normale(), Moyenne_volumique::eval_filtre(), Ch_front_Vortex::initialiser(), Rotation::interpreter_(), Pave::lire_front(), Ch_front_Vortex::mettre_a_jour(), Assembleur_P_VDF_Q4::modifier_secmem(), Segment_EF_axi::normale(), OrienteFacesBord::oriente_faces_bord(), Sous_Zone::readOn(), Pave::readOn(), and Sonde::readOn().
#define M_PI_2 1.57079632679489661923
Definition at line 51 of file Double.h.
#define M_PI_4 0.78539816339744830962
Definition at line 54 of file Double.h.
#define M_SQRT1_2 0.70710678118654752440
Definition at line 69 of file Double.h.
#define M_SQRT2 1.41421356237309504880
Definition at line 66 of file Double.h.
Function Documentation
double carre (double x) [inline]
fonctions utiles sur les double
Definition at line 98 of file Double.h.
Referenced by Assembleur_P_VDF::construire(), distance_sommets(), Assembleur_P_VDF::remplir(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), and vitesse_tangentielle().
{
  return x*x;
}
double dabs (double x) [inline]
Definition at line 255 of file Double.h.
Referenced by aire_triangle(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Reaction::calcul_proportion_implicite(), Polyedre::calculer_centres_gravite(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Op_Conv_EF::calculer_dt_stab(), Faces_VDF::calculer_orientation(), Faces::calculer_surfaces(), Eval_Forchheimer_VEF_Face::calculer_terme_source(), Eval_Forchheimer_VDF_Face::calculer_terme_source(), Tetraedre::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Prisme::calculer_volumes(), Polyedre::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Zone_VDF::calculer_volumes_entrelaces(), Reordonner_faces_periodiques::check_faces_periodiques(), Reordonner_faces_periodiques::chercher_direction_perio(), Partitionneur_Tranche::chercher_direction_perio(), Multiplicateur_diphasique_Muhler_Steinhagen::coefficient(), Multiplicateur_diphasique_homogene::coefficient(), Multiplicateur_diphasique_Friedel::coefficient(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_CoviMAC_Face::coeffs_perte_charge(), Matrice_Morse::compacte(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Periodique::completer(), Triangle::contient(), Tetraedre::contient(), Quadrangle_VEF::contient(), Prisme::contient(), contient_Tetra(), contient_triangle(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), conv_quick_sharp_moins(), conv_quick_sharp_plus(), convkschemas(), Perte_Charge_Reguliere::correction_direction(), Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), corriger_incr_alpha(), Tetraedriser_homogene_fin::creer_sommet(), creer_sommet(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Zone_CoviMAC::discretiser(), Zone_PolyMAC::dist_face_elem0(), Zone_CoviMAC::dist_face_elem0(), Zone_PolyMAC::dist_face_elem1(), Zone_CoviMAC::dist_face_elem1(), Zone_VDF::dist_face_period(), Zone_PolyMAC::dist_norm(), Zone_CoviMAC::dist_norm(), Zone_PolyMAC::dist_norm_bord(), Zone_CoviMAC::dist_norm_bord(), distance_2D(), distance_3D(), distance_face(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), est_egal(), Abs::eval(), Moyenne_volumique::eval_filtre(), TroisDto2D::extraire_2D(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Echange_contact_CoviMAC::fgrad(), flora(), flora_p(), Fram(), Fram4(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Op_Grad_PolyMAC_Face::impr(), Source_PDF_EF::impr(), Schema_Temps_base::imprimer_temps_courant(), inf_ou_egal(), inf_strict(), Echange_contact_Correlation_VEF::init(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Zone_CoviMAC::init_equiv(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_we_2d(), Champ_front_fonc_pois_ipsn::initialiser(), Ch_front_Vortex::initialiser(), Champ_Face_implementation::interpolation(), Decouper_multi::interpreter(), Porosites::interpreter(), Redresser_hexaedres_vdf::interpreter_(), Extraire_domaine::interpreter_(), Matrice_Dense::is_the_same(), Pave::lire_front(), local_max_abs_tab(), Pave::maille1D(), Pave::maille2D(), Pave::maille3D(), meme_point(), meme_point2(), Reynolds_maille_Champ_Face::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), minmod(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), norm_2D_vit(), norm_3D_vit(), Zone_VF::orientation(), Zone_VF::orientation_si_definie(), Zone_PolyMAC::orthocentrer(), Sonde_Int::ouvrir_fichier(), Sonde::ouvrir_fichier(), Traitement_particulier_Solide_canal_VDF::post_traitement_particulier(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), projette(), qrdcmp(), OctreeRoot::rang_arete(), OctreeRoot::rang_sommet(), Pave::readOn(), Raffiner_Simplexes::refine_domain(), Champ_front_contact_VEF::remplir_connect_bords(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Zone_Cl_EF::remplir_type_elem_Cl(), Reordonner_faces_periodiques::renum_som_perio(), reordonne(), Ch_front_Vortex::reprendre_vortex(), scalar_abs(), som_pscal(), Op_Diff_VEFP1NCP1B_Face::test(), Operateur_base::tester_contribuer_a_avec(), trier_abs(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Perte_Charge_Singuliere::update_K(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_implementation_Q1::value_interpolation(), Op_Diff_VEF_Face::verifier(), Op_Diff_VEF_Anisotrope_Face::verifier(), Loi_horaire::verifier_derivee(), visc_Q1(), viscA_Q1(), vitesse_tangentielle(), and Zone_PolyMAC::W_stabiliser().
{
  return fabs(x);
}
double determinant (double a[2], double b[2]) [inline]
Definition at line 140 of file Double.h.
{
  return (a[0]*b[1]-a[1]*b[0]);
}
double dmax (double x, double y) [inline]
Definition at line 218 of file Double.h.
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Reaction::calcul_proportion_implicite(), calculer_centres_gravite(), chakravarthy(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), create_listb_geom(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Fram(), Fram4(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Decouper_multi::interpreter(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), superbee(), and Schema_Temps_base::validateTimeStep().
{
  return(x>y ? x:y);
}
double dmin (double x, double y) [inline]
Definition at line 237 of file Double.h.
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), calculer_centres_gravite(), chakravarthy(), create_listb_geom(), ExtrudeParoi::extrude(), Fram(), Fram4(), Champ_front_synt::mettre_a_jour(), minmod(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_front_contact_VEF::remplir_connect_bords(), Octree_Double::search_nodes_close_to(), superbee(), and Schema_Temps_base::validateTimeStep().
{
  return(x<y ? x:y);
}
int est_different (double x1, double x2, double eps) [inline]
Definition at line 298 of file Double.h.
References est_egal().
Referenced by Equation_base::get_champ(), Champ_Fonc_MED::readOn(), and Terme_Source_Canal_perio::source().
{
  return !est_egal(x1,x2,eps);
}
int est_different (double x1, double x2) [inline]
Definition at line 303 of file Double.h.
References est_egal().
{
  return !est_egal(x1,x2);
}
int est_egal (double x1, double x2, double eps) [inline]
Definition at line 273 of file Double.h.
References dabs().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Diff_VDF_var_Face_Axi::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Diff_VDF_Face_Axi::ajouter_bord(), T_It_VDF_Elem< _TYPE_ >::ajouter_bords(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Simpler_Base::assembler_matrice_pression_implicite(), Champ_front_var_instationnaire::avancer(), Champ_front_instationnaire_base::avancer(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Champ_Face::calcul_duidxj(), Zone_EF::calculer_Bij(), Champ_Face::calculer_dercov_axi(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_local(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), T_It_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Assembleur_P_VEF::calculer_inv_volume(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Op_Dift_VEF_Face::calculer_pour_post(), Faces::calculer_surfaces(), Eval_Puiss_Neutr_VDF_Elem::calculer_terme_source(), Op_Ecart_type::calculer_valeurs(), Op_Correlation::calculer_valeurs(), Scatter::check_consistancy_remote_items(), Matrice_Morse::compacte(), Reaction::completer(), Segment::contient(), Quadrangle_VEF::contient(), Prisme::contient(), Point::contient(), contient_Tetra(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Fluide_Dilatable_base::creer_champs_non_lus(), Zone_PolyMAC::discretiser(), Zone_CoviMAC::discretiser(), Operateur_Conv_base::dt_stab_conv(), est_different(), est_egal(), TroisDto2D::extraire_2D(), Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi_fluide(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Zone::identifie_item_unique(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), T_It_VDF_Elem< _TYPE_ >::impr(), Schema_Temps_base::imprimer_temps_courant(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Champ_front_lu::initialiser(), Ch_front_Vortex::initialiser(), Schema_Temps_base::initialize(), Navier_Stokes_std::initTimeStep(), inverser_par_diagonale(), iterer_eqn_expl(), Mod_turb_hyd_base::limpr_ustar(), Champ_Fonc_MED::lire(), Champ_front_recyclage::lire_fichier_format3(), Perte_Charge_Singuliere::lire_surfaces(), Pave::maille2D(), Pave::maille3D(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_VEF_Face::modifier_pour_Cl(), Zone_VF::orientation(), Zone_VF::orientation_si_definie(), OrienteFacesBord::oriente_faces_bord(), Traitement_particulier_NS_canal::post_traitement_particulier(), Probleme_base::postraiter(), Loi_Etat_Multi_GP_QC::rabot(), Navier_Stokes_std::readOn(), Pave::readOn(), Champ_front_var_instationnaire::reculer(), Champ_front_instationnaire_base::reculer(), Assembleur_P_VDF::remplir(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Faces::reordonner(), Rectangle::reordonner_elem(), Hexaedre::reordonner_elem(), Operateurs_Statistique_tps::reprendre(), Postraitement::reprendre(), Traitement_particulier_NS_canal::reprendre_stat_canal(), Champ_Inc_base::sauvegarder(), Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi_fluide(), ICoCo::ProblemTrio::setInputField(), Format_Post_base::test_coherence(), Loi_horaire::tester(), Champ_P1_isoP1Bulle::trace(), Trianguler::trianguler(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_Face_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_front_var_instationnaire::valeurs_au_temps(), Champ_front_instationnaire_base::valeurs_au_temps(), NettoieNoeuds::verifie_noeuds(), Zone_VEF_PreP1b::verifie_ok_arete(), Probleme_base::verifie_tdeb_tfin(), verifier(), Loi_horaire::verifier_derivee(), and Terme_Source_Canal_perio::write_flow_rate().
{
  double somme = dabs(x1)+dabs(x2);
  return ( (somme < eps) || (dabs(x1-x2) < eps * somme) );
}
int est_egal (double x1, double x2) [inline]
Definition at line 279 of file Double.h.
References est_egal(), and Objet_U::precision_geom.
{
  return est_egal(x1,x2,Objet_U::precision_geom);
}
int inf_ou_egal (double x1, double x2, double eps) [inline]
Definition at line 321 of file Double.h.
References dabs().
Referenced by Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_base::calculer_masse_volumique(), Loi_Etat_GP_base::calculer_masse_volumique(), Terme_Boussinesq_base::check(), Rectangle_axi::contient(), Rectangle::contient(), Hexaedre_axi::contient(), Hexaedre::contient(), coord_barycentrique2D(), coord_barycentrique3D(), inf_ou_egal(), Postraitement::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), Integrale_tps_Champ::mettre_a_jour_integrale(), Navier_Stokes_std::projection_a_faire(), Sous_Zone::readOn(), sup_strict(), and Champ_implementation_Q1::value_interpolation().
{
  double somme=dabs(x1)+dabs(x2);
  return ( (somme < eps) || (x1 < x2 + eps * somme));
}
int inf_ou_egal (double x1, double x2) [inline]
Definition at line 327 of file Double.h.
References inf_ou_egal(), and Objet_U::precision_geom.
{
  return inf_ou_egal(x1,x2,Objet_U::precision_geom);
}
int inf_strict (double x1, double x2, double eps) [inline]
Definition at line 345 of file Double.h.
References dabs().
Referenced by Equation_base::derivee_en_temps_conv(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), inf_strict(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Operateurs_Statistique_tps::reprendre(), Postraitement::reprendre(), and sup_ou_egal().
{
  double somme=dabs(x1)+dabs(x2);
  return ( (somme > eps) && (x1 < x2 - eps * somme) );
}
int inf_strict (double x1, double x2) [inline]
Definition at line 351 of file Double.h.
References inf_strict(), and Objet_U::precision_geom.
{
  return inf_strict(x1,x2,Objet_U::precision_geom);
}
double max (double x, double y) [inline]
Definition at line 180 of file Double.h.
Referenced by Frontiere::add(), Perte_Charge_PolyMAC::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Polyedre::ajouter_elements(), Zone_PolyMAC::ajouter_stabilisation(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Source_Neutronique::aller_au_temps(), build_triofield(), calcul_longueur_filtre(), Reaction::calcul_proportion_implicite(), Changement_phase_Silver_Simpson::calculer(), Op_Dift_VDF_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Elem::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Fluide_reel_base::calculer_masse_volumique(), Reordonner_faces_periodiques::check_faces_periodiques(), Fluide_reel_base::check_unknown_range(), Reordonner_faces_periodiques::chercher_direction_perio(), Multiplicateur_diphasique_Muhler_Steinhagen::coefficient(), Multiplicateur_diphasique_Lottes_Flinn::coefficient(), Multiplicateur_diphasique_homogene::coefficient(), Multiplicateur_diphasique_Friedel::coefficient(), Frottement_interfacial_Sonnenburg::coefficient(), Terme_Source_Constituant::completer(), Operateur_base::completer(), Op_Diff_CoviMAC_base::completer(), Statistiques::compute_avg_min_max_var_per_step(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_pond(), OctreeRoot::construire(), Partitionneur_Sous_Domaine::construire_partition(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), corriger_incr_alpha(), create_listb_from_xyz(), Zone::creer_aretes(), Zone_VDF::dim_face(), ExtrudeParoi::extrude(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Echange_contact_CoviMAC::fgrad(), Ensemble_Lagrange_base::generer_marqueurs_sz(), gmres_local(), Echange_contact_CoviMAC::harmonic_points(), Op_Grad_PolyMAC_Face::impr(), Schema_Temps_base::imprimer_temps_courant(), Op_Diff_CoviMAC_base::init_op_ext(), init_parts(), Zone_PolyMAC::init_we(), Echange_contact_PolyMAC::initialiser(), Navier_Stokes_std::initTimeStep(), Decouper_multi::interpreter(), Redresser_hexaedres_vdf::interpreter_(), Lire_Ideas::interpreter_(), Matrice_Morse::inverse(), kersol(), LambdaL(), Navier_Stokes_std::mettre_a_jour(), Multi_Sch_ThHyd::nb_valeurs_temporelles(), nlinear_interpolation(), Zone_PolyMAC::orthocentrer(), Terme_Source_Constituant::ouvrir_fichier(), Source_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Sonde_Int::postraiter(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Octree::ranger_elem_2D(), Octree::ranger_elem_3D(), Sous_Zone::readOn(), Faces::reordonner(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Solv_Gen::solve(), Probleme_Couple::solveTimeStep(), Op_Diff_VEFP1NCP1B_Face::test(), Schema_Temps_base::update_critere_statio(), Perte_Charge_Singuliere::update_K(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Debog_Pb::verifier(), Debog_Pb::verifier_partie_std(), and Zone_PolyMAC::W_stabiliser().
{
  return(x>y ? x:y);
}
double min (double x, double y) [inline]
Definition at line 199 of file Double.h.
Referenced by Perte_Charge_PolyMAC::ajouter(), Zone_PolyMAC::ajouter_stabilisation(), Sch_CN_iteratif::ajuster_facsec(), Sch_CN_EX_iteratif::ajuster_facsec(), Source_Neutronique::aller_au_temps(), calcul_fac_sec(), Zone_VDF::calcul_h(), Reaction::calcul_proportion_implicite(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Chimie::calculer_pas_de_temps(), Probleme_base::calculer_pas_de_temps(), Equation_base::calculer_pas_de_temps(), Zone_VDF::calculer_volumes_entrelaces(), Fluide_reel_base::check_unknown_range(), Reordonner_faces_periodiques::chercher_direction_perio(), Multiplicateur_diphasique_Muhler_Steinhagen::coefficient(), Multiplicateur_diphasique_Lottes_Flinn::coefficient(), Multiplicateur_diphasique_homogene::coefficient(), Multiplicateur_diphasique_Friedel::coefficient(), Frottement_interfacial_Sonnenburg::coefficient(), Op_Diff_VEF_Face_Penalise::coefficient_penalisation(), Echange_contact_Correlation_VEF::completer(), Echange_contact_Correlation_VDF::completer(), Statistiques::compute_avg_min_max_var_per_step(), Schema_Temps_base::computeTimeStep(), OctreeRoot::construire(), Perte_Charge_PolyMAC::contribuer_a_avec(), Schema_Temps_base::corriger_dt_calcule(), create_listb_naif(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Matrix_tools::extend_matrix(), ExtrudeParoi::extrude(), Ensemble_Lagrange_base::generer_marqueurs_sz(), gmres_local(), Implicite_Multi_TimeStep_calcul_fac_sec(), Champ_P0_VDF::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Face_implementation::imprime_Face(), Echange_contact_Correlation_VEF::init(), Matrice_Morse::inverse(), kersol(), Matrice_Morse::largeur_de_bande(), lire_special(), IntVect::lit(), DoubleVect::lit(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), nlinear_interpolation(), Zone_PolyMAC::orthocentrer(), ppsf(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Octree::ranger_elem_2D(), Octree::ranger_elem_3D(), Sous_Zone::readOn(), Pave::readOn(), Faces::reordonner(), Rectangle::reordonner_elem(), Faces::typer(), Perte_Charge_Singuliere::update_K(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), and Zone_PolyMAC::W_stabiliser().
{
  return(x<y ? x:y);
}
double norme (int n, const double *const a) [inline]
Definition at line 159 of file Double.h.
References F77NAME.
Referenced by Terme_Source_Canal_perio::completer(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Champ_front_tangentiel_VEF::initialiser(), Ch_front_Vortex::initialiser(), Distanceparoi::interpreter_(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), norme_L2(), Champ_P1_isoP1Bulle::norme_L2(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Sonde_Int::ouvrir_fichier(), Sonde::ouvrir_fichier(), PrecondSolv::preconditionner_(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), second_membre(), and test_un_solveur().
{
  const integer un=1;
  const integer m=n ;
  return F77NAME(DNRM2)(&m, a, &un);
}
double* prodvect (const double * a, const double * b, double * resu) [inline]
Definition at line 117 of file Double.h.
Referenced by Tetra_VEF::creer_facette_normales(), Hexa_VEF::creer_facette_normales(), Tetra_VEF::creer_normales_facettes_Cl(), and Hexa_VEF::creer_normales_facettes_Cl().
{
  resu[0]=a[1]*b[2]-a[2]*b[1];
  resu[1]=a[2]*b[0]-a[0]*b[2];
  resu[2]=a[0]*b[1]-a[1]*b[0];
  return(resu);
}
int sup_ou_egal (double x1, double x2) [inline]
Definition at line 398 of file Double.h.
References Objet_U::precision_geom, and sup_ou_egal().
{
  return sup_ou_egal(x1,x2,Objet_U::precision_geom);
}
int sup_ou_egal (double x1, double x2, double eps) [inline]
Definition at line 393 of file Double.h.
References inf_strict().
Referenced by Terme_Boussinesq_base::check(), coord_barycentrique2D(), coord_barycentrique3D(), Postraitement::mettre_a_jour(), Postraitement::postraiter(), Sous_Zone::readOn(), Terme_Source_Canal_perio::source(), and sup_ou_egal().
{
  return !inf_strict(x1,x2,eps);
}
int sup_strict (double x1, double x2) [inline]
Definition at line 374 of file Double.h.
References Objet_U::precision_geom, and sup_strict().
{
  return sup_strict(x1,x2,Objet_U::precision_geom);
}
int sup_strict (double x1, double x2, double eps) [inline]
Definition at line 369 of file Double.h.
References inf_ou_egal().
Referenced by Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_local(), gmres_local(), Navier_Stokes_std::initTimeStep(), Postraitement::mettre_a_jour(), Sous_Zone::readOn(), Segment::reordonner(), sup_strict(), and Aretes::trier_pour_debog().
{
  return !inf_ou_egal(x1,x2,eps);
}