TRUST: src/Kernel/Math/DoubleTab.h File Reference
src/Kernel/Math/DoubleTab.h File Reference
#include <DoubleVect.h>
Classes
class DoubleTab
Tableau a n entrees pour n<= 4
Repose sur un DoubleVect avec calculs de l'indice corespondant
Voir les commentaires de DoubleVect.
Defines
#define MAXDIM_TAB 4
Functions
void mp_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void local_carre_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void mp_carre_norme_tab (const DoubleTab &tableau, ArrOfDouble &norme_colonne)
void local_max_abs_tab (const DoubleTab &tableau, ArrOfDouble &max_colonne)
void mp_max_abs_tab (const DoubleTab &tableau, ArrOfDouble &max_colonne)
Define Documentation
#define MAXDIM_TAB 4
Definition at line 34 of file DoubleTab.h.
Referenced by IntTab::copy(), DoubleTab::copy(), DoubleTab::DoubleTab(), init_dimensions(), IntTab::IntTab(), IntTab::readOn(), DoubleTab::readOn(), IntTab::ref(), DoubleTab::ref(), IntTab::ref_tab(), DoubleTab::ref_tab(), IntTab::resize(), and DoubleTab::resize().
Function Documentation
void local_carre_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 607 of file DoubleTab.cpp.
References MD_Vector_base::get_items_to_sum(), DoubleVect::get_md_vector(), DoubleVect::line_size(), ArrOfDouble::size_array(), ArrOfInt::size_array(), and MD_Vector::valeur().
Referenced by mp_carre_norme_tab().
{
  const ArrOfInt& blocs = tableau.get_md_vector().valeur().get_items_to_sum();
  const int nblocs = blocs.size_array() >> 1;
  const DoubleVect& vect = tableau;
  const int lsize = vect.line_size();
  assert(lsize == norme_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc];
      const int end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = vect[k++];
              norme_colonne[j] += x*x;
            }
        }
    }
}
void local_max_abs_tab (const DoubleTab & tableau, ArrOfDouble & max_colonne)
Definition at line 636 of file DoubleTab.cpp.
References dabs(), MD_Vector_base::get_items_to_compute(), DoubleVect::get_md_vector(), DoubleVect::line_size(), ArrOfDouble::size_array(), ArrOfInt::size_array(), and MD_Vector::valeur().
Referenced by mp_max_abs_tab().
{
  const ArrOfInt& blocs = tableau.get_md_vector().valeur().get_items_to_compute();
  const int nblocs = blocs.size_array() >> 1;
  const DoubleVect& vect = tableau;
  const int lsize = vect.line_size();
  for (int j = 0; j < lsize; j++)
    max_colonne[j] = 0;
  assert(lsize == max_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc];
      const int end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = dabs(vect[k++]);
              max_colonne[j] = (x > max_colonne[j]) ? x : max_colonne[j];
            }
        }
    }
}
void mp_carre_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 630 of file DoubleTab.cpp.
References local_carre_norme_tab(), and mp_sum_for_each_item().
Referenced by mp_norme_tab().
{
  local_carre_norme_tab(tableau, norme_colonne);
  mp_sum_for_each_item(norme_colonne);
}
void mp_max_abs_tab (const DoubleTab & tableau, ArrOfDouble & max_colonne)
Definition at line 661 of file DoubleTab.cpp.
References local_max_abs_tab(), and mp_max_for_each_item().
Referenced by Navier_Stokes_std::initTimeStep(), and Schema_Temps_base::update_critere_statio().
{
  local_max_abs_tab(tableau, max_colonne);
  mp_max_for_each_item(max_colonne);
}
void mp_norme_tab (const DoubleTab & tableau, ArrOfDouble & norme_colonne)
Definition at line 600 of file DoubleTab.cpp.
References mp_carre_norme_tab(), and ArrOfDouble::size_array().
{
  mp_carre_norme_tab(tableau,norme_colonne);
  for (int c=0; c<norme_colonne.size_array(); c++)
    norme_colonne(c)=sqrt(norme_colonne(c));
}