TRUST: src/VEF/Cond_Lim/Echange_contact_Correlation_VEF.cpp File Reference
Echange_contact_Correlation_VEF.cpp File Reference
#include <Echange_contact_Correlation_VEF.h>
#include <Champ_front_calc.h>
#include <Probleme_base.h>
#include <Zone_VEF.h>
#include <Milieu_base.h>
#include <Champ_Uniforme.h>
#include <Domaine.h>
#include <Solv_TDMA.h>
#include <communications.h>
#include <Schema_Comm.h>
#include <EFichier.h>
#include <SFichier.h>
Functions
void Echange_contact_Correlation_VEF_sauvegarder (const Nom &filename, const double temps, const DoubleVect &T)
void Echange_contact_Correlation_VEF_reprendre (const Nom &filename, const double temps, DoubleVect &T)
Variables
const Type_info * Echange_contact_Correlation_VEFbases [1] ={ &(Temperature_imposee_paroi ::info_obj)}
Function Documentation
Echange_contact_Correlation_VEF_reprendre()
void Echange_contact_Correlation_VEF_reprendre (const Nom & filename, const double temps, DoubleVect & T)
< Exit en cas d'erreur de lecture
< Verifie que c'est bien des double
< copie de T
< ne fait rien si pe==0
< ne fait rien si pe==0
< j'envoie un tableau de la bonne taille au proc 0
< je recois le tableau rempli
Definition at line 730 of file Echange_contact_Correlation_VEF.cpp.
{
  const int canal = 56;
  const int nproc = Process::nproc();
  if (Process::je_suis_maitre())
    {
      Cerr << "Echange_contact_Correlation_VEF::mettre_a_jour: reprise dans le fichier "
           << filename << finl;
      EFichier file(filename);
      file.set_error_action(Entree::ERROR_EXIT); //!< Exit en cas d'erreur de lecture
      file.set_check_types(1); //!< Verifie que c'est bien des double
      Nom bidon1, bidon2, temps_lu;
// Le format attendu en entete est "Temps = valeur"
      file >> bidon1 >> bidon2 >> temps_lu;
      if (bidon1 != "Temps" || bidon2 != "=" || temps_lu != temps)
        {
          Cerr << "Erreur dans Echange_contact_Correlation_VEF::mettre_a_jour() :\n"
               << " On attendait l'entet suivante dans le fichier " << filename
               << "\n Temps = " << temps << finl;
          if (temps_lu != temps)
            {
              Cerr << "Le temps indique dans le fichierest different du temps de reprise du calcul " << temps
                   << "Vous ne pouvez pas faire de reprise pour la correlation.\n"
                   << "Supprimez dans la correlation le mot clef \"Reprise\".\n"
                   << "La phase transitoire du calcul sera fausse, mais l'etat stationnaire sera juste." << finl;
            }
          Process::exit();
        }
      DoubleVect tmp(T); //!< copie de T
      double valeur;
      for (int pe = 0; pe < nproc; pe++)
        {
          recevoir(tmp, pe, canal); //!< ne fait rien si pe==0
          const int sz = tmp.size();
          for (int i = 0; i < sz; i++)
            {
// Le format attendu est "T(i) = valeur"
              file >> bidon1 >> bidon2 >> valeur;
              tmp[i] = valeur;
            }
          envoyer(tmp, pe, canal); //!< ne fait rien si pe==0
          if (pe == 0)
            T = tmp;
        }
    }
  else
    {
      envoyer(T, 0, canal); //!< j'envoie un tableau de la bonne taille au proc 0
      recevoir(T, 0, canal);//!< je recois le tableau rempli
    }
}
References Cerr, envoyer(), Entree::ERROR_EXIT, Process::exit(), finl, Process::je_suis_maitre(), Process::nproc(), recevoir(), Entree::set_check_types(), Entree::set_error_action(), TRUSTVect< _TYPE_ >::size(), and valeur().
Referenced by Echange_contact_Correlation_VEF::mettre_a_jour().
Echange_contact_Correlation_VEF_sauvegarder()
void Echange_contact_Correlation_VEF_sauvegarder (const Nom & filename, const double temps, const DoubleVect & T)
< copie de T
< ne fait rien si pe==0
Definition at line 701 of file Echange_contact_Correlation_VEF.cpp.
{
  const int canal = 56;
  const int nproc = Process::nproc();
  if (Process::je_suis_maitre())
    {
      Process::Journal() << "Echange_contact_Correlation_VEF::mettre_a_jour: sauvegarde dans le fichier "
                         << filename << finl;
      SFichier file(filename);
      file << "Temps = " << temps << finl;
      DoubleVect tmp(T); //!< copie de T
      int count = 0;
      for (int pe = 0; pe < nproc; pe++)
        {
          recevoir(tmp, pe, canal); //!< ne fait rien si pe==0
          const int sz = tmp.size();
          for (int i = 0; i < sz; i++)
            {
              file << "T(" << count << ")\t = " << tmp[i] << finl;
              count++;
            }
        }
    }
  else
    {
      envoyer(T, 0, canal);
    }
}
References envoyer(), finl, Process::je_suis_maitre(), Process::Journal(), Process::nproc(), recevoir(), and TRUSTVect< _TYPE_ >::size().
Referenced by Echange_contact_Correlation_VEF::mettre_a_jour().
Variable Documentation
Echange_contact_Correlation_VEFbases
const Type_info* Echange_contact_Correlation_VEFbases[1] ={ &(Temperature_imposee_paroi ::info_obj)}
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.