TRUST: src/VDF/Cond_Lim/Echange_contact_VDF.h File Reference
Echange_contact_VDF.h File Reference
#include <Echange_global_impose.h>
#include <TRUSTTabs_forward.h>
#include <Ref_Champ_Inc.h>
#include <map>
Classes
class Echange_contact_VDF
Functions
void calculer_h_local (DoubleTab &tab, const Equation_base &une_eqn, const Zone_VDF &zvdf_2, const Front_VF &front_vf, const Milieu_base &le_milieu, double invhparoi, int opt)
fin du cas Raccord_local_homogene
Function Documentation
calculer_h_local()
void calculer_h_local (DoubleTab & tab, const Equation_base & une_eqn, const Zone_VDF & zvdf_2, const Front_VF & front_vf, const Milieu_base & le_milieu, double invhparoi, int opt)
fin du cas Raccord_local_homogene
< la conductivite est un Champ uniforme
Definition at line 90 of file Echange_contact_VDF.cpp.
References Milieu_base::conductivite(), Zone_VDF::dist_norm_bord(), Turbulence_paroi_scal_base::equivalent_distance(), Zone_VF::face_voisins(), Zone_VF::front_VF(), Equation_base::get_modele(), Frontiere_dis_base::le_nom(), Modele_turbulence_scal_base::loi_paroi(), Champ_Don::nb_comp(), Front_VF::nb_faces(), Zone::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), ref_cast, TRUSTVect< _TYPE_ >::resize(), sub_type, TURBULENCE, Turbulence_paroi_scal_base::use_equivalent_distance(), Deriv_Champ_Don_base::valeur(), Ref_Objet_U::valeur(), Deriv_Turbulence_paroi_scal_base::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), and Echange_contact_VDF::calculer_h_mon_pb().