TRUST: src/PolyMAC/Cond_Lim/Echange_contact_PolyMAC.cpp File Reference
src/PolyMAC/Cond_Lim/Echange_contact_PolyMAC.cpp File Reference
#include <Echange_contact_PolyMAC.h>
#include <Champ_front_calc.h>
#include <Probleme_base.h>
#include <Champ_Uniforme.h>
#include <Schema_Euler_Implicite.h>
#include <Milieu_base.h>
#include <Zone_PolyMAC.h>
#include <Equation_base.h>
#include <Champ_P0_PolyMAC.h>
#include <Operateur.h>
#include <Op_Diff_PolyMAC_Elem.h>
#include <cmath>
Functions
int meme_point2 (const DoubleVect &a, const DoubleVect &b)
Variables
const Type_info * Echange_contact_PolyMACbases [1] = { &(Echange_externe_impose ::info_obj)}
Function Documentation
int meme_point2 (const DoubleVect & a, const DoubleVect & b)
Definition at line 463 of file Echange_contact_VDF.cpp.
References dabs(), Objet_U::precision_geom, and DoubleVect::size().
Referenced by Echange_contact_VDF::verifier_correspondance().
{
  int dim = x.size();
  assert(dim==y.size());
  int ind =1;
  for (int k=0; k<dim; k++)
    if (dabs(x(k)-y(k))>=Objet_U::precision_geom)
      {
        ind = 0;
        return ind;
      }
  return ind;
}
Variable Documentation
const Type_info* Echange_contact_PolyMACbases[1] = { &(Echange_externe_impose ::info_obj)}
Definition at line 38 of file Echange_contact_PolyMAC.cpp.