TRUST: src/VDF/Cond_Lim/Echange_contact_VDF.cpp File Reference
Echange_contact_VDF.cpp File Reference
#include <Echange_contact_VDF.h>
#include <Champ_front_calc.h>
#include <Probleme_base.h>
#include <Champ_Uniforme.h>
#include <Schema_Euler_Implicite.h>
#include <Milieu_base.h>
#include <Modele_turbulence_scal_base.h>
#include <Zone_VDF.h>
#include <Equation_base.h>
#include <Ref_Turbulence_paroi_scal.h>
#include <Schema_Comm.h>
#include <ArrOfBit.h>
#include <TRUSTTrav.h>
Functions
int meme_point2 (const DoubleVect &a, const DoubleVect &b)
void calculer_h_local (DoubleTab &tab, const Equation_base &une_eqn, const Zone_VDF &zvdf_2, const Front_VF &front_vf, const Milieu_base &le_milieu, double invhparoi, int opt)
fin du cas Raccord_local_homogene
void calculer_h_distant (DoubleTab &tab, const Equation_base &une_eqn, const Zone_VDF &zvdf_2, const Front_VF &front_vf, const Milieu_base &le_milieu, double invhparoi, int opt, const Nom &nom_racc2)
fin du cas Raccord_distant_homogene
Variables
const Type_info * Echange_contact_VDFbases [1] ={ &(Echange_global_impose ::info_obj)}
Function Documentation
calculer_h_distant()
void calculer_h_distant (DoubleTab & tab, const Equation_base & une_eqn, const Zone_VDF & zvdf_2, const Front_VF & front_vf, const Milieu_base & le_milieu, double invhparoi, int opt, const Nom & nom_racc2)
fin du cas Raccord_distant_homogene
< la conductivite est un Champ uniforme
Definition at line 165 of file Echange_contact_VDF.cpp.
References Milieu_base::conductivite(), TRUSTTab< _TYPE_ >::dimension(), Zone_VDF::dist_norm_bord(), Turbulence_paroi_scal_base::equivalent_distance_name(), Frontiere_dis_base::frontiere(), Equation_base::get_modele(), Modele_turbulence_scal_base::loi_paroi(), Champ_Don::nb_comp(), O_U_Ptr::non_nul(), ref_cast, sub_type, Frontiere::trace_elem_distant(), Frontiere::trace_face_distant(), TURBULENCE, Turbulence_paroi_scal_base::use_equivalent_distance(), Deriv_Champ_Don_base::valeur(), Ref_Objet_U::valeur(), Deriv_Turbulence_paroi_scal_base::valeur(), and Champ_Don::valeurs().
Referenced by Echange_contact_VDF::calculer_h_autre_pb().
calculer_h_local()
void calculer_h_local (DoubleTab & tab, const Equation_base & une_eqn, const Zone_VDF & zvdf_2, const Front_VF & front_vf, const Milieu_base & le_milieu, double invhparoi, int opt)
fin du cas Raccord_local_homogene
< la conductivite est un Champ uniforme
Definition at line 90 of file Echange_contact_VDF.cpp.
References Milieu_base::conductivite(), Zone_VDF::dist_norm_bord(), Turbulence_paroi_scal_base::equivalent_distance(), Zone_VF::face_voisins(), Zone_VF::front_VF(), Equation_base::get_modele(), Frontiere_dis_base::le_nom(), Modele_turbulence_scal_base::loi_paroi(), Champ_Don::nb_comp(), Front_VF::nb_faces(), Zone::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), ref_cast, TRUSTVect< _TYPE_ >::resize(), sub_type, TURBULENCE, Turbulence_paroi_scal_base::use_equivalent_distance(), Deriv_Champ_Don_base::valeur(), Ref_Objet_U::valeur(), Deriv_Turbulence_paroi_scal_base::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), and Echange_contact_VDF::calculer_h_mon_pb().
meme_point2()
int meme_point2 (const DoubleVect & a, const DoubleVect & b)
Definition at line 456 of file Echange_contact_VDF.cpp.
{
  int dim = x.size();
  assert(dim==y.size());
  int ind =1;
  for (int k=0; k<dim; k++)
    if (std::fabs(x(k)-y(k))>=Objet_U::precision_geom)
      {
        ind = 0;
        return ind;
      }
  return ind;
}
References Objet_U::precision_geom, and TRUSTVect< _TYPE_ >::size().
Referenced by Echange_contact_VDF::verifier_correspondance().
Variable Documentation
Echange_contact_VDFbases
const Type_info* Echange_contact_VDFbases[1] ={ &(Echange_global_impose ::info_obj)}
Definition at line 30 of file Echange_contact_VDF.cpp.