TRUST: src/Kernel/Utilitaires/Entree.h File Reference
Entree.h File Reference
#include <stdio.h>
#include <cstdio>
#include <iostream>
#include <assert.h>
#include <Process.h>
#include <arch.h>
Classes
class Entree
Classe de definition des operateurs et methodes pour toute lecture dans un flot d'entree<br>(fichier, clavier, tampon de communication, etc)
class Entree_Sortie_Error
Functions
int is_a_binary_file (Nom &)
Entree & operator>> (Entree &, Objet_U &ob)
void convert_to (const char *s, int &ob)
methode de conversion
void convert_to (const char *s, long &ob)
void convert_to (const char *s, float &ob)
void convert_to (const char *s, double &ob)
Function Documentation
convert_to() [1/4]
void convert_to (const char * s, double & ob)
Definition at line 218 of file Entree.cpp.
{
  errno = 0;
  char * errorptr = 0;
  ob = strtod(s, &errorptr);
  if (errno || *errorptr != 0)  error_convert(s,"double");
}
convert_to() [2/4]
void convert_to (const char * s, float & ob)
Definition at line 204 of file Entree.cpp.
{
  errno = 0;
  char * errorptr = 0;
#ifndef _COMPILE_AVEC_GCC_ /* NO_PROCESS */
// PL: strtof n'existe pas semble t'il qu'avec gcc. pour le reste on utiliser strtod
// BM: le risque, c'est qu'on ait un overflow qu'on ne detectera pas avec stdtod
  ob = strtod(s, &errorptr);
#else /* NO_PROCESS */
  ob = strtof(s, &errorptr);
#endif /* NO_PROCESS */
  if (errno || *errorptr != 0)  error_convert(s,"float");
}
References error_convert().
convert_to() [3/4]
void convert_to (const char * s, int & ob)
methode de conversion
Definition at line 170 of file Entree.cpp.
{
  errno = 0;
  char * errorptr = 0;
  ob = strtol(s, &errorptr, 0 /* base 10 par defaut */);
  if (errno || *errorptr != 0) error_convert(s,"int");
}
References error_convert().
Referenced by Entree::operator_template().
convert_to() [4/4]
void convert_to (const char * s, long & ob)
Definition at line 179 of file Entree.cpp.
{
  errno = 0;
  char * errorptr = 0;
  ob = strtol(s, &errorptr, 0 /* base 10 par defaut */);
  if (errno || *errorptr != 0)  error_convert(s,"long");
}
References error_convert().
is_a_binary_file()
int is_a_binary_file (Nom & filename)
Definition at line 391 of file Entree.cpp.
{
// On parcourt les 1000 premiers octets
// Detection tres imparfaite donc limite
// aux fichiers geom de TRUST
  int n=0;
  int c;
  std::ifstream fic(filename.getChar());
// Si on rencontre un caractere ASCII>127
// alors le fichier est de type binaire
  while((c = fic.get()) != EOF && n++<1000)
    if ((c>127)||(c<9))
      return 1;
// GF sous windows les caracteres binaire sont surtout <9
// else printf("ici %d %c \n",c,c);
  return 0;
}
References Nom::getChar().
Referenced by Lire_Fichier::interpreter().
operator>>()
Entree & operator>> (Entree & is, Objet_U & ob)
Definition at line 67 of file Entree.cpp.
{
  return ob.readOn(is);
}