TRUST: src/Kernel/Utilitaires/Entree.cpp File Reference
src/Kernel/Utilitaires/Entree.cpp File Reference
#include <Entree.h>
#include <Objet_U.h>
#include <Nom.h>
#include <errno.h>
#include <iostream>
#include <fstream>
Functions
void convert_to (const char *s, int &ob)
methode de conversion
void convert_to (const char *s, long &ob)
void convert_to (const char *s, long long &ob)
void convert_to (const char *s, float &ob)
void convert_to (const char *s, double &ob)
Entree & operator>> (Entree &is, Objet_U &ob)
int is_a_binary_file (Nom &filename)
Function Documentation
void convert_to (const char * s, int & ob)
methode de conversion
Definition at line 171 of file Entree.cpp.
References Cerr, Process::exit(), and finl.
{
  errno = 0;
  char * errorptr = 0;
  ob = strtol(s, &errorptr, 0 /* base 10 par defaut */);
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type long : string = " << s << finl;
      Process::exit();
    }
}
void convert_to (const char * s, long & ob)
Definition at line 183 of file Entree.cpp.
References Cerr, Process::exit(), and finl.
{
  errno = 0;
  char * errorptr = 0;
  ob = strtol(s, &errorptr, 0 /* base 10 par defaut */);
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type long : string = " << s << finl;
      Process::exit();
    }
}
void convert_to (const char * s, float & ob)
Definition at line 214 of file Entree.cpp.
References Cerr, Process::exit(), and finl.
{
  errno = 0;
  char * errorptr = 0;
#ifndef _COMPILE_AVEC_GCC_ /* NO_PROCESS */
// PL: strtof n'existe pas semble t'il qu'avec gcc. pour le reste on utiliser strtod
// BM: le risque, c'est qu'on ait un overflow qu'on ne detectera pas avec stdtod
  ob = strtod(s, &errorptr);
#else /* NO_PROCESS */
  ob = strtof(s, &errorptr);
#endif /* NO_PROCESS */
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type float : string = " << s << finl;
      Process::exit();
    }
}
void convert_to (const char * s, double & ob)
Definition at line 232 of file Entree.cpp.
References Cerr, Process::exit(), and finl.
Referenced by extract_time_from_string(), Perte_Charge_Singuliere::lire_donnees(), Entree::operator>>(), and Champ_Fonc_reprise::readOn().
{
  errno = 0;
  char * errorptr = 0;
  ob = strtod(s, &errorptr);
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type float : string = " << s << finl;
      Process::exit();
    }
}
void convert_to (const char * s, long long & ob)
Definition at line 195 of file Entree.cpp.
References Cerr, Process::exit(), and finl.
{
  errno = 0;
  char * errorptr = 0;
#ifdef HPPA_11 /* NO_PROCESS */
  ob = strtol(s, &errorptr, 0 /* base 10 par defaut */);
#else /* NO_PROCESS */
#ifdef MICROSOFT
  ob = _strtoi64(s, &errorptr, 0 /* base 10 par defaut */);
#else
  ob = strtoll(s, &errorptr, 0 /* base 10 par defaut */);
#endif
#endif /* NO_PROCESS */
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type long long : string = " << s << finl;
      Process::exit();
    }
}
int is_a_binary_file (Nom & filename)
Definition at line 682 of file Entree.cpp.
References Nom::getChar().
Referenced by Lire_Fichier::interpreter().
{
// On parcourt les 1000 premiers octets
// Detection tres imparfaite donc limite
// aux fichiers geom de TRUST
  int n=0;
  int c;
  std::ifstream fic(filename.getChar());
// Si on rencontre un caractere ASCII>127
// alors le fichier est de type binaire
  while((c = fic.get()) != EOF && n++<1000)
    if ((c>127)||(c<9))
      return 1;
// GF sous windows les caracteres binaire sont surtout <9
// else printf("ici %d %c \n",c,c);
  return 0;
}
Entree& operator>> (Entree & is, Objet_U & ob)
Definition at line 544 of file Entree.cpp.
References Objet_U::readOn().
{
  return ob.readOn(is);
}