TRUST: src/VDF/Operateurs/Evaluateurs/Eval_centre4_VDF_Face.h File Reference
src/VDF/Operateurs/Evaluateurs/Eval_centre4_VDF_Face.h File Reference
#include <Eval_Conv_VDF.h>
#include <Eval_VDF_Face.h>
#include <Zone_VDF.h>
Classes
class Eval_centre4_VDF_Face
class Eval_centre4_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection centre4 (sur 4 points)
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
Functions
void calcul_g (const double &dxam, const double &dx, const double &dxav, double &g1, double &g2, double &g3, double &g4)
double conv_centre (const double &psc, const double &vit_0_0, const double &vit_0, const double &vit_1, const double &vit1_1, double g1, double g2, double g3, double g4)
Function Documentation
void calcul_g (const double & dxam, const double & dx, const double & dxav, double & g1, double & g2, double & g3, double & g4) [inline]
Definition at line 221 of file Eval_centre4_VDF_Face.h.
Referenced by Eval_centre4_VDF_Face::flux_arete_interne(), Eval_centre4_VDF_Face::flux_arete_periodicite(), and Eval_centre4_VDF_Face::flux_fa7_elem().
{
  g1 = -dx*dx*(dx/2+dxav)/(4*(dx+dxam+dxav)*(dx+dxam)*dxam);
  g2 =  (dx+2*dxam)*(dx+2*dxav)/(8*dxam*(dx+dxav));
  g3 =  (dx+2*dxam)*(dx+2*dxav)/(8*dxav*(dx+dxam));
  g4 = -dx*dx*(dx/2+dxam)/(4*(dx+dxam+dxav)*dxav*(dx+dxav));
}
double conv_centre (const double & psc, const double & vit_0_0, const double & vit_0, const double & vit_1, const double & vit1_1, double g1, double g2, double g3, double g4) [inline]
Definition at line 229 of file Eval_centre4_VDF_Face.h.
Referenced by Eval_centre4_VDF_Face::flux_arete_interne(), Eval_centre4_VDF_Face::flux_arete_periodicite(), and Eval_centre4_VDF_Face::flux_fa7_elem().
{
  return  (g1*vit_0_0 + g2*vit_0 + g3*vit_1 + g4*vit1_1) * psc;
}