TRUST: src/VDF/Axi/Operateurs/Evaluateurs/Eval_Quick_VDF_Face_Axi.h File Reference
src/VDF/Axi/Operateurs/Evaluateurs/Eval_Quick_VDF_Face_Axi.h File Reference
#include <Eval_Conv_VDF.h>
#include <Eval_VDF_Face.h>
#include <Zone_VDF.h>
Classes
class Eval_Quick_VDF_Face_Axi
class Eval_Quick_VDF_Face_Axi
Evaluateur VDF pour la convection en coordonnees cylindriques
Le champ convecte est un Champ_Face
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
Functions
double sharp (const double &utc)
double conv_quick_sharp_plus (const double &psc, const double &vit_0, const double &vit_1, const double &vit_0_0, const double &dx, const double &dm, const double &dxam)
double conv_quick_sharp_moins (const double &psc, const double &vit_0, const double &vit_1, const double &vit_1_1, const double &dx, const double &dm, const double &dxam)
Function Documentation
double conv_quick_sharp_moins (const double & psc, const double & vit_0, const double & vit_1, const double & vit_1_1, const double & dx, const double & dm, const double & dxam) [inline]
Definition at line 234 of file Eval_Quick_VDF_Face_Axi.h.
References dabs(), and sharp().
Referenced by Eval_Quick_VDF_Face::flux_arete_interne(), Eval_Quick_VDF_Face_Axi::flux_arete_interne(), Eval_Quick_VDF_Face::flux_fa7_elem(), and Eval_Quick_VDF_Face_Axi::flux_fa7_elem().
{
  double cf;
  double curv;
  double delta_1 = vit_1_1 - vit_1;
  double delta = vit_1 - vit_0;
  double dd1,utc;
  double delta_delta;
  curv = ( delta_1/dxam - delta/dx )/dm ;
// Calcul de cf:
  delta_delta = delta_1+delta;
  dd1 = dabs(delta_delta);
  if (dd1 < 1.e-5)
    cf = 0.125;
  else
    {
      utc = delta_1/delta_delta;
      cf = sharp(utc);
    }
  return (0.5*(vit_0 + vit_1) - cf*(dx*dx)*curv)*psc;
}
double conv_quick_sharp_plus (const double & psc, const double & vit_0, const double & vit_1, const double & vit_0_0, const double & dx, const double & dm, const double & dxam) [inline]
Definition at line 205 of file Eval_Quick_VDF_Face_Axi.h.
References dabs(), and sharp().
Referenced by Eval_Quick_VDF_Face::flux_arete_interne(), Eval_Quick_VDF_Face_Axi::flux_arete_interne(), Eval_Quick_VDF_Face::flux_fa7_elem(), and Eval_Quick_VDF_Face_Axi::flux_fa7_elem().
{
  double cf;
  double curv;
  double delta_0 = vit_0 - vit_0_0;
  double delta = vit_1 - vit_0;
  double dd1,utc;
  double delta_delta;
  curv = (delta/dx - delta_0/dxam)/dm ;
// Calcul de cf:
  delta_delta = delta_0+delta;
  dd1 = dabs(delta_delta);
  if (dd1 < 1.e-5)
    cf = 0.125;
  else
    {
      utc = delta_0/delta_delta;
      cf = sharp(utc);
    }
// Cerr << "cf " << cf << " dx " << dx << " dxam " << dxam << " dm " << dm << finl ;
  return (0.5*(vit_0 + vit_1) - cf*(dx*dx)*curv)*psc;
}
double sharp (const double & utc) [inline]
Definition at line 189 of file Eval_Quick_VDF_Face_Axi.h.
Referenced by conv_quick_sharp_moins(), and conv_quick_sharp_plus().
{
  double cf;
  if ( (utc <= -1) || (utc >= 1.5) )
    cf = 0.125;
  else if ((utc > -1) && (utc <= 0) )
    cf = 0.5 + 0.375*utc;
  else if ((utc <= 0.25) && (utc > 0) )
    cf = 0.5 - 0.625*sqrt(utc);
  else if ((utc > 0.25) && (utc <= 1.) )
    cf = 0.25*(1.-utc);
  else
    cf = 0.25*(utc-1.);
  return cf;
}