TRUST: src/VDF/Operateurs/Evaluateurs/Eval_centre4_VDF_Elem.h File Reference
src/VDF/Operateurs/Evaluateurs/Eval_centre4_VDF_Elem.h File Reference
#include <Eval_Conv_VDF.h>
#include <Eval_VDF_Elem.h>
#include <Zone_VDF.h>
#include <Champ_P0_VDF.h>
Classes
class Eval_centre4_VDF_Elem
class Eval_centre4_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Centre
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
Functions
double Fram4 (const double &s1, const double &s2, const double &s3, const double &s4)
Function Documentation
double Fram4 (const double & s1, const double & s2, const double & s3, const double & s4) [inline]
Definition at line 1256 of file Eval_centre4_VDF_Elem.h.
References dabs(), dmax(), dmin(), and DMINFLOAT.
{
  double smin0 = dmin(s4,s2);
  double smax0 = dmax(s4,s2);
  double smin1 = dmin(s3,s1);
  double smax1 = dmax(s3,s1);
  double sr0 = (s3-smin0)/(smax0-smin0+DMINFLOAT);
  double sr1 = (s2-smin1)/(smax1-smin1+DMINFLOAT);
  double fr = 2.*dmax(dabs(sr0-0.5),dabs(sr1-0.5));
  fr *= fr;
  fr *= fr;
  return dmin(fr,1.0);
}