TRUST: src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_tools.h File Reference
Eval_Conv_VDF_tools.h File Reference
#include <TRUSTTab.h>
#include <Double.h>
Classes
class Eval_Conv_VDF_tools
Functions
double Fram4 (const double s1, const double s2, const double s3, const double s4)
double Fram (const double s1, const double s2, const double s3, const double s4)
double sharp2 (const double utc)
Function Documentation
Fram()
double Fram (const double s1, const double s2, const double s3, const double s4) inline
Definition at line 83 of file Eval_Conv_VDF_tools.h.
{
  double smin0 = std::min(s4,s2), smax0 = std::max(s4,s2), smin1 = std::min(s3,s1), smax1 = std::max(s3,s1);
  double sr0 = (std::fabs(smax0-smin0)<DMINFLOAT ? 0. : (s3-smin0)/(smax0-smin0));
  double sr1 = (std::fabs(smax1-smin1)<DMINFLOAT ? 0. : (s2-smin1)/(smax1-smin1));
  double fr = 2.*std::max(std::fabs(sr0-0.5),std::fabs(sr1-0.5));
  fr *= fr;
  fr *= fr;
  return std::min(fr,1.0);
}
References DMINFLOAT.
Referenced by Eval_Conv_VDF_tools::quick_fram_impl().
Fram4()
double Fram4 (const double s1, const double s2, const double s3, const double s4) inline
Definition at line 72 of file Eval_Conv_VDF_tools.h.
{
  double smin0 = std::min(s4,s2), smax0 = std::max(s4,s2), smin1 = std::min(s3,s1), smax1 = std::max(s3,s1);
  double sr0 = (s3-smin0)/(smax0-smin0+DMINFLOAT), sr1 = (s2-smin1)/(smax1-smin1+DMINFLOAT);
  double fr = 2.*std::max(std::fabs(sr0-0.5),std::fabs(sr1-0.5));
  fr *= fr;
  fr *= fr;
  return std::min(fr,1.0);
}
References DMINFLOAT.
sharp2()
double sharp2 (const double utc) inline
Definition at line 95 of file Eval_Conv_VDF_tools.h.
{
  double cf;
  if ( (utc <= -1) || (utc >= 1.5) ) cf = 0.125;
  else if ((utc > -1) && (utc <= 0) ) cf = 0.5 + 0.375*utc;
  else if ((utc <= 0.25) && (utc > 0) ) cf = 0.5 - 0.625*sqrt(utc);
  else if ((utc > 0.25) && (utc <= 1.) ) cf = 0.25*(1.-utc);
  else cf = 0.25*(utc-1.);
  return cf;
}
Referenced by Eval_Conv_VDF_tools::conv_quick_sharp_moins_impl(), and Eval_Conv_VDF_tools::conv_quick_sharp_plus_impl().