TRUST: src/Kernel/Geometrie/Extruder.cpp File Reference
src/Kernel/Geometrie/Extruder.cpp File Reference
#include <Extruder.h>
#include <Domaine.h>
#include <Static_Int_Lists.h>
#include <Connectivite_som_elem.h>
#include <Faces_builder.h>
#include <Scatter.h>
#include <Param.h>
Functions
void check_boundary_name (const Nom &name)
Variables
const Type_info * Extruderbases [1] = { &(Interprete_geometrique_base ::info_obj)}
Function Documentation
void check_boundary_name (const Nom & name) [inline]
Definition at line 112 of file Extruder.cpp.
References Cerr, Process::exit(), and finl.
Referenced by Extruder::extruder_dvt(), and Extruder::extruder_dvt_hexa().
{
// On verifie que le bord ne se nomme pas deja devant ou derriere
  if (name=="devant" || name=="derriere")
    {
      Cerr << "Problem : you must change the name of the boundary  : " <<name<<finl;
      Cerr << "because the extrusion keyword is going to create new boundaries named derriere and devant" << finl;
      Cerr << "which will create a conflict." << finl;
      Process::exit();
    }
}
Variable Documentation
const Type_info* Extruderbases[1] = { &(Interprete_geometrique_base ::info_obj)}
Definition at line 31 of file Extruder.cpp.