TRUST: src/Kernel/Geometrie/Extraire_plan.cpp File Reference
Extraire_plan.cpp File Reference
#include <Extraire_plan.h>
#include <Domaine.h>
#include <Param.h>
#include <Probleme_base.h>
#include <Equation_base.h>
#include <Zone_VF.h>
#include <NettoieNoeuds.h>
#include <EChaine.h>
#include <SChaine.h>
#include <Extraire_surface.h>
Functions
void calcul_normal (const ArrOfDouble &origine, const ArrOfDouble &point1, const ArrOfDouble &point2, ArrOfDouble &normal)
void calcul_normal_norme (const ArrOfDouble &org, const ArrOfDouble &point1, const ArrOfDouble &point2, ArrOfDouble &normal)
Variables
const Type_info * Extraire_planbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
calcul_normal()
void calcul_normal (const ArrOfDouble & origine, const ArrOfDouble & point1, const ArrOfDouble & point2, ArrOfDouble & normal)
Definition at line 68 of file Extraire_plan.cpp.
{
  normal[0]=(point1[1]-origine[1])*(point2[2]-origine[2])-((point2[1]-origine[1])*(point1[2]-origine[2]));
  normal[1]=(point1[2]-origine[2])*(point2[0]-origine[0])-((point2[2]-origine[2])*(point1[0]-origine[0]));
  normal[2]=(point1[0]-origine[0])*(point2[1]-origine[1])-((point2[0]-origine[0])*(point1[1]-origine[1]));
}
Referenced by calcul_normal_norme(), Extraire_surface::extraire_surface(), and Extraire_plan::interpreter_().
calcul_normal_norme()
void calcul_normal_norme (const ArrOfDouble & org, const ArrOfDouble & point1, const ArrOfDouble & point2, ArrOfDouble & normal)
Definition at line 76 of file Extraire_plan.cpp.
{
  calcul_normal(org, point1,  point2,normal);
  normal/=norme_array(normal);
}
References calcul_normal(), and norme_array().
Referenced by Integrer_champ_med::interpreter(), and Extraire_plan::interpreter_().
Variable Documentation
Extraire_planbases
const Type_info* Extraire_planbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 27 of file Extraire_plan.cpp.