TRUST: src/Kernel/Geometrie/ExtrudeParoi.cpp File Reference
ExtrudeParoi.cpp File Reference
#include <Connectivite_som_elem.h>
#include <Static_Int_Lists.h>
#include <Faces_builder.h>
#include <ExtrudeParoi.h>
#include <Array_tools.h>
#include <TRUSTList.h>
#include <TRUSTTab.h>
#include <Domaine.h>
#include <Scatter.h>
#include <Param.h>
Functions
void calcul_normal2 (const ArrOfDouble &pt0, const ArrOfDouble &pt1, const ArrOfDouble &pt2, ArrOfDouble &normal)
void calcul_normal_norme2 (const ArrOfDouble &pt0, const ArrOfDouble &pt1, const ArrOfDouble &pt2, ArrOfDouble &normal)
void calcul_tab_norme (DoubleTab &tab)
Variables
const Type_info * ExtrudeParoibases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
calcul_normal2()
void calcul_normal2 (const ArrOfDouble & pt0, const ArrOfDouble & pt1, const ArrOfDouble & pt2, ArrOfDouble & normal)
Definition at line 58 of file ExtrudeParoi.cpp.
{
  normal[0]=(pt1[1]-pt0[1])*(pt2[2]-pt0[2])-((pt2[1]-pt0[1])*(pt1[2]-pt0[2]));
  normal[1]=(pt1[2]-pt0[2])*(pt2[0]-pt0[0])-((pt2[2]-pt0[2])*(pt1[0]-pt0[0]));
  normal[2]=(pt1[0]-pt0[0])*(pt2[1]-pt0[1])-((pt2[0]-pt0[0])*(pt1[1]-pt0[1]));
}
Referenced by calcul_normal_norme2().
calcul_normal_norme2()
void calcul_normal_norme2 (const ArrOfDouble & pt0, const ArrOfDouble & pt1, const ArrOfDouble & pt2, ArrOfDouble & normal)
Definition at line 65 of file ExtrudeParoi.cpp.
{
  calcul_normal2(pt0, pt1,  pt2, normal);
  normal/=norme_array(normal);
}
References calcul_normal2(), and norme_array().
Referenced by ExtrudeParoi::extrude().
calcul_tab_norme()
void calcul_tab_norme (DoubleTab & tab)
Definition at line 72 of file ExtrudeParoi.cpp.
{
  for(int i=0; i<tab.dimension(0); i++)
    {
      double norm = sqrt(tab(i,0)*tab(i,0)+tab(i,1)*tab(i,1)+tab(i,2)*tab(i,2));
      norm += DMINFLOAT;
      tab(i,0)/=norm;
      tab(i,1)/=norm;
      tab(i,2)/=norm;
    }
}
References TRUSTTab< _TYPE_ >::dimension(), and DMINFLOAT.
Referenced by ExtrudeParoi::extrude().
Variable Documentation
ExtrudeParoibases
const Type_info* ExtrudeParoibases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 27 of file ExtrudeParoi.cpp.