TRUST: src/Kernel/Geometrie/Faces2.h File Reference
src/Kernel/Geometrie/Faces2.h File Reference
#include <Faces.h>
#include <IntLists.h>
Functions
int ppsf (const Faces &faces, int face, int nb_som)
Fonction hors classe
Renvoie le numero du plus petit (au sens de la
numerotation des sommets) sommet d'une face.
int same (const Faces &faces1, int f1, const Faces &faces2, int f2, int nb_som)
Fonction hors classe
Compare 2 faces de 2 ensembles de faces f1 et f2
et Renvoie 1 si elles sont egales, 0 Sinon.
void ajouter (Faces &faces, int &premier, const Faces &les_faces, IntLists &listes, int nb_som_face)
Fonction hors classe.
Function Documentation
void ajouter (Faces & faces, int & premier, const Faces & les_faces, IntLists & listes, int nb_som_face)
Fonction hors classe.
Definition at line 152 of file Faces2.cpp.
References Faces::nb_faces(), ppsf(), Faces::sommet(), and Faces::voisin().
Referenced by T_It_Sou_VDF_Face< _TYPE_ >::calculer(), T_It_Sou_VDF_Elem< _TYPE_ >::calculer(), T_It_VDF_Face< _TYPE_ >::calculer(), T_It_VDF_Elem< _TYPE_ >::calculer(), T_It_PolyMAC_Elem< _TYPE_ >::calculer(), and Equation_base::Gradient_conjugue_diff_impl().
{
  for(int face=0; face<les_faces.nb_faces(); face++)
    {
      faces.voisin(premier,0)=les_faces.voisin(face,0);
      faces.voisin(premier,1)=les_faces.voisin(face,1);
      int numero=ppsf(les_faces, face, nb_som_face);
      for(int i=0; i<nb_som_face; i++)
        faces.sommet(premier,i)=les_faces.sommet(face,i);
      listes[numero].add(premier++);
    }
}
int ppsf (const Faces & faces, int face, int nb_som)
Fonction hors classe
Renvoie le numero du plus petit (au sens de la
numerotation des sommets) sommet d'une face.
Returns:
int
Signification: le numero du plus petit sommet la face specifiee
Contraintes:
Definition at line 50 of file Faces2.cpp.
References min(), and Faces::sommet().
Referenced by ajouter(), and Faces::compare().
{
  int sommet=faces.sommet(face,0);
  for(int imin=1; imin < nb_som; imin++)
    sommet=min(sommet,faces.sommet(face,imin));
  return sommet;
}
int same (const Faces & faces1, int f1, const Faces & faces2, int f2, int nb_som)
Fonction hors classe
Compare 2 faces de 2 ensembles de faces f1 et f2
et Renvoie 1 si elles sont egales, 0 Sinon.
Returns:
int
Signification: 1 si les 2 faces sont les memes
0 sinon
Contraintes:
< memes sommets
< sommet pas trouve ==> pas meme face
Definition at line 98 of file Faces2.cpp.
References Faces::sommet().
Referenced by Faces::compare(), Sonde::initialiser(), and Matrice_Dense::is_the_same().
{
  int ok=1;
  for(int i=0; ((i<nb_som) && ok ); i++)
    {
      int nok=1;
      for(int j=0; ((j<nb_som) && nok ); j++)
        {
          if( faces1.sommet(f1, i) == faces2.sommet(f2, j))
            nok=0;           //!< memes sommets
        }
      if(nok) ok=0;          //!< sommet pas trouve ==> pas meme face
    }
  return ok;
}