TRUST: src/Kernel/Geometrie/Faces.cpp File Reference
Faces.cpp File Reference
#include <Faces.h>
#include <Faces2.h>
#include <DomaineAxi1d.h>
#include <communications.h>
#include <Linear_algebra_tools_impl.h>
Functions
void calculer_centres_gravite (DoubleTab &xv, Type_Face type_face_, const DoubleTab &coord, const IntTab &sommet)
Variables
const Type_info * Facesbases [1] ={ &(Objet_U ::info_obj)}
Function Documentation
calculer_centres_gravite()
void calculer_centres_gravite (DoubleTab & xv, Type_Face type_face_, const DoubleTab & coord, const IntTab & sommet)
Definition at line 867 of file Faces.cpp.
{
  int nb_faces_tot = sommet.dimension_tot(0);
  int dim = coord.dimension(1);
  xv.resize(nb_faces_tot, dim);
// Copie le descripteur parallele du tableau sommet:
  xv.set_md_vector(sommet.get_md_vector());
  if(nb_faces_tot!=0)
    {
      int nb_som_faces=sommet.dimension(1);
      double inv=1./nb_som_faces;
      int k, som;
      xv = 0;
      if(Objet_U::axi)
        {
          switch(type_face_)
            {
            case  Faces::segment_2D_axi :
              {
                for (int face=0; face<nb_faces_tot; face++)
                  {
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 0)+=coord(sommet(face ,som), 0);
                    double teta_0=coord(sommet(face ,0), 1);
                    double teta_1=coord(sommet(face ,1), 1);
                    double teta_min=std::min(teta_1, teta_0);
                    double teta_max=std::max(teta_1, teta_0);
                    double d_teta=teta_max-teta_min;
                    if( (teta_min==0.) && (d_teta>M_PI) )
                      {
                        teta_min+=2.*M_PI;
                      }
                    {
                      xv(face, 1)+=(teta_min+teta_max);
                    }
                  }
                break;
              }
            case Faces::quadrangle_3D_axi :
              {
                for (int face=0; face<nb_faces_tot; face++)
                  {
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 0)+=coord(sommet(face ,som), 0);
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 2)+=coord(sommet(face ,som), 2);
                    double teta_0=coord(sommet(face ,0), 1);
                    double teta_1=coord(sommet(face ,1), 1);
                    double teta_2=coord(sommet(face ,2), 1);
                    double teta_3=coord(sommet(face ,3), 1);
                    double teta_min=std::min(teta_1, teta_0);
                    teta_min=std::min(teta_min, teta_2);
                    teta_min=std::min(teta_min, teta_3);
                    double teta_max=std::max(teta_1, teta_0);
                    teta_max=std::max(teta_min, teta_2);
                    teta_max=std::max(teta_min, teta_3);
                    double d_teta=teta_max-teta_min;
                    if( (teta_min==0.) && (d_teta>M_PI) )
                      {
                        if(teta_0==0.) teta_0+=2.*M_PI;
                        if(teta_1==0.) teta_1+=2.*M_PI;
                        if(teta_2==0.) teta_2+=2.*M_PI;
                        if(teta_3==0.) teta_3+=2.*M_PI;
                      }
                    {
                      xv(face, 1)+=(teta_0+teta_1+teta_2+teta_3) ;
                    }
                  }
                break;
              }
            default:
              {
                Cerr << "Face type number " << (int)type_face_ << " not provided in Faces::calculer_centres_gravite" << finl;
                break;
              }
            }
          xv*=inv;
        }
      else
        {
          for (int face=0; face<nb_faces_tot; face++)
            {
              int nb_som=nb_som_faces;
              while (sommet(face,nb_som-1)==-1) nb_som--;
              inv=1./nb_som;
              for(k=0; k<dim; k++)
                for(som=0; som < nb_som; som++)
                  xv(face, k)+=coord(sommet(face ,som), k);
              for(k=0; k<dim; k++)
                xv(face, k)*=inv;
            }
        }
    }
}
References Objet_U::axi, Cerr, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), M_PI, Faces::quadrangle_3D_axi, TRUSTTab< _TYPE_ >::resize(), Faces::segment_2D_axi, and TRUSTTab< _TYPE_ >::set_md_vector().
Referenced by DecoupeBord::Decouper().
Variable Documentation
Facesbases
const Type_info* Facesbases[1] ={ &(Objet_U ::info_obj)}
Definition at line 23 of file Faces.cpp.