TRUST: src/Kernel/Geometrie/Faces_builder.cpp File Reference
Faces_builder.cpp File Reference
#include <Connectivite_som_elem.h>
#include <EcrFicCollecteBin.h>
#include <MD_Vector_tools.h>
#include <Poly_geom_base.h>
#include <Elem_geom_base.h>
#include <communications.h>
#include <NettoieNoeuds.h>
#include <Faces_builder.h>
#include <MD_Vector_std.h>
#include <Schema_Comm.h>
#include <Array_tools.h>
#include <Domaine.h>
#include <Scatter.h>
#include <Faces2.h>
#include <stdio.h>
#include <vector>
#include <array>
#include <map>
Functions
static void echanger_tableau_aretes (const IntTab &elem_aretes, int nb_aretes_reelles, ArrOfInt &tab_aretes)
Cette methode permet de faire un echange espace virtuel d'un tableau aux aretes
sans passer par le descripteur des aretes. On utilise le tableau elem_aretes et l'echange
espace virtuel des elements.
Function Documentation
echanger_tableau_aretes()
static void echanger_tableau_aretes (const IntTab & elem_aretes, int nb_aretes_reelles, ArrOfInt & tab_aretes) static
Cette methode permet de faire un echange espace virtuel d'un tableau aux aretes
sans passer par le descripteur des aretes. On utilise le tableau elem_aretes et l'echange
espace virtuel des elements.
< initialise avec "moi"
< copier uniquement la structure
Definition at line 845 of file Faces_builder.cpp.
{
  const int moi = Process::me();
  const int nb_elem = elem_aretes.dimension(0);
  const int nb_elem_tot = elem_aretes.dimension_tot(0);
  const int nb_aretes_elem = elem_aretes.dimension(1);
  int i;
// **********************
// I) Echange pour mettre a jour les items communs
// Algo un peu complique pour mettre a jour les items communs: pour chaque arete reele,
// la valeur de tab_aretes doit etre egale a la valeur initiale de tab_arete donnee par
// le processeur de rang le plus petit parmi ceux qui partagent l'arete (c'est a dire
// les processeurs qui ont un element adjacent a cette arete).
// Tableau permettant de connaitre le processeur proprietaire d'une arete reele
  ArrOfInt pe_arete(nb_aretes_reelles);
  pe_arete= moi;
// Tableau qui donne, pour chaque element, le processeur proprietaire
  IntVect pe_elem(nb_elem_tot);
  pe_elem= moi; //!< initialise avec "moi"
  {
    pe_elem.set_md_vector(elem_aretes.get_md_vector());
    pe_elem.echange_espace_virtuel();
// On range dans pe_arete le numero du plus petit processeur proprietaire des
// elements adjacents a cette arete
// Inutile de parcourir les elements reels, on va trouver pe_elem[i]==moi...
// Si l'arete se trouve sur un processeur de rang inferieur, on lui attribue
    for (i = nb_elem; i < nb_elem_tot; i++)
      for (int pe = pe_elem[i], j = 0, a; j < nb_aretes_elem && (a = elem_aretes(i, j)) >= 0; j++)
        if (a < nb_aretes_reelles && pe_arete[a] > pe)
          pe_arete[a] = pe;
  }
// On suppose que l'espace virtuel des elements contient au moins une couche d'elements virtuels
// (tous les voisins des elements reels par des sommets) alors les aretes reelles sont
// echangees (pas encore les aretes virtuelles)
// Dans ce cas, pe_arete est maintenant correctement rempli pour les aretes reelles.
  IntTab tmp;
  tmp.copy(elem_aretes, Array_base::NOCOPY_NOINIT); //!< copier uniquement la structure
// Copier tab_aretes dans la structure tmp (on sait echanger tmp, pas tab_aretes)
  for (i = 0; i < nb_elem; i++)
    for (int j = 0, a; j < nb_aretes_elem && (a = elem_aretes(i, j)) >= 0; j++)
      tmp(i, j) = tab_aretes[a];
// 2) Echange du tableau
  tmp.echange_espace_virtuel();
// 3) On reverse dans la partie reelle de tab_aretes les valeurs prises dans tmp:
// pour une arete partagee par plusieurs procs, c'est le proc de rang le plus petit
// qui donne la valeur
// Inutile de parcourir les elements reels, la valeur ne changerait pas
  for (i = nb_elem; i < nb_elem_tot; i++)
    for (int pe = pe_elem[i], j = 0, a; j < nb_aretes_elem && (a = elem_aretes(i, j)) >= 0; j++)
      if (a < nb_aretes_reelles && pe_arete[a] == pe)
        tab_aretes[a] = tmp(i, j);
// tab_aretes contient maintenant des valeurs correctes pour toutes les aretes reeles
// (les items communs sont a jour). On fait encore un echange en passant par tmp pour
// mettre a jour les items virtuels:
// ******************
// II) echange pour mettre a jour l'espace virtuel des aretes
// Copier encore une fois tab_aretes dans la structure tmp
  for (i = 0; i < nb_elem; i++)
    for (int j = 0, a; j < nb_aretes_elem && (a = elem_aretes(i, j)) >= 0; j++)
      tmp(i, j) = tab_aretes[a];
// Echange du tableau
  tmp.echange_espace_virtuel();
// Recopie de tmp dans tab_aretes
  for (i = nb_elem; i < nb_elem_tot; i++)
    for (int j = 0, a; j < nb_aretes_elem && (a = elem_aretes(i, j)) >= 0; j++)
      tab_aretes[a] = tmp(i, j);
}
References TRUSTTab< _TYPE_ >::copy(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::get_md_vector(), Process::me(), Array_base::NOCOPY_NOINIT, and TRUSTVect< _TYPE_ >::set_md_vector().
Referenced by Zone::creer_aretes().