TRUST: src/Kernel/Geometrie/Faces.h File Reference
src/Kernel/Geometrie/Faces.h File Reference
#include <IntTab.h>
#include <Ref_Zone.h>
Classes
class Faces
enum Type_Face
Les differents types geometriques de faces.
Typedefs
typedef Faces::Type_Face Type_Face
Functions
void calculer_centres_gravite (DoubleTab &xv, Type_Face type_face_, const DoubleTab &coord, const IntTab &sommet)
Typedef Documentation
typedef Faces::Type_Face Type_Face
Definition at line 112 of file Faces.h.
Function Documentation
void calculer_centres_gravite (DoubleTab & xv, Type_Face type_face_, const DoubleTab & coord, const IntTab & sommet)
Definition at line 873 of file Faces.cpp.
References Objet_U::axi, Cerr, IntTab::dimension(), DoubleTab::dimension(), IntTab::dimension_tot(), dmax(), dmin(), finl, IntVect::get_md_vector(), M_PI, Faces::quadrangle_3D_axi, DoubleTab::resize(), Faces::segment_2D_axi, and DoubleTab::set_md_vector().
Referenced by DecoupeBord::Decouper().
{
  int nb_faces_tot = sommet.dimension_tot(0);
  int dim = coord.dimension(1);
  xv.resize(nb_faces_tot, dim);
// Copie le descripteur parallele du tableau sommet:
  xv.set_md_vector(sommet.get_md_vector());
  if(nb_faces_tot!=0)
    {
      int nb_som_faces=sommet.dimension(1);
      double inv=1./nb_som_faces;
      int k, som;
      xv = 0;
      if(Objet_U::axi)
        {
          switch(type_face_)
            {
            case  Faces::segment_2D_axi :
              {
                for (int face=0; face<nb_faces_tot; face++)
                  {
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 0)+=coord(sommet(face ,som), 0);
                    double teta_0=coord(sommet(face ,0), 1);
                    double teta_1=coord(sommet(face ,1), 1);
                    double teta_min=dmin(teta_1, teta_0);
                    double teta_max=dmax(teta_1, teta_0);
                    double d_teta=teta_max-teta_min;
                    if( (teta_min==0.) && (d_teta>M_PI) )
                      {
                        teta_min+=2.*M_PI;
                      }
                    {
                      xv(face, 1)+=(teta_min+teta_max);
                    }
                  }
                break;
              }
            case Faces::quadrangle_3D_axi :
              {
                for (int face=0; face<nb_faces_tot; face++)
                  {
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 0)+=coord(sommet(face ,som), 0);
                    for(som=0; som < nb_som_faces; som++)
                      xv(face, 2)+=coord(sommet(face ,som), 2);
                    double teta_0=coord(sommet(face ,0), 1);
                    double teta_1=coord(sommet(face ,1), 1);
                    double teta_2=coord(sommet(face ,2), 1);
                    double teta_3=coord(sommet(face ,3), 1);
                    double teta_min=dmin(teta_1, teta_0);
                    teta_min=dmin(teta_min, teta_2);
                    teta_min=dmin(teta_min, teta_3);
                    double teta_max=dmax(teta_1, teta_0);
                    teta_max=dmax(teta_min, teta_2);
                    teta_max=dmax(teta_min, teta_3);
                    double d_teta=teta_max-teta_min;
                    if( (teta_min==0.) && (d_teta>M_PI) )
                      {
                        if(teta_0==0.) teta_0+=2.*M_PI;
                        if(teta_1==0.) teta_1+=2.*M_PI;
                        if(teta_2==0.) teta_2+=2.*M_PI;
                        if(teta_3==0.) teta_3+=2.*M_PI;
                      }
                    {
                      xv(face, 1)+=(teta_0+teta_1+teta_2+teta_3) ;
                    }
                  }
                break;
              }
            default:
              {
                Cerr << "Face type number " << (int)type_face_ << " not provided in Faces::calculer_centres_gravite" << finl;
                break;
              }
            }
          xv*=inv;
        }
      else
        {
          for (int face=0; face<nb_faces_tot; face++)
            {
              int nb_som=nb_som_faces;
              while (sommet(face,nb_som-1)==-1) nb_som--;
              inv=1./nb_som;
              for(k=0; k<dim; k++)
                for(som=0; som < nb_som; som++)
                  xv(face, k)+=coord(sommet(face ,som), k);
              for(k=0; k<dim; k++)
                xv(face, k)*=inv;
            }
        }
    }
}