TRUST: src/Kernel/Geometrie/Hexaedre_VEF.cpp File Reference
Hexaedre_VEF.cpp File Reference
#include <Hexaedre_VEF.h>
#include <Domaine.h>
Functions
static int entre_faces (const Zone &zone, const Domaine &dom, const ArrOfDouble &pos, int Asom0_, int Asom1_, int Asom2_, int Bsom0_, int Bsom1_, int Bsom2_)
teste si une position pos est un tetraedre de sommets som(i)
static int contient_Tetra (const Zone &zone, const Domaine &dom, const ArrOfDouble &pos, int som0_, int som1_, int som2_, int som3_, int aff)
teste si une position pos est un tetraedre de sommets som(i)
int reordonne (int i0, int i1, int i2, int i3, DoubleTab &coord, IntTab &elem, int &num_poly, int test, DoubleTab &v, ArrOfDouble &prod_, ArrOfDouble &prod_v, ArrOfDouble &dist, DoubleTab &prod_v2)
Reordonne.
Variables
const Type_info * Hexaedre_VEFbases [1] ={ &(Elem_geom_base ::info_obj)}
static int faces_sommets_hexa_vef [6][4]
Function Documentation
contient_Tetra()
static int contient_Tetra (const Zone & zone, const Domaine & dom, const ArrOfDouble & pos, int som0_, int som1_, int som2_, int som3_, int aff) static
teste si une position pos est un tetraedre de sommets som(i)
Returns
Nom&
Signification: toujours egal a "HEXA8"
Contraintes: reference constante
Definition at line 162 of file Hexaedre_VEF.cpp.
{
  double prod1,prod2;
  int som0, som1, som2, som3;
  som0 = som0_;
  som1 = som1_;
  som2 = som2_;
  som3 = som3_;
  double vec0[3], vec1[3], vec2[3];
  double vecx0[3], vecx1[3], vecx2[3];
  if (aff)
    {
      Cerr<<"Test contient_Tetra nodes="<<som0_<<" "<<som1_<<" "<<som2_<<" "<<som3_<<finl;
      Cerr<<"  position="<<pos[0]<<" "<<pos[1]<<" "<<pos[2]<<finl;
    }
  if( ( est_egal(dom.coord(som0,0),pos[0]) && est_egal(dom.coord(som0,1),pos[1]) && est_egal(dom.coord(som0,2),pos[2]) )
      || (est_egal(dom.coord(som1,0),pos[0]) && est_egal(dom.coord(som1,1),pos[1]) && est_egal(dom.coord(som1,2),pos[2]))
      || (est_egal(dom.coord(som2,0),pos[0]) && est_egal(dom.coord(som2,1),pos[1]) && est_egal(dom.coord(som2,2),pos[2]))
      || (est_egal(dom.coord(som3,0),pos[0]) && est_egal(dom.coord(som3,1),pos[1]) && est_egal(dom.coord(som3,2),pos[2])) )
    return 1;
  for (int j=0; j<4; j++)
    {
      switch(j)
        {
        case 0 :
          som0 = som0_;
          som1 = som1_;
          som2 = som2_;
          som3 = som3_;
          break;
        case 1 :
          som0 = som1_;
          som1 = som2_;
          som2 = som3_;
          som3 = som0_;
          break;
        case 2 :
          som0 = som2_;
          som1 = som3_;
          som2 = som0_;
          som3 = som1_;
          break;
        case 3 :
          som0 = som3_;
          som1 = som0_;
          som2 = som1_;
          som3 = som2_;
          break;
        }
// algo : les produits mixtes (som0, som1, som2,som3) et (pos, som1, som2,som3) doivent a voir le meme signe
// construction des vecteurs
      vec0[0] = dom.coord(som1,0) - dom.coord(som0,0);
      vec0[1] = dom.coord(som1,1) - dom.coord(som0,1);
      vec0[2] = dom.coord(som1,2) - dom.coord(som0,2);
      vec1[0] = dom.coord(som2,0) - dom.coord(som0,0);
      vec1[1] = dom.coord(som2,1) - dom.coord(som0,1);
      vec1[2] = dom.coord(som2,2) - dom.coord(som0,2);
      vec2[0] = dom.coord(som3,0) - dom.coord(som0,0);
      vec2[1] = dom.coord(som3,1) - dom.coord(som0,1);
      vec2[2] = dom.coord(som3,2) - dom.coord(som0,2);
      vecx0[0] = dom.coord(som1,0) - pos[0];
      vecx0[1] = dom.coord(som1,1) - pos[1];
      vecx0[2] = dom.coord(som1,2) - pos[2];
      vecx1[0] = dom.coord(som2,0) - pos[0];
      vecx1[1] = dom.coord(som2,1) - pos[1];
      vecx1[2] = dom.coord(som2,2) - pos[2];
      vecx2[0] = dom.coord(som3,0) - pos[0];
      vecx2[1] = dom.coord(som3,1) - pos[1];
      vecx2[2] = dom.coord(som3,2) - pos[2];
      prod1 = vec0[0]*vec1[1]*vec2[2] + vec0[1]*vec1[2]*vec2[0] + vec0[2]*vec1[0]*vec2[1]
              - vec0[0]*vec1[2]*vec2[1] - vec0[1]*vec1[0]*vec2[2] - vec0[2]*vec1[1]*vec2[0];
      prod2 = vecx0[0]*vecx1[1]*vecx2[2] + vecx0[1]*vecx1[2]*vecx2[0] + vecx0[2]*vecx1[0]*vecx2[1]
              - vecx0[0]*vecx1[2]*vecx2[1] - vecx0[1]*vecx1[0]*vecx2[2] - vecx0[2]*vecx1[1]*vecx2[0];
      if (aff)
        {
          Cerr<<"  test "<<som0<<" "<<som1<<" "<<som2<<" "<<som3<<finl;
          Cerr<<"  node0="<<som0<<" : "<<dom.coord(som0,0)<<"  "<<dom.coord(som0,1)<<"  "<<dom.coord(som0,2)<<finl;
          Cerr<<"  node1="<<som1<<" : "<<dom.coord(som1,0)<<"  "<<dom.coord(som1,1)<<"  "<<dom.coord(som1,2)<<finl;
          Cerr<<"  node2="<<som2<<" : "<<dom.coord(som2,0)<<"  "<<dom.coord(som2,1)<<"  "<<dom.coord(som2,2)<<finl;
          Cerr<<"  node3="<<som3<<" : "<<dom.coord(som3,0)<<"  "<<dom.coord(som3,1)<<"  "<<dom.coord(som3,2)<<finl;
          Cerr<<"  position : "<<pos[0]<<"  "<<pos[1]<<"  "<<pos[2]<<finl;
          Cerr<<"      prod1="<<prod1<<" prod2="<<prod2<<finl;
        }
      if (std::fabs(prod1)<Objet_U::precision_geom)
        {
          double norm_v0=0,norm_v1=0,norm_v2=0;
          for (int ii=0; ii<3; ii++)
            {
              norm_v0+=vec0[ii]*vec0[ii];
              norm_v1+=vec1[ii]*vec1[ii];
              norm_v2+=vec2[ii]*vec2[ii];
            }
          if (std::fabs(prod1)<Objet_U::precision_geom*sqrt(norm_v0*norm_v1*norm_v2))
            {
              Cerr<<"Test contient_Tetra ERROR : coplanar nodes"<<finl;
              Cerr<<"  node0="<<som0<<" : "<<dom.coord(som0,0)<<"  "<<dom.coord(som0,1)<<"  "<<dom.coord(som0,2)<<finl;
              Cerr<<"  node1="<<som1<<" : "<<dom.coord(som1,0)<<"  "<<dom.coord(som1,1)<<"  "<<dom.coord(som1,2)<<finl;
              Cerr<<"  node2="<<som2<<" : "<<dom.coord(som2,0)<<"  "<<dom.coord(som2,1)<<"  "<<dom.coord(som2,2)<<finl;
              Cerr<<"  node3="<<som3<<" : "<<dom.coord(som3,0)<<"  "<<dom.coord(som3,1)<<"  "<<dom.coord(som3,2)<<finl;
              Cerr<<"  position : "<<pos[0]<<"  "<<pos[1]<<"  "<<pos[2]<<finl;
              Process::exit();
            }
        }
      if (prod1*prod2<0 && std::fabs(prod2)>std::fabs(prod1)*Objet_U::precision_geom)
        {
          if (aff)
            {
              Cerr<<"  CONTAINS=0"<<finl;
            }
          return 0;
        }
    }
  if (aff)
    {
      Cerr<<"  CONTAINS=1"<<finl;
    }
  return 1;
}
References Cerr, Domaine::coord(), est_egal(), Process::exit(), finl, and Objet_U::precision_geom.
Referenced by Hexaedre_VEF::contient().
entre_faces()
static int entre_faces (const Zone & zone, const Domaine & dom, const ArrOfDouble & pos, int Asom0_, int Asom1_, int Asom2_, int Bsom0_, int Bsom1_, int Bsom2_) static
teste si une position pos est un tetraedre de sommets som(i)
Returns
Nom&
Signification: toujours egal a "HEXA8"
Contraintes: reference constante
Definition at line 98 of file Hexaedre_VEF.cpp.
{
  double prodA,prodB;
  const DoubleTab& coord=dom.les_sommets();
// pour A
  double vecA1[3], vecA2[3], AP[3];
  double normaleA[3];
  for (int i=0; i<3; i++)
    {
      double ref=coord(Asom0_,i);
      vecA1[i]=coord(Asom1_,i)-ref;
      vecA2[i]=coord(Asom2_,i)-ref;
      AP[i]=pos[i]-ref;
    }
  normaleA[0]=(vecA1[1]*vecA2[2]-vecA1[2]*vecA2[1]);
  normaleA[1]=(vecA1[2]*vecA2[0]-vecA1[0]*vecA2[2]);
  normaleA[2]=(vecA1[0]*vecA2[1]-vecA1[1]*vecA2[0]);
  prodA=0;
  for (int i=0; i<3; i++)
    prodA+=normaleA[i]*AP[i];
// pour B
  double vecB1[3], vecB2[3], BP[3];
  double normaleB[3];
  for (int i=0; i<3; i++)
    {
      double ref=coord(Bsom0_,i);
      vecB1[i]=coord(Bsom1_,i)-ref;
      vecB2[i]=coord(Bsom2_,i)-ref;
      BP[i]=pos[i]-ref;
    }
  normaleB[0]=(vecB1[1]*vecB2[2]-vecB1[2]*vecB2[1]);
  normaleB[1]=(vecB1[2]*vecB2[0]-vecB1[0]*vecB2[2]);
  normaleB[2]=(vecB1[0]*vecB2[1]-vecB1[1]*vecB2[0]);
  prodB=0;
  for (int i=0; i<3; i++)
    prodB+=normaleB[i]*BP[i];
  if (prodA*prodB<=0)
    return 1;
  else
    {
// on regarde si on n'est pas limite
      double rap=prodA/prodB;
      if (rap>1) rap=prodB/prodA;
      if (rap< Objet_U::precision_geom) return 1;
    }
  return 0;
}
References Domaine::les_sommets(), and Objet_U::precision_geom.
Referenced by Hexaedre_VEF::contient().
reordonne()
int reordonne (int i0, int i1, int i2, int i3, DoubleTab & coord, IntTab & elem, int & num_poly, int test, DoubleTab & v, ArrOfDouble & prod_, ArrOfDouble & prod_v, ArrOfDouble & dist, DoubleTab & prod_v2) inline
Reordonne.
Definition at line 577 of file Hexaedre_VEF.cpp.
{
  int s[4];
  s[0]=elem(num_poly,i0);
  s[1]=elem(num_poly,i1);
  s[2]=elem(num_poly,i2);
  s[3]=elem(num_poly,i3);
// DoubleTab v(3,3);
  for (int i=1; i<4; i++)
    for (int dir=0; dir<3; dir++)
      v(i-1,dir)=coord(s[i],dir)-coord(s[0],dir);
// ArrOfDouble prod_(3);
  int opp=-1;
// avant tout on teste si on a bien un plan
  {
// ArrOfDouble prod_v(3);
    int op=0,i=1;
// prod_v=O1^O2
    prod_v[0]=v(op,1)*v(i,2)-v(op,2)*v(i,1);
    prod_v[1]=v(op,2)*v(i,0)-v(op,0)*v(i,2);
    prod_v[2]=v(op,0)*v(i,1)-v(op,1)*v(i,0);
// ArrOfDouble dist(8);
    dist=0;
    for (int j=0; j<8; j++)
      {
        for (int dir=0; dir<3; dir++)
          dist[j]+=prod_v[dir]*(coord(elem(num_poly,j),dir)-coord(s[0],dir));
      }
// Cerr<<"ici "<<i0 <<" i1 " <<i1<<" i2 "<<i2 << " i3 "<<i3 <<" "<<dist<<finl;
// sommet le plus proche du plan
    int s_plan=0;
    double min_dist=1e25;
    for (int j=0; j<8; j++)
      {
        if ((j!=i0)&&(j!=i1)&&(j!=i2))
          if (std::fabs(dist[j])<min_dist)
            {
              s_plan=j;
              min_dist=std::fabs(dist[j]);
            }
      }
    if (s_plan!=i3)
      {
// pas un plan
        if (test)
          {
// Cerr<<"ici pb"<<finl;
            return 1;
          }
        else
          {
            Cerr<<"we do not have a plan "<<finl;
            Process::exit();
          }
      }
// doit on tester  si les 4 autres points sont du meme cote ???
  }
  for (int op=0; op<3; op++)
    {
// DoubleTab prod_v2(3,3);
      for (int i=0; i<3; i++)
        {
          prod_v2(i,0)=v(op,1)*v(i,2)-v(op,2)*v(i,1);
          prod_v2(i,1)=v(op,2)*v(i,0)-v(op,0)*v(i,2);
          prod_v2(i,2)=v(op,0)*v(i,1)-v(op,1)*v(i,0);
        }
      double prod=0;
      int i1bis=-1,j2bis=-1;
      if (op==0)
        {
          i1bis=1;
          j2bis=2;
        }
      else if (op==1)
        {
          i1bis=0;
          j2bis=2;
        }
      else if (op==2)
        {
          i1bis=0;
          j2bis=1;
        }
      for (int dir=0; dir<3; dir++)
        prod+=(prod_v2(i1bis,dir)*prod_v2(j2bis,dir));
      prod_[op]=prod;
      if (prod<0)
        {
          if (opp!=-1)
            {
              op=3;
              if (test) return 1;
// on a deux produits negatifs on ne fait rien
            }
          opp=op;
        }
    }
  if ((test==0)&& ((opp==3)||(opp==-1)))
    {
      Cerr<<" this does not seem to be a plan "<<finl;
      Process::exit();
    }
  if ((opp!=2)&&(opp!=-2))
    {
      int i2b=i2;
      if (opp==0) i2b=i1;
      if (test==0)
        {
          int tmp=elem(num_poly,i2b);
          elem(num_poly,i2b)=elem(num_poly,i3);
          elem(num_poly,i3)=tmp;
          Cerr << "Permutation of local nodes "<<i2b<<" and "<<i3<<" on the element " <<num_poly<<" prod "<<prod_<<finl;
        }
      return 1;
    }
  return 0;
}
References Cerr, Process::exit(), finl, prod(), and test().
Referenced by Hexaedre_VEF::reordonner().
Variable Documentation
faces_sommets_hexa_vef
int faces_sommets_hexa_vef[6][4] static
Initial value:
=
{
  { 0, 2, 4, 6 },
  { 0, 1, 4, 5 },
  { 0, 1, 2, 3 },
  { 1, 3, 5, 7 },
  { 2, 3, 6, 7 },
  { 4, 5, 6, 7 }
}
Definition at line 834 of file Hexaedre_VEF.cpp.
Referenced by Hexaedre_VEF::get_tab_faces_sommets_locaux().
Hexaedre_VEFbases
const Type_info* Hexaedre_VEFbases[1] ={ &(Elem_geom_base ::info_obj)}
Definition at line 19 of file Hexaedre_VEF.cpp.