TRUST: src/Kernel/Math/SolvSys/ILU.cpp File Reference
ILU.cpp File Reference
#include <ILU.h>
#include <Matrice_Bloc.h>
#include <Matrice_Morse_Sym.h>
#include <SPV2.h>
#include <Param.h>
Functions
void MorseSymToMorse (const Matrice_Morse_Sym &MS, Matrice_Morse &M)
Variables
const Type_info * ILUbases [1] ={ &(Precond_base ::info_obj)}
Function Documentation
MorseSymToMorse()
void MorseSymToMorse (const Matrice_Morse_Sym & MS, Matrice_Morse & M)
Definition at line 49 of file ILU.cpp.
{
  M = MS;
  Matrice_Morse mattmp(MS);
  int i, ordre;
  ordre = M.ordre();
  M.transpose(mattmp);
  for (i = 0; i < ordre; i++)
    M(i, i) = 0.;
  M = mattmp + M;
}
References Matrice_Morse::ordre(), and Matrice_Morse::transpose().
Referenced by ILU::prepare_(), and Solv_Petsc::resoudre_systeme().
Variable Documentation
ILUbases
const Type_info* ILUbases[1] ={ &(Precond_base ::info_obj)}
Definition at line 22 of file ILU.cpp.