TRUST: src/Kernel/MEDimpl/Integrer_champ_med.cpp File Reference
Integrer_champ_med.cpp File Reference
#include <Integrer_champ_med.h>
#include <Param.h>
#include <Champ_Fonc_MED.h>
#include <SFichier.h>
Functions
void calcul_normal_norme (const ArrOfDouble &org, const ArrOfDouble &point1, const ArrOfDouble &point2, ArrOfDouble &normal)
double calcul_surface_triangle (const ArrOfDouble &origine, const ArrOfDouble &point1, const ArrOfDouble &point2)
double portion_surface_elem (const ArrOfDouble &pointA, const ArrOfDouble &pointB, const ArrOfDouble &pointC, const double z)
double portion_surface (const ArrOfDouble &point0, const ArrOfDouble &point1, const ArrOfDouble &point2, const double zmin, const double zmax)
static True_int fonction_tri_data (const void *ptr1, const void *ptr2)
Variables
const Type_info * Integrer_champ_medbases [1] ={ &(Interprete ::info_obj)}
Function Documentation
calcul_normal_norme()
void calcul_normal_norme (const ArrOfDouble & org, const ArrOfDouble & point1, const ArrOfDouble & point2, ArrOfDouble & normal)
Definition at line 76 of file Extraire_plan.cpp.
{
  calcul_normal(org, point1,  point2,normal);
  normal/=norme_array(normal);
}
References calcul_normal(), and norme_array().
Referenced by Integrer_champ_med::interpreter(), and Extraire_plan::interpreter_().
calcul_surface_triangle()
double calcul_surface_triangle (const ArrOfDouble & origine, const ArrOfDouble & point1, const ArrOfDouble & point2)
Definition at line 62 of file Integrer_champ_med.cpp.
{
  double normal0=(point1[1]-origine[1])*(point2[2]-origine[2])-((point2[1]-origine[1])*(point1[2]-origine[2]));
  double normal1=(point1[2]-origine[2])*(point2[0]-origine[0])-((point2[2]-origine[2])*(point1[0]-origine[0]));
  double normal2=(point1[0]-origine[0])*(point2[1]-origine[1])-((point2[0]-origine[0])*(point1[1]-origine[1]));
  double res=normal0*normal0+ normal1*normal1 + normal2*normal2 ;
  return sqrt(res)/2.;
}
Referenced by portion_surface_elem().
fonction_tri_data()
static True_int fonction_tri_data (const void * ptr1, const void * ptr2) static
Definition at line 115 of file Integrer_champ_med.cpp.
{
  const double * tab1 = (const double *) ptr1;
  const double * tab2 = (const double *) ptr2;
  double delta=(tab1[0] - tab2[0]);
  if (delta>0)
    return 1;
  else if (delta<0)
    return -1;
  return 0;
}
Referenced by Integrer_champ_med::interpreter().
portion_surface()
double portion_surface (const ArrOfDouble & point0, const ArrOfDouble & point1, const ArrOfDouble & point2, const double zmin, const double zmax)
Definition at line 106 of file Integrer_champ_med.cpp.
{
  return portion_surface_elem(point0,point1,point2,zmax)- portion_surface_elem(point0,point1,point2,zmin);
}
References portion_surface_elem().
Referenced by Integrer_champ_med::interpreter().
portion_surface_elem()
double portion_surface_elem (const ArrOfDouble & pointA, const ArrOfDouble & pointB, const ArrOfDouble & pointC, const double z)
Definition at line 73 of file Integrer_champ_med.cpp.
{
  if (z<=pointA[2]) return 0;
  if (z>pointC[2]) return calcul_surface_triangle(pointA,pointB,pointC);
  ArrOfDouble pointD(3);
// le point D est sur AC a hauteur de B.
  pointD[2]=pointB[2];
  double lambda=(pointB[2]-pointA[2])/(pointC[2]-pointA[2]);
  for (int i=0; i<2; i++)
    pointD[i]=pointA[i]+lambda*(pointC[i]-pointA[i]);
  if (z<=pointB[2])
    {
// on calcul la surface du triangle inferieur
// et on prend la proportion...
      double surf_inf=calcul_surface_triangle(pointA,pointB,pointD);
      double rap=1;
      if (pointB[2]!=pointA[2])
        rap=(z-pointA[2])/(pointB[2]-pointA[2]);
      return surf_inf*rap*rap;
    }
  else
    {
// on calcul la surface du triangle inferieur
// et on prend la proportion...
// et on retire a la surface totale
      double surf_sup=calcul_surface_triangle(pointB,pointD,pointC);
      double rap=(z-pointC[2])/(pointB[2]-pointC[2]);
      double surf_tot=calcul_surface_triangle(pointA,pointB,pointC);
      return surf_tot-surf_sup*rap*rap;
    }
}
References calcul_surface_triangle().
Referenced by portion_surface().
Variable Documentation
Integrer_champ_medbases
const Type_info* Integrer_champ_medbases[1] ={ &(Interprete ::info_obj)}
Definition at line 21 of file Integrer_champ_med.cpp.