TRUST: src/Kernel/Math/IntVect.cpp File Reference
src/Kernel/Math/IntVect.cpp File Reference
#include <IntVect.h>
#include <MD_Vector_base.h>
#include <MD_Vector_tools.h>
#include <limits.h>
#include <communications.h>
#include <DescStructure.h>
Functions
int operator== (const IntVect &x, const IntVect &y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfInt<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
int operator!= (const IntVect &x, const IntVect &y)
static void invalidate_data (IntVect &resu, Mp_vect_options opt)
int local_prodscal (const IntVect &vx, const IntVect &vy)
Renvoie la somme des x[i]*y[i] pour les items sequentiels sur ce processeur.
(tous les items si pas de structure parallele, sinon voir MD_Vector_base::get_items_to_sum()
int local_carre_norme_vect (const IntVect &vx)
int mp_carre_norme_vect (const IntVect &vx)
int local_somme_vect (const IntVect &vx)
int mp_somme_vect (const IntVect &vx)
int local_imin_vect (const IntVect &vx, Mp_vect_options opt)
int local_min_vect (const IntVect &vx, Mp_vect_options opt)
int local_imax_vect (const IntVect &vx, Mp_vect_options opt)
int local_max_vect (const IntVect &vx, Mp_vect_options opt)
int local_max_abs_vect (const IntVect &vx, Mp_vect_options opt)
int local_min_abs_vect (const IntVect &vx, Mp_vect_options opt)
void operator_abs (IntVect &resu, Mp_vect_options opt)
void operator_add (IntVect &resu, const IntVect &vx, Mp_vect_options opt)
void operator_add (IntVect &resu, const int x, Mp_vect_options opt)
void operator_sub (IntVect &resu, const IntVect &vx, Mp_vect_options opt)
void operator_sub (IntVect &resu, const int x, Mp_vect_options opt)
void operator_multiply (IntVect &resu, const IntVect &vx, Mp_vect_options opt)
void operator_multiply (IntVect &resu, const int x, Mp_vect_options opt)
void operator_negate (IntVect &resu, Mp_vect_options opt)
void operator_egal (IntVect &resu, int x, Mp_vect_options opt)
void operator_egal (IntVect &resu, const IntVect &vx, Mp_vect_options opt)
void operator_divide (IntVect &resu, const int x, Mp_vect_options opt)
int mp_max_vect (const IntVect &x, Mp_vect_options opt)
int mp_min_vect (const IntVect &x, Mp_vect_options opt)
int mp_max_abs_vect (const IntVect &x, Mp_vect_options opt)
int mp_min_abs_vect (const IntVect &x, Mp_vect_options opt)
int mp_prodscal (const IntVect &x, const IntVect &y)
Variables
const Type_info * IntVectbases [1] = { &(ArrOfInt ::info_obj)}
Function Documentation
static void invalidate_data (IntVect & resu, Mp_vect_options opt) [static]
< no invalid values
Definition at line 367 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_multiply(), operator_negate(), and operator_sub().
{
  const int invalid = INT_MAX;
  const MD_Vector& md = resu.get_md_vector();
  const int line_size = resu.line_size();
  if (opt == VECT_ALL_ITEMS || (!md.non_nul()))
    return; //!< no invalid values
  assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
  const ArrOfInt& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
  const int blocs_size = items_blocs.size_array();
  int i = 0;
  for (int blocs_idx = 0; blocs_idx < blocs_size; blocs_idx += 2)
    {
// process data until beginning of next bloc, or end of array
      const int bloc_end = line_size * items_blocs[blocs_idx];
      int *ptr = resu.addr() + i;
      for (; i < bloc_end; i++)
        *(ptr++) = invalid;
      i = items_blocs[blocs_idx+1] * line_size;
    }
// Process until end of vector
  const int bloc_end = resu.size_array();
  int *ptr = resu.addr() + i;
  for (; i < bloc_end; i++)
    *(ptr++) = invalid;
}
int local_carre_norme_vect (const IntVect & vx)
< this test is necessary if md is null
Definition at line 469 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int sum = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( VECT_SEQUENTIAL_ITEMS != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS ||  VECT_SEQUENTIAL_ITEMS == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  sum;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          sum += x * x;
          x_ptr++;
        }
    }
  return  sum;
}
int local_imax_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 704 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = INT_MIN;;
  int i_max = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_max;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          if (x > max_val) { i_max = x_ptr - x_base; max_val = x; }
          x_ptr++;
        }
    }
  return  i_max;
}
int local_imin_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 591 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
  int i_min = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_min;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          if (x < min_val) { i_min = x_ptr - x_base; min_val = x; }
          x_ptr++;
        }
    }
  return  i_min;
}
int local_max_abs_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 817 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int xx = abs(x);
          max_val = (xx > max_val) ? xx : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
int local_max_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 761 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = INT_MIN;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          max_val = (x > max_val) ? x : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
int local_min_abs_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 874 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int xx = abs(x);
          min_val = (xx < min_val) ? xx : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
int local_min_vect (const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 648 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          min_val = (x < min_val) ? x : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
int local_prodscal (const IntVect & vx, const IntVect & vy)
Renvoie la somme des x[i]*y[i] pour les items sequentiels sur ce processeur.
(tous les items si pas de structure parallele, sinon voir MD_Vector_base::get_items_to_sum()
< this test is necessary if md is null
< this test is necessary if md is null
Definition at line 407 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int sum = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
  assert(vy.line_size() == line_size);
  assert(vy.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vy.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( VECT_SEQUENTIAL_ITEMS != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS ||  VECT_SEQUENTIAL_ITEMS == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  sum;
    }
  const int *x_base = vx.addr();
  const int *y_base = vy.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      const int* y_ptr = y_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          const int y = *(y_ptr++);
          sum += x * y;
          x_ptr++;
        }
    }
  return  sum;
}
int local_somme_vect (const IntVect & vx)
< this test is necessary if md is null
Definition at line 529 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int sum = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( VECT_SEQUENTIAL_ITEMS != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS ||  VECT_SEQUENTIAL_ITEMS == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( VECT_SEQUENTIAL_ITEMS == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  sum;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          sum += x;
          x_ptr++;
        }
    }
  return  sum;
}
int mp_carre_norme_vect (const IntVect & vx)
Definition at line 525 of file IntVect.cpp.
References local_carre_norme_vect(), and Process::mp_sum().
{
  return Process::mp_sum(local_carre_norme_vect(vx));
}
int mp_max_abs_vect (const IntVect & x, Mp_vect_options opt)
Definition at line 1645 of file IntVect.cpp.
References local_max_abs_vect(), and mp_max().
{
  int s = local_max_abs_vect(x, opt);
  s = mp_max(s);
  return s;
}
int mp_max_vect (const IntVect & x, Mp_vect_options opt)
Definition at line 1633 of file IntVect.cpp.
References local_max_vect(), and mp_max().
{
  int s = local_max_vect(x, opt);
  s =  mp_max(s);
  return s;
}
int mp_min_abs_vect (const IntVect & x, Mp_vect_options opt)
Definition at line 1651 of file IntVect.cpp.
References local_min_abs_vect(), and mp_min().
{
  int s = local_min_abs_vect(x, opt);
  s = mp_min(s);
  return s;
}
int mp_min_vect (const IntVect & x, Mp_vect_options opt)
Definition at line 1639 of file IntVect.cpp.
References local_min_vect(), and mp_min().
{
  int s = local_min_vect(x, opt);
  s =  mp_min(s);
  return s;
}
int mp_prodscal (const IntVect & x, const IntVect & y)
Definition at line 1657 of file IntVect.cpp.
References local_prodscal(), and Process::mp_sum().
{
  return Process::mp_sum(local_prodscal(x, y));
}
int mp_somme_vect (const IntVect & vx)
Definition at line 585 of file IntVect.cpp.
References local_somme_vect(), and Process::mp_sum().
{
  int x = local_somme_vect(vx);
  int y = Process::mp_sum(x);
  return y;
}
int operator!= (const IntVect & x, const IntVect & y)
Definition at line 359 of file IntVect.cpp.
{
  return !(x == y);
}
int operator== (const IntVect & x, const IntVect & y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfInt<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
Definition at line 350 of file IntVect.cpp.
References IntVect::get_md_vector().
{
  if (!(x.get_md_vector() == y.get_md_vector()))
    return 0;
  const ArrOfInt& ax = x;
  const ArrOfInt& ay = y;
  return ax == ay;
}
void operator_abs (IntVect & resu, Mp_vect_options opt)
Definition at line 931 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu = abs(p_resu);
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_add (IntVect & resu, const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 987 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu += x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_add (IntVect & resu, const int x, Mp_vect_options opt)
Definition at line 1050 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu += x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_divide (IntVect & resu, const int x, Mp_vect_options opt)
Definition at line 1519 of file IntVect.cpp.
References ArrOfInt::addr(), Cerr, Process::exit(), finl, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          if(x==0.) { Cerr << "Error: divide by 0 in operator_divide." << finl; Process::exit();};
          p_resu /= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (IntVect & resu, int x, Mp_vect_options opt)
Definition at line 1400 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu = x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (IntVect & resu, const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 1456 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu = x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (IntVect & resu, const int x, Mp_vect_options opt)
Definition at line 1288 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu *= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (IntVect & resu, const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 1225 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu *= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_negate (IntVect & resu, Mp_vect_options opt)
Definition at line 1344 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu = -p_resu;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (IntVect & resu, const int x, Mp_vect_options opt)
Definition at line 1169 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu -= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (IntVect & resu, const IntVect & vx, Mp_vect_options opt)
< this test is necessary if md is null
Definition at line 1106 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu -= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
Variable Documentation
const Type_info* IntVectbases[1] = { &(ArrOfInt ::info_obj)}
Definition at line 38 of file IntVect.cpp.