TRUST: src/Kernel/Math/IntVect.h File Reference
src/Kernel/Math/IntVect.h File Reference
#include <ArrOfInt.h>
#include <MD_Vector.h>
#include <Vect.h>
Classes
class IntVect
Functions
int operator== (const IntVect &x, const IntVect &y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfInt<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
int operator!= (const IntVect &x, const IntVect &y)
int local_imax_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int local_max_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int local_imin_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int local_min_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int mp_max_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int mp_min_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int mp_somme_vect (const IntVect &)
int local_max_abs_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int local_min_abs_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int mp_max_abs_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
int mp_min_abs_vect (const IntVect &, Mp_vect_options opt=VECT_REAL_ITEMS)
void operator_add (IntVect &resu, const IntVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_add (IntVect &resu, const int x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_sub (IntVect &resu, const IntVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_sub (IntVect &resu, const int x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_multiply (IntVect &resu, const IntVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_multiply (IntVect &resu, const int x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_negate (IntVect &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_egal (IntVect &resu, int x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_egal (IntVect &resu, const IntVect &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
Function Documentation
int local_imax_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 704 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = INT_MIN;;
  int i_max = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_max;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          if (x > max_val) { i_max = x_ptr - x_base; max_val = x; }
          x_ptr++;
        }
    }
  return  i_max;
}
int local_imin_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 591 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
  int i_min = -1;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  i_min;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          if (x < min_val) { i_min = x_ptr - x_base; min_val = x; }
          x_ptr++;
        }
    }
  return  i_min;
}
int local_max_abs_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 817 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = 0;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int xx = abs(x);
          max_val = (xx > max_val) ? xx : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
int local_max_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 761 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int max_val = INT_MIN;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  max_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          max_val = (x > max_val) ? x : max_val;
          x_ptr++;
        }
    }
  return  max_val;
}
int local_min_abs_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 874 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int xx = abs(x);
          min_val = (xx < min_val) ? xx : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
int local_min_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
< this test is necessary if md is null
Definition at line 648 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
  int min_val = INT_MAX;;
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = vx;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return  min_val;
    }
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          min_val = (x < min_val) ? x : min_val;
          x_ptr++;
        }
    }
  return  min_val;
}
int mp_max_abs_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 1645 of file IntVect.cpp.
References local_max_abs_vect(), and mp_max().
{
  int s = local_max_abs_vect(x, opt);
  s = mp_max(s);
  return s;
}
int mp_max_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 1633 of file IntVect.cpp.
References local_max_vect(), and mp_max().
{
  int s = local_max_vect(x, opt);
  s =  mp_max(s);
  return s;
}
int mp_min_abs_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 1651 of file IntVect.cpp.
References local_min_abs_vect(), and mp_min().
{
  int s = local_min_abs_vect(x, opt);
  s = mp_min(s);
  return s;
}
int mp_min_vect (const IntVect & , Mp_vect_options opt = VECT_REAL_ITEMS)
Definition at line 1639 of file IntVect.cpp.
References local_min_vect(), and mp_min().
{
  int s = local_min_vect(x, opt);
  s =  mp_min(s);
  return s;
}
int mp_somme_vect (const IntVect &)
Definition at line 585 of file IntVect.cpp.
References local_somme_vect(), and Process::mp_sum().
{
  int x = local_somme_vect(vx);
  int y = Process::mp_sum(x);
  return y;
}
int operator!= (const IntVect & x, const IntVect & y)
Definition at line 359 of file IntVect.cpp.
{
  return !(x == y);
}
int operator== (const IntVect & x, const IntVect & y)
renvoie 1 si meme strucuture parallele et egalite au sens ArrOfInt<br>(y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
Definition at line 350 of file IntVect.cpp.
References IntVect::get_md_vector().
{
  if (!(x.get_md_vector() == y.get_md_vector()))
    return 0;
  const ArrOfInt& ax = x;
  const ArrOfInt& ay = y;
  return ax == ay;
}
void operator_add (IntVect & resu, const int x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1050 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu += x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_add (IntVect & resu, const IntVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 987 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu += x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (IntVect & resu, int x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1400 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu = x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_egal (IntVect & resu, const IntVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1456 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu = x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (IntVect & resu, const IntVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1225 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu *= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_multiply (IntVect & resu, const int x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1288 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu *= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_negate (IntVect & resu, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1344 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu = -p_resu;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (IntVect & resu, const int x, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 1169 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          int& p_resu = *(resu_ptr++);
          p_resu -= x;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}
void operator_sub (IntVect & resu, const IntVect & vx, Mp_vect_options opt = VECT_ALL_ITEMS)
< this test is necessary if md is null
Definition at line 1106 of file IntVect.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), IntVect::get_md_vector(), invalidate_data(), IntVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), IntVect::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
{
// Master vect donne la structure de reference, les autres vecteurs
// doivent avoir la meme structure.
  const IntVect& master_vect = resu;
  int line_size = master_vect.line_size();
  const MD_Vector& md = master_vect.get_md_vector();
  const int vect_size_tot = master_vect.size_totale();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1;
  int one_bloc[2];
  const int *bloc_ptr;
  if ( opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert( opt == VECT_SEQUENTIAL_ITEMS ||  opt == VECT_REAL_ITEMS);
      const ArrOfInt& items_blocs = ( opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else
    {
// raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
      return ;
    }
  int *resu_base = resu.addr();
  const int *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size;
      const int end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      int* resu_ptr = resu_base + begin_bloc;
      const int* x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const int x = *x_ptr;
          int& p_resu = *(resu_ptr++);
          p_resu -= x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu,  opt);
#endif
  return ;
}