TRUST: src/Kernel/Utilitaires/Journal.h File Reference
Journal.h File Reference
Functions
void init_journal_file (int verbose_level, int journal_shared, const char *filename, int append)
Initialisation du journal
Parametre: verbose_level
Signification: les messages de niveau <= verbose_level seront affiches,
les autres seront mis a la poubelle.
Parametre: file_name
Signification: si pointeur nul, tout le monde ecrit dans cerr, sinon
c'est le nom du fichier (doit etre different sur chaque processeur)
Parametre: append
Signification: indique si on ouvre le fichier en mode append ou pas.
int get_journal_level ()
void change_journal_level (int new_level)
void end_journal (int verbose_level)
void set_Cerr_to_journal (int flag)
change la destination de Cerr et Cout
Si flag=0, c'est stderr et stdout, sinon, si le fichier
journal est ouvert, c'est le journal, sinon c'est
Sortie_Nulle
Function Documentation
change_journal_level()
void change_journal_level (int new_level)
Definition at line 519 of file Process.cpp.
{
  verbose_level_ = level;
}
References verbose_level_.
Referenced by Execute_parallel::interpreter().
end_journal()
void end_journal (int verbose_level)
Definition at line 434 of file Process.cpp.
{
// Attention: acrobatie pour que ca "plante proprement" si le destructeur
// ecrit dans le journal !
  if(journal_shared_)
    {
      FichierHDFPar fic_hdf;
      fic_hdf.create(journal_file_name_);
      fic_hdf.create_and_fill_dataset_MW("/log", journal_shared_stream_);
      fic_hdf.close();
    }
  else
    journal_file_.close();
  journal_file_open_ = 0;
}
References FichierHDF::close(), Sortie_Fichier_base::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), journal_file_, journal_file_name_, journal_file_open_, journal_shared_, and journal_shared_stream_.
Referenced by Process::exit(), init_journal_file(), and mon_main::~mon_main().
get_journal_level()
int get_journal_level ()
Definition at line 514 of file Process.cpp.
{
  return verbose_level_;
}
References verbose_level_.
Referenced by Execute_parallel::interpreter().
init_journal_file()
void init_journal_file (int verbose_level, int journal_shared, const char * filename, int append)
Initialisation du journal
Parametre: verbose_level
Signification: les messages de niveau <= verbose_level seront affiches,
les autres seront mis a la poubelle.
Parametre: file_name
Signification: si pointeur nul, tout le monde ecrit dans cerr, sinon
c'est le nom du fichier (doit etre different sur chaque processeur)
Parametre: append
Signification: indique si on ouvre le fichier en mode append ou pas.
Definition at line 395 of file Process.cpp.
{
  journal_shared_ = journal_shared;
  if( journal_shared_ )
    {
      if(journal_file_open_)
        end_journal(verbose_level);
    }
  else
    end_journal(verbose_level);
  if (verbose_level > 0)
    {
      if (file_name)
        {
          if(!journal_shared_)
            {
              IOS_OPEN_MODE mode = ios::out;
              if (append)
                mode = ios::app;
              if (!journal_file_.ouvrir(file_name, mode))
                {
                  Cerr << "Fatal error in init_journal_file: cannot open journal file" << finl;
                  Process::exit();
                }
            }
          else
            {
              if(append)
                Cerr << "Process.cpp::init_journal_file : append mode is not possible with HDF5!\n"
                     << "If " << file_name << " already exists, it will be overwritten" << finl;
            }
          journal_file_open_ = 1;
          journal_file_name_ = file_name;
        }
    }
  verbose_level_ = verbose_level;
}
References Cerr, end_journal(), Process::exit(), finl, IOS_OPEN_MODE, journal_file_, journal_file_name_, journal_file_open_, journal_shared_, Sortie_Fichier_base::ouvrir(), and verbose_level_.
Referenced by mon_main::dowork(), and mon_main::mon_main().
set_Cerr_to_journal()
void set_Cerr_to_journal (int flag)
change la destination de Cerr et Cout
Si flag=0, c'est stderr et stdout, sinon, si le fichier
journal est ouvert, c'est le journal, sinon c'est
Sortie_Nulle
Definition at line 509 of file Process.cpp.
{
  cerr_to_journal_ = flag;
}
References cerr_to_journal_.
Referenced by Execute_parallel::interpreter().