TRUST: src/Kernel/MEDimpl/LataToMED.cpp File Reference
src/Kernel/MEDimpl/LataToMED.cpp File Reference
#include <LataToMED.h>
#include <Domaine.h>
#include <EFichierBin.h>
#include <List_Nom.h>
#include <EChaine.h>
#include <Motcle.h>
#include <communications.h>
#include <PE_Groups.h>
#include <Lire_Fichier.h>
#include <SFichier.h>
#include <LataFilter.h>
#include <LmlReader.h>
#include <Format_Post.h>
#include <list>
Functions
void convert_domain_to_Domaine (const Domain &dom, Domaine &dom_trio)
Variables
const Type_info * LataToMEDbases [1] = { &(Interprete ::info_obj)}
const Type_info * latatootherbases [1] = { &(Interprete ::info_obj)}
Function Documentation
void convert_domain_to_Domaine (const Domain & dom, Domaine & dom_trio)
Definition at line 83 of file LataToMED.cpp.
References Domaine::add(), Zone::associer_domaine(), Joints::associer_zone(), Raccords::associer_zone(), Bords::associer_zone(), Elem_geom::associer_zone(), Domaine::deformable(), IntTab::dimension(), DoubleTab::dimension(), Zone::faces_bord(), Zone::faces_joint(), Zone::faces_raccord(), Zone::fixer_premieres_faces_frontiere(), Zone::les_elems(), Domaine::les_sommets(), Zone::nb_som_elem(), Zone::nommer(), IntTab::resize(), DoubleTab::resize(), DoubleVect::size(), Zone::type_elem(), type_elem(), Zone::typer(), and Domaine::zone().
Referenced by latatoother::interpreter().
{
// dom_trio.les_sommets()=geom.nodes_;
// mais geom.nodes est un FloatTab
  DoubleTab& som= dom_trio.les_sommets();
  int nx=1,ny=1,nz=1;
  if (dom.get_domain_type()==Domain::UNSTRUCTURED)
    {
      const DomainUnstructured& geom = dom.cast_DomainUnstructured();
      int dim1=geom.nodes_.dimension(0);
      int dim2=geom.nodes_.dimension(1);
      som.resize(dim1,dim2);
      for (int i1=0; i1<dim1; i1++)
        for (int i2=0; i2<dim2; i2++)
          som(i1,i2)=geom.nodes_(i1,i2);
    }
  else
    {
      assert(dom.get_domain_type()==Domain::IJK);
      const DomainIJK& geom = dom.cast_DomainIJK();
      const int dim = geom.coord_.size();
      nx=geom.coord_[0].size_array();
      ny=geom.coord_[1].size_array();
      nz=1;
      if (dim>2) nz=geom.coord_[2].size_array();
      som.resize(nx*ny*nz,dim);
      for (int i=0; i<nx; i++)
        for (int j=0; j<ny; j++)
          for (int k=0; k<nz; k++)
            {
              int nn=i*ny*nz+j*nz+k;
              som(nn,0)=geom.coord_[0][i];
              som(nn,1)=geom.coord_[1][j];
              if (dim>2)
                som(nn,2)=geom.coord_[2][k];
            }
    }
  Zone zone_bidon;
  dom_trio.add(zone_bidon);
  Zone& zone=dom_trio.zone(0);
  zone.nommer("PAS_NOMME");
  Nom type_elem=dom.lata_element_name(dom.elt_type_);
  if (type_elem=="PRISM6") type_elem="PRISME";
// zone.type_elem()=type_ele;
  zone.typer(type_elem);
  zone.type_elem().associer_zone(zone);
  zone.associer_domaine(dom_trio);
  if (dom.get_domain_type()==Domain::UNSTRUCTURED)
    {
      const DomainUnstructured& geom = dom.cast_DomainUnstructured();
      zone.les_elems()=geom.elements_;
    }
  else
    {
      zone.les_elems().resize((nx-1)*(ny-1)*(nz-1),zone.nb_som_elem());
      IntTab& elems=zone.les_elems();
      for (int i=0; i<nx-1; i++)
        for (int j=0; j<ny-1; j++)
          for (int k=0; k<nz-1; k++)
            {
              int nn=i*(ny-1)*(nz-1)+j*(nz-1)+k;
              nn=i+j*(nx-1)+k*((nx-1)*(ny-1));
              elems(nn,0)=i*ny*nz+j*nz+k;
              elems(nn,1)=(i+1)*ny*nz+j*nz+k;
              elems(nn,2)=(i)*ny*nz+(j+1)*nz+k;
              elems(nn,3)=(i+1)*ny*nz+(j+1)*nz+k;
              if (elems.dimension(1)>4)
                for (int ii=0; ii<4; ii++) elems(nn,4+ii)=elems(nn,ii)+1;
            }
// a coder
// Process::exit();
    }
  zone.faces_bord().associer_zone(zone);
  zone.faces_raccord().associer_zone(zone);
  zone.faces_joint().associer_zone(zone);
  zone.type_elem().associer_zone(zone);
  zone.fixer_premieres_faces_frontiere();
  if (dom.id_.timestep_!=0)
    dom_trio.deformable()=1;
}
Variable Documentation
const Type_info* LataToMEDbases[1] = { &(Interprete ::info_obj)}
Definition at line 40 of file LataToMED.cpp.
const Type_info* latatootherbases[1] = { &(Interprete ::info_obj)}
Definition at line 41 of file LataToMED.cpp.