TRUST: src/Kernel/MEDimpl/LireMED.h File Reference
LireMED.h File Reference
#include <Interprete_geometrique_base.h>
#include <TRUSTTabs_forward.h>
#include <med++.h>
Classes
class LireMED
Functions
void med_non_installe ()
void lire_nom_med (Nom &nom_champ, Entree &is)
void test_version (Nom &nom)
void dimensionne_char_ptr_taille (Char_ptr &nom, int taille_d_un_mot, int nb=1)
void traite_nom_fichier_med (Nom &nom_fic)
void medinfochamp_existe (const Nom &nom_fic, Noms &nomschamp, const Domaine &dom, ArrOfDouble &temps_sauv)
Function Documentation
dimensionne_char_ptr_taille()
void dimensionne_char_ptr_taille (Char_ptr & nom, int taille_d_un_mot, int nb = 1)
Definition at line 47 of file LireMED.cpp.
{
  nom.allocate(taille_d_un_mot*nb);
}
References Char_ptr::allocate().
lire_nom_med()
void lire_nom_med (Nom & nom_champ, Entree & is)
Referenced by Champ_Fonc_MED::readOn().
med_non_installe()
void med_non_installe () inline
Definition at line 52 of file LireMED.h.
{
  Cerr << "This version has not been built with MED library." << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
Referenced by Champ_Fonc_MED::creer(), EcrMED::ecrire_champ(), EcrMED::ecrire_domaine(), LireMED::interpreter_(), Champ_Fonc_MED::lire(), LireMED::lire_geom(), and Pb_MED::readOn().
medinfochamp_existe()
void medinfochamp_existe (const Nom & nom_fic, Noms & nomschamp, const Domaine & dom, ArrOfDouble & temps_sauv)
Referenced by Pb_MED::readOn().
test_version()
void test_version (Nom & nom)
traite_nom_fichier_med()
void traite_nom_fichier_med (Nom & nom_fic)
Referenced by Champ_Fonc_MED::readOn(), and Pb_MED::readOn().