TRUST: src/Kernel/Geometrie/Lire_Tgrid.cpp File Reference
Lire_Tgrid.cpp File Reference
#include <Lire_Tgrid.h>
#include <EFichier.h>
#include <Domaine.h>
#include <math.h>
#include <RefFrontiere.h>
#include <NettoieNoeuds.h>
#include <ctype.h>
Functions
void decompression (Nom &nom_fichier)
int chartoint (char c)
int htoi (const char *szChaine)
void va_a_la_parenthese_fermante (EFichier &fic)
void va_a_la_parenthese_ouvrante (EFichier &fic)
Variables
const Type_info * Lire_Tgridbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
chartoint()
int chartoint (char c)
Definition at line 78 of file Lire_Tgrid.cpp.
{
  if( (0>(c-'0')) || ((c-'0')>9) )
    return -1;
  else
    return (c-'0');
}
Referenced by htoi().
decompression()
void decompression (Nom & nom_fichier) inline
Definition at line 27 of file Lire_Tgrid.cpp.
{
  Nom tmp(nom_fichier);
  if (tmp.prefix(".gz")!=nom_fichier)
    {
      Cerr << "Unzipping file " << nom_fichier << " ..." << finl;
      Nom cmd="gunzip -c ";
      cmd+=nom_fichier+" > "+tmp;
      Cerr << (int)system(cmd) << finl;
      nom_fichier=tmp;
    }
}
References Cerr, finl, nom_fichier(), and Nom::prefix().
Referenced by Lire_Tgrid::interpreter_().
htoi()
int htoi (const char * szChaine)
< Caractere invalide en Hexa.
< Caractere non valide. lResult += iValue * pow(16, iLength - i - 1);
Definition at line 87 of file Lire_Tgrid.cpp.
{
  int lResult = 0;
  int iLength = 0;
// Pointeur null, on renvoi -1
  if (szChaine == NULL)
    return -1;
// On calcule la longueur de la chaine
  iLength = strlen(szChaine);
// On met la chaine en majuscule dans une nouvelle chaine (allouee par strdup)
  char * szHexaString = strdup(szChaine);
// Pour chaque caractere on calcule sa valeur
  for (int i = iLength - 1; i >= 0; i--)
    {
      char cCharacter = szHexaString[i];
      int iValue = 0;
// C'est un digit, on le convertit en entier
      if (isdigit(cCharacter))
        {
// iValue = atoi(&cCharacter);
// atoi a l'air mechamment bugge !
// Je code un chartoint correct !
          iValue = chartoint(cCharacter);
          if (iValue>9)
            {
              Cerr << "iValue is worth " << iValue << " ! " << finl;
              Process::exit();
            }
        }
// C'est un caractere, on lui associe une valeur entiere
      else if (isalpha(cCharacter))
        {
          switch(cCharacter)
            {
            case 'A' :
            case 'a' :
              iValue = 10;
              break;
            case 'B' :
            case 'b' :
              iValue = 11;
              break;
            case 'C' :
            case 'c' :
              iValue = 12;
              break;
            case 'D' :
            case 'd' :
              iValue = 13;
              break;
            case 'E' :
            case 'e' :
              iValue = 14;
              break;
            case 'F' :
            case 'f' :
              iValue = 15;
              break;
            default  :
              return -3;              //!< Caractere invalide en Hexa.
            }
        }
// Ce n'est ni un caractere ni un digit.
      else
        return -4;   //!< Caractere non valide. lResult += iValue * pow(16, iLength - i - 1);
//
      for (int puissance=0; puissance<iLength - i - 1; puissance++)
        iValue *= 16;
      lResult += iValue;
    }
// Liberation de la chaine allouee
  free (szHexaString);
// Cerr << lResult << finl;
  return lResult;
}
References Cerr, chartoint(), Process::exit(), and finl.
Referenced by Lire_Tgrid::interpreter_().
va_a_la_parenthese_fermante()
void va_a_la_parenthese_fermante (EFichier & fic) inline
Definition at line 164 of file Lire_Tgrid.cpp.
{
  int parenthese_ouverte=1;
  Nom lu;
  while ((parenthese_ouverte!=0)&&(fic.good()))
    {
      fic >> lu;
      const char* chaine = lu.getChar();
      Process::Journal()<<"|"<<chaine<<"|"<<finl;
      int iLength = strlen(chaine);
      for (int i=0; i<iLength; i++)
        {
          char c = chaine[i];
          switch(c)
            {
            case 40 :
              parenthese_ouverte++;
              break;
            case 41 :
              parenthese_ouverte--;
              break;
            }
        }
    }
  if (parenthese_ouverte!=0)
    {
      Cerr<< "Error in file"<<finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, Nom::getChar(), Entree_Fichier_base::good(), and Process::Journal().
Referenced by Lire_Tgrid::interpreter_().
va_a_la_parenthese_ouvrante()
void va_a_la_parenthese_ouvrante (EFichier & fic) inline
Definition at line 196 of file Lire_Tgrid.cpp.
{
  int ok=0;
  Nom lu;
  while (ok!=1)
    {
      fic >> lu;
      const char* chaine = lu.getChar();
      int iLength = strlen(chaine);
      for (int i=0; i<iLength; i++)
        {
          char c = chaine[i];
          switch(c)
            {
            case 40 :
              ok=1;
              break;
            }
        }
    }
}
References Nom::getChar().
Referenced by Lire_Tgrid::interpreter_().
Variable Documentation
Lire_Tgridbases
const Type_info* Lire_Tgridbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 39 of file Lire_Tgrid.cpp.