TRUST: src/Kernel/Framework/Loi_horaire.cpp File Reference
Loi_horaire.cpp File Reference
#include <Loi_horaire.h>
#include <Param.h>
#include <Ref_Loi_horaire.h>
#include <EChaine.h>
#include <Schema_Temps_base.h>
#include <Probleme_base.h>
#include <SFichier.h>
#include <sys/stat.h>
Functions
int operator== (const Ref_Loi_horaire &r1, const Ref_Loi_horaire &r2)
void check (const DoubleTab &mat)
void multiplie (const DoubleTab &matrice, ArrOfDouble &vecteur)
void inverse (const DoubleTab &mat, ArrOfDouble &x)
Variables
const Type_info * Loi_horairebases [1] ={ &(Objet_U ::info_obj)}
const Type_info * Ref_Loi_horairebases [1] ={ &(Ref_ ::info_obj)}
Function Documentation
check()
void check (const DoubleTab & mat) inline
Definition at line 110 of file Loi_horaire.cpp.
{
// Champ_Fonc_t DoubleTab(1,nb_comp)
  if (mat.dimension(0)!=1)
    {
      Cerr << "Problem in Loi_horaire::check" << finl;
      Cerr << "Format of the array of values of Champ_Fonc_t" << finl;
      Cerr << "Contact TRUST support." << finl;
      Process::exit();
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), and finl.
Referenced by Domaine::buildUFacesMesh(), inverse(), and multiplie().
inverse()
void inverse (const DoubleTab & mat, ArrOfDouble & x) inline
Definition at line 135 of file Loi_horaire.cpp.
{
  check(mat);
  int dimension = x.size_array();
  if (dimension==2)
    {
      const double a=mat(0,0);
      const double b=mat(0,1);
      const double c=mat(0,2);
      const double d=mat(0,3);
      double det=a*d-b*c;
      if (det==0)
        {
          Cerr << "Matrix of order 2 not invertible in Loi_horaire::inverse" << finl;
          Cerr << mat << finl;
          Process::exit();
        }
      double y0=(d*x[0]-b*x[1])/det;
      double y1=(-c*x[0]+a*x[1])/det;
      x[0]=y0;
      x[1]=y1;
    }
  else if (dimension==3)
    {
      const double a=mat(0,0);
      const double b=mat(0,1);
      const double c=mat(0,2);
      const double d=mat(0,3);
      const double e=mat(0,4);
      const double f=mat(0,5);
      const double g=mat(0,6);
      const double h=mat(0,7);
      const double i=mat(0,8);
      double det=a*(e*i-f*h)
                 -b*(d*i-f*g)
                 +c*(d*h-e*g);
      if (det==0)
        {
          Cerr << "Matrix of order 3 not invertible in Loi_horaire::inverse" << finl;
          Cerr << mat << finl;
          Process::exit();
        }
      double y0=((e*i-f*h)*x[0]
                 +(c*h-b*i)*x[1]
                 +(b*f-c*e)*x[2])/det;
      double y1=((f*g-d*i)*x[0]
                 +(a*i-c*g)*x[1]
                 +(c*d-a*f)*x[2])/det;
      double y2=((d*h-e*g)*x[0]
                 +(b*g-a*h)*x[1]
                 +(a*e-b*d)*x[2])/det;
      x[0]=y0;
      x[1]=y1;
      x[2]=y2;
    }
  else
    {
      Cerr << "Case not provided in Loi_horaire::inverse()" << finl;
      Process::exit();
    }
}
References Cerr, check(), Process::exit(), finl, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Matrix_tools::matdiag_mult_matmorse(), Matrix_tools::matmorse_mult_matdiag(), Matrix_tools::matmorse_mult_uniform_matdiag(), Loi_horaire::position(), Loi_horaire::tester(), Matrix_tools::uniform_matdiag_mult_matmorse(), and Loi_horaire::vitesse().
multiplie()
void multiplie (const DoubleTab & matrice, ArrOfDouble & vecteur) inline
Definition at line 123 of file Loi_horaire.cpp.
{
  check(matrice);
  ArrOfDouble x(vecteur);
  vecteur=0;
  int dimension = vecteur.size_array();
  for (int i=0; i<dimension; i++)
    for (int j=0; j<dimension; j++)
      vecteur[i] += matrice(0,i*dimension+j) * x[j];
}
References check(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Loi_horaire::position(), Loi_horaire::tester(), and Loi_horaire::vitesse().
operator==()
int operator== (const Ref_Loi_horaire & r1, const Ref_Loi_horaire & r2)
Definition at line 26 of file Loi_horaire.cpp.
Variable Documentation
Loi_horairebases
const Type_info* Loi_horairebases[1] ={ &(Objet_U ::info_obj)}
Definition at line 25 of file Loi_horaire.cpp.
Ref_Loi_horairebases
const Type_info* Ref_Loi_horairebases[1] ={ &(Ref_ ::info_obj)}
Definition at line 26 of file Loi_horaire.cpp.