TRUST: src/ThHyd/Multiphase/Milieu/Lois_sodium.h File Reference
src/ThHyd/Multiphase/Milieu/Lois_sodium.h File Reference
#include <cmath>
Defines
#define Tk ((T) + 273.15)
#define f1(Ts) (2.49121 + Ts * (-5.53796e-3 + Ts * (7.5465e-6 + Ts * (-4.20217e-9 + Ts * 8.59212e-13))))
#define Df1(Ts) (-5.53796e-3 + Ts * (2 * 7.5465e-6 + Ts * (-3 * 4.20217e-9 + Ts * 4 * 8.59212e-13)))
#define f2(dT) (1 + dT * (-5e-4 + dT * (6.25e-7 - dT * 4.1359e-25)))
#define Df2(dT) (-5e-4 + dT * (2 * 6.25e-7 - dT * 3 * 4.1359e-25))
#define CpVs(Ts) (-1223.89 + Ts * (14.1191 + Ts * (-1.62025e-2 + Ts * 5.76923e-6)))
#define DCpVs(Ts) (14.1191 + Ts * (- 2 * 1.62025e-2 + Ts * 3 * 5.76923e-6))
Functions
double IRhoL (double T)
double DTIRhoL (double T)
double RhoL (double T, double P)
double HL (double T, double P)
double DTHL (double T, double P)
double TLh (double h, double T0, double P)
double DTRhoL (double T, double P)
double DPRhoL (double T, double P)
double DPHL (double T, double P)
double EL (double T, double P)
double DTEL (double T, double P)
double DPEL (double T, double P)
double TLe (double e, double T0, double P)
double MuL (double T)
double LambdaL (double T)
double SigmaL (double T)
double NuL (double T, double P, double w, double Dh)
double Tsat_Na (double P)
double DTsat_Na (double P)
double Psat_Na (double T)
double DPsat_Na (double T)
double Hsat (double P)
double DHsat (double P)
double Lvap_Na (double P)
double DLvap_Na (double P)
double RhoV (double T, double P)
double DTRhoV (double T, double P)
double DPRhoV (double T, double P)
double IRhoV (double T, double P)
double DTIRhoV (double T, double P)
double DPIRhoV (double T, double P)
double HV (double T, double P)
double DTHV (double T, double P)
double DPHV (double T, double P)
double EV (double T, double P)
double DTEV (double T, double P)
double DPEV (double T, double P)
double LambdaV (double T)
double MuV (double T)
double NuV (double T, double P, double w, double Dh)
double Rho (double T, double x, double P)
Variables
const double Ksil = 1e-9
Define Documentation
#define CpVs (Ts) (-1223.89 + Ts * (14.1191 + Ts * (-1.62025e-2 + Ts * 5.76923e-6)))
Definition at line 222 of file Lois_sodium.h.
Referenced by DPHV(), DTHV(), and HV().
#define DCpVs (Ts) (14.1191 + Ts * (- 2 * 1.62025e-2 + Ts * 3 * 5.76923e-6))
Definition at line 223 of file Lois_sodium.h.
Referenced by DPHV().
#define Df1 (Ts) (-5.53796e-3 + Ts * (2 * 7.5465e-6 + Ts * (-3 * 4.20217e-9 + Ts * 4 * 8.59212e-13)))
Definition at line 184 of file Lois_sodium.h.
Referenced by DPRhoV().
#define Df2 (dT) (-5e-4 + dT * (2 * 6.25e-7 - dT * 3 * 4.1359e-25))
Definition at line 186 of file Lois_sodium.h.
Referenced by DPRhoV(), and DTRhoV().
#define f1 (Ts) (2.49121 + Ts * (-5.53796e-3 + Ts * (7.5465e-6 + Ts * (-4.20217e-9 + Ts * 8.59212e-13))))
Definition at line 183 of file Lois_sodium.h.
Referenced by Aretes::affecter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Champ_Face::calcul_duidxj(), Aretes::calculer_centre_de_gravite(), Prisme::calculer_volumes(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), DPRhoV(), DTRhoV(), Zone_CoviMAC::init_equiv(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), RhoV(), and Champ_Face_implementation::trace().
#define f2 (dT) (1 + dT * (-5e-4 + dT * (6.25e-7 - dT * 4.1359e-25)))
Definition at line 185 of file Lois_sodium.h.
Referenced by Aretes::affecter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Champ_Face::calcul_duidxj(), Prisme::calculer_volumes(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), DPRhoV(), DTRhoV(), Zone_CoviMAC::init_equiv(), Champ_front_contact_VEF::remplir_connect_bords(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), RhoV(), and Champ_Face_implementation::trace().
#define Tk ((T) + 273.15)
Definition at line 29 of file Lois_sodium.h.
Referenced by DPHL(), DPRhoV(), DPsat_Na(), DTHL(), DTIRhoL(), DTRhoV(), HL(), IRhoL(), LambdaL(), MuL(), MuV(), Psat_Na(), RhoV(), and SigmaL().
Function Documentation
double DHsat (double P) [inline]
Definition at line 164 of file Lois_sodium.h.
References DPHL(), DTHL(), DTsat_Na(), and Tsat_Na().
Referenced by Saturation_sodium::dP_Hls_(), and Saturation_sodium::dP_Hvs_().
{
  return DTsat_Na(P) * DTHL(Tsat_Na(P), P) + DPHL(Tsat_Na(P), P);
}
double DLvap_Na (double P) [inline]
Definition at line 176 of file Lois_sodium.h.
References DTsat_Na(), and Tsat_Na().
Referenced by Saturation_sodium::dP_Hvs_(), Saturation_sodium::dP_Lvap_(), and DPHV().
{
  double Tc = 2503.7, Tsk = Tsat_Na(P) + 273.15;
  return DTsat_Na(P) * (-3.9337e5 / Tc - 4.3986e6  * .29302 * pow( 1 - Tsk / Tc, .29302 - 1) / Tc);
}
double DPEL (double T, double P) [inline]
Definition at line 99 of file Lois_sodium.h.
References DPHL(), DPRhoL(), HL(), and RhoL().
{
  return DPHL(T, P) * RhoL(T, P) + HL(T, P) * DPRhoL(T, P);
}
double DPEV (double T, double P) [inline]
Definition at line 252 of file Lois_sodium.h.
References DPHV(), DPRhoV(), HV(), and RhoV().
{
  return DPRhoV(T, P) * HV(T, P) + RhoV(T, P) * DPHV(T, P);
}
double DPHL (double T, double P) [inline]
Definition at line 84 of file Lois_sodium.h.
References DTIRhoL(), IRhoL(), Ksil, and Tk.
Referenced by DHsat(), Fluide_sodium_liquide::dP_h_(), DPEL(), and DPHV().
{
  return (IRhoL(T) - Tk * DTIRhoL(T)) * exp(Ksil * (1e5 - P));
}
double DPHV (double T, double P) [inline]
Definition at line 235 of file Lois_sodium.h.
References CpVs, DCpVs, DLvap_Na(), DPHL(), DTHL(), DTsat_Na(), and Tsat_Na().
Referenced by Fluide_sodium_gaz::dP_h_(), and DPEV().
{
  double Ts = Tsat_Na(P), dT = T - Ts, Cp0 = 910, k = -4.6e-3;
  return DPHL(Ts, P) + DLvap_Na(P) + DTsat_Na(P) * (DTHL(Ts, P) - Cp0 - DCpVs(Ts) * (1 - exp(k * dT)) / k + (Cp0 - CpVs(Ts)) * exp(k * dT));
}
double DPIRhoV (double T, double P) [inline]
Definition at line 217 of file Lois_sodium.h.
References DPRhoV(), and RhoV().
{
  return -DPRhoV(T, P) / (RhoV(T, P) * RhoV(T, P));
}
double DPRhoL (double T, double P) [inline]
Definition at line 78 of file Lois_sodium.h.
References Ksil, and RhoL().
Referenced by Fluide_sodium_liquide::dP_rho_(), and DPEL().
{
  return Ksil * RhoL(T, P);
}
double DPRhoV (double T, double P) [inline]
Definition at line 198 of file Lois_sodium.h.
References Df1, Df2, DTsat_Na(), f1, f2, Tk, and Tsat_Na().
Referenced by Fluide_sodium_gaz::dP_rho_(), DPEV(), and DPIRhoV().
{
  double Tsk = Tsat_Na(P) + 273.15, dT = Tk - Tsk;
  return 2.7650313e-3 * (f1(Tsk) * f2(dT) + P * DTsat_Na(P) * (Df1(Tsk) * f2(dT) - f1(Tsk) * Df2(dT))) / Tk;
}
double DPsat_Na (double T) [inline]
Definition at line 153 of file Lois_sodium.h.
References Psat_Na(), and Tk.
Referenced by Saturation_sodium::dT_Psat_().
{
  double B = 11209, C = 5.249e5;
  return (B / (Tk * Tk) + 2 * C / (Tk * Tk * Tk)) * Psat_Na(T);
}
double DTEL (double T, double P) [inline]
Definition at line 95 of file Lois_sodium.h.
References DTHL(), DTRhoL(), HL(), and RhoL().
Referenced by TLe().
{
  return DTHL(T, P) * RhoL(T, P) + HL(T, P) * DTRhoL(T, P);
}
double DTEV (double T, double P) [inline]
Definition at line 248 of file Lois_sodium.h.
References DTHV(), DTRhoV(), HV(), and RhoV().
{
  return DTRhoV(T, P) * HV(T, P) + RhoV(T, P) * DTHV(T, P);
}
double DTHL (double T, double P) [inline]
Definition at line 58 of file Lois_sodium.h.
References Ksil, and Tk.
Referenced by Fluide_sodium_liquide::cp_(), DHsat(), DPHV(), Fluide_sodium_liquide::dT_h_(), DTEL(), NuL(), and TLh().
{
  return (-2992600 / (Tk*Tk) + 1658.2 + Tk * (-.42395 * 2 + Tk * 1.4847e-4 * 3))
         - Tk * (-3.340743e-11 * 2 + Tk * 6.680973e-14 * 6) * (1 - exp(Ksil*(1e5 - P))) / Ksil;
}
double DTHV (double T, double P) [inline]
Definition at line 230 of file Lois_sodium.h.
References CpVs, and Tsat_Na().
Referenced by Fluide_sodium_gaz::cp_(), Fluide_sodium_gaz::dT_h_(), DTEV(), and NuV().
{
  double Ts = Tsat_Na(P), dT = T - Ts, Cp0 = 910, k = -4.6e-3;
  return Cp0 - (Cp0 - CpVs(Ts)) * exp(k * dT);
}
double DTIRhoL (double T) [inline]
Definition at line 39 of file Lois_sodium.h.
References Tk.
Referenced by Fluide_sodium_liquide::beta_(), DPHL(), DTRhoL(), and HL().
{
  return (2.641186e-7 + Tk * (-3.340743e-11 * 2 + Tk * 6.680973e-14 * 3));
}
double DTIRhoV (double T, double P) [inline]
Definition at line 213 of file Lois_sodium.h.
References DTRhoV(), and RhoV().
Referenced by Fluide_sodium_gaz::beta_().
{
  return -DTRhoV(T, P) / (RhoV(T, P) * RhoV(T, P));
}
double DTRhoL (double T, double P) [inline]
Definition at line 74 of file Lois_sodium.h.
References DTIRhoL(), IRhoL(), and Ksil.
Referenced by Fluide_sodium_liquide::dT_rho_(), and DTEL().
{
  return - exp(Ksil * (P - 1e5)) * DTIRhoL(T) / (IRhoL(T) * IRhoL(T));
}
double DTRhoV (double T, double P) [inline]
Definition at line 193 of file Lois_sodium.h.
References Df2, f1, f2, Tk, and Tsat_Na().
Referenced by Fluide_sodium_gaz::dT_rho_(), DTEV(), and DTIRhoV().
{
  double Tsk = Tsat_Na(P) + 273.15, dT = Tk - Tsk;
  return P * 2.7650313e-3 * f1(Tsk) * (Df2(dT) - f2(dT) / Tk) / Tk;
}
double DTsat_Na (double P) [inline]
Definition at line 141 of file Lois_sodium.h.
References Tsat_Na().
Referenced by DHsat(), DLvap_Na(), Saturation_sodium::dP_Tsat_(), DPHV(), and DPRhoV().
{
  double A = 7.8130, B = 11209, C = 5.249e5, Tsk = Tsat_Na(P) + 273.15;
  return Tsk * Tsk / ( P * sqrt(B*B + 4 * A * C - 4 * C * log(P / 1e6)));
}
double EL (double T, double P) [inline]
Definition at line 90 of file Lois_sodium.h.
References HL(), and RhoL().
Referenced by TLe().
{
  return HL(T, P) * RhoL(T, P);
}
double EV (double T, double P) [inline]
Definition at line 243 of file Lois_sodium.h.
References HV(), and RhoV().
{
  return RhoV(T, P) * HV(T, P);
}
double HL (double T, double P) [inline]
Definition at line 51 of file Lois_sodium.h.
References DTIRhoL(), IRhoL(), Ksil, and Tk.
Referenced by DPEL(), DTEL(), EL(), Fluide_sodium_liquide::h_(), Hsat(), HV(), and TLh().
{
  return (2992600 / Tk - 365487.2 + Tk * (1658.2 + Tk * (-.42395 + Tk * 1.4847e-4)))
         + (IRhoL(T) - Tk * DTIRhoL(T)) * (1 - exp(Ksil*(1e5 - P))) / Ksil;
}
double Hsat (double P) [inline]
Definition at line 159 of file Lois_sodium.h.
References HL(), and Tsat_Na().
Referenced by Saturation_sodium::Hls_(), and Saturation_sodium::Hvs_().
{
  return HL(Tsat_Na(P), P);
}
double HV (double T, double P) [inline]
Definition at line 224 of file Lois_sodium.h.
References CpVs, HL(), Lvap_Na(), and Tsat_Na().
Referenced by DPEV(), DTEV(), EV(), and Fluide_sodium_gaz::h_().
{
  double Ts = Tsat_Na(P), dT = T - Ts, Cp0 = 910, k = -4.6e-3;
  return HL(Ts, P) + Lvap_Na(P) + Cp0 * dT + (Cp0 - CpVs(Ts)) * (1 - exp(k * dT)) / k;
}
double IRhoL (double T) [inline]
Definition at line 33 of file Lois_sodium.h.
References Tk.
Referenced by Fluide_sodium_liquide::beta_(), DPHL(), DTRhoL(), HL(), and RhoL().
{
  return (9.829728e-4 + Tk * (2.641186e-7 + Tk * (-3.340743e-11 + Tk * 6.680973e-14)));
}
double IRhoV (double T, double P) [inline]
Definition at line 208 of file Lois_sodium.h.
References RhoV().
Referenced by Fluide_sodium_gaz::beta_().
{
  return 1 / RhoV(T, P);
}
double LambdaL (double T) [inline]
Definition at line 119 of file Lois_sodium.h.
References max(), and Tk.
Referenced by Fluide_sodium_liquide::lambda_(), and NuL().
{
  return std::max(124.67 + Tk * (-.11381 + Tk * (5.5226e-5 - Tk * 1.1848e-8)), 0.045);
}
double LambdaV (double T) [inline]
Definition at line 258 of file Lois_sodium.h.
Referenced by Fluide_sodium_gaz::lambda_(), and NuV().
{
  return 0.045;
}
double Lvap_Na (double P) [inline]
Definition at line 169 of file Lois_sodium.h.
References Tsat_Na().
Referenced by HV(), Saturation_sodium::Hvs_(), and Saturation_sodium::Lvap_().
{
  double Tc = 2503.7, Tsk = Tsat_Na(P) + 273.15;
  return 3.9337e5 * ( 1 - Tsk / Tc) + 4.3986e6 * pow( 1 - Tsk / Tc, .29302);
}
double MuL (double T) [inline]
Definition at line 114 of file Lois_sodium.h.
References Tk.
Referenced by Fluide_sodium_liquide::mu_().
{
  return exp( -6.4406 - 0.3958 * log(Tk) + 556.835 / Tk );
}
double MuV (double T) [inline]
Definition at line 264 of file Lois_sodium.h.
References Tk.
Referenced by Fluide_sodium_gaz::mu_(), and NuV().
{
  return 2.5e-6 + 1.5e-8 * Tk;
}
double NuL (double T, double P, double w, double Dh) [inline]
Definition at line 129 of file Lois_sodium.h.
References DTHL(), LambdaL(), and RhoL().
{
  double Pe = RhoL(T, P) * std::abs(w) * Dh * DTHL(T, P) / LambdaL(T);
  return 4.82 + 0.0185 * pow(Pe, 0.827);
}
double NuV (double T, double P, double w, double Dh) [inline]
Definition at line 270 of file Lois_sodium.h.
References DTHV(), LambdaV(), MuV(), and RhoV().
{
  double Re = RhoV(T, P) * std::abs(w) * Dh / MuV(T), Pr = MuV(T) * DTHV(T, P) / LambdaV(T);
  return 0.023 * pow(Re, 0.8) * pow(Pr, 0.4);
}
double Psat_Na (double T) [inline]
Definition at line 147 of file Lois_sodium.h.
References Tk.
Referenced by DPsat_Na(), and Saturation_sodium::Psat_().
{
  double A = 7.8130, B = 11209, C = 5.249e5;
  return 1e6 * exp(A - B / Tk - C / (Tk * Tk));
}
double Rho (double T, double x, double P) [inline]
Definition at line 276 of file Lois_sodium.h.
References RhoL(), and RhoV().
{
  return 1 / ( (1-x)/RhoL(T, P) + x / RhoV(T, P) );
}
double RhoL (double T, double P) [inline]
Definition at line 45 of file Lois_sodium.h.
References IRhoL(), and Ksil.
Referenced by DPEL(), DPRhoL(), DTEL(), EL(), NuL(), Rho(), and Fluide_sodium_liquide::rho_().
{
  return exp(Ksil * (P - 1e5)) / IRhoL(T);
}
double RhoV (double T, double P) [inline]
Definition at line 187 of file Lois_sodium.h.
References f1, f2, Tk, and Tsat_Na().
Referenced by DPEV(), DPIRhoV(), DTEV(), DTIRhoV(), EV(), IRhoV(), NuV(), Rho(), and Fluide_sodium_gaz::rho_().
{
  double Tsk = Tsat_Na(P) + 273.15, dT = Tk - Tsk;
  return P * 2.7650313e-3 * f1(Tsk) * f2(dT) / Tk;
}
double SigmaL (double T) [inline]
Definition at line 124 of file Lois_sodium.h.
References Tk.
{
  return 0.2405 * pow(1 - Tk / 2503.7, 1.126);
}
double TLe (double e, double T0, double P) [inline]
Definition at line 104 of file Lois_sodium.h.
References DTEL(), and EL().
{
  double T = T0, sec;
  int i;
  for (i = 0; i < 100 && std::abs( sec = EL(T, P) - e ) > 1e-3; i++)
    T -= sec / DTEL(T, P);
  return i < 100 ? T : -1e10;
}
double TLh (double h, double T0, double P) [inline]
Definition at line 65 of file Lois_sodium.h.
References DTHL(), and HL().
{
  double T = T0, sec;
  int i;
  for (i = 0; i < 100 && std::abs( sec = HL(T, P) - h ) > 1e-8; i++)
    T -= sec / DTHL(T, P);
  return i < 100 ? T : -1e10;
}
double Tsat_Na (double P) [inline]
Definition at line 135 of file Lois_sodium.h.
Referenced by DHsat(), DLvap_Na(), DPHV(), DPRhoV(), DTHV(), DTRhoV(), DTsat_Na(), Hsat(), HV(), Lvap_Na(), RhoV(), and Saturation_sodium::Tsat_().
{
  double A = 7.8130, B = 11209, C = 5.249e5;
  return 2 * C / ( -B + sqrt(B*B + 4 * A * C - 4 * C * log(P / 1e6))) - 273.15;
}
Variable Documentation
const double Ksil = 1e-9
Definition at line 30 of file Lois_sodium.h.
Referenced by DPHL(), DPRhoL(), DTHL(), DTRhoL(), HL(), and RhoL().