TRUST: src/Kernel/Geometrie/MaillerParallel.cpp File Reference
MaillerParallel.cpp File Reference
#include <MaillerParallel.h>
#include <Domaine.h>
#include <Motcle.h>
#include <Scatter.h>
#include <Statistiques.h>
#include <Param.h>
#include <TRUSTArrays.h>
#include <Parser_U.h>
#include <Reordonner_faces_periodiques.h>
#include <EFichier.h>
#include <Schema_Comm.h>
#include <Octree_Double.h>
#include <Faces_builder.h>
#include <Connectivite_som_elem.h>
#include <Static_Int_Lists.h>
#include <communications.h>
#include <ArrOfBit.h>
#include <Array_tools.h>
#include <Ref_Joint.h>
Classes
struct BlocData
Functions
static int bbox_intersection (const DoubleTab &bboxes, int i, int j, double epsilon)
void find_matching_coordinates (const DoubleTab &coords, ArrsOfInt &match, double epsilon)
for a given set of local coordinates, finds which other processors
share the same nodes.
match must be sized to Process::nproc() and will be filled with, for each processor,
the indexes of coordinates that the corresponding processor shares with me.
Nodes are listed in the same order on couples of processors sharing a list of nodes
match[Process::me()] will be left empty.
static void find_joint_faces (const Zone &zone, IntTab &faces)
finds all faces of all elements that
- have only one neighbour elements
- and do not belong to a boundary<br>(these are joint faces)
Fills "faces" with the local node numbers of the faces that have been found.
static void auto_build_joints (Zone &zone, const int epaisseur_joint)
Variables
const Type_info * MaillerParallelbases [1] ={ &(Interprete ::info_obj)}
Function Documentation
auto_build_joints()
static void auto_build_joints (Zone & zone, const int epaisseur_joint) static
< copie du tableau
< init with 0.
Definition at line 413 of file MaillerParallel.cpp.
{
  const double epsilon = 1e-10;
  int i, j;
// Find joint faces (faces with 1 neighbour element not registered in boundary faces)
  IntTab faces;
  find_joint_faces(zone, faces);
  const DoubleTab& sommets = zone.domaine().les_sommets();
// List of unique local boundary node numbers
  const int dim = sommets.dimension(1);
  {
    ArrOfInt boundary_nodes_index;
    boundary_nodes_index = faces; //!< copie du tableau
    array_trier_retirer_doublons(boundary_nodes_index);
    const int ncoord = boundary_nodes_index.size_array();
// Fill nodes coordinates and bounding boxes
    DoubleTab coord;
    coord.resize(ncoord, dim, Array_base::NOCOPY_NOINIT);
    for (i = 0; i < ncoord; i++)
      {
        const int som = boundary_nodes_index[i];
        for (j = 0; j < dim; j++)
          coord(i, j) = sommets(som, j);
      }
    ArrsOfInt match(Process::nproc());
    find_matching_coordinates(coord, match, epsilon);
    for (int pe = 0; pe < match.size(); pe++)
      {
        const ArrOfInt& list = match[pe];
        const int n = list.size_array();
        if (n > 0)
          {
            Joint& joint = zone.faces_joint().add(Joint());
            joint.nommer("Joint_i");
            joint.associer_zone(zone);
            joint.affecte_epaisseur(epaisseur_joint);
            joint.affecte_PEvoisin(pe);
            joint.faces().typer(zone.type_elem().valeur().type_face());
            ArrOfInt& sommets_joint = joint.set_joint_item(Joint::SOMMET).set_items_communs();
            sommets_joint.resize_array(n, Array_base::NOCOPY_NOINIT);
            for (i = 0; i < n; i++)
              sommets_joint[i] = boundary_nodes_index[list[i]];
            sommets_joint.ordonne_array();
            Process::Journal() << "Joint sommets with pe " << pe << " has " << n << " nodes" << finl;
          }
      }
  }
  {
// Find matching faces (match the coordinates of the centers)
    const int nfaces = faces.dimension(0);
    const int nb_som_faces = faces.dimension(1);
    DoubleTab coord(nfaces, dim); //!< init with 0.
    const double facteur = 1. / (double)nb_som_faces;
    for (i = 0; i < nfaces; i++)
      {
        for (j = 0; j < nb_som_faces; j++)
          {
            const int som = faces(i,j);
            for (int k = 0; k < dim; k++)
              coord(i, k) += sommets(som, k) * facteur;
          }
      }
    ArrsOfInt match(Process::nproc());
    find_matching_coordinates(coord, match, epsilon);
    for (int pe = 0; pe < match.size(); pe++)
      {
        const ArrOfInt& list = match[pe];
        const int n = list.size_array();
        if (n > 0)
          {
            REF(Joint) ref_joint;
            int ii;
            for (ii = 0; ii < zone.faces_joint().size(); ii++)
              {
                Joint& joint = zone.faces_joint()[ii];
                if (joint.PEvoisin() == pe)
                  {
                    ref_joint = joint;
                    break;
                  }
              }
            if (!ref_joint.non_nul())
              {
                Joint& joint = zone.faces_joint().add(Joint());
                joint.nommer("Joint_i");
                joint.associer_zone(zone);
                joint.affecte_epaisseur(epaisseur_joint);
                joint.affecte_PEvoisin(pe);
                joint.faces().typer(zone.type_elem().valeur().type_face());
                ref_joint = joint;
              }
            Faces& les_faces = ref_joint.valeur().faces();
            les_faces.dimensionner(n);
            IntTab& faces_sommets = les_faces.les_sommets();
            for (ii = 0; ii < n; ii++)
              {
                const int num_face = list[ii];
                for (j = 0; j < nb_som_faces; j++)
                  faces_sommets(ii, j) = faces(num_face, j);
              }
            Process::Journal() << "Joint faces with pe " << pe << " has " << n << " faces" << finl;
          }
      }
  }
// Tri des joints dans l'ordre croissant des processeurs
  Scatter::trier_les_joints(zone.faces_joint());
}
References List_Joint::add(), Joint::affecte_epaisseur(), Joint::affecte_PEvoisin(), array_trier_retirer_doublons(), Frontiere::associer_zone(), TRUSTTab< _TYPE_ >::dimension(), Faces::dimensionner(), Zone::domaine(), Frontiere::faces(), Zone::faces_joint(), find_joint_faces(), find_matching_coordinates(), finl, Process::Journal(), Domaine::les_sommets(), Faces::les_sommets(), Array_base::NOCOPY_NOINIT, Frontiere::nommer(), Process::nproc(), TRUSTArray< _TYPE_ >::ordonne_array(), Joint::PEvoisin(), REF, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Joint_Items::set_items_communs(), Joint::set_joint_item(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), Joint::SOMMET, Scatter::trier_les_joints(), Zone::type_elem(), Elem_geom_base::type_face(), Faces::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by MaillerParallel::interpreter().
bbox_intersection()
static int bbox_intersection (const DoubleTab & bboxes, int i, int j, double epsilon) static
Definition at line 203 of file MaillerParallel.cpp.
{
  const int dim = bboxes.dimension(1) / 2;
  for (int k = 0; k < dim; k++)
    {
      double min1 = bboxes(i, k) - epsilon;
      double max1 = bboxes(i, dim+k) + epsilon;
      double min2 = bboxes(j, k);
      double max2 = bboxes(j, dim+k);
      if (min1 > max2 || max1 < min2)
        return 0;
    }
  return 1;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by find_matching_coordinates().
find_joint_faces()
static void find_joint_faces (const Zone & zone, IntTab & faces) static
finds all faces of all elements that
- have only one neighbour elements
- and do not belong to a boundary<br>(these are joint faces)
Fills "faces" with the local node numbers of the faces that have been found.
Definition at line 347 of file MaillerParallel.cpp.
{
  Static_Int_Lists som_elem;
  const IntTab& elements = zone.les_elems();
  const int nb_som = zone.domaine().nb_som();
  construire_connectivite_som_elem(nb_som, elements, som_elem, 0 /* do not include virtual elements */);
  const int nb_som_faces = zone.type_elem().valeur().nb_som_face();
  faces.resize(0, nb_som_faces);
  faces.set_smart_resize(1);
  IntTab faces_element_reference;
  zone.type_elem().valeur().get_tab_faces_sommets_locaux(faces_element_reference);
  const int nb_faces_elem = faces_element_reference.dimension(0);
// Mark faces of elements that are on a boundary
  const int nb_elem = elements.dimension(0);
  ArrOfBit boundary_faces(nb_elem * nb_faces_elem);
  boundary_faces = 0;
  ArrOfInt une_face(nb_som_faces);
  ArrOfInt liste_elements;
  liste_elements.set_smart_resize(1);
  const int nb_boundaries = zone.nb_front_Cl();
  for (int i_boundary = 0; i_boundary < nb_boundaries; i_boundary++)
    {
      const IntTab& faces_front = zone.frontiere(i_boundary).faces().les_sommets();
      const int nb_faces_bord = faces_front.dimension(0);
      for (int j = 0; j < nb_faces_bord; j++)
        {
          for (int k = 0; k < nb_som_faces; k++)
            une_face[k] = faces_front(j, k);
          find_adjacent_elements(som_elem, une_face, liste_elements);
          if (liste_elements.size_array() != 1)
            {
              Cerr << "Error in MaillerParallel::find_joint_faces: boundary face ArrOfInt=" << une_face
                   << " does not have exactly 1 neighbour element: " << liste_elements;
              Process::exit();
            }
          const int elem = liste_elements[0];
          const int face_locale = Faces_builder::chercher_face_element(elements, faces_element_reference, une_face, elem);
          boundary_faces.setbit(elem * nb_faces_elem + face_locale);
        }
    }
// Browse all faces of all elements, find faces with only one neighbour
  for (int elem = 0; elem < nb_elem; elem++)
    {
      for (int face_locale = 0; face_locale < nb_faces_elem; face_locale++)
        {
          if (boundary_faces[elem * nb_faces_elem + face_locale])
            continue;
          int i;
          for (i = 0; i < nb_som_faces; i++)
            {
              const int sommet_local = faces_element_reference(face_locale, i);
              une_face[i] = elements(elem, sommet_local);
            }
          find_adjacent_elements(som_elem, une_face, liste_elements);
          if (liste_elements.size_array() == 1)
            {
              const int n = faces.dimension(0);
              faces.resize_dim0(n+1);
              for (i = 0; i < nb_som_faces; i++)
                faces(n, i) = une_face[i];
            }
        }
    }
  Process::Journal() << "Domain " << zone.domaine().le_nom() << " has " << faces.dimension(0) << " undeclared boundary faces candidates for joint faces" << finl;
}
References Cerr, Faces_builder::chercher_face_element(), construire_connectivite_som_elem(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Process::exit(), Frontiere::faces(), find_adjacent_elements(), finl, Zone::frontiere(), Elem_geom_base::get_tab_faces_sommets_locaux(), Process::Journal(), Domaine::le_nom(), Zone::les_elems(), Faces::les_sommets(), Zone::nb_front_Cl(), Domaine::nb_som(), Elem_geom_base::nb_som_face(), TRUSTTab< _TYPE_ >::resize(), TRUSTTab< _TYPE_ >::resize_dim0(), TRUSTArray< _TYPE_ >::set_smart_resize(), ArrOfBit::setbit(), TRUSTArray< _TYPE_ >::size_array(), Zone::type_elem(), and Deriv_Elem_geom_base::valeur().
Referenced by auto_build_joints().
find_matching_coordinates()
void find_matching_coordinates (const DoubleTab & coords, ArrsOfInt & match, double epsilon)
for a given set of local coordinates, finds which other processors
share the same nodes.
match must be sized to Process::nproc() and will be filled with, for each processor,
the indexes of coordinates that the corresponding processor shares with me.
Nodes are listed in the same order on couples of processors sharing a list of nodes
match[Process::me()] will be left empty.
< processor number
< processor number
Definition at line 224 of file MaillerParallel.cpp.
{
  int i, j;
  const int dim = coords.dimension(1);
  const int ncoord = coords.dimension(0);
  const int nproc = Process::nproc();
  const int moi = Process::me();
// Fill nodes coordinates and bounding boxes
  DoubleTab bounding_boxes(nproc, dim*2);
  {
    const double big_val = 1.e36;
    ArrOfDouble min_coord(dim);
    min_coord= big_val;
    ArrOfDouble max_coord(dim);
    max_coord= -big_val;
    for (i = 0; i < ncoord; i++)
      {
        for (j = 0; j < dim; j++)
          {
            const double x = coords(i, j);
            if (x > max_coord[j])
              max_coord[j] = x;
            if (x < min_coord[j])
              min_coord[j] = x;
          }
      }
// broadcast a tous les processeurs
    for (i = 0; i < nproc; i++)
      {
        for (j = 0; j < dim; j++)
          {
            bounding_boxes(i, j) = min_coord[j];
            bounding_boxes(i, j+dim) = max_coord[j];
          }
      }
    envoyer_all_to_all(bounding_boxes, bounding_boxes);
  }
// Exchange boundary nodes coordinates with other processors
  ArrOfInt all_pe;
  all_pe.set_smart_resize(1);
  for (i = 0; i < nproc; i++)
    if (i != moi && bbox_intersection(bounding_boxes, moi, i, epsilon))
      all_pe.append_array(i);
  Schema_Comm schema;
  schema.set_send_recv_pe_list(all_pe, all_pe);
  schema.begin_comm();
  Octree_Double octree;
  octree.build_nodes(coords, 0 /* do not include virtual nodes */);
// Send nodes coordinates to processors with non empty intersection
// temporary array for octree functions:
  ArrOfInt nodes_list;
  nodes_list.set_smart_resize(1);
  int ipe;
  for (ipe = 0; ipe < all_pe.size_array(); ipe++)
    {
// Search nodes within the bounding box of the other processor:
      const int pe = all_pe[ipe]; //!< processor number
      const double xmin = bounding_boxes(pe, 0) - epsilon;
      const double ymin = bounding_boxes(pe, 1) - epsilon;
      const double zmin = (dim == 3) ? bounding_boxes(pe, 2) - epsilon : -epsilon;
      const double xmax = bounding_boxes(pe, dim) + epsilon;
      const double ymax = bounding_boxes(pe, dim+1) + epsilon;
      const double zmax = (dim == 3) ? bounding_boxes(pe, dim+2) + epsilon : epsilon;
      octree.search_elements_box(xmin, ymin, zmin, xmax, ymax, zmax, nodes_list);
      Sortie& buffer = schema.send_buffer(pe);
      const int n = nodes_list.size_array();
      for (i = 0; i < n; i++)
        {
          const int som = nodes_list[i];
          const double x = coords(som, 0);
          const double y = coords(som, 1);
          const double z = (dim==3) ? coords(som, 2) : 0;
// test again if inside bounding box (octree test gives more nodes)
          if (x>=xmin && x<=xmax && y>=ymin && y<=ymax && z>=zmin && z<=zmax)
            {
              buffer << x << y << z;
            }
        }
    }
  schema.echange_taille_et_messages();
  for (ipe = 0; ipe < all_pe.size_array(); ipe++)
    {
      const int pe = all_pe[ipe]; //!< processor number
      Entree& buffer = schema.recv_buffer(pe);
      ArrOfInt& resu = match[pe];
      resu.set_smart_resize(1);
      resu.resize_array(0);
      while(1)
        {
          double x, y, z;
          buffer >> x >> y >> z;
          if (buffer.eof())
            break;
// Seach for this node in my list
          octree.search_elements_box(x-epsilon, y-epsilon, z-epsilon,
                                     x+epsilon, y+epsilon, z+epsilon, nodes_list);
// Refine search to keep only matching nodes:
          octree.search_nodes_close_to(x, y, z, coords, nodes_list, epsilon);
          const int n = nodes_list.size_array();
          if (n > 1)
            {
              Cerr << "Error in automatic joint builder: more than one node within epsilon tolerance\n"
                   << " node coord = " << x << " " << y << " " << z << " tolerance= " << epsilon << finl;
              Process::exit();
            }
          if (n == 1)
            resu.append_array(nodes_list[0]);
        }
    }
  schema.end_comm();
}
References TRUSTArray< _TYPE_ >::append_array(), bbox_intersection(), Schema_Comm::begin_comm(), Octree_Double::build_nodes(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), envoyer_all_to_all(), Entree::eof(), Process::exit(), finl, Process::me(), Process::nproc(), Schema_Comm::recv_buffer(), TRUSTArray< _TYPE_ >::resize_array(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_ >::set_smart_resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by auto_build_joints().
Variable Documentation
MaillerParallelbases
const Type_info* MaillerParallelbases[1] ={ &(Interprete ::info_obj)}
Definition at line 35 of file MaillerParallel.cpp.