TRUST: src/Kernel/Math/Matrices/Matrice_Morse.cpp File Reference
src/Kernel/Math/Matrices/Matrice_Morse.cpp File Reference
#include <Matrice_Morse.h>
#include <DoubleLists.h>
#include <IntLists.h>
#include <Sparskit.h>
#include <Matrice_Morse_Sym.h>
#include <Check_espace_virtuel.h>
#include <comm_incl.h>
#include <Noms.h>
#include <ArrOfBit.h>
#include <Array_tools.h>
#include <IntTrav.h>
#include <DoubleTrav.h>
#include <Matrix_tools.h>
Functions
Matrice_Morse operator+ (const Matrice_Morse &A, const Matrice_Morse &B)
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Matrice_Morse operator* (double x, const Matrice_Morse &A)
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
int Matrice_Morse_test ()
NE FAIT RIEN.
Variables
const Type_info * Matrice_Morsebases [1] = { &(Matrice_Base ::info_obj)}
Function Documentation
int Matrice_Morse_test ()
NE FAIT RIEN.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 2245 of file Matrice_Morse.cpp.
{
  return 1;
}
Matrice_Morse operator* (double x, const Matrice_Morse & A)
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
Returns:
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1831 of file Matrice_Morse.cpp.
References Matrice_Morse::coeff_.
{
  Matrice_Morse mat_res(A);
  mat_res.coeff_*=x;
  return(mat_res);
}
Matrice_Morse operator+ (const Matrice_Morse & A, const Matrice_Morse & B)
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Returns:
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1117 of file Matrice_Morse.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Matrice_Morse::dimensionner(), F77NAME, Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::has_same_morse_matrix_structure(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), DoubleVect::resize(), IntVect::resize(), and Matrice_Morse::tab1_.
{
  int nrow=A.nb_lignes();
  int ncol=A.nb_colonnes();
  int job=1;
  int ierr;
  IntVect iw(ncol);
  Matrice_Morse C;
// PL: avant de dimensionner a nzmax on verifie si A et B n'ont pas la meme structure par hasard...
// Cela evite un pic memoire provoque par l'addition de matrices dans Equation_base::dimensionner_matrice
// Sinon, APLB n'est pas optimal, voir une autre implementation genre MKL:
// https://software.intel.com/en-us/mkl-developer-reference-c-mkl-sparse-add
  int nzmax = A.has_same_morse_matrix_structure(B) ? A.nb_coeff() : A.nb_coeff()+B.nb_coeff();
  C.dimensionner(nrow, ncol, nzmax);
  F77NAME(APLB) (&nrow, &ncol, &job, A.get_coeff().addr(), A.get_tab2().addr(), A.get_tab1().addr(),
                 B.get_coeff().addr(), B.get_tab2().addr(), B.get_tab1().addr(), C.get_set_coeff().addr(),
                 C.get_set_tab2().addr(), C.get_set_tab1().addr(),
                 &nzmax,iw.addr(),&ierr);
  const int nnz = C.tab1_[nrow] - 1;
  C.get_set_tab2().resize( nnz );
  C.get_set_coeff().resize( nnz );
  C.morse_matrix_structure_has_changed_=1;
  return(C);
}
Variable Documentation
const Type_info* Matrice_Morsebases[1] = { &(Matrice_Base ::info_obj)}
Definition at line 37 of file Matrice_Morse.cpp.