TRUST: src/Kernel/Math/Matrices/Matrice_Morse_Sym.h File Reference
src/Kernel/Math/Matrices/Matrice_Morse_Sym.h File Reference
#include <Matrice_Morse.h>
#include <Matrice_Sym.h>
#include <Matrice.h>
Classes
class Matrice_Morse_Sym
Classe Matrice_Morse_Sym
Represente une matrice M (creuse) symetrique stockee au format Morse
Symetrique: on ne stocke que la partie triangulaire superieure de la
matrice. Important: Tous les coefficients diagonaux doivent etre stockes
meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect).
Cette classe derive de Matrice_Morse et Matrice_Sym.
Functions
int Matrice_Morse_Sym_test ()
Matrice_Morse operator+ (const Matrice_Morse &, const Matrice_Morse &)
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Matrice_Morse operator* (double, const Matrice_Morse &)
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym &, const Matrice_Morse_Sym &)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym &, double)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Matrice_Morse_Sym operator* (double, const Matrice_Morse_Sym &)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Function Documentation
int Matrice_Morse_Sym_test ()
Definition at line 889 of file Matrice_Morse_Sym.cpp.
{
  return 1;
}
Matrice_Morse_Sym operator* (double x, const Matrice_Morse_Sym & A)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns:
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 621 of file Matrice_Morse_Sym.cpp.
References Matrice_Morse::get_set_coeff(), and Matrice_Morse::morse_matrix_structure_has_changed_.
{
  Matrice_Morse_Sym mat_res(A);
  mat_res.get_set_coeff()*=x;
  mat_res.morse_matrix_structure_has_changed_=1;
  return(mat_res);
}
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym & A, double x)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Returns:
Matrice_Morse_Sym
Signification: le resultat de l'appel sous-jacent
Contraintes:
Definition at line 650 of file Matrice_Morse_Sym.cpp.
{
  return(x*A);
}
Matrice_Morse operator* (double x, const Matrice_Morse & A)
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
Returns:
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1831 of file Matrice_Morse.cpp.
References Matrice_Morse::coeff_.
{
  Matrice_Morse mat_res(A);
  mat_res.coeff_*=x;
  return(mat_res);
}
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym & A, const Matrice_Morse_Sym & B)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns:
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 475 of file Matrice_Morse_Sym.cpp.
References DoubleList::add(), DoubleList::add_if_not(), Cerr, Process::exit(), finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_lignes(), DoubleList::suppr(), and DoubleList::vide().
{
// Il faut evidemment que les matrices soient de meme taille
  if (A.nb_lignes() != B.nb_lignes())
    {
      Cerr << "Error in Matrice_Morse_Sym::operator+" << finl;
      Cerr << "The 2 matrices must have the same dimension" << finl;
      Cerr << "The first matrix is of dimension: " << A.nb_lignes()<< finl;
      Cerr << "The second matrix is of dimension: " << B.nb_lignes()<< finl;
      Process::exit();
    }
  Matrice_Morse_Sym somme(A.nb_lignes(),A.nb_coeff()+B.nb_coeff());
  IntList colonnes_A_ligne_i,colonnes_B_ligne_i;
  int min_colonnes_A,min_colonnes_B,non_nuls_ligne_i;
  DoubleList coeffs_A_ligne_i,coeffs_B_ligne_i;
  double coeff_A,coeff_B;
// Pour s'assurer que compacte() va marcher
  for (int i=0; i<somme.get_coeff().size(); i++)
    somme.get_set_coeff()(i) = 0.;
// On va remplir tab2_ par ordre croissant de colonnes
  somme.get_set_tab1()(0) = 1;
  for (int i=0; i<A.nb_lignes(); i++) //boucle sur les lignes
    {
// Pour eviter les effets de bord
      if (!colonnes_A_ligne_i.est_vide()) colonnes_A_ligne_i.vide();
      if (!colonnes_B_ligne_i.est_vide()) colonnes_B_ligne_i.vide();
// Initialisation des colonnes_A et colonnes_B
// ATTENTION a la numerotation C++
      for (int j=0; j<A.get_tab1()(i+1)-A.get_tab1()(i); j++)
        {
          colonnes_A_ligne_i.add_if_not(A.get_tab2()(A.get_tab1()(i)+j-1));
          coeffs_A_ligne_i.add(A.get_coeff()(A.get_tab1()(i)+j-1));
        }//fin for
      for (int j=0; j<B.get_tab1()(i+1)-B.get_tab1()(i); j++)
        {
          colonnes_B_ligne_i.add_if_not(B.get_tab2()(B.get_tab1()(i)+j-1));
          coeffs_B_ligne_i.add(B.get_coeff()(B.get_tab1()(i)+j-1));
        }//fin for
// On initialise d'autres varibles
      non_nuls_ligne_i = 0;
// Debut de l'algorithme
      while (!colonnes_A_ligne_i.est_vide() || !colonnes_B_ligne_i.est_vide())
        {
// Si l'une des listes est vide et pas l'autre
          if (colonnes_A_ligne_i.est_vide() && !colonnes_B_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_B_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_B_ligne_i[0] ;
              colonnes_B_ligne_i.suppr(colonnes_B_ligne_i[0]);
              coeffs_B_ligne_i.suppr(coeffs_B_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
          if (colonnes_B_ligne_i.est_vide() && !colonnes_A_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_A_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_A_ligne_i[0];
              colonnes_A_ligne_i.suppr(colonnes_A_ligne_i[0]);
              coeffs_A_ligne_i.suppr(coeffs_A_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
// Aucune des deux listes n'est vide
          min_colonnes_A = colonnes_A_ligne_i[0];
          min_colonnes_B = colonnes_B_ligne_i[0];
          coeff_A = coeffs_A_ligne_i[0];
          coeff_B = coeffs_B_ligne_i[0];
          if (min_colonnes_A < min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              coeffs_A_ligne_i.suppr(coeff_A);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_B < min_colonnes_A)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_B;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_B;
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_A == min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A+coeff_B;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_A_ligne_i.suppr(coeff_A);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
        }//!< fin while
      somme.get_set_tab1()(i+1) = somme.get_tab1()(i)+non_nuls_ligne_i;//?????
    }//!< fin for
  somme.compacte();
  somme.morse_matrix_structure_has_changed_=1;
  return somme;
}
Matrice_Morse operator+ (const Matrice_Morse & A, const Matrice_Morse & B)
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Returns:
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1117 of file Matrice_Morse.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Matrice_Morse::dimensionner(), F77NAME, Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::has_same_morse_matrix_structure(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), DoubleVect::resize(), IntVect::resize(), and Matrice_Morse::tab1_.
{
  int nrow=A.nb_lignes();
  int ncol=A.nb_colonnes();
  int job=1;
  int ierr;
  IntVect iw(ncol);
  Matrice_Morse C;
// PL: avant de dimensionner a nzmax on verifie si A et B n'ont pas la meme structure par hasard...
// Cela evite un pic memoire provoque par l'addition de matrices dans Equation_base::dimensionner_matrice
// Sinon, APLB n'est pas optimal, voir une autre implementation genre MKL:
// https://software.intel.com/en-us/mkl-developer-reference-c-mkl-sparse-add
  int nzmax = A.has_same_morse_matrix_structure(B) ? A.nb_coeff() : A.nb_coeff()+B.nb_coeff();
  C.dimensionner(nrow, ncol, nzmax);
  F77NAME(APLB) (&nrow, &ncol, &job, A.get_coeff().addr(), A.get_tab2().addr(), A.get_tab1().addr(),
                 B.get_coeff().addr(), B.get_tab2().addr(), B.get_tab1().addr(), C.get_set_coeff().addr(),
                 C.get_set_tab2().addr(), C.get_set_tab1().addr(),
                 &nzmax,iw.addr(),&ierr);
  const int nnz = C.tab1_[nrow] - 1;
  C.get_set_tab2().resize( nnz );
  C.get_set_coeff().resize( nnz );
  C.morse_matrix_structure_has_changed_=1;
  return(C);
}