TRUST: src/Kernel/Math/Matrices/Matrice_Morse_Sym.cpp File Reference
src/Kernel/Math/Matrices/Matrice_Morse_Sym.cpp File Reference
#include <Matrice_Morse_Sym.h>
#include <IntList.h>
#include <DoubleList.h>
#include <Sparskit.h>
#include <comm_incl.h>
#include <Noms.h>
#include <Vect_ArrOfInt.h>
#include <Vect_IntTab.h>
#include <Array_tools.h>
Functions
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym &A, const Matrice_Morse_Sym &B)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Matrice_Morse_Sym operator* (double x, const Matrice_Morse_Sym &A)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym &A, double x)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
int Matrice_Morse_Sym_test ()
Variables
const Type_info * Matrice_Morse_Symbases [1] = { &(Matrice_Morse ::info_obj)}
Function Documentation
int Matrice_Morse_Sym_test ()
Definition at line 889 of file Matrice_Morse_Sym.cpp.
{
  return 1;
}
Matrice_Morse_Sym operator* (double x, const Matrice_Morse_Sym & A)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns:
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 621 of file Matrice_Morse_Sym.cpp.
References Matrice_Morse::get_set_coeff(), and Matrice_Morse::morse_matrix_structure_has_changed_.
{
  Matrice_Morse_Sym mat_res(A);
  mat_res.get_set_coeff()*=x;
  mat_res.morse_matrix_structure_has_changed_=1;
  return(mat_res);
}
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym & A, double x)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Returns:
Matrice_Morse_Sym
Signification: le resultat de l'appel sous-jacent
Contraintes:
Definition at line 650 of file Matrice_Morse_Sym.cpp.
{
  return(x*A);
}
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym & A, const Matrice_Morse_Sym & B)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns:
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 475 of file Matrice_Morse_Sym.cpp.
References DoubleList::add(), DoubleList::add_if_not(), Cerr, Process::exit(), finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_lignes(), DoubleList::suppr(), and DoubleList::vide().
{
// Il faut evidemment que les matrices soient de meme taille
  if (A.nb_lignes() != B.nb_lignes())
    {
      Cerr << "Error in Matrice_Morse_Sym::operator+" << finl;
      Cerr << "The 2 matrices must have the same dimension" << finl;
      Cerr << "The first matrix is of dimension: " << A.nb_lignes()<< finl;
      Cerr << "The second matrix is of dimension: " << B.nb_lignes()<< finl;
      Process::exit();
    }
  Matrice_Morse_Sym somme(A.nb_lignes(),A.nb_coeff()+B.nb_coeff());
  IntList colonnes_A_ligne_i,colonnes_B_ligne_i;
  int min_colonnes_A,min_colonnes_B,non_nuls_ligne_i;
  DoubleList coeffs_A_ligne_i,coeffs_B_ligne_i;
  double coeff_A,coeff_B;
// Pour s'assurer que compacte() va marcher
  for (int i=0; i<somme.get_coeff().size(); i++)
    somme.get_set_coeff()(i) = 0.;
// On va remplir tab2_ par ordre croissant de colonnes
  somme.get_set_tab1()(0) = 1;
  for (int i=0; i<A.nb_lignes(); i++) //boucle sur les lignes
    {
// Pour eviter les effets de bord
      if (!colonnes_A_ligne_i.est_vide()) colonnes_A_ligne_i.vide();
      if (!colonnes_B_ligne_i.est_vide()) colonnes_B_ligne_i.vide();
// Initialisation des colonnes_A et colonnes_B
// ATTENTION a la numerotation C++
      for (int j=0; j<A.get_tab1()(i+1)-A.get_tab1()(i); j++)
        {
          colonnes_A_ligne_i.add_if_not(A.get_tab2()(A.get_tab1()(i)+j-1));
          coeffs_A_ligne_i.add(A.get_coeff()(A.get_tab1()(i)+j-1));
        }//fin for
      for (int j=0; j<B.get_tab1()(i+1)-B.get_tab1()(i); j++)
        {
          colonnes_B_ligne_i.add_if_not(B.get_tab2()(B.get_tab1()(i)+j-1));
          coeffs_B_ligne_i.add(B.get_coeff()(B.get_tab1()(i)+j-1));
        }//fin for
// On initialise d'autres varibles
      non_nuls_ligne_i = 0;
// Debut de l'algorithme
      while (!colonnes_A_ligne_i.est_vide() || !colonnes_B_ligne_i.est_vide())
        {
// Si l'une des listes est vide et pas l'autre
          if (colonnes_A_ligne_i.est_vide() && !colonnes_B_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_B_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_B_ligne_i[0] ;
              colonnes_B_ligne_i.suppr(colonnes_B_ligne_i[0]);
              coeffs_B_ligne_i.suppr(coeffs_B_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
          if (colonnes_B_ligne_i.est_vide() && !colonnes_A_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_A_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_A_ligne_i[0];
              colonnes_A_ligne_i.suppr(colonnes_A_ligne_i[0]);
              coeffs_A_ligne_i.suppr(coeffs_A_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
// Aucune des deux listes n'est vide
          min_colonnes_A = colonnes_A_ligne_i[0];
          min_colonnes_B = colonnes_B_ligne_i[0];
          coeff_A = coeffs_A_ligne_i[0];
          coeff_B = coeffs_B_ligne_i[0];
          if (min_colonnes_A < min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              coeffs_A_ligne_i.suppr(coeff_A);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_B < min_colonnes_A)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_B;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_B;
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_A == min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A+coeff_B;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_A_ligne_i.suppr(coeff_A);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
        }//!< fin while
      somme.get_set_tab1()(i+1) = somme.get_tab1()(i)+non_nuls_ligne_i;//?????
    }//!< fin for
  somme.compacte();
  somme.morse_matrix_structure_has_changed_=1;
  return somme;
}
Variable Documentation
const Type_info* Matrice_Morse_Symbases[1] = { &(Matrice_Morse ::info_obj)}
Definition at line 33 of file Matrice_Morse_Sym.cpp.