TRUST: src/Kernel/Math/MD_Vector_tools.cpp File Reference
src/Kernel/Math/MD_Vector_tools.cpp File Reference
#include <MD_Vector_tools.h>
#include <Schema_Comm_Vecteurs.h>
#include <MD_Vector_composite.h>
#include <IntTab.h>
#include <Echange_EV_Options.h>
#include <Schema_Comm.h>
#include <stat_counters.h>
#include <communications.h>
#include <vector>
Functions
template<class VECT , class TAB >
static void creer_tableau_distribue (const MD_Vector &md, VECT &v, Array_base::Resize_Options opt)
template<class VType >
void echange_espace_virtuel_ (const MD_Vector &md, VType &v, int is_double, const Echange_EV_Options &opt=echange_ev_opt_default)
template<class VType >
void echange_espace_virtuel1_ (const MD_Vector &md, VType &v, int is_double, MD_Vector_tools::Operations_echange opt)
void setflag (ArrOfInt &flags, int i)
void clearflag (ArrOfInt &flags, int i)
void setflag (ArrOfBit &flags, int i)
void clearflag (ArrOfBit &flags, int i)
template<class FlagsType >
static int get_seq_flags (const MD_Vector_base &mdv, FlagsType &flags, int startidx, int line_size)
static int extract_blocs (const ArrOfInt src, const ArrOfInt &renum, ArrOfInt &dest)
Renvoie le nombre d'items extraits (pas le nombre de blocs)
static void creer_md_vect_renum (const IntVect &renum, const MD_Vector_std &src, MD_Vector_std &dest)
Variables
static Schema_Comm_Vecteurs comm
static MD_Vector last_md
static int last_isdouble = -1
static int last_linesize = 0
static Echange_EV_Options last_opt
Function Documentation
void clearflag (ArrOfInt & flags, int i) [inline]
Definition at line 225 of file MD_Vector_tools.cpp.
Referenced by get_seq_flags().
{
  flags[i] = 0;
}
void clearflag (ArrOfBit & flags, int i) [inline]
Definition at line 234 of file MD_Vector_tools.cpp.
References ArrOfBit::clearbit().
{
  flags.clearbit(i);
}
static void creer_md_vect_renum (const IntVect & renum, const MD_Vector_std & src, MD_Vector_std & dest) [static]
< Compteur d'items recus dans le descripteur source 1) Extraction des items individuels (remplissage de dest_items_recv_index, dest_items_recv_data et tmp)
< nombre d'items recus de ce processeur
< ne peut jamais etre egal a rj-1 Pour chaque item du bloc, s'il doit etre conserve, le reporter dans les blocs a recevoir:
< Initialise a zero
< Cet item est dans les blocs_to_recv_ de l'autre cote k est l'indice dans l'ancien tableau de l'item a envoyer
Definition at line 341 of file MD_Vector_tools.cpp.
References ArrOfInt::append_array(), Schema_Comm::begin_comm(), MD_Vector_std::blocs_items_count_, MD_Vector_base2::blocs_items_to_compute_, MD_Vector_base2::blocs_items_to_sum_, MD_Vector_std::blocs_to_recv_, Cerr, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), extract_blocs(), finl, Static_Int_Lists::get_data(), Static_Int_Lists::get_list_size(), MD_Vector_base2::get_nb_items_reels(), MD_Vector_base2::get_nb_items_tot(), MD_Vector_std::items_to_recv_, MD_Vector_std::items_to_send_, Process::me(), Process::mp_sum(), MD_Vector_base2::nb_items_reels_, MD_Vector_base2::nb_items_seq_local_, MD_Vector_base2::nb_items_seq_tot_, MD_Vector_std::nb_items_to_items_, MD_Vector_base2::nb_items_tot_, Array_base::NOCOPY_NOINIT, MD_Vector_std::pe_voisins_, Schema_Comm::recv_buffer(), ArrOfInt::resize_array(), Schema_Comm::send_buffer(), Static_Int_Lists::set_index_data(), Schema_Comm::set_send_recv_pe_list(), ArrOfInt::set_smart_resize(), and ArrOfInt::size_array().
Referenced by Zone_Cl_VEF::associer().
{
// Calcul de nb_items_tot_ et nb_items_reels_
// nb_items_tot_ est le nombre d'items pour lesquels renum[i] >= 0
// Les items reels sont ceux qui etaient reels dans le tableau d'origine et qui sont a conserver
  {
    const int src_size = src.get_nb_items_tot();
    const int src_size_r = src.get_nb_items_reels();
    dest.nb_items_tot_ = 0;
    dest.nb_items_reels_ = 0;
    for (int i = 0; i < src_size; i++)
      {
        if (renum[i] >= 0)
          {
            dest.nb_items_tot_++;
            if (i < src_size_r)
              dest.nb_items_reels_++;
          }
      }
// Si l'attribut nb_items_reels_ est invalide dans le vecteur source, il est invalide dans le
// vecteur resultat:
    if (src_size_r < 0)
      dest.nb_items_reels_ = -1;
  }
// Remplissage de blocs_items_to_sum_ et blocs_items_to_compute_
// Ce sont les items pour lesquels renum[i] >= 0 et qui sont dans les blocs_items_to_sum_
// et blocs_items_to_compute_ du descripteur source.
  extract_blocs(src.blocs_items_to_sum_, renum, dest.blocs_items_to_sum_);
  dest.nb_items_seq_local_ = extract_blocs(src.blocs_items_to_compute_, renum, dest.blocs_items_to_compute_);
  dest.nb_items_seq_tot_ = Process::mp_sum(dest.nb_items_seq_local_);
// ********************************************************
// Calcul des items a recevoir: ce sont les items pour lesquels renum[i] >= 0 et qui etaient a
// recevoir dans le descripteur source.
// Chaque fois qu'on trouve un item a recevoir, il faut informer le processeur voisin qui possede l'item
// que c'est item doit etre envoye (utilisation du schema_comm). Pour identifier ces items, on utilise
// sont rang dans le tableau des items a envoyer dans le descripteur source (variable item_rank)
//
  const int nb_pe_voisins = src.pe_voisins_.size_array();
  Schema_Comm schema_comm;
  schema_comm.set_send_recv_pe_list(src.pe_voisins_, src.pe_voisins_);
  schema_comm.begin_comm();
// Calcul des listes items_to_recv
// index+data forment les deux tableau d'un StaticIntLists.
// On construit pour commencer autant de listes que de processeurs voisins dans le descripteur source.
// On retirera a la fin les processeurs qui n'echangent pas de donnees
  ArrOfInt dest_items_recv_index;
  ArrOfInt dest_items_recv_data;
  ArrOfInt dest_blocs_recv_index;
  ArrOfInt dest_blocs_recv_data;
  ArrOfInt tmp;
  tmp.set_smart_resize(1);
  {
    dest_items_recv_index.resize_array(nb_pe_voisins + 1, Array_base::NOCOPY_NOINIT);
    dest_items_recv_index[0] = 0;
    dest_blocs_recv_index.resize_array(nb_pe_voisins + 1, Array_base::NOCOPY_NOINIT);
    dest_blocs_recv_index[0] = 0;
    dest.blocs_items_count_.resize_array(nb_pe_voisins, Array_base::NOCOPY_NOINIT);
    dest.nb_items_to_items_.resize_array(nb_pe_voisins, Array_base::NOCOPY_NOINIT);
// Preallocation de la taille maxi
    dest_items_recv_data.resize_array(src.items_to_recv_.get_data().size_array(), Array_base::NOCOPY_NOINIT);
    dest_items_recv_data.set_smart_resize(1);
    dest_items_recv_data.resize_array(0);
// On ne peut pas prevoir le nombre de blocs, il peut y en avoir plus que dans la source
    dest_blocs_recv_data.set_smart_resize(1);
    for (int i_pe = 0; i_pe < nb_pe_voisins; i_pe++)
      {
        tmp.resize_array(0);
        int item_rank = 0; //!< Compteur d'items recus dans le descripteur source 1) Extraction des items individuels    (remplissage de dest_items_recv_index, dest_items_recv_data et tmp)
//
//
        const int n = src.items_to_recv_.get_list_size(i_pe);
        for (int i = 0; i < n; i++)
          {
            const int j = src.items_to_recv_(i_pe, i);
            const int rj = renum[j];
            if (rj >= 0)
              {
// Ajout de cet item
                dest_items_recv_data.append_array(rj);
// Demander au processeur voisin d'envoyer cet item
                tmp.append_array(item_rank);
              }
            item_rank++;
          }
// Initialisation de la taille de la liste d'items pour ce processeur:
        dest_items_recv_index[i_pe+1] = dest_items_recv_data.size_array();
// 2) Extraction des blocs d'items recus de ce processeur
// (remplissage de dest_blocs_recv_index dest_blocs_recv_data dest.blocs_items_count_ et tmp)
        const int nblocs = src.blocs_to_recv_.get_list_size(i_pe) / 2;
        int received_count = 0; //!< nombre d'items recus de ce processeur
        for (int ibloc = 0; ibloc < nblocs; ibloc++)
          {
            const int jdeb = src.blocs_to_recv_(i_pe, ibloc * 2);
            const int jfin = src.blocs_to_recv_(i_pe, ibloc * 2 + 1);
            int last_added = -2; //!< ne peut jamais etre egal a rj-1 Pour chaque item du bloc, s'il doit etre conserve, le reporter dans les blocs a recevoir:
//
            for (int j = jdeb; j < jfin; j++)
              {
                const int rj = renum[j];
                if (rj >= 0)
                  {
                    if (rj <= last_added)
                      {
// Les items dans les blocs a recevoir doivent etre tries dans l'ordre croissant
// (sinon cet algorithme ne marche pas, il faut en utiliser un autre pour
// construire les blocs, et en plus le comptage des items reels ne veut peut-etre plus rien dire)
                        Cerr << "Error in creer_md_vect_renum: renum array is not sorted: cannot extract blocs to recv" << finl;
                        Process::exit();
                      }
// Cet item est-il contigu avec le precedent ?
                    if (last_added == rj-1)
                      {
// Oui, augmenter la taille du dernier bloc
                        const int k = dest_blocs_recv_data.size_array();
// fin de bloc = indice du dernier plus 1
                        dest_blocs_recv_data[k-1] = rj+1;
                      }
                    else
                      {
// Non, creer un nouveau bloc
                        dest_blocs_recv_data.append_array(rj);
                        dest_blocs_recv_data.append_array(rj+1);
                      }
                    last_added = rj;
// Demander au processeur voisin d'envoyer cet item
                    tmp.append_array(item_rank);
                    received_count++;
                  }
                item_rank++;
              }
          }
// Initialisation de la taille de la liste de blocs pour ce processeur:
        dest_blocs_recv_index[i_pe+1] = dest_blocs_recv_data.size_array();
// Nombre d'items recus de ce processeur
        dest.blocs_items_count_[i_pe] = received_count;
// Envoi du tableau tmp au processeur voisin:
        schema_comm.send_buffer(src.pe_voisins_[i_pe]) << tmp;
      }
  }
  schema_comm.echange_taille_et_messages();
// ********************************************************
// Construction de dest.items_to_send avec les infos recues
//
  ArrOfInt dest_items_send_index;
  dest_items_send_index.resize_array(nb_pe_voisins + 1, Array_base::NOCOPY_NOINIT);
  ArrOfInt dest_items_send_data;
  ArrOfInt nb_items_to_items(nb_pe_voisins); //!< Initialise a zero
// Allocation d'une taille par borne superieure:
  dest_items_send_data.resize_array(src.items_to_send_.get_data().size_array(), Array_base::NOCOPY_NOINIT);
  dest_items_send_index[0] = 0;
  {
    int count = 0;
    int error = 0;
    for (int i_pe = 0; i_pe < nb_pe_voisins; i_pe++)
      {
// nb_item_received_single est le nombre d'items dans items_to_send_ qui seront receptionnes
// par items_to_recv_. Les suivants sont recus dans blocs_to_recv_.
        const int j_limite_bloc = src.nb_items_to_items_[i_pe];
        int new_j_limite_bloc = 0;
        schema_comm.recv_buffer(src.pe_voisins_[i_pe]) >> tmp;
        const int n = tmp.size_array();
        for (int i = 0; i < n; i++)
          {
// tmp contient des indices qui pointent dans src.items_to_send_
            int j = tmp[i];
            if (j >= j_limite_bloc)
              new_j_limite_bloc++; //!< Cet item est dans les blocs_to_recv_ de l'autre cote k est l'indice dans l'ancien tableau de l'item a envoyer
//
            int k = src.items_to_send_(i_pe, j);
            int renum_k = renum[k];
// Une erreur possible ici: un processeur a besoin d'un item virtuel et l'item
// reel a ete supprime sur le processeur source. Il faut alors utiliser un
// autre algo pour changer le proprietaire de l'item...
            if (renum_k < 0)
              error = 1;
            dest_items_send_data[count++] = renum_k;
          }
        dest_items_send_index[i_pe+1] = count;
        nb_items_to_items[i_pe] = new_j_limite_bloc;
      }
    if (error)
      {
        Cerr << "Internal error in MD_Vector_tools::creer_md_vect_renum:\n"
             << " processor " << Process::me()
             << " received a request for distant items that are not in the new vector" << finl;
        Process::exit();
      }
// On ajuste a la taille definitive
    dest_items_send_data.set_smart_resize(1);
    dest_items_send_data.resize_array(count);
  }
  schema_comm.end_comm();
// Construction de la liste de processeurs voisins de dest
// (processeurs avec qui on echange des donnees)
// Et compression des indexes des StaticIntLists pour retirer les
// processeurs supprimes.
  {
    int pe_count = 0;
    dest.pe_voisins_.resize_array(nb_pe_voisins, Array_base::NOCOPY_NOINIT);
    for (int i_pe = 0; i_pe < nb_pe_voisins; i_pe++)
      {
        int flag = 0;
        if (dest_items_recv_index[i_pe+1] - dest_items_recv_index[i_pe] > 0)
          flag = 1;
        if (dest_blocs_recv_index[i_pe+1] - dest_blocs_recv_index[i_pe] > 0)
          flag = 1;
        if (dest_items_send_index[i_pe+1] - dest_items_send_index[i_pe] > 0)
          flag = 1;
        if (flag)
          {
            dest_items_recv_index[pe_count+1] = dest_items_recv_index[i_pe+1];
            dest_blocs_recv_index[pe_count+1] = dest_blocs_recv_index[i_pe+1];
            dest_items_send_index[pe_count+1] = dest_items_send_index[i_pe+1];
            dest.blocs_items_count_[pe_count] = dest.blocs_items_count_[i_pe];
            dest.pe_voisins_[pe_count] = src.pe_voisins_[i_pe];
            dest.nb_items_to_items_[pe_count] = nb_items_to_items[i_pe];
            pe_count++;
          }
      }
    dest_items_recv_index.set_smart_resize(1);
    dest_items_recv_index.resize_array(pe_count+1);
    dest_blocs_recv_index.set_smart_resize(1);
    dest_blocs_recv_index.resize_array(pe_count+1);
    dest_items_send_index.set_smart_resize(1);
    dest_items_send_index.resize_array(pe_count+1);
    dest.pe_voisins_.set_smart_resize(1);
    dest.pe_voisins_.resize_array(pe_count);
    dest.blocs_items_count_.set_smart_resize(1);
    dest.blocs_items_count_.resize_array(pe_count);
    dest.nb_items_to_items_.set_smart_resize(1);
    dest.nb_items_to_items_.resize_array(pe_count);
  }
  dest.items_to_send_.set_index_data(dest_items_send_index, dest_items_send_data);
  dest.items_to_recv_.set_index_data(dest_items_recv_index, dest_items_recv_data);
  dest.blocs_to_recv_.set_index_data(dest_blocs_recv_index, dest_blocs_recv_data);
}
template<class VECT , class TAB > static void creer_tableau_distribue (const MD_Vector & md, VECT & v, Array_base::Resize_Options opt) [static]
Definition at line 39 of file MD_Vector_tools.cpp.
References Cerr, Process::exit(), finl, MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), ref_cast, sub_type, sz, and MD_Vector::valeur().
Referenced by Debog_Pb::add_renum_item(), Zone_Cl_VEF::associer(), Scatter::construire_espace_virtuel_traduction(), Scatter::construire_md_vector(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Parmetis::construire_partition(), Scatter::construire_structures_paralleles(), Zone_VF::creer_tableau_aretes(), Zone::creer_tableau_elements(), Zone_VF::creer_tableau_faces(), Frontiere::creer_tableau_faces(), Zone_VF::creer_tableau_faces_bord(), Zone_VEF_PreP1b::creer_tableau_p1bulle(), Domaine::creer_tableau_sommets(), Zone::init_faces_virt_bord(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Traduction_Indice_Global_Local::initialiser(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), and Debog_Pb::verifier_matrice().
{
  if (v.get_md_vector().non_nul())
    {
// Si ce message apparait et qu'on est sur de ce qu'on fait,
// faire ceci avant d'appeler creer_tableau_distribue:
// vect.set_md_vector(MD_Vector()); // Annule le descripteur et garde le vecteur.
// ou
// vect.reset(); // Detruit completement le contenu du vecteur
      Cerr << "Internal error in MD_Vector_tools::creer_tableau_distribue:\n"
           << " Vector already has a parallel vector structure" << finl;
      Process::exit();
    }
  int sz = md.valeur().get_nb_items_tot();
// Attention, sz_r peut valoir -1 dans certains cas. Alors le test n==sz_r sera toujours faux,
// mais c'est bien ce qu'on veut...
  int sz_r = md.valeur().get_nb_items_reels();
  int err = 0;
  if (sub_type(TAB, v))
    {
      TAB& t = ref_cast(TAB, v);
      const int n = t.dimension_tot(0);
      if (n == sz_r || n == 0)
        {
          t.resize_dim0(sz, opt);
        }
      else if (n == sz)
        {
// ok no resize
        }
      else
        {
          err = 1;
        }
    }
  else
    {
      const int n = v.size_totale();
      if (n == sz_r || n == 0)
        {
          v.resize(sz, opt);
        }
      else if (n == sz)
        {
// ok no resize
        }
      else
        {
          err = 1;
        }
    }
  if (err)
    {
      Cerr << "Internal error in MD_Vector_tools::creer_tableau_distribue:\n"
           << " Input vector has wrong size or dimension(0): expected 0 or size_reele=" << sz_r << finl;
      Process::exit();
    }
  v.set_md_vector(md);
}
template<class VType > void echange_espace_virtuel1_ (const MD_Vector & md, VType & v, int is_double, MD_Vector_tools::Operations_echange opt)
Definition at line 160 of file MD_Vector_tools.cpp.
References Cerr, echange_espace_virtuel_(), MD_Vector_tools::ECHANGE_EV, echange_ev_opt_default, MD_Vector_tools::EV_MAX, MD_Vector_tools::EV_MINCOL1, MD_Vector_tools::EV_SOMME, MD_Vector_tools::EV_SOMME_ECHANGE, Process::exit(), finl, Echange_EV_Options::MAX, Echange_EV_Options::MINCOL1, and Echange_EV_Options::SUM.
Referenced by MD_Vector_tools::echange_espace_virtuel().
{
  switch(opt)
    {
    case MD_Vector_tools::ECHANGE_EV:
      echange_espace_virtuel_(md, v, is_double, echange_ev_opt_default);
      break;
    case MD_Vector_tools::EV_SOMME:
      echange_espace_virtuel_(md, v, is_double, Echange_EV_Options(Echange_EV_Options::SUM));
      break;
    case MD_Vector_tools::EV_SOMME_ECHANGE:
      echange_espace_virtuel_(md, v, is_double, Echange_EV_Options(Echange_EV_Options::SUM));
      echange_espace_virtuel_(md, v, is_double, echange_ev_opt_default);
      break;
    case MD_Vector_tools::EV_MAX:
      echange_espace_virtuel_(md, v, is_double, Echange_EV_Options(Echange_EV_Options::MAX));
      break;
    case MD_Vector_tools::EV_MINCOL1:
      echange_espace_virtuel_(md, v, is_double, Echange_EV_Options(Echange_EV_Options::MINCOL1));
      break;
    default:
      Cerr << "echange_espace_virtuel1_ operation not implemented" << finl;
      Process::exit();
    }
}
template<class VType > void echange_espace_virtuel_ (const MD_Vector & md, VType & v, int is_double, const Echange_EV_Options & opt = echange_ev_opt_default)
Definition at line 135 of file MD_Vector_tools.cpp.
References Schema_Comm_Vecteurs::begin_comm(), Schema_Comm_Vecteurs::begin_init(), Schema_Comm_Vecteurs::end_comm(), Schema_Comm_Vecteurs::end_init(), Schema_Comm_Vecteurs::exchange(), MD_Vector_base::initialize_comm(), last_isdouble, last_linesize, MD_Vector_base::prepare_send_data(), MD_Vector_base::process_recv_data(), and MD_Vector::valeur().
Referenced by echange_espace_virtuel1_().
{
  const MD_Vector_base& mdv = md.valeur();
  if (md == last_md && v.line_size() == last_linesize && last_isdouble == is_double && last_opt == opt)
    {
    }
  else
    {
      last_md = md;
      last_linesize = v.line_size();
      last_isdouble = is_double;
      last_opt = opt;
      comm.begin_init();
      mdv.initialize_comm(opt, comm, v);
      comm.end_init();
    }
  comm.begin_comm();
  mdv.prepare_send_data(opt, comm, v);
  comm.exchange();
  mdv.process_recv_data(opt, comm, v);
  comm.end_comm();
}
static int extract_blocs (const ArrOfInt src, const ArrOfInt & renum, ArrOfInt & dest) [static]
Renvoie le nombre d'items extraits (pas le nombre de blocs)
Definition at line 302 of file MD_Vector_tools.cpp.
References ArrOfInt::append_array(), ArrOfInt::resize_array(), ArrOfInt::set_smart_resize(), and ArrOfInt::size_array().
Referenced by creer_md_vect_renum().
{
  const int nblocs_src = src.size_array() / 2;
  dest.set_smart_resize(1);
  dest.resize_array(0);
  int end_last_bloc = -1;
  int count = 0;
  for (int i = 0; i < nblocs_src; i++)
    {
      const int deb = src[i*2];
      const int fin = src[i*2+1];
      for (int j = deb; j < fin; j++)
        {
          const int rj = renum[j];
          if (rj >= 0)
            {
              count++;
// Blocs construction assumes that renum is ordered
              assert(rj >= end_last_bloc);
              if (rj == end_last_bloc)
                {
// item is contiguous to last bloc in destination array, increase bloc size:
                  end_last_bloc++;
                  dest[dest.size_array()-1] = end_last_bloc;
                }
              else
                {
// non contiguous item, create new bloc
                  end_last_bloc = rj;
                  dest.append_array(end_last_bloc);
                  end_last_bloc++;
                  dest.append_array(end_last_bloc);
                }
            }
        }
    }
  return count;
}
template<class FlagsType > static int get_seq_flags (const MD_Vector_base & mdv, FlagsType & flags, int startidx, int line_size) [static]
< debut du prochain bloc d'items sequentiels
< fin du bloc d'items sequentiels
Definition at line 240 of file MD_Vector_tools.cpp.
References ArrOfInt::addr(), MD_Vector_base2::blocs_items_to_sum_, Cerr, clearflag(), Process::exit(), finl, MD_Vector_base::get_nb_items_tot(), Objet_U::que_suis_je(), ref_cast, setflag(), ArrOfInt::size_array(), sub_type, and sz.
Referenced by MD_Vector_tools::get_sequential_items_flags().
{
  int count = 0;
  if (sub_type(MD_Vector_base2, mdv))
    {
      const MD_Vector_base2& ms = ref_cast(MD_Vector_base2, mdv);
      const int nblocs = ms.blocs_items_to_sum_.size_array() >> 1;
      const int *ptr = ms.blocs_items_to_sum_.addr();
      int j = startidx;
      for (int i = nblocs; i; i--)
        {
// On pourrait optimiser pour les ArrOfBit en ajoutant a cette classe
// une methode setflag/clearflag(range_begin, range_end);
          int jmax = startidx + (*(ptr++)) * line_size; //!< debut du prochain bloc d'items sequentiels
          for (; j < jmax; j++)
            clearflag(flags, j);
          jmax = startidx + (*(ptr++)) * line_size; //!< fin du bloc d'items sequentiels
          assert(jmax > j);
          count += jmax - j;
          for (; j < jmax; j++)
            setflag(flags, j);
        }
// Fin du remplissage
      int sz = mdv.get_nb_items_tot() * line_size;
      for (; j < sz; j++)
        clearflag(flags, j);
    }
  else
    {
      Cerr << "Error in MD_Vector_tools::get_sequential_items_flags: unsupported MD_Vector type " << mdv.que_suis_je() << finl;
      Process::exit();
    }
  return count;
}
void setflag (ArrOfBit & flags, int i) [inline]
Definition at line 229 of file MD_Vector_tools.cpp.
{
// On a initialise le tableau a 1 par defaut dans get_sequential_items_flags()
  assert(flags[i] == 1);
}
void setflag (ArrOfInt & flags, int i) [inline]
Definition at line 221 of file MD_Vector_tools.cpp.
Referenced by get_seq_flags().
{
  flags[i] = 1;
}
Variable Documentation
Schema_Comm_Vecteurs comm [static]
Definition at line 32 of file MD_Vector_tools.cpp.
Referenced by Partitionneur_Parmetis::construire_partition(), Statistiques::new_counter(), and Statistiques::print_communciation_tracking_details().
int last_isdouble = -1 [static]
Definition at line 34 of file MD_Vector_tools.cpp.
Referenced by echange_espace_virtuel_().
int last_linesize = 0 [static]
Definition at line 35 of file MD_Vector_tools.cpp.
Referenced by echange_espace_virtuel_().
MD_Vector last_md [static]
Definition at line 33 of file MD_Vector_tools.cpp.
Echange_EV_Options last_opt [static]
Definition at line 36 of file MD_Vector_tools.cpp.