TRUST: src/Kernel/Math/MD_Vector_composite.cpp File Reference
MD_Vector_composite.cpp File Reference
#include <MD_Vector_composite.h>
#include <Array_tools.h>
#include <Param.h>
Functions
static void append_items (ArrOfInt &dest, const ArrOfInt &src, int offset=0, int multiplier=1)
static void append_blocs (ArrOfInt &dest, const ArrOfInt &src, int offset=0, int multiplier=1)
static int find_in_array (const ArrOfInt &a, int x)
returns i such that a[i]==x, or -1 if x is not found
static void append_global_md (MD_Vector_std &dest, const MD_Vector_std &src, int offset, int multiplier)
Variables
const Type_info * MD_Vector_compositebases [1] ={ &(MD_Vector_base2 ::info_obj)}
Function Documentation
append_blocs()
static void append_blocs (ArrOfInt & dest, const ArrOfInt & src, int offset = 0, int multiplier = 1) static
Definition at line 92 of file MD_Vector_composite.cpp.
{
  int i = dest.size_array();
  const int n = src.size_array();
  dest.resize_array(i + n);
  for (int j = 0; j < n; j++, i++)
    dest[i] = offset + src[j] * multiplier;
}
References TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by MD_Vector_composite::add_part(), and append_global_md().
append_global_md()
static void append_global_md (MD_Vector_std & dest, const MD_Vector_std & src, int offset, int multiplier) static
Definition at line 113 of file MD_Vector_composite.cpp.
{
// List sizes for items_to_send_, items_to_recv_ and blocs_to_recv_ of new descriptor
  ArrOfInt x_sz, y_sz, z_sz;
// Data of these lists:
  ArrOfInt x_data, y_data, z_data;
  ArrOfInt new_blocs_items_count, new_nb_items_to_items;
  x_sz.set_smart_resize(1);
  y_sz.set_smart_resize(1);
  z_sz.set_smart_resize(1);
  x_data.set_smart_resize(1);
  y_data.set_smart_resize(1);
  z_data.set_smart_resize(1);
  new_blocs_items_count.set_smart_resize(1);
  new_nb_items_to_items.set_smart_resize(1);
  ArrOfInt tmp;
  tmp.set_smart_resize(1);
  ArrOfInt pe_list(dest.pe_voisins_);
  pe_list.set_smart_resize(1);
  append_blocs(pe_list, src.pe_voisins_);
  array_trier_retirer_doublons(pe_list);
  const int np = pe_list.size_array();
  new_blocs_items_count.resize_array(np);
  new_nb_items_to_items.resize_array(np);
  for (int i = 0; i < np; i++)
    {
// Number of items to recv, send and blocs to recv for this processor:
      int nx = 0, ny = 0, nz = 0;
      int blocs_count = 0;
// Is processor pe_list[i] in initial "dest" descriptor ?
      int j;
      for (j = dest.pe_voisins_.size_array()-1; j >= 0; j--)
        if (dest.pe_voisins_[j] == pe_list[i])
          break;
      const int pe = pe_list[i];
// Insert items to send and items to recv from dest
      j = find_in_array(dest.pe_voisins_, pe);
      if (j >= 0)
        {
          const int count_items_single = dest.nb_items_to_items_[j];
          nx += count_items_single;
// take only single items to send
          tmp.resize_array(0);
          tmp.resize_array(count_items_single);
          for (int k = 0; k < count_items_single; k++)
            tmp[k] = dest.items_to_send_(j, k);
          append_blocs(x_data, tmp);
          ny += dest.items_to_recv_.get_list_size(j);
          dest.items_to_recv_.copy_list_to_array(j, tmp);
          append_blocs(y_data, tmp);
        }
// Insert items to send and items to recv from src, with multiplier
      j = find_in_array(src.pe_voisins_, pe);
      if (j >= 0)
        {
          const int count_items_single = src.nb_items_to_items_[j];
          nx += count_items_single * multiplier;
// take only single items to send
          tmp.resize_array(0);
          tmp.resize_array(count_items_single);
          for (int k = 0; k < count_items_single; k++)
            tmp[k] = src.items_to_send_(j, k);
          append_items(x_data, tmp, offset, multiplier);
          ny += src.items_to_recv_.get_list_size(j) * multiplier;
          src.items_to_recv_.copy_list_to_array(j, tmp);
          append_items(y_data, tmp, offset, multiplier);
        }
      const int single_items_count = nx;
// Insert blocs to send and blocs to recv from dest
      j = find_in_array(dest.pe_voisins_, pe);
      if (j >= 0)
        {
          const int count_items_tot = dest.items_to_send_.get_list_size(j);
          const int count_items_single = dest.nb_items_to_items_[j];
          nx += count_items_tot - count_items_single;
          tmp.resize_array(0);
          tmp.resize_array(count_items_tot - count_items_single);
          for (int k = count_items_single; k < count_items_tot; k++)
            tmp[k - count_items_single] = dest.items_to_send_(j, k);
          append_blocs(x_data, tmp);
          nz += dest.blocs_to_recv_.get_list_size(j);
          dest.blocs_to_recv_.copy_list_to_array(j, tmp);
          append_blocs(z_data, tmp);
          blocs_count += dest.blocs_items_count_[j];
        }
// Insert blocs to send and blocs to recv from src, with multiplier
      j = find_in_array(src.pe_voisins_, pe);
      if (j >= 0)
        {
          const int count_items_tot = src.items_to_send_.get_list_size(j);
          const int count_items_single = src.nb_items_to_items_[j];
          nx += (count_items_tot - count_items_single) * multiplier;
          tmp.resize_array(0);
          tmp.resize_array(count_items_tot - count_items_single);
          for (int k = count_items_single; k < count_items_tot; k++)
            tmp[k - count_items_single] = src.items_to_send_(j, k);
          append_items(x_data, tmp, offset, multiplier);
          nz += src.blocs_to_recv_.get_list_size(j);
          src.blocs_to_recv_.copy_list_to_array(j, tmp);
          append_blocs(z_data, tmp, offset, multiplier);
          blocs_count += src.blocs_items_count_[j] * multiplier;
        }
      x_sz.append_array(nx);
      y_sz.append_array(ny);
      z_sz.append_array(nz);
      new_blocs_items_count[i] = blocs_count;
      new_nb_items_to_items[i] = single_items_count;
    }
  dest.items_to_send_.set_list_sizes(x_sz);
  dest.items_to_send_.set_data(x_data);
  dest.items_to_recv_.set_list_sizes(y_sz);
  dest.items_to_recv_.set_data(y_data);
  dest.blocs_to_recv_.set_list_sizes(z_sz);
  dest.blocs_to_recv_.set_data(z_data);
  dest.pe_voisins_ = pe_list;
  dest.blocs_items_count_ = new_blocs_items_count;
  dest.nb_items_to_items_ = new_nb_items_to_items;
}
References TRUSTArray< _TYPE_ >::append_array(), append_blocs(), append_items(), array_trier_retirer_doublons(), MD_Vector_std::blocs_items_count_, MD_Vector_std::blocs_to_recv_, Static_Int_Lists::copy_list_to_array(), find_in_array(), Static_Int_Lists::get_list_size(), MD_Vector_std::items_to_recv_, MD_Vector_std::items_to_send_, MD_Vector_std::nb_items_to_items_, MD_Vector_std::pe_voisins_, TRUSTArray< _TYPE_ >::resize_array(), Static_Int_Lists::set_data(), Static_Int_Lists::set_list_sizes(), TRUSTArray< _TYPE_ >::set_smart_resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by MD_Vector_composite::add_part().
append_items()
static void append_items (ArrOfInt & dest, const ArrOfInt & src, int offset = 0, int multiplier = 1) static
Definition at line 79 of file MD_Vector_composite.cpp.
{
  int i = dest.size_array();
  const int n = src.size_array();
  dest.resize_array(i + n * multiplier);
  for (int j = 0; j < n; j++)
    {
      int x = offset + src[j] * multiplier;
      for (int k = 0; k < multiplier; k++)
        dest[i++] = x++;
    }
}
References TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by append_global_md().
find_in_array()
static int find_in_array (const ArrOfInt & a, int x) static
returns i such that a[i]==x, or -1 if x is not found
Definition at line 102 of file MD_Vector_composite.cpp.
{
  int n;
  for (n = a.size_array() - 1; n >= 0; n--)
    if (a[n] == x)
      break;
  return n;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by append_global_md().
Variable Documentation
MD_Vector_compositebases
const Type_info* MD_Vector_compositebases[1] ={ &(MD_Vector_base2 ::info_obj)}
Definition at line 22 of file MD_Vector_composite.cpp.