TRUST: src/Kernel/Math/MD_Vector_std.cpp File Reference
src/Kernel/Math/MD_Vector_std.cpp File Reference
#include <MD_Vector_std.h>
#include <DoubleVect.h>
#include <IntVect.h>
#include <Schema_Comm_Vecteurs.h>
#include <Echange_EV_Options.h>
#include <communications.h>
#include <Param.h>
Functions
void initialize_comm_ (const MD_Vector_std &md, const Echange_EV_Options &opt, Schema_Comm_Vecteurs &comm, int line_size, int is_double)
void read_from_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void write_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void add_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void max_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void mincol1_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void read_from_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void write_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void add_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfDouble &vect, Schema_Comm_Vecteurs &buffers)
void read_from_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void write_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void add_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void max_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void mincol1_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void read_from_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void write_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
void add_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, ArrOfInt &vect, Schema_Comm_Vecteurs &buffers)
Variables
const Type_info * MD_Vector_stdbases [1] = { &(MD_Vector_base2 ::info_obj)}
Function Documentation
void add_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 652 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) += *(bufptr++);
            }
        }
    }
}
void add_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 1116 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) += *(bufptr++);
            }
        }
    }
}
void add_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 413 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::process_recv_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) += *(bufptr++);
            }
        }
    }
}
void add_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 877 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) += *(bufptr++);
            }
        }
    }
}
void initialize_comm_ (const MD_Vector_std & md, const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, int line_size, int is_double) [inline]
Definition at line 265 of file MD_Vector_std.cpp.
References Schema_Comm_Vecteurs::add_recv_area_double(), Schema_Comm_Vecteurs::add_recv_area_int(), Schema_Comm_Vecteurs::add_send_area_double(), Schema_Comm_Vecteurs::add_send_area_int(), MD_Vector_std::blocs_items_count_, MD_Vector_std::blocs_to_recv_, Static_Int_Lists::get_data(), Static_Int_Lists::get_list_size(), Echange_EV_Options::get_op(), MD_Vector_std::items_to_recv_, MD_Vector_std::items_to_send_, MD_Vector_std::pe_voisins_, ArrOfInt::size_array(), and Echange_EV_Options::SYNC.
Referenced by MD_Vector_std::initialize_comm().
{
  const int reverse = (opt.get_op() != Echange_EV_Options::SYNC);
  const int have_items_to_recv = (md.items_to_recv_.get_data().size_array() > 0);
  const int have_blocs_to_recv = (md.blocs_to_recv_.get_data().size_array() > 0);
  const int nprocs = md.pe_voisins_.size_array();
  for (int i = 0; i < nprocs; i++)
    {
      const int pe = md.pe_voisins_[i];
      int sz1 = md.items_to_send_.get_list_size(i);
      int sz2 = 0;
      if (have_items_to_recv)
        sz2 = md.items_to_recv_.get_list_size(i);
      if (have_blocs_to_recv)
        sz2 += md.blocs_items_count_[i];
      if (reverse)
        {
// Schema a l'envers: lecture dans les items to recv,
// ecriture dans les items to send
          int tmp = sz1;
          sz1 = sz2;
          sz2 = tmp;
        }
      if (is_double)
        {
          comm.add_send_area_double(pe, sz1 * line_size);
          comm.add_recv_area_double(pe, sz2 * line_size);
        }
      else
        {
          comm.add_send_area_int(pe, sz1 * line_size);
          comm.add_recv_area_int(pe, sz2 * line_size);
        }
    }
}
void max_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 457 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::process_recv_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              double dest = *vectptr;
              double src  = *(bufptr++);
              *(vectptr++) = (dest > src) ? dest : src;
            }
        }
    }
}
void max_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 921 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              int dest = *vectptr;
              int src  = *(bufptr++);
              *(vectptr++) = (dest > src) ? dest : src;
            }
        }
    }
}
void mincol1_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 503 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::process_recv_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
// Copy whole line if first line is greater than destination
          assert(bufptr + line_size * bloc_size - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < bloc_size; j++)
            {
              double dest = *vectptr;
              double src  = *bufptr;
              if (src < dest)
                {
                  for (int k = line_size; k; k--)
                    *(vectptr++) = *(bufptr++);
                }
              else
                {
                  vectptr += line_size;
                  bufptr += line_size;
                }
            }
        }
    }
}
void mincol1_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 967 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
// Copy whole line if first line is greater than destination
          assert(bufptr + line_size * bloc_size - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < bloc_size; j++)
            {
              int dest = *vectptr;
              int src  = *bufptr;
              if (src < dest)
                {
                  for (int k = line_size; k; k--)
                    *(vectptr++) = *(bufptr++);
                }
              else
                {
                  vectptr += line_size;
                  bufptr += line_size;
                }
            }
        }
    }
}
void read_from_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 1022 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(bufptr++) = *(vectptr++);
            }
        }
    }
}
void read_from_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 558 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::prepare_send_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(bufptr++) = *(vectptr++);
            }
        }
    }
}
void read_from_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 325 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::prepare_send_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(bufptr++) = *(vectptr++);
            }
        }
    }
}
void read_from_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 789 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(bufptr++) = *(vectptr++);
            }
        }
    }
}
void write_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 1069 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) = *(bufptr++);
            }
        }
    }
}
void write_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 605 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::process_recv_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) = *(bufptr++);
            }
        }
    }
}
void write_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfDouble & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 369 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_double(), ArrOfDouble::size_array(), and ArrOfInt::size_array().
Referenced by MD_Vector_std::process_recv_data().
{
  assert(line_size > 0);
  double *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfDouble& buffer = buffers.get_next_area_double(voisins[i_voisin], nb_elems);
      double * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          double *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) = *(bufptr++);
            }
        }
    }
}
void write_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, ArrOfInt & vect, Schema_Comm_Vecteurs & buffers) [inline]
< Index in list.get_data()
Definition at line 833 of file MD_Vector_std.cpp.
References ArrOfInt::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_int(), and ArrOfInt::size_array().
{
  assert(line_size > 0);
  int *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin+1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      ArrOfInt& buffer = buffers.get_next_area_int(voisins[i_voisin], nb_elems);
      int * bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc+bloc_size) * line_size <= vect.size_array());
          int *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              *(vectptr++) = *(bufptr++);
            }
        }
    }
}
Variable Documentation
const Type_info* MD_Vector_stdbases[1] = { &(MD_Vector_base2 ::info_obj)}
Definition at line 33 of file MD_Vector_std.cpp.