TRUST: src/Kernel/Math/MD_Vector_std_tools.tpp File Reference
MD_Vector_std_tools.tpp File Reference
Macros
#define MD_Vector_std_tools_TPP_included
Enumerations
enum class VECT_ITEMS_TYPE { READ , WRITE , ADD , MAX }
enum class VECT_BLOCS_TYPE { READ , WRITE , ADD }
Functions
template<typename _TYPE_ , VECT_ITEMS_TYPE _ITEM_TYPE_>
void vect_items_generic (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void read_from_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void write_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void add_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void max_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void mincol1_to_vect_items (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ , VECT_BLOCS_TYPE _ITEM_TYPE_>
void vect_blocs_generic (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void read_from_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void write_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
template<typename _TYPE_ >
void add_to_vect_blocs (const int line_size, const ArrOfInt &voisins, const Static_Int_Lists &list, const ArrOfInt &nb_items_par_voisin, TRUSTArray< _TYPE_ > &vect, Schema_Comm_Vecteurs &buffers)
Macro Definition Documentation
MD_Vector_std_tools_TPP_included
#define MD_Vector_std_tools_TPP_included
Definition at line 17 of file MD_Vector_std_tools.tpp.
Enumeration Type Documentation
VECT_BLOCS_TYPE
enum class VECT_BLOCS_TYPE strong
Enumerator
READ
WRITE
ADD
Definition at line 20 of file MD_Vector_std_tools.tpp.
{ READ , WRITE , ADD };
VECT_ITEMS_TYPE
enum class VECT_ITEMS_TYPE strong
Enumerator
READ
WRITE
ADD
MAX
Definition at line 19 of file MD_Vector_std_tools.tpp.
{ READ , WRITE , ADD , MAX };
Function Documentation
add_to_vect_blocs()
template<typename _TYPE_ > void add_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 206 of file MD_Vector_std_tools.tpp.
{
  vect_blocs_generic<_TYPE_,VECT_BLOCS_TYPE::ADD>(line_size,voisins,list,nb_items_par_voisin,vect,buffers);
}
add_to_vect_items()
template<typename _TYPE_ > void add_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 88 of file MD_Vector_std_tools.tpp.
{
  vect_items_generic<_TYPE_,VECT_ITEMS_TYPE::ADD>(line_size,voisins,list,vect,buffers);
}
Referenced by MD_Vector_std::process_recv_data_template().
max_to_vect_items()
template<typename _TYPE_ > void max_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 94 of file MD_Vector_std_tools.tpp.
{
  vect_items_generic<_TYPE_,VECT_ITEMS_TYPE::MAX>(line_size,voisins,list,vect,buffers);
}
Referenced by MD_Vector_std::process_recv_data_template().
mincol1_to_vect_items()
template<typename _TYPE_ > void mincol1_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
< Index in list.get_data()
Definition at line 100 of file MD_Vector_std_tools.tpp.
{
  assert(line_size > 0);
  _TYPE_ *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin + 1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      TRUSTArray<_TYPE_>& buffer = buffers.get_next_area_template < _TYPE_ >(voisins[i_voisin], nb_elems);
      _TYPE_ *bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc + bloc_size) * line_size <= vect.size_array());
          _TYPE_ *vectptr = data + premier_item_bloc * line_size;
// Copy whole line if first line is greater than destination
          assert(bufptr + line_size * bloc_size - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < bloc_size; j++)
            {
              _TYPE_ dest = *vectptr;
              _TYPE_ src = *bufptr;
              if (src < dest)
                {
                  for (int k = line_size; k; k--)
                    *(vectptr++) = *(bufptr++);
                }
              else
                {
                  vectptr += line_size;
                  bufptr += line_size;
                }
            }
        }
    }
}
References TRUSTArray< _TYPE_ >::addr(), Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_template(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by MD_Vector_std::process_recv_data_template().
read_from_vect_blocs()
template<typename _TYPE_ > void read_from_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 194 of file MD_Vector_std_tools.tpp.
{
  vect_blocs_generic<_TYPE_,VECT_BLOCS_TYPE::READ>(line_size,voisins,list,nb_items_par_voisin,vect,buffers);
}
Referenced by MD_Vector_std::prepare_send_data_template().
read_from_vect_items()
template<typename _TYPE_ > void read_from_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 76 of file MD_Vector_std_tools.tpp.
{
  vect_items_generic<_TYPE_,VECT_ITEMS_TYPE::READ>(line_size,voisins,list,vect,buffers);
}
Referenced by MD_Vector_std::prepare_send_data_template().
vect_blocs_generic()
template<typename _TYPE_ , VECT_BLOCS_TYPE _ITEM_TYPE_> void vect_blocs_generic (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
< Index in list.get_data()
Definition at line 147 of file MD_Vector_std_tools.tpp.
{
  static constexpr bool IS_READ = (_ITEM_TYPE_ == VECT_BLOCS_TYPE::READ), IS_WRITE = (_ITEM_TYPE_ == VECT_BLOCS_TYPE::WRITE), IS_ADD = (_ITEM_TYPE_ == VECT_BLOCS_TYPE::ADD);
  assert(line_size > 0);
  _TYPE_ *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin + 1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = nb_items_par_voisin[i_voisin] * line_size;
      TRUSTArray<_TYPE_>& buffer = buffers.get_next_area_template < _TYPE_ >(voisins[i_voisin], nb_elems);
      _TYPE_ *bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
// For blocs, the array contains begin_bloc, end_bloc, begin_bloc, end_bloc...
          const int dernier_item_bloc = items_to_process[idx++];
          const int bloc_size = dernier_item_bloc - premier_item_bloc;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc + bloc_size) * line_size <= vect.size_array());
          _TYPE_ *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              if (IS_READ) *(bufptr++) = *(vectptr++);
              else if (IS_WRITE) *(vectptr++) = *(bufptr++);
              else if (IS_ADD) *(vectptr++) += *(bufptr++);
              else
                {
                  Cerr << "Unknown VECT_BLOCS_TYPE enum !" << finl;
                  throw;
                }
            }
        }
    }
}
References ADD, TRUSTArray< _TYPE_ >::addr(), Cerr, finl, Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_template(), READ, TRUSTArray< _TYPE_ >::size_array(), and WRITE.
vect_items_generic()
template<typename _TYPE_ , VECT_ITEMS_TYPE _ITEM_TYPE_> void vect_items_generic (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
< Index in list.get_data()
Definition at line 24 of file MD_Vector_std_tools.tpp.
{
  static constexpr bool IS_READ = (_ITEM_TYPE_ == VECT_ITEMS_TYPE::READ), IS_WRITE = (_ITEM_TYPE_ == VECT_ITEMS_TYPE::WRITE),
                        IS_ADD = (_ITEM_TYPE_ == VECT_ITEMS_TYPE::ADD), IS_MAX = (_ITEM_TYPE_ == VECT_ITEMS_TYPE::MAX);
  assert(line_size > 0);
  _TYPE_ *data = vect.addr();
  const int *items_to_process = list.get_data().addr();
  int idx = 0; //!< Index in list.get_data()
  const ArrOfInt& index = list.get_index();
  const int nb_voisins = list.get_nb_lists();
  for (int i_voisin = 0; i_voisin < nb_voisins; i_voisin++)
    {
// Indice dans list.get_data() de la fin de la liste d'items/blocs pour ce voisin:
      const int idx_end_of_list = index[i_voisin + 1];
// Nombre d'elements de tableau a envoyer/recevoir de ce voisin
      const int nb_elems = (idx_end_of_list - idx) * line_size;
      TRUSTArray<_TYPE_>& buffer = buffers.get_next_area_template < _TYPE_ >(voisins[i_voisin], nb_elems);
      _TYPE_ *bufptr = buffer.addr();
      assert(idx_end_of_list <= list.get_data().size_array());
      while (idx < idx_end_of_list)
        {
// Indice de l'item geometrique a copier (ou du premier item du bloc)
          int premier_item_bloc = items_to_process[idx++];
          const int bloc_size = 1;
// Adresse des elements a copier dans le vecteur
          assert(premier_item_bloc >= 0 && bloc_size > 0 && (premier_item_bloc + bloc_size) * line_size <= vect.size_array());
          _TYPE_ *vectptr = data + premier_item_bloc * line_size;
          const int n = line_size * bloc_size;
          assert(bufptr + n - buffer.addr() <= buffer.size_array());
          for (int j = 0; j < n; j++)
            {
              if (IS_READ) *(bufptr++) = *(vectptr++);
              else if (IS_WRITE) *(vectptr++) = *(bufptr++);
              else if (IS_ADD) *(vectptr++) += *(bufptr++);
              else if (IS_MAX)
                {
                  _TYPE_ dest = *vectptr;
                  _TYPE_ src = *(bufptr++);
                  *(vectptr++) = (dest > src) ? dest : src;
                }
              else
                {
                  Cerr << "Unknown VECT_ITEMS_TYPE enum !" << finl;
                  throw;
                }
            }
        }
    }
}
References ADD, TRUSTArray< _TYPE_ >::addr(), Cerr, finl, Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), Static_Int_Lists::get_nb_lists(), Schema_Comm_Vecteurs::get_next_area_template(), MAX, READ, TRUSTArray< _TYPE_ >::size_array(), and WRITE.
write_to_vect_blocs()
template<typename _TYPE_ > void write_to_vect_blocs (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, const ArrOfInt & nb_items_par_voisin, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 200 of file MD_Vector_std_tools.tpp.
{
  vect_blocs_generic<_TYPE_,VECT_BLOCS_TYPE::WRITE>(line_size,voisins,list,nb_items_par_voisin,vect,buffers);
}
Referenced by MD_Vector_std::process_recv_data_template().
write_to_vect_items()
template<typename _TYPE_ > void write_to_vect_items (const int line_size, const ArrOfInt & voisins, const Static_Int_Lists & list, TRUSTArray< _TYPE_ > & vect, Schema_Comm_Vecteurs & buffers) inline
Definition at line 82 of file MD_Vector_std_tools.tpp.
{
  vect_items_generic<_TYPE_,VECT_ITEMS_TYPE::WRITE>(line_size,voisins,list,vect,buffers);
}
Referenced by MD_Vector_std::process_recv_data_template().