TRUST: src/Kernel/Utilitaires/Memoire.h File Reference
src/Kernel/Utilitaires/Memoire.h File Reference
#include <assert.h>
#include <arch.h>
#include <Memoire_ptr.h>
Classes
class Memoire
La memoire de Trio-U.
Functions
Sortie & operator<< (Sortie &, const Memoire &)
Operateur d'affichage d'un etat de la memoire mem sur le flot de sortie os.
Function Documentation
Sortie& operator<< (Sortie & os, const Memoire & mem)
Operateur d'affichage d'un etat de la memoire mem sur le flot de sortie os.
Returns:
Sortie& le flot de sortie modifie
Signification:
Contraintes:
Definition at line 587 of file Memoire.cpp.
References compteur, Memoire::data, finl, Sortie::flush(), Objet_U::le_nom(), Objet_U::le_type(), Memoire_ptr::libre(), max_sz_mem, min_sz_mem, Memoire::objet_u(), ref_cast, ArrOfDouble::ref_count(), ArrOfInt::ref_count(), IntVect::size(), Memoire::size, ArrOfDouble::size_array(), ArrOfInt::size_array(), sub_type, and Objet_U::taille_memoire().
{
  int i;
  int total=0;
  int tmp=0;
  int tmp1=0;
  for(i=0; i<mem.size; i++)
    if(! mem.data[i].libre()) tmp++;
  os << "\n il y a " << mem.size << " cases memoires";
  os << "\n dont " << tmp << " ==(const char*)" << compteur << " sont occupees" << finl;
  for(i=0; i<mem.size; i++)
    if(! mem.data[i].libre())
      {
        os << i << " ";
        const Objet_U& obj=mem.objet_u(i);
        os << " :: ";
        os << "TYPE :" << obj.le_type();
        if(sub_type(Nom,obj)) os << " NOM : " << obj.le_nom() ;
        os << " adresse : " << (long)(&(obj));
        if(sub_type(ArrOfInt,obj))
          {
            const ArrOfInt& toto = ref_cast(ArrOfInt,obj);
            tmp = obj.taille_memoire() +
                  (int) ((toto.size_array()*sizeof(int))/toto.ref_count());
            os << " TAILLE ArrOfInt : " << tmp<< " octets ";
            if(sub_type(IntVect,obj))
              {
                const IntVect& titi = ref_cast(IntVect,obj);
                tmp1 = obj.taille_memoire() +
                       (int) ((titi.size()*sizeof(int))/titi.ref_count());
                os << " dont : " << (tmp-tmp1) << " octets virtuels ";
              }
            os << "\n";
          }
        else
          {
            if(sub_type(ArrOfDouble,obj))
              {
                const ArrOfDouble& toto = ref_cast(ArrOfDouble,obj);
                tmp = obj.taille_memoire() +
                      (int) ((toto.size_array()*sizeof(double))/toto.ref_count());
                os << " TAILLE ArrOfDouble : " << tmp<< " octets ";
                /* PL: Plante en P1Bulle donc je commente
                   if(sub_type(DoubleVect,obj)){
                   const DoubleVect& titi = ref_cast(DoubleVect,obj);
                   tmp1 = obj.taille_memoire() +
                   (int) ((titi.size()*sizeof(double))/titi.ref_count());
                   os << " dont : " << (tmp-tmp1) << " octets virtuels ";
                   } */
                os << "\n";
              }
            else
              {
                /*
                  if(sub_type(Matrice_Morse_Sym,obj)){
                  const Matrice_Morse_Sym& toto = ref_cast(Matrice_Morse_Sym,obj);
                  tmp = obj.taille_memoire() +
                  (int) (toto.nb_lignes()*sizeof(int)) +
                  (int) ((toto.nb_coeff()+1)*sizeof(int)) +
                  (int) (toto.nb_coeff()*sizeof(double));
                  os << " TAILLE Matrice_Morse_Sym : " << tmp<< " octets ";
                  os << "\n";
                  }
                  else
                */
                os << " TAILLE : " << (tmp=obj.taille_memoire())<< " octets \n ";
              }
          }
        total += tmp;
        os.flush();
      }
  os << "Taille memoire max: " <<  max_sz_mem << finl;
  os << "Taille memoire min: " <<  min_sz_mem << finl;
  os << "Taille memoire occupee en Mo: " <<  (max_sz_mem-min_sz_mem)/1024/1024 << finl;
  return os << "Occupation taille memoire totale en Mo: " << total/1024/1024 << finl;
}