TRUST: src/ThHyd/Dilatable/Common/Modifier_pour_fluide_dilatable.cpp File Reference
src/ThHyd/Dilatable/Common/Modifier_pour_fluide_dilatable.cpp File Reference
#include <Modifier_pour_fluide_dilatable.h>
#include <Fluide_Dilatable_base.h>
#include <Zone_VF.h>
Functions
static void multiplier_ou_diviser (DoubleVect &x, const DoubleVect &y, int diviser)
void multiplier_diviser_rho (DoubleVect &tab, const Fluide_Dilatable_base &le_fluide, int diviser)
void multiplier_par_rho_si_dilatable (DoubleVect &val, const Milieu_base &mil)
multiplie le tableau val par la masse volumique si le fluide est dilatable.
Le tableau val peut avoir diverses localisations (determinees a partir de get_md_vector())
et peut etre de type DoubleTab avec des dimension(i>0) quelconques (plusieurs composantes)
void diviser_par_rho_si_dilatable (DoubleVect &val, const Milieu_base &mil)
Idem que multiplier_par_rho_si_dilatable mais on divise par rho.
Function Documentation
void diviser_par_rho_si_dilatable (DoubleVect & val, const Milieu_base & mil)
Idem que multiplier_par_rho_si_dilatable mais on divise par rho.
Definition at line 114 of file Modifier_pour_fluide_dilatable.cpp.
References Cerr, Process::exit(), finl, multiplier_diviser_rho(), ref_cast, and sub_type.
Referenced by Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), and Op_Conv_PolyMAC_iterateur_base::calculer_pour_post().
{
  if (sub_type(Fluide_Dilatable_base,mil)) multiplier_diviser_rho(val,ref_cast(Fluide_Dilatable_base,mil), 1 /* diviser */);
  else
    {
      Cerr << "What ?? The method diviser_par_rho_si_dilatable should not be called since your fluid is not dilatable !!" << finl;
      Process::exit();
    }
}
void multiplier_diviser_rho (DoubleVect & tab, const Fluide_Dilatable_base & le_fluide, int diviser)
Definition at line 37 of file Modifier_pour_fluide_dilatable.cpp.
References Cerr, Zone_VF::creer_tableau_faces_bord(), IntTab::dimension(), Zone_VF::elem_faces(), Process::exit(), finl, DoubleVect::get_md_vector(), ArrOfDouble::inject_array(), Milieu_base::masse_volumique(), Zone_VF::md_vector_faces(), Zone_VF::md_vector_faces_bord(), multiplier_ou_diviser(), Array_base::NOCOPY_NOINIT, ref_cast, Milieu_base::rho, DoubleVect::size(), Deriv_Champ_Inc_base::valeur(), Champ_Proto::valeurs(), Fluide_Dilatable_base::vitesse(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by diviser_par_rho_si_dilatable(), Champ_Generique_modifier_pour_QC::get_champ(), and multiplier_par_rho_si_dilatable().
{
  const Zone_VF& zvf = ref_cast(Zone_VF,le_fluide.vitesse().valeur().zone_dis_base());
// Descripteurs des tableaux aux elements et aux faces:
  const Zone& zone = zvf.zone();
  const MD_Vector& md_elem = zone.les_elems().get_md_vector();
  const MD_Vector& md_faces = zvf.md_vector_faces();
  const MD_Vector& md_faces_bord = zvf.md_vector_faces_bord();
  if (tab.get_md_vector() == md_faces_bord)
    {
      const DoubleTab& rho = ref_cast(Fluide_Dilatable_base,le_fluide).rho_discvit();
      DoubleVect rho_bord;
// B.M. je cree une copie sinon il faut truander les tests sur les tailles dans multiply_any_shape
// ou creer un DoubleTab qui pointe sur rho...
      zvf.creer_tableau_faces_bord(rho_bord,Array_base::NOCOPY_NOINIT);
      rho_bord.inject_array(rho,rho_bord.size());
      multiplier_ou_diviser(tab,rho_bord,diviser);
      return;
    }
  if (tab.get_md_vector() == md_faces)
    {
      const DoubleTab& rho_faces = ref_cast(Fluide_Dilatable_base,le_fluide).rho_discvit();
      multiplier_ou_diviser(tab,rho_faces,diviser);
      return;
    }
  const DoubleTab& rho = le_fluide.masse_volumique().valeurs();
  if (tab.get_md_vector() == md_elem && rho.get_md_vector() == md_elem)
    {
      multiplier_ou_diviser(tab,rho,diviser);
      return;
    }
  if (tab.get_md_vector() == md_elem && rho.get_md_vector() == md_faces)
    {
// Il faut calculer rho aux elements
      const DoubleTab& tab_rho = le_fluide.masse_volumique().valeurs();
      DoubleVect rho_elem;
      zone.creer_tableau_elements(rho_elem, Array_base::NOCOPY_NOINIT);
      const int nb_elem_tot = zone.nb_elem_tot();
      const IntTab& elem_faces = zvf.elem_faces();
      const int nfe = elem_faces.dimension(1);
      const double facteur = 1. / nfe;
      for (int elem = 0; elem < nb_elem_tot; elem++)
        {
          double x = 0.;
          for (int face=0; face < nfe; face++)
            {
              int f = elem_faces(elem, face);
              x += tab_rho[f];
            }
          rho_elem[elem] = x * facteur;
        }
      multiplier_ou_diviser(tab,rho_elem,diviser);
      return;
    }
  Cerr << "Error in Modifier_pour_fluide_dilatable.cpp: multiplier_rho. Invalid discretization of tab and rho." << finl;
  Process::exit();
}
static void multiplier_ou_diviser (DoubleVect & x, const DoubleVect & y, int diviser) [static]
Definition at line 28 of file Modifier_pour_fluide_dilatable.cpp.
References DoubleVect::echange_espace_virtuel(), tab_divide_any_shape(), tab_multiply_any_shape(), and VECT_REAL_ITEMS.
Referenced by multiplier_diviser_rho().
{
  if (!diviser) tab_multiply_any_shape(x, y ,VECT_REAL_ITEMS);
  else tab_divide_any_shape(x, y ,VECT_REAL_ITEMS);
  x.echange_espace_virtuel();
// Debog::verifier("multiplier_ou_diviser x/y apres x:",x);
}
void multiplier_par_rho_si_dilatable (DoubleVect & val, const Milieu_base & mil)
multiplie le tableau val par la masse volumique si le fluide est dilatable.
Le tableau val peut avoir diverses localisations (determinees a partir de get_md_vector())
et peut etre de type DoubleTab avec des dimension(i>0) quelconques (plusieurs composantes)
Definition at line 103 of file Modifier_pour_fluide_dilatable.cpp.
References Cerr, Process::exit(), finl, multiplier_diviser_rho(), ref_cast, and sub_type.
Referenced by Source_QC_QDM_Gen::ajouter(), Source_Fluide_Dilatable_Face< DERIVED_T >::ajouter_impl(), Op_Conv_VEF_base::calculer_dt_stab(), and Op_Conv_VEF_base::calculer_pour_post().
{
  if (sub_type(Fluide_Dilatable_base,mil)) multiplier_diviser_rho(val,ref_cast(Fluide_Dilatable_base,mil), 0 /* multiplier */);
  else
    {
      Cerr << "What ?? The method multiplier_par_rho_si_dilatable should not be called since your fluid is not dilatable !!" << finl;
      Process::exit();
    }
}