TRUST: src/MAIN/mon_main.cpp File Reference
mon_main.cpp File Reference
#include <mon_main.h>
#include <LecFicDiffuse_JDD.h>
#include <instancie_appel.h>
#include <SFichier.h>
#include <Comm_Group_MPI.h>
#include <PE_Groups.h>
#include <Journal.h>
#include <stdio.h>
#include <Statistiques.h>
#include <communications.h>
#include <petsc_for_kernel.h>
#include <stat_counters.h>
#include <info_atelier.h>
#include <unistd.h>
#include <catch_and_trace.h>
#include <instancie_appel_c.h>
Functions
void declare_stat_counters ()
< Pour chdir for other compiler
void end_stat_counters ()
static int init_petsc (True_int argc, char **argv, int with_mpi, int &trio_began_mpi_)
static int init_parallel_mpi (Deriv_Comm_Group &groupe_trio)
Variables
Stat_Counter_Id temps_total_execution_counter_
Stat_Counter_Id initialisation_calcul_counter_
Function Documentation
declare_stat_counters()
void declare_stat_counters ()
< Pour chdir for other compiler
< Appels sur chaque process
< Appel uniquement sur maitre, appels plus souvents car bufferise
Definition at line 87 of file stat_counters.cpp.
{
// Creation de l'objet statistiques
  if (les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe)
    {
      Cerr << "Error : declare_stat_counters() has already been called " << finl;
      assert(0);
      return;
    }
  les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe
    = new Statistiques;
// Niveau de debug par defaut
  statistiques().set_debug_level(9);
// Temps total d'execution
// Ce compteur est declare en premier (on calcule les pourcentages)
// par rapport a celui-la dans Statistiques::dump()
  temps_total_execution_counter_ = statistiques().new_counter(1, "Temps total", 0);
// Initialisation du calcul (jusqu'a l'entree dans Resoudre)
  initialisation_calcul_counter_ = statistiques().new_counter(1, "Preparer calcul", 0);
// Boucle de calcul du pas de temps dans Resoudre::interpreter
  timestep_counter_ = statistiques().new_counter(1, "Resoudre (timestep loop)", 0);
// Appels a SolveurSys::resoudre_systeme
// quantity = nombre total d'iterations des solveurs
  solv_sys_counter_ = statistiques().new_counter(1, "SolveurSys::resoudre_systeme", 0);
  solv_sys_petsc_counter_ = statistiques().new_counter(1, "Solveurpetsc::resoudre_systeme", 0);
  diffusion_implicite_counter_ = statistiques().new_counter(1, "Equation_base::Gradient_conjugue_diff_impl", 0);
// Appels a differents operateurs:
  dt_counter_ = statistiques().new_counter(1, "Operateur::calculer_pas_de_temps", 0);
  nut_counter_ = statistiques().new_counter(1, "ModeleTurbulence*::mettre_a_jour", 0);
  convection_counter_ = statistiques().new_counter(1, "Operateur_Conv::ajouter/calculer", 0);
  diffusion_counter_ = statistiques().new_counter(1, "Operateur_Diff::ajouter/calculer", 0);
  decay_counter_ = statistiques().new_counter(1, "Operateur_Decr::ajouter/calculer", 0);
  gradient_counter_ = statistiques().new_counter(1, "Operateur_Grad::ajouter/calculer", 0);
  divergence_counter_ = statistiques().new_counter(1, "Operateur_Div::ajouter/calculer", 0);
  source_counter_ = statistiques().new_counter(1, "Source::ajouter/calculer", 0);
// Postraitement
  postraitement_counter_ = statistiques().new_counter(1, "Pb_base::postraiter", 0);
  sauvegarde_counter_ = statistiques().new_counter(1, "Probleme_base::sauver", 0);
  temporary_counter_ = statistiques().new_counter(1, "temporary", 0);
// Assemblage de la matrice
  assemblage_sys_counter_ = statistiques().new_counter(1, "Assembleur::assembler", 0);
  update_vars_counter_ = statistiques().new_counter(1, "Schema_Implicite_4eqs::update_vars", 0);
  update_fields_counter_ = statistiques().new_counter(1, "Probleme_Diphasique_base::updateGivenFields", 0);
  mettre_a_jour_counter_  = statistiques().new_counter(1, "::mettre_a_jour", 0);
// Divers
  divers_counter_ = statistiques().new_counter(1, "Divers", 0);
// Marqueurs pouvant etre places n'importe ou:
  m1 = statistiques().new_counter(1, "m1", 0);
  m2 = statistiques().new_counter(1, "m2", 0);
  m3 = statistiques().new_counter(1, "m3", 0);
// Problemes
  probleme_fluide_ = statistiques().new_counter(3 /* Level */, "pb_fluide", 0 /* Group */);
  probleme_combustible_ = statistiques().new_counter(3 /* Level */, "pb_combustible", 0 /* Group */);
// Appels a DoubleVect::echange_espace_virtuel()
  echange_vect_counter_ = statistiques().new_counter(2, "DoubleVect/IntVect::echange_espace_virtuel", 0, 1);
  mpi_sendrecv_counter_  = statistiques().new_counter(2, "MPI_send_recv", "MPI_sendrecv", 1);
  mpi_send_counter_      = statistiques().new_counter(2, "MPI_send",      "MPI_sendrecv", 1);
  mpi_recv_counter_      = statistiques().new_counter(2, "MPI_recv",      "MPI_sendrecv", 1);
  mpi_bcast_counter_     = statistiques().new_counter(2, "MPI_broadcast", "MPI_sendrecv", 1);
  mpi_alltoall_counter_  = statistiques().new_counter(2, "MPI_alltoall",  "MPI_sendrecv", 1);
  mpi_partialsum_counter_= statistiques().new_counter(2, "MPI_partialsum","MPI_allreduce", 1);
  mpi_sumdouble_counter_ = statistiques().new_counter(2, "MPI_sumdouble", "MPI_allreduce", 1);
  mpi_mindouble_counter_ = statistiques().new_counter(2, "MPI_mindouble", "MPI_allreduce", 1);
  mpi_maxdouble_counter_ = statistiques().new_counter(2, "MPI_maxdouble", "MPI_allreduce", 1);
  mpi_sumint_counter_    = statistiques().new_counter(2, "MPI_sumint",    "MPI_allreduce", 1);
  mpi_minint_counter_    = statistiques().new_counter(2, "MPI_minint",    "MPI_allreduce", 1);
  mpi_maxint_counter_    = statistiques().new_counter(2, "MPI_maxint",    "MPI_allreduce", 1);
  mpi_barrier_counter_   = statistiques().new_counter(2, "MPI_barrier",   "MPI_allreduce", 1);
// Compte le temps d'ecriture dans EcrireFicPartageXXX (gros volumes de donnees dans fichiers XYZ ou LATA)
// quantity = nombre d'octets ecrits
  IO_EcrireFicPartageMPIIO_counter_ = statistiques().new_counter(2, "MPI_File_write_all", "IO", 0); //!< Appels sur chaque process
  IO_EcrireFicPartageBin_counter_ = statistiques().new_counter(2, "write", "IO", 0); //!< Appel uniquement sur maitre, appels plus souvents car bufferise
// Execution de Scatter::interpreter
  interprete_scatter_counter_ = statistiques().new_counter(2, "Scatter", 0);
  if(GET_COMM_DETAILS)
    statistiques().allocate_communication_tracking_times();
}
References Statistiques::allocate_communication_tracking_times(), assemblage_sys_counter_, Cerr, convection_counter_, decay_counter_, diffusion_counter_, diffusion_implicite_counter_, divergence_counter_, divers_counter_, dt_counter_, echange_vect_counter_, finl, GET_COMM_DETAILS, gradient_counter_, initialisation_calcul_counter_, interprete_scatter_counter_, IO_EcrireFicPartageBin_counter_, IO_EcrireFicPartageMPIIO_counter_, les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe, m1, m2, m3, mettre_a_jour_counter_, mpi_alltoall_counter_, mpi_barrier_counter_, mpi_bcast_counter_, mpi_maxdouble_counter_, mpi_maxint_counter_, mpi_mindouble_counter_, mpi_minint_counter_, mpi_partialsum_counter_, mpi_recv_counter_, mpi_send_counter_, mpi_sendrecv_counter_, mpi_sumdouble_counter_, mpi_sumint_counter_, Statistiques::new_counter(), nut_counter_, postraitement_counter_, probleme_combustible_, probleme_fluide_, sauvegarde_counter_, Statistiques::set_debug_level(), solv_sys_counter_, solv_sys_petsc_counter_, source_counter_, statistiques(), temporary_counter_, temps_total_execution_counter_, timestep_counter_, update_fields_counter_, and update_vars_counter_.
Referenced by mon_main::dowork().
end_stat_counters()
void end_stat_counters ()
Definition at line 181 of file stat_counters.cpp.
{
  if(GET_COMM_DETAILS)
    statistiques().delete_communication_tracking_times();
  delete  les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe;
  les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe=0;
}
References Statistiques::delete_communication_tracking_times(), GET_COMM_DETAILS, les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe, and statistiques().
Referenced by mon_main::~mon_main().
init_parallel_mpi()
static int init_parallel_mpi (Deriv_Comm_Group & groupe_trio) static
Definition at line 116 of file mon_main.cpp.
{
#ifdef MPI_
  groupe_trio.typer("Comm_Group_MPI");
  Comm_Group_MPI& mpi = ref_cast(Comm_Group_MPI, groupe_trio.valeur());
// Si ca n'a pas ete fait dans Petsc, c'est ici qu'on fait MPI_Init()
  mpi.init_group_trio();
  return 1;
#else
  return 0;
#endif
}
References Comm_Group_MPI::init_group_trio(), and ref_cast.
Referenced by mon_main::init_parallel().
init_petsc()
static int init_petsc (True_int argc, char ** argv, int with_mpi, int & trio_began_mpi_) static
Definition at line 51 of file mon_main.cpp.
{
#ifdef PETSCKSP_H
  static char help[] = "TRUST may solve linear systems with Petsc library.\n\n" ;
  Nom pwd(::pwd());
// On initialise Petsc
#ifdef MPI_INIT_NEEDS_MPIRUN
  True_int flag;
  MPI_Initialized(&flag);
// si MPI initialise ou si argc>2
  if ((argc>2)||(flag))
    {
      PetscInitialize(&argc, &argv, (char*)0, help);
    }
#else
  PetscInitialize(&argc, &argv, (char*)0, help);
#endif
// Bizarrerie qui se produit sur une machine (ioulia, MPICH natif): PetscInitialize change le pwd()
// en sequentiel et si le binaire n'est pas dans le repertoire de l'etude, le pwd est perdu...
  int ierr;
  if (!with_mpi)
    {
      ierr=chdir(pwd);
      if (ierr)
        {
          Cerr << "Error on chdir into mon_main.cpp. Contact TRUST support." << finl;
          Process::exit();
        }
    }
// Equivalent de -abort_on_error (aucune erreur PETSc n'est tolere):
  PetscPushErrorHandler(PetscAbortErrorHandler,PETSC_NULL);
// Desactive le signal handler en optimise pour eviter d'etre trop bavard
// et de "masquer" les messages d'erreur TRUST:
  PetscPopSignalHandler();
  bool error_handlers = false;
  char* theValue = getenv("TRUST_ENABLE_ERROR_HANDLERS");
  if (theValue != NULL) error_handlers = true;
#ifndef NDEBUG
  error_handlers = true;
#endif
  if (error_handlers)
    {
      Cerr << "Enabling error handlers catching SIGFPE and SIGABORT and giving a trace of where the fault happened." << finl;
      install_handlers();
    }
#else
// MPI_Init pour les machines ou Petsc n'est pas
// installe: ex AIX avec MPICH: il faut que argc et argv soit passes
// correctement et pas comme dans Comm_Group_MPI::init_group_trio
// sinon message: xm_348262:  p4_error: Command-line arguments are missing: 0
#ifdef MPI_
  True_int flag;
  MPI_Initialized(&flag);
  if (!flag)
    {
      MPI_Init(&argc,&argv);
      trio_began_mpi_=1;
    }
#endif
#endif
  return 1;
}
References Cerr, Process::exit(), finl, install_handlers(), and pwd().
Referenced by mon_main::init_parallel().
Variable Documentation
initialisation_calcul_counter_
Stat_Counter_Id initialisation_calcul_counter_ extern
Definition at line 67 of file stat_counters.cpp.
Referenced by declare_stat_counters(), mon_main::dowork(), and Probleme_U::run().
temps_total_execution_counter_
Stat_Counter_Id temps_total_execution_counter_ extern
Definition at line 66 of file stat_counters.cpp.
Referenced by declare_stat_counters(), mon_main::dowork(), ICoCo::ProblemTrio::initialize(), Schema_Temps_base::mettre_a_jour(), print_statistics_analyse(), Probleme_U::run(), and Schema_Temps_base::validateTimeStep().