TRUST: src/Kernel/Utilitaires/Motcle.cpp File Reference
Motcle.cpp File Reference
#include <Motcle.h>
#include <Noms.h>
Functions
static char char_uppercase (char c)
static int strcmp_uppercase (const char *n1, const char *n2)
int operator== (const Motcle &nom, const Motcle &un_mot)
Comparaison d'un mot cle avec une chaine de caracteres.
int operator== (const Motcle &un_mot, const char *const nom)
int operator== (const char *const nom, const Motcle &un_mot)
int operator== (const Motcle &un_mot, const Nom &nom)
int operator== (const Nom &nom, const Motcle &un_mot)
int operator!= (const Motcle &nom, const Motcle &un_mot)
Comparaison d'un mot cle avec une chaine de caracteres.
int operator!= (const Motcle &un_mot, const char *const nom)
int operator!= (const char *const nom, const Motcle &un_mot)
int operator!= (const Motcle &un_mot, const Nom &nom)
int operator!= (const Nom &nom, const Motcle &un_mot)
Motcles noms_to_motcles (const Noms &a)
Variables
const Type_info * Vect_Motclebases [1] ={ &(vect_impl ::info_obj)}
const Type_info * Motclebases [1] ={ &(Nom ::info_obj)}
const Type_info * Motclesbases [1] ={ &(Vect_Motcle ::info_obj)}
Function Documentation
char_uppercase()
static char char_uppercase (char c) inline static
Definition at line 278 of file Motcle.cpp.
{
  if (c >= 'a' && c <= 'z')
    c += 'A' - 'a';
  return c;
}
Referenced by strcmp_uppercase().
noms_to_motcles()
Motcles noms_to_motcles (const Noms & a)
< ouais, ecriture bizarre mais la plus efficace...
Definition at line 437 of file Motcle.cpp.
{
  int n = a.size();
  Motcles b(n);
  for (int i = 0; i < n; i++)
    b[i] = a[i]; //!< ouais, ecriture bizarre mais la plus efficace...
  return b;
}
References vect_impl::size().
operator!=() [1/5]
int operator!= (const char *const nom, const Motcle & un_mot)
Definition at line 415 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator!=() [2/5]
int operator!= (const Motcle & nom, const Motcle & un_mot)
Comparaison d'un mot cle avec une chaine de caracteres.
Returns
int
Signification: 1 si le Nom du mot est different de la chaine
Contraintes:
Definition at line 405 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator!=() [3/5]
int operator!= (const Motcle & un_mot, const char *const nom)
Definition at line 410 of file Motcle.cpp.
{
  return ! (un_mot == nom);
}
operator!=() [4/5]
int operator!= (const Motcle & un_mot, const Nom & nom)
Definition at line 420 of file Motcle.cpp.
{
  return ! (un_mot == nom);
}
operator!=() [5/5]
int operator!= (const Nom & nom, const Motcle & un_mot)
Definition at line 425 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator==() [1/5]
int operator== (const char *const nom, const Motcle & un_mot)
Definition at line 370 of file Motcle.cpp.
{
  return (un_mot == nom);
}
operator==() [2/5]
int operator== (const Motcle & nom, const Motcle & un_mot)
Comparaison d'un mot cle avec une chaine de caracteres.
Returns
int
Signification: 1 si le Nom du mot est egal a la chaine
Contraintes:
Definition at line 358 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *) nom, (const char *)un_mot);
  return (resu == 0);
}
operator==() [3/5]
int operator== (const Motcle & un_mot, const char *const nom)
Definition at line 364 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *)un_mot, nom);
  return (resu == 0);
}
operator==() [4/5]
int operator== (const Motcle & un_mot, const Nom & nom)
Definition at line 375 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *)un_mot, (const char *) nom);
  return (resu == 0);
}
operator==() [5/5]
int operator== (const Nom & nom, const Motcle & un_mot)
Definition at line 381 of file Motcle.cpp.
{
  return (un_mot == nom);
}
strcmp_uppercase()
static int strcmp_uppercase (const char * n1, const char * n2) inline static
< Keyword found in n1
< Keyword found in n2
< Found the same keyword
< End of n2
< End of n1
Definition at line 288 of file Motcle.cpp.
{
// loop on n1
  unsigned char c1,c2;
  int i=0;
  int length_i=0;
  do
    {
      c1 = (unsigned char) char_uppercase(n1[i]);
      i++;
      length_i++;
      if (c1==0 || c1==124) //!< Keyword found in n1
        {
// loop on c2
          int j=0;
          int length_j=0;
          do
            {
              c2 = (unsigned char) char_uppercase(n2[j]);
              j++;
              length_j++;
              if (c2==0 || c2==124) //!< Keyword found in n2
                {
                  if (length_i==length_j)
                    {
// Same length, we compare each caracter:
                      int l=length_i;
                      int delta=0;
                      unsigned char C1,C2;
                      do
{
                          C1 = (unsigned char) char_uppercase(n1[i-l]);
                          C2 = (unsigned char) char_uppercase(n2[j-l]);
                          delta = C2 - C1;
                          l--;
                        }
                      while (l>1 && delta==0);
                      if (delta==0)
                        return 0; //!< Found the same keyword
                    }
                  length_j=0;
                }
            }
          while(c2!=0); //!< End of n2
          length_i=0;
        }
    }
  while (c1!=0); //!< End of n1
  return 1;
}
References char_uppercase().
Variable Documentation
Motclebases
const Type_info* Motclebases[1] ={ &(Nom ::info_obj)}
Definition at line 20 of file Motcle.cpp.
Motclesbases
const Type_info* Motclesbases[1] ={ &(Vect_Motcle ::info_obj)}
Definition at line 21 of file Motcle.cpp.
Vect_Motclebases
const Type_info* Vect_Motclebases[1] ={ &(vect_impl ::info_obj)}
Definition at line 19 of file Motcle.cpp.