TRUST: src/ThHyd/Incompressible/Equations/Navier_Stokes_std.cpp File Reference
src/ThHyd/Incompressible/Equations/Navier_Stokes_std.cpp File Reference
#include <Navier_Stokes_std.h>
#include <Probleme_base.h>
#include <Domaine.h>
#include <Fluide_base.h>
#include <Discret_Thyd.h>
#include <Avanc.h>
#include <Debog.h>
#include <LecFicDistribue.h>
#include <Matrice_Morse_Sym.h>
#include <Champ_Uniforme.h>
#include <Op_Conv_ALE.h>
#include <Frontiere_dis_base.h>
#include <solv_iteratif.h>
#include <Schema_Temps.h>
#include <DoubleTrav.h>
#include <Check_espace_virtuel.h>
#include <Assembleur_base.h>
#include <communications.h>
#include <Transport_Interfaces_base.h>
#include <Ensemble_Lagrange_base.h>
#include <SFichier.h>
#include <Param.h>
#include <MD_Vector_std.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <ConstDoubleTab_parts.h>
#include <Zone_VF.h>
#include <Source_PDF_base.h>
Functions
static void construire_matrice_implicite (Operateur_base &op, const DoubleTab &valeurs_inconnue, const Solveur_Masse &solv_masse, const double dt)
Variables
const Type_info * Navier_Stokes_stdbases [1] = { &(Equation_base ::info_obj)}
Function Documentation
static void construire_matrice_implicite (Operateur_base & op, const DoubleTab & valeurs_inconnue, const Solveur_Masse & solv_masse, const double dt) [static]
Definition at line 2044 of file Navier_Stokes_std.cpp.
References Solveur_Masse::ajouter_masse(), Operateur_base::contribuer_a_avec(), Operateur_base::dimensionner(), Operateur_base::get_decal_temps(), Operateur_base::get_solveur(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), ref_cast, SolveurSys_base::reinit(), Matrice_Sym::set_est_definie(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), Deriv_::typer(), Deriv_SolveurSys_base::valeur(), and Deriv_Matrice_Base::valeur().
Referenced by Navier_Stokes_std::derivee_en_temps_inco().
{
  Matrice& mat = op.set_matrice();
  if(!mat.non_nul())
    mat.typer("Matrice_Morse");
  if(op.get_decal_temps()==1)
    {
      Matrice_Morse& matrice = ref_cast(Matrice_Morse, mat.valeur());
      op.dimensionner(matrice);
      op.contribuer_a_avec(valeurs_inconnue, matrice);
      solv_masse.ajouter_masse(dt, matrice);
      matrice *= dt;
// Si le solveur est cholesky ou gcp, on attend une matrice de type
// Matrice_Morse_Sym. Transformation du type de la matrice:
      const Nom& type_solveur = op.get_solveur()->que_suis_je();
      if(type_solveur == "Solv_Cholesky" || type_solveur == "Solv_GCP")
        {
          Matrice_Morse_Sym new_mat(matrice);
          new_mat.set_est_definie(1);
// mat est detruite puis reconstruite:
          mat = new_mat;
// Reinitialisation du solveur (recalcul des preconditionnements, factorisation, etc...)
// ref_cast_non_const(SolveurSys_base,op.get_solveur().valeur()).reinit();
          op.set_solveur().valeur().reinit();
        }
    }
}
Variable Documentation
const Type_info* Navier_Stokes_stdbases[1] = { &(Equation_base ::info_obj)}
Definition at line 52 of file Navier_Stokes_std.cpp.