TRUST: src/Kernel/Utilitaires/Objet_U.cpp File Reference
src/Kernel/Utilitaires/Objet_U.cpp File Reference
#include <Objet_U.h>
#include <Interprete_bloc.h>
#include <Lire.h>
Functions
static void object_trap (int obj_id)
static Interprete & interprete_bidon ()
int operator== (const Objet_U &x, const Objet_U &y)
retourne x.est_egal_a(y)
int operator!= (const Objet_U &x, const Objet_U &y)
Comparaison de deux Objet_U x et y
Renvoie 1 - x.est_egal_a(y);.
Variables
static int object_id_to_track = -1
Function Documentation
static Interprete& interprete_bidon () [static]
Definition at line 411 of file Objet_U.cpp.
Referenced by Objet_U::interprete().
{
  static Lire bidon;
  return bidon;
}
static void object_trap (int obj_id) [static]
Definition at line 48 of file Objet_U.cpp.
References Cerr, and finl.
Referenced by Objet_U::Objet_U().
{
  Cerr << "Objet_U::Objet_U() : object_id_=" << obj_id << finl;
}
int operator!= (const Objet_U & x, const Objet_U & y)
Comparaison de deux Objet_U x et y
Renvoie 1 - x.est_egal_a(y);.
Returns:
int
Signification: 1 si les deux Objet_U sont differents, 0 s'ils sont egaux
Contraintes:
Definition at line 493 of file Objet_U.cpp.
References Objet_U::est_egal_a().
{
  return (1-(x.est_egal_a(y)));
}
int operator== (const Objet_U & x, const Objet_U & y)
retourne x.est_egal_a(y)
Returns:
int
Signification: 1 si les deux Objet_U sont egaux, 0 sinon
Contraintes:
Definition at line 468 of file Objet_U.cpp.
References Objet_U::est_egal_a().
{
  return x.est_egal_a(y);
}
Variable Documentation
int object_id_to_track = -1 [static]
Definition at line 41 of file Objet_U.cpp.
Referenced by Objet_U::Objet_U().