TRUST: src/VDF/Operateurs/Op_Divers/Op_VDF_Face.h File Reference
Op_VDF_Face.h File Reference
#include <Zone_VDF.h>
#include <TRUSTTab.h>
Classes
class Op_VDF_Face
Functions
int face_bord_amont2 (const Zone_VDF &la_zone, const int num_face, const int k, const int i)
Function Documentation
face_bord_amont2()
int face_bord_amont2 (const Zone_VDF & la_zone, const int num_face, const int k, const int i) inline
Definition at line 57 of file Op_VDF_Face.h.
{
  const int ori = la_zone.orientation(num_face);
  int elem = la_zone.face_voisins(num_face,0);
  if(elem != -1)
    {
      const int face = la_zone.elem_faces(elem, k+i*Objet_U::dimension), elem_bis = la_zone.face_voisins(face,i);
      elem = (elem_bis != -1) ? la_zone.elem_faces(elem_bis, ori+Objet_U::dimension) : -1;
    }
  else Process::exit();
  return elem;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), and Zone_VDF::orientation().
Referenced by Op_VDF_Face::dimensionner().