TRUST: src/VEF/Operateurs/Op_VEF_Face.cpp File Reference
Op_VEF_Face.cpp File Reference
#include <Op_VEF_Face.h>
#include <Matrice_Morse.h>
#include <Equation_base.h>
#include <Sortie.h>
#include <Probleme_base.h>
#include <Champ_Don.h>
#include <Champ_Uniforme.h>
#include <Schema_Temps_base.h>
#include <Milieu_base.h>
#include <Operateur_base.h>
#include <Operateur_Diff_base.h>
#include <Op_Conv_VEF_base.h>
#include <EcrFicPartage.h>
#include <SFichier.h>
#include <communications.h>
#include <Matrice_Morse_Diag.h>
#include <TRUSTTrav.h>
#include <Dirichlet_homogene.h>
#include <Periodique.h>
#include <Symetrie.h>
Functions
void modif_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &eqn)
void modif_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &eqn)
Function Documentation
modif_matrice_pour_periodique_apres_contribuer()
void modif_matrice_pour_periodique_apres_contribuer (Matrice_Morse & matrice, const Equation_base & eqn)
Definition at line 691 of file Op_VEF_Face.cpp.
{
  const int nb_comp = eqn.inconnue().valeurs().line_size();
  const Zone_Cl_dis_base& zone_Cl_VEF=eqn.zone_Cl_dis().valeur();
  const Zone_VF& zone_VEF= ref_cast(Zone_VF,eqn.zone_dis().valeur());
  int nb_bords=zone_VEF.nb_front_Cl();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces_elem = elem_faces.dimension(1);
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1+le_bord.nb_faces()/2;
          for (int dir=0; dir<2; dir++)
            for (int num_face=num1; num_face<num2; num_face++)
              {
                int elem1 = face_voisins(num_face,dir);
                int fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
                for (int i=0; i<nb_faces_elem; i++)
                  {
                    int j=elem_faces(elem1,i);
// if (j!=num_face)
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
// int j0=j*nb_comp+nc;
                        int n0perio=fac_asso*nb_comp+nc;
                        if (((j==num_face)||(j==fac_asso)))
{
                            if (dir==0)
{
                                for (int nc2=0; nc2<nb_comp; nc2++)
{
                                    int j0=num_face*nb_comp+nc2;
                                    int j0perio=fac_asso*nb_comp+nc2;
                                    matrice(n0,j0)+=matrice(n0,j0perio);
                                    matrice(n0,j0perio)=0;
                                    matrice(n0perio,j0perio)+=matrice(n0perio,j0);
                                    matrice(n0perio,j0)=0;
                                    double titi=(matrice(n0,j0)+matrice(n0perio,j0perio));
                                    matrice(n0,j0)=titi;
                                    if (nc!=nc2)
{
                                        matrice(n0perio,j0)=titi;
                                        matrice(n0perio,j0perio)=0;
                                      }
                                    else
                                      matrice(n0perio,j0perio)=titi;
                                  }
                              }
                          }
                        else
{
                            for (int nc2=0; nc2<nb_comp; nc2++)
{
                                int j20=j*nb_comp+nc2;
                                double titi=(matrice(n0,j20)+matrice(n0perio,j20));
                                matrice(n0,j20)=titi;
                                matrice(n0perio,j20)=titi;
                              }
                          }
                      }
                  }
              }
        }
    }
// matrice.imprimer(Cerr);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Inc::valeurs(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer().
modif_matrice_pour_periodique_avant_contribuer()
void modif_matrice_pour_periodique_avant_contribuer (Matrice_Morse & matrice, const Equation_base & eqn)
Definition at line 627 of file Op_VEF_Face.cpp.
{
  const int nb_comp = eqn.inconnue().valeurs().line_size();
  const Zone_Cl_dis_base& zone_Cl_VEF=eqn.zone_Cl_dis().valeur();
  const Zone_VF& zone_VEF= ref_cast(Zone_VF,eqn.zone_dis().valeur());
  int nb_bords=zone_VEF.nb_front_Cl();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces_elem = elem_faces.dimension(1);
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2=num1+le_bord.nb_faces()/2;
          for (int dir=0; dir<2; dir++)
            for (int num_face=num1; num_face<num2; num_face++)
              {
                int elem1 = face_voisins(num_face,dir);
                int fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
                for (int i=0; i<nb_faces_elem; i++)
                  {
                    int j=elem_faces(elem1,i);
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int n0perio=fac_asso*nb_comp+nc;
                        if (((j==num_face)||(j==fac_asso)))
{
                            if (dir==0)
{
                                assert(matrice(n0,n0perio)==0);
                                assert(matrice(n0perio,n0)==0);
                                assert(matrice(n0,n0)==matrice(n0perio,n0perio));
                                double titi=(matrice(n0,n0))/2.;
                                matrice(n0,n0)=titi;
                                matrice(n0perio,n0perio)=titi;
                              }
                          }
                        else
{
                            for (int nc2=0; nc2<nb_comp; nc2++)
{
                                int j20=j*nb_comp+nc2;
                                assert(matrice(n0,j20)==matrice(n0perio,j20));
                                double titi=(matrice(n0,j20)/2.);
                                matrice(n0,j20)=titi;
                                matrice(n0perio,j20)=titi;
                              }
                          }
                      }
                  }
              }
        }
    }
// matrice.imprimer(Cerr);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Inc::valeurs(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer().