TRUST: src/P1NCP1B/Operateurs/Op_Diff_VEFP1NCP1B_Face.cpp File Reference
src/P1NCP1B/Operateurs/Op_Diff_VEFP1NCP1B_Face.cpp File Reference
#include <Op_Diff_VEFP1NCP1B_Face.h>
#include <Champ_P1NC.h>
#include <Champ_Don.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Periodique.h>
#include <Neumann_paroi.h>
#include <Neumann_homogene.h>
#include <Neumann_sortie_libre.h>
#include <Echange_externe_impose.h>
#include <Symetrie.h>
#include <Champ_Uniforme.h>
#include <Domaine.h>
#include <Ref_Champ_P1NC.h>
#include <Debog.h>
#include <DoubleLists.h>
#include <Champ_front_txyz.h>
#include <Champ_Don_lu.h>
#include <Champ_Don_Fonc_xyz.h>
#include <Champ_Uniforme_Morceaux.h>
#include <Schema_Temps_base.h>
#include <Porosites_champ.h>
#include <Check_espace_virtuel.h>
#include <Conduction.h>
#include <fstream>
Functions
static double maximum (const double &x, const double &y)
Variables
const Type_info * Op_Diff_VEFP1NCP1B_Facebases [1] = { &(Op_Diff_VEF_Face ::info_obj)}
Function Documentation
static double maximum (const double & x, const double & y) [inline, static]
Definition at line 54 of file Op_Diff_VEFP1NCP1B_Face.cpp.
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Dij(), limiteur(), and maximum().
{
  if(x<y)
    return y;
  return x;
}
Variable Documentation
const Type_info* Op_Diff_VEFP1NCP1B_Facebases[1] = { &(Op_Diff_VEF_Face ::info_obj)}
Definition at line 51 of file Op_Diff_VEFP1NCP1B_Face.cpp.