TRUST: src/VEF/Operateurs/Op_Diff_VEF_Face_Q1.cpp File Reference
src/VEF/Operateurs/Op_Diff_VEF_Face_Q1.cpp File Reference
#include <Op_Diff_VEF_Face_Q1.h>
#include <Champ_P1NC.h>
#include <Champ_Q1NC.h>
#include <Champ_Uniforme.h>
#include <Periodique.h>
#include <Neumann_paroi.h>
#include <Echange_externe_impose.h>
#include <Ref_Champ_Q1NC.h>
Functions
double visc_Q1 (const Zone_VEF &la_zone, int num_face, int num2, int num_elem, int dimension, DoubleTab &nu)
Variables
const Type_info * Op_Diff_VEF_Face_Q1bases [1] = { &(Op_Diff_VEF_base ::info_obj)}
Function Documentation
double visc_Q1 (const Zone_VEF & la_zone, int num_face, int num2, int num_elem, int dimension, DoubleTab & nu)
Definition at line 87 of file Op_Diff_VEF_Face_Q1.cpp.
References dabs(), Zone_VEF::face_normales(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), and Zone_VF::volumes().
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), and Op_Diff_VEF_Face_Q1::ajouter_contribution().
{
  double constante = nu(num_elem)/la_zone.volumes(num_elem)*la_zone.porosite_elem(num_elem);
  double Valeur=0;
  if(dimension==2)
    {
      Valeur=la_zone.face_normales(num_face,0)*
             la_zone.face_normales(num2,1) -
             la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,0);
      Valeur=constante*dabs(Valeur)*(la_zone.porosite_face(num_face)* la_zone.porosite_face(num2));
    }
  else if (dimension == 3)
    {
      Valeur=(la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,2) -
              la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,1)) +
             (la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,0) -
              la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,2)) +
             (la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,1) -
              la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,0));
      Valeur=constante*dabs(Valeur)*(la_zone.porosite_face(num_face)* la_zone.porosite_face(num2));
    }
// Cerr << "Valeur " << Valeur << finl;
  return Valeur;
}
Variable Documentation
const Type_info* Op_Diff_VEF_Face_Q1bases[1] = { &(Op_Diff_VEF_base ::info_obj)}
Definition at line 32 of file Op_Diff_VEF_Face_Q1.cpp.