TRUST: src/VDF/Operateurs/Op_Conv_VDF_base.h File Reference
src/VDF/Operateurs/Op_Conv_VDF_base.h File Reference
#include <Operateur_Conv.h>
#include <Iterateur_VDF_base.h>
Classes
class Op_Conv_VDF_base
class Op_Conv_VDF_base
Classe de base des operateurs de convection VDF
Functions
void eval_fluent (const double &, const int, const int, DoubleVect &)
Function Documentation
void eval_fluent (const double & , const int , const int , DoubleVect &) [inline]
Definition at line 50 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Referenced by Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_pour_post(), and Op_Conv_PolyMAC_iterateur_base::calculer_pour_post().
{
  if (psc >= 0)
    fluent[num2]  += psc;
  else
    fluent[num1]  -= psc;
}