TRUST: src/EF/Operateurs/Op_Diff_EF_base.h File Reference
Op_Diff_EF_base.h File Reference
#include <Neumann_sortie_libre.h>
#include <Operateur_Diff_base.h>
#include <Ref_Champ_Inc_base.h>
#include <Ref_Zone_Cl_EF.h>
#include <Ref_Zone_EF.h>
#include <Op_EF_base.h>
#include <Zone_Cl_EF.h>
#include <Zone_EF.h>
Classes
class Op_Diff_EF_base
class Op_Diff_EF_base
Classe de base des operateurs de diffusion EF
Enumerations
enum class AJOUTE_SCAL { GEN , D3_8 , D2_4 }
enum class AJOUTE_VECT { GEN , D3_8 , D2_4 }
Functions
void remplir_marqueur_sommet_neumann (ArrOfInt &marqueur, const Zone_EF &zone_EF, const Zone_Cl_EF &zone_Cl_EF, int transpose_partout)
Enumeration Type Documentation
AJOUTE_SCAL
enum class AJOUTE_SCAL strong
Enumerator
GEN
D3_8
D2_4
Definition at line 32 of file Op_Diff_EF_base.h.
{ GEN , D3_8 , D2_4 };
AJOUTE_VECT
enum class AJOUTE_VECT strong
Enumerator
GEN
D3_8
D2_4
Definition at line 33 of file Op_Diff_EF_base.h.
{ GEN , D3_8 , D2_4 };
Function Documentation
remplir_marqueur_sommet_neumann()
void remplir_marqueur_sommet_neumann (ArrOfInt & marqueur, const Zone_EF & zone_EF, const Zone_Cl_EF & zone_Cl_EF, int transpose_partout) inline
Definition at line 58 of file Op_Diff_EF_base.h.
{
  marqueur.resize_array(zone_EF.nb_som_tot());
  if ( transpose_partout) return;
// Neumann :
  int n_bord;
  int nb_bords=zone_EF.nb_front_Cl();
  const IntTab& face_sommets=zone_EF.face_sommets();
  int nb_som_face=zone_EF.nb_som_face();
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nfin =le_bord.nb_faces_tot();
          for (int ind_face=0; ind_face<nfin; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  marqueur[glob2]=1;
                }
            }
        }
    }
}
References Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone_VF::nb_som_face(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_vectoriel_template(), and Op_Dift_EF_Q1::ajouter_vectoriel_template().