TRUST: src/VEF/Operateurs/Op_Conv_EF_VEF_P1NC_Stab.cpp File Reference
Op_Conv_EF_VEF_P1NC_Stab.cpp File Reference
#include <Op_Conv_EF_VEF_P1NC_Stab.h>
#include <Champ_P1NC.h>
#include <BilanQdmVEF.h>
#include <Schema_Temps_base.h>
#include <Debog.h>
#include <Porosites_champ.h>
#include <Sous_zone_VF.h>
#include <Probleme_base.h>
#include <ArrOfBit.h>
#include <TRUSTVects.h>
#include <SFichier.h>
#include <TRUSTList.h>
#include <TRUSTTabs.h>
#include <stat_counters.h>
#include <Neumann_sortie_libre.h>
#include <Dirichlet_homogene.h>
#include <Neumann_homogene.h>
#include <Periodique.h>
#include <Symetrie.h>
#include <Echange_impose_base.h>
Functions
static double maximum (const double x, const double y)
static double maximum (const double x, const double y, const double z)
static double minimum (const double x, const double y)
static double Dij (int elem, int face_loc_i, int face_loc_j, const DoubleTab &Kij)
static double limiteur (double r)
double formule_Id_2D (int n)
double formule_Id_3D (int n)
double formule_2D (int n)
double formule_3D (int n)
Variables
const Type_info * Op_Conv_EF_VEF_P1NC_Stabbases [1] ={ &(Op_Conv_VEF_Face ::info_obj)}
Function Documentation
Dij()
static double Dij (int elem, int face_loc_i, int face_loc_j, const DoubleTab & Kij) inline static
Definition at line 189 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const double kij=Kij(elem,face_loc_i,face_loc_j);
  const double kji=Kij(elem,face_loc_j,face_loc_i);
  return maximum(-kij,-kji,0);
}
References maximum().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), and Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu().
formule_2D()
double formule_2D (int n)
Definition at line 215 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  switch(n)
    {
    case 0:
      return 1./3;
      break;
    case 1:
      return 0.5;
      break;
    case 2:
      return 1.;
      break;
    default:
      Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::formule_2D()" << finl;
      Process::exit();
      break;
    }
  return 0.;
}
References Cerr, Process::exit(), and finl.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), and Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible().
formule_3D()
double formule_3D (int n)
Definition at line 236 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  switch(n)
    {
    case 0:
      return 0.25;
      break;
    case 1:
      return 1./3;
      break;
    case 2:
      return 0.5;
      break;
    case 3:
      return 1.;
      break;
    default:
      Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::formule_3D()" << finl;
      Process::exit();
      break;
    }
  return 0.;
}
References Cerr, Process::exit(), and finl.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), and Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible().
formule_Id_2D()
double formule_Id_2D (int n)
Definition at line 205 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  return 1./3;
}
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), and Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible().
formule_Id_3D()
double formule_Id_3D (int n)
Definition at line 210 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  return 0.25;
}
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), and Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible().
limiteur()
static double limiteur (double r) inline static
Definition at line 199 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  if(r<=0) return 0.;
  return maximum(minimum(2,r),minimum(1,2*r));//SuperBee
}
References maximum(), and minimum().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::readOn(), and Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu().
maximum() [1/2]
static double maximum (const double x, const double y) inline static
Definition at line 165 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  if(x<y)
    return y;
  return x;
}
Referenced by Dij(), limiteur(), and maximum().
maximum() [2/2]
static double maximum (const double x, const double y, const double z) inline static
Definition at line 173 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  return maximum(maximum(x,y),z);
}
References maximum().
minimum()
static double minimum (const double x, const double y) inline static
Definition at line 180 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  if(x>y)
    return y;
  return x;
}
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), limiteur(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), and Op_Diff_RotRot::Tri().
Variable Documentation
Op_Conv_EF_VEF_P1NC_Stabbases
const Type_info* Op_Conv_EF_VEF_P1NC_Stabbases[1] ={ &(Op_Conv_VEF_Face ::info_obj)}
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.