TRUST: src/VEF/Operateurs/Op_Conv_Amont_old_VEF_Face.cpp File Reference
Op_Conv_Amont_old_VEF_Face.cpp File Reference
#include <Op_Conv_Amont_old_VEF_Face.h>
#include <Hexaedre_VEF.h>
#include <Periodique.h>
#include <Neumann_sortie_libre.h>
Functions
static void convbis (const double psc, const int num1, const int num2, const DoubleTab &transporte, const int ncomp, DoubleTab &resu, DoubleVect &fluent)
static void convbisimplicite (const double psc, const int num1, const int num2, const DoubleTab &transporte, const int ncomp, DoubleVect &coeff, Matrice_Morse &matrice)
Variables
const Type_info * Op_Conv_Amont_old_VEF_Facebases [1] ={ &(Op_Conv_VEF_base ::info_obj)}
Function Documentation
convbis()
static void convbis (const double psc, const int num1, const int num2, const DoubleTab & transporte, const int ncomp, DoubleTab & resu, DoubleVect & fluent) static
Definition at line 43 of file Op_Conv_Amont_old_VEF_Face.cpp.
{
  int comp,amont;
  double flux;
  if (psc >= 0)
    {
      amont = num1;
      fluent[num2] += psc;
    }
  else
    {
      amont = num2;
      fluent[num1] -= psc;
    }
  for (comp=0; comp<ncomp; comp++)
    {
      flux = transporte(amont,comp)*psc;
      resu(num1,comp) -= flux;
      resu(num2,comp) += flux;
    }
}
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter().
convbisimplicite()
static void convbisimplicite (const double psc, const int num1, const int num2, const DoubleTab & transporte, const int ncomp, DoubleVect & coeff, Matrice_Morse & matrice) static
Definition at line 68 of file Op_Conv_Amont_old_VEF_Face.cpp.
{
  int comp,k;
  IntVect& tab1 = matrice.get_set_tab1();
  IntVect& tab2 = matrice.get_set_tab2();
  for (comp=0; comp<ncomp; comp++)
    {
      if (psc >=0)
        {
          for (k=tab1[num1*ncomp+comp]-1; k<tab1[num1*ncomp+comp+1]-1; k++)
            {
              if (tab2[k]-1== num1*ncomp+comp)
                coeff(k) += psc;
            }
          for (k=tab1[num2*ncomp+comp]-1; k<tab1[num2*ncomp+comp+1]-1; k++)
            {
              if (tab2[k]-1== num1*ncomp+comp)
                coeff(k) -= psc;
            }
        }
      else
        {
          for (k=tab1[num1*ncomp+comp]-1; k<tab1[num1*ncomp+comp+1]-1; k++)
            {
              if (tab2[k]-1== num2*ncomp+comp)
                coeff(k) += psc;
            }
          for (k=tab1[num2*ncomp+comp]-1; k<tab1[num2*ncomp+comp+1]-1; k++)
            {
              if (tab2[k]-1== num2*ncomp+comp)
                coeff(k) -= psc;
            }
        }
    }
}
References coeff, Matrice_Morse::get_set_tab1(), and Matrice_Morse::get_set_tab2().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter_contribution().
Variable Documentation
Op_Conv_Amont_old_VEF_Facebases
const Type_info* Op_Conv_Amont_old_VEF_Facebases[1] ={ &(Op_Conv_VEF_base ::info_obj)}
Definition at line 21 of file Op_Conv_Amont_old_VEF_Face.cpp.