TRUST: src/VEF/Operateurs/Op_Dift_VEF_Face_Q1.cpp File Reference
Op_Dift_VEF_Face_Q1.cpp File Reference
#include <Op_Dift_VEF_Face_Q1.h>
#include <Champ_Q1NC.h>
#include <Champ_Don.h>
#include <Periodique.h>
#include <Dirichlet_paroi_fixe.h>
#include <Dirichlet_paroi_defilante.h>
#include <Neumann_paroi.h>
#include <Echange_externe_impose.h>
#include <Champ_Uniforme.h>
#include <Debog.h>
#include <TRUSTTrav.h>
#include <Milieu_base.h>
#include <Zone_Cl_VEF.h>
Functions
static double viscA_Q1 (const Zone_VEF &la_zone, int num_face, int num2, int dimension, int num_elem, double diffu)
Variables
const Type_info * Op_Dift_VEF_Face_Q1bases [1] ={ &(Op_Dift_VEF_base ::info_obj)}
Function Documentation
viscA_Q1()
static double viscA_Q1 (const Zone_VEF & la_zone, int num_face, int num2, int dimension, int num_elem, double diffu) static
Definition at line 110 of file Op_Dift_VEF_Face_Q1.cpp.
{
  double constante = (diffu)/la_zone.volumes(num_elem);
  double Valeur=0;
  if(dimension==2)
    {
      Valeur=la_zone.face_normales(num_face,0)*
             la_zone.face_normales(num2,1) -
             la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,0);
      Valeur=constante*std::fabs(Valeur);
    }
  else
    {
      Valeur=(la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,2) -
              la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,1)) +
             (la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,0) -
              la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,2)) +
             (la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,1) -
              la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,0));
      Valeur=constante*std::fabs(Valeur);
    }
  return Valeur;
}
References Zone_VEF::face_normales(), and Zone_VF::volumes().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), and Op_Dift_VEF_Face_Q1::ajouter_contribution().
Variable Documentation
Op_Dift_VEF_Face_Q1bases
const Type_info* Op_Dift_VEF_Face_Q1bases[1] ={ &(Op_Dift_VEF_base ::info_obj)}
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.