TRUST: src/VEF/Operateurs/Op_Conv_DI_L2_VEF_Face.cpp File Reference
Op_Conv_DI_L2_VEF_Face.cpp File Reference
#include <Op_Conv_DI_L2_VEF_Face.h>
#include <Champ_P1NC.h>
#include <Schema_Temps_base.h>
#include <Periodique.h>
#include <Neumann_sortie_libre.h>
Functions
void flora (DoubleTab A, int &N, DoubleVect B, DoubleVect &U, int &test_flora)
void flora_p (DoubleTab &A, int &N, DoubleVect &B, DoubleVect &U, int &test_flora)
void qrdcmp (DoubleTab &A, int &N, DoubleVect &C, DoubleVect &D, int &sing)
void rsolv (DoubleTab &A, int &N, DoubleVect &D, DoubleVect &B)
void qrsolv (DoubleTab &A, int &N, DoubleVect &B, DoubleVect &X, int &sing, int &ncomp, DoubleVect &C, DoubleVect &D)
void gradient_biconjugue (DoubleTab A, int n, DoubleVect b, DoubleVect &x, int &sing, int &niter)
void convbis (double psc, int num1, int num2, const DoubleTab &transporte, int ncomp, DoubleTab &resu, DoubleVect &fluent)
Variables
const Type_info * Op_Conv_DI_L2_VEF_Facebases [1] ={ &(Op_Conv_VEF_base ::info_obj)}
Function Documentation
convbis()
void convbis (double psc, int num1, int num2, const DoubleTab & transporte, int ncomp, DoubleTab & resu, DoubleVect & fluent)
Definition at line 369 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  int comp,amont;
  double flux;
  if (psc >= 0)
    {
      amont = num1;
      fluent[num2] += psc;
    }
  else
    {
      amont = num2;
      fluent[num1] -= psc;
    }
  if (ncomp == 1)
    {
      flux = transporte(amont)*psc;
      resu(num1) -= flux;
      resu(num2) += flux;
    }
  else
    for (comp=0; comp<ncomp; comp++)
      {
        flux = transporte(amont,comp)*psc;
        resu(num1,comp) -= flux;
        resu(num2,comp) += flux;
      }
}
Referenced by Op_Conv_DI_L2_VEF_Face::ajouter().
flora()
void flora (DoubleTab A, int & N, DoubleVect B, DoubleVect & U, int & test_flora)
Definition at line 53 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// cette procedure correspond a la methode d'elimination de Gauss
  test_flora = 0; //test pour savoir si la matrice est inversible(0) ou non(1)
  int N1 = N-1;
  int m, m1, i, i1, k, l;
  double quo,SU;
  for(m=0; m<N1; m++)
    {
      m1 = m+1;
      if(std::fabs(A(m,m)) > 1e-20)
        {
          for(i=m1; i<N; i++)
            {
              quo = A(i,m)/A(m,m);
              for(k=m; k<N; k++)
                A(i,k) =A(i,k)-quo*A(m,k);
              B(i) = B(i)-quo*B(m);
            }
        }
      else
        {
          Cerr<<"Erreur flora: matrice non inversible a l'indice "<<m<<finl;
          test_flora = 1;
        }
    }
  if(std::fabs(A(N-1,N-1)) >= 1e-20)
    {
      U(N-1) = B(N-1)/A(N-1,N-1);
      for(l=0; l<N1; l++)
        {
          i = N1-l-1;
          SU = 0;
          i1 = i+1;
          for(k=i1; k<N; k++)
            SU = SU+A(i,k)*U(k);
          U(i) = (B(i)-SU)/A(i,i);
        }
    }
  else
    {
      Cerr<<"Erreur flora: matrice non inversible a l'indice"<<N-1<<finl;
      test_flora = 1;
    }
}
References Cerr, finl, and m1.
flora_p()
void flora_p (DoubleTab & A, int & N, DoubleVect & B, DoubleVect & U, int & test_flora)
Definition at line 101 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// cette procedure correspond a la methode d'elimination de Gauss
  test_flora = 1;//test pour savoir si la matrice est inversible(1) ou non(0)
  int N1 = N-1;
  int m, m1, i, j, i1, k, l;
  int test=0;
  double quo, SU, x, y;
  for(m=0; m<N1; m++)
    {
      m1 = m+1;
      if(std::fabs(A(m,m))  >= 1.e-10)
        {
          for(i=m1; i<N; i++)
            {
              quo = A(i,m)/A(m,m);
              for(k=m; k<N; k++)
                A(i,k) =A(i,k)-quo*A(m,k);
              B(i) = B(i)-quo*B(m);
            }
        }
      else
        {
          j=m+1;
          while(j<N && test == 0)
            {
              if(std::fabs(A(m,j)) >= 1.e-10) test =1;
              j++;
            }
          if(j == N)
            {
              Cerr<<"Erreur flora: matrice non inversible a l'indice "<<m<<finl;
              test_flora = 1;
            }
          else         //echange des colonnes m et j
            {
              for(i=0; i<N; i++)
                {
                  x=A(i,m);
                  A(i,m)=A(i,j);
                  A(i,j)=x;
                  y=B(m);
                  B(m)=B(j);
                  B(j)=y;
                }
            }
          test_flora = 0;
        }
    }
  if(std::fabs(A(N-1,N-1)) >= 1.e-10)
    {
      U(N-1) = B(N-1)/A(N-1,N-1);
      for(l=0; l<N1; l++)
        {
          i = N1-l-1;
          SU = 0;
          i1 = i+1;
          for(k=i1; k<N; k++)
            SU = SU+A(i,k)*U(k);
          U(i) = (B(i)-SU)/A(i,i);
        }
    }
  else
    {
// Cerr<<"Erreur flora: matrice non inversible a l'indice"<<N-1<<finl;
      test_flora = 0;
    }
}
References Cerr, finl, m1, and test().
gradient_biconjugue()
void gradient_biconjugue (DoubleTab A, int n, DoubleVect b, DoubleVect & x, int & sing, int & niter)
< B.M. code visiblement faux en parallele
Definition at line 263 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  if (Process::nproc() > 1)
    {
      Cerr << "OpVEF_DI_L2.cpp: gradient_biconjugue() n'est pas parallele" << finl;
      assert(0);
      Process::exit();
    }
  double seuil ;
  double dnew  = 1. ;
  double dold, alfa, beta ;
  niter = 0 ;
  sing = 0 ;
  DoubleVect r(n) ;
  DoubleVect r_tilda(n);
  DoubleVect p(n) ;
  DoubleVect p_tilda(n);
  DoubleVect q(n) ;
  DoubleVect u(n);
  double r_norme, b_norme = norme_array(b);
  int i,j;
  if(b_norme > 1.e-7 )
    seuil = 1.e-5/b_norme;
  else seuil = 1.e-10;
  r = 0. ;
  p = 0. ;
  q = 0. ;
  for(i=0; i<n; i++)
    p(i) = b(i);
  int nmax = 50 ;
  for(i=0; i<n; i++)
    for(j=0; j<n; j++)
      {
        r(i) = p(i)-A(i,j)*x(j) ;
        r_tilda(i) = r(i) ;
      }
  p = 0 ;
  dold = dotproduct_array(r_tilda, r);
  r_norme = norme_array(r);
  if(sqrt(dold) > seuil)
    {
      while ( ( r_norme > seuil ) && (niter++ < nmax) )
        {
          assert(Process::nproc() == 1); //!< B.M. code visiblement faux en parallele
          dnew = dotproduct_array(r_tilda, r);
          if(dold == 0.)        niter = nmax ;
          else
            {
              beta = dnew/dold ;
              for(i=0; i<n; i++)
                {
                  p(i) = r(i)+beta*p(i) ;
                  p_tilda(i) = r_tilda(i)+beta*p_tilda(i) ;
                }
              q = 0. ;
              for(i=0; i<n; i++)
                for(j=0; j<n; j++)
                  q(i) += A(i,j)*p(j) ;
              beta = dotproduct_array(p_tilda, q) ;
// Cerr<<"beta :"<<beta<<finl ;
              if(beta == 0.)        niter = nmax ;
              else
                {
                  alfa = dnew / beta ;
                  x.ajoute_sans_ech_esp_virt(alfa, p);
                  r.ajoute_sans_ech_esp_virt(-alfa, q);
                  q = 0. ;
                  for(i=0; i<n; i++)
                    for(j=0; j<n; j++)
                      q(i) += A(j,i)*p_tilda(j) ;
                  r_tilda.ajoute_sans_ech_esp_virt(-alfa, q);
                  dold = dnew;
// assert(dnew >= 0.);
                  r_norme = norme_array(r);
// Cerr << " niter " << niter << " dnew " << dnew <<finl ;
// Cerr << " r " << r.norme() << finl;
// Cerr << " x " << x << finl;
                }
            }
        }
    }
  if ( niter >= nmax) sing = 1 ;
// Cerr<<"niter :"<<niter<<finl;
}
References TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), Cerr, dotproduct_array(), Process::exit(), finl, norme_array(), and Process::nproc().
qrdcmp()
void qrdcmp (DoubleTab & A, int & N, DoubleVect & C, DoubleVect & D, int & sing)
Definition at line 173 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// construit la decomposition QR de A. Le triangle superieur R est stockee dans le triangle superieur de A,
// exepte les elements de la diagonale, qui sont stockes dans D. La matrice orthogonale Q est representee
// comme un produit de N-1 matrice Q(1), ..., Q(N-1) ou Q(j) = Id-(uj*ujt)/cj. La ieme composante de uj est 0
// pour i=1, ...,j-1 et A(i,j) pour i=j, ..., N. sing retourne 0 si la decomposition est possible et 1 sinon.
  int i, j, k;
  double scale, sigma, sum, tau;
  sing =0;
  for(k=0; k<N-1; k++)
    {
      scale = 0.;
      for(i=k; i<N; i++)
        if(scale < std::fabs(A(i,k)))                scale = std::fabs(A(i,k));
      if(std::fabs(scale)<1.e-15)
        {
// cas singulier
          Cerr << " huhu " << finl ;
          sing = 1;
          C(k) = 0;
          D(k) = 0;
          return ;
        }
      else
        {
          for(i=k; i<N; i++)        A(i,k) /= scale;
          for(sum=0.0,i=k; i<N; i++)        sum += (A(i,k) * A(i,k));
          if(A(k,k)>0) sigma = sqrt(sum);
          else        sigma = -1*sqrt(sum);
          A(k,k) += sigma;
          C(k) = sigma*A(k,k);
          D(k) = -1*scale*sigma;
          for(j=k+1; j<N; j++)
            {
              for(sum=0.0,i=k; i<N; i++)        sum += A(i,k)*A(i,j);
              tau = sum/C(k);
              for(i=k; i<N; i++)        A(i,j) -= tau*A(i,k);
            }
        }
    }
  D(N-1) = A(N-1,N-1);
  if(std::fabs(D(N-1)) <1.e-12)
    {
      Cerr << " hoho " << finl ;
      sing =1;
    }
}
References Cerr, and finl.
Referenced by qrsolv().
qrsolv()
void qrsolv (DoubleTab & A, int & N, DoubleVect & B, DoubleVect & X, int & sing, int & ncomp, DoubleVect & C, DoubleVect & D)
Definition at line 237 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// resout le systeme lineaire Ax=B
// DoubleVect C(N), D(N);
  int i, j;
  double sum, tau;
  if(ncomp == 0 ) qrdcmp(A, N, C, D, sing);
  if(sing == 0)
    {
      for(j=0; j<N-1; j++)
        {
          for(sum=0.0,i=j; i<N; i++)        sum += A(i,j)*B(i);
          tau = sum/C(j);
          for(i=j; i<N; i++)        B(i) -= tau*A(i,j);
        }
      rsolv(A, N, D, B);//resout Rx=QtB
      for(i=0; i<N; i++)        X(i) = B(i);
    }
// else        Cerr<<"erreur"<<finl;
}
References qrdcmp(), and rsolv().
Referenced by Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), and Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d().
rsolv()
void rsolv (DoubleTab & A, int & N, DoubleVect & D, DoubleVect & B)
Definition at line 223 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// resout le systeme Rx=B, ou R est triangulaire superieure stockee dans A et D, provenant de qrdcmp
// le resultat est stocke dans B.
  int i, j;
  double sum;
  B(N-1) /= D(N-1);
  for(i=N-2; i>=0; i--)
    {
      for(sum=0.0,j=i+1; j<N; j++)        sum += A(i,j)*B(j);
      B(i) = (B(i)-sum)/D(i);
    }
}
Referenced by qrsolv().
Variable Documentation
Op_Conv_DI_L2_VEF_Facebases
const Type_info* Op_Conv_DI_L2_VEF_Facebases[1] ={ &(Op_Conv_VEF_base ::info_obj)}
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.