TRUST: src/EF/Operateurs/Op_Grad_EF.cpp File Reference
Op_Grad_EF.cpp File Reference
#include <Op_Grad_EF.h>
#include <Neumann_sortie_libre.h>
#include <Dirichlet.h>
#include <Navier_Stokes_std.h>
#include <Probleme_base.h>
#include <Schema_Temps_base.h>
#include <EcrFicPartage.h>
#include <SFichier.h>
#include <Champ_P0_EF.h>
#include <Check_espace_virtuel.h>
#include <Debog.h>
#include <Discretisation_base.h>
#include <EChaine.h>
#include <interface_INITGAUSS.h>
#include <interface_CALCULSI.h>
#include <Domaine.h>
Functions
void test (const DoubleTab &pression, DoubleTab &grad, const Op_Grad_EF &op)
void ajouter_bord (DoubleTab &resu, const Zone_EF &zone_EF, const Zone_Cl_EF &zone_Cl_EF, const Champ_Don &int_P_bord_)
Variables
const Type_info * Op_Grad_EFbases [1] ={ &(Operateur_Grad_base ::info_obj)}
static int bid =0
Function Documentation
ajouter_bord()
void ajouter_bord (DoubleTab & resu, const Zone_EF & zone_EF, const Zone_Cl_EF & zone_Cl_EF, const Champ_Don & int_P_bord_)
Definition at line 109 of file Op_Grad_EF.cpp.
{
// const IntTab& face_voisins = zone_EF.face_voisins();
  const DoubleTab& face_normales = zone_EF.face_normales();
  const IntTab& face_sommets=zone_EF.face_sommets();
  int nb_som_face=zone_EF.nb_som_face();
  if (int_P_bord_.non_nul())
    {
      resu+= int_P_bord_.valeurs();
    }
  else
    {
      const DoubleVect& porosite_sommet = zone_EF.porosite_sommet();
      if (face_sommets.dimension(1)==4)
        {
          ArrOfInt filter(4) ;
          filter[0] = 0 ;
          filter[1] = 2 ;
          filter[2] = 3 ;
          filter[3] = 1 ;
          interface_INITGAUSS init_gauss;
          int npgau=9;
          int nbnn=4;
          DoubleTab xgau(npgau,3),frgau(npgau,nbnn),dfrgau(npgau,nbnn,(int)3),poigau(npgau);
          int dim=2;
// init_gauss.compute(&dim,&nbnn,&npgau,xgau.addr(),frgau.addr(),dfrgau.addr(),poigau.addr());
          init_gauss.Compute(dim,nbnn,npgau,xgau,frgau,dfrgau,poigau);
// ArrOfInt num(nbnn);
          interface_CALCULSI CALCULSI;
          DoubleTab xl(3,8),poro(4),detj(npgau), cnorm(3),si(4);
          int ip=0;
          const DoubleTab& coord=zone_EF.zone().domaine().coord_sommets();
// const DoubleTab& face_normales = zone_EF.face_normales();
          ArrOfInt num(4);
          for ( int n_bord=0; n_bord<zone_EF.nb_front_Cl(); n_bord++)
            {
              const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int nfin = le_bord.nb_faces_tot();
              if ( sub_type(Neumann_sortie_libre,la_cl.valeur()) )
                {
                  const Neumann_sortie_libre& la_cl_typee =
                    ref_cast(Neumann_sortie_libre, la_cl.valeur());
                  for (int ind_face=0; ind_face<nfin; ind_face++)
                    {
                      int face=le_bord.num_face(ind_face);
                      for (int i=0; i<3; i++)
                        cnorm(i)=face_normales(face,i);
                      cnorm/=norme_array(cnorm);
// int elem = face_voisins(face,0);
                      double val_imp= la_cl_typee.flux_impose(ind_face);
                      for (int i=0; i<nbnn; i++)
{
                          num[i]=face_sommets(face,filter[i]);
                        }
                      for (int i=0; i<nbnn; i++)
{
                          for (int d=0; d<Objet_U::dimension; d++)
                            xl(d,i)=coord(num[i],d);
                          poro(i)=porosite_sommet[num[i]];
                        }
                      ip=1;
                      CALCULSI.Compute(nbnn, xl,
                                       poro,ip,
                                       npgau, xgau, frgau, dfrgau,
                                       poigau,detj, cnorm,si);
                      for (int i=0; i<nbnn; i++)
{
                          for (int d=0; d<Objet_U::dimension; d++)
{
                              int som=num[(i)];
                              resu(som,d)+=si(i)*cnorm(d)*val_imp;
                            }
                        }
                    }
                }
            }
        }
      else
        for ( int n_bord=0; n_bord<zone_EF.nb_front_Cl(); n_bord++)
          {
            const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
            const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
            int nfin = le_bord.nb_faces_tot();
            if ( sub_type(Neumann_sortie_libre,la_cl.valeur()) )
              {
                const Neumann_sortie_libre& la_cl_typee =
                  ref_cast(Neumann_sortie_libre, la_cl.valeur());
                for (int ind_face=0; ind_face<nfin; ind_face++)
                  {
                    int face=le_bord.num_face(ind_face);
// int elem = face_voisins(face,0);
                    double val_imp= la_cl_typee.flux_impose(ind_face);
                    val_imp/=nb_som_face;
                    for (int s=0; s<nb_som_face; s++)
                      {
                        int som=face_sommets(face,s);
                        for (int dir=0; dir<Objet_U::dimension; dir++)
                          resu(som,dir)+=val_imp*face_normales(face,dir)*porosite_sommet(som);
                      }
                  }
              }
          }
    }
  zone_Cl_EF.imposer_symetrie(resu);
}
References interface_INITGAUSS::Compute(), interface_CALCULSI::Compute(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_EF::face_normales(), Zone_VF::face_sommets(), Neumann::flux_impose(), Cond_lim::frontiere_dis(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone_VF::nb_som_face(), O_U_Ptr::non_nul(), norme_array(), Front_VF::num_face(), Zone_EF::porosite_sommet(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
Referenced by Op_Grad_EF::ajouter().
test()
void test (const DoubleTab & pression, DoubleTab & grad, const Op_Grad_EF & op)
Definition at line 92 of file Op_Grad_EF.cpp.
{
  if (bid==0)
    {
      bid=1;
      DoubleTab pe(pression);
      pe=1;
      op.ajouter(pe,grad);
      Cerr<<"ici max grad "<<grad.mp_max_abs_vect()<<finl;
// Cerr<<grad<<finl;
    }
}
References Op_Grad_EF::ajouter(), bid, Cerr, finl, and TRUSTVect< _TYPE_ >::mp_max_abs_vect().
Referenced by Op_Grad_EF::ajouter(), Convection_Diffusion_Espece_Multi_QC::assembler(), Assembleur_P_EF::assembler_mat(), Source_Dirac_VDF_Elem::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Eval_Dirac_VDF_Elem::calculer_terme_source(), Eval_Dirac_VEF_Face::calculer_terme_source_non_standard(), Eval_Dirac_VEF_Face::calculer_terme_source_standard(), Chimie::completer(), Partitionneur_base::corriger_sommets_bord(), Pb_MED::creer_champ(), Chimie::discretiser(), TroisDto2D::extraire_2D(), ExtrudeBord::extruder_bord(), flora_p(), Chimie::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Chimie::get_noms_champs_postraitables(), histogramme_angle(), Sonde::initialiser(), Raffiner_isotrope_parallele::interpreter(), Extraire_plan::interpreter_(), inverser_par_diagonale(), Scatter::lire_domaine(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), Loi_Etat_Multi_GP_QC::rabot(), Probleme_base::readOn(), Sous_Zone::readOn(), Champ_Fonc_reprise::readOn(), Raffiner_Simplexes::refine_domain(), Op_Diff_RotRot::remplir_som_som_EF(), reordonne(), Hexaedre_VEF::reordonner(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Solv_Petsc::resoudre_systeme(), test_un_solveur(), Trianguler::trianguler(), and Aretes::trier_pour_debog().
Variable Documentation
bid
int bid =0 static
Definition at line 91 of file Op_Grad_EF.cpp.
Referenced by test().
Op_Grad_EFbases
const Type_info* Op_Grad_EFbases[1] ={ &(Operateur_Grad_base ::info_obj)}
Definition at line 34 of file Op_Grad_EF.cpp.