TRUST: src/P1NCP1B/Operateurs/Op_Grad_VEF_P1B_Face.cpp File Reference
Op_Grad_VEF_P1B_Face.cpp File Reference
#include <Op_Grad_VEF_P1B_Face.h>
#include <Periodique.h>
#include <Symetrie.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Neumann_sortie_libre.h>
#include <Navier_Stokes_std.h>
#include <Domaine.h>
#include <Debog.h>
#include <Check_espace_virtuel.h>
#include <TRUSTTrav.h>
#include <Probleme_base.h>
#include <Schema_Temps_base.h>
#include <EcrFicPartage.h>
#include <communications.h>
Functions
static int chercher_arete (int elem, int somi, int somj, const IntTab &elem_aretes, const IntTab &aretes_som)
static void verifier (const Op_Grad_VEF_P1B_Face &op, int &init, const Zone_VEF_PreP1b &zone_VEF, const DoubleTab &pre, DoubleTab &grad)
Variables
const Type_info * Op_Grad_VEF_P1B_Facebases [1] ={ &(Op_Grad_VEF_Face ::info_obj)}
Function Documentation
chercher_arete()
static int chercher_arete (int elem, int somi, int somj, const IntTab & elem_aretes, const IntTab & aretes_som) static
Definition at line 55 of file Op_Grad_VEF_P1B_Face.cpp.
{
  if(somi>somj)
    {
      int k=somi;
      somi=somj;
      somj=k;
    }
  for(int i_arete=0; i_arete<6; i_arete++)
    {
      int arete=elem_aretes(elem, i_arete);
      int som1=aretes_som(arete,0);
      if(somi==som1)
        {
          int som2=aretes_som(arete,1);
          if(somj==som2)
            return arete;
        }
    }
  return -1;
}
Referenced by Op_Grad_VEF_P1B_Face::ajouter_aretes().
verifier()
static void verifier (const Op_Grad_VEF_P1B_Face & op, int & init, const Zone_VEF_PreP1b & zone_VEF, const DoubleTab & pre, DoubleTab & grad) static
Definition at line 78 of file Op_Grad_VEF_P1B_Face.cpp.
{
// Methode verifier ne marche que pour P0+P1 en 2D et P0+P1+Pa en 3D
  if (Objet_U::dimension==2 && zone_VEF.get_alphaE()+zone_VEF.get_alphaS()!=2)
    {
      Cerr << "Methode verifier de Op_Grad_VEF_P1B_Face non valable pour cette discretisation." << finl;
      Process::exit();
    }
  if (Objet_U::dimension==3 && zone_VEF.get_alphaE()+zone_VEF.get_alphaS()+zone_VEF.get_alphaA()!=3)
    {
      Cerr << "Methode verifier de Op_Grad_VEF_P1B_Face non valable pour cette discretisation." << finl;
      Process::exit();
    }
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_som_tot=dom.nb_som_tot();
  int nb_elem=zone.nb_elem();
  init=1;
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleTab& xp = zone_VEF.xp();
  const DoubleTab& coord_sommets=dom.coord_sommets();
// Verification de la pression arete
  DoubleTab tab(pre);
  exemple_champ_non_homogene(zone_VEF, tab);
  DoubleTab r(grad);
  r=0;
  op.ajouter(tab, r);
// Pression mise a 1 sur tous les noeuds
  DoubleTab p(pre);
  p=1;
  r=0;
  op.ajouter(p, r);
  if (nb_elem<30)
    {
      Cerr << Process::me() << " grad(1) som = " << finl;
      r.ecrit(Cerr);
    }
// Pression mise a 1 sur les elements seulement
  p=0;
  int i=0;
  for(; i<nb_elem_tot; i++)
    p(i)=0;
  r=0;
  op.ajouter(p, r);
  Cerr << "["<<Process::me() << "] p(1) elem = " << finl;
  p.ecrit(Cerr);
  Cerr << "["<<Process::me() << "] grad(1) elem = " << finl;
  r.ecrit(Cerr);
// Pression mise a 1 sur les sommets seulement
  p=0;
  for(; i<nb_elem_tot+nb_som_tot; i++)
    p(i)=1;
  r=0;
  op.ajouter(p, r);
  Cerr << Process::me() << " grad(1) som = " << finl;
  r.ecrit(Cerr);
// Pression mise a 1 sur les aretes seulement
  p=0;
  int sz=p.size_totale();
  for(; i<sz; i++)
    p(i)=1;
  r=0;
  op.ajouter(p, r);
  Cerr << Process::me() << " grad(1) aretes = " << finl;
  r.ecrit(Cerr);
// Pression variable sur les elements seulement
  p=0;
  for(i=0; i<nb_elem_tot; i++)
    p(i)=xp(i,0)-1;
  r=0;
  op.ajouter(p, r);
  int nbf=volumes_entrelaces.size();
  for(i=0; i<nbf; i++)
    for(int comp=0; comp<Objet_U::dimension; comp++)
      r(i,comp)/=volumes_entrelaces(i);
  Cerr << Process::me() << " grad(x-1) elem = " << finl;
  r.ecrit(Cerr);
// Pression variable sur les sommets seulement
  p=0;
  for(i=nb_elem_tot; i<nb_elem_tot+nb_som_tot; i++)
    {
      p(i)=coord_sommets(i-nb_elem_tot,0)-1;
    }
  r=0;
  op.ajouter(p, r);
  for(i=0; i<nbf; i++)
    for(int comp=0; comp<Objet_U::dimension; comp++)
      r(i,comp)/=volumes_entrelaces(i);
  Cerr << Process::me() << " grad(x-1) som = " << finl;
  r.ecrit(Cerr);
  /*
    const IntTab& som_elem=zone.les_elems();
    int nfe=zone.nb_faces_elem();
    p=0;
    int ii=nb_elem_tot+nb_som_tot/2;
    p(ii)=1;
    r=0;
    op.ajouter(p, r);
    Debog::verifier("toto",r);
    for(i=0; i<nbf; i++)
    for(int comp=0; comp<Objet_U::dimension; comp++)
    r(i,comp)/=volumes_entrelaces(i);
    Cerr << "grad(1K) = " << r << finl;
    for(i=0; i<nb_elem_tot; i++)
    for(int indice=0; indice<nfe; indice++)
    {
    int som = nb_elem_tot+dom.get_renum_som_perio(som_elem(i,indice));
    if(som==ii) p(i)+=1./12.;
    }
    r=0;
    op.ajouter(p, r);
    for(i=0; i<nbf; i++)
    for(int comp=0; comp<Objet_U::dimension; comp++)
    r(i,comp)/=volumes_entrelaces(i);
    Cerr << "grad(eta) = " << r << finl;
    }
  */
}
References Op_Grad_VEF_P1B_Face::ajouter(), Cerr, Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), TRUSTTab< _TYPE_ >::ecrit(), exemple_champ_non_homogene(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Process::me(), Zone::nb_elem(), Zone::nb_elem_tot(), Domaine::nb_som_tot(), TRUSTVect< _TYPE_ >::size(), TRUSTVect< _TYPE_ >::size_totale(), Zone_VF::volumes_entrelaces(), Zone_VF::xp(), and Zone_dis_base::zone().
Referenced by Op_Grad_VEF_P1B_Face::ajouter().
Variable Documentation
Op_Grad_VEF_P1B_Facebases
const Type_info* Op_Grad_VEF_P1B_Facebases[1] ={ &(Op_Grad_VEF_Face ::info_obj)}
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.