TRUST: src/P1NCP1B/Operateurs/Op_Div_VEFP1B_Elem.cpp File Reference
src/P1NCP1B/Operateurs/Op_Div_VEFP1B_Elem.cpp File Reference
#include <Op_Div_VEFP1B_Elem.h>
#include <Domaine.h>
#include <Zone_Cl_VEF.h>
#include <Periodique.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Dirichlet_entree_fluide.h>
#include <Symetrie.h>
#include <Neumann.h>
#include <Neumann_val_ext.h>
#include <Zone_VEF_PreP1b.h>
#include <Debog.h>
#include <Probleme_base.h>
#include <Check_espace_virtuel.h>
#include <Schema_Temps_base.h>
#include <Porosites_champ.h>
#include <SChaine.h>
#include <VerifierCoin.h>
#include <SFichier.h>
Functions
static int chercher_arete (int elem, int somi, int somj, const IntTab &elem_aretes, const IntTab &aretes_som)
static int verifier (const Op_Div_VEFP1B_Elem &op, int &init, const Zone_VEF_PreP1b &zone_VEF, const DoubleTab &vit, DoubleTab &div)
int find_cl_face (const Zone &zone, const int face)
double calculer_coef_som (int elem, int &nb_face_diri, ArrOfInt &indice_diri, const Zone_Cl_VEF &zcl, const Zone_VEF &zone_VEF)
Variables
const Type_info * Op_Div_VEFP1B_Elembases [1] = { &(Op_Div_VEF_Elem ::info_obj)}
Function Documentation
double calculer_coef_som (int elem, int & nb_face_diri, ArrOfInt & indice_diri, const Zone_Cl_VEF & zcl, const Zone_VEF & zone_VEF)
Definition at line 159 of file Op_Div_VEFP1B_Elem.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone_VEF::rang_elem_non_std(), type_elem(), and Zone_Cl_VEF::type_elem_Cl().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), and Op_Div_VEFP1B_Elem::ajouter_som().
{
// prov ajouter verif par %2 ....
  int type_elem=0;
  int& dimension= Objet_U::dimension;
  int rang_elem=zone_VEF.rang_elem_non_std()(elem);
  if (rang_elem!=-1)
    type_elem=zcl.type_elem_Cl(rang_elem);
  if ((0)||(type_elem==0))
    {
      nb_face_diri=0;
      double coeff_som=1./(dimension*(dimension+1));
      return coeff_som;
    }
  else
    {
      if (dimension==2)
        {
          switch(type_elem)
            {
            case 1:
              nb_face_diri=1;
              indice_diri[0]=2;
              break;
            case 2:
              nb_face_diri=1;
              indice_diri[0]=1;
              break;
            case 4:
              nb_face_diri=1;
              indice_diri[0]=0;
              break;
            case 3:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=2;
              break;
            case 5:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=2;
              break;
            case 6:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=1;
              break;
            default:
              nb_face_diri=10000;
              Cerr<<__FILE__<<(int)__LINE__<<" impossible "<<finl;
              Process::exit();
              break;
            }
        }
      else if (dimension==3)
        {
          switch(type_elem)
            {
            case 1:
              nb_face_diri=1;
              indice_diri[0]=3;
              break;
            case 2:
              nb_face_diri=1;
              indice_diri[0]=2;
              break;
            case 4:
              nb_face_diri=1;
              indice_diri[0]=1;
              break;
            case 8:
              nb_face_diri=1;
              indice_diri[0]=0;
              break;
            case 3:
              nb_face_diri=2;
              indice_diri[0]=3;
              indice_diri[1]=2;
              break;
            case 5:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=3;
              break;
            case 6:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=2;
              break;
            case 9:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=3;
              break;
            case 10:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=2;
              break;
            case 12:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=1;
              break;
            case 7:
              nb_face_diri=3;
              indice_diri[0]=1;
              indice_diri[1]=2;
              indice_diri[2]=3;
              break;
            case 11:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=2;
              indice_diri[2]=3;
              break;
            case 13:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=1;
              indice_diri[2]=3;
              break;
            case 14:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=1;
              indice_diri[2]=2;
              break;
            default:
              nb_face_diri=10000;
              Cerr<<__FILE__<<(int)__LINE__<<" impossible "<<finl;
              Process::exit();
              break;
            }
        }
      else
        {
          nb_face_diri=10000;
          abort();
          Process::exit();
        }
    }
  double coeff_som=1./(dimension*(dimension+1-nb_face_diri));
  return coeff_som;
}
static int chercher_arete (int elem, int somi, int somj, const IntTab & elem_aretes, const IntTab & aretes_som) [static]
Definition at line 57 of file Op_Div_VEFP1B_Elem.cpp.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes().
{
  if(somi>somj)
    {
      int k=somi;
      somi=somj;
      somj=k;
    }
  for(int i_arete=0; i_arete<6; i_arete++)
    {
      int arete=elem_aretes(elem, i_arete);
      int som1=aretes_som(arete,0);
      if(somi==som1)
        {
          int som2=aretes_som(arete,1);
          if(somj==som2)
            return arete;
        }
    }
  return -1;
}
int find_cl_face (const Zone & zone, const int face)
Definition at line 140 of file Op_Div_VEFP1B_Elem.cpp.
References Zone::frontiere(), Frontiere::get_faces_virt(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Frontiere::num_premiere_face(), and ArrOfInt::size_array().
Referenced by Op_Div_VEFP1B_Elem::degres_liberte().
{
  int i;
  const int nb_cl = zone.nb_front_Cl();
  for (i = 0; i < nb_cl; i++)
    {
      const Frontiere& fr = zone.frontiere(i);
      const int debut = fr.num_premiere_face();
      if (face >= debut && face < debut + fr.nb_faces())
        return i;
      const ArrOfInt& faces_virt = fr.get_faces_virt();
      const int nb_faces_virt = faces_virt.size_array();
      for (int j = 0; j < nb_faces_virt; j++)
        if (face == faces_virt[j])
          return i;
    }
  return -1;
}
static int verifier (const Op_Div_VEFP1B_Elem & op, int & init, const Zone_VEF_PreP1b & zone_VEF, const DoubleTab & vit, DoubleTab & div) [static]
Definition at line 81 of file Op_Div_VEFP1B_Elem.cpp.
References Op_Div_VEFP1B_Elem::ajouter(), Cerr, DoubleTab::dimension(), finl, Debog::verifier(), and Zone_VF::xv().
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_EF::ajouter(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Solveur_Masse_base::appliquer(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_VEFPreP1B::assembler_mat(), Champ_Q1NC::cal_rot_ordre1(), Champ_Q1_EF::cal_rot_ordre1(), Op_Dift_standard_VEF_Face::calcul_divergence(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_Cp(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Equation_base::calculer_pas_de_temps(), EOS_Tools_VDF::calculer_rho_face_np1(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Equation_base::completer(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Champ_P1iP1B_implementation::filtrage(), Champ_P1NC_implementation::filtrer_L2(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_CoviMAC::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Piso::iterer_NS(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Navier_Stokes_std::mettre_a_jour(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_solution(), Assembleur_P_EF::modifier_solution(), Assembleur_P_CoviMAC::modifier_solution(), Navier_Stokes_std::preparer_calcul(), Equation_base::preparer_calcul(), Navier_Stokes_std::projeter(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), EOS_Tools_VEF::secmembre_divU_Z(), EOS_Tools_VDF::secmembre_divU_Z(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
{
  init=1;
  DoubleTab v(vit);
  v=1;
  DoubleTab r(div);
  r=0;
  op.ajouter(v, r);
  Cerr << "div(1,..,1) = " << r << finl;
  Debog::verifier("div(1,..,1) =",r);
  const DoubleTab& xv = zone_VEF.xv();
  v=xv;
  {
    for (int i=0; i< v.dimension(0); i++)
      v(i,1)=0;
  }
  r=0;
  op.ajouter(v, r);
  Cerr << "div(x,0) = " << r << finl;
  Debog::verifier("div(x,0) =",r);
  return 1;
}
Variable Documentation
const Type_info* Op_Div_VEFP1B_Elembases[1] = { &(Op_Div_VEF_Elem ::info_obj)}
Definition at line 43 of file Op_Div_VEFP1B_Elem.cpp.