TRUST: src/VEF/Operateurs/Op_Dift_Stab_VEF_Face.cpp File Reference
Op_Dift_Stab_VEF_Face.cpp File Reference
#include <Op_Dift_Stab_VEF_Face.h>
#include <Champ_P1NC.h>
#include <Periodique.h>
#include <Neumann_paroi.h>
#include <Echange_externe_impose.h>
#include <Neumann_homogene.h>
#include <Symetrie.h>
#include <Neumann_sortie_libre.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Scalaire_impose_paroi.h>
#include <Debog.h>
#include <TRUSTTrav.h>
#include <Check_espace_virtuel.h>
#include <Porosites_champ.h>
#include <Modele_turbulence_scal_base.h>
Functions
double my_minimum (double a, double b, double c)
double my_maximum (double a, double b, double c)
double my_minimum (double a, double b)
double my_maximum (double a, double b)
Variables
const Type_info * Op_Dift_Stab_VEF_Facebases [1] ={ &(Op_Dift_VEF_Face ::info_obj)}
Function Documentation
my_maximum() [1/2]
double my_maximum (double a, double b)
Definition at line 60 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (a>=b) return a;
  else return b;
}
my_maximum() [2/2]
double my_maximum (double a, double b, double c)
Definition at line 45 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (a>=b)
    if (a>=c) return a;
    else return c;
  else if (b>=c) return b;
  else return c;
}
Referenced by Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), and Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel().
my_minimum() [1/2]
double my_minimum (double a, double b)
Definition at line 54 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (a<=b) return a;
  else return b;
}
my_minimum() [2/2]
double my_minimum (double a, double b, double c)
Definition at line 36 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (a<=b)
    if (a<=c) return a;
    else return c;
  else if (b<=c) return b;
  else return c;
}
Referenced by Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), and Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel().
Variable Documentation
Op_Dift_Stab_VEF_Facebases
const Type_info* Op_Dift_Stab_VEF_Facebases[1] ={ &(Op_Dift_VEF_Face ::info_obj)}
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.