TRUST: src/EF/Operateurs/Op_Diff_EF.cpp File Reference
src/EF/Operateurs/Op_Diff_EF.cpp File Reference
#include <Op_Diff_EF.h>
#include <Zone_EF.h>
#include <Zone_Cl_EF.h>
#include <Champ_Uniforme.h>
#include <Milieu_base.h>
#include <Debog.h>
#include <DoubleTrav.h>
#include <Probleme_base.h>
#include <Neumann_paroi.h>
#include <Neumann_sortie_libre.h>
#include <Echange_global_impose.h>
#include <Param.h>
#include <Op_Conv_EF.h>
Defines
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define bij_(elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som, a) inco_ptr[som * N + a]
#define resu_(som, a) resu_ptr[som * N + a]
#define matrice_coef(i, j) matrice.coef(i,j)
Functions
void remplir_marqueur_sommet_neumann (ArrOfInt &marqueur, const Zone_EF &zone_EF, const Zone_Cl_EF &zone_Cl_EF, int transpose_partout)
double & coeff_opt (Matrice_Morse &matrice, int i, int j)
Variables
const Type_info * Op_Diff_EFbases [1] = { &(Op_Diff_EF_base ::info_obj)}
const Type_info * Op_Diff_option_EFbases [1] = { &(Op_Diff_EF ::info_obj)}
Define Documentation
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define bij_ (elem, i, j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_ (som, a) inco_ptr[som * N + a]
#define inconnue_ (som, a) inco_ptr[som * N + a]
Referenced by Op_Diff_EF::ajouter_scalaire_dim2_nbn_4(), Op_Diff_EF::ajouter_scalaire_dim3_nbn_8(), Op_Diff_EF::ajouter_scalaire_gen(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), and Op_Diff_EF::ajouter_vectoriel_gen().
#define inconnue_ (som, a) inco_ptr[som * N + a]
#define inconnue_ (som, a) inco_ptr[som * N + a]
#define inconnue_ (som, a) inco_ptr[som * N + a]
#define inconnue_ (som, a) inco_ptr[som * N + a]
#define matrice_coef (i, j) matrice.coef(i,j)
Definition at line 826 of file Op_Diff_EF.cpp.
Referenced by Op_Diff_EF::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), and Op_Diff_EF::ajouter_contributions_bords().
#define resu_ (som, a) resu_ptr[som * N + a]
#define resu_ (som, a) resu_ptr[som * N + a]
#define resu_ (som, a) resu_ptr[som * N + a]
#define resu_ (som, a) resu_ptr[som * N + a]
#define resu_ (som, a) resu_ptr[som * N + a]
#define resu_ (som, a) resu_ptr[som * N + a]
Function Documentation
double& coeff_opt (Matrice_Morse & matrice, int i, int j) [inline]
Definition at line 807 of file Op_Diff_EF.cpp.
References Cerr, Process::exit(), finl, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_colonnes(), and Matrice_Morse::nb_lignes().
{
  const IntVect& tab1_=matrice.get_tab1();
  const IntVect& tab2_=matrice.get_tab2();
  int k1=tab1_[i]-1;
  int k2=tab1_[i+1]-1;
  int k;
  for (k=k1; k<k2; k++)
    if (tab2_[k]-1 == j) return(matrice.get_set_coeff()(k));
  Cerr << "i ou j ne conviennent pas " << finl;
  Cerr << "i=" << i << finl;
  Cerr << "j=" << j << finl;
  Cerr << "n_lignes=" << matrice.nb_lignes() << finl;
  Cerr << "n_colonnes=" << matrice.nb_colonnes() << finl;
  assert( k<tab1_[i]-1);
  Process::exit();
  return coeff_opt(matrice,i,j);
}
void remplir_marqueur_sommet_neumann (ArrOfInt & marqueur, const Zone_EF & zone_EF, const Zone_Cl_EF & zone_Cl_EF, int transpose_partout)
Definition at line 91 of file Op_Diff_EF.cpp.
References Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone_VF::nb_som_face(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), ref_cast, ArrOfInt::resize_array(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Op_Diff_EF::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), and Op_Diff_EF::ajouter_vectoriel_gen().
{
  marqueur.resize_array(zone_EF.nb_som_tot());
  if ( transpose_partout) return;
// Neumann :
  int n_bord;
  int nb_bords=zone_EF.nb_front_Cl();
  const IntTab& face_sommets=zone_EF.face_sommets();
  int nb_som_face=zone_EF.nb_som_face();
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nfin =le_bord.nb_faces_tot();
          for (int ind_face=0; ind_face<nfin; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  marqueur(glob2)=1;
                }
            }
        }
    }
}
Variable Documentation
const Type_info* Op_Diff_EFbases[1] = { &(Op_Diff_EF_base ::info_obj)}
Definition at line 42 of file Op_Diff_EF.cpp.
const Type_info* Op_Diff_option_EFbases[1] = { &(Op_Diff_EF ::info_obj)}
Definition at line 61 of file Op_Diff_EF.cpp.