TRUST: src/VDF/Operateurs/Op_VDF_Face.cpp File Reference
src/VDF/Operateurs/Op_VDF_Face.cpp File Reference
#include <Op_VDF_Face.h>
#include <Zone_VDF.h>
#include <Zone_Cl_VDF.h>
#include <Periodique.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Symetrie.h>
#include <Matrice_Morse.h>
#include <Equation_base.h>
#include <Champ_Inc.h>
Functions
int face_bord_amont2 (const Zone_VDF &la_zone, int num_face, int k, int i)
Function Documentation
int face_bord_amont2 (const Zone_VDF & la_zone, int num_face, int k, int i) [inline]
Definition at line 35 of file Op_VDF_Face.cpp.
References Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), and Zone_VDF::orientation().
Referenced by Op_VDF_Face::dimensionner().
{
  int ori = la_zone.orientation(num_face);
  int elem = la_zone.face_voisins(num_face,0);
  if(elem != -1)
    {
      int face = la_zone.elem_faces(elem, k+i*Objet_U::dimension);
      int elem_bis = la_zone.face_voisins(face,i);
      if (elem_bis != -1)
        elem = la_zone.elem_faces(elem_bis, ori+Objet_U::dimension);
      else
        elem = -1;
    }
  else
    {
      Process::exit();
    }
  return elem;
}