TRUST: src/VEF/Operateurs/Op_Conv_kschemas_VEF.cpp File Reference
src/VEF/Operateurs/Op_Conv_kschemas_VEF.cpp File Reference
#include <Op_Conv_kschemas_VEF.h>
Functions
void convkschemas (const double K, const int ncomp, int dimension, const int poly, const int poly1, const int poly2, const int jel0, const int jel1, const double &psc, const DoubleTab &tab1, DoubleVect &fluent, DoubleVect &flux, const DoubleVect &rx0, const DoubleTab &gradient_elem)
Variables
const Type_info * Op_Conv_kschemas_VEFbases [1] = { &(Op_Conv_VEF_base ::info_obj)}
Function Documentation
void convkschemas (const double K, const int ncomp, int dimension, const int poly, const int poly1, const int poly2, const int jel0, const int jel1, const double & psc, const DoubleTab & tab1, DoubleVect & fluent, DoubleVect & flux, const DoubleVect & rx0, const DoubleTab & gradient_elem)
Definition at line 68 of file Op_Conv_kschemas_VEF.cpp.
References dabs(), and Process::exit().
Referenced by Op_Conv_kschemas_VEF::ajouter().
{
  int comp,amont,i,elem1,elem2;
  double CF,UTC,deltat0,deltat1,deltat;
  DoubleVect rx(dimension);
  deltat0 = 0.;
  deltat1 = 0.;
//
// Test sur les bords
//
  if ((poly1==-1) || (poly2==-1))
    {
      if (psc >= 0)
        {
          amont = jel0;
          fluent[jel1] += psc;
        }
      else
        {
          amont = jel1;
          fluent[jel0] -= psc;
        }
      for (comp=0; comp<ncomp; comp++)
        flux(comp) = tab1(amont,comp);
    }
  else
    {
      if (psc >= 0)
        {
          amont = jel0;
          rx = rx0;
          elem1 = poly;
          elem2 = poly1;
          fluent(jel1)  += psc;
        }
      else
        {
          amont = jel1;
          rx = rx0;
          rx *= -1.;
          elem1 = poly;
          elem2 = poly2;
          fluent(jel0)  -= psc;
        }
      for (comp=0; comp<ncomp; comp++)
        {
          deltat0 = deltat1 = 0.0;
          flux(comp) = tab1(amont,comp);
// Cerr << " flux(" << comp << ") ie phiamont= " <<  flux(comp) << finl;
          for (i=0; i<dimension; i++)
            {
              deltat0 += gradient_elem(elem1,comp,i)*rx(i);
              deltat1 += gradient_elem(elem2,comp,i)*rx(i);
            }
          if (K == 0.5)
            {
              deltat = deltat0 + deltat1;
              if  (dabs(deltat) <= 1.e-5)
                {
                  CF = 0.125;
                }
              else
                {
                  UTC = deltat1 / deltat;
                  if ( (UTC <= -1.) || (UTC >= 1.5) )      CF = 0.125;
                  else if ((UTC > -1.) && (UTC <= 0.))     CF = 0.5 + 0.375*UTC;
                  else if ((UTC > 0.) && (UTC <= 0.25))    CF = 0.5 - 0.625*sqrt(UTC);
                  else if ((UTC > 0.25) && (UTC < 1.5 ))   CF = 0.25* dabs(UTC - 1.);
                  else
                    {
                      CF=0.;
                      Process::exit();
                    }
                }
// Calcul du flux
              flux(comp) += (0.5 - CF)*deltat0 + CF*deltat1 ;
// Cerr << " flux(" << comp << ")= " <<  flux(comp) << finl;
            }
          else
            {
// Calcul du flux
              flux(comp) += 0.25*((1.+K)*deltat0 + (1.-K)*deltat1) ;
            }
        }
    }
}
Variable Documentation
const Type_info* Op_Conv_kschemas_VEFbases[1] = { &(Op_Conv_VEF_base ::info_obj)}
Definition at line 25 of file Op_Conv_kschemas_VEF.cpp.