TRUST: src/Kernel/Utilitaires/Param.cpp File Reference
src/Kernel/Utilitaires/Param.cpp File Reference
#include <Param.h>
#include <Parser_U.h>
#include <ArrOfInt.h>
#include <ArrOfDouble.h>
Functions
List_Nom split_mot (const Nom &nom)
Objet_a_lire::Nature convert_nature (Param::Nature nat)
Function Documentation
Objet_a_lire::Nature convert_nature (Param::Nature nat)
Definition at line 378 of file Param.cpp.
References Objet_a_lire::OPTIONAL, Objet_a_lire::REQUIRED, and Param::REQUIRED.
Referenced by Param::ajouter(), Param::ajouter_arr_size_predefinie(), Param::ajouter_deriv(), Param::ajouter_flag(), Param::ajouter_non_std(), and Param::ajouter_param().
{
  if (nat==Param::REQUIRED)
    return Objet_a_lire::REQUIRED;
  else
    return Objet_a_lire::OPTIONAL;
}
List_Nom split_mot (const Nom & nom)
Definition at line 277 of file Param.cpp.
References LIST, Nom::prefix(), and Nom::suffix().
Referenced by Param::create_or_get_objet_a_lire(), and Param::supprimer().
{
  LIST(Nom) res;
  Nom n0(nom);
// on cherche le dernier |
  const char * marq= strchr(n0,'|');
  while (marq)
    {
      Nom n1(n0);
      n1.prefix(marq);
      res.add(n1);
      marq++;
      Nom n1b(n0);
      n1b.prefix(marq);
      Nom n2(n0);
      n2.suffix(n1b);
// Cerr<<" IIIII "<< n0 <<" "<<n1<<" "<<n2<<finl;
      n0=n2;
      marq= strchr(n0,'|');
    }
// Cerr<<" "<<n0<<finl;
  res.add(n0);
// Cerr<<"YYY "<<res<<finl;
  return res;
}