TRUST: src/Kernel/Math/Parser.cpp File Reference
Parser.cpp File Reference
#include <Parser.h>
#include <StdFunction.h>
#include <StringTokenizer.h>
Functions
void debug (StringTokenizer *)
void destroy (PNode *p)
Function Documentation
debug()
void debug (StringTokenizer * t)
Definition at line 724 of file Parser.cpp.
{
  if (t->type == StringTokenizer::STRING)
    Cout << "STRING : " << t->getSValue() << finl;
  else if (t->type == StringTokenizer::NUMBER)
    Cout << "NUMBER : " << t->getNValue() << finl;
  else if (t->type == StringTokenizer::EOS)
    Cout << "END " << finl;
  else
    Cout << "OP : " << (int)t->type << finl;
}
References Cout, StringTokenizer::EOS, finl, StringTokenizer::getNValue(), StringTokenizer::getSValue(), StringTokenizer::NUMBER, StringTokenizer::STRING, and StringTokenizer::type.
Referenced by Raffiner_isotrope_parallele::interpreter().
destroy()
void destroy (PNode * p)
Definition at line 136 of file Parser.cpp.
{
  if (p!=NULL)
    {
      if (p->left!=NULL) destroy(p->left);
      if (p->right!=NULL) destroy(p->right);
      delete p;
      p=NULL;
    }
}
References destroy(), PNode::left, and PNode::right.
Referenced by destroy(), Parser::parseString(), and Parser::~Parser().