TRUST: src/Kernel/Geometrie/Decoupeur/Partitionneur_base.cpp File Reference
Partitionneur_base.cpp File Reference
#include <Partitionneur_base.h>
#include <Domaine.h>
#include <Connectivite_som_elem.h>
#include <Static_Int_Lists.h>
#include <Reordonner_faces_periodiques.h>
#include <ArrOfBit.h>
#include <Array_tools.h>
#include <Param.h>
#include <TRUSTLists.h>
#include <communications.h>
Functions
static void chercher_elems_voisins_faces (const Static_Int_Lists &som_elem, const IntTab &faces, const Nom &nom_faces, ArrOfInt &elements)
construction (taille et contenu) du tableau elements avec
pour chaque face du bord donne, l'indice de l'element de la zone adjacent
a cette face.
Parametre: som_elem
Signification: connectivite sommet-elements de la zone, calculee a l'aide
de construire_connectivite_som_elem
Parametre: faces
Signification: les faces du bord a traiter (pour chaque face, indices des sommets)
Parametre: nom_faces
Signification: un nom de bord a imprimer en cas d'erreur
Parametre: elements
Signification: le tableau a remplir.
Variables
const Type_info * Deriv_Partitionneur_basebases [1] ={ &(Deriv_ ::info_obj)}
const Type_info * Partitionneur_basebases [1] ={ &(Objet_U ::info_obj)}
Function Documentation
chercher_elems_voisins_faces()
static void chercher_elems_voisins_faces (const Static_Int_Lists & som_elem, const IntTab & faces, const Nom & nom_faces, ArrOfInt & elements) static
construction (taille et contenu) du tableau elements avec
pour chaque face du bord donne, l'indice de l'element de la zone adjacent
a cette face.
Parametre: som_elem
Signification: connectivite sommet-elements de la zone, calculee a l'aide
de construire_connectivite_som_elem
Parametre: faces
Signification: les faces du bord a traiter (pour chaque face, indices des sommets)
Parametre: nom_faces
Signification: un nom de bord a imprimer en cas d'erreur
Parametre: elements
Signification: le tableau a remplir.
Definition at line 96 of file Partitionneur_base.cpp.
{
  const int nb_faces = faces.dimension(0);
  elements.resize_array(nb_faces);
  if (nb_faces == 0)
    return;
  const int nb_som_faces = faces.dimension(1);
  ArrOfInt une_face(nb_som_faces);
  ArrOfInt voisins;
  for (int i = 0; i < nb_faces; i++)
    {
      for (int j = 0; j < nb_som_faces; j++)
        une_face[j] = faces(i, j);
      find_adjacent_elements(som_elem, une_face, voisins);
      const int nb_voisins = voisins.size_array();
      if (nb_voisins != 1)
        {
          Cerr << "Error in chercher_elems_voisins_faces : the face " << i
               << "\n of boundary " << nom_faces << " has " << nb_voisins
               << " neighboring elements with the indices : " << voisins << finl;
          Process::exit();
        }
      elements[i] = voisins[0];
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), find_adjacent_elements(), finl, TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_base::corriger_multiperiodique(), and Partitionneur_base::corriger_sommets_bord().
Variable Documentation
Deriv_Partitionneur_basebases
const Type_info* Deriv_Partitionneur_basebases[1] ={ &(Deriv_ ::info_obj)}
Definition at line 26 of file Partitionneur_base.cpp.
Partitionneur_basebases
const Type_info* Partitionneur_basebases[1] ={ &(Objet_U ::info_obj)}
Definition at line 28 of file Partitionneur_base.cpp.