TRUST: src/Kernel/Geometrie/Decoupeur/Partitionneur_Tranche.cpp File Reference
Partitionneur_Tranche.cpp File Reference
#include <Reordonner_faces_periodiques.h>
#include <Partitionneur_Tranche.h>
#include <TRUSTArray.h>
#include <Domaine.h>
#include <Param.h>
Functions
static True_int trier_index_compare_fct (const void *i_, const void *j_)
fonction outil pour tri quicksort<br>(comparaison de deux reels avec un index)
static void trier_index_colonne_i (const DoubleTab &tab, ArrOfInt &index, const int colonne)
Fonction outil utilisee dans construire_partition.
On reordonne les valeurs du tableau index de sorte que les valeurs
tab(index[i], colonne) soient classees dans l'ordre croissant.
Variables
const Type_info * Partitionneur_Tranchebases [1] ={ &(Partitionneur_base ::info_obj)}
static const DoubleTab * static_qsort_DoubleTab_ptr
static int static_qsort_DoubleTab_colonne
Function Documentation
trier_index_colonne_i()
static void trier_index_colonne_i (const DoubleTab & tab, ArrOfInt & index, const int colonne) static
Fonction outil utilisee dans construire_partition.
On reordonne les valeurs du tableau index de sorte que les valeurs
tab(index[i], colonne) soient classees dans l'ordre croissant.
Definition at line 105 of file Partitionneur_Tranche.cpp.
{
  assert(colonne >= 0 && colonne < tab.dimension(1));
  static_qsort_DoubleTab_ptr = &tab;
  static_qsort_DoubleTab_colonne = colonne;
  int * index_ptr = index.addr();
  const int index_size = index.size_array();
  const int index_member_size = sizeof(int);
  qsort(index_ptr, index_size, index_member_size, trier_index_compare_fct);
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), TRUSTArray< _TYPE_ >::size_array(), static_qsort_DoubleTab_colonne, static_qsort_DoubleTab_ptr, and trier_index_compare_fct().
Referenced by Partitionneur_Tranche::construire_partition().
trier_index_compare_fct()
static True_int trier_index_compare_fct (const void * i_, const void * j_) static
fonction outil pour tri quicksort<br>(comparaison de deux reels avec un index)
Definition at line 86 of file Partitionneur_Tranche.cpp.
{
  const int i = *((int*)i_);
  const int j = *((int*)j_);
  const int k = static_qsort_DoubleTab_colonne;
  const DoubleTab& tab = *static_qsort_DoubleTab_ptr;
  const double x = tab(i,k);
  const double y = tab(j,k);
  True_int resu = 0;
  if (x > y)
    resu = 1;
  else if (x < y)
    resu = -1;
  return resu;
}
References static_qsort_DoubleTab_colonne, and static_qsort_DoubleTab_ptr.
Referenced by trier_index_colonne_i().
Variable Documentation
Partitionneur_Tranchebases
const Type_info* Partitionneur_Tranchebases[1] ={ &(Partitionneur_base ::info_obj)}
Definition at line 22 of file Partitionneur_Tranche.cpp.
static_qsort_DoubleTab_colonne
int static_qsort_DoubleTab_colonne static
Definition at line 82 of file Partitionneur_Tranche.cpp.
Referenced by trier_index_colonne_i(), and trier_index_compare_fct().
static_qsort_DoubleTab_ptr
const DoubleTab* static_qsort_DoubleTab_ptr static
Definition at line 81 of file Partitionneur_Tranche.cpp.
Referenced by trier_index_colonne_i(), and trier_index_compare_fct().