TRUST: src/Kernel/ICoCo/Pilote_ICoCo.cpp File Reference
src/Kernel/ICoCo/Pilote_ICoCo.cpp File Reference
#include <Pilote_ICoCo.h>
#include <ICoCoTrioField.h>
#include <ProblemTrio.h>
#include <Param.h>
#include <Probleme_U.h>
Functions
void main_pilote_icoco_1 (Probleme_U &pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo
On lui fournit a chaque pas de temps les champs
d'entree "pression_sortie" et "vitesse_entree"
qui sont respectivement un ch_front_input et un ch_front_input_uniforme
Montre l'utilisation de l'avance en temps et des input fields.
void main_pilote_icoco_2 (Probleme_U &pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo.
On lui fournit a chaque pas de temps le champ
d'entree "puissance" qui est un Champ_input_P0
Montre l'utilisation de l'avance en temps et des input fields.
void main_abort (Probleme_U &pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo
Le troisieme pas de temps est effectue deux fois.
Variables
const Type_info * Pilote_ICoCobases [1] = { &(Interprete ::info_obj)}
Function Documentation
void main_abort (Probleme_U & pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo
Le troisieme pas de temps est effectue deux fois.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
< Does the Problem want to stop ?
< Is the time interval successfully solved ?
< Loop on timesteps
< Loop on timestep tries
< The resolution failed, try with a new time interval
< validate and go to the next time step
Definition at line 317 of file Pilote_ICoCo.cpp.
References ICoCo::ProblemTrio::abortTimeStep(), Cerr, ICoCo::ProblemTrio::computeTimeStep(), finl, ICoCo::ProblemTrio::getInputFieldTemplate(), ICoCo::ProblemTrio::initialize_pb(), ICoCo::ProblemTrio::initTimeStep(), ICoCo::ProblemTrio::setInputField(), ICoCo::ProblemTrio::solveTimeStep(), ICoCo::ProblemTrio::terminate(), and ICoCo::ProblemTrio::validateTimeStep().
Referenced by Pilote_ICoCo::interpreter().
{
// char* pb_name=nom1.getChar();
  ProblemTrio pb;
// pb.setDataFile(pb_name);
  pb.initialize_pb(pb_to_solve);
  bool stop=false; //!< Does the Problem want to stop ?
  bool ok=true; //!< Is the time interval successfully solved ?
  int n=0;
// loop on time step
  while (!stop)                       //!< Loop on timesteps
    {
      ok=false;
      while (!ok && !stop)                  //!< Loop on timestep tries
        {
// compute time step length
          double dt=pb.computeTimeStep(stop);
          if (stop)
            break;
// prepare the new time step
          pb.initTimeStep(dt);
// ---------------------
// Solve next time step
// ---------------------
          {
            TrioField afield;
            int nb_elems;
            pb.getInputFieldTemplate("temperature_bord",afield);
            afield.set_standalone();
            nb_elems=afield._nb_elems;
            for (int i=0; i<nb_elems; i++)
              afield._field[i]=600;
            pb.setInputField("temperature_bord",afield);
          }
          bool ok2=pb.solveTimeStep();
          n++;
          if (!ok2 || n==3)   //!< The resolution failed, try with a new time interval
            {
              Cerr<<" call of abortTimeStep" <<finl;
              pb.abortTimeStep();
            }
          else   //!< validate and go to the next time step
            {
              pb.validateTimeStep();
            }
        }                                     //!< End loop on timestep size
    }                                   //!< End loop on timesteps
  pb.terminate();
}
void main_pilote_icoco_1 (Probleme_U & pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo
On lui fournit a chaque pas de temps les champs
d'entree "pression_sortie" et "vitesse_entree"
qui sont respectivement un ch_front_input et un ch_front_input_uniforme
Montre l'utilisation de l'avance en temps et des input fields.
< Does the Problem want to stop ?
< Is the time interval successfully solved ?
< Is the time interval successfully solved ?
< ch_front_input_uniforme in the data file
< The resolution failed, try with a new time interval.
< The resolution was successful, validate and go to the next time step.
< Impossible to solve the next time step, the Problem
< has given up
Definition at line 96 of file Pilote_ICoCo.cpp.
References ICoCo::ProblemTrio::abortTimeStep(), ICoCo::ProblemTrio::computeTimeStep(), ICoCo::ProblemTrio::getInputFieldsNames(), ICoCo::ProblemTrio::getInputFieldTemplate(), ICoCo::ProblemTrio::initialize_pb(), ICoCo::ProblemTrio::initTimeStep(), ICoCo::ProblemTrio::isStationary(), Probleme_U::le_nom(), ICoCo::ProblemTrio::presentTime(), ICoCo::ProblemTrio::setInputField(), ICoCo::ProblemTrio::solveTimeStep(), ICoCo::ProblemTrio::terminate(), and ICoCo::ProblemTrio::validateTimeStep().
Referenced by Pilote_ICoCo::interpreter().
{
  ProblemTrio pb;
  Nom pb_name=pb_to_solve.le_nom();
  pb.initialize_pb(pb_to_solve);
  bool stop=false; //!< Does the Problem want to stop ?
  bool ok=true; //!< Is the time interval successfully solved ?
// Compute the first time step length
  double dt=pb.computeTimeStep(stop);
// Loop on the time steps
  while(!stop)
    {
      ok=false; //!< Is the time interval successfully solved ?
// Loop on the time interval tries
      while (!ok && !stop)
        {
// Prepare the next time step
          ok=pb.initTimeStep(dt);
          if (!ok)
            break;
// Example of field exchange
          {
            vector<string> sv=pb.getInputFieldsNames();
            cout << "Input Fields for " << pb_name << " :" << endl;
            for (unsigned i=0; i<sv.size(); i++)
              std::cout << i << ". " << sv[i] << std::endl;
            TrioField afield;
            int nb_elems,nb_comp;
// Get the right geometry & nbcomp for "pression_sortie"
            pb.getInputFieldTemplate("pression_sortie",afield);
// Allocate memory for the values (size=nb_elems*nb_comp)
            afield.set_standalone();
// Fill the values
            nb_elems=afield._nb_elems;
            nb_comp=afield._nb_field_components;
            assert(nb_comp==1);
            for (int i=0; i<nb_elems; i++)
              afield._field[i]=0;
// Give the field to the problem
            pb.setInputField("pression_sortie",afield);
// Get the right geometry & nbcomp for "vitesse_entree"
            pb.getInputFieldTemplate("vitesse_entree",afield);
// Allocate memory for the values (size=nb_elems*nb_comp)
            afield.set_standalone();
// Fill the values
            nb_elems=afield._nb_elems;
            nb_comp=afield._nb_field_components;
            assert(nb_elems==1); //!< ch_front_input_uniforme in the data file
            double t=pb.presentTime();
            t+=dt;
            double vx=(t>100)?100:t;
            for (int i=0; i<nb_elems; i++)
              for (int j=0; j<afield._nb_field_components; j++)
                afield._field[i*nb_comp+j]=(j==0)?vx:0;
// Give the field to the problem
            pb.setInputField("vitesse_entree",afield);
          }
// Solve the next time step
          ok=pb.solveTimeStep();
          if (!ok)   //!< The resolution failed, try with a new time interval.
            {
              pb.abortTimeStep();
              dt=pb.computeTimeStep(stop);
            }
          else //!< The resolution was successful, validate and go to the next time step.
//
            pb.validateTimeStep();
        }
      if (!ok) //!< Impossible to solve the next time step, the Problem
        break; //!< has given up
// Compute the next time step length
      dt=pb.computeTimeStep(stop);
// Stop the resolution if the Problem is stationnary
      if (pb.isStationary())
        stop=true;
    }
  pb.terminate();
}
void main_pilote_icoco_2 (Probleme_U & pb_to_solve)
Fonction principale de l'interprete:
resoudre un probleme
Le probleme est pilote via l'interface ICoCo.
On lui fournit a chaque pas de temps le champ
d'entree "puissance" qui est un Champ_input_P0
Montre l'utilisation de l'avance en temps et des input fields.
< Does the Problem want to stop ?
< Is the time interval successfully solved ?
< Is the time interval successfully solved ?
< The resolution failed, try with a new time interval.
< The resolution was successful, validate and go to the next time step.
< Impossible to solve the next time step, the Problem
< has given up
Definition at line 204 of file Pilote_ICoCo.cpp.
References ICoCo::ProblemTrio::abortTimeStep(), ICoCo::ProblemTrio::computeTimeStep(), ICoCo::ProblemTrio::getInputFieldsNames(), ICoCo::ProblemTrio::getInputFieldTemplate(), ICoCo::ProblemTrio::initialize_pb(), ICoCo::ProblemTrio::initTimeStep(), ICoCo::ProblemTrio::isStationary(), Probleme_U::le_nom(), ICoCo::ProblemTrio::setInputField(), ICoCo::ProblemTrio::solveTimeStep(), ICoCo::ProblemTrio::terminate(), and ICoCo::ProblemTrio::validateTimeStep().
Referenced by Pilote_ICoCo::interpreter().
{
  ProblemTrio pb;
  Nom pb_name=pb_to_solve.le_nom();
  pb.initialize_pb(pb_to_solve);
  bool stop=false; //!< Does the Problem want to stop ?
  bool ok=true; //!< Is the time interval successfully solved ?
// Compute the first time step length
  double dt=pb.computeTimeStep(stop);
// Loop on the time steps
  while(!stop)
    {
      ok=false; //!< Is the time interval successfully solved ?
// Loop on the time interval tries
      while (!ok && !stop)
        {
// Prepare the next time step
          ok=pb.initTimeStep(dt);
          if (!ok)
            break;
// Example of field exchange
          {
            vector<string> sv=pb.getInputFieldsNames();
            cout << "Input Fields for " << pb_name << " :" << endl;
            for (unsigned i=0; i<sv.size(); i++)
              std::cout << i << ". " << sv[i] << std::endl;
            TrioField afield;
            int nb_elems;
// Get the right geometry & nbcomp for "puissance"
            pb.getInputFieldTemplate("puissance",afield);
// Allocate memory for the values (size=nb_elems*nb_comp)
            afield.set_standalone();
// Fill the values
            nb_elems=afield._nb_elems;
// nb_comp=afield._nb_field_components;
            assert(afield._nb_field_components==1);
            assert(afield._space_dim==2);
            for (int i=0; i<nb_elems; i++)
              {
// Find gravity center of the element.
                double x=0,y=0;
                for (int j=0; j<afield._nodes_per_elem; j++)
                  {
                    int som=afield._connectivity[afield._nodes_per_elem*i+j];
                    x+=afield._coords[som*2];
                    y+=afield._coords[som*2+1];
                  }
                x/=afield._nodes_per_elem;
                y/=afield._nodes_per_elem;
                afield._field[i]=(((x-0.5)*(x-0.5)+(y-0.5)*(y-0.5))<0.3*0.3)*10;
              }
// Give the field to the problem
            pb.setInputField("puissance",afield);
          }
// Solve the next time step
          ok=pb.solveTimeStep();
          if (!ok)   //!< The resolution failed, try with a new time interval.
            {
              pb.abortTimeStep();
              dt=pb.computeTimeStep(stop);
            }
          else //!< The resolution was successful, validate and go to the next time step.
//
            pb.validateTimeStep();
        }
      if (!ok) //!< Impossible to solve the next time step, the Problem
        break; //!< has given up
// Compute the next time step length
      dt=pb.computeTimeStep(stop);
// Stop the resolution if the Problem is stationnary
      if (pb.isStationary())
        stop=true;
    }
  pb.terminate();
}
Variable Documentation
const Type_info* Pilote_ICoCobases[1] = { &(Interprete ::info_obj)}
Definition at line 39 of file Pilote_ICoCo.cpp.