TRUST: src/ThHyd/Schemas_Temps/Piso.cpp File Reference
Piso.cpp File Reference
#include <Piso.h>
#include <Source_PDF_base.h>
#include <EChaine.h>
#include <Debog.h>
#include <Matrice_Bloc.h>
#include <Assembleur_base.h>
#include <Schema_Temps_base.h>
#include <TRUSTTrav.h>
#include <Fluide_Dilatable_base.h>
#include <Probleme_base.h>
#include <MD_Vector_std.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <TRUSTTab_parts.h>
#include <Discretisation_base.h>
Functions
void test_imposer_cond_lim (Equation_base &eqn, DoubleTab &current2, const char *msg, int flag)
Variables
const Type_info * Pisobases [1] ={ &(Simpler ::info_obj)}
const Type_info * Implicitebases [1] ={ &(Piso ::info_obj)}
Function Documentation
test_imposer_cond_lim()
void test_imposer_cond_lim (Equation_base & eqn, DoubleTab & current2, const char * msg, int flag)
Definition at line 106 of file Piso.cpp.
{
  return;
  DoubleTab& present = eqn.inconnue().futur();
  DoubleTab sauv(present);
  const Schema_Temps_base& sch = eqn.probleme().schema_temps();
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),sch.temps_courant()+sch.pas_de_temps());
  present -= sauv;
// BM, je remplace max_abs par mp_pax_abs: du coup la methode doit etre appelee simultanement par tous les procs.
  double ecart_max=mp_max_abs_vect(present);
  Cout<<msg <<" "<<ecart_max<<finl;
  if ((ecart_max>1e-10))
    abort();
  present = sauv;
}
References Cout, finl, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), mp_max_abs_vect(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and Equation_base::zone_Cl_dis().
Referenced by Piso::iterer_NS().
Variable Documentation
Implicitebases
const Type_info* Implicitebases[1] ={ &(Piso ::info_obj)}
Definition at line 38 of file Piso.cpp.
Pisobases
const Type_info* Pisobases[1] ={ &(Simpler ::info_obj)}
Definition at line 36 of file Piso.cpp.