TRUST: src/Kernel/Geometrie/Polyedriser.cpp File Reference
Polyedriser.cpp File Reference
#include <Polyedriser.h>
#include <Domaine.h>
#include <Scatter.h>
#include <Polyedre.h>
#include <vector>
Functions
static double computeAngleBetweenCoplanarVectors (std::vector< double > u, std::vector< double > v, std::vector< double > normale)
static void reorder_vertices (Faces &faces, DoubleTab coords)
Variables
static int faces_sommets_poly [6][4]
const Type_info * Polyedriserbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
computeAngleBetweenCoplanarVectors()
static double computeAngleBetweenCoplanarVectors (std::vector< double > u, std::vector< double > v, std::vector< double > normale) static
Definition at line 61 of file Polyedriser.cpp.
{
  double dot = u[0]*v[0] + u[1]*v[1] + u[2]*v[2];
  double det =   u[0]*v[1]*normale[2]
                 +   v[0]*normale[1]*u[2]
                 +   normale[0]*u[1]*v[2]
                 -   u[2]* v[1] *normale[0]
                 -   v[2]* normale[1] *u[0]
                 -   normale[2]* u[1] *v[0];
  double angle = atan2(det, dot);
  if(det == 0.0)
    {
      int dir = 0;
      while(v[dir] == 0.0) dir++;
      double quotient = u[dir] / v[dir];
      if( quotient > 0)
        angle = 0.0;
      else if( quotient < 0 )
        angle = M_PI;
    }
  else if(det < 0)
    angle += 2*M_PI;
  return angle;
}
References M_PI.
Referenced by reorder_vertices().
reorder_vertices()
static void reorder_vertices (Faces & faces, DoubleTab coords) static
Definition at line 91 of file Polyedriser.cpp.
{
  int nb_sommets = faces.les_sommets().dimension(1);
  int nb_faces = faces.nb_faces();
  for(int face = 0; face < nb_faces; face++)
    {
// computing the center of gravity of the face
      std::vector<double> center(3,0.0);
      for(int s=0; s < nb_sommets; s++)
        for(int dir=0; dir<3; dir++)
          center[dir] += coords(faces.sommet(face,s),dir);
      for(int dir=0; dir<3; dir++)
        center[dir] /= nb_sommets;
// computing the normal to the face
      int s0 = faces.sommet(face, 0);
      int s1 = faces.sommet(face, 1);
      int s2 = faces.sommet(face, 2);
      std::vector<double> u =
      {
        coords(s1,0) - coords(s0,0),
        coords(s1,1) - coords(s0,1),
        coords(s1,2) - coords(s0,2),
      };
      std::vector<double> v =
      {
        coords(s2,0) - coords(s0,0),
        coords(s2,1) - coords(s0,1),
        coords(s2,2) - coords(s0,2),
      };
      std::vector<double> normale =
      {
        u[1]*v[2] - u[2]*v[1] ,
        u[2]*v[0] - u[0]*v[2] ,
        u[0]*v[1] - u[1]*v[0] ,
      };
      double normale_norm = sqrt( normale[0]*normale[0] + normale[1]*normale[1] + normale[2]*normale[2] );
      for(int dir=0; dir<3; dir++)  normale[dir] /= normale_norm;
// reference vector used to compute angles
      std::vector<double> vec_ref = { coords(faces.sommet(face,0),0) - center[0],
                                      coords(faces.sommet(face,0),1) - center[1],
                                      coords(faces.sommet(face,0),2) - center[2]
                                    };
// sorting the vertices in the face according to their angle formed with the reference vector
// in ascending order
      for (int i = 0; i < nb_sommets-1; i++)
        {
          for (int j = 0; j < nb_sommets-i-1; j++)
            {
              std::vector<double> vec1 = {coords(faces.sommet(face,j),0)-center[0],
                                          coords(faces.sommet(face,j),1)-center[1],
                                          coords(faces.sommet(face,j),2)-center[2]
                                         };
              std::vector<double> vec2 = {coords(faces.sommet(face,j+1),0)-center[0],
                                          coords(faces.sommet(face,j+1),1)-center[1],
                                          coords(faces.sommet(face,j+1),2)-center[2]
                                         };
              double angle1 = computeAngleBetweenCoplanarVectors(vec1, vec_ref, normale);
              double angle2 = computeAngleBetweenCoplanarVectors(vec2, vec_ref, normale);
              if (angle1 > angle2)
                {
                  int tmp = faces.sommet(face,j);
                  faces.sommet(face, j) = faces.sommet(face,j+1);
                  faces.sommet(face, j+1) = tmp;
                }
            }
        }
    }
  return;
}
References computeAngleBetweenCoplanarVectors(), TRUSTTab< _TYPE_ >::dimension(), Faces::les_sommets(), Faces::nb_faces(), and Faces::sommet().
Referenced by Polyedriser::polyedriser().
Variable Documentation
faces_sommets_poly
int faces_sommets_poly[6][4] static
Initial value:
=
{
  { 0, 4, 6, 2 },
  { 1, 5, 7, 3 },
  { 0, 2, 3, 1 },
  { 4, 6, 7, 5 },
  { 2, 6, 7, 3 },
  { 0, 4, 5, 1 }
}
Definition at line 35 of file Polyedriser.cpp.
Referenced by Polyedriser::polyedriser().
Polyedriserbases
const Type_info* Polyedriserbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 45 of file Polyedriser.cpp.