TRUST: src/Kernel/Geometrie/Polygone.cpp File Reference
src/Kernel/Geometrie/Polygone.cpp File Reference
#include <Polygone.h>
#include <Domaine.h>
#include <IntList.h>
#include <Triangle.h>
#include <algorithm>
Functions
int contient_triangle (const ArrOfDouble &pos, int som0, int som1, int som2, const DoubleTab &coord)
Variables
const Type_info * Polygonebases [1] = { &(Poly_geom_base ::info_obj)}
Function Documentation
int contient_triangle (const ArrOfDouble & pos, int som0, int som1, int som2, const DoubleTab & coord)
Definition at line 183 of file Polygone.cpp.
References dabs(), Objet_U::precision_geom, and prod().
Referenced by Polygone::contient().
{
  double prod,p0,p1,p2;
// Il faut donc determiner le sens (trigo ou anti trigo) pour la numerotation :
// Calcul de prod = 01 vectoriel 02 selon z
// prod > 0 : sens trigo
// prod < 0 : sens anti trigo
  prod = (coord(som1,0)-coord(som0,0))*(coord(som2,1)-coord(som0,1))
         - (coord(som1,1)-coord(som0,1))*(coord(som2,0)-coord(som0,0));
  double signe;
  if (prod >= 0)
    signe = 1;
  else
    signe = -1;
// Calcul de p0 = 0M vectoriel 1M selon z
  p0 = (pos[0]-coord(som0,0))*(pos[1]-coord(som1,1))
       - (pos[1]-coord(som0,1))*(pos[0]-coord(som1,0));
  p0 *= signe;
// Calcul de p1 = 1M vectoriel 2M selon z
  p1 = (pos[0]-coord(som1,0))*(pos[1]-coord(som2,1))
       - (pos[1]-coord(som1,1))*(pos[0]-coord(som2,0));
  p1 *= signe;
// Calcul de p2 = 2M vectoriel 0M selon z
  p2 = (pos[0]-coord(som2,0))*(pos[1]-coord(som0,1))
       - (pos[1]-coord(som2,1))*(pos[0]-coord(som0,0));
  p2 *= signe;
  double epsilon=dabs(prod)*Objet_U::precision_geom;
  if ((p0>-epsilon) && (p1>-epsilon) && (p2>-epsilon))
    return 1;
  else
    return 0;
}
Variable Documentation
const Type_info* Polygonebases[1] = { &(Poly_geom_base ::info_obj)}
Definition at line 30 of file Polygone.cpp.