TRUST: src/Kernel/Framework/Porosites_champ.h File Reference
Porosites_champ.h File Reference
#include <TRUSTTabs_forward.h>
#include <Interprete.h>
Classes
class Porosites_champ
Porosites_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfaciques comme moyenne harmonique.
Functions
const DoubleTab & modif_par_porosite_si_flag (const DoubleTab &org, DoubleTab &res, int flag, const DoubleVect &porosite)
renvoit le tableau res, res=org si flag=0, res= porosite*org sinon
attention ne pas modifier res car sinon on ne sait pas ce que l'on fait sur org (d'ou le renvoi const)
Function Documentation
modif_par_porosite_si_flag()
const DoubleTab & modif_par_porosite_si_flag (const DoubleTab & org, DoubleTab & res, int flag, const DoubleVect & porosite)
renvoit le tableau res, res=org si flag=0, res= porosite*org sinon
attention ne pas modifier res car sinon on ne sait pas ce que l'on fait sur org (d'ou le renvoi const)
Definition at line 27 of file Porosites_champ.cpp.
{
// Switch mp_min_vect to local_min_abs_vect to avoid mp_min
// call during the calculation of operators (convection, diffusion,...)
  if ((flag==0)||(local_min_abs_vect(porosite)==1))
    res.ref(org);
  else
    {
      assert(org.dimension_tot(0)==porosite.size_totale());
      res = org;
      tab_multiply_any_shape(res, porosite, VECT_ALL_ITEMS);
    }
  return res;
}
References TRUSTTab< _TYPE_ >::dimension_tot(), local_min_abs_vect(), TRUSTTab< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::size_totale(), tab_multiply_any_shape(), and VECT_ALL_ITEMS.
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face::contribue_au_second_membre(), EOS_Tools_VEF::secmembre_divU_Z(), and Op_Diff_VEFP1NCP1B_Face::test().