TRUST: src/Kernel/Framework/Postraitement.cpp File Reference
Postraitement.cpp File Reference
#include <Postraitement.h>
#include <EFichier.h>
#include <Zone_VF.h>
#include <Champ_Generique_Interpolation.h>
#include <Champ_Generique_refChamp.h>
#include <Champ_Generique_Correlation.h>
#include <Champ_Generique_Statistiques.h>
#include <Entree_complete.h>
#include <EcritureLectureSpecial.h>
#include <Equation_base.h>
#include <Discretisation_base.h>
#include <Operateur_base.h>
#include <Operateur.h>
#include <Param.h>
#include <LecFicDiffuse_JDD.h>
Functions
void nom_fichier (const Postraitement &post, const Champ_Generique_Statistiques &op, const Domaine &dom, Nom &nom_fichier)
void nom_fichier (const Postraitement &post, const Nom &nom_post, const Nom &loc, const double temps_ch, const Domaine &dom, Nom &nom_fichier)
void nom_fichier (const Domaine &dom, Nom &nom_fichier)
int composante (const Nom &le_nom_, const Champ_base &mon_champ)
Variables
const Type_info * Postraitementbases [1] ={ &(Postraitement_base ::info_obj)}
static Noms liste_dom_ecrit
Function Documentation
composante()
int composante (const Nom & le_nom_, const Champ_base & mon_champ) inline
Definition at line 152 of file Postraitement.cpp.
{
  Motcle motlu(le_nom_);
  const Nom& le_nom_ch = mon_champ.le_nom();
  if (motlu == Motcle(le_nom_ch))
    return -1;
  else
    {
      const Noms& noms_comp = mon_champ.noms_compo();
      int n = noms_comp.size();
      Motcles les_noms_comp(n);
      for (int i=0; i<n; i++)
        les_noms_comp[i] = noms_comp[i];
      int ncomp = les_noms_comp.search(motlu);
      if (ncomp == -1)
        {
          Cerr << "TRUST error, the Champ_Generique name : " << le_nom_ << finl
               << " is neither the field name nor"
               << " one of its components\n";
          Cerr << le_nom_ch << " have for components : " << finl;
          for (int ii=0; ii<n; ii++)
            Cerr << noms_comp[ii] << " ";
          Cerr << finl;
          Process::exit();
        }
      return ncomp;
    }
}
References Cerr, Process::exit(), finl, Field_base::le_nom(), Field_base::noms_compo(), Motcles::search(), and vect_impl::size().
Referenced by Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Op_Curl_VEFP1B::vecteur_normal(), Op_Diff_RotRot::vecteur_normal(), and Op_Rot_VEFP1B::vecteur_normal().
nom_fichier() [1/3]
void nom_fichier (const Domaine & dom, Nom & nom_fichier) inline
Definition at line 147 of file Postraitement.cpp.
{
  nom_fichier+=".";
  nom_fichier+=dom.le_nom();
}
References Domaine::le_nom(), and nom_fichier().
nom_fichier() [2/3]
void nom_fichier (const Postraitement & post, const Champ_Generique_Statistiques & op, const Domaine & dom, Nom & nom_fichier) inline
Definition at line 113 of file Postraitement.cpp.
{
  nom_fichier+=".";
  const Entity& loc = op->get_localisation();
  Nom loc_post;
// contenu de la methode get_nom_localisation()
  if (loc==ELEMENT)
    loc_post = "ELEM";
  else if (loc==NODE)
    loc_post = "SOM";
  else if (loc==FACE)
    loc_post = "FACES";
  else
    {
      Cerr<<"This location is not valid for the postprocessing"<<finl;
      Process::exit();
    }
  nom_fichier+=op->get_nom_post()+"."+loc_post+"."+dom.le_nom()+"."+post.probleme().le_nom()+".";
  char s[100];
  sprintf(s,"%.10f", op->get_time());
  nom_fichier+=Nom(s);
}
References Cerr, ELEMENT, Process::exit(), FACE, finl, Probleme_base::le_nom(), Domaine::le_nom(), NODE, nom_fichier(), and Postraitement::probleme().
Referenced by Partitionneur_Partition::construire_partition(), decompression(), Op_Div_VEFP1B_Elem::degres_liberte(), DomaineCutter::ecrire_zones(), Format_Post_Med::finir_med(), Loi_horaire::imprimer(), Probleme_base::init_postraitements(), Integrer_champ_med::interpreter(), Execute_parallel::interpreter(), Lire_Tgrid::interpreter_(), Postraitement::lire_fichier(), Sondes::lire_fichier(), nom_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Sondes::readOn(), and Schema_Implicite_Multi_TimeStep_base::reprendre().
nom_fichier() [3/3]
void nom_fichier (const Postraitement & post, const Nom & nom_post, const Nom & loc, const double temps_ch, const Domaine & dom, Nom & nom_fichier) inline
Definition at line 138 of file Postraitement.cpp.
{
  nom_fichier+=".";
  nom_fichier+=nom_post+"."+loc+"."+dom.le_nom()+"."+post.probleme().le_nom()+".";
  char s[100];
  sprintf(s,"%.10f",temps_ch);
  nom_fichier+=Nom(s);
}
References Probleme_base::le_nom(), Domaine::le_nom(), nom_fichier(), and Postraitement::probleme().
Variable Documentation
liste_dom_ecrit
Noms liste_dom_ecrit static
Definition at line 1135 of file Postraitement.cpp.
Referenced by Postraitement::init().
Postraitementbases
const Type_info* Postraitementbases[1] ={ &(Postraitement_base ::info_obj)}
Definition at line 33 of file Postraitement.cpp.