TRUST: src/Kernel/Geometrie/Postraiter_domaine.cpp File Reference
Postraiter_domaine.cpp File Reference
#include <Postraiter_domaine.h>
#include <Sous_Zone.h>
#include <Format_Post.h>
#include <Param.h>
#include <communications.h>
Functions
void traite_bord (const Zone &zone, IntVect &ch_som, IntVect &ch_elem3, int num2, Faces &faces, Nom &nom_bord, Nom &fichier, const IntTab &les_elems, Format_Post_base &post, int &compteur, int &compteur0, int &compteur_reel, int &moi, int isjoint=0)
Variables
const Type_info * Postraiter_domainebases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
traite_bord()
void traite_bord (const Zone & zone, IntVect & ch_som, IntVect & ch_elem3, int num2, Faces & faces, Nom & nom_bord, Nom & fichier, const IntTab & les_elems, Format_Post_base & post, int & compteur, int & compteur0, int & compteur_reel, int & moi, int isjoint = 0)
Definition at line 61 of file Postraiter_domaine.cpp.
{
  const Domaine& dom=zone.domaine();
  Nom nom_dom=dom.le_nom();
  int num=-num2;
  int nb_elem=les_elems.dimension(0);
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_faces=faces.nb_faces();
  int nb_som_faces=faces.nb_som_faces();
  int j,k,som;
  DoubleTab ch_elem2(nb_elem,1);
  ch_elem2=moi;
  if (isjoint!=2)
    {
// on a pas encore calcule ch_elem3
      ch_elem3=moi;
      for (j=0; j<nb_faces; j++)
        for (k=0; k<nb_som_faces; k++)
          {
            som=faces.sommet(j,k);
// cas des polyedres
            if (som==-1)  break;
            if (ch_som(som)==0)
              ch_som(som)=num;
            else
              ch_som(som)=(ch_som(som)+num)/2;
          }
// num=-Process::nproc();
      num=-1;
      if (nb_faces!=0)
        {
          if (0)
            {
              int taille1=les_elems.dimension(1);
              for (int e=0 ; e < nb_elem ; e++)
                {
                  for (j=0; j<nb_faces; j++)
                    {
                      int m=-1;
                      for (k=0; k<nb_som_faces; k++)
{
                          som=faces.sommet(j,k);
                          for (int kk=0; kk<taille1; kk++)
{
                              if (les_elems(e,kk)==som)
{
                                  m++;;
                                  break;
                                }
                            }
                          if (m!=k) break;
                        }
                      if (m==nb_som_faces-1)
                        ch_elem3[e]=num;
                    }
                }
            }
          else
            {
              const IntTab& faces_voisin=faces.voisins();
              if (faces_voisin.dimension(0) > 0 && local_max_vect(faces_voisin)!=-1)
                {
// Cerr<<" we use faces_voisins"<<finl;
                  for (j=0; j<nb_faces; j++)
                    {
                      int el1=faces_voisin(j,0);
                      if (el1==-1) el1=faces_voisin(j,1);
                      if (el1==-1)
{
                          Cerr << "Error, the face " << j << " of the domain " << dom.le_nom() << " has no neighbours !" << finl;
                          Cerr << "Check that the domain " << dom.le_nom() << " has been discretized." << finl;
                          Process::exit();
                        }
                      ch_elem3[el1]=num;
                    }
                }
              else
                {
                  DoubleTab position(1,Objet_U::dimension);
                  IntVect res;
                  DoubleTab xv;
                  faces.associer_zone(zone);
                  faces.calculer_centres_gravite(xv);
                  for (j=0; j<nb_faces; j++)
                    {
                      for (int dir=0; dir<Objet_U::dimension; dir++)
                        position(0,dir)=xv(j,dir);
                      zone.chercher_elements(position,res);
                      if (res[0]<0)
{
                          position+=1e-5;
                          zone.chercher_elements(position,res);
                          if (res[0]<0)
{
                              position-=2e-5;
                              zone.chercher_elements(position,res);
                            }
                        }
                      if (res[0]<nb_elem)
{
                          if (res[0]<0)
{
                              if (isjoint==1)
                                Cerr<<"To properly view the joints, the splitting area must be complete "<<finl;
                              else
{
                                  Cerr<<"Problem in Postraiter_domaine.cpp with the boundary "<<nom_bord<<finl;
// abort();
                                }
                            }
                          else
{
                              ch_elem3[res[0]]=num;
                            }
                        }
                      else
{
                          if (nb_elem>=nb_elem_tot) abort();
                        }
                    }
                }
            }
        }
    }
  for (int s=0; s<nb_elem; s++) ch_elem2(s,0)=(ch_elem3[s]);
// on ajoute ce bord
  Noms noms_post(1);
  noms_post[0]=nom_bord;
  Noms unites(1);
  unites[0]="1";
// Cerr<<Process::me() <<" ch_elem2 size"<<fichier<< " "<<nom_dom<<" " <<nom_bord<<" "<<ch_elem2.dimension(0)<<finl;
  post.ecrire_champ(dom,unites,noms_post,-1,0.,0.,nom_bord, nom_dom, "ELEM","scalar",ch_elem2);
}
References Faces::associer_zone(), Faces::calculer_centres_gravite(), Cerr, Zone::chercher_elements(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Format_Post_base::ecrire_champ(), Process::exit(), finl, Domaine::le_nom(), local_max_vect(), Zone::nb_elem_tot(), Faces::nb_faces(), Faces::nb_som_faces(), Faces::sommet(), and Faces::voisins().
Referenced by Postraiter_domaine::ecrire().
Variable Documentation
Postraiter_domainebases
const Type_info* Postraiter_domainebases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 22 of file Postraiter_domaine.cpp.