TRUST: src/Kernel/Math/SolvSys/PrecondA.cpp File Reference
src/Kernel/Math/SolvSys/PrecondA.cpp File Reference
#include <PrecondA.h>
#include <Matrice_Morse_Sym.h>
#include <Matrice_Bloc_Sym.h>
#include <Motcle.h>
#include <ConstDoubleTab_parts.h>
Functions
static void prepare_precond (Precond &p, const Matrice_Base &m, const DoubleVect &v, Precond_base::Init_Status status)
Variables
const Type_info * PrecondAbases [1] = { &(Precond_base ::info_obj)}
Function Documentation
static void prepare_precond (Precond & p, const Matrice_Base & m, const DoubleVect & v, Precond_base::Init_Status status) [static]
Definition at line 109 of file PrecondA.cpp.
References O_U_Ptr::non_nul(), Precond_base::prepare(), Precond_base::reinit(), and Deriv_Precond_base::valeur().
Referenced by PrecondA::prepare_().
{
  if (p.non_nul())
    {
      Precond_base& pp = p.valeur();
      pp.reinit(status);
      pp.prepare(m, v);
    }
}
Variable Documentation
const Type_info* PrecondAbases[1] = { &(Precond_base ::info_obj)}
Definition at line 29 of file PrecondA.cpp.