TRUST: src/Kernel/Framework/Probleme_base.cpp File Reference
Probleme_base.cpp File Reference
#include <Probleme_base.h>
#include <Equation.h>
#include <Periodique.h>
#include <Schema_Euler_Implicite.h>
#include <Milieu_base.h>
#include <EcrFicCollecteBin.h>
#include <LecFicDiffuseBin.h>
#include <EcritureLectureSpecial.h>
#include <Postraitement.h>
#include <Discretisation_base.h>
#include <ICoCoExceptions.h>
#include <stat_counters.h>
#include <Debog.h>
#include <List_Ref_Postraitement.h>
#include <Champ_Gen_de_Champs_Gen.h>
#include <communications.h>
#include <Avanc.h>
#include <Deriv_Entree_Fichier_base.h>
#include <sys/stat.h>
#include <Loi_Fermeture_base.h>
#include <FichierHDFPar.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
Macros
#define CHECK_ALLOCATE 0
Pour acces a int close(int fd); avec PGI.
Functions
int version_format_sauvegarde ()
Variables
const Type_info * Probleme_basebases [1] ={ &(Probleme_U ::info_obj)}
List_Nom glob_noms_fichiers
List_Ref_Postraitement glob_derniers_posts
Macro Definition Documentation
CHECK_ALLOCATE
#define CHECK_ALLOCATE 0
Pour acces a int close(int fd); avec PGI.
Definition at line 40 of file Probleme_base.cpp.
Function Documentation
version_format_sauvegarde()
int version_format_sauvegarde () inline
Definition at line 403 of file Probleme_base.cpp.
{
  return 184;
}
Referenced by Probleme_base::readOn(), Probleme_base::sauver(), and Probleme_base::sauver_xyz().
Variable Documentation
glob_derniers_posts
List_Ref_Postraitement glob_derniers_posts
Definition at line 72 of file Probleme_base.cpp.
Referenced by Probleme_base::init_postraitements(), and Probleme_base::~Probleme_base().
glob_noms_fichiers
List_Nom glob_noms_fichiers
Definition at line 71 of file Probleme_base.cpp.
Referenced by Probleme_base::init_postraitements(), and Probleme_base::~Probleme_base().
Probleme_basebases
const Type_info* Probleme_basebases[1] ={ &(Probleme_U ::info_obj)}
Definition at line 48 of file Probleme_base.cpp.