TRUST: src/Kernel/ICoCo/ProblemTrio.h File Reference
src/Kernel/ICoCo/ProblemTrio.h File Reference
#include <ICoCoProblem.h>
#include <vector>
#include <string>
Classes
class ICoCo::ProblemTrio
class ProblemTrio
This class defines the API a problem has to implement in order to be coupled.
For precise specifications and possible use of this API, See NT
SSTH/LMDL_2006_001
Implements IterativeUnsteadyProblem and FieldIO
Namespaces
namespace ICoCo
Functions
Objet_U & get_obj (const char *)
< namespace ICoCo
Function Documentation
Objet_U& get_obj (const char *)
< namespace ICoCo
Definition at line 720 of file ProblemTrio.cpp.
References Objet_U::interprete(), and Interprete::objet().
Referenced by ICoCo::ProblemTrio::initialize().
{
  Nom nom(chr);
  Objet_U& obj=nom.interprete().objet(nom);
  return obj;
}