TRUST: src/Kernel/ICoCo/ProblemTrio.cpp File Reference
src/Kernel/ICoCo/ProblemTrio.cpp File Reference
#include <ProblemTrio.h>
#include <Probleme_U.h>
#include <Probleme_base.h>
#include <ICoCoExceptions.h>
#include <Noms.h>
#include <stdlib.h>
#include <Comm_Group_MPI.h>
#include <MAIN.h>
#include <mon_main.h>
#include <ICoCoTrioField.h>
#include <Schema_Temps_base.h>
#include <Catch_SIGINIT.h>
#include <Init_Params.h>
#include <Motcle.h>
#include <medcoupling++.h>
#include <ICoCoMEDDoubleField.h>
#include <MEDCouplingFieldDouble.hxx>
#include <MEDCoupling_version.h>
#include <Convert_ICoCoTrioField.h>
#include <stat_counters.h>
#include <Field_base.h>
Functions
Problem * getProblem ()
Objet_U & get_obj (const char *chr)
< namespace ICoCo
Function Documentation
Objet_U& get_obj (const char * chr)
< namespace ICoCo
Definition at line 720 of file ProblemTrio.cpp.
References Objet_U::interprete(), and Interprete::objet().
Referenced by ICoCo::ProblemTrio::initialize().
{
  Nom nom(chr);
  Objet_U& obj=nom.interprete().objet(nom);
  return obj;
}
Problem* getProblem ()
Definition at line 74 of file ProblemTrio.cpp.
{
// Cerr<<"coucou getProblem"<<finl;
  Problem* T=new ProblemTrio;
  return T;
}