TRUST: src/Kernel/Utilitaires/Process.cpp File Reference
Process.cpp File Reference
#include <Process.h>
#include <Statistiques.h>
#include <Comm_Group.h>
#include <PE_Groups.h>
#include <communications.h>
#include <Sortie_Nulle.h>
#include <Journal.h>
#include <SFichier.h>
#include <Synonyme_info.h>
#include <petsc_for_kernel.h>
#include <comm_incl.h>
#include <TriouError.h>
#include <Comm_Group_MPI.h>
#include <unistd.h>
#include <SChaine.h>
#include <FichierHDFPar.h>
Macros
#define MPI_ENTIER MPI_INT
Functions
void init_journal_file (int verbose_level, int journal_shared, const char *file_name, int append)
Initialisation du journal
Parametre: verbose_level
Signification: les messages de niveau <= verbose_level seront affiches,
les autres seront mis a la poubelle.
Parametre: file_name
Signification: si pointeur nul, tout le monde ecrit dans cerr, sinon
c'est le nom du fichier (doit etre different sur chaque processeur)
Parametre: append
Signification: indique si on ouvre le fichier en mode append ou pas.
void end_journal (int verbose_level)
Sortie & get_Cerr ()
Renvoie l'objet Sortie sur lequel seront redirigees les
objets ecrits dans Cerr. Cela peut etre std_err_ ou journal_file_.
Sortie & get_Cout ()
Si on est sur le maitre, on renvoie cout ou le fichier journal
sinon journal_zero_.
Voir aussi cerr_to_journal_.
void set_Cerr_to_journal (int flag)
change la destination de Cerr et Cout
Si flag=0, c'est stderr et stdout, sinon, si le fichier
journal est ouvert, c'est le journal, sinon c'est
Sortie_Nulle
int get_journal_level ()
void change_journal_level (int level)
int get_disable_stop ()
Returns the disable_stop_ flag (Disable or not the writing of the .stop file)
void change_disable_stop (int new_stop)
Affects a new value to disable_stop_ flag (Disable or not the writing of the .stop file)
Variables
static Sortie_Nulle journal_zero_
< sleep() pour certaines machines
static Sortie std_err_ (cerr)
static Sortie std_out_ (cout)
static SFichier journal_file_
static SChaine journal_shared_stream_
static int journal_shared_
static int journal_file_open_
static Nom journal_file_name_
static int verbose_level_ = 0
static int disable_stop_ = 0
static int cerr_to_journal_ = 0
Stat_Counter_Id mpi_allreduce_counter_
Macro Definition Documentation
MPI_ENTIER
#define MPI_ENTIER MPI_INT
Function Documentation
change_disable_stop()
void change_disable_stop (int new_stop)
Affects a new value to disable_stop_ flag (Disable or not the writing of the .stop file)
Definition at line 533 of file Process.cpp.
{
  disable_stop_ = new_stop;
}
References disable_stop_.
Referenced by mon_main::mon_main().
change_journal_level()
void change_journal_level (int level)
Definition at line 519 of file Process.cpp.
{
  verbose_level_ = level;
}
References verbose_level_.
Referenced by Execute_parallel::interpreter().
end_journal()
void end_journal (int verbose_level)
Definition at line 434 of file Process.cpp.
{
// Attention: acrobatie pour que ca "plante proprement" si le destructeur
// ecrit dans le journal !
  if(journal_shared_)
    {
      FichierHDFPar fic_hdf;
      fic_hdf.create(journal_file_name_);
      fic_hdf.create_and_fill_dataset_MW("/log", journal_shared_stream_);
      fic_hdf.close();
    }
  else
    journal_file_.close();
  journal_file_open_ = 0;
}
References FichierHDF::close(), Sortie_Fichier_base::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), journal_file_, journal_file_name_, journal_file_open_, journal_shared_, and journal_shared_stream_.
Referenced by Process::exit(), init_journal_file(), and mon_main::~mon_main().
get_Cerr()
Sortie & get_Cerr ()
Renvoie l'objet Sortie sur lequel seront redirigees les
objets ecrits dans Cerr. Cela peut etre std_err_ ou journal_file_.
Definition at line 452 of file Process.cpp.
{
  if (journal_file_open_ && cerr_to_journal_)
    {
      if(journal_shared_)
        return journal_shared_stream_;
      else
        return journal_file_;
    }
  else
    {
// dans le cas ou on a pas initialise les groupes
// on ne peut pas tester si on est maitre
      if (PE_Groups::get_nb_groups()==0)
        return std_err_;
// Seul le processeur maitre ecrit sur std_err_, les autres ecrivent sur journal_file_
      if (Process::je_suis_maitre())
        return std_err_;
      else if (verbose_level_)
        {
          if(journal_shared_)
            return journal_shared_stream_;
          else
            return journal_file_;
        }
      else
        return journal_zero_;
    }
}
References cerr_to_journal_, PE_Groups::get_nb_groups(), Process::je_suis_maitre(), journal_file_, journal_file_open_, journal_shared_, journal_shared_stream_, journal_zero_, std_err_, and verbose_level_.
Referenced by SETS::iterer_NS().
get_Cout()
Sortie & get_Cout ()
Si on est sur le maitre, on renvoie cout ou le fichier journal
sinon journal_zero_.
Voir aussi cerr_to_journal_.
Definition at line 485 of file Process.cpp.
{
  if (Process::je_suis_maitre())
    {
      if (journal_file_open_ && cerr_to_journal_)
        {
          if(journal_shared_)
            return journal_shared_stream_;
          else
            return journal_file_;
        }
      else
        return std_out_;
    }
  else
    {
      return journal_zero_;
    }
}
References cerr_to_journal_, Process::je_suis_maitre(), journal_file_, journal_file_open_, journal_shared_, journal_shared_stream_, journal_zero_, and std_out_.
get_disable_stop()
int get_disable_stop ()
Returns the disable_stop_ flag (Disable or not the writing of the .stop file)
Definition at line 526 of file Process.cpp.
{
  return disable_stop_;
}
References disable_stop_.
Referenced by mon_main::dowork(), Process::exit(), Mod_turb_hyd_base::limpr_ustar(), and Schema_Temps_base::stop().
get_journal_level()
int get_journal_level ()
Definition at line 514 of file Process.cpp.
{
  return verbose_level_;
}
References verbose_level_.
Referenced by Execute_parallel::interpreter().
init_journal_file()
void init_journal_file (int verbose_level, int journal_shared, const char * file_name, int append)
Initialisation du journal
Parametre: verbose_level
Signification: les messages de niveau <= verbose_level seront affiches,
les autres seront mis a la poubelle.
Parametre: file_name
Signification: si pointeur nul, tout le monde ecrit dans cerr, sinon
c'est le nom du fichier (doit etre different sur chaque processeur)
Parametre: append
Signification: indique si on ouvre le fichier en mode append ou pas.
Definition at line 395 of file Process.cpp.
{
  journal_shared_ = journal_shared;
  if( journal_shared_ )
    {
      if(journal_file_open_)
        end_journal(verbose_level);
    }
  else
    end_journal(verbose_level);
  if (verbose_level > 0)
    {
      if (file_name)
        {
          if(!journal_shared_)
            {
              IOS_OPEN_MODE mode = ios::out;
              if (append)
                mode = ios::app;
              if (!journal_file_.ouvrir(file_name, mode))
                {
                  Cerr << "Fatal error in init_journal_file: cannot open journal file" << finl;
                  Process::exit();
                }
            }
          else
            {
              if(append)
                Cerr << "Process.cpp::init_journal_file : append mode is not possible with HDF5!\n"
                     << "If " << file_name << " already exists, it will be overwritten" << finl;
            }
          journal_file_open_ = 1;
          journal_file_name_ = file_name;
        }
    }
  verbose_level_ = verbose_level;
}
References Cerr, end_journal(), Process::exit(), finl, IOS_OPEN_MODE, journal_file_, journal_file_name_, journal_file_open_, journal_shared_, Sortie_Fichier_base::ouvrir(), and verbose_level_.
Referenced by mon_main::dowork(), and mon_main::mon_main().
set_Cerr_to_journal()
void set_Cerr_to_journal (int flag)
change la destination de Cerr et Cout
Si flag=0, c'est stderr et stdout, sinon, si le fichier
journal est ouvert, c'est le journal, sinon c'est
Sortie_Nulle
Definition at line 509 of file Process.cpp.
{
  cerr_to_journal_ = flag;
}
References cerr_to_journal_.
Referenced by Execute_parallel::interpreter().
Variable Documentation
cerr_to_journal_
int cerr_to_journal_ = 0 static
Definition at line 58 of file Process.cpp.
Referenced by get_Cerr(), get_Cout(), and set_Cerr_to_journal().
disable_stop_
int disable_stop_ = 0 static
Definition at line 54 of file Process.cpp.
Referenced by change_disable_stop(), and get_disable_stop().
journal_file_
SFichier journal_file_ static
Definition at line 44 of file Process.cpp.
Referenced by end_journal(), get_Cerr(), get_Cout(), init_journal_file(), and Process::Journal().
journal_file_name_
Nom journal_file_name_ static
Definition at line 49 of file Process.cpp.
Referenced by end_journal(), Process::exit(), and init_journal_file().
journal_file_open_
int journal_file_open_ static
Definition at line 48 of file Process.cpp.
Referenced by end_journal(), Process::exit(), get_Cerr(), get_Cout(), init_journal_file(), and Process::Journal().
journal_shared_
int journal_shared_ static
Definition at line 46 of file Process.cpp.
Referenced by end_journal(), Process::exit(), get_Cerr(), get_Cout(), init_journal_file(), and Process::Journal().
journal_shared_stream_
SChaine journal_shared_stream_ static
Definition at line 45 of file Process.cpp.
Referenced by end_journal(), get_Cerr(), get_Cout(), and Process::Journal().
journal_zero_
Sortie_Nulle journal_zero_ static
< sleep() pour certaines machines
Definition at line 36 of file Process.cpp.
Referenced by get_Cerr(), get_Cout(), and Process::Journal().
mpi_allreduce_counter_
Stat_Counter_Id mpi_allreduce_counter_ extern
std_err_
Sortie std_err_(cerr) (cerr) static
Referenced by Process::exit(), get_Cerr(), and Process::Journal().
std_out_
Sortie std_out_(cout) (cout) static
Referenced by get_Cout().
verbose_level_
int verbose_level_ = 0 static
Definition at line 53 of file Process.cpp.
Referenced by change_journal_level(), Process::exit(), get_Cerr(), get_journal_level(), and init_journal_file().