TRUST: src/Kernel/Utilitaires/Process.h File Reference
Process.h File Reference
Classes
class Process
Classe de base de TRUST (notamment Objet_U).
Elle fournit quelques services de base
accessibles de partout dans le code (ces services etaient historiquement
des methodes non statiques, depuis que tous ces services sont statiques,
cette classe n'a plus vraiment d'autre fonction que de ranger ces methodes
quelque part)
Functions
int get_disable_stop ()
Returns the disable_stop_ flag (Disable or not the writing of the .stop file)
void change_disable_stop (int new_stop)
Affects a new value to disable_stop_ flag (Disable or not the writing of the .stop file)
Function Documentation
change_disable_stop()
void change_disable_stop (int new_stop)
Affects a new value to disable_stop_ flag (Disable or not the writing of the .stop file)
Definition at line 533 of file Process.cpp.
{
  disable_stop_ = new_stop;
}
References disable_stop_.
Referenced by mon_main::mon_main().
get_disable_stop()
int get_disable_stop ()
Returns the disable_stop_ flag (Disable or not the writing of the .stop file)
Definition at line 526 of file Process.cpp.
{
  return disable_stop_;
}
References disable_stop_.
Referenced by mon_main::dowork(), Process::exit(), Mod_turb_hyd_base::limpr_ustar(), and Schema_Temps_base::stop().