TRUST: src/Kernel/Geometrie/Raffiner_isotrope_parallele.cpp File Reference
Raffiner_isotrope_parallele.cpp File Reference
#include <Raffiner_isotrope_parallele.h>
#include <LecFicDistribue.h>
#include <EcrFicCollecte.h>
#include <FichierHDFPar.h>
#include <LecFicDiffuse.h>
#include <Statistiques.h>
#include <TRUSTArrays.h>
#include <Schema_Comm.h>
#include <TRUSTTabs.h>
#include <SFichier.h>
#include <Domaine.h>
#include <Scatter.h>
#include <Param.h>
#include <Nom.h>
Functions
void mon_construire_correspondance_items_par_coordonnees (Joints &joints, const Joint::Type_Item type_item, const DoubleTab &coord_items)
void mon_construire_correspondance_sommets_par_coordonnees (Domaine &dom)
Construction des tableaux joint_item(Joint::SOMMET).items_communs de tous les joints de la zone(0) du domaine dom.
Variables
const Type_info * Raffiner_isotrope_parallelebases [1] ={ &(Raffiner_Simplexes ::info_obj)}
Function Documentation
mon_construire_correspondance_items_par_coordonnees()
void mon_construire_correspondance_items_par_coordonnees (Joints & joints, const Joint::Type_Item type_item, const DoubleTab & coord_items)
Definition at line 46 of file Raffiner_isotrope_parallele.cpp.
{
  switch(type_item)
    {
    case Joint::SOMMET:
      ;
      break;
    case Joint::ARETE:
      ;
      break;
    default:
      Cerr << "Scatter::construire_correspondance_items_par_coordonnees unusable for item "
           << (int)type_item
           << finl;
      Process::exit();
    }
  const int dim = Objet_U::dimension;
  const int nb_joints = joints.size();
// Indices des items de joints dans le domaine sur mon processeur
  ArrsOfInt  indices_items_locaux(nb_joints);
// Indices des items de joints dans le domaine sur le processeur voisin
  ArrsOfInt  indices_items_distants(nb_joints);
// Coordonnees des items correspondants (dans le meme ordre que indices_items_xxx)
  DoubleTabs coord_items_locaux(nb_joints);
  DoubleTabs coord_items_distants(nb_joints);
// Remplissage des tableaux indices_items_locaux
// et coord_items_locaux
  {
    int i_joint;
    for (i_joint = 0; i_joint < nb_joints; i_joint++)
      {
        const Joint& joint = joints[i_joint];
        ArrOfInt& items = indices_items_locaux[i_joint];
// Remarque: **LISTE_TRI** les indices_items_locaux sont
// tries dans l'ordre croissant:
// Scatter::calculer_liste_complete_items_joint(joint, type_item, items);
        items = joint.joint_item(Joint::SOMMET).items_communs();
        const int n       = items.size_array();
        DoubleTab&   coord   = coord_items_locaux[i_joint];
        int i, j;
        coord.resize(n, dim);
        for (i = 0; i < n; i++)
          for (j = 0; j < dim; j++)
            coord(i,j) = coord_items(items[i], j);
      }
  }
// Envoi des indices et coordonnees locaux au processeur voisin
  {
    Schema_Comm schema_comm;
    ArrOfInt liste_pe_voisins(nb_joints);
    int i;
    for (i = 0; i < nb_joints; i++)
      liste_pe_voisins[i] = joints[i].PEvoisin();
    schema_comm.set_send_recv_pe_list(liste_pe_voisins, liste_pe_voisins);
    schema_comm.begin_comm();
    for (i = 0; i < nb_joints; i++)
      {
        const int pe = liste_pe_voisins[i];
        Sortie& buffer = schema_comm.send_buffer(pe);
        buffer << indices_items_locaux[i];
        buffer << coord_items_locaux[i];
      }
    schema_comm.echange_taille_et_messages();
    for (i = 0; i < nb_joints; i++)
      {
        const int pe = liste_pe_voisins[i];
        Entree& buffer = schema_comm.recv_buffer(pe);
        buffer >> indices_items_distants[i];
        buffer >> coord_items_distants[i];
      }
    schema_comm.end_comm();
  }
// Boucle sur les joints
  {
// Cette fois, on modifie les joints (remplissage de renum_virt_loc)
// const int moi = Process::me();
    for (int i_joint = 0; i_joint < nb_joints; i_joint++)
      {
        Joint&           joint           = joints[i_joint];
        const int     PEvoisin        = joint.PEvoisin();
        const ArrOfInt& indices_locaux  = indices_items_locaux[i_joint];
// ArrOfInt &       indices_distants= indices_items_distants[i_joint];
        const DoubleTab& coord_locaux    = coord_items_locaux[i_joint];
        const DoubleTab& coord_distants  = coord_items_distants[i_joint];
        const int n = indices_locaux.size_array();
        /*
          if (n != indices_distants.size_array()) {
          Cerr << "Error in Scatter::remplir_renum_virt_loc on PE "
          << Process::me();
          Cerr << "\n Joint with PE " << joint.PEvoisin()
          << "\n Number of items " << type_item << " on my joint : " << n;
          Cerr << "\n Number of items " << type_item << " on the remote joint : "
          << indices_distants.size_array()
          << finl;
          exit();
          } */
// Recherche des correspondances entre items
        ArrOfInt corresp(n);
        const double epsilon = Objet_U::precision_geom;
        int nbsomr=Scatter::Chercher_Correspondance(coord_distants, coord_locaux, corresp, epsilon);
        if (nbsomr)
          {
            Cerr<<"iiiiiiiiiiii"<<finl;
// abort();
          }
        ArrOfInt& items_communs = joint.set_joint_item(type_item).set_items_communs();
        int nb_items_communs_trouves=0;
        for (int k = 0; k < n; k++)
          if (corresp[k]>=0)
            nb_items_communs_trouves++;
          else
            Cerr<<items_communs[k] << " not found in joint voisin "<<PEvoisin<<finl;
        ArrOfInt items_communs_sa(items_communs);
        items_communs.resize_array(nb_items_communs_trouves);
        int l=0;
        for (int k = 0; k < n; k++ )
          {
            if  (corresp[k]>=0)
              items_communs[l++]=items_communs_sa[k];
          }
      }
  }
}
References Joint::ARETE, Schema_Comm::begin_comm(), Cerr, Scatter::Chercher_Correspondance(), Objet_U::dimension, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), finl, Joint_Items::items_communs(), Joint::joint_item(), Joint::PEvoisin(), Objet_U::precision_geom, Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Schema_Comm::send_buffer(), Joint_Items::set_items_communs(), Joint::set_joint_item(), Schema_Comm::set_send_recv_pe_list(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), and Joint::SOMMET.
Referenced by mon_construire_correspondance_sommets_par_coordonnees().
mon_construire_correspondance_sommets_par_coordonnees()
void mon_construire_correspondance_sommets_par_coordonnees (Domaine & dom)
Construction des tableaux joint_item(Joint::SOMMET).items_communs de tous les joints de la zone(0) du domaine dom.
Definition at line 182 of file Raffiner_isotrope_parallele.cpp.
{
  mon_construire_correspondance_items_par_coordonnees(dom.zone(0).faces_joint(), Joint::SOMMET, dom.coord_sommets());
}
References Domaine::coord_sommets(), Zone::faces_joint(), mon_construire_correspondance_items_par_coordonnees(), Joint::SOMMET, and Domaine::zone().
Referenced by Raffiner_isotrope_parallele::interpreter().
Variable Documentation
Raffiner_isotrope_parallelebases
const Type_info* Raffiner_isotrope_parallelebases[1] ={ &(Raffiner_Simplexes ::info_obj)}
Definition at line 31 of file Raffiner_isotrope_parallele.cpp.