TRUST: src/Kernel/Geometrie/Raffiner_Simplexes.cpp File Reference
Raffiner_Simplexes.cpp File Reference
#include <Raffiner_Simplexes.h>
#include <Domaine.h>
#include <Nom.h>
#include <Scatter.h>
#include <Motcle.h>
#include <TRUSTTab.h>
#include <Array_tools.h>
#include <Static_Int_Lists.h>
#include <Connectivite_som_elem.h>
#include <Faces_builder.h>
#include <Synonyme_info.h>
Macros
#define NODE_ID(num) num
#define EDGE_ID(num) (-num-1)
Functions
static void fill_tab_2 (const int *t, int n, int m, IntTab &tab)
static void fill_tab_2_new (const int *t, int n, int m, IntTab &tab)
static void fill_tab_3 (const int *t, int n, int m, int p, IntTab &tab)
static void build_quadrangle_cell_refinement_pattern (IntTab &pattern)
static void build_triangle_cell_refinement_pattern (IntTab &pattern)
static void build_tetrahedron_cell_refinement_pattern (IntTab &pattern)
static void build_hexa_cell_refinement_pattern (IntTab &pattern)
int type_elem (const Nom &cell_type)
static void build_cell_refinement_pattern (IntTab &pattern, const Nom &cell_type)
static void build_quadrangle_face_refinement_pattern (IntTab &pattern)
static void build_triangle_face_refinement_pattern (IntTab &pattern)
static void build_tetrahedron_face_refinement_pattern (IntTab &pattern)
static void build_hexa_face_refinement_pattern (IntTab &pattern)
static void build_face_refinement_pattern (IntTab &pattern, const Nom &cell_type)
static void build_quadrangle_edges_pattern (IntTab &pattern)
static void build_triangle_edges_pattern (IntTab &pattern)
static void build_tetrahedron_edges_pattern (IntTab &pattern)
static void build_hexa_edges_pattern (IntTab &pattern)
static void build_edges_pattern (IntTab &pattern, const Nom &cell_type)
static void build_quadrangle_faces_pattern (IntTab &pattern)
static void build_triangle_faces_pattern (IntTab &pattern)
static void build_tetrahedron_faces_pattern (IntTab &pattern)
static void build_hexa_faces_pattern (IntTab &pattern)
static void build_faces_pattern (IntTab &pattern, const Nom &cell_type)
static void build_edges (const IntTab &nodes_of_cells, const IntTab &edges_pattern, IntTab &edges_of_cells, IntTab &nodes_of_edges)
static void build_nodes (const DoubleTab &nodes_src, const IntTab &nodes_of_edges_src, DoubleTab &nodes_dest)
static int find_refined_node_index (const IntTab &nodes_of_cells_src, const IntTab &edges_of_cells_src, int nb_nodes_src, int cell_src, int index)
static void build_cells (const IntTab &nodes_of_cells_src, const IntTab &edges_of_cells_src, const IntTab &pattern, int nb_nodes_src, IntTab &nodes_of_cells_dest)
static void build_frontier (const Frontiere &src, const Type_Face &face_type, const IntTab &nodes_of_cells_src, const Static_Int_Lists &cells_of_nodes_src, const IntTab &edges_of_cells_src, const IntTab &faces_pattern, const IntTab &faces_refinement_pattern, const Zone &zone_dest, Frontiere &dest)
Variables
const Type_info * Raffiner_Simplexesbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
const Synonyme_info synonym_Raffiner_Simplexes__LINE__ ("Raffiner_isotrope", Raffiner_Simplexes ::info_obj.name())
Raffiner_Simplexes class replaces the obsolete Raffiner_isotrope class.
Macro Definition Documentation
EDGE_ID
#define EDGE_ID (num) (-num-1)
Definition at line 48 of file Raffiner_Simplexes.cpp.
NODE_ID
#define NODE_ID (num) num
Definition at line 46 of file Raffiner_Simplexes.cpp.
Function Documentation
build_cell_refinement_pattern()
static void build_cell_refinement_pattern (IntTab & pattern, const Nom & cell_type) static
Definition at line 190 of file Raffiner_Simplexes.cpp.
{
  int rank = type_elem(cell_type);
  switch(rank)
    {
    case 0  :
      build_triangle_cell_refinement_pattern(pattern);
      break;
    case 1  :
      build_tetrahedron_cell_refinement_pattern(pattern);
      break;
    case 2  :
      build_quadrangle_cell_refinement_pattern(pattern);
      break;
    case 3  :
      build_hexa_cell_refinement_pattern(pattern);
      break;
    default :
      Cerr << "Error in Raffiner_Simplexes.cpp 'build_cell_refinement_pattern()'" << finl;
      Cerr << "  Unknown cell type : " << cell_type << finl;
      Cerr << "  Raffiner_Simplexes can only refine Triangles and Tetrahedrons" << finl;
      Process::exit();
    }
}
References build_hexa_cell_refinement_pattern(), build_quadrangle_cell_refinement_pattern(), build_tetrahedron_cell_refinement_pattern(), build_triangle_cell_refinement_pattern(), Cerr, Process::exit(), finl, and type_elem().
Referenced by Raffiner_Simplexes::refine_domain().
build_cells()
static void build_cells (const IntTab & nodes_of_cells_src, const IntTab & edges_of_cells_src, const IntTab & pattern, int nb_nodes_src, IntTab & nodes_of_cells_dest) static
Definition at line 685 of file Raffiner_Simplexes.cpp.
{
  assert( &(nodes_of_cells_src) != &(nodes_of_cells_dest) );
  const int nb_cells_src              = nodes_of_cells_src.dimension(0);
  const int nb_nodes_per_cell         = nodes_of_cells_src.dimension(1);
  const int nb_refined_cells_per_cell = pattern.dimension(0);
  nodes_of_cells_dest.resize(nb_cells_src * nb_refined_cells_per_cell, nb_nodes_per_cell);
  int nb_cells_dest = 0;
  for (int cell_src=0; cell_src<nb_cells_src; ++cell_src)
    {
      for (int refined_cell=0; refined_cell<nb_refined_cells_per_cell; ++refined_cell)
        {
          for (int node_in_cell=0; node_in_cell<nb_nodes_per_cell; ++node_in_cell)
            {
              const int index = pattern(refined_cell,node_in_cell);
              const int node  = find_refined_node_index(nodes_of_cells_src,edges_of_cells_src,nb_nodes_src,cell_src,index);
              nodes_of_cells_dest(nb_cells_dest,node_in_cell) = node;
            }
          ++nb_cells_dest;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), find_refined_node_index(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Raffiner_Simplexes::refine_domain().
build_edges()
static void build_edges (const IntTab & nodes_of_cells, const IntTab & edges_pattern, IntTab & edges_of_cells, IntTab & nodes_of_edges) static
Definition at line 505 of file Raffiner_Simplexes.cpp.
{
  const int nb_cells          = nodes_of_cells.dimension(0);
  const int nb_edges_per_cell = edges_pattern.dimension(0);
// const int nb_nodes_per_edge = 2;
  const int nb_nodes_per_edge_max=edges_pattern.dimension(1);
  IntTab duplicated_edges(nb_cells * nb_edges_per_cell, nb_nodes_per_edge_max);
  int nb_duplicated_edges = 0;
  for (int cell=0; cell<nb_cells; ++cell)
    {
      for (int edge_in_cell=0; edge_in_cell<nb_edges_per_cell; ++edge_in_cell)
        {
          const int node_in_cell_0 = edges_pattern(edge_in_cell,0);
          const int node_in_cell_1 = edges_pattern(edge_in_cell,1);
          int node_0 = nodes_of_cells(cell,node_in_cell_0);
          int node_1 = nodes_of_cells(cell,node_in_cell_1);
// En 3D le centre de gravite des faces est defini par les 2 diagonales
// pour assurer l'unicite avec la numerotation on prend la diagonale avec l indice de noeuds le grand en premier
          int quad_2d=0;
          if (Objet_U::dimension==3)
            {
              int it=nb_nodes_per_edge_max;
              while ( edges_pattern(edge_in_cell,it-1)==-1) it--;
              if (it==4)
                quad_2d=1;
            }
          if (quad_2d)
            {
              const int node_in_cell_2 = edges_pattern(edge_in_cell,2);
              const int node_in_cell_3 = edges_pattern(edge_in_cell,3);
              int node_2 = nodes_of_cells(cell,node_in_cell_2);
              int node_3 = nodes_of_cells(cell,node_in_cell_3);
              if (node_0 <node_1)
                std::swap(node_0,node_1);
              if (node_2 <node_3)
                std::swap(node_2,node_3);
              if (node_2>node_0)
                {
                  duplicated_edges(nb_duplicated_edges,2)=node_0;
                  duplicated_edges(nb_duplicated_edges,3)=node_1;
                  node_0=node_2;
                  node_1=node_3;
                }
              else
                {
                  assert(node_2!=node_0);
                  duplicated_edges(nb_duplicated_edges,2)=node_2;
                  duplicated_edges(nb_duplicated_edges,3)=node_3;
                }
              for (int c=4; c<nb_nodes_per_edge_max; c++)
                duplicated_edges(nb_duplicated_edges,c)=-1;
            }
          duplicated_edges(nb_duplicated_edges,0) = (node_0 < node_1) ? node_0 : node_1;
          duplicated_edges(nb_duplicated_edges,1) = (node_0 < node_1) ? node_1 : node_0;
          if (!quad_2d)
            for (int c=2; c<nb_nodes_per_edge_max; c++)
              {
                int node=edges_pattern(edge_in_cell,c);
                if (node==-1)
                  duplicated_edges(nb_duplicated_edges,c)=-1;
                else
                  duplicated_edges(nb_duplicated_edges,c)=nodes_of_cells(cell,node);
              }
          ++nb_duplicated_edges;
        }
    }
  ArrOfInt edges_indices;
  tri_lexicographique_tableau_indirect(duplicated_edges,edges_indices);
  edges_of_cells.resize(nb_cells, nb_edges_per_cell);
  nodes_of_edges.resize(0, nb_nodes_per_edge_max);
  nodes_of_edges.set_smart_resize(1);
  ArrOfInt& edges_of_cells_array = edges_of_cells;
  int node_0,node_1,edges_counter;
  node_0 = node_1 = edges_counter = -1;
  for (int duplicated_edge=0; duplicated_edge<nb_duplicated_edges; ++duplicated_edge)
    {
      const int edge_index = edges_indices[duplicated_edge];
      const int new_node_0 = duplicated_edges(edge_index, 0);
      const int new_node_1 = duplicated_edges(edge_index, 1);
      if (node_0 != new_node_0 || node_1 != new_node_1)
        {
          edges_counter++;
          nodes_of_edges.resize(edges_counter+1, nb_nodes_per_edge_max);
          nodes_of_edges(edges_counter, 0) = new_node_0;
          nodes_of_edges(edges_counter, 1) = new_node_1;
          for (int c=2; c<nb_nodes_per_edge_max; c++)
            nodes_of_edges(edges_counter, c)=duplicated_edges(edge_index,c);
          node_0 = new_node_0;
          node_1 = new_node_1;
        }
// la, ya un truc qui m'etonne : dans mon code, c'est plus complexe
      edges_of_cells_array[edge_index] = edges_counter;
    }
  nodes_of_edges.resize(edges_counter+2, nb_nodes_per_edge_max);
  nodes_of_edges.set_smart_resize(0);
  nodes_of_edges.resize(edges_counter+1, nb_nodes_per_edge_max);
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), swap(), and tri_lexicographique_tableau_indirect().
Referenced by Raffiner_Simplexes::refine_domain().
build_edges_pattern()
static void build_edges_pattern (IntTab & pattern, const Nom & cell_type) static
Definition at line 412 of file Raffiner_Simplexes.cpp.
{
  int rank = type_elem(cell_type);
  switch(rank)
    {
    case 0  :
      build_triangle_edges_pattern(pattern);
      break;
    case 1  :
      build_tetrahedron_edges_pattern(pattern);
      break;
    case 2  :
      build_quadrangle_edges_pattern(pattern);
      break;
    case 3  :
      build_hexa_edges_pattern(pattern);
      break;
    default :
      Cerr << "Error in Raffiner_Simplexes.cpp 'build_edges_pattern()'" << finl;
      Cerr << "  Unknown cell type : " << cell_type << finl;
      Cerr << "  Raffiner_Simplexes can only refine Triangles and Tetrahedrons" << finl;
      Process::exit();
    }
}
References build_hexa_edges_pattern(), build_quadrangle_edges_pattern(), build_tetrahedron_edges_pattern(), build_triangle_edges_pattern(), Cerr, Process::exit(), finl, and type_elem().
Referenced by Raffiner_Simplexes::refine_domain().
build_face_refinement_pattern()
static void build_face_refinement_pattern (IntTab & pattern, const Nom & cell_type) static
Definition at line 316 of file Raffiner_Simplexes.cpp.
{
  int rank = type_elem(cell_type);
  switch(rank)
    {
    case 0  :
      build_triangle_face_refinement_pattern(pattern);
      break;
    case 1  :
      build_tetrahedron_face_refinement_pattern(pattern);
      break;
    case 2  :
      build_quadrangle_face_refinement_pattern(pattern);
      break;
    case 3  :
      build_hexa_face_refinement_pattern(pattern);
      break;
    default :
      Cerr << "Error in Raffiner_Simplexes.cpp 'build_face_refinement_pattern()'" << finl;
      Cerr << "  Unknown cell type : " << cell_type << finl;
      Cerr << "  Raffiner_Simplexes can only refine Triangles and Tetrahedrons" << finl;
      Process::exit();
    }
}
References build_hexa_face_refinement_pattern(), build_quadrangle_face_refinement_pattern(), build_tetrahedron_face_refinement_pattern(), build_triangle_face_refinement_pattern(), Cerr, Process::exit(), finl, and type_elem().
Referenced by Raffiner_Simplexes::refine_domain().
build_faces_pattern()
static void build_faces_pattern (IntTab & pattern, const Nom & cell_type) static
Definition at line 479 of file Raffiner_Simplexes.cpp.
{
  int rank = type_elem(cell_type);
  switch(rank)
    {
    case 0  :
      build_triangle_faces_pattern(pattern);
      break;
    case 1  :
      build_tetrahedron_faces_pattern(pattern);
      break;
    case 2  :
      build_quadrangle_faces_pattern(pattern);
      break;
    case 3  :
      build_hexa_faces_pattern(pattern);
      break;
    default :
      Cerr << "Error in Raffiner_Simplexes.cpp 'build_faces_pattern()'" << finl;
      Cerr << "  Unknown cell type : " << cell_type << finl;
      Cerr << "  Raffiner_Simplexes can only refine Triangles and Tetrahedrons" << finl;
      Process::exit();
    }
}
References build_hexa_faces_pattern(), build_quadrangle_faces_pattern(), build_tetrahedron_faces_pattern(), build_triangle_faces_pattern(), Cerr, Process::exit(), finl, and type_elem().
Referenced by Raffiner_Simplexes::refine_domain().
build_frontier()
static void build_frontier (const Frontiere & src, const Type_Face & face_type, const IntTab & nodes_of_cells_src, const Static_Int_Lists & cells_of_nodes_src, const IntTab & edges_of_cells_src, const IntTab & faces_pattern, const IntTab & faces_refinement_pattern, const Zone & zone_dest, Frontiere & dest) static
Definition at line 715 of file Raffiner_Simplexes.cpp.
{
  dest.associer_zone(zone_dest);
  dest.typer_faces(face_type);
  dest.nommer(src.le_nom());
  const IntTab& nodes_of_faces_src         = src.les_sommets_des_faces();
  int         nb_faces_src               = nodes_of_faces_src.dimension(0);
  int         nb_nodes_per_face          = nodes_of_faces_src.dimension(1);
  int         nb_faces_dest_per_face_src = faces_refinement_pattern.dimension(1);
  int         nb_nodes_src               = cells_of_nodes_src.get_nb_lists();
  IntTab nodes_of_faces_dest(nb_faces_src*nb_faces_dest_per_face_src,nb_nodes_per_face);
  ArrOfInt nodes_of_current_face(nb_nodes_per_face);
  ArrOfInt incident_cells;
  incident_cells.set_smart_resize(1);
  for (int face=0; face<nb_faces_src; ++face)
    {
      for (int node_in_face=0; node_in_face<nb_nodes_per_face; ++node_in_face)
        {
          nodes_of_current_face[node_in_face] = nodes_of_faces_src(face,node_in_face);
        }
      find_adjacent_elements(cells_of_nodes_src,nodes_of_current_face,incident_cells);
      if (incident_cells.size_array() != 1)
        {
// Cette erreur n'en est pas une pour les "faces internes"...
// si le cas se presente, faire un test en essayant d'ignorer l'erreur...
          Cerr << "Error in Raffiner_Simplexes.cpp 'build_frontier()'" << finl;
          Cerr << "  The boundary face " << face << " having nodes " << nodes_of_current_face << " has the following incident cells " << incident_cells << finl;
          Process::exit();
        }
      const int coarse_cell         = incident_cells[0];
      const int face_in_coarse_cell = Faces_builder::chercher_face_element(nodes_of_cells_src,
                                                                           faces_pattern,
                                                                           nodes_of_current_face,
                                                                           coarse_cell);
      if (face_in_coarse_cell < 0)
        {
          Cerr << "Error in Raffiner_Simplexes.cpp 'build_frontier()'" << finl;
          Cerr << "  Internal error in 'Faces_builder::chercher_face_element()'" << finl;
          Process::exit();
        }
      for (int fine_face=0; fine_face<nb_faces_dest_per_face_src; ++fine_face)
        {
          int face_dest = (face*nb_faces_dest_per_face_src)+fine_face;
          for (int node_in_face=0; node_in_face<nb_nodes_per_face; ++node_in_face)
            {
              const int index = faces_refinement_pattern(face_in_coarse_cell,fine_face,node_in_face);
              const int node_dest  = find_refined_node_index(nodes_of_cells_src,edges_of_cells_src,nb_nodes_src,coarse_cell,index);
              nodes_of_faces_dest(face_dest,node_in_face) = node_dest;
            }
        }
    }
  dest.les_sommets_des_faces() = nodes_of_faces_dest;
}
References Frontiere::associer_zone(), Cerr, Faces_builder::chercher_face_element(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), find_adjacent_elements(), find_refined_node_index(), finl, Static_Int_Lists::get_nb_lists(), Frontiere::le_nom(), Frontiere::les_sommets_des_faces(), Frontiere::nommer(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), and Frontiere::typer_faces().
Referenced by Raffiner_Simplexes::refine_domain().
build_hexa_cell_refinement_pattern()
static void build_hexa_cell_refinement_pattern (IntTab & pattern) static
< tetraedre defini par sommet0 arete0 arete1 arete2
Definition at line 156 of file Raffiner_Simplexes.cpp.
{
  static const int t[] =
  {
    NODE_ID(0),EDGE_ID(0),EDGE_ID(3),EDGE_ID(4),EDGE_ID(5),EDGE_ID(6),EDGE_ID(8),EDGE_ID(9), //!< tetraedre defini par sommet0 arete0 arete1 arete2
    EDGE_ID(0),NODE_ID(1),EDGE_ID(4),EDGE_ID(1),EDGE_ID(6),EDGE_ID(7),EDGE_ID(9),EDGE_ID(10),
    EDGE_ID(3),EDGE_ID(4),NODE_ID(2),EDGE_ID(2),EDGE_ID(8),EDGE_ID(9),EDGE_ID(11),EDGE_ID(12),
    EDGE_ID(4),EDGE_ID(1),EDGE_ID(2),NODE_ID(3),EDGE_ID(9),EDGE_ID(10),EDGE_ID(12),EDGE_ID(13),
    EDGE_ID(5),EDGE_ID(6),EDGE_ID(8),EDGE_ID(9),NODE_ID(4),EDGE_ID(14),EDGE_ID(17),EDGE_ID(18),
    EDGE_ID(6),EDGE_ID(7),EDGE_ID(9),EDGE_ID(10),EDGE_ID(14),NODE_ID(5),EDGE_ID(18),EDGE_ID(15),
    EDGE_ID(8),EDGE_ID(9),EDGE_ID(11),EDGE_ID(12),EDGE_ID(17),EDGE_ID(18),NODE_ID(6),EDGE_ID(16),
    EDGE_ID(9),EDGE_ID(10),EDGE_ID(12),EDGE_ID(13),EDGE_ID(18),EDGE_ID(15),EDGE_ID(16),NODE_ID(7),
    -1
  };
  fill_tab_2(t, 8, 8, pattern);
}
References EDGE_ID, fill_tab_2(), and NODE_ID.
Referenced by build_cell_refinement_pattern().
build_hexa_edges_pattern()
static void build_hexa_edges_pattern (IntTab & pattern) static
< L'arete 0 est entre le sommet 0 et le sommet 1 de l'element
< etc...
< 5' 6' 7'
Definition at line 396 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  2, 0, 1 , //!< L'arete 0 est entre le sommet 0 et le sommet 1 de l'element
                            2, 1, 3 , //!< etc...
                            2, 2, 3 ,
                            2, 0, 2 ,
                            4, 0, 3 , 1,2,
                            2, 0,4, 4,0,5,1,4 ,2, 1,5 , //!< 5' 6' 7'
                            4,0,6,2,4, 8,0,7,1,6,3,4,2,5, 4,1,7,3,5,
                            2,2,6, 4,2,7,3,6, 2,3,7, //11' 12' 13'
                            2,4,5, 2,5,7, 2,6,7, 2,4,6 , 4,4,7,5,6,
                            -1
                         };
  fill_tab_2_new(t, 19, 8, pattern);
}
References fill_tab_2_new().
Referenced by build_edges_pattern().
build_hexa_face_refinement_pattern()
static void build_hexa_face_refinement_pattern (IntTab & pattern) static
< 0 2 4 6
< 0, 1, 4, 5 ,
< 0, 1, 2, 3 ,
< 1, 3, 5, 7 ,
< 2, 3, 6, 7 ,
< 4, 5, 6, 7
Definition at line 273 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = { NODE_ID(0), EDGE_ID(3), EDGE_ID(5), EDGE_ID(8),           //!< 0 2 4 6
                           EDGE_ID(3), NODE_ID(2), EDGE_ID(8), EDGE_ID(11),
                           EDGE_ID(5), EDGE_ID(8), NODE_ID(4), EDGE_ID(17),
                           EDGE_ID(8), EDGE_ID(11), EDGE_ID(17), NODE_ID(6),
                           NODE_ID(0), EDGE_ID(0), EDGE_ID(5), EDGE_ID(6),           //!< 0, 1, 4, 5 ,
                           EDGE_ID(0), NODE_ID(1), EDGE_ID(6), EDGE_ID(7),
                           EDGE_ID(5), EDGE_ID(6), NODE_ID(4), EDGE_ID(14),
                           EDGE_ID(6), EDGE_ID(7), EDGE_ID(14), NODE_ID(5),
                           NODE_ID(0), EDGE_ID(0), EDGE_ID(3), EDGE_ID(4),           //!<       0, 1, 2, 3 ,
                           EDGE_ID(0), NODE_ID(1), EDGE_ID(4), EDGE_ID(1),
                           EDGE_ID(3), EDGE_ID(4), NODE_ID(2), EDGE_ID(2),
                           EDGE_ID(4), EDGE_ID(1), EDGE_ID(2), NODE_ID(3),
                           NODE_ID(1), EDGE_ID(1), EDGE_ID(7), EDGE_ID(10),           //!<      1, 3, 5, 7 ,
                           EDGE_ID(1), NODE_ID(3), EDGE_ID(10), EDGE_ID(13),
                           EDGE_ID(7), EDGE_ID(10), NODE_ID(5), EDGE_ID(15),
                           EDGE_ID(10), EDGE_ID(13), EDGE_ID(15), NODE_ID(7),
                           NODE_ID(2), EDGE_ID(2), EDGE_ID(11), EDGE_ID(12),           //!< 2, 3, 6, 7 ,
                           EDGE_ID(2), NODE_ID(3), EDGE_ID(12), EDGE_ID(13),
                           EDGE_ID(11), EDGE_ID(12), NODE_ID(6), EDGE_ID(16),
                           EDGE_ID(12), EDGE_ID(13), EDGE_ID(16), NODE_ID(7),
                           NODE_ID(4), EDGE_ID(14), EDGE_ID(17), EDGE_ID(18),           //!< 4, 5, 6, 7
                           EDGE_ID(14), NODE_ID(5), EDGE_ID(18), EDGE_ID(15),
                           EDGE_ID(17), EDGE_ID(18), NODE_ID(6), EDGE_ID(16),
                           EDGE_ID(18), EDGE_ID(15), EDGE_ID(16), NODE_ID(7),
                           -1
                         };
  fill_tab_3(t, 6, 4, 4, pattern);
}
References EDGE_ID, fill_tab_3(), and NODE_ID.
Referenced by build_face_refinement_pattern().
build_hexa_faces_pattern()
static void build_hexa_faces_pattern (IntTab & pattern) static
Definition at line 465 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {   0, 2, 4, 6 ,
                             0, 1, 4, 5 ,
                             0, 1, 2, 3 ,
                             1, 3, 5, 7 ,
                             2, 3, 6, 7 ,
                             4, 5, 6, 7 , -1
                         };
  fill_tab_2(t, 6, 4, pattern);
}
References fill_tab_2().
Referenced by build_faces_pattern().
build_nodes()
static void build_nodes (const DoubleTab & nodes_src, const IntTab & nodes_of_edges_src, DoubleTab & nodes_dest) static
Definition at line 617 of file Raffiner_Simplexes.cpp.
{
  assert( &(nodes_src) != &(nodes_dest) );
  const int nb_nodes_src = nodes_src.dimension(0);
  const int nb_edges_src = nodes_of_edges_src.dimension(0);
  const int nb_nodes_dest = nb_nodes_src + nb_edges_src;
  nodes_dest = nodes_src;
  nodes_dest.resize(nb_nodes_dest,Objet_U::dimension);
  int nb_node_per_edge_max= nodes_of_edges_src.dimension(1);
  if (nb_node_per_edge_max==20)
    for (int edge=0; edge<nb_edges_src; ++edge)
      {
        const int node_0 = nodes_of_edges_src(edge, 0);
        const int node_1 = nodes_of_edges_src(edge, 1);
        for (int i=0; i<Objet_U::dimension; ++i)
          {
            const double x = (nodes_src(node_0, i) + nodes_src(node_1, i)) * 0.5;
            nodes_dest(nb_nodes_src + edge, i) = x;
          }
      }
  else
    for (int edge=0; edge<nb_edges_src; ++edge)
      {
        int nb=nb_node_per_edge_max;
        while(nodes_of_edges_src(edge,nb-1)==-1) nb--;
        double inv=1./nb;
        const int node_0 = nodes_of_edges_src(edge, 0);
        for (int i=0; i<Objet_U::dimension; ++i)
          {
            double x = nodes_src(node_0, i);
            for (int c=1; c<nb; c++)
              {
                const int node_1 = nodes_of_edges_src(edge, c);
                x+=nodes_src(node_1, i);
              }
            nodes_dest(nb_nodes_src + edge, i) = x*inv;
          }
      }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, and TRUSTTab< _TYPE_ >::resize().
Referenced by Raffiner_Simplexes::refine_domain().
build_quadrangle_cell_refinement_pattern()
static void build_quadrangle_cell_refinement_pattern (IntTab & pattern) static
< triangle defini par sommet0 arete0 arete1
< etc...
Definition at line 114 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  NODE_ID(0), EDGE_ID(0), EDGE_ID(3), EDGE_ID(4), //!< triangle defini par sommet0 arete0 arete1
                            EDGE_ID(0), NODE_ID(1), EDGE_ID(4),EDGE_ID(1), //!< etc...
                            EDGE_ID(4), EDGE_ID(1), EDGE_ID(2), NODE_ID(3),
                            EDGE_ID(3), EDGE_ID(4), NODE_ID(2), EDGE_ID(2), -1
                         } ;
  fill_tab_2(t, 4, 4, pattern);
}
References EDGE_ID, fill_tab_2(), and NODE_ID.
Referenced by build_cell_refinement_pattern().
build_quadrangle_edges_pattern()
static void build_quadrangle_edges_pattern (IntTab & pattern) static
Definition at line 342 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  2,0, 1 ,
                            2,1, 3,
                            2, 2, 3,
                            2, 0, 2,
                            4,0,3,1,2,
                            -1
                         };
  fill_tab_2_new(t, 5, 4, pattern);
}
References fill_tab_2_new().
Referenced by build_edges_pattern().
build_quadrangle_face_refinement_pattern()
static void build_quadrangle_face_refinement_pattern (IntTab & pattern) static
Definition at line 218 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {   NODE_ID(0), EDGE_ID(0),
                             EDGE_ID(0), NODE_ID(1),
                             NODE_ID(3), EDGE_ID(1),
                             EDGE_ID(1), NODE_ID(1),
                             NODE_ID(3), EDGE_ID(2),
                             EDGE_ID(2), NODE_ID(2),
                             NODE_ID(0), EDGE_ID(3),
                             EDGE_ID(3), NODE_ID(2),-1
                         };
  fill_tab_3(t, 4, 2, 2, pattern);
}
References EDGE_ID, fill_tab_3(), and NODE_ID.
Referenced by build_face_refinement_pattern().
build_quadrangle_faces_pattern()
static void build_quadrangle_faces_pattern (IntTab & pattern) static
Definition at line 438 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  0, 1 ,
                            1, 3,
                            3, 2 ,
                            2, 0 , -1
                         };
  fill_tab_2(t, 4, 2, pattern);
}
References fill_tab_2().
Referenced by build_faces_pattern().
build_tetrahedron_cell_refinement_pattern()
static void build_tetrahedron_cell_refinement_pattern (IntTab & pattern) static
< tetraedre defini par sommet0 arete0 arete1 arete2
< etc...
Definition at line 134 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  NODE_ID(0), EDGE_ID(0), EDGE_ID(1), EDGE_ID(2) , //!< tetraedre defini par sommet0 arete0 arete1 arete2
                            EDGE_ID(0), NODE_ID(1), EDGE_ID(3), EDGE_ID(4) , //!< etc...
                            EDGE_ID(1), EDGE_ID(3), NODE_ID(2), EDGE_ID(5) ,
                            EDGE_ID(2), EDGE_ID(4), EDGE_ID(5), NODE_ID(3) ,
                            EDGE_ID(1), EDGE_ID(5), EDGE_ID(4), EDGE_ID(3) ,
                            EDGE_ID(5), EDGE_ID(4), EDGE_ID(2), EDGE_ID(1) ,
                            EDGE_ID(4), EDGE_ID(2), EDGE_ID(1), EDGE_ID(0) ,
                            EDGE_ID(3), EDGE_ID(1), EDGE_ID(0), EDGE_ID(4) , -1
                         };
  fill_tab_2(t, 8, 4, pattern);
}
References EDGE_ID, fill_tab_2(), and NODE_ID.
Referenced by build_cell_refinement_pattern().
build_tetrahedron_edges_pattern()
static void build_tetrahedron_edges_pattern (IntTab & pattern) static
< L'arete 0 est entre le sommet 0 et le sommet 1 de l'element
< L'arete 1 est entre 0 et 2
< etc...
Definition at line 364 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  0, 1 , //!< L'arete 0 est entre le sommet 0 et le sommet 1 de l'element
                            0, 2 , //!< L'arete 1 est entre 0 et 2
                            0, 3 , //!< etc...
                            1, 2 ,
                            1, 3 ,
                            2, 3 , -1
                         };
  fill_tab_2(t, 6, 2, pattern);
}
References fill_tab_2().
Referenced by build_edges_pattern().
build_tetrahedron_face_refinement_pattern()
static void build_tetrahedron_face_refinement_pattern (IntTab & pattern) static
Definition at line 248 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = { NODE_ID(1), EDGE_ID(3), EDGE_ID(4),
                           EDGE_ID(3), NODE_ID(2), EDGE_ID(5),
                           EDGE_ID(4), EDGE_ID(5), NODE_ID(3),
                           EDGE_ID(5), EDGE_ID(4), EDGE_ID(3),
                           NODE_ID(2), EDGE_ID(1), EDGE_ID(5),
                           EDGE_ID(1), NODE_ID(0), EDGE_ID(2),
                           EDGE_ID(5), EDGE_ID(2), NODE_ID(3),
                           EDGE_ID(2), EDGE_ID(5), EDGE_ID(1),
                           NODE_ID(3), EDGE_ID(2), EDGE_ID(4),
                           EDGE_ID(2), NODE_ID(0), EDGE_ID(0),
                           EDGE_ID(4), EDGE_ID(0), NODE_ID(1),
                           EDGE_ID(0), EDGE_ID(4), EDGE_ID(2),
                           NODE_ID(0), EDGE_ID(1), EDGE_ID(0),
                           EDGE_ID(1), NODE_ID(2), EDGE_ID(3),
                           EDGE_ID(0), EDGE_ID(3), NODE_ID(1),
                           EDGE_ID(3), EDGE_ID(0), EDGE_ID(1), -1
                         };
  fill_tab_3(t, 4, 4, 3, pattern);
}
References EDGE_ID, fill_tab_3(), and NODE_ID.
Referenced by build_face_refinement_pattern().
build_tetrahedron_faces_pattern()
static void build_tetrahedron_faces_pattern (IntTab & pattern) static
Definition at line 456 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  1, 2, 3,
                            2, 0, 3,
                            3, 0, 1,
                            0, 2, 1, -1
                         };
  fill_tab_2(t, 4, 3, pattern);
}
References fill_tab_2().
Referenced by build_faces_pattern().
build_triangle_cell_refinement_pattern()
static void build_triangle_cell_refinement_pattern (IntTab & pattern) static
< triangle defini par sommet0 arete0 arete1
< etc...
Definition at line 124 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  NODE_ID(0), EDGE_ID(0), EDGE_ID(1), //!< triangle defini par sommet0 arete0 arete1
                            EDGE_ID(0), NODE_ID(1), EDGE_ID(2), //!< etc...
                            EDGE_ID(1), EDGE_ID(2), NODE_ID(2),
                            EDGE_ID(2), EDGE_ID(1), EDGE_ID(0), -1
                         } ;
  fill_tab_2(t, 4, 3, pattern);
}
References EDGE_ID, fill_tab_2(), and NODE_ID.
Referenced by build_cell_refinement_pattern().
build_triangle_edges_pattern()
static void build_triangle_edges_pattern (IntTab & pattern) static
Definition at line 355 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  0, 1 ,
                            0, 2 ,
                            1, 2 , -1
                         };
  fill_tab_2(t, 3, 2, pattern);
}
References fill_tab_2().
Referenced by build_edges_pattern().
build_triangle_face_refinement_pattern()
static void build_triangle_face_refinement_pattern (IntTab & pattern) static
Definition at line 234 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  NODE_ID(2), EDGE_ID(2),
                            EDGE_ID(2), NODE_ID(1),
                            NODE_ID(0), EDGE_ID(1),
                            EDGE_ID(1), NODE_ID(2),
                            NODE_ID(1), EDGE_ID(0),
                            EDGE_ID(0), NODE_ID(0), -1
                         };
  fill_tab_3(t, 3, 2, 2, pattern);
}
References EDGE_ID, fill_tab_3(), and NODE_ID.
Referenced by build_face_refinement_pattern().
build_triangle_faces_pattern()
static void build_triangle_faces_pattern (IntTab & pattern) static
Definition at line 447 of file Raffiner_Simplexes.cpp.
{
  static const int t[] = {  2, 1 ,
                            0, 2,
                            1, 0 , -1
                         };
  fill_tab_2(t, 3, 2, pattern);
}
References fill_tab_2().
Referenced by build_faces_pattern().
fill_tab_2()
static void fill_tab_2 (const int * t, int n, int m, IntTab & tab) static
Definition at line 50 of file Raffiner_Simplexes.cpp.
{
  tab.resize(n, m);
  for (int i=0; i<n; ++i)
    {
      for (int j=0; j<m; ++j)
        {
          tab(i,j) = t[i*m+j];
        }
    }
  if (t[n*m] != -1)
    {
      Cerr << "Error in Raffiner_Simplexes 'filltab_2'" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, and TRUSTTab< _TYPE_ >::resize().
Referenced by build_hexa_cell_refinement_pattern(), build_hexa_faces_pattern(), build_quadrangle_cell_refinement_pattern(), build_quadrangle_faces_pattern(), build_tetrahedron_cell_refinement_pattern(), build_tetrahedron_edges_pattern(), build_tetrahedron_faces_pattern(), build_triangle_cell_refinement_pattern(), build_triangle_edges_pattern(), and build_triangle_faces_pattern().
fill_tab_2_new()
static void fill_tab_2_new (const int * t, int n, int m, IntTab & tab) static
Definition at line 68 of file Raffiner_Simplexes.cpp.
{
  tab.resize(n, m);
  tab=-1;
  int compt=0;
  for (int i=0; i<n; ++i)
    {
      int nb=t[compt++];
      for (int j=0; j<nb; ++j)
        {
          tab(i,j) = t[compt++];
        }
    }
  if (t[compt] != -1)
    {
      Cerr << "Error in Raffiner_Simplexes 'filltab_2_new'" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, and TRUSTTab< _TYPE_ >::resize().
Referenced by build_hexa_edges_pattern(), and build_quadrangle_edges_pattern().
fill_tab_3()
static void fill_tab_3 (const int * t, int n, int m, int p, IntTab & tab) static
Definition at line 91 of file Raffiner_Simplexes.cpp.
{
  tab.resize(n, m, p);
  for (int i=0; i<n; ++i)
    {
      for (int j=0; j<m; ++j)
        {
          for (int k=0; k<p; ++k)
            {
              tab(i,j,k) = t[(i*m+j)*p+k];
            }
        }
    }
  if (t[n*m*p] != -1)
    {
      Cerr << "Error in Raffiner_Simplexes 'filltab_3'" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, and TRUSTTab< _TYPE_ >::resize().
Referenced by build_hexa_face_refinement_pattern(), build_quadrangle_face_refinement_pattern(), build_tetrahedron_face_refinement_pattern(), and build_triangle_face_refinement_pattern().
find_refined_node_index()
static int find_refined_node_index (const IntTab & nodes_of_cells_src, const IntTab & edges_of_cells_src, int nb_nodes_src, int cell_src, int index) static
Definition at line 665 of file Raffiner_Simplexes.cpp.
{
  int node_index = -1;
  if (index >= 0)
    {
      const int idx = NODE_ID(index);
      node_index = nodes_of_cells_src(cell_src,idx);
    }
  else
    {
      const int idx = EDGE_ID(index);
      node_index = nb_nodes_src + edges_of_cells_src(cell_src,idx);
    }
  return node_index;
}
References EDGE_ID, and NODE_ID.
Referenced by build_cells(), build_frontier(), and Raffiner_Simplexes::refine_domain().
type_elem()
int type_elem (const Nom & cell_type)
Definition at line 176 of file Raffiner_Simplexes.cpp.
{
  Motcles understood_keywords(6);
  understood_keywords[0] = "Triangle";
  understood_keywords[1] = "Tetraedre";
  understood_keywords[2] = "Rectangle";
  understood_keywords[3] = "Hexaedre";
  understood_keywords[4] = "Quadrangle";
  understood_keywords[5] = "Hexaedre_VEF";
  int rank = understood_keywords.search(cell_type);
  if (rank>3) rank-=2;
  return rank;
}
References Motcles::search().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Polyedre::ajouter_elements(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Zone_Cl_VEF::associer(), build_cell_refinement_pattern(), build_edges_pattern(), build_face_refinement_pattern(), build_faces_pattern(), Polyedre::build_reduced(), Polygone::build_reduced(), build_triofield(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), calculer_coef_som(), Champ_Generique_Extraction::completer(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), convert_domain_to_Domaine(), corriger_type(), Champ_Fonc_MED::creer(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ_fonc_don(), Format_Post_Med::ecrire_champ_med(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), Champ_input_P0::getTemplate(), histogramme_angle(), latatoother::interpreter(), Extraire_plan::interpreter_(), projette(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Transformer::transformation_complete(), type_face_to_type_elem(), and Transformer::verifie_type_elem().
Variable Documentation
Raffiner_Simplexesbases
const Type_info* Raffiner_Simplexesbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 28 of file Raffiner_Simplexes.cpp.
synonym_Raffiner_Simplexes__LINE__
const Synonyme_info synonym_Raffiner_Simplexes__LINE__("Raffiner_isotrope", Raffiner_Simplexes ::info_obj.name()) ("Raffiner_isotrope" , Raffiner_Simplexes ::info_obj. name())
Raffiner_Simplexes class replaces the obsolete Raffiner_isotrope class.