TRUST: src/ThHyd/Chimie/Reaction.cpp File Reference
Reaction.cpp File Reference
#include <Reaction.h>
#include <Parser_U.h>
#include <Param.h>
#include <Equation_base.h>
#include <Probleme_base.h>
#include <Discretisation_base.h>
Functions
void extract_coef_local (ArrOfDouble &coeff_reactifs, const Nom &reactifs_, const Motcles &list_var)
Variables
const Type_info * Reactionbases [1] ={ &(Objet_U ::info_obj)}
const Type_info * List_Reactionbases [1] ={ &(liste ::info_obj)}
Function Documentation
extract_coef_local()
void extract_coef_local (ArrOfDouble & coeff_reactifs, const Nom & reactifs_, const Motcles & list_var)
Definition at line 54 of file Reaction.cpp.
{
  int sz=list_var.size();
  assert(sz==list_var.size());
  Parser_U parser;
  parser.setNbVar(sz);
  for (int i=0; i<sz; i++)
    parser.addVar(list_var[i]);
  Nom copie(reactifs_);
  parser.setString(copie);
  parser.parseString();
  coeff_reactifs.resize_array(sz);
  for (int i=0; i<sz; i++)
    {
      for (int j=0; j<sz; j++)
        parser.setVar(j,0);
      parser.setVar(i,1);
      double val=parser.eval();
      coeff_reactifs[i]=val;
    }
  Cerr<<reactifs_<<" "<<list_var<<" "<<coeff_reactifs<<finl;
  for (int i=0; i<sz; i++) Cerr<<coeff_reactifs[i]<<"*"<<list_var[i]<<"+";
  Cerr<<finl;
}
References Parser_U::addVar(), Cerr, Parser_U::eval(), finl, Parser_U::parseString(), TRUSTArray< _TYPE_ >::resize_array(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), and vect_impl::size().
Referenced by Reaction::completer(), and Reaction::extract_coef().
Variable Documentation
List_Reactionbases
const Type_info* List_Reactionbases[1] ={ &(liste ::info_obj)}
Definition at line 24 of file Reaction.cpp.
Reactionbases
const Type_info* Reactionbases[1] ={ &(Objet_U ::info_obj)}
Definition at line 23 of file Reaction.cpp.