TRUST: src/Kernel/Geometrie/Reordonner_faces_periodiques.cpp File Reference
Reordonner_faces_periodiques.cpp File Reference
#include <Reordonner_faces_periodiques.h>
#include <Domaine.h>
#include <Scatter.h>
#include <Octree_Double.h>
#include <Param.h>
Functions
void message ()
static void calculer_vecteur_2faces (const DoubleTab &coord, const IntTab &faces, const int i_face1, const int i_face2, ArrOfDouble &vect)
static double local_norme_vect (const DoubleVect &dv)
Function Documentation
calculer_vecteur_2faces()
static void calculer_vecteur_2faces (const DoubleTab & coord, const IntTab & faces, const int i_face1, const int i_face2, ArrOfDouble & vect) inline static
Definition at line 27 of file Reordonner_faces_periodiques.cpp.
{
  const int nb_som_faces = faces.dimension(1);
  const int dim = coord.dimension(1);
  assert(vect.size_array() == dim);
  vect = 0.;
// Calcul du vecteur entre le centre de la face i et le centre de la face i+n
  for (int j = 0; j < nb_som_faces; j++)
    {
      const int sommet1 = faces(i_face1, j);
      const int sommet2 = faces(i_face2, j);
      for (int compo = 0; compo < dim; compo++)
        vect[compo] += coord(sommet2, compo) - coord(sommet1, compo);
    }
  vect /= nb_som_faces;
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Reordonner_faces_periodiques::check_faces_periodiques(), and Reordonner_faces_periodiques::chercher_direction_perio().
local_norme_vect()
static double local_norme_vect (const DoubleVect & dv) static
Definition at line 49 of file Reordonner_faces_periodiques.cpp.
{
  double x=0.0;
  for(int i=0; i< dv.size_reelle(); i++)
    x += dv(i)*dv(i);
  x = sqrt(x);
  return x;
}
References TRUSTVect< _TYPE_ >::size_reelle().
Referenced by Reordonner_faces_periodiques::chercher_direction_perio().
message()
void message () inline
Definition at line 21 of file Reordonner_faces_periodiques.cpp.
{
  Cerr << "You need to use the Corriger_frontiere_periodique keyword on the periodic boundaries." << finl;
  Cerr << "See the reference manual to use this keyword on your data file." << finl;
}
References Cerr, and finl.
Referenced by Champ_base::affecter_erreur(), Param::ajouter_condition(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::check_faces_periodiques(), Statistiques::dump(), Process::exit(), Champ_Generique_refChamp::get_localisation(), Champ_Generique_refChamp::get_ref_connectivity(), Debog_Pb::goto_msg(), mpi_print_error(), Statistiques::print_communciation_tracking_details(), print_statistics_analyse(), Reordonner_faces_periodiques::renum_som_perio(), and Debog_Pb::verifier_partie_std().