TRUST: src/Kernel/Geometrie/Scatter.cpp File Reference
Scatter.cpp File Reference
#include <Scatter.h>
#include <Domaine.h>
#include <LecFicDistribueBin.h>
#include <Statistiques.h>
#include <TRUSTTabs.h>
#include <Connectivite_som_elem.h>
#include <Schema_Comm.h>
#include <Faces_builder.h>
#include <Zone_VF.h>
#include <Reordonner_faces_periodiques.h>
#include <Postraitement_lata.h>
#include <communications.h>
#include <MD_Vector_tools.h>
#include <MD_Vector_std.h>
#include <unistd.h>
#include <Poly_geom_base.h>
#include <Entree_Brute.h>
#include <Comm_Group_MPI.h>
#include <FichierHDFPar.h>
#include <LecFicDiffuse.h>
#include <EFichierBin.h>
Classes
class Traduction_Indice_Global_Local
Cette classe fournit les outils pour construire l'espace
virtuel d'un tableau contenant des indices d'entites geometriques<br>(sommets, elements, faces). Elle gere en particulier la
renumerotation des elements virtuels.
Functions
static void dump_lata (const Domaine &dom)
static void array_trier_retirer_doublons (ArrOfInt &array)
Methode outil pour retirer les doublons dans un tableau.
static void array_retirer_elements (ArrOfInt &sorted_array, const ArrOfInt &sorted_elements_list)
Retire de "sorted_array" les elements qui figurent dans "sorted_elements".
Les deux tableaux doivent etre initialement ordonnes dans l'ordre croissant.
Exemple:
En entree sorted_array=[1,4,9,10,12,18], sorted_elements=[3,5,9,10,18,25]
En sortie sorted_array=[1,4,12].
static int ajouter_joint (Zone &zone, int pe)
Nom endian ()
static void calculer_espace_distant_item (Zone &la_zone, const Joint::Type_Item type_item, const IntTab &connectivite_elem_item, const int nb_items_reels, const ArrOfInt &items_lies)
Methode generique pour calculer l'espace distant d'un type d'items geometrique<br>(sommet, face, arete) en fonction de l'espace distant des elements:
Les "type_item" distants (pour type_item = sommet face ou arete) sont
les "type_item" attaches aux elements distants.
Exemple : les sommets distants sont tous les sommets de tous les elements
distants.
Voir aussi:
Scatter::calculer_espace_distant_sommets
Scatter::calculer_espace_distant_faces
Parametre: zone
Signification: bah, la zone quoi...
Parametre: type_item
Signification: le type des items dont on veut calculer l'espace distant
Parametre: connectivite_elem_item
Signification: le tableau qui donne pour chaque element de la zone les
indices des items de cet element. On n'utilise que la partie reele du
tableau (logiquement, la partie virtuelle n'existe pas encore).
(exemple: zone().les_elems() pour type_item==SOMMET ou zone_VF().face_sommets()
pour type_item==FACE)
Parametre: nb_items_reels
Signification: le nombre de "type_item" reels
Parametre: items_lies
Signification: si le tableau est non vide, il doit etre de taille nb_items_reels.
Dans ce cas, il permet de forcer la propriete suivante :
"si l'item i est distant, alors l'item items_lies[i] est distant aussi".
Ce tableau est utilise pour inclure les sommets periodiques virtuels associes.
(voir calculer_espace_distant_sommets).
static True_int fct_tri_table_inverse (const void *ptr1, const void *ptr2)
static void calculer_liste_complete_sommets_joint (const Joint &joint, ArrOfInt &liste_sommets)
Methode outil: renvoie une liste complete de tous les
sommets de joint (sommets des faces + sommets isoles), triee et
sans doublons.
int arete_de_sommets_Si_et_Sj (const int Si, const int Sj, const int arete, const IntTab &aretes_som)
static void calculer_liste_complete_aretes_joint (const Joint &joint, ArrOfInt &liste_aretes)
Methode outil: renvoie une liste complete de tous les
aretes de joint (aretes des faces + aretes isolees), triee et
sans doublons.
static void calculer_liste_complete_items_joint (const Joint &joint, const Joint::Type_Item type_item, ArrOfInt &liste_items)
static True_int fct_cmp_coordonnees (const double *s1, const double *s2)
static True_int fct_cmp_index_coord (const void *ptr1, const void *ptr2)
static void init_simple_md_vector (MD_Vector_std &md, const int n)
Variables
Stat_Counter_Id interprete_scatter_counter_
< PGI
const Type_info * Scatterbases [1] ={ &(Interprete ::info_obj)}
static int fct_cmp_coord_dimension = -1
static double fct_cmp_coord_epsilon = -1.
static const DoubleTab * fct_cmp_coord_tableau = 0
Function Documentation
ajouter_joint()
static int ajouter_joint (Zone & zone, int pe) static
Definition at line 839 of file Scatter.cpp.
{
  Joints& joints = zone.faces_joint();
  const int i_joint = joints.size();
  {
    for (int i = 0; i < i_joint; i++)
      if (joints[i].PEvoisin() == pe)
        return i;
  }
  Joint& joint = joints.add(Joint());
  joint.nommer(Nom("Joint_")+Nom(pe));
  joint.associer_zone(zone);
  int ep = (i_joint > 0) ? joints[0].epaisseur() : 1;
  joint.affecte_epaisseur(ep);
  joint.affecte_PEvoisin(pe);
// Initialiser tous les tableaux des joints supplementaires.
// Note BM: pour bien faire, il faudrait initialiser uniquement
// certains tableaux (ceux qui sont deja initialises pour les
// joints existants), mais c'est plus complique a faire...
  {
    for (int t = 0; t < 5; t++)
      {
        Joint::Type_Item type;
        switch(t)
          {
          case 0:
            type = Joint::SOMMET;
            break;
          case 1:
            type = Joint::ELEMENT;
            break;
          case 2:
            type = Joint::FACE;
            break;
          case 3:
            type = Joint::ARETE;
            break;
          case 4:
            type = Joint::FACE_FRONT;
            break;
          default:
            Cerr << "Error in Scatter.cpp : ajouter_joint" << finl;
// Pour eviter le warning suivant sur gcc 3.4:
// Scatter.cpp:416: warning: 'type' might be used uninitialized in this function
            type = Joint::SOMMET;
            Process::exit();
          }
        Joint_Items& data = joint.set_joint_item(type);
        data.set_items_communs();
        data.set_items_distants();
        data.set_nb_items_virtuels(0);
        data.set_renum_items_communs().resize(0,2);
      }
  }
  return i_joint;
}
References List_Joint::add(), Joint::affecte_epaisseur(), Joint::affecte_PEvoisin(), Joint::ARETE, Frontiere::associer_zone(), Cerr, Joint::ELEMENT, Process::exit(), Joint::FACE, Joint::FACE_FRONT, Zone::faces_joint(), finl, Frontiere::nommer(), TRUSTTab< _TYPE_ >::resize(), Joint_Items::set_items_communs(), Joint_Items::set_items_distants(), Joint::set_joint_item(), Joint_Items::set_nb_items_virtuels(), Joint_Items::set_renum_items_communs(), liste::size(), and Joint::SOMMET.
Referenced by Scatter::ajouter_joints().
arete_de_sommets_Si_et_Sj()
int arete_de_sommets_Si_et_Sj (const int Si, const int Sj, const int arete, const IntTab & aretes_som) inline
Definition at line 1908 of file Scatter.cpp.
{
  if ( (aretes_som(arete,0) == Si && aretes_som(arete,1) == Sj)
       || (aretes_som(arete,1) == Si && aretes_som(arete,0) == Sj) )
    return 1;
  else
    return 0;
}
Referenced by calculer_liste_complete_aretes_joint().
array_retirer_elements()
static void array_retirer_elements (ArrOfInt & sorted_array, const ArrOfInt & sorted_elements_list) static
Retire de "sorted_array" les elements qui figurent dans "sorted_elements".
Les deux tableaux doivent etre initialement ordonnes dans l'ordre croissant.
Exemple:
En entree sorted_array=[1,4,9,10,12,18], sorted_elements=[3,5,9,10,18,25]
En sortie sorted_array=[1,4,12].
< Index dans sorted_array (en lecture)
< Index dans sorted_array (la ou on ecrit)
< Index dans sorted_elements
< Tableau trie ?
Definition at line 797 of file Scatter.cpp.
{
  int i_read;      //!< Index dans sorted_array (en lecture)
  int i_write = 0; //!< Index dans sorted_array (la ou on ecrit)
  int j = 0;       //!< Index dans sorted_elements
  const int n = sorted_array.size_array();
  const int m = sorted_elements_list.size_array();
  if (m == 0)
    return;
  int j_value = sorted_elements_list[j];
  for (i_read = 0; i_read < n; i_read++)
    {
// Tableau trie ?
      assert(i_read == 0 || sorted_array[i_read] > sorted_array[i_read-1]);
      const int i_value = sorted_array[i_read];
// On avance dans la liste sorted_elements jusqu'a trouver ou depasser
// l'element i_value
      while ((j_value < i_value) && (j < m))
        {
          j++;
          if (j == m)
            break;
          assert(sorted_elements_list[j] > j_value); //!< Tableau trie ?
          j_value = sorted_elements_list[j];
        }
      if (j == m || j_value != i_value)
        {
// i_value ne figure pas dans le tableau sorted_elements, on le garde
          sorted_array[i_write] = i_value;
          i_write++;
        }
    }
  sorted_array.resize_array(i_write);
}
References TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Scatter::ajouter_joints(), Scatter::calculer_espace_distant(), and calculer_liste_complete_aretes_joint().
array_trier_retirer_doublons()
static void array_trier_retirer_doublons (ArrOfInt & array) static
Methode outil pour retirer les doublons dans un tableau.
Definition at line 769 of file Scatter.cpp.
{
  const int size_ = array.size_array();
  if (size_ == 0)
    return;
// Tri dans l'ordre croissant
  array.ordonne_array();
// Retire les doublons
  int new_size_ = 1;
  int last_value = array[0];
  for (int i = 1; i < size_; i++)
    {
      if (array[i] != last_value)
        {
          array[new_size_] = last_value = array[i];
          new_size_++;
        }
    }
  array.resize_array(new_size_);
}
References TRUSTArray< _TYPE_ >::ordonne_array(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Scatter::ajouter_joints(), append_global_md(), auto_build_joints(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_sommets_joints_ssdom(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), and Raffiner_Simplexes::refine_domain().
calculer_espace_distant_item()
static void calculer_espace_distant_item (Zone & la_zone, const Joint::Type_Item type_item, const IntTab & connectivite_elem_item, const int nb_items_reels, const ArrOfInt & items_lies) static
Methode generique pour calculer l'espace distant d'un type d'items geometrique<br>(sommet, face, arete) en fonction de l'espace distant des elements:
Les "type_item" distants (pour type_item = sommet face ou arete) sont
les "type_item" attaches aux elements distants.
Exemple : les sommets distants sont tous les sommets de tous les elements
distants.
Voir aussi:
Scatter::calculer_espace_distant_sommets
Scatter::calculer_espace_distant_faces
Parametre: zone
Signification: bah, la zone quoi...
Parametre: type_item
Signification: le type des items dont on veut calculer l'espace distant
Parametre: connectivite_elem_item
Signification: le tableau qui donne pour chaque element de la zone les
indices des items de cet element. On n'utilise que la partie reele du
tableau (logiquement, la partie virtuelle n'existe pas encore).
(exemple: zone().les_elems() pour type_item==SOMMET ou zone_VF().face_sommets()
pour type_item==FACE)
Parametre: nb_items_reels
Signification: le nombre de "type_item" reels
Parametre: items_lies
Signification: si le tableau est non vide, il doit etre de taille nb_items_reels.
Dans ce cas, il permet de forcer la propriete suivante :
"si l'item i est distant, alors l'item items_lies[i] est distant aussi".
Ce tableau est utilise pour inclure les sommets periodiques virtuels associes.
(voir calculer_espace_distant_sommets).
< chaine de liaisons interdite
Definition at line 1210 of file Scatter.cpp.
{
  const Joints& joints                 = la_zone.faces_joint();
  const int   nb_joints              = joints.size();
  const int   nproc                  = Process::nproc();
  const int   nb_items_par_element   = connectivite_elem_item.dimension(1);
// Les type_item a envoyer a chaque processeur:
  ArrsOfInt items_to_send(nproc);
// Un tableau temporaire;
  ArrOfInt liste_items;
  liste_items.set_smart_resize(1);
// Est-ce qu'il y a des items lies ?
  const int flag_items_lies = (items_lies.size_array() > 0);
  assert(flag_items_lies == 0 || items_lies.size_array() == nb_items_reels);
  for (int i_joint = 0; i_joint < nb_joints; i_joint++)
    {
      const Joint&     joint          = joints[i_joint];
      const int     pe_voisin      = joint.PEvoisin();
      const ArrOfInt& esp_dist_elems = joint.joint_item(Joint::ELEMENT).items_distants();
      const int     nb_elems_dist  = esp_dist_elems.size_array();
      liste_items.resize_array(0);
// On met dans liste_items tous les items de tous les elements
// qui sont dans esp_dist_elems:
      for (int i_elem = 0; i_elem < nb_elems_dist; i_elem++)
        {
          const int elem = esp_dist_elems[i_elem];
          for (int i_item = 0; i_item < nb_items_par_element; i_item++)
            {
              const int item = connectivite_elem_item(elem, i_item);
              if (item>-1)
                {
                  liste_items.append_array(item);
// Si un item est lie a l'item courant, on envoie aussi l'item lie.
                  if (flag_items_lies)
                    {
                      const int item_lie = items_lies[item];
                      if (item_lie != item)
{
                          assert(item_lie >= 0 && item_lie < nb_items_reels);
                          assert(items_lies[item_lie] == item_lie); //!< chaine de liaisons interdite
                          liste_items.append_array(item_lie);
                        }
                    }
                }
            }
        }
      array_trier_retirer_doublons(liste_items);
// Ces items doivent etre envoyes au processeur voisin:
      items_to_send[pe_voisin] = liste_items;
    }
// Calcul des espaces distants en fonction de "items_to_send"
  Scatter::calculer_espace_distant(la_zone, nb_items_reels, items_to_send, type_item);
}
References TRUSTArray< _TYPE_ >::append_array(), array_trier_retirer_doublons(), Scatter::calculer_espace_distant(), TRUSTTab< _TYPE_ >::dimension(), Joint::ELEMENT, Zone::faces_joint(), Joint_Items::items_distants(), Joint::joint_item(), Process::nproc(), Joint::PEvoisin(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), liste::size(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Scatter::calculer_espace_distant_aretes(), Scatter::calculer_espace_distant_faces(), and Scatter::calculer_espace_distant_sommets().
calculer_liste_complete_aretes_joint()
static void calculer_liste_complete_aretes_joint (const Joint & joint, ArrOfInt & liste_aretes) static
Methode outil: renvoie une liste complete de tous les
aretes de joint (aretes des faces + aretes isolees), triee et
sans doublons.
Definition at line 1920 of file Scatter.cpp.
{
// Construction de la liste des aretes communes liste_aretes
  liste_aretes.set_smart_resize(1);
//
// Recherche des aretes de joint sur les faces de joint
//
  int nb_faces_joint=joint.faces().nb_faces();
  int nb_som_faces=joint.faces().nb_som_faces();
  const IntTab& sommet=joint.faces().les_sommets();
  const Domaine& dom=joint.zone().domaine();
  const DoubleTab& coord=dom.coord_sommets();
  const IntTab& aretes_som=joint.zone().aretes_som();
  ArrOfInt aretes(1);
  int compteur=0;
  DoubleTab positions(1,Objet_U::dimension);
  ArrOfInt som_faces(nb_faces_joint*nb_som_faces);
// On parcourt 2 a 2 les sommets de chaque face du joint
  for (int face=0; face<nb_faces_joint; face++)
    for (int i=0; i<nb_som_faces; i++)
      {
        int Si = sommet(face,i);
        som_faces[face*nb_som_faces+i]=Si;
        for (int j=i; j<nb_som_faces; j++)
          {
            int Sj = sommet(face,j);
// Calcul du point C entre 2 sommets Si et Sj
            for (int comp=0; comp<Objet_U::dimension; comp++)
              positions(0,comp)=0.5*(coord(Si,comp)+coord(Sj,comp));
            dom.zone(0).chercher_aretes(positions,aretes);
// Si on trouve une arete dont le centre coincide avec le point C
// et dont les sommets sont identiques a Si et Sj, on ajoute l'arete a la liste
            if (aretes[0]>=0 && arete_de_sommets_Si_et_Sj(Si, Sj, aretes[0], aretes_som))
              {
                compteur++;
                liste_aretes.append_array(aretes[0]);
              }
          }
      }
  Process::Journal() << "common edges found on faces of joint with " << joint.PEvoisin() << " :" << compteur << finl;
//
// Recherche des aretes de joint isolees sur les sommets de joints isoles
//
// joint.sommets() contient parfois tous les sommets !
// Donc on construit un tableau som_isoles
  ArrOfInt som_isoles;
// Met tous les sommets dans som_isoles (isoles+issus des faces de joint):
  calculer_liste_complete_sommets_joint(joint, som_isoles);
// On trie som_faces et on supprime les doublons
  array_trier_retirer_doublons(som_faces);
// Supprime tous les sommets de som_isoles contenus dans som_faces
  array_retirer_elements(som_isoles, som_faces);
// Supprime les sommets des faces de joint
  const int n = som_isoles.size_array();
  Process::Journal() << "number of isolated nodes: " << n << finl;
  Process::Journal() << "number of nodes of faces of joint: " << 3*sommet.dimension(0) << finl;
  compteur=0;
// On parcourt 2 a 2 les sommets isoles
  for (int i = 0; i < n; i++)
    for (int j = i; j < n; j++)
      {
// Calcul du point C entre 2 sommets Si et Sj
        int Si = som_isoles[i];
        int Sj = som_isoles[j];
        for (int comp=0; comp<Objet_U::dimension; comp++)
          positions(0,comp)=0.5*(coord(Si,comp)+coord(Sj,comp));
        dom.zone(0).chercher_aretes(positions,aretes);
// Si on trouve une arete dont le centre coincide avec le point C
// et dont les sommets sont identiques a Si et Sj, on ajoute l'arete a la liste
        if (aretes[0]>=0 && arete_de_sommets_Si_et_Sj(Si, Sj, aretes[0], aretes_som))
          {
            compteur++;
            liste_aretes.append_array(aretes[0]);
          }
      }
  Process::Journal() << "common edges found isolated on joint with " << joint.PEvoisin() << " :" << compteur << finl;
// Retirer les doublons de la liste
  array_trier_retirer_doublons(liste_aretes);
}
References TRUSTArray< _TYPE_ >::append_array(), arete_de_sommets_Si_et_Sj(), Zone::aretes_som(), array_retirer_elements(), array_trier_retirer_doublons(), calculer_liste_complete_sommets_joint(), Zone::chercher_aretes(), compteur, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Frontiere::faces(), finl, Process::Journal(), Faces::les_sommets(), Faces::nb_faces(), Faces::nb_som_faces(), Joint::PEvoisin(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Frontiere::zone(), and Domaine::zone().
Referenced by calculer_liste_complete_items_joint().
calculer_liste_complete_items_joint()
static void calculer_liste_complete_items_joint (const Joint & joint, const Joint::Type_Item type_item, ArrOfInt & liste_items) static
Definition at line 2001 of file Scatter.cpp.
{
  switch(type_item)
    {
    case Joint::SOMMET:
      calculer_liste_complete_sommets_joint(joint, liste_items);
      break;
    case Joint::ARETE:
      calculer_liste_complete_aretes_joint(joint, liste_items);
      break;
    default:
      Cerr << "Error in Scatter::calculer_liste_complete_items_joint" << finl;
      Cerr << "Type of item not expected." << finl;
      Process::exit();
    }
}
References Joint::ARETE, calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Cerr, Process::exit(), finl, and Joint::SOMMET.
Referenced by Scatter::construire_correspondance_items_par_coordonnees().
calculer_liste_complete_sommets_joint()
static void calculer_liste_complete_sommets_joint (const Joint & joint, ArrOfInt & liste_sommets) static
Methode outil: renvoie une liste complete de tous les
sommets de joint (sommets des faces + sommets isoles), triee et
sans doublons.
Definition at line 1890 of file Scatter.cpp.
{
  liste_sommets = joint.joint_item(Joint::SOMMET).items_communs();
#if 0
  liste_sommets.set_smart_resize(1);
// On prend tous les sommets des faces de joint:
  const IntTab& som_faces = joint.faces().les_sommets();
  liste_sommets = ref_cast(ArrOfInt,som_faces);
// On ajoute tous les sommets isoles :
  const ArrOfInt& som_isoles = joint.sommets();
  const int n = som_isoles.size_array();
  for (int i = 0; i < n; i++)
    liste_sommets.append_array(som_isoles[i]);
// Retirer les doublons de la liste
  array_trier_retirer_doublons(liste_sommets);
#endif
}
References TRUSTArray< _TYPE_ >::append_array(), array_trier_retirer_doublons(), Frontiere::faces(), Joint_Items::items_communs(), Joint::joint_item(), Faces::les_sommets(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), and Joint::SOMMET.
Referenced by calculer_liste_complete_aretes_joint(), and calculer_liste_complete_items_joint().
dump_lata()
static void dump_lata (const Domaine & dom) static
Definition at line 92 of file Scatter.cpp.
{
  const Zone& zone = dom.zone(0);
  const int nb_joints = zone.nb_joints();
  const Comm_Group *cg = 0;
  Nom nom_fichier_lata("espaces_virtuels");
  Postraitement_lata::Format format = Postraitement_lata::BINAIRE;
  Postraitement_lata::ecrire_entete(nom_fichier_lata,
                                    "Discretisation_inconnue",
                                    format, cg);
  Postraitement_lata::ecrire_zone(nom_fichier_lata,
                                  zone,
                                  format, cg);
  Postraitement_lata::ecrire_temps(nom_fichier_lata,
                                   0.,
                                   format, cg);
  const int n = zone.nb_elem();
  DoubleTab data(n);
  for(int ij = 0; ij < nb_joints; ij++)
    {
      const ArrOfInt& t1 = zone.joint(ij).joint_item(Joint::ELEMENT).items_distants();
      data = 0.;
      {
        const int nt1 = t1.size_array();
        for (int i = 0; i < nt1; i++)
          data[t1[i]] += 1;
      }
      Postraitement_lata::ecrire_champ(nom_fichier_lata,
                                       Nom("partition") + Nom(zone.joint(ij).PEvoisin()),
                                       Postraitement_lata::CHAMP,
                                       'I',
                                       dom.le_nom(),
                                       "pb",
                                       0., /* temps */
                                       Postraitement_base::ELEMENTS,
                                       data,
                                       format);
    }
}
References Postraitement_lata::BINAIRE, Postraitement_lata::CHAMP, Postraitement_lata::ecrire_champ(), Postraitement_lata::ecrire_entete(), Postraitement_lata::ecrire_temps(), Postraitement_lata::ecrire_zone(), Joint::ELEMENT, Postraitement_base::ELEMENTS, Joint_Items::items_distants(), Zone::joint(), Joint::joint_item(), Domaine::le_nom(), Zone::nb_elem(), Zone::nb_joints(), Joint::PEvoisin(), TRUSTArray< _TYPE_ >::size_array(), and Domaine::zone().
Referenced by Scatter::interpreter().
endian()
Nom endian () inline
Definition at line 1124 of file Scatter.cpp.
{
  int x = 1;
  if(*(char *)&x == 1)
    return "little-endian";
  else
    return "big-endian";
}
fct_cmp_coordonnees()
static True_int fct_cmp_coordonnees (const double * s1, const double * s2) inline static
Definition at line 2451 of file Scatter.cpp.
{
  const int dim = fct_cmp_coord_dimension;
  const double epsilon = fct_cmp_coord_epsilon;
  assert(dim==2 || dim==3);
  if (s1[0] < s2[0] - epsilon)
    return -1;
  else if (s1[0] > s2[0] + epsilon)
    return 1;
  else if (s1[1] < s2[1] - epsilon)
    return -1;
  else if (s1[1] > s2[1] + epsilon)
    return 1;
  else if (dim<3)
    return 0;
  else if (s1[2] < s2[2] - epsilon)
    return -1;
  else if (s1[2] > s2[2] + epsilon)
    return 1;
  else
    return 0;
}
References fct_cmp_coord_dimension, and fct_cmp_coord_epsilon.
Referenced by Scatter::Chercher_Correspondance(), and fct_cmp_index_coord().
fct_cmp_index_coord()
static True_int fct_cmp_index_coord (const void * ptr1, const void * ptr2) static
Definition at line 2479 of file Scatter.cpp.
{
  const int i1 = *(const int *)ptr1;
  const int i2 = *(const int *)ptr2;
  const double * s1 = & (*fct_cmp_coord_tableau)(i1,0);
  const double * s2 = & (*fct_cmp_coord_tableau)(i2,0);
  const True_int resu = fct_cmp_coordonnees(s1, s2);
  return resu;
}
References fct_cmp_coordonnees().
Referenced by Scatter::Chercher_Correspondance().
fct_tri_table_inverse()
static True_int fct_tri_table_inverse (const void * ptr1, const void * ptr2) static
Definition at line 1498 of file Scatter.cpp.
{
  const int i1 = *(int*)ptr1;
  const int i2 = *(int*)ptr2;
#ifdef INT_is_64_
  if (i1 == i2)
    return 0;
  if (i1>i2)
    return 1;
  return -1;
#else
  return i1 - i2;
#endif
}
Referenced by Traduction_Indice_Global_Local::initialiser().
init_simple_md_vector()
static void init_simple_md_vector (MD_Vector_std & md, const int n) static
Definition at line 2836 of file Scatter.cpp.
{
  md.nb_items_tot_ = n;
  md.nb_items_reels_ = n;
  md.nb_items_seq_tot_ = n;
  md.nb_items_seq_local_ = n;
  md.blocs_items_to_sum_.resize_array(2, Array_base::NOCOPY_NOINIT);
  md.blocs_items_to_sum_[0] = 0;
  md.blocs_items_to_sum_[1] = n;
  md.blocs_items_to_compute_.resize_array(2, Array_base::NOCOPY_NOINIT);
  md.blocs_items_to_compute_[0] = 0;
  md.blocs_items_to_compute_[1] = n;
}
References MD_Vector_base2::blocs_items_to_compute_, MD_Vector_base2::blocs_items_to_sum_, MD_Vector_base2::nb_items_reels_, MD_Vector_base2::nb_items_seq_local_, MD_Vector_base2::nb_items_seq_tot_, MD_Vector_base2::nb_items_tot_, Array_base::NOCOPY_NOINIT, and TRUSTArray< _TYPE_ >::resize_array().
Referenced by Scatter::init_sequential_domain().
Variable Documentation
fct_cmp_coord_dimension
int fct_cmp_coord_dimension = -1 static
Definition at line 2448 of file Scatter.cpp.
Referenced by Scatter::Chercher_Correspondance(), and fct_cmp_coordonnees().
fct_cmp_coord_epsilon
double fct_cmp_coord_epsilon = -1. static
Definition at line 2449 of file Scatter.cpp.
Referenced by Scatter::Chercher_Correspondance(), and fct_cmp_coordonnees().
fct_cmp_coord_tableau
const DoubleTab* fct_cmp_coord_tableau = 0 static
Definition at line 2474 of file Scatter.cpp.
Referenced by Scatter::Chercher_Correspondance().
interprete_scatter_counter_
Stat_Counter_Id interprete_scatter_counter_ extern
< PGI
Definition at line 65 of file stat_counters.cpp.
Referenced by Scatter::interpreter().
Scatterbases
const Type_info* Scatterbases[1] ={ &(Interprete ::info_obj)}
Definition at line 42 of file Scatter.cpp.