TRUST: src/Kernel/Schemas_Temps/Schema_Implicite_Multi_TimeStep_base.cpp File Reference
Schema_Implicite_Multi_TimeStep_base.cpp File Reference
#include <Schema_Implicite_Multi_TimeStep_base.h>
#include <Equation_base.h>
#include <Probleme_base.h>
#include <Probleme_Couple.h>
#include <Milieu_base.h>
#include <Param.h>
#include <LecFicDiffuse.h>
#include <communications.h>
#include <Matrice_Morse.h>
Functions
static void Implicite_Multi_TimeStep_calcul_fac_sec (double &residu_, double &residu_old, double &facsec_, const double facsec_max_, int &nb_ite_sans_accel_)
static void Implicite_Multi_TimeStep_recommencer_pb (int nb_valeurs_passees, Probleme_base &pb)
Variables
const Type_info * Schema_Implicite_Multi_TimeStep_basebases [1] ={ &(Schema_Implicite_base ::info_obj)}
Function Documentation
Implicite_Multi_TimeStep_calcul_fac_sec()
static void Implicite_Multi_TimeStep_calcul_fac_sec (double & residu_, double & residu_old, double & facsec_, const double facsec_max_, int & nb_ite_sans_accel_) static
Definition at line 63 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  double rap                   = 1.2;
  int    nb_ite_sans_accel_max = 20000;
  if (residu_old==0)
    {
      residu_old=residu_;
      nb_ite_sans_accel_=0;
    }
  else if ((residu_old>rap*residu_)||(nb_ite_sans_accel_>nb_ite_sans_accel_max))
    {
      facsec_*=sqrt(rap);
      residu_old=residu_;
      facsec_=std::min(facsec_,facsec_max_);
      nb_ite_sans_accel_=0;
    }
  nb_ite_sans_accel_++;
}
Referenced by Schema_Implicite_Multi_TimeStep_base::mettre_a_jour().
Implicite_Multi_TimeStep_recommencer_pb()
static void Implicite_Multi_TimeStep_recommencer_pb (int nb_valeurs_passees, Probleme_base & pb) static
Definition at line 235 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  int i = 0;
  int j = 0;
  for(i=0; i<pb.nombre_d_equations(); i++)
    {
      for (j=0; j<nb_valeurs_passees; j++)
        {
          pb.equation(i).inconnue().passe(j) = pb.equation(i).inconnue().passe(j+1);
        }
    }
}
References Probleme_base::equation(), Equation_base::inconnue(), Probleme_base::nombre_d_equations(), and Champ_Inc::passe().
Referenced by Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), and Schema_Implicite_Multi_TimeStep_base::iterateTimeStep().
Variable Documentation
Schema_Implicite_Multi_TimeStep_basebases
const Type_info* Schema_Implicite_Multi_TimeStep_basebases[1] ={ &(Schema_Implicite_base ::info_obj)}
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.