TRUST: src/Kernel/Utilitaires/Schema_Comm.cpp File Reference
Schema_Comm.cpp File Reference
#include <Schema_Comm.h>
#include <PE_Groups.h>
#include <InOutCommBuffers.h>
#include <Comm_Group.h>
#include <communications.h>
#include <Comm_Group_MPI.h>
Functions
static void exchange_data (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, const Comm_Group &group, bool use_all_to_all)
static int check_PE_in_list (int num_pe, const ArrOfInt &list)
Variables
static const int BEGIN_COMM_TAG = 1
static const int ECHANGE_MESSAGES_COMM_TAG = 2
static const int END_COMM_TAG = 3
static const int COPY_OPERATOR_TAG = 4
Function Documentation
check_PE_in_list()
static int check_PE_in_list (int num_pe, const ArrOfInt & list) static
Definition at line 458 of file Schema_Comm.cpp.
{
  int i;
  int n = list.size_array();
  for (i = 0; i < n && list[i] != num_pe; i++);
  return (i < n);
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by Schema_Comm::recv_buffer(), and Schema_Comm::send_buffer().
exchange_data()
static void exchange_data (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, const Comm_Group & group, bool use_all_to_all) static
< dest
< source
< size Exchange data
< dest
< source
< size [ABN] arrruhhhhhmmmmmm:
Definition at line 171 of file Schema_Comm.cpp.
{
// GF je rajoute le ifdef pour les versions sans MPI comm_group_mpi n'existep pas
#ifdef MPI_
  if (!use_all_to_all || !sub_type(Comm_Group_MPI, group))
#else
// if (!use_all_to_all || !sub_type(Comm_Group_MPI, group))
// on n utilise pas le all_to_all car n'exsite pas sans MPI
  if (1)
#endif
    {
      group.send_recv_start(send_list, send_size, send_buffers,
                            recv_list, recv_size, recv_buffers);
      group.send_recv_finish();
    }
  else
    {
#ifdef MPI_
      const int n = group.nproc();
      const int nsend = send_list.size_array();
      const int nrecv = recv_list.size_array();
// Pack all send data in a single buffer:
      ArrOfInt a_send_size(n);
      ArrOfInt a_send_offset(n);
      ArrOfInt a_recv_size(n);
      ArrOfInt a_recv_offset(n);
      int i, offset;
// Compute send_size array
      for (i = 0; i < nsend; i++)
        a_send_size[send_list[i]] = send_size[i];
// Compute send_offset
      for (i = 0, offset = 0; i < n; i++)
        {
          a_send_offset[i] = offset;
          offset += a_send_size[i];
        }
      const int buf_size_send = offset;
// Compute recv_size array
      for (i = 0; i < nrecv; i++)
        a_recv_size[recv_list[i]] = recv_size[i];
// Compute recv_offset
      for (i = 0, offset = 0; i < n; i++)
        {
          a_recv_offset[i] = offset;
          offset += a_recv_size[i];
        }
      const int buf_size_recv = offset;
// Allocate contiguous send and recv buffer:
      char *send_buffer = (char *) malloc(buf_size_send);
      char *recv_buffer = (char *) malloc(buf_size_recv);
// Copy send data to send buffer
      for (i = 0; i < nsend; i++)
        memcpy(send_buffer + a_send_offset[send_list[i]], //!< dest
               send_buffers[i], //!< source
               send_size[i]); //!< size Exchange data
//
      ref_cast(Comm_Group_MPI, group).all_to_allv(send_buffer, a_send_size.addr(), a_send_offset.addr(),
                                                  recv_buffer, a_recv_size.addr(), a_recv_offset.addr());
// Copy recv data to recv_buffers
      for (i = 0; i < nrecv; i++)
        memcpy(recv_buffers[i], //!< dest
               recv_buffer + a_recv_offset[recv_list[i]], //!< source
               recv_size[i]); //!< size [ABN] arrruhhhhhmmmmmm:
//
      free(send_buffer);
      free(recv_buffer);
#endif
    }
}
References TRUSTArray< _TYPE_ >::addr(), Comm_Group::nproc(), ref_cast, Comm_Group::send_recv_finish(), Comm_Group::send_recv_start(), TRUSTArray< _TYPE_ >::size_array(), and sub_type.
Referenced by Schema_Comm::echange_messages(), and Schema_Comm::echange_taille().
Variable Documentation
BEGIN_COMM_TAG
const int BEGIN_COMM_TAG = 1 static
Definition at line 47 of file Schema_Comm.cpp.
Referenced by Schema_Comm::begin_comm().
COPY_OPERATOR_TAG
const int COPY_OPERATOR_TAG = 4 static
Definition at line 50 of file Schema_Comm.cpp.
Referenced by Schema_Comm::operator=().
ECHANGE_MESSAGES_COMM_TAG
const int ECHANGE_MESSAGES_COMM_TAG = 2 static
Definition at line 48 of file Schema_Comm.cpp.
Referenced by Schema_Comm::echange_messages(), and Schema_Comm::echange_taille().
END_COMM_TAG
const int END_COMM_TAG = 3 static
Definition at line 49 of file Schema_Comm.cpp.
Referenced by Schema_Comm::end_comm().