TRUST: src/ThHyd/Multiphase/Schemas_Temps/SETS.cpp File Reference
SETS.cpp File Reference
#include <Discretisation_base.h>
#include <Operateur_Diff_base.h>
#include <Schema_Temps_base.h>
#include <Masse_Multiphase.h>
#include <Neumann_val_ext.h>
#include <MD_Vector_tools.h>
#include <Assembleur_base.h>
#include <TRUSTTab_parts.h>
#include <QDM_Multiphase.h>
#include <Pb_Multiphase.h>
#include <Pb_Conduction.h>
#include <MD_Vector_std.h>
#include <Matrix_tools.h>
#include <Matrice_Bloc.h>
#include <Statistiques.h>
#include <Array_tools.h>
#include <TRUSTTrav.h>
#include <Dirichlet.h>
#include <Zone_VF.h>
#include <EChaine.h>
#include <Lapack.h>
#include <Debog.h>
#include <SETS.h>
#include <TablePrinter.h>
Functions
static double corriger_incr_alpha (const DoubleTab &alpha, DoubleTab &incr, double &err_a_sum)
Variables
const Type_info * SETSbases [1] ={ &(Simpler ::info_obj)}
const Type_info * ICEbases [1] ={ &(SETS ::info_obj)}
Function Documentation
corriger_incr_alpha()
static double corriger_incr_alpha (const DoubleTab & alpha, DoubleTab & incr, double & err_a_sum) inline static
Definition at line 109 of file SETS.cpp.
{
  int i, n, N = alpha.line_size();
  double a_sum, corr_max = 0;
  DoubleTrav n_a(N);
  for (i = 0, err_a_sum = 0; i < alpha.dimension_tot(0); i++)
    {
      for (a_sum = 0, n = 0; n < N; n++) n_a(n) = alpha(i, n) + incr(i, n), a_sum += n_a(n);
      err_a_sum = std::max(err_a_sum, std::abs(a_sum - 1));
      for (a_sum = 0, n = 0; n < N; n++) n_a(n) = std::max(n_a(n), 0.), a_sum += n_a(n);
      if (a_sum)
        for (n = 0; n < N; n++) n_a(n) /= a_sum;
      else for (n = 0; n < N; n++) n_a(n) = 1. / N;
      for (n = 0; n < N; n++) corr_max = std::max(corr_max, std::fabs(alpha(i, n) + incr(i, n) - n_a(n))), incr(i, n) = n_a(n) - alpha(i, n);
    }
  err_a_sum = Process::mp_max(err_a_sum);
  return Process::mp_max(corr_max);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::line_size(), and Process::mp_max().
Variable Documentation
ICEbases
const Type_info* ICEbases[1] ={ &(SETS ::info_obj)}
Definition at line 50 of file SETS.cpp.
SETSbases
const Type_info* SETSbases[1] ={ &(Simpler ::info_obj)}
Definition at line 48 of file SETS.cpp.