TRUST: src/ThHyd/Schemas_Temps/Simple.h File Reference
Simple.h File Reference
#include <TRUSTTabs_forward.h>
#include <Simpler_Base.h>
Classes
class Simple
Functions
void diviser_par_rho_np1_face (Equation_base &eqn, DoubleTab &tab)
Function Documentation
diviser_par_rho_np1_face()
void diviser_par_rho_np1_face (Equation_base & eqn, DoubleTab & tab)
Definition at line 83 of file Simple.cpp.
{
  Fluide_Dilatable_base& fluide_dil = ref_cast(Fluide_Dilatable_base,eqn.milieu());
  const DoubleTab& rho = fluide_dil.rho_face_np1();
  int nbdim = tab.nb_dim();
  int taille_0_tot = tab.dimension_tot(0);
  if (nbdim==1)
    for (int i=0; i<taille_0_tot; i++)
      tab(i) /= rho(i);
  else
    {
      int dim = tab.dimension(1);
      for (int i=0; i<taille_0_tot; i++)
        for (int j=0; j<dim; j++)
          tab(i,j) /= rho(i);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Equation_base::milieu(), TRUSTTab< _TYPE_ >::nb_dim(), ref_cast, and Fluide_Dilatable_base::rho_face_np1().
Referenced by Piso::iterer_NS(), and Simple::iterer_NS().