TRUST: src/ThHyd/Schemas_Temps/Simpler.h File Reference
Simpler.h File Reference
#include <Simple.h>
Classes
class Simpler
Functions
int inverser_par_diagonale (const Matrice_Morse &matrice, const DoubleTrav &resu, const DoubleTab &present, DoubleTrav &correction_en_vitesse)
Function Documentation
inverser_par_diagonale()
int inverser_par_diagonale (const Matrice_Morse & matrice, const DoubleTrav & resu, const DoubleTab & present, DoubleTrav & correction_en_vitesse)
Definition at line 44 of file Simpler.cpp.
{
  const IntVect& tab1 = matrice.get_tab1();
  const IntVect& tab2 = matrice.get_tab2();
  const DoubleVect& coeff = matrice.get_coeff();
  int deux_entrees=0;
  int nb_comp=1;
  if (resu.nb_dim()==2)
    {
      deux_entrees=1;
      nb_comp=resu.dimension(1);
    }
  int nb_ligne_reel=correction_en_vitesse.dimension(0);
// Determine U^
  if (deux_entrees==0)
    {
      for(int i=0; i<nb_ligne_reel; i++)
        {
          for(int j=0; j<nb_comp; j++)
            {
              double t=resu(i);
              for (int k=tab1(i*nb_comp+j); k<tab1(i*nb_comp+j+1)-1; k++)
                t -= coeff(k)*current(tab2(k)-1);
              correction_en_vitesse(i) = t/matrice(i*nb_comp+j,i*nb_comp+j);
            }
        }
// verif
// test
      if (0)
        for(int i=0; i<nb_ligne_reel; i++)
          {
            for (int j=0; j<nb_comp; j++)
              {
                int ii=i*nb_comp+j;
                double tmp=resu(i);
                for (int k = 0; k<matrice.nb_colonnes(); k++)
                  if ((k/nb_comp)!=i)
                    {
                      if (matrice(ii,k))
                        tmp -= matrice(ii,k)*current((k/nb_comp));
                    }
                double test=tmp/matrice(ii,ii);
                if (!est_egal(test,correction_en_vitesse(i),1e-5))
                  {
                    Cerr<<i<<" "<<j<<" "<<resu(i)<<finl;
                    Cerr<<test<<" ici "<<correction_en_vitesse(i)-test<<finl;
                    return -1;
                  }
              }
          }
    }
  else
    {
      for(int i=0; i<nb_ligne_reel; i++)
        {
          for(int j=0; j<nb_comp; j++)
            {
              double t=resu(i,j);
              for (int k=tab1(i*nb_comp+j); k<tab1(i*nb_comp+j+1)-1; k++)
                {
                  int i1 = (tab2(k)-1)/nb_comp;
                  int j1 = (tab2(k)-1)-i1*nb_comp;
                  t -= coeff(k)*current(i1,j1);
                }
              const double diagonal_coefficient = matrice(i*nb_comp+j,i*nb_comp+j);
              assert(diagonal_coefficient!=0);
              correction_en_vitesse(i,j) = t/diagonal_coefficient;
            }
        }
// test
      if (0)
        {
          Cerr<<"milieu"<<finl;
          DoubleTrav corr2(correction_en_vitesse);
          matrice.multvect(current,corr2);
          for(int i=0; i<nb_ligne_reel; i++)
            {
              for (int j=0; j<nb_comp; j++)
                {
                  int ii = i*nb_comp+j;
                  corr2(i,j) = (resu(i,j)-corr2(i,j)+matrice(ii,ii)*current(i,j))/matrice(ii,ii);
                  double test = corr2(i,j);
                  if (!est_egal(test,correction_en_vitesse(i,j)))
                    {
                      Cerr<<i<<" "<<j<<" "<<resu(i,j)<<finl;
                      Cerr<<test<<" ici "<<correction_en_vitesse(i,j)<<" "<<current(i,j)<<" "<<matrice(ii,ii) <<finl;
                      return -1;
                    }
                }
            }
          Cerr<<"fin"<<finl;
        }
    }
  correction_en_vitesse.echange_espace_virtuel();
  return 0;
}
References Cerr, coeff, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), est_egal(), finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Base::multvect(), Matrice_Morse::nb_colonnes(), TRUSTTab< _TYPE_ >::nb_dim(), and test().
Referenced by Piso::iterer_NS(), and Simpler::iterer_NS().