TRUST: src/ThHyd/Schemas_Temps/Simple.cpp File Reference
src/ThHyd/Schemas_Temps/Simple.cpp File Reference
#include <Simple.h>
#include <Navier_Stokes_std.h>
#include <EChaine.h>
#include <Debog.h>
#include <Matrice_Bloc.h>
#include <Matrice_Morse_Sym.h>
#include <Matrice_Nulle.h>
#include <Matrix_tools.h>
#include <Assembleur_base.h>
#include <Statistiques.h>
#include <Schema_Temps_base.h>
#include <DoubleTrav.h>
#include <Schema_Euler_Implicite.h>
#include <Fluide_Dilatable_base.h>
#include <Probleme_base.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <ConstDoubleTab_parts.h>
#include <SETS.h>
Functions
void diviser_par_rho_np1_face (Equation_base &eqn, DoubleTab &tab)
void iterer_eqn_expl (Equation_base &eqn, int nb_iter, double dt, DoubleTab &current, DoubleTab &dudt, int &converge, const int &no_qdm_)
void iterer_eqn_expl_diffusion_implicite (Equation_base &eqn, int nb_iter, double dt, DoubleTab &current, DoubleTab &dudt, int &converge, const int &no_qdm_, const double &seuil)
Variables
const Type_info * Simplebases [1] = { &(Simpler_Base ::info_obj)}
Function Documentation
void diviser_par_rho_np1_face (Equation_base & eqn, DoubleTab & tab)
Definition at line 89 of file Simple.cpp.
References DoubleTab::dimension(), DoubleTab::dimension_tot(), Equation_base::milieu(), DoubleTab::nb_dim(), ref_cast, and Fluide_Dilatable_base::rho_face_np1().
Referenced by Simple::iterer_NS(), and Piso::iterer_NS().
{
  Fluide_Dilatable_base& fluide_dil = ref_cast(Fluide_Dilatable_base,eqn.milieu());
  const DoubleTab& rho = fluide_dil.rho_face_np1();
  int nbdim = tab.nb_dim();
  int taille_0_tot = tab.dimension_tot(0);
  if (nbdim==1)
    for (int i=0; i<taille_0_tot; i++)
      tab(i) /= rho(i);
  else
    {
      int dim = tab.dimension(1);
      for (int i=0; i<taille_0_tot; i++)
        for (int j=0; j<dim; j++)
          tab(i,j) /= rho(i);
    }
}
void iterer_eqn_expl (Equation_base & eqn, int nb_iter, double dt, DoubleTab & current, DoubleTab & dudt, int & converge, const int & no_qdm_)
Definition at line 108 of file Simple.cpp.
References Equation_base::calculer_pas_de_temps(), Cout, Equation_base::derivee_en_temps_inco(), est_egal(), finl, Objet_U::que_suis_je(), test(), and Equation_base::valider_iteration().
Referenced by Simple::iterer_eqn().
{
  if (nb_iter>1)
    {
      converge = 1;
      return;
    }
  if ((no_qdm_))
    {
      Cout<<eqn.que_suis_je()<<" equation is not solved."<<finl;
      eqn.valider_iteration();
      converge = 1;
      return;
    }
  double dt_stab = eqn.calculer_pas_de_temps();
// Voir Schema_Temps_base::limpr pour information sur modf
  double n_sous_ite;
  modf((dt/dt_stab), &n_sous_ite);
  if (dt>dt_stab*n_sous_ite) n_sous_ite=n_sous_ite+1.;
  double dt_calc = dt/n_sous_ite;
  assert(dt_calc<=dt_stab);
  double test = 0;
  for (double i=0; i<n_sous_ite; i=i+1.)
    {
      eqn.derivee_en_temps_inco(dudt);
      dudt *= dt_calc;
      test += dt_calc;
      current += dudt;
      eqn.valider_iteration();
    }
  Cout <<"It is solved with " << n_sous_ite << " explicit sub-iterations."<<finl;
  assert(est_egal(test,dt));
  converge=1;
}
void iterer_eqn_expl_diffusion_implicite (Equation_base & eqn, int nb_iter, double dt, DoubleTab & current, DoubleTab & dudt, int & converge, const int & no_qdm_, const double & seuil)
Definition at line 146 of file Simple.cpp.
References Cout, Equation_base::derivee_en_temps_inco(), Schema_Temps_base::diffusion_implicite(), finl, Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::set_diffusion_implicite(), Schema_Temps_base::set_seuil_diffusion_implicite(), Schema_Temps_base::seuil_diffusion_implicite(), and Equation_base::valider_iteration().
Referenced by Simple::iterer_eqn().
{
  if (nb_iter>1)
    {
      converge = 1;
      return;
    }
  if ((no_qdm_))
    {
      Cout<<eqn.que_suis_je()<<" equation is not solved."<<finl;
      eqn.valider_iteration();
      converge = 1;
      return;
    }
// dudt = current;
  Schema_Temps_base& sch = eqn.probleme().schema_temps();
  double seuil_sa = sch.seuil_diffusion_implicite();
  int flag_sa = sch.diffusion_implicite();
  sch.set_seuil_diffusion_implicite() = seuil;
  sch.set_diffusion_implicite() = 1;
  eqn.derivee_en_temps_inco(dudt);
  dudt *= dt;
  current += dudt;
  eqn.valider_iteration();
// On remet les parametres de diffusion implicite a leur ancienne valeur
  sch.set_seuil_diffusion_implicite() = seuil_sa;
  sch.set_diffusion_implicite() = flag_sa;
  converge = 1;
}
Variable Documentation
const Type_info* Simplebases[1] = { &(Simpler_Base ::info_obj)}
Definition at line 43 of file Simple.cpp.