TRUST: src/Kernel/Math/SolvSys/Solv_Gmres.cpp File Reference
Solv_Gmres.cpp File Reference
#include <Solv_Gmres.h>
#include <Matrice_Morse_Sym.h>
#include <Matrice_Bloc.h>
#include <Motcle.h>
Functions
int gmres_local (const Matrice_Morse &A, const DoubleVect &b, DoubleVect &x1, double &seuil, int precond_diag, int &nb_it_max, int &controle_residu, DoubleVects &v, int dim_espace_Krilov, int limpr_=0)
Variables
const Type_info * Solv_Gmresbases [1] ={ &(solv_iteratif ::info_obj)}
Function Documentation
gmres_local()
int gmres_local (const Matrice_Morse & A, const DoubleVect & b, DoubleVect & x1, double & seuil, int precond_diag, int & nb_it_max, int & controle_residu, DoubleVects & v, int dim_espace_Krilov, int limpr_ = 0)
< dimension de l'espace de Krylov nkr=10;
< Krilov vectors
< Heisenberg maatrix of coefficients
< nothing to do
Definition at line 201 of file Solv_Gmres.cpp.
{
// return le_solveur_.resoudre_systeme(A,b,x1);
// A.inverse(b,x1,seuil); return 1;
  int i,j,nk,i0,im,it,ii;
  double tem=1.,res,ccos,ssin ;
// PL c'est pas joli et c'est de moi mais je ne comprends pas pourquoi
// l'utilisation de b.size_reelle() plante sur la matrice en pression depuis la 1.6.0 (non teste)
// Qu'est ce qui est fait en implicite pour b.size_reelle() soit >=0 ???
  const int ns=(b.size_reelle_ok()?b.size_reelle():b.size_array());
  int nb_ligne_tot=(int)Process::mp_sum((double) ns);
// Ajoute par DJ
// --------------
// int nb_elem_tot = b.size_totale();
// DoubleVect x1(x);
// x1=0.;
// for(int n_elem=0; n_elem<nb_elem_tot; n_elem++)
// {
// x1(n_elem)=x(n_elem);
// }
// --------------
// A present dans le jdd
  double epsGMRES=1.e-10*0;
  int nkr_min = 10;
  int nkr=std::max(nkr_min,nb_ligne_tot/2);                         //!< dimension de l'espace de Krylov nkr=10;
//
  nkr=dim_espace_Krilov;
  int nit1_min = 20;
  int nit1=std::max(nit1_min,nb_ligne_tot);
  int nit=std::min(nb_it_max,nit1);
  double rec_min = seuil;
  double rec_max = 0.1  ;
  double res2_old=-1;
  if (v.size()==0)
    v.dimensionner(nkr);                         //!< Krilov vectors
  DoubleTab h(nkr+1,nkr);                //!< Heisenberg maatrix of coefficients
  DoubleVect r(nkr+1);
  DoubleVect v0(x1);
  DoubleVect v1(x1) ;
  int ns2=ns;
  DoubleVect Diag(ns);
  Diag=1.;
  if (precond_diag)
    for ( i=0; i<ns; i++)
      Diag[i]=1./A(i,i);
// Initialisation
  v0 = 0. ;
  v1 = 0. ;
  A.multvect_(x1,v0);
  v0 *= -1. ;
  v0+=b;
  v0.echange_espace_virtuel();
  double res0 = mp_norme_vect(v0);
  for (ii=0; ii<ns2; ii++)
    v0(ii)*=Diag(ii);
  res = mp_norme_vect(v0);
  if (limpr_==1)
    Cout<<"Gmres : initial residual = "<<res0<<finl;
// See http://stackoverflow.com/questions/3437085/check-nan-number
// May be could be interesting to implement isnan function somewhere
  if (res0!=res0)
    {
      Cerr << "Nan detected in Solv_Gmres::gmres_local()" << finl;
      Cerr << "Contact TRUST support." << finl;
      Process::exit();
    }
  rec_min = (rec_min<res*epsGMRES) ? res*epsGMRES : rec_min;
  rec_min = (rec_min<rec_max) ? rec_min : rec_max ;
// iterations
  for(it=0; it<nit; it++)
    {
      if (res==0) return 0; //!< nothing to do
      nk = nkr;
// ...Orthogonalisation of Arnoldi
      v0 /= res;
      r = 0. ;
      r[0] = res;
      h=0.;
      for(j=0; j<nkr; j++)
        {
          v0.echange_espace_virtuel();
          v[j]=v0;
          A.multvect(v0,v1);
          for (ii=0; ii<ns2; ii++) v1(ii)*=Diag(ii);
          v0 = v1 ;
// Modifie par DJ
// ---------------
          for(i=0; i<=j; i++)
            {
              DoubleVect& vvi=v[i];
              h(i,j)+=mp_prodscal(v0,vvi);
              for (ii=0; ii<ns; ii++) v0(ii) -= h(i,j) * vvi(ii);
              v0.echange_espace_virtuel();
            }
          tem=mp_norme_vect(v0);
          h(j+1,j) = tem;
          if(tem<rec_min)
            {
              nk = j+1;
              goto l5;
            }
          v0 /= tem;
        }
// ...Triangularisation
l5:
      for(i=0; i<nk; i++)
        {
          im = i+1;
          tem = 1./sqrt(h(i,i)*h(i,i) + h(im,i)*h(im,i));
          ccos = h(i,i) * tem;
          ssin = - h(im,i) * tem;
          for(j=i; j<nk; j++)
            {
              tem = h(i,j);
              h(i,j) = ccos * tem - ssin * h(im,j);
              h(im,j) =  ssin * tem + ccos * h(im,j);
            }
          r[im] = ssin * r[i];
          r[i] *= ccos;
        }
// ...Solution of linear system
      for(i=nk-1; i>=0; i--)
        {
          r[i] /= h(i,i);
          for(i0=i-1; i0>=0; i0--)
            r[i0] -= h(i0,i)* r[i];
        }
      for(i=0; i<nk; i++)
        {
          DoubleVect& vvi=v[i];
          for(ii=0; ii<ns; ii++)  x1(ii) += r[i]*vvi(ii);
        }
      x1.echange_espace_virtuel();
      A.multvect_(x1,v0);
      v0 *= -1. ;
      v0+=b;
// calcul du residu sans le precond....
      double res2=mp_norme_vect(v0);
      if ((it>0) && (controle_residu==1) && (sup_strict(res2,res2_old)))
        {
          Cout << "The Gmres iterative system is stopped after : " << it+1 <<" iterations "<<finl;
          Cout << "since an increase of the residue is detected."<< finl;
          return it;
        }
      res2_old = res2;
      if (limpr_==1)
        Cout<<" - At it = "<< it+1 <<", residu scalar = "<< res2 << finl;
// Test d'arret sur le residu
      if(res2<rec_min)
        {
// Ajoute par DJ
// --------------
          if (limpr_>-1)
            {
              Cout << "Gmres : Number of iterations to reach convergence : " << it+1 << finl;
              double residu_relatif = (res0>0?res2/res0:res2);
              Cout << "Final residue: " << res2 << " ( " << residu_relatif << " )" << finl;
            }
          return it+1;
        }
// Test d'arret sur le nombre d'iterations max
      else if (it==nit-1)
        {
// Ajoute par DJ
// --------------
// On fait le choix de mettre a jour c_demi et mutilde_demi meme s'il n'y a pas convergence...
// x=x1;
// --------------
          if (limpr_>-1)
            {
              Cout << "Gmres : Stopped after "<< it+1 <<" iterations (=nb_it_max)"<< finl;
              double residu_relatif = (res0>0?res2/res0:res2);
              Cout << "Final residue: " << res2 << " ( " << residu_relatif << " )" << finl;
            }
          if (it == (nb_ligne_tot-1))
            {
              Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"<< finl;
              Cerr << "!!! Gmres stopped after a number of iterations equal to the matrix size. "<< finl;
              Cerr << "!!! Either your matrix is ill-conditioned (try cholesky instead), or your convergence threshold is too low. "<< finl;
              Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"<< finl;
              Process::exit(-1);
            }
          return it+1;
        }
// Calcul du residu avec preconditionnement
      for (ii=0; ii<ns2; ii++) v0(ii)*=Diag(ii);
      res = mp_norme_vect(v0);
    }
  return -1;
}
References Cerr, Cout, vect_impl::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, mp_norme_vect(), mp_prodscal(), Process::mp_sum(), Matrice_Base::multvect(), Matrice_Base::multvect_(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_reelle(), TRUSTVect< _TYPE_ >::size_reelle_ok(), and sup_strict().
Referenced by Solv_Gmres::Gmres().
Variable Documentation
Solv_Gmresbases
const Type_info* Solv_Gmresbases[1] ={ &(solv_iteratif ::info_obj)}
Definition at line 25 of file Solv_Gmres.cpp.