TRUST: src/Kernel/Math/SolvSys/Solv_Optimal.cpp File Reference
Solv_Optimal.cpp File Reference
#include <Solv_Optimal.h>
#include <Param.h>
#include <LecFicDistribueBin.h>
#include <stat_counters.h>
#include <LecFicDiffuse.h>
#include <Matrice_Bloc.h>
#include <Matrice_Morse_Sym.h>
#include <SFichier.h>
#include <petsc_for_kernel.h>
#include <MD_Vector_tools.h>
Functions
void test_un_solveur (SolveurSys &solveur, const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution, int nmax, ArrOfDouble &temps, double seuil_verification=1e+38)
int test_solveur (SolveurSys &solveur, const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution, int nmax, ArrOfDouble &temps, Entree &list_solveur, double seuil_verification=1e+38)
void generate_defaut (const Matrice_Base &matrice, const double seuil, Sortie &sortie, int limpr=0)
Variables
const Type_info * Test_solveurbases [1] ={ &(Interprete ::info_obj)}
const Type_info * Solv_Optimalbases [1] ={ &(solv_iteratif ::info_obj)}
static int numero_solv_optimal =0
numero du solveur pour avoir des noms de fichiers solveurs par defaut differents pour chaque solveur
Function Documentation
generate_defaut()
void generate_defaut (const Matrice_Base & matrice, const double seuil, Sortie & sortie, int limpr = 0)
Definition at line 128 of file Solv_Optimal.cpp.
{
  Nom impr(" impr " );
  if (limpr==0) impr=" ";
  if (limpr==-1) impr=" quiet ";
  if (Process::je_suis_maitre())
    {
      if((!sub_type(Matrice_Morse_Sym,matrice))&&(!sub_type(Matrice_Bloc,matrice)))
        {
          sortie <<" solveur gen { seuil "<<seuil <<" "<<impr<< " solv_elem bicgstab precond ilu { type 2 filling 10 } }" <<finl;
          sortie <<" solveur gen { seuil "<<seuil <<" "<<impr<< " solv_elem bicgstab precond ilu { type 2 filling 20 } }" <<finl;
          sortie <<" solveur gmres { diag seuil "<<seuil <<" "<<impr<<"}"<<finl;
#ifdef __PETSCKSP_H
          sortie <<" solveur petsc bicgstab { precond diag { }                  seuil "<<seuil <<" "<<impr<<"}"<<finl;
#endif
        }
      else
        {
// on a une matrice de type pression (?)
// Mise a jour des solveurs testes 24/05/2012
          sortie <<" solveur gcp       { precond ssor       { omega 1.6 }       seuil "<<seuil <<" "<<impr<<"}"<<finl;
#ifdef __PETSCKSP_H
          sortie <<" solveur petsc gcp { precond ssor       { omega 1.6 }       seuil "<<seuil <<" "<<impr<<"}"<<finl;
          if (Process::nproc()<512)
            sortie <<" solveur petsc cholesky { impr }"<< finl;
          else
            {
// Pour les tres grands calculs on bascule de Cholesky a BICGSTAB ILU(1) par bloc
              sortie <<" solveur petsc bicgstab { precond block_jacobi_icc { level 1 } seuil "<<seuil <<" "<<impr<<"}"<<finl;
// Voire CG ILU(1) par bloc car BICGSTAB peut avoir du mal a converger lors de la projection initiale...
              sortie <<" solveur petsc gcp { precond block_jacobi_icc { level 1 } seuil "<<seuil <<" "<<impr<<"}"<<finl;
            }
// SPAI n'a jamais fait ses preuves (comme tous les preconditionnements de Hypre), on l'enleve
// sortie <<" solveur petsc gcp { precond spai       { level 2 epsilon 0.2 } seuil "<<seuil <<" "<<impr<<"}"<<finl;
#endif
        }
    }
}
References finl, Process::je_suis_maitre(), Process::nproc(), and sub_type.
Referenced by Test_solveur::interpreter(), and Solv_Optimal::prepare_resol().
test_solveur()
int test_solveur (SolveurSys & solveur, const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax, ArrOfDouble & temps, Entree & list_solveur, double seuil_verification = 1e+38)
Definition at line 90 of file Solv_Optimal.cpp.
{
  DoubleVect solution_ref(solution);
  int numero=0,numero_best=-1;
  double best_time=1e36;
  Motcle motsolveur("solveur"),motlu;
  list_solveur >> motlu;
  int dernier=temps.size_array()-1;
  while (list_solveur.good())
    {
      if (motlu!=motsolveur)
        {
          Cerr<<" One expected "<<motsolveur <<" and not "<<motlu<<finl;
          Process::exit();
        }
      numero++;
      SolveurSys newsolveur;
      list_solveur>>newsolveur;
      solution=solution_ref;
      test_un_solveur(newsolveur, matrice, secmem ,solution, nmax, temps, seuil_verification);
      if (temps[dernier]<best_time)
        {
          solveur=newsolveur;
          best_time=temps[dernier];
          numero_best=numero;
        }
      list_solveur>>motlu;
    }
  if (numero_best==-1)
    {
      Cerr<<" None of the tested solvers give the expected residue" <<finl;
      Cerr<< " does the same solver must be kept ? "<<finl;
// exit();
    }
  temps=best_time;
  return numero_best;
}
References Cerr, Process::exit(), finl, Entree::good(), TRUSTArray< _TYPE_ >::size_array(), and test_un_solveur().
Referenced by Test_solveur::interpreter(), and Solv_Optimal::prepare_resol().
test_un_solveur()
void test_un_solveur (SolveurSys & solveur, const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax, ArrOfDouble & temps, double seuil_verification = 1e+38)
Definition at line 43 of file Solv_Optimal.cpp.
{
  DoubleVect solution_ref(solution);
  int n=temps.size_array();
  Stat_Counter_Id  solv_sys_counter_l= statistiques().new_counter(1, "SolveurSys::resoudre_systeme", 0);
  for (int i=0; i<n; i++)
    {
      solution=solution_ref;
// etape de resolution
      Stat_Results stat_resol_0;
      statistiques().get_stats(solv_sys_counter_l, stat_resol_0);
      Cout<<"------------------------------------"<<finl;
      Cout<<"Try " << i << " of solver " << solveur <<finl;
// solveur.valeur().fixer_limpr(0);
      statistiques().begin_count(solv_sys_counter_l);
      solveur.nommer("test_solver");
      solveur.resoudre_systeme(matrice,secmem,solution);
      statistiques().end_count(solv_sys_counter_l);
      Stat_Results stat_resol;
      statistiques().get_stats(solv_sys_counter_l, stat_resol);
// on recupere un delta time et non un time absolu !!
      double time_resol=stat_resol.time-stat_resol_0.time;
      DoubleVect test(secmem);
      test*=-1;
      matrice.ajouter_multvect(solution,test);
// test-=secmem;
      double norme=mp_norme_vect(test);
// statistiques().dump("Statistiques de resolution du probleme");
// print_statistics_analyse("Statistiques de resolution du probleme", 1);
      Cout<<"CPU= " <<time_resol<<" s , ||Ax -b||= " << norme << finl;
      Process::imprimer_ram_totale();
      temps[i]=Process::mp_max(time_resol);
      if (norme>seuil_verification)
        {
          Cerr<<"residue calculated greater than the threshold value indicated ("<<seuil_verification<<")"<<finl;
          Cerr<<" one will not use the solver "<<solveur<<finl;
          temps=1.e37;
        }
    }
}
References Matrice_Base::ajouter_multvect(), Statistiques::begin_count(), Cerr, Cout, Statistiques::end_count(), finl, Statistiques::get_stats(), Process::imprimer_ram_totale(), Process::mp_max(), mp_norme_vect(), Statistiques::new_counter(), SolveurSys::nommer(), norme(), SolveurSys::resoudre_systeme(), TRUSTArray< _TYPE_ >::size_array(), statistiques(), test(), and Stat_Results::time.
Referenced by Test_solveur::interpreter(), and test_solveur().
Variable Documentation
numero_solv_optimal
int numero_solv_optimal =0 static
numero du solveur pour avoir des noms de fichiers solveurs par defaut differents pour chaque solveur
Definition at line 260 of file Solv_Optimal.cpp.
Referenced by Solv_Optimal::Solv_Optimal().
Solv_Optimalbases
const Type_info* Solv_Optimalbases[1] ={ &(solv_iteratif ::info_obj)}
Definition at line 29 of file Solv_Optimal.cpp.
Test_solveurbases
const Type_info* Test_solveurbases[1] ={ &(Interprete ::info_obj)}
Definition at line 27 of file Solv_Optimal.cpp.