TRUST: src/Kernel/Math/SolvSys/Solv_GCP_NS.cpp File Reference
src/Kernel/Math/SolvSys/Solv_GCP_NS.cpp File Reference
#include <Solv_GCP_NS.h>
#include <Matrice_Bloc_Sym.h>
#include <ConstDoubleTab_parts.h>
#include <Motcle.h>
Functions
static void corriger (DoubleVect &X, double alpha, double beta, const DoubleVect &X1, const DoubleVect &X0, int prems, int n)
static void injecter (const DoubleVect &X, DoubleVect &tmp, int prems, int n)
static void extraire (DoubleVect &X, const DoubleVect &tmp, int prems, int n)
void erreur ()
Variables
const Type_info * Solv_GCP_NSbases [1] = { &(solv_iteratif ::info_obj)}
Function Documentation
static void corriger (DoubleVect & X, double alpha, double beta, const DoubleVect & X1, const DoubleVect & X0, int prems, int n) [inline, static]
Definition at line 110 of file Solv_GCP_NS.cpp.
References sz.
Referenced by Solv_GCP_NS::resoudre_systeme().
{
  int sz=prems+n;
  int i=0;
  for(; i<prems; i++)
    X(i)+=beta*X0(i);
  for(; i<sz; i++)
    X(i)+=alpha*X1(i-prems);
}
void erreur () [inline]
Definition at line 141 of file Solv_GCP_NS.cpp.
References Cerr, Process::exit(), and finl.
Referenced by Op_Grad_VEF_Face::ajouter(), Op_Div_VEF_Elem::ajouter(), avancer_fichier(), Scatter::calculer_espace_distant_elements(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_Tranche::chercher_direction_perio(), Periodique::completer(), Op_Grad_VEF_Face::impr(), is_parallel_object(), Champ_Generique_Transformation::preparer_macro(), Champ_Don_Face_lu::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Reordonner_faces_periodiques::renum_som_perio(), Solv_GCP_NS::resoudre_systeme(), Champ_front_contact_VEF::test_faces_coin(), verifier(), and verifier_complet().
{
  Cerr << "The dedicated solver GCP_NS can be used only for blocks symetric matrixes" << finl;
  Cerr << "containing 2*2 blocks for VEF discretization P0+P1." << finl;
  Process::exit();
}
static void extraire (DoubleVect & X, const DoubleVect & tmp, int prems, int n) [inline, static]
Definition at line 133 of file Solv_GCP_NS.cpp.
References sz.
Referenced by Solv_GCP_NS::resoudre_systeme().
{
  int sz=prems+n;
  for(int i=prems; i<sz; i++)
    X(i-prems)=tmp(i);
}
static void injecter (const DoubleVect & X, DoubleVect & tmp, int prems, int n) [inline, static]
Definition at line 126 of file Solv_GCP_NS.cpp.
References sz.
Referenced by Solv_GCP_NS::resoudre_systeme().
{
  int sz=prems+n;
  for(int i=prems; i<sz; i++)
    tmp(i)=X(i-prems);
}
Variable Documentation
const Type_info* Solv_GCP_NSbases[1] = { &(solv_iteratif ::info_obj)}
Definition at line 28 of file Solv_GCP_NS.cpp.