TRUST: src/Kernel/Math/SolvSys/Solv_GCP.cpp File Reference
Solv_GCP.cpp File Reference
#include <Solv_GCP.h>
#include <SSOR.h>
#include <Param.h>
#include <Matrice_Bloc_Sym.h>
#include <Sparskit.h>
#include <MD_Vector_base.h>
#include <MD_Vector_tools.h>
#include <communications.h>
#include <TRUSTTab_parts.h>
Functions
static void multiply_sub (DoubleVect &vx, DoubleVect &vy, double alpha)
static double ajoute_alpha_v_norme (DoubleVect &vx, double alpha, DoubleVect &vy)
Variables
const Type_info * Solv_GCPbases [1] ={ &(solv_iteratif ::info_obj)}
Function Documentation
ajoute_alpha_v_norme()
static double ajoute_alpha_v_norme (DoubleVect & vx, double alpha, DoubleVect & vy) static
Definition at line 370 of file Solv_GCP.cpp.
{
  int n = vx.size();
  assert(vy.size() == n);
  double *x_ptr = vx.addr();
  double *y_ptr = vy.addr();
  double norme1 = 0., norme2 = 0.;
  for (n = n - 1; n > 0; n -= 2, x_ptr += 2, y_ptr += 2)
    {
      double a = x_ptr[0] + alpha * y_ptr[0];
      double b = x_ptr[1] + alpha * y_ptr[1];
      x_ptr[0] = a;
      x_ptr[1] = b;
      norme1 += a * a;
      norme2 += b * b;
    }
// n etait-il impair au depart ?
  if (n == 0)
    {
      double a = x_ptr[0] + alpha * y_ptr[0];
      x_ptr[0] = a;
      norme1 += a * a;
    }
  return norme1 + norme2;
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTVect< _TYPE_ >::size().
Referenced by Solv_GCP::resoudre_().
multiply_sub()
static void multiply_sub (DoubleVect & vx, DoubleVect & vy, double alpha) static
Definition at line 349 of file Solv_GCP.cpp.
{
  int n = vx.size_reelle_ok() ? vx.size() : vx.size_totale();
  assert(vy.size_totale() >= n);
  double *x_ptr = vx.addr();
  double *y_ptr = vy.addr();
  for (n = n - 1; n > 0; n -= 2, x_ptr += 2, y_ptr += 2)
    {
      double a = x_ptr[0] * alpha - y_ptr[0];
      double b = x_ptr[1] * alpha - y_ptr[1];
      x_ptr[0] = a;
      x_ptr[1] = b;
    }
// n etait-il impair au depart ?
  if (n == 0)
    x_ptr[0] = x_ptr[0] * alpha - y_ptr[0];
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTVect< _TYPE_ >::size(), TRUSTVect< _TYPE_ >::size_reelle_ok(), and TRUSTVect< _TYPE_ >::size_totale().
Referenced by Solv_GCP::resoudre_().
Variable Documentation
Solv_GCPbases
const Type_info* Solv_GCPbases[1] ={ &(solv_iteratif ::info_obj)}
Definition at line 26 of file Solv_GCP.cpp.