TRUST: src/PolyMAC/Sources/Source_Generique_Face_PolyMAC.cpp File Reference
Source_Generique_Face_PolyMAC.cpp File Reference
#include <Source_Generique_Face_PolyMAC.h>
#include <Zone_PolyMAC_P0.h>
#include <Zone_Cl_PolyMAC.h>
#include <Zone_Cl_dis.h>
#include <Champ_Face_PolyMAC.h>
#include <Equation_base.h>
Functions
double valeur (const DoubleTab &valeurs_champ, int elem1, int elem2, const int &compo)
Variables
const Type_info * Source_Generique_Face_PolyMACbases [1] ={ &(Source_Generique_base ::info_obj)}
Function Documentation
valeur()
double valeur (const DoubleTab & valeurs_champ, int elem1, int elem2, const int & compo) inline
< Champ uniforme
< face frontiere
Definition at line 38 of file Source_Generique_Face_PolyMAC.cpp.
{
  if (valeurs_champ.dimension(0)==1)
    return valeurs_champ(0,compo); //!< Champ uniforme
  else
    {
      if (elem2<0) elem2 = elem1; //!< face frontiere
      if (valeurs_champ.nb_dim()==1)
        return 0.5*(valeurs_champ(elem1)+valeurs_champ(elem2));
      else
        return 0.5*(valeurs_champ(elem1,compo)+valeurs_champ(elem2,compo));
    }
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTTab< _TYPE_ >::nb_dim().
Referenced by Objet_a_lire::add_dict(), Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Div_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), TRUSTArray< _TYPE_ >::append_array(), array_bsearch(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_mat(), assert_invalide_items_non_calcules(), Milieu_base::associer_(), Perte_Charge_PolyMAC::associer_pb(), Perte_Charge_VEF::associer_pb(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_P1NC::calcul_critere_Q(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Op_Diff_P1NC_barprim::calculer(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Echange_contact_VDF::calculer_Teta_paroi(), Champ_base::calculer_valeurs_elem_compo_post(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Matrice_Bloc::check_block_matrix_structure(), PE_Groups::check_current_group(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), Zone::check_zone(), Traduction_Indice_Global_Local::chercher_table_inverse(), Periodique::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Paroi_Knudsen_non_negligeable::completer(), Navier_Stokes_std::completer(), Flux_interfacial_PolyMAC::completer(), Echange_interne_global_impose::completer(), Force_Centrifuge_VDF_Face_Axi::completer(), Echange_interne_impose::completer(), Terme_Source_Constituant_VDF_Elem::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Champ_P1iP1B_implementation::completer(), Domaine::construire_renum_som_perio(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Masse_PolyMAC_Face::corriger_solution(), Masse_PolyMAC_P0_Face::corriger_solution(), PE_Groups::create_group(), Solv_Petsc::create_solver(), Zone::creer_aretes(), declare_espace_virtuel_invalide(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Param::dictionnaire(), Param::dictionnaire_param(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Equation_base::discretiser(), Domaine_dis::discretiser(), Navier_Stokes_std::discretiser_assembleur_pression(), Echange_contact_Correlation_VEF_reprendre(), Format_Post_Lata::ecrire_domaine(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Simpler_Base::get_and_set_parametre_implicite(), Moyenne_volumique::get_champ(), Probleme_base::getOutputFieldsNames(), Champ_P1NC::gradient(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_VF::info_elem_som(), Echange_contact_Correlation_VEF::init(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Zone_Poly_base::init_dist_paroi_globale(), Champ_Elem_PolyMAC::init_fcl(), Champ_Face_PolyMAC::init_fcl(), Op_Diff_PolyMAC_Elem::init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_s_dist(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Fluide_base::initialiser(), Echange_contact_VDF::initialiser(), Zone_Cl_VEF::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), Navier_Stokes_std::initTimeStep(), Execute_parallel::interpreter(), Create_domain_from_sous_zone::interpreter_(), Piso::iterer_NS(), Solveur_U_P::iterer_NS(), Zone_VEF_PreP1b::lecture_ok_arete(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), vect_impl::lit(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Chimie::mettre_a_jour(), Champ_Gen_de_Champs_Gen::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Fluide_base::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_a_jour_tag_indicatrice_pena_glob(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), VDF_discretisation::modifier_champ_tabule(), VEF_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Zone_Cl_EF::nb_bord_periodicite(), Zone_Cl_PolyMAC::nb_bord_periodicite(), Zone_Cl_VEF::nb_bord_periodicite(), Zone_Cl_VDF::nb_faces_sortie_libre(), Zone_Cl_VEF::nb_faces_sortie_libre(), Champ_Gen_de_Champs_Gen::nommer_sources(), ArrOfBit::operator=(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), vect_impl::printOn(), Navier_Stokes_std::projeter(), Stack< T >::push(), Loi_Etat_Multi_GP_QC::rabot(), Source_Scalaire_EF::readOn(), Zone_Cl_dis_base::readOn(), vect_impl::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Navier_Stokes_std::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), Echange_contact_VDF::readOn(), Raffiner_Simplexes::refine_domain(), Matrice_Bloc::remplir(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), remplir_items_non_calcules(), remplir_items_non_calcules_(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Champ_Gen_de_Champs_Gen::reprendre(), Champ_Gen_de_Champs_Gen::sauvegarder(), Static_Int_Lists::set_value(), Terme_Source_Canal_perio::source_convection_diffusion(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Convection_Diffusion_Temperature::transport_ibc(), Echange_contact_Correlation_VDF::trier_coord(), Op_Diff_PolyMAC_base::update_aux(), Op_Grad_PolyMAC_P0_Face::update_grad(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Face::val_imp_face_bord_private(), Champ_front_softanalytique::valeur_a(), Champ_Inc_base::valeur_aux_bords(), Echange_contact_VDF::verifier_correspondance(), Convection_Diffusion_Temperature::verifier_tag_indicatrice_pena_glob(), Zone_Cl_EF::zone_EF(), Zone_Cl_PolyMAC::zone_PolyMAC(), Zone_Cl_VDF::zone_VDF(), and Zone_Cl_VEF::zone_VEF().
Variable Documentation
Source_Generique_Face_PolyMACbases
const Type_info* Source_Generique_Face_PolyMACbases[1] ={ &(Source_Generique_base ::info_obj)}
Definition at line 23 of file Source_Generique_Face_PolyMAC.cpp.