TRUST: src/Kernel/Math/SolvSys/SPV2.h File Reference
SPV2.h File Reference
Functions
void F77DECLARE() ilutv2 (const int *n, const double *a, const int *ja, const int *ia, const int *lfil, const double *droptol, const double *alu, const int *jlu, const int *ju, const int *iwk, const double *w, const int *jw, const int *ierr)
void F77NAME() ILUTV2 (const int *n, const double *a, const int *ja, const int *ia, const int *lfil, const double *droptol, const double *alu, const int *jlu, const int *ju, const int *iwk, const double *w, const int *jw, const int *ierr)
void F77DECLARE() milu0v2 (const int *n, const double *a, const int *ja, const int *ia, const double *alu, const int *jlu, const int *ju, const int *jw, const int *ierr)
void F77NAME() MILU0V2 (const int *n, const double *a, const int *ja, const int *ia, const double *alu, const int *jlu, const int *ju, const int *jw, const int *ierr)
void F77DECLARE() ilu0v2 (const int *n, const double *a, const int *ja, const int *ia, const double *alu, const int *jlu, const int *ju, const int *jw, const int *ierr)
void F77NAME() ILU0V2 (const int *n, const double *a, const int *ja, const int *ia, const double *alu, const int *jlu, const int *ju, const int *jw, const int *ierr)
void F77DECLARE() lusolv2 (const int *const, const double *const, const double *const, const double *const, const int *const, const int *const)
void F77DECLARE() lutsolv2 (const int *const, const double *const, const double *const, const double *const, const int *const, const int *const)
void F77DECLARE() pgmresv2 (const int *const, const int *const, const double *const, double *const, const double *const, const double *const, const int *const, const int *const, const double *const, const int *const, const int *const, const double *const, const int *const, const int *const, int *const)
void F77NAME() cgv2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
void F77NAME() bcgstabv2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
void F77NAME() gmresv2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
void F77NAME() LUSOLV2 (const int *const a, const double *const b, const double *const c, const double *const d, const int *const e, const int *const f)
void F77NAME() LUTSOLV2 (const int *const a, const double *const b, const double *const c, const double *const d, const int *const e, const int *const f)
void F77NAME() PGMRESV2 (const int *const a, const int *const b, const double *const c, double *const d, const double *const e, const double *const f, const int *const g, const int *const h, const double *const i, const int *const j, const int *const k, const double *const l, const int *const m, const int *const n, int *const o)
void F77NAME() CGV2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
void F77NAME() BCGSTABV2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
void F77NAME() GMRESV2 (const int *const a, const double *const b, double *c, int *d, double *e, double *f)
Function Documentation
bcgstabv2()
void F77NAME() bcgstabv2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f)
Referenced by BCGSTABV2().
BCGSTABV2()
void F77NAME() BCGSTABV2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f) inline
Definition at line 168 of file SPV2.h.
{
  F77NAME(bcgstabv2)(a,b,c,d,e,f);
}
References bcgstabv2(), and F77NAME.
Referenced by SolvElem_BiCGStab::iteration().
cgv2()
void F77NAME() cgv2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f)
Referenced by CGV2().
CGV2()
void F77NAME() CGV2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f) inline
Definition at line 162 of file SPV2.h.
{
  F77NAME(cgv2)(a,b,c,d,e,f);
}
References cgv2(), and F77NAME.
gmresv2()
void F77NAME() gmresv2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f)
Referenced by GMRESV2().
GMRESV2()
void F77NAME() GMRESV2 (const int *const a, const double *const b, double * c, int * d, double * e, double * f) inline
Definition at line 174 of file SPV2.h.
{
  F77NAME(gmresv2)(a,b,c,d,e,f);
}
References F77NAME, and gmresv2().
Referenced by SolvElem_Gmres::iteration().
ilu0v2()
void F77DECLARE() ilu0v2 (const int * n, const double * a, const int * ja, const int * ia, const double * alu, const int * jlu, const int * ju, const int * jw, const int * ierr)
Referenced by ILU0V2().
ILU0V2()
void F77NAME() ILU0V2 (const int * n, const double * a, const int * ja, const int * ia, const double * alu, const int * jlu, const int * ju, const int * jw, const int * ierr) inline
Definition at line 65 of file SPV2.h.
{
  F77NAME(ilu0v2)( n,a,ja,ia,alu,jlu,ju,jw,  ierr)
  ;
}
References F77NAME, and ilu0v2().
ilutv2()
void F77DECLARE() ilutv2 (const int * n, const double * a, const int * ja, const int * ia, const int * lfil, const double * droptol, const double * alu, const int * jlu, const int * ju, const int * iwk, const double * w, const int * jw, const int * ierr)
Referenced by ILUTV2().
ILUTV2()
void F77NAME() ILUTV2 (const int * n, const double * a, const int * ja, const int * ia, const int * lfil, const double * droptol, const double * alu, const int * jlu, const int * ju, const int * iwk, const double * w, const int * jw, const int * ierr) inline
Definition at line 27 of file SPV2.h.
{
  F77NAME(ilutv2)( n,a,ja,ia,lfil,droptol,alu,jlu,ju,iwk,w,jw,  ierr)
  ;
}
References F77NAME, and ilutv2().
Referenced by ILU::factoriser().
LUSOLV2()
void F77NAME() LUSOLV2 (const int *const a, const double *const b, const double *const c, const double *const d, const int *const e, const int *const f) inline
Definition at line 124 of file SPV2.h.
{
  F77NAME(lusolv2)(a,b,c,d,e,f);
}
References F77NAME, and lusolv2().
Referenced by ILU::ilu().
lusolv2()
void F77DECLARE() lusolv2 (const int * const , const double * const , const double * const , const double * const , const int * const , const int * const)
Referenced by LUSOLV2().
LUTSOLV2()
void F77NAME() LUTSOLV2 (const int *const a, const double *const b, const double *const c, const double *const d, const int *const e, const int *const f) inline
Definition at line 131 of file SPV2.h.
{
  F77NAME(lutsolv2)(a,b,c,d,e,f);
}
References F77NAME, and lutsolv2().
Referenced by ILU::ilut().
lutsolv2()
void F77DECLARE() lutsolv2 (const int * const , const double * const , const double * const , const double * const , const int * const , const int * const)
Referenced by LUTSOLV2().
milu0v2()
void F77DECLARE() milu0v2 (const int * n, const double * a, const int * ja, const int * ia, const double * alu, const int * jlu, const int * ju, const int * jw, const int * ierr)
Referenced by MILU0V2().
MILU0V2()
void F77NAME() MILU0V2 (const int * n, const double * a, const int * ja, const int * ia, const double * alu, const int * jlu, const int * ju, const int * jw, const int * ierr) inline
Definition at line 46 of file SPV2.h.
{
  F77NAME(milu0v2)( n,a,ja,ia,alu,jlu,ju,jw,  ierr)
  ;
}
References F77NAME, and milu0v2().
PGMRESV2()
void F77NAME() PGMRESV2 (const int *const a, const int *const b, const double *const c, double *const d, const double *const e, const double *const f, const int *const g, const int *const h, const double *const i, const int *const j, const int *const k, const double *const l, const int *const m, const int *const n, int *const o) inline
Definition at line 152 of file SPV2.h.
{
  F77NAME(pgmresv2)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o);
}
References F77NAME, and pgmresv2().
pgmresv2()
void F77DECLARE() pgmresv2 (const int * const , const int * const , const double * const , double * const , const double * const , const double * const , const int * const , const int * const , const double * const , const int * const , const int * const , const double * const , const int * const , const int * const , int * const)
Referenced by PGMRESV2().