TRUST: src/Kernel/Math/SolvSys/SSOR.cpp File Reference
src/Kernel/Math/SolvSys/SSOR.cpp File Reference
#include <SSOR.h>
#include <Motcle.h>
#include <Matrice_Morse_Sym.h>
#include <Matrice_Bloc_Sym.h>
#include <MD_Vector_tools.h>
#include <MD_Vector_base.h>
#include <Param.h>
#include <ConstDoubleTab_parts.h>
Functions
void traite_diagonale (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void remontee (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void remontee (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void descente_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente_bloc_extradiag_assert (const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, const DoubleVect &vecteur, DoubleVect &vecteur2)
void remontee_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void remontee_bloc_extradiag_assert (const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const DoubleVect &vecteur2)
void descente_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void descente_bloc_extradiag_assert (const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, const DoubleVect &vecteur, DoubleVect &vecteur2, const ArrOfInt &items_a_traiter)
void remontee_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void remontee_bloc_extradiag_assert (const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const DoubleVect &vecteur2, const ArrOfInt &items_a_traiter)
void descente_diag_ok_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void remontee_diag_ok_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente_diag_ok_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void remontee_diag_ok_assert (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void descente_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void remontee_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void remontee_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void descente_assert_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void remontee_assert_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur)
void descente_assert_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
void remontee_assert_precond_diag (const double omega, const ArrOfInt &tab1, const ArrOfInt &tab2, const ArrOfDouble &coeff, DoubleVect &vecteur, const ArrOfInt &items_a_traiter)
Variables
const Type_info * SSORbases [1] = { &(Precond_base ::info_obj)}
Function Documentation
void descente (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 179 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
        static_cast<void> (0);
        const double omega_coeff_i_i = omega / (*coeff_ptr);
        const double v_i = sol_fortran[i] *= omega_coeff_i_i;
        tab2_ptr++;
        coeff_ptr++;
        for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
          {
            const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
            const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
// Pas d'items virtuels autorises !
            static_cast<void> (0);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
            sol_fortran[i2] -= coeff_i_i2 * v_i;
          }
      }
    }
}
void descente (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 282 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *flags_ptr = items_a_traiter.addr();
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      static_cast<void> (0);
      const int item_a_traiter = *(flags_ptr++);
      if (item_a_traiter)
        {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
          static_cast<void> (0);
          const double omega_coeff_i_i = omega / (*coeff_ptr);
          const double v_i = sol_fortran[i] *= omega_coeff_i_i;
          tab2_ptr++;
          coeff_ptr++;
          for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
            {
              const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
              const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
              static_cast<void> (0);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
              sol_fortran[i2] -= coeff_i_i2 * v_i;
            }
        }
      else
        {
// **Annulation items communs**
// c'est la derniere fois qu'on ecrit dans sol_fortran[i] car la
// matrice est diagonale superieure. Pour eviter le test sur items_a_traiter_
// dans la remontee, on annule la solution pour les items communs et virtuels
// (sol_fortran[i] ne sera plus modifie ensuite dans la descente)
          sol_fortran[i] = 0.;
          coeff_ptr += nvois;
          tab2_ptr += nvois;
        }
    }
// **Annulation items communs**
// Pour la remontee il faut annuler les valeurs dans les cases virtuelles
  {
    const int fin = vecteur.size_totale();
    for (int i = nb_lignes_a_traiter+1; i <= fin; i++)
      sol_fortran[i] = 0.;
  }
}
void descente_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 586 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *flags_ptr = items_a_traiter.addr();
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      assert((flags_ptr - items_a_traiter.addr()) == (i-1));
      const int item_a_traiter = *(flags_ptr++);
      if (item_a_traiter)
        {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
          assert(nvois >= 1 && (*tab2_ptr) == i && (*coeff_ptr) > 0.);
          const double omega_coeff_i_i = omega / (*coeff_ptr);
          const double v_i = sol_fortran[i] *= omega_coeff_i_i;
          tab2_ptr++;
          coeff_ptr++;
          for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
            {
              const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
              const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
              assert(i2 > i && i2 <= vecteur.size_totale());
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
              sol_fortran[i2] -= coeff_i_i2 * v_i;
            }
        }
      else
        {
// **Annulation items communs**
// c'est la derniere fois qu'on ecrit dans sol_fortran[i] car la
// matrice est diagonale superieure. Pour eviter le test sur items_a_traiter_
// dans la remontee, on annule la solution pour les items communs et virtuels
// (sol_fortran[i] ne sera plus modifie ensuite dans la descente)
          sol_fortran[i] = 0.;
          coeff_ptr += nvois;
          tab2_ptr += nvois;
        }
    }
// **Annulation items communs**
// Pour la remontee il faut annuler les valeurs dans les cases virtuelles
  {
    const int fin = vecteur.size_totale();
    for (int i = nb_lignes_a_traiter+1; i <= fin; i++)
      sol_fortran[i] = 0.;
  }
}
void descente_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 411 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
        assert(nvois >= 1 && (*tab2_ptr) == i && (*coeff_ptr) > 0.);
        const double omega_coeff_i_i = omega / (*coeff_ptr);
        const double v_i = sol_fortran[i] *= omega_coeff_i_i;
        tab2_ptr++;
        coeff_ptr++;
        for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
          {
            const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
            const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
// Pas d'items virtuels autorises !
            assert(i2 > i && i2 <= nb_lignes_a_traiter);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
            sol_fortran[i2] -= coeff_i_i2 * v_i;
          }
      }
    }
}
void descente_assert_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 1239 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      {
// Pas de coefficient diagonal stocke (ni dans tab2 ni dans coeff), la diagonale vaut 1:
        const double v_i = sol_fortran[i] *= omega;
        for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
          {
            const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
            const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
// Pas d'items virtuels autorises !
            assert(i2 > i && i2 <= nb_lignes_a_traiter);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
            sol_fortran[i2] -= coeff_i_i2 * v_i;
          }
      }
    }
}
void descente_assert_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 1333 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *flags_ptr = items_a_traiter.addr();
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      assert((flags_ptr - items_a_traiter.addr()) == (i-1));
      const int item_a_traiter = *(flags_ptr++);
      if (item_a_traiter)
        {
// Pas de coefficient diagonal stocke (ni dans tab2 ni dans coeff), la diagonale vaut 1:
          const double v_i = sol_fortran[i] *= omega;
          for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
            {
              const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
              const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
              assert(i2 > i && i2 <= vecteur.size_totale());
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
              sol_fortran[i2] -= coeff_i_i2 * v_i;
            }
        }
      else
        {
// **Annulation items communs**
// c'est la derniere fois qu'on ecrit dans sol_fortran[i] car la
// matrice est diagonale superieure. Pour eviter le test sur items_a_traiter_
// dans la remontee, on annule la solution pour les items communs et virtuels
// (sol_fortran[i] ne sera plus modifie ensuite dans la descente)
          sol_fortran[i] = 0.;
          coeff_ptr += nvois;
          tab2_ptr += nvois;
        }
    }
// **Annulation items communs**
// Pour la remontee il faut annuler les valeurs dans les cases virtuelles
  {
    const int fin = vecteur.size_totale();
    for (int i = nb_lignes_a_traiter+1; i <= fin; i++)
      sol_fortran[i] = 0.;
  }
}
void descente_bloc_extradiag_assert (const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, const DoubleVect & vecteur, DoubleVect & vecteur2, const ArrOfInt & items_a_traiter)
Definition at line 659 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr();
  const double *vecteur_ptr = vecteur.addr();
  double       *vecteur2_fortran_ptr = vecteur2.addr() - 1;
  const int *tab2_fortran_ptr = tab2.addr() - 1;
  const double *coeff_fortran_ptr = coeff.addr() - 1;
  assert(coeff.size_array() == tab2.size_array());
  for (int i_ligne = 0; i_ligne < nb_lignes; i_ligne++, vecteur_ptr++)
    {
      if (*(flags_ptr++))
        {
          const double v_i = *vecteur_ptr;
          int index = tab1[i_ligne];
          const int index_fin = tab1[i_ligne+1];
// Il peut n'y avoir aucun coefficient sur la ligne => index_fin == index
          assert(index > 0 && index_fin >= index && index_fin <= tab2.size_array()+1);
          const int *tab2_ptr = tab2_fortran_ptr + index;
          const double *coeff_ptr = coeff_fortran_ptr + index;
          for (; index < index_fin; index++, tab2_ptr++, coeff_ptr++)
            {
              const int i_colonne = *tab2_ptr;
              assert(i_colonne >= 1 && i_colonne <= vecteur2.size_array());
              const double c = *coeff_ptr;
// pas de test item commun sur les colonnes, voir **Annulation items communs**
              vecteur2_fortran_ptr[i_colonne] -= c * v_i;
            }
        }
    }
}
void descente_bloc_extradiag_assert (const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, const DoubleVect & vecteur, DoubleVect & vecteur2)
Definition at line 461 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double *vecteur_ptr = vecteur.addr();
  double       *vecteur2_fortran_ptr = vecteur2.addr() - 1;
  const int *tab2_fortran_ptr = tab2.addr() - 1;
  const double *coeff_fortran_ptr = coeff.addr() - 1;
  assert(coeff.size_array() == tab2.size_array());
  for (int i_ligne = 0; i_ligne < nb_lignes; i_ligne++, vecteur_ptr++)
    {
      {
        const double v_i = *vecteur_ptr;
        int index = tab1[i_ligne];
        const int index_fin = tab1[i_ligne+1];
// Il peut n'y avoir aucun coefficient sur la ligne => index_fin == index
        assert(index > 0 && index_fin >= index && index_fin <= tab2.size_array()+1);
        const int *tab2_ptr = tab2_fortran_ptr + index;
        const double *coeff_ptr = coeff_fortran_ptr + index;
        for (; index < index_fin; index++, tab2_ptr++, coeff_ptr++)
          {
            const int i_colonne = *tab2_ptr;
            assert(i_colonne >= 1 && i_colonne <= vecteur2.size_array());
            const double c = *coeff_ptr;
// pas de test item commun sur les colonnes, voir **Annulation items communs**
            vecteur2_fortran_ptr[i_colonne] -= c * v_i;
          }
      }
    }
}
void descente_diag_ok_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 896 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *flags_ptr = items_a_traiter.addr();
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      assert((flags_ptr - items_a_traiter.addr()) == (i-1));
      const int item_a_traiter = *(flags_ptr++);
      if (item_a_traiter)
        {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
          assert(nvois >= 1 && (*tab2_ptr) == i && (*coeff_ptr) > 0.);
          const double omega_coeff_i_i = omega / (*coeff_ptr);
          const double v_i = sol_fortran[i] *= omega_coeff_i_i;
          tab2_ptr++;
          coeff_ptr++;
          for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
            {
              const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
              const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
              assert(i2 > i && i2 <= vecteur.size_totale());
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
              sol_fortran[i2] -= coeff_i_i2 * v_i;
            }
        }
      else
        {
// **Annulation items communs**
// c'est la derniere fois qu'on ecrit dans sol_fortran[i] car la
// matrice est diagonale superieure. Pour eviter le test sur items_a_traiter_
// dans la remontee, on annule la solution pour les items communs et virtuels
// (sol_fortran[i] ne sera plus modifie ensuite dans la descente)
          sol_fortran[i] = 0.;
          coeff_ptr += nvois;
          tab2_ptr += nvois;
        }
    }
// **Annulation items communs**
// Pour la remontee il faut annuler les valeurs dans les cases virtuelles
  {
    const int fin = vecteur.size_totale();
    for (int i = nb_lignes_a_traiter+1; i <= fin; i++)
      sol_fortran[i] = 0.;
  }
}
void descente_diag_ok_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 793 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      assert(nvois >= 0 && (tab1_de_i - 1) <= tab2.size_array());
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      {
// Le premier coeff doit etre le coef diagonal et doit etre strictement positif
        assert(nvois >= 1 && (*tab2_ptr) == i && (*coeff_ptr) > 0.);
        const double omega_coeff_i_i = omega / (*coeff_ptr);
        const double v_i = sol_fortran[i] *= omega_coeff_i_i;
        tab2_ptr++;
        coeff_ptr++;
        for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
          {
            const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
            const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
// Pas d'items virtuels autorises !
            assert(i2 > i && i2 <= nb_lignes_a_traiter);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
            sol_fortran[i2] -= coeff_i_i2 * v_i;
          }
      }
    }
}
void descente_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 1025 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      {
// Pas de coefficient diagonal stocke (ni dans tab2 ni dans coeff), la diagonale vaut 1:
        const double v_i = sol_fortran[i] *= omega;
        for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
          {
            const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
            const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
// Pas d'items virtuels autorises !
            static_cast<void> (0);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
            sol_fortran[i2] -= coeff_i_i2 * v_i;
          }
      }
    }
}
void descente_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< sinon 2 lignes ci-dessous fausses.
< = tab1[i]
< indice de colonne pour le prochain coefficient
Definition at line 1119 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
// le pointeur est constant, pas le tableau pointe.
  double * const sol_fortran = vecteur.addr() - 1;
  const int *flags_ptr = items_a_traiter.addr();
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const int *tab1_ptr = tab1.addr();
  assert(nb_lignes_a_traiter <= tab1.size_array() + 1);
  assert(*tab1_ptr == 1); //!< sinon 2 lignes ci-dessous fausses.
  const int *tab2_ptr = tab2.addr();
  const double *coeff_ptr = coeff.addr();
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr++;
  for (int i = 1; i <= nb_lignes_a_traiter; i++, tab1_ptr++)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = tab1_de_i - last_tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester, sinon on pollue les autres lignes du vecteur sol
// avec des valeurs dependant des items communs et virtuels
      static_cast<void> (0);
      const int item_a_traiter = *(flags_ptr++);
      if (item_a_traiter)
        {
// Pas de coefficient diagonal stocke (ni dans tab2 ni dans coeff), la diagonale vaut 1:
          const double v_i = sol_fortran[i] *= omega;
          for (int j = nvois-1; j; j--, tab2_ptr++, coeff_ptr++)
            {
              const int i2 = *tab2_ptr; //!< indice de colonne pour le prochain coefficient
              const double coeff_i_i2 = *coeff_ptr;
// la matrice n'a que des coeffs diagonaux superieurs et on a deja traite
// la diagonale, donc i2 > i.
              static_cast<void> (0);
// B.M.: ... en revanche, le test sur les items communs est superflu ici car
// la valeur sera annulee (voir **Annulation items communs**),
// gain de perfs si on ne fait pas le test
              sol_fortran[i2] -= coeff_i_i2 * v_i;
            }
        }
      else
        {
// **Annulation items communs**
// c'est la derniere fois qu'on ecrit dans sol_fortran[i] car la
// matrice est diagonale superieure. Pour eviter le test sur items_a_traiter_
// dans la remontee, on annule la solution pour les items communs et virtuels
// (sol_fortran[i] ne sera plus modifie ensuite dans la descente)
          sol_fortran[i] = 0.;
          coeff_ptr += nvois;
          tab2_ptr += nvois;
        }
    }
// **Annulation items communs**
// Pour la remontee il faut annuler les valeurs dans les cases virtuelles
  {
    const int fin = vecteur.size_totale();
    for (int i = nb_lignes_a_traiter+1; i <= fin; i++)
      sol_fortran[i] = 0.;
  }
}
void remontee (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< = tab1[i]
Definition at line 353 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr() + nb_lignes_a_traiter - 1;
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (*(flags_ptr--))
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          static_cast<void> (0);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
          *soli_ptr = (*soli_ptr) * psi * omega - x * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< = tab1[i]
Definition at line 227 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (1)
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          static_cast<void> (0);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
          *soli_ptr = (*soli_ptr) * psi * omega - x * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< = tab1[i]
Definition at line 494 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (1)
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          assert((*tab2_ptr) == i);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
          *soli_ptr = (*soli_ptr) * psi * omega - x * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< = tab1[i]
Definition at line 695 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr() + nb_lignes_a_traiter - 1;
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (*(flags_ptr--))
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          assert((*tab2_ptr) == i);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
          *soli_ptr = (*soli_ptr) * psi * omega - x * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_assert_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< = tab1[i]
Definition at line 1400 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr() + nb_lignes_a_traiter - 1;
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (*(flags_ptr--))
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// Preconditionnement diagonal, pas de coefficient diagonal stocke:
          *soli_ptr = ((*soli_ptr) * psi - x) * omega;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_assert_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< = tab1[i]
Definition at line 1283 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (1)
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// Preconditionnement diagonal, pas de coefficient diagonal stocke:
          *soli_ptr = ((*soli_ptr) * psi - x) * omega;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_bloc_extradiag_assert (const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const DoubleVect & vecteur2)
Definition at line 552 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), ArrOfInt::size_array(), ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  double *vecteur_ptr = vecteur.addr();
  const double *vecteur2_fortran_ptr = vecteur2.addr() - 1;
  const int *tab2_fortran_ptr = tab2.addr() - 1;
  const double *coeff_fortran_ptr = coeff.addr() - 1;
  assert(coeff.size_array() == tab2.size_array());
  for (int i_ligne = 0; i_ligne < nb_lignes; i_ligne++, vecteur_ptr++)
    {
      {
        double x = *vecteur_ptr;
        int index = tab1[i_ligne];
        const int index_fin = tab1[i_ligne+1];
// Il peut n'y avoir aucun coefficient sur la ligne => index_fin == index
        assert(index > 0 && index_fin >= index && index_fin <= tab2.size_array()+1);
        const int *tab2_ptr = tab2_fortran_ptr + index;
        const double *coeff_ptr = coeff_fortran_ptr + index;
        for (; index < index_fin; index++, tab2_ptr++, coeff_ptr++)
          {
            const int i_colonne = *tab2_ptr;
            assert(i_colonne >= 1 && i_colonne <= vecteur2.size_array());
            const double c = *coeff_ptr;
            const double x2 = vecteur2_fortran_ptr[i_colonne];
// pas de test item commun sur les colonnes, voir **Annulation items communs**
            x -= c * x2;
          }
        *vecteur_ptr = x;
      }
    }
}
void remontee_bloc_extradiag_assert (const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const DoubleVect & vecteur2, const ArrOfInt & items_a_traiter)
Definition at line 756 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr();
  double *vecteur_ptr = vecteur.addr();
  const double *vecteur2_fortran_ptr = vecteur2.addr() - 1;
  const int *tab2_fortran_ptr = tab2.addr() - 1;
  const double *coeff_fortran_ptr = coeff.addr() - 1;
  assert(coeff.size_array() == tab2.size_array());
  for (int i_ligne = 0; i_ligne < nb_lignes; i_ligne++, vecteur_ptr++)
    {
      if (*(flags_ptr++))
        {
          double x = *vecteur_ptr;
          int index = tab1[i_ligne];
          const int index_fin = tab1[i_ligne+1];
// Il peut n'y avoir aucun coefficient sur la ligne => index_fin == index
          assert(index > 0 && index_fin >= index && index_fin <= tab2.size_array()+1);
          const int *tab2_ptr = tab2_fortran_ptr + index;
          const double *coeff_ptr = coeff_fortran_ptr + index;
          for (; index < index_fin; index++, tab2_ptr++, coeff_ptr++)
            {
              const int i_colonne = *tab2_ptr;
              assert(i_colonne >= 1 && i_colonne <= vecteur2.size_array());
              const double c = *coeff_ptr;
              const double x2 = vecteur2_fortran_ptr[i_colonne];
// pas de test item commun sur les colonnes, voir **Annulation items communs**
              x -= c * x2;
            }
          *vecteur_ptr = x;
        }
    }
}
void remontee_diag_ok_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< = tab1[i]
Definition at line 967 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr() + nb_lignes_a_traiter - 1;
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (*(flags_ptr--))
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          assert((*tab2_ptr) == i);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
// La diagonale a deja ete multipliee par psi * coeff_i_i
          *soli_ptr = ((*soli_ptr) - x) * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_diag_ok_assert (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< = tab1[i]
Definition at line 841 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      assert(nvois >= 0 && tab1_de_i > 0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (1)
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// ici coeff_ptr est le coeff diagonal
          assert((*tab2_ptr) == i);
          const double coeff_i_i = *coeff_ptr;
          const double omega_coeff_i_i = omega / coeff_i_i;
// La diagonale a deja ete multipliee par psi * coeff_i_i
          *soli_ptr = ((*soli_ptr) - x) * omega_coeff_i_i;
          coeff_ptr--;
          tab2_ptr--;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< = tab1[i]
Definition at line 1069 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (1)
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// Preconditionnement diagonal, pas de coefficient diagonal stocke:
          *soli_ptr = ((*soli_ptr) * psi - x) * omega;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void remontee_precond_diag (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur, const ArrOfInt & items_a_traiter)
< = tab1[i]
Definition at line 1186 of file SSOR.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), ArrOfInt::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const int *flags_ptr = items_a_traiter.addr() + nb_lignes_a_traiter - 1;
  assert(nb_lignes_a_traiter <= items_a_traiter.size_array());
  const double psi = (2. - omega) / omega;
// pointeur "fortran" vers le tableau solution (indexable avec index fortran)
  const double * const sol_fortran = vecteur.addr() - 1;
  const int *tab1_ptr = tab1.addr() + nb_lignes_a_traiter;
  int last_tab1_de_i = *tab1_ptr;
  tab1_ptr--;
// On ne va pas a la fin de tab2 car on n'est pas sur que nb_lignes_a_traiter = tab1.size_array() :
// -2 car last_tab1_de_i est l'indice du premier coefficient de la ligne suivante en fortran
// (dont -1 pour fortran->c et -1 pour passer au dernier coeff de la ligne precedente)
  const int *tab2_ptr = tab2.addr() + last_tab1_de_i - 2;
  const double *coeff_ptr = coeff.addr() + last_tab1_de_i - 2;
  double * soli_ptr = vecteur.addr() + nb_lignes_a_traiter - 1;
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr--, soli_ptr--)
    {
      const int tab1_de_i = *tab1_ptr; //!< = tab1[i]
      const int nvois = last_tab1_de_i - tab1_de_i;
      static_cast<void> (0);
      last_tab1_de_i = tab1_de_i;
// Ce test doit rester car il ne faut pas modifier sol[i] pour les items communs
// et virtuels (ils sont nuls et doivent le rester pour ne pas polluer les autres lignes):
      if (*(flags_ptr--))
        {
// Operation "diagonale":
          double x = 0.;
          for (int j = nvois-1; j; j--, tab2_ptr--, coeff_ptr--)
            {
              const int i2 = *tab2_ptr;
              const double coeff_i_i2 = *coeff_ptr;
// Operation nulle pour les items communs et virtuels
// (on a annule le second membre lors de la descente)
              x += coeff_i_i2 * sol_fortran[i2];
            }
// Preconditionnement diagonal, pas de coefficient diagonal stocke:
          *soli_ptr = ((*soli_ptr) * psi - x) * omega;
        }
      else
        {
          assert((*soli_ptr) == 0.);
          coeff_ptr -= nvois;
          tab2_ptr -= nvois;
        }
    }
}
void traite_diagonale (const double omega, const ArrOfInt & tab1, const ArrOfInt & tab2, const ArrOfDouble & coeff, DoubleVect & vecteur)
< indexable par index fortran
Definition at line 161 of file SSOR.cpp.
References ArrOfInt::addr(), ArrOfDouble::addr(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and DoubleVect::size_totale().
Referenced by SSOR::ssor().
{
  const int nb_lignes_a_traiter = vecteur.size_reelle_ok() ? vecteur.size_reelle() : vecteur.size_totale();
  const double psi = (2. - omega) / omega;
  const double *coeff_fortran = coeff.addr() - 1; //!< indexable par index fortran
  const int *tab1_ptr = tab1.addr();
  double *vect_ptr = vecteur.addr();
  for (int i = nb_lignes_a_traiter; i; i--, tab1_ptr++, vect_ptr++)
    {
      const int j = *tab1_ptr;
// Coefficient diagonale de la ligne i:
      const double coeff_i_i = coeff_fortran[j];
      (*vect_ptr) *= psi * coeff_i_i;
    }
}
Variable Documentation
const Type_info* SSORbases[1] = { &(Precond_base ::info_obj)}
Definition at line 36 of file SSOR.cpp.