TRUST: src/Kernel/Utilitaires/Statistiques.h File Reference
Statistiques.h File Reference
#include <assert.h>
Classes
class Statistiques
class Stat_Counter_Id
class Stat_Results
Functions
Statistiques & statistiques ()
Variables
static const int JUMP_3_FIRST_STEPS = 0
static const int GET_COMM_DETAILS = 1
Statistiques * les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe
Function Documentation
statistiques()
Statistiques & statistiques () inline
Definition at line 183 of file Statistiques.h.
{
  assert(les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe);
  return *les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe;
}
References les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe.
Referenced by Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Div::ajouter(), Operateur_Grad::ajouter(), Source::ajouter(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Comm_Group_MPI::all_to_all(), Comm_Group_MPI::all_to_allv(), Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Equation_base::assembler_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_mat(), Comm_Group_MPI::barrier(), Comm_Group_MPI::broadcast(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Source::calculer(), Operateur::calculer_pas_de_temps(), call_echange_espace_virtuel(), declare_stat_counters(), mon_main::dowork(), end_stat_counters(), Equation_base::Gradient_conjugue_diff_impl(), ICoCo::ProblemTrio::initialize(), Scatter::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Pb_Dilatable_base::iterateTimeStep(), Scatter::lire_domaine(), Schema_Temps_base::mettre_a_jour(), Comm_Group_MPI::mp_collective_op(), Comm_Group_MPI::mppartial_sum(), Probleme_base::postraiter(), print_statistics_analyse(), Comm_Group_MPI::ptop_send_recv(), EcrFicPartageMPIIO::put(), Champ_Fonc_reprise::readOn(), Comm_Group_MPI::recv(), Probleme_base::reprendre(), Solv_Petsc::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), SolveurSys::resoudre_systeme(), Probleme_U::run(), Probleme_U::runUntil(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), Comm_Group_MPI::send(), Comm_Group_MPI::send_recv_finish(), Comm_Group_MPI::send_recv_start(), ICoCo::ProblemTrio::solveTimeStep(), EcrFicPartage::syncfile(), ICoCo::ProblemTrio::terminate(), test_un_solveur(), Schema_Temps_base::validateTimeStep(), and ICoCo::ProblemTrio::validateTimeStep().
Variable Documentation
GET_COMM_DETAILS
const int GET_COMM_DETAILS = 1 static
Definition at line 28 of file Statistiques.h.
Referenced by Statistiques::begin_communication_tracking(), Statistiques::compute_avg_min_max_var_per_step(), declare_stat_counters(), mon_main::dowork(), Statistiques::dump(), Statistiques::end_communication_tracking(), end_stat_counters(), print_statistics_analyse(), and Probleme_U::run().
JUMP_3_FIRST_STEPS
const int JUMP_3_FIRST_STEPS = 0 static
Definition at line 26 of file Statistiques.h.
Referenced by Statistiques::begin_count_(), Statistiques::compute_avg_min_max_var_per_step(), Statistiques::dump(), Statistiques::end_count_(), print_statistics_analyse(), and Probleme_U::run().
les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe
Statistiques* les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe extern
Definition at line 70 of file Statistiques.cpp.
Referenced by declare_stat_counters(), mon_main::dowork(), end_stat_counters(), and statistiques().