TRUST: src/Kernel/Utilitaires/Statistiques.cpp File Reference
Statistiques.cpp File Reference
#include <Statistiques.h>
#include <EcrFicPartage.h>
#include <SChaine.h>
#include <petsc_for_kernel.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <stdio.h>
#include <TRUSTArray.h>
#include <communications.h>
#include <map>
Classes
class Time
class Stat_Internals
Macros
#define TIME_IS_gettimeofday
#define GetTimeOfDay_or_rusage
#define BUFLEN 100
Functions
static void print_stat (Sortie &perfs, Sortie &perfs_globales, const char *description, int level, double time, double nb, double quantity, double temps_total_max, int skip_globals, double avg_time_per_step=0, double min_time_per_step=0, double max_time_per_step=0, double var_time_per_step=0)
Variables
Statistiques * les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe = 0
static const double INITIAL_MIN = 1000.0
static const int MILLION = 1000000
static const int MAXCOUNTERS = 1000
Macro Definition Documentation
BUFLEN
#define BUFLEN 100
Definition at line 81 of file Statistiques.cpp.
GetTimeOfDay_or_rusage
#define GetTimeOfDay_or_rusage
Definition at line 75 of file Statistiques.cpp.
TIME_IS_gettimeofday
#define TIME_IS_gettimeofday
Definition at line 72 of file Statistiques.cpp.
Function Documentation
print_stat()
static void print_stat (Sortie & perfs, Sortie & perfs_globales, const char * description, int level, double time, double nb, double quantity, double temps_total_max, int skip_globals, double avg_time_per_step = 0, double min_time_per_step = 0, double max_time_per_step = 0, double var_time_per_step = 0) static
Definition at line 529 of file Statistiques.cpp.
{
  char tampon[BUFLEN+200];
  if (Process::nproc() > 1)
    {
      double percent_time = (temps_total_max==0 ? 0 : time / temps_total_max * 100.);
      char s[50];
      s[0] = 0;
      if (min_time_per_step != max_time_per_step)
        sprintf(s, "(%0.3f,%0.3f, %0.3f)", min_time_per_step == INITIAL_MIN? 0.0 : min_time_per_step, max_time_per_step, var_time_per_step);
      sprintf(tampon, "%55s (%02d) %10.2f %5.1f%% %10.3g %10.3g %10.2f %10s ",
              description, (True_int)level, time, percent_time, nb, quantity,
              avg_time_per_step, s);
      perfs << tampon << finl;
    }
  if (! skip_globals)
    {
      ArrOfDouble tmp(3);
// Min
      tmp[0]=time;
      tmp[1]=nb;
      tmp[2]=quantity;
      mp_min_for_each_item(tmp);
      double min_time = tmp[0];
      double min_nb = tmp[1];
      double min_quantity = tmp[2];
// Max
      tmp[0]=time;
      tmp[1]=nb;
      tmp[2]=quantity;
      mp_max_for_each_item(tmp);
      double max_time = tmp[0];
      double max_nb = tmp[1];
      double max_quantity = tmp[2];
// Average
      tmp.resize(5);
      tmp[0]=time;
      tmp[1]=nb;
      tmp[2]=quantity;
      tmp[3]=avg_time_per_step;
      tmp[4]=var_time_per_step;
      mp_sum_for_each_item(tmp);
      double avg_time = tmp[0] / Process::nproc();
      double avg_nb = tmp[1] / Process::nproc();
      double avg_quantity = tmp[2] / Process::nproc();
      double avg_avg_time_ps = tmp[3] / Process::nproc();
      double avg_var_time_ps = tmp[4]/ Process::nproc();
      if (Process::je_suis_maitre())
        {
          double percent_time = (temps_total_max==0 ? 0 : avg_time / temps_total_max * 100.);
          char s1[50], s2[50], s3[50];
          s1[0] = s2[0] = s3[0] = 0;
          if (min_time != max_time)
            sprintf(s1, "(%0.2f,%0.2f)", min_time, max_time);
          if (min_nb != max_nb)
            sprintf(s2, "(%0.3g,%0.3g)", min_nb, max_nb);
          if (min_quantity != max_quantity)
            sprintf(s3, "(%0.3g,%0.3g)", min_quantity, max_quantity);
          sprintf(tampon,
                  "%55s (%02d) %10.2f  %5.1f%% %-23s %10.3g %-23s %10.3g %-23s %10.2f (%0.3f)",
                  description, (True_int)level,
                  avg_time, percent_time, s1,
                  avg_nb, s2,
                  avg_quantity, s3,
                  avg_avg_time_ps, avg_var_time_ps);
          perfs_globales << tampon << finl;
        }
    }
}
References BUFLEN, finl, INITIAL_MIN, Process::je_suis_maitre(), mp_max_for_each_item(), mp_min_for_each_item(), mp_sum_for_each_item(), Process::nproc(), and TRUSTArray< _TYPE_ >::resize().
Referenced by Statistiques::dump().
Variable Documentation
INITIAL_MIN
const double INITIAL_MIN = 1000.0 static
Definition at line 83 of file Statistiques.cpp.
Referenced by print_stat(), Statistiques::reset_counters(), and Stat_Internals::Stat_Internals().
les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe
Statistiques* les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe = 0
Definition at line 70 of file Statistiques.cpp.
Referenced by declare_stat_counters(), mon_main::dowork(), end_stat_counters(), and statistiques().
MAXCOUNTERS
const int MAXCOUNTERS = 1000 static
Definition at line 261 of file Statistiques.cpp.
Referenced by Statistiques::allocate_communication_tracking_times(), Statistiques::new_counter(), Statistiques::reset_counters(), and Stat_Internals::Stat_Internals().
MILLION
const int MILLION = 1000000 static
Definition at line 96 of file Statistiques.cpp.
Referenced by Time::add(), Time::add_time(), and Time::minus().