TRUST: BlocData Struct Reference
BlocData Struct Reference
Public Member Functions
void add_bloc (Domaine &domaine, const ArrsOfDouble &coord_ijk) const
int nb_som (int i) const
int nb_elem (int i) const
void add_faces (Zone &zone, const Nom &nombord, int offset_sommets, int dir, int cote_max) const
Public Attributes
ArrOfInt xmax_tot_
ArrOfInt xmin_
ArrOfInt xmax_
Noms bord_xmin_
Noms bord_xmax_
Detailed Description
Definition at line 47 of file MaillerParallel.cpp.
Member Function Documentation
add_bloc()
void BlocData::add_bloc (Domaine & domaine, const ArrsOfDouble & coord_ijk) const
Definition at line 68 of file MaillerParallel.cpp.
{
  if (nb_elem(0) < 1 || nb_elem(1) < 1 || nb_elem(2) < 1)
    {
      Cerr << "Error : not enough nodes in a block, increase mesh size or decrease processor count" << finl;
      Process::exit();
    }
  const int dim = 3;
// Les sommets
  const int old_nb_som = domaine.les_sommets().dimension(0);
  {
    DoubleTab& sommets = domaine.les_sommets();
    const int nsom = nb_som(0) * nb_som(1) * nb_som(2);
    sommets.resize(old_nb_som + nsom, dim);
    int index = old_nb_som;
    int i, j, k;
    for (k = xmin_[2]; k < xmax_[2]; k++)
      {
        for (j = xmin_[1]; j < xmax_[1]; j++)
          {
            for (i = xmin_[0]; i < xmax_[0]; i++)
              {
                sommets(index, 0) = coord_ijk[0][i];
                sommets(index, 1) = coord_ijk[1][j];
                if (dim==3)
                  sommets(index, 2) = coord_ijk[2][k];
                index++;
              }
          }
      }
  }
// Les elements
  {
    assert(dim==3);
    Zone& zone = domaine.zone(0);
    IntTab& elements = zone.les_elems();
    const int nb_som_par_element = 8;
// stride des indices de sommets:
    const int dx = 1;
    const int dy = nb_som(0);
    const int dz = dy * nb_som(1);
// nombre d'elements dans chaque direction
    const int nx = nb_elem(0);
    const int ny = nb_elem(1);
    const int nz = nb_elem(2);
    const int nb_elem_old = zone.les_elems().dimension(0);
    const int nbelem = nx * ny * nz;
    elements.resize(nb_elem_old + nbelem, nb_som_par_element);
    int index = nb_elem_old;
    int i, j, k;
    for (k = 0; k < nz; k++)
      {
        for (j = 0; j < ny; j++)
          {
            for (i = 0; i < nx; i++)
              {
                int n = old_nb_som + k * dz + j * dy + i * dx;
                elements(index, 0) = n;
                elements(index, 1) = n + dx;
                elements(index, 2) = n + dy;
                elements(index, 3) = n + dx + dy;
                elements(index, 4) = n + dz;
                elements(index, 5) = n + dz + dx;
                elements(index, 6) = n + dz + dy;
                elements(index, 7) = n + dz + dx + dy;
                index++;
              }
          }
      }
  }
// Les bords
  Zone& zone = domaine.zone(0);
  for (int dir = 0; dir < 3; dir++)
    {
      if (xmin_[dir] == 0)
        add_faces(zone, bord_xmin_[dir], old_nb_som, dir, 0);
      if (xmax_[dir] == xmax_tot_[dir])
        add_faces(zone, bord_xmax_[dir], old_nb_som, dir, 1);
    }
}
References add_faces(), bord_xmax_, bord_xmin_, Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Zone::les_elems(), Domaine::les_sommets(), nb_elem(), nb_som(), TRUSTTab< _TYPE_ >::resize(), xmax_, xmax_tot_, xmin_, and Domaine::zone().
Referenced by MaillerParallel::interpreter().
add_faces()
void BlocData::add_faces (Zone & zone, const Nom & nombord, int offset_sommets, int dir, int cote_max) const
Definition at line 152 of file MaillerParallel.cpp.
{
  int nfaces1, nfaces2;
  int increment1, increment2;
  int increment_dir;
  switch(dir)
    {
    case 0:
      nfaces1 = nb_elem(1);
      nfaces2 = nb_elem(2);
      increment1 = nb_som(0);
      increment2 = nb_som(0) * nb_som(1);
      increment_dir = 1;
      break;
    case 1:
      nfaces1 = nb_elem(0);
      nfaces2 = nb_elem(2);
      increment1 = 1;
      increment2 = nb_som(0) * nb_som(1);
      increment_dir = nb_som(0);
      break;
    default:
      nfaces1 = nb_elem(0);
      nfaces2 = nb_elem(1);
      increment1 = 1;
      increment2 = nb_som(0);
      increment_dir = nb_som(0)*nb_som(1);
      break;
    }
  if (cote_max)
    offset_sommets += increment_dir * (nb_som(dir)-1);
  IntTab& faces = zone.frontiere(nombord).faces().les_sommets();
  int count = faces.dimension(0);
  zone.frontiere(nombord).faces().dimensionner(count + nfaces1 * nfaces2);
  for (int i = 0; i < nfaces2; i++)
    {
      int sommet = offset_sommets;
      for (int j = 0; j < nfaces1; j++)
        {
          faces(count, 0) = sommet;
          faces(count, 1) = sommet + increment1;
          faces(count, 2) = sommet + increment2;
          faces(count, 3) = sommet + increment1 + increment2;
          sommet += increment1;
          count++;
        }
      offset_sommets += increment2;
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Faces::dimensionner(), Frontiere::faces(), Zone::frontiere(), Faces::les_sommets(), nb_elem(), and nb_som().
Referenced by add_bloc().
nb_elem()
int BlocData::nb_elem (int i) const inline
Definition at line 61 of file MaillerParallel.cpp.
  {
    return xmax_[i] - xmin_[i] - 1;
  }
References xmax_, and xmin_.
Referenced by add_bloc(), and add_faces().
nb_som()
int BlocData::nb_som (int i) const inline
Definition at line 57 of file MaillerParallel.cpp.
  {
    return xmax_[i] - xmin_[i];
  }
References xmax_, and xmin_.
Referenced by add_bloc(), and add_faces().
Member Data Documentation
bord_xmax_
Noms BlocData::bord_xmax_
Definition at line 56 of file MaillerParallel.cpp.
Referenced by add_bloc(), and MaillerParallel::interpreter().
bord_xmin_
Noms BlocData::bord_xmin_
Definition at line 56 of file MaillerParallel.cpp.
Referenced by add_bloc(), and MaillerParallel::interpreter().
xmax_
ArrOfInt BlocData::xmax_
Definition at line 55 of file MaillerParallel.cpp.
Referenced by add_bloc(), MaillerParallel::interpreter(), nb_elem(), and nb_som().
xmax_tot_
ArrOfInt BlocData::xmax_tot_
Definition at line 54 of file MaillerParallel.cpp.
Referenced by add_bloc(), and MaillerParallel::interpreter().
xmin_
ArrOfInt BlocData::xmin_
Definition at line 55 of file MaillerParallel.cpp.
Referenced by add_bloc(), MaillerParallel::interpreter(), nb_elem(), and nb_som().
The documentation for this struct was generated from the following file:
src/Kernel/Geometrie/MaillerParallel.cpp