TRUST: Roue_ptr Struct Reference
Roue_ptr Struct Reference
Pointeur sur une roue.
La roue est creee dans le constructeur, detruite dans le destructeur.
Elle est recopiee dans le constructeur par recopie
et dans l'operateur d'affectation d'un Roue_ptr a un autre.
Dans tous les autres cas seuls les pointeurs sont manipules.
#include <Roue.h>
Public Member Functions
Roue * operator-> () const
Roue * operator-> ()
Roue_ptr (const Roue_ptr &)
Constructeur par recopie. Copie de l'ensemble de la roue.
Utile pour les constructeurs par recopie des champs.
(ce constructeur est appele quand on fait un Champ = un autre Champ,
la version precedente copie la reference, d'ou plantage a la destruction)
Roue_ptr & operator= (const Roue_ptr &x)
Constructeur par recopie. Copie de l'ensemble de la roue.
Roue_ptr (Roue &)
Roue_ptr ()
Roue_ptr (Roue *)
~Roue_ptr ()
Roue & valeur ()
const Roue & valeur () const
void annule ()
operator bool () const
Roue & operator= (Roue &x)
Roue * operator= (Roue *x)
Roue & operator[] (int i)
const Roue & operator[] (int i) const
Public Attributes
Roue * ptr
Detailed Description
Pointeur sur une roue.
La roue est creee dans le constructeur, detruite dans le destructeur.
Elle est recopiee dans le constructeur par recopie
et dans l'operateur d'affectation d'un Roue_ptr a un autre.
Dans tous les autres cas seuls les pointeurs sont manipules.
Definition at line 34 of file Roue.h.
Constructor & Destructor Documentation
Roue_ptr() [1/4]
Roue_ptr::Roue_ptr (const Roue_ptr & x)
Constructeur par recopie. Copie de l'ensemble de la roue.
Utile pour les constructeurs par recopie des champs.
(ce constructeur est appele quand on fait un Champ = un autre Champ,
la version precedente copie la reference, d'ou plantage a la destruction)
Definition at line 45 of file Roue.cpp.
{
  ptr=new Roue(x.valeur());
}
References ptr, and valeur().
Roue_ptr() [2/4]
Roue_ptr::Roue_ptr (Roue & x)
Definition at line 73 of file Roue.cpp.
                         :ptr(&x)
{
}
Roue_ptr() [3/4]
Roue_ptr::Roue_ptr ()
Definition at line 35 of file Roue.cpp.
                   : ptr(new(Roue))
{
}
Roue_ptr() [4/4]
Roue_ptr::Roue_ptr (Roue * x) inline
Definition at line 141 of file Roue.h.
: ptr(x) {}
~Roue_ptr()
Roue_ptr::~Roue_ptr ()
Definition at line 90 of file Roue.cpp.
{
  if(ptr)
    {
      delete ptr;
      ptr=0;
    }
}
References ptr.
Member Function Documentation
annule()
void Roue_ptr::annule () inline
Definition at line 55 of file Roue.h.
  {
    ptr=0;
  }
References ptr.
operator bool()
Roue_ptr::operator bool () const inline
Definition at line 59 of file Roue.h.
  {
    return (ptr!=0);
  }
References ptr.
operator->() [1/2]
Roue * Roue_ptr::operator-> () inline
Definition at line 174 of file Roue.h.
{
  return ptr;
}
References ptr.
operator->() [2/2]
Roue * Roue_ptr::operator-> () const inline
Definition at line 156 of file Roue.h.
{
  return ptr;
}
References ptr.
operator=() [1/3]
Roue_ptr & Roue_ptr::operator= (const Roue_ptr & x)
Constructeur par recopie. Copie de l'ensemble de la roue.
Definition at line 52 of file Roue.cpp.
{
  Cerr << "We pass through Roue_ptr=Roue_ptr" << finl;
  assert(0);
  ptr=new Roue(x.valeur());
  return *this;
}
References Cerr, finl, ptr, and valeur().
operator=() [2/3]
Roue & Roue_ptr::operator= (Roue & x) inline
Definition at line 63 of file Roue.h.
  {
    ptr=&x;
    return *ptr;
  }
References ptr.
operator=() [3/3]
Roue * Roue_ptr::operator= (Roue * x) inline
Definition at line 68 of file Roue.h.
  {
    return ptr=x;
  }
References ptr.
operator[]() [1/2]
Roue & Roue_ptr::operator[] (int i)
Definition at line 112 of file Roue.cpp.
{
  return ptr->futur(i);
}
References Roue::futur(), and ptr.
operator[]() [2/2]
const Roue & Roue_ptr::operator[] (int i) const
Definition at line 131 of file Roue.cpp.
{
  return ptr->futur(i);
}
References Roue::futur(), and ptr.
valeur() [1/2]
Roue & Roue_ptr::valeur () inline
Definition at line 47 of file Roue.h.
  {
    return *ptr;
  }
References ptr.
Referenced by Roue::avancer(), Champ_Inc_base::changer_temps_futur(), Champ_Inc_base::changer_temps_passe(), operator=(), Roue::reculer(), Champ_Inc_base::recuperer_temps_futur(), Champ_Inc_base::recuperer_temps_passe(), Roue_ptr(), and Champ_Inc_base::valeurs().
valeur() [2/2]
const Roue & Roue_ptr::valeur () const inline
Definition at line 51 of file Roue.h.
  {
    return *ptr;
  }
References ptr.
Member Data Documentation
ptr
Roue* Roue_ptr::ptr
Definition at line 46 of file Roue.h.
Referenced by Roue::ajouter_case(), annule(), operator bool(), operator->(), operator=(), operator[](), Roue_ptr(), Roue::supprimer_case(), valeur(), Roue::~Roue(), and ~Roue_ptr().
The documentation for this struct was generated from the following files:
src/Kernel/Utilitaires/Roue.h
src/Kernel/Utilitaires/Roue.cpp