TRUST: src/Kernel/Utilitaires/Synonyme_info.cpp File Reference
Synonyme_info.cpp File Reference
#include <Synonyme_info.h>
#include <Noms.h>
Functions
static char char_uppercase (char c)
static int strcmp_uppercase (const char *n1, const char *n2)
Function Documentation
char_uppercase()
static char char_uppercase (char c) inline static
Definition at line 40 of file Synonyme_info.cpp.
{
  if (c >= 'a' && c <= 'z')
    c += 'A' - 'a';
  return c;
}
Referenced by strcmp_uppercase().
strcmp_uppercase()
static int strcmp_uppercase (const char * n1, const char * n2) inline static
Definition at line 47 of file Synonyme_info.cpp.
{
  int i = 0;
  unsigned char c1, c2;
  int delta;
  do
    {
      c1 = (unsigned char) char_uppercase(n1[i]);
      c2 = (unsigned char) char_uppercase(n2[i]);
      delta = c1 - c2;
      i++;
    }
  while ((delta == 0) && (c1 != 0) && (c2 != 0));
  return delta;
}
References char_uppercase().
Referenced by Synonyme_info::search_synonyme_info_name().