TRUST: src/Kernel/Math/Table.cpp File Reference
src/Kernel/Math/Table.cpp File Reference
#include <Table.h>
#include <utility>
Functions
double nlinear_interpolation (const std::vector< double > &x, const std::vector< std::pair< double, double >> &gridpoints, const std::vector< double > &data)
Variables
const Type_info * Tablebases [1] = { &(Objet_U ::info_obj)}
Function Documentation
double nlinear_interpolation (const std::vector< double > & x, const std::vector< std::pair< double, double >> & gridpoints, const std::vector< double > & data)
Definition at line 148 of file Table.cpp.
References max(), and min().
Referenced by Table::val().
{
  const int n = x.size();
// on construit les poids pour chaque sommet de l'hyper-rectangle
  std::vector<std::pair<double, double>> Wvecs;
  for (int i = 0; i < n; i++)
    {
      const double weight = min(1.0, max(0.0, (x[i] - gridpoints[i].first) / (gridpoints[i].second - gridpoints[i].first)));
      Wvecs.push_back({1 - weight, weight});
    }
// le calcul est effecte en utilisant une representation en bit j (int) -> index (n valeurs 0 ou 1)
// j=0 -> index=00...000 ; j=1 -> index=00...001 ; j=2 -> index=00...010
  double interpolant = 0.0;
  for (int j = 0; j < pow(2, n); j++)
    {
      std::vector<int> index(n, 0);
      for (int k = 0; k < n; k++) index[n - 1 - k] = ((j >> k) & 1);
      double prodw = 1.0;
      for (int i = 0; i < n; i++) prodw *= index[i] ? Wvecs[i].second : Wvecs[i].first;
// for (int i = 0; i < n; i++) prodw *= std::get<index[i]>(Wvecs[i]);
      int k = index.back();
      for (int i = 0; i < n - 1; i++) k += pow(2, n - i - 1) * index[i];
      interpolant += data[k] * prodw;
    }
  return interpolant;
}
Variable Documentation
const Type_info* Tablebases[1] = { &(Objet_U ::info_obj)}
Definition at line 26 of file Table.cpp.