TRUST: src/VEF/Sources/Terme_Source_Qdm_VEF_Face.cpp File Reference
src/VEF/Sources/Terme_Source_Qdm_VEF_Face.cpp File Reference
#include <Terme_Source_Qdm_VEF_Face.h>
#include <Champ_Uniforme.h>
#include <Domaine.h>
#include <Zone_Cl_dis.h>
#include <Zone_VEF.h>
#include <Zone_Cl_VEF.h>
#include <Periodique.h>
#include <BilanQdmVEF.h>
#include <Equation_base.h>
#include <Champ_Inc.h>
#include <Debog.h>
#include <Schema_Temps_base.h>
#include <Zone_VEF_PreP1b.h>
Functions
double calculer_coef_som (int elem, int &nb_face_diri, ArrOfInt &indice_diri, const Zone_Cl_VEF &zcl, const Zone_VEF &zone_VEF)
Variables
const Type_info * Terme_Source_Qdm_VEF_Facebases [1] = { &(Source_base ::info_obj)}
Function Documentation
double calculer_coef_som (int elem, int & nb_face_diri, ArrOfInt & indice_diri, const Zone_Cl_VEF & zcl, const Zone_VEF & zone_VEF)
Definition at line 159 of file Op_Div_VEFP1B_Elem.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone_VEF::rang_elem_non_std(), type_elem(), and Zone_Cl_VEF::type_elem_Cl().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), and Op_Div_VEFP1B_Elem::ajouter_som().
{
// prov ajouter verif par %2 ....
  int type_elem=0;
  int& dimension= Objet_U::dimension;
  int rang_elem=zone_VEF.rang_elem_non_std()(elem);
  if (rang_elem!=-1)
    type_elem=zcl.type_elem_Cl(rang_elem);
  if ((0)||(type_elem==0))
    {
      nb_face_diri=0;
      double coeff_som=1./(dimension*(dimension+1));
      return coeff_som;
    }
  else
    {
      if (dimension==2)
        {
          switch(type_elem)
            {
            case 1:
              nb_face_diri=1;
              indice_diri[0]=2;
              break;
            case 2:
              nb_face_diri=1;
              indice_diri[0]=1;
              break;
            case 4:
              nb_face_diri=1;
              indice_diri[0]=0;
              break;
            case 3:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=2;
              break;
            case 5:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=2;
              break;
            case 6:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=1;
              break;
            default:
              nb_face_diri=10000;
              Cerr<<__FILE__<<(int)__LINE__<<" impossible "<<finl;
              Process::exit();
              break;
            }
        }
      else if (dimension==3)
        {
          switch(type_elem)
            {
            case 1:
              nb_face_diri=1;
              indice_diri[0]=3;
              break;
            case 2:
              nb_face_diri=1;
              indice_diri[0]=2;
              break;
            case 4:
              nb_face_diri=1;
              indice_diri[0]=1;
              break;
            case 8:
              nb_face_diri=1;
              indice_diri[0]=0;
              break;
            case 3:
              nb_face_diri=2;
              indice_diri[0]=3;
              indice_diri[1]=2;
              break;
            case 5:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=3;
              break;
            case 6:
              nb_face_diri=2;
              indice_diri[0]=1;
              indice_diri[1]=2;
              break;
            case 9:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=3;
              break;
            case 10:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=2;
              break;
            case 12:
              nb_face_diri=2;
              indice_diri[0]=0;
              indice_diri[1]=1;
              break;
            case 7:
              nb_face_diri=3;
              indice_diri[0]=1;
              indice_diri[1]=2;
              indice_diri[2]=3;
              break;
            case 11:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=2;
              indice_diri[2]=3;
              break;
            case 13:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=1;
              indice_diri[2]=3;
              break;
            case 14:
              nb_face_diri=3;
              indice_diri[0]=0;
              indice_diri[1]=1;
              indice_diri[2]=2;
              break;
            default:
              nb_face_diri=10000;
              Cerr<<__FILE__<<(int)__LINE__<<" impossible "<<finl;
              Process::exit();
              break;
            }
        }
      else
        {
          nb_face_diri=10000;
          abort();
          Process::exit();
        }
    }
  double coeff_som=1./(dimension*(dimension+1-nb_face_diri));
  return coeff_som;
}
Variable Documentation
const Type_info* Terme_Source_Qdm_VEF_Facebases[1] = { &(Source_base ::info_obj)}
Definition at line 38 of file Terme_Source_Qdm_VEF_Face.cpp.