TRUST: src/ThHyd/Incompressible/Sources/Terme_Boussinesq_base.cpp File Reference
Terme_Boussinesq_base.cpp File Reference
#include <Convection_Diffusion_std.h>
#include <Terme_Boussinesq_base.h>
#include <Milieu_composite.h>
#include <Motcle.h>
Functions
void read (Entree &is, Parser_U &fct_Scalaire0_)
Variables
const Type_info * Terme_Boussinesq_basebases [1] ={ &(Source_base ::info_obj)}
Function Documentation
read()
void read (Entree & is, Parser_U & fct_Scalaire0_)
Definition at line 83 of file Terme_Boussinesq_base.cpp.
{
  Nom expression;
  is >> expression;
  std::string ss(expression.getString());
  for (auto & c: ss) c = toupper(c);
  fct_Scalaire0_.setNbVar(1);
  fct_Scalaire0_.setString(ss);
  fct_Scalaire0_.addVar("t");
  fct_Scalaire0_.parseString();
}
References Parser_U::addVar(), Nom::getString(), Parser_U::parseString(), Parser_U::setNbVar(), and Parser_U::setString().
Referenced by Terme_Boussinesq_base::lire_donnees().
Variable Documentation
Terme_Boussinesq_basebases
const Type_info* Terme_Boussinesq_basebases[1] ={ &(Source_base ::info_obj)}
Definition at line 21 of file Terme_Boussinesq_base.cpp.