TRUST: src/ThHyd/Incompressible/Sources/Terme_Boussinesq_base.h File Reference
Terme_Boussinesq_base.h File Reference
#include <Ref_Champ_Don_base.h>
#include <Ref_Champ_Don.h>
#include <Champ_Don.h>
#include <Equation_base.h>
#include <Probleme_base.h>
#include <Parser_U.h>
#include <Ref_Convection_Diffusion_std.h>
#include <Vect_Parser_U.h>
#include <Convection_Diffusion_Temperature.h>
#include <Domaine.h>
Classes
class Terme_Boussinesq_base
Classe Terme_Boussinesq_base
Cette classe represente le terme de gravite qui figure dans l'equation
de la dynamique divisee par la masse volumique de reference.
On est dans le cadre de l'hypothese de Boussinesq:la masse volumique est
supposee constante et egale a sa valeur de reference sauf dans le terme
des forces de volumes ou on prend en compte une petite variation de la
masse volumique en fonction d'un ou de plusieurs scalaires transportes
par l'ecoulement (la temperature et/ou une ou plusieurs concentrations).
Cas particulier de Terme_Boussinesq_base pour la temperature
Le terme de gravite a pour expression: beta*(T-T0) ou beta
represente la dilatabilite de la masse volumique et T0 une valeur
de reference pour la temperature
Cas particulier de Terme_Boussinesq_base pour une concentration
Le terme de gravite a pour expression : beta*(C-C0)
ou (beta[0]*(C[0]-C0[0]) + .....+ beta[i]*(C[i]-C0[i])) dans
le cas d'un vecteur de concentrations
beta represente la variation de la masse volumique en fonction
de la concentration du constituant et C0 une valeur de reference
pour la concentration.
Functions
double valeur (const DoubleTab &valeurs, const int elem, const int dim)
double valeur (const DoubleTab &valeurs_champ, int elem1, int elem2, const int compo)
Function Documentation
valeur() [1/2]
double valeur (const DoubleTab & valeurs, const int elem, const int dim) inline
Definition at line 132 of file Terme_Boussinesq_base.h.
{
  if(valeurs.nb_dim()==1)
    return valeurs(elem);
  else
    return valeurs(elem,dim);
}
References TRUSTTab< _TYPE_ >::nb_dim().
valeur() [2/2]
double valeur (const DoubleTab & valeurs_champ, int elem1, int elem2, const int compo) inline
< Champ uniforme
< face frontiere
Definition at line 141 of file Terme_Boussinesq_base.h.
{
  if (valeurs_champ.dimension(0)==1)
    return valeurs_champ(0,compo); //!< Champ uniforme
  else
    {
      if (elem2<0) elem2 = elem1; //!< face frontiere
      if (valeurs_champ.nb_dim()==1)
        return 0.5*(valeurs_champ(elem1)+valeurs_champ(elem2));
      else
        return 0.5*(valeurs_champ(elem1,compo)+valeurs_champ(elem2,compo));
    }
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTTab< _TYPE_ >::nb_dim().