TRUST: src/Kernel/Geometrie/Tetraedriser_homogene.cpp File Reference
Tetraedriser_homogene.cpp File Reference
#include <Tetraedriser_homogene.h>
Functions
static void decoupe (Zone &zone, Faces &faces, IntTab &new_soms_old_elems)
int creer_sommet (Domaine &dom, Zone &zone, DoubleTab &new_soms, IntTab &elem_traite, IntTab &new_soms_old_elems, int NbSom, IntTab &sommets, int &compteur, int oldnbsom, int &nbnewsoms)
Variables
const Type_info * Tetraedriser_homogenebases [1] ={ &(Triangulation_base ::info_obj)}
Function Documentation
creer_sommet()
int creer_sommet (Domaine & dom, Zone & zone, DoubleTab & new_soms, IntTab & elem_traite, IntTab & new_soms_old_elems, int NbSom, IntTab & sommets, int & compteur, int oldnbsom, int & nbnewsoms)
Definition at line 129 of file Tetraedriser_homogene.cpp.
{
  const DoubleTab& coord_sommets=dom.coord_sommets();
// int nb_zones = dom.nb_zones();
  int _out;
  double x=0,y=0,z=0;
// x = 0.5*(coord_sommets(i1,0)+coord_sommets(i2,0));
// y = 0.5*(coord_sommets(i1,1)+coord_sommets(i2,1));
// z = 0.5*(coord_sommets(i1,2)+coord_sommets(i2,2));
  for (int ii=0 ; ii<NbSom ; ii++)
    {
      x += coord_sommets(sommets(ii),0);
      y += coord_sommets(sommets(ii),1);
      z += coord_sommets(sommets(ii),2);
    }
  x /= NbSom;
  y /= NbSom;
  z /= NbSom;
  int trouve = -1;
  /*
    for (int zo=0; zo<nb_zones-1; zo++) {
    trouve = dom.zone(zo).chercher_elements(x,y,z);
    if(trouve!=-1) break;
    }
  */
  trouve = zone.chercher_elements(x,y,z);
  if (trouve<0)
    {
      for (int ii=0 ; ii<NbSom ; ii++)
        {
          Cerr<<"i"<<ii<<"="<<sommets(ii)<<" coord="<<coord_sommets(sommets(ii),0)<<" "<<coord_sommets(sommets(ii),1)<<" "<<coord_sommets(sommets(ii),2)<<finl;
        }
      Cerr<<"x="<<x<<" y="<<y<<" z="<<z<<finl;
      Cerr<<"-----"<<finl;
      assert(trouve>=0);
    }
  if (elem_traite(trouve))
    {
      _out = -1;
      int j = 0;
      double epsilon = Objet_U::precision_geom;
      do
        {
          if ((std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 0)-x)<epsilon) &&
              (std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 1)-y)<epsilon)&&
              (std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 2)-z)<epsilon))
            /*if ((coord_sommets(new_soms_old_elems(trouve, j), 0) == x) &&
              (coord_sommets(new_soms_old_elems(trouve, j), 1) == y) &&
              (coord_sommets(new_soms_old_elems(trouve, j), 2) == z)   ) */
            {
              _out = new_soms_old_elems(trouve, j);
            }
          j++;
        }
      while ((_out == -1) && (j<19));
      if (_out<0)
        {
          Cerr << "Error, not found !" << finl;
          Cerr << "found="<<trouve<<" x="<<x<<" y="<<y<<" z="<<z<<finl;
          for (int ii=0 ; ii<NbSom ; ii++)
            {
              Cerr<<"i"<<ii<<"="<<sommets(ii)<<" coord="<<coord_sommets(sommets(ii),0)<<" "<<coord_sommets(sommets(ii),1)<<" "<<coord_sommets(sommets(ii),2)<<finl;
            }
          Process::exit();
        }
    }
  else
    {
      _out = oldnbsom + nbnewsoms;
      new_soms(compteur, 0) = x;
      new_soms(compteur, 1) = y;
      new_soms(compteur, 2) = z;
      nbnewsoms++;
      compteur++;
    }
  if(_out<0)
    {
      Cerr << "Problem at the creation of node" << finl;
      Process::exit();
    }
  return _out;
}
References Cerr, Zone::chercher_elements(), compteur, Domaine::coord_sommets(), Process::exit(), finl, and Objet_U::precision_geom.
Referenced by Tetraedriser_homogene::trianguler().
decoupe()
static void decoupe (Zone & zone, Faces & faces, IntTab & new_soms_old_elems) static
Definition at line 32 of file Tetraedriser_homogene.cpp.
{
  const Domaine& dom=zone.domaine();
  const DoubleTab& coord=dom.coord_sommets();
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  assert(sommets.dimension(1)==4);
  IntTab nouveaux(8*nb_faces, 3);
  faces.voisins().resize(8*nb_faces, 2);
  faces.voisins()=-1;
  for(int i=0; i<nb_faces; i++)
    {
      int i1 = sommets(i,0);
      int i3 = sommets(i,1);
      int i7 = sommets(i,2);
      int i9 = sommets(i,3);
      double x=0.5*(coord(i1,0)+coord(i3,0));
      double y=0.5*(coord(i1,1)+coord(i3,1));
      double z=0.5*(coord(i1,2)+coord(i3,2));
      int i2 = zone.chercher_sommets( x, y, z);
      assert(i2>=0);
      x=0.5*(coord(i3,0)+coord(i9,0));
      y=0.5*(coord(i3,1)+coord(i9,1));
      z=0.5*(coord(i3,2)+coord(i9,2));
      int i4 = zone.chercher_sommets(x, y, z);
      assert(i4>=0);
      x=0.5*(coord(i1,0)+coord(i7,0));
      y=0.5*(coord(i1,1)+coord(i7,1));
      z=0.5*(coord(i1,2)+coord(i7,2));
      int i5 = zone.chercher_sommets(x, y, z) ;
      assert(i5>=0);
      x=0.5*(coord(i7,0)+coord(i9,0));
      y=0.5*(coord(i7,1)+coord(i9,1));
      z=0.5*(coord(i7,2)+coord(i9,2));
      int i8 = zone.chercher_sommets(x, y, z) ;
      assert(i8>=0);
// Nouveau : on prend le barycentre de la face
// x=0.5*(coord(i3,0)+coord(i7,0));
// y=0.5*(coord(i3,1)+coord(i7,1));
// z=0.5*(coord(i3,2)+coord(i7,2));
      x=0.25*(coord(i1,0)+coord(i3,0)+coord(i7,0)+coord(i9,0));
      y=0.25*(coord(i1,1)+coord(i3,1)+coord(i7,1)+coord(i9,1));
      z=0.25*(coord(i1,2)+coord(i3,2)+coord(i7,2)+coord(i9,2));
      int i6 = zone.chercher_sommets(x, y, z) ;
      if (i6<0)
        {
          Cerr<<"New Node i6 not found : pos="<<x<<" "<<y<<" "<<z<<finl;
          Cerr<<"  -> i6="<<i6<<finl;
        }
      assert(i6>=0);
      nouveaux(i,0) = i1;
      nouveaux(i,1) = i2;
      nouveaux(i,2) = i6;
      nouveaux(nb_faces+i,0) = i1;
      nouveaux(nb_faces+i,1) = i6;
      nouveaux(nb_faces+i,2) = i5;
      nouveaux(2*nb_faces+i,0) = i7;
      nouveaux(2*nb_faces+i,1) = i6;
      nouveaux(2*nb_faces+i,2) = i5;
      nouveaux(3*nb_faces+i,0) = i7;
      nouveaux(3*nb_faces+i,1) = i6;
      nouveaux(3*nb_faces+i,2) = i8;
      nouveaux(4*nb_faces+i,0) = i9;
      nouveaux(4*nb_faces+i,1) = i6;
      nouveaux(4*nb_faces+i,2) = i8;
      nouveaux(5*nb_faces+i,0) = i9;
      nouveaux(5*nb_faces+i,1) = i6;
      nouveaux(5*nb_faces+i,2) = i4;
      nouveaux(6*nb_faces+i,0) = i3;
      nouveaux(6*nb_faces+i,1) = i6;
      nouveaux(6*nb_faces+i,2) = i4;
      nouveaux(7*nb_faces+i,0) = i3;
      nouveaux(7*nb_faces+i,1) = i6;
      nouveaux(7*nb_faces+i,2) = i2;
    }
  sommets.ref(nouveaux);
}
References Cerr, Zone::chercher_sommets(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), finl, Faces::les_sommets(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), and Faces::voisins().
Referenced by Tetraedriser_homogene::trianguler().
Variable Documentation
Tetraedriser_homogenebases
const Type_info* Tetraedriser_homogenebases[1] ={ &(Triangulation_base ::info_obj)}
Definition at line 18 of file Tetraedriser_homogene.cpp.