TRUST: src/Kernel/Geometrie/Tetraedriser_par_prisme.cpp File Reference
Tetraedriser_par_prisme.cpp File Reference
#include <Tetraedriser_par_prisme.h>
#include <Domaine.h>
Functions
static void decoupe (Zone &zone, Faces &faces)
Fonction hors classe
Decoupe toutes les faces d'un objet Faces
dont les faces ont 4 sommets
en 2 faces a 3 sommets.
Variables
const Type_info * Tetraedriser_par_prismebases [1] ={ &(Triangulation_base ::info_obj)}
Function Documentation
decoupe()
static void decoupe (Zone & zone, Faces & faces) static
Fonction hors classe
Decoupe toutes les faces d'un objet Faces
dont les faces ont 4 sommets
en 2 faces a 3 sommets.
Definition at line 78 of file Tetraedriser_par_prisme.cpp.
{
  const Domaine& dom=zone.domaine();
  const DoubleTab& coord=dom.coord_sommets();
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  assert(sommets.dimension(1)==4);
  IntTab nouveaux(2*nb_faces, 3);
  faces.voisins().resize(2*nb_faces, 2);
  faces.voisins()=-1;
  for(int i=0; i<nb_faces; i++)
    {
      int i1 = sommets(i,0);
      int i2 = sommets(i,1);
      int i3 = sommets(i,2);
      int i4 = sommets(i,3);
// C'est une face a X constant
      if((coord(i1,0)==coord(i2,0)) && (coord(i1,0)==coord(i3,0)))
        {
          nouveaux(i,0) = i1;
          nouveaux(i,1) = i2;
          nouveaux(i,2) = i3;
          nouveaux(nb_faces+i,0) = i2;
          nouveaux(nb_faces+i,1) = i3;
          nouveaux(nb_faces+i,2) = i4;
        }
// C'est une face a Z constant
      if((coord(i1,2)==coord(i2,2)) && (coord(i1,2)==coord(i3,2)))
        {
          nouveaux(i,0) = i1;
          nouveaux(i,1) = i2;
          nouveaux(i,2) = i3;
          nouveaux(nb_faces+i,0) = i2;
          nouveaux(nb_faces+i,1) = i3;
          nouveaux(nb_faces+i,2) = i4;
        }
// C'est une face a Y constant
      if((coord(i1,1)==coord(i2,1)) && (coord(i1,1)==coord(i3,1)))
        {
          nouveaux(i,0) = i1;
          nouveaux(i,1) = i2;
          nouveaux(i,2) = i4;
          nouveaux(nb_faces+i,0) = i1;
          nouveaux(nb_faces+i,1) = i3;
          nouveaux(nb_faces+i,2) = i4;
        }
    }
  sommets.ref(nouveaux);
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Faces::les_sommets(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), and Faces::voisins().
Referenced by Tetraedriser_par_prisme::trianguler().
Variable Documentation
Tetraedriser_par_prismebases
const Type_info* Tetraedriser_par_prismebases[1] ={ &(Triangulation_base ::info_obj)}
Definition at line 19 of file Tetraedriser_par_prisme.cpp.