TRUST: src/Kernel/Geometrie/Tetraedriser.cpp File Reference
Tetraedriser.cpp File Reference
#include <Tetraedriser.h>
Functions
static void decoupe (Faces &faces)
Fonction hors classe
Decoupe toutes les faces d'un objet Faces
dont les faces on 4 sommets
en 2 faces a 3 sommets.
Variables
const Type_info * Tetraedriserbases [1] ={ &(Triangulation_base ::info_obj)}
Function Documentation
decoupe()
static void decoupe (Faces & faces) static
Fonction hors classe
Decoupe toutes les faces d'un objet Faces
dont les faces on 4 sommets
en 2 faces a 3 sommets.
Definition at line 77 of file Tetraedriser.cpp.
{
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  assert(sommets.dimension(1)==4);
  IntTab nouveaux(2*nb_faces, 3);
  faces.voisins().resize(2*nb_faces, 2);
  faces.voisins()=-1;
  for(int i=0; i<nb_faces; i++)
    {
      int i1 = sommets(i,0);
      int i2 = sommets(i,1);
      int i3 = sommets(i,2);
      int i4 = sommets(i,3);
      nouveaux(i,0) = i1;
      nouveaux(i,1) = i2;
      nouveaux(i,2) = i3;
      nouveaux(nb_faces+i,0) = i2;
      nouveaux(nb_faces+i,1) = i3;
      nouveaux(nb_faces+i,2) = i4;
    }
  sommets.ref(nouveaux);
}
References TRUSTTab< _TYPE_ >::dimension(), Faces::les_sommets(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), and Faces::voisins().
Referenced by Tetraedriser::trianguler().
Variable Documentation
Tetraedriserbases
const Type_info* Tetraedriserbases[1] ={ &(Triangulation_base ::info_obj)}
Definition at line 18 of file Tetraedriser.cpp.