TRUST: src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_EC.cpp File Reference
Traitement_particulier_NS_EC.cpp File Reference
#include <Traitement_particulier_NS_EC.h>
#include <Navier_Stokes_std.h>
#include <Zone_VF.h>
#include <Terme_Source_Acceleration.h>
#include <Milieu_base.h>
#include <Ref_ArrOfDouble.h>
#include <Ref_DoubleTab.h>
#include <Probleme_base.h>
#include <Schema_Temps_base.h>
#include <sys/stat.h>
Functions
static double trait_part_calculer_ec_faces (const int face_debut, const int nb_faces, const int frontiere, const DoubleTab &vitesse, const DoubleVect &volumes_entrelaces, const DoubleTab &xv, const DoubleTab &masse_volumique, const ArrOfDouble &translation, const ArrOfDouble &rotation, const int repere_mobile_, const ArrOfInt &faces_doubles)
Fonction outil utilisee dans calculer_Ec. Calcule la somme
de 0.5*v^2*rho*volumes_entrelaces.
Variables
const Type_info * Traitement_particulier_NS_ECbases [1] ={ &(Traitement_particulier_NS_base ::info_obj)}
Function Documentation
trait_part_calculer_ec_faces()
static double trait_part_calculer_ec_faces (const int face_debut, const int nb_faces, const int frontiere, const DoubleTab & vitesse, const DoubleVect & volumes_entrelaces, const DoubleTab & xv, const DoubleTab & masse_volumique, const ArrOfDouble & translation, const ArrOfDouble & rotation, const int repere_mobile_, const ArrOfInt & faces_doubles) static
Fonction outil utilisee dans calculer_Ec. Calcule la somme
de 0.5*v^2*rho*volumes_entrelaces.
< En effet probleme de conception, il faudrait avoir l'orientation des faces VDF
Definition at line 187 of file Traitement_particulier_NS_EC.cpp.
{
  const int face_fin = face_debut + nb_faces;
  double ec = 0.;
  double rho = 0.;
  const int nb_dim_1 = (vitesse.line_size() == 1);
  const int dim      = Objet_U::dimension;
  ArrOfDouble ve(Objet_U::dimension);
  for (int face = face_debut; face < face_fin; face++)
    {
// Calcul de la vitesse d'entrainement
      if (repere_mobile_)
        {
          ve[0]=translation[0];
          ve[1]=translation[1];
          if (Objet_U::dimension==3)
            {
              ve[2]=translation[2];
              ve[0]+=rotation[1]*xv(face,2)-rotation[2]*xv(face,1);
              ve[1]+=rotation[2]*xv(face,0)-rotation[0]*xv(face,2);
              ve[2]+=rotation[0]*xv(face,1)-rotation[1]*xv(face,0);
            }
        }
      else
        ve=0;
      double v2;
      double volume;
      if (nb_dim_1)
        {
// Une composante de vitesse a la face (VDF)
          const double v = vitesse(face);
          if (repere_mobile_)
            {
              Cerr << "Le codage de l'energie cinetique calculee dans un repere fixe" <<finl;
              Cerr << "n'est pas fait en VDF." << finl;
              Process::exit(); //!< En effet probleme de conception, il faudrait avoir l'orientation des faces VDF
            }
          v2 = v * v;
// En VDF, sur les frontieres, on ne prend que le 1/2 volume entrelace
          volume = (frontiere ? 0.5 : 1) * volumes_entrelaces(face);
        }
      else
        {
// Deux ou trois composantes (VEFP1B)
          v2 = 0.;
          for (int i = 0; i < dim; i++)
            {
              const double v_i = vitesse(face, i);
              v2 += (v_i + ve[i]) * (v_i + ve[i]);
            }
// En VEF, cela est incorrect, il faudrait les volumes etendus:
          volume = volumes_entrelaces(face);
        }
      const int k = (masse_volumique.dimension(0)==1) ? 0 : face;
      rho = masse_volumique(k, 0);
      double contribution = (faces_doubles[face]==1) ? 0.5 : 1 ;
      ec += contribution * 0.5 * v2 * volume * rho;
    }
  return ec;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, and TRUSTVect< _TYPE_ >::line_size().
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
Variable Documentation
Traitement_particulier_NS_ECbases
const Type_info* Traitement_particulier_NS_ECbases[1] ={ &(Traitement_particulier_NS_base ::info_obj)}
Definition at line 27 of file Traitement_particulier_NS_EC.cpp.