TRUST: src/Kernel/Geometrie/Triangle.h File Reference
src/Kernel/Geometrie/Triangle.h File Reference
#include <Elem_geom_base.h>
#include <DoubleTab.h>
Classes
class Triangle
Classe Triangle
Cette classe represente l'element geometrique Triangle.
Un triangle a 3 faces, 3 sommets et un seul type de face ayant
2 sommets par face.
Functions
double aire_triangle (const DoubleTab &pos)
Function Documentation
double aire_triangle (const DoubleTab & pos) [inline]
Definition at line 68 of file Triangle.h.
References dabs(), and Objet_U::dimension.
Referenced by Polygone::calculer_centres_gravite(), Polygone::calculer_un_centre_gravite(), Triangle::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), and Polygone::calculer_volumes().
{
  double x0 = pos(0,0);
  double y0 = pos(0,1);
  double x1 = pos(1,0);
  double y1 = pos(1,1);
  double x2 = pos(2,0);
  double y2 = pos(2,1);
  double dz = (x1-x0)*(y2-y0) - (x2-x0)*(y1-y0);
  if (Objet_U::dimension==2)
    return 0.5 * dabs(dz);
  else
    {
      double z0 = pos(0,2);
      double z1 = pos(1,2);
      double z2 = pos(2,2);
      double dx = (y1-y0)*(z2-z0) - (y2-y0)*(z1-z0);
      double dy = (z1-z0)*(x2-x0) - (x1-x0)*(z2-z0);
      return 0.5 * sqrt(dx*dx+dy*dy+dz*dz);
    }
}