TRUST: src/Kernel/Math/Matrices/Trier.cpp File Reference
Trier.cpp File Reference
#include <TRUSTVect.h>
#include <Trier.h>
Functions
void QuickSort (const DoubleVect &a, int g, int d, ArrOfInt &c)
void trier_abs (const DoubleVect &a, ArrOfInt &c)
void trier (const DoubleVect &a, ArrOfInt &c)
void essai ()
Function Documentation
essai()
void essai ()
Definition at line 73 of file Trier.cpp.
{
  DoubleVect a(5);
  ArrOfInt c(5);
  int i;
  a[0]=-10.1;
  a[1]=8.3;
  a[2]=7.31;
  a[3]=7.3;
  a[4]=7.1;
  Cerr << "a before selecting "  << finl;
  for (i=0; i<5; i++) Cerr << a[i] << " ";
  Cerr << finl;
  trier (a,c);
  Cerr << "a after selecting " << finl;
  for ( i=0; i<5; i++) Cerr << a[c[i]] << " ";
  Cerr << finl;
  trier_abs (a,c);
  Cerr << "a after selecting abs " << finl;
  for ( i=0; i<5; i++) Cerr << a[c[i]] << " ";
  Cerr << finl;
}
References Cerr, finl, trier(), and trier_abs().
Referenced by Zone_PolyMAC_P0::fgrad().
QuickSort()
void QuickSort (const DoubleVect & a, int g, int d, ArrOfInt & c)
Definition at line 19 of file Trier.cpp.
{
  int t,i,j;
  double v;
  if (g < d)
    {
      if(a[c[g]]>a[c[d]])
        {
          t=c[g];
          c[g]=c[d];
          c[d]=t;
        }
      v = a[c[d]];
      i = g-1;
      j = d;
      do
        {
          do i++;
          while (a[c[i]] < v);
          do j--;
          while (a[c[j]] > v);
          t = c[i];
          c[i] = c[j];
          c[j] = t;
        }
      while (j > i);
      c[j] = c[i];
      c[i] = c[d];
      c[d] = t;
      QuickSort (a, g, i-1,c);
      QuickSort (a, i+1, d,c);
    }
}
References QuickSort().
Referenced by QuickSort(), trier(), and trier_abs().
trier()
void trier (const DoubleVect & a, ArrOfInt & c)
Definition at line 65 of file Trier.cpp.
{
  c.resize_array(a.size_array());
  int i;
  for (i=0; i<c.size_array(); i++) c[i]=i;
  QuickSort(a, 0, a.size_array()-1, c);
}
References QuickSort(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by essai().
trier_abs()
void trier_abs (const DoubleVect & a, ArrOfInt & c)
Definition at line 53 of file Trier.cpp.
{
  DoubleVect a2(a.size_array());
  c.resize_array(a.size_array());
  int i;
  for (i=0; i<a2.size_array(); i++) a2[i]=std::fabs(a[i]);
  for ( i=0; i<c.size_array(); i++) c[i]=i;
  QuickSort(a2, 0, a2.size_array()-1, c);
}
References QuickSort(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by essai().