TRUST: src/Kernel/Math/TRUSTArray_tools.tpp File Reference
TRUSTArray_tools.tpp File Reference
Macros
#define TRUSTArray_tools_TPP_included
Functions
template<typename _TYPE_ >
int operator== (const TRUSTArray< _TYPE_ > &v, const TRUSTArray< _TYPE_ > &a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
template<typename _TYPE_ >
int imin_array (const TRUSTArray< _TYPE_ > &dx)
Retourne l'indice du min ou -1 si le tableau est vide.
template<typename _TYPE_ >
int imax_array (const TRUSTArray< _TYPE_ > &dx)
Retourne l'indice du max ou -1 si le tableau est vide.
template<typename _TYPE_ >
_TYPE_ min_array (const TRUSTArray< _TYPE_ > &dx)
Retourne la valeur minimale.
template<typename _TYPE_ >
_TYPE_ max_array (const TRUSTArray< _TYPE_ > &dx)
Retourne la valeur maximale.
static double scalar_abs (double x)
static int scalar_abs (int x)
template<typename _TYPE_ >
_TYPE_ max_abs_array (const TRUSTArray< _TYPE_ > &dx)
Retourne le max des abs(i)
template<typename _TYPE_ >
_TYPE_ min_abs_array (const TRUSTArray< _TYPE_ > &dx)
Retourne le min des abs(i)
template<typename _TYPE_ >
_TYPE_ dotproduct_array (const TRUSTArray< _TYPE_ > &dx, const TRUSTArray< _TYPE_ > &dy)
Produit scalaire de deux "array" (dotproduct_array remplace operator* car le nom indique clairement que l'on fait un produit scalaire non distribue)
template<typename _TYPE_ >
_TYPE_ norme_array (const TRUSTArray< _TYPE_ > &dx)
Calcul de la norme du vecteur dx (fonction blas DNRM2, soit racine carree(somme des dx[i]*dx[i]).
Macro Definition Documentation
TRUSTArray_tools_TPP_included
#define TRUSTArray_tools_TPP_included
Definition at line 17 of file TRUSTArray_tools.tpp.
Function Documentation
dotproduct_array()
template<typename _TYPE_ > _TYPE_ dotproduct_array (const TRUSTArray< _TYPE_ > & dx, const TRUSTArray< _TYPE_ > & dy)
Produit scalaire de deux "array" (dotproduct_array remplace operator* car le nom indique clairement que l'on fait un produit scalaire non distribue)
Definition at line 161 of file TRUSTArray_tools.tpp.
{
  const int size = dx.size_array();
  assert(size == dy.size_array());
  _TYPE_ resultat = 0.;
  if (size > 0)
    {
      integer n = size;
      integer incx = 1;
      resultat = F77NAME(DDOT)(&n, dx.addr(), &incx, dy.addr(), &incx);
    }
  return resultat;
}
References TRUSTArray< _TYPE_ >::addr(), F77NAME, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), dotproduct_array_fois_inverse_quantitee_entrelacee(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), gradient_biconjugue(), Extraire_plan::interpreter_(), norm_vit_lp(), and som_pscal().
imax_array()
template<typename _TYPE_ > int imax_array (const TRUSTArray< _TYPE_ > & dx)
Retourne l'indice du max ou -1 si le tableau est vide.
Definition at line 70 of file TRUSTArray_tools.tpp.
{
  int indice_max = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_max = 0;
      _TYPE_ valeur_max = dx[0];
      for (int i = 1; i < size; i++)
        {
          const _TYPE_ val = dx[i];
          if(val > valeur_max)
            {
              indice_max = i;
              valeur_max = val;
            }
        }
    }
  return indice_max;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), and Domaine::imprimer().
imin_array()
template<typename _TYPE_ > int imin_array (const TRUSTArray< _TYPE_ > & dx)
Retourne l'indice du min ou -1 si le tableau est vide.
Definition at line 48 of file TRUSTArray_tools.tpp.
{
  int indice_min = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_min = 0;
      _TYPE_ valeur_min = dx[0];
      for (int i = 1; i < size; i++)
        {
          const _TYPE_ val = dx[i];
          if(val < valeur_min)
            {
              indice_min = i;
              valeur_min = val;
            }
        }
    }
  return indice_min;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), calcul_longueur_filtre(), Rectify_Mesh::check_cell_enumeration_3D(), check_internal_diagonal_for_tetrahedron(), choose_internal_diagonal_for_tetrahedron(), and Domaine::imprimer().
max_abs_array()
template<typename _TYPE_ > _TYPE_ max_abs_array (const TRUSTArray< _TYPE_ > & dx)
Retourne le max des abs(i)
Definition at line 130 of file TRUSTArray_tools.tpp.
{
  const int size = dx.size_array();
  assert(size > 0);
  _TYPE_ valeur_max = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const _TYPE_ val = scalar_abs(dx[i]);
      if (val > valeur_max) valeur_max = val;
    }
  return valeur_max;
}
References scalar_abs(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Op_VEF_Face::impr(), and Champ_Fonc_MED::readOn().
max_array()
template<typename _TYPE_ > _TYPE_ max_array (const TRUSTArray< _TYPE_ > & dx)
Retourne la valeur maximale.
Definition at line 110 of file TRUSTArray_tools.tpp.
{
  const int size = dx.size_array();
  assert(size > 0);
  _TYPE_ valeur_max = dx[0];
  for (int i = 1; i < size; i++)
    {
      const _TYPE_ val = dx[i];
      if (val > valeur_max) valeur_max = val;
    }
  return valeur_max;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by Op_Dift_VDF_Multi_inco_Elem::alpha_(), Octree_Int::build(), calcul_longueur_filtre(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Reordonner_faces_periodiques::chercher_direction_perio(), Partitionneur_Tranche::chercher_direction_perio(), compute_global_connex_components(), Partitionneur_Partition::construire_partition(), Decouper::ecrire(), ExtrudeParoi::extrude(), DomaineCutter::initialiser(), Zone_VEF_PreP1b::lecture_ok_arete(), Zone_Cl_EF::remplir_type_elem_Cl(), and reverse_send_recv_pe_list().
min_abs_array()
template<typename _TYPE_ > _TYPE_ min_abs_array (const TRUSTArray< _TYPE_ > & dx)
Retourne le min des abs(i)
Definition at line 146 of file TRUSTArray_tools.tpp.
{
  const int size = dx.size_array();
  assert(size > 0);
  _TYPE_ v = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const _TYPE_ val = scalar_abs(dx[i]);
      if (val < v) v = val;
    }
  return v;
}
References scalar_abs(), and TRUSTArray< _TYPE_ >::size_array().
min_array()
template<typename _TYPE_ > _TYPE_ min_array (const TRUSTArray< _TYPE_ > & dx)
Retourne la valeur minimale.
Definition at line 94 of file TRUSTArray_tools.tpp.
{
  const int size = dx.size_array();
  assert(size > 0);
  _TYPE_ valeur_min = dx[0];
  for (int i = 1; i < size; i++)
    {
      const _TYPE_ val = dx[i];
      if (val < valeur_min) valeur_min = val;
    }
  return valeur_min;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by Polyedre::affecte_connectivite_numero_global(), Octree_Int::build(), calcul_longueur_filtre(), Reordonner_faces_periodiques::chercher_direction_perio(), Chimie::completer(), Zone_VEF_PreP1b::construire_ok_arete(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), ExtrudeParoi::extrude(), Champ_implementation_P1::init_from_file(), Sonde::initialiser(), Partitionneur_Tranche::initialiser(), DomaineCutter::initialiser(), Execute_parallel::interpreter(), Zone_VEF_PreP1b::lecture_ok_arete(), Pave::lire_Noeuds(), champ_init_canal_sinal::readOn(), Partitionneur_Tranche::readOn(), Pave::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Zone_Cl_EF::remplir_type_elem_Cl(), Hexaedre::reordonner_elem(), Rectangle::reordonner_elem(), reverse_send_recv_pe_list(), and Zone_VEF_PreP1b::verifie_ok_arete().
norme_array()
template<typename _TYPE_ > _TYPE_ norme_array (const TRUSTArray< _TYPE_ > & dx)
Calcul de la norme du vecteur dx (fonction blas DNRM2, soit racine carree(somme des dx[i]*dx[i]).
Definition at line 178 of file TRUSTArray_tools.tpp.
{
  integer n = dx.size_array();
  _TYPE_ resultat = 0.;
  if (n > 0)
    {
      integer incx = 1;
      resultat = F77NAME(DNRM2)(&n, &dx[0], &incx);
    }
  return resultat;
}
References F77NAME, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), calcul_normal_norme(), calcul_normal_norme2(), Champ_base::calculer_valeurs_som_post(), check_espace_virtuel_vect(), Periodique::completer(), Terme_Source_Canal_perio::completer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), gradient_biconjugue(), Champ_front_recyclage::initialiser(), norm_vit_lp(), Zone_Cl_EF::remplir_type_elem_Cl(), som_pscal(), and Loi_horaire::tester().
operator==()
template<typename _TYPE_ > int operator== (const TRUSTArray< _TYPE_ > & v, const TRUSTArray< _TYPE_ > & a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
Definition at line 22 of file TRUSTArray_tools.tpp.
{
  const int n = v.size_array();
  const int na = a.size_array();
  int resu = 1;
  if (n != na)
    {
      resu = 0;
    }
  else
    {
      const _TYPE_ * vv = v.addr();
      const _TYPE_ * av = a.addr();
      for (int i = 0; i < n; i++)
        {
          if (av[i] != vv[i])
            {
              resu = 0;
              break;
            }
        }
    }
  return resu;
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTArray< _TYPE_ >::size_array().
scalar_abs() [1/2]
static double scalar_abs (double x) inline static
Definition at line 124 of file TRUSTArray_tools.tpp.
{ return std::fabs(x); }
Referenced by max_abs_array(), and min_abs_array().
scalar_abs() [2/2]
static int scalar_abs (int x) inline static
Definition at line 125 of file TRUSTArray_tools.tpp.
{ return abs(x); }