TRUST: src/Kernel/Math/TRUSTVect_tools.tpp File Reference
TRUSTVect_tools.tpp File Reference
Macros
#define TRUSTVect_tools_TPP_included
Enumerations
enum class TYPE_OPERATION_VECT {
IMAX_ , IMIN_ , MAX_ , MIN_ ,
MAX_ABS_ , MIN_ABS_
}
enum class TYPE_OPERATION_VECT_BIS { CARRE_ , SOMME_ }
enum class TYPE_OPERATOR_VECT {
ADD_ , SUB_ , MULT_ , DIV_ ,
EGAL_
}
enum class TYPE_OPERATOR_SINGLE {
ADD_ , SUB_ , MULT_ , DIV_ ,
EGAL_ , NEGATE_ , INV_ , ABS_ ,
RACINE_CARRE_ , CARRE_
}
enum class TYPE_OPERATION_VECT_SPEC { ADD_ , CARRE_ }
enum class TYPE_OPERATION_VECT_SPEC_GENERIC { MUL_ , DIV_ }
Functions
template<typename _TYPE_ >
int operator== (const TRUSTVect< _TYPE_ > &x, const TRUSTVect< _TYPE_ > &y)
renvoie 1 si meme strucuture parallele et egalite au sens TRUSTArray (y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
template<typename _TYPE_ >
int operator!= (const TRUSTVect< _TYPE_ > &x, const TRUSTVect< _TYPE_ > &y)
template<typename _TYPE_ >
void invalidate_data (TRUSTVect< _TYPE_ > &resu, Mp_vect_options opt)
double neutral_value_double_ (const bool IS_MAX)
int neutral_value_int_ (const bool IS_MAX)
template<typename _TYPE_ , TYPE_OPERATION_VECT _TYPE_OP_>
_TYPE_ neutral_value ()
template<typename _TYPE_ , typename _TYPE_RETURN_ , TYPE_OPERATION_VECT _TYPE_OP_>
_TYPE_RETURN_ local_extrema_vect_generic (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt)
template<typename _TYPE_ >
int local_imax_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
int local_imin_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_max_vect_ (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_max_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_min_vect_ (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_min_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_max_vect_ (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_max_vect (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_min_vect_ (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_min_vect (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_somme_vect (const TRUSTVect< _TYPE_ > &vx)
template<typename _TYPE_ >
_TYPE_ local_max_abs_vect_ (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_max_abs_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_min_abs_vect_ (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_min_abs_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_max_abs_vect_ (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_max_abs_vect (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_min_abs_vect_ (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_min_abs_vect (const TRUSTVect< _TYPE_ > &x, Mp_vect_options opt=VECT_REAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ local_prodscal (const TRUSTVect< _TYPE_ > &vx, const TRUSTVect< _TYPE_ > &vy, Mp_vect_options opt=VECT_SEQUENTIAL_ITEMS)
template<typename _TYPE_ , TYPE_OPERATION_VECT_BIS _TYPE_OP_>
_TYPE_ local_operations_vect_bis_generic (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt)
template<typename _TYPE_ >
_TYPE_ local_carre_norme_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_SEQUENTIAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_carre_norme_vect (const TRUSTVect< _TYPE_ > &vx)
template<typename _TYPE_ >
_TYPE_ local_somme_vect (const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_SEQUENTIAL_ITEMS)
template<typename _TYPE_ >
_TYPE_ mp_prodscal (const TRUSTVect< _TYPE_ > &x, const TRUSTVect< _TYPE_ > &y)
int mp_norme_vect (const TRUSTVect< int > &vx)=delete
forbidden
double mp_norme_vect (const TRUSTVect< double > &vx)
template<typename _TYPE_ >
_TYPE_ mp_norme_vect_ (const TRUSTVect< _TYPE_ > &vx)
int mp_moyenne_vect (const TRUSTVect< int > &x)=delete
forbidden
double mp_moyenne_vect (const TRUSTVect< double > &x)
void error_divide (const char *nom_funct)
template<typename _TYPE_ , TYPE_OPERATOR_VECT _TYPE_OP_>
void operator_vect_vect_generic (TRUSTVect< _TYPE_ > &resu, const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt)
template<typename _TYPE_ >
void operator_add (TRUSTVect< _TYPE_ > &resu, const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_sub (TRUSTVect< _TYPE_ > &resu, const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_multiply (TRUSTVect< _TYPE_ > &resu, const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_divide (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden
void operator_divide (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_egal (TRUSTVect< _TYPE_ > &resu, const TRUSTVect< _TYPE_ > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ , TYPE_OPERATOR_SINGLE _TYPE_OP_>
void operator_vect_single_generic (TRUSTVect< _TYPE_ > &resu, const _TYPE_ x, Mp_vect_options opt)
template<typename _TYPE_ >
void operator_add (TRUSTVect< _TYPE_ > &resu, const _TYPE_ x, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_sub (TRUSTVect< _TYPE_ > &resu, const _TYPE_ x, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ , typename _SCALAR_TYPE_ >
std::enable_if< std::is_convertible< _SCALAR_TYPE_, _TYPE_ >::value >::type operator_multiply (TRUSTVect< _TYPE_ > &resu, const _SCALAR_TYPE_ x, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_divide (TRUSTVect< int > &resu, const int x, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden (avant c'etait possible ... a voir si besoin)
void operator_divide (TRUSTVect< double > &resu, const double x, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_egal (TRUSTVect< _TYPE_ > &resu, _TYPE_ x, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_negate (TRUSTVect< _TYPE_ > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void operator_inverse (TRUSTVect< int > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden
void operator_inverse (TRUSTVect< double > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void operator_abs (TRUSTVect< _TYPE_ > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree (TRUSTVect< int > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden
void racine_carree (TRUSTVect< double > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree_ (TRUSTVect< int > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden
void racine_carree_ (TRUSTVect< double > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void carre (TRUSTVect< _TYPE_ > &resu, Mp_vect_options opt=VECT_ALL_ITEMS)
template<typename _TYPE_ >
void carre_ (TRUSTVect< _TYPE_ > &resu, Mp_vect_options opt)
template<TYPE_OPERATION_VECT_SPEC _TYPE_OP_>
void ajoute_operation_speciale_generic (TRUSTVect< int > &resu, int alpha, const TRUSTVect< int > &vx, Mp_vect_options opt)=delete
forbidden ... ajoute si besoin
template<TYPE_OPERATION_VECT_SPEC _TYPE_OP_>
void ajoute_operation_speciale_generic (TRUSTVect< double > &resu, double alpha, const TRUSTVect< double > &vx, Mp_vect_options opt)
void ajoute_alpha_v (TRUSTVect< int > &resu, int alpha, const TRUSTVect< int > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)=delete
forbidden ... ajoute si besoin
void ajoute_alpha_v (TRUSTVect< double > &resu, double alpha, const TRUSTVect< double > &vx, Mp_vect_options opt=VECT_REAL_ITEMS)
void ajoute_carre (TRUSTVect< int > &resu, int alpha, const TRUSTVect< int > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... ajoute si besoin
void ajoute_carre (TRUSTVect< double > &resu, double alpha, const TRUSTVect< double > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute_carre_ (TRUSTVect< int > &resu, int alpha, const TRUSTVect< int > &vx, Mp_vect_options opt)=delete
forbidden ... ajoute si besoin
void ajoute_carre_ (TRUSTVect< double > &resu, double alpha, const TRUSTVect< double > &vx, Mp_vect_options opt)
void ajoute_produit_scalaire (TRUSTVect< int > &resu, int alpha, const TRUSTVect< int > &vx, const TRUSTVect< int > &vy, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... ajoute si besoin
void ajoute_produit_scalaire (TRUSTVect< double > &resu, double alpha, const TRUSTVect< double > &vx, const TRUSTVect< double > &vy, Mp_vect_options opt=VECT_ALL_ITEMS)
template<TYPE_OPERATION_VECT_SPEC_GENERIC _TYPE_OP_>
void operation_speciale_tres_generic (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt)=delete
forbidden !!
template<TYPE_OPERATION_VECT_SPEC_GENERIC _TYPE_OP_>
void operation_speciale_tres_generic (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt)
void tab_multiply_any_shape_ (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt)=delete
forbidden
void tab_multiply_any_shape_ (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt)
void tab_divide_any_shape_ (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt)=delete
forbidden
void tab_divide_any_shape_ (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt)
void tab_multiply_any_shape (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void tab_multiply_any_shape (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden
void tab_divide_any_shape (TRUSTVect< double > &resu, const TRUSTVect< double > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)
void tab_divide_any_shape (TRUSTVect< int > &resu, const TRUSTVect< int > &vx, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden FIN code pour operations speciales ==================================================================================================================================
Macro Definition Documentation
TRUSTVect_tools_TPP_included
#define TRUSTVect_tools_TPP_included
Definition at line 17 of file TRUSTVect_tools.tpp.
Enumeration Type Documentation
TYPE_OPERATION_VECT
enum class TYPE_OPERATION_VECT strong
Enumerator
IMAX_
IMIN_
MAX_
MIN_
MAX_ABS_
MIN_ABS_
Definition at line 74 of file TRUSTVect_tools.tpp.
{ IMAX_ , IMIN_ , MAX_ , MIN_ , MAX_ABS_ , MIN_ABS_ };
TYPE_OPERATION_VECT_BIS
enum class TYPE_OPERATION_VECT_BIS strong
Enumerator
CARRE_
SOMME_
Definition at line 350 of file TRUSTVect_tools.tpp.
{ CARRE_ , SOMME_ };
TYPE_OPERATION_VECT_SPEC
enum class TYPE_OPERATION_VECT_SPEC strong
Enumerator
ADD_
CARRE_
Definition at line 737 of file TRUSTVect_tools.tpp.
{ ADD_ , CARRE_ };
TYPE_OPERATION_VECT_SPEC_GENERIC
enum class TYPE_OPERATION_VECT_SPEC_GENERIC strong
Enumerator
MUL_
DIV_
Definition at line 888 of file TRUSTVect_tools.tpp.
{ MUL_ , DIV_ };
TYPE_OPERATOR_SINGLE
enum class TYPE_OPERATOR_SINGLE strong
Enumerator
ADD_
SUB_
MULT_
DIV_
EGAL_
NEGATE_
INV_
ABS_
RACINE_CARRE_
CARRE_
Definition at line 577 of file TRUSTVect_tools.tpp.
{ ADD_ , SUB_ , MULT_ , DIV_ , EGAL_ , NEGATE_ , INV_ , ABS_ , RACINE_CARRE_ , CARRE_ };
TYPE_OPERATOR_VECT
enum class TYPE_OPERATOR_VECT strong
Enumerator
ADD_
SUB_
MULT_
DIV_
EGAL_
Definition at line 467 of file TRUSTVect_tools.tpp.
{ ADD_ , SUB_ , MULT_ , DIV_ , EGAL_ };
Function Documentation
ajoute_alpha_v() [1/2]
void ajoute_alpha_v (TRUSTVect< double > & resu, double alpha, const TRUSTVect< double > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 807 of file TRUSTVect_tools.tpp.
{
  ajoute_operation_speciale_generic<TYPE_OPERATION_VECT_SPEC::ADD_>(resu,alpha,vx,opt);
}
ajoute_alpha_v() [2/2]
void ajoute_alpha_v (TRUSTVect< int > & resu, int alpha, const TRUSTVect< int > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline delete
forbidden ... ajoute si besoin
Referenced by TRUSTVect< _TYPE_ >::ajoute(), TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), and Solv_GCP::resoudre_().
ajoute_carre() [1/2]
void ajoute_carre (TRUSTVect< double > & resu, double alpha, const TRUSTVect< double > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 814 of file TRUSTVect_tools.tpp.
{
  ajoute_operation_speciale_generic<TYPE_OPERATION_VECT_SPEC::CARRE_>(resu,alpha,vx,opt);
}
ajoute_carre() [2/2]
void ajoute_carre (TRUSTVect< int > & resu, int alpha, const TRUSTVect< int > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden ... ajoute si besoin
Referenced by ajoute_carre_().
ajoute_carre_() [1/2]
void ajoute_carre_ (TRUSTVect< double > & resu, double alpha, const TRUSTVect< double > & vx, Mp_vect_options opt) inline
Definition at line 821 of file TRUSTVect_tools.tpp.
{
  ajoute_carre(resu,alpha,vx,opt);
}
References ajoute_carre().
ajoute_carre_() [2/2]
void ajoute_carre_ (TRUSTVect< int > & resu, int alpha, const TRUSTVect< int > & vx, Mp_vect_options opt) inline delete
forbidden ... ajoute si besoin
Referenced by TRUSTVect< _TYPE_ >::ajoute_carre().
ajoute_operation_speciale_generic() [1/2]
template<TYPE_OPERATION_VECT_SPEC _TYPE_OP_> void ajoute_operation_speciale_generic (TRUSTVect< double > & resu, double alpha, const TRUSTVect< double > & vx, Mp_vect_options opt) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 743 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_ADD = (_TYPE_OP_ == TYPE_OPERATION_VECT_SPEC::ADD_), IS_CARRE = (_TYPE_OP_ == TYPE_OPERATION_VECT_SPEC::CARRE_);
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<double>& master_vect = resu;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return;
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double *resu_ptr = resu_base + begin_bloc;
      const double *x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          double& p_resu = *(resu_ptr++);
          if (IS_ADD) p_resu += alpha * x;
          if (IS_CARRE) p_resu += alpha * x * x;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu, opt);
#endif
  return;
}
References ADD_, TRUSTArray< _TYPE_ >::addr(), CARRE_, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), invalidate_data(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
ajoute_operation_speciale_generic() [2/2]
template<TYPE_OPERATION_VECT_SPEC _TYPE_OP_> void ajoute_operation_speciale_generic (TRUSTVect< int > & resu, int alpha, const TRUSTVect< int > & vx, Mp_vect_options opt) inline delete
forbidden ... ajoute si besoin
ajoute_produit_scalaire() [1/2]
void ajoute_produit_scalaire (TRUSTVect< double > & resu, double alpha, const TRUSTVect< double > & vx, const TRUSTVect< double > & vy, Mp_vect_options opt = VECT_ALL_ITEMS) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 828 of file TRUSTVect_tools.tpp.
{
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<double>& master_vect = resu;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size && vy.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot && vy.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md && vy.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return;
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  const double *y_base = vy.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double *resu_ptr = resu_base + begin_bloc;
      const double *x_ptr = x_base + begin_bloc;
      const double *y_ptr = y_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
          const double y = *(y_ptr++);
          double& p_resu = *(resu_ptr++);
          p_resu += alpha * x * y;
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu, opt);
#endif
  return;
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), invalidate_data(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
ajoute_produit_scalaire() [2/2]
void ajoute_produit_scalaire (TRUSTVect< int > & resu, int alpha, const TRUSTVect< int > & vx, const TRUSTVect< int > & vy, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden ... ajoute si besoin
carre()
template<typename _TYPE_ > void carre (TRUSTVect< _TYPE_ > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 721 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::CARRE_>(resu,0. /* inutile */,opt);
}
Referenced by carre_().
carre_()
template<typename _TYPE_ > void carre_ (TRUSTVect< _TYPE_ > & resu, Mp_vect_options opt) inline
Definition at line 727 of file TRUSTVect_tools.tpp.
{
  carre(resu,opt);
}
References carre().
Referenced by TRUSTVect< _TYPE_ >::carre().
error_divide()
void error_divide (const char * nom_funct) inline
Definition at line 469 of file TRUSTVect_tools.tpp.
{
  Cerr << "What ??? Divide by 0 in " << nom_funct << " operator_divide() !!" << finl;
  throw;
}
References Cerr, and finl.
Referenced by operation_speciale_tres_generic(), operator_vect_single_generic(), operator_vect_vect_generic(), and tab_divide_any_shape().
invalidate_data()
template<typename _TYPE_ > void invalidate_data (TRUSTVect< _TYPE_ > & resu, Mp_vect_options opt) inline
< no invalid values
< process data until beginning of next bloc, or end of array
< Process until end of vector
Definition at line 46 of file TRUSTVect_tools.tpp.
{
  _TYPE_ invalid = (std::is_same<_TYPE_,double>::value) ? -987654.321 : INT_MAX;
  const MD_Vector& md = resu.get_md_vector();
  const int line_size = resu.line_size();
  if (opt == VECT_ALL_ITEMS || (!md.non_nul())) return; //!< no invalid values
  assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
  const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
  const int blocs_size = items_blocs.size_array();
  int i = 0;
  for (int blocs_idx = 0; blocs_idx < blocs_size; blocs_idx += 2) //!< process data until beginning of next bloc, or end of array
    {
      const int bloc_end = line_size * items_blocs[blocs_idx];
      _TYPE_ *ptr = resu.addr() + i;
      for (; i < bloc_end; i++) *(ptr++) = invalid;
      i = items_blocs[blocs_idx+1] * line_size;
    }
  const int bloc_end = resu.size_array(); //!< Process until end of vector
  _TYPE_ *ptr = resu.addr() + i;
  for (; i < bloc_end; i++) *(ptr++) = invalid;
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by ajoute_operation_speciale_generic(), ajoute_produit_scalaire(), operation_speciale_tres_generic(), operator_vect_single_generic(), and operator_vect_vect_generic().
local_carre_norme_vect()
template<typename _TYPE_ > _TYPE_ local_carre_norme_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_SEQUENTIAL_ITEMS) inline
Definition at line 410 of file TRUSTVect_tools.tpp.
{
  return local_operations_vect_bis_generic<_TYPE_,TYPE_OPERATION_VECT_BIS::CARRE_>(vx,opt);
}
Referenced by mp_carre_norme_vect(), and Solv_GCP::resoudre_().
local_extrema_vect_generic()
template<typename _TYPE_ , typename _TYPE_RETURN_ , TYPE_OPERATION_VECT _TYPE_OP_> _TYPE_RETURN_ local_extrema_vect_generic (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt) inline
< TYPE et pas TYPE_RETURN desole ...
< seulement pour IMAX_ et IMIN_
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 101 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_IMAX = (_TYPE_OP_ == TYPE_OPERATION_VECT::IMAX_), IS_IMIN = (_TYPE_OP_ == TYPE_OPERATION_VECT::IMIN_), IS_MAX = (_TYPE_OP_ == TYPE_OPERATION_VECT::MAX_),
                        IS_MIN = (_TYPE_OP_ == TYPE_OPERATION_VECT::MIN_), IS_MAX_ABS = (_TYPE_OP_ == TYPE_OPERATION_VECT::MAX_ABS_), IS_MIN_ABS = (_TYPE_OP_ == TYPE_OPERATION_VECT::MIN_ABS_);
  _TYPE_ min_max_val = neutral_value<_TYPE_,_TYPE_OP_>(); //!< _TYPE_ et pas _TYPE_RETURN_ desole ...
  _TYPE_RETURN_ i_min_max = -1 ; //!< seulement pour IMAX_ et IMIN_
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<_TYPE_>& master_vect = vx;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return (IS_IMAX || IS_IMIN) ? i_min_max : min_max_val;
  const _TYPE_ *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const _TYPE_ *x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const _TYPE_ x = *x_ptr;
          if ((IS_IMAX && x > min_max_val) || (IS_IMIN && x < min_max_val))
            {
              i_min_max = x_ptr - x_base;
              min_max_val = x;
            }
          if ((IS_MAX && x > min_max_val) || (IS_MIN && x < min_max_val)) min_max_val = x;
          if (IS_MAX_ABS || IS_MIN_ABS)
            {
              _TYPE_ xx;
              xx = std::is_same<_TYPE_, double>::value ? std::fabs(x) : std::abs(x);
              if ((IS_MAX_ABS && xx > min_max_val) || (IS_MIN_ABS && xx < min_max_val)) min_max_val = xx;
            }
          x_ptr++;
        }
    }
  return (IS_IMAX || IS_IMIN) ? i_min_max : min_max_val;
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), IMAX_, IMIN_, TRUSTVect< _TYPE_ >::line_size(), MAX_, MAX_ABS_, MIN_, MIN_ABS_, MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), and local_min_vect().
local_imax_vect()
template<typename _TYPE_ > int local_imax_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 172 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,int,TYPE_OPERATION_VECT::IMAX_>(vx,opt);
}
local_imin_vect()
template<typename _TYPE_ > int local_imin_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 178 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,int,TYPE_OPERATION_VECT::IMIN_>(vx,opt);
}
local_max_abs_vect()
template<typename _TYPE_ > _TYPE_ local_max_abs_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 250 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,_TYPE_ /* return type */,TYPE_OPERATION_VECT::MAX_ABS_>(vx, opt);
}
References local_extrema_vect_generic(), and MAX_ABS_.
Referenced by local_max_abs_vect_(), mp_max_abs_vect(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Schema_Temps_base::update_critere_statio(), and Debog_Pb::verifier_partie_std().
local_max_abs_vect_()
template<typename _TYPE_ > _TYPE_ local_max_abs_vect_ (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 244 of file TRUSTVect_tools.tpp.
{
  return local_max_abs_vect(vx,opt);
}
References local_max_abs_vect().
Referenced by TRUSTVect< _TYPE_ >::local_max_abs_vect().
local_max_vect()
template<typename _TYPE_ > _TYPE_ local_max_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 190 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,_TYPE_ /* return type */,TYPE_OPERATION_VECT::MAX_>(vx,opt);
}
References local_extrema_vect_generic(), and MAX_.
Referenced by Op_Diff_EF_base::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Op_Diff_VEF_base::calculer_pour_post(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Distanceparoi::interpreter_(), local_max_vect_(), mp_max_vect(), Loi_Etat_Multi_GP_QC::rabot(), and traite_bord().
local_max_vect_()
template<typename _TYPE_ > _TYPE_ local_max_vect_ (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 184 of file TRUSTVect_tools.tpp.
{
  return local_max_vect(vx,opt);
}
References local_max_vect().
Referenced by TRUSTVect< _TYPE_ >::local_max_vect().
local_min_abs_vect()
template<typename _TYPE_ > _TYPE_ local_min_abs_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 262 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,_TYPE_ /* return type */,TYPE_OPERATION_VECT::MIN_ABS_>(vx, opt);
}
References local_extrema_vect_generic(), and MIN_ABS_.
Referenced by local_min_abs_vect_(), modif_par_porosite_si_flag(), and mp_min_abs_vect().
local_min_abs_vect_()
template<typename _TYPE_ > _TYPE_ local_min_abs_vect_ (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 256 of file TRUSTVect_tools.tpp.
{
  return local_min_abs_vect(vx,opt);
}
References local_min_abs_vect().
Referenced by TRUSTVect< _TYPE_ >::local_min_abs_vect().
local_min_vect()
template<typename _TYPE_ > _TYPE_ local_min_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 202 of file TRUSTVect_tools.tpp.
{
  return local_extrema_vect_generic<_TYPE_,_TYPE_ /* return type */,TYPE_OPERATION_VECT::MIN_>(vx, opt);
}
References local_extrema_vect_generic(), and MIN_.
Referenced by Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), local_min_vect_(), mp_min_vect(), Loi_Etat_Multi_GP_QC::rabot(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
local_min_vect_()
template<typename _TYPE_ > _TYPE_ local_min_vect_ (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 196 of file TRUSTVect_tools.tpp.
{
  return local_min_vect(vx,opt);
}
References local_min_vect().
Referenced by TRUSTVect< _TYPE_ >::local_min_vect().
local_operations_vect_bis_generic()
template<typename _TYPE_ , TYPE_OPERATION_VECT_BIS _TYPE_OP_> _TYPE_ local_operations_vect_bis_generic (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 353 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_CARRE = (_TYPE_OP_ == TYPE_OPERATION_VECT_BIS::CARRE_), IS_SOMME = (_TYPE_OP_ == TYPE_OPERATION_VECT_BIS::SOMME_);
  _TYPE_ sum = 0;
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<_TYPE_>& master_vect = vx;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return sum;
  const _TYPE_ *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const _TYPE_ *x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const _TYPE_ x = *x_ptr;
          if (IS_CARRE) sum += x * x;
          if (IS_SOMME) sum += x;
          x_ptr++;
        }
    }
  return sum;
}
References TRUSTArray< _TYPE_ >::addr(), CARRE_, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), SOMME_, MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
local_prodscal()
template<typename _TYPE_ > _TYPE_ local_prodscal (const TRUSTVect< _TYPE_ > & vx, const TRUSTVect< _TYPE_ > & vy, Mp_vect_options opt = VECT_SEQUENTIAL_ITEMS) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 296 of file TRUSTVect_tools.tpp.
{
  _TYPE_ sum = 0;
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<_TYPE_>& master_vect = vx;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size && vy.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot && vy.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md && vy.get_md_vector() == md);
// Determine blocs of data to process, depending on " VECT_SEQUENTIAL_ITEMS"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return sum;
  const _TYPE_ *x_base = vx.addr();
  const _TYPE_ *y_base = vy.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      const _TYPE_ *x_ptr = x_base + begin_bloc;
      const _TYPE_ *y_ptr = y_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const _TYPE_ x = *x_ptr;
          const _TYPE_ y = *(y_ptr++);
          sum += x * y;
          x_ptr++;
        }
    }
  return sum;
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
Referenced by mp_prodscal(), and Solv_GCP::resoudre_().
local_somme_vect()
template<typename _TYPE_ > _TYPE_ local_somme_vect (const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_SEQUENTIAL_ITEMS) inline
Definition at line 422 of file TRUSTVect_tools.tpp.
{
  return local_operations_vect_bis_generic<_TYPE_,TYPE_OPERATION_VECT_BIS::SOMME_>(vx,opt);
}
Referenced by mp_somme_vect().
mp_carre_norme_vect()
template<typename _TYPE_ > _TYPE_ mp_carre_norme_vect (const TRUSTVect< _TYPE_ > & vx) inline
Definition at line 416 of file TRUSTVect_tools.tpp.
{
  return Process::mp_sum(local_carre_norme_vect(vx));
}
References local_carre_norme_vect(), and Process::mp_sum().
Referenced by RRK2::faire_un_pas_de_temps_eqn_base(), Equation_base::Gradient_conjugue_diff_impl(), mp_norme_vect(), and Solv_GCP::resoudre_().
mp_max_abs_vect()
template<typename _TYPE_ > _TYPE_ mp_max_abs_vect (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 274 of file TRUSTVect_tools.tpp.
{
  _TYPE_ s = local_max_abs_vect(x, opt);
  s = Process::mp_max(s);
  return s;
}
References local_max_abs_vect(), and Process::mp_max().
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Zone_EF::calculer_Bij(), Sch_CN_iteratif::convergence(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Navier_Stokes_std::initTimeStep(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Navier_Stokes_std::mettre_a_jour(), mp_max_abs_vect_(), test_imposer_cond_lim(), Operateur_base::tester_contribuer_a_avec(), Schema_Temps_base::update_critere_statio(), and Debog_Pb::verifier_partie_std().
mp_max_abs_vect_()
template<typename _TYPE_ > _TYPE_ mp_max_abs_vect_ (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 268 of file TRUSTVect_tools.tpp.
{
  return mp_max_abs_vect(x, opt);
}
References mp_max_abs_vect().
Referenced by TRUSTVect< _TYPE_ >::mp_max_abs_vect().
mp_max_vect()
template<typename _TYPE_ > _TYPE_ mp_max_vect (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 214 of file TRUSTVect_tools.tpp.
{
  _TYPE_ s = local_max_vect(x, opt);
  s = Process::mp_max(s);
  return s;
}
References local_max_vect(), and Process::mp_max().
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Masse_VDF_base::ajouter_blocs(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Zone_EF::calculer_Bij(), Zone_EF::calculer_volumes_sommets(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Equation_base::imprime_residu(), mp_max_vect_(), Loi_Etat_Multi_GP_QC::rabot(), Operateur_base::tester_contribuer_a_avec(), and verifier().
mp_max_vect_()
template<typename _TYPE_ > _TYPE_ mp_max_vect_ (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 208 of file TRUSTVect_tools.tpp.
{
  return mp_max_vect(x, opt);
}
References mp_max_vect().
Referenced by TRUSTVect< _TYPE_ >::mp_max_vect().
mp_min_abs_vect()
template<typename _TYPE_ > _TYPE_ mp_min_abs_vect (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 288 of file TRUSTVect_tools.tpp.
{
  _TYPE_ s = local_min_abs_vect(x, opt);
  s = Process::mp_min(s);
  return s;
}
References local_min_abs_vect(), and Process::mp_min().
Referenced by mp_min_abs_vect_().
mp_min_abs_vect_()
template<typename _TYPE_ > _TYPE_ mp_min_abs_vect_ (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 282 of file TRUSTVect_tools.tpp.
{
  return mp_min_abs_vect(x, opt);
}
References mp_min_abs_vect().
Referenced by TRUSTVect< _TYPE_ >::mp_min_abs_vect().
mp_min_vect()
template<typename _TYPE_ > _TYPE_ mp_min_vect (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 228 of file TRUSTVect_tools.tpp.
{
  _TYPE_ s = local_min_vect(x, opt);
  s = Process::mp_min(s);
  return s;
}
References local_min_vect(), and Process::mp_min().
Referenced by Zone_EF::calculer_Bij(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Zone_EF::calculer_volumes_sommets(), Op_EF_base::dimensionner(), Equation_base::imprime_residu(), Assembleur_P_PolyMAC::modifier_solution(), mp_min_vect_(), Loi_Etat_Multi_GP_QC::rabot(), and Fluide_base::verifier_coherence_champs().
mp_min_vect_()
template<typename _TYPE_ > _TYPE_ mp_min_vect_ (const TRUSTVect< _TYPE_ > & x, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Definition at line 222 of file TRUSTVect_tools.tpp.
{
  return mp_min_vect(x, opt);
}
References mp_min_vect().
Referenced by TRUSTVect< _TYPE_ >::mp_min_vect().
mp_moyenne_vect() [1/2]
double mp_moyenne_vect (const TRUSTVect< double > & x) inline
< Coding error: mp_moyenne_vect is used on a not distributed TRUSTVect<double> !
Definition at line 450 of file TRUSTVect_tools.tpp.
{
  double s = mp_somme_vect(x), n;
  const MD_Vector& md = x.get_md_vector();
  if (md.non_nul()) n = md.valeur().nb_items_seq_tot() * x.line_size();
  else
    {
      assert(Process::nproc() == 1); //!< Coding error: mp_moyenne_vect is used on a not distributed TRUSTVect<double> !
      n = x.size_totale();
    }
  return s / n;
}
References TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), mp_somme_vect(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), Process::nproc(), TRUSTVect< _TYPE_ >::size_totale(), and MD_Vector::valeur().
mp_moyenne_vect() [2/2]
int mp_moyenne_vect (const TRUSTVect< int > & x) inline delete
forbidden
Referenced by Champ_P1_isoP1Bulle::affecter_(), Terme_Boussinesq_base::check(), corriger(), and Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
mp_norme_vect() [1/2]
double mp_norme_vect (const TRUSTVect< double > & vx) inline
Definition at line 435 of file TRUSTVect_tools.tpp.
{
  double x = mp_carre_norme_vect(vx);
  x = sqrt(x);
  return x;
}
References mp_carre_norme_vect().
mp_norme_vect() [2/2]
int mp_norme_vect (const TRUSTVect< int > & vx) inline delete
forbidden
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Champ_P1NC_implementation::filtrer_H1(), gmres_local(), Matrice_Morse::inverse(), Simple::iterer_eqn(), Simple::iterer_eqs(), Piso::iterer_NS(), mp_norme_vect_(), PrecondSolv::preconditionner_(), PrecondA::preconditionner_(), Navier_Stokes_std::projeter(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), second_membre(), test_un_solveur(), Navier_Stokes_std::uzawa(), and verifier().
mp_norme_vect_()
template<typename _TYPE_ > _TYPE_ mp_norme_vect_ (const TRUSTVect< _TYPE_ > & vx) inline
Definition at line 443 of file TRUSTVect_tools.tpp.
{
  return mp_norme_vect(vx);
}
References mp_norme_vect().
Referenced by TRUSTVect< _TYPE_ >::mp_norme_vect().
mp_prodscal()
template<typename _TYPE_ > _TYPE_ mp_prodscal (const TRUSTVect< _TYPE_ > & x, const TRUSTVect< _TYPE_ > & y) inline
Definition at line 428 of file TRUSTVect_tools.tpp.
{
  return Process::mp_sum(local_prodscal(x, y));
}
References local_prodscal(), and Process::mp_sum().
Referenced by Champ_P1NC::calculer_integrale_volumique(), estim_cond(), RRK2::faire_un_pas_de_temps_eqn_base(), gmres_local(), Equation_base::Gradient_conjugue_diff_impl(), Matrice_Morse::inverse(), PrecondA::preconditionner_(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Navier_Stokes_std::uzawa(), and verifier().
mp_somme_vect()
template<typename _TYPE_ > _TYPE_ mp_somme_vect (const TRUSTVect< _TYPE_ > & vx) inline
Definition at line 236 of file TRUSTVect_tools.tpp.
{
  _TYPE_ x = local_somme_vect(vx);
  _TYPE_ y = Process::mp_sum(x);
  return y;
}
References local_somme_vect(), and Process::mp_sum().
Referenced by Perte_Charge_Singuliere::calculate_Q(), Zone::calculer_mon_centre_de_gravite(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Source_PDF_EF::impr(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Domaine::imprimer(), Zone_Poly_base::init_equiv(), Perte_Charge_Singuliere::lire_surfaces(), mp_moyenne_vect(), Zone_PolyMAC::orthocentrer(), and DP_Impose_PolyMAC_Face::remplir_num_faces().
neutral_value()
template<typename _TYPE_ , TYPE_OPERATION_VECT _TYPE_OP_> _TYPE_ neutral_value () inline
Definition at line 87 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_MAX = ((_TYPE_OP_ == TYPE_OPERATION_VECT::IMAX_) || (_TYPE_OP_ == TYPE_OPERATION_VECT::MAX_)), IS_MAX_ABS = (_TYPE_OP_ == TYPE_OPERATION_VECT::MAX_ABS_);
  if (IS_MAX_ABS) return 0;
  _TYPE_ neutral_val;
  if (std::is_same<_TYPE_, double>::value) neutral_val = neutral_value_double_(IS_MAX);
  else neutral_val = neutral_value_int_(IS_MAX);
  return neutral_val;
}
References IMAX_, MAX_, MAX_ABS_, neutral_value_double_(), and neutral_value_int_().
neutral_value_double_()
double neutral_value_double_ (const bool IS_MAX) inline
Definition at line 76 of file TRUSTVect_tools.tpp.
{
  return IS_MAX ? (-HUGE_VALL) : HUGE_VALL;
}
Referenced by neutral_value().
neutral_value_int_()
int neutral_value_int_ (const bool IS_MAX) inline
Definition at line 81 of file TRUSTVect_tools.tpp.
{
  return IS_MAX ? INT_MIN : INT_MAX;
}
Referenced by neutral_value().
operation_speciale_tres_generic() [1/2]
template<TYPE_OPERATION_VECT_SPEC_GENERIC _TYPE_OP_> void operation_speciale_tres_generic (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 894 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_MUL = (_TYPE_OP_ == TYPE_OPERATION_VECT_SPEC_GENERIC::MUL_), IS_DIV = (_TYPE_OP_ == TYPE_OPERATION_VECT_SPEC_GENERIC::DIV_);
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<double>& master_vect = resu;
  const int line_size = master_vect.line_size(), line_size_vx = vx.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
// Le line_size du vecteur resu doit etre un multiple du line_size du vecteur vx
  assert(line_size > 0 && line_size_vx > 0 && line_size % line_size_vx == 0);
  const int delta_line_size = line_size / line_size_vx;
  assert(vx.size_totale() * delta_line_size == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return;
  double *resu_base = resu.addr();
  const double *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size_vx, end_bloc = (*(bloc_ptr++)) * line_size_vx;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      double *resu_ptr = resu_base + begin_bloc * delta_line_size;
      const double *x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const double x = *x_ptr;
// Any shape: pour chaque item de vx, on a delta_line_size items de resu a traiter
          for (int count2 = delta_line_size; count2; count2--)
            {
              double& p_resu = *(resu_ptr++);
              if (IS_MUL) p_resu *= x;
              if (IS_DIV)
                {
                  if (x == 0) error_divide(__func__);
                  p_resu *= (1. / x);
                }
            }
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu, opt);
#endif
  return;
}
References TRUSTArray< _TYPE_ >::addr(), DIV_, error_divide(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), invalidate_data(), TRUSTVect< _TYPE_ >::line_size(), MUL_, MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
operation_speciale_tres_generic() [2/2]
template<TYPE_OPERATION_VECT_SPEC_GENERIC _TYPE_OP_> void operation_speciale_tres_generic (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt) inline delete
forbidden !!
operator!=()
template<typename _TYPE_ > int operator!= (const TRUSTVect< _TYPE_ > & x, const TRUSTVect< _TYPE_ > & y) inline
Definition at line 35 of file TRUSTVect_tools.tpp.
{
  return !(x == y);
}
operator==()
template<typename _TYPE_ > int operator== (const TRUSTVect< _TYPE_ > & x, const TRUSTVect< _TYPE_ > & y) inline
renvoie 1 si meme strucuture parallele et egalite au sens TRUSTArray (y compris espaces virtuels)
BM: faut-il etre aussi strict, comparer uniquement size() elements ?
Definition at line 26 of file TRUSTVect_tools.tpp.
{
  if (!(x.get_md_vector() == y.get_md_vector())) return 0;
  const TRUSTArray<_TYPE_>& ax = x;
  const TRUSTArray<_TYPE_>& ay = y;
  return ax == ay;
}
References TRUSTVect< _TYPE_ >::get_md_vector().
operator_abs()
template<typename _TYPE_ > void operator_abs (TRUSTVect< _TYPE_ > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 701 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::ABS_>(resu,(_TYPE_)0 /* inutile */,opt);
}
Referenced by TRUSTVect< _TYPE_ >::abs().
operator_add() [1/2]
template<typename _TYPE_ > void operator_add (TRUSTVect< _TYPE_ > & resu, const _TYPE_ x, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 656 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::ADD_>(resu,x,opt);
}
operator_add() [2/2]
template<typename _TYPE_ > void operator_add (TRUSTVect< _TYPE_ > & resu, const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 547 of file TRUSTVect_tools.tpp.
{
  operator_vect_vect_generic<_TYPE_,TYPE_OPERATOR_VECT::ADD_>(resu,vx,opt);
}
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Simpler::iterer_NS(), TRUSTVect< _TYPE_ >::operator+=(), and Navier_Stokes_std::preparer_calcul().
operator_divide() [1/4]
void operator_divide (TRUSTVect< double > & resu, const double x, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 676 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<double,TYPE_OPERATOR_SINGLE::DIV_>(resu,x,opt);
}
operator_divide() [2/4]
void operator_divide (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 566 of file TRUSTVect_tools.tpp.
{
  operator_vect_vect_generic<double,TYPE_OPERATOR_VECT::DIV_>(resu,vx,opt);
}
operator_divide() [3/4]
void operator_divide (TRUSTVect< int > & resu, const int x, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden (avant c'etait possible ... a voir si besoin)
operator_divide() [4/4]
void operator_divide (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden
Referenced by TRUSTVect< _TYPE_ >::operator/=(), and tab_divide_any_shape().
operator_egal() [1/2]
template<typename _TYPE_ > void operator_egal (TRUSTVect< _TYPE_ > & resu, _TYPE_ x, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 682 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::EGAL_>(resu,x,opt);
}
operator_egal() [2/2]
template<typename _TYPE_ > void operator_egal (TRUSTVect< _TYPE_ > & resu, const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 572 of file TRUSTVect_tools.tpp.
{
  operator_vect_vect_generic<_TYPE_,TYPE_OPERATOR_VECT::EGAL_>(resu,vx,opt);
}
Referenced by T_It_VDF_Elem< _TYPE_ >::calculer(), Zone_VEF_PreP1b::discretiser(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Matrice_Morse_Sym::multvect_et_prodscal(), PrecondSolv::preconditionner_(), and SSOR::preconditionner_().
operator_inverse() [1/2]
void operator_inverse (TRUSTVect< double > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 695 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<double,TYPE_OPERATOR_SINGLE::INV_>(resu,0. /* inutile */,opt);
}
operator_inverse() [2/2]
void operator_inverse (TRUSTVect< int > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden
operator_multiply() [1/2]
template<typename _TYPE_ , typename _SCALAR_TYPE_ > std::enable_if< std::is_convertible< _SCALAR_TYPE_, _TYPE_ >::value >::type operator_multiply (TRUSTVect< _TYPE_ > & resu, const _SCALAR_TYPE_ x, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 669 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::MULT_>(resu,x,opt);
}
operator_multiply() [2/2]
template<typename _TYPE_ > void operator_multiply (TRUSTVect< _TYPE_ > & resu, const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 559 of file TRUSTVect_tools.tpp.
{
  operator_vect_vect_generic<_TYPE_,TYPE_OPERATOR_VECT::MULT_>(resu,vx,opt);
}
Referenced by TRUSTVect< _TYPE_ >::operator*=(), PrecondSolv::preconditionner_(), PrecondA::preconditionner_(), tab_divide_any_shape(), and tab_multiply_any_shape().
operator_negate()
template<typename _TYPE_ > void operator_negate (TRUSTVect< _TYPE_ > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 688 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::NEGATE_>(resu,(_TYPE_)0 /* inutile */,opt);
}
Referenced by Operateur_Grad_base::multvect(), Solv_GCP::resoudre_(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
operator_sub() [1/2]
template<typename _TYPE_ > void operator_sub (TRUSTVect< _TYPE_ > & resu, const _TYPE_ x, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 662 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<_TYPE_,TYPE_OPERATOR_SINGLE::SUB_>(resu,x,opt);
}
operator_sub() [2/2]
template<typename _TYPE_ > void operator_sub (TRUSTVect< _TYPE_ > & resu, const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 553 of file TRUSTVect_tools.tpp.
{
  operator_vect_vect_generic<_TYPE_,TYPE_OPERATOR_VECT::SUB_>(resu,vx,opt);
}
Referenced by TRUSTVect< _TYPE_ >::operator-=(), and Solv_GCP::resoudre_().
operator_vect_single_generic()
template<typename _TYPE_ , TYPE_OPERATOR_SINGLE _TYPE_OP_> void operator_vect_single_generic (TRUSTVect< _TYPE_ > & resu, const _TYPE_ x, Mp_vect_options opt) inline
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 580 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_ADD = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::ADD_), IS_SUB = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::SUB_),
                        IS_MULT = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::MULT_), IS_DIV = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::DIV_), IS_EGAL = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::EGAL_),
                        IS_NEGATE = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::NEGATE_), IS_INV = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::INV_), IS_ABS = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::ABS_),
                        IS_RACINE_CARRE = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::RACINE_CARRE_), IS_CARRE = (_TYPE_OP_ == TYPE_OPERATOR_SINGLE::CARRE_);
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<_TYPE_>& master_vect = resu;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul
// Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return;
  _TYPE_ *resu_base = resu.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      _TYPE_ *resu_ptr = resu_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          _TYPE_ &p_resu = *(resu_ptr++);
          if (IS_ADD) p_resu += x;
          if (IS_SUB) p_resu -= x;
          if (IS_MULT) p_resu *= x;
          if (IS_EGAL) p_resu = x;
          if (IS_NEGATE) p_resu = -p_resu;
          if (IS_ABS) p_resu = std::is_same<_TYPE_,double>::value ? std::fabs(p_resu) : std::abs(p_resu);
          if (IS_RACINE_CARRE) p_resu = sqrt(p_resu);
          if (IS_CARRE) p_resu *= p_resu;
          if (IS_DIV)
            {
              if (x == 0.) error_divide(__func__);
              p_resu /= x;
            }
          if (IS_INV)
            {
              if (p_resu == 0.) error_divide(__func__);
              p_resu = 1. / p_resu;
            }
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu, opt);
#endif
  return;
}
References ABS_, ADD_, TRUSTArray< _TYPE_ >::addr(), CARRE_, DIV_, EGAL_, error_divide(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), INV_, invalidate_data(), TRUSTVect< _TYPE_ >::line_size(), MULT_, NEGATE_, MD_Vector::non_nul(), RACINE_CARRE_, TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), SUB_, MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
operator_vect_vect_generic()
template<typename _TYPE_ , TYPE_OPERATOR_VECT _TYPE_OP_> void operator_vect_vect_generic (TRUSTVect< _TYPE_ > & resu, const TRUSTVect< _TYPE_ > & vx, Mp_vect_options opt) inline
< this test is necessary if md is null
< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
Definition at line 476 of file TRUSTVect_tools.tpp.
{
  static constexpr bool IS_ADD = (_TYPE_OP_ == TYPE_OPERATOR_VECT::ADD_), IS_SUB = (_TYPE_OP_ == TYPE_OPERATOR_VECT::SUB_),
                        IS_MULT = (_TYPE_OP_ == TYPE_OPERATOR_VECT::MULT_), IS_DIV = (_TYPE_OP_ == TYPE_OPERATOR_VECT::DIV_), IS_EGAL = (_TYPE_OP_ == TYPE_OPERATOR_VECT::EGAL_);
// Master vect donne la structure de reference, les autres vecteurs doivent avoir la meme structure.
  const TRUSTVect<_TYPE_>& master_vect = resu;
  const int line_size = master_vect.line_size(), vect_size_tot = master_vect.size_totale();
  const MD_Vector& md = master_vect.get_md_vector();
  assert(vx.line_size() == line_size);
  assert(vx.size_totale() == vect_size_tot); //!< this test is necessary if md is null
  assert(vx.get_md_vector() == md);
// Determine blocs of data to process, depending on " opt"
  int nblocs_left = 1, one_bloc[2];
  const int *bloc_ptr;
  if (opt != VECT_ALL_ITEMS && md.non_nul())
    {
      assert(opt == VECT_SEQUENTIAL_ITEMS || opt == VECT_REAL_ITEMS);
      const TRUSTArray<int>& items_blocs = (opt == VECT_SEQUENTIAL_ITEMS) ? md.valeur().get_items_to_sum() : md.valeur().get_items_to_compute();
      assert(items_blocs.size_array() % 2 == 0);
      nblocs_left = items_blocs.size_array() >> 1;
      bloc_ptr = items_blocs.addr();
    }
  else if (vect_size_tot > 0)
    {
// attention, si vect_size_tot est nul, line_size a le droit d'etre nul. Compute all data, in the vector (including virtual data), build a big bloc:
      nblocs_left = 1;
      bloc_ptr = one_bloc;
      one_bloc[0] = 0;
      one_bloc[1] = vect_size_tot / line_size;
    }
  else //!< raccourci pour les tableaux vides (evite le cas particulier line_size == 0)
    return;
  _TYPE_ *resu_base = resu.addr();
  const _TYPE_ *x_base = vx.addr();
  for (; nblocs_left; nblocs_left--)
    {
// Get index of next bloc start:
      const int begin_bloc = (*(bloc_ptr++)) * line_size, end_bloc = (*(bloc_ptr++)) * line_size;
      assert(begin_bloc >= 0 && end_bloc <= vect_size_tot && end_bloc >= begin_bloc);
      _TYPE_ *resu_ptr = resu_base + begin_bloc;
      const _TYPE_ *x_ptr = x_base + begin_bloc;
      int count = end_bloc - begin_bloc;
      for (; count; count--)
        {
          const _TYPE_ x = *x_ptr;
          _TYPE_ &p_resu = *(resu_ptr++);
          if (IS_ADD) p_resu += x;
          if (IS_SUB) p_resu -= x;
          if (IS_MULT) p_resu *= x;
          if (IS_EGAL) p_resu = x;
          if (IS_DIV)
            {
              if (x == 0.) error_divide(__func__);
              p_resu /= x;
            }
          x_ptr++;
        }
    }
// In debug mode, put invalid values where data has not been computed
#ifndef NDEBUG
  invalidate_data(resu, opt);
#endif
  return;
}
References ADD_, TRUSTArray< _TYPE_ >::addr(), DIV_, EGAL_, error_divide(), MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), invalidate_data(), TRUSTVect< _TYPE_ >::line_size(), MULT_, MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), SUB_, MD_Vector::valeur(), VECT_ALL_ITEMS, VECT_REAL_ITEMS, and VECT_SEQUENTIAL_ITEMS.
racine_carree() [1/2]
void racine_carree (TRUSTVect< double > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 708 of file TRUSTVect_tools.tpp.
{
  operator_vect_single_generic<double,TYPE_OPERATOR_SINGLE::RACINE_CARRE_>(resu,0. /* inutile */,opt);
}
racine_carree() [2/2]
void racine_carree (TRUSTVect< int > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden
Referenced by racine_carree_().
racine_carree_() [1/2]
void racine_carree_ (TRUSTVect< double > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Definition at line 715 of file TRUSTVect_tools.tpp.
{
  racine_carree(resu,opt);
}
References racine_carree().
racine_carree_() [2/2]
void racine_carree_ (TRUSTVect< int > & resu, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden
Referenced by TRUSTVect< _TYPE_ >::racine_carree().
tab_divide_any_shape() [1/2]
void tab_divide_any_shape (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
< division par une constante
< division membre a membre
< Cas general
Definition at line 1000 of file TRUSTVect_tools.tpp.
{
  if (vx.size_array() == 1 && !vx.get_md_vector().non_nul()) //!< division par une constante
    {
      if (vx[0] == 0) error_divide(__func__);
      const double x = 1. / vx[0];
      operator_multiply(resu, x, opt);
    }
  else if (vx.line_size() == resu.line_size()) //!< division membre a membre
    operator_divide(resu, vx, opt);
  else //!< Cas general
    tab_divide_any_shape_(resu, vx, opt);
}
References error_divide(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), operator_divide(), operator_multiply(), TRUSTArray< _TYPE_ >::size_array(), and tab_divide_any_shape_().
Referenced by Solveur_Masse_base::appliquer(), Milieu_base::calculer_alpha(), Champ_Q1NC::gradient(), and multiplier_ou_diviser().
tab_divide_any_shape() [2/2]
void tab_divide_any_shape (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden FIN code pour operations speciales ==================================================================================================================================
tab_divide_any_shape_() [1/2]
void tab_divide_any_shape_ (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt) inline
Definition at line 975 of file TRUSTVect_tools.tpp.
{
  operation_speciale_tres_generic<TYPE_OPERATION_VECT_SPEC_GENERIC::DIV_>(resu,vx,opt);
}
tab_divide_any_shape_() [2/2]
void tab_divide_any_shape_ (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt) inline delete
forbidden
Referenced by tab_divide_any_shape().
tab_multiply_any_shape() [1/2]
void tab_multiply_any_shape (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline
< Produit par une constante
< Produit membre a membre
< Cas general
Definition at line 984 of file TRUSTVect_tools.tpp.
{
  if (vx.size_array() == 1 && !vx.get_md_vector().non_nul()) //!< Produit par une constante
    {
      const double x = vx[0];
      operator_multiply(resu, x, opt);
    }
  else if (vx.line_size() == resu.line_size()) //!< Produit membre a membre
    operator_multiply(resu, vx, opt);
  else //!< Cas general
    tab_multiply_any_shape_(resu, vx, opt);
}
References TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), operator_multiply(), TRUSTArray< _TYPE_ >::size_array(), and tab_multiply_any_shape_().
Referenced by Masse_Multiphase::calculer_alpha_rho(), Equation_base::calculer_champ_conserve(), Op_Diff_VEFP1NCP1B_Face::corriger_pour_diffusivite(), modif_par_porosite_si_flag(), multiplier_ou_diviser(), Milieu_base::update_rho_cp(), and Fluide_Dilatable_base::update_rho_cp().
tab_multiply_any_shape() [2/2]
void tab_multiply_any_shape (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt = VECT_ALL_ITEMS) inline delete
forbidden
tab_multiply_any_shape_() [1/2]
void tab_multiply_any_shape_ (TRUSTVect< double > & resu, const TRUSTVect< double > & vx, Mp_vect_options opt) inline
Definition at line 968 of file TRUSTVect_tools.tpp.
{
  operation_speciale_tres_generic<TYPE_OPERATION_VECT_SPEC_GENERIC::MUL_>(resu,vx,opt);
}
tab_multiply_any_shape_() [2/2]
void tab_multiply_any_shape_ (TRUSTVect< int > & resu, const TRUSTVect< int > & vx, Mp_vect_options opt) inline delete
forbidden
Referenced by tab_multiply_any_shape().