TRUST: src/Kernel/Math/TRUSTTab_parts.tpp File Reference
TRUSTTab_parts.tpp File Reference
Macros
#define TRUSTTab_parts_TPP_included
Functions
template<typename _TYPE_ >
void init_parts (TRUSTVect< _TYPE_ > &vect, TRUST_Vector< TRUSTTab, _TYPE_ > &parts, TRUSTTab< _TYPE_ > *dummy_type_ptr)
Macro Definition Documentation
TRUSTTab_parts_TPP_included
#define TRUSTTab_parts_TPP_included
Definition at line 17 of file TRUSTTab_parts.tpp.
Function Documentation
init_parts()
template<typename _TYPE_ > void init_parts (TRUSTVect< _TYPE_ > & vect, TRUST_Vector< TRUSTTab, _TYPE_ > & parts, TRUSTTab< _TYPE_ > * dummy_type_ptr) inline
Definition at line 20 of file TRUSTTab_parts.tpp.
{
  const MD_Vector& md = vect.get_md_vector();
  TRUSTTab<_TYPE_>* Tab_ptr = dynamic_cast<TRUSTTab<_TYPE_>*>(&vect);
  if (! md.non_nul() || !sub_type(MD_Vector_composite, md.valeur()))
    {
// Ce n'est pas un tableau a plusieurs sous-parties, on cree juste une partie qui pointe sur vect.
      parts.dimensionner(1);
      TRUSTTab<_TYPE_>& part = parts[0];
// On preserve le 'shape' du tableau de depart, si c'est un TRUSTTab<_TYPE_>...
      if (Tab_ptr) part.ref(*Tab_ptr);
      else part.ref(vect);
    }
  else
    {
      ArrOfInt shape;
      const int line_size = vect.line_size();
      if (Tab_ptr)
        {
          const TRUSTTab<_TYPE_>& tab = *Tab_ptr;
          const int n = tab.nb_dim();
          shape.resize_array(n);
          for (int i = 0; i < n; i++) shape[i] = tab.dimension_tot(i);
        }
      else
        {
          if (line_size == 1)
            {
              shape.resize_array(1);
              shape[0] = vect.size_totale();
            }
          else
            {
              shape.resize_array(2);
              shape[0] = vect.size_totale() / line_size;
              shape[1] = line_size;
            }
        }
      const MD_Vector_composite& mdata = ref_cast(MD_Vector_composite, md.valeur());
      const int n = mdata.data_.size(), un = 1;
      parts.dimensionner(n);
      for (int i = 0, j; i < n; i++)
        {
          ArrOfInt shape_i;
          if (mdata.shapes_[i] == 0) shape_i = shape; //si mdata.shapes_[i] > 0, alors la sous-partie a une dimension mineure en plus
          else for (shape_i.resize(shape.size_array() + 1), shape_i[1] = mdata.shapes_[i], j = 1; j < shape.size_array(); j++) shape_i[j + 1] = shape[j];
          const int offset = mdata.parts_offsets_[i];
          const MD_Vector& md_part = mdata.data_[i];
          shape_i[0] = md_part.valeur().get_nb_items_tot();
          TRUSTTab<_TYPE_>& part = parts[i];
// Fait pointer la zone de memoire sur le sous-tableau (pour l'instant tableau monodimensionnel)
          part.ref_array(vect, offset * line_size, shape_i[0] * line_size * std::max(mdata.shapes_[i], un));
// Change le "shape" du tableau pour mettre le nombre de lignes et de colonnes
// (nombre total d'items inchange, donc resize autorise)
          part.resize(shape_i);
// Associe le md_vector
          part.set_md_vector(md_part);
        }
    }
}
References MD_Vector_composite::data_, TRUSTTab< _TYPE_ >::dimension_tot(), vect_impl::dimensionner(), TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_base::get_nb_items_tot(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), MD_Vector::non_nul(), MD_Vector_composite::parts_offsets_, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::ref_array(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTTab< _TYPE_ >::set_md_vector(), MD_Vector_composite::shapes_, Vect_MD_Vector::size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), sub_type, and MD_Vector::valeur().