TRUST: src/Kernel/Math/TRUSTLists.h File Reference
TRUSTLists.h File Reference
#include <TRUSTList.h>
Classes
class TRUSTLists< _TYPE_ >
: Un tableau de listes de type IntList
Typedefs
using IntLists = TRUSTLists< int >
using DoubleLists = TRUSTLists< double >
Functions
void throw_ ()
Typedef Documentation
DoubleLists
using DoubleLists = TRUSTLists<double>
Definition at line 89 of file TRUSTLists.h.
IntLists
using IntLists = TRUSTLists<int>
Definition at line 88 of file TRUSTLists.h.
Function Documentation
throw_()
void throw_ () inline
Definition at line 21 of file TRUSTLists.h.
{
  Cerr << "Unable to carry out allocation " << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
Referenced by IntListsListe::dimensionner(), TRUSTLists< _TYPE_ >::dimensionner(), IntListsListe::IntListsListe(), IntListsListe::operator=(), TRUSTLists< _TYPE_ >::operator=(), and TRUSTLists< _TYPE_ >::TRUSTLists().