TRUST: src/Kernel/Math/TRUSTTab_tools.tpp File Reference
TRUSTTab_tools.tpp File Reference
Macros
#define TRUSTTab_tools_TPP_included
Functions
void local_carre_norme_tab (const TRUSTTab< double > &tableau, TRUSTArray< double > &norme_colonne)
void mp_carre_norme_tab (const TRUSTTab< double > &tableau, TRUSTArray< double > &norme_colonne)
void mp_norme_tab (const TRUSTTab< double > &tableau, TRUSTArray< double > &norme_colonne)
void local_max_abs_tab (const TRUSTTab< double > &tableau, TRUSTArray< double > &max_colonne)
void mp_max_abs_tab (const TRUSTTab< double > &tableau, TRUSTArray< double > &max_colonne)
Macro Definition Documentation
TRUSTTab_tools_TPP_included
#define TRUSTTab_tools_TPP_included
Definition at line 17 of file TRUSTTab_tools.tpp.
Function Documentation
local_carre_norme_tab()
void local_carre_norme_tab (const TRUSTTab< double > & tableau, TRUSTArray< double > & norme_colonne) inline
Definition at line 19 of file TRUSTTab_tools.tpp.
{
  const TRUSTArray<int>& blocs = tableau.get_md_vector().valeur().get_items_to_sum();
  const int nblocs = blocs.size_array() >> 1;
  const TRUSTVect<double>& vect = tableau;
  const int lsize = vect.line_size();
  assert(lsize == norme_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc], end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = vect[k++];
              norme_colonne[j] += x*x;
            }
        }
    }
}
References MD_Vector_base::get_items_to_sum(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), TRUSTArray< _TYPE_ >::size_array(), and MD_Vector::valeur().
Referenced by mp_carre_norme_tab().
local_max_abs_tab()
void local_max_abs_tab (const TRUSTTab< double > & tableau, TRUSTArray< double > & max_colonne) inline
Definition at line 53 of file TRUSTTab_tools.tpp.
{
  const TRUSTArray<int>& blocs = tableau.get_md_vector().valeur().get_items_to_compute();
  const int nblocs = blocs.size_array() >> 1;
  const TRUSTVect<double>& vect = tableau;
  const int lsize = vect.line_size();
  for (int j = 0; j < lsize; j++) max_colonne[j] = 0;
  assert(lsize == max_colonne.size_array());
  for (int ibloc = 0; ibloc < nblocs; ibloc++)
    {
      const int begin_bloc = blocs[ibloc], end_bloc = blocs[ibloc+1];
      for (int i = begin_bloc; i < end_bloc; i++)
        {
          int k = i * lsize;
          for (int j = 0; j < lsize; j++)
            {
              const double x = std::fabs(vect[k++]);
              max_colonne[j] = (x > max_colonne[j]) ? x : max_colonne[j];
            }
        }
    }
}
References MD_Vector_base::get_items_to_compute(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), TRUSTArray< _TYPE_ >::size_array(), and MD_Vector::valeur().
Referenced by mp_max_abs_tab().
mp_carre_norme_tab()
void mp_carre_norme_tab (const TRUSTTab< double > & tableau, TRUSTArray< double > & norme_colonne) inline
Definition at line 41 of file TRUSTTab_tools.tpp.
{
  local_carre_norme_tab(tableau, norme_colonne);
  mp_sum_for_each_item(norme_colonne);
}
References local_carre_norme_tab(), and mp_sum_for_each_item().
Referenced by mp_norme_tab().
mp_max_abs_tab()
void mp_max_abs_tab (const TRUSTTab< double > & tableau, TRUSTArray< double > & max_colonne) inline
Definition at line 76 of file TRUSTTab_tools.tpp.
{
  local_max_abs_tab(tableau, max_colonne);
  mp_max_for_each_item(max_colonne);
}
References local_max_abs_tab(), and mp_max_for_each_item().
Referenced by Navier_Stokes_std::initTimeStep(), and Schema_Temps_base::update_critere_statio().
mp_norme_tab()
void mp_norme_tab (const TRUSTTab< double > & tableau, TRUSTArray< double > & norme_colonne) inline
Definition at line 47 of file TRUSTTab_tools.tpp.
{
  mp_carre_norme_tab(tableau,norme_colonne);
  for (int c=0; c<norme_colonne.size_array(); c++) norme_colonne[c] = sqrt(norme_colonne[c]);
}
References mp_carre_norme_tab(), and TRUSTArray< _TYPE_ >::size_array().