TRUST: src/ThHyd/Modele_turbulence_base/Turbulence_paroi_base.h File Reference
src/ThHyd/Modele_turbulence_base/Turbulence_paroi_base.h File Reference
#include <Champ_Inc.h>
#include <Champ_Fonc.h>
#include <Ref_Mod_turb_hyd_base.h>
#include <Champs_compris.h>
#include <Champs_compris_interface.h>
#include <List_Nom.h>
Classes
class Turbulence_paroi_base
Classe Turbulence_paroi_base
Classe de base pour la hierarchie des classes representant les modeles
de calcul des grandeurs turbulentes aux voisinages des parois.
Contient une reference a un modele de turbulence.
Functions
void erreur_non_convergence ()
Function Documentation
void erreur_non_convergence () [inline]
Definition at line 230 of file Turbulence_paroi_base.h.
References Cerr, Process::exit(), finl, Process::me(), and Process::nproc().
{
  Cerr << "TRUST stopped cause in the function calculer_u_plus of wall law." << finl;
  Cerr << "The iterative process of u* did not converge" << finl;
  if (Process::nproc()>1) Cerr << " on the processor" << Process::me();
  else Cerr << ".";
  Cerr << finl << "The hydraulic calculation is may be diverging." << finl;
  Process::exit();
}