TRUST: src/ThHyd/Incompressible/Cond_Lim/Verif_Cl.cpp File Reference
Verif_Cl.cpp File Reference
#include <Verif_Cl.h>
#include <Zone_Cl_dis.h>
#include <Periodique.h>
#include <Dirichlet_paroi_fixe.h>
#include <Dirichlet_paroi_defilante.h>
#include <Entree_fluide_vitesse_imposee.h>
#include <Entree_fluide_vitesse_imposee_libre.h>
#include <Entree_fluide_temperature_imposee.h>
#include <Entree_fluide_T_h_imposee.h>
#include <Entree_fluide_concentration_imposee.h>
#include <Entree_fluide_fraction_massique_imposee.h>
#include <Neumann_paroi.h>
#include <Neumann_paroi_adiabatique.h>
#include <Neumann_paroi_flux_nul.h>
#include <Symetrie.h>
#include <Echange_global_impose.h>
#include <Echange_externe_impose.h>
#include <Neumann_sortie_libre.h>
#include <Scalaire_impose_paroi.h>
#include <Motcle.h>
#include <Frontiere_dis_base.h>
Functions
int tester_compatibilite_hydr_thermique (const Zone_Cl_dis &zone_Cl_hydr, const Zone_Cl_dis &zone_Cl_th)
Teste la compatibilite des conditions aux limites
thermiques et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Thermique
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_temperature_imposee
Entree_fluide_vitesse_imposee_libre => Neumann_sortie_libre
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_adiabatique
=================================> Neumann_paroi
=================================> Echange_global_impose
=================================> Echange_externe_impose
=================================> Scalaire_impose_paroi
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Entree_fluide_temperature_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Symetrie ========================> Neumann_paroi_adiabatique
=================================> Neumann_paroi
=================================> Echange_global_impose
=================================> Echange_externe_impose
=================================> Scalaire_impose_paroi
=================================> Symetrie
--------------------------------------------------------------------—
Periodique ======================> Periodique.
int message_erreur_therm (const Cond_lim &la_cl_hydr, const Cond_lim &la_cl_th, int &num_Cl)
Affiche un message d'erreur pour la fonction precedente.
int tester_compatibilite_hydr_concentration (const Zone_Cl_dis &zone_Cl_hydr, const Zone_Cl_dis &zone_Cl_co)
Teste la compatibilite des conditions aux limites
concentration et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Concentration
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_concentration_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_flux_nul
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Neumann_sortie_libre
=================================> Entree_fluide_concentration_imposee
--------------------------------------------------------------------—
Symetrie ========================> Symetrie
=================================> Neumann_paroi_flux_nul
--------------------------------------------------------------------—
Periodique ======================> Periodique.
int message_erreur_conc (const Cond_lim &la_cl_hydr, const Cond_lim &la_cl_co, int &num_Cl)
Affiche un message d'erreur pour la fonction precedente.
int tester_compatibilite_hydr_fraction_massique (const Zone_Cl_dis &zone_Cl_hydr, const Zone_Cl_dis &zone_Cl_fm)
Teste la compatibilite des conditions aux limites
fraction massqiues et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Fraction massique
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_fraction_massique_imposee
Entree_fluide_vitesse_imposee_libre => Neumann_sortie_libre
Entree_fluide_vitesse_imposee ===> Echange_externe_impose
Entree_fluide_vitesse_imposee ===> Neumann_paroi
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_flux_nul
=================================> Echange_externe_impose
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Entree_fluide_fraction_massique_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Symetrie ========================> Symetrie
=================================> Neumann_paroi_flux_nul
=================================> Neumann_paroi
--------------------------------------------------------------------—
Periodique ======================> Periodique.
int message_erreur_fraction_massique (const Cond_lim &la_cl_hydr, const Cond_lim &la_cl_frac_mass, int &num_Cl)
Affiche un message d'erreur pour la fonction precedente.
Function Documentation
message_erreur_conc()
int message_erreur_conc (const Cond_lim & la_cl_hydr, const Cond_lim & la_cl_co, int & num_Cl)
Affiche un message d'erreur pour la fonction precedente.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 358 of file Verif_Cl.cpp.
{
  Cerr << "The hydraulic and concentration boundary conditions are not consitent on border:" << finl;
  Cerr << "Boundary conditions number " << num_Cl << " \"" << la_cl_co.frontiere_dis().le_nom() << "\" have been assigned to : " << finl;
  Cerr << la_cl_hydr.valeur().que_suis_je() << " and " << la_cl_co.valeur().que_suis_je() << " !! " << finl;
  Process::exit();
  return 1;
}
References Cerr, Process::exit(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), Objet_U::que_suis_je(), and Deriv_Cond_lim_base::valeur().
Referenced by tester_compatibilite_hydr_concentration().
message_erreur_fraction_massique()
int message_erreur_fraction_massique (const Cond_lim & la_cl_hydr, const Cond_lim & la_cl_frac_mass, int & num_Cl)
Affiche un message d'erreur pour la fonction precedente.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 521 of file Verif_Cl.cpp.
{
  Cerr << "The hydraulic and massic fraction boundary conditions are not consitent on border:" << finl;
  Cerr << "Boundary conditions number " << num_Cl << " \"" << la_cl_frac_mass.frontiere_dis().le_nom() << "\" have been assigned to : " << finl;
  Cerr << la_cl_hydr.valeur().que_suis_je() << " and " << la_cl_frac_mass.valeur().que_suis_je() << " !! " << finl;
  Process::exit();
  return 1;
}
References Cerr, Process::exit(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), Objet_U::que_suis_je(), and Deriv_Cond_lim_base::valeur().
Referenced by tester_compatibilite_hydr_fraction_massique().
message_erreur_therm()
int message_erreur_therm (const Cond_lim & la_cl_hydr, const Cond_lim & la_cl_th, int & num_Cl)
Affiche un message d'erreur pour la fonction precedente.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 209 of file Verif_Cl.cpp.
{
  Cerr << "The hydraulic and thermal boundary conditions are not consitent on border:" << finl;
  Cerr << "Boundary conditions number " << num_Cl << " \"" << la_cl_th.frontiere_dis().le_nom() << "\" have been assigned to : " << finl;
  Cerr << la_cl_hydr.valeur().que_suis_je() << " and " << la_cl_th.valeur().que_suis_je() << " !! " << finl;
  Process::exit();
  return 1;
}
References Cerr, Process::exit(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), Objet_U::que_suis_je(), and Deriv_Cond_lim_base::valeur().
Referenced by tester_compatibilite_hydr_thermique().
tester_compatibilite_hydr_concentration()
int tester_compatibilite_hydr_concentration (const Zone_Cl_dis & zone_Cl_hydr, const Zone_Cl_dis & zone_Cl_co)
Teste la compatibilite des conditions aux limites
concentration et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Concentration
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_concentration_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_flux_nul
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Neumann_sortie_libre
=================================> Entree_fluide_concentration_imposee
--------------------------------------------------------------------—
Symetrie ========================> Symetrie
=================================> Neumann_paroi_flux_nul
--------------------------------------------------------------------—
Periodique ======================> Periodique.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 257 of file Verif_Cl.cpp.
{
  int nb_Cl = zone_Cl_hydr.nb_cond_lim();
  if (zone_Cl_co.nb_cond_lim() != nb_Cl)
    {
      Cerr << "The two objects of Zone_Cl_dis type don't have" << finl;
      Cerr << "the same number of boundary conditions." << finl;
      Process::exit();
    }
  for (int num_Cl=0; num_Cl<nb_Cl; num_Cl++)
    {
      const Cond_lim& la_cl_hydr = zone_Cl_hydr.les_conditions_limites(num_Cl);
      const Cond_lim& la_cl_co = zone_Cl_co.les_conditions_limites(num_Cl);
      if (sub_type(Entree_fluide_vitesse_imposee,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Entree_fluide_concentration_imposee,la_cl_co.valeur()))
               || (sub_type(Neumann_sortie_libre,la_cl_co.valeur()))  )
            ;
          else
            {
              message_erreur_conc( la_cl_hydr, la_cl_co, num_Cl);
            }
        }
      else if ( (sub_type(Dirichlet_paroi_fixe,la_cl_hydr.valeur())) ||
                (sub_type(Dirichlet_paroi_defilante,la_cl_hydr.valeur()))  )
        {
          if ((!sub_type(Neumann_paroi_flux_nul,la_cl_co.valeur())) && (!sub_type(Neumann_paroi,la_cl_co.valeur()))
              && (!sub_type(Scalaire_impose_paroi,la_cl_co.valeur())))
            {
              message_erreur_conc( la_cl_hydr, la_cl_co, num_Cl);
            }
        }
      else if (sub_type(Neumann_sortie_libre,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Neumann_sortie_libre,la_cl_co.valeur())) ||
               (sub_type(Entree_fluide_concentration_imposee,la_cl_co.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_conc( la_cl_hydr, la_cl_co, num_Cl);
            }
        }
      else if (sub_type(Symetrie,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Symetrie,la_cl_co.valeur()))
               || (sub_type(Neumann_paroi_flux_nul,la_cl_co.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_conc( la_cl_hydr, la_cl_co, num_Cl);
            }
        }
      else if (sub_type(Periodique,la_cl_hydr.valeur()))
        {
          if (sub_type(Periodique,la_cl_co.valeur()))
            {
              ;
            }
          else
            {
              message_erreur_conc( la_cl_hydr, la_cl_co, num_Cl);
            }
        }
    }
  return 1;
}
References Cerr, Process::exit(), finl, Zone_Cl_dis::les_conditions_limites(), message_erreur_conc(), Zone_Cl_dis::nb_cond_lim(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Pb_Hydraulique_Concentration::verifier(), and Pb_Thermohydraulique_Concentration::verifier().
tester_compatibilite_hydr_fraction_massique()
int tester_compatibilite_hydr_fraction_massique (const Zone_Cl_dis & zone_Cl_hydr, const Zone_Cl_dis & zone_Cl_fm)
Teste la compatibilite des conditions aux limites
fraction massqiues et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Fraction massique
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_fraction_massique_imposee
Entree_fluide_vitesse_imposee_libre => Neumann_sortie_libre
Entree_fluide_vitesse_imposee ===> Echange_externe_impose
Entree_fluide_vitesse_imposee ===> Neumann_paroi
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_flux_nul
=================================> Echange_externe_impose
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Entree_fluide_fraction_massique_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Symetrie ========================> Symetrie
=================================> Neumann_paroi_flux_nul
=================================> Neumann_paroi
--------------------------------------------------------------------—
Periodique ======================> Periodique.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 409 of file Verif_Cl.cpp.
{
  int nb_Cl = zone_Cl_hydr.nb_cond_lim();
  if (zone_Cl_fm.nb_cond_lim() != nb_Cl)
    {
      Cerr << "The two objects of Zone_Cl_dis type don't have" << finl;
      Cerr << "the same number of boundary conditions." << finl;
      Process::exit();
    }
  for (int num_Cl=0; num_Cl<nb_Cl; num_Cl++)
    {
      const Cond_lim& la_cl_hydr = zone_Cl_hydr.les_conditions_limites(num_Cl);
      const Cond_lim& la_cl_fm = zone_Cl_fm.les_conditions_limites(num_Cl);
      if (sub_type(Entree_fluide_vitesse_imposee_libre,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Entree_fluide_fraction_massique_imposee,la_cl_fm.valeur()))
               || (sub_type(Neumann_sortie_libre,la_cl_fm.valeur()))  ||
               (sub_type(Echange_externe_impose,la_cl_fm.valeur())) ||
               (sub_type(Neumann_paroi,la_cl_fm.valeur())) )
            ;
          else
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
      else if (sub_type(Entree_fluide_vitesse_imposee,la_cl_hydr.valeur()))
        {
          if (sub_type(Entree_fluide_fraction_massique_imposee,la_cl_fm.valeur()))
            ;
          else
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
      else if ( (sub_type(Dirichlet_paroi_fixe,la_cl_hydr.valeur())) ||
                (sub_type(Dirichlet_paroi_defilante,la_cl_hydr.valeur()))  )
        {
          if ((!sub_type(Neumann_paroi_flux_nul,la_cl_fm.valeur())) &&
              (!sub_type(Neumann_paroi,la_cl_fm.valeur())) &&
              (!sub_type(Scalaire_impose_paroi,la_cl_fm.valeur())) &&
              (!sub_type(Echange_externe_impose,la_cl_fm.valeur())) )
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
      else if (sub_type(Neumann_sortie_libre,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Entree_fluide_fraction_massique_imposee,la_cl_fm.valeur()))
               || (sub_type(Neumann_sortie_libre,la_cl_fm.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
      else if (sub_type(Symetrie,la_cl_hydr.valeur()))
        {
          if( (sub_type(Symetrie,la_cl_fm.valeur()))
              || (sub_type(Neumann_paroi_flux_nul,la_cl_fm.valeur()))
              || (sub_type(Neumann_paroi,la_cl_fm.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
      else if (sub_type(Periodique,la_cl_hydr.valeur()))
        {
          if (sub_type(Periodique,la_cl_fm.valeur()))
            {
              ;
            }
          else
            {
              message_erreur_fraction_massique( la_cl_hydr, la_cl_fm, num_Cl);
            }
        }
    }
  return 1;
}
References Cerr, Process::exit(), finl, Zone_Cl_dis::les_conditions_limites(), message_erreur_fraction_massique(), Zone_Cl_dis::nb_cond_lim(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Pb_Dilatable_Proto::verifier_impl().
tester_compatibilite_hydr_thermique()
int tester_compatibilite_hydr_thermique (const Zone_Cl_dis & zone_Cl_hydr, const Zone_Cl_dis & zone_Cl_th)
Teste la compatibilite des conditions aux limites
thermiques et hydrauliques.
La liste des compatibilites est la suivante:
--------------------------------------------------------------------—
Hydraulique | Thermique
--------------------------------------------------------------------—
Entree_fluide_vitesse_imposee ===> Entree_fluide_temperature_imposee
Entree_fluide_vitesse_imposee_libre => Neumann_sortie_libre
--------------------------------------------------------------------—
Dirichlet_paroi_fixe |
Dirichlet_paroi_defilante =======> Neumann_paroi_adiabatique
=================================> Neumann_paroi
=================================> Echange_global_impose
=================================> Echange_externe_impose
=================================> Scalaire_impose_paroi
--------------------------------------------------------------------—
Neumann_sortie_libre ============> Entree_fluide_temperature_imposee
=================================> Neumann_sortie_libre
--------------------------------------------------------------------—
Symetrie ========================> Neumann_paroi_adiabatique
=================================> Neumann_paroi
=================================> Echange_global_impose
=================================> Echange_externe_impose
=================================> Scalaire_impose_paroi
=================================> Symetrie
--------------------------------------------------------------------—
Periodique ======================> Periodique.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 85 of file Verif_Cl.cpp.
{
  int nb_Cl = zone_Cl_hydr.nb_cond_lim();
  if (zone_Cl_th.nb_cond_lim() != nb_Cl)
    {
      Cerr << "The two objects of Zone_Cl_dis type don't have" << finl;
      Cerr << "the same number of boundary conditions." << finl;
      Process::exit();
    }
  for (int num_Cl=0; num_Cl<nb_Cl; num_Cl++)
    {
      const Cond_lim& la_cl_hydr = zone_Cl_hydr.les_conditions_limites(num_Cl);
      const Cond_lim& la_cl_th = zone_Cl_th.les_conditions_limites(num_Cl);
      if (sub_type(Entree_fluide_vitesse_imposee_libre,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Entree_fluide_temperature_imposee,la_cl_th.valeur()))
               || (sub_type(Neumann_sortie_libre,la_cl_th.valeur())) )
            ;
          else if ( (sub_type(Entree_fluide_T_h_imposee,la_cl_th.valeur()))
                    || (sub_type(Neumann_sortie_libre,la_cl_th.valeur())) )
            ;
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
      else if (sub_type(Entree_fluide_vitesse_imposee,la_cl_hydr.valeur()))
        {
          if (sub_type(Entree_fluide_temperature_imposee,la_cl_th.valeur()))
            ;
          else if (sub_type(Entree_fluide_T_h_imposee,la_cl_th.valeur()))
            ;
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
      else if ( (sub_type(Dirichlet_paroi_fixe,la_cl_hydr.valeur())) ||
                (sub_type(Dirichlet_paroi_defilante,la_cl_hydr.valeur()))  )
        {
          if ( (sub_type(Neumann_paroi_adiabatique,la_cl_th.valeur()))
               || (sub_type(Neumann_paroi,la_cl_th.valeur()))
               || (sub_type(Echange_global_impose,la_cl_th.valeur()))
               || (sub_type(Echange_externe_impose,la_cl_th.valeur()))
               || (sub_type(Scalaire_impose_paroi,la_cl_th.valeur()))
             )
            {
              ;
            }
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
      else if (sub_type(Neumann_sortie_libre,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Entree_fluide_temperature_imposee,la_cl_th.valeur()))
               || (sub_type(Neumann_sortie_libre,la_cl_th.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
      else if (sub_type(Symetrie,la_cl_hydr.valeur()))
        {
          if ( (sub_type(Neumann_paroi_adiabatique,la_cl_th.valeur()))
               || (sub_type(Neumann_paroi,la_cl_th.valeur()))
               || (sub_type(Echange_global_impose,la_cl_th.valeur()))
               || (sub_type(Echange_externe_impose,la_cl_th.valeur()))
               || (sub_type(Scalaire_impose_paroi,la_cl_th.valeur()))
               || (sub_type(Symetrie,la_cl_th.valeur())) )
            {
              ;
            }
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
      else if (sub_type(Periodique,la_cl_hydr.valeur()))
        {
          if (sub_type(Periodique,la_cl_th.valeur()))
            {
              ;
            }
          else
            {
              message_erreur_therm( la_cl_hydr, la_cl_th, num_Cl);
            }
        }
    }
  return 1;
}
References Cerr, Process::exit(), finl, Zone_Cl_dis::les_conditions_limites(), message_erreur_therm(), Zone_Cl_dis::nb_cond_lim(), sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Pb_Thermohydraulique::verifier(), Pb_Thermohydraulique_Concentration::verifier(), Pb_Multiphase::verifier(), and Pb_Dilatable_Proto::verifier_impl().