TRUST: src/Kernel/Geometrie/Verifier_Qualite_Raffinements.cpp File Reference
Verifier_Qualite_Raffinements.cpp File Reference
#include <Verifier_Qualite_Raffinements.h>
#include <Domaine.h>
#include <TRUSTArray.h>
#include <SFichier.h>
Functions
static void compute_triangle_side_lengths (const ArrOfDouble &x, const ArrOfDouble &y, ArrOfDouble &l)
static void compute_cell_qualities_for_triangle (const Domaine &domain, ArrOfDouble &quality)
static double compute_tetrahedron_diameter (const ArrOfDouble &x, const ArrOfDouble &y, const ArrOfDouble &z)
static double compute_tetrahedron_volume (const ArrOfDouble &x, const ArrOfDouble &y, const ArrOfDouble &z)
static double compute_tetrahedron_surface (const ArrOfDouble &x, const ArrOfDouble &y, const ArrOfDouble &z)
static void compute_cell_qualities_for_tetrahedron (const Domaine &domain, ArrOfDouble &quality)
static void compute_cell_qualities (const Domaine &domain, ArrOfDouble &quality)
Variables
const Type_info * Verifier_Qualite_Raffinementsbases [1] ={ &(Interprete_geometrique_base ::info_obj)}
Function Documentation
compute_cell_qualities()
static void compute_cell_qualities (const Domaine & domain, ArrOfDouble & quality) static
Definition at line 201 of file Verifier_Qualite_Raffinements.cpp.
{
  const Nom& cell_type = domain.zone(0).type_elem().valeur().que_suis_je();
  Motcles understood_keywords(2);
  understood_keywords[0] = "Triangle";
  understood_keywords[1] = "Tetraedre";
  int rank = understood_keywords.search(cell_type);
  switch(rank)
    {
    case 0  :
      compute_cell_qualities_for_triangle(domain,quality);
      break;
    case 1  :
      compute_cell_qualities_for_tetrahedron(domain,quality);
      break;
    default :
      Cerr << "Error in Verifier_Qualite_Raffinements.cpp 'compute_cell_qualities()'" << finl;
      Cerr << "  Unknown cell type : " << cell_type << finl;
      Cerr << "  Verifier_Qualite_Raffinements can only check Triangles and Tetrahedrons" << finl;
      Process::exit();
    }
}
References Cerr, compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), Process::exit(), finl, Objet_U::que_suis_je(), Motcles::search(), Zone::type_elem(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by Verifier_Qualite_Raffinements::verifier_qualite_raffinements().
compute_cell_qualities_for_tetrahedron()
static void compute_cell_qualities_for_tetrahedron (const Domaine & domain, ArrOfDouble & quality) static
Definition at line 169 of file Verifier_Qualite_Raffinements.cpp.
{
  const IntTab&    cells = domain.zone(0).les_elems();
  const DoubleTab& nodes = domain.les_sommets();
  const int nb_cells = cells.dimension(0);
  quality.resize_array(nb_cells);
  ArrOfDouble x(4);
  ArrOfDouble y(4);
  ArrOfDouble z(4);
  double h,s,v;
  for (int cell=0; cell<nb_cells; ++cell)
    {
      for (int i=0; i<4; ++i)
        {
          x[i] = nodes(cells(cell,i),0);
          y[i] = nodes(cells(cell,i),1);
          z[i] = nodes(cells(cell,i),2);
        }
      h = compute_tetrahedron_diameter(x,y,z);
      v = compute_tetrahedron_volume(x,y,z);
      s = compute_tetrahedron_surface(x,y,z);
      quality[cell] = ( (h*s) / v );
    }
}
References compute_tetrahedron_diameter(), compute_tetrahedron_surface(), compute_tetrahedron_volume(), TRUSTTab< _TYPE_ >::dimension(), Zone::les_elems(), Domaine::les_sommets(), TRUSTArray< _TYPE_ >::resize_array(), and Domaine::zone().
Referenced by compute_cell_qualities().
compute_cell_qualities_for_triangle()
static void compute_cell_qualities_for_triangle (const Domaine & domain, ArrOfDouble & quality) static
Definition at line 46 of file Verifier_Qualite_Raffinements.cpp.
{
  const IntTab&    cells = domain.zone(0).les_elems();
  const DoubleTab& nodes = domain.les_sommets();
  const int nb_cells = cells.dimension(0);
  quality.resize_array(nb_cells);
  ArrOfDouble x(3);
  ArrOfDouble y(3);
  ArrOfDouble l(3);
  double p,r,h;
  for (int cell=0; cell<nb_cells; ++cell)
    {
      for (int i=0; i<3; ++i)
        {
          x[i] = nodes(cells(cell,i),0);
          y[i] = nodes(cells(cell,i),1);
        }
      compute_triangle_side_lengths(x,y,l);
      p = l[0]+l[1]+l[2];
      r = sqrt(p*(p-l[0])*(p-l[1])*(p-l[2]))/p;
      h = (l[0] > l[1]) ? ( (l[0]>l[2]) ? l[0] : l[2]) : ( (l[1]>l[2]) ? l[1] : l[2] );
      quality[cell] = ( h / r );
    }
}
References compute_triangle_side_lengths(), TRUSTTab< _TYPE_ >::dimension(), Zone::les_elems(), Domaine::les_sommets(), TRUSTArray< _TYPE_ >::resize_array(), and Domaine::zone().
Referenced by compute_cell_qualities().
compute_tetrahedron_diameter()
static double compute_tetrahedron_diameter (const ArrOfDouble & x, const ArrOfDouble & y, const ArrOfDouble & z) static
Definition at line 80 of file Verifier_Qualite_Raffinements.cpp.
{
  double diameter = 0.;
  double dx,dy,dz,l;
  for (int i=0; i<4; ++i)
    {
      for (int j=i+1; j<4; ++j)
        {
          dx = x[j]-x[i];
          dy = y[j]-y[i];
          dz = z[j]-z[i];
          l = dx*dx + dy*dy + dz*dz;
          diameter = (diameter < l) ? l : diameter;
        }
    }
  return sqrt(diameter);
}
Referenced by compute_cell_qualities_for_tetrahedron().
compute_tetrahedron_surface()
static double compute_tetrahedron_surface (const ArrOfDouble & x, const ArrOfDouble & y, const ArrOfDouble & z) static
Definition at line 115 of file Verifier_Qualite_Raffinements.cpp.
{
  ArrOfDouble u(3);
  ArrOfDouble v(3);
  double surface = 0.;
  u[0] = x[2] - x[1];
  v[0] = x[3] - x[1];
  u[1] = y[2] - y[1];
  v[1] = y[3] - y[1];
  u[2] = z[2] - z[1];
  v[2] = z[3] - z[1];
  surface += 0.5 * sqrt( ( ( (u[1]*v[2]) - (u[2]*v[1]) ) * ( (u[1]*v[2]) - (u[2]*v[1]) ) ) +
                         ( ( (u[2]*v[0]) - (u[0]*v[2]) ) * ( (u[2]*v[0]) - (u[0]*v[2]) ) ) +
                         ( ( (u[0]*v[1]) - (u[1]*v[0]) ) * ( (u[0]*v[1]) - (u[1]*v[0]) ) ) );
  u[0] = x[3] - x[2];
  v[0] = x[0] - x[2];
  u[1] = y[3] - y[2];
  v[1] = y[0] - y[2];
  u[2] = z[3] - z[2];
  v[2] = z[0] - z[2];
  surface += 0.5 * sqrt( ( ( (u[1]*v[2]) - (u[2]*v[1]) ) * ( (u[1]*v[2]) - (u[2]*v[1]) ) ) +
                         ( ( (u[2]*v[0]) - (u[0]*v[2]) ) * ( (u[2]*v[0]) - (u[0]*v[2]) ) ) +
                         ( ( (u[0]*v[1]) - (u[1]*v[0]) ) * ( (u[0]*v[1]) - (u[1]*v[0]) ) ) );
  u[0] = x[0] - x[3];
  v[0] = x[1] - x[3];
  u[1] = y[0] - y[3];
  v[1] = y[1] - y[3];
  u[2] = z[0] - z[3];
  v[2] = z[1] - z[3];
  surface += 0.5 * sqrt( ( ( (u[1]*v[2]) - (u[2]*v[1]) ) * ( (u[1]*v[2]) - (u[2]*v[1]) ) ) +
                         ( ( (u[2]*v[0]) - (u[0]*v[2]) ) * ( (u[2]*v[0]) - (u[0]*v[2]) ) ) +
                         ( ( (u[0]*v[1]) - (u[1]*v[0]) ) * ( (u[0]*v[1]) - (u[1]*v[0]) ) ) );
  u[0] = x[1] - x[0];
  v[0] = x[2] - x[0];
  u[1] = y[1] - y[0];
  v[1] = y[2] - y[0];
  u[2] = z[1] - z[0];
  v[2] = z[2] - z[0];
  surface += 0.5 * sqrt( ( ( (u[1]*v[2]) - (u[2]*v[1]) ) * ( (u[1]*v[2]) - (u[2]*v[1]) ) ) +
                         ( ( (u[2]*v[0]) - (u[0]*v[2]) ) * ( (u[2]*v[0]) - (u[0]*v[2]) ) ) +
                         ( ( (u[0]*v[1]) - (u[1]*v[0]) ) * ( (u[0]*v[1]) - (u[1]*v[0]) ) ) );
  return surface;
}
Referenced by compute_cell_qualities_for_tetrahedron().
compute_tetrahedron_volume()
static double compute_tetrahedron_volume (const ArrOfDouble & x, const ArrOfDouble & y, const ArrOfDouble & z) static
Definition at line 98 of file Verifier_Qualite_Raffinements.cpp.
{
  double volume = (x[1]-x[0]) * (y[2]-y[0]) * (z[3]-z[0]) +
                  (x[2]-x[0]) * (y[3]-y[0]) * (z[1]-z[0]) +
                  (x[3]-x[0]) * (y[1]-y[0]) * (z[2]-z[0]) -
                  (z[1]-z[0]) * (y[2]-y[0]) * (x[3]-x[0]) -
                  (x[2]-x[0]) * (z[3]-z[0]) * (y[1]-y[0]) -
                  (y[3]-y[0]) * (x[1]-x[0]) * (z[2]-z[0]);
// GF est ce le lieu pour faire l'assert....
  if (volume<0.) volume=-volume;
  assert( volume > 0. );
  return (volume / 6.);
}
Referenced by compute_cell_qualities_for_tetrahedron().
compute_triangle_side_lengths()
static void compute_triangle_side_lengths (const ArrOfDouble & x, const ArrOfDouble & y, ArrOfDouble & l) static
Definition at line 35 of file Verifier_Qualite_Raffinements.cpp.
{
  double dx,dy;
  for (int i=0; i<3; ++i)
    {
      dx = x[(i+1)%3] - x[i];
      dy = y[(i+1)%3] - y[i];
      l[i] = sqrt(dx*dx + dy*dy);
    }
}
Referenced by compute_cell_qualities_for_triangle().
Variable Documentation
Verifier_Qualite_Raffinementsbases
const Type_info* Verifier_Qualite_Raffinementsbases[1] ={ &(Interprete_geometrique_base ::info_obj)}
Definition at line 21 of file Verifier_Qualite_Raffinements.cpp.