TRUST: src/PolyMAC/Zones/Zone_PolyMAC.cpp File Reference
Zone_PolyMAC.cpp File Reference
#include <Linear_algebra_tools_impl.h>
#include <Champ_implementation_P1.h>
#include <Connectivite_som_elem.h>
#include <MD_Vector_composite.h>
#include <Zone_Cl_PolyMAC.h>
#include <MD_Vector_tools.h>
#include <Comm_Group_MPI.h>
#include <communications.h>
#include <Poly_geom_base.h>
#include <Matrix_tools.h>
#include <Statistiques.h>
#include <Zone_PolyMAC.h>
#include <unordered_map>
#include <Array_tools.h>
#include <TRUSTLists.h>
#include <PE_Groups.h>
#include <Rectangle.h>
#include <Tetraedre.h>
#include <EFichier.h>
#include <SFichier.h>
#include <Hexaedre.h>
#include <Triangle.h>
#include <Segment.h>
#include <Domaine.h>
#include <Scatter.h>
#include <EChaine.h>
#include <Lapack.h>
#include <unistd.h>
#include <numeric>
#include <cfloat>
#include <vector>
#include <tuple>
#include <cmath>
#include <cfenv>
#include <set>
#include <map>
Functions
void clamp (DoubleTab &m)
Variables
const Type_info * Zone_PolyMACbases [1] ={ &(Zone_Poly_base ::info_obj)}
Function Documentation
clamp()
void clamp (DoubleTab & m) inline
Definition at line 208 of file Zone_PolyMAC.cpp.
{
  for (int i = 0; i < m.dimension(0); i++)
    for (int j = 0; j < m.dimension(1); j++)
      for (int n = 0; n < m.dimension(2); n++)
        if (1e6 * std::abs(m(i, j, n)) < std::abs(m(i, i, n)) + std::abs(m(j, j, n))) m(i, j, n) = 0;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
Variable Documentation
Zone_PolyMACbases
const Type_info* Zone_PolyMACbases[1] ={ &(Zone_Poly_base ::info_obj)}
Definition at line 53 of file Zone_PolyMAC.cpp.