TRUST: src/Kernel/VF/Zones/Zone_Poly_base.cpp File Reference
Zone_Poly_base.cpp File Reference
#include <Linear_algebra_tools_impl.h>
#include <Connectivite_som_elem.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <Comm_Group_MPI.h>
#include <Quadrangle_VEF.h>
#include <communications.h>
#include <Zone_Poly_base.h>
#include <Matrice_Morse.h>
#include <Segment_poly.h>
#include <Statistiques.h>
#include <Hexaedre_VEF.h>
#include <Matrix_tools.h>
#include <unordered_map>
#include <Array_tools.h>
#include <Quadri_poly.h>
#include <Tetra_poly.h>
#include <TRUSTLists.h>
#include <Tetraedre.h>
#include <Rectangle.h>
#include <PE_Groups.h>
#include <Hexa_poly.h>
#include <Tri_poly.h>
#include <Hexaedre.h>
#include <Triangle.h>
#include <EFichier.h>
#include <SFichier.h>
#include <Segment.h>
#include <Domaine.h>
#include <Scatter.h>
#include <EChaine.h>
#include <unistd.h>
#include <Lapack.h>
#include <numeric>
#include <vector>
#include <tuple>
#include <cmath>
#include <set>
#include <map>
#include <medcoupling++.h>
#include <Dirichlet_homogene.h>
#include <Dirichlet_paroi_defilante.h>
#include <Navier.h>
Functions
void disp_dt (const DoubleTab &A)
void disp_da (const ArrOfDouble &A)
void disp_it (const IntTab &A)
void disp_ia (const ArrOfInt &A)
void disp_m (const Matrice_Base &M_in)
void disp_mt (const tabs_t &mvect)
void disp_mm (const std::map< std::string, Matrice_Morse > &mmat)
void disp_mmp (const matrices_t &mmat)
Variables
const Type_info * Zone_Poly_basebases [1] ={ &(Zone_VF ::info_obj)}
Function Documentation
disp_da()
void disp_da (const ArrOfDouble & A)
Definition at line 580 of file Zone_Poly_base.cpp.
{
  int i;
  for (i = 0, fprintf(stderr, "{"); i < A.size_array(); i++)
    fprintf(stderr, "%.10E%s ", A.addr()[i], i + 1 < A.size_array() ? "," : "");
  fprintf(stderr, "}\n");
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTArray< _TYPE_ >::size_array().
disp_dt()
void disp_dt (const DoubleTab & A)
Definition at line 557 of file Zone_Poly_base.cpp.
{
  int i, j, k, l;
  if (A.nb_dim() == 4)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "}},{" : "{"); k < A.dimension(2); k++)
          for (l = 0, fprintf(stderr, k ? "},{" : "{"); l < A.dimension(3); l++)
            fprintf(stderr, "%.10E%s ", A.addr()[A.dimension(3) * (A.dimension(2) * (i * A.dimension(1) + j) + k) + l], l + 1 < A.dimension(3) ? "," : "");
  else if (A.nb_dim() == 3)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "},{" : "{"); k < A.dimension(2); k++)
          fprintf(stderr, "%.10E%s ", A.addr()[A.dimension(2) * (i * A.dimension(1) + j) + k], k + 1 < A.dimension(2) ? "," : "");
  else if (A.nb_dim() == 2)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "},{" : "{{"); j < A.dimension(1); j++)
        fprintf(stderr, "%.10E%s ", A.addr()[i * A.dimension(1) + j], j + 1 < A.dimension(1) ? "," : "");
  else for (i = 0, fprintf(stderr, "{"); i < A.dimension_tot(0); i++)
      fprintf(stderr, "%.10E%s ", A.addr()[i], i + 1 < A.dimension_tot(0) ? "," : "");
  fprintf(stderr, A.nb_dim() == 4 ? "}}}}\n" : A.nb_dim() == 3 ? "}}}\n" : A.nb_dim() == 2 ? "}}\n" : "}\n");
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), and TRUSTTab< _TYPE_ >::nb_dim().
Referenced by disp_m(), and disp_mt().
disp_ia()
void disp_ia (const ArrOfInt & A)
Definition at line 611 of file Zone_Poly_base.cpp.
{
  int i;
  for (i = 0, fprintf(stderr, "{"); i < A.size_array(); i++)
    fprintf(stderr, "%d%s ", (True_int)A.addr()[i], i + 1 < A.size_array() ? "," : "");
  fprintf(stderr, "}\n");
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTArray< _TYPE_ >::size_array().
disp_it()
void disp_it (const IntTab & A)
Definition at line 588 of file Zone_Poly_base.cpp.
{
  int i, j, k, l;
  if (A.nb_dim() == 4)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "}},{" : "{"); k < A.dimension(2); k++)
          for (l = 0, fprintf(stderr, k ? "},{" : "{"); l < A.dimension(3); l++)
            fprintf(stderr, "%d%s ", (True_int)A.addr()[A.dimension(3) * (A.dimension(2) * (i * A.dimension(1) + j) + k) + l], l + 1 < A.dimension(3) ? "," : "");
  else if (A.nb_dim() == 3)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "},{" : "{"); k < A.dimension(2); k++)
          fprintf(stderr, "%d%s ", (True_int)A.addr()[A.dimension(2) * (i * A.dimension(1) + j) + k], k + 1 < A.dimension(2) ? "," : "");
  else if (A.nb_dim() == 2)
    for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "},{" : "{{"); j < A.dimension(1); j++)
        fprintf(stderr, "%d%s ", (True_int)A.addr()[i * A.dimension(1) + j], j + 1 < A.dimension(1) ? "," : "");
  else for (i = 0, fprintf(stderr, "{"); i < A.dimension_tot(0); i++)
      fprintf(stderr, "%d%s ", (True_int)A.addr()[i], i + 1 < A.dimension_tot(0) ? "," : "");
  fprintf(stderr, A.nb_dim() == 4 ? "}}}}\n" : A.nb_dim() == 3 ? "}}}\n" : A.nb_dim() == 2 ? "}}\n" : "}\n");
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), and TRUSTTab< _TYPE_ >::nb_dim().
disp_m()
void disp_m (const Matrice_Base & M_in)
Definition at line 619 of file Zone_Poly_base.cpp.
{
  Matrice_Morse M;
  Matrix_tools::convert_to_morse_matrix(M_in, M);
  DoubleTab A(M.nb_lignes(), M.nb_colonnes());
  for (int i = 0; i < A.dimension(0); i++)
    for (int k = M.get_tab1().addr()[i] - 1; k < M.get_tab1().addr()[i + 1] - 1; k++)
      A(i, M.get_tab2().addr()[k] - 1) = M.get_coeff().addr()[k];
  disp_dt(A);
}
References TRUSTArray< _TYPE_ >::addr(), Matrix_tools::convert_to_morse_matrix(), TRUSTTab< _TYPE_ >::dimension(), disp_dt(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_colonnes(), and Matrice_Morse::nb_lignes().
Referenced by disp_mm(), and disp_mmp().
disp_mm()
void disp_mm (const std::map< std::string, Matrice_Morse > & mmat)
Definition at line 636 of file Zone_Poly_base.cpp.
{
  for (auto &&n_v : mmat)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_m(n_v.second), fprintf(stderr, "\n");
}
References disp_m().
disp_mmp()
void disp_mmp (const matrices_t & mmat)
Definition at line 642 of file Zone_Poly_base.cpp.
{
  for (auto &&n_v : mmat)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_m(*n_v.second), fprintf(stderr, "\n");
}
References disp_m().
disp_mt()
void disp_mt (const tabs_t & mvect)
Definition at line 630 of file Zone_Poly_base.cpp.
{
  for (auto &&n_v : mvect)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_dt(n_v.second), fprintf(stderr, "\n");
}
References disp_dt().
Variable Documentation
Zone_Poly_basebases
const Type_info* Zone_Poly_basebases[1] ={ &(Zone_VF ::info_obj)}
Definition at line 67 of file Zone_Poly_base.cpp.