TRUST: src/VEF/Zones/Zone_Cl_VEF.cpp File Reference
Zone_Cl_VEF.cpp File Reference
#include <Zone_Cl_VEF.h>
#include <Zone_VEF.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Periodique.h>
#include <Symetrie.h>
#include <Dirichlet_paroi_fixe.h>
#include <Dirichlet_paroi_defilante.h>
#include <Dirichlet_entree_fluide.h>
#include <Scalaire_impose_paroi.h>
#include <Neumann_sortie_libre.h>
#include <Champ_P0_VEF.h>
#include <Champ_P1NC.h>
#include <Domaine.h>
#include <Tri_VEF.h>
#include <Tetra_VEF.h>
#include <Quadri_VEF.h>
#include <Hexa_VEF.h>
#include <Hexaedre_VEF.h>
#include <Debog.h>
#include <MD_Vector_tools.h>
#include <Check_espace_virtuel.h>
Functions
int Deux_Puissance (int n)
int trois_puissance (int n)
Variables
const Type_info * Zone_Cl_VEFbases [1] ={ &(Zone_Cl_dis_base ::info_obj)}
Function Documentation
Deux_Puissance()
int Deux_Puissance (int n)
Definition at line 41 of file Zone_Cl_VEF.cpp.
{
  switch(n)
    {
    case 0 :
      return 1;
    case 1 :
      return 2;
    case 2 :
      return 4;
    case 3 :
      return 8;
    default:
      return 8*Deux_Puissance((int)(n-3));
    }
}
References Deux_Puissance().
Referenced by Deux_Puissance(), and Zone_Cl_VEF::remplir_type_elem_Cl().
trois_puissance()
int trois_puissance (int n)
Definition at line 305 of file Zone_Cl_VEF.cpp.
{
  switch(n)
    {
    case 0:
      return 1;
    case 1:
      return 3;
    case 2:
      return 9;
    case 3:
      return 27;
    default :
      return 27*trois_puissance(n-3);
    }
}
References trois_puissance().
Referenced by Zone_Cl_VEF::remplir_type_elem_Cl(), and trois_puissance().
Variable Documentation
Zone_Cl_VEFbases
const Type_info* Zone_Cl_VEFbases[1] ={ &(Zone_Cl_dis_base ::info_obj)}
Definition at line 39 of file Zone_Cl_VEF.cpp.