TRUST: src/P1NCP1B/Zones/Zone_VEF_PreP1b.cpp File Reference
src/P1NCP1B/Zones/Zone_VEF_PreP1b.cpp File Reference
#include <Zone_VEF_PreP1b.h>
#include <Domaine.h>
#include <Scatter.h>
#include <IntLists.h>
#include <Conds_lim.h>
#include <Periodique.h>
#include <Debog.h>
#include <EcrFicPartageBin.h>
#include <EFichierBin.h>
#include <MD_Vector_tools.h>
#include <ArrOfBit.h>
#include <Connectivite_som_elem.h>
#include <Static_Int_Lists.h>
#include <MD_Vector_composite.h>
#include <Check_espace_virtuel.h>
#include <VEFPreP1B.h>
#include <communications.h>
#include <Octree_Double.h>
Functions
static int next (int S, const ArrOfInt &contenu)
void exemple_champ_non_homogene (const Zone_VEF_PreP1b &zone_VEF, DoubleTab &tab)
Variables
const Type_info * Zone_VEF_PreP1bbases [1] = { &(Zone_VEF ::info_obj)}
Function Documentation
void exemple_champ_non_homogene (const Zone_VEF_PreP1b & zone_VEF, DoubleTab & tab)
Definition at line 287 of file Zone_VEF_PreP1b.cpp.
References Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), DoubleVect::echange_espace_virtuel(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Zone::nb_aretes(), Zone::nb_elem(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_tot(), ArrOfDouble::size_array(), Debog::verifier(), Zone_VF::xa(), Zone_VF::xp(), and Zone_dis_base::zone().
Referenced by verifier(), and verifier_complet().
{
  const DoubleTab& xp = zone_VEF.xp();
  const Zone& zone=zone_VEF.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const DoubleTab& xa=zone_VEF.xa();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
// Verification du tableau xa des coordonnees arete
  if (xa.size_array()) Debog::verifier("xa=",xa);
  int nb_elem=zone.nb_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_som=zone.nb_som();
  int nb_som_tot=zone.nb_som_tot();
  int nb_aretes=zone.nb_aretes();
  for (int I=0 ; I<nb_elem; I++)
    {
      tab(I)=(1.1+xp(I,0))*(1.1+2*xp(I,1));
      if (Objet_U::dimension==3) tab(I)*=(1.1+3*xp(I,2));
    }
  for (int I=0; I<nb_som; I++)
    {
      tab(nb_elem_tot+I)=(1.1+coord(I,0))*(1.1+2*coord(I,1));
      if (Objet_U::dimension==3) tab(nb_elem_tot+I)*=(1.1+3*coord(I,2));
// On applique la periodicite:
      tab(nb_elem_tot+I)=tab(nb_elem_tot+zone.domaine().get_renum_som_perio(I));
    }
#ifndef NDEBUG
  const IntVect& ok_arete = zone_VEF.get_ok_arete();
#endif
  for (int I=0; I<nb_aretes; I++)
    {
      tab(nb_elem_tot+nb_som_tot+I)=(1.1+xa(I,0))*(1.1+2*xa(I,1))*(1.1+3*xa(I,2));
// On applique la periodicite:
      tab(nb_elem_tot+nb_som_tot+I)=tab(nb_elem_tot+nb_som_tot+renum_arete_perio(I));
// On verifie ok_arete au passage
      assert(ok_arete(I)==ok_arete(renum_arete_perio(I)));
    }
  tab.echange_espace_virtuel();
}
static int next (int S, const ArrOfInt & contenu) [static]
Definition at line 204 of file Zone_VEF_PreP1b.cpp.
References ArrOfInt::size_array().
Referenced by Memoire::add(), IntListElem::add(), IntList::add(), DoubleListElem::add(), DoubleList::add(), Memoire::compacte(), compute_graph_connex_components(), Zone_VEF_PreP1b::construire_ok_arete(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), DoubleList::DoubleList(), DoubleListElem::DoubleListElem(), Statistiques::dump(), liste::inserer(), IntList::IntList(), IntListElem::IntListElem(), Memoire::Memoire(), liste::suppr(), IntList::suppr(), DoubleList::suppr(), and Matrice_Morse::transpose().
{
  int nb_som=contenu.size_array();
  int i=S+1;
  while(i<nb_som)
    if(contenu(i)==1)
      return i;
    else i++;
  i=0;
  while(i<S)
    if(contenu(i)==1)
      return i;
    else i++;
  return -1;
}
Variable Documentation
const Type_info* Zone_VEF_PreP1bbases[1] = { &(Zone_VEF ::info_obj)}
Definition at line 42 of file Zone_VEF_PreP1b.cpp.