TRUST: src/Kernel/Geometrie/Zone.cpp File Reference
Zone.cpp File Reference
#include <MD_Vector_tools.h>
#include <communications.h>
#include <TRUSTList.h>
#include <Sous_Zone.h>
#include <Domaine.h>
#include <Octree.h>
#include <Zone.h>
Functions
template<class LIST_FRONTIERE >
void check_frontiere (const LIST_FRONTIERE &list, const char *msg)
static void corriger_type (Faces &faces, const Elem_geom_base &type_elem)
bool sameDoubleTab (const DoubleTab &a, const DoubleTab &b)
Variables
const Type_info * Zonebases [1] ={ &(Objet_U ::info_obj)}
static double cached_memory =0
Recherche des elements contenant les points dont les
coordonnees sont specifiees.
Function Documentation
check_frontiere()
template<class LIST_FRONTIERE > void check_frontiere (const LIST_FRONTIERE & list, const char * msg)
Definition at line 62 of file Zone.cpp.
{
  int n = list.size();
  if (! is_parallel_object(n))
    {
      Cerr << " Fatal error: processors don't have the same number of boundaries " << msg << finl;
      Process::barrier();
      Process::exit();
    }
  for (int i = 0; i < n; i++)
    {
      const Nom& nom = list[i].le_nom();
      Cerr << "  Boundary " << msg << " : " << nom << finl;
      if (! is_parallel_object(nom))
        {
          Cerr << " Fatal error: processors don't have the same number of boundaries " << msg << finl;
          Process::barrier();
          Process::exit();
        }
    }
}
References Process::barrier(), Cerr, Process::exit(), finl, is_parallel_object(), and Nom::le_nom().
Referenced by Zone::check_zone().
corriger_type()
static void corriger_type (Faces & faces, const Elem_geom_base & type_elem) static
Definition at line 86 of file Zone.cpp.
{
  int typ = faces.type_face();
  const int pe = (faces.type_face() == Faces::vide_0D) ? Process::nproc()-1 : Process::me();
  const int min_pe = ::mp_min(pe);
// Le processeur min_pe envoie son type a tous les autres
  int typ_commun = typ;
  envoyer_broadcast(typ_commun, min_pe);
  if (typ_commun != typ)
    {
      if (typ != Faces::vide_0D)
        {
          Cerr << "Error in Zone.cpp corriger_type: invalid boundary face type" << finl;
          Process::exit();
        }
      Type_Face tt = (Type_Face)typ_commun;
      faces.typer(tt);
// int n= faces.nb_som_faces();
      int n =type_elem.nb_som_face();
      faces.les_sommets().resize(0, n);
    }
}
References Cerr, envoyer_broadcast(), Process::exit(), finl, Faces::les_sommets(), Process::me(), mp_min(), Process::nproc(), TRUSTTab< _TYPE_ >::resize(), type_elem(), Faces::type_face(), Faces::typer(), and Faces::vide_0D.
Referenced by Zone::check_zone().
sameDoubleTab()
bool sameDoubleTab (const DoubleTab & a, const DoubleTab & b)
Definition at line 344 of file Zone.cpp.
{
  int size_a = a.size_array();
  int size_b = b.size_array();
  if (size_a != size_b) return false;
  for (int i=0; i<size_a; i++)
    if (a.addr()[i] != b.addr()[i]) return false;
  return true;
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Zone::chercher_elements().
Variable Documentation
cached_memory
double cached_memory =0 static
Recherche des elements contenant les points dont les
coordonnees sont specifiees.
Returns
ArrOfInt&
Signification: le tableau des numeros des elements contenant
les points specifies
Contraintes:
Definition at line 343 of file Zone.cpp.
Referenced by Zone::chercher_elements().
Zonebases
const Type_info* Zonebases[1] ={ &(Objet_U ::info_obj)}
Definition at line 24 of file Zone.cpp.