TRUST: src/PolyMAC/Zones/Zone_PolyMAC.h File Reference
src/PolyMAC/Zones/Zone_PolyMAC.h File Reference
#include <math.h>
#include <Zone_VF.h>
#include <Elem_PolyMAC.h>
#include <Domaine.h>
#include <Static_Int_Lists.h>
#include <IntLists.h>
#include <Conds_lim.h>
#include <Matrice_Morse_Sym.h>
#include <SolveurSys.h>
#include <DoubleTrav.h>
#include <IntTrav.h>
#include <Lapack.h>
#include <array>
#include <Periodique.h>
#include <Neumann_sortie_libre.h>
#include <Neumann_homogene.h>
#include <Dirichlet.h>
#include <Symetrie.h>
#include <Echange_global_impose.h>
#include <Champ_front_var_instationnaire.h>
#include <vector>
#include <map>
#include <string>
Classes
class Zone_PolyMAC
class Zone_PolyMAC
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Defines
#define CRIMP(a)
Functions
static DoubleTab prod (DoubleTab a, DoubleTab b)
static DoubleTab transp (DoubleTab a)
static double kersol (const DoubleTab &M, DoubleTab &b, double eps, DoubleTab *P, DoubleTab &x, DoubleTab &S)
Define Documentation
#define CRIMP (a)
Value:
a.nb_dim() > 1 ? a.resize(a.dimension(0) + 1, a.dimension(1)) : a.resize(a.dimension(0) + 1), \
        a.set_smart_resize(0), \
        a.nb_dim() > 1 ? a.resize(a.dimension(0) - 1, a.dimension(1)) : a.resize(a.dimension(0) - 1)
Definition at line 430 of file Zone_PolyMAC.h.
Function Documentation
static double kersol (const DoubleTab & M, DoubleTab & b, double eps, DoubleTab * P, DoubleTab & x, DoubleTab & S) [inline, static]
Definition at line 376 of file Zone_PolyMAC.h.
References ArrOfDouble::addr(), DoubleTab::dimension(), F77NAME, info, max(), min(), prod(), DoubleTab::resize(), and transp().
{
  int i, j, nk, m = M.dimension(0), n = M.dimension(1), k = min(m, n), l = max(m, n), w = 5 * l, info, iP, jP;
  double res2 = 0;
  char a = 'A';
// lapack en mode Fortran -> on decompose en fait Mt!!
  DoubleTab A = M, U(m, m), Vt(n, n), W(w), iS(n, m);
  S.resize(k);
  F77NAME(dgesvd)(&a, &a, &n, &m, A.addr(), &n, S.addr(), Vt.addr(), &n, U.addr(), &m, W.addr(), &w, &info);
  for (i = 0, nk = n; i < k && S(i) > eps * S(0); i++) nk--;
  if (P) P->resize(n, nk);
  for (i = 0, jP = -1; i < n; i++) if (i < k && S(i) > eps * S(0)) iS(i, i) = 1 / S(i); //terme diagonal de iS
    else if (P) for (iP = 0, jP++; iP < n; iP++) (*P)(iP, jP) = Vt(i, iP); //colonne de V -> colonne de P
  x = prod(transp(Vt), prod(iS, prod(transp(U), b)));
  DoubleTab res = prod(M, x);
  for (i = 0; i < m; i++) for (j = 0; j < b.dimension(1); j++) res2 += std::pow(res(i, j) - b(i, j), 2);
  return sqrt(res2);
}
static DoubleTab prod (DoubleTab a, DoubleTab b) [inline, static]
Definition at line 359 of file Zone_PolyMAC.h.
References DoubleTab::dimension().
Referenced by kersol().
{
  int i, j, k, m = a.dimension(0), n = a.dimension(1), p = b.dimension(1);
  assert(n == b.dimension(0));
  DoubleTab r(m, p);
  for (i = 0; i < m; i++) for (j = 0; j < n; j++) for (k = 0; k < p; k++) r(i, k) += a(i, j) * b(j, k);
  return r;
}
static DoubleTab transp (DoubleTab a) [inline, static]
Definition at line 367 of file Zone_PolyMAC.h.
References DoubleTab::dimension().
Referenced by kersol().
{
  int i, j, m = a.dimension(0), n = a.dimension(1);
  DoubleTab r(n, m);
  for (i = 0; i < m; i++) for (j = 0; j < n; j++) r(j, i) = a(i, j);
  return r;
}