TRUST: src/EF/Zones/Zone_Cl_EF.cpp File Reference
Zone_Cl_EF.cpp File Reference
#include <Zone_Cl_EF.h>
#include <Zone_EF.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Symetrie.h>
#include <Neumann.h>
#include <Neumann_homogene.h>
#include <Periodique.h>
#include <Champ_P1_EF.h>
#include <Domaine.h>
#include <Tri_EF.h>
#include <Tetra_EF.h>
#include <Quadri_EF.h>
#include <Equation_base.h>
#include <Champ_front_txyz.h>
#include <Champ_front_softanalytique.h>
#include <Static_Int_Lists.h>
#include <Probleme_base.h>
#include <Discretisation_base.h>
#include <Matrice_Morse.h>
#include <Dirichlet_paroi_fixe_iso_Genepi2.h>
Functions
int Deux_Puissance (int n)
int trois_puissance (int n)
void construit_connectivite_sommet (int type_cl, Static_Int_Lists &som_face_bord, const Conds_lim &les_conditions_limites_, const Zone_EF &zone_EF)
Variables
const Type_info * Zone_Cl_EFbases [1] ={ &(Zone_Cl_dis_base ::info_obj)}
Function Documentation
construit_connectivite_sommet()
void construit_connectivite_sommet (int type_cl, Static_Int_Lists & som_face_bord, const Conds_lim & les_conditions_limites_, const Zone_EF & zone_EF)
Definition at line 110 of file Zone_Cl_EF.cpp.
{
  if (type_cl!=1) Process::exit();
  int compt=0;
  int nb_faces_tot=zone_EF.nb_faces_tot();
  ArrOfInt face_bords(nb_faces_tot);
  for(int i=0; i<les_conditions_limites_.size(); i++)
    {
      const Cond_lim_base& la_cl=les_conditions_limites_[i].valeur();
      const Front_VF& le_bord=  zone_EF.front_VF(i);
      int num2 =  le_bord.nb_faces_tot();
      if ( (sub_type(Symetrie,la_cl)))
        {
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              face_bords[compt++]=face;
            }
        }
    }
  face_bords.resize_array(compt);
  ArrOfInt is_sommet_sur_bord(zone_EF.nb_som_tot());
  const IntTab& face_sommets=zone_EF.face_sommets();
  int nb_som_face=face_sommets.dimension(1);
  for (int fac=0; fac<compt; fac++)
    {
      int face=face_bords[fac];
      for (int som=0; som<nb_som_face; som++)
        {
          int sommet=face_sommets(face,som);
          is_sommet_sur_bord[sommet]++;
        }
    }
// On exploite is_sommet_sur_bord pour fixer la taille des List que va repertorier som_face_bord
// -som_face_bord contient nb_som_tot List
// -chaque List est dimensionnee par le nombre de faces de bord (portant une CL de Dirichlet)
// connectees au sommet considere
// -une List donnee pour un sommet repertorie le numero des faces qui lui sont connectees
  som_face_bord.set_list_sizes(is_sommet_sur_bord);
  is_sommet_sur_bord=0;
  for (int fac=0; fac<compt; fac++)
    {
      int face=face_bords[fac];
      for (int som=0; som<nb_som_face; som++)
        {
          int sommet=face_sommets(face,som);
          int n=(is_sommet_sur_bord[sommet])++;
          som_face_bord.set_value(sommet,n,face);
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Process::exit(), Zone_VF::face_sommets(), Zone_VF::front_VF(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), TRUSTArray< _TYPE_ >::resize_array(), Static_Int_Lists::set_list_sizes(), Static_Int_Lists::set_value(), vect_impl::size(), and sub_type.
Referenced by Zone_Cl_EF::remplir_type_elem_Cl().
Deux_Puissance()
int Deux_Puissance (int n)
Definition at line 41 of file Zone_Cl_VEF.cpp.
{
  switch(n)
    {
    case 0 :
      return 1;
    case 1 :
      return 2;
    case 2 :
      return 4;
    case 3 :
      return 8;
    default:
      return 8*Deux_Puissance((int)(n-3));
    }
}
References Deux_Puissance().
Referenced by Deux_Puissance(), and Zone_Cl_VEF::remplir_type_elem_Cl().
trois_puissance()
int trois_puissance (int n)
Definition at line 305 of file Zone_Cl_VEF.cpp.
{
  switch(n)
    {
    case 0:
      return 1;
    case 1:
      return 3;
    case 2:
      return 9;
    case 3:
      return 27;
    default :
      return 27*trois_puissance(n-3);
    }
}
References trois_puissance().
Referenced by Zone_Cl_VEF::remplir_type_elem_Cl(), and trois_puissance().
Variable Documentation
Zone_Cl_EFbases
const Type_info* Zone_Cl_EFbases[1] ={ &(Zone_Cl_dis_base ::info_obj)}
Definition at line 39 of file Zone_Cl_EF.cpp.