TRUST: src/Kernel/VF/Zones/Zone_Poly_base.h File Reference
Zone_Poly_base.h File Reference
#include <Champ_front_var_instationnaire.h>
#include <Static_Int_Lists.h>
#include <Elem_poly_base.h>
#include <Elem_poly.h>
#include <TRUSTLists.h>
#include <Periodique.h>
#include <TRUSTTrav.h>
#include <Conds_lim.h>
#include <Zone_VF.h>
#include <Domaine.h>
#include <Lapack.h>
#include <math.h>
#include <vector>
#include <string>
#include <array>
#include <map>
Classes
class Zone_Poly_base
class Zone_Poly_base
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Macros
#define CRIMP(a)
Functions
static DoubleTab prod (DoubleTab a, DoubleTab b)
static DoubleTab transp (DoubleTab a)
static double kersol (const DoubleTab &M, DoubleTab &b, double eps, DoubleTab *P, DoubleTab &x, DoubleTab &S)
Macro Definition Documentation
CRIMP
#define CRIMP (a)
Value:
        a.nb_dim() > 2 ? a.resize(a.dimension(0) + 1, a.dimension(1), a.dimension(2)) : a.nb_dim() > 1 ? a.resize(a.dimension(0) + 1, a.dimension(1)) : a.resize(a.dimension(0) + 1), \
        a.set_smart_resize(0), \
        a.nb_dim() > 2 ? a.resize(a.dimension(0) - 1, a.dimension(1), a.dimension(2)) : a.nb_dim() > 1 ? a.resize(a.dimension(0) - 1, a.dimension(1)) : a.resize(a.dimension(0) - 1)
Definition at line 386 of file Zone_Poly_base.h.
Function Documentation
kersol()
static double kersol (const DoubleTab & M, DoubleTab & b, double eps, DoubleTab * P, DoubleTab & x, DoubleTab & S) inline static
Definition at line 314 of file Zone_Poly_base.h.
{
  int i, nk, m = M.dimension(0), n = M.dimension(1), k = std::min(m, n), l = std::max(m, n), w = 5 * l, info, iP, jP;
  double res2 = 0;
  char a = 'A';
// lapack en mode Fortran -> on decompose en fait Mt!!
  DoubleTab A = M, U(m, m), Vt(n, n), W(w), iS(n, m);
  S.resize(k);
  F77NAME(dgesvd)(&a, &a, &n, &m, A.addr(), &n, S.addr(), Vt.addr(), &n, U.addr(), &m, W.addr(), &w, &info);
  for (i = 0, nk = n; i < k && S(i) > eps * S(0); i++) nk--;
  if (P) P->resize(n, nk);
  for (i = 0, jP = -1; i < n; i++)
    if (i < k && S(i) > eps * S(0)) iS(i, i) = 1 / S(i); //terme diagonal de iS
    else if (P)
      for (iP = 0, jP++; iP < n; iP++) (*P)(iP, jP) = Vt(i, iP); //colonne de V -> colonne de P
  x = prod(transp(Vt), prod(iS, prod(transp(U), b)));
  DoubleTab res = prod(M, x);
  for (i = 0; i < m; i++) res2 += std::pow(res(i, 0) - b(i, 0), 2);
  return sqrt(res2);
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), F77NAME, info, prod(), TRUSTTab< _TYPE_ >::resize(), and transp().
Referenced by Zone_PolyMAC::orthocentrer().
prod()
static DoubleTab prod (DoubleTab a, DoubleTab b) inline static
Definition at line 294 of file Zone_Poly_base.h.
{
  int i, j, k, m = a.dimension(0), n = a.dimension(1), p = b.dimension(1);
  assert(n == b.dimension(0));
  DoubleTab r(m, p);
  for (i = 0; i < m; i++)
    for (j = 0; j < n; j++)
      for (k = 0; k < p; k++) r(i, k) += a(i, j) * b(j, k);
  return r;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Faces::calculer_surfaces(), Quadrangle_VEF::contient(), Triangle::contient(), contient_triangle(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_partiellement(), integrate_lagrangian_basis(), kersol(), Zone_Cl_EF::modifie_gradient(), operation01(), operation11(), range(), Zone_Cl_EF::remplir_type_elem_Cl(), reordonne(), and Quadrangle_VEF::reordonner().
transp()
static DoubleTab transp (DoubleTab a) inline static
Definition at line 304 of file Zone_Poly_base.h.
{
  int i, j, m = a.dimension(0), n = a.dimension(1);
  DoubleTab r(n, m);
  for (i = 0; i < m; i++)
    for (j = 0; j < n; j++) r(j, i) = a(i, j);
  return r;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by kersol().