TRUST: src/CoviMAC/Zones/Zone_CoviMAC.cpp File Reference
src/CoviMAC/Zones/Zone_CoviMAC.cpp File Reference
#include <Zone_CoviMAC.h>
#include <tuple>
#include <unordered_map>
#include <Rectangle.h>
#include <Hexaedre.h>
#include <Triangle.h>
#include <Segment.h>
#include <Tetraedre.h>
#include <Quadrangle_VEF.h>
#include <Hexaedre_VEF.h>
#include <Zone_Cl_CoviMAC.h>
#include <Tri_CoviMAC.h>
#include <Segment_CoviMAC.h>
#include <Tetra_CoviMAC.h>
#include <Quadri_CoviMAC.h>
#include <Hexa_CoviMAC.h>
#include <Domaine.h>
#include <Scatter.h>
#include <EFichier.h>
#include <SFichier.h>
#include <IntList.h>
#include <DoubleList.h>
#include <Connectivite_som_elem.h>
#include <Array_tools.h>
#include <Matrix_tools.h>
#include <EChaine.h>
#include <Comm_Group_MPI.h>
#include <PE_Groups.h>
#include <communications.h>
#include <Statistiques.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_tools.h>
#include <ConstDoubleTab_parts.h>
#include <Lapack.h>
#include <Option_CoviMAC.h>
#include <Echange_contact_CoviMAC.h>
#include <Dirichlet_homogene.h>
#include <LireMED.h>
#include <EcrMED.h>
#include <Champ_implementation_P1.h>
#include <Linear_algebra_tools_impl.h>
#include <IntLists.h>
#include <DoubleLists.h>
#include <unistd.h>
#include <vector>
#include <set>
#include <map>
#include <cmath>
#include <cfloat>
#include <numeric>
#include <cfenv>
#include <osqp/osqp.h>
Functions
void disp_dt (const DoubleTab &A)
void disp_da (const ArrOfDouble &A)
void disp_it (const IntTab &A)
void disp_ia (const ArrOfInt &A)
void disp_m (const Matrice_Morse &M)
void disp_mt (const tabs_t &mvect)
void disp_mm (const std::map< std::string, Matrice_Morse > &mmat)
void disp_mmp (const matrices_t &mmat)
Variables
const Type_info * Zone_CoviMACbases [1] = { &(Zone_VF ::info_obj)}
Function Documentation
void disp_da (const ArrOfDouble & A)
Definition at line 591 of file Zone_CoviMAC.cpp.
References ArrOfDouble::addr(), and ArrOfDouble::size_array().
{
  int i;
  for (i = 0, fprintf(stderr, "{"); i < A.size_array(); i++)
    fprintf(stderr, "%.10E%s ", A.addr()[i], i + 1 < A.size_array() ? "," : "");
  fprintf(stderr, "}\n");
}
void disp_dt (const DoubleTab & A)
Definition at line 571 of file Zone_CoviMAC.cpp.
References ArrOfDouble::addr(), DoubleTab::dimension(), DoubleTab::dimension_tot(), and DoubleTab::nb_dim().
Referenced by disp_m(), and disp_mt().
{
  int i, j, k, l;
  if (A.nb_dim() == 4) for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "}},{" : "{"); k < A.dimension(2); k++)
          for (l = 0, fprintf(stderr, k ? "},{" : "{"); l < A.dimension(3); l++)
            fprintf(stderr, "%.10E%s ", A.addr()[A.dimension(3) * (A.dimension(2) * (i * A.dimension(1) + j) + k) + l], l + 1 < A.dimension(3) ? "," : "");
  else if (A.nb_dim() == 3) for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "}},{" : "{{"); j < A.dimension(1); j++)
        for (k = 0, fprintf(stderr, j ? "},{" : "{"); k < A.dimension(2); k++)
          fprintf(stderr, "%.10E%s ", A.addr()[A.dimension(2) * (i * A.dimension(1) + j) + k], k + 1 < A.dimension(2) ? "," : "");
  else if (A.nb_dim() == 2) for (i = 0; i < A.dimension_tot(0); i++)
      for (j = 0, fprintf(stderr, i ? "},{" : "{{"); j < A.dimension(1); j++)
        fprintf(stderr, "%.10E%s ", A.addr()[i * A.dimension(1) + j], j + 1 < A.dimension(1) ? "," : "");
  else for (i = 0, fprintf(stderr, "{"); i < A.dimension_tot(0); i++)
      fprintf(stderr, "%.10E%s ", A.addr()[i], i + 1 < A.dimension_tot(0) ? "," : "");
  fprintf(stderr, A.nb_dim() == 4 ? "}}}}\n" : A.nb_dim() == 3 ? "}}}\n" : A.nb_dim() == 2 ? "}}\n" : "}\n");
}
void disp_ia (const ArrOfInt & A)
Definition at line 610 of file Zone_CoviMAC.cpp.
References ArrOfInt::addr(), and ArrOfInt::size_array().
{
  int i;
  for (i = 0, fprintf(stderr, "{"); i < A.size_array(); i++)
    fprintf(stderr, "%d%s ", A.addr()[i], i + 1 < A.size_array() ? "," : "");
  fprintf(stderr, "}\n");
}
void disp_it (const IntTab & A)
Definition at line 599 of file Zone_CoviMAC.cpp.
References ArrOfInt::addr(), IntTab::dimension(), and IntTab::nb_dim().
{
  int i, j;
  if (A.nb_dim() == 2) for (i = 0; i < A.dimension(0); i++)
      for (j = 0, fprintf(stderr, i ? "},{" : "{{"); j < A.dimension(1); j++)
        fprintf(stderr, "%d%s ", A.addr()[i * A.dimension(1) + j], j + 1 < A.dimension(1) ? "," : "");
  else for (i = 0, fprintf(stderr, "{"); i < A.dimension(0); i++)
      fprintf(stderr, "%d%s ", A.addr()[i], i + 1 < A.dimension(0) ? "," : "");
  fprintf(stderr, A.nb_dim() == 2 ? "}}\n" : "}\n");
}
void disp_m (const Matrice_Morse & M)
Definition at line 618 of file Zone_CoviMAC.cpp.
References ArrOfDouble::addr(), ArrOfInt::addr(), disp_dt(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_colonnes(), and Matrice_Morse::nb_lignes().
Referenced by disp_mm(), and disp_mmp().
{
  DoubleTab A(M.nb_lignes(), M.nb_colonnes());
  for (int i = 0; i < A.dimension(0); i++)
    for (int k = M.get_tab1().addr()[i] - 1; k < M.get_tab1().addr()[i + 1] - 1; k++)
      A(i, M.get_tab2().addr()[k] - 1) = M.get_coeff().addr()[k];
  disp_dt(A);
}
void disp_mm (const std::map< std::string, Matrice_Morse > & mmat)
Definition at line 633 of file Zone_CoviMAC.cpp.
References disp_m().
{
  for (auto &&n_v : mmat)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_m(n_v.second), fprintf(stderr, "\n");
}
void disp_mmp (const matrices_t & mmat)
Definition at line 639 of file Zone_CoviMAC.cpp.
References disp_m().
{
  for (auto &&n_v : mmat)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_m(*n_v.second), fprintf(stderr, "\n");
}
void disp_mt (const tabs_t & mvect)
Definition at line 627 of file Zone_CoviMAC.cpp.
References disp_dt().
{
  for (auto &&n_v : mvect)
    fprintf(stderr, "%s:\n", n_v.first.c_str()), disp_dt(n_v.second), fprintf(stderr, "\n");
}
Variable Documentation
const Type_info* Zone_CoviMACbases[1] = { &(Zone_VF ::info_obj)}
Definition at line 83 of file Zone_CoviMAC.cpp.