TRUST: src/P1NCP1B/Zones/Zone_VEF_PreP1b.h File Reference
Zone_VEF_PreP1b.h File Reference
#include <Zone_VEF.h>
#include <Zone.h>
Classes
class Zone_VEF_PreP1b
Functions
void exemple_champ_non_homogene (const Zone_VEF_PreP1b &, DoubleTab &)
Function Documentation
exemple_champ_non_homogene()
void exemple_champ_non_homogene (const Zone_VEF_PreP1b & zone_VEF, DoubleTab & tab)
Definition at line 279 of file Zone_VEF_PreP1b.cpp.
{
  const DoubleTab& xp = zone_VEF.xp();
  const Zone& zone=zone_VEF.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const DoubleTab& xa=zone_VEF.xa();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
// Verification du tableau xa des coordonnees arete
  if (xa.size_array()) Debog::verifier("xa=",xa);
  int nb_elem=zone.nb_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_som=zone.nb_som();
  int nb_som_tot=zone.nb_som_tot();
  int nb_aretes=zone.nb_aretes();
  for (int I=0 ; I<nb_elem; I++)
    {
      tab(I)=(1.1+xp(I,0))*(1.1+2*xp(I,1));
      if (Objet_U::dimension==3) tab(I)*=(1.1+3*xp(I,2));
    }
  for (int I=0; I<nb_som; I++)
    {
      tab(nb_elem_tot+I)=(1.1+coord(I,0))*(1.1+2*coord(I,1));
      if (Objet_U::dimension==3) tab(nb_elem_tot+I)*=(1.1+3*coord(I,2));
// On applique la periodicite:
      tab(nb_elem_tot+I)=tab(nb_elem_tot+zone.domaine().get_renum_som_perio(I));
    }
#ifndef NDEBUG
  const IntVect& ok_arete = zone_VEF.get_ok_arete();
#endif
  for (int I=0; I<nb_aretes; I++)
    {
      tab(nb_elem_tot+nb_som_tot+I)=(1.1+xa(I,0))*(1.1+2*xa(I,1))*(1.1+3*xa(I,2));
// On applique la periodicite:
      tab(nb_elem_tot+nb_som_tot+I)=tab[nb_elem_tot+nb_som_tot+renum_arete_perio[I]];
// On verifie ok_arete au passage
      assert(ok_arete(I)==ok_arete(renum_arete_perio[I]));
    }
  tab.echange_espace_virtuel();
}
References Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Zone::nb_aretes(), Zone::nb_elem(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_tot(), TRUSTArray< _TYPE_ >::size_array(), Debog::verifier(), Zone_VF::xa(), Zone_VF::xp(), and Zone_dis_base::zone().
Referenced by verifier(), and verifier_complet().