TRUST: src/VDF/Zones/Zone_VDF.cpp File Reference
Zone_VDF.cpp File Reference
#include <Zone_VDF.h>
#include <Zone_Cl_VDF.h>
#include <Rectangle.h>
#include <Hexaedre.h>
#include <Faces_VDF.h>
#include <Aretes.h>
#include <Periodique.h>
#include <Dirichlet_entree_fluide.h>
#include <Neumann_sortie_libre.h>
#include <EcrFicCollecte.h>
#include <math.h>
#include <TRUSTTrav.h>
Functions
static void reordonner_vdf (const int nb_faces_front, Faces_VDF &faces, IntTab &elem_faces, IntVect &orientation, Joints &joints)
Reordonne les faces internes par orientation, on doit mettre a jour
tous les tableaux qui dependent des indices de faces internes, soit:
- faces_sommets
- faces_voisins
- elem_faces
- orientation
- Zone.faces_joint().items_communs(FACE)
static int face_vois (const Zone_VDF &zvdf, const Zone &zone, int face, int i)
Variables
const Type_info * Zone_VDFbases [1] ={ &(Zone_VF ::info_obj)}
Function Documentation
face_vois()
static int face_vois (const Zone_VDF & zvdf, const Zone & zone, int face, int i) inline static
Definition at line 345 of file Zone_VDF.cpp.
{
  int elem=zvdf.face_voisins(face,i);
  if(elem==-1)
    {
      face=zone.face_interne_conjuguee(face);
      if(face!=-1)
        {
          elem=zvdf.face_voisins(face,i);
          assert(elem!=-1);
        }
    }
  return elem;
}
References Zone::face_interne_conjuguee(), and Zone_VF::face_voisins().
Referenced by T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VEF::discretiser(), Zone_VDF::genere_aretes(), Eval_Darcy_VDF_Face::mettre_a_jour(), and Eval_Darcy_VEF_Face::mettre_a_jour().
reordonner_vdf()
static void reordonner_vdf (const int nb_faces_front, Faces_VDF & faces, IntTab & elem_faces, IntVect & orientation, Joints & joints) static
Reordonne les faces internes par orientation, on doit mettre a jour
tous les tableaux qui dependent des indices de faces internes, soit:
- faces_sommets
- faces_voisins
- elem_faces
- orientation
- Zone.faces_joint().items_communs(FACE)
< items_communs rempli ?
< ancien indice local
Definition at line 95 of file Zone_VDF.cpp.
{
// Construction d'un int selon lequel on va trier les faces:
// orientation * nb_faces + indice_face
// Quand on trie par ordre croissant de cet int, on trie selon l'orientation
// en preservant l'ordre initial des faces de meme orientation
  const int nb_faces = faces.nb_faces();
  int i, j;
  ArrOfInt sort_key(nb_faces);
// On ne trie pas les faces de bord, qui restent au debut:
  for (i = 0; i < nb_faces_front; i++)
    sort_key[i] = i;
  for (; i < nb_faces; i++)
    {
      const int ori = orientation(i);
      sort_key[i] = ori * nb_faces + i;
    }
  sort_key.ordonne_array();
// Il suffit de revenir a l'index initial pour avoir les indices des
// faces triees par orientation : sort_key[nouveau numero] = ancien numero
  for (i = nb_faces_front; i < nb_faces; i++)
    {
      const int key = sort_key[i];
      orientation[i] = key / nb_faces;
      sort_key[i]    = key % nb_faces;
    }
// On reordonne les faces:
  {
    IntTab& faces_sommets = faces.les_sommets();
    IntTab old_tab(faces_sommets);
    const int nb_som_faces = faces_sommets.dimension(1);
    for (i = 0; i < nb_faces; i++)
      {
        const int old_i = sort_key[i];
        for (j = 0; j < nb_som_faces; j++)
          faces_sommets(i, j) = old_tab(old_i, j);
      }
  }
  {
    IntTab& faces_voisins = faces.voisins();
    IntTab old_tab(faces_voisins);
    for (i = 0; i < nb_faces; i++)
      {
        const int old_i = sort_key[i];
        faces_voisins(i, 0) = old_tab(old_i, 0);
        faces_voisins(i, 1) = old_tab(old_i, 1);
      }
  }
// Calcul de la table inversee: reverse_index[ancien_numero] = nouveau numero
  ArrOfInt reverse_index(nb_faces);
  {
    for (i = 0; i < nb_faces; i++)
      {
        const int jj = sort_key[i];
        reverse_index[jj] = i;
      }
  }
// Renumerotation de elem_faces:
  {
// Nombre d'indices de faces dans le tableau
    const int nb_items = elem_faces.size();
    ArrOfInt& array = elem_faces;
    for (i = 0; i < nb_items; i++)
      {
        const int old = array[i];
        array[i] = reverse_index[old];
      }
  }
// Mise a jour des indices des faces de joint:
  {
    const int nb_joints = joints.size();
    for (int i_joint = 0; i_joint < nb_joints; i_joint++)
      {
        Joint&     joint         = joints[i_joint];
        ArrOfInt& indices_faces = joint.set_joint_item(Joint::FACE).set_items_communs();
        const int nb_faces_bis    = indices_faces.size_array();
        assert(nb_faces_bis == joint.nb_faces()); //!< items_communs rempli ?
        for (i = 0; i < nb_faces_bis; i++)
          {
            const int old = indices_faces[i]; //!< ancien indice local
            indices_faces[i] = reverse_index[old];
          }
// Les faces de joint ne sont plus consecutives dans le
// tableau: num_premiere_face n'a plus ne sens
        joint.fixer_num_premiere_face(-1);
      }
  }
}
References TRUSTTab< _TYPE_ >::dimension(), Joint::FACE, Frontiere::fixer_num_premiere_face(), Faces::les_sommets(), Faces::nb_faces(), Frontiere::nb_faces(), TRUSTArray< _TYPE_ >::ordonne_array(), Joint_Items::set_items_communs(), Joint::set_joint_item(), TRUSTVect< _TYPE_ >::size(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), and Faces::voisins().
Referenced by Zone_VDF::reordonner().
Variable Documentation
Zone_VDFbases
const Type_info* Zone_VDFbases[1] ={ &(Zone_VF ::info_obj)}
Definition at line 29 of file Zone_VDF.cpp.